import { useCallback,useEffect,useMemo,useState } from 'react'
import { GAME_NAMES,GAME_REGISTRY } from '../gameRegistry'
import { getAcquisitionDashboard } from './api'
import { filterDateLabel,formatMetric,parseDashboardFilters,serializeDashboardFilters,type AcquisitionResponse,type DashboardFilters } from './model'
import { DataTable,KpiCard,LoadingState,PageHeader,StatePanel } from './Primitives'
import { FilterBar,FilterDrawer } from './FilterDrawer'

const SOURCES=['','ChatGPT','Google','Bing','Other AI','Instagram','TikTok','Facebook','X / Twitter','WhatsApp','Other social','Shared link','Other referral','Direct','Unknown']
function defaults():DashboardFilters{const to=new Date();const from=new Date(to);from.setUTCDate(from.getUTCDate()-29);return{environment:'production',from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),gameId:'',deviceClass:'all',comparison:'previous_period'}}
function percent(n:number,d:number){return d?100*n/d:0}

export default function AcquisitionPage(){
  const params=new URLSearchParams(window.location.search)
  const[filters,setFilters]=useState(()=>parseDashboardFilters(window.location.search,defaults()))
  const[source,setSource]=useState(params.get('source')??'');const[landing,setLanding]=useState(params.get('landing')??'');const[country,setCountry]=useState(params.get('country')??'')
  const[draft,setDraft]=useState({filters,source,landing,country});const[open,setOpen]=useState(false)
  const[data,setData]=useState<AcquisitionResponse|null>(null);const[state,setState]=useState<'loading'|'ready'|'error'>('loading')
  const load=useCallback(async()=>{setState('loading');try{setData(await getAcquisitionDashboard(filters,source,landing,country));setState('ready')}catch{setState('error')}},[filters,source,landing,country])
  useEffect(()=>{const query=new URLSearchParams(serializeDashboardFilters(filters));if(source)query.set('source',source);if(landing)query.set('landing',landing);if(country)query.set('country',country);window.history.replaceState({},'',`${window.location.pathname}?${query}`);void load()},[filters,source,landing,country,load])
  const aiStartRate=percent(data?.sources.filter(row=>row.source==='ChatGPT'||row.source==='Other AI').reduce((sum,row)=>sum+row.game_starts,0)??0,data?.sources.filter(row=>row.source==='ChatGPT'||row.source==='Other AI').reduce((sum,row)=>sum+row.sessions,0)??0)
  const topSource=useMemo(()=>[...(data?.sources??[])].sort((a,b)=>b.visitors-a.visitors)[0],[data])
  const filterCount=Number(filters.environment!=='production')+Number(Boolean(filters.gameId))+Number(filters.deviceClass!=='all')+Number(Boolean(source))+Number(Boolean(landing))+Number(Boolean(country))
  return <>
    <PageHeader eyebrow="GROWTH & DISCOVERY" title="Acquisition" description="See how AI, search, social, shared links, and direct traffic progress from landing page to completed game."/>
    <FilterBar summary={`${filters.environment} · ${filterDateLabel(filters.from,filters.to)} · ${source||'All sources'} · ${filters.gameId?GAME_NAMES[filters.gameId as keyof typeof GAME_NAMES]??filters.gameId:'All games'}`} count={filterCount} onOpen={()=>{setDraft({filters,source,landing,country});setOpen(true)}}/>
    <FilterDrawer open={open} title="Acquisition filters" description="Attribution is first-touch within each anonymous analytics session." onClose={()=>setOpen(false)} onApply={()=>{setFilters(draft.filters);setSource(draft.source);setLanding(draft.landing);setCountry(draft.country.toUpperCase());setOpen(false)}} onReset={()=>setDraft({filters:defaults(),source:'',landing:'',country:''})}>
      <div className="cc-drawer-filter-grid"><label>Environment<select value={draft.filters.environment} onChange={event=>setDraft({...draft,filters:{...draft.filters,environment:event.target.value as DashboardFilters['environment']}})}><option value="production">Production</option><option value="preview">Preview</option><option value="development">Development</option></select></label><label>From<input type="date" value={draft.filters.from} max={draft.filters.to} onChange={event=>setDraft({...draft,filters:{...draft.filters,from:event.target.value}})}/></label><label>To<input type="date" value={draft.filters.to} min={draft.filters.from} onChange={event=>setDraft({...draft,filters:{...draft.filters,to:event.target.value}})}/></label><label>Source<select value={draft.source} onChange={event=>setDraft({...draft,source:event.target.value})}>{SOURCES.map(item=><option key={item||'all'} value={item}>{item||'All sources'}</option>)}</select></label><label>Landing page<input value={draft.landing} placeholder="/ or /games" onChange={event=>setDraft({...draft,landing:event.target.value})}/></label><label>Game<select value={draft.filters.gameId} onChange={event=>setDraft({...draft,filters:{...draft.filters,gameId:event.target.value}})}><option value="">All games</option>{GAME_REGISTRY.map(game=><option key={game.id} value={game.id}>{game.name}</option>)}</select></label><label>Device<select value={draft.filters.deviceClass??'all'} onChange={event=>setDraft({...draft,filters:{...draft.filters,deviceClass:event.target.value as DashboardFilters['deviceClass']}})}><option value="all">All devices</option><option value="mobile">Mobile</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option><option value="unknown">Unknown</option></select></label><label>Country code<input value={draft.country} maxLength={2} placeholder="NG" onChange={event=>setDraft({...draft,country:event.target.value.replace(/[^a-z]/gi,'')})}/></label></div>
    </FilterDrawer>
    {state==='loading'?<LoadingState/>:state==='error'?<StatePanel title="Acquisition report unavailable" action={<button className="cc-button" onClick={()=>void load()}>Try again</button>}><p>The staff-only aggregate query failed. Your filters are preserved.</p></StatePanel>:data?<>
      <p className="cc-freshness">{data.refreshed_at?`Data refreshed ${new Date(data.refreshed_at).toLocaleString()}`:'Raw acquisition data is current; aggregate freshness is unavailable.'}</p>
      {data.partial_warnings.map(warning=><div className="cc-warning" role="note" key={warning}>{warning}</div>)}
      <div className="cc-kpi-grid"><KpiCard label="Visitors" value={formatMetric(data.summary.visitors)} detail={`${data.summary.sessions.toLocaleString()} attributed sessions`}/><KpiCard label="AI-referred visitors" value={formatMetric(data.summary.ai_visitors)} detail="ChatGPT and other recognized AI sources"/><KpiCard label="Top source" value={topSource?.source??'—'} detail={topSource?`${topSource.visitors.toLocaleString()} visitors`:'No attributed traffic yet'}/><KpiCard label="AI to start" value={formatMetric(aiStartRate,'percent')} detail="AI-attributed sessions reaching a game start"/><KpiCard label="Game selections" value={formatMetric(data.summary.game_selections)} detail={`${formatMetric(percent(data.summary.game_selections,data.summary.sessions),'percent')} of sessions`}/><KpiCard label="Completions" value={formatMetric(data.summary.completions)} detail={`${formatMetric(percent(data.summary.completions,data.summary.game_starts),'percent')} of starts`}/></div>
      <AcquisitionTrend rows={data.daily}/>
      <SourceBars rows={data.sources}/>
      <section className="cc-panel"><div className="cc-panel-heading"><h2>Source performance</h2><p>Visitors and conversion through selection, start, first card, and completion.</p></div><DataTable label="Acquisition source performance"><thead><tr><th>Source</th><th>Visitors</th><th>New</th><th>Returning</th><th>Sessions</th><th>Selections</th><th>Starts</th><th>First cards</th><th>Completions</th><th>Start rate</th><th>Completion</th><th>Median to start</th><th>Top landing</th><th>Top game</th></tr></thead><tbody>{data.sources.map(row=><tr key={row.source}><td>{row.source}</td><td>{row.visitors}</td><td>{row.new_visitors}</td><td>{row.returning_visitors}</td><td>{row.sessions}</td><td>{row.game_selections}</td><td>{row.game_starts}</td><td>{row.first_cards}</td><td>{row.completions}</td><td>{formatMetric(row.start_rate,'percent')}</td><td>{formatMetric(row.completion_rate,'percent')}</td><td>{formatMetric(row.median_seconds_to_start,'duration')}</td><td>{row.top_landing_page??'—'}</td><td>{row.top_game_id?GAME_NAMES[row.top_game_id as keyof typeof GAME_NAMES]??row.top_game_id:'—'}</td></tr>)}</tbody></DataTable></section>
      <div className="cc-detail-grid"><SimpleTable title="Landing-page performance" columns={['Landing page','Visitors','Sessions','Selections','Starts','Completions']} rows={data.landing_pages.map(row=>[row.landing_page,row.visitors,row.sessions,row.game_selections,row.game_starts,row.completions])}/><SimpleTable title="Source to game" columns={['Source / game','Selections','Starts','Completions']} rows={data.games.map(row=>[`${row.source} · ${GAME_NAMES[row.game_id as keyof typeof GAME_NAMES]??row.game_id}`,row.selections,row.game_starts,row.completions])}/></div>
      <p className="cc-privacy-note">Referrers can be removed by browsers, messaging apps, and privacy controls, so some AI or shared-link traffic will appear as Direct. Decked stores approved campaign fields and domains—not complete referring URLs or conversation text.</p>
    </>:null}
  </>
}

function SourceBars({rows}:{rows:AcquisitionResponse['sources']}){const visible=[...rows].sort((a,b)=>b.visitors-a.visitors).slice(0,8),max=Math.max(1,...visible.map(row=>row.visitors));return <section className="cc-panel cc-geo-bars"><div className="cc-panel-heading"><h2>Visitors by source</h2><p>Top acquisition sources for the selected period.</p></div><div>{visible.length?visible.map(row=><article key={row.source}><span>{row.source}</span><div><i style={{width:`${100*row.visitors/max}%`}}/></div><strong>{row.visitors}</strong></article>):<p className="cc-inline-empty">No acquisition data for this period.</p>}</div></section>}
function AcquisitionTrend({rows}:{rows:AcquisitionResponse['daily']}){const dates=[...new Set(rows.map(row=>row.metric_date))].sort(),sources=['ChatGPT','Google','Bing','Other AI','Other social','Direct'],width=900,height=260,pad=38,max=Math.max(1,...rows.map(row=>row.visitors)),x=(i:number)=>pad+(i/Math.max(1,dates.length-1))*(width-pad*2),y=(v:number)=>height-pad-(v/max)*(height-pad*2),value=(date:string,source:string)=>rows.find(row=>row.metric_date===date&&row.source===source)?.visitors??0;return <section className="cc-panel cc-timeseries cc-acquisition-trend"><div className="cc-panel-heading"><div><h2>Acquisition trend</h2><p>Daily visitors from AI, search, social, and direct sources.</p></div><div className="cc-legend">{sources.map(source=><span key={source}>{source}</span>)}</div></div>{dates.length?<svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Daily acquisition trend across ${dates.length} days`} >{[0,.5,1].map(t=><line key={t} x1={pad} x2={width-pad} y1={pad+t*(height-pad*2)} y2={pad+t*(height-pad*2)}/>)}{sources.map((source,index)=><polyline key={source} className={`series-${index}`} points={dates.map((date,i)=>`${x(i)},${y(value(date,source))}`).join(' ')} />)}{dates.map((date,i)=><text key={date} className="cc-x-label" x={x(i)} y={height-7} textAnchor={i===0?'start':i===dates.length-1?'end':'middle'}>{dates.length<=10||i===0||i===dates.length-1?new Date(`${date}T00:00:00Z`).toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'}):''}</text>)}</svg>:<div className="cc-chart-empty">No acquisition trend data for this period.</div>}</section>}
function SimpleTable({title,columns,rows}:{title:string;columns:string[];rows:Array<Array<string|number>>}){return <section className="cc-panel cc-detail-panel"><div className="cc-panel-heading"><h2>{title}</h2></div>{rows.length?<DataTable label={title}><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></DataTable>:<p className="cc-inline-empty">No observed data.</p>}</section>}
