import { useCallback,useEffect,useRef,useState } from 'react'
import { GAME_REGISTRY } from '../gameRegistry'
import { getFunnelsDashboard } from './api'
import { applyFunnelDimensionFilters,completeFunnels, funnelsViewState, parseFunnelDimensionFilters,type FunnelReport,type FunnelsResponse } from './funnelsModel'
import { filterDateLabel,formatMetric,parseDashboardFilters,serializeDashboardFilters,type DashboardFilters } from './model'
import { DataTable,LoadingState,PageHeader,StatePanel } from './Primitives'
import { ExportButton } from './ExportButton'
import { FilterBar,FilterDrawer } from './FilterDrawer'

function defaults():DashboardFilters{const to=new Date();const from=new Date(to);from.setUTCDate(from.getUTCDate()-29);return{environment:'production',from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),gameId:'',playMode:'',deviceClass:'all',comparison:'previous_period'}}

export default function FunnelsPage(){
  const initial=parseFunnelDimensionFilters(window.location.search)
  const [filters,setFilters]=useState(()=>parseDashboardFilters(window.location.search,defaults()));const [filtersOpen,setFiltersOpen]=useState(false);const [draft,setDraft]=useState(filters)
  const [source,setSource]=useState(initial.source);const [appVersion,setAppVersion]=useState(initial.appVersion)
  const [data,setData]=useState<FunnelsResponse|null>(null);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');const requestId=useRef(0)
  const load=useCallback(async()=>{const id=++requestId.current;setState('loading');try{const result=await getFunnelsDashboard(filters,source,appVersion);if(id===requestId.current){setData(result);setState('ready')}}catch{if(id===requestId.current)setState('error')}},[filters,source,appVersion])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{const query=applyFunnelDimensionFilters(new URLSearchParams(serializeDashboardFilters(filters)),{source,appVersion});window.history.replaceState({},'',`${window.location.pathname}?${query}`)},[filters,source,appVersion])
  const viewState=funnelsViewState(state,data)
  const [draftSource,setDraftSource]=useState(source);const [draftVersion,setDraftVersion]=useState(appVersion)
  return <><PageHeader eyebrow="CONVERSION" title="Funnels" description="Ordered journeys from discovery or multiplayer intent to a completed game."/><FilterBar summary={`${filters.environment} · ${filterDateLabel(filters.from,filters.to)} · ${filters.gameId||'All games'}`} count={Number(Boolean(filters.gameId))+Number(Boolean(filters.playMode))+Number(filters.deviceClass!=='all')+Number(Boolean(source))+Number(Boolean(appVersion))} onOpen={()=>{setDraft(filters);setDraftSource(source);setDraftVersion(appVersion);setFiltersOpen(true)}}><ExportButton report="funnels" filters={filters} source={source} appVersion={appVersion}/></FilterBar><FilterDrawer open={filtersOpen} title="Funnel filters" description="Adjust attribution and conversion dimensions." onClose={()=>setFiltersOpen(false)} onApply={()=>{setFilters(draft);setSource(draftSource);setAppVersion(draftVersion);setFiltersOpen(false)}} onReset={()=>{setDraft(defaults());setDraftSource('');setDraftVersion('')}}><FunnelFilters filters={draft} onChange={setDraft} source={draftSource} onSource={setDraftSource} appVersion={draftVersion} onVersion={setDraftVersion}/></FilterDrawer>{state==='ready'?<p className="cc-freshness" role="status">{data?.refreshed_at?`Data refreshed ${new Date(data.refreshed_at).toLocaleString()}`:'Data freshness unavailable for the complete selected range.'}</p>:null}{state==='ready'&&data?<Rules rules={data.rules}/>:null}{viewState==='loading'?<LoadingState/>:viewState==='error'?<StatePanel title="Funnel report unavailable" action={<button className="cc-button" onClick={()=>void load()}>Try again</button>}><p>The ordered funnel query failed. Your filters are preserved.</p></StatePanel>:data?<>{viewState==='empty'?<div className="cc-zero-notice" role="status"><strong>No funnel entrants</strong><span>Every canonical step remains visible with zero conversion.</span></div>:null}<div className="cc-funnel-list">{completeFunnels(data.funnels).map(funnel=><Funnel key={funnel.funnel_id} funnel={funnel}/>)}</div></>:null}</>
}

function FunnelFilters({filters,onChange,source,onSource,appVersion,onVersion}:{filters:DashboardFilters;onChange:(filters:DashboardFilters)=>void;source:string;onSource:(value:string)=>void;appVersion:string;onVersion:(value:string)=>void}){return <div className="cc-drawer-filter-grid" aria-label="Funnel filters">
  <label>Environment<select value={filters.environment} onChange={event=>onChange({...filters,environment:event.target.value as DashboardFilters['environment']})}><option value="production">Production</option><option value="preview">Preview</option><option value="development">Development</option></select></label>
  <label>From<input type="date" value={filters.from} max={filters.to} onChange={event=>onChange({...filters,from:event.target.value})}/></label><label>To<input type="date" value={filters.to} min={filters.from} onChange={event=>onChange({...filters,to:event.target.value})}/></label>
  <label>Game<select value={filters.gameId} onChange={event=>onChange({...filters,gameId:event.target.value})}><option value="">All games</option>{GAME_REGISTRY.map(game=><option value={game.id} key={game.id}>{game.name}</option>)}</select></label>
  <label>Play mode<select value={filters.playMode} onChange={event=>onChange({...filters,playMode:event.target.value as DashboardFilters['playMode']})}><option value="">All modes</option><option value="pass_and_play">Pass and play</option><option value="play_together">Play Together</option></select></label>
  <label>Device<select value={filters.deviceClass} onChange={event=>onChange({...filters,deviceClass:event.target.value as DashboardFilters['deviceClass']})}><option value="all">All devices</option><option value="mobile">Mobile</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option><option value="unknown">Unknown</option></select></label>
  <label>Acquisition source<input value={source} maxLength={100} placeholder="All sources" onChange={event=>onSource(event.target.value)}/></label><label>App version<input value={appVersion} maxLength={100} placeholder="All versions" onChange={event=>onVersion(event.target.value)}/></label>
  <label>Country <span className="cc-filter-note" id="funnel-country-note">not collected</span><select disabled value="" aria-describedby="funnel-country-note"><option>Unavailable</option></select></label>
  </div>}

function Rules({rules}:{rules:FunnelsResponse['rules']}){return <details className="cc-rules"><summary>How these funnels are calculated</summary><ul><li>Entry date and reporting timezone: {rules.timezone}.</li><li>Conversion window: {rules.conversion_window_hours} hours from entry.</li><li>Ordering: {rules.ordering}.</li><li>Repeated steps: {rules.repeat_handling}.</li><li>{rules.first_card_note}</li><li>“Join opened” is the Play Together screen view; “code submitted” is the room join attempt.</li></ul></details>}

function Funnel({funnel}:{funnel:FunnelReport}){return <section className="cc-panel cc-funnel"><div className="cc-panel-heading"><h2>{funnel.name}</h2><p>{funnel.steps[0]?.entrants??0} entrants</p></div><div className="cc-funnel-bars" aria-hidden="true">{funnel.steps.map(step=><div key={step.step_order} style={{width:`${step.entrants===0?0:Math.max(3,step.conversion_from_first)}%`}} title={`${step.step_name}: ${step.entrants}`}/>)}</div><DataTable label={`${funnel.name} conversion steps`}><thead><tr><th>Step</th><th>Entrants</th><th>From previous</th><th>From first</th><th>Median from previous</th></tr></thead><tbody>{funnel.steps.map(step=><tr key={step.step_order}><td>{step.step_order}. {step.step_name}</td><td>{step.entrants}</td><td>{formatMetric(step.conversion_from_previous,'percent')}</td><td>{formatMetric(step.conversion_from_first,'percent')}</td><td>{formatMetric(step.median_seconds_from_previous,'duration')}</td></tr>)}</tbody></DataTable></section>}
