import { useCallback,useEffect,useRef,useState,type ReactNode } from 'react'
import { GAME_REGISTRY } from '../gameRegistry'
import { getMultiplayerDashboard,getReliabilityDashboard } from './api'
import { filterDateLabel,formatMetric,parseDashboardFilters,serializeDashboardFilters,type DashboardFilters } from './model'
import { applyReliabilityDimensionFilters,operationsViewState,parseReliabilityDimensionFilters,safeGroupLabel,type Breakdown,type MultiplayerOperationsResponse,type ReliabilityOperationsResponse } from './operationsModel'
import { DataTable,LoadingState,PageHeader,StatePanel } from './Primitives'
import { ExportButton } from './ExportButton'
import { FilterBar,FilterDrawer } from './FilterDrawer'

function defaults():DashboardFilters{const to=new Date();const from=new Date(to);from.setUTCDate(from.getUTCDate()-29);return{environment:'production',from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),gameId:'',playMode:'',deviceClass:'all',comparison:'previous_period'}}

export function MultiplayerPage(){
  const [filters,setFilters]=useState(()=>parseDashboardFilters(window.location.search,defaults()));const [filtersOpen,setFiltersOpen]=useState(false);const [draft,setDraft]=useState(filters);const [data,setData]=useState<MultiplayerOperationsResponse|null>(null);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');const requestId=useRef(0)
  const load=useCallback(async()=>{const id=++requestId.current;setState('loading');try{const result=await getMultiplayerDashboard(filters);if(id===requestId.current){setData(result);setState('ready')}}catch{if(id===requestId.current)setState('error')}},[filters])
  useEffect(()=>{void load()},[load]);useEffect(()=>{window.history.replaceState({},'',`${window.location.pathname}?${serializeDashboardFilters(filters)}`)},[filters])
  const activity=data?data.metrics.rooms_created+data.metrics.realtime_failures+data.join_failures.reduce((sum,row)=>sum+row.occurrences,0):null;const viewState=operationsViewState(state,activity)
  return <><PageHeader eyebrow="ROOM HEALTH" title="Multiplayer" description="Authoritative room success, conversion, resilience, and repeat play."/><FilterBar summary={`${filters.environment} · ${filterDateLabel(filters.from,filters.to)} · ${filters.gameId||'All games'}`} count={Number(Boolean(filters.gameId))+Number(filters.environment!=='production')} onOpen={()=>{setDraft(filters);setFiltersOpen(true)}}><ExportButton report="multiplayer" filters={filters}/></FilterBar><FilterDrawer open={filtersOpen} title="Multiplayer filters" description="Adjust room-health reporting dimensions." onClose={()=>setFiltersOpen(false)} onApply={()=>{setFilters(draft);setFiltersOpen(false)}} onReset={()=>setDraft(defaults())}><BaseFilters filters={draft} onChange={setDraft}/></FilterDrawer>{state==='ready'&&data?<><Freshness value={data.refreshed_at}/><OperationsNotices warnings={data.partial_warnings} redactedTitle="Room timelines are redacted" redactedBody="The approved design returns aggregate room facts only—never room codes, participant identities, or raw room references."/></>:null}{viewState==='loading'?<LoadingState/>:viewState==='error'?<Failure title="Multiplayer report unavailable" retry={load}/>:data?<>{viewState==='empty'?<ZeroOperationsNotice label="No rooms or room failures match this period. Multiplayer metrics remain visible at zero."/>:null}<MultiplayerContent data={data}/></>:null}</>
}

function MultiplayerContent({data}:{data:MultiplayerOperationsResponse}){const m=data.metrics;return <><section className="cc-kpi-grid cc-operations-kpis">
  <Kpi label="Rooms created" value={formatMetric(m.rooms_created)}/><Kpi label="Successful joins" value={formatMetric(m.successful_joins)}/><Kpi label="Lobby → start" value={formatMetric(m.lobby_to_start_rate,'percent')}/><Kpi label="Median to first guest" value={formatMetric(m.median_seconds_to_first_guest,'duration')}/><Kpi label="Median to start" value={formatMetric(m.median_seconds_to_start,'duration')}/><Kpi label="Completion rate" value={formatMetric(m.completion_rate,'percent')}/><Kpi label="Host disconnects" value={formatMetric(m.host_disconnects)}/><Kpi label="Handoff success" value={formatMetric(m.host_handoff_success_rate,'percent')}/><Kpi label="Realtime failures" value={formatMetric(m.realtime_failures)}/><Kpi label="Rematch requests" value={formatMetric(m.rematch_requests)}/><Kpi label="Rematches started" value={formatMetric(m.rematches_started)}/>
  </section><div className="cc-detail-grid"><SimpleTable title="Join failure reasons" columns={['Reason','Occurrences']} rows={data.join_failures.map(row=>[safeGroupLabel(row.reason),row.occurrences])}/><SimpleTable title="Room-size distribution" columns={['Peak players','Rooms']} rows={data.room_sizes.map(row=>[row.room_size,row.rooms])}/><SimpleTable title="Daily room trend" columns={['UTC date','Created','Started','Completed games']} rows={data.trend.map(row=>[row.metric_date,row.rooms_created,row.rooms_started,row.games_completed])}/></div></>}

export function ReliabilityPage(){
  const initial=parseReliabilityDimensionFilters(window.location.search);const [filters,setFilters]=useState(()=>parseDashboardFilters(window.location.search,defaults()));const [filtersOpen,setFiltersOpen]=useState(false);const [draft,setDraft]=useState(filters);const [browser,setBrowser]=useState(initial.browser);const [version,setVersion]=useState(initial.appVersion);const [draftBrowser,setDraftBrowser]=useState(browser);const [draftVersion,setDraftVersion]=useState(version);const [data,setData]=useState<ReliabilityOperationsResponse|null>(null);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');const requestId=useRef(0)
  const load=useCallback(async()=>{const id=++requestId.current;setState('loading');try{const result=await getReliabilityDashboard(filters,browser,version);if(id===requestId.current){setData(result);setState('ready')}}catch{if(id===requestId.current)setState('error')}},[filters,browser,version]);useEffect(()=>{void load()},[load]);useEffect(()=>{const query=applyReliabilityDimensionFilters(new URLSearchParams(serializeDashboardFilters(filters)),{browser,appVersion:version});window.history.replaceState({},'',`${window.location.pathname}?${query}`)},[filters,browser,version])
  const activity=data?data.metrics.frontend_errors+data.metrics.rpc_failures+data.metrics.realtime_failures+(data.metrics.total_sessions??0):null;const viewState=operationsViewState(state,activity)
  return <><PageHeader eyebrow="RELEASE QUALITY" title="Reliability" description="Sanitized errors, affected sessions, and release-quality trends."/><FilterBar summary={`${filters.environment} · ${filterDateLabel(filters.from,filters.to)} · ${filters.gameId||'All games'}`} count={Number(Boolean(filters.gameId))+Number(filters.deviceClass!=='all')+Number(Boolean(browser))+Number(Boolean(version))} onOpen={()=>{setDraft(filters);setDraftBrowser(browser);setDraftVersion(version);setFiltersOpen(true)}}><ExportButton report="reliability" filters={filters} browser={browser} appVersion={version}/></FilterBar><FilterDrawer open={filtersOpen} title="Reliability filters" description="Adjust release and diagnostic dimensions." onClose={()=>setFiltersOpen(false)} onApply={()=>{setFilters(draft);setBrowser(draftBrowser);setVersion(draftVersion);setFiltersOpen(false)}} onReset={()=>{setDraft(defaults());setDraftBrowser('');setDraftVersion('')}}><ReliabilityFilters filters={draft} onChange={setDraft} browser={draftBrowser} onBrowser={setDraftBrowser} version={draftVersion} onVersion={setDraftVersion}/></FilterDrawer>{state==='ready'&&data?<><Freshness value={data.refreshed_at}/><OperationsNotices warnings={data.partial_warnings} redactedTitle="Sensitive diagnostics removed" redactedBody="Groups contain stable classes and fingerprints only. Stack frames, tokens, content, and raw session identities are unavailable."/></>:null}{viewState==='loading'?<LoadingState/>:viewState==='error'?<Failure title="Reliability report unavailable" retry={load}/>:data?<>{viewState==='empty'?<ZeroOperationsNotice label="No sessions or failures match this period. Reliability metrics remain visible at zero."/>:null}<ReliabilityContent data={data}/></>:null}</>
}

function ReliabilityContent({data}:{data:ReliabilityOperationsResponse}){const m=data.metrics;return <><section className="cc-kpi-grid cc-operations-kpis"><Kpi label="Frontend errors" value={formatMetric(m.frontend_errors)}/><Kpi label="Failed RPC calls" value={formatMetric(m.rpc_failures)}/><Kpi label="Realtime failures" value={formatMetric(m.realtime_failures)}/><Kpi label="Affected sessions" value={formatMetric(m.affected_sessions)}/><Kpi label="Error-free sessions" value={formatMetric(m.error_free_sessions)}/><Kpi label="Error-free rate" value={formatMetric(m.error_free_session_rate,'percent')}/></section><section className="cc-panel"><div className="cc-panel-heading"><h2>Grouped errors</h2><p>Identical sanitized signatures retain occurrence and affected-session counts.</p></div><DataTable label="Grouped reliability errors"><thead><tr><th>Type</th><th>Fingerprint</th><th>Class</th><th>Occurrences</th><th>Affected sessions</th><th>First seen</th><th>Last seen</th></tr></thead><tbody>{data.groups.map(group=><tr key={`${group.error_type}-${group.fingerprint}-${group.error_class}`}><td>{group.error_type}</td><td>{safeGroupLabel(group.fingerprint)}</td><td>{safeGroupLabel(group.error_class)}</td><td>{group.occurrences}</td><td>{group.affected_sessions}</td><td>{new Date(group.first_seen).toLocaleString()}</td><td>{new Date(group.last_seen).toLocaleString()}</td></tr>)}</tbody></DataTable></section><div className="cc-detail-grid cc-operations-details"><SimpleTable title="Daily failures" columns={['UTC date','Frontend','RPC','Realtime']} rows={data.trend.map(row=>[row.metric_date,row.frontend_errors,row.rpc_failures,row.realtime_failures])}/><BreakdownTable title="By game" rows={data.breakdowns.game}/><BreakdownTable title="By browser" rows={data.breakdowns.browser}/><BreakdownTable title="By device" rows={data.breakdowns.device}/><BreakdownTable title="By app version / release" rows={data.breakdowns.app_version}/></div></>}

function Freshness({value}:{value:string|null}){return <p className="cc-freshness" role="status">{value?`Data refreshed ${new Date(value).toLocaleString()}`:'Data freshness unavailable for the complete selected range.'}</p>}
function OperationsNotices({warnings,redactedTitle,redactedBody}:{warnings:string[];redactedTitle:string;redactedBody:string}){return <>{warnings.map(w=><div className="cc-warning" role="note" key={w}>{w}</div>)}<div className="cc-redacted" role="note"><strong>{redactedTitle}</strong><span>{redactedBody}</span></div></>}
function ZeroOperationsNotice({label}:{label:string}){return <div className="cc-zero-notice" role="status"><strong>No matching activity</strong><span>{label}</span></div>}

function BaseFilters({filters,onChange,children}:{filters:DashboardFilters;onChange:(filters:DashboardFilters)=>void;children?:ReactNode}){return <div className="cc-drawer-filter-grid" aria-label="Report filters"><label>Environment<select value={filters.environment} onChange={event=>onChange({...filters,environment:event.target.value as DashboardFilters['environment']})}><option value="production">Production</option><option value="preview">Preview</option><option value="development">Development</option></select></label><label>From<input required type="date" value={filters.from} max={filters.to} onChange={event=>onChange({...filters,from:event.target.value})}/></label><label>To<input required type="date" value={filters.to} min={filters.from} onChange={event=>onChange({...filters,to:event.target.value})}/></label><label>Game<select value={filters.gameId} onChange={event=>onChange({...filters,gameId:event.target.value})}><option value="">All games</option>{GAME_REGISTRY.map(game=><option key={game.id} value={game.id}>{game.name}</option>)}</select></label>{children}</div>}
function ReliabilityFilters({filters,onChange,browser,onBrowser,version,onVersion}:{filters:DashboardFilters;onChange:(filters:DashboardFilters)=>void;browser:string;onBrowser:(v:string)=>void;version:string;onVersion:(v:string)=>void}){return <BaseFilters filters={filters} onChange={onChange}><label>Device<select value={filters.deviceClass} onChange={event=>onChange({...filters,deviceClass:event.target.value as DashboardFilters['deviceClass']})}><option value="all">All devices</option><option value="mobile">Mobile</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option><option value="unknown">Unknown</option></select></label><label>Browser<input value={browser} maxLength={80} placeholder="All browsers" onChange={event=>onBrowser(event.target.value)}/></label><label>App version / release<input value={version} maxLength={100} placeholder="All releases" onChange={event=>onVersion(event.target.value)}/></label></BaseFilters>}
function Kpi({label,value}:{label:string;value:string}){return <article className="cc-kpi"><span>{label}</span><strong>{value}</strong></article>}
function Failure({title,retry}:{title:string;retry:()=>Promise<void>}){return <StatePanel title={title} action={<button className="cc-button" onClick={()=>void retry()}>Try again</button>}><p>The staff-only aggregate query failed. Filters remain in the URL.</p></StatePanel>}
function SimpleTable({title,columns,rows}:{title:string;columns:string[];rows:Array<Array<string|number>>}){return <section className="cc-panel cc-detail-panel"><div className="cc-panel-heading"><h2>{title}</h2></div>{rows.length?<DataTable label={title}><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></DataTable>:<p className="cc-inline-empty">No observed data.</p>}</section>}
function BreakdownTable({title,rows}:{title:string;rows:Breakdown[]}){return <SimpleTable title={title} columns={['Value','Occurrences']} rows={rows.map(row=>[safeGroupLabel(row.value),row.occurrences])}/>}
