import { useCallback, useEffect, useMemo, useState } from 'react'
import { getPlayPatternsDashboard } from './api'
import { filterDateLabel, formatMetric, parseDashboardFilters, serializeDashboardFilters, type DashboardFilters, type PlayPatternsResponse } from './model'
import { DataTable, KpiCard, LoadingState, PageHeader, StatePanel } from './Primitives'
import { FilterBar, FilterDrawer } from './FilterDrawer'

function defaults():DashboardFilters{const to=new Date();const from=new Date(to);from.setUTCDate(from.getUTCDate()-29);return{environment:'production',from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),gameId:'',playMode:'',deviceClass:'all',comparison:'previous_period'}}
function countryName(code:string){try{return new Intl.DisplayNames(undefined,{type:'region'}).of(code)??code}catch{return code}}
function hourLabel(hour:number|null){if(hour===null)return'—';return new Intl.DateTimeFormat(undefined,{hour:'numeric'}).format(new Date(Date.UTC(2020,0,1,hour)))}

export default function PlayPatternsPage(){
  const params=new URLSearchParams(window.location.search)
  const[filters,setFilters]=useState(()=>parseDashboardFilters(window.location.search,defaults()))
  const[country,setCountry]=useState(params.get('country')??'');const[timezone,setTimezone]=useState(params.get('timezone')??'')
  const[draft,setDraft]=useState(filters);const[draftCountry,setDraftCountry]=useState(country);const[draftTimezone,setDraftTimezone]=useState(timezone);const[open,setOpen]=useState(false)
  const[data,setData]=useState<PlayPatternsResponse|null>(null);const[state,setState]=useState<'loading'|'ready'|'error'>('loading')
  const load=useCallback(async()=>{setState('loading');try{setData(await getPlayPatternsDashboard(filters,country,timezone));setState('ready')}catch{setState('error')}},[filters,country,timezone])
  useEffect(()=>{const query=new URLSearchParams(serializeDashboardFilters(filters));if(country)query.set('country',country);if(timezone)query.set('timezone',timezone);window.history.replaceState({},'',`${window.location.pathname}?${query}`);void load()},[filters,country,timezone,load])
  const max=useMemo(()=>Math.max(1,...(data?.heatmap??[]).map(row=>row.game_starts)),[data])
  const byCell=useMemo(()=>new Map((data?.heatmap??[]).map(row=>[`${row.iso_weekday}-${row.hour}`,row])),[data])
  const activeFilters=Number(filters.environment!=='production')+Number(Boolean(filters.gameId))+Number(Boolean(filters.playMode))+Number(filters.deviceClass!=='all')+Number(Boolean(country))+Number(Boolean(timezone))
  return <>
    <PageHeader eyebrow="PLAYER BEHAVIOUR" title="Play Patterns" description="See when people start games in their own local time, with privacy-safe country and product breakdowns."/>
    <FilterBar summary={`${filters.environment} · ${filterDateLabel(filters.from,filters.to)}${country?` · ${countryName(country)}`:''}${timezone?` · ${timezone}`:''}`} count={activeFilters} onOpen={()=>{setDraft(filters);setDraftCountry(country);setDraftTimezone(timezone);setOpen(true)}}/>
    <FilterDrawer open={open} title="Play-pattern filters" description="Local time comes from the browser IANA timezone captured at app open." onClose={()=>setOpen(false)} onApply={()=>{setFilters(draft);setCountry(draftCountry.trim().toUpperCase());setTimezone(draftTimezone.trim());setOpen(false)}} onReset={()=>{setDraft(defaults());setDraftCountry('');setDraftTimezone('')}}>
      <div className="cc-drawer-filter-grid"><label>Environment<select value={draft.environment} onChange={e=>setDraft({...draft,environment:e.target.value as DashboardFilters['environment']})}><option value="production">Production</option><option value="preview">Preview</option><option value="development">Development</option></select></label><label>From<input type="date" value={draft.from} max={draft.to} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>To<input type="date" value={draft.to} min={draft.from} onChange={e=>setDraft({...draft,to:e.target.value})}/></label><label>Game ID<input value={draft.gameId} onChange={e=>setDraft({...draft,gameId:e.target.value})}/></label><label>Play mode<select value={draft.playMode} onChange={e=>setDraft({...draft,playMode:e.target.value as DashboardFilters['playMode']})}><option value="">All modes</option><option value="pass_and_play">Pass and play</option><option value="play_together">Play together</option></select></label><label>Device<select value={draft.deviceClass} onChange={e=>setDraft({...draft,deviceClass:e.target.value as DashboardFilters['deviceClass']})}><option value="all">All devices</option><option value="mobile">Mobile</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option><option value="unknown">Unknown</option></select></label><label>Country code<input maxLength={2} placeholder="NG" value={draftCountry} onChange={e=>setDraftCountry(e.target.value)}/></label><label>Timezone<input placeholder="Africa/Lagos" value={draftTimezone} onChange={e=>setDraftTimezone(e.target.value)}/></label></div>
    </FilterDrawer>
    {state==='loading'?<LoadingState/>:state==='error'?<StatePanel title="Play patterns unavailable" action={<button className="cc-button" onClick={()=>void load()}>Try again</button>}><p>The staff-only report failed. Deploy the Play Patterns migration if this is the first time opening this page.</p></StatePanel>:data?<>
      {data.partial_warnings.map(warning=><div className="cc-warning" key={warning}>{warning}</div>)}
      <p className="cc-freshness">{data.refreshed_at?`Data refreshed ${new Date(data.refreshed_at).toLocaleString()}`:'No matching game starts have arrived yet.'}</p>
      <div className="cc-kpi-grid"><KpiCard label="Game starts" value={formatMetric(data.summary.game_starts)} detail="Within the selected UTC date range"/><KpiCard label="Local-time coverage" value={formatMetric(data.summary.timezone_coverage,'percent')} detail={`${data.summary.timezone_attributed_starts} starts have a timezone`}/><KpiCard label="Peak day" value={data.summary.peak_weekday??'—'} detail="Highest local-time start count"/><KpiCard label="Peak hour" value={hourLabel(data.summary.peak_hour)} detail="Player-local time"/></div>
      <section className="cc-panel cc-play-heatmap"><div className="cc-panel-heading"><h2>Weekly play heatmap</h2><p>Every cell is game starts at that local weekday and hour. Zeroes remain visible.</p></div><div className="cc-heatmap-scroll"><table aria-label="Game starts by local weekday and hour"><thead><tr><th>Day</th>{Array.from({length:24},(_,hour)=><th key={hour}>{String(hour).padStart(2,'0')}</th>)}</tr></thead><tbody>{[1,2,3,4,5,6,7].map(day=><tr key={day}><th>{byCell.get(`${day}-0`)?.weekday??['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day-1]}</th>{Array.from({length:24},(_,hour)=>{const count=byCell.get(`${day}-${hour}`)?.game_starts??0;return <td key={hour} style={{'--heat':String(count/max)} as React.CSSProperties} title={`${count} starts`} aria-label={`${count} starts`}>{count}</td>})}</tr>)}</tbody></table></div></section>
      <div className="cc-detail-grid"><section className="cc-panel cc-geo-bars"><div className="cc-panel-heading"><h2>Starts by weekday</h2><p>Player-local weekday.</p></div><div>{data.weekdays.map(row=><article key={row.iso_weekday}><span>{row.weekday}</span><div><i style={{width:`${100*row.game_starts/Math.max(1,...data.weekdays.map(item=>item.game_starts))}%`}}/></div><strong>{row.game_starts}</strong></article>)}</div></section><section className="cc-panel"><div className="cc-panel-heading"><h2>Hourly totals</h2><p>All 24 local hours.</p></div><DataTable label="Hourly starts"><thead><tr><th>Hour</th><th>Starts</th></tr></thead><tbody>{data.hourly.map(row=><tr key={row.hour}><td>{hourLabel(row.hour)}</td><td>{row.game_starts}</td></tr>)}</tbody></DataTable></section></div>
      <div className="cc-detail-grid"><section className="cc-panel"><div className="cc-panel-heading"><h2>Peak time by country</h2><p>Country is approximate; time is reported browser-local.</p></div><DataTable label="Country peak times"><thead><tr><th>Country</th><th>Starts</th><th>Peak day</th><th>Peak hour</th><th>Coverage</th></tr></thead><tbody>{data.countries.map(row=><tr key={row.country_code}><td>{countryName(row.country_code)} ({row.country_code})</td><td>{row.game_starts}</td><td>{row.peak_weekday??'—'}</td><td>{hourLabel(row.peak_hour)}</td><td>{formatMetric(row.timezone_coverage,'percent')}</td></tr>)}</tbody></DataTable></section><section className="cc-panel"><div className="cc-panel-heading"><h2>Peak time by game</h2><p>Use this to time promotion and content releases.</p></div><DataTable label="Game peak times"><thead><tr><th>Game</th><th>Starts</th><th>Peak day</th><th>Peak hour</th></tr></thead><tbody>{data.games.map(row=><tr key={row.game_id}><td>{row.game_id.replace(/_/g,' ')}</td><td>{row.game_starts}</td><td>{row.peak_weekday??'—'}</td><td>{hourLabel(row.peak_hour)}</td></tr>)}</tbody></DataTable></section></div>
      <p className="cc-privacy-note">No city, GPS coordinate, IP address, room code, display name, card text, or answer is used. Country is server-derived and approximate. Timezone is browser-reported and may differ from physical location.</p>
    </>:null}
  </>
}
