export type ChooseSideCategory = 'everyday' | 'funny' | 'friends' | 'relationships' | 'party' | 'money' | 'morals' | 'deep' | 'adventure' | 'after-dark'

export interface ChooseSidePrompt { optionA: string; optionB: string }

export const CHOOSE_SIDE_CATEGORIES: readonly { id: ChooseSideCategory; label: string; description: string; adult?: boolean }[] = [
  { id: 'everyday', label: 'Everyday', description: 'Habits, food, work and daily trade-offs' },
  { id: 'funny', label: 'Funny & Weird', description: 'Ridiculous choices that split the room' },
  { id: 'friends', label: 'Friendship', description: 'Loyalty, group chats and inside jokes' },
  { id: 'relationships', label: 'Relationships', description: 'Love, communication and compromise' },
  { id: 'party', label: 'Party', description: 'Social chaos, confidence and nightlife' },
  { id: 'money', label: 'Money & Success', description: 'Ambition, comfort and opportunity' },
  { id: 'morals', label: 'Moral Dilemmas', description: 'Honesty, fairness, loyalty and responsibility' },
  { id: 'deep', label: 'Deep Questions', description: 'Identity, meaning and the life you want' },
  { id: 'adventure', label: 'Risk & Adventure', description: 'Travel, courage and the unknown' },
  { id: 'after-dark', label: 'After Dark', description: 'Flirty, revealing choices for adults', adult: true },
]

const p = (optionA: string, optionB: string): ChooseSidePrompt => ({ optionA, optionB })

export const CHOOSE_SIDE_PROMPTS: Record<ChooseSideCategory, readonly ChooseSidePrompt[]> = {
  everyday: [
    p('Wake up naturally every day', 'Fall asleep instantly every night'), p('Always arrive one hour early', 'Always arrive thirty minutes late'),
    p('Give up coffee forever', 'Give up dessert forever'), p('Cook every meal yourself', 'Eat every meal from a restaurant'),
    p('Have a spotless home', 'Never have to do laundry'), p('Work four long days', 'Work five shorter days'),
    p('Only use cash', 'Only use mobile payments'), p('Live without air conditioning', 'Live without hot water'),
    p('Repeat your favourite meal daily', 'Never eat the same meal twice'), p('Always take the stairs', 'Always walk twice as far'),
    p('Lose your phone for a week', 'Lose your wallet for a day'), p('Have unlimited free groceries', 'Have unlimited free transport'),
    p('Do every task immediately', 'Always have one extra day'), p('Share a home with a neat freak', 'Share a home with a great cook'),
    p('Never wait in traffic', 'Never wait in a queue'), p('Have perfect internet everywhere', 'Have a full battery forever'),
    p('Wear one colour for a year', 'Wear one outfit style for a year'), p('Give up music while travelling', 'Give up videos while eating'),
    p('Always know the weather', 'Always know the fastest route'), p('Have breakfast for dinner', 'Have dinner for breakfast'),
    p('Clean as you cook', 'Clean everything after eating'), p('Answer every call', 'Reply to every message immediately'),
    p('Have a tiny kitchen', 'Have a tiny bathroom'), p('Shop once a month', 'Shop a little every day'),
    p('Always find parking', 'Always get the best seat'), p('Never need an alarm', 'Never need a calendar'),
    p('Have quiet neighbours', 'Have helpful neighbours'), p('Only eat crunchy food', 'Only eat soft food'),
    p('Start work at sunrise', 'Finish work at midnight'), p('Have every weekend planned', 'Keep every weekend spontaneous'),
  ],
  funny: [
    p('Laugh every time someone cries', 'Cry every time someone laughs'), p('Speak only in rhymes', 'Sing everything you say'),
    p('Have spaghetti for hair', 'Sweat maple syrup'), p('Fight one horse-sized duck', 'Fight fifty duck-sized horses'),
    p('Wear wet socks all day', 'Sleep with a mosquito in the room'), p('Only whisper at parties', 'Only shout at libraries'),
    p('Have a rewind button', 'Have a mute button'), p('Sneeze glitter', 'Burp bubbles'),
    p('Be followed by dramatic music', 'Hear canned laughter after every joke'), p('Have elbows for knees', 'Have knees for elbows'),
    p('Always smell like onions', 'Always taste toothpaste'), p('Talk to animals that dislike you', 'Understand babies who complain about you'),
    p('Wear clown shoes to work', 'Wear a cape to every formal event'), p('Be famous for a terrible dance', 'Be famous for a ridiculous catchphrase'),
    p('Have a tiny personal cloud', 'Have a loud personal narrator'), p('Only walk backwards', 'Only sit facing the wrong way'),
    p('Turn purple when embarrassed', 'Hiccup whenever you lie'), p('Eat soup with a fork', 'Eat rice with a teaspoon'),
    p('Live in a house shaped like a shoe', 'Drive a car shaped like a banana'), p('Have a pet dinosaur the size of a cat', 'Have a cat the size of a dinosaur'),
    p('Have eyebrows that dance', 'Have ears that applaud'), p('Wear flippers everywhere', 'Wear oven mitts everywhere'),
    p('Be chased by one angry chicken', 'Be judged by one disappointed goat'), p('Have your ringtone play when you sneeze', 'Have confetti fall when you yawn'),
    p('Only communicate with memes', 'Only communicate with movie quotes'), p('Have a laugh that echoes', 'Have footsteps that squeak'),
    p('Be unable to close doors quietly', 'Be unable to open snacks quietly'), p('Have a talking mirror', 'Have a sarcastic fridge'),
    p('Always sit on a warm chair', 'Always drink lukewarm water'), p('Swap voices with your best friend', 'Swap laughs with your boss'),
  ],
  friends: [
    p('Have one brutally honest friend', 'Have five endlessly supportive friends'), p('Share every secret with your best friend', 'Keep one secret forever'),
    p('Plan every group outing', 'Never choose where the group goes'), p('Be the funniest in the group', 'Be the most dependable in the group'),
    p('Lend a friend money', 'Let a friend stay with you for a month'), p('Tell your friend their partner is wrong for them', 'Stay quiet and support their choice'),
    p('Be added to every group chat', 'Never be included in group drama'), p('Take a dream trip with new friends', 'Repeat a familiar trip with old friends'),
    p('Have friends who challenge you', 'Have friends who always understand you'), p('Know what your friends say about you', 'Never hear anyone gossip again'),
    p('Forgive a cancelled plan', 'Stop inviting the person who always cancels'), p('Call out your friend in public', 'Correct them privately later'),
    p('Be remembered for great advice', 'Be remembered for showing up'), p('Share a room with your messiest friend', 'Share a road trip with your slowest friend'),
    p('Keep a friend’s harmless secret', 'Tell the truth when someone asks directly'), p('Choose friendship over a promotion', 'Take the promotion and move away'),
    p('Have matching humour', 'Have matching values'), p('Reunite with a childhood friend', 'Make a lifelong friend today'),
    p('Be the friend everyone calls in a crisis', 'Be the friend everyone calls to celebrate'), p('Know exactly when a friendship will end', 'Never know whether it will last'),
    p('Tell your friend they are wrong', 'Let experience teach them'), p('Share a holiday with your oldest friend', 'Share a new hobby with your newest friend'),
    p('Have friends nearby', 'Have close friends around the world'), p('Remember every birthday', 'Remember every important conversation'),
    p('Give honest feedback immediately', 'Wait until they ask for it'), p('Be invited everywhere', 'Feel completely at home somewhere'),
    p('Keep the peace in your group', 'Challenge the group when it matters'), p('Loan your favourite outfit', 'Loan your favourite book'),
    p('Celebrate a friend’s success quietly', 'Throw them a surprise party'), p('Have friends who share your lifestyle', 'Have friends who expand your worldview'),
  ],
  relationships: [
    p('Date someone spontaneous', 'Date someone dependable'), p('Receive thoughtful words', 'Receive thoughtful actions'),
    p('Share every hobby', 'Have completely separate interests'), p('Resolve every argument immediately', 'Take time apart before talking'),
    p('Have perfect chemistry', 'Have perfect communication'), p('Know your partner’s every thought', 'Let some mystery remain'),
    p('Celebrate every anniversary extravagantly', 'Make ordinary days feel special'), p('Live near both families', 'Live far away and build your own traditions'),
    p('Have a partner who plans everything', 'Have a partner who follows your lead'), p('Say “I love you” often', 'Show love without saying it'),
    p('Share one bank account', 'Keep finances completely separate'), p('Be with someone exactly like you', 'Be with someone who balances you'),
    p('Forgive one major mistake', 'Leave after one broken promise'), p('Choose stability together', 'Take a big shared risk'),
    p('Have weekly date nights', 'Take one unforgettable yearly trip'), p('Always agree on money', 'Always agree on family decisions'),
    p('Meet the right person too early', 'Meet them later when you are ready'), p('Know how the relationship ends', 'Enjoy it without knowing'),
    p('Be loved loudly', 'Be understood deeply'), p('Have a private relationship', 'Share your relationship openly'),
    p('Plan your future early', 'Let the relationship unfold naturally'), p('Receive flowers regularly', 'Receive practical help regularly'),
    p('Spend every holiday together', 'Alternate holidays with family'), p('Share your daily plans', 'Protect personal privacy'),
    p('Have identical sleep schedules', 'Have identical social energy'), p('Move for your partner’s opportunity', 'Ask them to stay for yours'),
    p('Discuss every disagreement', 'Let small things go'), p('Know you are compatible immediately', 'Grow compatible over time'),
    p('Have your partner surprise you', 'Choose everything together'), p('Build a quiet home together', 'Build an exciting life together'),
  ],
  party: [
    p('Host the party', 'Arrive as the favourite guest'), p('Control the music', 'Control the food'),
    p('Dance first', 'Start the first conversation'), p('Attend a huge festival', 'Attend a perfect house party'),
    p('Be overdressed', 'Be underdressed'), p('Know everyone at the party', 'Meet everyone for the first time'),
    p('Sing karaoke solo', 'Lead a group dance'), p('Stay until sunrise', 'Leave while the night is still good'),
    p('Have unlimited drinks', 'Have unlimited food'), p('Lose your voice', 'Lose one shoe'),
    p('Give the toast', 'Plan the surprise'), p('Have the best photos', 'Have the funniest stories'),
    p('Party on a rooftop', 'Party on a beach'), p('Attend in costume', 'Attend a black-tie event'),
    p('Play games all night', 'Dance all night'), p('Be introduced with the wrong name', 'Forget someone’s name immediately'),
    p('Have your ex arrive', 'Have your boss arrive'), p('Be responsible for the playlist', 'Be responsible for getting everyone home'),
    p('Join a party where nobody knows you', 'Host people who do not know each other'), p('End the night with breakfast', 'End the night with a long walk home'),
    p('Attend a themed party', 'Attend a secret-location party'), p('Win every party game', 'Tell the best story of the night'),
    p('Meet your favourite artist', 'Get backstage with your friends'), p('Have one perfect dance partner', 'Have the entire room join your dance'),
    p('Take photos all night', 'Keep your phone away all night'), p('Celebrate your birthday big', 'Celebrate someone else’s surprise'),
    p('Attend a party in another city', 'Bring another city’s party to your home'), p('Have a live band', 'Have a brilliant DJ'),
    p('Be the first person there', 'Be the last person standing'), p('Know the host well', 'Know the guest of honour well'),
  ],
  money: [
    p('Earn more doing work you dislike', 'Earn enough doing work you love'), p('Receive a large sum now', 'Receive a smaller amount every month forever'),
    p('Own your dream home', 'Travel whenever you want'), p('Have complete job security', 'Have unlimited career freedom'),
    p('Be respected but unknown', 'Be famous but frequently criticised'), p('Retire early with a simple life', 'Work longer for a luxurious life'),
    p('Double your income', 'Cut your working hours in half'), p('Invest in a friend’s idea', 'Keep your savings safe'),
    p('Get your dream title', 'Get your dream salary'), p('Build one successful company', 'Have five successful careers'),
    p('Know every good investment', 'Never make an expensive mistake'), p('Buy experiences', 'Buy things that last'),
    p('Receive public credit', 'Receive a private bonus'), p('Work from anywhere', 'Never work after 3 p.m.'),
    p('Have a brilliant boss', 'Have brilliant colleagues'), p('Start over in a new industry', 'Become the expert where you are'),
    p('Share your salary openly', 'Never discuss money'), p('Inherit wealth with conditions', 'Build wealth without help'),
    p('Be rich with no free time', 'Be comfortable with complete freedom'), p('Fund your own dream', 'Fund someone else’s potential'),
    p('Have a high salary in an expensive city', 'Have a modest salary in an affordable town'), p('Own a profitable business', 'Hold a meaningful leadership role'),
    p('Take a guaranteed small return', 'Risk it for a much larger return'), p('Pay off every debt', 'Build a strong emergency fund'),
    p('Be excellent at negotiation', 'Be excellent at spotting opportunities'), p('Choose a prestigious employer', 'Choose a kind employer'),
    p('Earn money from your talent', 'Keep your talent free from pressure'), p('Receive ten years of salary today', 'Receive twice your salary for ten years'),
    p('Own fewer premium things', 'Own many practical things'), p('Teach others how to succeed', 'Keep your winning strategy private'),
  ],
  morals: [
    p('Tell a painful truth', 'Protect someone with a lie'), p('Return money nobody saw you find', 'Give it to someone who urgently needs it'),
    p('Expose a friend who cheated', 'Remain loyal and stay silent'), p('Save one person you love', 'Save five strangers'),
    p('Forgive someone who never apologised', 'Remove them from your life'), p('Report a coworker’s serious mistake', 'Help them quietly fix it'),
    p('Keep a promise that causes harm', 'Break the promise to prevent harm'), p('Give one person a second chance', 'Protect the group from another risk'),
    p('Accept credit for a team success', 'Correct the record and risk conflict'), p('Follow an unfair rule', 'Break it openly and accept the consequence'),
    p('Tell a friend their partner is unfaithful', 'Wait until you have undeniable proof'), p('Donate anonymously', 'Donate publicly to encourage others'),
    p('Choose the most qualified person', 'Choose the person who needs the opportunity'), p('Reveal confidential information to prevent harm', 'Protect the confidence you were trusted with'),
    p('Punish one guilty person severely', 'Risk letting several guilty people go free'), p('Take responsibility for a group mistake', 'Name the person who caused it'),
    p('Help family before strangers', 'Help whoever needs it most'), p('Judge someone by their intention', 'Judge them by the outcome'),
    p('Offer mercy after repeated mistakes', 'Enforce the same consequence for everyone'), p('Stand by a friend you disagree with', 'Publicly defend the principle you believe in'),
    p('Keep found property safe', 'Search immediately for its owner'), p('Tell the whole truth', 'Leave out a detail that would only cause pain'),
    p('Reward effort', 'Reward results'), p('Protect one person’s privacy', 'Warn everyone about a real risk'),
    p('Give scarce help to the youngest', 'Give it to the person most likely to recover'), p('Refuse an unfair advantage', 'Use it to help people you care about'),
    p('Respect a harmful tradition', 'Challenge it and upset your community'), p('Keep your word to a rival', 'Change course to protect your team'),
    p('Reveal your own mistake first', 'Fix the damage before explaining'), p('Choose equal treatment', 'Choose help based on individual need'),
  ],
  deep: [
    p('Know your life’s purpose', 'Know exactly how to achieve it'), p('Remember everything', 'Be able to forget anything'),
    p('Be admired by millions', 'Be truly known by five people'), p('Relive your happiest year', 'Skip ahead to your most successful year'),
    p('Change one past decision', 'See one future consequence'), p('Have complete certainty', 'Keep the freedom to change your mind'),
    p('Live a short extraordinary life', 'Live a long peaceful life'), p('Be understood without speaking', 'Say exactly what you mean every time'),
    p('Lose every old regret', 'Keep every lesson it taught you'), p('Discover an uncomfortable truth', 'Keep a comforting belief'),
    p('Be remembered for your achievements', 'Be remembered for how you treated people'), p('Have more confidence', 'Have more self-awareness'),
    p('Always follow your head', 'Always follow your heart'), p('Know when people lie', 'Know why they lie'),
    p('Find belonging anywhere', 'Build one place that feels like home'), p('Have unlimited time', 'Have unlimited motivation'),
    p('Live without comparison', 'Live without regret'), p('Become the person your younger self wanted', 'Become the person your future self needs'),
    p('Receive closure', 'Receive another chance'), p('Know the meaning of life', 'Create your own meaning'),
    p('Be completely independent', 'Be deeply connected to others'), p('Always feel needed', 'Always feel free'),
    p('See yourself as others see you', 'See others as they see themselves'), p('Keep every memory', 'Keep only the memories that help you grow'),
    p('Find peace with uncertainty', 'Find answers to your biggest questions'), p('Be consistent forever', 'Keep reinventing yourself'),
    p('Have courage without confidence', 'Have confidence without certainty'), p('Choose who you become', 'Understand who you already are'),
    p('Experience intense joy and grief', 'Experience steady contentment'), p('Leave a lasting legacy', 'Live fully without being remembered'),
  ],
  adventure: [
    p('Explore the deepest ocean', 'Explore outer space'), p('Travel alone for a year', 'Travel with friends for one month'),
    p('Climb a famous mountain', 'Cross a country by road'), p('Visit the past', 'Visit the future'),
    p('Live in a new country', 'Travel constantly without settling'), p('Take a trip with no plan', 'Follow a perfectly planned itinerary'),
    p('Skydive once', 'Scuba dive every year'), p('Spend a week in the desert', 'Spend a week in the Arctic'),
    p('Discover a hidden city', 'Discover a new species'), p('Sail across an ocean', 'Trek across a continent'),
    p('Travel with one small bag', 'Travel with every comfort'), p('Take the scenic route', 'Reach the destination instantly'),
    p('Camp beneath the stars', 'Sleep in a historic castle'), p('Visit every capital city', 'Visit every natural wonder'),
    p('Have a local guide everywhere', 'Understand every language'), p('Lose your map', 'Lose your luggage'),
    p('Try every local dish', 'Try every local adventure'), p('Photograph every trip', 'Experience every trip without a camera'),
    p('Take one dangerous shortcut', 'Take the safe route twice as long'), p('Return to your favourite destination', 'Go somewhere completely unknown'),
    p('Explore a jungle', 'Explore a volcanic island'), p('Travel by sleeper train', 'Travel by sailing boat'),
    p('Spend a month off-grid', 'Spend a month in a megacity'), p('Take a spontaneous flight', 'Plan a dream journey for a year'),
    p('Cross a glass bridge', 'Enter a deep cave'), p('See the northern lights', 'See a total solar eclipse'),
    p('Travel for food', 'Travel for music'), p('Learn survival skills', 'Learn navigation skills'),
    p('Hike at sunrise', 'Kayak at sunset'), p('Have every trip be comfortable', 'Have every trip become a great story'),
  ],
  'after-dark': [
    p('Make the first move', 'Be pursued'), p('Kiss in the rain', 'Dance together at midnight'),
    p('Have undeniable chemistry', 'Have complete emotional safety'), p('Send a risky text', 'Say it face to face'),
    p('Date your longtime crush', 'Meet someone completely unexpected'), p('Plan a romantic night', 'Be completely surprised'),
    p('Share your biggest turn-on', 'Hear your partner’s secret fantasy'), p('Have a private weekend away', 'Attend a glamorous party together'),
    p('Be caught flirting', 'Accidentally reveal your crush'), p('Choose slow-burn tension', 'Choose instant attraction'),
    p('Have perfect kisses', 'Have perfect cuddles'), p('Revisit your best date', 'Design a completely new one'),
    p('Be bold in public', 'Be adventurous in private'), p('Receive a love letter', 'Receive a late-night voice note'),
    p('Confess first', 'Wait for them to confess'), p('Date someone mysterious', 'Date someone completely transparent'),
    p('Know their dating history', 'Know nothing and start fresh'), p('Have one unforgettable romance', 'Have one dependable lifelong love'),
    p('Flirt through humour', 'Flirt through eye contact'), p('Stay up talking until sunrise', 'Wake up together somewhere beautiful'),
    p('Choose a secret admirer', 'Choose an obvious flirt'), p('Have a candlelit dinner', 'Have a spontaneous night drive'),
    p('Share a daring compliment', 'Ask a revealing question'), p('Be kissed unexpectedly', 'Be asked first'),
    p('Plan the first date', 'Plan the first getaway'), p('Keep a holiday romance', 'Reconnect with an old flame'),
    p('Receive a teasing message', 'Receive a sincere confession'), p('Have attraction grow slowly', 'Feel an immediate spark'),
    p('Share your celebrity crush', 'Share your most embarrassing dating story'), p('End the night with a kiss', 'End the night wanting one more date'),
  ],
}

export const CHOOSE_SIDE_DECK = Object.values(CHOOSE_SIDE_PROMPTS).flat()
export const CHOOSE_SIDE_AUDIT_TEXT = CHOOSE_SIDE_DECK.map(card => `${card.optionA} OR ${card.optionB}`)
