import { uniqueCards } from '../utils/deckShuffle'
import { expandPromptDeck } from './promptExpansion.js'

export function withMinimumContent(
  primary: readonly string[],
  supplementary: readonly string[],
  minimum = 300,
): string[] {
  const combined = uniqueCards([...primary, ...supplementary])
  return combined.length >= minimum ? combined : expandPromptDeck(primary, supplementary, minimum)
}

/** Broad, all-ages questions used only to deepen compatible conversation decks. */
export const CONVERSATION_SUPPLEMENT = [
  'What small decision changed your life more than you expected?',
  'Which ordinary moment from this year would you happily relive?',
  'What is something you understand now that you wish you knew five years ago?',
  'When do you feel most like yourself?',
  'What is the kindest thing a stranger has ever done for you?',
  'Which tradition would you like to start with the people you love?',
  'What opinion have you changed your mind about recently?',
  'What is a skill you would learn instantly if effort were not required?',
  'Which place makes you feel calm as soon as you arrive?',
  'What compliment have you remembered for years?',
  'What does a genuinely good day look like for you?',
  'Which part of growing older has surprised you most?',
  'What is something people often misunderstand about you?',
  'What are you better at than you give yourself credit for?',
  'Which conversation had a lasting impact on you?',
  'What is one thing you hope never becomes outdated?',
  'Who taught you an important lesson without realizing it?',
  'What makes a friendship feel safe to you?',
  'Which memory always makes you laugh before you finish telling it?',
  'What would your younger self be proud to see you doing now?',
  'What is something you are currently learning to accept?',
  'Which everyday luxury do you appreciate most?',
  'What is the best advice you ignored before discovering it was right?',
  'When was the last time you surprised yourself?',
  'What is one boundary that improved your life?',
  'Which family story deserves to be remembered for generations?',
  'What is your favorite way to make someone feel welcome?',
  'What are you looking forward to that has nothing to do with work?',
  'Which personal rule do you live by?',
  'What is something you miss about a past version of your life?',
  'What is the most useful failure you have experienced?',
  'Which smell instantly takes you back to a particular memory?',
  'What makes you lose track of time in the best way?',
  'What is one thing you wish people asked you about more often?',
  'Which risk are you glad you took?',
  'What does feeling at home mean to you?',
  'What is a belief you inherited and later chose for yourself?',
  'Which simple habit has improved your mood the most?',
  'What kind of support is hardest for you to ask for?',
  'What is the most unexpectedly beautiful place you have visited?',
  'Which song feels connected to an important chapter of your life?',
  'What is something you hope to become more courageous about?',
  'How do you know when you truly trust someone?',
  'What is your favorite memory involving food?',
  'Which quality do you admire in someone at this table?',
  'What is a harmless hill you are willing to die on?',
  'If your week had a title, what would it be?',
  'What is the funniest misunderstanding you have been part of?',
  'Which fictional world would be fun to visit but terrible to live in?',
  'What is a purchase under twenty dollars that improved your life?',
  'If you could preserve one sound forever, what would it be?',
  'What is your most specific and unnecessary talent?',
  'Which social rule would you happily retire?',
  'What is the strangest food combination you genuinely enjoy?',
  'If your personality were a room, what would be inside it?',
  'What is the best surprise you have ever planned or received?',
  'Which minor inconvenience turns you into a dramatic person?',
  'What is a boring topic you could discuss for an hour?',
  'If today came with a warning label, what would it say?',
  'Which phase of your life had the most questionable style?',
  'What is a tiny act of rebellion that always delights you?',
  'Which app would be hardest for you to delete for a month?',
  'What is the funniest excuse you have ever used?',
  'If your life had a recurring background character, who would it be?',
  'What is an irrational fear you can laugh about now?',
  'Which childhood snack still has power over you?',
  'What is the most memorable thing you have overheard in public?',
  'If you opened a very niche museum, what would it display?',
  'What is something everyone seems to know how to do except you?',
  'Which everyday object would make the worst roommate?',
  'What is the most chaotic trip you have ever taken?',
  'If you had to give a ten-minute talk with no preparation, what topic would you choose?',
  'Which movie would improve if one character were replaced by a talking dog?',
  'What is your most dramatic reaction to a very small problem?',
  'Which trend did you resist and later enjoy?',
  'What is a food you defend even when everyone judges you?',
  'If your phone could reveal one statistic about you, what would be most embarrassing?',
  'What is the worst haircut you have ever willingly requested?',
  'Which household chore would you make an Olympic event?',
  'What is a strangely specific sign that someone is your kind of person?',
  'If you could add one unofficial holiday to the calendar, what would it celebrate?',
  'What is the funniest thing you believed as a child?',
  'Which ordinary activity makes you feel unexpectedly competitive?',
  'What would your signature dish be if cooking skill were guaranteed?',
  'What is a rule you follow even when nobody is watching?',
  'Which object in your home has the best story?',
  'What is a problem you are proud of how you handled?',
  'When have you felt most supported by a group?',
  'What is one thing you want to make more time for?',
  'Which person brings out a side of you that you like?',
  'What is something you have outgrown without noticing?',
  'What does success look like in your current season of life?',
  'Which memory reminds you that difficult periods eventually pass?',
  'What is a promise you want to keep to yourself?',
  'What is one way your priorities have changed this year?',
  'Which part of your routine deserves more appreciation?',
  'What kind of legacy matters to you on a small, everyday scale?',
  'What would you attempt if you knew embarrassment was impossible?',
  'Which question are you currently trying to answer in your own life?',
  'What is one thing you hope the people here understand about you?',
  'What has made you feel genuinely hopeful lately?',
  'Which part of your personality took time for you to appreciate?',
  'What is a lesson you learned from watching someone else?',
  'When do you find it easiest to be honest?',
  'What is one memory you would place in a time capsule?',
  'Which relationship in your life has changed you for the better?',
  'What do you want to be remembered for by the people closest to you?',
  'What is something you once feared that now feels ordinary?',
  'Which choice brought an unexpected person into your life?',
  'What is one way you have become more patient?',
  'What kind of conversation makes you feel energized?',
  'Which personal achievement means more to you than it looks from outside?',
  'What do you wish adults had explained better when you were younger?',
  'What is a quality you are actively trying to strengthen?',
  'Which part of your future feels most exciting right now?',
  'What is the best thing someone has taught you about friendship?',
  'When have you chosen peace over being right?',
  'What is something difficult that made you gentler?',
  'Which expectation of adulthood turned out to be completely wrong?',
  'What makes you feel appreciated without anyone saying a word?',
  'What is a question you wish you had asked someone sooner?',
  'Which season of your life taught you the most about yourself?',
  'What is a dream you have not talked about much?',
  'When did a small kindness arrive at exactly the right time?',
  'What would you like to thank your past self for?',
  'Which value becomes more important to you as you grow older?',
  'What is one thing you are ready to do differently?',
  'How has your definition of love changed over time?',
  'What gives you a sense of belonging?',
  'Which decision helped you trust yourself more?',
  'What is a memory that feels warmer every time you revisit it?',
  'What do you need more of in this chapter of your life?',
  'Which part of yourself are you learning to protect?',
  'What is something you hope to teach another person someday?',
  'What helps you return to yourself after a difficult day?',
  'Which unplanned experience became a favorite memory?',
  'What is something you want to celebrate more openly?',
  'When have you felt truly seen by another person?',
  'What does emotional maturity look like to you?',
  'Which sacrifice are you grateful someone made for you?',
  'What is one belief about yourself you are trying to rewrite?',
  'Who makes you feel comfortable enough to be ridiculous?',
  'What is something beautiful about your current life that you once wished for?',
  'Which goodbye taught you the most?',
  'What is one thing you would like to forgive yourself for?',
  'How do you want people to feel after spending time with you?',
  'What is a form of courage people do not praise enough?',
  'Which ordinary person in your life deserves more recognition?',
  'What is the most honest advice you could give your future self?',
  'What are you becoming more certain about?',
  'What is one way you would like to show up better for your friends?',
  'Which difficult conversation are you glad you finally had?',
  'What does a healthy apology sound like to you?',
  'What is a goal you care about even if nobody else notices?',
  'Which part of your story do you understand differently now?',
  'What is a joyful memory you have not thought about recently?',
  'Who believed in you before you believed in yourself?',
  'What helps you feel grounded when life becomes noisy?',
  'Which change in your life arrived at the right time?',
  'What would a more balanced version of your week look like?',
  'What is something you are proud to have walked away from?',
  'Which relationship taught you the meaning of reciprocity?',
  'What do you find easier to give than to receive?',
  'What is one assumption people make about your life that is wrong?',
  'Which experience made you more open-minded?',
  'What does rest mean to you beyond simply sleeping?',
  'What is something you would do again despite how difficult it was?',
  'Which version of yourself needed the most compassion?',
  'What does being dependable mean in practice?',
  'What is a quiet source of confidence for you?',
  'Which friendship lesson did you learn later than you wish you had?',
  'What makes an ordinary gathering memorable?',
  'What is something you want to approach with more curiosity?',
  'Which part of your life feels most aligned right now?',
  'What is one thing you no longer need permission to do?',
  'When have you felt proud of how you treated someone?',
  'What is a responsibility you carry that others may not see?',
  'Which compliment would mean the most to you today?',
  'What does a meaningful life contain for you?',
  'What is something you have learned about asking for help?',
  'Which ending created space for a better beginning?',
  'What is a recent moment when you chose yourself?',
  'What does consistency look like in a relationship?',
  'Which shared experience brings people closer quickly?',
  'What would you like to become less afraid of saying?',
  'What is one way you have surprised the people who know you best?',
  'Which daily choice reflects your values most clearly?',
  'What is something you want to remember about this period of your life?',
  'What would make the next month feel meaningful?',
  'Which part of connection cannot be rushed?',
]

/** Physical, verbal, and improvisational dares suitable for a party setting. */
export const DARE_SUPPLEMENT = [
  'Give a dramatic acceptance speech for an award you clearly did not earn.',
  'Let the group choose an animal you must imitate until someone guesses it.',
  'Sell a random object in the room as if it costs one million dollars.',
  'Speak in rhyme until your next turn.',
  'Perform a thirty-second runway walk using the nearest object as an accessory.',
  'Call an imaginary customer-service line and complain about gravity.',
  'Narrate another player taking a sip as if it is a championship final.',
  'Make up a short song about the person to your left.',
  'Attempt to moonwalk across the room.',
  'Let the group give you a new nickname for the next three rounds.',
  'Explain how to make toast as if you are revealing a dangerous secret.',
  'Do your best impression of someone waking up late for an important meeting.',
  'Balance an object on your head while answering the next question.',
  'Create a handshake with the player opposite you.',
  'Act out your morning routine without speaking.',
  'Deliver a weather forecast for the mood in the room.',
  'Try to make the group laugh using only facial expressions.',
  'Invent a slogan for your personality and perform the advertisement.',
  'Dance for twenty seconds to music only you can hear.',
  'Read your most recent harmless text message like a Shakespearean monologue.',
  'Pretend to be a tour guide showing everyone around this exact room.',
  'Hold a serious press conference about losing one sock.',
  'Use three random words chosen by the group in a convincing love poem.',
  'Recreate your favorite emoji with your whole body.',
  'Speak like a robot until another player completes a dare.',
  'Act like a celebrity avoiding imaginary photographers for thirty seconds.',
  'Make a sound effect every time someone moves until your next turn.',
  'Perform a commercial for water without saying the word water.',
  'Walk across the room as though the floor changes texture every step.',
  'Give everyone in the group a superhero name.',
  'Do ten seconds of interpretive dance about Monday mornings.',
  'Pretend your hand is a phone and have an argument with it.',
  'Describe the person on your right using only movie titles.',
  'Create a new dance move and teach it to one other player.',
  'Give a motivational speech to a household object.',
  'Talk without closing your mouth fully until your next turn.',
  'Act out a famous film scene chosen by the group.',
  'Compose a jingle for the snack closest to you.',
  'Do your best slow-motion celebration.',
  'Pretend you are a detective investigating who finished the snacks.',
  'Say the alphabet backwards until you make a mistake.',
  'Use a different accent for the next two rounds.',
  'Perform a silent argument with an invisible roommate.',
  'Let another player pose you like a statue for one round.',
  'Describe your day using only sound effects.',
  'Invent a conspiracy theory about a common household object.',
  'Give a one-minute cooking show using imaginary ingredients.',
  'Attempt a tongue twister chosen by the group three times quickly.',
  'Pretend to receive life-changing news, then reveal it is about pizza.',
  'Create a five-second theme song for every player.',
  'Move like you are underwater until your next turn.',
  'Give a sincere apology to a chair for sitting on it.',
  'Try to wink with both eyes separately on command.',
  'Act like a sports coach giving halftime advice to the group.',
  'Tell a familiar story while replacing every person with a fruit.',
  'Perform your best evil laugh, then your best heroic laugh.',
  'Pretend you are an influencer reviewing the room.',
  'Let the group choose one word you must include in every sentence for two rounds.',
  'Do an impression of your own laugh.',
  'Invent and demonstrate a useless exercise routine.',
  'Explain social media to someone from the year 1800.',
  'Pose for three imaginary magazine covers.',
  'Deliver a breakup speech to your least favorite vegetable.',
  'Make up a bedtime story starring two people in the group.',
  'Perform a dramatic reenactment of your last minor inconvenience.',
  'Speak as if everything is unbelievably exciting until your next turn.',
  'Try to juggle three safe objects selected by the group.',
  'Create a secret-agent code name and mission for yourself.',
  'Act like a cat trying to convince humans to open a door.',
  'Host a ten-second awards show for the best outfit in the room.',
  'Give directions to the kitchen as though it is a mythical quest.',
  'Pretend the floor is extremely hot for twenty seconds.',
  'Make an ordinary sentence sound terrifying.',
  'Do your best impression of a buffering video call.',
  'Start a group wave and keep trying until everyone joins.',
  'Use your elbows to mime brushing your teeth.',
  'Act out three emotions while saying the same sentence.',
  'Perform a magic trick, even if the trick is obviously fake.',
  'Introduce yourself as a professional in a completely invented career.',
  'Make up a national anthem for the room you are in.',
  'Give a dramatic reading of an ingredient label.',
  'Pretend to be a flight attendant explaining party safety rules.',
  'Create an interpretive dance for a notification sound.',
  'Speak only in questions until your next turn.',
  'Act like you are walking through three kinds of imaginary weather.',
  'Let the group choose a word you must sing instead of say.',
  'Invent a product that solves a problem nobody has.',
  'Give a two-sentence speech as the mayor of this gathering.',
  'Mime a hobby until the group identifies it.',
  'Make up a rumor about your own fictional celebrity life.',
  'Perform a victory lap around your seat in slow motion.',
  'Describe your outfit as though it belongs in a museum.',
  'Act like a confused time traveler seeing a smartphone for the first time.',
  'Give a pep talk to the player who goes next.',
  'Reenact ordering food using no words.',
  'Create a new greeting and use it with every player.',
  'Pretend you are hosting a documentary about the group.',
  'Turn the last thing someone said into a short chorus.',
  'Freeze whenever anyone says your name until your next turn.',
  'End every sentence with “apparently” for two rounds.',
  'Pretend to audition for the role of yourself in a film.',
  'Give a dramatic warning about the dangers of wearing socks.',
  'Act out opening the world’s most disappointing present.',
  'Create a three-step dance inspired by making breakfast.',
  'Speak like a nature-documentary narrator until your next turn.',
  'Perform a silent scene about being locked out of your house.',
  'Pitch a reality show starring everyone in the room.',
  'Let the group choose a celebrity for you to impersonate ordering lunch.',
  'Make up a poem using the names of three objects nearby.',
  'Pretend an invisible string is pulling you around the room.',
  'Give a tutorial on how to procrastinate professionally.',
  'Act like the room is a spaceship experiencing mild turbulence.',
  'Sing everything you say until another player laughs.',
  'Invent a mascot for the group and demonstrate its signature move.',
  'Describe your last meal as though it was a luxury fashion collection.',
  'Hold a debate with yourself about whether cereal is soup.',
  'Perform a dramatic scene in which your charger stops working.',
  'Try to make three different people laugh in thirty seconds.',
  'Imitate three phone notification sounds chosen by the group.',
  'Give a speech entirely in made-up words while acting confident.',
  'Pretend to teach a class on a subject you know nothing about.',
  'Walk like a video-game character stuck against a wall.',
  'Announce every movement you make until your next turn.',
  'Create a commercial for the shoes you are wearing.',
  'Act like a waiter describing an extremely ordinary glass of water.',
  'Tell a joke while maintaining the most serious face possible.',
  'Pretend to be a GPS that is becoming increasingly emotional.',
  'Perform a thirty-second soap-opera scene with another player.',
  'Give an inspirational quote, then admit you invented it.',
  'Mime being chased by the smallest possible monster.',
  'Turn a nursery rhyme into a dramatic power ballad.',
  'Speak in third person for the next two rounds.',
  'Pretend every object you touch is surprisingly cold.',
  'Create a handshake with yourself and perform both sides.',
  'Narrate your next action like a movie trailer.',
  'Act out trying to stay awake in the world’s longest meeting.',
  'Give a breaking-news report about something happening in the room.',
  'Make up a restaurant menu based on the personalities present.',
  'Do a slow-motion impression of missing a bus.',
  'Pretend your reflection has started disagreeing with you.',
  'Explain a simple object as if it were alien technology.',
  'Deliver a campaign speech for becoming group leader.',
  'Create a new sound and convince everyone it is a real word.',
  'Act like a very dramatic ghost who only haunts kitchens.',
  'Perform a scene where you discover your pockets are portals.',
  'Give a guided meditation that becomes increasingly absurd.',
  'Invent a handshake for people who dislike handshakes.',
  'Pretend you are accepting an award for best nap.',
  'Describe the room using the voice of an excited sports commentator.',
  'Act out receiving a text that changes absolutely nothing.',
  'Pretend you are a museum guard protecting a completely ordinary object.',
  'Give a dramatic monologue about waiting for food delivery.',
  'Act like your shoes have suddenly developed personalities.',
  'Host a cooking competition between two imaginary chefs.',
  'Perform a scene where every sentence must begin with “Unfortunately.”',
  'Create a dance inspired by trying to open stubborn packaging.',
  'Pretend to interview yourself after an important imaginary victory.',
  'Give a serious lecture about the proper way to eat a biscuit.',
  'Act like a weather reporter standing in an invisible storm.',
  'Make a thirty-second documentary about the nearest lamp.',
  'Invent a new sport using only objects within reach.',
  'Pretend you are a villain whose only goal is stealing leftovers.',
  'Give a tour of the room in the style of a luxury estate agent.',
  'Perform an emotional reunion with an object you used five minutes ago.',
  'Describe a normal day as though it were an epic fantasy adventure.',
  'Act out realizing you have joined the wrong video meeting.',
  'Create a slogan and mascot for doing absolutely nothing.',
  'Speak like a pirate who is afraid of the ocean until your next turn.',
  'Pretend to be a personal trainer for someone lifting a single cushion.',
  'Narrate an imaginary chase scene happening behind the group.',
  'Give a product demonstration for an invisible invention.',
  'Act like a detective questioning a suspicious snack.',
  'Turn your name into a three-line song.',
  'Pretend the group has just landed on a newly discovered planet.',
  'Perform a dramatic reading of the current time.',
  'Act like you are trying to communicate through a terrible phone signal.',
  'Invent a holiday tradition and demonstrate it.',
  'Give a motivational speech to someone who has dropped a spoon.',
  'Pretend you are a royal announcing a very minor decision.',
  'Create sound effects for another player walking across the room.',
  'Act out a job interview for the role of professional napper.',
  'Explain your favorite snack without naming any ingredients.',
  'Perform a silent scene about stepping on something unexpectedly wet.',
  'Speak in headlines until your next turn.',
  'Act like an overly enthusiastic host welcoming everyone to breakfast.',
  'Invent a warning label for yourself and present it to the group.',
  'Pretend to translate an imaginary language spoken by another player.',
  'Give a eulogy for a phone battery that reached zero percent.',
  'Act out trying to look normal after walking into the wrong room.',
  'Create a short anthem for people who are always five minutes late.',
]

/** Experiences that can be adapted to Never Have I Ever and similar formats. */
export const EXPERIENCE_SUPPLEMENT = [
  'sent a message to the wrong person and immediately panicked',
  'pretended to know a song and confidently sang the wrong words',
  'laughed at a joke I did not understand',
  'waved back at someone who was not waving at me',
  'rehearsed an argument alone and still lost the real one',
  'searched for my phone while holding it',
  'made an excuse to leave a party early',
  'stayed at a party much longer than I wanted to',
  'forgot someone’s name seconds after being introduced',
  'looked up the ending of a show before finishing it',
  'cried because I was tired rather than sad',
  'taken food from someone else’s plate without asking',
  'pretended my camera was broken during a video call',
  'missed a stop because I was distracted',
  'bought something mainly because the packaging looked good',
  'practiced a casual greeting before seeing someone',
  'avoided a person by suddenly checking my phone',
  'kept a gift I did not like and pretended to love it',
  'used a fake birthday while signing up for a website',
  'fallen asleep during a film I chose',
  'eaten an entire meal while standing in the kitchen',
  'cancelled plans and felt immediate relief',
  'made plans while already hoping they would be cancelled',
  'googled a basic fact I was too embarrassed to ask about',
  'replied “you too” when it made no sense',
  'worn clothes with the tag still attached',
  'left a shop without buying anything because an employee approached me',
  'pretended to receive a call to escape a conversation',
  'judged a restaurant by its bathroom',
  'made a playlist for a relationship that did not exist',
  'deleted a post because it did not get enough attention',
  'checked who viewed my story more than once',
  'looked through years of someone’s social-media posts',
  'accidentally liked an old photo while scrolling',
  'typed a long message and deleted it without sending',
  'ignored a message while continuing to post online',
  'sent a screenshot back to the person it was about',
  'changed my profile photo hoping one specific person would notice',
  'used song lyrics as an indirect message',
  'muted a group chat and forgot it existed',
  'joined a trend after publicly saying it was silly',
  'searched my own name online',
  'created a second account for a very specific purpose',
  'pretended not to see a notification so I could answer later',
  'read a message from the notification preview to avoid opening it',
  'used a filter and wished I looked like that in real life',
  'unfollowed someone after a minor disagreement',
  'written a caption and decided the photo was not worth posting',
  'taken more than twenty photos to get one acceptable picture',
  'kept an embarrassing photo of a friend for future leverage',
  'had a crush on someone my friends strongly disliked',
  'gone on a date mostly for the story',
  'pretended to share an interest because I liked someone',
  'ignored an obvious red flag because the chemistry was good',
  'checked whether an ex still followed me',
  'replied too quickly and then waited before sending the next message',
  'made up a reason to text someone I missed',
  'developed feelings for someone who started as a friend',
  'stayed in a situation after knowing it was over',
  'asked a friend to analyze a one-word reply',
  'imagined an entire future after one good conversation',
  'forgot an anniversary or important date',
  'said I was fine when I clearly was not',
  'been jealous without admitting it',
  'apologized just to end an argument',
  'kept a souvenir from a past relationship',
  'had a dream about someone and acted differently around them afterward',
  'written a message I knew I should not send',
  'mistaken friendliness for flirting',
  'flirted to get a small favor',
  'called in sick when I simply needed a break',
  'nodded during a meeting while understanding nothing',
  'forgotten why I entered a room',
  'used a word without being completely sure what it meant',
  'copied homework or an assignment at the last minute',
  'started working only when the deadline became frightening',
  'pretended to take notes while doodling',
  'celebrated when a meeting was cancelled',
  'made a typo in an important email',
  'blamed technology for a mistake that was mine',
  'taken credit for an idea the group developed together',
  'forgotten a colleague’s role after working with them for months',
  'eaten someone else’s labeled food',
  'worked from bed and called it a home office',
  'joined a call without realizing my microphone was on',
  'pretended to be busy to avoid being given another task',
  'looked for a new job during work hours',
  'sent an email and immediately noticed the attachment was missing',
  'used “per my last email” while feeling annoyed',
  'said “almost done” before actually starting',
  'booked a trip without a real plan',
  'missed a flight, train, or bus through my own fault',
  'packed far too much for a short trip',
  'worn the same travel outfit for several days',
  'gotten lost and refused to ask for directions',
  'tried local food without knowing what it was',
  'made friends with a stranger while travelling',
  'spent most of a trip taking photos',
  'returned from a holiday needing another holiday',
  'bought a souvenir at the airport because I forgot earlier',
  'pretended to understand directions and immediately got lost',
  'taken a photo of food and let it get cold',
  'ordered the same meal as someone else after judging their choice',
  'hidden snacks so I would not have to share',
  'eaten dessert before dinner and called it self-care',
  'claimed I was not hungry and then ate someone else’s food',
  'opened the fridge repeatedly hoping new food would appear',
  'followed a recipe and ignored half the instructions',
  'burned something and served it anyway',
  'used the five-second rule very generously',
  'pretended homemade food was mine when someone else prepared it',
  'ordered a familiar dish because the menu felt overwhelming',
  'eaten leftovers directly from the container',
  'planned an entire day around one meal',
  'lied about how spicy I could handle my food',
  'started a hobby and bought equipment before learning the basics',
  'quit a new routine within the first week',
  'watched tutorials for a skill I never attempted',
  'pretended to enjoy exercise while secretly counting every second',
  'become intensely competitive over a casual game',
  'cheered for a team only because everyone else was',
  'faked an injury to avoid an activity as a child',
  'kept a collection that made no sense to anyone else',
  'learned a strange fact solely to win an argument',
  'spent more time choosing entertainment than actually enjoying it',
  'rewatched a comfort show instead of trying something new',
  'cried over a fictional character',
  'pretended not to be scared during a horror film',
  'read reviews after buying something just to validate the purchase',
  'abandoned a book with fewer than twenty pages left',
  'memorized dialogue from a film without trying',
  'listened to one song repeatedly until I ruined it for myself',
  'judged someone’s music taste while hiding my own guilty pleasures',
  'started cleaning to avoid a more important task',
  'left laundry unfolded for several days',
  'hidden clutter before guests arrived',
  'bought storage containers instead of getting rid of anything',
  'watered a plant only after it looked dramatic',
  'named an object or plant in my home',
  'spoken to a pet as though it understood every word',
  'changed outfits several times before leaving home',
  'stayed in uncomfortable clothes because the outfit looked good',
  'owned something for years without using it once',
  'kept an empty box because it seemed too useful to throw away',
  'ignored an alarm and then blamed the alarm',
  'set several alarms with optimistic labels',
  'fallen asleep with the lights on and my phone in my hand',
  'woken from a nap unsure what day it was',
  'gone to bed early and scrolled for another two hours',
  'said “one more episode” more than once in the same night',
  'started telling a story and forgotten the point halfway through',
  'laughed so hard at the wrong moment that I could not explain myself',
  'pretended to recognize someone who clearly knew me',
  'introduced two people and forgotten one of their names',
  'entered a room confidently and realized it was the wrong place',
  'held a door open for someone who was still uncomfortably far away',
  'tripped in public and immediately looked around to see who noticed',
  'pretended a fall was an intentional movement',
  'answered a question that was directed at someone else',
  'mispronounced a word for years before being corrected',
  'used an expression incorrectly with complete confidence',
  'told the same story to the same person twice',
  'forgotten what I was saying in the middle of a sentence',
  'laughed during a serious moment because I was nervous',
  'practiced saying a name before calling someone',
  'avoided using someone’s name because I was unsure how to pronounce it',
  'pretended to read something because everyone else was reading it',
  'joined a queue without knowing what it was for',
  'taken free samples more than once while hoping not to be recognized',
  'pretended to browse while waiting for someone in a shop',
  'left an item at the checkout after seeing the price',
  'bought something I did not need because it was on sale',
  'kept a receipt for months and lost it when I actually needed it',
  'carried a reusable bag and still forgotten to use it',
  'ordered something online while half asleep',
  'forgotten about a subscription until I was charged again',
  'accepted terms and conditions without reading a single line',
  'used the same password for more accounts than I should admit',
  'ignored a software update until it became unavoidable',
  'closed a warning message without reading it',
  'opened too many browser tabs and refused to close any',
  'taken a screenshot instead of writing something down',
  'kept a screenshot so long that I forgot why I took it',
  'used a calculator for arithmetic I could probably do myself',
  'asked the internet a question I already knew the answer to',
  'checked the weather after already stepping outside',
  'looked at a clock and immediately forgotten the time',
  'walked somewhere while wearing headphones with no audio playing',
  'pretended not to hear someone calling my name',
  'said goodbye and then walked in the same direction as the other person',
]

/** Relationship and friendship behaviours for Red Flag / Green Flag voting. */
export const FLAG_SCENARIO_SUPPLEMENT = [
  'They are kind to you but rude to service workers.',
  'They always arrive early and become irritated when others are late.',
  'They have a close friendship with an ex and are completely open about it.',
  'They never post you online but introduce you proudly to everyone in person.',
  'They remember tiny details from your stories months later.',
  'They need several hours alone after every disagreement.',
  'They share every relationship problem with their best friend.',
  'They dislike texting but make time for thoughtful phone calls.',
  'They apologize quickly but repeat the same behavior.',
  'They ask before sharing photos of you.',
  'They are extremely competitive during harmless games.',
  'They still use a dating app because they “forgot to delete it.”',
  'They keep every gift an ex ever gave them.',
  'They encourage your goals even when those goals require time apart.',
  'They expect to know your phone password but will not share theirs.',
  'They cancel plans often but always reschedule immediately.',
  'They refuse to discuss money under any circumstances.',
  'They are affectionate in private but distant around friends.',
  'They have no close friendships older than one year.',
  'They defend you publicly and challenge you privately.',
  'They turn every disagreement into a joke.',
  'They need constant reassurance that you still like them.',
  'They maintain a detailed five-year plan for the relationship.',
  'They ask for space clearly instead of disappearing.',
  'They compare your relationship with couples online.',
  'They are generous with gifts but rarely present emotionally.',
  'They remember birthdays but forget everyday promises.',
  'They dislike all of your closest friends.',
  'They are willing to attend events that matter to you even when uninterested.',
  'They insist every expense must be split exactly in half.',
  'They never raise their voice, but become cold and silent when upset.',
  'They ask their parents before making major decisions.',
  'They regularly compliment strangers in front of you.',
  'They have a private social-media account you cannot follow.',
  'They want to spend nearly all free time together.',
  'They can admit when they do not know something.',
  'They bring up old mistakes during new arguments.',
  'They have different political beliefs but discuss them respectfully.',
  'They are deeply ambitious and frequently unavailable.',
  'They do not celebrate anniversaries but create meaningful surprises randomly.',
  'They avoid saying “I love you” but consistently show care through actions.',
  'They want separate bedrooms even in a committed relationship.',
  'They insist on sharing location at all times.',
  'They delete messages from people they think you would worry about.',
  'They are still financially supporting a former partner.',
  'They tell small lies to avoid unnecessary conflict.',
  'They correct your grammar during serious conversations.',
  'They are loved by animals but disliked by most people.',
  'They cannot cook but happily clean everything afterward.',
  'They expect immediate replies while taking hours to respond themselves.',
  'They speak positively about most of their former partners.',
  'They never speak positively about any former partner.',
  'They make major purchases without discussing them first.',
  'They keep a written list of relationship boundaries.',
  'They need to win every debate, even about trivial things.',
  'They actively work on themselves in therapy but use therapy language in arguments.',
  'They are extremely close to their family and expect you to join everything.',
  'They have little contact with family but strong chosen-family relationships.',
  'They dislike public affection but initiate plenty of affection at home.',
  'They borrow your belongings and always return them cleaner than before.',
  'They organize your things without asking.',
  'They surprise you with plans instead of checking your schedule.',
  'They ask direct questions whenever they feel insecure.',
  'They test your loyalty by creating fake situations.',
  'They prioritize sleep and will end any conversation at bedtime.',
  'They keep a strict budget and question spontaneous spending.',
  'They are friends with people whose values they disagree with.',
  'They refuse to gossip about anyone, including people who hurt them.',
  'They share private jokes from your relationship with others.',
  'They want children someday but have no preferred timeline.',
  'They are unsure about marriage but certain about long-term commitment.',
  'They dislike your hobbies but make room for you to enjoy them.',
  'They become quiet around conflict but return ready to talk later.',
  'They ask for advice and then consistently ignore it.',
  'They are excellent at grand gestures and poor at daily communication.',
  'They are terrible at gifts but remember exactly how you take your coffee.',
  'They refuse to lend money to friends or family.',
  'They often lend money and rarely ask to be repaid.',
  'They keep their phone face down during every conversation.',
  'They put their phone away completely when spending time with you.',
  'They need a detailed reason whenever you say no.',
  'They respect a no immediately, even when disappointed.',
  'They want joint accounts but also support separate personal accounts.',
  'They never feel jealous and do not understand when you do.',
  'They enjoy flirting socially but say it means nothing.',
  'They ask permission before venting about a difficult day.',
  'They interrupt often because they are excited, then apologize.',
  'They never interrupt but sometimes seem emotionally absent.',
  'They want to resolve every disagreement before sleeping.',
  'They prefer to pause difficult conversations until the next day.',
  'They carefully plan dates but expect you to plan every holiday.',
  'They keep separate friend groups and rarely mix them.',
  'They have many friends but no single best friend.',
  'They need your opinion before choosing almost anything.',
  'They encourage you to make decisions independently.',
  'They find it difficult to accept compliments.',
  'They are friendly with everyone but private about their emotions.',
  'They expect you to attend every family celebration.',
  'They will leave an event early with you whenever you feel uncomfortable.',
  'They forgive quickly but take a long time to trust again.',
  'They remember every detail of arguments but forget positive moments.',
  'They ask how they can support you instead of assuming.',
  'They make jokes about your insecurities in front of friends.',
  'They celebrate your success without making it about themselves.',
  'They expect access to every part of your past.',
  'They are curious about your culture and willing to learn respectfully.',
  'They refuse to try any food they have not eaten before.',
  'They are spontaneous with plans but reliable with commitments.',
  'They say yes to plans and cancel when something better appears.',
  'They communicate boundaries clearly but enforce them rigidly.',
  'They are close friends with someone who openly dislikes you.',
  'They volunteer regularly but never mention it online.',
  'They post every charitable act they perform.',
  'They expect gifts to match exactly what they spent.',
  'They keep notes about things you mention wanting.',
  'They dislike surprises and want to approve every plan.',
  'They cannot remember names but never forget a face.',
  'They ask for feedback and receive it without becoming defensive.',
  'They criticize themselves whenever you raise a concern.',
  'They avoid confrontation with others but argue freely with you.',
  'They are honest even when honesty makes them look bad.',
  'They share good news with you before anyone else.',
  'They share your private news before you are ready.',
  'They dislike lending possessions but are generous with their time.',
  'They always offer solutions when you mainly want empathy.',
  'They can sit comfortably with you in silence.',
  'They fill every silence because quiet makes them nervous.',
  'They have a strict morning routine and expect you to follow it.',
  'They make friends everywhere and invite strangers into plans.',
  'They never make the first move after a disagreement.',
  'They apologize through actions but rarely use the words.',
  'They say the right words but make no practical changes.',
  'They enjoy debating sensitive topics at social gatherings.',
  'They leave parties without saying goodbye to anyone.',
  'They always make sure everyone gets home safely.',
  'They expect you to choose sides in their friendships.',
  'They remain neutral when someone treats you unfairly.',
  'They can laugh at themselves when they make a mistake.',
  'They tease constantly but become hurt when teased back.',
  'They protect weekends from work except during emergencies.',
  'They answer work messages throughout every date.',
  'They have a different password for every account and a detailed emergency plan.',
  'They keep all important documents in one chaotic drawer.',
  'They plan thoughtful low-cost dates instead of expensive ones.',
  'They expect expensive gestures on every special occasion.',
  'They ask your friends for advice when planning surprises.',
  'They tell your friends details about your disagreements.',
  'They make room for your emotions without trying to rush them.',
  'They need you to become cheerful whenever they feel uncomfortable.',
  'They are willing to change their mind when presented with new information.',
]
