import { WE_JUST_MET_SUPPLEMENTAL } from './weJustMetSupplemental'

export type WeJustMetCategory = 'easy' | 'personality' | 'stories' | 'dating' | 'online' | 'fun'

export const WE_JUST_MET_CATEGORIES: ReadonlyArray<{ id: WeJustMetCategory; label: string; description: string; color: string }> = [
  { id: 'easy', label: 'Easy Start', description: 'Light questions to settle in', color: '#ff7a16' },
  { id: 'personality', label: 'Your World', description: 'Habits, values, and personality', color: '#ef5f83' },
  { id: 'stories', label: 'Good Stories', description: 'Memories worth sharing', color: '#ffd166' },
  { id: 'dating', label: 'Dating Energy', description: 'Chemistry without the pressure', color: '#9dcc34' },
  { id: 'online', label: 'From The Chat', description: 'Great for people meeting online', color: '#59b7f2' },
  { id: 'fun', label: 'Just For Fun', description: 'Playful and unexpected', color: '#a982e8' },
]

export const WE_JUST_MET_PROMPTS: Record<WeJustMetCategory, readonly string[]> = {
  easy: [
    'What is one small thing that made you smile this week?',
    'What is your ideal way to spend a free afternoon?',
    'What food could you happily eat every week?',
    'Are you naturally early, exactly on time, or fashionably late?',
    'What song have you had on repeat lately?',
    'What is your go-to comfort show or movie?',
    'Do you prefer quiet weekends or packed plans?',
    'What is one place in your city you always recommend?',
    'What is your usual first order at a café?',
    'What is something you are looking forward to right now?',
    'Which season feels most like you?',
    'What does a genuinely good day look like for you?',
    ...WE_JUST_MET_SUPPLEMENTAL.easy,
  ],
  personality: [
    'What is something people often misunderstand about you?',
    'What quality do you appreciate quickly in another person?',
    'What helps you feel comfortable around someone new?',
    'Are you more likely to plan everything or figure it out as you go?',
    'What is one boundary you have learned to value?',
    'When do you feel most like yourself?',
    'What kind of compliment stays with you?',
    'What is something you are quietly proud of?',
    'Do you recharge best alone or around people you like?',
    'What makes you feel genuinely listened to?',
    'What is a value you would never want to lose?',
    'What is one habit you are trying to build?',
    ...WE_JUST_MET_SUPPLEMENTAL.personality,
  ],
  stories: [
    'What is a childhood memory that still makes you laugh?',
    'What is the most spontaneous thing you have ever done?',
    'Tell the story of a trip you still think about.',
    'What is the best surprise anyone has given you?',
    'What is a harmless mistake that became a great story?',
    'Who influenced you more than they probably realise?',
    'What is a tradition you would like to keep forever?',
    'What is the bravest decision you have made so far?',
    'What is a celebration that did not go as planned but became a good story?',
    'What is your favourite memory involving food?',
    'What is a compliment you still remember?',
    'What is the funniest misunderstanding you have been part of?',
    ...WE_JUST_MET_SUPPLEMENTAL.stories,
  ],
  dating: [
    'What makes a first date feel easy rather than awkward?',
    'What is a green flag you notice early?',
    'What does thoughtful effort look like to you?',
    'Do you prefer planned dates or spontaneous ones?',
    'What helps you know that you can trust someone?',
    'How do you usually show someone that you like them?',
    'What kind of communication feels best to you?',
    'What would make an ordinary date memorable?',
    'What does taking things at a good pace mean to you?',
    'What is a relationship lesson you are glad you learned?',
    'What makes you excited to see someone again?',
    'What is one thing you hope a partner understands about you?',
    ...WE_JUST_MET_SUPPLEMENTAL.dating,
  ],
  online: [
    'What made you want to keep this conversation going?',
    'What is easier for you to say by text than in person?',
    'What part of your everyday life would you like to show me?',
    'What would our ideal first in-person hangout look like?',
    'What is your favourite way to stay connected from a distance?',
    'What is one thing your profile does not tell people about you?',
    'What kind of message instantly improves your day?',
    'Would you rather have a long call or exchange voice notes all day?',
    'What is something you want us to experience together offline?',
    'What helps an online connection feel real to you?',
    'What is the funniest thing that has happened during a video call?',
    'What question have you wanted to ask me but have not yet?',
    ...WE_JUST_MET_SUPPLEMENTAL.online,
  ],
  fun: [
    'If your personality were a drink, what would it be?',
    'What very ordinary thing are you strangely competitive about?',
    'If we had to start a tiny business together, what would we sell?',
    'What is your most defendable unpopular opinion?',
    'Which fictional world would you visit for one weekend?',
    'What would your warning label say?',
    'If today had a soundtrack, what song would open it?',
    'What silly talent would you bring to a talent show?',
    'If we missed a flight together, who would handle it better?',
    'What is a ridiculous purchase you do not regret?',
    'Which three snacks belong in the perfect movie-night lineup?',
    'What harmless conspiracy about yourself could your friends invent?',
    ...WE_JUST_MET_SUPPLEMENTAL.fun,
  ],
}

export const WE_JUST_MET_DECK = Array.from(new Set(Object.values(WE_JUST_MET_PROMPTS).flat()))
