export const WE_JUST_MET_SUPPLEMENTAL = {
  easy: [
    'What is the best thing you have eaten recently?',
    'Which app do you probably use more than you should?',
    'What is your favourite way to start a morning?',
    'What is one thing you always keep in your bag?',
    'Which holiday do you enjoy most?',
    'What is your favourite thing about where you grew up?',
    'Would you choose the beach, the mountains, or a busy city?',
    'What is the last thing that made you laugh out loud?',
    'Which meal of the day do you enjoy most?',
    'What is your favourite way to spend a rainy day?',
    'What everyday task do you secretly enjoy?',
    'What is one thing you never leave home without?',
    'Which smell instantly puts you in a good mood?',
    'What is your favourite kind of celebration?',
    'Do you prefer phone calls, texts, or voice notes?',
    'What is the nicest part of your usual routine?',
    'What is a simple pleasure you never get tired of?',
    'Which snack disappears fastest around you?',
    'What is your favourite time of day?',
    'What is the last photo you took?',
    'Do you enjoy surprises or prefer knowing the plan?',
    'What is your favourite way to move your body?',
    'What is one local place you still want to visit?',
    'Which household chore would you happily trade away?',
    'What is your ideal breakfast?',
    'What is one thing that makes a place feel like home?',
    'Do you prefer small gatherings or big events?',
    'What is the best gift you have received lately?',
    'What is your favourite way to treat yourself?',
    'Which day of the week has the best energy?',
    'What is something you could talk about for ten minutes without preparation?',
    'What is your favourite thing to do after a long day?',
    'Which sound do you find especially calming?',
    'What is a tiny luxury you appreciate?',
    'What is your usual karaoke choice?',
    'What kind of weather improves your mood?',
    'What is the last new thing you tried?',
    'What would make this week feel like a win?',
  ],
  personality: [
    'What brings out your playful side?',
    'What do your closest friends rely on you for?',
    'What do you need before making a big decision?',
    'What kind of environment helps you do your best thinking?',
    'What is one everyday opinion your friends know you will defend?',
    'How do you usually respond when plans suddenly change?',
    'What kind of honesty do you value most?',
    'What makes you feel appreciated?',
    'What is a trait you inherited from your family?',
    'What is a trait you deliberately developed for yourself?',
    'What does confidence look like in your everyday life?',
    'What tends to make you overthink?',
    'What helps you recover after a difficult day?',
    'What is something you take seriously that others may not?',
    'What part of your personality took time to accept?',
    'What kind of person makes you feel at ease?',
    'What do you wish people asked you about more often?',
    'What is one thing you are learning to be patient with?',
    'What does loyalty mean to you?',
    'How do you prefer to receive difficult feedback?',
    'What motivates you when excitement wears off?',
    'What does independence mean to you?',
    'Which quality in yourself are you protecting as you grow?',
    'What usually tells you that you need rest?',
    'What kind of support is most useful when you feel stressed?',
    'What makes you feel safe enough to be silly?',
    'What personal rule has served you well?',
    'How do you know when you genuinely like someone?',
    'What is one thing you do differently from most people you know?',
    'What are you more sensitive to than people might expect?',
    'What does being dependable mean to you?',
    'What is one way you have become more yourself over time?',
    'What is something you are comfortable saying no to now?',
    'When do you find it easiest to be open?',
    'What makes an apology feel sincere to you?',
    'What is one belief that guides your choices?',
    'What do you want more room for in your life?',
    'What kind of energy do you hope you bring into a room?',
  ],
  stories: [
    'What is the first concert or live event you remember attending?',
    'Tell me about a teacher who left an impression on you.',
    'What is a family story you have heard many times?',
    'When have you felt especially lucky?',
    'What is a moment when a stranger was unexpectedly kind to you?',
    'What is the best celebration you have ever attended?',
    'Tell me about a time you surprised yourself.',
    'What is a place that felt completely different from what you expected?',
    'What is a childhood phase your family still teases you about?',
    'What is the most useful thing someone taught you outside school?',
    'Tell me about a friendship that shaped you.',
    'What is a time you laughed when you were not supposed to?',
    'What is the most memorable meal you have shared with someone?',
    'What is a goal you once thought was impossible?',
    'Tell me about a day that went better than planned.',
    'What is a small decision that changed a lot for you?',
    'What is your favourite story behind something you own?',
    'Tell me about a time you took a chance on yourself.',
    'What is a memory connected to your favourite song?',
    'What is the nicest thing a friend has done for you?',
    'What is a childhood game you took very seriously?',
    'Tell me about a journey that did not go according to plan.',
    'What is a moment you wish you could watch again?',
    'What is an achievement that mattered more than it looked from outside?',
    'Who gave you advice that finally made sense later?',
    'What is a moment when you felt completely understood?',
    'What is the funniest excuse you have ever used?',
    'Tell me about your first real responsibility.',
    'What is a tradition you created for yourself?',
    'What is the best coincidence you have experienced?',
    'Tell me about a time you changed someone else’s mind.',
    'What is a memory that always improves your mood?',
    'What is a risk you are glad you took?',
    'Tell me about a time you had to improvise.',
    'What is your favourite memory from the last year?',
    'What is a lesson you learned from an unexpected person?',
    'Tell me about a moment that made you feel grown up.',
    'What experience would you happily relive for one day?',
  ],
  dating: [
    'What makes conversation flow naturally for you?',
    'What does consistency look like when you are getting to know someone?',
    'How important is humour in a connection?',
    'What makes you feel chosen without feeling pressured?',
    'What is your favourite kind of low-key date?',
    'What helps you open up at your own pace?',
    'What does emotional maturity look like to you?',
    'How do you like someone to handle a misunderstanding?',
    'What makes flirting feel fun rather than awkward?',
    'What kind of affection comes most naturally to you?',
    'What is one thing you value more now than you did in earlier relationships?',
    'What does a healthy amount of space look like to you?',
    'How do you prefer to make plans with someone you are dating?',
    'What is a sign that two people communicate well?',
    'What makes you feel respected on a date?',
    'What is one expectation worth discussing early?',
    'What makes an invitation feel thoughtful?',
    'How do you like to celebrate relationship milestones?',
    'What is your idea of quality time?',
    'What makes someone easy to be honest with?',
    'What does being intentional in dating mean to you?',
    'How do you balance romance with friendship in a relationship?',
    'What is something small that feels romantic to you?',
    'What helps you stay curious about another person?',
    'How do you know when a connection deserves more time?',
    'What makes a disagreement feel productive instead of threatening?',
    'What kind of reassurance matters to you?',
    'What do you hope dating adds to your life?',
    'What is a dating habit you would like to leave behind?',
    'What is a dating habit you want to carry forward?',
    'How do you like to repair things after hurting someone’s feelings?',
    'What does partnership mean before a relationship becomes serious?',
    'What is one subject you believe couples should be able to discuss openly?',
    'What makes you feel emotionally close to someone?',
    'What is your favourite way to show care?',
    'How do you prefer someone to express interest?',
    'What would make you feel proud of the relationship you are building?',
    'What pace allows attraction and trust to grow together?',
  ],
  online: [
    'What was your honest first impression of my profile?',
    'What topic makes you send the longest messages?',
    'What makes you feel comfortable moving from text to a call?',
    'Which emoji do you use most accurately?',
    'What is your favourite kind of voice note to receive?',
    'How much texting feels natural to you during a busy day?',
    'What makes an online conversation feel effortless?',
    'What is one thing you prefer discussing face to face?',
    'What would make a virtual date genuinely fun for you?',
    'What part of your personality comes across better in person?',
    'What part of your personality comes across best by text?',
    'What is a photo you would send to describe your day?',
    'What is one question profiles should answer but rarely do?',
    'How do you tell when someone online is being authentic?',
    'What kind of check-in message feels thoughtful?',
    'What is your funniest autocorrect or mistyped-message story?',
    'What would you want to know before planning a first meeting?',
    'What song would you add to a shared playlist for us?',
    'What is one everyday moment you enjoy sharing with someone?',
    'Do you prefer quick replies or thoughtful replies later?',
    'What makes distance easier to manage?',
    'What online habit are you trying to improve?',
    'What would our shared group-chat name be?',
    'Which part of your city would you show me first?',
    'What is something you noticed about the way we talk?',
    'What helps build trust before meeting in person?',
    'What would make you excited for our next call?',
    'What is a digital boundary that matters to you?',
    'What is one thing you never want misunderstood over text?',
    'What kind of conversation deserves a phone call?',
    'What is the best link, meme, or video someone could send you?',
    'How do you like to end a really good call?',
    'What would make an online connection worth the effort?',
    'What is one thing we could do together while apart?',
    'How do you show interest when you cannot be physically present?',
    'What does reliable communication look like online?',
    'What are you most curious to learn about me in person?',
    'What would help this connection keep feeling natural?',
  ],
  fun: [
    'If your week were a film, what genre would it be?',
    'What would you name a boat if you owned one?',
    'Which food opinion could get you removed from a group chat?',
    'If you could master one dance overnight, which would you choose?',
    'What is your funniest completely irrational fear?',
    'If you had a personal mascot, what would it be?',
    'What game-show challenge would you definitely win?',
    'Which celebrity would play you in a very inaccurate film?',
    'If you could add one harmless law, what would it require?',
    'What is the weirdest useful fact you know?',
    'If your phone could expose one habit, what would it reveal?',
    'What would your signature dish be on a cooking show?',
    'If we swapped lives for a day, what would surprise me most?',
    'What is a trend you would happily bring back?',
    'What is your most dramatic reaction to a minor inconvenience?',
    'If animals could talk, which would be the rudest?',
    'What would your entrance music be?',
    'Which fictional character would be a terrible roommate?',
    'What would you do first with an extra free day every week?',
    'If you opened a themed restaurant, what would the theme be?',
    'What is the funniest name for a pet you can invent?',
    'Which ordinary activity deserves to be an Olympic event?',
    'If your laugh had a name, what would it be called?',
    'What would you put in a time capsule from today?',
    'Which outfit from your past should never return?',
    'If you could ban one conversational phrase, what would it be?',
    'What is your strongest opinion about breakfast?',
    'Which three people would make the most chaotic dinner party?',
    'If you had to teach a class with no preparation, what would you teach?',
    'What is your favourite harmless way to waste time?',
    'If we formed a two-person band, what would we call it?',
    'Which small problem would you solve with a ridiculous invention?',
    'What is the funniest thing you believed as a child?',
    'If your life had chapter titles, what would this chapter be called?',
    'Which competition would reveal your most competitive side?',
    'What is the most unnecessary thing you are good at?',
    'If you could instantly become a regular anywhere, where would it be?',
    'What challenge would make a surprisingly good second date?',
  ],
} as const
