import type { MultiplayerGameId } from '../multiplayer/types'

export interface PassAndPlayGameDefinition {
  gameId: MultiplayerGameId
  initialStep: string
  playableSteps: readonly string[]
  completionSteps: readonly string[]
  playerKey?: string
  totalKey?: string
  deckKey?: string
  cardKey?: string
  skippedKey?: string
  customCardsKey?: string
  optionSteps?: Readonly<Record<string, { optionType: string; stateKey: string }>>
  cardSourceReliable: boolean
  completionReason: string
}

export const PASS_AND_PLAY_GAMES: Readonly<Record<string, PassAndPlayGameDefinition>> = {
  'truth-or-dare': { gameId: 'truth-or-dare', initialStep: 'ageGate', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', cardKey: 'cardIndex', skippedKey: 'skipCount', cardSourceReliable: true, completionReason: 'deck_finished' },
  'spicy-starters': { gameId: 'spicy-starters', initialStep: 'ageGate', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', cardKey: 'cardIndex', skippedKey: 'skipCount', optionSteps: { howSpicy: { optionType: 'spice_level', stateKey: 'spiceLevel' } }, cardSourceReliable: true, completionReason: 'deck_finished' },
  'never-have-i-ever': { gameId: 'never-have-i-ever', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: ['done'], playerKey: 'players', deckKey: 'prompts', cardKey: 'cardIdx', optionSteps: { modeSelect: { optionType: 'mode', stateKey: 'mode' } }, cardSourceReliable: true, completionReason: 'deck_finished' },
  'late-night-talks': { gameId: 'late-night-talks', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'cardIndex', skippedKey: 'skipCount', cardSourceReliable: true, completionReason: 'deck_finished' },
  'dinner-table': { gameId: 'dinner-table', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'cardIndex', skippedKey: 'skipCount', cardSourceReliable: true, completionReason: 'deck_finished' },
  icebreaker: { gameId: 'icebreaker', initialStep: 'playMode', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'gameCardIndex', skippedKey: 'skipCount', optionSteps: { playMode: { optionType: 'mode', stateKey: 'mode' } }, cardSourceReliable: true, completionReason: 'deck_finished' },
  'everyday-conversations': { gameId: 'everyday-conversation', initialStep: 'theme', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { theme: { optionType: 'theme', stateKey: 'theme' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'lets-reconnect': { gameId: 'reconnect', initialStep: 'relationship', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { relationship: { optionType: 'relationship', stateKey: 'relationship' }, depth: { optionType: 'depth', stateKey: 'depth' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'red-flag-green-flag': { gameId: 'red-flag-green-flag', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'scenarios', cardKey: 'gameCardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', cardSourceReliable: false, completionReason: 'deck_finished' },
  charades: { gameId: 'charades', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: ['done'], playerKey: 'players', totalKey: 'deckSize', deckKey: 'deck', cardKey: 'cardIdx', customCardsKey: 'customCards', optionSteps: { categorySelect: { optionType: 'category', stateKey: 'selectedCategories' }, roundLength: { optionType: 'round_length', stateKey: 'roundLength' } }, cardSourceReliable: false, completionReason: 'rounds_finished' },
  wnrs: { gameId: 'strangers', initialStep: 'relationship', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'questions', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { relationship: { optionType: 'relationship', stateKey: 'relationship' }, journey: { optionType: 'journey', stateKey: 'journey' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'put-a-finger-down': { gameId: 'finger-down', initialStep: 'categories', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'prompts', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' }, fingers: { optionType: 'starting_fingers', stateKey: 'fingers' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'take-a-sip': { gameId: 'take-a-sip', initialStep: 'categories', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'prompts', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'sip-or-spill': { gameId: 'sip-or-spill', initialStep: 'categories', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'prompts', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'you-laugh': { gameId: 'you-laugh', initialStep: 'playerSetup', playableSteps: ['gameplay'], completionSteps: ['winner'], playerKey: 'players', deckKey: 'challenges', cardKey: 'challengeIdx', optionSteps: { roundLength: { optionType: 'round_length', stateKey: 'roundSeconds' }, livesSetup: { optionType: 'lives', stateKey: 'maxLives' } }, cardSourceReliable: true, completionReason: 'winner_declared' },
  'do-or-drink': { gameId: 'do-or-drink', initialStep: 'categories', playableSteps: ['game'], completionSteps: [], playerKey: 'players', totalKey: 'totalCards', deckKey: 'prompts', cardKey: 'cardIndex', skippedKey: 'skipCount', customCardsKey: 'customCards', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
  'two-truths-bluff': { gameId: 'two-truths-bluff', initialStep: 'playerSetup', playableSteps: ['write', 'handoff', 'guess', 'reveal'], completionSteps: ['done'], playerKey: 'players', cardKey: 'round', cardSourceReliable: false, completionReason: 'rounds_finished' },
  'most-likely-to': { gameId: 'most-likely-to', initialStep: 'playerSetup', playableSteps: ['vote', 'reveal'], completionSteps: ['done'], playerKey: 'players', totalKey: 'deckSize', deckKey: 'deck', cardKey: 'cardIndex', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: true, completionReason: 'deck_finished' },
  'choose-your-side': { gameId: 'choose-your-side', initialStep: 'playerSetup', playableSteps: ['vote', 'reveal'], completionSteps: ['done'], playerKey: 'players', totalKey: 'deckSize', deckKey: 'deck', cardKey: 'cardIndex', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: true, completionReason: 'deck_finished' },
  'who-said-that': { gameId: 'who-said-that', initialStep: 'playerSetup', playableSteps: ['answer', 'guess', 'reveal'], completionSteps: ['done'], playerKey: 'players', totalKey: 'totalCards', deckKey: 'deck', cardKey: 'round', customCardsKey: 'customCards', cardSourceReliable: false, completionReason: 'rounds_finished' },
  'we-just-met': { gameId: 'we-just-met', initialStep: 'playerSetup', playableSteps: ['game'], completionSteps: ['done'], playerKey: 'players', totalKey: 'deckSize', deckKey: 'deck', cardKey: 'cardIndex', skippedKey: 'skipped', customCardsKey: 'customCards', optionSteps: { categories: { optionType: 'category', stateKey: 'categories' } }, cardSourceReliable: false, completionReason: 'deck_finished' },
}
