export const CHARADES_TV_SHOWS: readonly string[] = [
  'I Love Lucy',
  'The Twilight Zone',
  'The Addams Family',
  'Bewitched',
  'Gilligan\'s Island',
  'The Flintstones',
  'The Jetsons',
  'Star Trek',
  'Mission: Impossible',
  'Columbo',
  'M*A*S*H',
  'Happy Days',
  'The Muppet Show',
  'Charlie\'s Angels',
  'The Love Boat',
  'Dallas',
  'Knight Rider',
  'The A-Team',
  'Cheers',
  'MacGyver',
  'Murder, She Wrote',
  'The Golden Girls',
  'Miami Vice',
  'Full House',
  'Baywatch',
  'Seinfeld',
  'Twin Peaks',
  'The Fresh Prince of Bel-Air',
  'The X-Files',
  'Frasier',
  'ER',
  'Buffy the Vampire Slayer',
  'Dawson\'s Creek',
  'Sex and the City',
  'The Sopranos',
  'Gilmore Girls',
  'Smallville',
  '24',
  'The Wire',
  'Lost',
  'Fawlty Towers',
  'Grey\'s Anatomy',
  'Prison Break',
  'Dexter',
  'Mad Men',
  'Gossip Girl',
  'Sons of Anarchy',
  'Glee',
  'The Walking Dead',
  'Downton Abbey',
  'Black Mirror',
  'Suits',
  'Homeland',
  'Scandal',
  'Vikings',
  'The Blacklist',
  'Outlander',
  'How to Get Away with Murder',
  'Better Call Saul',
  'Mr. Robot',
  'This Is Us',
  'Westworld',
  'The Handmaid\'s Tale',
  'Yellowstone',
  'The Mandalorian',
  'The Boys',
  'Euphoria',
  'The Morning Show',
  'Only Murders in the Building',
  'The Bear',
  'House of the Dragon',
  'The Last of Us',
  'Fallout',
  'Shōgun',
  'Severance',
  'The White Lotus',
  'Yellowjackets',
  'The Gilded Age',
  'Abbott Elementary',
  'Ghosts',
  'Hacks',
  'Ted Lasso',
  'Shrinking',
  'Happy Valley',
  'The Diplomat',
  'Slow Horses',
  'The Night Agent',
  '3 Body Problem',
  'The Penguin',
  'Agatha All Along',
  'The Pitt',
  'Andor',
  'A Different World',
  'The Wonder Years',
  'Living Single',
  'The Nanny',
  'Everybody Loves Raymond',
  'The King of Queens',
  'Malcolm in the Middle',
  'Scrubs',
  'Arrested Development',
  'Desperate Housewives',
  'How I Met Your Mother',
  '30 Rock',
  'The Big Bang Theory',
  'Parks and Recreation',
  'Modern Family',
  'Community',
  'New Girl',
  'Brooklyn Nine-Nine',
  'Schitt\'s Creek',
  'Jane the Virgin',
  'Crazy Ex-Girlfriend',
  'The Good Place',
  'Fleabag',
  'Atlanta',
  'Insecure',
  'Derry Girls',
  'Kim\'s Convenience',
  'Coronation Street',
  'Reservation Dogs',
  'What We Do in the Shadows',
  'Wednesday',
  'Bridgerton',
  'Emily in Paris',
  'Cobra Kai',
  'Curb Your Enthusiasm',
  'It\'s Always Sunny in Philadelphia',
  'Veep',
  'The Marvelous Mrs. Maisel',
  'Orange Is the New Black',
  'Russian Doll',
  'Dead to Me',
  'Grace and Frankie',
  'Unbreakable Kimmy Schmidt',
  'Broad City',
  'Superstore',
  'Black-ish',
  'Fresh Off the Boat',
  'The Good Doctor',
  'EastEnders',
  'Call the Midwife',
  'Sherlock',
  'NCIS',
  'Line of Duty',
  'Law & Order',
  'Lupin',
  'Fauda',
  'Monk',
  'Psych',
  'Tehran',
  'Delhi Crime',
  'The Family Man',
  'Panchayat',
  'Babylon Berlin',
  'Gomorrah',
  'Detectorists',
  'True Detective',
  'Mindhunter',
  'Ozark',
  'Elite',
  'The Umbrella Academy',
  'The Witcher',
  'Blood & Water',
  'The Sandman',
  'Good Omens',
  'Queen Sono',
  'An African City',
  'The Rings of Power',
  'Foundation',
  'Silo',
  'For All Mankind',
  'The Expanse',
  'Orphan Black',
  'Sense8',
  'Dark',
  'Alice in Borderland',
  'All of Us Are Dead',
  'Kingdom',
  'Extraordinary Attorney Woo',
  'Crash Landing on You',
  'Business Proposal',
  'Vincenzo',
  'The Glory',
  'Queen of Tears',
  'Moving',
  'Reply 1988',
  'Borgen',
  'Boys Over Flowers',
  'My Love from the Star',
  'Pachinko',
  'One Piece',
  'Dragon Ball Z',
  'Sailor Moon',
  'Naruto',
  'Demon Slayer',
  'Attack on Titan',
  'My Hero Academia',
  'Jujutsu Kaisen',
  'Death Note',
  'Fullmetal Alchemist: Brotherhood',
  'Cowboy Bebop',
  'Avatar: The Last Airbender',
  'The Legend of Korra',
  'Adventure Time',
  'Regular Show',
  'Steven Universe',
  'Gravity Falls',
  'Phineas and Ferb',
  'Kim Possible',
  'Teen Titans',
  'The Powerpuff Girls',
  'Dexter\'s Laboratory',
  'Courage the Cowardly Dog',
  'Johnny Bravo',
  'Rugrats',
  'Hey Arnold!',
  'The Fairly OddParents',
  'The Magic School Bus',
  'Arthur',
  'Bluey',
  'Peppa Pig',
  'PAW Patrol',
  'Blue\'s Clues',
  'Mister Rogers\' Neighborhood',
  'Barney & Friends',
  'The Wiggles',
  'LazyTown',
  'Bear in the Big Blue House',
  'Doc McStuffins',
  'PJ Masks',
  'Miraculous: Tales of Ladybug & Cat Noir',
  'Teenage Mutant Ninja Turtles',
  'The Transformers',
  'ThunderCats',
  'He-Man and the Masters of the Universe',
  'Doraemon',
  'The Looney Tunes Show',
  'Animaniacs',
  'Pinky and the Brain',
  'Bob\'s Burgers',
  'Futurama',
  'Family Guy',
  'South Park',
  'Rick and Morty',
  'BoJack Horseman',
  'Archer',
  'Invincible',
  'Love, Death & Robots',
  'RuPaul\'s Drag Race',
  'The Amazing Race',
  'The Bachelor',
  'Love Island',
  'The Great British Bake Off',
  'America\'s Got Talent',
  'Dancing with the Stars',
  'Project Runway',
  'Top Chef',
  'Shark Tank',
  'The Masked Singer',
  'Nailed It!',
  'Is It Cake?',
  'The Circle',
  'Love Is Blind',
  'Queer Eye',
  'The Traitors',
  'Taskmaster',
  'Neighbours',
  'MasterChef Australia',
  'The Block',
  'MythBusters',
  'Deadliest Catch',
  'Dirty Jobs',
  'American Ninja Warrior',
  'Wipeout',
  'Fear Factor',
  'Jeopardy!',
  'Wheel of Fortune',
  'Family Feud',
  'Who Wants to Be a Millionaire?',
  'The Price Is Right',
  'Deal or No Deal',
  'Planet Earth',
  'The Blue Planet',
  'Our Planet',
  'Cosmos: A Spacetime Odyssey',
  'The Last Dance',
  'Chef\'s Table',
  'Making a Murderer',
  'Tiger King',
  'Formula 1: Drive to Survive',
  'Welcome to Wrexham',
  'The Crocodile Hunter',
  'Top Gear',
  'The Grand Tour',
  'Antiques Roadshow',
  'The Graham Norton Show',
  'Strictly Come Dancing',
  'Saturday Night Live',
  'The Daily Show',
]
