export const CHARADES_MOVIES: readonly string[] = [
  'Citizen Kane',
  'Casablanca',
  'The Godfather',
  'Gone with the Wind',
  'Lawrence of Arabia',
  'The Wizard of Oz',
  "It's a Wonderful Life",
  'Singin’ in the Rain',
  'Rear Window',
  'Vertigo',
  'Psycho',
  'Roman Holiday',
  'Sunset Boulevard',
  'All About Eve',
  'On the Waterfront',
  'Some Like It Hot',
  'North by Northwest',
  'The Sound of Music',
  'Mary Poppins',
  'West Side Story',
  'My Fair Lady',
  'Breakfast at Tiffany’s',
  'The Great Escape',
  'The Graduate',
  'Cool Hand Luke',
  'Planet of the Apes',
  'The Producers',
  'Midnight Cowboy',
  'Butch Cassidy and the Sundance Kid',
  'The French Connection',
  'A Clockwork Orange',
  'The Last Picture Show',
  'The Exorcist',
  'Chinatown',
  'Young Frankenstein',
  'One Flew Over the Cuckoo’s Nest',
  'Taxi Driver',
  'Close Encounters of the Third Kind',
  'Saturday Night Fever',
  'Superman',
  'Alien',
  'Apocalypse Now',
  'The Blues Brothers',
  'Raging Bull',
  'Raiders of the Lost Ark',
  'Blade Runner',
  'Tootsie',
  'Scarface',
  'The Karate Kid',
  'Back to the Future',
  'The Color Purple',
  'Ferris Bueller’s Day Off',
  'Top Gun',
  'Dirty Dancing',
  'The Princess Bride',
  'Beetlejuice',
  'Who Framed Roger Rabbit',
  'Dead Poets Society',
  'When Harry Met Sally…',
  'Edward Scissorhands',
  'Goodfellas',
  'The Silence of the Lambs',
  'Beauty and the Beast',
  'A League of Their Own',
  'Groundhog Day',
  'Mrs. Doubtfire',
  'The Nightmare Before Christmas',
  'Schindler’s List',
  'Forrest Gump',
  'The Shawshank Redemption',
  'Clueless',
  'Apollo 13',
  'Braveheart',
  'Sense and Sensibility',
  'Atlantics',
  'Jerry Maguire',
  'Men in Black',
  'Good Will Hunting',
  'The Truman Show',
  'The Parent Trap',
  'Saving Private Ryan',
  'The Sixth Sense',
  'Notting Hill',
  'The Mummy',
  'The Green Mile',
  'Cast Away',
  'Crouching Tiger, Hidden Dragon',
  'Gladiator',
  'Legally Blonde',
  'Monsters, Inc.',
  'A Beautiful Mind',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Spirited Away',
  'Bend It Like Beckham',
  'Catch Me If You Can',
  'Chicago',
  'Lilo & Stitch',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'School of Rock',
  'Mean Girls',
  'The Incredibles',
  'Howl’s Moving Castle',
  'The Notebook',
  'Million Dollar Baby',
  'Charlie and the Chocolate Factory',
  'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  'The Devil Wears Prada',
  'Little Miss Sunshine',
  'The Pursuit of Happyness',
  'Sarafina!',
  'Enchanted',
  'Kung Fu Panda',
  'Slumdog Millionaire',
  'WALL-E',
  'The Dark Knight',
  'Wadjda',
  'Coraline',
  'Fantastic Mr. Fox',
  'The Blind Side',
  'How to Train Your Dragon',
  'The King’s Speech',
  'Black Swan',
  'The Help',
  'The Artist',
  'Hugo',
  'Life of Pi',
  'The Avengers',
  'The Hunger Games',
  'Silver Linings Playbook',
  'Gravity',
  'The Great Gatsby',
  'The Lego Movie',
  'Big Hero 6',
  'Guardians of the Galaxy',
  'Interstellar',
  'Paddington',
  'The Martian',
  'Inside Out',
  'Mad Max: Fury Road',
  'The Revenant',
  'The Jungle Book',
  'Hidden Figures',
  'La La Land',
  'Zootopia',
  'Coco',
  'Get Out',
  'The Greatest Showman',
  'Wonder Woman',
  'Black Panther',
  'Persepolis',
  'Crazy Rich Asians',
  'A Quiet Place',
  'Roma',
  'Green Book',
  'Knives Out',
  'Jojo Rabbit',
  'Little Women',
  'Parasite',
  'Ford v Ferrari',
  'Dune',
  'Encanto',
  'Everything Everywhere All at Once',
  'The Fabelmans',
  'Glass Onion',
  'The Banshees of Inisherin',
  'Barbie',
  'Oppenheimer',
  'The Holdovers',
  'Past Lives',
  'The Boy and the Heron',
  'Anatomy of a Fall',
  'The Wild Robot',
  'Wicked',
  'Flow',
  'The Iron Giant',
  'Chicken Run',
  'The Emperor’s New Groove',
  'Ice Age',
  'The Polar Express',
  'Wallace & Gromit: The Curse of the Were-Rabbit',
  'Happy Feet',
  'The Princess and the Frog',
  'Tangled',
  'The Secret World of Arrietty',
  'Wreck-It Ralph',
  'The Croods',
  'The Book of Life',
  'Shaun the Sheep Movie',
  'Kubo and the Two Strings',
  'Sing',
  'Ferdinand',
  'Onward',
  'Luca',
  'Turning Red',
  'Puss in Boots: The Last Wish',
  'The Sea Beast',
  'Nimona',
  'Robot Dreams',
  'The Red Balloon',
  'The 400 Blows',
  'Breathless',
  'The Umbrellas of Cherbourg',
  'PlayTime',
  'The Battle of Algiers',
  'Cinema Paradiso',
  'Life Is Beautiful',
  'Amélie',
  'The Intouchables',
  'Bicycle Thieves',
  'La Dolce Vita',
  '8½',
  'The Good, the Bad and the Ugly',
  'The Conformist',
  'A Separation',
  'Children of Heaven',
  'Pan’s Labyrinth',
  'The Secret in Their Eyes',
  'Wild Tales',
  'Central Station',
  'City of God',
  'The Motorcycle Diaries',
  'Y Tu Mamá También',
  'Like Water for Chocolate',
  'Seven Samurai',
  'Rashomon',
  'Tokyo Story',
  'Ikiru',
  'Godzilla Minus One',
  'My Neighbor Totoro',
  'Princess Mononoke',
  'Kiki’s Delivery Service',
  'Akira',
  'Shoplifters',
  'Drive My Car',
  'Oldboy',
  'The Host',
  'Train to Busan',
  'Minari',
  'In the Mood for Love',
  'Chungking Express',
  'Infernal Affairs',
  'Shaolin Soccer',
  'Hero',
  'House of Flying Daggers',
  'Farewell My Concubine',
  'Raise the Red Lantern',
  'The Lunchbox',
  'Lagaan',
  '3 Idiots',
  'Dangal',
  'RRR',
  'Pather Panchali',
  'Monsoon Wedding',
  'Dilwale Dulhania Le Jayenge',
  'Baahubali: The Beginning',
  'The Raid',
  'Ong-Bak',
  'The Gods Must Be Crazy',
  'Tsotsi',
  'District 9',
  'The Wedding Party',
  'Lionheart',
  'Rafiki',
  'Queen of Katwe',
  'The Boy Who Harnessed the Wind',
  'Whale Rider',
  'The Piano',
  'Rabbit-Proof Fence',
  'The Castle',
  'Strictly Ballroom',
  'Hunt for the Wilderpeople',
  'The Adventures of Priscilla, Queen of the Desert',
  'Four Weddings and a Funeral',
  'Billy Elliot',
  'The Full Monty',
  'Babe',
  'Nanny McPhee',
  'The Railway Children',
  'Chariots of Fire',
  'Gandhi',
  'The Bridge on the River Kwai',
  'Doctor Zhivago',
  'Ben-Hur',
  'Spartacus',
  'The Last Emperor',
  'The Ten Commandments',
  'The Magnificent Seven',
  'The Great Dictator',
  'Modern Times',
  'City Lights',
  'The General',
  'Safety Last!',
  'Nosferatu',
  'The Cabinet of Dr. Caligari',
  'Metropolis',
  'The Invisible Man',
  'The Bride of Frankenstein',
  'The Day the Earth Stood Still',
  'Once',
  'The Commitments',
] as const
