export const CHARADES_APPS: readonly string[] = [
  'Messenger',
  'WeChat',
  'Signal',
  'Viber',
  'LINE',
  'KakaoTalk',
  'GroupMe',
  'TextNow',
  'Marco Polo',
  'Zello',
  'Nextdoor',
  'Bumble',
  'Hinge',
  'Badoo',
  'Meetup',
  'BeReal',
  'Threads',
  'Tumblr',
  'Mastodon',
  'Bluesky',
  'Clubhouse',
  'Quora',
  'Weibo',
  'Lemon8',
  'Likee',
  'Bigo Live',
  'Flickr',
  'VSCO',
  'Imgur',
  'Substack',
  'Patreon',
  'Letterboxd',
  'Goodreads',
  'Indeed',
  'Yelp',
  'Foursquare',
  'Google Chrome',
  'Firefox',
  'Microsoft Edge',
  'Safari',
  'Brave',
  'Google Drive',
  'Dropbox',
  'OneDrive',
  'Google Docs',
  'Google Sheets',
  'Google Slides',
  'Microsoft Word',
  'Microsoft Excel',
  'Microsoft PowerPoint',
  'Microsoft Outlook',
  'Microsoft Teams',
  'Google Meet',
  'Google Calendar',
  'Google Keep',
  'Notion',
  'Evernote',
  'OneNote',
  'Todoist',
  'Trello',
  'Asana',
  'Monday.com',
  'ClickUp',
  'Slack',
  'Airtable',
  'Miro',
  'Figma',
  'Canva',
  'Adobe Acrobat',
  'Adobe Scan',
  'DocuSign',
  'Grammarly',
  'Calendly',
  'WeTransfer',
  'Box',
  'Zapier',
  'IFTTT',
  'LastPass',
  '1Password',
  'NordVPN',
  'TeamViewer',
  'Pocket',
  'Instapaper',
  'Feedly',
  'Flipboard',
  'Google News',
  'Apple News',
  'The New York Times',
  'Google Photos',
  'iCloud',
  'Proton Mail',
  'Yahoo Mail',
  'AOL Mail',
  'SoundCloud',
  'Apple Music',
  'Amazon Music',
  'YouTube Music',
  'Pandora',
  'Tidal',
  'Deezer',
  'iHeartRadio',
  'TuneIn Radio',
  'Audible',
  'Pocket Casts',
  'Apple Podcasts',
  'Amazon Prime Video',
  'Disney+',
  'Hulu',
  'Max',
  'Redfin',
  'Paramount+',
  'Apple TV',
  'Tubi',
  'Pluto TV',
  'Crunchyroll',
  'Vimeo',
  'Twitch',
  'Roku',
  'Plex',
  'F1 TV',
  'ESPN',
  'DAZN',
  'NBA App',
  'NFL App',
  'MLB',
  'Strava',
  'Peloton',
  'Fitbit',
  'MyFitnessPal',
  'Nike Run Club',
  'adidas Running',
  'AllTrails',
  'Calm',
  'Headspace',
  'BetterHelp',
  'Flo',
  'Clue',
  'Sleep Cycle',
  'Oura',
  'Garmin Connect',
  'Samsung Health',
  'Google Fit',
  'Apple Health',
  'Zocdoc',
  'WebMD',
  'GoodRx',
  'Teladoc Health',
  'Insight Timer',
  'ClassPass',
  'Noom',
  'Cronometer',
  'Komoot',
  'Uber Eats',
  'DoorDash',
  'Grubhub',
  'Postmates',
  'Deliveroo',
  'Just Eat',
  'Glovo',
  'Zomato',
  'Swiggy',
  'Instacart',
  'Gopuff',
  'OpenTable',
  'Resy',
  'Too Good To Go',
  'Starbucks',
  "McDonald's",
  "Domino's",
  'KFC',
  'Chick-fil-A',
  'Seamless',
  'Lyft',
  'Bolt',
  'Grab',
  'Careem',
  'DiDi',
  'inDrive',
  'Cabify',
  'Gett',
  'Lime',
  'Citymapper',
  'Moovit',
  'Transit',
  'Rome2Rio',
  'Google Earth',
  'Flightradar24',
  'Tripadvisor',
  'Booking.com',
  'Expedia',
  'Hotels.com',
  'Skyscanner',
  'Hopper',
  'Kayak',
  'Vrbo',
  'Hostelworld',
  'Agoda',
  'Trip.com',
  'Trivago',
  'Lonely Planet',
  'AccuWeather',
  'The Weather Channel',
  'Payoneer',
  'Cash App',
  'Zelle',
  'Revolut',
  'Wise',
  'Chime',
  'Monzo',
  'N26',
  'Klarna',
  'Afterpay',
  'Stripe',
  'Square',
  'Coinbase',
  'Robinhood',
  'eToro',
  'Binance',
  'Kraken',
  'Mint',
  'YNAB',
  'Credit Karma',
  'TurboTax',
  'QuickBooks',
  'Remitly',
  'Western Union',
  'Shopify',
  'eBay',
  'Etsy',
  'Temu',
  'SHEIN',
  'AliExpress',
  'Alibaba.com',
  'Walmart',
  'Target',
  'Best Buy',
  'IKEA',
  'Wayfair',
  'Wish',
  'Depop',
  'Vinted',
  'Poshmark',
  'Mercari',
  'OfferUp',
  'StockX',
  'Nike',
  'Sephora',
  'Chewy',
  'Khan Academy',
  'Coursera',
  'Udemy',
  'edX',
  'Quizlet',
  'Kahoot!',
  'Photomath',
  'Babbel',
  'Rosetta Stone',
  'Memrise',
  'Busuu',
  'Google Classroom',
  'Canvas Student',
  'Brainly',
  'Skillshare',
  'MasterClass',
  'TED',
  'Codecademy',
  'Mimo',
  'LinkedIn Learning',
  'Procreate',
  'Adobe Lightroom',
  'Photoshop Express',
  'Picsart',
  'CapCut',
  'InShot',
  'Snapseed',
  'Facetune',
  'Remini',
  'LumaFusion',
  'iMovie',
  'GarageBand',
  'BandLab',
  'Shutterstock',
  'Behance',
  'GIPHY',
  'Bitmoji',
  'Google Translate',
  'Microsoft Translator',
  'Google Lens',
  'Find My',
  'Life360',
  'Truecaller',
  'Speedtest',
  'Files by Google',
  'Authy',
  'Microsoft Authenticator',
  'Google Home',
  'Amazon Alexa',
  'Ring',
  'SmartThings',
  'Philips Hue',
]
