export const CHARADES_HOBBIES = [
  'Watercoloring',
  'Sketching',
  'Doodling',
  'Cartooning',
  'Calligraphy',
  'Hand Lettering',
  'Life Drawing',
  'Pastel Art',
  'Charcoal Drawing',
  'Mural Making',
  'Face Painting',
  'Body Painting',
  'Airbrushing',
  'Screen Printing',
  'Block Printing',
  'Linocut Printing',
  'Etching',
  'Collage Making',
  'Mosaic Making',
  'Stained Glass',
  'Glassblowing',
  'Glass Etching',
  'Flower Pressing',
  'Sand Art',
  'String Art',
  'Paper Marbling',
  'Bookbinding',
  'Art Journaling',
  'Urban Sketching',
  'Digital Art',
  'Pixel Art',
  'Animation',
  'Clay Modeling',
  'Wood Carving',
  'Stone Carving',
  'Soap Carving',
  'Ice Carving',
  'Whittling',
  'Woodburning',
  'Furniture Making',
  'Cabinetmaking',
  'Woodturning',
  'Basket Weaving',
  'Tapestry Weaving',
  'Rug Making',
  'Macrame',
  'Crocheting',
  'Embroidery',
  'Cross-Stitching',
  'Needlepoint',
  'Quilting',
  'Felting',
  'Lace Making',
  'Spinning Yarn',
  'Tie-Dyeing',
  'Batik',
  'Beadwork',
  'Jewelry Making',
  'Leatherworking',
  'Metalworking',
  'Blacksmithing',
  'Welding',
  'Candle Making',
  'Soap Making',
  'Resin Casting',
  'Miniature Painting',
  'Model Building',
  'Dollhouse Making',
  'Puppet Making',
  'Mask Making',
  'Costume Making',
  'Millinery',
  'Shoemaking',
  'Upholstery',
  'Paper Cutting',
  'Papier-Mache',
  'Decoupage',
  'Scrapbooking',
  'Card Making',
  'Rubber Stamping',
  'Balloon Twisting',
  'Kite Making',
  'Ship Modeling',
  'Train Modeling',
  'Terrarium Making',
  'Bonsai',
  'Floral Arranging',
  'Wreath Making',
  'Topiary',
  'Herb Gardening',
  'Vegetable Gardening',
  'Indoor Gardening',
  'Hydroponics',
  'Composting',
  'Seed Saving',
  'Mushroom Growing',
  'Beekeeping',
  'Aquascaping',
  'Birdwatching',
  'Stargazing',
  'Cloud Spotting',
  'Storm Watching',
  'Wildlife Tracking',
  'Rockhounding',
  'Fossil Hunting',
  'Shell Collecting',
  'Beachcombing',
  'Foraging',
  'Mushroom Hunting',
  'Tree Identification',
  'Wildflower Spotting',
  'Insect Watching',
  'Butterfly Watching',
  'Nature Journaling',
  'Nature Sketching',
  'Trail Mapping',
  'Lacemaking',
  'Geocaching',
  'Letterboxing',
  'Metal Detecting',
  'Gold Panning',
  'Magnet Fishing',
  'Picnicking',
  'Hammocking',
  'Forest Bathing',
  'Dog Walking',
  'Horse Grooming',
  'Animal Training',
  'Aquarium Keeping',
  'Ant Keeping',
  'Keeping Chickens',
  'Pigeon Keeping',
  'Stamp Collecting',
  'Coin Collecting',
  'Postcard Collecting',
  'Vinyl Collecting',
  'Comic Collecting',
  'Book Collecting',
  'Toy Collecting',
  'Doll Collecting',
  'Button Collecting',
  'Keychain Collecting',
  'Magnet Collecting',
  'Mineral Collecting',
  'Antique Collecting',
  'Autograph Collecting',
  'Sneaker Collecting',
  'Thrifting',
  'Antiquing',
  'Genealogy',
  'Board Gaming',
  'Card Gaming',
  'Jigsaw Puzzles',
  'Crossword Puzzles',
  'Sudoku',
  'Word Searches',
  'Logic Puzzles',
  'Rubik\'s Cube',
  'Mahjong',
  'Backgammon',
  'Checkers',
  'Dominoes',
  'Billiards',
  'Foosball',
  'Pinball',
  'Miniature Wargaming',
  'Role-Playing Games',
  'Escape Rooms',
  'Trivia Nights',
  'Treasure Hunting',
  'Scavenger Hunts',
  'Magic Tricks',
  'Cardistry',
  'Yo-Yoing',
  'Cup Stacking',
  'Pen Spinning',
  'Fingerboarding',
  'Speedcubing',
  'Kendama',
  'Puppetry',
  'Mime',
  'Improv',
  'Stand-Up Comedy',
  'Storytelling',
  'Poetry Reciting',
  'Spoken Word',
  'Beatboxing',
  'Whistling',
  'Choir Singing',
  'Karaoke',
  'Songwriting',
  'Rapping',
  'DJing',
  'Music Mixing',
  'Playing Guitar',
  'Playing Piano',
  'Playing Drums',
  'Playing Violin',
  'Playing Flute',
  'Playing Trumpet',
  'Playing Harmonica',
  'Playing Ukulele',
  'Hand Drumming',
  'Tap Dancing',
  'Ballet',
  'Ballroom Dancing',
  'Line Dancing',
  'Breakdancing',
  'Belly Dancing',
  'Square Dancing',
  'Clogging',
  'Hula Dancing',
  'Poi Spinning',
  'Hula Hooping',
  'Plate Spinning',
  'Unicycling',
  'Pogo Sticking',
  'Slacklining',
  'Parkour',
  'Jump Roping',
  'Roller Skating',
  'Rollerblading',
  'Power Walking',
  'Tai Chi',
  'Pilates',
  'Zumba',
  'Aerobics',
  'Calisthenics',
  'Meditation',
  'Breathwork',
  'LARPing',
  'Historical Reenactment',
  'Cosplay',
  'Amateur Dramatics',
  'Shadow Puppetry',
  'Ventriloquism',
  'Podcasting',
  'Vlogging',
  'Blogging',
  'Creative Writing',
  'Poetry Writing',
  'Sandcastle Building',
  'Letter Writing',
  'Fan Fiction',
  'Comic Drawing',
  'Zine Making',
  'Stop-Motion Animation',
  'Film Making',
  'Video Editing',
  'Sound Recording',
  'Field Recording',
  'Photo Editing',
  'Astrophotography',
  'Macro Photography',
  'Drone Photography',
  'Model Shipbuilding',
  'Web Design',
  'Game Development',
  'Robotics',
  'Electronics Tinkering',
  'Circuit Building',
  'Computer Building',
  'Mechanical Keyboards',
  'Amateur Radio',
  'Radio Scanning',
  'Breadmaking',
  'Cake Decorating',
  'Cookie Decorating',
  'Candy Making',
  'Chocolate Making',
  'Cheesemaking',
  'Jam Making',
  'Pickling',
  'Fermenting',
  'Homebrewing',
  'Coffee Roasting',
  'Tea Blending',
  'Barbecuing',
  'Grilling',
  'Pizza Making',
  'Pasta Making',
  'Sushi Making',
  'Ice Cream Making',
  'Fruit Carving',
  'Food Styling',
  'Recipe Testing',
  'Cake Baking',
  'Meal Prepping',
  'Language Learning',
  'Sign Language',
  'Lip Reading',
  'Speed Reading',
  'Memory Training',
  'Public Speaking',
  'Debating',
  'Map Reading',
  'Knot Tying',
  'Lock Picking',
  'Watch Repair',
  'Clockmaking',
] as const satisfies readonly string[]
