export const CHARADES_SPORTS = [
  'Association Football',
  'Futsal',
  'Beach Soccer',
  'Blind Football',
  'American Football',
  'Flag Football',
  'Australian Rules Football',
  'Gaelic Football',
  'Rugby Union',
  'Rugby League',
  'Rugby Sevens',
  'Wheelchair Rugby',
  'Basketball 3x3',
  'Wheelchair Basketball',
  'Netball',
  'Korfball',
  'Team Handball',
  'Beach Handball',
  'Water Polo',
  'Field Hockey',
  'Ice Hockey',
  'Roller Hockey',
  'Floorball',
  'Lacrosse',
  'Box Lacrosse',
  'Hurling',
  'Camogie',
  'Shinty',
  'Bandy',
  'Fistball',
  'Sepak Takraw',
  'Bossaball',
  'Kin-Ball',
  'Tchoukball',
  'Dodgeball',
  'Kickball',
  'Rounders',
  'Softball',
  'Baseball5',
  'Wiffle Ball',
  'Beach Volleyball',
  'Sitting Volleyball',
  'Snow Volleyball',
  'Canoe Polo',
  'Cycle Ball',
  'Polo',
  'Singles Tennis',
  'Doubles Tennis',
  'Wheelchair Tennis',
  'Beach Tennis',
  'Padel',
  'Pickleball',
  'Racquetball',
  'Squash',
  'Para Badminton',
  'Table Tennis Singles',
  'Table Tennis Doubles',
  'Para Table Tennis',
  'Basque Pelota',
  'Jai Alai',
  'Greco-Roman Wrestling',
  'Freestyle Wrestling',
  'Beach Wrestling',
  'Sumo Wrestling',
  'Arm Wrestling',
  'Judo',
  'Para Judo',
  'Taekwondo',
  'Para Taekwondo',
  'Kickboxing',
  'Muay Thai',
  'Savate',
  'Sambo',
  'Brazilian Jiu-Jitsu',
  'Kendo',
  'Wushu Sanda',
  'Capoeira',
  'Pencak Silat',
  'Kurash',
  'Kumite',
  'Karate Kata',
  'Mixed Martial Arts',
  'Olympic Boxing',
  'Bare-Knuckle Boxing',
  'Wheelchair Fencing',
  'Freestyle Swimming',
  'Backstroke Swimming',
  'Breaststroke Swimming',
  'Butterfly Swimming',
  'Individual Medley',
  'Open Water Swimming',
  'Marathon Swimming',
  'Para Swimming',
  'Artistic Swimming',
  'Springboard Diving',
  'Platform Diving',
  'Synchronized Diving',
  'High Diving',
  'Cliff Diving',
  'Canoe Sprint',
  'Canoe Slalom',
  'Canoe Marathon',
  'Kayak Cross',
  'Para Canoe',
  'Whitewater Rafting',
  'Dragon Boat Racing',
  'Coastal Rowing',
  'Indoor Rowing',
  'Para Rowing',
  'Sailing',
  'Windsurfing',
  'Kitesurfing',
  'Wakeboarding',
  'Water Skiing',
  'Bodyboarding',
  'Stand-Up Paddleboarding',
  'Surf Lifesaving',
  'Underwater Hockey',
  'Underwater Rugby',
  'Finswimming',
  'Alpine Skiing',
  'Cross-Country Skiing',
  'Ski Jumping',
  'Nordic Combined',
  'Freestyle Skiing',
  'Moguls Skiing',
  'Ski Cross',
  'Halfpipe Skiing',
  'Slopestyle Skiing',
  'Ski Mountaineering',
  'Speed Skiing',
  'Telemark Skiing',
  'Para Alpine Skiing',
  'Para Nordic Skiing',
  'Snowboard Cross',
  'Snowboard Halfpipe',
  'Snowboard Slopestyle',
  'Parallel Giant Slalom',
  'Para Snowboard',
  'Figure Skating',
  'Pair Skating',
  'Ice Dance',
  'Speed Skating',
  'Short Track Skating',
  'Synchronized Skating',
  'Curling',
  'Wheelchair Curling',
  'Bobsleigh',
  'Skeleton',
  'Luge',
  'Biathlon',
  'Para Biathlon',
  'Ice Climbing',
  'Snowshoe Racing',
  'Dog Sled Racing',
  'Skijoring',
  '100-Metre Sprint',
  '200-Metre Sprint',
  '400-Metre Sprint',
  '800-Metre Race',
  '1500-Metre Race',
  '5000-Metre Race',
  '10000-Metre Race',
  'Marathon Running',
  'Cross-Country Running',
  'Trail Running',
  'Mountain Running',
  'Ultramarathon',
  'Steeplechase',
  'Sprint Hurdles',
  '400-Metre Hurdles',
  'Relay Racing',
  'Race Walking',
  'High Jump',
  'Pole Vault',
  'Triple Jump',
  'Shot Put',
  'Discus Throw',
  'Hammer Throw',
  'Javelin Throw',
  'Decathlon',
  'Heptathlon',
  'Para Athletics',
  'Wheelchair Racing',
  'Frame Running',
  'Orienteering',
  'Obstacle Course Racing',
  'Parkour Freestyle',
  'Sport Climbing',
  'Speed Climbing',
  'Bouldering',
  'Para Climbing',
  'Artistic Gymnastics',
  'Rhythmic Gymnastics',
  'Trampoline Gymnastics',
  'Acrobatic Gymnastics',
  'Aerobic Gymnastics',
  'Tumbling',
  'Competitive Cheerleading',
  'Breaking',
  'Latin DanceSport',
  'Powerlifting',
  'Para Powerlifting',
  'Olympic Weightlifting',
  'Strongman',
  'Highland Games',
  'Tug of War',
  'Kettlebell Sport',
  'Road Cycling',
  'Track Cycling',
  'Mountain Biking',
  'Cyclocross',
  'BMX Racing',
  'BMX Freestyle',
  'Para Road Cycling',
  'Para Track Cycling',
  'Inline Speed Skating',
  'Skateboard Street',
  'Skateboard Park',
  'Formula One Racing',
  'Endurance Racing',
  'Touring Car Racing',
  'Drag Racing',
  'Drifting',
  'Rally Racing',
  'Rallycross',
  'Rally-Raid',
  'Kart Racing',
  'Formula E Racing',
  'Motocross',
  'Supercross',
  'Motorcycle Trials',
  'Enduro Motorcycling',
  'Speedway Motorcycling',
  'Recurve Archery',
  'Compound Archery',
  'Field Archery',
  'Para Archery',
  'Sporting Clays',
  'Skeet Shooting',
  'Trap Shooting',
  'Air Rifle Shooting',
  'Air Pistol Shooting',
  'Shooting Para Sport',
  'Modern Pentathlon',
  'Disc Golf',
  'Ultimate Frisbee',
  'Drone Racing',
  'Pétanque',
  'Lawn Bowls',
  'Tenpin Bowling',
  'Carom Billiards',
  'Pool Billiards',
  'Snooker',
  'English Billiards',
  'Shuffleboard',
  'Quoits',
  'Horseshoes',
  'Cornhole',
  'Sport Stacking',
  'Dressage',
  'Show Jumping',
  'Equestrian Eventing',
  'Endurance Riding',
  'Equestrian Vaulting',
  'Reining',
  'Harness Racing',
  'Horse Racing',
  'Para Equestrian Dressage',
  'Mounted Archery',
  'Buzkashi',
  'Kabaddi',
  'Kho Kho',
  'Mallakhamb',
  'Gatka',
  'Teqball',
  'Footvolley',
  'Chinlone',
  'Cuju',
  'Gateball',
  'Woodball',
  'Wife Carrying',
  'Log Rolling',
  'Caber Toss',
  'Sheaf Toss',
  'Stone Skimming',
  'Competitive Lifesaving',
  'Firefighter Combat Challenge',
  'Boccia',
  'Goalball',
  'Powerchair Football',
  'Wheelchair Handball',
  'Wheelchair Racing Slalom',
  'Para Ice Hockey',
  'Showdown',
  'Torball',
  'Beep Baseball',
  'Para Surfing',
  'Para Sailing',
  'Para Triathlon',
] as const satisfies readonly string[]
