export const CHARADES_SONGS: readonly string[] = [
  'Over the Rainbow',
  'Blue Suede Shoes',
  'Hound Dog',
  'Jailhouse Rock',
  'Great Balls of Fire',
  'Johnny B. Goode',
  'Wake Up Little Susie',
  'Rock Around the Clock',
  'Tutti Frutti',
  'La Bamba',
  'Only You (And You Alone)',
  'Dream Lover',
  'Mack the Knife',
  'Que Sera, Sera',
  'Mr. Sandman',
  'Earth Angel',
  'Shout',
  'Beyond the Sea',
  'Day-O (The Banana Boat Song)',
  'Put Your Head on My Shoulder',
  'Stand by Me',
  'My Girl',
  'The Twist',
  'Oh, Pretty Woman',
  'Ring of Fire',
  'I Got You Babe',
  'Dancing in the Street',
  'Do You Love Me',
  'Stop! In the Name of Love',
  'Ain\'t No Mountain High Enough',
  'Respect',
  'Chain of Fools',
  'I Say a Little Prayer',
  'What a Wonderful World',
  '(Sittin\' On) The Dock of the Bay',
  'The Lion Sleeps Tonight',
  'Sugar, Sugar',
  'California Dreamin\'',
  'These Boots Are Made for Walkin\'',
  'House of the Rising Sun',
  'I Want to Hold Your Hand',
  'Yellow Submarine',
  'Help!',
  'Here Comes the Sun',
  'All You Need Is Love',
  'Paint It, Black',
  'Jumpin\' Jack Flash',
  'Good Vibrations',
  'Daydream Believer',
  'Space Oddity',
  'Suspicious Minds',
  'Proud Mary',
  'Son of a Preacher Man',
  'Sweet Caroline',
  'Raindrops Keep Fallin\' on My Head',
  'Leaving on a Jet Plane',
  'Aquarius',
  'Light My Fire',
  'Born to Be Wild',
  'My Way',
  'Dancing Queen',
  'Waterloo',
  'Mamma Mia',
  'Stayin\' Alive',
  'Night Fever',
  'I Will Survive',
  'We Are Family',
  'Le Freak',
  'Y.M.C.A.',
  'Play That Funky Music',
  'September',
  'Boogie Wonderland',
  'Car Wash',
  'Disco Inferno',
  'Superstition',
  'Isn\'t She Lovely',
  'Sir Duke',
  'Lean on Me',
  'Lovely Day',
  'Let\'s Stay Together',
  'Killing Me Softly with His Song',
  'Midnight Train to Georgia',
  'Lady Marmalade',
  'Three Little Birds',
  'No Woman, No Cry',
  'One Love',
  'Jolene',
  'Take Me Home, Country Roads',
  'The Gambler',
  'Rhinestone Cowboy',
  'American Pie',
  'Piano Man',
  'Rocket Man',
  'Crocodile Rock',
  'Hotel California',
  'Go Your Own Way',
  'Dream On',
  'Smoke on the Water',
  'Another One Bites the Dust',
  'We Will Rock You',
  'We Are the Champions',
  'Bohemian Rhapsody',
  'Don\'t Stop Me Now',
  'Highway to Hell',
  'Thunderstruck',
  'Walk This Way',
  'The Boys Are Back in Town',
  'Free Bird',
  'Bridge over Troubled Water',
  'Sweet Home Alabama',
  'Heart of Glass',
  'Rivers of Babylon',
  'Kung Fu Fighting',
  'You\'re the One That I Want',
  'Greased Lightnin\'',
  'Hopelessly Devoted to You',
  'Thriller',
  'Billie Jean',
  'Beat It',
  'Man in the Mirror',
  'Smooth Criminal',
  'Like a Prayer',
  'Material Girl',
  'Into the Groove',
  'Girls Just Want to Have Fun',
  'Time After Time',
  'Wake Me Up Before You Go-Go',
  'Careless Whisper',
  'Footloose',
  'Flashdance... What a Feeling',
  'Maniac',
  'Eye of the Tiger',
  'The Power of Love',
  'Walking on Sunshine',
  'You Spin Me Round',
  'Take on Me',
  'The Final Countdown',
  '99 Luftballons',
  'Sweet Dreams (Are Made of This)',
  'Every Breath You Take',
  'Walk Like an Egyptian',
  'Down Under',
  'Africa',
  'Karma Chameleon',
  'Red Red Wine',
  'I Think We\'re Alone Now',
  'Heaven Is a Place on Earth',
  'Total Eclipse of the Heart',
  'Holding Out for a Hero',
  'You Can Call Me Al',
  'Born in the U.S.A.',
  'Summer of \'69',
  'Livin\' on a Prayer',
  'Another Day in Paradise',
  'Fast Car',
  'Like a Rolling Stone',
  'Walk of Life',
  'Beds Are Burning',
  'Orinoco Flow',
  'Don\'t Worry, Be Happy',
  'Push It',
  'Ice Ice Baby',
  'U Can\'t Touch This',
  'Jump Around',
  'Baby Got Back',
  'Rapper\'s Delight',
  'Fight the Power',
  'Straight Outta Compton',
  'Gangsta\'s Paradise',
  'Waterfalls',
  'No Scrubs',
  'This Is How We Do It',
  'Return of the Mack',
  'I Will Always Love You',
  'My Heart Will Go On',
  'I\'m Your Baby Tonight',
  'Genie in a Bottle',
  '...Baby One More Time',
  'Everybody (Backstreet\'s Back)',
  'I Want It That Way',
  'Wannabe',
  'Say My Name',
  'Man! I Feel Like a Woman!',
  'You Get What You Give',
  'Tubthumping',
  'MMMBop',
  'Macarena',
  'Mambo No. 5',
  'Blue (Da Ba Dee)',
  'Cotton Eye Joe',
  'Barbie Girl',
  'The Sign',
  'What Is Love',
  'Rhythm Is a Dancer',
  'Freed from Desire',
  'Vogue',
  'Livin\' la Vida Loca',
  'La Copa de la Vida',
  'Bailamos',
  'Oye Mi Canto',
  'The Ketchup Song',
  'Dragostea Din Tei',
  'Lambada',
  'Gasolina',
  'Hips Don\'t Lie',
  'Whenever, Wherever',
  'On the Floor',
  'Crazy in Love',
  'Single Ladies (Put a Ring on It)',
  'Umbrella',
  'Don\'t Stop the Music',
  'Poker Face',
  'Just Dance',
  'Firework',
  'Roar',
  'Toxic',
  'Sk8er Boi',
  'Since U Been Gone',
  'Pocketful of Sunshine',
  'A Thousand Miles',
  'Hey Ya!',
  'Clocks',
  'Beautiful Day',
  'Seven Nation Army',
  'Mr. Brightside',
  'Teenage Dirtbag',
  'I Believe in a Thing Called Love',
  'Bad Day',
  'You\'re Beautiful',
  'Bleeding Love',
  'Rehab',
  'Back to Black',
  'Valerie',
  'Put Your Records On',
  'Ordinary People',
  'Viva la Vida',
  'We Don\'t Talk About Bruno',
  'I Gotta Feeling',
  'Boom Boom Pow',
  'Fireflies',
  'TiK ToK',
  'Dynamite',
  'Rolling in the Deep',
  'Someone Like You',
  'Call Me Maybe',
  'Happy',
  'Shake It Off',
  'Blank Space',
  'Uptown Funk',
  'Shape of You',
  'Counting Stars',
  'Just the Way You Are',
  'Moves Like Jagger',
  'What Makes You Beautiful',
  'Party Rock Anthem',
  'Cheap Thrills',
  'Chandelier',
  'Titanium',
  'La Vie en rose',
  'Radioactive',
  'Royals',
  'Blurred Lines',
  'All About That Bass',
  'Despacito',
  'Bailando',
  'Danza Kuduro',
  'Mi Gente',
  'Waka Waka (This Time for Africa)',
  'Jerusalema',
  'Pata Pata',
  'Water',
  'love nwantiti (ah ah ah)',
  'Calm Down',
  'Last Last',
  'I Lived',
  'Soweto',
  'Gangnam Style',
  'Sukiyaki',
  'Butter',
  'Cupid',
  'APT.',
  'Golden',
  'Baby Shark',
  'See You Again',
  'Let Her Go',
  'Stressed Out',
  'Old Town Road',
  'Bad Guy',
  'Dance Monkey',
  'Blinding Lights',
  'Levitating',
  'Flowers',
  'As It Was',
  'Anti-Hero',
  'Cruel Summer',
  'The Climb',
  'Beautiful Things',
  'Birds of a Feather',
  'Pink Pony Club',
  'Die with a Smile',
]
