export const CHARADES_INTERNET_SLANG = [
  'AFK',
  'AMA',
  'ASAP',
  'BFF',
  'BRB',
  'BTW',
  'DIY',
  'DM',
  'ELI5',
  'FTW',
  'FYI',
  'GG',
  'GLHF',
  'GRWM',
  'GTG',
  'HMU',
  'ICYMI',
  'IDK',
  'IKR',
  'ILY',
  'IMHO',
  'IRL',
  'JK',
  'JSYK',
  'LMK',
  'NGL',
  'NP',
  'NVM',
  'OFC',
  'OMW',
  'OOTD',
  'OP',
  'POV',
  'ROFL',
  'SMH',
  'TBH',
  'TBT',
  'TIL',
  'TLDR',
  'TTYL',
  'WIP',
  'WYD',
  'YOLO',
  'AFAIK',
  'Behind the Scenes',
  'FAQ',
  'FYP',
  'QOTD',
  'Big Brain',
  'Big Mood',
  'Brain Rot',
  'Canon Event',
  'Caught in 4K',
  'Chef’s Kiss',
  'Core Memory',
  'Crying Emoji',
  'Dad Joke',
  'Epic Fail',
  'Facepalm',
  'Fake News',
  'Fan Theory',
  'Girl Dinner',
  'Goblin Mode',
  'How It Started',
  'How It’s Going',
  'I Can’t Even',
  'IYKYK',
  'Main Character',
  'Mic Drop',
  'Plot Twist',
  'Rickroll',
  'Side-Eye',
  'Spill the Tea',
  'This Is Fine',
  'Throwback Thursday',
  'Tiny Violin',
  'Troll Face',
  'Understood the Assignment',
  'Unpopular Opinion',
  'Victory Royale',
  'Weird Flex',
  'Wholesome Content',
  'Who Asked',
  'Wrong Answers Only',
  'You Had One Job',
  'Zoom Bombing',
  'Distracted Boyfriend',
  'Galaxy Brain',
  'Keyboard Cat',
  'Side Quest',
  'Surprised Pikachu',
  'The Floor Is Lava',
  'Woman Yelling at Cat',
  'Doge',
  'Nyan Cat',
  'Success Kid',
  'Grumpy Cat',
  'Hide the Pain Harold',
  'Mutuals Only',
  'Binge-Watching',
  'Clickbait',
  'Doomscrolling',
  'Double Tap',
  'Endless Scroll',
  'Friend Request',
  'Going Viral',
  'Google It',
  'Hashtag',
  'Inbox Zero',
  'Keyboard Warrior',
  'Left on Read',
  'Lurking',
  'Mute Button',
  'Seen Zone',
  'Reply Guy',
  'Rage Quit',
  'Reply All',
  'Screen Time',
  'Shadowban',
  'Social Butterfly',
  'Spam Folder',
  'Swipe Left',
  'Swipe Right',
  'Tag a Friend',
  'Touch Grass',
  'Trending Topic',
  'Typing Indicator',
  'Unfollow',
  'Unfriend',
  'Viral Challenge',
  'Voice Note',
  'Watch Party',
  'Wi-Fi Password',
  'Zoom Fatigue',
  'Catfishing',
  'Cyberstalking',
  'Digital Detox',
  'Photo Dump',
  'Soft Launch',
  'Hard Launch',
  'Comment Section',
  'Community Notes',
  'Content Warning',
  'Cross-Posting',
  'Duet Video',
  'Emoji Reaction',
  'Fan Account',
  'Finsta',
  'Group Chat',
  'Like Button',
  'Link in Bio',
  'Pinned Comment',
  'Profile Picture',
  'Quote Tweet',
  'Reaction Video',
  'Read Receipt',
  'Story Time',
  'Stitch Video',
  'Subscriber Only',
  'Thread',
  'Timeline',
  'Close Friends',
  'Creator Fund',
  'Disappearing Message',
  'Filter Bubble',
  'Mutuals',
  'News Feed',
  'Photo Tag',
  'Quote Tweeting',
  'Repost',
  'Story Highlight',
  'Blue Check',
  'Alt Account',
  'Burner Account',
  'Carousel Post',
  'Collab Post',
  'Pinned Post',
  'Reaction GIF',
  'Voice Chat',
  'Auto-Reply',
  'Block List',
  'Content Creator',
  'Daily Vlog',
  'Face Filter',
  'Follower Count',
  'Internet Famous',
  'Meme Page',
  'Notification Bell',
  'Online Poll',
  'Private Account',
  'Screen Recording',
  'Spoiler Alert',
  'Status Update',
  'Subscriber Milestone',
  'Thumbnail',
  'Unboxing',
  'Viral Dance',
  'Bio Link',
  'Brand Deal',
  'Camera Flip',
  'Content Calendar',
  'Creator Burnout',
  'Editing Tutorial',
  'Fan Edit',
  'Green Screen',
  'Influencer Trip',
  'Live Chat',
  'Merch Drop',
  'Mukbang',
  'Outtake',
  'Ring Light',
  'Sound Check',
  'Sponsored Post',
  'Stream Sniper',
  'Trending Audio',
  'Video Essay',
  'Vlogmas',
  'Bloopers',
  'Channel Raid',
  'Chat Moderator',
  'Follower Goal',
  'Live Reaction',
  'Speedrun',
  'Stream Delay',
  'Stream Key',
  'Subscriber Badge',
  'Viewer Count',
  'Donation Alert',
  'Emote Spam',
  'Hype Train',
  'Stream Overlay',
  'Clutch',
  'Combo Breaker',
  'Cooldown',
  'Critical Hit',
  'Easter Egg',
  'Fast Travel',
  'Final Boss',
  'Grinding',
  'Hitbox',
  'Lag Spike',
  'Level Up',
  'Loot Drop',
  'Matchmaking',
  'Nerf',
  'Noob',
  'NPC',
  'Party Invite',
  'Power-Up',
  'Respawn',
  'Save Point',
  'Spawn Camping',
  'Squad Goals',
  'Team Wipe',
  'Victory Screen',
  'Boss Battle',
  'Button Mash',
  'Friendly Fire',
  'Game Lobby',
  'Health Bar',
  'Thread Unroll',
  'Player Two',
  'Skill Issue',
  'Smurf Account',
  'Battle Pass',
  'Daily Quest',
  'Game Chat',
  'Leaderboard',
  'Loot Box',
  'Patch Notes',
  'Ping Spike',
  'Player Skin',
  'Squad Up',
  'Achievement Unlocked',
  'One More Game',
  'Press F',
  'Cozy Gamer',
  'Backseat Gaming',
  'Casual Gamer',
  'Emoji Keyboard',
  'Internet Troll',
  'Meme Lord',
  'Mobile Gamer',
  'Online Friend',
  'Pro Gamer',
  'Server Admin',
  'Slow Mode',
  'Spoiler Tag',
  'Typing in Caps',
  'Username Taken',
  'Webcam Freeze',
  'Feed Refresh',
  '404 Error',
  'Copy-Paste',
  'Cringe Compilation',
  'Downvote',
  'Upvote',
  'Internet Rabbit Hole',
  'Meme Template',
  'Reaction Image',
] as const satisfies readonly string[]
