export const CHARADES_NATURAL_DISASTERS: readonly string[] = [
  'Aftershock',
  'Ground Shaking',
  'Fault Rupture',
  'Surface Faulting',
  'Soil Liquefaction',
  'Ground Subsidence',
  'Sinkhole',
  'Rockfall',
  'Rockslide',
  'Mudslide',
  'Debris Flow',
  'Mudflow',
  'Earthflow',
  'Slump',
  'Snow Avalanche',
  'Ice Avalanche',
  'Glacial Earthquake',
  'Ice Quake',
  'Frost Quake',
  'Seiche',
  'Rogue Wave',
  'Storm Surge',
  'Coastal Flooding',
  'River Flooding',
  'Flash Flood',
  'Ice Jam',
  'Glacial Lake Outburst',
  'Jokulhlaup',
  'Limnic Eruption',
  'Tidal Bore',
  'Rip Current',
  'Whirlpool',
  'Waterspout',
  'Pumice Raft',
  'Dust Devil',
  'Gustnado',
  'Landspout',
  'Funnel Cloud',
  'Downburst',
  'Microburst',
  'Macroburst',
  'Derecho',
  'Squall',
  'White Squall',
  'Windstorm',
  'Gale',
  'Sirocco',
  'Chinook Wind',
  'Santa Ana Winds',
  'Katabatic Wind',
  'Atmospheric River',
  'Cloudburst',
  'Rainstorm',
  'Freezing Rain',
  'Ice Storm',
  'Sleet',
  'Snowstorm',
  'Snow Squall',
  'Lake-Effect Snow',
  'Thundersnow',
  'Ground Blizzard',
  'Whiteout',
  'Cold Wave',
  'Black Ice',
  'Hoarfrost',
  'Rime Ice',
  'Graupel',
  'Hail',
  'Heat Dome',
  'Firestorm',
  'Fire Whirl',
  'Crown Fire',
  'Peat Fire',
  'Ground Fire',
  'Smoke Haze',
  'Dust Storm',
  'Haboob',
  'Ashfall',
  'Volcanic Ash Cloud',
  'Lava Flow',
  'Lava Fountain',
  'Lava Bomb',
  'Lava Lake',
  'Pyroclastic Flow',
  'Pyroclastic Surge',
  'Lahar',
  'Tephra Fall',
  'Volcanic Lightning',
  'Volcanic Gas',
  'Volcanic Smog',
  'Fissure Eruption',
  'Phreatic Eruption',
  'Phreatomagmatic Eruption',
  'Strombolian Eruption',
  'Vulcanian Eruption',
  'Plinian Eruption',
  'Peléan Eruption',
  'Surtseyan Eruption',
  'Submarine Eruption',
  'Caldera Collapse',
  'Lava Dome Collapse',
  'Flank Collapse',
  'Steam Explosion',
  'Geyser Eruption',
  'Mud Volcano',
  'Sand Boil',
  'Quicksand',
  'Karst Collapse',
  'Coastal Erosion',
  'Cliff Collapse',
  'Dune Migration',
  'Desertification',
  'Soil Erosion',
  'Salinization',
  'Permafrost Thaw',
  'Glacier Surge',
  'Glacier Calving',
  'Ice Shelf Collapse',
  'Iceberg Roll',
  'Sea Ice Breakup',
  'High Tide Flooding',
  'King Tide',
  'Red Tide',
  'Algal Bloom',
  'Sea Foam',
  'Ocean Upwelling',
  'El Niño',
  'La Niña',
  'Polar Vortex',
  'Bomb Cyclone',
  'Tropical Depression',
  'Tropical Storm',
  'Typhoon',
  'Medicane',
  'Subtropical Storm',
  'Extratropical Cyclone',
  'Nor’easter',
  'Monsoon Burst',
  'Monsoon Break',
  'Rain Shadow',
  'Temperature Inversion',
  'Supercell',
  'Wall Cloud',
  'Shelf Cloud',
  'Roll Cloud',
  'Mammatus Cloud',
  'Arcus Cloud',
  'Lightning Bolt',
  'Ball Lightning',
  'Dry Lightning',
  'Heat Lightning',
  'Thunderclap',
  'St. Elmo’s Fire',
  'Green Flash',
  'Sun Dog',
  'Light Pillar',
  'Moonbow',
  'Fog Bank',
  'Freezing Fog',
  'Sea Smoke',
  'Mirage',
  'Aurora Borealis',
  'Aurora Australis',
  'Solar Flare',
  'Solar Storm',
  'Geomagnetic Storm',
  'Radiation Storm',
  'Coronal Mass Ejection',
  'Solar Wind',
  'Solar Prominence',
  'Sunspot',
  'Radio Blackout',
  'Meteor Shower',
  'Meteor Airburst',
  'Asteroid Impact',
  'Comet Impact',
  'Chelyabinsk Meteor',
  'Tunguska Event',
  'Carrington Event',
  'Mount Vesuvius Eruption',
  'Mount Tambora Eruption',
  'Krakatoa Eruption',
  'Mount Pelée Eruption',
  'Novarupta Eruption',
  'Mount St. Helens Eruption',
  'Nevado del Ruiz Eruption',
  'Mount Pinatubo Eruption',
  'Eyjafjallajökull Eruption',
  'Hunga Tonga Eruption',
  'Kīlauea Eruption',
  'Laki Eruption',
  'Santorini Eruption',
  'Mount Unzen Eruption',
  'Mount Agung Eruption',
  'El Chichón Eruption',
  'Mount Merapi Eruption',
  'La Soufrière Eruption',
  'Cumbre Vieja Eruption',
  'Great Lisbon Earthquake',
  'San Francisco Earthquake',
  'Great Kantō Earthquake',
  'Valdivia Earthquake',
  'Good Friday Earthquake',
  'Tangshan Earthquake',
  'Mexico City Earthquake',
  'Loma Prieta Earthquake',
  'Northridge Earthquake',
  'Kobe Earthquake',
  'İzmit Earthquake',
  'Haiti Earthquake',
  'Christchurch Earthquake',
  'Tohoku Earthquake',
  'Nepal Earthquake',
  'Sichuan Earthquake',
  'Indian Ocean Tsunami',
  'Tōhoku Tsunami',
  'Krakatoa Tsunami',
  'Lisbon Tsunami',
  'Lituya Bay Megatsunami',
  'Hurricane Andrew',
  'Hurricane Katrina',
  'Hurricane Sandy',
  'Hurricane Harvey',
  'Hurricane Irma',
  'Hurricane Maria',
  'Hurricane Dorian',
  'Hurricane Ian',
  'Hurricane Mitch',
  'Hurricane Gilbert',
  'Hurricane Camille',
  'Hurricane Hugo',
  'Hurricane Wilma',
  'Hurricane Ike',
  'Hurricane Michael',
  'Hurricane Otis',
  'Typhoon Haiyan',
  'Typhoon Tip',
  'Typhoon Hagibis',
  'Typhoon Bopha',
  'Cyclone Nargis',
  'Cyclone Idai',
  'Cyclone Freddy',
  'Cyclone Tracy',
  'Cyclone Yasi',
  'Cyclone Bhola',
  'Great Galveston Storm',
  'Great Hurricane of 1780',
  'Tri-State Tornado',
  'Joplin Tornado',
  'Daulatpur–Saturia Tornado',
  'Super Outbreak',
  'Palm Sunday Outbreak',
  'El Reno Tornado',
  'Moore Tornado',
  'Tuscaloosa Tornado',
  'Great Blizzard of 1888',
  'Schoolhouse Blizzard',
  'Armistice Day Blizzard',
  'Great Appalachian Storm',
  'Storm of the Century',
  'Great Ice Storm',
  'Texas Winter Storm',
  'European Heatwave',
  'Russian Heatwave',
  'Dust Bowl',
  'Great Smog of London',
  'Great Flood of 1931',
  'Great Mississippi Flood',
  'North Sea Flood',
  'Yellow River Flood',
  'Pakistan Floods',
  'Queensland Floods',
  'Red River Flood',
  'Central European Floods',
  'Black Saturday Bushfires',
  'Black Summer Bushfires',
  'Ash Wednesday Bushfires',
  'Camp Fire',
  'Maui Wildfires',
  'Fort McMurray Wildfire',
  'Peshtigo Fire',
  'Great Fire of 1910',
  'Yellowstone Fires',
  'Oso Landslide',
  'Vajont Landslide',
  'Thredbo Landslide',
  'Frank Slide',
  'Hope Slide',
  'Usoy Landslide',
  'Armero Tragedy',
  'Lake Nyos Disaster',
  'Huascarán Avalanche',
  'White Friday Avalanches',
  'Wellington Avalanche',
  'Knickerbocker Storm',
  'Year Without Summer',
  'Great Frost',
  'Sahel Drought',
  'Millennium Drought',
  'Horn of Africa Drought',
]
