export const CHARADES_POLITICIANS: readonly string[] = [
  'Sargon of Akkad',
  'Hammurabi',
  'Ramesses II',
  'Hatshepsut',
  'Cleopatra',
  'Cyrus the Great',
  'Darius the Great',
  'Xerxes I',
  'Pericles',
  'Alexander the Great',
  'Ashoka',
  'Qin Shi Huang',
  'Hannibal',
  'Scipio Africanus',
  'Julius Caesar',
  'Augustus',
  'Mark Antony',
  'Nero',
  'Marcus Aurelius',
  'Constantine the Great',
  'Justinian I',
  'Theodora',
  'Attila the Hun',
  'Charlemagne',
  'Alfred the Great',
  'William the Conqueror',
  'Richard the Lionheart',
  'Saladin',
  'Genghis Khan',
  'Kublai Khan',
  'Mansa Musa',
  'Joan of Arc',
  'Mehmed II',
  'Moctezuma II',
  'Pachacuti',
  'Suleiman the Magnificent',
  'Akbar',
  'Tokugawa Ieyasu',
  'Shaka Zulu',
  'Peter the Great',
  'Catherine the Great',
  'Ivan the Terrible',
  'Louis XIV',
  'Marie Antoinette',
  'Henry VIII',
  'Elizabeth I',
  'Mary I of England',
  'Mary, Queen of Scots',
  'Oliver Cromwell',
  'Queen Victoria',
  'Napoleon Bonaparte',
  'Simón Bolívar',
  'José de San Martín',
  'Toussaint Louverture',
  'Otto von Bismarck',
  'Giuseppe Garibaldi',
  'Vladimir Lenin',
  'Joseph Stalin',
  'Leon Trotsky',
  'Mikhail Gorbachev',
  'Boris Yeltsin',
  'Vladimir Putin',
  'Volodymyr Zelenskyy',
  'Winston Churchill',
  'Margaret Thatcher',
  'Tony Blair',
  'Boris Johnson',
  'Theresa May',
  'David Cameron',
  'Keir Starmer',
  'Charles de Gaulle',
  'Georges Clemenceau',
  'François Mitterrand',
  'Jacques Chirac',
  'Nicolas Sarkozy',
  'Emmanuel Macron',
  'Napoleon III',
  'Adolf Hitler',
  'Benito Mussolini',
  'Silvio Berlusconi',
  'Giorgia Meloni',
  'Angela Merkel',
  'Helmut Kohl',
  'Olaf Scholz',
  'Konrad Adenauer',
  'Willy Brandt',
  'Ursula von der Leyen',
  'Jean Monnet',
  'Robert Schuman',
  'Lech Wałęsa',
  'Václav Havel',
  'Alexander Dubček',
  'Josip Broz Tito',
  'Slobodan Milošević',
  'Nicolae Ceaușescu',
  'Viktor Orbán',
  'Gro Harlem Brundtland',
  'Jacinda Ardern',
  'Sanna Marin',
  'Mark Rutte',
  'Pedro Sánchez',
  'António de Oliveira Salazar',
  'António Guterres',
  'George Washington',
  'Thomas Jefferson',
  'Benjamin Franklin',
  'John Adams',
  'James Madison',
  'Andrew Jackson',
  'Abraham Lincoln',
  'Ulysses S. Grant',
  'Theodore Roosevelt',
  'Woodrow Wilson',
  'Franklin D. Roosevelt',
  'Harry S. Truman',
  'Dwight D. Eisenhower',
  'John F. Kennedy',
  'Lyndon B. Johnson',
  'Richard Nixon',
  'Gerald Ford',
  'Jimmy Carter',
  'Ronald Reagan',
  'George H. W. Bush',
  'Bill Clinton',
  'George W. Bush',
  'Joe Biden',
  'Donald Trump',
  'Kamala Harris',
  'Hillary Clinton',
  'Bernie Sanders',
  'Nancy Pelosi',
  'Ruth Bader Ginsburg',
  'John McCain',
  'Robert F. Kennedy',
  'Malcolm X',
  'Martin Luther King Jr.',
  'Rosa Parks',
  'Harriet Tubman',
  'Frederick Douglass',
  'Susan B. Anthony',
  'César Chávez',
  'Harvey Milk',
  'Justin Trudeau',
  'Pierre Trudeau',
  'Stephen Harper',
  'Lester B. Pearson',
  'John A. Macdonald',
  'Claudia Sheinbaum',
  'Andrés Manuel López Obrador',
  'Benito Juárez',
  'Porfirio Díaz',
  'Emiliano Zapata',
  'Pancho Villa',
  'Fidel Castro',
  'Raúl Castro',
  'Che Guevara',
  'Fulgencio Batista',
  'Jean-Bertrand Aristide',
  'François Duvalier',
  'Augusto Pinochet',
  'Salvador Allende',
  'Gabriel Boric',
  'Juan Perón',
  'Eva Perón',
  'Javier Milei',
  'Luiz Inácio Lula da Silva',
  'Jair Bolsonaro',
  'Dilma Rousseff',
  'Getúlio Vargas',
  'Nicolás Maduro',
  'Hugo Chávez',
  'Gustavo Petro',
  'Álvaro Uribe',
  'José Mujica',
  'Alberto Fujimori',
  'Evo Morales',
  'Rafael Correa',
  'Daniel Ortega',
  'Rigoberta Menchú',
  'Kwame Nkrumah',
  'Jomo Kenyatta',
  'Julius Nyerere',
  'Haile Selassie',
  'Patrice Lumumba',
  'Mobutu Sese Seko',
  'Thomas Sankara',
  'Félix Houphouët-Boigny',
  'Léopold Sédar Senghor',
  'Ahmed Sékou Touré',
  'Gamal Abdel Nasser',
  'Anwar Sadat',
  'Hosni Mubarak',
  'Abdel Fattah el-Sisi',
  'Muammar Gaddafi',
  'Habib Bourguiba',
  'Ahmed Ben Bella',
  'Abdelaziz Bouteflika',
  'King Hassan II',
  'Mohammed VI',
  'Samora Machel',
  'Robert Mugabe',
  'Ian Smith',
  'Kenneth Kaunda',
  'Hastings Banda',
  'Seretse Khama',
  'Paul Kagame',
  'Yoweri Museveni',
  'Idi Amin',
  'Milton Obote',
  'Mengistu Haile Mariam',
  'Meles Zenawi',
  'Abiy Ahmed',
  'Siad Barre',
  'Ellen Johnson Sirleaf',
  'Jerry Rawlings',
  'Olusegun Obasanjo',
  'Yakubu Gowon',
  'Muhammadu Buhari',
  'Goodluck Jonathan',
  'Bola Tinubu',
  'Nnamdi Azikiwe',
  'Obafemi Awolowo',
  'Moshood Abiola',
  'Desmond Tutu',
  'Steve Biko',
  'F. W. de Klerk',
  'Thabo Mbeki',
  'Jacob Zuma',
  'Cyril Ramaphosa',
  'Albert Luthuli',
  'Wangari Maathai',
  'Kofi Annan',
  'Mahatma Gandhi',
  'Jawaharlal Nehru',
  'Indira Gandhi',
  'Rajiv Gandhi',
  'Narendra Modi',
  'Manmohan Singh',
  'Atal Bihari Vajpayee',
  'B. R. Ambedkar',
  'Muhammad Ali Jinnah',
  'Benazir Bhutto',
  'Imran Khan',
  'Pervez Musharraf',
  'Sheikh Mujibur Rahman',
  'Sheikh Hasina',
  'Aung San',
  'Aung San Suu Kyi',
  'Ne Win',
  'Lee Kuan Yew',
  'Mahathir Mohamad',
  'Tunku Abdul Rahman',
  'Sukarno',
  'Suharto',
  'Joko Widodo',
  'Ferdinand Marcos',
  'Corazon Aquino',
  'Rodrigo Duterte',
  'Ho Chi Minh',
  'Ngo Dinh Diem',
  'Pol Pot',
  'Norodom Sihanouk',
  'Mao Zedong',
  'Deng Xiaoping',
  'Xi Jinping',
  'Sun Yat-sen',
  'Chiang Kai-shek',
  'Tsai Ing-wen',
  'Kim Il Sung',
  'Kim Jong Il',
  'Kim Jong Un',
  'Syngman Rhee',
  'Park Chung Hee',
  'Moon Jae-in',
  'Shinzo Abe',
  'Emperor Meiji',
  'Dalai Lama',
  'King Bhumibol Adulyadej',
  'José Rizal',
  'Benigno Aquino Jr.',
  'Ayatollah Khomeini',
  'Mohammad Reza Pahlavi',
  'Mohammad Mossadegh',
  'Mahmoud Ahmadinejad',
  'Recep Tayyip Erdoğan',
  'Mustafa Kemal Atatürk',
  'Saddam Hussein',
  'King Faisal',
  'Mohammed bin Salman',
  'David Ben-Gurion',
  'Golda Meir',
  'Yitzhak Rabin',
  'Shimon Peres',
  'Benjamin Netanyahu',
  'Yasser Arafat',
  'Mahmoud Abbas',
  'King Hussein',
  'King Abdullah II',
  'Hafez al-Assad',
  'Bashar al-Assad',
]
