export const CHARADES_AI_TECH: readonly string[] = [
  'Artificial Intelligence',
  'Machine Learning',
  'Neural Network',
  'Deep Learning',
  'Generative AI',
  'Computer Vision',
  'Speech Recognition',
  'Face Recognition',
  'Voice Assistant',
  'Recommendation Engine',
  'Predictive Text',
  'Image Generator',
  'AI Hallucination',
  'Language Model',
  'Digital Twin',
  'Pattern Recognition',
  'Natural Language Processing',
  'Text to Speech',
  'Motion Tracking',
  'Object Detection',
  'Voice Cloning',
  'Deepfake',
  'AI Agent',
  'Prompt Engineering',
  'Facial Filter',
  'Autocorrect',
  'Smart Home',
  'Smart Speaker',
  'Robot Vacuum',
  'Robot Dog',
  'Humanoid Robot',
  'Robotic Arm',
  'Desktop Computer',
  'Laptop',
  'Tablet',
  'Flip Phone',
  'Landline Phone',
  'Gaming Console',
  'Handheld Console',
  'Computer Monitor',
  'Touchscreen',
  'Computer Mouse',
  'Trackpad',
  'Webcam',
  'Microphone',
  'Headphones',
  'Earbuds',
  'Loudspeaker',
  'Printer',
  'Scanner',
  'Photocopier',
  'Projector',
  'Remote Control',
  'USB Drive',
  'Memory Card',
  'Hard Drive',
  'Solid-State Drive',
  'Circuit Board',
  'Computer Chip',
  'Processor',
  'Graphics Card',
  'Motherboard',
  'Cooling Fan',
  'Power Button',
  'Power Bank',
  'Charging Cable',
  'Wireless Charger',
  'Charging Port',
  'Headphone Jack',
  'USB Hub',
  'Docking Station',
  'Ethernet Cable',
  'Wi-Fi Router',
  'Modem',
  'Network Switch',
  'Server Rack',
  'Data Center',
  'Smart Glasses',
  'Fitness Tracker',
  'Digital Camera',
  'Action Camera',
  'Security Camera',
  'Doorbell Camera',
  'Dash Camera',
  'E-Reader',
  'Digital Alarm Clock',
  'Electronic Calculator',
  'Barcode Scanner',
  'Card Reader',
  'Contactless Payment',
  'Smart Thermostat',
  'Smart Light Bulb',
  'Streaming Stick',
  'Television Antenna',
  'Satellite Dish',
  'Weather Radar',
  'Radio Telescope',
  'Undersea Cable',
  'Cell Tower',
  'Supercomputer',
  'Quantum Computer',
  'Mechanical Keyboard',
  'Joystick',
  'Game Controller',
  'Stylus',
  'Laser Pointer',
  '3D Scanner',
  'Circuit Breaker',
  'Digital Whiteboard',
  'Biometric Scanner',
  'Fingerprint Sensor',
  'Iris Scanner',
  'Face Unlock',
  'Voice Control',
  'Gesture Control',
  'Window Resize',
  'Double Click',
  'Right Click',
  'Scrolling',
  'Swiping',
  'Pinch to Zoom',
  'Drag and Drop',
  'Copy and Paste',
  'Typing',
  'Voice Typing',
  'Logging In',
  'Logging Out',
  'Resetting a Password',
  'Two-Factor Authentication',
  'Scanning a Fingerprint',
  'Unlocking a Phone',
  'Answering a Call',
  'Ending a Call',
  'Muting a Call',
  'Screen Sharing',
  'Recording a Message',
  'Sending an Email',
  'Opening an Attachment',
  'Uploading a File',
  'Downloading a File',
  'Saving a Document',
  'Deleting a File',
  'Emptying the Trash',
  'Creating a Folder',
  'Renaming a File',
  'Printing a Document',
  'Scanning a Document',
  'Taking a Photo',
  'Cropping a Photo',
  'Editing a Video',
  'Buffering',
  'Loading Screen',
  'Progress Bar',
  'Pop-Up Window',
  'Drop-Down Menu',
  'Search Bar',
  'Home Screen',
  'Lock Screen',
  'Dark Mode',
  'Airplane Mode',
  'Silent Mode',
  'Push Notification',
  'Low Battery Warning',
  'Software Update',
  'Factory Reset',
  'Restarting a Computer',
  'Frozen Screen',
  'Cracked Screen',
  'Spinning Cursor',
  'Forgotten Password',
  'Wrong Password',
  'Lost Signal',
  'Weak Connection',
  'Dropped Call',
  'Computer Crash',
  'Blue Screen',
  'Error Message',
  'Broken Link',
  'Dead Pixel',
  'Pocket Dial',
  'Accidental Reply-All',
  'Computer File',
  'File Folder',
  'Recycle Bin',
  'Desktop Icon',
  'Cursor',
  'Web Browser',
  'Search Engine',
  'Website',
  'Hyperlink',
  'Browser Tab',
  'Bookmark',
  'Browsing History',
  'Private Browsing',
  'Web Cookie',
  'Browser Cache',
  'Source Code',
  'Computer Program',
  'Operating System',
  'User Interface',
  'Command Line',
  'Computer Bug',
  'Debugging',
  'Coding',
  'Binary Code',
  'Algorithm',
  'Database',
  'Spreadsheet',
  'Cloud Storage',
  'File Compression',
  'Zip File',
  'Open Source',
  'Version Control',
  'Code Review',
  'Software Patch',
  'Beta Test',
  'Domain Name',
  'Web Server',
  'IP Address',
  'Fiber Optics',
  'Broadband',
  'Hotspot',
  'Mobile Data',
  'Cloud Computing',
  'Edge Computing',
  'Bandwidth',
  'Latency',
  'Internet Outage',
  'Offline Mode',
  'Online Shopping',
  'Online Banking',
  'Online Classroom',
  'Remote Work',
  'File Sharing',
  'Wireless Network',
  'Public Wi-Fi',
  'Internet Cafe',
  'Smart City',
  'Internet of Things',
  'Cybersecurity',
  'Computer Virus',
  'Malware',
  'Ransomware',
  'Spyware',
  'Trojan Horse',
  'Phishing',
  'Spam Email',
  'Firewall',
  'Antivirus Software',
  'Data Breach',
  'Identity Theft',
  'Hacker',
  'Ethical Hacker',
  'Password Manager',
  'Security Question',
  'Encryption',
  'Privacy Settings',
  'Parental Controls',
  'Captcha',
  'Botnet',
  'Cyberattack',
  'Social Engineering',
  'Shoulder Surfing',
  'Data Backup',
  'Recovery Code',
  'Security Alert',
  'Virtual Private Network',
  'Warehouse Robot',
  'Delivery Robot',
  'Factory Robot',
  'Robot Surgeon',
  'Mars Rover',
  'Space Probe',
  'Reusable Rocket',
  'Electric Vehicle',
  'Charging Station',
  'Solar Roof',
  'Wind Turbine',
  'Smart Grid',
  'Home Automation',
  'Augmented Reality',
  'Mixed Reality',
  'Metaverse',
  'Haptic Feedback',
  'Motion Sensor',
  'Brain-Computer Interface',
  'Wearable Technology',
  'Bionic Hand',
  'Exoskeleton',
  'Prosthetic Limb',
  'Gene Editing',
  'Lab-Grown Meat',
  'Vertical Farming',
  'Nanotechnology',
  'Quantum Internet',
  'Blockchain',
  'Cryptocurrency',
  'Digital Wallet',
  'Non-Fungible Token',
  'LiDAR',
] as const
