export const CHARADES_MUSIC_GENRES: readonly string[] = [
  // African traditions and popular styles
  'Afrobeat',
  'Amapiano',
  'Jùjú',
  'Fuji',
  'Apala',
  'Palm-wine Music',
  'Hiplife',
  'Azonto',
  'Mbalax',
  'Soukous',
  'Makossa',
  'Bikutsi',
  'Taarab',
  'Benga',
  'Genge',
  'Singeli',
  'Kwaito',
  'Mbaqanga',
  'Maskanda',
  'Isicathamiya',
  'Mbube',
  'Gqom',
  'Chimurenga',
  'Zamrock',
  'Zouglou',
  'Coupé-décalé',
  'Gnawa',

  // South, East, and Southeast Asian traditions
  'Hindustani Classical',
  'Carnatic Music',
  'Dhrupad',
  'Khyal',
  'Thumri',
  'Ghazal',
  'Qawwali',
  'Filmi',
  'Bhangra',
  'Baul',
  'Rabindra Sangeet',
  'Bhatiali',
  'Lavani',
  'Gamelan',
  'Dangdut',
  'Keroncong',
  'Campursari',
  'Jaipongan',
  'Kecak',
  'Luk Thung',
  'Mor Lam',
  'Kantrum',
  'Pinoy Rock',
  'Manila Sound',
  'Kundiman',
  'V-pop',
  'Pinoy Pop',

  // East and Central Asian traditions
  'Gagaku',
  'Minyō',
  'Enka',
  'Kayōkyoku',
  'Shibuya-kei',
  'Japanese City Pop',
  'J-pop',
  'J-rock',
  'Trot',
  'Pansori',
  'Gugak',
  'Mandopop',
  'Cantopop',
  'Hokkien Pop',
  'Chinese Rock',
  'Yayue',
  'Qinqiang',
  'Mongolian Long Song',
  'Tuvan Throat Singing',
  'Maqom',
  'Shashmaqam',
  'Küy',
  'Estrada',
  'Anadolu Rock',
  'Arabesque Music',
  'Khaliji',
  'Dabke',

  // Caribbean and Latin American traditions
  'Calypso',
  'Soca',
  'Chutney Music',
  'Zouk',
  'Compas',
  'Rasin',
  'Bachata',
  'Merengue Típico',
  'Son Cubano',
  'Mambo',
  'Cha-cha-chá',
  'Bolero',
  'Timba',
  'Bomba',
  'Plena',
  'Reggaeton',
  'Dembow',
  'Cumbia',
  'Vallenato',
  'Champeta',
  'Joropo',
  'Huayno',
  'Chicha',
  'Cueca',
  'Nueva Canción',
  'Forró',
  'Bossa Nova',

  // More Latin American and Iberian styles
  'Samba',
  'Choro',
  'Axé',
  'Pagode',
  'Sertanejo',
  'Frevo',
  'Maracatu',
  'Carimbó',
  'Tecnobrega',
  'Manguebeat',
  'Tango',
  'Milonga',
  'Chamamé',
  'Murga',
  'Candombe',
  'Mariachi',
  'Ranchera',
  'Corrido',
  'Norteño',
  'Tejano',
  'Banda Sinaloense',
  'Son Jarocho',
  'Son Huasteco',
  'Punta Rock',
  'Flamenco',
  'Fado',
  'Catalan Rumba',

  // Middle Eastern, North African, and European traditions
  'Samri',
  'Andalusian Classical Music',
  'Malouf',
  'Raï',
  'Chaabi',
  'Aita',
  'Mizrahi Music',
  'Klezmer',
  'Sephardic Music',
  'Persian Classical Music',
  'Turkish Classical Music',
  'Ottoman Military Music',
  'Rebetiko',
  'Laïkó',
  'Éntekhno',
  'Skiladiko',
  'Turbo-folk',
  'Sevdalinka',
  'Chalga',
  'Manele',
  'Csárdás',
  'Polka',
  'Schlager',
  'Dansband',
  'Joik',
  'Celtic Music',
  'Nordic Folk Music',

  // Western classical and sacred forms
  'Baroque Music',
  'Renaissance Music',
  'Medieval Music',
  'Romantic Music',
  'Impressionist Music',
  'Expressionist Music',
  'Serialism',
  'Twelve-tone Music',
  'Minimalism',
  'Aleatoric Music',
  'Musique Concrète',
  'Chamber Music',
  'Choral Music',
  'Oratorio',
  'Cantata',
  'Motet',
  'Madrigal',
  'Gregorian Chant',
  'Ars Nova',
  'Bel Canto',
  'Verismo',
  'Operetta',
  'Singspiel',
  'Zarzuela',
  'Lied',
  'Neoclassical Music',
  'Spectral Music',

  // Electronic and dance styles
  'Ambient Music',
  'Drone Music',
  'New Age Music',
  'Trance',
  'Goa Trance',
  'Psytrance',
  'Hardstyle',
  'Gabber',
  'Breakbeat',
  'Big Beat',
  'Drum and Bass',
  'Jungle',
  'UK Garage',
  'Dubstep',
  'Grime',
  'Footwork',
  'Electro',
  'Synth-pop',
  'Industrial Music',
  'EBM',
  'Chillwave',
  'Vaporwave',
  'Future Bass',
  'Eurodance',
  'Hi-NRG',
  'Italo Disco',
  'Acid House',

  // Rock, metal, and punk subgenres
  'Alternative Rock',
  'Garage Punk',
  'Garage Rock',
  'Surf Rock',
  'Psychedelic Rock',
  'Progressive Rock',
  'Glam Rock',
  'Hard Rock',
  'Krautrock',
  'Shoegaze',
  'Dream Pop',
  'Post-rock',
  'Math Rock',
  'Gothic Rock',
  'New Wave',
  'Post-punk',
  'Hardcore Punk',
  'Pop Punk',
  'Ska Punk',
  'Emo',
  'Sludge Metal',
  'Thrash Metal',
  'Death Metal',
  'Black Metal',
  'Doom Metal',
  'Power Metal',
  'Metalcore',

  // Jazz, blues, soul, and diasporic styles
  'Ragtime',
  'Swing',
  'Bebop',
  'Cool Jazz',
  'Hard Bop',
  'Modal Jazz',
  'Free Jazz',
  'Jazz Fusion',
  'Latin Jazz',
  'Acid Jazz',
  'Smooth Jazz',
  'Boogie-woogie',
  'Delta Blues',
  'Chicago Blues',
  'Electric Blues',
  'Jump Blues',
  'Piedmont Blues',
  'Northern Soul',
  'Doo-wop',
  'Motown',
  'Neo Soul',
  'New Jack Swing',
  'Quiet Storm',
  'P-Funk',
  'Spirituals',
  'Barbershop Music',
  'Go-go',

  // North American roots, popular, and hip-hop styles
  'Old-time Music',
  'Cajun Music',
  'Zydeco',
  'Appalachian Music',
  'Western Swing',
  'Honky-tonk',
  'Rockabilly',
  'Americana',
  'Powwow Music',
  'Southern Gospel',
  'Power Pop',
  'Britpop',
  'Teen Pop',
  'Bubblegum Pop',
  'Inuit Throat Singing',
  'Hyperpop',
  'Hip House',
  'Boom Bap',
  'Gangsta Rap',
  'Conscious Hip-Hop',
  'Alternative Hip-Hop',
  'Cloud Rap',
  'Drill',
  'Crunk',
  'Bounce Music',
  'G-funk',
  'Nerdcore',
  'Chicano Rap',
  'Horrorcore',
  'Miami Bass',
]
