export const CHARADES_MUSIC_ARTISTS = [
  'Michael Jackson',
  'Beyoncé',
  'Elvis Presley',
  'Adele',
  'Elton John',
  'Madonna',
  'Whitney Houston',
  'Bob Marley',
  'Freddie Mercury',
  'Taylor Swift',
  'Ed Sheeran',
  'Justin Bieber',
  'Stevie Wonder',
  'Prince',
  'Tina Turner',
  'John Lennon',
  'Cher',
  'Shakira',
  'Celine Dion',
  'Mariah Carey',
  'Bruno Mars',
  'Katy Perry',
  'Lady Gaga',
  'Britney Spears',
  'Miley Cyrus',
  'Ariana Grande',
  'Billie Eilish',
  'Olivia Rodrigo',
  'Dua Lipa',
  'Harry Styles',
  'Justin Timberlake',
  'Christina Aguilera',
  'Jennifer Lopez',
  'Selena Gomez',
  'Avril Lavigne',
  'P!nk',
  'Sia',
  'Lorde',
  'Lana Del Rey',
  'Amy Winehouse',
  'George Michael',
  'Phil Collins',
  'Rod Stewart',
  'David Bowie',
  'Mick Jagger',
  'Paul McCartney',
  'Ringo Starr',
  'Diana Ross',
  'Janet Jackson',
  'Aretha Franklin',
  'Dolly Parton',
  'Barbra Streisand',
  'Cyndi Lauper',
  'Annie Lennox',
  'Kate Bush',
  'Enya',
  'Alanis Morissette',
  'Shania Twain',
  'Kelly Clarkson',
  'Carrie Underwood',
  'Robbie Williams',
  'Sam Smith',
  'Lizzo',
  'Doja Cat',
  'Sabrina Carpenter',
  'Chappell Roan',
  'The Weeknd',
  'Post Malone',
  'Shawn Mendes',
  'Camila Cabello',
  'Gwen Stefani',
  'Tracy Chapman',
  'Billy Joel',
  'Bruce Springsteen',
  'Bryan Adams',
  'Sting',
  'Seal',
  'Tom Jones',
  'Rick Astley',
  'The Beatles',
  'The Rolling Stones',
  'Queen',
  'ABBA',
  'U2',
  'Coldplay',
  'Maroon 5',
  'One Direction',
  'Spice Girls',
  'Backstreet Boys',
  'NSYNC',
  'Jonas Brothers',
  'Imagine Dragons',
  'The Killers',
  'Arctic Monkeys',
  'Oasis',
  'Radiohead',
  'Linkin Park',
  'Green Day',
  'Foo Fighters',
  'Nirvana',
  'Pearl Jam',
  'Red Hot Chili Peppers',
  'Bon Jovi',
  'Guns N\' Roses',
  'Aerosmith',
  'AC/DC',
  'Metallica',
  'Iron Maiden',
  'Black Sabbath',
  'Led Zeppelin',
  'Pink Floyd',
  'The Who',
  'The Doors',
  'The Beach Boys',
  'Bee Gees',
  'Fleetwood Mac',
  'Eagles',
  'Journey',
  'KISS',
  'Duran Duran',
  'Depeche Mode',
  'The Cure',
  'Paramore',
  'Fall Out Boy',
  'My Chemical Romance',
  'Panic! at the Disco',
  'Evanescence',
  'The Cranberries',
  'No Doubt',
  'Eurythmics',
  'The Police',
  'Wham!',
  'Eminem',
  'Drake',
  'Kanye West',
  'Jay-Z',
  'Snoop Dogg',
  'Dr. Dre',
  'Tupac Shakur',
  'The Notorious B.I.G.',
  'Kendrick Lamar',
  'J. Cole',
  'Nicki Minaj',
  'Cardi B',
  'Megan Thee Stallion',
  'Lil Wayne',
  '50 Cent',
  'Ice Cube',
  'LL Cool J',
  'Missy Elliott',
  'Lauryn Hill',
  'Queen Latifah',
  'Nas',
  'Pitbull',
  'Travis Scott',
  'Tyler, the Creator',
  'Childish Gambino',
  'A Tribe Called Quest',
  'Run-DMC',
  'Wu-Tang Clan',
  'Public Enemy',
  'OutKast',
  'Beastie Boys',
  'Salt-N-Pepa',
  'Fugees',
  'Destiny\'s Child',
  'TLC',
  'Boyz II Men',
  'Usher',
  'Chris Brown',
  'Alicia Keys',
  'Mary J. Blige',
  'John Legend',
  'Jason Derulo',
  'Pharrell Williams',
  'Lionel Richie',
  'Marvin Gaye',
  'Otis Redding',
  'James Brown',
  'Ray Charles',
  'Sam Cooke',
  'Al Green',
  'Chaka Khan',
  'Gladys Knight',
  'The Supremes',
  'The Temptations',
  'Earth, Wind & Fire',
  'Kool & the Gang',
  'Village People',
  'Johnny Cash',
  'Willie Nelson',
  'Patsy Cline',
  'Loretta Lynn',
  'Reba McEntire',
  'Garth Brooks',
  'George Strait',
  'Kenny Rogers',
  'Glen Campbell',
  'Tim McGraw',
  'Faith Hill',
  'Keith Urban',
  'Luke Combs',
  'Chris Stapleton',
  'Kacey Musgraves',
  'Zac Brown Band',
  'Brooks & Dunn',
  'The Chicks',
  'Hank Williams',
  'Sheryl Crow',
  'Alabama',
  'Bad Bunny',
  'Daddy Yankee',
  'Karol G',
  'J Balvin',
  'Maluma',
  'Ricky Martin',
  'Enrique Iglesias',
  'Gloria Estefan',
  'Luis Fonsi',
  'Marc Anthony',
  'Selena',
  'Carlos Santana',
  'Celia Cruz',
  'Héctor Lavoe',
  'Rubén Blades',
  'Juanes',
  'Juan Luis Guerra',
  'Romeo Santos',
  'Don Omar',
  'Ozuna',
  'Rosalía',
  'Becky G',
  'Maná',
  'Buena Vista Social Club',
  'Burna Boy',
  'Wizkid',
  'Davido',
  'Tems',
  'Rema',
  'Ayra Starr',
  'Asake',
  'Tyla',
  'Fela Kuti',
  'Angélique Kidjo',
  'Miriam Makeba',
  'Youssou N\'Dour',
  'Ali Farka Touré',
  'Hugh Masekela',
  'Black Coffee',
  'Sarkodie',
  'Tiwa Savage',
  'Yemi Alade',
  '2Baba',
  'King Sunny Adé',
  'Lucky Dube',
  'Amr Diab',
  'Fairuz',
  'BTS',
  'BLACKPINK',
  'PSY',
  'TWICE',
  'Stray Kids',
  'EXO',
  'SEVENTEEN',
  'Girls\' Generation',
  'A. R. Rahman',
  'Lata Mangeshkar',
  'Asha Bhosle',
  'Arijit Singh',
  'Diljit Dosanjh',
  'Jay Chou',
  'Hikaru Utada',
  'David Guetta',
  'Calvin Harris',
  'Tiësto',
  'Martin Garrix',
  'Marshmello',
  'Skrillex',
  'Steve Aoki',
  'Avicii',
  'Daft Punk',
  'The Chainsmokers',
  'DJ Snake',
  'Alan Walker',
  'Armin van Buuren',
  'Peggy Gou',
  'Deadmau5',
  'Wolfgang Amadeus Mozart',
  'Ludwig van Beethoven',
  'Johann Sebastian Bach',
  'Frédéric Chopin',
  'Pyotr Ilyich Tchaikovsky',
  'Antonio Vivaldi',
  'Miles Davis',
  'Louis Armstrong',
  'Ella Fitzgerald',
  'Nina Simone',
  'Frank Sinatra',
  'Andrea Bocelli',
  'Luciano Pavarotti',
] as const satisfies readonly string[]
