export const CHARADES_FOOD_DRINKS: readonly string[] = [
  'Paella',
  'Biryani',
  'Butter Chicken',
  'Chicken Tikka Masala',
  'Beef Wellington',
  'Fish and Chips',
  'Shepherd’s Pie',
  'Bangers and Mash',
  'Chicken Pot Pie',
  'Macaroni and Cheese',
  'Meatloaf',
  'Barbecue Ribs',
  'Buffalo Wings',
  'Chicken Nuggets',
  'Corn Dog',
  'Sloppy Joe',
  'Philly Cheesesteak',
  'Lobster Roll',
  'Clam Chowder',
  'Gumbo',
  'Jambalaya',
  'Shrimp and Grits',
  'Pulled Pork',
  'Poutine',
  'Pierogi',
  'Goulash',
  'Schnitzel',
  'Bratwurst',
  'Currywurst',
  'Fondue',
  'Raclette',
  'Moussaka',
  'Souvlaki',
  'Gyro',
  'Falafel',
  'Shawarma',
  'Hummus',
  'Baba Ganoush',
  'Tabbouleh',
  'Dolma',
  'Shakshuka',
  'Tagine',
  'Couscous',
  'Ful Medames',
  'Koshari',
  'Injera',
  'Doro Wat',
  'Bunny Chow',
  'Bobotie',
  'Egusi Soup',
  'Pounded Yam',
  'Suya',
  'Moi Moi',
  'Akara',
  'Fufu',
  'Groundnut Stew',
  'Thieboudienne',
  'Biltong',
  'Chapati',
  'Samosa',
  'Pakora',
  'Dosa',
  'Idli',
  'Chana Masala',
  'Palak Paneer',
  'Dal Makhani',
  'Aloo Gobi',
  'Vindaloo',
  'Rogan Josh',
  'Tandoori Chicken',
  'Naan',
  'Paratha',
  'Pani Puri',
  'Bhel Puri',
  'Pav Bhaji',
  'Vada Pav',
  'Kati Roll',
  'Nasi Lemak',
  'Roti Canai',
  'Laksa',
  'Char Kway Teow',
  'Hainanese Chicken Rice',
  'Satay',
  'Nasi Goreng',
  'Rendang',
  'Gado-Gado',
  'Lumpia',
  'Adobo',
  'Sinigang',
  'Lechon',
  'Sisig',
  'Pho',
  'Banh Mi',
  'Spring Rolls',
  'Pad Thai',
  'Green Curry',
  'Tom Yum',
  'Som Tam',
  'Mango Sticky Rice',
  'Bibimbap',
  'Kimchi',
  'Bulgogi',
  'Korean Barbecue',
  'Tteokbokki',
  'Kimbap',
  'Ramen',
  'Tempura',
  'Teriyaki Chicken',
  'Udon',
  'Soba',
  'Onigiri',
  'Okonomiyaki',
  'Takoyaki',
  'Miso Soup',
  'Dim Sum',
  'Peking Duck',
  'Kung Pao Chicken',
  'Sweet and Sour Pork',
  'Mapo Tofu',
  'Hot Pot',
  'Chow Mein',
  'Fried Rice',
  'Wonton Soup',
  'Scallion Pancake',
  'Congee',
  'Baozi',
  'Pupusa',
  'Arepa',
  'Empanada',
  'Tamale',
  'Quesadilla',
  'Enchiladas',
  'Burrito',
  'Nachos',
  'Churros',
  'Elote',
  'Esquites',
  'Guacamole',
  'Mole Poblano',
  'Pozole',
  'Ceviche',
  'Lomo Saltado',
  'Anticuchos',
  'Feijoada',
  'Pão de Queijo',
  'Coxinha',
  'Brigadeiro',
  'Asado',
  'Chimichurri',
  'Tres Leches Cake',
  'Flan',
  'Arroz con Leche',
  'Ropa Vieja',
  'Tostones',
  'Jerk Chicken',
  'Ackee and Saltfish',
  'Curry Goat',
  'Beef Patty',
  'Plantain Chips',
  'Arancini',
  'Lasagna',
  'Ravioli',
  'Risotto',
  'Gnocchi',
  'Carbonara',
  'Pesto',
  'Bruschetta',
  'Calzone',
  'Focaccia',
  'Baguette',
  'Croissant',
  'Quiche',
  'Crêpe',
  'Ratatouille',
  'French Onion Soup',
  'Croque Monsieur',
  'Spanish Omelette',
  'Gazpacho',
  'Patatas Bravas',
  'Croquettes',
  'Baklava',
  'Turkish Delight',
  'Pide',
  'Lahmacun',
  'Kebab',
  'Khachapuri',
  'Borscht',
  'Pelmeni',
  'Blini',
  'Cabbage Rolls',
  'Potato Latkes',
  'Bagel',
  'Pretzel',
  'Sourdough',
  'Pita',
  'Lavash',
  'Cornbread',
  'Biscuits and Gravy',
  'French Toast',
  'Eggs Benedict',
  'Avocado Toast',
  'Huevos Rancheros',
  'Hash Browns',
  'Oatmeal',
  'Granola',
  'Cereal',
  'Scrambled Eggs',
  'Poached Egg',
  'Deviled Eggs',
  'Caesar Salad',
  'Coleslaw',
  'Potato Salad',
  'Fruit Salad',
  'Mashed Potatoes',
  'Baked Potato',
  'Corn on the Cob',
  'Onion Rings',
  'French Fries',
  'Mozzarella Sticks',
  'Garlic Bread',
  'Trail Mix',
  'Energy Bar',
  'Potato Chips',
  'Rice Crackers',
  'Peanut Butter',
  'Maple Syrup',
  'Ketchup',
  'Mustard',
  'Mayonnaise',
  'Hot Sauce',
  'Soy Sauce',
  'Tzatziki',
  'Salsa Verde',
  'Harissa',
  'Mochi',
  'Cheesecake',
  'Brownie',
  'Apple Crumble',
  'Bread Pudding',
  'Banana Split',
  'Crème Brûlée',
  'Tiramisu',
  'Panna Cotta',
  'Cannoli',
  'Macaron',
  'Éclair',
  'Profiterole',
  'Pavlova',
  'Sticky Toffee Pudding',
  'Rice Pudding',
  'Gulab Jamun',
  'Jalebi',
  'Kulfi',
  'Halva',
  'Kunafa',
  'Mooncake',
  'Fortune Cookie',
  'Rambutan',
  'Pineapple',
  'Cantaloupe',
  'Papaya',
  'Dragon Fruit',
  'Passion Fruit',
  'Pomegranate',
  'Kiwi Fruit',
  'Strawberry',
  'Blueberry',
  'Peach',
  'Pear',
  'Grapes',
  'Plum',
  'Fig',
  'Cherry',
  'Jackfruit',
  'Lychee',
  'Guava',
  'Durian',
  'Bubble Tea',
  'Matcha',
  'Hot Chocolate',
  'Orange Juice',
  'Coconut Water',
  'Sugarcane Juice',
  'Mango Lassi',
  'Masala Chai',
  'Teh Tarik',
  'Horchata',
  'Agua Fresca',
  'Root Beer Float',
  'Egg Cream',
  'Slushie',
  'Kombucha',
  'Ayran',
  'Thai Iced Tea',
  'Vietnamese Coffee',
  'Espresso',
  'Cappuccino',
  'Fruit Punch',
  'Ginger Ale',
  'Sparkling Water',
]
