export const CHARADES_FOOTBALL_CLUBS: readonly string[] = [
  // Europe
  'Manchester United FC',
  'Manchester City FC',
  'Liverpool FC',
  'Arsenal FC',
  'Chelsea FC',
  'Tottenham Hotspur',
  'Newcastle United',
  'Aston Villa FC',
  'West Ham United',
  'Everton FC',
  'Leicester City FC',
  'Nottingham Forest',
  'Leeds United',
  'Wolverhampton Wanderers',
  'Crystal Palace',
  'Brighton & Hove Albion',
  'Southampton FC',
  'Sunderland AFC',
  'Blackburn Rovers',
  'Sheffield Wednesday',
  'Real Madrid CF',
  'FC Barcelona',
  'Atlético de Madrid',
  'Athletic Club',
  'Sevilla FC',
  'Real Betis',
  'Valencia CF',
  'Villarreal CF',
  'Real Sociedad',
  'Celta Vigo',
  'Deportivo La Coruña',
  'RCD Espanyol',
  'Real Zaragoza',
  'Rayo Vallecano',
  'CA Osasuna',
  'Juventus FC',
  'Inter',
  'AS Roma',
  'SS Lazio',
  'SSC Napoli',
  'Atalanta BC',
  'ACF Fiorentina',
  'Torino FC',
  'Bologna FC',
  'UC Sampdoria',
  'Genoa CFC',
  'Parma Calcio',
  'Hellas Verona',
  'US Palermo',
  'Udinese Calcio',
  'FC Bayern Munich',
  'Bayer Leverkusen',
  'RB Leipzig',
  'Eintracht Frankfurt',
  'Schalke 04',
  'Werder Bremen',
  'Hamburger SV',
  'VfB Stuttgart',
  'Borussia Mönchengladbach',
  'VfL Wolfsburg',
  'Paris Saint-Germain',
  'Olympique de Marseille',
  'Olympique Lyonnais',
  'AS Saint-Étienne',
  'LOSC Lille',
  'RC Lens',
  'Girondins de Bordeaux',
  'OGC Nice',
  'Stade Rennais',
  'FC Nantes',
  'SL Benfica',
  'FC Porto',
  'Sporting CP',
  'SC Braga',
  'Vitória SC',
  'Boavista FC',
  'AFC Ajax',
  'PSV Eindhoven',
  'Feyenoord',
  'AZ Alkmaar',
  'FC Twente',
  'Celtic FC',
  'Rangers FC',
  'Aberdeen FC',
  'Heart of Midlothian',
  'Hibernian FC',
  'Galatasaray SK',
  'Fenerbahçe SK',
  'Beşiktaş JK',
  'Olympiacos FC',
  'Panathinaikos FC',
  'Red Star Belgrade',
  'Dinamo Zagreb',
  'Sparta Prague',
  'Slavia Prague',
  'Legia Warsaw',
  'Shakhtar Donetsk',
  'Dynamo Kyiv',
  'RSC Anderlecht',
  'Club Brugge',
  'Standard Liège',
  'FC Basel',
  'Young Boys',
  'Red Bull Salzburg',
  'Rapid Wien',
  'Rosenborg BK',
  'Malmö FF',
  'FC Copenhagen',
  'Ferencvárosi TC',
  'FCSB',

  // Africa
  'Al Ahly SC',
  'Zamalek SC',
  'Pyramids FC',
  'Ismaily SC',
  'Espérance de Tunis',
  'Étoile du Sahel',
  'Club Africain',
  'Wydad AC',
  'Raja CA',
  'AS FAR',
  'RS Berkane',
  'Mamelodi Sundowns',
  'Orlando Pirates',
  'Kaizer Chiefs',
  'SuperSport United',
  'Cape Town City FC',
  'TP Mazembe',
  'AS Vita Club',
  'DC Motema Pembe',
  'ASEC Mimosas',
  'Africa Sports',
  'Asante Kotoko',
  'Accra Hearts of Oak',
  'Enyimba FC',
  'Kano Pillars',
  'Rangers International',
  'Shooting Stars SC',
  'Simba SC',
  'Young Africans SC',
  'Gor Mahia',
  'AFC Leopards',
  'Al Hilal Omdurman',
  'Al Merrikh SC',
  'CR Belouizdad',
  'JS Kabylie',
  'MC Alger',
  'Petro de Luanda',
  'Primeiro de Agosto',
  'Coton Sport',
  'Horoya AC',

  // Asia
  'Al Hilal SFC',
  'Al Nassr FC',
  'Al Ittihad Club',
  'Al Ahli Saudi FC',
  'Al Ain FC',
  'Shabab Al Ahli',
  'Sharjah FC',
  'Al Sadd SC',
  'Al Duhail SC',
  'Persepolis FC',
  'Esteghlal FC',
  'Sepahan SC',
  'Pakhtakor Tashkent',
  'FC Nasaf',
  'Urawa Red Diamonds',
  'Kashima Antlers',
  'Yokohama F. Marinos',
  'Kawasaki Frontale',
  'Gamba Osaka',
  'Vissel Kobe',
  'Jeonbuk Hyundai Motors',
  'Ulsan HD FC',
  'Pohang Steelers',
  'FC Seoul',
  'Shanghai Port FC',
  'Shanghai Shenhua',
  'Beijing Guoan',
  'Shandong Taishan',
  'Buriram United',
  'Muangthong United',
  'BG Pathum United',
  'Johor Darul Ta’zim',
  'Selangor FC',
  'Persib Bandung',
  'Persija Jakarta',
  'Lion City Sailors',
  'Mohun Bagan Super Giant',
  'East Bengal FC',
  'Mumbai City FC',
  'Sydney FC',

  // South America
  'Boca Juniors',
  'River Plate',
  'Racing Club',
  'Independiente',
  'San Lorenzo',
  'Estudiantes de La Plata',
  'Vélez Sarsfield',
  'Rosario Central',
  'Newell’s Old Boys',
  'Argentinos Juniors',
  'Flamengo',
  'Fluminense',
  'Palmeiras',
  'Corinthians',
  'São Paulo FC',
  'Santos FC',
  'Botafogo',
  'Vasco da Gama',
  'Grêmio',
  'SC Internacional',
  'Cruzeiro',
  'Atlético Mineiro',
  'Athletico Paranaense',
  'EC Bahia',
  'Peñarol',
  'Club Nacional de Football',
  'Defensor Sporting',
  'Danubio FC',
  'Colo-Colo',
  'Universidad de Chile',
  'Universidad Católica Chile',
  'Cobreloa',
  'Atlético Nacional',
  'Millonarios FC',
  'América de Cali',
  'Deportivo Cali',
  'Junior FC',
  'Independiente Santa Fe',
  'LDU Quito',
  'Independiente del Valle',
  'Barcelona SC',
  'Emelec',
  'Club Olimpia',
  'Cerro Porteño',
  'Club Libertad',
  'Alianza Lima',
  'Universitario de Deportes',
  'Sporting Cristal',
  'Club Bolívar',
  'The Strongest',

  // North America, Central America, and the Caribbean
  'Club América',
  'Chivas Guadalajara',
  'Cruz Azul',
  'Pumas UNAM',
  'Tigres UANL',
  'CF Monterrey',
  'Deportivo Toluca FC',
  'Club León',
  'CF Pachuca',
  'Club Tijuana',
  'Inter Miami CF',
  'LA Galaxy',
  'Los Angeles FC',
  'Seattle Sounders FC',
  'Atlanta United FC',
  'New York City FC',
  'New York Red Bulls',
  'Portland Timbers',
  'Columbus Crew',
  'Toronto FC',
  'Vancouver Whitecaps FC',
  'Deportivo Saprissa',
  'LD Alajuelense',
  'CS Herediano',
  'CSD Municipal',
  'Comunicaciones FC',
  'CD Olimpia',
  'Real España',
  'Alianza FC El Salvador',
  'Cibao FC',

  // Oceania
  'Auckland City FC',
  'Hekari United FC',
  'AS Pirae',
  'Rewa FC',
  'Ba FC',
  'Ifira Black Bird FC',
  'Solomon Warriors',
  'Hienghène Sport',
  'Tupapa Maraerenga FC',
  'Lupe o le Soaga',

  // Women's clubs with distinct team identities
  'Angel City FC',
  'NJ/NY Gotham FC',
  'San Diego Wave FC',
  'Kansas City Current',
  'Bay FC',
  'Racing Louisville FC',
  'North Carolina Courage',
  'Utah Royals FC',
  'Chicago Stars FC',
  'Seattle Reign FC',
  'Portland Thorns FC',
  'Washington Spirit',
  'OL Lyonnes',
  'Paris FC Féminines',
  'Chelsea Women',
  'Arsenal Women',
  'Manchester City Women',
  'FC Barcelona Femení',
  'VfL Wolfsburg Women',
  'Bayern Munich Women',
]
