export const CHARADES_INFLUENCERS: readonly string[] = [
  'MrBeast',
  'PewDiePie',
  'Dude Perfect',
  'KSI',
  'Logan Paul',
  'Jake Paul',
  'Sidemen',
  'Markiplier',
  'Jacksepticeye',
  'DanTDM',
  'VanossGaming',
  'Dream',
  'TommyInnit',
  'GeorgeNotFound',
  'Sapnap',
  'Technoblade',
  'PrestonPlayz',
  'Unspeakable',
  'Aphmau',
  'LDShadowLady',
  'SSSniperWolf',
  'Valkyrae',
  'Pokimane',
  'Ninja',
  'Shroud',
  'xQc',
  'Kai Cenat',
  'IShowSpeed',
  'Ibai Llanos',
  'Rubius',
  'AuronPlay',
  'TheGrefg',
  'JuanSGuarnizo',
  'Quackity',
  'ElMariana',
  'Gaules',
  'Alanzoka',
  'Cellbit',
  'Casimiro',
  'CarryMinati',
  'Total Gaming',
  'Techno Gamerz',
  'Mortal',
  'Dynamo Gaming',
  'Mythpat',
  'Tanmay Bhat',
  'Triggered Insaan',
  'BB Ki Vines',
  'Ashish Chanchlani',
  'Prajakta Koli',
  'Slayy Point',
  'KL Bro Biju',
  'Village Cooking Channel',
  'Mr Indian Hacker',
  'Dhruv Rathee',
  'Sourav Joshi',
  'Round2hell',
  'Amit Bhadana',
  'Harsh Beniwal',
  'Fukra Insaan',
  'Flying Beast',
  'Zach King',
  'Khaby Lame',
  "Charli D'Amelio",
  'Addison Rae',
  'Bella Poarch',
  'Brittany Broski',
  'Wisdom Kaye',
  'Alix Earle',
  'Drew Afualo',
  'Keith Lee',
  'Reece Feldman',
  'Brooke Monk',
  'Michael Le',
  'Spencer X',
  'Avani Gregg',
  'Noah Beck',
  'Quen Blackwell',
  'Chris Olsen',
  'Jake Shane',
  'Tefi Pessoa',
  'Nara Smith',
  'Haley Kalil',
  'Anna Sitar',
  'Kallmekris',
  'CelinaSpookyBoo',
  'Alan Chikin Chow',
  'Kinigra Deon',
  'Jordan Matter',
  'Rebecca Zamolo',
  'Brent Rivera',
  'Ben Azelart',
  'Lexi Rivera',
  'Pierson Wodzynski',
  'Stokes Twins',
  'Royalty Family',
  'Niana Guerrero',
  'Ranz Kyle',
  'Cong TV',
  'Mimiyuuuh',
  'Wil Dasovich',
  'Erwan Heussaff',
  'Hikakin',
  'Hajime Syacho',
  'Fischer’s',
  'Kemio',
  'Naenano',
  'Marina Takewaki',
  'Sagawa',
  'Bayashi',
  'Junya',
  'Seikin',
  'Heisei Flamingo',
  'Pony Syndrome',
  'Risabae',
  'Korean Englishman',
  'Ddotty',
  'Pani Bottle',
  'Q2Han',
  'Edward Avila',
  'Maangchi',
  'Seonkyoung Longest',
  'Ryan Higa',
  'Wengie',
  'Lachlan',
  'LazarBeam',
  'Loserfruit',
  'Muselk',
  'HowToBasic',
  'RackaRacka',
  'Superwog',
  'Ann Reardon',
  'Chloe Ting',
  'Sarah’s Day',
  'Ozzy Man Reviews',
  'Mr Sunday Movies',
  'Cold Ones',
  'Yes Theory',
  'Casey Neistat',
  'Emma Chamberlain',
  'Liza Koshy',
  'David Dobrik',
  'Safiya Nygaard',
  'Ryan Trahan',
  'MKBHD',
  'Mrwhosetheboss',
  'Linus Tech Tips',
  'iJustine',
  'Unbox Therapy',
  'Austin Evans',
  'JerryRigEverything',
  'UrAvgConsumer',
  'Sara Dietschy',
  'SuperSaf',
  'Dave2D',
  'Tech Burner',
  'Geekyranjit',
  'C4ETech',
  'Technical Guruji',
  'Trakin Tech',
  'Beebom',
  'Hank Green',
  'John Green',
  'Vsauce',
  'Veritasium',
  'SmarterEveryDay',
  'Mark Rober',
  'Physics Girl',
  'AsapSCIENCE',
  'Kurzgesagt',
  'CrashCourse',
  'Tom Scott',
  'CGP Grey',
  'Numberphile',
  'MinutePhysics',
  'SciShow',
  'Doctor Mike',
  'Mama Doctor Jones',
  'Medlife Crisis',
  'LegalEagle',
  'Coffeezilla',
  'Johnny Harris',
  'Cleo Abram',
  'Nas Daily',
  'Jay Shetty',
  'Ali Abdaal',
  'Thomas Frank',
  'Matt D’Avella',
  'Michelle Khare',
  'Marina Mogilko',
  'Lingualizer',
  'Easy Languages',
  'Rachel’s English',
  'LearnoHub',
  'Khan Sir',
  'Amoeba Sisters',
  'James Hoffmann',
  'Babish',
  'Joshua Weissman',
  'Nick DiGiovanni',
  'Rosanna Pansino',
  'Emmymade',
  'Max Miller',
  'Andy Cooks',
  'Doobydobap',
  'Uncle Roger',
  'Tabitha Brown',
  'Matty Matheson',
  'Sorted Food',
  'Chef RV Manabat',
  'Mark Wiens',
  'Best Ever Food Review Show',
  'Strictly Dumpling',
  'The Food Ranger',
  'Abir El Saghir',
  'Amaury Guichon',
  'Cédric Grolet',
  'James Charles',
  'Jeffree Star',
  'NikkieTutorials',
  'Jackie Aina',
  'Patrick Starrr',
  'Manny MUA',
  'Bretman Rock',
  'Huda Kattan',
  'Desi Perkins',
  'RawBeautyKristi',
  'Robert Welsh',
  'Brad Mondo',
  'Guy Tang',
  'Chris Appleton',
  'Brittany Xavier',
  'Camila Coelho',
  'Aimee Song',
  'Chiara Ferragni',
  'Leonie Hanne',
  'Tamara Kalinic',
  'Komal Pandey',
  'Masoom Minawala',
  'Dolly Singh',
  'Sakshi Sindwani',
  'Nancy Tyagi',
  'Patricia Bright',
  'Nyma Tang',
  'Dimma Umeh',
  'Temi Otedola',
  'Shalom Blac',
  'Nyane Lebajoa',
  'Mihlali Ndamase',
  'Lasizwe',
  'Wabosha Maxine',
  'Elsa Majimbo',
  'Azziad Nasenya',
  'KieKie',
  'Taaooma',
  'Mr Macaroni',
  'Broda Shaggi',
  'Sabinus',
  'Mark Angel',
  'Emmanuella',
  'Wode Maya',
  'Kwadwo Sheldon',
  'Miss Trudy',
  'Tayo Aina',
  'Trevor Stuurman',
  'Angella Summer Namubiru',
  'Adriene Mishler',
  'Cassey Ho',
  'Pamela Reif',
  'Joe Rogan',
  'Alex Cooper',
  'Steven Bartlett',
  'Mel Robbins',
  'Theo Von',
  'Hasan Piker',
  'Philip DeFranco',
  'Anthony Padilla',
  'Rhett and Link',
  'Dhar Mann',
  'MatPat',
  'Jaiden Animations',
  'TheOdd1sOut',
  'Lilly Singh',
  'Lele Pons',
  'Juanpa Zurita',
  'Luisito Comunica',
  'Yuya',
  'Kimberly Loaiza',
  'Domelipa',
  'Yeri Mua',
  'Whindersson Nunes',
  'Felipe Neto',
  'Lucas Rangel',
  'Virginia Fonseca',
  'Bianca Andrade',
  'Hugo Décrypte',
  'Squeezie',
  'Léna Situations',
  'Cyprien',
  'Inoxtag',
]
