export const DINNER_TABLE_TEAM_PROMPTS = [
  "What is something small that helped you feel welcome on a team?",
  "What kind of greeting helps you settle into a group gathering?",
  "What is an easy topic you enjoy chatting about during a break?",
  "What everyday detail has made you smile recently?",
  "What is a simple comfort you would happily recommend to the table?",
  "What kind of shared meal makes conversation feel especially easy?",
  "What is a low-key way a group can help a new person feel included?",
  "What is one pleasant part of your usual workday rhythm?",
  "What harmless subject can you talk about with almost anyone?",
  "What is a tiny ritual that helps a group gathering begin warmly?",

  "What strength do you appreciate in people who bring calm to a team?",
  "What useful quality often goes unnoticed in group work?",
  "What kind of contribution makes a team feel more capable?",
  "When have you seen patience improve a shared task?",
  "What strength can turn a confusing moment into a manageable one?",
  "What quality helps someone make space for quieter voices?",
  "What talent would you enjoy seeing more often in team settings?",
  "What kind of behind-the-scenes effort deserves more appreciation?",
  "Which strength becomes especially valuable when plans change?",
  "What is a generous way to recognize a teammate's skill?",

  "What working condition helps you do thoughtful work?",
  "How do you like people to share context when starting something together?",
  "What makes a request feel clear and manageable to you?",
  "How do you prefer to keep track of decisions made by a group?",
  "What kind of preparation helps you contribute confidently to a discussion?",
  "How do you like to signal that you need time to think?",
  "What meeting habit helps you stay engaged?",
  "What balance between structure and flexibility works well for you?",
  "How do you prefer to receive a reminder about a shared commitment?",
  "What helps you switch between focused work and collaboration?",

  "What makes a group conversation feel safe enough for unfinished ideas?",
  "How can a team invite disagreement without making it personal?",
  "What phrase can make it easier to ask a basic question?",
  "What helps people admit uncertainty without losing momentum?",
  "How can a group respond kindly when someone changes their mind?",
  "What makes it easier to say that a plan needs clarification?",
  "How can teammates show curiosity when perspectives differ?",
  "What ground rule helps everyone participate without pressure?",
  "How can a group make room for someone who prefers to listen first?",
  "What response encourages people to raise concerns early?",

  "What is a helpful way to learn how a new teammate works?",
  "What question reveals useful skills without putting someone on the spot?",
  "How can a team share unwritten knowledge more openly?",
  "What helps a person learn a process without feeling rushed?",
  "What is one kind way to explain a team custom to someone new?",
  "How can experienced teammates stay curious about a newcomer's perspective?",
  "What makes an introduction to a new project genuinely useful?",
  "How can a team make it normal to ask where something is documented?",
  "What is a welcoming way to offer help without assuming it is needed?",
  "What can a new team member notice that others may have stopped seeing?",

  "What is a lesson you learned from trying a new way of working?",
  "What kind of mistake can be especially useful for learning?",
  "How do you know when practice is turning into progress?",
  "What helps you stay curious when a task feels unfamiliar?",
  "What is a skill you would enjoy learning alongside other people?",
  "How can a team make experiments feel worthwhile even when they fail?",
  "What is a good way to share a lesson while it is still fresh?",
  "When does watching someone else work teach more than instructions do?",
  "What learning resource have you found surprisingly engaging?",
  "How can teammates celebrate improvement without expecting perfection?",

  "What makes collaboration feel energizing rather than crowded?",
  "How can two people divide a task while staying connected?",
  "What is a sign that a group is coordinating well?",
  "When is pairing up especially helpful?",
  "What helps a team combine ideas without losing their best parts?",
  "How can collaborators check alignment before doing too much work?",
  "What makes handing off a task feel smooth?",
  "How can a group avoid leaving coordination to one person?",
  "What kind of update helps others contribute at the right moment?",
  "How can teammates recover when they have been working from different assumptions?",

  "What specific kind of thanks feels meaningful in a team?",
  "Whose type of contribution is easy to overlook during a busy week?",
  "How can appreciation be expressed without making someone uncomfortable?",
  "What team effort would you put in a small imaginary hall of fame?",
  "What is a thoughtful way to celebrate steady reliability?",
  "How can a group recognize progress before a project is finished?",
  "What kind of compliment helps people understand their positive impact?",
  "When has someone made your work easier in a way they may not have noticed?",
  "What is worth celebrating even if it never appears in a final result?",
  "How can teammates make gratitude part of ordinary work rather than a special event?",

  "What playful constraint could spark fresh ideas for a familiar challenge?",
  "If this team had a mascot for curiosity, what might it be and why?",
  "What ordinary object could inspire a clever team ritual?",
  "How would you redesign a meeting if it had to happen without chairs?",
  "What imaginary award would bring out this team's sense of humor?",
  "If a current process were a board game, what would its trickiest square be?",
  "What would a deliberately over-the-top version of a team celebration include?",
  "Which unlikely setting might inspire a fresh approach to collaboration?",
  "If the team could borrow one feature from a great kitchen, what would help most?",
  "What creative theme could make a routine planning session more memorable?",

  "What helps you protect concentration without seeming unavailable?",
  "How can teammates make it comfortable to decline a nonessential request?",
  "What is a respectful way to check whether now is a good time to talk?",
  "How can a group honor different levels of social energy?",
  "What boundary helps shared work remain sustainable?",
  "How can people clarify urgency without treating everything as urgent?",
  "What makes it easier to pause a conversation and return to it later?",
  "How can a team support someone taking a genuine break?",
  "What is a considerate way to handle messages outside agreed working times?",
  "How can colleagues offer choices without creating pressure to say yes?",

  "What is one team habit that could become lighter or simpler?",
  "Where might a five-minute improvement save repeated effort?",
  "What question should a team revisit every few months?",
  "How can a group notice that an old process no longer fits?",
  "What would make the next shared project easier to begin?",
  "What small change could improve the flow of information?",
  "How can a team test an improvement without overcommitting to it?",
  "What is a useful signal that a new habit is working?",
  "Which recurring frustration might contain a practical improvement idea?",
  "How can a team keep a good change from quietly fading away?",

  "What makes a meeting feel worth the time it takes?",
  "How could an agenda invite participation from different thinking styles?",
  "What is a useful reason to end a meeting early?",
  "How can a facilitator make transitions between topics smoother?",
  "What helps a group distinguish discussion from decision time?",
  "How can people contribute when they do not have an immediate answer?",
  "What meeting role would be useful to rotate among teammates?",
  "How can a team prevent the final minutes from becoming rushed?",
  "What is a friendly way to bring a wandering conversation back on track?",
  "Which information is most helpful to share before a meeting begins?",

  "What makes a decision process feel understandable even when your idea is not chosen?",
  "How can a team tell when it has enough information to move forward?",
  "What helps groups separate preferences from requirements?",
  "How can teammates make tradeoffs visible without making them dramatic?",
  "What is a fair way to hear several viewpoints before deciding?",
  "When is a reversible decision especially useful?",
  "How can a group record why it chose a particular direction?",
  "What question can reveal a hidden assumption in a decision?",
  "How should a team revisit a choice when circumstances change?",
  "What makes it easier to support a group decision after honest disagreement?",

  "What communication detail prevents unnecessary confusion?",
  "How can someone ask for context without sounding critical?",
  "What makes a written update easy to absorb?",
  "How do you prefer people to distinguish information from action items?",
  "What is a useful way to confirm that two people understood each other?",
  "How can a team communicate a delay without creating alarm?",
  "What helps a message feel warm while staying concise?",
  "When is a quick conversation better than a long thread?",
  "How can teammates reduce jargon when sharing specialized knowledge?",
  "What question helps uncover what someone means by 'done'?",

  "What kind of feedback helps you decide what to try next?",
  "How can someone ask permission before offering a suggestion?",
  "What makes praise useful as well as encouraging?",
  "How can teammates discuss an idea's limitations without discouraging its creator?",
  "What is a constructive way to request a second look?",
  "How can feedback focus on the work while respecting the person?",
  "What helps people receive input when they are still exploring?",
  "How can a group normalize saying which kind of feedback is wanted?",
  "What makes a suggestion easier to consider rather than defend against?",
  "How can someone close a feedback conversation with clarity?",

  "What does dependable follow-through look like in everyday team life?",
  "How can a teammate flag a risk before it becomes a surprise?",
  "What helps people make realistic commitments?",
  "How can a group respond when priorities compete?",
  "What is a respectful way to renegotiate a deadline?",
  "How can teammates make ownership clear without becoming territorial?",
  "What kind of progress note builds trust?",
  "How can a team distinguish a promise from a possibility?",
  "What supports accountability without creating blame?",
  "How can people acknowledge a missed commitment and reset constructively?",

  "What helps a team stay steady when plans suddenly change?",
  "How can people preserve what matters while adapting the details?",
  "What is a useful first question when a surprise arrives?",
  "How can a group keep change from overwhelming the whole conversation?",
  "What helps teammates identify what is still known during uncertainty?",
  "How can humor support a tense moment without dismissing concerns?",
  "What is one way to create breathing room before reacting?",
  "How can a team learn from a detour that was nobody's fault?",
  "What makes a backup plan practical rather than pessimistic?",
  "How can teammates help one another regain momentum after disruption?",

  "What kind of role do you naturally enjoy in a shared project?",
  "What role would you like to try when the stakes are low?",
  "How can a team match tasks with energy as well as skill?",
  "What makes it comfortable to ask for a role adjustment?",
  "How can people avoid confusing visibility with value?",
  "What role helps a group notice details it might otherwise miss?",
  "How can a team share routine responsibilities fairly?",
  "What is a good way to invite volunteers without relying on the same people?",
  "How can teammates make room for both specialists and generalists?",
  "What helps someone step back from a role they have outgrown?",

  "What is a good question for understanding who is affected by a team decision?",
  "How can a group make participation possible in more than one format?",
  "What helps people avoid assuming everyone has the same resources?",
  "How can a team notice whose perspective is missing without putting anyone on display?",
  "What is one way to make shared language more accessible?",
  "How can teammates respect names and pronunciation with care?",
  "What scheduling practice can include people with different constraints?",
  "How can a group welcome a perspective that challenges its usual approach?",
  "What makes an invitation feel genuine rather than symbolic?",
  "How can a team design activities that do not depend on personal disclosure?",

  "What question brings a useful lesson out of a completed project?",
  "How can a team reflect without turning the conversation into a search for fault?",
  "What is worth documenting while memories are fresh?",
  "How can a group notice success that was not part of the original plan?",
  "What helps people talk honestly about a process that felt difficult?",
  "How can a retrospective produce one realistic next step?",
  "What is a fair way to discuss factors outside the team's control?",
  "How can teammates compare expectations with what actually happened?",
  "What would make project reflection feel useful rather than ceremonial?",
  "How can a team carry a lesson forward without creating a rigid rule?",

  "What helps trust grow through ordinary interactions?",
  "How can teammates show that a question is welcome?",
  "What makes it easier to rely on someone's update?",
  "How can a group repair a minor misunderstanding before it grows?",
  "What everyday action communicates respect?",
  "How can consistency make collaboration feel safer?",
  "What helps people be candid without being harsh?",
  "How can a teammate show care while respecting privacy?",
  "What behavior signals that someone will handle shared information responsibly?",
  "How can a group rebuild rhythm after trust has been lightly strained?",

  "What kind of question opens a conversation without steering the answer?",
  "How can curiosity improve a routine task?",
  "What topic would you enjoy hearing a teammate explain simply?",
  "How can a group reward thoughtful questions, not just quick answers?",
  "What is something familiar that becomes interesting when viewed differently?",
  "How can teammates investigate a hunch without treating it as fact?",
  "What question might reveal an overlooked possibility?",
  "When has changing the question changed the direction of the work?",
  "How can a team stay curious after it finds a workable answer?",
  "What would you examine first if time for exploration suddenly doubled?",

  "What helps a group focus on the people it aims to serve?",
  "How can teammates check whether a solution is useful in real life?",
  "What is a respectful way to learn from community members' experiences?",
  "How can a team avoid mistaking its own convenience for another person's need?",
  "What question keeps purpose visible during detailed work?",
  "How can people respond when users value something the team did not expect?",
  "What makes listening to community feedback feel genuine?",
  "How can a group balance immediate requests with longer-term benefit?",
  "What is one way to share decisions back with people who offered input?",
  "How can a team notice unintended effects of a well-meant idea?",

  "What gives a team enough energy to keep going during a long project?",
  "How can people notice when the pace is becoming hard to sustain?",
  "What kind of pause can improve the quality of later work?",
  "How can a group plan around energy instead of assuming it is constant?",
  "What small reset helps after an intense stretch of collaboration?",
  "How can teammates protect recovery time after a major push?",
  "What makes a workload conversation practical and safe?",
  "How can a team reduce unnecessary urgency?",
  "What routine helps maintain momentum without exhausting people?",
  "How can people encourage rest without asking anyone to justify it?",

  "What does helpful support look like when someone is learning a task?",
  "How can a teammate offer backup without taking over?",
  "What makes it easy to ask for an extra pair of eyes?",
  "How can a group share the load when one area becomes unexpectedly busy?",
  "What is a considerate way to check what kind of help would be useful?",
  "How can people support a colleague while preserving that person's choices?",
  "What resource is often more useful than advice?",
  "How can a team make mutual help feel normal rather than exceptional?",
  "What helps people accept assistance without feeling indebted?",
  "How can teammates tell the difference between support and interruption?",

  "What possibility for this team would be exciting to explore next?",
  "What capability could the group build gradually over the coming year?",
  "How would you like collaboration to feel different six months from now?",
  "What future challenge could become an interesting learning opportunity?",
  "What should the team preserve as it grows or changes?",
  "How can today's small improvement create more options later?",
  "What would make future newcomers glad they joined this team?",
  "Which emerging idea deserves a little space to develop?",
  "What could the group become known for through consistent practice?",
  "What hopeful sign would show that the team is moving in a good direction?",

  "What object on this table could represent a useful team quality?",
  "If teamwork had a flavor, what would a balanced version taste like?",
  "What menu item best resembles a project with many contributors, and why?",
  "If each meeting needed a secret ingredient, what would you choose?",
  "What can sharing food teach us about making room for different preferences?",
  "If this table could give the team one piece of advice, what might it say?",
  "What part of preparing a meal offers a useful collaboration metaphor?",
  "If a team plan were a recipe, which instruction would deserve extra attention?",
  "What does a good host do that a good facilitator could borrow?",
  "Which kitchen tool best symbolizes dependable teamwork, and what is your reasoning?",

  "What would make an ordinary team day feel unexpectedly delightful?",
  "What harmless tradition could add more laughter to shared work?",
  "What kind of surprise helps a group feel appreciated?",
  "How can teammates make routine moments a little more human?",
  "What is a playful way to welcome a fresh idea?",
  "What small detail can transform the mood of a shared space?",
  "How could a team add joy without adding another obligation?",
  "What wholesome competition could be fun even for people who do not win?",
  "What funny but kind title could describe a common team moment?",
  "What would a perfect five-minute team break look like?",

  "What value becomes visible through a team's everyday choices?",
  "How can a group turn a stated value into a practical habit?",
  "What principle helps when speed and care pull in different directions?",
  "How can teammates notice when their actions no longer match their intentions?",
  "What value should guide how a team handles limited resources?",
  "How can a group discuss competing priorities without questioning anyone's character?",
  "What does fairness look like when people's needs are different?",
  "How can a team keep respect visible during a difficult decision?",
  "What principle would you want reflected in every handoff?",
  "How can people make room for values to evolve through experience?",

  "What is one thoughtful question this team could ask more often?",
  "What conversation would help the group work together with greater ease?",
  "What is a simple idea from tonight that could be tried soon?",
  "How might the team keep useful meal-table conversations going afterward?",
  "What would help everyone leave a team gathering with clarity?",
  "What is one encouraging observation someone could carry into the next workday?",
  "How can a group close a conversation while leaving room for later thoughts?",
  "What would make the next team meal welcoming for a wider range of people?",
  "What is a gentle way to invite reflections after everyone has had time to think?",
  "What shared intention could give the team's next chapter a positive start?",
] as const
