export const DINNER_TABLE_EVERYDAY_PROMPTS = [
  "What caught your attention today that might have gone unnoticed on a busier day?",
  "Which ordinary sound do you find unexpectedly comforting?",
  "What small choice made today a little easier?",
  "What is something useful you learned by accident?",
  "Which part of your daily routine feels most like your own?",
  "What made you pause and look twice recently?",
  "How would you describe the pace of your day without using a number?",
  "What is one thing nearby that you appreciate more when you really notice it?",
  "Which everyday object has a design you admire?",
  "What detail tells you that a place is well cared for?",
  "What kind of weather brings out a different side of you?",
  "Which smell can improve your mood almost immediately?",
  "What did you notice on your way here?",
  "Where do you tend to find a quiet moment in a full day?",
  "What has felt pleasantly simple lately?",
  "Which color seems to be showing up often in your life right now?",
  "What is something familiar that you recently saw in a new way?",
  "Which tiny convenience would you miss more than you expect?",
  "What does a room need before it feels welcoming to you?",
  "What is the most interesting thing you have seen through a window lately?",
  "How does natural light change the mood of a place you know?",
  "What ordinary task gives you a surprising sense of satisfaction?",
  "What is one sign that tells you a day is going well?",
  "Which texture do you especially enjoy encountering?",
  "What is something in your surroundings that deserves a better name?",
  "What went slightly better than expected this week?",
  "Which recent effort are you glad you made, even if nobody noticed?",
  "What is a tiny problem you solved in a way that pleased you?",
  "What did you finish recently that had been quietly waiting for you?",
  "Which good decision has been paying off lately?",
  "What is one way you made life easier for your future self?",
  "What recent moment made you think, “I handled that well”?",
  "Which skill of yours showed up at a useful moment this week?",
  "What have you become faster or calmer at doing?",
  "What is a modest goal that feels good to complete?",
  "Which bit of progress would be easy to overlook but worth recognizing?",
  "What did you remember at exactly the right time?",
  "When did you last turn an awkward moment into an okay one?",
  "What is something you repaired, restored, or put back in order?",
  "Which recent choice saved you time, energy, or trouble?",
  "What is one thing you did today that deserves a quiet high-five?",
  "What have you kept going with longer than you expected?",
  "Which small risk worked out well for you recently?",
  "What did you make more enjoyable through your own effort?",
  "What is a recent example of good timing in your life?",
  "Which task feels lighter now than it did a few months ago?",
  "What did you say no to that created room for something better?",
  "What is a useful habit you have built without much fanfare?",
  "Which recent mistake helped you improve something practical?",
  "What are you quietly getting better at?",
  "What food do you enjoy most for its texture?",
  "Which flavor deserves more attention than it gets?",
  "What simple meal can you happily eat again and again?",
  "How do you like to make an everyday drink feel special?",
  "Which ingredient can transform a dish with very little effort?",
  "What food has a smell that is almost as enjoyable as its taste?",
  "Which snack has the most satisfying sound?",
  "What is your favorite contrast in a meal, such as hot and cold or crisp and soft?",
  "Which food did you learn to appreciate over time?",
  "What is a dish you enjoy differently depending on your mood?",
  "Which food is better in a humble version than a fancy one?",
  "What makes a meal feel complete to you?",
  "Which kitchen shortcut do you fully support?",
  "What is one food opinion you could cheerfully debate without needing to win?",
  "Which aroma belongs in your ideal kitchen?",
  "What is the best use for leftovers you have encountered?",
  "Which food do you prefer at an unusual time of day?",
  "What would you put on a plate designed to represent your current mood?",
  "Which bite of a meal do you tend to save for last?",
  "What small detail makes food feel thoughtfully prepared?",
  "Which fruit or vegetable is at its best with almost nothing added?",
  "What dish seems to invite the best conversation?",
  "Which food would you choose as the official taste of a rainy day?",
  "What is something you like to eat in your own particular way?",
  "Which meal taught you that simple can be memorable?",
  "What harmless topic could you give a five-minute speech about with no preparation?",
  "Which everyday rule would you rewrite for greater convenience?",
  "What deserves to be available in more colors?",
  "Which common phrase would make a funny title for a film?",
  "What is an unpopular preference you enjoy explaining?",
  "Which object should come with better instructions?",
  "What is something people often rush that is better taken slowly?",
  "Which minor inconvenience produces the most creative solutions?",
  "What everyday decision takes you longer than it probably should?",
  "Which item is worth paying a little more for, in your experience?",
  "What is something that works better the old-fashioned way?",
  "Which modern convenience do you think is genuinely delightful?",
  "What deserves its own tiny celebration?",
  "Which word is especially fun to say?",
  "What everyday situation could use a clearer etiquette rule?",
  "Which chore has the most satisfying before-and-after difference?",
  "What is something you prefer slightly imperfect?",
  "Which queue or waiting-room activity should become standard everywhere?",
  "What is your strongest harmless opinion about how to arrange a space?",
  "Which season has the best light?",
  "What is an item people should borrow more often instead of buying?",
  "Which ordinary product deserves a better package?",
  "What is more fun to choose than it has any right to be?",
  "Which social custom do you find genuinely useful?",
  "What small luxury lives up to the hype?",
  "What is a story you enjoy telling because of one perfect detail?",
  "When did a wrong turn lead you somewhere worthwhile?",
  "What is the funniest misunderstanding you can laugh about now?",
  "Which ordinary outing became unexpectedly memorable?",
  "What is a moment when a stranger made the day more interesting?",
  "When did you improvise a solution with whatever was available?",
  "What is a time you were surprised by your own patience?",
  "Which small adventure began with a casual suggestion?",
  "What is a memorable thing you once found?",
  "When did you arrive somewhere at exactly the right moment?",
  "What is a story behind something you still own?",
  "Which plan changed completely but still turned out well?",
  "What is a memorable compliment you received about something unexpected?",
  "When did you laugh at a moment that was not supposed to be funny?",
  "What is a time you learned the local way of doing something?",
  "Which errand has given you the best story?",
  "What is a moment when you felt instantly at ease in a new place?",
  "When did a simple question lead to a fascinating conversation?",
  "What is a story about lending or borrowing something?",
  "Which memory has a very clear soundtrack in your mind?",
  "What is a time you made something work without the proper tool?",
  "When did someone’s enthusiasm become contagious?",
  "What is a pleasant surprise that came from changing your usual plan?",
  "Which everyday mishap became funnier with time?",
  "What is a brief encounter you remember with unusual clarity?",
  "What subject has been feeding your curiosity lately?",
  "Which question would you ask someone who is excellent at their craft?",
  "What fact recently sent you down an interesting trail of reading or listening?",
  "Which skill looks effortless until you try it?",
  "What is something you understand better after seeing it done?",
  "Which topic could you happily learn through a guided tour?",
  "What have you become curious about simply because someone mentioned it?",
  "Which ordinary system would you like to see behind the scenes?",
  "What have you learned from someone with a very different routine from yours?",
  "Which kind of expert makes you want to ask endless questions?",
  "What is something you once found confusing that now seems clear?",
  "Which new word or idea have you enjoyed adding to your vocabulary?",
  "What can a beginner notice that an expert might overlook?",
  "Which process becomes more interesting when you know how it works?",
  "What is something you would enjoy learning purely for the pleasure of it?",
  "Which place would you explore with a knowledgeable local guide?",
  "What is a recent example of changing your approach after learning more?",
  "Which everyday mystery would you like explained in plain language?",
  "What is something another person taught you without realizing it?",
  "Which craft would you like to watch from start to finish?",
  "What is a topic where your questions have become better over time?",
  "Which piece of advice made sense only after you gained experience?",
  "What would you like to learn by doing rather than by reading?",
  "Which part of nature makes you most curious about how it works?",
  "What is a useful lesson you picked up from an unlikely source?",
  "If today had a title, what would you call it?",
  "What would a museum of ordinary life need to display?",
  "If your week were a landscape, what would it look like?",
  "Which everyday object would be most entertaining if it could offer commentary?",
  "What new flavor would you invent, and what would it taste like?",
  "If you could add one pleasant feature to your neighborhood, what would it be?",
  "What would you name a café designed around your favorite kind of atmosphere?",
  "If you could make one routine task happen in a more playful way, how would it work?",
  "Which animal would be the most surprising but competent shopkeeper?",
  "What would be included in a starter kit for a really good afternoon?",
  "If you designed a bench for lingering, where would you place it?",
  "What imaginary award would you be pleased to receive this month?",
  "If a scent could be saved like a photograph, which one would you keep?",
  "What would a map of your current interests look like?",
  "If you could give a friendly voice to one machine, which would you choose?",
  "What would you include in a time capsule of everyday life right now?",
  "If you opened a tiny shop for one day, what would it offer?",
  "What would make a public space feel a little more joyful?",
  "If your current mood were a kind of weather, what would be in the forecast?",
  "What would you choose as a mascot for taking things one step at a time?",
  "If you could create a new hour between two existing hours, how would you use it?",
  "What imaginary button would make one harmless part of life easier?",
  "If you designed a postcard for this stage of your life, what would be pictured?",
  "What would a festival celebrating small pleasures include?",
  "If you could hear one place wake up in the morning, where would you listen?",
  "Which song fits the energy you would like more of this week?",
  "What book would you enjoy discussing even with someone who had a different reaction?",
  "Which film setting would be interesting to visit for one afternoon?",
  "What piece of art has stayed in your mind longer than you expected?",
  "Which story taught you something without feeling like a lesson?",
  "What kind of live performance draws you in most easily?",
  "Which fictional character has a quality you appreciate?",
  "What song has an opening that immediately gets your attention?",
  "Which creative work feels connected to a particular time in your life?",
  "What is something made by hand that you love to look at?",
  "Which comedy style reliably makes you laugh?",
  "What story would you like to experience again without remembering the ending?",
  "Which building or public space feels like a work of art to you?",
  "What kind of music changes the way a room feels?",
  "Which illustration, photograph, or image have you returned to more than once?",
  "What makes a storyteller easy for you to listen to?",
  "Which creative hobby seems especially satisfying?",
  "What is a performance you remember for its atmosphere?",
  "Which familiar story would be fun to see from another character’s point of view?",
  "What is something you admire because it is beautifully made?",
  "Which title has made you curious before you knew anything else about the work?",
  "What creative choice can completely change your experience of a story?",
  "Which kind of exhibit could keep you browsing for hours?",
  "What artwork would you like to ask its creator about?",
  "Which sound belongs on a playlist of everyday life?",
  "What custom from a place you have visited or learned about struck you as thoughtful?",
  "Which local food would you recommend to someone curious about where you live?",
  "What is something people can learn about a place by using its public spaces?",
  "Which greeting or expression from another language do you enjoy?",
  "What makes you feel like a respectful guest somewhere new?",
  "Which market, street, or gathering place has shown you something about local life?",
  "What is a tradition you admire without needing to claim as your own?",
  "Which everyday habit varies interestingly from place to place?",
  "What can a meal reveal about the environment where it developed?",
  "Which place has changed the way you think about hospitality?",
  "What is a cultural detail you became curious about after encountering it in a story?",
  "Which everyday word has an interesting history or journey?",
  "What is something visitors often miss about a place you know well?",
  "Which form of public celebration do you find especially inviting?",
  "What can clothing communicate besides personal style?",
  "Which place would you like to understand beyond its famous sights?",
  "What is a considerate way to learn about a custom that is new to you?",
  "Which kind of shared meal creates a strong sense of place?",
  "What is something you appreciate about how another community organizes daily life?",
  "Which craft carries a story about where it comes from?",
  "What have you learned by hearing how another language describes a familiar idea?",
  "Which local recommendation has given you a more genuine experience of a place?",
  "What is one way travel close to home can still widen your perspective?",
  "Which public tradition would be interesting to observe with a good guide?",
  "What helps curiosity about other ways of living remain respectful?",
  "What kind gesture have you noticed someone offer recently?",
  "Which everyday comfort are you especially grateful for today?",
  "What is something reliable in your life that deserves more appreciation?",
  "Who made a routine moment easier for you lately, and how?",
  "What is one thing your body allowed you to experience today that you value?",
  "Which familiar place are you glad exists?",
  "What useful thing did someone take the time to explain to you?",
  "Which part of your day was improved by another person’s care?",
  "What is something in nature you never tire of seeing?",
  "Which ordinary resource, service, or tool made a difference for you this week?",
  "What is a kindness you enjoy passing along?",
  "Which person’s work quietly supports your daily life?",
  "What is something you can appreciate now that you once took for granted?",
  "Which recent conversation left you feeling lighter?",
  "What is a simple pleasure you are glad you did not outgrow?",
  "Which shared space do you appreciate when people treat it with care?",
  "What is something someone remembered about you that felt thoughtful?",
  "Which part of the natural world feels generous to you?",
  "What is a convenience created by people you will probably never meet?",
  "Which everyday act of cooperation gives you hope?",
  "What is something you received today, even if it was only time or attention?",
  "Which object has served you well for longer than expected?",
  "What is one aspect of the present moment you are glad to be part of?",
  "Which recent experience reminded you that people can be considerate?",
  "What is something good that became possible because someone shared what they knew?",
  "What has been taking up your attention in a good way?",
  "Which part of your current routine would you like to protect?",
  "What feels different about life this month compared with the last one?",
  "Which unfinished thing are you content to let unfold slowly?",
  "What is giving your days a bit of structure right now?",
  "Which recent change has started to feel normal?",
  "What are you making room for these days?",
  "Which part of your week feels most spacious?",
  "What is currently easier to enjoy because you stopped overcomplicating it?",
  "Which everyday responsibility feels meaningful to you?",
  "What are you paying closer attention to at the moment?",
  "Which boundary has helped your time feel more manageable?",
  "What is something you are approaching with fresh energy?",
  "Which area of life feels pleasantly steady right now?",
  "What have you been choosing more intentionally lately?",
  "Which recent pause helped you decide what mattered next?",
  "What is one thing you are happy to take day by day?",
  "Which part of your current season feels worth remembering?",
  "What has been a good use of your attention lately?",
  "Which obligation have you found a kinder way to handle?",
  "What is something you are enjoying without needing to improve it?",
  "Which current priority feels truly like yours?",
  "What has helped you feel present this week?",
  "Which everyday choice is reflecting what matters to you now?",
  "What is one part of life that feels comfortably ordinary at the moment?",
  "What would you like to have a little more time for next week?",
  "Which place nearby would you like to explore more slowly?",
  "What is a gentle goal that could make the coming days brighter?",
  "Which skill would you enjoy being slightly better at by this time next year?",
  "What experience would you like to say yes to when the chance appears?",
  "Which part of your surroundings would you like to make more comfortable?",
  "What is something you hope becomes easier with practice?",
  "Which conversation would you be glad to continue another day?",
  "What would you like to notice more often?",
  "Which small plan are you looking forward to carrying out?",
  "What is one thing you would enjoy making with your own hands?",
  "Which everyday pleasure would you like to build into your routine?",
  "What would make an upcoming morning feel especially good?",
  "Which curiosity would you like to follow further?",
  "What is a place you hope to revisit with more time?",
  "Which practical change could give you a little more breathing room?",
  "What would you like to become more confident doing?",
  "Which good habit would you like to make easier to return to?",
  "What is something pleasant you could plan without planning every detail?",
  "Which part of the year ahead are you curious to experience?",
  "What would you like to learn from the next person who knows something you do not?",
  "Which small project would feel satisfying to begin?",
  "What is a hope you can hold lightly, without needing to rush it?",
  "Which ordinary day in the future are you already looking forward to?",
  "What would you like your next free hour to contain?",
] as const
