export const DINNER_TABLE_HOLIDAY_GATHERING_PROMPTS = [
  'What seasonal tradition feels most meaningful to you, and what gives it that meaning?',
  'Which food makes a gathering feel festive to you, even if nobody else expects it?',
  'What is a celebration from your past that you remember mostly through its sounds?',
  'How would you describe the ideal welcome at a holiday gathering?',
  'What small detail helps you feel included when you join a celebration?',
  'Which scent instantly signals a special season or gathering to you?',
  'What is one tradition you enjoy adapting rather than following exactly?',
  'If this meal had a theme song, what kind of song would suit it?',
  'What dish would you be curious to learn from someone who makes it with care?',
  'Which part of preparing for a gathering is more enjoyable than people give it credit for?',
  'What does a generous host do that has nothing to do with spending money?',
  'What is a seasonal memory that still feels vivid when you picture it?',
  'How do you like to mark the end of one year or season and the start of another?',
  'What is the most comforting thing to eat or drink when the weather changes?',
  'Which decoration, color, or natural object makes a space feel celebratory to you?',
  'What makes a group meal memorable long after the food is gone?',
  'What is a tradition you discovered later in life and came to appreciate?',
  'If you could bottle one atmosphere from a past gathering, which would you choose?',
  'What kind of invitation makes you genuinely excited to attend?',
  'Which ordinary food deserves a place of honor at a festive table?',
  'What is your favorite way to contribute when someone else is hosting?',
  'How would you create a celebration for people who need a quiet, restful day?',
  'What is something this season has taught you to appreciate differently?',
  'Which gathering ritual helps people settle in and connect naturally?',
  'What story about a special meal do you never get tired of hearing?',
  'If everyone brought one flavor that represents home, what flavor would you bring?',
  'What is a holiday custom you would happily borrow, with respect, after learning its meaning?',
  'How can a gathering make room for people who celebrate differently?',
  'What simple pleasure feels especially good during a busy season?',
  'Which meal-preparation job would you claim first in a friendly kitchen?',
  'What is the most creative table setting or decoration you have seen?',
  'If you invented a seasonal drink, what would be in it and what would you call it?',
  'What makes a shared silence at a table feel comfortable rather than awkward?',
  'Which song would you add to a gathering playlist to lift the room?',
  'What is a useful lesson you learned from hosting or helping at an event?',
  'How do you prefer to balance familiar traditions with trying something new?',
  'What would make a celebration feel special without using any decorations?',
  'Which texture do you associate with a cozy or joyful gathering?',
  'What is one thing you are grateful someone made easier for you this year?',
  'If tonight became an annual tradition, what detail should stay the same?',
  'What is your favorite kind of story to hear around a table?',
  'How would you welcome a guest who arrived knowing nobody?',
  'What dish tastes even better because of who usually shares it with you?',
  'Which moment in a gathering tells you that everyone has begun to relax?',
  'What is a seasonal activity that deserves a slower pace?',
  'If you could add one new sense to experience celebrations, what would it detect?',
  'What kind of handmade offering feels especially thoughtful to receive?',
  'How has your idea of a meaningful celebration changed over time?',
  'What is a joyful way to honor people who cannot be at the table?',
  'Which part of a festive day would you happily skip, and what would you do instead?',
  'What local place feels most alive during a special season?',
  'If each person here designed one course, what course would you volunteer to create?',
  'What is a gathering mishap that became funny with enough time?',
  'How do you know when a tradition still serves the people practicing it?',
  'What is one kind thing a community can do during a celebratory season?',
  'Which sound belongs in your perfect dinner atmosphere?',
  'What recipe would you preserve in a community cookbook, and why?',
  'If you could give everyone at this table an extra hour, how would you hope they use it?',
  'What is something worth celebrating that rarely appears on a calendar?',
  'How would you describe the difference between a full schedule and a full heart?',
  'What is a playful tradition that people of many ages could enjoy together?',
  'Which seasonal expectation would you replace with a kinder one?',
  'What is your favorite way to make leftovers feel like a new meal?',
  'If this gathering had a signature color palette, which colors belong in it?',
  'What helps conversation flow when people at the table have different backgrounds?',
  'Which object would you place in a time capsule to represent this season?',
  'What does thoughtful giving look like when no physical present is involved?',
  'How can a host signal that guests are free to be themselves?',
  'What is a celebration you would like to understand more deeply?',
  'Which taste reminds you of being cared for?',
  'If you planned a feast around one ingredient, which ingredient would lead the menu?',
  'What small ritual helps you pause amid a crowded season?',
  'How would you make an outdoor gathering welcoming in your current weather?',
  'What is a tradition that began by accident and became worth keeping?',
  'Which part of cleaning up can become its own kind of togetherness?',
  'What would your ideal post-meal activity be tonight?',
  'If gratitude had a sound, what might it sound like?',
  'What is a thoughtful way to include someone joining a tradition for the first time?',
  'Which seasonal food do you enjoy in a completely unconventional way?',
  'What is a meaningful question to ask someone you have not seen in a while?',
  'How would you design a gathering where nobody has to perform happiness?',
  'What is a moment from this year that deserves a tiny toast?',
  'Which shared task has brought you unexpectedly close to other people?',
  'If the table could keep one story told tonight, what kind of story should it be?',
  'What makes a meal feel abundant besides the amount of food?',
  'How do changing seasons affect your energy or routines?',
  'What is a celebration-friendly game that requires almost no equipment?',
  'Which familiar tradition would be fun to experience in a completely new setting?',
  'What is the nicest way someone has remembered your preferences as a guest?',
  'Which overlooked quality deserves an annual celebration, and how would people observe it?',
  'What flavor combination feels like a celebration in one bite?',
  'How can people share gratitude without putting anyone on the spot?',
  'What is a favorite memory of people working together to prepare something?',
  'Which light—sunrise, candles, lanterns, city lights, or something else—feels most festive to you?',
  'What would you put on a menu designed entirely around comfort?',
  'If a celebration could happen at any hour, which hour would you choose and why?',
  'What is one way to make a gathering gentler for someone who feels overwhelmed?',
  'Which custom from your own experience would you enjoy explaining to a curious visitor?',
  'What is a beautiful example of resourcefulness you have seen during a celebration?',
  'How might a shared meal help neighbors become a community?',
  'What is a food opinion you can defend playfully without needing anyone to agree?',
  'If you were in charge of the centerpiece using only nearby objects, what would you make?',
  'What is a new ritual that could help people leave a gathering feeling connected?',
  'Which seasonal sound would you miss if it disappeared?',
  'What is something you learned from a celebration that was different from your own?',
  'How do you like people to show appreciation for food you have prepared?',
  'What would a celebration designed by your younger self include?',
  'Which part of a special meal is worth making from scratch, in your opinion?',
  'What can guests do to make hosting feel more shared?',
  'If you could send a plate from tonight to anyone, who would appreciate it and why?',
  'What is your favorite sign that a season is changing where you live?',
  'How would you celebrate a collective achievement in a way everyone could join?',
  'What is a kind response when someone declines an invitation or tradition?',
  'Which gathering memory is attached to a surprising location?',
  'What word would you like this season to feel like?',
  'If the kitchen had awards tonight, what funny categories should exist?',
  'What is a simple way to turn waiting for food into part of the fun?',
  'How can traditions evolve when the people around them change?',
  'What is something nature contributes to a celebration without being asked?',
  'Which item on a shared table invites the best conversation?',
  'What does a restful celebration look like from morning to evening?',
  'If you wrote a thank-you note to this past year, what would one line say?',
  'What is a way to give time that feels genuinely generous?',
  'Which cooking aroma should greet guests at the door?',
  'How would you help two guests with little in common find an easy starting point?',
  'What is a seasonal tradition best enjoyed alone sometimes?',
  'If everyone exchanged recommendations instead of objects, what would you recommend?',
  'What detail makes a table feel welcoming before anyone sits down?',
  'Which celebration from a book or film would you like to observe for an evening?',
  'What is one reason to gather that your community could use more often?',
  'How do you prefer to remember a meaningful event: photos, stories, keepsakes, or something else?',
  'What food would be the mascot of your ideal holiday gathering?',
  'If you could rename the busiest part of the season, what would you call it?',
  'What is a gentle tradition for acknowledging a difficult year?',
  'Which compliment would mean the most to someone who organized this meal?',
  'How can celebration and reflection share the same table?',
  'What is a funny kitchen habit you have noticed in yourself or others?',
  'If the weather outside became part of the menu, what dish would represent it?',
  'What is a non-food contribution that makes a dinner better?',
  'Which memory proves that a celebration does not need to go according to plan?',
  'What is a welcoming way to handle different dietary needs at one table?',
  'How would you turn a familiar seasonal chore into a small celebration?',
  'What is an everyday object that becomes special when used for gatherings?',
  'Which story from the past year would you like future you to remember?',
  'If you made a garland of meaningful moments, which moment would go first?',
  'What kind of generosity is easiest to overlook?',
  'How can a gathering leave the place or community better than it found it?',
  'What is your preferred balance of lively conversation and quiet pauses at dinner?',
  'Which seasonal treat would you redesign with an unexpected flavor?',
  'What is a question that helps people share without feeling pressured?',
  'If this meal were served somewhere outdoors, where would suit it best?',
  'What has someone taught you through the way they welcome people?',
  'Which part of a gathering would you photograph if you could take only one picture?',
  'What is a tradition you would like to make more accessible or flexible?',
  'How would you describe the taste of celebration without naming a specific food?',
  'What is the best use for an unexpectedly free day during a busy season?',
  'If you hosted a meal with one playful rule, what would the rule be?',
  'What is something people can make together even when their skills differ?',
  'Which natural material would you use to decorate a table sustainably?',
  'What does receiving well look like when someone offers help or hospitality?',
  'How would you include a moment of gratitude that allows people to pass?',
  'What is a favorite way to share food beyond sitting at a formal table?',
  'If your mood today were a seasonal dish, what would it be?',
  'What is one tradition that works better when kept simple?',
  'Which celebration skill would you like to learn: cooking, music, decorating, storytelling, or another?',
  'What would make a community feast feel fair and welcoming?',
  'How have travel, migration, or new neighbors influenced foods you enjoy?',
  'What is a meaningful way to celebrate someone who dislikes being the center of attention?',
  'If you designed place cards with one curious prompt, what would they ask?',
  'What seasonal soundscape would help you unwind?',
  'Which tiny luxury would you add to an otherwise simple meal?',
  'What is something worth passing down besides an object or recipe?',
  'How can people honor a tradition without insisting everyone participate?',
  'What is a good meal to cook when conversation matters more than presentation?',
  'If your favorite gathering memory had a title, what would it be?',
  'What is one thing a host can stop worrying about?',
  'Which shared experience creates connection faster than small talk for you?',
  'What would you serve at a celebration of fresh starts?',
  'How might children, elders, and everyone between shape a gathering differently?',
  'What is a festive use for something that might otherwise be discarded?',
  'If you could preserve one recipe technique for future generations, which would it be?',
  'What is a thoughtful way to check what guests need before they arrive?',
  'Which ordinary moment during a holiday feels secretly magical to you?',
  'What would you choose as the official scent of a new tradition?',
  'How do you make space for rest when celebrations create extra work?',
  'What is a gathering you enjoyed because it was smaller or simpler than expected?',
  'If tonight had a souvenir that was not an object, what should it be?',
  'What kind of story helps people understand where a tradition came from?',
  'Which food is most fun to assemble together at the table?',
  'What is a way to express care across distance during a special season?',
  'How would you plan a celebration around the night sky, daylight, rain, or wind?',
  'What is a communal tradition that could benefit from a modern update?',
  'If the meal could answer one question about us as a group, what should we ask it?',
  'What makes an invitation feel easy to accept or decline honestly?',
  'Which smell from a kitchen deserves its own poem?',
  'What is a subtle sign that someone has put care into hosting?',
  'How could a gathering celebrate both joy and people who are missed?',
  'What is the most satisfying sound involved in preparing food?',
  'If you created a seasonal scavenger hunt, what would people look for?',
  'What is a tradition that helps you notice the passage of time?',
  'Which way of serving food—shared plates, individual portions, buffet, picnic, or another—creates the mood you enjoy?',
  'What would a holiday for appreciating neighbors involve?',
  'How can guests help make a gathering environmentally thoughtful?',
  'What is a celebratory food you would happily eat for breakfast?',
  'If everyone contributed one line to a group blessing or good wish, what would yours focus on?',
  'What does belonging at a table feel like in practice?',
  'Which moment of preparation deserves to be enjoyed rather than rushed?',
  'What is a seasonal memory connected to water, heat, wind, or earth?',
  'How would you make a long meal engaging for people with different attention spans?',
  'What is an inventive way to share appreciation anonymously?',
  'If you could hear the history of one dish at this table, which would you choose?',
  'What is a gathering custom that encourages people to listen well?',
  'Which ingredient has traveled furthest through your food memories?',
  'What would you include in a care package made entirely of experiences?',
  'How do you distinguish a meaningful keepsake from clutter?',
  'What is a warm way to acknowledge a guest who helped behind the scenes?',
  'If a holiday gathering had intermission, what should happen during it?',
  'What is one thing you would like to savor before this season passes?',
  'Which table conversation topic reliably brings out people’s curiosity?',
  'What does enough look like during a season that often encourages more?',
  'How would you design a ritual for letting go of something from the past year?',
  'What is a festive dish that reflects the place where you currently live?',
  'If each chair at the table offered a different view, which view would you pick?',
  'What can music communicate at a gathering before anyone speaks?',
  'Which act of service feels most personal to you?',
  'What is a tradition that creates anticipation in a pleasant way?',
  'How could a gathering welcome people who arrive late or leave early?',
  'What would you name a holiday dedicated to unhurried meals?',
  'If you could add a surprising room to a celebration venue, what would it be for?',
  'What is a memory of sharing limited food or resources generously?',
  'Which seasonal custom helps you feel connected to a place?',
  'What is a creative alternative to exchanging presents?',
  'How do you prefer to recover after a socially full day?',
  'What food preparation feels almost meditative to you?',
  'If the people at this table formed a tiny festival committee, what role would you take?',
  'What is a way to celebrate good news without comparing anyone’s achievements?',
  'Which color reminds you of warmth, and what memory gives it that feeling?',
  'What would you cook for someone experiencing your favorite season for the first time?',
  'How can a group decide which traditions to keep without dismissing anyone’s feelings?',
  'What is a holiday gathering detail you notice that others might miss?',
  'If you could make one seasonal pleasure free for everyone, what would it be?',
  'What is a lesson about hospitality you learned as a guest?',
  'Which food has the most interesting transformation from raw ingredient to finished dish?',
  'What would a celebration of ordinary resilience look like?',
  'How could people create a sense of occasion in a temporary or borrowed space?',
  'What is the funniest thing that could become an elegant centerpiece?',
  'If you made a playlist in three moods for this meal, what moods would you choose?',
  'What is a gentle way to change the subject when table conversation becomes uncomfortable?',
  'Which task would you trade with someone else during preparation, and what would you offer?',
  'What could a community share so that more people can celebrate with ease?',
  'How does eating outdoors change the way a meal feels?',
  'What is a ritual for beginning a gathering that does not require words?',
  'If you could thank one unnoticed worker who supports seasonal celebrations, whom would you thank?',
  'What is a food tradition that tells a story about adaptation?',
  'Which part of hosting can be improvised successfully?',
  'What would you place on a celebration menu for the five senses?',
  'How can a group make room for both nostalgia and new memories?',
  'What is a seasonal pleasure that costs little or nothing?',
  'If you designed a holiday postcard showing real life, what scene would be on it?',
  'What quality in the people around you feels worth celebrating tonight?',
  'Which kitchen tool has earned a place in your personal hall of fame?',
  'What would make a virtual or long-distance gathering feel more present?',
  'How do you like to signal that a meal is beginning?',
  'What is a thoughtful way to share the last portion of something delicious?',
  'If this season were represented by one shape, what would it be?',
  'What makes laughter at a table feel connecting rather than excluding?',
  'Which old custom could inspire a completely new ritual?',
  'What is one way a celebration can support local makers or growers?',
  'How would you create a sensory-friendly corner at a lively gathering?',
  'What dish would you choose to represent patience?',
  'If everyone wrote one hope for the coming season, where should the hopes be kept?',
  'What is a gathering habit that helps quieter voices enter the conversation?',
  'Which food is best enjoyed slowly, and what makes it worth the time?',
  'What would you celebrate about the place you call home right now?',
  'How can someone offer help without taking over?',
  'What is a moment when a guest made a gathering better in an unexpected way?',
  'If you could add one communal table to any public place, where would it go?',
  'What kind of lighting makes you want to linger over a meal?',
  'Which seasonal routine helps you feel prepared rather than pressured?',
  'What is a meaningful use for recipes that carry complicated memories?',
  'How would you celebrate a milestone that matters privately but not publicly?',
  'What is an imaginative name for tonight’s gathering?',
  'If you could hear one sound from celebrations a century ago, what would you choose?',
  'What does respectful curiosity about another person’s tradition sound like?',
  'Which dish invites the best personal variations?',
  'What is one way to let a host know you felt comfortable in their space?',
  'How might a celebration look different if rest were the main event?',
  'What would you put in a bowl labeled “take what you need” besides food?',
  'If the next season could bring one shared resource to your community, what should it be?',
  'What is a happy memory involving weather that did not cooperate?',
  'Which tradition helps people reconnect after time apart?',
  'What would make volunteering together feel celebratory?',
  'How can a table honor both inherited recipes and invented ones?',
  'What is the best conversation you have had while washing dishes?',
  'If you made a gratitude map, which places would appear on it?',
  'What is a simple signal that everyone is welcome to take a break?',
  'Which ingredient do you associate with someone’s generosity?',
  'What would a feast for birds, insects, or neighborhood animals look like?',
  'How do you decide when a gathering has reached its natural ending?',
  'What is a tradition you appreciate more for its process than its result?',
] as const
