export const DINNER_TABLE_FAMILY_PROMPTS = [
  "What is a small moment from today that you would enjoy telling us about?",
  "Which part of your day had the most interesting sound, sight, or smell?",
  "What ordinary thing made life a little easier for you this week?",
  "What overlooked detail from this week would you like everyone here to notice?",
  "Which moment this week would you put in a family time capsule?",
  "What has been taking up your curiosity lately?",
  "What is one pleasant surprise your day brought you?",
  "Which everyday task do you enjoy more than people might expect?",
  "What is something you are looking forward to before this week ends?",
  "How would you describe the pace of your day using a kind of weather?",
  "What made you feel welcome somewhere recently?",
  "Which part of your routine feels most like your own?",
  "What is a tiny choice you made today that you are glad about?",
  "What everyday object has been especially useful to you lately?",
  "Which recent conversation left you with something interesting to think about?",
  "What is one thing you would happily make more time for tomorrow?",
  "What was the most peaceful part of your day?",
  "Which place you visited this week had the most interesting atmosphere?",
  "What is something new in your world that you would like us to know about?",
  "What simple pleasure has been reliable for you lately?",
  "Which part of today deserves a quiet little celebration?",
  "What is a question you found yourself wondering about this week?",
  "What did you do recently that felt satisfying to finish?",
  "Which everyday smell instantly improves your mood?",
  "What is one detail that would help us picture your day?",
  "What has felt easier this week than it did last week?",
  "Which part of your day gave you fresh energy?",
  "What is something nearby that you appreciate more when you slow down?",
  "What recent change to your routine has worked well for you?",
  "If today had a title, what would you call it and why?",

  "What food aroma brings a vivid memory to mind for you?",
  "Which snack from another time in your life would you enjoy tasting again?",
  "Tell us about a meal that felt special because of the setting.",
  "What dish or ingredient has grown on you over time?",
  "Which food do you associate with being cared for?",
  "What is a cooking mistake that turned into a good story or discovery?",
  "Describe a food memory that begins with a particular sound.",
  "What meal have you eaten outdoors that you still remember clearly?",
  "Which kitchen job do you find the most satisfying, and what makes it so?",
  "What food would you choose to represent this season of the year?",
  "Tell us about a time someone improvised a meal with what was available.",
  "What ingredient do you think deserves more appreciation?",
  "Which meal from your past would you like to watch being prepared again?",
  "What food texture do you especially enjoy, and how would you describe it?",
  "If you could add one scent to the air at this table, what would you choose?",
  "What is a food you enjoy in a very particular way?",
  "Which drink makes you think of a certain time, place, or person?",
  "Tell us about a meal whose company mattered more than the menu.",
  "What is the most creative use of leftovers you have seen or tried?",
  "Which food have you learned to prepare in your own style?",
  "What dish would you enjoy learning about from someone who knows it well?",
  "Describe a memorable meal that came from a very simple plan.",
  "What food do you like sharing because everyone can make it their own?",
  "Which flavor combination surprised you by working well?",
  "What is a food-related skill you would enjoy passing along?",
  "Tell us about a time a meal helped a new place feel more familiar.",
  "What would make a picnic designed by everyone at this table distinctive?",
  "Which part of preparing a meal feels most like an art to you?",
  "What menu would capture the mood of a really restful day?",
  "How has a favorite food of yours changed across the years?",

  "What custom in your family circle makes ordinary time feel meaningful?",
  "Which tradition would you enjoy adapting for the people gathered here now?",
  "Tell us about a celebration detail that matters more to you than its size.",
  "What repeated ritual helps you feel grounded?",
  "Which seasonal activity would you like to experience through someone else's eyes?",
  "What is a tradition you created for yourself, intentionally or by accident?",
  "How would you put a fresh twist on a familiar gathering?",
  "What music, scent, or decoration signals that a special occasion has begun?",
  "Which everyday ritual deserves to become a tradition?",
  "Tell us about a custom whose meaning became clearer to you over time.",
  "What tradition from any community would you like to learn more about?",
  "Which recurring occasion brings out a side of people that you enjoy?",
  "What is one low-cost way to make a gathering feel festive?",
  "How could we mark a new beginning in a way that feels like us?",
  "What object helps tell the story of a tradition important to you?",
  "Which part of a celebration do you enjoy preparing for most?",
  "What tradition works especially well because people of different ages can join in?",
  "Tell us about a familiar custom that has changed as people and circumstances changed.",
  "What kind of annual day would you invent for this group to enjoy?",
  "Which tradition feels meaningful even when it is done imperfectly?",
  "What is a welcoming ritual you have experienced as a guest?",
  "How do you like to make milestones feel memorable?",
  "What could a tradition of gratitude look like without needing a special occasion?",
  "Which celebration food carries a story worth preserving?",
  "What is a small ritual that helps people reconnect after time apart?",
  "Tell us about a tradition that makes room for both quiet and lively people.",
  "What shared activity could become a future tradition for this table?",
  "Which tradition would you preserve in a recording, recipe, or written note?",
  "What does a truly inclusive celebration feel like to you?",
  "How might a tradition change when a new person joins the circle?",

  "What story from long ago still makes you smile when you tell it?",
  "Which memory would be easier to tell with a map in front of you?",
  "Tell us about a day when an ordinary plan became an adventure.",
  "What childhood game or pastime could you still teach someone?",
  "Which place from your earlier years can you picture most clearly?",
  "What is a funny misunderstanding you can laugh about now?",
  "Tell us about a time you felt very proud of learning something practical.",
  "Which old photograph would you choose as the start of a story?",
  "What did people do for fun when you were at a different stage of life?",
  "Tell us about a memorable journey, whether it was long or just around the corner.",
  "What object from your past had a surprisingly big role in daily life?",
  "Which memory has a soundtrack in your mind?",
  "Tell us about a time weather changed the whole course of a day.",
  "What was a favorite hiding place, reading spot, or quiet corner from your past?",
  "Which story about a pet or animal visitor is worth retelling?",
  "What is an old-fashioned convenience you once wished existed?",
  "Tell us about a time you made something with your own hands.",
  "Which memory shows how your neighborhood or surroundings have changed?",
  "What was a small luxury to you at an earlier point in life?",
  "Tell us about a time you were delighted by something free.",
  "Which journey to school, work, or another regular place stands out in your memory?",
  "What is a story about resourcefulness that you enjoy remembering?",
  "Tell us about an occasion when everyone had to change plans together.",
  "Which fashion, phrase, or trend from your past is fun to explain now?",
  "What memory would you describe as a perfect snapshot of its era?",
  "Tell us about a person who made an everyday place more interesting.",
  "Which old skill do you think would still be useful today?",
  "What is a harmless family legend whose details seem to shift with each telling?",
  "Tell us about a memorable gift that was not expensive or elaborate.",
  "Which moment from your life would make a charming short film?",

  "What quality do you admire in the way someone at this table handles daily life?",
  "Which kind of kindness tends to stay in your memory?",
  "What value becomes visible through small actions rather than big speeches?",
  "Tell us about a time patience helped something turn out well.",
  "What does being dependable look like in ordinary life?",
  "Which strength have you come to appreciate more as you have grown?",
  "What is a thoughtful way someone has made space for your ideas?",
  "How can people show respect when their preferences are different?",
  "What kind of courage can be easy to overlook?",
  "Tell us about a time cooperation made a task lighter or more enjoyable.",
  "Which non-material gesture has taught you something memorable about generosity?",
  "Which personal quality helps a group feel comfortable together?",
  "What is something you have learned about keeping your word?",
  "How do you recognize wisdom in someone, regardless of their age?",
  "What everyday action can communicate, 'You matter here'?",
  "Tell us about a time humor helped people work well together.",
  "Which kind of effort deserves more recognition than it usually gets?",
  "What does fairness mean when different people need different things?",
  "How can curiosity help people understand one another?",
  "What is a strength you have seen develop in someone over time?",
  "Tell us about a quiet act of leadership you witnessed.",
  "Which compliment have you received that felt especially true to you?",
  "What is one way to disagree while still showing care?",
  "How do you like others to encourage you when you are learning?",
  "What personal strength shows up most clearly when plans change?",
  "Tell us about a time someone trusted you with a useful responsibility.",
  "Which value would you want reflected in the atmosphere of this table?",
  "What does making amends look like in a healthy everyday situation?",
  "How can a person be both confident and open to learning?",
  "What quality helps people of different generations learn from one another?",

  "What useful thing did someone teach you without using a classroom?",
  "Which question would you ask a person who is excellent at their craft?",
  "Tell us about something that became fun once you understood how it worked.",
  "What skill looked easy until you tried it yourself?",
  "Which subject could you happily explore one small piece at a time?",
  "What have you learned by watching someone else's approach?",
  "Tell us about a mistake that gave you a practical insight.",
  "Which everyday mystery would you enjoy having explained?",
  "What is something a younger person has taught you?",
  "What is something an older person helped you see differently?",
  "Which skill would be enjoyable for several generations to learn together?",
  "How do you know when you have truly understood something?",
  "Tell us about a time practice changed your opinion of your own abilities.",
  "What topic makes you lose track of time when you explore it?",
  "Which learning tool works especially well for you: seeing, hearing, doing, or something else?",
  "What fact recently made you say, 'I never knew that'?",
  "Tell us about a shortcut you learned only after doing something the long way.",
  "What skill from one generation could pair well with knowledge from another?",
  "Which everyday problem would you like to understand better?",
  "What is a lesson from nature that you find useful?",
  "Tell us about something you taught yourself in an unusual way.",
  "What would you enjoy learning from someone sitting here?",
  "Which book, program, conversation, or experience sparked lasting curiosity?",
  "What is one sign that a learning environment feels welcoming?",
  "How has technology changed the way you learn or share knowledge?",
  "Tell us about a skill you learned mainly through repetition.",
  "Which topic could people of many ages discuss as equals?",
  "What would you include in a one-hour class called 'Something Useful I Know'?",
  "How do you make learning less intimidating for someone new?",
  "What is one thing you understand now that once seemed puzzling?",

  "What are three small things that made today better?",
  "Who brought some brightness to your week, and how?",
  "What convenience are you especially thankful exists?",
  "Which part of this meal can you appreciate with more than one sense?",
  "What place are you grateful to be able to visit?",
  "What ability do you value more now than you once did?",
  "Which ordinary item would you miss quickly if it disappeared for a week?",
  "What is something another generation made possible for yours?",
  "What is something your generation can offer to those who follow?",
  "Which part of the natural world lifted your spirits recently?",
  "Tell us about a helpful gesture that arrived at just the right time.",
  "What is one thing at this table that took unseen effort to provide?",
  "Which memory are you glad someone helped preserve?",
  "What freedom or choice in daily life do you appreciate?",
  "Who deserves a thank-you for teaching you something useful?",
  "What is a familiar sound you would be sorry never to hear again?",
  "Which public place or shared service improves your everyday life?",
  "What part of growing older has brought something worth appreciating?",
  "What can you appreciate about being exactly the age you are now?",
  "Tell us about a welcome you received that you still remember.",
  "What simple comfort are you glad to have today?",
  "Which creative work are you thankful someone shared with the world?",
  "What challenge has made you appreciate a skill or resource you now have?",
  "Who in your wider community makes life better in an often-unnoticed way?",
  "What is one thing you are grateful your past self did?",
  "Which chance encounter added something good to your life?",
  "What part of a shared meal do you value beyond the food?",
  "What is something you appreciate about how this group includes people?",
  "Which recent laugh are you glad you got to share?",
  "What possibility in the near future makes you feel thankful now?",

  "What helps a place feel like somewhere you belong?",
  "Which role do you naturally enjoy taking when people gather?",
  "What is a way a newcomer can be included without being put on the spot?",
  "Tell us about a group where you could comfortably be yourself.",
  "What signals that everyone has a real voice in a shared decision?",
  "Which shared experience can connect people even when their backgrounds differ?",
  "What is a small way to remember someone who cannot be at the table?",
  "How can a group make room for someone who prefers listening to speaking?",
  "What does the word 'family' make room for in your understanding of it?",
  "Which place outside a home has given you a sense of belonging?",
  "What helps different generations feel like teammates?",
  "Tell us about a time you felt included through an ordinary gesture.",
  "What can make shared silence feel comfortable rather than awkward?",
  "Which activity lets people participate in many different ways?",
  "How can we show that every person's contribution counts?",
  "What is a sign that a gathering welcomes people as they are?",
  "Which story, song, recipe, or object connects you to a wider community?",
  "What helps you settle in when you enter an unfamiliar group?",
  "Tell us about a place where people of different ages mix naturally.",
  "What makes an invitation feel genuine to you?",
  "Which shared responsibility can strengthen a sense of togetherness?",
  "What is one way a group can honor different needs at the same time?",
  "How can people stay connected when they live far apart?",
  "What contribution do you enjoy making to a shared space?",
  "Which signs of welcome can cross language barriers?",
  "What helps you feel remembered between gatherings?",
  "Tell us about a community tradition that brings different people together.",
  "What could we do to make this table even more welcoming next time?",
  "Which everyday phrase or gesture makes you feel seen?",
  "What does being part of something larger than yourself mean to you?",

  "What is a hope you have for an ordinary day in the coming month?",
  "Which place would you like to explore slowly rather than rush through?",
  "What would you enjoy making, growing, or building over time?",
  "What small improvement would make daily life more pleasant for many people?",
  "Which future occasion would you enjoy helping to plan?",
  "What is a skill you hope someone at this table keeps sharing?",
  "How would you like people to describe the feeling of our future gatherings?",
  "What part of the future are you most curious to witness?",
  "Which shared project could be meaningful even if it stayed simple?",
  "What is something you hope becomes easier for the next generation?",
  "Tell us about a possibility you are quietly excited about.",
  "What would a really good day together look like next season?",
  "Which idea would you like to test just for the fun of seeing what happens?",
  "What is one thing worth taking good care of for the future?",
  "How could a future meal reflect something everyone here enjoys?",
  "What do you hope never goes out of style?",
  "Which new tradition might people still enjoy years from now?",
  "What kind of story do you hope we will be telling about this year someday?",
  "What is a hopeful change you have already started to notice?",
  "Which dream becomes more interesting when other people can join in?",
  "What would you put in a care package for your future self?",
  "How might people make their neighborhood better one small step at a time?",
  "What is something you hope to understand more deeply one year from now?",
  "Which invention would you like to see improve everyday life?",
  "What future memory would you enjoy beginning today?",
  "How would you spend a free afternoon that appeared on next week's calendar?",
  "What is one way you hope to keep growing while staying true to yourself?",
  "Which positive habit would be easier or more fun to build together?",
  "What do you hope people at this table always make time for?",
  "If we could send one encouraging message forward ten years, what should it say?",

  "If this table could travel anywhere for one meal, where would you send it?",
  "What imaginary restaurant would be especially fun for all ages to visit?",
  "If everyone here contributed one ingredient to a new dish, what might we create?",
  "What animal would make the most entertaining dinner guest, and why?",
  "If your favorite color had a flavor, how would it taste?",
  "What would you name a boat, train, or spaceship carrying everyone at this table?",
  "If you designed a family board game, what would players be trying to accomplish?",
  "What harmless superpower would be most useful during a shared meal?",
  "If tonight's conversation became a book, what would its cover look like?",
  "What tiny museum would you create inside a single cupboard?",
  "If you could make one everyday sound musical, which sound would you choose?",
  "What would be included in a holiday invented entirely around coziness?",
  "If a friendly visitor arrived from another planet, how would you explain this meal?",
  "What playful award could each person at this table have a chance to win?",
  "If your week were a board game, what special spaces would appear on it?",
  "What room would you add to a dream community center for every generation?",
  "If you could combine two ordinary objects into a useful invention, what would you make?",
  "What would a garden planned by everyone here contain besides plants?",
  "If this group formed a band, what kind of music might we make?",
  "What friendly mascot would represent the spirit of our gatherings?",
  "If you could shrink any place into a tabletop model, which place would you pick?",
  "What story could begin with everyone discovering the same mysterious key?",
  "If laughter could be stored in jars, when would you open one?",
  "What would you serve at a meal inspired entirely by the sky?",
  "If you invented a machine that saves people five minutes a day, what would it do?",
  "What kind of parade could everyone at this table enjoy joining?",
  "If each season wrote us a postcard, what might the current one say?",
  "What would make the world's smallest festival worth attending?",
  "If you could give a new name to this day of the week, what would it be?",
  "What imaginative group adventure could happen without anyone leaving this room?",
] as const
