export const DINNER_TABLE_BIRTHDAY_PROMPTS: readonly string[] = [
  "Which moment from today would you happily replay tomorrow?",
  "What small detail has made this celebration feel like yours?",
  "Which ordinary moment from the past year became unexpectedly special?",
  "What recent memory still brings an easy smile to your face?",
  "Which day from your life deserves its own tiny holiday?",
  "What is a favorite memory that began with no special plans?",
  "Which shared laugh would you put in a birthday highlight reel?",
  "What place holds a memory you enjoy returning to in your mind?",
  "Which recent first-time experience are you glad you tried?",
  "What is one peaceful moment from this year you would save in a jar?",
  "Which celebration from any time in your life had the best atmosphere?",
  "What memory feels brighter each time you tell the story?",
  "Which simple outing turned into a surprisingly good time?",
  "What moment made you feel especially welcome somewhere?",
  "Which recent conversation stayed with you in a good way?",
  "What is a moment when the timing of everything felt just right?",
  "Which sound, smell, or flavor can bring back a happy scene for you?",
  "What is a memory of being pleasantly surprised by your own courage?",
  "Which low-key gathering have you enjoyed more than a grand event?",
  "What snapshot from your life would make a wonderful postcard?",
  "Which part of your usual day is bringing you the most joy lately?",
  "What have you been genuinely excited to talk about recently?",
  "Which tiny pleasure never seems to lose its charm for you?",
  "What is making life feel a little lighter these days?",
  "Which activity helps you feel most like yourself right now?",
  "What is currently earning a regular spot in your happy thoughts?",
  "Which corner of your world feels especially cozy at the moment?",
  "What have you enjoyed learning simply because it interests you?",
  "Which recent discovery have you been recommending to people?",
  "What part of this season of life feels refreshingly uncomplicated?",
  "Which routine has become something you actually look forward to?",
  "What is a current favorite that you hope stays in your rotation?",
  "Which person, place, or pastime has been lifting your energy lately?",
  "What has captured your curiosity in the best way?",
  "Which everyday convenience are you especially grateful for today?",
  "What has been making you laugh reliably these days?",
  "Which recent choice has made your days feel more enjoyable?",
  "What is giving you a satisfying sense of momentum right now?",
  "Which part of your week tends to have the best mood?",
  "What harmless thing are you happily obsessed with at the moment?",
  "What quality in the person being celebrated deserves a cheerful toast?",
  "Which way does the birthday person make a room feel better?",
  "What is something the guest of honor does with unmistakable flair?",
  "Which strength of the birthday person shows up in quiet ways?",
  "What have you learned from watching the guest of honor be themselves?",
  "Which contribution from the birthday person has made a difference to you?",
  "What is a kindness from the guest of honor that you still remember?",
  "Which word of appreciation fits the birthday person, and what gives it meaning?",
  "What is something the guest of honor makes look delightfully easy?",
  "Which of the birthday person's quirks adds joy to the group?",
  "What do you hope the guest of honor gets to hear more often?",
  "Which talent or instinct of the birthday person deserves more applause?",
  "What is one way the guest of honor helps people feel included?",
  "Which shared experience made you appreciate the birthday person anew?",
  "What does the guest of honor bring that could never be replaced by a party decoration?",
  "Which choice by the birthday person has inspired you?",
  "What is a compliment for the guest of honor that has nothing to do with achievement?",
  "Which part of the birthday person's perspective makes conversations richer?",
  "What is one gentle wish you have for the guest of honor's everyday happiness?",
  "Which part of knowing the birthday person feels worth celebrating tonight?",
  "If this celebration had a mascot, what would suit its mood?",
  "What ridiculous luxury should every birthday include for one day?",
  "If the cake could grant one playful wish, what would you ask for?",
  "What would the title of today's birthday episode be?",
  "If this table became a parade float, how would we decorate it?",
  "What imaginary award should the guest of honor receive tonight?",
  "If you could add one harmless rule to birthdays, what would it be?",
  "What animal would make the most entertaining party host?",
  "If today's mood were a weather forecast, what would it predict?",
  "What tiny superpower would make celebrations more fun?",
  "If the birthday person had a signature confetti shape, what should it be?",
  "What should be inside a party favor designed especially for this group?",
  "If laughter were a dessert, how would tonight's version be served?",
  "What fictional venue would be fun to borrow for a birthday gathering?",
  "If you named a dance move after the guest of honor, what would it look like?",
  "What would make a delightfully unnecessary entrance for the birthday person?",
  "If this meal came with a souvenir, what should it be?",
  "What friendly competition would make an amusing birthday tradition?",
  "If everyone here wore a party crown, what would yours be made of?",
  "What would a five-minute birthday theme park need to include?",
  "What is something you understand about yourself more clearly now?",
  "Which personal quality have you grown more comfortable owning?",
  "What kind of challenge has shown you a strength you did not expect?",
  "Which old pressure have you become better at setting down?",
  "What is one boundary that has made room for more joy?",
  "Which part of yourself have you welcomed more warmly lately?",
  "What belief about a good life has become more personal to you?",
  "Which decision helped you trust your own judgment a little more?",
  "What have you learned to approach with more patience?",
  "Which mistake eventually gave you something useful to carry forward?",
  "What does being true to yourself look like in an ordinary week?",
  "Which expectation have you happily rewritten in your own way?",
  "What has helped you become kinder to your learning process?",
  "Which part of change now feels less intimidating than it once did?",
  "What is something you no longer need to be perfect at to enjoy?",
  "Which value has become easier for you to name and protect?",
  "Which kind of support feels easier to request than it did a year ago?",
  "Which personal win mattered even though few people saw it?",
  "What is one way your idea of confidence has changed?",
  "Which version of yourself would be pleased by how you handled something recently?",
  "What part of your personality feels most alive around this table?",
  "Which three objects would make a playful museum exhibit about you?",
  "What interest of yours deserves a longer conversation tonight?",
  "Which description of you feels accurate but might surprise some people?",
  "What is a personal preference you enjoy having strong opinions about?",
  "Which role in a group comes naturally to you?",
  "What part of your style tells a story about you?",
  "Which skill feels connected to who you are, beyond being useful?",
  "What is something you like about the way your mind works?",
  "Which environment brings out your most playful side?",
  "What personal tradition have you shaped to fit yourself?",
  "Which topic can make you forget to check the time?",
  "What is one way you express care that feels distinctly yours?",
  "Which piece of your identity has brought you an unexpected community?",
  "What kind of beauty do you tend to notice first?",
  "Which everyday choice feels like a small expression of who you are?",
  "What is something people often come to you for?",
  "Which compliment feels especially meaningful because it recognizes the real you?",
  "What part of yourself would you put on the cover of an imaginary magazine?",
  "Which nickname, title, or description would be fun to try on for an evening?",
  "What hope feels pleasant to imagine without needing a deadline?",
  "Which experience would you enjoy having more space for someday?",
  "What would you like a future ordinary Tuesday to feel like?",
  "Which possibility makes you curious when you picture the months ahead?",
  "What kind of welcome surprise would fit your life nicely?",
  "Which place would you enjoy exploring at an unhurried pace?",
  "What would you love to become easier in your daily life?",
  "Which creative idea would be fun to follow just to see where it leads?",
  "What is a future pleasure you enjoy anticipating?",
  "Which skill might be satisfying to learn without needing to master it?",
  "What would you like to make more room for when the timing feels right?",
  "Which kind of adventure sounds appealing at your current energy level?",
  "What atmosphere would you like to create around yourself in the coming season?",
  "Which invitation would you be delighted to receive one day?",
  "What is one future scene that feels both simple and wonderful?",
  "Which curiosity would you follow if you had a free afternoon?",
  "What new flavor of fun would you like to sample?",
  "Which possibility feels exciting precisely because it is still undefined?",
  "What would a gentle, satisfying next chapter contain?",
  "Which wish would you send forward with no obligation attached?",
  "What makes a friendship feel easy to return to?",
  "Which kind of check-in helps you feel genuinely remembered?",
  "What is something a friend introduced you to that enriched your life?",
  "Which shared activity tends to bring out good conversation?",
  "What quality helps a new connection grow at a comfortable pace?",
  "Which friendship memory feels like a perfect little time capsule?",
  "What is a way someone has made belonging feel natural for you?",
  "Which kind of support do you value when words are not necessary?",
  "What makes someone enjoyable to celebrate with?",
  "Which friend-taught phrase or habit has become part of your life?",
  "What is an underrated ingredient in lasting friendship?",
  "Which spontaneous plan with friends turned out especially well?",
  "What helps a group make room for everyone's different energy?",
  "Which sign tells you a conversation has become a real connection?",
  "What is a small way friends can make milestones feel meaningful?",
  "Which shared joke has taken on a life of its own?",
  "What kind of invitation makes it easiest for you to join in?",
  "Which friendship has expanded your view of what is possible?",
  "What is something wonderful about friends who know different sides of you?",
  "Which quality would you add to a recipe for a welcoming circle?",
  "What food would make a perfect edible portrait of your personality?",
  "Which bite on this table deserves its own round of applause?",
  "What dish instantly makes an occasion feel festive to you?",
  "Which snack would you choose as your unofficial birthday ambassador?",
  "What flavor combination feels like a celebration in itself?",
  "Which meal would you love to have prepared exactly to your taste?",
  "What food memory is really a memory about the people who were there?",
  "Which ingredient makes almost any dish more exciting for you?",
  "What would you serve at a party built around comfort?",
  "Which dessert best matches your current mood?",
  "What is a food you enjoy more because of the ritual around it?",
  "Which dish would you gladly learn from someone who makes it beautifully?",
  "What would the menu say if each course described the guest of honor?",
  "Which aroma makes a dining room feel welcoming to you?",
  "What is your ideal balance of familiar favorites and new tastes at a feast?",
  "Which drink deserves a celebratory garnish, and what would you add?",
  "What plate from any memorable trip or outing would you bring to this table?",
  "Which humble food would you proudly put on a special-occasion menu?",
  "What is the best way to turn leftovers into a next-day celebration?",
  "Which imaginary restaurant would serve the birthday person's signature dish?",
  "What song would make a great soundtrack for bringing out the cake?",
  "Which tune can lift your mood within the first few notes?",
  "What artist would you trust to set the tone for tonight?",
  "Which song belongs on a playlist about a favorite memory?",
  "What kind of music makes conversation around a table feel warmer?",
  "Which track would you dedicate to the guest of honor for purely joyful reasons?",
  "What song title could double as a birthday toast?",
  "Which musical instrument best matches your personality today?",
  "What piece of music makes an ordinary journey feel cinematic?",
  "Which song do you enjoy hearing someone else choose?",
  "What would the opening track be on an album about this celebration?",
  "Which musical era would be fun to borrow for a themed party?",
  "What sound always signals that a good time is beginning?",
  "Which lyric-free piece could score a montage of your happiest moments?",
  "What song has found a new meaning for you over time?",
  "Which style of music makes you want to move in your own way?",
  "What would a band named after this table sound like?",
  "Which song would be the perfect closing credits for tonight?",
  "What music would you play while preparing your favorite celebratory meal?",
  "Which unexpected song choice could make this party more memorable?",
  "What does feeling celebrated look like when it is quiet and simple?",
  "Which birthday custom would you keep, reinvent, or happily skip?",
  "What is the most thoughtful way someone can mark your special day?",
  "Which part of a celebration matters more than its size?",
  "What kind of birthday message feels most like a gift?",
  "Which low-key ritual could make a birthday morning feel special?",
  "What helps a celebration feel personal instead of performative?",
  "Which detail would make a gathering feel thoughtfully designed for you?",
  "What kind of attention feels warm without putting you on the spot?",
  "Which celebration ingredient can never be bought in a shop?",
  "What would your ideal birthday pace be from morning to night?",
  "Which tradition becomes better when everyone can adapt it?",
  "How could friends honor your birthday while keeping the attention comfortably low-key?",
  "Which gesture says 'I know you' more clearly than an expensive present?",
  "What would make a birthday gathering feel restful as well as joyful?",
  "Which part of planning a celebration can be fun in its own right?",
  "What kind of surprise leaves plenty of room for choice?",
  "Which birthday detail would you outsource to an imaginary expert?",
  "What does a perfectly unhurried celebration include?",
  "Which ordinary space could become festive with one clever change?",
  "What recent accomplishment deserves a moment of recognition, however small?",
  "Which choice are you glad you made on your own terms?",
  "What have you handled lately with more grace than you expected?",
  "Which unfinished effort are you proud to have begun?",
  "What is something you made, fixed, or improved that felt satisfying?",
  "Which quiet act of persistence deserves a private cheer?",
  "What did you make time for recently that mattered to you?",
  "Which moment helped you notice your own progress?",
  "What is a kind decision you made for your future self?",
  "Which challenge revealed a useful resourcefulness in you?",
  "What have you become better at enjoying along the way?",
  "Which contribution are you pleased to have made to a shared effort?",
  "What is something you followed through on despite a bumpy start?",
  "Which everyday responsibility have you found a smarter way to handle?",
  "What personal standard are you proud to define for yourself?",
  "Which attempt taught you to notice progress differently?",
  "What is one thing you gave your full attention to and enjoyed?",
  "Which recent moment made you think, 'I handled that well'?",
  "What have you protected space for, even when life got busy?",
  "Which choice helped your life fit you better?",
  "If you received a coupon for one perfect afternoon, how would you spend it?",
  "What friendly message would you put inside a fortune cookie for yourself?",
  "If your next season had a color palette, what shades would you choose?",
  "What would you name a boat meant for leisurely future adventures?",
  "If one everyday task could become oddly delightful, which would you transform?",
  "What room would you add to an imaginary house built for joy?",
  "If you could order a custom sunset, what details would you request?",
  "What would be the theme of a festival devoted to your favorite things?",
  "If tomorrow came with background music, what mood should it create?",
  "What harmless mystery would you enjoy having the answer to?",
  "If you designed a bench for perfect conversations, where would it sit?",
  "What would you include in a care package for an unexpectedly free weekend?",
  "If your calendar had a bonus day, what would that day be for?",
  "What fictional shop would you enjoy browsing with unlimited time?",
  "If you could rename one month to improve its mood, what name would you choose?",
  "What would an amusement park based on your interests feature?",
  "If a friendly breeze could deliver one thing, what should it bring?",
  "What future memory would you like to stumble into by chance?",
  "If you hosted a tiny radio show, what would tonight's episode explore?",
  "What would you place on a shelf labeled 'more of this, please'?",
  "What question would you enjoy being asked more often?",
  "Which recent moment made you feel pleasantly understood?",
  "What makes it easier for you to relax into a conversation?",
  "Which kind of compliment do you enjoy giving?",
  "What is something you appreciate more when you slow down?",
  "Which everyday sound feels comforting to you?",
  "What helps a new place begin to feel familiar?",
  "Which small choice can turn your mood around?",
  "What is a gentle way you like to recharge?",
  "Which possession carries more meaning than its price could suggest?",
  "What kind of story do you never get tired of hearing?",
  "Which simple pleasure would you recommend to everyone at the table?",
  "What is one way you make an ordinary day feel more personal?",
  "Which season brings out a side of you that you enjoy?",
  "What is something delightful you noticed before anyone else?",
  "Which type of invitation feels like an instant mood boost?",
  "Which quiet moment with people you trust has felt celebratory in its own way?",
  "Which everyday object has an unexpectedly pleasing design?",
  "What is a recent reminder that people can be wonderfully thoughtful?",
  "Which word would you like to set the tone for this table?",
  "What would you thank your past self for choosing?",
  "Which recent detour gave you something better than the original plan?",
  "What has become more enjoyable since you stopped rushing it?",
  "Which part of your life currently feels nicely in tune?",
  "What do you hope remains wonderfully unchanged for a while?",
  "Which new perspective has made something familiar more interesting?",
  "What is one thing you are glad to know about the person beside you?",
  "Which moment from this gathering might become a story later?",
  "What kind of generosity makes a celebration ripple beyond one day?",
  "Which shared value seems especially present around this table?",
  "What is something this group does particularly well together?",
  "Which wish would you make for everyone here, including yourself?",
  "What could we celebrate more often without needing a formal occasion?",
  "Which feeling would you like each person to take home tonight?",
  "What is one thing about the present moment worth fully noticing?",
  "Which word would make a fitting caption for this gathering?",
  "What would you add to a time capsule from tonight?",
  "Which part of this meal tells the best story?",
  "What is a warm way to end a celebration while keeping its spirit going?",
  "Which tiny tradition could begin at this table tonight?",
]
