export const DINNER_TABLE_FRIENDS_NIGHT_PROMPTS = [
  'What food always puts you in a better mood, and what gives it that power?',
  'Describe a meal you would happily travel across town to eat again.',
  'Which snack best matches your personality tonight, and why?',
  'What is your ideal balance of conversation, music, and food at dinner?',
  'Tell us about a dish that surprised you by being much better than expected.',
  'What food opinion could you defend with a completely unnecessary presentation?',
  'Which ingredient deserves a better publicist, in your view?',
  'How would you build the perfect plate from foods already on this table?',
  'What dish do you enjoy more when someone else makes it?',
  'Describe the most memorable setting where you have eaten something simple.',
  'What is your preferred strategy when a menu has too many good choices?',
  'Which food texture do you think deserves more appreciation?',
  'If tonight had a flavor, what would it taste like?',
  'What meal feels celebratory to you without needing a special occasion?',
  'Which kitchen smell would you bottle if that were possible?',
  'Tell us about a food experiment that went in an unexpected direction.',
  'What would you serve at a dinner themed around your current mood?',
  'Which condiment would you nominate for a lifetime achievement award?',
  'What ordinary drink feels like a treat when it is served just right?',
  'How do you decide whether to share a favorite bite or keep it for yourself?',
  'What food did you learn to appreciate only after giving it another chance?',
  'Which part of a meal do you secretly look forward to most?',
  'What is the funniest name you could give a restaurant run by this group?',
  'Describe your personal definition of a truly satisfying sandwich.',
  'What would be on a tasting menu inspired by your week?',
  'Which meal feels completely different when eaten beside moving water?',
  'What is a meal you can assemble confidently without checking instructions?',
  'How would you turn a familiar food into a ridiculous luxury item?',
  'What is your favorite thing to order for the whole table?',
  'Which bite on this table would you recommend first to someone arriving late?',
  'Tell us about a time a meal plan went completely off course.',
  'What tiny dining habit makes a meal more enjoyable for you?',
  'Which food would be the most entertaining mascot for this friend group?',
  'What dish would you choose to represent comfort in a museum exhibit?',
  'How would you describe your taste in food using three unexpected words?',
  'What is the best use of leftovers you have ever discovered?',
  'Which meal would you pair with a rainy evening?',
  'What food-related skill would make your everyday life noticeably better?',
  'Describe a food combination that sounds questionable but works for you.',
  'What does a welcoming table look and feel like to you?',
  'What minor mishap became funnier each time you retold it?',
  'Tell us about a moment when you confidently misunderstood the situation.',
  'What is the strangest reason you have ever been late to something casual?',
  'Describe a time an ordinary errand turned into an adventure.',
  'What harmless mistake do your friends still enjoy reminding you about?',
  'Which moment from the past month deserves a comedic reenactment?',
  'Tell us about a time you tried to look composed but absolutely were not.',
  'What is the funniest thing you have seen someone do with total seriousness?',
  'Describe an autocorrect or message mix-up that changed the whole conversation.',
  'What unexpected object has caused you the most unnecessary trouble?',
  'Tell us about a plan that failed in a way that improved the story.',
  'What is your best tale involving bad directions?',
  'Which everyday task has produced your most dramatic personal saga?',
  'What was a moment when the group energy became delightfully chaotic?',
  'Describe a time you laughed at exactly the wrong moment without sharing private details.',
  'What is the most elaborate solution you have used for a tiny problem?',
  'Tell us about an outfit choice that made more sense in your head.',
  'What is your funniest encounter with a machine that refused to cooperate?',
  'Describe a time you accidentally became the center of attention.',
  'What is a sentence you once said that made no sense without context?',
  'Tell us about a moment when improvising worked better than preparation.',
  'What is the funniest disagreement you have witnessed between people who liked each other?',
  'Describe a completely ordinary event that felt cinematic at the time.',
  'What is your most entertaining story involving a lost item?',
  'Tell us about a time the weather rewrote everyone\'s plans.',
  'What small victory have you celebrated with wildly excessive enthusiasm?',
  'Describe a time you followed the crowd and immediately questioned that choice.',
  'What is the most memorable thing that happened while everyone was waiting?',
  'Tell us about a photo whose backstory is much funnier than the image.',
  'What innocent misunderstanding would make a good scene in a comedy?',
  'Describe a time a shortcut took much longer than the normal route.',
  'What is the best accidental joke you have ever made?',
  'Tell us about a moment when one person\'s laugh made everyone else lose composure.',
  'What is a harmless situation in which you become surprisingly dramatic?',
  'Describe a time you were rescued by a very simple idea.',
  'What funny memory involves a place that no longer exists or has changed?',
  'Tell us about a time someone in a group invented a brilliant excuse on the spot.',
  'What mundane inconvenience has inspired your funniest complaint?',
  'Describe a moment when you realized everyone had interpreted the instructions differently.',
  'What story can you tell that gets better when someone at this table adds their version?',
  'What quality makes someone easy to spend an unplanned afternoon with?',
  'How do you usually show friends that you are glad they came?',
  'What kind of invitation makes you feel especially included?',
  'Describe a small gesture from a friend that landed at exactly the right time.',
  'What role do you naturally take when a group is deciding what to do?',
  'How can friends make room for different energy levels during a gathering?',
  'What is something a friend introduced you to that became part of your life?',
  'Which friendship skill deserves more recognition?',
  'What makes silence between friends feel comfortable rather than awkward?',
  'Describe the sort of check-in that feels caring without feeling intrusive.',
  'What is a sign that a group has become comfortable with one another?',
  'How do you like friends to celebrate your good news?',
  'What do you appreciate about friendships that can pick up after time apart?',
  'Which shared responsibility can unexpectedly bring friends closer?',
  'What makes someone a great person to have beside you during a confusing moment?',
  'Describe a way a friend has helped you see an ordinary thing differently.',
  'What kind of group tradition would you be excited to maintain?',
  'How do you help a new person feel part of an established group?',
  'What have your friends taught you about having fun?',
  'Which trait in a friend makes plans easier to enjoy, even when they change?',
  'What is a thoughtful way to remember the little details people share?',
  'Describe a friendship that began in an unexpected setting.',
  'What makes advice from a friend feel useful rather than pushy?',
  'How do you recognize when a friend wants company more than solutions?',
  'What is something friends can disagree about and still enjoy discussing?',
  'Which kind of shared project would reveal everyone\'s best qualities?',
  'What do you value about friends who have different habits from yours?',
  'Describe a moment when a friend made a place feel more familiar.',
  'What is your favorite way to turn an acquaintance into a friend?',
  'How does your idea of a good friend gathering change with your mood?',
  'What is an underrated way friends can encourage one another?',
  'Which everyday moment becomes better when a friend joins you?',
  'What makes a group chat genuinely enjoyable for you?',
  'Describe a time a friend remembered something you had forgotten about yourself.',
  'What kind of honesty strengthens a friendship?',
  'How would you describe the atmosphere this group creates when it is at its best?',
  'What have you learned from a friend whose life experience differs from yours?',
  'Which friend-made recommendation has had the longest-lasting impact on your routine?',
  'What is a way to make plans that respects everyone\'s different circumstances?',
  'Describe one thing you hope your friends feel when they spend time with you.',
  'What harmless topic brings out your most competitive side?',
  'How would a patient observer describe your decision-making style?',
  'What tiny detail are you unusually good at noticing?',
  'Which everyday luxury matters far more to you than its price suggests?',
  'What sort of problem do people naturally ask you to help solve?',
  'Describe the version of you that appears when you are very hungry.',
  'What is your most reliable method for making a dull task tolerable?',
  'Which compliment best matches something you value about yourself?',
  'What kind of surprise do you actually enjoy receiving?',
  'How do you behave when you are trying not to laugh?',
  'What opinion do you hold with enthusiasm but very little expertise?',
  'Describe your personal style of telling a story.',
  'What is a quirk you have decided to treat as a feature?',
  'Which part of your daily routine says the most about your personality?',
  'What do you become unexpectedly patient about?',
  'How would your closest friends describe your approach to a minor crisis?',
  'What is something you organize carefully while leaving everything else flexible?',
  'Which fictional sidekick shares the most traits with you?',
  'What kind of social setting brings out your most talkative side?',
  'Describe your sense of humor without naming a comedian or show.',
  'What do you take seriously that others might find delightfully specific?',
  'Which personal habit would be easiest to identify in a documentary about you?',
  'What is your signature move when you need a moment to think?',
  'How does your personality change when you know everyone in the room?',
  'What choice do you make quickly that others tend to deliberate over?',
  'Describe a topic that reliably activates your curiosity.',
  'What is the most accurate playful nickname someone could give your planning style?',
  'Which type of challenge makes you more determined instead of discouraged?',
  'What is something you enjoy doing badly?',
  'How would you spend an hour that belonged entirely to your most playful self?',
  'What object would serve as a useful symbol for your personality?',
  'Which of your habits makes more sense once people know you well?',
  'Describe the kind of attention to detail you appreciate from others.',
  'What is your default response when a plan suddenly becomes open-ended?',
  'Which version of yourself shows up on a long journey?',
  'What small decision reveals your taste more than people might expect?',
  'How do you recharge after a lively gathering?',
  'What is something you are more adventurous about than people assume?',
  'Describe an ordinary situation where your personality becomes unmistakable.',
  'What personal preference have you developed a surprisingly detailed theory about?',
  'If this table were a tiny country, what would its national motto be?',
  'What unusual competition would this group have a real chance of winning?',
  'Imagine everyone here runs a shop together; what does it sell, and who does what?',
  'If tonight became a board game, what would players need to do to win?',
  'What would be the first attraction at a theme park designed by this table?',
  'If you could give one ordinary object a new and absurd purpose, what would you choose?',
  'Imagine a festival based on a very small pleasure; what happens there?',
  'What would you name a boat crewed by your friends?',
  'If the room could speak after everyone left, what story would it tell?',
  'What impossible convenience would you add to everyday life?',
  'Imagine you can commission a monument to an underrated experience; what does it honor?',
  'If everyone here had a matching uniform, what would it look like?',
  'What new sport could be invented using only items found near this table?',
  'If your week were adapted into a short film, what would the opening scene show?',
  'Imagine a café where the menu changes with the weather; what is served today?',
  'What job would you assign to a friendly robot that is talented but easily distracted?',
  'If this gathering had a soundtrack made only of everyday sounds, what belongs on it?',
  'What would a museum curator place in an exhibit about your friend group?',
  'Imagine you wake up with expert knowledge of one wonderfully impractical subject; what is it?',
  'If you designed a holiday for people who need a quiet reset, how would it be observed?',
  'What fictional rule would make public transport more entertaining?',
  'If your laughter had a visible shape, what would it look like?',
  'Imagine each person here contributes one room to a shared house; what room would you create?',
  'What would be included in a starter kit for having a surprisingly good Tuesday?',
  'If a meal could grant a harmless temporary superpower, what power should tonight\'s food provide?',
  'Imagine a town where everyone must practice one creative hobby; which hobby would you propose?',
  'What would you call a weather pattern that perfectly matches your mood today?',
  'If you could make one animal-sized object enormous, which would be funniest?',
  'Imagine your phone gains a polite personality; what does it gently tease you about?',
  'What three supplies would you bring to host a party on the moon?',
  'If your favorite chair could travel, where would you send it for the view?',
  'What would a restaurant for time travelers need on its menu?',
  'Imagine that boring chores earn unusual rewards; what reward system would motivate you?',
  'If this group had to communicate using only sound effects for an hour, who would adapt fastest?',
  'What new room would you add to every home if space and cost were irrelevant?',
  'If you could rename one color based on how it feels, what name would you choose?',
  'Imagine a parade celebrating an overlooked achievement; what floats would appear?',
  'What would you put inside a vending machine that dispenses experiences instead of objects?',
  'If the next group outing had to follow a fictional map, where would the map lead?',
  'Imagine a friendly ghost joins dinner; what question should the table ask first?',
  'What local place would you show a visitor who wanted to understand daily life here?',
  'Describe a custom from any community you belong to that makes gatherings feel welcoming.',
  'What music helps create the right atmosphere for sharing a meal?',
  'Which saying, expression, or bit of slang do you enjoy explaining to people?',
  'What have you learned by eating with people whose routines differ from yours?',
  'Describe a celebration detail you find especially joyful.',
  'What craft, game, or activity connects you to a place or community?',
  'Which sound makes a neighborhood feel lively to you?',
  'What is a respectful question you enjoy answering about where you come from?',
  'Describe a food-serving habit that you find thoughtful.',
  'What place has influenced your taste in music, art, or food?',
  'Which everyday phrase carries more meaning than its literal translation?',
  'What have you discovered from attending someone else\'s celebration?',
  'Describe a public space where many different people seem comfortable gathering.',
  'What tradition would you enjoy seeing through a friend\'s eyes?',
  'Which local business gives its surroundings a distinctive character?',
  'What is something visitors often overlook about a place you know well?',
  'Describe a style of hospitality that made you feel genuinely at ease.',
  'What art form gives you a window into experiences unlike your own?',
  'Which seasonal change affects how people gather where you live?',
  'What story about a place becomes richer when several people tell it?',
  'Describe a community event you would gladly attend again.',
  'What is a meal-time courtesy you appreciate, wherever it comes from?',
  'Which place has the most interesting mix of old and new in your experience?',
  'What question helps people share their background without putting them in a box?',
  'Describe a meaningful object that can be discussed without revealing anything private.',
  'What have friends helped you understand about a culture or community beyond your own?',
  'Which language would you enjoy hearing spoken fluently, and what draws you to its sound?',
  'What neighborhood feature makes it easier for people to know one another?',
  'Describe an everyday ritual that deserves to be documented for the future.',
  'What makes a shared meal feel generous beyond the amount of food?',
  'Which film, book, or song offered you a fresh view of a place?',
  'What is a creative way communities make use of limited space?',
  'Describe a style choice that tells a story about its time or place.',
  'What can people learn by paying attention to how others welcome guests?',
  'Which public celebration would you like to experience as a curious observer?',
  'What is one way to share cultural knowledge without treating anyone as a spokesperson?',
  'Describe a market, street, or gathering place you remember through its sounds and smells.',
  'What connects people across very different backgrounds, in your experience?',
  'Which part of your surroundings would you preserve for people to enjoy years from now?',
  'What is one plan for the next month that would be more fun with friends?',
  'Design a low-cost outing that still feels like an occasion.',
  'Where could this group go when nobody wants to plan very much?',
  'What skill could friends learn together without needing to be good at it?',
  'Describe an ideal day trip with plenty of room for detours.',
  'What recurring gathering would be realistic enough to keep doing?',
  'Which ordinary place could become a great hangout with the right additions?',
  'What should be on a shared list of things to try at least once?',
  'How would you make a future dinner memorable without making it complicated?',
  'What outdoor plan works for people with different energy levels?',
  'Which unfinished group idea deserves another chance?',
  'What would make a weekend feel refreshing without requiring travel?',
  'Describe a friendly challenge everyone could prepare for at their own pace.',
  'What is a good backup plan when the main plan falls apart?',
  'Which place would be interesting to revisit at a different time of day?',
  'What could this group create together and finish in one afternoon?',
  'How would you plan an outing around one excellent snack?',
  'What activity leaves enough space for conversation as well as fun?',
  'Describe a themed dinner people could join without buying anything special.',
  'What nearby destination deserves a deliberately slow visit?',
  'Which plan becomes better when everyone brings one small contribution?',
  'What tradition could mark the changing seasons for a group of friends?',
  'How would you organize a day where each person chooses one stop?',
  'What is a plan worth putting on the calendar before everyone gets busy?',
  'Describe an evening that would feel adventurous while staying close to home.',
  'What shared goal could create good stories even if nobody completes it perfectly?',
  'Which place would suit a long conversation with no need to rush?',
  'What would make a group trip feel flexible rather than over-scheduled?',
  'How could friends turn helping with a practical task into a pleasant gathering?',
  'What is a simple plan for celebrating someone without making them the center of a spectacle?',
  'Describe a future meal where each guest contributes a story instead of a dish.',
  'What kind of club would you genuinely attend if friends started it?',
  'Which local route would make a good wandering adventure?',
  'What should everyone remember when planning for different budgets?',
  'How would you spend a free morning with this group?',
  'What new experience feels approachable when friends are involved?',
  'Describe a plan that would give everyone something to look forward to.',
  'What could become this group\'s signature annual event?',
  'Which spontaneous plan from your past would you happily repeat in a new way?',
  'What is one invitation you would like to extend to friends soon?',
  'What recent moment felt better because you could share it with someone?',
  'Describe a piece of encouragement that stayed with you.',
  'What ordinary part of life are you appreciating more these days?',
  'Which shared memory captures a side of you that you like?',
  'What have you become more curious about lately?',
  'Describe a time friendship made a difficult day feel lighter.',
  'What is something small that you are quietly looking forward to?',
  'Which personal change has made gatherings more enjoyable for you?',
  'What kind of moment makes you pause and think, this is good?',
  'Describe something a friend noticed that made you feel understood.',
  'What have you learned about making time for people who matter to you?',
  'Which recent choice gave you more room to enjoy your days?',
  'What is a joyful detail from today that might otherwise be forgotten?',
  'Describe a way your idea of fun has evolved over time.',
  'What do you hope remains familiar about this season of your life?',
  'Which conversation left you feeling more energized than when it began?',
  'What is something you appreciate more when it is unplanned?',
  'Describe a moment when someone made participation easier for you.',
  'What has a friendship helped you become more confident about?',
  'Which part of spending time together matters more than the activity itself?',
] as const satisfies readonly string[]
