export const DINNER_TABLE_DATE_NIGHT_PROMPTS = [
  "What part of your inner world has felt especially alive lately?",
  "What have you been noticing about yourself this season?",
  "Which thought has been keeping you good company recently?",
  "What has felt quietly meaningful to you this week?",
  "Where has your curiosity been wandering these days?",
  "What is taking up more of your attention than you expected?",
  "Which feeling has been easiest for you to welcome lately?",
  "What has given you a fresh sense of possibility recently?",
  "What are you currently learning to enjoy at your own pace?",
  "Which part of life feels most like you right now?",
  "What small discovery about yourself would you like to share tonight?",
  "What has been making ordinary days feel more interesting?",
  "Which question about life are you enjoying not having answered yet?",
  "What kind of moment has been restoring your energy lately?",
  "What is something you understand differently than you did a year ago?",
  "Which recent experience left you with more to think about?",
  "What would a gentle, satisfying week feel like from the inside?",
  "What personal interest deserves a little more room in your life?",
  "What has surprised you about your own response to something lately?",
  "Which side of yourself would you enjoy letting out more often?",

  "What is one way I have made life feel lighter for you recently?",
  "Which quality of mine have you appreciated in a new way lately?",
  "What ordinary thing we do together feels special to you?",
  "When have you felt especially seen by me in a small moment?",
  "What is something about us that you never want to take for granted?",
  "Which of my everyday habits brings you an unexpected bit of joy?",
  "What kind of support from me has stayed with you?",
  "What do you admire about the way we have grown together?",
  "Which part of our connection feels easiest to celebrate tonight?",
  "What is a compliment you have thought about me but not said aloud?",
  "When does being together feel most effortless to you?",
  "What do I bring to your life that feels distinctly like me?",
  "Which shared strength of ours makes you smile?",
  "What is one way you feel cared for in our relationship?",
  "What have you enjoyed watching me become better at?",
  "Which little kindness between us deserves its own toast?",
  "What about our partnership makes you feel fortunate?",
  "What is something I remember about you that makes you feel known?",
  "Which part of my personality adds a welcome flavor to your days?",
  "What recent moment made you glad we were on the same team?",

  "Which early memory of us feels different when you revisit it now?",
  "What detail from one of our first conversations still stands out?",
  "When did our connection first begin to feel comfortably familiar?",
  "What is a tiny moment from our story that deserves to be remembered?",
  "Which shared adventure became funnier with time?",
  "What meal from our past would you happily sit down to again?",
  "Which place we have visited holds the warmest atmosphere in your memory?",
  "What is a moment when we improvised and somehow made it work?",
  "Which version of us from the past would enjoy seeing us now?",
  "What soundtrack belongs to a memorable chapter of our relationship?",
  "Which unexpected detour became a favorite part of our story?",
  "What old photo of us carries a story worth retelling?",
  "Which shared first would you most enjoy experiencing again?",
  "What is a memory of us laughing that you can still picture clearly?",
  "Which past date had an ingredient you would borrow for tonight?",
  "What moment made a familiar place feel like ours?",
  "Which memory reveals something sweet about who we were becoming?",
  "What is a forgotten detail from a celebration we shared?",
  "Which ordinary day together became memorable for an unexpected reason?",
  "What chapter of our story would make the best short film?",

  "If tonight had a theme song, what mood would it carry?",
  "What harmless competition between us would make a ridiculous championship?",
  "If our relationship had a mascot, what would it be and why?",
  "What imaginary award would you present to me over dessert?",
  "If we hosted a tiny festival for two, what would be on the program?",
  "What would our signature dance move look like?",
  "If this dinner were a scene in a comedy, what would happen next?",
  "Which fictional world would be most entertaining for us to visit for a day?",
  "What silly rule would improve a made-up holiday just for us?",
  "If we formed a two-person band, what would our name and sound be?",
  "What snack best captures each of our personalities?",
  "If we traded talents for an afternoon, how would you use mine?",
  "What would be the title of a cheerful documentary about us?",
  "Which animal duo would play us in an animated movie?",
  "If we designed a secret handshake, what move would it need?",
  "What completely unnecessary luxury would make our next date hilarious?",
  "If our shared jokes became a museum exhibit, what would be displayed?",
  "What playful dare could we both complete while staying seated?",
  "If we opened a one-night pop-up restaurant, what strange specialty would we serve?",
  "What absurd product could we convincingly advertise together?",

  "How would you design an unhurried morning for the two of us?",
  "What kind of evening helps you feel close without needing much activity?",
  "Which atmosphere makes conversation flow most naturally for you?",
  "What balance of planned and spontaneous makes a date enjoyable to you?",
  "What sensory detail can instantly improve a meal for you?",
  "How do you like a shared weekend to begin?",
  "What kind of surprise feels delightful rather than overwhelming?",
  "Which simple outing almost always lifts your mood?",
  "What pace makes time together feel spacious to you?",
  "What makes a place feel inviting enough to linger?",
  "How would you spend a free hour together in an unfamiliar neighborhood?",
  "What kind of weather creates your favorite date-night mood?",
  "Which sounds belong in the background of a cozy evening?",
  "What would you include on a menu built entirely around comfort?",
  "How do you prefer to mark a small personal win together?",
  "What is your favorite way for us to make an ordinary night feel intentional?",
  "Which low-key activity leaves the most room for connection?",
  "What kind of setting brings out your most talkative side?",
  "How would you make a familiar date feel freshly interesting?",
  "What is your ideal ending to a lovely evening out?",

  "What is a tiny ritual between us that you would enjoy repeating more often?",
  "Which part of our usual greetings or goodbyes means the most to you?",
  "What everyday moment gives us a natural chance to reconnect?",
  "How can a shared meal feel like a small pause from the rest of the world?",
  "What ordinary task becomes more pleasant when we do it side by side?",
  "Which bit of our daily rhythm feels most companionable?",
  "What kind of check-in feels warm and natural to you?",
  "Where in our routine do you find an underrated moment of togetherness?",
  "What small gesture can turn your day around?",
  "Which everyday sound, phrase, or signal feels uniquely ours?",
  "What helps you arrive mentally when we finally have time together?",
  "How do you like us to reconnect after a busy stretch?",
  "What shared pause would you add to a typical day?",
  "Which mundane moment tends to bring out our best conversations?",
  "What makes sitting in comfortable silence feel connected to you?",
  "How could we make our next cup of tea or coffee feel like an occasion?",
  "What recent everyday exchange between us deserves a second look?",
  "Which routine has quietly become part of our shared identity?",
  "What is one easy way we make each other feel welcome?",
  "What piece of an average day would you bottle as a keepsake?",

  "What recent success would you enjoy celebrating a little more?",
  "Which effort of yours are you proud of even if nobody noticed?",
  "What is something you handled lately with more grace than you expected?",
  "Which personal milestone feels meaningful at this point in your life?",
  "What brave little choice have you made recently?",
  "Where have you noticed your confidence growing?",
  "What skill have you enjoyed seeing yourself develop?",
  "Which past version of you would be impressed by something you do now?",
  "What compliment have you received that you are beginning to believe?",
  "What progress feels good even though it is still unfinished?",
  "Which quality in yourself has helped you through this season?",
  "What did you do recently that felt genuinely generous?",
  "Which choice has made you feel more aligned with yourself?",
  "What is a quiet accomplishment you would like me to understand better?",
  "Where are you giving yourself more credit than you once did?",
  "What new boundary, habit, or perspective has served you well?",
  "Which part of your growth has been especially satisfying to witness from within?",
  "What have you created, repaired, or improved that brings you pride?",
  "What challenge revealed a strength you did not know you had?",
  "How would you like us to savor one of your current wins?",

  "What topic could you happily explore for an entire evening?",
  "Which new skill looks enjoyable even if you never mastered it?",
  "What place nearby are you curious to see with fresh eyes?",
  "Which everyday object has a design you find surprisingly clever?",
  "What kind of class would be fun for us to take as complete beginners?",
  "What question would you ask someone with your dream expertise?",
  "Which unfamiliar cuisine would you enjoy discovering one dish at a time?",
  "What natural phenomenon would you love to witness together?",
  "Which creative medium are you tempted to experiment with?",
  "What small mystery from daily life would you enjoy investigating?",
  "Which era would you visit briefly just to observe ordinary life?",
  "What subject became more fascinating once you learned a little about it?",
  "Which local experience have we probably overlooked?",
  "What would you enjoy collecting stories about from different people?",
  "Which behind-the-scenes process would you like to watch in person?",
  "What could we learn from each other simply by swapping roles for a hobby?",
  "Which language, craft, or tradition would you like to understand more deeply?",
  "What experiment in taste, style, or routine sounds fun to try together?",
  "Which museum could be invented specifically for one of your interests?",
  "What rabbit hole would you gladly invite me to explore with you?",

  "What value do you think shows up most clearly in the way we spend time together?",
  "Which shared experience has shaped what partnership means to you?",
  "What does feeling at home with another person mean in your own words?",
  "Which quality helps a long relationship keep feeling alive?",
  "What kind of attention makes a conversation feel meaningful to you?",
  "How has loving someone over time expanded your idea of care?",
  "What does choosing each other look like in small, ordinary moments?",
  "Which part of companionship feels more valuable as time passes?",
  "What do you hope people sense when they spend time around us together?",
  "How would you describe the particular kind of comfort we share?",
  "What has our relationship taught you about being known?",
  "Which shared principle would you place at the heart of our story?",
  "What does making room for each other's individuality add to a partnership?",
  "How has your understanding of romance become more personal over time?",
  "What kind of generosity matters most in everyday love?",
  "Which moments make commitment feel like a living choice rather than an idea?",
  "What does mutual encouragement bring out in us?",
  "How do playfulness and seriousness complement each other in our connection?",
  "What makes shared history feel like a gift rather than simply elapsed time?",
  "Which meaning have we created together that neither of us had alone?",

  "What hope has been quietly gaining energy for you?",
  "Which future experience would you love to anticipate together?",
  "What would a refreshing change of scenery look like for us?",
  "What kind of memory would you enjoy creating before this year ends?",
  "Which season of the year would you build a small tradition around?",
  "What is one dream that feels more inviting when imagined as a team?",
  "How would you like our dates to evolve as we keep changing?",
  "What future version of an ordinary evening makes you smile?",
  "Which shared project sounds energizing without needing to be productive?",
  "What would you put on a gentle wish list for our next chapter?",
  "Which place would you like to know slowly rather than visit in a rush?",
  "What kind of celebration would suit something we hope to achieve together?",
  "What is a future story you would enjoy telling about the two of us?",
  "Which interest could grow into a shared tradition over time?",
  "How might we keep making space for surprise in the years ahead?",
  "What would a tiny adventure next month look like?",
  "Which part of our future feels pleasant to picture without needing a firm plan?",
  "What would you enjoy learning alongside me over the next few years?",
  "Which simple pleasure do you hope remains part of our life for a long time?",
  "What possibility for us feels worth daydreaming about over dinner?",

  "What kind of story always captures your imagination?",
  "Which song reveals something about your taste that words cannot?",
  "What fictional character would make an unexpectedly good dinner guest for us?",
  "Which piece of art has stayed vivid in your mind?",
  "What movie scene creates a mood you wish you could step into?",
  "Which book would you enjoy hearing me react to chapter by chapter?",
  "What performance would you travel a reasonable distance to experience together?",
  "Which creator's work makes you feel understood?",
  "What story from your life deserves a better title?",
  "Which familiar song would be funniest as a dramatic duet for us?",
  "What kind of live event brings out your most enthusiastic side?",
  "Which fictional home would you borrow for a weekend?",
  "What work of art would you choose as the backdrop to tonight's conversation?",
  "Which character's wardrobe would you enjoy trying for a day?",
  "What album would you play from beginning to end during a long dinner?",
  "Which story ending have you kept thinking about long after it finished?",
  "What creative work would you love to experience again for the first time?",
  "Which scene from a show best matches our sense of humor?",
  "What kind of story would we be surprisingly good at creating together?",
  "Which cultural experience would you like us to discuss on the walk home?",

  "What flavor has become more appealing to you over time?",
  "Which meal feels celebratory without being fancy?",
  "What dish would you choose to represent your current mood?",
  "Which food memory is more about the atmosphere than the recipe?",
  "What ingredient do you think deserves a better reputation?",
  "How would you build the perfect plate for a slow conversation?",
  "Which aroma immediately transports you somewhere pleasant?",
  "What is a food opinion you can defend with playful passion?",
  "Which dessert best matches the personality of our relationship?",
  "What meal would you pair with a rainy evening and nowhere to be?",
  "Which bite from your past can you still remember clearly?",
  "What would make an outdoor meal feel magical to you?",
  "Which dish would you be delighted to perfect together?",
  "What drink feels most suited to a long, winding conversation?",
  "Which food tradition would you enjoy inventing from scratch with me?",
  "What menu would capture three different chapters of your life?",
  "Which humble food would you happily choose over something luxurious?",
  "What is the most memorable texture you have encountered in a meal?",
  "Which dinner-table sound makes a meal feel especially convivial?",
  "What culinary experience would be worth dressing up for?",

  "What does rest look like when it is genuinely nourishing for you?",
  "Which environment helps you hear your own thoughts most clearly?",
  "What small comfort are you especially grateful for lately?",
  "How do you know when you have had enough time to yourself?",
  "What kind of encouragement lands most warmly with you?",
  "Which part of the day feels most naturally reflective?",
  "What helps you shift from a busy mind into a receptive one?",
  "How do you like joy to be shared when something good happens?",
  "What form of quiet feels peaceful rather than empty to you?",
  "Which personal pleasure helps you return to yourself?",
  "What does being fully present at a meal feel like to you?",
  "How would you describe your favorite kind of contentment?",
  "What helps you feel free to be unpolished around someone?",
  "Which gentle pleasure do you wish people talked about more?",
  "What kind of company suits you when your energy is low?",
  "How can someone make space for you without making you feel distant?",
  "What recent moment gave you a sense of calm you would like to revisit?",
  "Which words make appreciation feel sincere to you?",
  "What does a deeply comfortable evening allow you to stop carrying?",
  "How do you recognize that a conversation has filled your cup?",

  "What is something about your taste that has changed since we met?",
  "Which opinion of yours has become more nuanced over the years?",
  "What new side of you do you think I have been getting to know lately?",
  "How has your idea of a good life shifted with experience?",
  "Which old preference still feels wonderfully consistent?",
  "What have you become more willing to make time for?",
  "Which expectation have you happily outgrown?",
  "What part of yourself feels steadier now than it once did?",
  "How has your relationship with spontaneity changed?",
  "What do you appreciate now that a younger you might have overlooked?",
  "Which personal priority has moved closer to the center of your life?",
  "What has become simpler for you with time?",
  "Which kind of beauty are you more able to notice these days?",
  "What once felt ordinary but now seems precious?",
  "How has your definition of adventure changed?",
  "Which part of growing older together feels unexpectedly interesting?",
  "What have you learned about the conditions in which you flourish?",
  "Which former certainty has made room for curiosity?",
  "What aspect of yourself do you hope always remains recognizable?",
  "How would you describe the person you are becoming?",

  "What question would you love for me to ask you more often?",
  "Which of your current interests would you enjoy showing me firsthand?",
  "What is something you would like us to notice together on the way home?",
  "Which story about your day would be more fun with all the tiny details included?",
  "What would help tonight feel like a memorable pause in the week?",
  "Which answer of mine are you genuinely curious to hear right now?",
  "What could we each choose for the other on a surprise mini-date?",
  "Which shared joke deserves a new chapter?",
  "What would you like to understand about the way I experience joy?",
  "Which part of tonight would you be happy to stretch a little longer?",
  "What two words would you choose for the energy between us this evening?",
  "Which question from this dinner would you enjoy continuing tomorrow?",
  "What is one thing we could admire together before the night ends?",
  "How would you capture this phase of our relationship in a postcard?",
  "What detail about me are you newly curious about?",
  "Which kind of conversation makes you lose track of time with me?",
  "What would make our next shared laugh especially welcome?",
  "Which part of being known by me still feels pleasantly surprising?",
  "What invitation for connection would feel easy to say yes to this week?",
  "What would you like us to carry from this dinner into the days ahead?",
] as const satisfies readonly string[]
