export const DO_OR_DRINK_FUNNY: readonly string[] = [
  "Narrate your next turn like a nature documentary. Or drink.",
  "Explain how to make toast in the voice of a movie villain. Or drink.",
  "Speak like a cheerful robot until your next turn. Or drink.",
  "Give a weather forecast for the mood in the room. Or drink.",
  "Say the alphabet as though each letter brings shocking news. Or drink.",
  "Describe your socks like a luxury product in a television advert. Or drink.",
  "Deliver a royal announcement declaring that snacks are now legal. Or drink.",
  "Read the title of this game like an overly dramatic news anchor. Or drink.",
  "Explain your favourite colour as if defending it in court. Or drink.",
  "Whisper a motivational speech to an imaginary potato. Or drink.",

  "Mime getting trapped inside an invisible sleeping bag. Or drink.",
  "Act out opening an umbrella during an indoor windstorm. Or drink.",
  "Pretend to walk through a room filled with invisible cobwebs. Or drink.",
  "Mime assembling furniture with instructions that make no sense. Or drink.",
  "Act out trying to catch a bubble that refuses to land. Or drink.",
  "Pretend an invisible magnet is pulling your elbows together. Or drink.",
  "Mime discovering that the floor is unexpectedly sticky. Or drink.",
  "Act out carrying a tower of imaginary cushions across the room. Or drink.",
  "Pretend to lose an argument with an automatic door. Or drink.",
  "Mime untangling the world's longest pair of headphones. Or drink.",

  "Enter the room again as a detective who has found one suspicious crumb. Or drink.",
  "Play a wizard whose only spell makes things slightly warmer. Or drink.",
  "Act like a superhero whose power is finding missing lids. Or drink.",
  "Become a pirate searching the room for a legendary biscuit. Or drink.",
  "Play a tour guide showing visitors around an extremely ordinary chair. Or drink.",
  "Act like a time traveller amazed by modern shoelaces. Or drink.",
  "Portray a ghost who is too polite to scare anyone. Or drink.",
  "Play a spy attempting to blend in at a family picnic. Or drink.",
  "Act like a chef revealing a masterpiece made entirely of air. Or drink.",
  "Become a referee for a very serious staring contest between two cushions. Or drink.",

  "Cross the room as if your knees have never met before. Or drink.",
  "Walk five steps like a penguin late for an appointment. Or drink.",
  "Perform a slow-motion victory lap around your seat. Or drink.",
  "Move like a video game character stuck against a wall. Or drink.",
  "Take three steps as though each foot has a different personality. Or drink.",
  "Demonstrate how a very tired astronaut would sit down. Or drink.",
  "Walk in a tiny circle like you are following confusing map directions. Or drink.",
  "Pretend your shoulders are competing in a silent dance contest. Or drink.",
  "Move from one side of your seat to the other in exaggerated slow motion. Or drink.",
  "Show how you would sneak past a sleeping imaginary dragon. Or drink.",

  "Invent a three-move dance called The Wobbly Sandwich. Or drink.",
  "Dance for ten seconds as if the music keeps changing genres. Or drink.",
  "Perform a seated dance using only your eyebrows and shoulders. Or drink.",
  "Create a victory dance for successfully finding your keys. Or drink.",
  "Dance like a balloon slowly losing air. Or drink.",
  "Make up a dance move inspired by folding laundry. Or drink.",
  "Perform the world's least intimidating battle dance. Or drink.",
  "Dance as though one shoe is much more enthusiastic than the other. Or drink.",
  "Create a silent disco routine for a song only you can hear. Or drink.",
  "Show the dance a confused traffic cone would do. Or drink.",

  "Hum a made-up anthem for people who arrive exactly on time. Or drink.",
  "Sing your name as a four-note opera finale. Or drink.",
  "Create a jingle advertising a completely empty box. Or drink.",
  "Beatbox the sound of a tiny train climbing a hill. Or drink.",
  "Perform a dramatic drum solo using only sounds from your mouth. Or drink.",
  "Sing one sentence about the nearest lamp or light. Or drink.",
  "Make the sound effects for an imaginary superhero landing gently. Or drink.",
  "Whistle or hum a tune that sounds like a sneaky cucumber. Or drink.",
  "Create a two-line song about forgetting why you entered a room. Or drink.",
  "Provide a musical sting for someone taking a normal sip of water. Or drink.",

  "Hold your funniest dignified expression for ten seconds. Or drink.",
  "React as though you have just learned that clouds are rented. Or drink.",
  "Show the face you would make if your sandwich winked at you. Or drink.",
  "Cycle through happy, confused, and suspicious without speaking. Or drink.",
  "Give your best expression of someone remembering an awkward handshake. Or drink.",
  "Look deeply impressed by the most ordinary object you can see. Or drink.",
  "Make a face that belongs on a poster for a terrible action film. Or drink.",
  "React silently to an imaginary bill for one million buttons. Or drink.",
  "Show what polite panic looks like using only your face. Or drink.",
  "Pose for an imaginary passport photo taken during an earthquake. Or drink.",

  "Use an imaginary spoon to conduct an orchestra of frogs. Or drink.",
  "Demonstrate three unintended uses for an invisible hat. Or drink.",
  "Pretend a nearby cushion is a phone with terrible reception. Or drink.",
  "Use an imaginary remote control that changes your own emotions. Or drink.",
  "Show how an invisible suitcase behaves when it refuses to close. Or drink.",
  "Pretend to teach a stubborn imaginary broom how to dance. Or drink.",
  "Use an imaginary magnifying glass to investigate your own sleeve. Or drink.",
  "Demonstrate an invisible gadget that solves a problem nobody has. Or drink.",
  "Pretend an imaginary scarf keeps trying to escape. Or drink.",
  "Show the group how to safely operate an invisible banana phone. Or drink.",

  "Tell a ten-second story containing a lighthouse, a slipper, and a surprise. Or drink.",
  "Describe the heroic journey of a crumb trying to reach a plate. Or drink.",
  "Invent a bedtime story with the worst possible opening sentence. Or drink.",
  "Tell the origin story of your most ordinary habit. Or drink.",
  "Create a tiny mystery about a missing left sock. Or drink.",
  "Narrate an epic quest to move from your seat to the door. Or drink.",
  "Tell a story in which a pigeon becomes mayor for one afternoon. Or drink.",
  "Invent a happy ending for a villainous alarm clock. Or drink.",
  "Describe a disastrous picnic in exactly three sentences. Or drink.",
  "Tell a heroic tale starring the last object you touched. Or drink.",

  "Give yourself a silly stage name and explain its origin. Or drink.",
  "Invent a polite replacement for a common swear word and use it in a sentence. Or drink.",
  "Create a new word for the feeling of finding forgotten snacks. Or drink.",
  "Say five words that rhyme, even if one must be imaginary. Or drink.",
  "Describe a chair without using the words sit, seat, or furniture. Or drink.",
  "Make a sentence in which every word starts with the same letter. Or drink.",
  "Invent a tongue twister about two clumsy turtles. Or drink.",
  "Explain the internet using only words a medieval knight might know. Or drink.",
  "Rename three everyday objects with unnecessarily fancy titles. Or drink.",
  "Give a one-sentence definition of nonsense that proves your point. Or drink.",

  "Draw a cat in the air using your elbow. Or drink.",
  "Sketch an imaginary self-portrait with your eyes closed. Or drink.",
  "Use your finger to draw a mystery object in the air for the group to guess. Or drink.",
  "Trace a giant smile in the air using your nose. Or drink.",
  "Draw an invisible map from your seat to an imaginary treasure. Or drink.",
  "Air-draw a house using one continuous line. Or drink.",
  "Create an invisible logo for a company that sells naps. Or drink.",
  "Draw a spiral in the air with one hand and a square with the other. Or drink.",
  "Sketch the world's most impractical bicycle in the air. Or drink.",
  "Air-draw your best guess at what laughter looks like. Or drink.",

  "Balance a safe lightweight object on the back of your hand for ten seconds. Or drink.",
  "Stack three safe nearby objects without letting them topple. Or drink.",
  "Slide a coin or similarly small safe object toward a target on the table. Or drink.",
  "Transfer a soft object from one hand to the other using only your elbows. Or drink.",
  "Make a paper scrap stand upright without holding it. Or drink.",
  "Spin a coin or another safe flat object and catch it after it stops. Or drink.",
  "Build a tiny arch from three safe objects within twenty seconds. Or drink.",
  "Balance a spoon on one finger for five seconds. Or drink.",
  "Move a napkin across the table without gripping it in your hand. Or drink.",
  "Arrange four safe objects from quietest to loudest when tapped. Or drink.",

  "Wear a napkin as formal fashion for the next round. Or drink.",
  "Model an imaginary hat designed for a very important duck. Or drink.",
  "Turn your sleeves into a red-carpet feature and strike a pose. Or drink.",
  "Present your current outfit as though it belongs in a museum. Or drink.",
  "Invent a fashion trend based on wearing everything slightly sideways. Or drink.",
  "Create a runway pose inspired by waiting for a bus. Or drink.",
  "Describe your footwear as if it has won a major award. Or drink.",
  "Style your hair using only your hands into a harmless silly shape. Or drink.",
  "Pretend to reveal an invisible cape hidden inside your outfit. Or drink.",
  "Give a serious critique of an imaginary outfit made of curtains. Or drink.",

  "Perform five seconds of seated aerobics for extremely lazy superheroes. Or drink.",
  "Make your hands act out a chase scene across your knees. Or drink.",
  "Do a slow-motion celebration without leaving your chair. Or drink.",
  "Pretend your chair is a tiny boat crossing gentle waves. Or drink.",
  "Create a hand routine that looks like two birds arguing politely. Or drink.",
  "Show a full morning routine using only movements above your shoulders. Or drink.",
  "Mime climbing one very small imaginary stair while seated. Or drink.",
  "Perform a seated moonwalk using only your feet. Or drink.",
  "Make your fingers perform a dramatic reunion scene. Or drink.",
  "Act out a sports victory using only one hand. Or drink.",

  "Invite a willing player to join you in a synchronized slow-motion high five. Or drink.",
  "With a willing partner, mirror each other's hand movements for ten seconds. Or drink.",
  "Ask a willing player to perform an imaginary tug-of-war with you. Or drink.",
  "With a willing partner, act out two people sharing one enormous umbrella. Or drink.",
  "Invite a willing player to create a two-person statue of confusion. Or drink.",
  "With a willing partner, mime carrying an awkward imaginary sofa. Or drink.",
  "Ask a willing player to join you in a three-second soap-opera reunion. Or drink.",
  "With a willing partner, invent a handshake that uses no touching. Or drink.",
  "Invite a willing player to conduct while you provide ridiculous orchestra sounds. Or drink.",
  "With a willing partner, act like two news anchors reporting a missing biscuit. Or drink.",

  "Name three objects in the room, then recall them in reverse order. Or drink.",
  "Study the room for five seconds, close your eyes, and name four colours you noticed. Or drink.",
  "Repeat the previous player's first three words in a theatrical voice. Or drink.",
  "Name one harmless detail you noticed when you first arrived. Or drink.",
  "Look away while a willing player makes a pose, then imitate it from memory. Or drink.",
  "Memorize a six-word sentence invented by the group and recite it backwards by word. Or drink.",
  "Name the last three challenges completed before this one. Or drink.",
  "Observe three safe objects, let someone rearrange them, and identify what moved. Or drink.",
  "Recall what you were doing exactly one card ago and reenact it. Or drink.",
  "Name five things you can see that begin with different letters. Or drink.",

  "Name six breakfast foods in ten seconds. Or drink.",
  "Mime three different emotions in five seconds. Or drink.",
  "Say your full name very slowly while clapping a fast rhythm. Or drink.",
  "Count from one to ten while alternating between a whisper and a normal voice. Or drink.",
  "Name four fictional places before someone counts to five. Or drink.",
  "Switch between standing and sitting in imaginary slow motion for ten seconds. Or drink.",
  "List five round things without mentioning a ball. Or drink.",
  "Make three distinct animal sounds in six seconds. Or drink.",
  "Say the days of the week as though racing an invisible opponent. Or drink.",
  "Name five things that are softer than a table in ten seconds. Or drink.",

  "Improvise being a barista who has only imaginary ingredients. Or drink.",
  "Act out returning a cloud to a shop because it is too fluffy. Or drink.",
  "Pretend to interview for the job of professional queue stander. Or drink.",
  "Improvise a customer asking whether a library sells soup. Or drink.",
  "Act like a mechanic inspecting an invisible unicycle. Or drink.",
  "Pretend to be a hotel receptionist checking in a family of penguins. Or drink.",
  "Improvise a teacher explaining why Tuesday has been cancelled. Or drink.",
  "Act out ordering lunch from a menu written entirely in riddles. Or drink.",
  "Pretend you are a tailor measuring a giant for tiny gloves. Or drink.",
  "Improvise a librarian shushing an unusually loud book. Or drink.",

  "Give a brief presentation on why naps deserve their own holiday. Or drink.",
  "Pitch a business that rents matching socks by the hour. Or drink.",
  "Present an award to yourself for an extremely minor achievement. Or drink.",
  "Explain three benefits of having an imaginary personal cloud. Or drink.",
  "Sell the group an invisible umbrella with one ridiculous feature. Or drink.",
  "Give a campaign speech for becoming president of the snack cupboard. Or drink.",
  "Present a safety briefing for travelling by flying carpet. Or drink.",
  "Deliver a short lecture on the secret social lives of spoons. Or drink.",
  "Pitch a film about a hero who always misses the bus. Or drink.",
  "Give an acceptance speech for winning Best Use of a Chair. Or drink.",

  "Act like a cat discovering its own reflection for the first time. Or drink.",
  "Imitate a dog trying to understand a magic trick. Or drink.",
  "Move like a crab navigating a crowded imaginary lift. Or drink.",
  "Show how a giraffe might attempt to play hide-and-seek. Or drink.",
  "Act like an owl struggling to stay awake during the day. Or drink.",
  "Imitate a squirrel giving directions to a lost tourist. Or drink.",
  "Move like a flamingo testing a slippery floor. Or drink.",
  "Act like a tortoise celebrating a personal speed record. Or drink.",
  "Show how a fish might react to hearing about rain. Or drink.",
  "Imitate a goat politely requesting a restaurant table. Or drink.",

  "Pretend to taste-test an imaginary soup that changes flavour every second. Or drink.",
  "Review a glass of water like a famous food critic. Or drink.",
  "Mime eating the crunchiest invisible sandwich ever made. Or drink.",
  "Describe your dream pizza using only dramatic gestures. Or drink.",
  "Act like a chef whose pancake has floated to the ceiling. Or drink.",
  "Invent a fancy menu name for plain cereal. Or drink.",
  "Pretend to peel an imaginary fruit with an absurd number of layers. Or drink.",
  "Give a cooking demonstration for a dish containing only one pea. Or drink.",
  "React as though an imaginary lemon is surprisingly sweet. Or drink.",
  "Mime sharing a very long strand of spaghetti with yourself. Or drink.",

  "Apologize sincerely to a table for bumping into it in an imaginary scene. Or drink.",
  "Interview a nearby inanimate object about its career goals. Or drink.",
  "Convince an imaginary door that you deserve to enter. Or drink.",
  "Give a cushion a pep talk before its big performance. Or drink.",
  "Act like a lamp that has just had a brilliant idea. Or drink.",
  "Stage a polite disagreement between your left shoe and your right shoe. Or drink.",
  "Thank the floor for its years of reliable service. Or drink.",
  "Pretend a clock is your coach during an important race. Or drink.",
  "Introduce a spoon as the surprise guest at a grand banquet. Or drink.",
  "Act out a blanket demanding one more day of the weekend. Or drink.",

  "Play an invisible game of hopscotch using only your fingers. Or drink.",
  "Recite a nursery rhyme as if it were a serious documentary. Or drink.",
  "Make up a playground game involving one clap and two silly poses. Or drink.",
  "Pretend to blow the world's most stubborn imaginary bubble. Or drink.",
  "Act out losing a race to a wind-up toy. Or drink.",
  "Build an imaginary pillow fort and defend its very simple rules. Or drink.",
  "Show how you once believed adults walked into every room. Or drink.",
  "Invent a secret club whose only requirement is liking round stickers. Or drink.",
  "Play a round of peekaboo with an imaginary dinosaur. Or drink.",
  "Demonstrate a new way to play tag without anyone moving. Or drink.",

  "Act like an alien trying to understand why humans use pockets. Or drink.",
  "Deliver a message from a kingdom where everyone speaks in questions. Or drink.",
  "Pretend your spaceship is powered by compliments for furniture. Or drink.",
  "Play a dragon who hoards mildly interesting receipts. Or drink.",
  "Act like a fairy granting an extremely specific wish for matching shoelaces. Or drink.",
  "Portray a knight preparing to battle a squeaky toy. Or drink.",
  "Pretend to discover a planet populated entirely by accountants. Or drink.",
  "Act like a merperson explaining how umbrellas work underwater. Or drink.",
  "Play a giant who is terrified of tiny doorbells. Or drink.",
  "Pretend to cast a spell that makes everyone remember where they put their keys. Or drink.",

  "Lead a five-second parade celebrating an ordinary weekday. Or drink.",
  "Give a toast to the person who invented pockets. Or drink.",
  "Create a fanfare for the arrival of an imaginary cake. Or drink.",
  "Celebrate finding an invisible coin as though you won a championship. Or drink.",
  "Announce a festival dedicated to comfortable chairs. Or drink.",
  "Perform a ribbon-cutting ceremony for an imaginary cupboard. Or drink.",
  "Invent a holiday greeting for National Quiet Sock Day. Or drink.",
  "Accept a pretend trophy for surviving a mildly inconvenient morning. Or drink.",
  "Start a one-person cheer for someone remembering their password. Or drink.",
  "Do a countdown to absolutely nothing, then celebrate anyway. Or drink.",

  "Act out waving back at someone who was greeting the person behind you. Or drink.",
  "Mime trying to leave a conversation but repeatedly choosing the same direction. Or drink.",
  "Pretend to push a door that clearly says pull. Or drink.",
  "Act like you have forgotten a familiar word halfway through a sentence. Or drink.",
  "Reenact realizing you have been carrying an empty bag. Or drink.",
  "Show the moment you notice your shirt is inside out without changing it. Or drink.",
  "Act out confidently entering the wrong imaginary meeting. Or drink.",
  "Pretend to laugh at a joke you heard several seconds too late. Or drink.",
  "Mime searching for glasses that are already on your face. Or drink.",
  "Act out saying goodbye and then walking in the same direction. Or drink.",

  "Declare a dramatic rivalry with an imaginary mosquito. Or drink.",
  "Deliver a soap-opera monologue about the last biscuit. Or drink.",
  "Faint theatrically into your chair after hearing mildly surprising news. Or drink.",
  "Reveal that you have secretly been three ducks in a coat all along. Or drink.",
  "Make a dramatic entrance without leaving your current spot. Or drink.",
  "Announce that the room has exactly one minute to solve an imaginary crisis. Or drink.",
  "Beg an invisible jury to forgive your terrible dance moves. Or drink.",
  "React as though a harmless paper cut has ended your action-hero career. Or drink.",
  "Give a tearful farewell to an imaginary bus you have missed. Or drink.",
  "Perform a villainous laugh that gradually turns into a polite cough. Or drink.",

  "Invent a mascot for this game and demonstrate its signature move. Or drink.",
  "Summarize the game so far as a title for a comedy film. Or drink.",
  "Create a harmless victory pose for completing this challenge. Or drink.",
  "Pretend the next card is being delivered at a royal ceremony. Or drink.",
  "Give the room a team name based on two objects you can see. Or drink.",
  "Describe your current game strategy using only three sound effects. Or drink.",
  "Act like a sports commentator reviewing your previous turn. Or drink.",
  "Design an imaginary warning label for your own sense of humour. Or drink.",
  "Thank an invisible audience for watching tonight's game. Or drink.",
  "End your turn with the closing pose of a low-budget musical. Or drink.",

  "Solve an imaginary maze by giving yourself increasingly unhelpful directions. Or drink.",
  "Pretend to crack a secret code that turns out to say hello. Or drink.",
  "Ask yourself a riddle, then confidently give the wrong answer. Or drink.",
  "Demonstrate how to complete an invisible jigsaw with one missing piece. Or drink.",
  "Act like a game-show contestant unsure what the prize actually is. Or drink.",
  "Invent a puzzle whose answer is the nearest safe object. Or drink.",
  "Pretend to unlock an imaginary safe using a dance sequence. Or drink.",
  "Explain your method for counting something that keeps moving. Or drink.",
  "Act out finally solving a mystery you accidentally created. Or drink.",
  "Give three absurd clues for the word banana. Or drink.",

  "Host a radio show for listeners who are all currently napping. Or drink.",
  "Report live from the scene of a very slow snail race. Or drink.",
  "Announce an imaginary train delay caused by excessive politeness. Or drink.",
  "Present a traffic update for a hallway with no traffic. Or drink.",
  "Interview yourself as tonight's least prepared celebrity guest. Or drink.",
  "Read an imaginary advertisement for noise-cancelling earmuffs in a whisper. Or drink.",
  "Deliver breaking news that someone has matched two socks. Or drink.",
  "Host a call-in show and answer a question from an imaginary confused baker. Or drink.",
  "Give a sports update about a championship game of rock-paper-scissors. Or drink.",
  "Sign off an imaginary broadcast with an unnecessarily elaborate catchphrase. Or drink.",
] as const
