export const DO_OR_DRINK_SOCIAL = [
  "Give a specific compliment about the welcoming energy someone brings to the room. Or drink.",
  "Compliment another player's way of making conversations feel comfortable. Or drink.",
  "Recognize a thoughtful choice someone made during this gathering. Or drink.",
  "Tell the group which shared quality makes tonight enjoyable. Or drink.",
  "Praise someone's talent for helping others join a conversation. Or drink.",
  "Offer a genuine compliment about a player's sense of humor. Or drink.",
  "Name one conversational strength you have noticed in the group. Or drink.",
  "Compliment the host on one detail that helped everyone settle in. Or drink.",
  "Acknowledge someone who has listened attentively tonight. Or drink.",
  "Give a compliment focused on effort rather than appearance. Or drink.",
  "Celebrate a player's ability to explain ideas clearly. Or drink.",
  "Tell someone what makes their stories engaging to hear. Or drink.",
  "Praise a small act of consideration you noticed in the room. Or drink.",
  "Compliment the group on something it does well together. Or drink.",
  "Recognize someone for asking an interesting question tonight. Or drink.",
  "Give a brief toast to a positive quality shared by two players. Or drink.",
  "Tell a player why their enthusiasm improves group activities. Or drink.",
  "Compliment someone's skill at making space for different opinions. Or drink.",
  "Point out a kind habit that helps gatherings run smoothly. Or drink.",
  "Thank someone for a moment when they made the room feel more inclusive. Or drink.",
  "Offer a compliment that the whole group can agree is well earned. Or drink.",
  "Praise someone's knack for finding common ground. Or drink.",
  "Describe one admirable way a player contributes to teamwork. Or drink.",
  "Compliment another player's curiosity without mentioning their appearance. Or drink.",
  "Give the room a collective compliment in exactly seven words. Or drink.",
  "Introduce yourself using your name and a harmless skill you enjoy practicing. Or drink.",
  "Introduce the player across from you using only details they shared tonight. Or drink.",
  "Give yourself a playful title based on your role in group conversations. Or drink.",
  "Welcome everyone as though this were the first meeting of a cheerful club. Or drink.",
  "Introduce two players by naming an interest they appear to share. Or drink.",
  "Present yourself as tonight's volunteer expert on a lighthearted topic. Or drink.",
  "Give a ten-second introduction suitable for joining a new game night. Or drink.",
  "Introduce the group as a team with a friendly team name. Or drink.",
  "Reintroduce yourself using three upbeat words chosen on the spot. Or drink.",
  "Welcome the newest arrival with a one-sentence summary of the room's mood. Or drink.",
  "Introduce a willing player like the guest of honor at a community event. Or drink.",
  "Present the person on your right as an expert in something they mentioned. Or drink.",
  "Create a warm opening line for meeting someone at a neighborhood gathering. Or drink.",
  "Introduce yourself by naming a favorite way to spend a free hour. Or drink.",
  "Give the circle a name and introduce its members collectively. Or drink.",
  "Welcome an imaginary new teammate and explain the current activity clearly. Or drink.",
  "Introduce yourself without mentioning work, school, or where you live. Or drink.",
  "Present another player using one strength and one safe interest they have shared. Or drink.",
  "Open an imaginary reunion by making every person present feel included. Or drink.",
  "Introduce today's gathering in the style of a friendly radio host. Or drink.",
  "Give a concise introduction that includes something you can teach the group. Or drink.",
  "Welcome the group to an imaginary club devoted to good conversation. Or drink.",
  "Introduce yourself as a character whose special power helps people connect. Or drink.",
  "Announce each side of the room as two halves of one cooperative team. Or drink.",
  "Create a friendly introduction for someone who prefers not to be the center of attention. Or drink.",
  "Listen while the player on your left names three favorite snacks, then repeat them accurately. Or drink.",
  "Ask someone a light question and summarize their answer in one sentence. Or drink.",
  "Let a player describe an ideal weekend morning, then name the detail you found most vivid. Or drink.",
  "Invite someone to explain a hobby for twenty seconds without interrupting. Or drink.",
  "Repeat the last speaker's main point before adding your own thought. Or drink.",
  "Ask a follow-up question that directly builds on what someone just said. Or drink.",
  "Listen to two opinions on a snack, then identify one point they share. Or drink.",
  "Give the next speaker your full attention and recap their final sentence. Or drink.",
  "Invite a player to name a favorite season and reflect back their reason. Or drink.",
  "Paraphrase the rules of the current game so everyone can confirm them. Or drink.",
  "Hear a player's short description of a perfect afternoon and ask one relevant question. Or drink.",
  "Wait for two other people to finish speaking before contributing to the next topic. Or drink.",
  "Ask someone to explain a simple preference and acknowledge it without debating. Or drink.",
  "Listen for one minute and name two ideas raised by different people. Or drink.",
  "Invite a willing participant who has not spoken this round and listen without filling the pause. Or drink.",
  "Restate a group suggestion neutrally before the group discusses it. Or drink.",
  "Ask a player what makes a gathering comfortable and remember their exact first point. Or drink.",
  "Let someone finish a story, then identify the moment that changed its direction. Or drink.",
  "Respond to the next comment with a sentence that shows you understood it. Or drink.",
  "Listen to a player's game idea and explain it back in your own words. Or drink.",
  "Ask an open-ended question about a shared activity in this room. Or drink.",
  "Notice when the next speaker pauses and give them space to continue. Or drink.",
  "Collect one suggestion from each side of the room before offering yours. Or drink.",
  "Summarize the last two contributions without judging either one. Or drink.",
  "Invite clarification about something just said instead of making an assumption. Or drink.",
  "Offer everyone a choice between two simple group activities. Or drink.",
  "Explain where guests can find what they need using one clear sentence. Or drink.",
  "Propose a two-minute activity that includes every willing player. Or drink.",
  "Give the room a warm welcome and set one considerate ground rule. Or drink.",
  "Check whether the group would prefer a lively or relaxed next round. Or drink.",
  "Suggest a seating adjustment that improves conversation without singling anyone out. Or drink.",
  "Announce a short break in a way that makes returning easy. Or drink.",
  "Describe how you would welcome a guest who arrives after the game begins. Or drink.",
  "Offer a simple choice that accommodates both talkative and quiet players. Or drink.",
  "Invent a gracious way to redirect the group when one topic runs long. Or drink.",
  "Name three small comforts a thoughtful host could provide in this room. Or drink.",
  "Give a thirty-second orientation for someone joining this gathering now. Or drink.",
  "Propose a fair method for choosing who begins the next activity. Or drink.",
  "Create a welcoming phrase the group can use when someone rejoins after a break. Or drink.",
  "Demonstrate how to explain a game rule without sounding impatient. Or drink.",
  "Ask the room whether anyone needs the pace or volume adjusted. Or drink.",
  "Plan a smooth transition from conversation to a group game. Or drink.",
  "Offer a host-style reminder that passing on any prompt is acceptable. Or drink.",
  "Suggest one way to make the current setup easier for everyone to participate in. Or drink.",
  "Welcome an imaginary first-time guest without making assumptions about them. Or drink.",
  "Give a closing announcement that thanks everyone and ends on time. Or drink.",
  "Create a simple signal anyone can use when they want the rules repeated. Or drink.",
  "Describe how a host can balance a schedule with spontaneous conversation. Or drink.",
  "Invite the group to help choose the atmosphere for the next ten minutes. Or drink.",
  "Offer a polite reset after pretending two activities were announced at once. Or drink.",
  "Begin a group story with a character entering a surprisingly cheerful library. Or drink.",
  "Add one sentence to a story using a detail from the previous sentence. Or drink.",
  "Continue a group tale without changing any fact already established. Or drink.",
  "Introduce a harmless problem for the story's characters to solve together. Or drink.",
  "Add a new setting to the group story and connect it to the current plot. Or drink.",
  "Narrate a transition that gives the next storyteller an easy opening. Or drink.",
  "Bring back an earlier story detail in a surprising but logical way. Or drink.",
  "Give the group story a hopeful twist in one sentence. Or drink.",
  "Add a character whose special talent is careful listening. Or drink.",
  "Turn the last story obstacle into an opportunity for teamwork. Or drink.",
  "Describe a story scene using sound, color, and movement. Or drink.",
  "Continue the tale with dialogue that reveals a useful clue. Or drink.",
  "Add a funny misunderstanding that is resolved kindly. Or drink.",
  "Connect two characters in the story through a shared goal. Or drink.",
  "Give the story a one-sentence recap before advancing the action. Or drink.",
  "Introduce an object that every character can use cooperatively. Or drink.",
  "Add a calm moment that lets the story characters make a plan. Or drink.",
  "Create a choice for the story and let the group select the next direction. Or drink.",
  "Resolve the current story scene without ending the whole tale. Or drink.",
  "Name the imaginary chapter based on everything that has happened so far. Or drink.",
  "Give a background character one sentence that helps the entire team. Or drink.",
  "Add a playful surprise that fits the story's established setting. Or drink.",
  "Tell the next part from the viewpoint of a helpful narrator. Or drink.",
  "Conclude the group story by mentioning one contribution from each storyteller. Or drink.",
  "Retell the story so far in exactly three sentences. Or drink.",
  "Propose three names for the group and guide a quick vote. Or drink.",
  "Help the room choose between two activities by stating one benefit of each. Or drink.",
  "Suggest a fair tiebreaker for a decision with equal support. Or drink.",
  "Ask for one preference from each player before recommending a plan. Or drink.",
  "Turn several snack suggestions into one balanced group choice. Or drink.",
  "Lead a vote in which abstaining is explicitly welcomed. Or drink.",
  "Summarize the group's options without favoring your own suggestion. Or drink.",
  "Find a compromise between starting now and taking a short break. Or drink.",
  "Offer a decision rule the group could reuse later tonight. Or drink.",
  "Help choose a conversation topic by combining two people's ideas. Or drink.",
  "Ask the room what matters most before selecting the next activity. Or drink.",
  "Propose a trial round so the group can decide with experience. Or drink.",
  "Give everyone five seconds to consider a choice before requesting votes. Or drink.",
  "Explain the group's final decision in a way that respects the other options. Or drink.",
  "Suggest a plan that gives two popular ideas equal time. Or drink.",
  "Invite one concern about a proposed activity and address it constructively. Or drink.",
  "Create a quick ranking method for three harmless group options. Or drink.",
  "Identify the common goal behind two competing suggestions. Or drink.",
  "Guide the group to choose a pace everyone can comfortably follow. Or drink.",
  "Offer to revisit a close decision after one short round. Or drink.",
  "Ask a player to summarize the choice while you check for agreement. Or drink.",
  "Suggest rotating who makes the next three low-stakes decisions. Or drink.",
  "Frame a decision question so a simple show of hands can answer it. Or drink.",
  "Name one situation where consensus matters more than speed. Or drink.",
  "Close a group decision by thanking people who offered alternatives. Or drink.",
  "Assign yourself a useful role in an imaginary team preparing a picnic. Or drink.",
  "Name a task you would happily handle during a group project. Or drink.",
  "Coordinate a five-second countdown with the entire room. Or drink.",
  "Lead the group in saying one word together without rehearsing twice. Or drink.",
  "Propose three roles for completing an imaginary puzzle as a team. Or drink.",
  "Explain how you would help a teammate who missed an instruction. Or drink.",
  "Ask two players to contribute different ideas toward one shared answer. Or drink.",
  "Create a team motto using a word suggested by the group. Or drink.",
  "Name one teamwork habit that prevents confusion. Or drink.",
  "Describe how to divide a simple task without ranking the roles. Or drink.",
  "Volunteer to keep time for the next one-minute group challenge. Or drink.",
  "Help the group arrange three spoken ideas into a sensible order. Or drink.",
  "Give a teammate encouraging feedback on a suggestion they just made. Or drink.",
  "Invent a cooperative challenge the room could complete while seated. Or drink.",
  "Explain how a team can recover when its first plan does not work. Or drink.",
  "Ask the group which role is still needed before choosing your own. Or drink.",
  "Combine one practical idea and one playful idea into a team plan. Or drink.",
  "Recognize the contribution that is easiest to overlook in group work. Or drink.",
  "Lead a quick check that every teammate understands the shared goal. Or drink.",
  "Suggest a way to celebrate a team effort without choosing a single winner. Or drink.",
  "Describe a respectful method for correcting a teammate's misunderstanding. Or drink.",
  "Invite someone else to lead while you offer support. Or drink.",
  "Name a strength that this particular group could use in a challenge. Or drink.",
  "Turn four random words from the room into one team slogan. Or drink.",
  "Thank the group for a cooperative moment that happened during this game. Or drink.",
  "Thank three players for three different kinds of contribution tonight. Or drink.",
  "Name a small convenience in the room that you appreciate. Or drink.",
  "Express gratitude for a conversation that made the gathering more enjoyable. Or drink.",
  "Thank someone for explaining something clearly without overcomplicating it. Or drink.",
  "Offer a one-sentence toast to the effort behind bringing everyone together. Or drink.",
  "Name one ordinary social kindness that deserves more appreciation. Or drink.",
  "Thank the last person who helped the group reach a decision. Or drink.",
  "Express appreciation for everyone who made room for another speaker. Or drink.",
  "Recognize a moment when the group adapted well to a change. Or drink.",
  "Thank someone for bringing positive energy to a quiet moment. Or drink.",
  "Share one reason you appreciate games that encourage cooperation. Or drink.",
  "Acknowledge the person who most recently clarified a confusing point. Or drink.",
  "Give thanks for a simple pleasure available at this gathering. Or drink.",
  "Tell the room why you appreciate having different perspectives present. Or drink.",
  "Thank a player for making a suggestion, whether or not it was chosen. Or drink.",
  "Express gratitude for a group tradition you enjoy without revealing private history. Or drink.",
  "Name one hosting effort that guests sometimes forget to notice. Or drink.",
  "Thank everyone who arrived ready to participate at their own comfort level. Or drink.",
  "Recognize a helpful question that improved the group's understanding. Or drink.",
  "Give a brief appreciation speech for shared laughter. Or drink.",
  "Thank someone for keeping a story moving without taking it over. Or drink.",
  "Name a communication skill you are glad someone demonstrated tonight. Or drink.",
  "Express appreciation for the group's patience during the last round. Or drink.",
  "End a gratitude statement by inviting others to notice small kindnesses. Or drink.",
  "Turn a yes-or-no question into an open-ended conversation starter. Or drink.",
  "Ask the room a question that has many easy, nonpersonal answers. Or drink.",
  "Explain a simple idea without using the words thing, stuff, or basically. Or drink.",
  "Disagree with an imaginary opinion using a respectful opening sentence. Or drink.",
  "Change the subject gracefully from weather to favorite indoor activities. Or drink.",
  "Give a concise answer first, then add one useful detail. Or drink.",
  "Invite another viewpoint after stating a harmless preference. Or drink.",
  "Replace a vague invitation with one clear and welcoming sentence. Or drink.",
  "Ask a follow-up that begins with what rather than why. Or drink.",
  "Explain the current mood using a comparison everyone can understand. Or drink.",
  "Respond to an unfamiliar idea with curiosity instead of judgment. Or drink.",
  "Offer a polite way to pause a conversation and return to it later. Or drink.",
  "Introduce a new topic by linking it to the previous speaker's last point. Or drink.",
  "Give directions for a simple imaginary activity in three clear steps. Or drink.",
  "Ask for clarification without suggesting that the speaker explained poorly. Or drink.",
  "Make a short point and invite someone else to build on it. Or drink.",
  "Describe a preference while leaving room for other people to differ. Or drink.",
  "Turn a complaint about a long wait into a constructive suggestion. Or drink.",
  "Summarize a playful debate as if both sides made strong points. Or drink.",
  "Offer a neutral phrase for interrupting only when urgent clarification is needed. Or drink.",
  "Start a conversation about something everyone can observe in the room. Or drink.",
  "End your next answer with a genuine question for another player. Or drink.",
  "Rephrase a competitive statement so it emphasizes shared fun. Or drink.",
  "Give an example of feedback that is specific, kind, and useful. Or drink.",
  "Bridge a moment of silence with a low-pressure group question. Or drink.",
  "Invite anyone who has not spoken this round to choose the next topic. Or drink.",
  "Ask the group whether people prefer answering in order or volunteering. Or drink.",
  "Offer two ways to participate in the next challenge, including a quiet option. Or drink.",
  "Make space for another voice by limiting your next response to one sentence. Or drink.",
  "Invite a willing player to pass the next question to someone else. Or drink.",
  "Suggest a round where every participant may answer with one word. Or drink.",
  "Ask whether anyone wants more thinking time before the group moves on. Or drink.",
  "Give the next choice to someone who has not chosen an activity yet. Or drink.",
  "State a discussion rule that protects both speakers and listeners. Or drink.",
  "Invite two different perspectives before the group settles on an answer. Or drink.",
  "Offer to explain the prompt again for anyone who wants clarification. Or drink.",
  "Suggest an activity that works equally well for observers and active players. Or drink.",
  "Ask the group to leave a pause after each answer in the next round. Or drink.",
  "Create a response format that prevents one person from dominating. Or drink.",
  "Invite someone to contribute through a gesture, a word, or a sentence. Or drink.",
  "Check that the current topic is comfortable for everyone before continuing. Or drink.",
  "Offer the first turn to the group without pressuring anyone to take it. Or drink.",
  "Ask a player whether they would like to speak now or later. Or drink.",
  "Propose alternating between volunteers and people who opt in by raising a hand. Or drink.",
  "Welcome a different interpretation of the current prompt. Or drink.",
  "Remind the room that a brief answer counts as full participation. Or drink.",
  "Invite the group to replace a confusing rule with clearer shared wording. Or drink.",
  "Name one way to include a person who enjoys listening more than speaking. Or drink.",
  "Ask everyone to signal readiness before beginning the next timed activity. Or drink.",
  "Create a round in which each person chooses their own level of involvement. Or drink.",
  "Ask the player on your right to name a color, then recall it after two more turns. Or drink.",
  "Repeat the three activity options the group considered earlier. Or drink.",
  "Name two details from the most recent story told in this room. Or drink.",
  "Recall who introduced the current conversation topic. Or drink.",
  "Listen as three players each name a fruit, then recite the fruits in reverse order. Or drink.",
  "Remember a player's preferred game pace and use it in the next group choice. Or drink.",
  "Name one suggestion from earlier that the group has not tried yet. Or drink.",
  "Recall the team name created during this gathering. Or drink.",
  "Ask someone for a harmless favorite and accurately mention it later this round. Or drink.",
  "List the last three speakers in the order they contributed. Or drink.",
  "Repeat a player's stated snack preference without adding an assumption. Or drink.",
  "Remember two words offered by the group and use both in one sentence. Or drink.",
  "Identify the detail that appeared twice in the current group story. Or drink.",
  "Recall the first option presented in the latest group decision. Or drink.",
  "Name a question from earlier that produced several different answers. Or drink.",
  "Ask three players for a number from one to nine, then repeat each number correctly. Or drink.",
  "Remember which person volunteered to keep time in the last activity. Or drink.",
  "Recall one compliment given earlier and identify the quality it praised. Or drink.",
  "Name the sequence of two topics the group discussed most recently. Or drink.",
  "Listen to four single-word suggestions and repeat all four in any order. Or drink.",
  "Recall one ground rule the group agreed to follow. Or drink.",
  "Remember the last choice made by a show of hands. Or drink.",
  "Ask a player to name an animal and weave it accurately into the next story turn. Or drink.",
  "Name one idea contributed by someone seated on each side of you. Or drink.",
  "Recap the current activity's goal and the next step from memory. Or drink.",
  "Invent a group cheer that can be performed using voices only. Or drink.",
  "Lead a call-and-response using two cheerful everyday words. Or drink.",
  "Create a seven-word slogan celebrating this gathering. Or drink.",
  "Ask everyone to choose one sound, then conduct a five-second soundscape. Or drink.",
  "Turn the room's current mood into a fictional weather forecast. Or drink.",
  "Give the group an imaginary award with a kind and funny title. Or drink.",
  "Lead a seated wave using only facial expressions. Or drink.",
  "Invent a mascot that represents the group's conversational style. Or drink.",
  "Ask each side of the room for a word and combine them into a club name. Or drink.",
  "Narrate ten seconds of the gathering like a nature documentary. Or drink.",
  "Create a harmless signature greeting made entirely of spoken words. Or drink.",
  "Describe the group as a team of heroes whose power is cooperation. Or drink.",
  "Lead everyone in a synchronized three-word celebration. Or drink.",
  "Invent a playful holiday honoring good listeners. Or drink.",
  "Give a dramatic announcement about the arrival of the next conversation topic. Or drink.",
  "Ask the group to complete a cheerful sentence one word at a time. Or drink.",
  "Create a nickname for tonight's gathering using two suggestions from players. Or drink.",
  "Describe an imaginary flag for the group without assigning anyone to draw it. Or drink.",
  "Lead a quick round where everyone names a different pleasant sound. Or drink.",
  "Turn a routine reminder into a friendly ceremonial proclamation. Or drink.",
  "Invent a one-line anthem about making room for every voice. Or drink.",
  "Ask the group to choose an imaginary destination for a shared adventure. Or drink.",
  "Create a closing catchphrase for the end of each game round. Or drink.",
  "Give a sports-style recap of the group's best teamwork moment. Or drink.",
  "End with a playful prediction about the group's next excellent idea. Or drink.",
  "Invite the group to invent a shared tradition that takes less than ten seconds. Or drink.",
] as const satisfies readonly string[]
