export const DO_OR_DRINK_SPICY: readonly string[] = [
  "Deliver your smoothest pickup line to an empty chair. Or drink.",
  "Give a dramatic wink to the group without laughing. Or drink.",
  "Describe your ideal first date in exactly five words. Or drink.",
  "Demonstrate your signature flirting move using only your eyebrows. Or drink.",
  "Invent a cheesy romance-novel title starring you. Or drink.",
  "Say three qualities that make you a great catch. Or drink.",
  "Recreate your best mysterious entrance from a romantic movie. Or drink.",
  "Give yourself a flirty alter ego and introduce them to the room. Or drink.",
  "Practice saying hello as if you just spotted your crush. Or drink.",
  "Pitch yourself as the prize on a fictional dating show. Or drink.",
  "Act out how you look when someone attractive walks past. Or drink.",
  "Turn your favorite snack into a seductive advertisement. Or drink.",
  "Make up a slogan for your dating life. Or drink.",
  "Reveal your most charming dance move for five seconds. Or drink.",
  "Describe your personal brand of romance as a weather forecast. Or drink.",

  "Give a sincere, nonphysical compliment to any willing player. Or drink.",
  "Ask a willing player to exchange one playful wink with you. Or drink.",
  "Tell a willing player what makes their energy attractive. Or drink.",
  "Invite a willing player to hold eye contact for five seconds. Or drink.",
  "Offer a willing player your best imaginary rose. Or drink.",
  "Ask a willing player to join you for a ten-second slow dance without touching. Or drink.",
  "Give a willing player a grand introduction worthy of a heartthrob. Or drink.",
  "Trade tasteful pet names with a willing player for one round. Or drink.",
  "Ask a willing player to rate your best smoldering look. Or drink.",
  "Serenade a willing player with one original, wholesome line. Or drink.",
  "Let a willing player choose a word for you to say flirtatiously. Or drink.",
  "Ask a willing player to mirror your most confident pose. Or drink.",
  "Give a willing player a compliment fit for a movie trailer. Or drink.",
  "Invite a willing player to invent a fictional meet-cute with you. Or drink.",
  "Ask a willing player to choose your romantic-comedy character name. Or drink.",

  "Read an imaginary love letter to pizza with complete sincerity. Or drink.",
  "Flirt with a houseplant for ten seconds. Or drink.",
  "Propose dramatically to the nearest cushion. Or drink.",
  "Whisper a compliment to your own reflection in a spoon. Or drink.",
  "Perform a breakup speech to a snack you cannot resist. Or drink.",
  "Act jealous of a lamp for getting everyone's attention. Or drink.",
  "Blow a theatrical kiss to the ceiling. Or drink.",
  "Recite a romantic poem about clean laundry. Or drink.",
  "Make a seductive entrance while carrying an ordinary object. Or drink.",
  "Treat the room to your most dramatic hair flip. Or drink.",
  "Ask an empty seat where it has been all your life. Or drink.",
  "Give a sultry weather report about a completely mild day. Or drink.",
  "Act out falling in love with the last slice of cake. Or drink.",
  "Dedicate an imaginary power ballad to your favorite beverage. Or drink.",
  "Make a candlelight-dinner toast to a bowl of cereal. Or drink.",

  "Walk across the room like you own the red carpet. Or drink.",
  "Hold your most confident pose for ten seconds. Or drink.",
  "Give a one-sentence acceptance speech for being irresistible. Or drink.",
  "Introduce yourself without using your name or occupation. Or drink.",
  "Show how you would enter a room where your crush is waiting. Or drink.",
  "Deliver a compliment to yourself without downplaying it. Or drink.",
  "Name one boundary that makes you feel more confident while dating. Or drink.",
  "Announce one thing you bring to a healthy relationship. Or drink.",
  "Model your boldest seated pose until the next turn. Or drink.",
  "Turn a nervous habit into a confident signature gesture. Or drink.",
  "Give the group your best knowing smile. Or drink.",
  "Describe yourself as a luxury experience in one sentence. Or drink.",
  "Strike a pose that says emotionally available and fabulous. Or drink.",
  "Say one feature of your personality you genuinely find attractive. Or drink.",
  "Walk three steps as though a love song just started playing. Or drink.",

  "Perform the chorus of a love song as spoken-word poetry. Or drink.",
  "Hum a tune that belongs in a steamy movie scene. Or drink.",
  "Turn a nursery rhyme into a dramatic serenade. Or drink.",
  "Sing one original line about forbidden dessert. Or drink.",
  "Dance for ten seconds like you just received a flirty message. Or drink.",
  "Create a two-step dance called The Meet-Cute. Or drink.",
  "Lip-sync an imaginary romantic duet, playing both parts. Or drink.",
  "Perform a slow-motion spin worthy of a music video. Or drink.",
  "Make up a jingle advertising your ideal date. Or drink.",
  "Use finger snaps to accompany a flirty one-line song. Or drink.",
  "Dance with an imaginary partner while keeping it playful. Or drink.",
  "Sing your name as though it ends a love ballad. Or drink.",
  "Create a short victory dance for getting someone's number. Or drink.",
  "Perform a romantic drum solo on your knees. Or drink.",
  "Make three ordinary dance moves look unexpectedly glamorous. Or drink.",

  "Act out a first date using two different characters. Or drink.",
  "Perform a soap-opera gasp after an imaginary confession. Or drink.",
  "Pretend you are caught between two fictional admirers. Or drink.",
  "Deliver a dramatic monologue about an unanswered wink. Or drink.",
  "Reenact spotting an ex while looking exceptionally good. Or drink.",
  "Play a detective investigating who stole your heart. Or drink.",
  "Act out realizing your blind date is surprisingly charming. Or drink.",
  "Perform a silent scene of getting butterflies before a kiss. Or drink.",
  "Pretend to host a reunion episode for your imaginary dating show. Or drink.",
  "Act out politely escaping a painfully boring date. Or drink.",
  "Deliver a movie-villain speech about stealing the spotlight. Or drink.",
  "Perform your reaction to receiving flowers from a secret admirer. Or drink.",
  "Act out a love triangle involving you and two desserts. Or drink.",
  "Pretend to discover your date is secretly royalty. Or drink.",
  "Create a cliff-hanger ending to an imaginary romantic episode. Or drink.",

  "Explain your ideal kiss using only movie genres. Or drink.",
  "Describe your flirting style as a menu item. Or drink.",
  "Compare your dating energy to a fictional animal. Or drink.",
  "Summarize your romantic history as a book title. Or drink.",
  "Describe your type without mentioning appearance. Or drink.",
  "Explain your current love-life mood using a song title. Or drink.",
  "Name the color that best represents your chemistry with someone. Or drink.",
  "Describe a perfect cuddle using only three adjectives. Or drink.",
  "Compare your first-date personality to a famous landmark. Or drink.",
  "Describe attraction as though it were a recipe. Or drink.",
  "Explain your biggest green flag through a sports metaphor. Or drink.",
  "Describe your dream romance as a holiday destination. Or drink.",
  "Sum up your kissing confidence with a film rating. Or drink.",
  "Describe your ideal flirtation as a dance style. Or drink.",
  "Compare your romantic patience to a household appliance. Or drink.",

  "Create a pickup line involving the word avocado. Or drink.",
  "Invent a flirty compliment that includes a weather term. Or drink.",
  "Make the word spreadsheet sound romantic. Or drink.",
  "Use three food names in one smooth pickup line. Or drink.",
  "Create a tasteful innuendo about assembling furniture. Or drink.",
  "Turn a traffic sign into a flirtatious opening line. Or drink.",
  "Make a charming invitation using the word mysterious. Or drink.",
  "Invent a pickup line for someone who loves naps. Or drink.",
  "Create a flirty sentence that rhymes with night. Or drink.",
  "Turn a boring household chore into a romantic invitation. Or drink.",
  "Make a playful compliment involving a fictional superpower. Or drink.",
  "Invent a dating-app opener for a time traveler. Or drink.",
  "Create a cheeky line about sharing the last biscuit. Or drink.",
  "Turn a grocery list into a short declaration of affection. Or drink.",
  "Make the phrase low battery sound irresistible. Or drink.",

  "Let the group give your imaginary dating profile a headline. Or drink.",
  "Choose three objects nearby as your fictional profile photos. Or drink.",
  "State one honest green flag you would put in your bio. Or drink.",
  "Deliver your imaginary dating profile as a movie preview. Or drink.",
  "Name a harmless quirk your ideal match should appreciate. Or drink.",
  "Give your dating profile a theme song and hum it. Or drink.",
  "Describe your perfect match without referring to looks or status. Or drink.",
  "Create a witty bio that is exactly six words long. Or drink.",
  "Announce the most wholesome reason someone should swipe right on you. Or drink.",
  "Pose for an imaginary profile photo chosen by the group. Or drink.",
  "Name the fictional character who would write your profile best. Or drink.",
  "Share the hobby that would feature first on your ideal profile. Or drink.",
  "Invent a harmless disclaimer for anyone who dates you. Or drink.",
  "Describe the profile photo you would never use. Or drink.",
  "Give your future date a playful one-line preview of you. Or drink.",

  "Show your reaction to getting a perfect-match notification. Or drink.",
  "Act out receiving an unexpectedly bold compliment. Or drink.",
  "Demonstrate your face when a date remembers a tiny detail. Or drink.",
  "React silently to an imaginary person asking for a second date. Or drink.",
  "Show how you recover after a failed pickup line. Or drink.",
  "Act out trying not to smile at someone attractive. Or drink.",
  "Demonstrate realizing you have been flirting by accident. Or drink.",
  "Show your face when the chemistry is instantly obvious. Or drink.",
  "React as if your crush just called you charming. Or drink.",
  "Act out noticing your date wore your favorite color. Or drink.",
  "Show your reaction to an invitation for a spontaneous date. Or drink.",
  "Demonstrate the moment a friendly chat turns flirtatious. Or drink.",
  "Act out being caught practicing a seductive look. Or drink.",
  "Show how you would respond to a respectful romantic surprise. Or drink.",
  "React to an imaginary kiss scene ending too soon. Or drink.",

  "Ask the group to choose a harmless word you must make sound seductive. Or drink.",
  "Let the group direct your five-second perfume advertisement. Or drink.",
  "Allow the group to name your imaginary signature fragrance. Or drink.",
  "Let the group choose a prop for your romantic monologue. Or drink.",
  "Ask the group for a setting, then improvise a meet-cute there. Or drink.",
  "Let the group choose your pose for an imaginary romance cover. Or drink.",
  "Ask the group to supply a noun for your pickup line. Or drink.",
  "Let the group cast you as a character in a romantic comedy. Or drink.",
  "Allow the group to choose your entrance music, then mime it. Or drink.",
  "Ask the group to title your imaginary celebrity romance. Or drink.",
  "Let the group pick an accent for one flirty sentence. Or drink.",
  "Ask the group to choose your fictional date's unusual profession. Or drink.",
  "Let the group select an emotion for your dramatic love confession. Or drink.",
  "Ask the group to invent a safe secret signal for your alter ego. Or drink.",
  "Let the group choose a mundane object for you to serenade. Or drink.",

  "Share a three-second air kiss with any willing player. Or drink.",
  "Offer your hand for a theatrical bow with a willing player. Or drink.",
  "Ask a willing player to join you in a back-to-back power pose. Or drink.",
  "Exchange a respectful compliment about style with a willing player. Or drink.",
  "Invite a willing player to perform a synchronized hair flip. Or drink.",
  "Ask a willing player to invent a couple nickname for your fictional characters. Or drink.",
  "Share a ten-second imaginary candlelit dinner with a willing player. Or drink.",
  "Invite a willing player to recreate a dramatic almost-handshake. Or drink.",
  "Ask a willing player to trade your best first-date smiles. Or drink.",
  "Perform a synchronized slow-motion entrance with a willing player. Or drink.",
  "Invite a willing player to exchange one courteous dance twirl without contact. Or drink.",
  "Ask a willing player to narrate your imaginary meet-cute together. Or drink.",
  "Share a playful toast to mutual good taste with a willing player. Or drink.",
  "Invite a willing player to pose for an imaginary prom photo. Or drink.",
  "Ask a willing player to co-star in a silent romantic-movie poster. Or drink.",

  "Give a ten-second speech about why consent is attractive. Or drink.",
  "Name one respectful way to check whether flirting is welcome. Or drink.",
  "Demonstrate a confident and gracious response to rejection. Or drink.",
  "Say one phrase that can make a romantic boundary clear. Or drink.",
  "Act out asking before moving closer on a date. Or drink.",
  "Share one way a partner can make you feel emotionally safe. Or drink.",
  "Practice accepting a changed mind without taking it personally. Or drink.",
  "Name one sign that a date deserves more personal space. Or drink.",
  "Give an example of a warm invitation with no pressure attached. Or drink.",
  "State one boundary you are proud to communicate. Or drink.",
  "Demonstrate checking in during a pretend slow dance. Or drink.",
  "Say how you would kindly pause an uncomfortable flirtation. Or drink.",
  "Name one quality that makes bold flirting feel respectful. Or drink.",
  "Practice asking whether a compliment is welcome. Or drink.",
  "Offer a one-line reminder that enthusiasm matters more than persuasion. Or drink.",

  "Narrate a romantic dinner while pretending the menu is outrageous. Or drink.",
  "Mime sharing an umbrella during an imaginary rainstorm. Or drink.",
  "Act out stargazing on a date while indoors. Or drink.",
  "Plan a dream date using only things already in the room. Or drink.",
  "Perform a toast at an imaginary anniversary dinner. Or drink.",
  "Pretend to cook a romantic meal with invisible ingredients. Or drink.",
  "Describe a cozy date that costs nothing. Or drink.",
  "Act out winning a stuffed toy for your imaginary date. Or drink.",
  "Create a five-second montage of a perfect weekend away. Or drink.",
  "Mime choosing a song for a candlelit evening. Or drink.",
  "Describe the ideal ending to a first date in one sentence. Or drink.",
  "Act out discovering a hidden rooftop date setup. Or drink.",
  "Design a romantic picnic using three imaginary items. Or drink.",
  "Pretend to give a museum tour focused entirely on romance. Or drink.",
  "Create a date-night plan for two fictional rivals. Or drink.",

  "Deliver a playful compliment in your most formal voice. Or drink.",
  "Say come here using only a hand gesture and facial expression. Or drink.",
  "Make an ordinary greeting sound delightfully suggestive without being explicit. Or drink.",
  "Read the phrase nice to meet you like a romance lead. Or drink.",
  "Say goodnight in three increasingly dramatic ways. Or drink.",
  "Turn thank you into a charming three-word response. Or drink.",
  "Whisper your favorite dessert name as though it is a secret. Or drink.",
  "Deliver a harmless double entendre about making breakfast. Or drink.",
  "Say your own name with maximum mysterious energy. Or drink.",
  "Make the phrase see you later sound like a promise. Or drink.",
  "Give a one-line toast with a mischievous pause. Or drink.",
  "Say that was fun as though you are inviting an encore. Or drink.",
  "Turn a polite goodbye into a cinematic moment. Or drink.",
  "Deliver one innocent sentence with a perfectly timed eyebrow raise. Or drink.",
  "Say maybe in a way that keeps an imaginary flirt guessing. Or drink.",

  "Create a tasteful romance-cover pose using a nearby chair. Or drink.",
  "Model an imaginary outfit for a daring first date. Or drink.",
  "Give a runway turn inspired by your favorite date-night look. Or drink.",
  "Describe the outfit that makes you feel most attractive. Or drink.",
  "Invent a signature accessory for your flirty alter ego. Or drink.",
  "Strike a pose for an imaginary fragrance named Temptation. Or drink.",
  "Show how you would adjust an invisible collar before flirting. Or drink.",
  "Create a fashion slogan for your most confident self. Or drink.",
  "Mime getting ready for a date in fast-forward. Or drink.",
  "Showcase your shoes as though they are irresistibly glamorous. Or drink.",
  "Describe your dream date-night outfit using three textures. Or drink.",
  "Turn an ordinary sleeve adjustment into a dramatic reveal. Or drink.",
  "Pose like the lead in a stylish romantic thriller. Or drink.",
  "Give an imaginary makeover reveal with a confident spin. Or drink.",
  "Model the expression that completes your boldest look. Or drink.",

  "Invent a cocktail name inspired by your love life. Or drink.",
  "Name a dessert that matches your flirting style and explain it. Or drink.",
  "Describe your ideal date as a three-course menu. Or drink.",
  "Create a romantic toast involving something sweet and something spicy. Or drink.",
  "Pretend to feed yourself one imaginary strawberry in slow motion. Or drink.",
  "Advertise a glass of water as the hottest drink in town. Or drink.",
  "Name a food pairing that represents your ideal chemistry. Or drink.",
  "Turn ordering dessert into a dramatic declaration. Or drink.",
  "Describe your crush energy as a flavor combination. Or drink.",
  "Invent a romantic fortune-cookie message for yourself. Or drink.",
  "Make an imaginary cup of tea look scandalously exciting. Or drink.",
  "Create a menu description for a dish called First Kiss. Or drink.",
  "Mime sharing the last bite with an imaginary date. Or drink.",
  "Give a sensual but silly review of plain toast. Or drink.",
  "Name the snack you would bring to a midnight date. Or drink.",

  "Perform your best voice for a late-night radio host. Or drink.",
  "Read an imaginary bedtime story in a charming voice. Or drink.",
  "Give a hushed tour of an imaginary moonlit city. Or drink.",
  "Describe the night sky as if it were flirting with you. Or drink.",
  "Create a secret midnight greeting for your alter ego. Or drink.",
  "Act out sneaking one last dance before bedtime. Or drink.",
  "Deliver a goodnight message to the room like a romantic lead. Or drink.",
  "Mime lighting candles for an imaginary late-night dinner. Or drink.",
  "Tell a ten-second story about an unexpectedly magical evening. Or drink.",
  "Perform a slow stretch as though waking after a perfect date. Or drink.",
  "Describe your ideal after-dark adventure without leaving the room. Or drink.",
  "Create a name for a fictional club where flirting is always respectful. Or drink.",
  "Act out hearing your favorite slow song at midnight. Or drink.",
  "Whisper a dramatic farewell to the moon. Or drink.",
  "Invent a harmless secret that only your night-time alter ego knows. Or drink.",

  "Give a fictional crush a charming code name. Or drink.",
  "Describe the plot twist that would improve your current romantic comedy. Or drink.",
  "Name the actor who would play your confident alter ego. Or drink.",
  "Invent a superpower useful only on first dates. Or drink.",
  "Create a fictional holiday celebrating excellent chemistry. Or drink.",
  "Design a secret lair for a lovable heartbreaker. Or drink.",
  "Name the signature move of your imaginary romance superhero. Or drink.",
  "Describe a magical object that detects mutual attraction. Or drink.",
  "Invent a fairy-tale curse cured by healthy communication. Or drink.",
  "Create a villain whose weakness is sincere compliments. Or drink.",
  "Name the fictional town where every date goes surprisingly well. Or drink.",
  "Invent a spell for summoning the courage to flirt. Or drink.",
  "Describe your love life as a harmless fantasy quest. Or drink.",
  "Create a mascot for respectful romantic tension. Or drink.",
  "Name the award your imaginary love story would win. Or drink.",

  "Hold a straight face while giving your most over-the-top smolder. Or drink.",
  "Balance an imaginary crown while delivering a pickup line. Or drink.",
  "Keep eye contact with your own reflection for five seconds. Or drink.",
  "Say irresistible three times without smiling. Or drink.",
  "Perform a confident wink with each eye separately. Or drink.",
  "Walk backward for three careful steps while striking a romantic pose. Or drink.",
  "Deliver a smooth compliment immediately after a deliberate hiccup sound. Or drink.",
  "Maintain a glamorous pose while naming five date ideas. Or drink.",
  "Blow three air kisses without making the same expression twice. Or drink.",
  "Say hello flirtatiously while pretending to be extremely sleepy. Or drink.",
  "Hold an imaginary rose between your teeth for a silent pose. Or drink.",
  "Perform a slow-motion wink that lasts three seconds. Or drink.",
  "Give a romantic speech while keeping both hands in your pockets. Or drink.",
  "Create a heart shape with your hands behind your back. Or drink.",
  "Finish a pickup line while doing a careful seated shoulder shimmy. Or drink.",
]
