export const DO_OR_DRINK_DARES: readonly string[] = [
  "Act like a detective examining an ordinary pencil for an important clue. Or drink.",
  "Pretend you are a museum guide presenting the nearest chair as a masterpiece. Or drink.",
  "Mime opening a gift that becomes more surprising with every layer. Or drink.",
  "Play a chef proudly serving an invisible meal to a food critic. Or drink.",
  "Act out missing an imaginary bus by one dramatic second. Or drink.",
  "Pretend to be a librarian discovering that every book can whisper. Or drink.",
  "Play an astronaut calmly repairing an imaginary dashboard. Or drink.",
  "Act like a magician whose rabbit keeps giving stage directions. Or drink.",
  "Mime being interviewed after winning a championship in tidying. Or drink.",
  "Pretend you are a shopkeeper selling clouds in different sizes. Or drink.",
  "Act out a superhero realizing their power only works on stationery. Or drink.",
  "Play a royal messenger delivering news about a missing teaspoon. Or drink.",
  "Pretend to direct traffic made entirely of slow-moving turtles. Or drink.",
  "Act like a scientist testing whether an imaginary feather can sing. Or drink.",
  "Mime a photographer arranging an extremely impatient group of statues. Or drink.",
  "Play a gardener encouraging one stubborn imaginary flower to bloom. Or drink.",
  "Act out a pilot announcing a gentle landing on a giant cushion. Or drink.",
  "Pretend to be a tailor measuring an invisible giant for a jacket. Or drink.",
  "Play a mayor opening the world's smallest public park. Or drink.",
  "Act like an archaeologist uncovering a perfectly ordinary button. Or drink.",

  "Describe your morning in the voice of a suspenseful film trailer. Or drink.",
  "Count backward from ten in a cheerful robot voice. Or drink.",
  "Explain how a door works in the voice of an excited sports commentator. Or drink.",
  "Say three kind sentences in the voice of a sleepy dragon. Or drink.",
  "Announce the day of the week like a grand opera narrator. Or drink.",
  "Describe the nearest object in a whispering detective voice. Or drink.",
  "Recite the alphabet in the voice of a nervous game-show host. Or drink.",
  "Give a weather report in the voice of a delighted pirate. Or drink.",
  "Explain how to tie a shoelace in a dignified royal voice. Or drink.",
  "Name five colors in the voice of a tiny friendly monster. Or drink.",
  "Introduce yourself in the voice of an old-fashioned radio announcer. Or drink.",
  "Describe a sandwich in the voice of a serious documentary narrator. Or drink.",
  "Read the time aloud in the voice of a confused wizard. Or drink.",
  "Give directions to an imaginary kitchen in a superhero voice. Or drink.",
  "Say a tongue twister in the voice of a calm meditation guide. Or drink.",
  "Explain rain in the voice of someone sharing wonderful news. Or drink.",
  "Name four animals in the voice of a malfunctioning tour guide. Or drink.",
  "Describe a sock in the voice of an elegant auctioneer. Or drink.",
  "Deliver a one-line warning in the voice of a polite computer. Or drink.",
  "Welcome everyone to the room in the voice of a weary time traveler. Or drink.",

  "Invent a rhyme containing the words chair and bear. Or drink.",
  "Name six words that begin and end with different vowels. Or drink.",
  "Create a five-word sentence in which every word starts with S. Or drink.",
  "Say a compliment without using the letter E. Or drink.",
  "Invent a new word for the feeling of finding a lost pen and define it. Or drink.",
  "Give three rhyming clues for the word light. Or drink.",
  "Name four things whose names contain a silent letter. Or drink.",
  "Turn the word table into a playful acronym. Or drink.",
  "Make a sentence using both moonlight and marmalade. Or drink.",
  "List five words that become new words when their first letter changes. Or drink.",
  "Describe a clock using exactly seven words. Or drink.",
  "Invent a tongue twister about a blue balloon. Or drink.",
  "Name four words that sound pleasant but are not adjectives. Or drink.",
  "Create a question in which every word has four letters or fewer. Or drink.",
  "Give a definition of umbrella without saying rain, wet, or weather. Or drink.",
  "Say a sentence whose words begin with consecutive letters from A to E. Or drink.",
  "Invent a two-line poem about a quiet spoon. Or drink.",
  "Name three compound words and swap their first halves. Or drink.",
  "Describe laughter using only words that start with C. Or drink.",
  "Create a slogan for Tuesdays that includes an internal rhyme. Or drink.",

  "Draw a recognizable cat using only five straight lines. Or drink.",
  "Sketch a house without lifting your drawing hand from the page. Or drink.",
  "Draw an imaginary fruit and label its three unusual features. Or drink.",
  "Sketch the nearest object using your non-dominant hand. Or drink.",
  "Draw a tiny map from your seat to an imaginary treasure. Or drink.",
  "Create a face using only circles and triangles. Or drink.",
  "Draw a robot designed to perform one household chore. Or drink.",
  "Sketch a landscape made entirely from letters of your name. Or drink.",
  "Draw a maze with one entrance and one clear exit. Or drink.",
  "Illustrate the phrase raining ideas without writing any words. Or drink.",
  "Draw a creature that could live inside a clock. Or drink.",
  "Sketch a new flag for an imaginary peaceful island. Or drink.",
  "Draw the outline of your hand as if it were a mountain range. Or drink.",
  "Create a four-panel stick-figure story with no dialogue. Or drink.",
  "Draw a familiar object from a bird's-eye view. Or drink.",
  "Sketch a pair of shoes designed for a cloud. Or drink.",
  "Draw a symmetrical pattern using at least three shapes. Or drink.",
  "Turn a scribble into a recognizable animal. Or drink.",
  "Draw a room where every piece of furniture is round. Or drink.",
  "Sketch an invention that keeps bookmarks from falling out. Or drink.",

  "Study five nearby objects for ten seconds, look away, and name them. Or drink.",
  "Repeat this sequence backward: lamp, river, seven, apple. Or drink.",
  "Name the last five letters of the alphabet in reverse order. Or drink.",
  "Listen to a six-word sentence from another player and repeat it backward by word. Or drink.",
  "Memorize a four-beat table tap pattern and reproduce it once. Or drink.",
  "Name three details you noticed about the room when you first entered. Or drink.",
  "Hear four unrelated nouns and recall them after counting to ten. Or drink.",
  "Recite the months backward from December to July. Or drink.",
  "Look at a small arrangement of three safe objects, turn away, and describe their order. Or drink.",
  "Repeat the sequence 3, 8, 1, 6, 4 without changing the order. Or drink.",
  "Name every category challenge you have completed so far this round. Or drink.",
  "Memorize and repeat the phrase silver kites drift quietly twice. Or drink.",
  "Recall what the player before you said on their most recent turn. Or drink.",
  "Name four colors you can currently see without looking around again. Or drink.",
  "Repeat a seven-clap rhythm demonstrated slowly by another player. Or drink.",
  "Study a drawn symbol for five seconds, hide it, and recreate it. Or drink.",
  "Say the days of the week in reverse without restarting. Or drink.",
  "Remember three numbers chosen aloud and state their sum after the next challenge is read. Or drink.",
  "List four objects you passed on your way into this room. Or drink.",
  "Repeat a short sentence after replacing each noun with the word banana. Or drink.",

  "Pat your knees twice, clap once, and repeat the pattern four times. Or drink.",
  "Trace a square in the air with one hand and a circle with the other. Or drink.",
  "Balance a lightweight cushion on one open palm for ten seconds. Or drink.",
  "Tap each fingertip to your thumb from index to little finger and back twice. Or drink.",
  "Pass a soft object from hand to hand around your waist three times while seated. Or drink.",
  "Point left while looking right, then switch sides five times slowly. Or drink.",
  "Roll an imaginary ball from one shoulder to the other without using your hands. Or drink.",
  "Draw a figure eight in the air with each index finger in opposite directions. Or drink.",
  "Touch your right ear with your left hand and your left shoulder with your right hand, then switch. Or drink.",
  "Tap the table in a steady beat while counting aloud by twos to twelve. Or drink.",
  "Move a coin-sized safe object between the backs of your hands without dropping it. Or drink.",
  "Mime juggling three slow balloons while keeping your feet still. Or drink.",
  "Rotate one wrist clockwise and the other counterclockwise for five seconds. Or drink.",
  "Point to four corners of the room in a smooth clockwise sequence. Or drink.",
  "Pretend to type with one hand while conducting music with the other. Or drink.",
  "Stack three lightweight safe objects and unstack them using one hand. Or drink.",
  "Make alternating shoulder and finger movements to a steady count of eight. Or drink.",
  "Slide a sheet of paper between your hands without gripping its edges. Or drink.",
  "Air-draw your first name with your elbow while seated. Or drink.",
  "Move both hands through the motions of tying two different imaginary knots. Or drink.",

  "Invent a holiday celebrating misplaced objects and describe one tradition. Or drink.",
  "Imagine gravity becomes half as strong and explain how the room changes. Or drink.",
  "Design a friendly creature made from three household objects. Or drink.",
  "Describe a city where every building makes a different musical note. Or drink.",
  "Invent a useful superpower that only works for ten seconds a day. Or drink.",
  "Explain what clouds might keep in their pockets. Or drink.",
  "Create a new season between spring and summer and name its weather. Or drink.",
  "Imagine the nearest lamp can grant one very small wish and choose it. Or drink.",
  "Describe a school where the teachers are friendly animals. Or drink.",
  "Invent a vehicle powered by compliments and explain its dashboard. Or drink.",
  "Imagine mirrors show tomorrow and describe one ordinary reflection. Or drink.",
  "Create a planet where everything grows downward from the sky. Or drink.",
  "Invent a pocket-sized festival and describe its main event. Or drink.",
  "Imagine your shoes can give advice and share their first suggestion. Or drink.",
  "Describe a library that lends experiences instead of books. Or drink.",
  "Invent a new shape and explain how many corners it has. Or drink.",
  "Imagine every color has a sound and describe the sound of green. Or drink.",
  "Create a job for someone who organizes dreams. Or drink.",
  "Describe the menu at a cafe for time travelers. Or drink.",
  "Invent a harmless button for the room and explain what it does. Or drink.",

  "Solve this riddle: what has hands but cannot clap. Or drink.",
  "Arrange the numbers two, three, and four aloud from greatest product potential to least. Or drink.",
  "Name the odd item out and explain why: spoon, fork, plate, violin. Or drink.",
  "Give two different ways to make ten using positive whole numbers. Or drink.",
  "Continue this pattern with two terms: circle, square, circle, triangle. Or drink.",
  "Solve this clue: I become shorter as I grow older and give light. Or drink.",
  "Name a word that can follow both sun and flower. Or drink.",
  "Work out which is heavier: a kilogram of paper or a kilogram of pencils. Or drink.",
  "State the next number in the sequence one, two, four, seven, eleven. Or drink.",
  "Find a word that becomes another word when its first letter is removed. Or drink.",
  "Explain how to divide eight identical imaginary biscuits equally among four people. Or drink.",
  "Solve this riddle: what has one eye but cannot see. Or drink.",
  "Name three different categories that the word orange can belong to. Or drink.",
  "Choose the missing direction in this cycle: north, east, south, blank. Or drink.",
  "Find the hidden animal across the words elegant tiger. Or drink.",
  "Say which does not belong and defend your answer: two, three, five, nine. Or drink.",
  "Turn the letters in LISTEN into another six-letter word. Or drink.",
  "Answer without counting on your fingers: how many corners do three squares have altogether. Or drink.",
  "Name something that has keys but opens no locks. Or drink.",
  "Explain the rule behind the sequence A, C, E, G. Or drink.",

  "Tell a thirty-second story that begins with a ringing clock and ends with a blue hat. Or drink.",
  "Create a story about a brave paperclip using exactly four sentences. Or drink.",
  "Tell a mystery in which the missing item was never actually missing. Or drink.",
  "Narrate a journey to the kitchen as an epic quest. Or drink.",
  "Make up a bedtime story for a robot that cannot power down. Or drink.",
  "Tell a tale where the villain solves the hero's smallest problem. Or drink.",
  "Create a story that includes a ladder, a lemon, and a lullaby. Or drink.",
  "Retell a familiar fairy tale from the viewpoint of a doorway. Or drink.",
  "Tell a story in which every problem is solved by careful labeling. Or drink.",
  "Invent the origin story of an ordinary mug. Or drink.",
  "Tell a three-sentence adventure with a question as the middle sentence. Or drink.",
  "Create a story about two shadows that choose different careers. Or drink.",
  "Narrate the biography of an imaginary champion napper. Or drink.",
  "Tell a tale that moves from the future to the present to the past. Or drink.",
  "Invent a legend explaining why pockets have corners. Or drink.",
  "Tell a story without using the words and, but, or then. Or drink.",
  "Create a tiny comedy about a serious banana and a playful calculator. Or drink.",
  "Narrate an ordinary afternoon from the perspective of the ceiling. Or drink.",
  "Tell a story whose first and last sentence are identical. Or drink.",
  "Invent a sequel to a dream you remember without revealing anything private. Or drink.",

  "Stand on one foot beside your seat for eight seconds while focusing on a fixed point. Or drink.",
  "Balance a paperback book on your head for ten seconds while standing still. Or drink.",
  "Hold a heel-to-toe stance beside your seat for eight seconds. Or drink.",
  "Balance a lightweight paper card on one fingertip for five seconds. Or drink.",
  "Stand with your feet together and slowly turn your head left and right twice. Or drink.",
  "Hold both arms straight ahead while standing still for ten seconds. Or drink.",
  "Balance a cushion on one knee while seated for eight seconds. Or drink.",
  "Rise onto your toes beside your seat and hold for five seconds. Or drink.",
  "Stand with one foot slightly ahead of the other and count slowly to ten. Or drink.",
  "Balance an empty paper cup on the back of your hand for eight seconds. Or drink.",
  "Hold a seated knee lift for five seconds on each side. Or drink.",
  "Stand like a motionless flamingo for six seconds near your seat. Or drink.",
  "Balance a folded sheet of paper on your shoulder for ten seconds. Or drink.",
  "Hold a wide steady stance and reach both hands gently toward the ceiling. Or drink.",
  "Stand beside your seat and slowly shift your weight from left foot to right foot four times. Or drink.",
  "Balance a soft lightweight object on your forearm for eight seconds. Or drink.",
  "Sit upright and hold both feet just above the floor for five seconds. Or drink.",
  "Stand with one hand hovering above your chair and close one eye for five seconds. Or drink.",
  "Balance a pencil horizontally across two open palms for ten seconds. Or drink.",
  "Hold a gentle seated pose with one arm up and the other out for eight seconds. Or drink.",

  "Clap a steady four-beat pattern and repeat it three times at the same speed. Or drink.",
  "Tap a rhythm that sounds like your first name. Or drink.",
  "Create an eight-count beat using claps, snaps, or table taps. Or drink.",
  "Hum one note while tapping a different steady pulse for ten seconds. Or drink.",
  "Copy a short rhythm made by the player to your left. Or drink.",
  "Make a rhythm that gradually gets quieter without slowing down. Or drink.",
  "Tap three quick beats and three slow beats in alternating sets. Or drink.",
  "Create a beat using only two different mouth sounds. Or drink.",
  "Keep a steady pulse while saying the alphabet from A to H. Or drink.",
  "Perform a seated drumroll that ends on exactly the count of eight. Or drink.",
  "Turn the phrase good morning into a repeating spoken rhythm. Or drink.",
  "Tap a five-beat pattern and invite the room to echo it once. Or drink.",
  "Make a rhythm inspired by a ticking clock that speeds up slightly. Or drink.",
  "Alternate a clap and a knee tap twelve times without breaking tempo. Or drink.",
  "Create a quiet rhythm using only fingertip taps. Or drink.",
  "Beatbox a simple pattern for ten seconds at an even pace. Or drink.",
  "Conduct an imaginary orchestra through four slow beats and four fast beats. Or drink.",
  "Say one, two, three, four while clapping only on two and four. Or drink.",
  "Invent a three-sound rhythm and perform it backward. Or drink.",
  "Keep time with one hand while the other marks every third beat. Or drink.",

  "Name five rectangular things you can see from your seat. Or drink.",
  "Find two objects in the room that share an unexpected color. Or drink.",
  "Identify the nearest object with visible writing and count its words. Or drink.",
  "Spot something in the room that has both a curved edge and a straight edge. Or drink.",
  "Name three different materials visible in the room. Or drink.",
  "Find an object whose shadow resembles a different object. Or drink.",
  "Identify the smallest clearly visible item without leaving your seat. Or drink.",
  "Name two objects positioned at roughly the same height. Or drink.",
  "Find a repeating pattern somewhere in the room and describe it. Or drink.",
  "Point out an object that could be viewed as perfectly symmetrical. Or drink.",
  "Name four things you can see that contain no letter A in their names. Or drink.",
  "Find the object with the most corners that you can clearly see. Or drink.",
  "Identify one item that reflects light and one that absorbs it. Or drink.",
  "Name three visible objects arranged from nearest to farthest. Or drink.",
  "Find two different objects that make similar sounds when used normally. Or drink.",
  "Choose a visible object and describe one detail others may have missed. Or drink.",
  "Count how many distinct light sources are visible without moving around. Or drink.",
  "Find an object whose function is not obvious from its shape. Or drink.",
  "Name one thing above eye level and one thing below knee level. Or drink.",
  "Identify three visible items that could fit inside one another. Or drink.",

  "Lead the group in saying one word each to build a complete sentence. Or drink.",
  "Create a four-beat clap pattern for everyone to echo once. Or drink.",
  "With another player, alternate words to describe an imaginary holiday. Or drink.",
  "Guide two players to name alternating items in the same category for six turns. Or drink.",
  "Start a sound pattern that each player can extend with one new sound. Or drink.",
  "Coordinate a seated group wave that travels around the room once. Or drink.",
  "With a partner, count from one to ten by alternating numbers without overlap. Or drink.",
  "Lead everyone in freezing silently on the same countdown from three. Or drink.",
  "Build a six-word group story by inviting one word from each available player in order. Or drink.",
  "Choose a category and take turns with another player naming items until you reach eight total. Or drink.",
  "Conduct the group to hum one comfortable note together for three seconds. Or drink.",
  "With another player, mirror simple hand movements from across the room for ten seconds. Or drink.",
  "Lead a call-and-response using the words ready and steady. Or drink.",
  "Coordinate three players to point in three different directions on the same count. Or drink.",
  "Start a compliment chain focused only on imaginary characters. Or drink.",
  "With a partner, invent a handshake made entirely of matching gestures from a distance. Or drink.",
  "Lead the room in spelling a five-letter word one letter per person. Or drink.",
  "Coordinate a group countdown where each number uses a different safe sound. Or drink.",
  "With another player, create matching statues without looking at each other's final pose until the reveal. Or drink.",
  "Guide the group to make a ten-second imaginary rainstorm using only quiet finger sounds. Or drink.",

  "Mime brushing your teeth while your reflection moves one second late. Or drink.",
  "Act out packing an invisible suitcase for a trip to the moon. Or drink.",
  "Pretend to fold a fitted sheet that keeps changing shape. Or drink.",
  "Mime finding the perfect radio station on an imaginary dial. Or drink.",
  "Act out watering a row of flowers that grow at different speeds. Or drink.",
  "Pretend to polish an invisible trophy that is much taller than you. Or drink.",
  "Mime making a sandwich with ingredients that keep floating away. Or drink.",
  "Act out reading a map that rotates whenever you turn it. Or drink.",
  "Pretend to assemble a tiny tent for an imaginary mouse. Or drink.",
  "Mime opening a window against a gentle imaginary breeze. Or drink.",
  "Act out choosing between several invisible hats in a mirror. Or drink.",
  "Pretend to organize a shelf of objects that keep swapping places. Or drink.",
  "Mime catching and releasing a slow imaginary butterfly. Or drink.",
  "Act out painting a fence with a brush that changes size. Or drink.",
  "Pretend to repair an imaginary clock with oversized tools. Or drink.",
  "Mime following a recipe written in disappearing ink. Or drink.",
  "Act out wrapping a perfectly round invisible present. Or drink.",
  "Pretend to untangle a string of imaginary lights one careful loop at a time. Or drink.",
  "Mime testing a series of invisible keys in a stubborn lock. Or drink.",
  "Act out carrying a tray of imaginary jelly across three careful steps. Or drink.",

  "Explain how to use a spoon as though presenting a revolutionary invention. Or drink.",
  "Give a one-minute lesson on an imaginary subject called advanced napping. Or drink.",
  "Deliver a campaign speech for making weekends one hour longer. Or drink.",
  "Describe your ideal reading corner in exactly three sentences. Or drink.",
  "Pitch a television show about competitive sock matching. Or drink.",
  "Give an acceptance speech for an award in excellent listening. Or drink.",
  "Present three rules for a sport played with invisible feathers. Or drink.",
  "Explain why circles deserve a national appreciation day. Or drink.",
  "Give a short motivational speech to someone starting a jigsaw puzzle. Or drink.",
  "Introduce an imaginary expert whose specialty is quiet celebrations. Or drink.",
  "Describe a normal pencil as if it were a rare historical artifact. Or drink.",
  "Give a breaking-news report about a clock being exactly on time. Or drink.",
  "Present a safety briefing for passengers on an imaginary flying sofa. Or drink.",
  "Explain the benefits of owning a pocket-sized rainbow. Or drink.",
  "Give a product demonstration for a notebook that remembers forgotten ideas. Or drink.",
  "Deliver a closing argument defending breakfast for dinner. Or drink.",
  "Host a brief quiz show with one question and an imaginary contestant. Or drink.",
  "Announce the grand opening of a shop that sells only useful sounds. Or drink.",
  "Give a guided meditation about waiting for toast. Or drink.",
  "Present an award to the most dependable object in the room. Or drink.",
] as const
