export const DO_OR_DRINK_DRINKING: readonly string[] = [
  "Identify the gas that gives sparkling water its bubbles. Or drink.",
  "Describe what steeping does to tea leaves, using everyday language. Or drink.",
  "Solve this beverage riddle aloud: I begin as a bean and often end in a mug. Or drink.",
  "Distinguish juice from zest as if you were explaining a citrus menu. Or drink.",
  "Tell the group what decaffeinated means without promising that it means caffeine-free. Or drink.",
  "Answer a pretend quiz host asking whether a mocktail needs alcohol. Or drink.",
  "Trace coffee's journey from plant to cup in a spoken story. Or drink.",
  "Reveal the ordinary meaning of the word carbonation in a theatrical whisper. Or drink.",
  "Tea bags and loose leaves walk into a fictional quiz: explain what they have in common. Or drink.",
  "Name the fruit behind the word lemonade and give it a royal title. Or drink.",
  "Translate tart into a description that would make sense on a drinks menu. Or drink.",
  "Give the tasting word crisp a meaning that has nothing to do with potato chips. Or drink.",
  "Use floral in a fictional beverage review without mentioning a specific flower. Or drink.",
  "Contrast aroma with flavor using an imagined cup of tea. Or drink.",
  "Make earthy sound appealing in an imaginary menu description. Or drink.",
  "Replace delicious with more precise language in a pretend drink review. Or drink.",
  "Demonstrate with your voice how a mellow flavor differs from a sharp flavor. Or drink.",
  "Define mouthfeel without putting anything in your mouth. Or drink.",
  "Invent a beverage description that uses bright without referring to its color. Or drink.",
  "Turn the word balanced into a tiny speech about flavor. Or drink.",
  "Pitch an alcohol-free drink inspired by a rainy afternoon. Or drink.",
  "Design a fictional mocktail menu for a library where the drinks have literary names. Or drink.",
  "Create a name and flavor idea for a cucumber refresher served at an imaginary garden party. Or drink.",
  "Sell the group on a citrus mocktail with the confidence of a theater announcer. Or drink.",
  "Rename plain sparkling water as though it were the star of a glamorous menu. Or drink.",
  "Compose a menu description for an alcohol-free drink inspired by moonlight. Or drink.",
  "Dream up a tea-based mocktail whose name sounds like a mystery novel. Or drink.",
  "Present an imaginary cafe special built around peach and a cozy mood. Or drink.",
  "Choose a beverage concept for a fictional underwater restaurant and explain the name. Or drink.",
  "Build a spoken pitch for a watermelon refresher that sounds like summer. Or drink.",
  "Welcome the group to an imaginary drinks station where choosing water feels special. Or drink.",
  "Announce a fictional menu so alcohol-free choices receive the same enthusiasm as everything else. Or drink.",
  "Offer a gracious hosting line for a guest who declines a beverage. Or drink.",
  "Plan the look of an imaginary refreshment table with clear labels. Or drink.",
  "Rehearse asking an imaginary guest what they would enjoy without assuming alcohol is involved. Or drink.",
  "Suggest a comfortable place for a fictional water station and explain your choice. Or drink.",
  "Deliver a host's opening welcome that makes passing on drinks feel ordinary. Or drink.",
  "Arrange an imaginary cafe counter aloud so the menu is easy to read. Or drink.",
  "Write a drinks-station sign in the air, then read its welcoming wording aloud. Or drink.",
  "Propose a party tradition centered on conversation instead of beverage choices. Or drink.",
  "Outline a goblet in the air and point out its stem. Or drink.",
  "Compare the silhouettes of a mug and a tumbler using your hands. Or drink.",
  "Act as a museum guide introducing an imaginary teacup as a priceless treasure. Or drink.",
  "Explain what a saucer does with the seriousness of an engineering lecture. Or drink.",
  "A handleless cup needs a job; deliver its persuasive application aloud. Or drink.",
  "Describe a transparent glass as though advising the designer of an imaginary drinks display. Or drink.",
  "Mime inspecting an empty fictional carafe for an art exhibition. Or drink.",
  "Argue that the humble mug deserves a design award. Or drink.",
  "Draw an imaginary pitcher with your finger in the air and narrate its shape. Or drink.",
  "If clouds had a cafe, what would their cups look like? Describe your design aloud. Or drink.",
  "Explain why a toast can mark a celebration without requiring a sip. Or drink.",
  "Describe a fictional tea ceremony whose central gesture is a welcoming bow. Or drink.",
  "Say cheers with a welcoming flourish of your voice, leaving everyone's hands free. Or drink.",
  "Give an imaginary cafe a closing ritual based on gratitude. Or drink.",
  "Adapt the idea of raising a glass into an equally festive empty-handed gesture. Or drink.",
  "Tell a tiny story about a town that celebrates milestones with a water fountain. Or drink.",
  "Create a make-believe tradition for welcoming spring with beverage-themed poetry. Or drink.",
  "Describe what makes sharing a tea break feel welcoming without requiring anyone to join. Or drink.",
  "Perform the opening words of a fictional harvest celebration focused on apple juice. Or drink.",
  "Imagine an annual celebration of the teapot and announce its harmless signature ritual. Or drink.",
  "Rehearse saying no thanks to an offered drink in a relaxed, confident voice. Or drink.",
  "Respond warmly to the fictional statement, 'I'm choosing an alcohol-free option tonight.' Or drink.",
  "Explain why a host should accept a declined drink without asking for a reason. Or drink.",
  "Invent a slogan that makes taking a break sound welcome. Or drink.",
  "State a considerate way to offer water without commenting on anyone's drink choice. Or drink.",
  "Act out a host remembering that guests can change their minds about refreshments. Or drink.",
  "Turn 'You have to try it' into an invitation that leaves the choice open. Or drink.",
  "Model a cheerful response when an imaginary guest says they want nothing to drink. Or drink.",
  "Make a case for clearly labeling alcohol-free options on a fictional menu. Or drink.",
  "Give an imaginary designated driver a welcome that includes appealing alcohol-free choices. Or drink.",
  "Personify water as a quietly confident guest introducing itself. Or drink.",
  "Describe a hydration reminder that sounds friendly rather than bossy. Or drink.",
  "Compose a catchy refrain celebrating access to drinking water. Or drink.",
  "Pitch a water station as the hero of an imaginary outdoor gathering. Or drink.",
  "Choose a calming name for a fictional water lounge. Or drink.",
  "In a dramatic movie-trailer voice, introduce plain water as the star attraction. Or drink.",
  "Imagine a reusable water bottle with a personality and perform its greeting. Or drink.",
  "Explain how a host could make water easy to find at an imaginary event. Or drink.",
  "Describe the sound of a fictional fountain using only your voice. Or drink.",
  "Celebrate the word refreshing with an original spoken line about water. Or drink.",
  "Name a citrus fruit that could inspire a fictional drink, then describe its color. Or drink.",
  "Discuss the role ginger might play in an imagined flavor description. Or drink.",
  "Give a cucumber the starring role in a beverage advertisement. Or drink.",
  "Explain why a menu might mention lemon peel as an aroma detail. Or drink.",
  "Choose a fruit for an imaginary ruby-colored refresher and justify the choice. Or drink.",
  "Describe mint as a character auditioning for a drinks menu. Or drink.",
  "Invent a debate between tea leaves and coffee beans about their aroma reputations. Or drink.",
  "Make a fictional pineapple drink sound inviting without using tropical. Or drink.",
  "Associate rosemary with a scene in nature, then turn that scene into menu wording. Or drink.",
  "Explain what fruit pulp adds to a beverage's imagined texture. Or drink.",
  "Recall a drink word from an earlier challenge, or invent a drink word if this is the opening card. Or drink.",
  "Observe a color visible in the room and use it to name an imaginary mocktail. Or drink.",
  "Play a teapot who has just been cast in a musical. Or drink.",
  "Trace a curling wisp of imaginary steam in the air. Or drink.",
  "Coin a pun involving a cup and a compliment. Or drink.",
  "Toast the pleasure of a good conversation without lifting anything. Or drink.",
  "Describe an imaginary drink's aroma as a landscape. Or drink.",
  "Give a fictional beverage label a name that reads like a comedy title. Or drink.",
  "Turn a nearby shape into the inspiration for an imaginary glass design. Or drink.",
  "Perform a delighted reaction to discovering that a fictional menu includes water. Or drink.",
  "Debate whether an imaginary cafe should name its drinks after weather or music. Or drink.",
  "Fill the blank in this imaginary menu entry: 'A ___ apple refresher.' Defend your wording. Or drink.",
  "Retell the familiar tea-or-coffee question as a scene from a fantasy adventure. Or drink.",
  "Sketch a fictional coaster in the air with a design inspired by bubbles. Or drink.",
  "Introduce yourself as the official spokesperson for the word zesty. Or drink.",
  "Decode 'on the rocks' as a beverage expression in the voice of a puzzle solver. Or drink.",
  "Praise an imaginary menu for describing flavors instead of judging customers' choices. Or drink.",
  "A water jug has won a design award. Accept the honor on its behalf. Or drink.",
  "Narrate the thoughts of a tea leaf admiring an imaginary ceramic cup. Or drink.",
  "Create an acrostic aloud using the letters in TEA and beverage-related words. Or drink.",
  "Describe bitterness in a fictional tasting note without treating it as a flaw. Or drink.",
  "Explain the difference between a drink being aromatic and being sweet. Or drink.",
  "Put velvety into a menu sentence about an imagined beverage's texture. Or drink.",
  "Give the word finish a tasting definition in the voice of a dictionary narrator. Or drink.",
  "Rewrite 'It tastes like fruit' aloud to make the imagined flavor more specific. Or drink.",
  "Herbal is the theme of an imaginary cafe. Describe the atmosphere that would suit the word. Or drink.",
  "Make a sound that suggests sparkling, then explain your vocal choice. Or drink.",
  "Describe a fictional tea as delicate without calling it weak. Or drink.",
  "Illustrate the idea of a rounded flavor through a hand gesture. Or drink.",
  "Turn an imagined citrus aroma into a line of poetry with no taste claims. Or drink.",
  "Ask a pretend server whether a menu's alcohol-free label describes the whole drink. Or drink.",
  "Demonstrate how to accept 'No, thank you' and smoothly return to the conversation. Or drink.",
  "Suggest menu wording that gives an alcohol-free drink its own identity. Or drink.",
  "Host an imaginary awards ceremony where water receives applause for being available. Or drink.",
  "Explain why choosing an alcohol-free beverage needs no personal explanation. Or drink.",
  "Practice a neutral question for clarifying an unfamiliar beverage description. Or drink.",
  "Welcome a fictional guest who brings a reusable cup without making a fuss. Or drink.",
  "Design a spoken invitation to a gathering where refreshments are optional. Or drink.",
  "Replace 'What's your excuse?' with a courteous response to a declined drink. Or drink.",
  "Propose an imaginary cafe layout where the water sign is easy to notice. Or drink.",
  "Mime a cup handle trying to win a handshake contest without touching anyone. Or drink.",
  "Act like a tea cozy presenting its credentials as a fashion accessory. Or drink.",
  "Perform a silent scene in which an imaginary menu unfolds into a map. Or drink.",
  "Let your voice become the gentle hiss of a fictional sparkling-water mascot. Or drink.",
  "An empty mug is sitting for a portrait. Become the mug and complain about the artist's choice of background. Or drink.",
  "Narrate a detective finding a mysterious teacup-shaped shadow. Or drink.",
  "Convey the personality of an elegant carafe through posture while staying comfortably seated. Or drink.",
  "Give an imaginary citrus peel the dramatic entrance of a stage performer. Or drink.",
  "Act out a fictional cafe sign proudly displaying the word welcome. Or drink.",
  "Improvise a conversation between a paper menu and a chalkboard menu. Or drink.",
  "Separate a beverage's brand name from its drink type using a made-up example. Or drink.",
  "Answer this word puzzle: what everyday drink is also the name of a social break? Or drink.",
  "Explain what the word still means when it appears on a water menu. Or drink.",
  "Distinguish a beverage's ingredient list from its tasting description. Or drink.",
  "Identify the familiar kitchen vessel whose name starts tea and ends pot. Or drink.",
  "Describe what a barista's job involves without performing any beverage preparation. Or drink.",
  "Clarify why alcohol-free and flavorless do not mean the same thing. Or drink.",
  "Offer a plain-language definition of an infusion. Or drink.",
  "Explain where an orange's zest comes from using an imaginary fruit as your example. Or drink.",
  "State what a drinks menu usually means by freshly squeezed. Or drink.",
  "Remember a beverage name from a fictional story, or create a story title that includes a beverage. Or drink.",
  "Recite the letters of CUP backward, then use cup in a cheerful sentence. Or drink.",
  "Notice a curved line in the room and describe how it could decorate a teacup. Or drink.",
  "Link the word amber to an imagined tea color and a scene that matches it. Or drink.",
  "Reconstruct the silhouette of a teapot from memory using a finger in the air. Or drink.",
  "Recall a familiar cafe sign style and imitate its wording with an invented cafe name. Or drink.",
  "Describe a drink container you can picture from a cartoon without naming its owner. Or drink.",
  "Look for a visible pattern and adapt it into a fictional coaster design aloud. Or drink.",
  "Repeat the mocktail name you invent now in the voice of a pleased menu editor. Or drink.",
  "Summon the imagined sound of a kettle through a spoken sound effect. Or drink.",
  "Compose a toast to curiosity that includes a beverage metaphor. Or drink.",
  "Honor ordinary kindness with a spoken toast that asks nothing of the group. Or drink.",
  "The ribbon is imaginary, but the cafe's opening speech is yours to perform. Welcome its future guests. Or drink.",
  "Toast a fictional teapot's retirement from a long career in hospitality. Or drink.",
  "Dedicate a spoken toast to the joy of being included. Or drink.",
  "Make a ceremonial announcement welcoming a new mocktail to an imaginary menu. Or drink.",
  "Salute the humble coaster with the dignity of a formal speech. Or drink.",
  "Celebrate an imaginary community fountain with a hopeful toast. Or drink.",
  "Invent a toast whose final word is sparkle. Or drink.",
  "Deliver a heartfelt tribute to the imaginary mug that stars in your kitchen daydream. Or drink.",
  "Describe the typography for a fictional tea menu as though the letters had personalities. Or drink.",
  "Choose a backdrop for an imaginary citrus drink's portrait and explain the visual effect. Or drink.",
  "Design a beverage label that communicates calm through color and shape alone. Or drink.",
  "Draw a pretend cafe logo in the air without using a cup shape. Or drink.",
  "Arrange imaginary glassware into a display inspired by a city skyline, describing it aloud. Or drink.",
  "Explain how a fictional menu could distinguish drink categories without relying only on color. Or drink.",
  "Pitch a reusable cup design inspired by a leaf. Or drink.",
  "Describe a watercolor portrait of sparkling water so vividly that no picture is needed. Or drink.",
  "A sunrise belongs on an imaginary drinks menu. Describe the cover illustration you would choose. Or drink.",
  "Outline an imaginary glass with an unusual silhouette and explain its artistic inspiration. Or drink.",
  "Find a rhyme for tea and weave it into a cafe slogan. Or drink.",
  "What would bubbles call their imaginary greeting? Coin the word and pronounce it aloud. Or drink.",
  "Turn mug into a verb and demonstrate its meaning in a fictional sentence. Or drink.",
  "Create a tongue twister about cheerful cups without asking anyone to repeat it. Or drink.",
  "Give sparkling water a superhero name and a harmless superpower. Or drink.",
  "Explain an original pun that pairs steep with a dramatic situation. Or drink.",
  "Rename a fictional cafe using a joke about grounds. Or drink.",
  "Compose a mock-serious dictionary entry for teapotitude. Or drink.",
  "Blend a weather word with a fruit word to name an imaginary refresher. Or drink.",
  "Write an imaginary newspaper headline about a mug winning a poetry prize, then say it aloud. Or drink.",
  "Consider a lemon aroma as a musical instrument and explain the association. Or drink.",
  "Describe an imagined coffee aroma without using strong or rich. Or drink.",
  "Give an apple scent a fictional address in a landscape instead of a real location. Or drink.",
  "Imagine mint's aroma entering a room as a character and narrate the scene. Or drink.",
  "Compare an imagined roasted aroma with an imagined fresh citrus aroma using mood words. Or drink.",
  "Tell a story in which a fragrant tea is recognized before its cup is seen. Or drink.",
  "At an imaginary aroma costume parade, peach needs an outfit. Describe its costume aloud. Or drink.",
  "Make up a perfume-style description for an imaginary rosemary refresher. Or drink.",
  "Describe the scent of an imagined garden as the inspiration for an alcohol-free menu. Or drink.",
  "Close an imaginary aroma exhibition with a speech about how words evoke scents. Or drink.",
  "Defend the imaginary menu name Cloud Orchard to a skeptical editor. Or drink.",
  "Translate 'a bright, citrus-led profile' into casual language for a fictional guest. Or drink.",
  "Narrate a nature documentary about the bubbles in an imaginary glass. Or drink.",
  "Map a pretend tea room in the air, showing where its welcoming water sign belongs. Or drink.",
  "Propose a name for a fictional beverage museum's glassware gallery. Or drink.",
  "Describe how an imaginary cup could look festive without any decorative extras. Or drink.",
  "Reassure a fictional guest that passing on refreshments will not interrupt the fun. Or drink.",
  "Play the role of a menu proofreader fixing the phrase 'alcohol-free options are boring.' Or drink.",
  "Summarize an imaginary film in which a teapot learns to appreciate quiet moments. Or drink.",
  "Grant water an honorary title and explain the honor in a formal voice. Or drink.",
  "Build suspense around the unveiling of a fictional pear refresher's name. Or drink.",
  "Convert the texture word silky into a visual image using only a hand movement. Or drink.",
  "Discuss whether a drink name should reveal its ingredients or create a mood. Or drink.",
  "Describe a make-believe beverage inspired by autumn leaves without using pumpkin. Or drink.",
  "Compose the first line of an imaginary novel set in an alcohol-free cafe. Or drink.",
  "Imitate the thoughtful nod of a fictional glassware curator evaluating an invisible mug. Or drink.",
  "Explain a fictional cafe's policy of never questioning a declined drink. Or drink.",
  "Invent a ceremonial title for the person who keeps an imaginary water station welcoming. Or drink.",
  "Stage a lighthearted debate about whether an imaginary teapot needs a hat. Or drink.",
  "Whisper an invented legend about a glass that reflects imaginary constellations. Or drink.",
  "Spot a light or shadow in the room and describe its effect on an imagined glass. Or drink.",
  "Use the nearest visible color as the opening word of a fictional beverage title. Or drink.",
  "Observe the room's overall mood and suggest a fitting imaginary tea-menu theme. Or drink.",
  "Describe a nearby straight edge as inspiration for a fictional drinks menu border. Or drink.",
  "Turn a visible texture into an imagined cup design without touching its source. Or drink.",
  "Notice an ordinary shape and explain why it would make a useful beverage-menu icon. Or drink.",
  "Find a visual detail in the room that could inspire an imaginary cafe's name. Or drink.",
  "Compare the room's lighting with the mood you would give a fictional evening mocktail. Or drink.",
  "Frame an imaginary cup portrait with your hands, keeping the pose comfortable. Or drink.",
  "Describe where a water sign could stand in an imagined version of this room. Or drink.",
  "Ask yourself an easy beverage trivia question, then answer in a quiz-show voice. Or drink.",
  "Resolve this menu mystery aloud: the label says herbal infusion, so must it contain tea leaves? Or drink.",
  "A fictional inventor pitches the reusable cup. Take that role and explain the problem it solves. Or drink.",
  "Identify the difference between a teapot's spout and its handle through gestures. Or drink.",
  "Tell the group why a beverage's color cannot confirm whether it contains alcohol. Or drink.",
  "Define garnish as a menu term without demonstrating any preparation. Or drink.",
  "Sort grape, teapot, zest, and carafe into ingredients and serving vessels aloud. Or drink.",
  "Clarify the distinction between fizzy water and a flavored soft drink in casual language. Or drink.",
  "Explain why an unfamiliar drink name alone cannot tell you its ingredients. Or drink.",
  "Describe the relationship between a coffee bean and a coffee grinder without using either. Or drink.",
  "Put on a fictional trial where a coaster argues that decoration is a worthwhile job. Or drink.",
  "Dramatize a tea menu deciding whether it wants to become a poetry collection. Or drink.",
  "Voice an imaginary water bottle's cheerful response to being mistaken for a vase. Or drink.",
  "Act as a tour guide leading an imaginary visit through a teapot-shaped building. Or drink.",
  "Perform a tiny scene in which the word refreshing auditions for a billboard. Or drink.",
  "Narrate an imaginary cup's daydream about becoming a flowerpot. Or drink.",
  "As an unusually enthusiastic cafe critic, review the clear lettering on an imaginary menu. Or drink.",
  "Play both sides of a conversation between an imaginary lemon and its portrait. Or drink.",
  "Convey a teapot's surprise at being named mayor of a fictional cupboard. Or drink.",
  "Adopt a storyteller's voice for a tale about a water jug that loves gatherings. Or drink.",
  "Name an imaginary drink after a made-up constellation and explain its flavor concept. Or drink.",
  "Design a fictional mocktail for a silent cinema, using its appearance as the main attraction. Or drink.",
  "Imagine a cafe menu organized by moods and introduce its comforting option. Or drink.",
  "Give an alcohol-free drink inspired by a forest a description without using green. Or drink.",
  "Compose a fictional menu entry where cucumber and citrus share the spotlight. Or drink.",
  "Pitch a pear-based refresher to an imaginary cafe that names everything after dances. Or drink.",
  "Invent a drink title that suits a rainy window, then describe its imagined aroma. Or drink.",
  "Develop a fictional tea special around the idea of a cozy reading nook. Or drink.",
  "For an imaginary ginger mocktail, devise a name that suggests warmth without implying alcohol. Or drink.",
  "Present an imaginary plum refresher as a character from a gentle fairy tale. Or drink.",
  "Draw the outline of an imaginary citrus slice in the air and explain its symmetry. Or drink.",
  "Illustrate a fictional tea leaf with a finger gesture that shows its central vein. Or drink.",
  "Sketch the spiral logo of an imaginary sparkling-water brand in the air. Or drink.",
  "Use your hands to suggest a saucer's shape, then give the imagined saucer a name. Or drink.",
  "Trace an invisible cafe awning decorated with beverage symbols. Or drink.",
  "Describe a comic panel in which an empty mug enjoys a sunny windowsill. Or drink.",
  "Design an imaginary menu icon that means alcohol-free, and explain it aloud. Or drink.",
  "Picture a teapot shadow puppet and show its outline using comfortable hand gestures. Or drink.",
  "Explain your idea for an abstract painting titled Still Water. Or drink.",
  "Invent a visual emblem for a fictional hydration corner without using a droplet. Or drink.",
  "Recall the shape of a cup from a familiar illustration, or describe an invented version. Or drink.",
  "Place tea-related words in alphabetical order aloud, choosing the words yourself. Or drink.",
  "Repeat a tasting adjective already heard during this game, or introduce a fresh adjective if none comes to mind. Or drink.",
  "Describe the imagined beverage that the word orchard brings to mind before naming its fruit. Or drink.",
  "Retrieve a familiar saying involving tea or coffee, or invent a saying about a mug. Or drink.",
  "Associate each letter of MUG with a word that fits a welcoming cafe. Or drink.",
  "Revisit a fictional drink idea from this game, or invent a drink idea now, and give it a new title. Or drink.",
  "Remember a beverage-related sound from a film, or create a sound for an imaginary scene. Or drink.",
  "Say a fruit name backward as best you can, then give that word to an imaginary mocktail. Or drink.",
  "Describe the color you imagine when hearing tea, then explain the association. Or drink.",
  "Make the phrase 'tea leaves' the punch line of an original harmless joke. Or drink.",
  "Coin a cheerful nickname for a fictional hydration station using alliteration. Or drink.",
  "Transform the word fizz into a cartoon character's catchphrase. Or drink.",
  "Compose a riddle whose answer is mug, then reveal the answer yourself. Or drink.",
  "A fictional citrus drink needs a rhyming title. Announce your choice as if unveiling a sculpture. Or drink.",
  "Invent an expression meaning 'welcome here' that includes the word cup. Or drink.",
  "Turn a coffee-related term into the title of an imaginary detective story. Or drink.",
  "Explain why Steep Dreams would suit an imaginary tea shop's sign. Or drink.",
  "Create a playful weather forecast for an imaginary cafe where the outlook is sparkling. Or drink.",
  "End a tiny fictional cafe anecdote with the words 'the mug understood.' Or drink.",
  "Propose a fictional tea-break ritual that begins with a kind word and requires no beverage. Or drink.",
  "Welcome a choice of plain water with the same warmth you would give a fancy menu selection. Or drink.",
  "Explain how optional refreshments help an imaginary celebration feel inclusive. Or drink.",
  "Give a spoken toast to hosts who listen when guests decline. Or drink.",
  "Describe a make-believe festival where glassware is admired as art rather than used. Or drink.",
  "Practice ending an imaginary drinks offer with 'Whatever you prefer is welcome.' Or drink.",
  "Invent a cheerful cafe motto about enjoying the company at the table. Or drink.",
  "Honor the imagined menu designer who made water and alcohol-free choices easy to find. Or drink.",
  "Deliver a closing toast to creativity with a metaphor drawn from tea. Or drink.",
  "Imagine the credits for a film starring a mug and thank its fictional supporting cast. Or drink.",
];
