export const DO_OR_DRINK_PARTY = [
  "Lead a ten-second dance break using moves everyone can copy. Or drink.",
  "Invent a dance move named after tonight's celebration and demonstrate it. Or drink.",
  "Dance as though the floor changes texture every five seconds. Or drink.",
  "Perform a silent disco routine while the group imagines your song. Or drink.",
  "Create a three-move party dance and teach it to one willing player. Or drink.",
  "Cross the room with your most theatrical dance-floor entrance. Or drink.",
  "Dance using only your shoulders until someone guesses your imaginary rhythm. Or drink.",
  "Turn a simple wave into an eight-count dance sequence. Or drink.",
  "Perform a dance inspired by a balloon floating around the room. Or drink.",
  "Show how you would dance at three different decades of parties. Or drink.",
  "Lead a seated dance routine that keeps everyone's feet on the floor. Or drink.",
  "Dance like the music keeps switching between fast and slow. Or drink.",
  "Create a victory dance for finding the last party snack. Or drink.",
  "Mime dancing through an unexpectedly crowded party. Or drink.",
  "Perform a graceful dance with an imaginary cape. Or drink.",
  "Let the group name an animal and make it the inspiration for a dance. Or drink.",
  "Dance in place while pretending you are on a gently rocking boat. Or drink.",
  "Demonstrate your best end-of-the-night dance move. Or drink.",
  "Make up a dance that can be performed while holding an imaginary plate. Or drink.",
  "Freeze in a new party pose whenever another player claps, for twenty seconds. Or drink.",
  "Hum a well-known party song and let the group guess it. Or drink.",
  "Sing one line of a celebration song in an operatic style. Or drink.",
  "Turn the name of this game into a short jingle. Or drink.",
  "Perform an imaginary drum solo using only the air in front of you. Or drink.",
  "Beatbox a simple rhythm for the group to echo. Or drink.",
  "Sing a chorus chosen by you as though it were a lullaby. Or drink.",
  "Make three party sounds and combine them into a tiny song. Or drink.",
  "Whistle or hum a tune that always improves your mood. Or drink.",
  "Give a dramatic spoken-word reading of a familiar song title. Or drink.",
  "Create a two-line anthem for the people in this room. Or drink.",
  "Conduct an imaginary orchestra through a grand finale. Or drink.",
  "Tap a rhythm on your knees and invite the group to repeat it. Or drink.",
  "Sing your next sentence to a melody you invent on the spot. Or drink.",
  "Imitate the opening sound of a song without using any lyrics. Or drink.",
  "Perform a one-person harmony by switching between two contrasting voices. Or drink.",
  "Narrate an imaginary DJ transition between two wildly different songs. Or drink.",
  "Make a sound effect for confetti falling in slow motion. Or drink.",
  "Sing a snack name as if it were the final note of a concert. Or drink.",
  "Create a hand-clap rhythm that includes one surprising pause. Or drink.",
  "Announce an imaginary band's encore and imitate its first note. Or drink.",
  "Give a five-second acceptance speech for Best Party Guest. Or drink.",
  "Deliver a grand toast to comfortable shoes without standing up. Or drink.",
  "Introduce the player on your left like a beloved talk-show guest. Or drink.",
  "Announce the arrival of an imaginary celebrity with extravagant excitement. Or drink.",
  "Give a weather report for the current party atmosphere. Or drink.",
  "Describe this gathering like the trailer for a feel-good movie. Or drink.",
  "Present an imaginary award for the room's coziest seat. Or drink.",
  "Make a campaign speech for extending snack time by five minutes. Or drink.",
  "Introduce yourself as the official expert on an absurd party topic. Or drink.",
  "Give a sports-style commentary on someone reaching for a snack. Or drink.",
  "Deliver a breaking-news report about an imaginary balloon escape. Or drink.",
  "Welcome everyone to a fictional festival devoted to friendship. Or drink.",
  "Make a royal proclamation declaring a harmless new party tradition. Or drink.",
  "Pitch this room as the world's most exclusive party venue. Or drink.",
  "Give a brief motivational speech to a bowl of snacks. Or drink.",
  "Announce the next round as though millions are watching live. Or drink.",
  "Describe your entrance tonight like a red-carpet commentator. Or drink.",
  "Offer a sincere toast to a small joy everyone can appreciate. Or drink.",
  "Close an imaginary awards ceremony with a memorable final sentence. Or drink.",
  "Act out arriving at a party and realizing you know everyone. Or drink.",
  "Mime carrying an enormous birthday cake through a crowded room. Or drink.",
  "Pretend to be a host welcoming guests from three different planets. Or drink.",
  "Act out discovering that the decorations have come alive. Or drink.",
  "Mime trying to choose between five equally tempting snacks. Or drink.",
  "Perform a scene where an invisible party hat keeps escaping your head. Or drink.",
  "Act out being surprised by a celebration you secretly expected. Or drink.",
  "Pretend the room is a museum of legendary party objects and lead a tour. Or drink.",
  "Mime opening an imaginary gift that becomes increasingly puzzling. Or drink.",
  "Act out a party guest attempting to sit in an invisible chair. Or drink.",
  "Pretend you are a detective investigating a missing cupcake. Or drink.",
  "Mime decorating a cake while riding an imaginary slow elevator. Or drink.",
  "Act out a host calmly solving three imaginary party mishaps. Or drink.",
  "Pretend to greet a guest whose handshake has seven steps. Or drink.",
  "Mime navigating a buffet while wearing an enormous imaginary hat. Or drink.",
  "Act out hearing your favorite song from across a crowded venue. Or drink.",
  "Pretend a tiny parade is crossing the table and describe what you see. Or drink.",
  "Mime taking the perfect group photo with an imaginary camera. Or drink.",
  "Act out trying to leave a party while saying five separate goodbyes. Or drink.",
  "Pretend you are the calm coordinator of a celebration in zero gravity. Or drink.",
  "Strike three different poses for an imaginary party photographer. Or drink.",
  "Model an imaginary outfit designed for a celebration on the moon. Or drink.",
  "Create a red-carpet pose inspired by your favorite snack. Or drink.",
  "Walk five steps as though your outfit has its own theme music. Or drink.",
  "Show the group your friendliest arrival pose and your sleepiest departure pose. Or drink.",
  "Invent a signature wave for entering a glamorous party. Or drink.",
  "Pose like the centerpiece in an elaborate party display. Or drink.",
  "Demonstrate how three fictional characters would enter this room. Or drink.",
  "Create a runway walk for an outfit made entirely of imaginary streamers. Or drink.",
  "Hold a dramatic album-cover pose while the group counts to five. Or drink.",
  "Show your best pose for a photo taken just as confetti falls. Or drink.",
  "Model an imaginary accessory and explain its most ridiculous feature. Or drink.",
  "Make a slow-motion entrance from your seat to the center of the room. Or drink.",
  "Pose as a statue titled The Last Guest Still Dancing. Or drink.",
  "Create a friendly secret-agent entrance for a surprise party. Or drink.",
  "Demonstrate a formal bow for thanking an imaginary party host. Or drink.",
  "Show four facial expressions for four very different party themes. Or drink.",
  "Walk an imaginary red carpet while answering one harmless pretend interview question. Or drink.",
  "Finish a pretend fashion show with a pose the group can copy. Or drink.",
  "Give the player across from you a genuine compliment about their party energy. Or drink.",
  "Invite a willing player to invent a two-person handshake with you. Or drink.",
  "Find one cheerful thing everyone in the group has in common. Or drink.",
  "Ask the group a lighthearted question nobody has answered tonight. Or drink.",
  "Offer a friendly welcome to anyone who joined the game most recently. Or drink.",
  "Name one quality that makes someone a considerate party guest. Or drink.",
  "Thank another player for something small they contributed to the gathering. Or drink.",
  "Start a round of applause for a harmless achievement chosen by the group. Or drink.",
  "Invite a willing player to mirror your hand movements for ten seconds. Or drink.",
  "Create a team name for everyone sitting on your side of the room. Or drink.",
  "Ask a willing player to join you in a synchronized bow. Or drink.",
  "Share a party icebreaker that can be answered in three words. Or drink.",
  "Choose two willing players and introduce them as an imaginary comedy duo. Or drink.",
  "Lead the group in a cheerful greeting using only gestures. Or drink.",
  "Say something kind about the way the group has played tonight. Or drink.",
  "Invite everyone to vote with a thumbs-up on a silly party theme. Or drink.",
  "Give a willing partner a made-up award based on something positive you noticed. Or drink.",
  "Start a chain where each willing player adds one friendly word to a party motto. Or drink.",
  "Teach the group a simple greeting you invent without touching anyone. Or drink.",
  "Ask another player to choose between two equally fun imaginary celebrations. Or drink.",
  "Describe the ideal snack table using exactly seven words. Or drink.",
  "Name five party supplies without using the letter A. Or drink.",
  "Invent a flavor for a celebration cake and give it a catchy name. Or drink.",
  "Pitch a harmless party theme based on the nearest color you can see. Or drink.",
  "Name three ways to make a shy guest feel welcome. Or drink.",
  "Describe a dream dance floor without mentioning music or lights. Or drink.",
  "Invent a festive mocktail name for the mood in the room. Or drink.",
  "List four things a thoughtful host might keep within easy reach. Or drink.",
  "Create a slogan for a party where everyone wears pajamas. Or drink.",
  "Name three songs you would choose for three different party moments. Or drink.",
  "Describe an imaginary centerpiece that would surprise everyone. Or drink.",
  "Plan a tiny celebration using only items already visible in the room. Or drink.",
  "Invent a new shape for confetti and explain why it is better. Or drink.",
  "Name four occasions that deserve more celebrations. Or drink.",
  "Describe a party invitation using only sound effects. Or drink.",
  "Create a menu for a fictional midnight picnic. Or drink.",
  "Name three clues that tell you a party is going well. Or drink.",
  "Invent a holiday centered on sharing good news. Or drink.",
  "Describe the perfect final song without naming an actual song. Or drink.",
  "Give a one-sentence review of this gathering as a friendly critic. Or drink.",
  "Balance a napkin or similarly light object on your head for ten seconds. Or drink.",
  "Stack three safe, unbreakable objects chosen by you. Or drink.",
  "Keep an imaginary balloon in the air for fifteen seconds. Or drink.",
  "Walk heel-to-toe along a short clear path at your comfortable pace. Or drink.",
  "Pass a small safe object around your back and return it to the front. Or drink.",
  "Make a paper or fabric item flutter without blowing directly on anyone. Or drink.",
  "Balance on either foot for five seconds with support nearby if wanted. Or drink.",
  "Move an imaginary tray across the room without spilling its imaginary contents. Or drink.",
  "Toss a soft object gently upward and catch it once. Or drink.",
  "Trace a star in the air with your elbow while seated or standing. Or drink.",
  "Keep both feet still while moving to an imaginary beat for ten seconds. Or drink.",
  "Carry a lightweight object from one safe surface to another like precious cargo. Or drink.",
  "Spin an unbreakable object once on a clear tabletop. Or drink.",
  "Walk around your chair once using your most careful parade step. Or drink.",
  "Balance two lightweight objects in separate hands for ten seconds. Or drink.",
  "Make a soft object land inside a nearby empty container from one step away. Or drink.",
  "Draw a circle in the air with one hand and a square with the other. Or drink.",
  "Move from sitting to standing in exaggerated slow motion if comfortable. Or drink.",
  "Hold a party pose while slowly turning your head from side to side. Or drink.",
  "Guide an imaginary hula hoop around your waist for ten seconds. Or drink.",
  "Draw a party hat with your eyes closed and show the result. Or drink.",
  "Fold a napkin or sheet of paper into a shape you name afterward. Or drink.",
  "Create a tiny table decoration from one safe item you choose. Or drink.",
  "Sketch the room as a treasure map in twenty seconds. Or drink.",
  "Build an imaginary balloon animal using only hand gestures. Or drink.",
  "Design a party logo in the air and explain each part. Or drink.",
  "Arrange three nearby unbreakable items into a temporary art display. Or drink.",
  "Draw a portrait of an imaginary DJ without lifting your pen. Or drink.",
  "Make a crown from a clean napkin or piece of paper. Or drink.",
  "Create a shadow puppet that resembles a party guest. Or drink.",
  "Sketch a new dance-floor pattern using five simple lines. Or drink.",
  "Fold a paper fan and give it a grand product name. Or drink.",
  "Use your hands to frame the best imaginary photo spot in the room. Or drink.",
  "Design a ticket for tonight's party in fifteen seconds. Or drink.",
  "Create a miniature sculpture using only two safe, movable objects. Or drink.",
  "Draw what celebration sounds would look like as shapes. Or drink.",
  "Make an imaginary party mask with your hands and hold the pose. Or drink.",
  "Sketch a cake that could never exist in real life. Or drink.",
  "Arrange a napkin into the fanciest shape you can manage. Or drink.",
  "Create a pretend party favor and demonstrate how it works. Or drink.",
  "Speak like an enthusiastic party planner until your next turn. Or drink.",
  "Use only questions during your next contribution to the game. Or drink.",
  "Replace the word yes with absolutely until your next turn. Or drink.",
  "Narrate your next action as if it is part of a nature documentary. Or drink.",
  "End your next two sentences with a tiny celebratory flourish. Or drink.",
  "Speak as though every sentence is an exciting party announcement until your next turn. Or drink.",
  "Use a different cheerful greeting each time someone addresses you until your next turn. Or drink.",
  "Describe your next choice as though selecting the winner of a contest. Or drink.",
  "Refer to the room as the grand ballroom until your next turn. Or drink.",
  "Add a harmless sound effect to your next three gestures. Or drink.",
  "Speak in rhymes for your next two sentences. Or drink.",
  "Pretend an imaginary microphone is required whenever you speak until your next turn. Or drink.",
  "Begin your next turn by saying, 'Previously at this party...' Or drink.",
  "Use the voice of a friendly game-show host for one round. Or drink.",
  "Celebrate your next correct guess with a silent victory pose. Or drink.",
  "Call every snack a delicacy until your next turn. Or drink.",
  "Deliver your next answer as a three-part list. Or drink.",
  "Treat your next turn like the final scene of a cheerful play. Or drink.",
  "Use your hands like subtitles while speaking for twenty seconds. Or drink.",
  "Introduce your next sentence with an imaginary drumroll. Or drink.",
  "Tell a ten-second story about a party hat with a secret mission. Or drink.",
  "Invent a legend explaining why people hang streamers at celebrations. Or drink.",
  "Describe the heroic journey of the last slice of cake. Or drink.",
  "Tell a tiny mystery set beside a completely ordinary snack bowl. Or drink.",
  "Create a happy ending for a balloon that drifted away. Or drink.",
  "Tell a story in which a playlist saves a celebration. Or drink.",
  "Describe the day an invitation arrived for an impossible venue. Or drink.",
  "Make up a tale about two decorations that become best friends. Or drink.",
  "Tell a six-sentence story with a party, a penguin, and a surprise. Or drink.",
  "Invent the origin story of an imaginary dance craze. Or drink.",
  "Describe a celebration planned by friendly robots. Or drink.",
  "Tell a story where the quietest guest solves the biggest problem. Or drink.",
  "Create a fairy tale about a crown made from a napkin. Or drink.",
  "Narrate a quest to find the perfect final song. Or drink.",
  "Tell a brief story that begins with one unopened invitation. Or drink.",
  "Invent a sequel to the best imaginary party ever held. Or drink.",
  "Describe a surprise party from the cake's point of view. Or drink.",
  "Tell a story where every guest brings the same harmless item. Or drink.",
  "Create a bedtime story about a disco ball that needed a day off. Or drink.",
  "Tell a one-minute adventure starring the nearest party decoration. Or drink.",
  "Mime a party-related word of your choice for the group to guess. Or drink.",
  "Describe a celebration using three clues while avoiding its name. Or drink.",
  "Draw a common party object in the air for everyone to identify. Or drink.",
  "Act out a familiar party role without speaking. Or drink.",
  "Hum a dance tune while the group guesses its mood rather than its title. Or drink.",
  "Give clues for a famous fictional party without naming its characters. Or drink.",
  "Make the sound of a party item and let everyone identify it. Or drink.",
  "Describe a party food without mentioning taste, color, or shape. Or drink.",
  "Use gestures to show a celebration tradition for the group to guess. Or drink.",
  "Give a one-word clue for each of three different party activities. Or drink.",
  "Mime preparing for guests in fast-forward. Or drink.",
  "Describe a dance style as though it were a mystery object. Or drink.",
  "Act out a party scene using only facial expressions. Or drink.",
  "Give three clues for an imaginary themed party and let the group name it. Or drink.",
  "Represent a party song using only hand movements. Or drink.",
  "Describe a festive outfit without naming any clothing item. Or drink.",
  "Mime the moment a surprise is revealed and let the group name the occasion. Or drink.",
  "Explain a party game badly enough to be funny but well enough to identify. Or drink.",
  "Make a frozen pose that represents a dance style for the group to guess. Or drink.",
  "Use three safe objects as clues for an imaginary celebration. Or drink.",
  "Lead a group countdown from five to a completely ordinary moment. Or drink.",
  "Start a wave around the room and cheer when it returns. Or drink.",
  "Invite the group to copy your sequence of three simple hand gestures. Or drink.",
  "Choose a cheerful word for everyone to say in three different emotions. Or drink.",
  "Conduct a ten-second group orchestra made entirely of soft sound effects. Or drink.",
  "Lead a synchronized stretch that each player may adapt or skip. Or drink.",
  "Create a call-and-response chant about snacks with no more than six words. Or drink.",
  "Invite everyone to freeze, then unfreeze in slow motion. Or drink.",
  "Lead a seated parade lasting one trip around an imaginary block. Or drink.",
  "Ask the group to build a ten-word celebration story one word at a time. Or drink.",
  "Coordinate a group pose where every willing player chooses their own gesture. Or drink.",
  "Lead a round of finger snaps, claps, or gentle taps in any accessible combination. Or drink.",
  "Invite everyone to imitate one harmless party sound you create. Or drink.",
  "Start a group pantomime of inflating and releasing an imaginary balloon. Or drink.",
  "Direct the group through a five-second silent cheer. Or drink.",
  "Lead a chorus of one invented celebratory word. Or drink.",
  "Ask everyone to point toward the imaginary dance floor at the same time. Or drink.",
  "Create a group rhythm where each willing person contributes one beat. Or drink.",
  "Lead a toast made only of gestures and smiles. Or drink.",
  "Invite the group to recreate the sound of a party starting and ending. Or drink.",
  "Pretend to adjust invisible party lights to match three different moods. Or drink.",
  "Demonstrate how an imaginary confetti machine with too many settings works. Or drink.",
  "Give a guided tour of the tiniest fictional party venue in the world. Or drink.",
  "Use an imaginary remote control to pause, rewind, and replay your entrance. Or drink.",
  "Pretend to wrap an oddly shaped gift without using real materials. Or drink.",
  "Show how you would test an invisible dance floor before guests arrive. Or drink.",
  "Operate an imaginary photo booth and demonstrate three pose buttons. Or drink.",
  "Pretend to inflate a balloon that keeps changing into other shapes. Or drink.",
  "Demonstrate a fictional machine that turns small talk into party games. Or drink.",
  "Pretend to arrange invisible flowers that have strong personalities. Or drink.",
  "Show how you would carry a towering imaginary stack of party hats. Or drink.",
  "Operate an imaginary elevator reserved for celebration guests. Or drink.",
  "Pretend to untangle a string of lights that politely untangles itself. Or drink.",
  "Demonstrate an invisible vending machine that dispenses compliments. Or drink.",
  "Show how an imaginary chair transforms for three party themes. Or drink.",
  "Pretend to sweep up confetti that keeps forming pictures. Or drink.",
  "Demonstrate a remote that changes the room's party decade. Or drink.",
  "Pretend to open curtains on the world's smallest dance stage. Or drink.",
  "Show how you would pack an entire party into an imaginary suitcase. Or drink.",
  "Demonstrate a fictional doorway that gives every guest a grand entrance. Or drink.",
  "Share your favorite kind of low-pressure celebration and say why. Or drink.",
  "Describe a party tradition you would happily adopt. Or drink.",
  "Name a song that makes a gathering feel welcoming without singing it. Or drink.",
  "Share the best snack you have discovered at a celebration. Or drink.",
  "Describe a small hosting detail that makes guests comfortable. Or drink.",
  "Name a party theme you would genuinely enjoy dressing for. Or drink.",
  "Share a harmless celebration moment that still makes you smile. Or drink.",
  "Describe your ideal balance between lively and relaxed at a gathering. Or drink.",
  "Name one activity that helps strangers become teammates. Or drink.",
  "Share a simple way to include someone who prefers quieter fun. Or drink.",
  "Describe a decoration that instantly feels festive to you. Or drink.",
  "Name a party game you enjoy even when you lose. Or drink.",
  "Share the kindest thing a host has done to make you feel welcome. Or drink.",
  "Describe an occasion you would celebrate with an afternoon party. Or drink.",
  "Name a food that belongs at your perfect gathering. Or drink.",
  "Share one sign that tells you it is time for the final song. Or drink.",
  "Describe a memorable party favor that would not create clutter. Or drink.",
  "Name a celebration that is better outdoors when the weather cooperates. Or drink.",
  "Share a way to make a party enjoyable without spending much money. Or drink.",
  "Describe the mood you would choose for a gathering tomorrow. Or drink.",
  "Turn an ordinary sentence chosen by you into an enthusiastic party invitation. Or drink.",
  "Say the days of the week as though each one is a different party guest. Or drink.",
] as const satisfies readonly string[]
