export const EVERYDAY_PARTY_PROMPTS = [
  "Which song would make the best opening track for tonight?",
  "What kind of music makes a room feel instantly welcoming?",
  "Which artist would you trust to soundtrack a long road trip?",
  "What song deserves a dramatic group singalong?",
  "Which instrument would be funniest in a dance remix?",
  "What tune always puts a little spring in your step?",
  "Which decade would you borrow for a one-night dance floor?",
  "What song would you choose for a slow-motion entrance?",
  "Which unexpected musical collaboration would you love to hear?",
  "What everyday sound could become a surprisingly good beat?",
  "Which movie soundtrack can carry an entire gathering?",
  "What song would you play to welcome the sunrise?",
  "Which style of music should get its own themed evening?",
  "What lyric-free track could score your current mood?",
  "Which performer brings the most joyful energy to a stage?",
  "What song would work best as a victory anthem for this group?",
  "Which familiar tune would be funniest as an opera?",
  "What music belongs on a perfect picnic playlist?",
  "Which song do you enjoy more when other people join in?",
  "What would you name a band formed in this room?",
  "Which music video has a world you would happily visit?",
  "What genre swap could make a well-known song fascinating?",
  "How should tonight's playlist change as the room grows more energetic?",
  "What song feels like colorful lights in musical form?",
  "Which fictional character would make a brilliant DJ?",
  "What track would you use for a two-minute kitchen dance break?",
  "Which musician's wardrobe deserves its own exhibition?",
  "What song can improve an ordinary walk across town?",
  "Which concert setting sounds most fun: rooftop, beach, garden, or train station?",
  "What new title would you give a song everyone here knows?",

  "Which snack deserves a place of honor at every gathering?",
  "What food is easiest to share without interrupting a conversation?",
  "Which two flavors make a surprisingly strong team?",
  "What would belong on a snack board designed for this group?",
  "Which dessert has the most celebratory personality?",
  "What ordinary meal could become festive with one clever change?",
  "Which food would make the best mascot for a party?",
  "What dip, sauce, or topping improves the widest range of snacks?",
  "Which dish smells like good news when it arrives?",
  "What food is more fun to assemble together than to receive finished?",
  "Which fruit would win a contest for best party guest?",
  "What would you serve at a celebration with a single-color menu?",
  "Which breakfast food deserves an evening event?",
  "What snack combination should sound strange but genuinely works?",
  "Which food has the best crunch in a quiet room?",
  "What would be the signature treat at an imaginary neighborhood café?",
  "Which meal becomes better when served family-style?",
  "What food could inspire the most playful costume?",
  "Which warm drink makes conversation feel cozier?",
  "What dish would you rename to make it sound more exciting?",
  "Which ingredient deserves more attention at the snack table?",
  "What portable food would you bring to a spontaneous park gathering?",
  "Which dessert would be the best centerpiece for a tiny celebration?",
  "What should a build-your-own food station include?",
  "Which food debate can stay friendly all evening?",
  "What meal would suit a party held entirely in pajamas?",
  "Which snack has the most satisfying shape?",
  "What edible creation would be fun for the group to decorate?",
  "Which fictional place probably serves the best food?",
  "What menu theme could turn leftovers into an occasion?",

  "What harmless mix-up still makes you smile when you remember it?",
  "Which everyday task has turned unexpectedly comedic for you?",
  "What is the funniest thing you have seen an animal do?",
  "When did a perfectly timed sound make a moment much funnier?",
  "What minor plan went wrong in a way that improved the story?",
  "Which autocorrect mistake created the best accidental sentence?",
  "What is a funny misunderstanding from a game or activity?",
  "When has the weather added an absurd twist to your plans?",
  "What is the most theatrical reaction you have seen to a tiny inconvenience?",
  "Which cooking attempt produced a better story than a meal?",
  "What unexpected object has made a surprisingly good prop?",
  "When did someone recover brilliantly from forgetting a word?",
  "What is the funniest explanation you have heard from a child?",
  "Which public sign or label made you do a double take?",
  "What innocent coincidence felt scripted for a comedy?",
  "When did a group decision become delightfully overcomplicated?",
  "What is a funny moment that required no words at all?",
  "Which everyday object seems to have a comic personality?",
  "What small victory have you celebrated far more dramatically than necessary?",
  "When has a pet or animal appeared at exactly the right moment?",
  "What failed shortcut became an entertaining detour?",
  "Which costume or decoration had an amusing life of its own?",
  "What is the funniest polite disagreement you have witnessed?",
  "When did background music accidentally match a real-life moment?",
  "What ordinary phrase became funny because of the timing?",
  "Which lost item turned up in the least logical place?",
  "What is a memorable example of everyone laughing at the same harmless surprise?",
  "When did technology behave as if it had its own agenda?",
  "What attempt to be efficient created extra steps and a good laugh?",
  "Which quiet moment was broken by an impossibly well-timed noise?",

  "If this room could travel anywhere for an hour, where should it land?",
  "What friendly creature would make the ideal party host?",
  "If clouds had flavors, which one would be most popular?",
  "What would a theme park designed by houseplants be like?",
  "If everyone received a harmless superpower until midnight, what should it be?",
  "What job would a dragon enjoy in a modern city?",
  "If tonight had a weather forecast based on mood, what would it predict?",
  "What would you put inside a vending machine for good ideas?",
  "If furniture could dance, which piece would have the best moves?",
  "What would a festival on the moon celebrate?",
  "If laughter came in colors, what shades would fill this room?",
  "What tiny world might exist inside a forgotten coat pocket?",
  "If a sandwich could tell a story, what genre would it choose?",
  "What friendly message should aliens receive as their first party invitation?",
  "If the floor became a map, where would the sofa be located?",
  "What sport could be invented using only balloons and spoons?",
  "If your favorite season hosted a parade, what would lead it?",
  "What would make an excellent name for a cheerful spaceship?",
  "If shadows could choose outfits, what would they wear tonight?",
  "What would happen at a convention for imaginary friends?",
  "If one household object became enormous, which would create the most fun?",
  "What new constellation should be added to the night sky?",
  "If snacks could vote, which one would become class president?",
  "What would a hotel for time travelers offer at reception?",
  "If every door played a sound effect, what should this one play?",
  "What would be sold at a market run entirely by birds?",
  "If the group shared a friendly robot, what should it be excellent at?",
  "What would a holiday for unfinished projects look like?",
  "If a rainbow had an extra color, what would you call it?",
  "What attraction belongs in the world's smallest amusement park?",

  "Which is the better party shape: circle, triangle, or star?",
  "Should crispy snacks be louder or quieter?",
  "Is a surprise better when hinted at or completely unexpected?",
  "Which makes a stronger entrance: a cape or a great hat?",
  "Should cake have more frosting, less frosting, or frosting on the side?",
  "Is it more fun to know a dance or invent one in the moment?",
  "Which is the superior seat at a gathering: corner, center, or near the snacks?",
  "Should a playlist begin gently or announce itself immediately?",
  "Is confetti worth the cleanup when it is biodegradable?",
  "Which is more festive: string lights or paper lanterns?",
  "Should group photos be carefully arranged or happily chaotic?",
  "Is a themed invitation more exciting than a mysterious one?",
  "Which is the better celebration sound: bells, drums, or applause?",
  "Should the best snack be served first or saved for later?",
  "Is a dance floor improved by a mirror ball?",
  "Which is more useful at a picnic: extra cushions or extra napkins?",
  "Should party decorations match or joyfully clash?",
  "Is it better to revisit a favorite game or try an unfamiliar one?",
  "Which wins: tiny desserts with variety or one spectacular dessert?",
  "Should an event have a schedule or follow the room's energy?",
  "Is a costume more fun when it is clever or comfortable?",
  "Which creates more suspense: a countdown or a drumroll?",
  "Should celebratory food be easy to eat or impressive to display?",
  "Is a funny prize better than a useful prize?",
  "Which is more inviting: an open doorway or a handmade sign?",
  "Should every gathering have a signature color?",
  "Is background music better familiar or full of discoveries?",
  "Which deserves the final slice: the host, the guest, or whoever notices it?",
  "Should a party game reward strategy or surprising creativity?",
  "Is anticipation part of the celebration or merely the waiting room?",

  "Which fictional duo would bring the best energy to a gathering?",
  "What movie scene would become better with a surprise dance number?",
  "Which television setting would be fun to rent for an evening?",
  "What book character would choose the most interesting snacks?",
  "Which animated vehicle would be the most memorable ride home?",
  "What fictional competition would be enjoyable without any real stakes?",
  "Which famous story deserves a cheerful alternate ending?",
  "What screen character would excel at welcoming new arrivals?",
  "Which fictional wardrobe would be most useful for a theme party?",
  "What game-show format should exist for groups of friends?",
  "Which movie object would make the best conversation piece?",
  "What familiar tale would work well in a futuristic setting?",
  "Which fictional restaurant would you book for a group dinner?",
  "What character would give the most entertaining museum tour?",
  "Which remake should swap its entire cast for puppets?",
  "What fictional town seems to hold the best local festivals?",
  "Which hero would be surprisingly good at planning a relaxed evening?",
  "What story would benefit from a narrator with a sense of humor?",
  "Which imaginary gadget would make hosting easier?",
  "What film title could double as a name for tonight?",
  "Which character would dominate a friendly trivia night?",
  "What fictional pet would be welcome at a garden party?",
  "Which on-screen outfit deserves a modern comeback?",
  "What book would inspire the most creative table decorations?",
  "Which celebrity chef should design a snack based on a movie?",
  "What fictional celebration would you like to observe from a safe balcony?",
  "Which character's catchphrase would make a good toast to the group?",
  "What series would be transformed by setting one episode at a block party?",
  "Which imaginary newspaper would have the funniest society page?",
  "What pop-culture mystery could this group solve over snacks?",

  "What small occasion deserves a cheerful celebration this week?",
  "How could we make an ordinary Tuesday feel like an event?",
  "What detail makes a welcome feel especially warm?",
  "Which achievement is best celebrated with noise, and which with quiet?",
  "What could become a new annual tradition among friends?",
  "How would you celebrate the first perfect-weather day of the year?",
  "What should be included in a care package for someone having a good week?",
  "Which decoration can transform a space with the least effort?",
  "What kind of compliment adds joy without putting anyone on the spot?",
  "How could a group celebrate finishing a difficult puzzle?",
  "What everyday milestone deserves its own card or banner?",
  "Which scent makes a place feel ready for company?",
  "What makes a group cheer feel genuine rather than rehearsed?",
  "How would you mark the arrival of a long-awaited weekend?",
  "What simple ritual could open a joyful gathering?",
  "Which shared activity makes a birthday feel personal without centering attention too strongly?",
  "What should people celebrate more often in their communities?",
  "How could a rainy day become a reason to gather?",
  "What low-key way of celebrating feels especially meaningful?",
  "Which seasonal change deserves a welcoming ceremony?",
  "What is a creative way to recognize everyone's contribution to a group effort?",
  "How would you decorate for a celebration inspired by gratitude?",
  "What sound signals that something good is about to begin?",
  "Which shared tradition can include someone joining for the first time?",
  "What makes a farewell gathering feel hopeful?",
  "How could you celebrate learning something new without needing to master it?",
  "What tiny award category would brighten an ordinary day?",
  "Which moment during a gathering deserves a pause to appreciate it?",
  "What would a celebration of fresh starts include?",
  "How can a group make room for both lively and quiet ways of joining in?",

  "If we had two free hours nearby, what spontaneous plan sounds appealing?",
  "What destination is perfect for an unplanned afternoon wander?",
  "Which group outing works well in almost any weather?",
  "What would you pack for a last-minute sunset picnic?",
  "Which local place would make a fun starting point for an adventure?",
  "What plan needs only comfortable shoes and curiosity?",
  "Where could a group go to find the best people-watching?",
  "What simple outing feels like a miniature holiday?",
  "Which errand could become enjoyable with the right company?",
  "What spontaneous plan would suit a group with mixed energy levels?",
  "Where would you go to collect three interesting photographs?",
  "What is a good adventure for a budget of almost nothing?",
  "Which nearby place might feel completely different after dark?",
  "What plan could begin with everyone choosing one stop?",
  "Where should a mystery bus ride end for maximum delight?",
  "What indoor adventure could rescue a stormy evening?",
  "Which route would you take for a walk with no destination?",
  "What would make a casual café visit feel like a special mission?",
  "Which spontaneous activity is better with a small group?",
  "What plan could turn a free morning into a story worth retelling?",
  "Where would you hunt for the most unusual souvenir under a small budget?",
  "What outing allows people to participate at their own pace?",
  "Which public place would be fun to sketch or describe together?",
  "What could a group discover by following the next interesting sign?",
  "Which plan sounds best for a day when nobody wants to rush?",
  "What last-minute event would you happily make room for?",
  "Where could you go to sample one new thing and return before dinner?",
  "What neighborhood challenge could be completed without bothering anyone?",
  "Which outdoor spot would suit an impromptu storytelling circle?",
  "What plan could be decided entirely by drawing choices from a bowl?",

  "What group choice should be made by applause tonight?",
  "Which three snacks would earn a place on the group's shared menu?",
  "What theme could everyone interpret in their own comfortable way?",
  "Which room feature should become the unofficial gathering landmark?",
  "What should the group name a shared playlist?",
  "Which simple game could everyone learn in under two minutes?",
  "What color combination should represent this gathering?",
  "Which activity should have a quiet-participation option built in?",
  "What phrase could serve as the group's cheerful motto for the evening?",
  "Which imaginary team mascot fits the room's energy?",
  "What should everyone help choose for a future get-together?",
  "Which of three stations sounds best: music, snacks, or crafts?",
  "What group decision would benefit from a coin toss?",
  "Which shared challenge could be completed with cooperation instead of competition?",
  "What topic should appear in a custom trivia round for this group?",
  "Which seating arrangement makes conversation flow most easily?",
  "What could everyone add one small piece to before leaving?",
  "Which group photo concept would allow people to join or opt out comfortably?",
  "What background theme would suit a collaborative doodle?",
  "Which word should inspire the next five minutes of conversation?",
  "What can the group choose now to make cleanup easier later?",
  "Which shared goal could make a gathering feel pleasantly purposeful?",
  "What kind of voting method would make a small choice more entertaining?",
  "Which table item should receive a playful new name?",
  "What should the group invent a flag for?",
  "Which part of the evening should remain completely unplanned?",
  "What signal could invite a change of activity without interrupting anyone?",
  "Which collective sound effect should mark a good idea?",
  "What simple choice could help a newcomer feel included right away?",
  "Which group-created rule would make conversation more playful and kind?",

  "What low-pressure activity helps you settle into a lively room?",
  "How do you like to join in when a group starts dancing?",
  "What makes it easier for everyone to take part in a game?",
  "Which role suits you today: chooser, helper, observer, or wildcard?",
  "What conversation starter works well when people are still arriving?",
  "How can hosts signal that taking a break is completely welcome?",
  "What kind of group activity leaves room for side conversations?",
  "Which invitation sounds both exciting and easy to decline?",
  "What makes a lively gathering comfortable for different personalities?",
  "How can a game stay fun when someone prefers to pass?",
  "What is a friendly way to bring several conversations together?",
  "Which activity can be enjoyed equally by participating or watching?",
  "What helps a new person learn the rhythm of a group?",
  "How could music volume support both energy and conversation?",
  "What is a good role for someone who enjoys helping behind the scenes?",
  "Which shared activity creates connection without putting anyone on display?",
  "What makes instructions feel inviting instead of demanding?",
  "How can a group welcome different answers to the same playful question?",
  "What kind of pause can refresh the energy in a room?",
  "Which party tradition is easy to adapt for different access needs?",
  "What could make a crowded space feel calmer and easier to navigate?",
  "How might the group include someone joining remotely?",
  "What activity works when people want different levels of involvement?",
  "Which small hosting gesture communicates that everyone can be themselves?",
  "What is a graceful way to switch games when the energy changes?",
  "How could a host offer choices without creating decision overload?",
  "What makes a group introduction playful without becoming personal?",
  "Which kind of celebration leaves space for people who dislike attention?",
  "What helps conversation move naturally between familiar faces and new ones?",
  "How would you describe an ideal gathering where everyone can participate their own way?",
] as const
