export const EVERYDAY_TEAM_PROMPTS: readonly string[] = [
  "What helps you get oriented when you begin a new piece of work?",
  "How do you like a group to clarify who is doing what?",
  "What kind of advance notice helps you prepare for a change?",
  "When do you prefer a quick conversation over a written message?",
  "What makes written instructions easy for you to use?",
  "How do you prefer to signal that you need more context?",
  "What helps you decide which task deserves attention first?",
  "Which meeting habits make it easier for you to contribute?",
  "Which agenda details help you arrive ready to contribute?",
  "How much thinking time is helpful before a group discussion?",
  "What is one working preference you wish teams asked about sooner?",
  "How do you like to keep track of shared decisions?",
  "What helps you stay focused during collaborative work?",
  "Which kinds of updates are most useful to receive asynchronously?",
  "How do you prefer teammates to raise a time-sensitive question?",
  "What makes a handoff feel clear and complete?",
  "How do you like to confirm that everyone has the same understanding?",
  "What helps you switch between independent and group work?",
  "Which part of your workday is usually best for thoughtful discussion?",
  "What makes a deadline feel realistic and workable?",
  "How do you prefer to handle a task whose scope is still unclear?",
  "What helps you participate when a conversation moves quickly?",
  "Which tools or formats make shared planning easier for you?",
  "How do you like a teammate to check in on a shared task?",
  "What is your preferred way to close out a piece of work?",
  "How do you know when a plan is detailed enough to begin?",
  "What kind of reminder feels genuinely helpful?",
  "How do you prefer to revisit a decision when circumstances change?",
  "What helps you protect concentration time while staying reachable?",
  "Which small routine makes teamwork smoother for you?",
  "What kind of problem do you especially enjoy untangling?",
  "Which contribution of yours is easiest to overlook but useful to a team?",
  "What skill do you enjoy bringing into group work?",
  "When have you felt that your way of thinking added something valuable?",
  "What type of task tends to bring out your resourcefulness?",
  "Which strength in a teammate often improves your own work?",
  "What do people tend to rely on you for at work?",
  "Which part of turning an idea into reality suits you best?",
  "What kind of detail are you particularly good at noticing?",
  "How do you contribute when a team needs steadiness?",
  "What role do you naturally take when a group is getting organized?",
  "Which ability would you enjoy using more often with this team?",
  "What is a recent work moment that made you feel capable?",
  "How do you help a group see options it may have missed?",
  "What strength do you appreciate in someone who works differently from you?",
  "Which kind of challenge gives you useful energy?",
  "What do you bring to a project during its early, uncertain stage?",
  "How do you help when a project needs a strong finish?",
  "Which behind-the-scenes contribution deserves more recognition in teams?",
  "What have you learned to do well through practice rather than instinct?",
  "What personal standard helps you produce work you are proud of?",
  "How do you make complex information easier for others to use?",
  "What is one way your curiosity benefits a project?",
  "Which team role would you like a chance to explore?",
  "What kind of contribution feels most satisfying to you?",
  "How do you help create momentum when a group feels stuck?",
  "What strength have you noticed emerging in this team?",
  "Which skill from outside your current role has proved surprisingly useful?",
  "How do you recognize when someone is doing quiet but important work?",
  "What capability could our team make better use of?",
  "What makes a status update clear without being overwhelming?",
  "How can teammates make questions feel welcome?",
  "What helps you hear the main point in a complicated discussion?",
  "How do you prefer to receive context for an unexpected request?",
  "What is a respectful way to interrupt when something needs clarification?",
  "How can a group make room for people who communicate more reflectively?",
  "What helps you say that you see an issue differently?",
  "When does a visual explanation work better than a verbal one for you?",
  "What makes feedback about a shared process easier to act on?",
  "How should a team communicate when there is no new information yet?",
  "What helps prevent a message from sounding more urgent than it is?",
  "How can we make requests easier to understand the first time?",
  "What is a useful way to summarize a discussion before moving on?",
  "What makes a meeting invitation informative enough to respond to?",
  "How can teammates signal whether they want ideas, action, or simply awareness?",
  "What communication habit reduces avoidable back-and-forth?",
  "How do you like someone to tell you that a priority has shifted?",
  "What makes it easier to acknowledge a message without answering fully yet?",
  "How can a team distinguish a suggestion from a decision?",
  "What wording helps make ownership of a next step clear?",
  "How do you prefer to surface a possible misunderstanding?",
  "What can make remote or hybrid conversations feel more connected?",
  "How should we share information that may affect only part of the team?",
  "What helps you follow a discussion when several topics are in play?",
  "How can a group invite dissent without putting anyone on the spot?",
  "What is a gracious way to redirect a conversation that has drifted?",
  "How do you like to learn that someone has completed a handoff to you?",
  "What makes a question feel specific enough to answer well?",
  "Which communication practice would you like our team to try?",
  "What helps newcomers understand how a team really works?",
  "How can a group make sure access needs are considered in its routines?",
  "What makes it easier for everyone to enter an ongoing conversation?",
  "How might we notice whose perspective has not yet shaped a decision?",
  "What helps people contribute without needing to compete for airtime?",
  "How can a team welcome different levels of familiarity with a topic?",
  "What is one way to make shared documents easier for everyone to navigate?",
  "How can meeting leaders create more than one path for participation?",
  "What helps a new teammate ask basic questions comfortably?",
  "How might we explain unwritten norms without making assumptions?",
  "What makes a group celebration feel inclusive?",
  "How can we avoid treating the loudest view as the shared view?",
  "What does respectful curiosity look like between colleagues?",
  "How can a team respond when someone says a process is not working for them?",
  "What helps people request a pause or clarification without awkwardness?",
  "How might we make optional social activities feel genuinely optional?",
  "What is a welcoming way to bring someone into a project already underway?",
  "How can we keep insider language from becoming a barrier?",
  "What makes it clear that changing your mind is acceptable?",
  "How can a group share credit fairly across visible and less-visible work?",
  "What helps ensure remote participants are part of the room?",
  "How might we make brainstorming comfortable for people who prefer preparation?",
  "What is one sign that a team values different working styles?",
  "How can we check assumptions about availability before making plans?",
  "What helps a group separate familiarity with a process from actual expertise?",
  "How can a team make room for questions after a meeting ends?",
  "What would help everyone understand why a decision was made?",
  "How might we rotate opportunities that tend to go to the same people?",
  "What does an accessible team event look like in practice?",
  "How can we invite input without requiring anyone to speak for a whole group?",
  "What is a considerate way to learn how a colleague's name is pronounced?",
  "How can we create belonging through everyday work rather than special occasions?",
  "How can a group normalize saying, 'I need to find out'?",
  "How do you prefer to learn a new tool or process?",
  "What kind of example helps a new idea click for you?",
  "How can a team make experiments feel safe to try?",
  "What helps turn a mistake into useful shared learning?",
  "Which question often leads you to a better understanding?",
  "How do you like to practice a skill before using it in real work?",
  "What makes documentation worth returning to?",
  "How can colleagues share expertise without making others feel behind?",
  "What is something this team has learned recently?",
  "How do you decide when to ask for help while learning?",
  "What makes a demonstration memorable and useful?",
  "How can we capture lessons while they are still fresh?",
  "What helps you stay curious when the first attempt does not work?",
  "Which kind of question opens up learning for a whole group?",
  "How can a team test an assumption before building around it?",
  "What is a helpful way to share an early, imperfect draft?",
  "How do you prefer to learn from someone else's experience?",
  "What makes it worthwhile to revisit an old approach?",
  "How can we distinguish a useful failure from a preventable one?",
  "What small experiment could teach us something valuable?",
  "How do you know when you have learned enough to teach someone else?",
  "What helps a group remain patient with a learning curve?",
  "Which recent insight changed how you approach a task?",
  "How can we make space to learn before urgency takes over?",
  "What is one topic the team could explore together?",
  "How do you prefer to receive tips while trying something new?",
  "What helps knowledge travel beyond the person who discovered it?",
  "How can we make retrospectives more useful for learning?",
  "What makes it easier to ask for help at the right moment?",
  "How can we offer help without taking over someone else's work?",
  "What does a strong collaboration feel like while it is happening?",
  "How do you prefer to divide work that has many connected parts?",
  "What helps two people combine different approaches successfully?",
  "How can teammates keep each other informed without adding noise?",
  "What makes you confident that a shared task is on track?",
  "How should a group handle an important task with no obvious owner?",
  "What helps collaboration across teams start well?",
  "How can we make dependencies visible before they become obstacles?",
  "What is a good way to renegotiate a commitment when conditions change?",
  "How do you like to resolve two reasonable but competing ideas?",
  "What helps a group recover after a plan falls through?",
  "How can we make joint decisions without waiting for perfect certainty?",
  "What is a useful role for someone who is not leading a discussion?",
  "How can a teammate support you during a demanding stretch of work?",
  "What makes cross-functional collaboration feel balanced?",
  "How do you prefer to coordinate when several people are editing the same work?",
  "What helps a group notice that its plan needs adjustment?",
  "How can we make asking for a second set of eyes routine?",
  "How should a team respond when responsibilities overlap?",
  "What helps people challenge an idea while staying on the same side?",
  "How can we preserve useful context during a handover?",
  "What makes a working session feel productive to you?",
  "How do you like to acknowledge another person's contribution to your work?",
  "What can a project partner do to make coordination effortless?",
  "How can a team avoid solving the same problem in parallel unknowingly?",
  "What helps turn individual progress into shared momentum?",
  "How should we decide when a conversation needs a smaller group?",
  "What collaboration habit is worth protecting when work gets busy?",
  "How can we end a partnership or project phase on a clear note?",
  "What kind of appreciation feels meaningful in a work setting?",
  "How can we recognize effort without creating competition?",
  "What is a contribution from this team that deserves a quiet thank-you?",
  "How do you like to celebrate a milestone that took many people to reach?",
  "What makes praise feel specific and sincere?",
  "How can we show appreciation for someone who prefers little public attention?",
  "Which everyday act of teamwork are you grateful for?",
  "How can a team acknowledge progress before the final result arrives?",
  "What is a simple way colleagues can make each other's day easier?",
  "How do you prefer the group to mark the end of a demanding project?",
  "What recent team choice made work better?",
  "How can we appreciate the people who maintain reliable routines?",
  "What form of recognition supports a sense of shared success?",
  "How might we thank someone for raising a useful concern?",
  "What is worth celebrating about how this team works together?",
  "How can appreciation include the thinking behind an outcome?",
  "Which bit of forward movement deserves attention today?",
  "How do you like to pass along positive feedback you hear about a colleague?",
  "What makes a thank-you feel timely?",
  "How can we recognize helpful course corrections, not just flawless outcomes?",
  "Whose contribution becomes most visible when it is missing?",
  "How can a team celebrate without adding pressure or extra work?",
  "What kind of progress is easy to miss unless we pause to notice it?",
  "How might we acknowledge someone who improved a process for everyone?",
  "What does fair recognition look like on a shared project?",
  "How can gratitude strengthen collaboration beyond a single moment?",
  "What recent example of thoughtful teamwork stayed with you?",
  "How do you prefer to respond when someone appreciates your work?",
  "What team ritual could help good work feel seen?",
  "What is one thing we can appreciate about an unfinished effort?",
  "What helps you maintain a steady pace during a busy period?",
  "How can a team spot overload before it becomes a crisis?",
  "What makes it easier to communicate that your capacity has changed?",
  "How should we prioritize when everything initially appears important?",
  "What meeting could be shorter, less frequent, or handled another way?",
  "How can we protect recovery time after an intense deadline?",
  "What helps you leave enough margin for unexpected work?",
  "How can a team make workload conversations practical and blame-free?",
  "What is a reasonable signal that a plan needs more time or fewer tasks?",
  "How do you decide what is good enough for the purpose?",
  "What routine helps prevent small requests from crowding out focused work?",
  "How can we make boundaries around availability easier to respect?",
  "What helps you return to a task after an interruption?",
  "How might we reduce urgency that comes from unclear planning?",
  "What is one process we could simplify to save energy?",
  "How can teammates support a sustainable pace without monitoring one another?",
  "How should a team adjust when its capacity is lower than expected?",
  "What helps you avoid carrying unfinished work in your attention?",
  "How can we plan for busy seasons without treating exhaustion as normal?",
  "What is a healthy way to respond to a last-minute request?",
  "How might we create more uninterrupted time for complex work?",
  "What helps a group choose what not to do?",
  "How can we make estimates more honest and useful?",
  "What recurring task might no longer earn the time it takes?",
  "How do you prefer to flag that a timeline is becoming unrealistic?",
  "What would make our weekly rhythm more manageable?",
  "How can we account for coordination time when planning workload?",
  "What helps you finish the day with a clear stopping point?",
  "What is one way the team could create breathing room?",
  "What conditions help you come up with fresh ideas?",
  "How can a group invite bold suggestions without demanding instant polish?",
  "What ordinary frustration might contain an interesting design opportunity?",
  "How do you like to build on another person's idea?",
  "What helps brainstorming move beyond the first obvious answers?",
  "How can we explore an unusual idea without committing to it?",
  "What constraint has ever made your thinking more inventive?",
  "How might we make room for ideas that arrive after the meeting?",
  "What question could help us see a familiar process differently?",
  "How do you decide which creative possibility to test first?",
  "What is a low-cost way to make an idea tangible?",
  "How can we keep early feedback from narrowing an idea too quickly?",
  "What helps you connect ideas from unrelated areas?",
  "How might a beginner look at one of our familiar challenges?",
  "What would we try if the goal were to learn rather than impress?",
  "How can a team encourage playful thinking while respecting people's time?",
  "What part of our work could benefit from a new metaphor?",
  "How do you like to capture ideas that are not ready yet?",
  "What assumption could we temporarily set aside to uncover new options?",
  "How can we tell when an unconventional idea deserves a closer look?",
  "What is one familiar tool we could use in an unfamiliar way?",
  "How might we make a routine task more engaging?",
  "What helps a creative session end with useful next steps?",
  "How can we welcome half-formed thoughts into a discussion?",
  "What would a deliberately simple version of our solution look like?",
  "How might we borrow a useful practice from another kind of work?",
  "What idea became better after someone questioned it?",
  "How can we test imagination against real needs?",
  "What would make it easier to propose a small improvement?",
  "Which current challenge could benefit from a fresh pair of eyes?",
  "What went more smoothly for the team than it might have six months ago?",
  "Which recent decision would be useful to understand better?",
  "What did we handle well when plans last changed?",
  "Where did a small clarification save substantial effort?",
  "What team habit is producing better results than we expected?",
  "Which part of our current workflow deserves a closer look?",
  "What did a recent project teach us about planning?",
  "Where are we relying on individual memory instead of a shared system?",
  "What is one lesson we should carry into the next project?",
  "Which recent challenge revealed something useful about our teamwork?",
  "What has become easier since we changed how we work?",
  "Where could a clearer decision point prevent confusion?",
  "What is one practice we should keep even if the team grows?",
  "Which assumption about our work is worth checking again?",
  "What did we learn from a task that took longer than expected?",
  "Where has informal coordination worked especially well?",
  "What is a useful question we did not ask early enough?",
  "Which part of a recent success could we repeat intentionally?",
  "What friction have we started treating as normal?",
  "Where could we replace a workaround with a clearer process?",
  "What is one sign that our collaboration is improving?",
  "Which team agreement needs refreshing rather than replacing?",
  "What did we stop doing that made work better?",
  "Where would a shared definition help us move faster?",
  "What is one recent surprise worth learning from?",
  "Which part of our process works well only because someone quietly maintains it?",
  "What would help us reflect without turning reflection into extra bureaucracy?",
  "Where could we close the loop more consistently?",
  "What pattern should we watch as our work evolves?",
  "What is one thing our future team could thank us for improving now?",
]
