export const EVERYDAY_FIRST_DATE_PROMPTS: readonly string[] = [
  "What kind of snack can brighten an ordinary afternoon for you?",
  "When in the year do you feel most in step with the world?",
  "What sound makes a place feel welcoming to you?",
  "What is your favorite way to enjoy a slow morning?",
  "Which everyday smell do you find especially comforting?",
  "What kind of weather makes you want to head outside?",
  "What drink do you like to take your time with?",
  "What is a small treat you rarely turn down?",
  "What kind of view could hold your attention for a while?",
  "Which meal feels most like a celebration to you?",
  "What music suits a good start to your day?",
  "What is something simple that you find beautiful?",
  "What kind of shop do you enjoy wandering through?",
  "How would you spend a weekend morning with nowhere you need to be?",
  "What kind of place helps you feel at ease quickly?",
  "What is a tiny luxury that feels worthwhile to you?",
  "Which local spot would you be happy to revisit anytime?",
  "What do you like to have nearby while you work or focus?",
  "Which part of the day usually has the best energy for you?",
  "What is a pleasant detail you tend to notice in a room?",
  "Which type of outing feels refreshingly uncomplicated?",
  "What is your favorite reason to take a longer route somewhere?",
  "Which background sound helps you settle into a space?",
  "What do you enjoy ordering when you want something familiar?",
  "What kind of lighting makes an evening feel cozy?",
  "Which everyday object has a design you really appreciate?",
  "What do you like to do while waiting for something?",
  "What kind of breakfast fits your actual mornings?",
  "What is one thing that can make errands more enjoyable?",
  "Which household chore feels most satisfying once it is done?",
  "If a midday pause went exactly right, how would you spend it?",
  "Which part of your usual routine would you gladly linger over?",
  "What helps you shift out of work mode at the end of a day?",
  "Which day of the week tends to feel most like yours?",
  "What do you enjoy doing when you arrive somewhere early?",
  "What is your preferred way to keep track of things you want to remember?",
  "Which daily decision do you like to make spontaneously?",
  "When an evening feels uncomplicated, what usually made it that way?",
  "What is a routine you have shaped to suit yourself?",
  "Which part of getting ready do you enjoy the most?",
  "What helps an unfamiliar neighborhood feel inviting to you?",
  "What is something you have made more convenient in your daily life?",
  "Which ordinary moment tends to improve your mood?",
  "What do you like your Sundays to leave room for?",
  "Which everyday choice reflects your taste especially well?",
  "What kind of reminder actually works for you?",
  "What is a habit that gives your day a useful rhythm?",
  "Which part of your week benefits most from having a plan?",
  "What do you do when you want a brief change of scenery?",
  "What is one way you make your living space feel like your own?",
  "What topic can reliably pull you into a good conversation?",
  "Which hobby has surprised you with how much you enjoy it?",
  "What is something you would happily learn just for fun?",
  "Which kind of story keeps you turning pages or watching another episode?",
  "What creative activity feels most approachable to you?",
  "What is a subject you enjoy hearing an enthusiast explain?",
  "Which game brings out an interesting side of you?",
  "What is a skill you admire when you see someone practice it well?",
  "Which museum, market, or public place could you explore without a plan?",
  "What is an interest you have returned to after time away?",
  "Which kind of live performance would you choose for an evening out?",
  "What do you enjoy making with your hands, if anything?",
  "What is the last idea that sent you down an enjoyable rabbit hole?",
  "Which activity makes time pass quickly for you?",
  "Which form of art do you connect with most easily?",
  "What would you enjoy being a beginner at again?",
  "Which kind of puzzle or challenge holds your interest?",
  "What is an underrated way to spend an hour?",
  "What kind of book would you recommend based on mood rather than genre?",
  "Which pastime helps you notice the world differently?",
  "What is a niche subject you know a surprising amount about?",
  "Which event would tempt you to rearrange your week?",
  "What is something you enjoy improving little by little?",
  "Which enthusiasm becomes more fun when someone joins you in it?",
  "What is your favorite way to discover new music?",
  "Which activity feels both playful and absorbing to you?",
  "Which recent recommendation turned out to be genuinely good?",
  "What kind of project gives you satisfying momentum?",
  "What is something you enjoy even though you are not especially skilled at it?",
  "Which cultural tradition are you curious to learn more about?",
  "What is a question you love asking people who know their craft?",
  "Which outdoor activity feels accessible and enjoyable to you?",
  "Which curiosity deserves a larger place in your schedule?",
  "Which piece of media has stayed in your thoughts lately?",
  "What do you like most about sharing an interest with someone else?",
  "What is a recent moment that became a better story than you expected?",
  "Which harmless misunderstanding still makes you laugh?",
  "What is the nicest surprise you have had on an ordinary day?",
  "Which detour led you somewhere worth remembering?",
  "What is a time when trying something new paid off in a small way?",
  "Which compliment has stayed with you for a good reason?",
  "What is a moment when a stranger made your day easier?",
  "Which celebration had a detail you still remember fondly?",
  "What is a recent occasion when you impressed yourself?",
  "Which meal comes with a story you enjoy telling?",
  "What is a time when your curiosity led to an unexpected experience?",
  "What is a small adventure you would gladly repeat?",
  "Which day trip has given you a lasting memory?",
  "What is a moment when a plan changing worked in your favor?",
  "Which thoughtful gesture have you enjoyed receiving?",
  "What is something you have done that felt delightfully out of character?",
  "Which ordinary place is connected to a vivid memory for you?",
  "Which possession carries a memory you enjoy revisiting?",
  "Which unexpected invitation are you glad you accepted?",
  "What is a moment when you felt warmly included?",
  "Which personal milestone did you celebrate in your own way?",
  "Which childhood curiosity still makes sense to you now?",
  "What is a memory that always brings a particular place to life?",
  "Which minor victory deserved more celebration than it got?",
  "What is a time when someone remembered a detail that mattered to you?",
  "Which unplanned conversation taught you something interesting?",
  "What is a choice you made on instinct that turned out well?",
  "Which tradition has gathered good memories for you over time?",
  "What is a moment when you saw a familiar place differently?",
  "Which first attempt makes you smile when you remember it?",
  "What is an experience that became meaningful only later?",
  "Which kind of story from another person's life do you enjoy hearing?",
  "What is a memorable way someone has welcomed you?",
  "What is a moment when you felt completely absorbed in what was happening?",
  "Which everyday tradition would you enjoy starting with someone?",
  "What helps a conversation feel natural to you?",
  "How do you usually show that you are enjoying someone's company?",
  "Which questions invite you to say more than you expected?",
  "How do you prefer to handle a pause in conversation?",
  "What makes humor feel easy between two people?",
  "How can someone tell when you are excited about a topic?",
  "What helps you feel comfortable offering a different opinion?",
  "How do you like people to check what you meant?",
  "Which topics tend to leave you with fresh ideas afterward?",
  "What makes a compliment feel sincere to you?",
  "What helps you stay curious when someone sees things differently?",
  "How do you like to signal that you need a moment to think?",
  "What kind of listening makes you feel understood?",
  "What makes playful teasing feel friendly rather than uncomfortable to you?",
  "How do you prefer someone to raise a minor misunderstanding?",
  "What kind of response makes sharing good news especially satisfying?",
  "How do you show appreciation in everyday conversation?",
  "How do you like to end an enjoyable conversation?",
  "What conversational habit do you appreciate in others?",
  "How do you prefer to communicate when plans are still uncertain?",
  "What makes silence feel companionable to you?",
  "What helps you feel heard during a disagreement?",
  "How do you like someone to share a concern with you?",
  "What kind of honesty builds trust gradually for you?",
  "How do you prefer to receive an apology for a small misstep?",
  "What makes it easier for you to say you have changed your mind?",
  "How do you show someone that their perspective has landed with you?",
  "What is a respectful way to pause a difficult topic in your view?",
  "How do you prefer to resolve crossed wires about plans?",
  "What kind of reassurance feels grounded rather than excessive?",
  "How do you like to make room for both people's preferences?",
  "What helps a serious conversation still feel caring?",
  "How do you prefer someone to respond when they cannot meet a request?",
  "What does thoughtful communication look like when life gets busy?",
  "How do you know when a conversation has reached a good stopping point?",
  "What quality makes someone enjoyable to spend time with?",
  "Which value tends to guide your everyday choices?",
  "What does being considerate look like in small moments?",
  "Which personal principle has become more important to you over time?",
  "What kind of generosity means the most to you?",
  "What does reliability look like beyond arriving on time?",
  "Which qualities help you trust someone's intentions?",
  "What does curiosity add to a close connection?",
  "Which quiet behavior tells you that someone is considerate by nature?",
  "What does mutual respect feel like in practice?",
  "Which everyday action can reveal a lot about someone's character?",
  "Which kind of courage do you admire most?",
  "What role does humor play when life feels demanding?",
  "What does keeping your word mean to you when circumstances change?",
  "Which value do you hope people experience when they are around you?",
  "Which forms of care are easy for you to notice?",
  "What does accountability sound like in an everyday conversation?",
  "Which character trait do you appreciate more now than you once did?",
  "Which choices help a community feel welcoming?",
  "What does patience look like when it is active rather than passive?",
  "Which value helps you navigate uncertainty?",
  "What does genuine encouragement sound like to you?",
  "What does being present with someone involve for you?",
  "Which kind of growth do you find most meaningful?",
  "What does reciprocity mean in a healthy connection?",
  "What does making amends involve beyond saying sorry?",
  "Which signs tell you someone treats other people thoughtfully?",
  "What does independence contribute to a strong connection?",
  "Which belief helps you approach people with compassion?",
  "What does loyalty mean without losing room for honesty?",
  "Which kind of integrity matters when no one is watching?",
  "What does emotional steadiness look like in ordinary life?",
  "Which value would you want reflected in a shared decision?",
  "What does it mean to disagree with care?",
  "Which everyday behavior makes respect visible to you?",
  "What balance of plans and spontaneity suits your life these days?",
  "How much quiet time helps you feel restored?",
  "What role does movement or exercise play in your week, if any?",
  "How do you like to divide time between familiar places and new ones?",
  "What makes a social plan feel manageable rather than draining?",
  "How do you prefer to spend time when your energy is low?",
  "What kind of home atmosphere helps you relax?",
  "How important is being outdoors in the life you enjoy?",
  "What pace of travel feels most satisfying to you?",
  "What place does cooking have in your routine, if any?",
  "How do you prefer to share decisions about where to go?",
  "What makes a night out worth the effort for you?",
  "How much variety do you enjoy in a typical week?",
  "What kind of gathering feels easiest for you to settle into?",
  "What does taking good care of your energy look like?",
  "How do you decide when to keep a plan flexible?",
  "What sort of environment helps you be most playful?",
  "How do you like to spend time with someone when neither person wants a big plan?",
  "What makes trying a new restaurant enjoyable for you?",
  "What rhythm makes a vacation feel restorative?",
  "How do you prefer to mark special occasions?",
  "What role do personal projects have in the life you want?",
  "How do you make space for people you care about during a busy period?",
  "What kind of shared activity makes conversation flow more easily?",
  "What makes a neighborhood pleasant to live in for you?",
  "How do you decide which invitations to accept?",
  "What is your preferred balance between eating at home and going out?",
  "How do you like to use an unexpected free afternoon?",
  "What degree of routine helps you thrive without feeling boxed in?",
  "What role does learning have in your ideal lifestyle?",
  "How do you like to handle changes made at the last minute?",
  "Which details help everyone relax in a place they are sharing?",
  "How do you prefer to balance conversation and activity on an outing?",
  "What kind of weekend leaves you feeling ready for the next week?",
  "How do you make room for rest without feeling that the day was wasted?",
  "What helps you feel a genuine sense of connection with someone?",
  "How do you like affection to show up in nonphysical ways?",
  "What makes spending time together feel intentional to you?",
  "How can two people make curiosity about each other last?",
  "What helps a new connection develop at a comfortable pace?",
  "How do you recognize when effort feels mutual?",
  "What kind of consistency helps trust grow for you?",
  "How do you like to celebrate someone else's good news?",
  "How can someone support your interests without needing to share all of them?",
  "What does quality time mean when schedules are full?",
  "How do you like to express that you would enjoy seeing someone again?",
  "How can two people stay themselves while growing closer?",
  "What kind of check-in feels warm and welcome to you?",
  "How do you prefer to build shared traditions over time?",
  "What makes a thoughtful gesture feel personal?",
  "How do you like someone to respond when you are excited about an idea?",
  "What does giving each other room look like in a close connection?",
  "What helps you feel appreciated without being put on the spot?",
  "How do you like to navigate having different social batteries?",
  "What makes compromise feel collaborative to you?",
  "How can two people remain curious when their tastes do not match?",
  "What kind of shared memory would you enjoy creating with someone new?",
  "How do you like to be included in another person's plans?",
  "What makes it easier to ask for what you need in a connection?",
  "How can someone show care when they are short on time?",
  "What does a comfortable amount of contact look like while getting acquainted?",
  "How do you prefer to navigate moments when one person needs more quiet?",
  "How can people keep small misunderstandings from becoming bigger ones?",
  "What helps you enjoy closeness without feeling rushed?",
  "How do you like to reconnect after each person has had a busy stretch?",
  "What makes a shared plan feel equally chosen?",
  "How can someone invite honesty while respecting privacy?",
  "How do you like differences to be acknowledged in a connection?",
  "What helps two people feel like they are on the same team?",
  "How can a connection leave room for both ease and growth?",
  "What is a boundary that helps social time stay enjoyable for you?",
  "How do you prefer to say no to a plan while keeping the connection warm?",
  "What helps you feel comfortable changing your mind?",
  "How would you like someone to check before making an assumption about you?",
  "What kind of notice do you appreciate when plans need to change?",
  "How do you prefer to handle topics you are not ready to discuss?",
  "What makes a request feel respectful even when your answer may be no?",
  "How do you like someone to respond when you set a limit?",
  "What helps you voice a preference before it becomes a frustration?",
  "How do you prefer to navigate different comfort levels with public attention?",
  "What does respecting personal time look like to you?",
  "How can someone check in without making you responsible for their feelings?",
  "What is a considerate way to ask about availability?",
  "How do you like to discuss expectations while something is still new?",
  "What helps you feel free to decline an invitation?",
  "How should someone respond if a joke does not land well?",
  "What does privacy mean to you when getting to know someone?",
  "How do you prefer to handle photos or posts that include you?",
  "What makes a conversation about boundaries feel ordinary and caring?",
  "How can two people notice a mismatch without treating either preference as wrong?",
  "What upcoming experience feels worth making room for now?",
  "How would you like your free time to feel a year from now?",
  "As your life changes, what would you be glad to keep steady?",
  "Which new tradition might be fun to grow into slowly?",
  "What kind of place would you enjoy exploring in a future season?",
  "How do you hope your everyday routines evolve over the next few years?",
  "Which unfamiliar activity would you enjoy approaching with more confidence?",
  "Which interest would you be glad to deepen over time?",
  "What kind of community would you like to feel more connected to?",
  "How do you hope to protect space for rest in the future?",
  "What is a future milestone you would enjoy defining in your own way?",
  "Which part of life would you like to approach with more playfulness?",
  "What kind of memories would you like your next chapter to contain?",
  "How do you imagine balancing stability and novelty in the years ahead?",
  "What would make an upcoming year feel well spent to you?",
  "Which shared goal can be enjoyable even if it changes along the way?",
  "What kind of support helps people pursue separate ambitions while staying connected?",
  "How would you like meaningful relationships to fit into the life you are building?",
  "What is one possibility for the future that you enjoy leaving open?",
  "What would a hopeful next season of life make more room for?",
]
