export const EVERYDAY_NOSTALGIA_PROMPTS = [
  "What place from an earlier time in your life can you still picture clearly?",
  "Which doorway from your past do you remember walking through most often?",
  "What view you once saw regularly would feel meaningful to see again?",
  "Which corner of a former home, room, or neighborhood stands out in your memory?",
  "What outdoor place from years ago do you remember through its weather?",
  "Which route from an earlier chapter of your life could you still trace from memory?",
  "What building that has changed or disappeared do you remember well?",
  "Where did you once go when you wanted a little space to yourself?",
  "What waiting place from your past—such as a stop, lobby, or queue—do you recall?",
  "Which place once felt enormous but might seem smaller to you now?",
  "What local landmark helped you know you were nearly there?",
  "Which room from your past had the most memorable light?",
  "What place did you come to appreciate only after you stopped visiting it?",
  "Where do you remember watching the world go by?",
  "What place from long ago felt especially busy, and what was happening there?",
  "Which familiar place had a smell that announced where you were?",
  "What landscape from an earlier journey has stayed with you?",
  "Which past place would you most like to revisit for ten quiet minutes?",
  "What shortcut or hidden path did you once know well?",
  "Where did people gather in a community you once knew?",
  "What ceiling, floor, or wall pattern from the past can you still visualize?",
  "Which place used to mark the edge of your known world?",
  "What spot from an earlier era felt different at night than during the day?",
  "What everyday sound once shaped the rhythm of your surroundings?",
  "Which voice from an earlier time can you still hear in your mind?",
  "What old sound would instantly tell you what time of day it was?",
  "Which piece of music is tied to a particular room or journey for you?",
  "What sound from a former neighborhood or community do you remember?",
  "Which long-gone machine or device had a sound you could recognize anywhere?",
  "What announcement, call, or signal from years ago stays in your memory?",
  "Which song did you learn by hearing it repeatedly rather than choosing it?",
  "What quiet sound from the past do you notice is missing now?",
  "Which old ringtone, startup tone, or alert can you imitate?",
  "What kind of music once seemed to be playing everywhere around you?",
  "Which remembered laugh still has a distinctive sound to you?",
  "What sound meant that food or a drink was nearly ready?",
  "Which weather sound brings back a specific earlier moment?",
  "What song changed meaning for you as time passed?",
  "Which sound used to make you hurry?",
  "What background noise from an old routine do you remember fondly or simply vividly?",
  "Which spoken phrase from your past still arrives with its original tone of voice?",
  "What music did you first encounter through someone else's listening?",
  "Which crowd sound from a past event can you still imagine?",
  "What sound once made a place feel open for the day?",
  "Which old broadcast, jingle, or theme tune has stayed with you?",
  "What meal from an earlier period of your life tells a larger story?",
  "Which snack do you associate with a particular journey or outing?",
  "What food did you learn to enjoy later than the people around you?",
  "Which recipe have you watched change as it passed between people or places?",
  "What drink once felt like a special occasion?",
  "Which food smell could guide you to a particular street, room, or gathering?",
  "What simple meal from the past was memorable because of the setting?",
  "Which food used to come in packaging you can still picture?",
  "What dish connects you to a place you no longer visit often?",
  "Which taste did you expect to dislike but ended up remembering warmly?",
  "What food preparation sound belongs to an earlier routine in your life?",
  "Which treat once required patience, saving, or a special trip?",
  "What meal did you first learn to make in your own way?",
  "Which food tradition have you adapted rather than preserved exactly?",
  "What fruit, spice, or ingredient marks a season in your memory?",
  "Which shared meal do you remember more for the conversation than the menu?",
  "What food from another person's culture first became familiar to you?",
  "Which once-common snack or drink seems difficult to find now?",
  "What was your earliest memorable experience of choosing your own meal?",
  "Which kitchen tool or serving dish carries a story for you?",
  "What meal from a difficult time still offered a moment of steadiness?",
  "Which food did you know by a local or personal name?",
  "What aroma from a market, café, canteen, or street stall do you remember?",
  "What did a place of learning sound like just before the day began?",
  "Which lesson stayed with you because of how it was taught?",
  "What object from a classroom or learning space do you remember handling?",
  "Which subject surprised you by becoming interesting?",
  "What did you once learn informally from a neighbor, peer, colleague, or elder?",
  "Which question from a teacher or mentor continued to matter later?",
  "What was a memorable way people passed notes or messages while learning?",
  "Which school-day or training-day routine feels especially tied to its era?",
  "What did you first learn by watching rather than being instructed?",
  "Which book from an earlier learning experience left you with a vivid scene?",
  "What small classroom success do you still remember?",
  "Which rule in a learning environment made sense only years later—or never did?",
  "What did people carry to school, training, or lessons where you lived?",
  "Which learning mistake helped something finally click?",
  "What field trip, visit, or practical lesson broadened your world?",
  "Which person made learning feel more possible without demanding perfection?",
  "What skill did you pick up outside any formal classroom?",
  "Which old notebook, certificate, or piece of work would be interesting to find?",
  "What lunch-break or recess custom do you remember observing or joining?",
  "Which piece of advice about learning have you revised over time?",
  "What was the first topic you remember researching for yourself?",
  "Which learning space had an atmosphere unlike anywhere else?",
  "What phrase from a school report or piece of feedback stayed with you?",
  "What piece of technology once seemed astonishingly advanced to you?",
  "Which device required a ritual that newer technology has removed?",
  "What was your first memorable experience of waiting for something to load?",
  "Which obsolete button, dial, or switch do your hands still remember using?",
  "What did you once record, collect, or save on a physical format?",
  "Which technology did you resist at first and later adopt?",
  "What device did people have to share or take turns using?",
  "Which old screen or display had a look you can still picture?",
  "What was a memorable early experience of communicating across a distance?",
  "Which piece of technology felt fragile or temperamental?",
  "What digital habit from years ago now seems wonderfully slow?",
  "Which cable, adapter, cartridge, or battery was always in demand?",
  "What did you enjoy about discovering music before streaming became common?",
  "Which early online space felt like its own little world?",
  "What was the first digital creation you remember feeling proud of?",
  "Which piece of information did you once have to memorize because a device could not store it?",
  "What technology-related sound has nearly vanished from daily life?",
  "Which old device would you enjoy showing someone who has never used one?",
  "What did taking a photograph involve at an earlier point in your life?",
  "Which technology made your world feel noticeably larger?",
  "What old way of watching a film or program shaped the experience?",
  "Which repair or workaround kept an old device going?",
  "What technology do you remember learning through trial and error?",
  "What game could people start with almost no equipment?",
  "Which play space had rules that newcomers had to learn?",
  "What made-up game from your past had surprisingly detailed rules?",
  "Which pastime helped long stretches of waiting pass more quickly?",
  "What did you once build from whatever materials were available?",
  "Which game changed depending on who joined in?",
  "What playful competition do you remember for its unusual prize or stakes?",
  "Which activity made an ordinary object feel like something else entirely?",
  "What indoor pastime belonged to rainy, hot, or otherwise stay-inside days?",
  "Which outdoor activity depended on a particular season or kind of weather?",
  "What game did you learn from someone of a different generation?",
  "Which playtime disagreement taught you how to renegotiate the rules?",
  "What activity made you lose track of time in an earlier era?",
  "Which game had a chant, rhyme, gesture, or call attached to it?",
  "What did you enjoy collecting even if the collection had little practical value?",
  "Which hobby introduced you to people beyond your usual circle?",
  "What playful tradition made a certain day of the week feel different?",
  "Which game was more fun to watch than to play?",
  "What was a creative use you found for leftover or discarded materials?",
  "Which pastime did you return to after many years away?",
  "What rule from an old game varies depending on where people learned it?",
  "Which activity once made you feel daring in a manageable way?",
  "What kind of pretend world did you enjoy inventing or observing?",
  "What item of clothing marks a particular chapter of your life?",
  "Which hairstyle do you associate with a specific year or era?",
  "What color combination used to feel especially fashionable where you were?",
  "Which accessory once mattered more to you than it probably does now?",
  "What outfit did you choose when you wanted to feel confident?",
  "Which clothing rule or expectation have you gladly left behind?",
  "What borrowed, shared, or secondhand item became part of your style?",
  "Which fabric or texture brings back a strong memory?",
  "What trend did you admire without ever trying yourself?",
  "Which shoes do you remember for the places they carried you?",
  "What item did you repair, alter, or decorate to make it your own?",
  "Which past style choice still feels true to you?",
  "What clothing did the weather or local environment make essential?",
  "Which uniform or dress code shaped how a place felt?",
  "What garment was saved for rare occasions?",
  "Which style from before your time did you discover and enjoy?",
  "What old photograph captures an outfit with a story behind it?",
  "Which fashion detail helps you date a memory without checking the year?",
  "What did getting ready for an event involve in an earlier era?",
  "Which item looked better with age and use?",
  "What personal style experiment taught you something about your taste?",
  "Which scent or grooming product belongs to a past period for you?",
  "What clothing shop, tailor, market, or swap do you remember visiting?",
  "What morning routine from another time feels vivid now?",
  "Which weekly errand used to have its own rhythm?",
  "What task once took much longer than it does today?",
  "Which evening ritual helped signal that the day was winding down?",
  "What did people do while waiting before phones filled the gaps?",
  "Which household chore had a method specific to where you lived?",
  "What regular journey became familiar enough to do almost automatically?",
  "Which calendar tradition helped you notice the changing seasons?",
  "What part of an old routine would you happily restore?",
  "Which routine are you relieved no longer belongs to your days?",
  "What small purchase used to be part of a regular outing?",
  "Which day of the week had the strongest personality in your past?",
  "What did preparing for bad weather involve where you were?",
  "Which recurring visitor, vendor, or service marked time in your community?",
  "What bedtime routine do you remember from any stage of life?",
  "Which ordinary responsibility first made you feel more capable?",
  "What routine changed when you moved, traveled, or entered a new setting?",
  "Which old habit disappeared so gradually you barely noticed?",
  "What seasonal preparation brought people together?",
  "Which everyday queue or commute had its own unwritten etiquette?",
  "What did a day off look like during a former chapter?",
  "Which regular radio or television schedule shaped your plans?",
  "What simple routine helped an unfamiliar place begin to feel known?",
  "What first attempt do you remember more clearly than the eventual success?",
  "Which first day in a new place taught you how things worked there?",
  "What was your earliest experience of earning or managing money?",
  "Which first journey on your own changed how you saw your surroundings?",
  "What was the first event you chose to attend for yourself?",
  "Which first responsibility felt larger than it looks in hindsight?",
  "What was your first memorable encounter with a language unfamiliar to you?",
  "Which first purchase made with your own savings felt significant?",
  "What was the first skill you taught to someone else?",
  "Which first performance, presentation, or public contribution do you recall?",
  "What was your first experience of being the newcomer?",
  "Which first taste opened the door to a kind of food you now enjoy?",
  "What was the first news event you remember people around you discussing?",
  "Which first letter, message, or call from far away felt important?",
  "What was your first experience of seeing a familiar place from a new angle?",
  "Which first job, role, or informal task taught you an unexpected lesson?",
  "What was the first object you remember fixing instead of replacing?",
  "Which first creative project felt recognizably yours?",
  "What was your earliest memorable experience of staying up unusually late?",
  "Which first goodbye made distance feel real to you?",
  "What was the first tradition you consciously chose to continue or change?",
  "Which first mistake became easier to laugh about with time?",
  "What was your first glimpse of a place that had existed only in stories to you?",
  "What community gathering do you remember through its smallest details?",
  "Which local custom took time for you to understand?",
  "What did neighbors or nearby people once share with one another?",
  "Which public space encouraged conversation among people who might not otherwise meet?",
  "What community celebration changed from year to year?",
  "Which local character, worker, or familiar face helped define a place?",
  "What form of welcome did you encounter in a community new to you?",
  "Which community rule was rarely written down but widely understood?",
  "What did people do together when local plans were disrupted?",
  "Which tradition brought several generations into the same space?",
  "What local phrase or expression immediately locates a memory for you?",
  "Which community resource mattered more than outsiders might realize?",
  "What public event offered your first look at a talent or tradition?",
  "Which gathering place changed purpose over the years?",
  "What small act of cooperation do you remember seeing often?",
  "Which local craft, trade, or service fascinated you?",
  "What community memory has been kept alive through storytelling?",
  "Which annual event helped you measure the passage of time?",
  "What did hospitality look like in a place you once spent time?",
  "Which neighborhood change made daily life feel noticeably different?",
  "What shared challenge revealed something memorable about a community?",
  "Which public noticeboard, announcement point, or message chain kept people informed?",
  "What local tradition would need explanation for someone arriving today?",
  "What journey do you remember through one unexpected stop?",
  "Which mode of transport belongs strongly to an earlier chapter of your life?",
  "What did packing for a trip once involve that it no longer does?",
  "Which road, rail, air, or water journey changed your sense of distance?",
  "What travel delay became more memorable than the original plan?",
  "Which arrival made you immediately notice new sounds, smells, or light?",
  "What did you once bring home to remember a place?",
  "Which trip taught you a useful unspoken rule?",
  "What local transport did you have to learn by observing others?",
  "Which journey felt like crossing between two different worlds?",
  "What travel companion—person, book, song, or object—shaped a journey?",
  "Which trip do you remember through the food you encountered?",
  "What place did you understand differently after returning a second time?",
  "Which journey began before sunrise or ended after dark?",
  "What travel photograph leaves out the most interesting part of the story?",
  "Which border, bridge, station, or terminal felt significant to cross?",
  "What did getting lost once help you discover?",
  "Which familiar journey changed as the landscape developed?",
  "What weather made a past trip especially memorable?",
  "Which destination surprised you by feeling familiar?",
  "What travel plan changed for the better through improvisation?",
  "Which short local trip felt like a major adventure at the time?",
  "What phrase or gesture helped you communicate while traveling?",
  "What well-used object from your past would show its history at a glance?",
  "Which small item did you keep long after its practical purpose ended?",
  "What object once traveled with you almost everywhere?",
  "Which hand-me-down or shared possession gathered more than one person's story?",
  "What tool taught you the value of doing something by hand?",
  "Which container—box, tin, bag, or jar—was reused in a memorable way?",
  "What object did you once save up, trade, or wait patiently to get?",
  "Which item from your past had rules about who could use it and when?",
  "What broken object do you remember someone trying to repair?",
  "Which printed item—ticket, map, card, or leaflet—captures an earlier era?",
  "What object made a particular task feel official?",
  "Which possession became special because of ordinary repeated use?",
  "What object did you personalize with marks, stickers, covers, or decoration?",
  "Which item helped you feel prepared in an unfamiliar situation?",
  "What object do you remember mainly through its weight or texture?",
  "Which item was passed around so often that everyone recognized it?",
  "What old object would require the most explanation to someone younger?",
  "Which possession did you outgrow before you were ready to let it go?",
  "What useful object had a design detail you wish still existed?",
  "Which item seemed ordinary until it became difficult to replace?",
  "What object from a workplace, shop, or public service marks an era for you?",
  "Which gift became meaningful in a way the giver may not have predicted?",
  "What object did you use differently from its intended purpose?",
  "What past opinion of yours is interesting to revisit without judging it?",
  "Which experience became funnier only after enough time had passed?",
  "What once felt ordinary but now seems historically distinctive?",
  "Which change in everyday manners have you noticed across the years?",
  "What did you once consider a luxury that now feels routine?",
  "Which older practice makes more sense to you now than it once did?",
  "What part of the past do you remember with mixed feelings?",
  "Which memory has gained new meaning as you learned more context?",
  "What once-popular idea has faded from the conversations around you?",
  "Which skill from an earlier era remains valuable in your life?",
  "What did people predict about the future that turned out differently?",
  "Which change has made connection easier, and what has it made less noticeable?",
  "What past inconvenience also created an unexpected kind of anticipation?",
  "Which tradition became more meaningful after you adapted it?",
  "What ordinary memory helps you understand a larger moment in history?",
  "Which age or stage of life looks different from where you stand now?",
  "What did you once rush through that you would now slow down to notice?",
  "Which old rule have you reconsidered after hearing other perspectives?",
  "What part of an earlier lifestyle would be hardest to recreate accurately?",
  "Which change in language or expression has caught your attention over time?",
  "What memory reminds you that two people can experience the same moment differently?",
  "Which expectation about growing older has proved inaccurate for you?",
  "What from your present life might surprise an earlier version of you?",
  "Which era you lived through is most often misunderstood by people who came later?",
  "What would you preserve from today so someone in the future could understand it?",
] as const satisfies readonly string[]
