export const EVERYDAY_DEEP_CONVERSATIONS_PROMPTS = [
  'What value do you notice guiding your choices even when you do not name it?',
  'How do you decide which principles deserve to stay firm and which should evolve?',
  'What does fairness ask of us when everyone has different needs?',
  'When kindness and honesty pull in different directions, how do you navigate the tension?',
  'What makes a compromise feel wise rather than like abandoning something important?',
  'How can someone disagree with you in a way that still feels respectful?',
  'What everyday action says the most about what a person values?',
  'Which matters more to you in a hard choice: the intention, the process, or the outcome?',
  'What does integrity look like when nobody involved has a perfect option?',
  'How do you recognize when loyalty is helping a relationship grow?',
  'What responsibility do we have to people we may never meet?',
  'When does keeping an open mind become difficult, and what helps?',
  'What makes a rule worthy of respect beyond the fact that it is a rule?',
  'How should people balance personal freedom with care for a shared space?',
  'What is a generous interpretation you wish people offered one another more often?',
  'How do you tell the difference between being patient and postponing a needed choice?',
  'What kind of honesty creates room for connection?',
  'When can changing your mind be an act of courage?',
  'What does accountability look like when repair matters more than punishment?',
  'How can we honor good intentions while still addressing unintended effects?',
  'What is something people owe one another simply because they share a community?',
  'How do you decide when an exception to a principle is justified?',
  'What can make generosity sustainable instead of exhausting?',
  'Where do you see quiet forms of courage in ordinary life?',
  'What helps you act according to your values when there is no recognition for it?',
  'How do humility and confidence strengthen each other?',
  'What is the difference between keeping the peace and building peace?',
  'When does curiosity become a form of respect?',
  'What does it mean to use influence responsibly in a small group?',
  'Which shared value could improve daily life if people practiced it more deliberately?',

  'What parts of a person can remain steady even while their roles keep changing?',
  'How do the places you spend time in shape the version of you that appears there?',
  'What does authenticity allow to be flexible?',
  'When do labels help people understand themselves, and when can labels feel limiting?',
  'What aspect of your character shows up most clearly through your choices?',
  'How can someone belong to a group without becoming smaller within it?',
  'What have you discovered about yourself through an interest you chose freely?',
  'How does language influence the way people understand who they are?',
  'What makes it possible to feel continuous with an earlier version of yourself?',
  'Which parts of identity are best understood through action rather than description?',
  'How do you make room for contradictions within your sense of self?',
  'What can a person learn by noticing where they feel most at ease?',
  'How might being known by different people reveal different genuine sides of someone?',
  'What does self-respect sound like in an inner conversation?',
  'How do chosen communities contribute to a person\'s sense of identity?',
  'What is worth keeping when you reinvent part of your life?',
  'How can we let people surprise us instead of holding them to an old image?',
  'What makes a personal story feel true even as its meaning changes?',
  'How does creativity give people new ways to recognize themselves?',
  'What can you appreciate about yourself without needing to rank it?',
  'How do you distinguish your own preferences from expectations you have absorbed?',
  'What helps a person feel welcome to be complex?',
  'How can identity be a source of connection without becoming a requirement to agree?',
  'What part of being yourself feels more like a practice than a fact?',
  'How does the way you introduce yourself change across settings?',
  'What do people reveal about themselves through what they pay attention to?',
  'How might your sense of self expand without rejecting who you have been?',
  'What does it mean to define yourself with room for revision?',
  'How can someone protect their individuality while building close bonds?',
  'What helps you see another person beyond the first story you formed about them?',

  'What kind of change feels energizing even before you know where it will lead?',
  'How do you know when to adapt a plan rather than work harder at it?',
  'What can remain meaningful after its original purpose has changed?',
  'How might a transition be honored without deciding whether it is good or bad?',
  'What does gradual growth look like when it is too subtle to measure day by day?',
  'How can people support change without demanding a finished version of someone?',
  'What helps an unfamiliar situation become more navigable?',
  'When has a change of pace altered what you were able to notice?',
  'What is the value of beginning before you feel fully prepared?',
  'How do you make space for mixed feelings about a welcome change?',
  'What can a detour teach that a direct route cannot?',
  'How might changing a routine shift the way a problem appears?',
  'What helps you release a goal that no longer fits without calling the effort wasted?',
  'How can small experiments make a major decision feel more approachable?',
  'What deserves patience when you are learning a new way of doing things?',
  'How do you recognize progress that does not look impressive from the outside?',
  'What is gained when a group changes a tradition thoughtfully?',
  'How can an ending be acknowledged without rushing to frame it as a beginning?',
  'What conditions help people become more flexible?',
  'How does your relationship with change differ when you choose it yourself?',
  'What old solution might be ready for a new question?',
  'How can a person stay grounded while several things are shifting at once?',
  'What makes trying again meaningfully different from repeating the same attempt?',
  'How do seasons and cycles affect the way you think about progress?',
  'What could become possible if a current limitation changed shape?',
  'How can you respect the pace of change without becoming passive?',
  'What helps a new chapter feel connected to everything that came before it?',
  'When does simplification count as growth?',
  'How might you design a transition so that everyone affected has a voice?',
  'What change in the wider world would reshape an ordinary day for the better?',

  'What makes a question worth living with even when it has no final answer?',
  'How do you stay curious when certainty would feel more comfortable?',
  'What helps you form an opinion while leaving room to learn?',
  'How should we make choices when the available information is incomplete?',
  'What is the difference between uncertainty and possibility?',
  'How can saying “I do not know” strengthen a conversation?',
  'What kind of evidence tends to change your perspective?',
  'When two explanations both seem plausible, what do you consider next?',
  'How do you decide which unknowns require action and which can remain open?',
  'What role should intuition play when facts do not point clearly in one direction?',
  'How can a group make a thoughtful decision without pretending to be certain?',
  'What makes ambiguity creative rather than frustrating?',
  'How do you keep a tentative belief from hardening into an assumption?',
  'What would it look like to treat confusion as the start of inquiry?',
  'How can we talk productively about something none of us fully understands?',
  'What helps you separate a confident voice from a well-supported idea?',
  'When is waiting for more clarity wise, and when can it become avoidance?',
  'What do you gain by asking how else something could be understood?',
  'How might uncertainty invite cooperation?',
  'What makes you trust a process even when its outcome is unclear?',
  'How can people update a shared plan without blaming earlier decisions?',
  'What uncertainty would you rather explore than eliminate?',
  'How do you hold hope without turning it into a prediction?',
  'What can disagreement reveal about the questions beneath a topic?',
  'How might you test an assumption in a kind and low-stakes way?',
  'What is a useful way to respond when new information complicates your view?',
  'How can wonder coexist with careful skepticism?',
  'What helps you notice the limits of your own perspective?',
  'How do you choose a direction when several futures seem equally imaginable?',
  'What would become easier if people were more comfortable revising their answers?',

  'What gives an ordinary task a sense of meaning?',
  'How can purpose be shared without everyone contributing in the same way?',
  'What is the difference between a meaningful life and an impressive one?',
  'How do you recognize work that matters even when it is never finished?',
  'What makes an effort worthwhile apart from whether it succeeds?',
  'How can playfulness contribute to a serious sense of purpose?',
  'What deserves your attention simply because it makes life feel more alive?',
  'How might purpose change across different chapters without becoming less sincere?',
  'What forms of contribution are easy for society to overlook?',
  'How can caring for something small connect to a larger sense of meaning?',
  'What turns a personal interest into a source of service?',
  'How do rest and purpose support each other?',
  'What would count as enough in an area where more is always possible?',
  'How can someone pursue excellence without making achievement their identity?',
  'What kind of usefulness leaves room for joy?',
  'How do you know whether a goal belongs to you or merely sounds admirable?',
  'What can make a repeated practice feel significant over time?',
  'How might purpose emerge from attention rather than from a grand plan?',
  'What does it mean to contribute without needing to be central?',
  'How can a person measure a life by relationships rather than milestones?',
  'What is the place of delight in deciding what matters?',
  'How can purpose remain flexible enough to include surprise?',
  'What makes a responsibility feel chosen even when it is not optional?',
  'How do you balance becoming better with appreciating what already is?',
  'What kind of impact can only be noticed over a long period?',
  'How can people create meaning together during an otherwise routine day?',
  'What would you keep doing even if it could never become a credential?',
  'How does tending to a shared resource express purpose?',
  'What might a satisfying definition of “productive” include besides output?',
  'How can a sense of direction exist without a fixed destination?',

  'What makes a community feel participatory rather than merely welcoming?',
  'How can newcomers be welcomed whether they arrive confidently or cautiously?',
  'What helps neighbors move from familiarity to mutual care?',
  'How should a community handle traditions that do not serve everyone equally?',
  'Which qualities turn a common space into one everyone can claim?',
  'How can quieter forms of participation be recognized?',
  'What does healthy interdependence look like in everyday life?',
  'How might a group distribute invisible work more fairly?',
  'What helps people ask for context before judging a community decision?',
  'How can hospitality respect both newcomers and those already present?',
  'What small ritual could help people feel connected without requiring closeness?',
  'How can communities preserve memory while allowing their story to expand?',
  'What makes feedback feel like an investment in a shared future?',
  'How do people build trust across differences that will not disappear?',
  'What does repair require after a group makes a mistake?',
  'How can shared celebrations include people with different ways of participating?',
  'What would make public conversation more thoughtful and less performative?',
  'How can a community notice who is missing from a decision?',
  'What kind of leadership helps other people use their own judgment?',
  'How do informal helpers shape the character of a place?',
  'What can turn a collection of people into a genuine “we”?',
  'How might communities make disagreement safer without expecting harmony?',
  'What responsibility comes with being a long-standing member of a group?',
  'How can shared resources be cared for without creating a culture of gatekeeping?',
  'What makes an invitation feel sincere even when someone chooses not to accept it?',
  'How can a group celebrate contribution without creating a hierarchy of worth?',
  'What would help people feel more able to shape the places they inhabit?',
  'How does a community stay open to change while protecting what sustains it?',
  'What can people with different levels of power do to make collaboration more balanced?',
  'Which everyday form of civic care deserves more imagination?',

  'What ordinary sight becomes remarkable when you give it patient attention?',
  'How does wonder change the way you relate to something familiar?',
  'What question about the natural world would you enjoy exploring with no deadline?',
  'Why can learning the explanation for something make it more astonishing?',
  'What kind of beauty is easiest to miss when you are in a hurry?',
  'How might awe affect the way people treat a place?',
  'What simple human invention still seems quietly miraculous?',
  'Where do you notice patterns that make the world feel connected?',
  'What would you like to observe through the eyes of a complete beginner?',
  'How can boredom become an invitation to look more closely?',
  'What sound makes you aware of the scale or complexity of the world?',
  'Which everyday process becomes fascinating once you understand how it works?',
  'How does sharing amazement differ from explaining it?',
  'What is something vast that helps you think more gently about small concerns?',
  'How might a familiar route change if you treated it as an expedition?',
  'What kind of mystery feels nourishing rather than unsettling?',
  'How does making something by hand alter your appreciation of it?',
  'What can children\'s questions remind adults to notice?',
  'Which part of a city can inspire the same wonder as a landscape?',
  'How might technology deepen attention instead of dividing it?',
  'What fact have you encountered that made reality seem more imaginative?',
  'How does scale—from tiny to immense—change what you find beautiful?',
  'What could people rediscover by spending more time observing and less time naming?',
  'How might wonder help people care across differences?',
  'What everyday transformation would make a good subject for a slow documentary?',
  'Why do some unanswered questions feel like gifts?',
  'What place invites you to notice time differently?',
  'How can art reveal something extraordinary in common materials?',
  'What aspect of being alive seems most improbable when you pause to consider it?',
  'What would a shared practice of wonder add to a community?',

  'What does growth make possible besides becoming more skilled?',
  'What helps a disappointing attempt become useful knowledge for the next one?',
  'What kind of challenge expands you without requiring constant strain?',
  'How do you know when reflection has turned into useful understanding?',
  'What helps feedback become information rather than a verdict?',
  'How can you practice something imperfectly and still respect the process?',
  'What does beginnerhood offer that expertise sometimes loses?',
  'How might you define progress when the path is not linear?',
  'What conditions make it easier to experiment without fearing embarrassment?',
  'How can people encourage one another without setting the direction for them?',
  'What is the difference between resilience and simply enduring too much?',
  'How does teaching something reveal the edges of your own understanding?',
  'What can a pause contribute to improvement?',
  'How do you preserve curiosity once you become competent?',
  'What would it mean to grow in discernment rather than speed?',
  'How can a group normalize learning in public?',
  'What skill becomes more humane when paired with patience?',
  'How might you learn from someone whose approach is unlike yours?',
  'What helps a lesson travel from one situation into another?',
  'How can celebrating effort remain honest about outcomes?',
  'What is something you can understand only by practicing it?',
  'How do limits sometimes improve the way people learn?',
  'What does a sustainable learning rhythm include?',
  'How can unlearning be recognized as real work?',
  'What might change if you approached a weakness as a design problem?',
  'How do you decide which abilities are worth deepening?',
  'What can curiosity teach that ambition cannot?',
  'How might a mentor support independence rather than imitation?',
  'What part of mastery involves knowing when not to act?',
  'How can growth be meaningful even if nobody else can see it?',

  'What everyday choice now could make a future neighborhood more livable?',
  'How do you imagine progress that does not leave care behind?',
  'What hope feels more credible when people work on it together?',
  'How might future generations describe what our era learned to value?',
  'What would a hopeful future preserve from the present rather than replace?',
  'How can planning for tomorrow remain attentive to people here now?',
  'What possibility deserves patient preparation even if it is not guaranteed?',
  'How might success look different if we planned in decades instead of quarters?',
  'What future convenience should still leave room for human connection?',
  'How can imagination help people move beyond choosing between two poor options?',
  'What would make a city feel kinder twenty years from now?',
  'How should we decide which new capabilities are worth pursuing?',
  'What hope asks for practice rather than optimism?',
  'How could education better prepare people for futures nobody can predict?',
  'What would responsible innovation protect as it creates something new?',
  'How might tomorrow benefit from knowledge that modern life tends to overlook?',
  'What is one resource people could treat as borrowed from the future?',
  'How can a long-term vision remain open to correction?',
  'What kind of abundance would improve life without requiring more possessions?',
  'How might communities rehearse the future they want in small ways today?',
  'What deserves to become easier for people who come after us?',
  'How can hope include clear-eyed attention to obstacles?',
  'What would it mean for a future to be advanced in compassion?',
  'How could public spaces reflect greater trust in the people who use them?',
  'What tradition might future communities invent to stay connected?',
  'How can we imagine better systems without expecting perfect people?',
  'What would a future built around enoughness look like in daily life?',
  'How might people preserve meaningful choice as technology becomes more capable?',
  'What promise to the future can be kept through ordinary habits?',
  'What shared hope would you enjoy hearing many different people describe?',

  'What would a compassionate observer notice before judging this moment in history?',
  'How might two people with opposing views discover the value beneath each position?',
  'What changes when you imagine a decision from the perspective of the least-heard person?',
  'How can stories expand moral imagination without turning people into lessons?',
  'What might generosity look like when time, money, and energy are all limited?',
  'How should people respond when a fair process produces an uneven outcome?',
  'What do we learn by imagining the best reasonable case for a view we resist?',
  'How can mercy and responsibility exist in the same response?',
  'What would it mean to design a policy around dignity as well as efficiency?',
  'How might a conflict shift if everyone named what they hoped to protect?',
  'What is the ethical difference between helping, rescuing, and partnering?',
  'How can people share a burden without taking away another person\'s agency?',
  'What deserves consideration when a convenient choice has distant consequences?',
  'How could a group make space for repair without demanding public disclosure?',
  'What might justice require beyond treating everyone identically?',
  'How does imagining another person\'s constraints change a quick judgment?',
  'When resources are scarce, what principles should guide how they are shared?',
  'What makes consent meaningful in ordinary group decisions?',
  'How can someone challenge an idea while protecting the speaker\'s dignity?',
  'What would a humane solution make possible for everyone involved?',
  'How can we care about consequences that remain mostly invisible to us?',
  'What role should forgiveness play when trust still needs rebuilding?',
  'How might a decision change if future participants had a seat at the table?',
  'What does solidarity offer that sympathy alone does not?',
  'How can people avoid confusing discomfort with harm during honest dialogue?',
  'What is gained by asking who carries the cost of a seemingly simple solution?',
  'How might compassion change the questions asked before a decision?',
  'What responsibility comes with understanding a problem others can ignore?',
  'How can a community protect room for principled dissent?',
  'What would it look like to leave a difficult conversation with everyone\'s humanity intact?',
] as const
