export const EVERYDAY_EVERYDAY_PROMPTS = [
  "What has caught your attention in a pleasant way today?",
  "Which part of your surroundings feels especially noticeable right now?",
  "What ordinary sound have you enjoyed hearing lately?",
  "Where did you spot an interesting color combination recently?",
  "What bit of weather have you appreciated this week?",
  "Which everyday object have you noticed is designed surprisingly well?",
  "What is something nearby that you had not really looked at before?",
  "Which recent moment made the day feel briefly unhurried?",
  "What small detail tends to tell you that morning has properly begun?",
  "Which view on a familiar route do you still like seeing?",
  "What pleasant scent have you come across recently?",
  "Which background noise helps a place feel lively to you?",
  "What have you noticed changing with the season where you are?",
  "Which simple sight can reliably improve your mood?",
  "What everyday texture do you find oddly satisfying?",
  "Which passing scene outside a window recently held your attention?",
  "Which local sign, mural, or display has made you look twice?",
  "What tiny sign of care have you noticed in a shared space?",
  "Which familiar place feels different depending on the time of day?",
  "What has made your surroundings feel welcoming recently?",
  "Which overlooked sound would you miss if it disappeared?",
  "What recent change in your usual scenery did you notice first?",
  "Which everyday pattern or shape do you enjoy spotting?",
  "What is something ordinary that looked unexpectedly beautiful lately?",
  "Which kind of light makes a room feel best to you?",
  "What do you tend to notice first when entering a new place?",
  "Which public space near you has a character of its own?",

  "What small thing went more smoothly than expected today?",
  "Which task felt satisfying to finish recently?",
  "What tiny improvement have you made to your day-to-day life?",
  "Which recent choice saved you a little time or effort?",
  "What did you remember at exactly the right moment lately?",
  "Which everyday problem have you found a workable answer to?",
  "What is something you handled with more ease than usual?",
  "Which small bit of progress deserves a quiet nod today?",
  "What have you become quicker at without really noticing?",
  "Which unfinished thing are you glad you moved forward a little?",
  "What recent moment made you think, that worked out nicely?",
  "Which useful decision are you pleased you made ahead of time?",
  "What minor challenge brought out your resourceful side?",
  "What did you recently complete while you still had momentum?",
  "What have you made a little simpler for your future self?",
  "Which recent effort felt worthwhile even before it was complete?",
  "What is one thing you did well without needing it to be perfect?",
  "Which practical skill came in handy for you this week?",
  "What small recovery turned a wobble into an okay day?",
  "Which item did you finally find, fix, organize, or replace?",
  "What everyday decision have you been glad not to overthink?",
  "Which bit of good timing helped you out recently?",
  "What have you crossed off a list that brought real relief?",
  "Which low-key accomplishment would you happily celebrate?",
  "What did you make room for by saying no to something optional?",
  "Which new shortcut has actually made life easier?",
  "What small act of preparation paid off recently?",

  "What topic has been fun for you to follow lately?",
  "Which question have you enjoyed wondering about recently?",
  "What have you been curious enough to look up more than once?",
  "Which current interest could easily hold your attention for an hour?",
  "What is something niche you would enjoy hearing an enthusiast explain?",
  "Which recent discovery sent you down an interesting rabbit hole?",
  "What subject seems more interesting now than it once did?",
  "Which everyday mystery would you genuinely like answered?",
  "What are you enjoying learning simply because it is interesting?",
  "Which idea have you been turning over in your mind for fun?",
  "What has recently made you curious about how it works?",
  "Which hobby looks appealing from the outside, even if you never try it?",
  "What kind of facts are easiest for you to remember?",
  "Which subject would you explore on a free afternoon?",
  "What recent conversation gave you something new to look up?",
  "Which ordinary object would you like to see being made?",
  "What place would you enjoy learning about from someone who lives there?",
  "Which small question could lead to a surprisingly long conversation?",
  "What skill have you enjoyed watching someone else do well?",
  "Which part of a familiar process do you still find fascinating?",
  "What is a field you understand just enough to want to know more about?",
  "Which harmless debate have you been curious to hear both sides of?",
  "What kind of behind-the-scenes detail always interests you?",
  "Which recent fact changed how you looked at an ordinary thing?",
  "What would you enjoy having a patient beginner lesson in?",
  "Which topic makes you ask follow-up questions almost automatically?",
  "What have you learned lately from paying closer attention?",

  "Which part of your usual rhythm helps the day feel manageable?",
  "What is a gentle way you like to start something?",
  "Which routine has become easier after a small adjustment?",
  "What do you enjoy doing before the rest of the day gets busy?",
  "Which end-of-day habit helps you shift gears?",
  "What is your preferred pace for an unscheduled morning?",
  "Which recurring task do you make more enjoyable for yourself?",
  "What helps you remember the little things you need to do?",
  "Which part of getting ready do you like to keep simple?",
  "What makes a break feel genuinely refreshing to you?",
  "Which everyday choice do you prefer to make in advance?",
  "What is one routine you are happy to keep flexible?",
  "Which small ritual marks the start of your free time?",
  "What tends to make an ordinary afternoon flow well?",
  "Which chore is most improved by good company, music, or a podcast?",
  "What do you like to have within easy reach during a typical day?",
  "Which part of your schedule benefits most from a little breathing room?",
  "What is your favorite way to reset a room after using it?",
  "Which daily decision becomes easier when you have a default option?",
  "What kind of reminder actually works well for you?",
  "Which routine would you gladly make five minutes longer?",
  "What is a pleasant way you transition between two parts of your day?",
  "Which ordinary task gives you an unexpected sense of order?",
  "What do you tend to prepare before you can fully relax?",
  "Which part of a busy day do you protect from rushing when possible?",
  "What is a low-effort habit that makes tomorrow nicer?",
  "Which routine feels better when you do it your own way?",

  "What flavor have you been especially drawn to lately?",
  "Which snack has the best balance of taste and convenience?",
  "What drink suits a slow afternoon for you?",
  "Which food is most improved by the right texture?",
  "What is your favorite thing to add for a little extra crunch?",
  "Which simple meal leaves you feeling pleasantly sorted?",
  "What food aroma makes waiting worthwhile?",
  "Which ingredient do you appreciate more now than you used to?",
  "What is a food you prefer in its simplest form?",
  "Which taste combination sounds unusual but works for you?",
  "What kind of treat feels right for an ordinary day?",
  "Which food do you enjoy more at a particular temperature?",
  "What is your ideal balance between familiar choices and trying something new?",
  "Which kitchen sound signals that something good is happening?",
  "What is a small food upgrade that makes a noticeable difference?",
  "Which fruit or vegetable has the most satisfying name?",
  "What food is more about the experience than the flavor for you?",
  "Which condiment earns its place in your regular rotation?",
  "What is your preferred level of crispiness for something toasted?",
  "Which food would you choose for its aroma alone?",
  "What is a snack you enjoy eating one small piece at a time?",
  "Which meal component deserves more credit than it gets?",
  "What food do you like preparing almost as much as eating?",
  "Which warm drink has the coziest personality?",
  "What is your favorite way to make plain water more appealing?",
  "Which food tastes best when shared casually?",
  "What kind of breakfast feels most inviting on a free day?",

  "What song has fit the mood of your week?",
  "Which kind of story has been holding your attention lately?",
  "What have you watched recently that was easy to settle into?",
  "Which fictional setting would be pleasant to visit for an afternoon?",
  "What makes you keep listening to a new song past the first few seconds?",
  "Which character have you enjoyed spending time with on the page or screen?",
  "What kind of video do you find unexpectedly absorbing?",
  "Which old favorite still earns a place in your current rotation?",
  "What is your preferred way to discover something new to watch or read?",
  "Which piece of media has a particularly inviting opening?",
  "What kind of ending leaves you pleasantly satisfied?",
  "Which soundtrack would make an ordinary errand feel cinematic?",
  "What have you enjoyed recently without needing to analyze it?",
  "Which short-form story, episode, or article felt complete in just the right way?",
  "What makes a recommendation feel well matched to you?",
  "Which genre do you visit when you want something dependable?",
  "What is a title you think is especially well chosen?",
  "Which familiar story would be fun to experience in a different format?",
  "What kind of narrator or host makes you want to keep listening?",
  "Which scene from something recent had a detail you admired?",
  "What is the best time of day for you to enjoy a longer story?",
  "Which song works surprisingly well as background music?",
  "What makes you decide that a series is worth continuing?",
  "Which type of comedy tends to land best for you?",
  "What is something you enjoyed even though it was outside your usual taste?",
  "Which fictional job looks more enjoyable than its real-world version?",
  "What kind of cover art or thumbnail catches your eye?",

  "What makes a nearby walk or outing feel worthwhile to you?",
  "Which kind of local business do you always enjoy discovering?",
  "What is a useful feature you appreciate in your neighborhood?",
  "Which nearby place would you choose for a relaxed pause?",
  "What sort of street activity makes an area feel cheerful?",
  "Which local spot seems to change character through the week?",
  "What have you learned by taking a different route recently?",
  "Which neighborhood detail would you point out to a visitor?",
  "What makes a public bench or resting spot well placed?",
  "Which local errand can double as a pleasant outing?",
  "What kind of shop window do you like browsing?",
  "Which feature makes a market enjoyable to wander through?",
  "What is a small way people make shared spaces friendlier?",
  "Which nearby destination feels just far enough for a change of scene?",
  "What kind of local event would tempt you to stop by?",
  "Which place around you is especially good for people-watching?",
  "What makes a café, library, park, or lobby comfortable to linger in?",
  "Which familiar corner seems to have the best everyday stories?",
  "What is something useful you wish were within a short walk?",
  "Which local sound belongs to the rhythm of the area?",
  "What makes you choose one route over another when time is flexible?",
  "Which kind of greenery adds the most to a street?",
  "What is a considerate habit you appreciate from people nearby?",
  "Which ordinary place would be interesting to photograph across a whole year?",
  "What makes a neighborhood feel easy to navigate?",
  "Which local detail reflects the personality of the area?",
  "What type of public space invites people to use it well?",

  "What have you found a clever use for recently?",
  "Which everyday item would you enjoy redesigning for convenience?",
  "What is a simple thing you like arranging with care?",
  "Which practical project sounds satisfying for a spare hour?",
  "What have you repaired or refreshed instead of replacing?",
  "Which household problem invites the most creative solution?",
  "What would you enjoy making with materials already around you?",
  "Which storage idea has genuinely earned your approval?",
  "What is a tiny space that could be made more useful?",
  "Which object could benefit from one thoughtful extra feature?",
  "What is your favorite kind of low-stakes creative decision?",
  "Which practical task lets you improvise a little?",
  "What have you customized to suit the way you actually use it?",
  "Which everyday inconvenience could inspire a charming invention?",
  "What is something you like labeling, sorting, or displaying?",
  "Which item could be repurposed in a way that still looks good?",
  "What would you enjoy assembling if the instructions were excellent?",
  "Which small corner would be fun to give a new purpose?",
  "What is a practical detail you always notice in a well-made space?",
  "Which tool or supply is surprisingly versatile?",
  "What simple design choice can make an object easier to use?",
  "Which useful thing would be more delightful in a bold color?",
  "What is a project that would feel creative without needing to be artistic?",
  "Which common object has room for a better version?",
  "What is your approach when instructions leave out an important step?",
  "Which kind of before-and-after result feels most satisfying?",
  "What would you add to a shared fix-it or craft shelf?",

  "Which harmless preference could you cheerfully argue for?",
  "What is the ideal amount of planning for a casual outing?",
  "Which everyday item is worth choosing carefully?",
  "What is better when it is slightly imperfect?",
  "Which common convenience do you think is genuinely excellent?",
  "What is the best shape for a drinking glass or mug?",
  "Which kind of seat do you choose first when options are open?",
  "What deserves to come in more colors?",
  "Which ordinary experience is better at an off-peak time?",
  "What is a small luxury that does not need to be expensive?",
  "Which familiar smell is underrated?",
  "What is the right amount of background music for a conversation?",
  "Which simple activity is better without multitasking?",
  "What should always be easier to open?",
  "Which everyday rule makes more sense than people give it credit for?",
  "What is best enjoyed in a smaller portion?",
  "Which task is improved by taking the scenic approach?",
  "What object should have a more satisfying sound?",
  "Which season has the best everyday wardrobe options?",
  "What is the most useful pocket a bag or outfit can have?",
  "Which simple pleasure benefits from a little ceremony?",
  "What is something you prefer to borrow rather than own?",
  "Which kind of list is actually enjoyable to make?",
  "What deserves a place closer to the front door?",
  "Which tiny decision has an outsized effect on comfort?",
  "What is more enjoyable when you take your time with it?",
  "Which everyday product has packaging you appreciate?",

  "What has given you a quiet sense of appreciation lately?",
  "Which ordinary convenience are you glad exists?",
  "What is something dependable that made this week easier?",
  "Which recent exchange left you feeling a little lighter?",
  "What part of your day are you glad you got to experience?",
  "Which useful thing do you appreciate each time it works?",
  "What is something familiar you were happy to return to recently?",
  "Which small kindness have you enjoyed seeing, whether or not it involved you?",
  "What is one comfortable detail you are thankful for today?",
  "Which part of your routine feels quietly supportive?",
  "What recent moment felt like enough just as it was?",
  "Which everyday resource do you try not to take for granted?",
  "What is something simple that has been reliable for you?",
  "Which shared laugh brightened an otherwise ordinary moment?",
  "What have you been glad to have nearby lately?",
  "Which part of your week offered an unexpected bit of ease?",
  "What is something you can appreciate without needing to improve it?",
  "Which ordinary skill are you grateful someone took time to teach you?",
  "What has reminded you recently that small comforts matter?",
  "Which familiar voice or sound are you always pleased to hear?",
  "What simple option are you glad was available when you needed it?",
  "Which unnoticed effort by others makes daily life run better?",
  "What is a recent example of good enough being genuinely good?",
  "Which small part of the day felt generous to you?",
  "What everyday tool has served you well for a long time?",
  "Which moment this week would you like to quietly appreciate once more?",
  "What is something ordinary that feels fortunate when you pause to notice it?",

  "What do you hope the weather gives you a chance to do soon?",
  "Which ordinary plan would make tomorrow feel inviting?",
  "What is something small you hope to notice more often?",
  "Which current interest would be fun to explain to a curious beginner?",
  "What would make the next free afternoon feel well spent?",
  "Which simple experience would you enjoy repeating soon?",
  "What low-key plan have you been waiting for the right mood to try?",
  "Which part of an upcoming day could hold a little fun?",
  "What would you like to become more comfortable doing at your own pace?",
  "Which nearby place would you enjoy seeing in a new season?",
  "What small tradition might be nice to begin?",
  "Which everyday skill would you like to practice a bit more?",
  "What is a modest change of scenery you would welcome?",
  "Which unfinished idea would be enjoyable to pick up again?",
  "What would you like to find a better everyday use for?",
  "Which kind of pleasant surprise would suit the coming days?",
  "What simple plan could give you something nice to anticipate?",
  "Which part of your surroundings would you like to explore more closely?",
  "What would you enjoy getting slightly better at this month?",
  "Which low-pressure invitation would sound especially appealing?",
  "What everyday moment would you like to make less rushed?",
  "Which useful idea would you be happy to try once?",
  "What is something familiar you hope continues to feel good?",
  "Which small project would be satisfying to see take shape?",
  "What would make an upcoming routine day feel a little special?",
  "Which simple pleasure would you like to share with someone soon?",
  "What new detail would you enjoy adding to a familiar habit?",
  "Which harmless curiosity might lead you somewhere interesting next?",
  "What do you hope leaves you pleasantly surprised in the near future?",
  "Which lighthearted possibility feels worth keeping open?",
] as const
