export const ICEBREAKER_SOCIAL_PROMPTS = [
  'What ordinary sound do you find especially satisfying?',
  'Which part of the day tends to bring out your best energy?',
  'What snack deserves more appreciation than it gets?',
  'How do you like to make a new place feel familiar?',
  'Which small convenience would you miss surprisingly quickly?',
  'What kind of weather puts you in a good mood?',
  'Which everyday task do you secretly enjoy?',
  'What is your preferred pace for an unplanned afternoon?',
  'Which scent makes a space feel welcoming to you?',
  'What simple pleasure rarely disappoints you?',
  'How do you usually choose what to listen to?',
  'Which texture do you find oddly comforting?',
  'What is a tiny improvement that makes a room better?',
  'Which meal works at almost any time of day?',
  'What do you notice first when you enter a new space?',
  'Which season has the best everyday atmosphere?',
  'What harmless thing are you unusually particular about?',
  'How would you spend an extra twenty quiet minutes?',
  'Which common object has a design you admire?',
  'What background noise helps you focus or relax?',
  'Which color combination always catches your eye?',
  'What makes waiting feel less tedious for you?',
  'Which simple food tastes best when shared?',
  'What type of lighting makes you feel most comfortable?',
  'How do you decide when a day has been well spent?',
  'Which familiar routine would you happily recommend?',
  'What is your favorite way to reset between activities?',
  'Which everyday smell would you put in a candle?',
  'What makes a seat a particularly good seat?',
  'Which little ritual helps you begin something?',
  'What topic can almost always draw you into a conversation?',
  'Which hobby would you enjoy hearing an enthusiast explain?',
  'What is something you learned recently just because you were curious?',
  'Which kind of story holds your attention most easily?',
  'What subject becomes more interesting the closer you look?',
  'Which skill do you enjoy watching someone do well?',
  'What is a question you like being asked?',
  'Which everyday mystery would you enjoy having solved?',
  'What could you give a lively five-minute explanation about?',
  'Which word or phrase do you enjoy using?',
  'What has sparked your curiosity this week?',
  'Which kind of puzzle appeals to you most?',
  'What fact changed how you look at something ordinary?',
  'Which subject did you appreciate later than expected?',
  'What do you enjoy learning through trial and error?',
  'Which craft or process seems fascinating from the outside?',
  'What makes someone a good storyteller in your view?',
  'Which question could lead to hours of friendly discussion?',
  'What is something you understand better by seeing than hearing?',
  'Which topic would make a fun community workshop?',
  'What have you picked up from another person without formal teaching?',
  'Which detail do you tend to remember from conversations?',
  'What kind of explanation makes a complicated idea click for you?',
  'Which overlooked subject deserves a documentary?',
  'What do you wish came with clearer instructions?',
  'Which new interest would you like to explore casually?',
  'What is a useful thing someone can learn in one afternoon?',
  'Which question do you think has many good answers?',
  'What is a niche topic you are always happy to encounter?',
  'How do you know when curiosity has turned into a real interest?',
  'Which song would fit the opening scene of your morning?',
  'What kind of performance is most fun to watch with a crowd?',
  'Which fictional setting seems pleasant for a short visit?',
  'What makes you want to recommend a story to someone?',
  'Which creative activity feels approachable even for beginners?',
  'What piece of art has stayed in your mind lately?',
  'Which instrument has a sound you immediately recognize?',
  'What makes a playlist feel thoughtfully assembled?',
  'Which familiar story would be interesting from another character’s view?',
  'What title would suit a gentle comedy about this week?',
  'Which creative work do you enjoy differently each time?',
  'What kind of live event has an atmosphere you like?',
  'Which visual style makes you pause to look longer?',
  'What is a creative choice you admire even when it is not your taste?',
  'Which book, show, or game world feels especially well built?',
  'What makes a character easy to root for?',
  'Which sound belongs in a soundtrack for a calm moment?',
  'What kind of humor tends to work on you?',
  'Which old-fashioned form of entertainment should make a comeback?',
  'What is the most interesting use of color you have noticed?',
  'Which story format makes it easiest for you to get invested?',
  'What ordinary scene would you like to see painted?',
  'Which creative collaboration would you enjoy observing?',
  'What makes a handmade object feel special?',
  'Which imaginary place would have the best public spaces?',
  'What artistic skill seems almost magical to you?',
  'Which ending leaves you with the most satisfying feeling?',
  'What would make a good theme for a neighborhood festival?',
  'Which kind of exhibit would tempt you to read every label?',
  'What creative project sounds fun even if the result is imperfect?',
  'What helps a group conversation feel easy to join?',
  'Which quality makes someone a comfortable person to sit beside?',
  'How can a group make room for quieter voices?',
  'What is a good sign that people are listening to one another?',
  'Which shared activity helps conversation happen naturally?',
  'What makes an invitation feel genuinely welcoming?',
  'How do you like people to show they remembered something you said?',
  'Which group tradition can create a quick sense of togetherness?',
  'What helps you learn people’s names?',
  'Which kind of compliment feels easiest to receive?',
  'What makes teamwork enjoyable even before the result is known?',
  'How can someone gracefully bring a new person into a discussion?',
  'Which behavior signals that disagreement can stay respectful?',
  'What is a small way to help someone feel included?',
  'How do you prefer a group to make simple decisions?',
  'Which role do you naturally take when people plan something together?',
  'What makes a shared silence feel comfortable?',
  'How can a host reduce pressure on people meeting for the first time?',
  'Which conversation habit do you appreciate in others?',
  'What helps people recover from an awkward moment together?',
  'How do you recognize a group where people can be themselves?',
  'Which gesture communicates encouragement without interrupting?',
  'What makes an introduction memorable in a good way?',
  'How can people celebrate different approaches within one group?',
  'Which type of group project tends to reveal unexpected talents?',
  'What makes asking for clarification feel safe?',
  'How do you help a conversation move beyond small talk gently?',
  'Which shared expectation improves almost any gathering?',
  'What helps turn a collection of people into a team?',
  'How can a group show that opting out is truly acceptable?',
  'What local place would you suggest for a relaxed group meetup?',
  'Which community event would you be curious to attend?',
  'What makes a public space pleasant to spend time in?',
  'Which neighborhood sound gives an area character?',
  'What could people nearby teach one another?',
  'Which local feature do you think people overlook?',
  'What makes a community noticeboard worth checking?',
  'Which shared space encourages chance conversations?',
  'What low-cost event could bring different age groups together?',
  'Which everyday place is surprisingly good for people-watching?',
  'What would make your local area easier to explore?',
  'Which community resource are you glad exists?',
  'What kind of market stall always draws your attention?',
  'Which public service deserves a friendly thank-you?',
  'What makes a walk around an area interesting to you?',
  'Which kind of local club would you consider joining once?',
  'What could make a waiting area feel more human?',
  'Which public tradition helps strangers feel connected?',
  'What would you add to an ideal shared courtyard?',
  'Which place nearby changes most interestingly through the day?',
  'What makes a café, library, or park feel open to everyone?',
  'Which local view would make a good postcard?',
  'What community skill-swap would you sign up to browse?',
  'Which small change could make gatherings easier to access?',
  'What makes an event feel rooted in its community?',
  'Which free activity is better with other people around?',
  'What would you name a new gathering spot in your area?',
  'Which local custom would be enjoyable for newcomers to learn about?',
  'What brings a sense of life to a street or shared space?',
  'Which ordinary location could host a surprisingly good celebration?',
  'If this group had a mascot, what qualities should it represent?',
  'What would you put in a time capsule meant to explain an average day?',
  'If your current mood were a landscape, what would it look like?',
  'Which everyday object would be funniest at ten times its usual size?',
  'What rule would improve a city designed entirely for leisure?',
  'If you could rename one color, what name would you choose?',
  'What would a restaurant based on comfort serve besides food?',
  'Which harmless superpower would be most useful at a gathering?',
  'If a month needed a new tradition, what should people do?',
  'What would you include in a museum of ordinary life?',
  'If your laugh had a visual shape, what might it resemble?',
  'Which animal would make the most patient meeting facilitator?',
  'What invention would make rainy days more enjoyable?',
  'If chairs could have personalities, which type would be friendliest?',
  'What would be the first lesson at a school for good neighbors?',
  'If a conversation came with a soundtrack, when should the music change?',
  'Which made-up award would you enjoy presenting to someone?',
  'What would a festival of small victories look like?',
  'If you designed a flag for curiosity, what would appear on it?',
  'Which impossible shop would be fun to browse?',
  'What feature belongs in a park built for conversation?',
  'If your week were a board game, what special square would it include?',
  'What would you serve at a gathering for fictional characters?',
  'Which everyday problem deserves an absurdly elaborate solution?',
  'If clouds carried messages, what would be pleasant to read overhead?',
  'What would a library of experiences let people borrow?',
  'Which imaginary sport could almost become real?',
  'If a doorway could lead to any relaxing setting, where should it open?',
  'What would make a robot seem immediately considerate?',
  'If this conversation became a mural, which details should appear?',
  'Which shared task becomes more enjoyable with good company?',
  'What is an easy way for people to be helpful without taking over?',
  'Which kind of plan benefits from several different viewpoints?',
  'What makes dividing responsibilities feel fair?',
  'How do you prefer to receive a friendly reminder?',
  'Which contribution to a group often goes unnoticed?',
  'What helps you trust that someone will follow through?',
  'How can a group make progress when nobody has a strong preference?',
  'Which part of planning together do you enjoy most?',
  'What is a good way to acknowledge an idea that cannot be used?',
  'How do you tell when collaboration is bringing out better thinking?',
  'Which question helps a group get unstuck?',
  'What makes feedback feel useful and respectful?',
  'How can people share credit well?',
  'Which team habit saves more time than people expect?',
  'What do you appreciate in someone who coordinates a group?',
  'How can a group use different working styles as an advantage?',
  'Which small success is worth pausing to recognize?',
  'What helps people admit they need more time?',
  'How do you like a group to close a productive session?',
  'Which sign suggests that a plan is simple enough?',
  'What makes you feel that your input has been considered?',
  'How can teammates make routine work more enjoyable?',
  'Which kind of challenge is easier when tackled together?',
  'What is a fair way to rotate an unpopular task?',
  'How do you prefer others to raise a different perspective?',
  'Which group achievement feels meaningful beyond the final result?',
  'What makes it easier to ask a teammate for help?',
  'How can a team welcome someone who joins midway?',
  'Which collaboration lesson applies outside of work too?',
  'What is something enjoyable that takes less than ten minutes?',
  'Which recent moment made you smile unexpectedly?',
  'What is a pleasant change of pace from your usual routine?',
  'Which small choice can improve the rest of your day?',
  'What do you enjoy noticing when you slow down?',
  'Which everyday success deserves more celebration?',
  'What is a reliable way to make yourself laugh?',
  'Which simple activity helps time feel spacious?',
  'What has felt refreshingly easy lately?',
  'Which ordinary moment is better without multitasking?',
  'What is something you are glad you tried once?',
  'Which recent discovery have you enjoyed sharing?',
  'What is a small thing you are looking forward to?',
  'Which part of your routine feels most flexible?',
  'What has made an ordinary day memorable for you?',
  'Which kind of break leaves you feeling restored?',
  'What is one thing that went better than expected recently?',
  'Which everyday item do you use in an unconventional way?',
  'What makes a familiar activity feel new again?',
  'Which moment in a typical week feels most peaceful?',
  'What is an easy treat that feels like an occasion?',
  'Which recent choice simplified something for you?',
  'What makes you feel pleasantly productive?',
  'Which simple change of scenery helps your mood?',
  'What is a low-effort way you add fun to a day?',
  'Which everyday experience do you never mind repeating?',
  'What has caught your attention for a good reason lately?',
  'Which pause in your day do you value most?',
  'What is something ordinary you have grown to appreciate?',
  'Which small surprise would brighten a routine day?',
  'What quality helps people with different backgrounds connect?',
  'Which tradition from any community would you enjoy learning about respectfully?',
  'What makes it interesting to hear how another person does an everyday task?',
  'Which universal experience seems to inspire the widest variety of stories?',
  'What can people learn by comparing ordinary routines?',
  'Which form of welcome can be understood without many words?',
  'What makes a shared meal comfortable for people with different preferences?',
  'Which celebration element appears in many places in different forms?',
  'What is a respectful way to ask about an unfamiliar custom?',
  'Which kind of story helps people recognize common ground?',
  'What everyday gesture communicates care where you are?',
  'Which difference between people can make a conversation more interesting?',
  'What helps a group avoid treating one person as a spokesperson for others?',
  'Which shared value can show up through very different habits?',
  'What makes learning a few words from another language meaningful?',
  'Which question invites comparison without ranking anyone’s experience?',
  'What can make a gathering work well across different schedules and routines?',
  'Which type of exchange helps people appreciate different perspectives?',
  'What makes curiosity feel respectful rather than intrusive?',
  'Which everyday topic reveals variety without requiring private details?',
  'How can people welcome corrections when learning about one another?',
  'What is gained when a group has more than one way to participate?',
  'Which shared experience can connect people who have just met?',
  'What helps prevent unfamiliarity from turning into assumption?',
  'Which kind of question leaves room for many ways of living?',
  'How can a gathering honor different comfort levels with conversation?',
  'What makes exchanging recommendations a good way to connect?',
  'Which ordinary object might carry different meanings in different places?',
  'What helps people feel included when references are unfamiliar?',
  'How can a group turn differences into opportunities for learning?',
  'Which personal strength tends to become visible over time?',
  'What is something you enjoy helping others understand?',
  'Which kind of challenge brings out your patience?',
  'What helps you feel comfortable contributing an unfinished idea?',
  'Which quality in yourself has become more useful than you expected?',
  'What is a low-pressure way to encourage someone?',
  'Which type of appreciation do you enjoy giving?',
  'What helps you stay open-minded in a friendly disagreement?',
  'Which mistake can people usually laugh about soon afterward?',
  'What is an example of progress that is easy to overlook?',
  'Which habit helps you be present with other people?',
  'What do you value in a person who asks thoughtful questions?',
  'Which situation makes cooperation feel natural to you?',
  'What is a kind way to signal that someone has been heard?',
  'Which strength do groups need more often than they realize?',
  'What helps you change your mind without feeling defeated?',
  'Which form of generosity does not involve spending money?',
  'What is a good way to make enthusiasm contagious?',
  'Which everyday choice can show consideration for others?',
  'What helps a conversation stay lively without becoming competitive?',
  'Which quality makes someone easy to learn alongside?',
  'What is a gentle way to redirect a conversation?',
  'Which contribution can improve a gathering from behind the scenes?',
  'What helps you recognize when another person needs more space?',
  'Which kind of honesty strengthens a new connection?',
  'What is one way people can disagree and still build rapport?',
  'Which social skill deserves to be practiced rather than assumed?',
  'What helps a person recover after forgetting someone’s name?',
  'Which shared goal can unite people with different preferences?',
  'What makes a group memory enjoyable to revisit?',
] as const
