export const ICEBREAKER_FUN_PROMPTS = [
  "What tiny thing reliably makes an ordinary day more cheerful?",
  "If your mood today had a weather forecast, what would it predict?",
  "Which harmless sound effect would improve your entrance into a room?",
  "What snack would you appoint as the official snack of this group?",
  "If your week had a movie title, what would it be?",
  "Which everyday object deserves a dramatic theme song?",
  "What color feels the most energetic to you?",
  "A new silly holiday appears on the calendar; what does it celebrate?",
  "Which small convenience do you appreciate more than most people seem to?",
  "Who would make the funniest sports commentator from the entire animal kingdom?",
  "What word is especially satisfying to say out loud?",
  "If you had a personal mascot for today, what would it be?",
  "What simple activity makes time pass surprisingly quickly for you?",
  "Which smell instantly makes a place feel welcoming?",
  "What imaginary prize would you be delighted to win?",
  "If your laugh were a musical instrument, which one would it resemble?",
  "What ordinary task would be more fun as a team sport?",
  "Which fictional vehicle would you like to borrow for an afternoon?",
  "What is your preferred way to make a boring wait more entertaining?",
  "If you opened a tiny museum, what harmlessly specific thing would it display?",
  "What food tastes better when someone else prepares it?",
  "Which season has the best personality?",
  "What would you name a friendly cloud that followed you around?",
  "If socks could have special powers, what power should yours have?",
  "Which compliment do you especially enjoy giving people?",
  "Which household chore would you outsource to a cheerful robot?",
  "What is the funniest polite phrase you could use to end a conversation?",
  "If your current energy level were an animal, which animal would it be?",
  "What small tradition would you invent for the first day of every month?",
  "Which fruit has the most interesting design?",
  "What background music would suit a slow walk to the kitchen?",
  "If you could rename Tuesday, what would you call it?",
  "Which surprisingly useful skill can you share with the group?",
  "Which board game piece would make the best desk companion?",
  "What would be the least intimidating name for a dragon?",
  "Which object should glow whenever you misplace it?",
  "What is your favorite kind of good surprise?",
  "Which sandwich ingredient has the strongest personality?",
  "What imaginary club would you happily join?",
  "Whose thoughts would you rather hear for a minute: a tree, a flower, or a houseplant?",
  "What mundane event deserves confetti?",
  "Which shape would you trust to give sensible advice?",
  "Which cozy sound could you happily hear again and again?",
  "If your shoes could leave any pattern behind, what would you pick?",
  "What playful rule would you add to elevators?",
  "Which dessert would make the best building material in a cartoon?",
  "Which impractical talent would you genuinely enjoy having?",
  "If your phone could only keep three nonessential apps, which kinds would survive?",
  "What gentle competition could you imagine winning?",
  "Which item on a breakfast table seems most likely to have a secret life?",
  "How would you name a newly discovered shade of blue?",
  "If you ran a café for one day, what unusual detail would make it memorable?",
  "What gesture makes a greeting feel especially friendly?",
  "Picture animals in tiny hats; which one looks most distinguished?",
  "What everyday moment would you put in slow motion for comic effect?",
  "How would your ideal doorbell greet visitors?",
  "How do you like to recharge when you want to spend very little effort?",
  "Which fictional job sounds fun for exactly one day?",
  "What would you put at the center of a parade made just for fun?",
  "If pencils had flavors, what flavor should the yellow one be?",
  "What familiar object would be funniest at ten times its normal size?",
  "Which type of hat could improve almost any outfit?",
  "Can you invent a silly name for a serious-looking goose?",
  "If you could instantly decorate this room for a theme, what theme would you choose?",
  "What snack has the most satisfying texture?",
  "Which made-up award would you give yourself this week?",
  "Which punctuation mark looks the friendliest?",
  "If you could make a new flavor of popcorn, what would it taste like?",
  "What everyday object would make an excellent cartoon sidekick?",
  "Which sound belongs in a museum of delightful noises?",
  "Which tiny luxury makes you feel unexpectedly fancy?",
  "If your handwriting had a personality, how would you describe it?",
  "What imaginary creature would be easiest to care for as a pet?",
  "Which room in a home would make the strangest setting for a game show?",
  "Can you share one fun fact about something you genuinely enjoy?",
  "Your remote control gains a new button; what does it do?",
  "What food would you trust to cheer up a grumpy cartoon character?",
  "Which mode of transportation would be improved by adding music?",
  "How creatively have you seen someone use a cardboard box?",
  "If the moon could wear an accessory, what should it wear?",
  "What harmless mystery would you enjoy solving?",
  "Which vegetable would make the most convincing detective?",
  "How would you happily spend ten unexpected free minutes?",
  "If a friendly ghost tidied one area for you, what should it organize?",
  "What item would you include in a time capsule of everyday life today?",
  "Which fictional place would be nice to visit during quiet hours?",
  "Which ordinary skill looks impressive when someone does it smoothly?",
  "If you designed a playground for adults, what would it include?",
  "What sound should play when someone finds a lost item?",
  "Which drink has the most cheerful appearance?",
  "Which harmless trend would you happily bring back?",
  "If your favorite chair had a name, what might it be?",
  "What kind of shop would you enjoy browsing with no intention of buying anything?",
  "Who from the animal kingdom should host a calm talk show?",
  "Which thing is unexpectedly enjoyable to organize?",
  "Which routine deserves to become a five-minute festival?",
  "What would a trophy for excellent lounging look like?",
  "Which kitchen utensil would have the funniest speaking voice?",
  "What discovery would make reaching into a coat pocket delightful?",
  "If you were a friendly neighborhood legend, what would people know you for?",
  "What simple invention would make picnics more fun?",
  "Which kind of light makes a room feel happiest?",
  "What would you call a boat built entirely for ducks?",
  "If you could give one animal a new hobby, which pairing would amuse you most?",
  "How does your ideal cleanup soundtrack sound?",
  "Which common object has an underrated shape?",
  "Could you invent a game using only items in this room?",
  "If your name belonged to a paint color, what would that color look like?",
  "Which sentence from a robot would charm you most?",
  "Which food should always be served with a tiny flag on top?",
  "What would you place in a relaxation vending machine?",
  "Given one sentence in an animal's voice, which voice and words would you choose?",
  "What everyday achievement deserves a victory lap?",
  "Which object would you choose as captain of a team of office supplies?",
  "How would you replace an alarm clock with something more cheerful?",
  "If your day came with a sticker, what would the sticker show?",
  "Where do you particularly enjoy noticing small details?",
  "Which fictional food are you most curious to taste?",
  "What would be an excellent name for a group of friendly strangers?",
  "Where would a slide be both practical and fun?",
  "Which tune gets pleasantly stuck in your head?",
  "Who would be surprisingly good at delivering mail if animals had jobs?",
  "What type of souvenir would you collect from imaginary places?",
  "If every meeting began with a ten-second ritual, what should it be?",
  "Which snack combination deserves more attention?",
  "Which common phrase would make a funny title for a mystery novel?",
  "What would you teach in a one-hour class called Useful Nonsense?",
  "If your reflection could wave independently, how would you react?",
  "What object seems like it would tell the best stories?",
  "Which kind of weather makes indoor time feel extra cozy?",
  "Which creative project would be satisfying to finish in one afternoon?",
  "Which possession would benefit from a cleverly hidden compartment?",
  "What friendly message would you put on a banner across the sky?",
  "Which food has the most dramatic name?",
  "Which unexpected thing would look funniest as a pillow?",
  "If you directed a commercial for water, what would happen in it?",
  "What would make a library even more inviting?",
  "Which fictional character would be excellent at planning a picnic?",
  "Which pleasant scent deserves its own candle?",
  "If a button could summon one harmless thing, what would yours summon?",
  "What ordinary object would you display on a velvet cushion?",
  "Whose pep talk would be most encouraging if animals could speak?",
  "How do you make a space feel comfortable?",
  "Where would you place a window to reveal a wonderful view?",
  "What new sport could be played without keeping score?",
  "Which sound would you use to signal that snacks have arrived?",
  "Which cookie shape appeals to you most?",
  "If you wrote a guidebook to a completely imaginary town, what would visitors see first?",
  "What everyday item would you decorate with googly eyes?",
  "Which polite social rule would be fun to replace with a dance move?",
  "Which simple question do you enjoy answering?",
  "If you had a pocket-sized helper, what small job would it do?",
  "What type of scenery makes a journey more interesting?",
  "Who from the animal kingdom should narrate a nature documentary about people?",
  "What would be the signature dish at a restaurant for time travelers?",
  "Which texture deserves to appear in more places?",
  "How would you playfully title your current chapter of life?",
  "Which object would make the worst umbrella but the best conversation piece?",
  "What small detail can make a gift feel thoughtful?",
  "If the stars rearranged into a picture tonight, what would you like to see?",
  "Which unusual but harmless thing belongs in a whimsical fountain?",
  "Which cartoon sound should happen more often in real life?",
  "What could make waiting in line genuinely enjoyable?",
  "How should people everywhere signal that good news has arrived?",
  "What everyday object deserves a nicer name?",
  "Which kind of tree seems most likely to enjoy a joke?",
  "How should a game decide who goes first in the most amusing way?",
  "Which large thing would be delightful at desktop size?",
  "What would a very formal invitation to a nap say?",
  "Which food would make the cutest mascot?",
  "Where has inspiration surprised you by showing up?",
  "If your favorite mug could offer advice, what might it say?",
  "What made-up word should mean comfortably full after a good meal?",
  "Which public space would benefit from more playful design?",
  "Which simple thing gives you a fresh-start feeling?",
  "A community center has space for one fun new room; what goes in it?",
  "What should a squirrel pack for a weekend trip?",
  "Which object would be the most dramatic if it could complain?",
  "Which sort of puzzle do you enjoy figuring out?",
  "If rain fell in a harmless flavor, what flavor would you choose?",
  "What unusual shape would make a memorable building?",
  "Which fictional creature would be a considerate neighbor?",
  "What can people celebrate without spending any money?",
  "If every street had a theme, what theme would suit yours?",
  "What would you name a bakery run by bears?",
  "Which everyday sound could work as a dance beat?",
  "Which discovery would make a rarely opened drawer more fun?",
  "Which nickname would suit the sun?",
  "What type of performance would you enjoy seeing in an unexpected place?",
  "Which piece of furniture would be the best storyteller?",
  "How would you describe the gentlest possible adventure?",
  "If you built a maze, what would wait at the center?",
  "What harmless thing would you make rain from the ceiling at a celebration?",
  "Which animal footprint would make a lovely repeating pattern?",
  "Which cheerful phrase could replace goodbye?",
  "If a vending machine dispensed experiences, what option would you select?",
  "What familiar place would look funniest upside down?",
  "Which object would be delighted to receive a birthday party?",
  "Which small choice can make a meal more enjoyable?",
  "If you created a constellation, what story would it tell?",
  "What should be included in a starter kit for a wonderfully lazy afternoon?",
  "Which bird seems most likely to have excellent manners?",
  "Which harmless topic could you happily discuss for five minutes?",
  "If your local park gained one magical feature, what should appear?",
  "What sound would a rainbow make if it had one?",
  "Which kind of container is oddly satisfying to open?",
  "How would you use one sheet of colorful paper for maximum fun?",
  "If you could give a statue a day off, where would you send it?",
  "What would be a fun name for a train that never runs late?",
  "Which item would you choose to represent Earth in a friendly interplanetary exhibit?",
  "Which skill would make a talent show unexpectedly delightful?",
  "If your afternoon were a postcard, what picture would be on it?",
  "What everyday object could become a musical instrument with a little imagination?",
  "Which tiny creature would make an excellent tour guide?",
  "Which party theme works perfectly without costumes?",
  "If you could redesign a park bench, what feature would you add?",
  "What imaginary flavor would you like to try once?",
  "Which activity becomes more fun when done at an unhurried pace?",
  "Which surprise would be nicest to discover in a mailbox?",
  "If you invented a dance for celebrating small wins, what move would it include?",
  "What object would look most confident wearing sunglasses?",
  "Which kind of map would you enjoy exploring even if it led nowhere?",
  "How might you say thank you creatively without using words?",
  "If clouds had job titles, what role would suit the fluffiest one?",
  "What would make a waiting room feel more playful?",
  "Imagine animals playing hide-and-seek; which contestant makes you laugh?",
  "Which low-stakes opinion do you enjoy defending?",
  "If you could invent a scent for the color green, what would it smell like?",
  "What household object would make the most elegant crown?",
  "Which tiny improvement would make mornings smoother?",
  "How would you cross a very large room for maximum entertainment?",
  "If you found a door labeled Just for Fun, what would you hope was behind it?",
  "What name would you give a very patient snail?",
  "Which food would be most amusing to eat in miniature form?",
  "When is it entirely appropriate to use a fancy voice?",
  "If you could turn one sound into a visible shape, which sound would you choose?",
  "What would you include in a parade for everyday heroes?",
  "Which ordinary place could host an unexpectedly great treasure hunt?",
  "What is the most useful imaginary pocket you could add to your clothing?",
  "If you designed a greeting card for no particular occasion, what would it say?",
  "What animal would make a surprisingly graceful dancer?",
  "Which simple treat feels celebratory to you?",
  "What is a fictional store you would enjoy wandering through?",
  "How would you decorate a crosswalk while keeping it clear and usable?",
  "What should be the official sound of a task being completed?",
  "Which object is secretly shaped like something else?",
  "What is a playful way to make a decision between two equally good options?",
  "If you could give any building a hat, which building would you choose?",
  "What would a menu for a midnight picnic include?",
  "Which imaginary sport would have the most entertaining uniforms?",
  "What is a kind message you might leave for a stranger to find?",
  "Which harmless feature would make stairs more enjoyable?",
  "What common object would be most impressive if made of glass?",
  "Which animal seems best suited to run a cozy bookshop?",
  "What is a delightful name for a very short song?",
  "If you had to communicate only with drawings for an hour, what would you draw first?",
  "What would you grow in a garden designed purely to make people smile?",
  "Which everyday task would benefit from a costume?",
  "What is an appealing destination for a ten-minute imaginary vacation?",
  "Which room could gently spin with the least inconvenience?",
  "What snack would you serve at a meeting of friendly aliens?",
  "Which object would win an award for being dependably useful?",
  "What is a good name for a song about doing absolutely nothing?",
  "Where does a mysterious tiny door belong, and who uses it?",
  "What would be the best surprise feature in a notebook?",
  "Which kind of weather would make the funniest indoor decoration?",
  "What is a small sign that a day is going well?",
  "If a museum displayed one moment from your day, which moment would be easiest to exhibit?",
  "What playful upgrade would you give to a grocery basket?",
  "Picture a parade of animals with briefcases; who looks most natural?",
  "What is a pleasant sound that rarely gets noticed?",
  "Which ordinary object deserves its own festival?",
  "What would make a sidewalk more interesting without making it harder to use?",
  "Which shape of pasta seems to have the best attitude?",
  "What is an imaginative use for a stack of sticky notes?",
  "If a friendly monster lived under your desk, what snack would you offer it?",
  "What title would you give a documentary about your favorite relaxing activity?",
  "Which object would you send as an ambassador to a planet of giants?",
  "What is the funniest place for a secret button?",
  "Which harmless thing would be fun to watch float?",
  "What would a weather report for a perfect day mention?",
  "Which everyday object would make a surprisingly good dance partner?",
  "What is a creative way to mark the end of a long week?",
  "If a tree could send you a postcard, what might it write?",
  "What should the world's smallest theme park feature?",
  "Which item would you put on the cover of a magazine about comfort?",
  "What is a playful question you would ask a visitor from the future?",
  "If your shadow could carry one thing for you, what would you hand it?",
  "What would be a charming name for a café with no chairs?",
  "Who from the animal kingdom could direct traffic most calmly?",
  "What is a fun way to use an empty jar?",
  "If every book came with a sound effect, what should happen when one opens?",
  "What ordinary object would look best covered in stars?",
  "Which gentle challenge would you add to a neighborhood fair?",
  "What is a tiny detail that makes a celebration feel complete?",
  "If you could invent a new kind of bookmark, what would it do?",
  "What should a penguin wear to a garden party?",
  "Which place would be improved by a giant soft rug?",
  "What is an amusing name for a machine that folds laundry?",
  "If the ocean sent a friendly gift, what would you hope it was?",
] as const
