export const ICEBREAKER_REFLECTIVE_PROMPTS = [
  'What small part of your day helps you feel settled?',
  'Which everyday sound tends to lift your mood?',
  'Where do you naturally slow down and notice your surroundings?',
  'What simple routine makes life feel a little easier?',
  'When does a familiar place feel especially welcoming to you?',
  'Which ordinary object do you appreciate more than most people might expect?',
  'What kind of weather brings out a side of you that you enjoy?',
  'Which ritual marks the transition from work or study into personal time for you?',
  'What recent moment made you pause in a good way?',
  'Which part of your usual week do you quietly look forward to?',
  'What helps an unhurried morning feel complete for you?',
  'If your current mood had a texture, what would it be?',
  'What is something nearby that you often notice before others do?',
  'Which scent makes a space feel comfortable to you?',
  'How would you spend an unexpected free hour today?',
  'What modest convenience are you especially grateful exists?',
  'When you need a reset, what change of scenery works well for you?',
  'Which season best matches your natural pace?',
  'What do you enjoy doing without trying to become better at it?',
  'What tiny decision can improve the rest of your day?',
  'Which daily task do you find surprisingly satisfying?',
  'What makes a room feel inviting when you first enter it?',
  'What signals that you have had enough screen time?',
  'What is one pleasant detail from today that you would like to remember?',
  'Which low-key activity deserves more appreciation?',
  'What topic can reliably awaken your curiosity?',
  'When did you last change your mind about something unimportant?',
  'Which question do you enjoy being asked?',
  'What subject could you happily explore with no practical goal?',
  'Where does a spark of interest usually take you next?',
  'What have you noticed recently that you want to understand better?',
  'Which skill looks enjoyable even if you never master it?',
  'What kind of museum, exhibit, or collection would hold your attention?',
  'When you encounter a new idea, what makes you want to keep listening?',
  'What is something you once overlooked but now find fascinating?',
  'Which everyday process seems quietly remarkable to you?',
  'What would you enjoy learning from someone in this group?',
  'How has a hobby changed the way you notice the world?',
  'What unfamiliar place would you like to explore slowly rather than rush through?',
  'Which fact have you enjoyed sharing lately?',
  'What makes a conversation feel genuinely interesting to you?',
  'If you could observe one craft being practiced up close, which would you choose?',
  'What is a useful thing you learned later than you expected?',
  'Which question about the future keeps returning to your mind?',
  'What makes a new interest feel worth your time?',
  'What have you learned simply by paying closer attention?',
  'Which part of someone else\'s work would you like to understand better?',
  'What kind of puzzle or mystery draws you in?',
  'Where does your curiosity tend to lead you when nobody sets the agenda?',
  'What is one thing you would like a patient teacher to show you?',
  'Which personal strength shows up most clearly in ordinary moments?',
  'What comes more naturally to you now than it did a few years ago?',
  'When have you surprised yourself in a positive way?',
  'What quality do you value in yourself even if it rarely gets noticed?',
  'Which signs tell you that you are making progress?',
  'Which kind of challenge tends to bring out your resourcefulness?',
  'What is something you handle with more calm than you once did?',
  'When do you feel most capable of figuring things out?',
  'What compliment have you received that felt accurate?',
  'Which ability would your younger self be pleased to see you using?',
  'What helps you recover your confidence after a small setback?',
  'How have you made a task fit your own way of thinking?',
  'What do people often trust you to help with?',
  'Which choice have you made that reflects quiet courage?',
  'What have you become better at through repetition rather than talent?',
  'When does patience become one of your strengths?',
  'What aspect of your personality has become more useful with time?',
  'In a group, what helps you make room for your own voice?',
  'What is one capability you would like to use more often?',
  'Which past version of yourself taught you something valuable?',
  'What does being dependable look like in your own style?',
  'When have you found a creative route around a limitation?',
  'What healthy boundary helps you show up at your best?',
  'Before knowing the outcome, how might you celebrate the effort?',
  'What is a strength you recognize more readily in others than in yourself?',
  'Which kind of welcome helps you feel at ease in a new group?',
  'What makes it easier for you to contribute to a conversation?',
  'How can someone show they are listening without saying much?',
  'What shared activity helps people connect without forcing conversation?',
  'When do you feel that a group has found a comfortable rhythm?',
  'Which small gesture can make a newcomer feel included?',
  'What do you appreciate about people who approach life differently from you?',
  'In what way do you like others to invite your opinion?',
  'What helps a disagreement remain respectful?',
  'Which group tradition would you enjoy starting?',
  'What makes teamwork feel fair to you?',
  'When has someone made space for you in a memorable way?',
  'What do you hope people experience when spending time with you?',
  'How can a group make quieter forms of participation visible?',
  'Which kind of humor helps people relax together?',
  'What signals that you can be yourself around someone?',
  'Which pace feels natural when you are getting to know a new person?',
  'What is one way people can support each other without giving advice?',
  'When does collaboration become more enjoyable than working alone?',
  'What helps you remember names or details about people?',
  'Which shared value can bring very different people together?',
  'How might a host make a gathering feel less formal?',
  'What does thoughtful participation look like from your perspective?',
  'When have you felt pleasantly surprised by a group dynamic?',
  'What would make this conversation feel worthwhile for you?',
  'Which small accomplishment from the past month feels meaningful to you?',
  'What is something you finished that taught you more than you expected?',
  'How might you acknowledge progress that others may not see?',
  'When has consistency paid off for you?',
  'What recent choice made your life slightly simpler?',
  'Which effort are you glad you made, regardless of the result?',
  'What did you handle well this week?',
  'How has your definition of success become more personal over time?',
  'What is a milestone you prefer to celebrate quietly?',
  'When did a small improvement create a noticeable difference?',
  'Which unfinished project has still given you something useful?',
  'What good habit began with a very small step?',
  'Where do you find perspective when progress feels slow?',
  'What have you recently made, repaired, arranged, or improved?',
  'Which ordinary responsibility gives you a sense of completion?',
  'When has asking for help moved something forward?',
  'What is one result that mattered because of how you reached it?',
  'At what point does something feel good enough to share?',
  'What recent learning curve are you glad you stayed with?',
  'Which personal win deserves a second moment of recognition?',
  'What did you make easier for your future self lately?',
  'When has changing course been a form of progress?',
  'What is something you can do today because you practiced yesterday?',
  'Which form of recognition feels right for your contributions?',
  'Which goal became more meaningful after you adjusted it?',
  'What value guides you when the best choice is not obvious?',
  'What separates the urgent from the important in your mind?',
  'Which principle becomes clearest in the way you spend your time?',
  'What does generosity look like when money is not involved?',
  'When is simplicity more valuable to you than having more options?',
  'What kind of promise do you take especially seriously?',
  'Where do flexibility and commitment to your priorities meet?',
  'Which everyday choice reflects something you care about deeply?',
  'What does fairness ask of people in a group?',
  'When do you choose usefulness over perfection?',
  'What makes a tradition worth continuing?',
  'How has one of your priorities shifted in a welcome direction?',
  'Which matters more to you in a plan: clarity, freedom, or momentum?',
  'What does respect sound like during a difficult conversation?',
  'When is it worthwhile to take the slower route?',
  'By what measure does something deserve your attention?',
  'What role does kindness play in honest feedback?',
  'Which expectation have you learned to question?',
  'What makes an ordinary day feel well spent?',
  'How do your choices change when you think beyond the immediate result?',
  'What does enough mean in one area of your life?',
  'When do you feel most aligned with what matters to you?',
  'Which trade-off are you usually comfortable making?',
  'What helps you act thoughtfully when opinions differ?',
  'How would you describe a good use of shared time?',
  'What kind of break leaves you feeling genuinely refreshed?',
  'Where can a little unstructured time fit into a busy week?',
  'Which activity helps your attention return to the present?',
  'What tells you that your pace has become too hurried?',
  'When is doing less the wisest choice?',
  'What form of rest do you wish people valued more?',
  'How does your environment affect your ability to recharge?',
  'Which harmless indulgence feels restorative to you?',
  'What is your favorite way to let a day be uncomplicated?',
  'When do you find it easiest to put a task aside?',
  'What helps you move from mental clutter toward clarity?',
  'How would an ideal pause fit into your current routine?',
  'Which boundary preserves your energy without closing people out?',
  'What do you enjoy noticing when you have nowhere to hurry?',
  'When has a quiet moment improved your perspective?',
  'What kind of movement helps you feel more awake?',
  'What softens the edges of a demanding day for you?',
  'Which place allows your mind to wander comfortably?',
  'What is one signal that you are ready to begin again?',
  'When do you prefer companionable silence to conversation?',
  'What helps you leave work unfinished without carrying it everywhere?',
  'How can a group respect different energy levels?',
  'Which comforting ritual would you recommend without expecting it to suit everyone?',
  'What does a balanced weekend look like in your season of life?',
  'When are you happiest doing one thing at a time?',
  'What recent change has given you a fresh perspective?',
  'When a plan opens up unexpectedly, where does your mind go first?',
  'Which transition taught you something useful about your adaptability?',
  'What helps you stay curious when circumstances shift?',
  'When has an alternate plan turned out better than the original?',
  'What is one change you welcomed more easily than expected?',
  'What creates a sense of steadiness during an uncertain week?',
  'Which familiar habit has evolved along with you?',
  'What becomes possible when you release an outdated expectation?',
  'When do you prefer to prepare thoroughly, and when do you improvise?',
  'What have you learned about beginning before you feel fully ready?',
  'How does your sense of home adapt to new places or routines?',
  'Which change of mind are you grateful you allowed yourself?',
  'What helps you distinguish a temporary discomfort from a poor fit?',
  'When has flexibility protected something important to you?',
  'What is a gentle way to approach a new chapter?',
  'While trying a different approach, what helps you retain what matters?',
  'Which surprise led you toward an interesting possibility?',
  'What part of change feels energizing once you get started?',
  'When have you discovered that you needed a different kind of plan?',
  'What helps you orient yourself in an unfamiliar setting?',
  'How have you grown more comfortable with not knowing the next step?',
  'Which adjustment improved a routine you thought was already settled?',
  'What can remain constant even while circumstances change?',
  'When does a fresh start feel most believable to you?',
  'What idea have you borrowed from another generation?',
  'How has a family, community, or cultural tradition shaped your sense of celebration?',
  'Which story from the past do you enjoy hearing retold?',
  'What everyday custom from your background would you gladly share with others?',
  'When does nostalgia help you notice what matters now?',
  'What object connects you to a time or place in a pleasant way?',
  'How have your tastes changed while still keeping a link to the past?',
  'Which childhood interest still appears in your life today?',
  'What did an older person teach you through example?',
  'When has a familiar recipe, song, or saying created connection?',
  'What piece of everyday wisdom has aged well for you?',
  'How would you preserve a favorite memory without taking a photograph?',
  'Which place from your earlier life would be interesting to revisit?',
  'What have younger people helped you see differently?',
  'When do old routines feel comforting rather than limiting?',
  'What tradition have you adapted to suit who you are now?',
  'How does remembering a past success help with a present challenge?',
  'Which souvenir matters more for its story than its appearance?',
  'What ordinary technology from the past do you remember fondly?',
  'When have you enjoyed introducing someone to something familiar to you?',
  'What is a lesson you hope remains useful across generations?',
  'How has your idea of fun changed since you were younger?',
  'Which former routine would you bring back for one week?',
  'What can a group learn by comparing how people grew up?',
  'When does looking back give you energy for what comes next?',
  'What possibility for the coming year feels quietly exciting?',
  'How would you like your days to feel, apart from what you accomplish?',
  'Which future skill would make your life more interesting?',
  'What is one thing you hope becomes easier with time?',
  'When you picture a satisfying project, what is happening around you?',
  'What kind of experience would you like to make room for soon?',
  'How might your future self benefit from a small choice today?',
  'Which place would you enjoy getting to know across several visits?',
  'What do you hope remains unchanged as life moves forward?',
  'When does anticipation add enjoyment to an experience?',
  'What would you like to approach with more playfulness?',
  'How could you make an upcoming obligation feel more humane?',
  'Which idea would be worth testing on a small scale?',
  'What is a future conversation you look forward to having?',
  'When you imagine more free time, what draws your attention first?',
  'What would make the next season feel distinct from the last?',
  'In what way would you like to contribute to a place you spend time in?',
  'Which kind of invitation would be easy for you to say yes to?',
  'What are you becoming more willing to try?',
  'When might curiosity be a better guide than certainty?',
  'What would you like to understand about the world five years from now?',
  'How could an ordinary plan become something to look forward to?',
  'Which future memory would you enjoy helping create for a group?',
  'What is one hopeful change you can imagine without needing to predict it?',
  'When you think ahead, what helps possibility feel grounded?',
  'What kind of creativity fits naturally into your life?',
  'What personal touch makes an everyday task more enjoyable?',
  'Which constraint has ever helped you invent a better solution?',
  'What would you create if usefulness were the only requirement?',
  'When does play help you think more clearly?',
  'What is an unusual combination of interests that makes sense to you?',
  'Where do you capture ideas before they disappear?',
  'Which material would you like to learn to shape, build with, or arrange?',
  'What familiar thing could be redesigned to bring more delight?',
  'When have you solved a problem by looking at it sideways?',
  'What does a satisfying creative process feel like to you?',
  'How would you add a touch of personality to a shared space?',
  'Which rule is fun to work within rather than ignore?',
  'What have you seen recently that felt thoughtfully designed?',
  'When is imitation a useful starting point for learning?',
  'What ordinary scene would make an interesting painting or photograph?',
  'How do other people\'s ideas help your own thinking expand?',
  'Which unfinished idea still makes you smile?',
  'What could you explain more easily with a sketch than with words?',
  'When does arranging or organizing become a creative act?',
  'What playful experiment could improve a routine?',
  'How would you represent this week using three colors?',
  'Which kind of making feels rewarding even when the result is temporary?',
  'What changes when you treat a problem as a design question?',
  'When have limited resources led to an unexpectedly good idea?',
  'What thoughtful act have you noticed someone do recently?',
  'Which way of expressing appreciation feels natural in everyday situations?',
  'Which kind of help feels especially practical to you?',
  'What makes a thank-you feel sincere?',
  'When has someone remembered a small detail that mattered to you?',
  'What contribution to your daily life often goes unseen?',
  'How can appreciation change the atmosphere of a group?',
  'Which shared resource are you glad people maintain for one another?',
  'What is one thing about your surroundings that works well because someone cared?',
  'When do you find gratitude easiest to express?',
  'What form of encouragement helps you keep going?',
  'How might you recognize effort without judging the result?',
  'Which everyday kindness tends to stay in your memory?',
  'What do you appreciate about the way someone else thinks?',
  'When has receiving clear information felt like an act of care?',
  'What is a considerate habit that improves shared spaces?',
  'When someone makes your day easier, how do you like to respond?',
  'Which role in a group deserves more acknowledgment?',
  'What can people thank themselves for at the end of a demanding week?',
  'When does noticing good work matter more than praising talent?',
  'What local place or service are you grateful to have access to?',
  'How has someone made a routine interaction unexpectedly pleasant?',
  'Which act of preparation can be a quiet gift to others?',
  'What do you value about people who ask for little recognition?',
  'When has appreciation helped you see something familiar differently?',
] as const
