export const ICEBREAKER_CREATIVE_PROMPTS = [
  'If today had an opening title sequence, what would happen in it?',
  'What imaginary holiday would you add to the calendar, and how would people celebrate?',
  'Which ordinary object deserves a dramatic theme song?',
  'What new color would you invent, and what would you name it?',
  'If your laugh could create something each time it appeared, what would it make?',
  'What tiny museum would you enjoy curating?',
  'Which sound would make a surprisingly good doorbell?',
  'What friendly creature would you design to help people find lost things?',
  'If clouds carried messages for one afternoon, what would yours say?',
  'What would you put in a vending machine that dispenses moments instead of snacks?',
  'Which everyday task would be more delightful as a game?',
  'What imaginary award would you be happy to present to someone?',
  'If a staircase could lead somewhere impossible, where should it go?',
  'What would the first chapter of a book about this group be called?',
  'Which two harmless things would you combine to create a curious new invention?',
  'What rule would you add to make waiting in line more playful?',
  'If your current mood were a room, what interesting feature would it have?',
  'What kind of shop would exist on the friendliest street imaginable?',
  'Which animal would make an entertaining narrator for a nature documentary about humans?',
  'What secret talent would you give a garden?',
  'If you could redesign the sound of rain, what would you try?',
  'What would a map of a perfect lazy afternoon include?',
  'Which fictional job would you like to try for exactly one hour?',
  'What could a lamp do besides provide light?',
  'If a blank wall invited one changing scene each day, what should appear first?',
  'A café has tables that inspire different conversations; what belongs on its sign?',
  'Which small inconvenience needs a wildly overqualified solution?',
  'What surprising ingredient belongs in a recipe for a good day?',
  'If shoes could leave temporary patterns instead of footprints, what pattern would you choose?',
  'What message would you send using only three drawings?',
  'Which familiar place would make the best setting for a gentle mystery?',
  'What invention would help shy ideas make themselves heard?',
  'If you designed a flag for curiosity, what would be on it?',
  'What might a moonlit library lend besides books?',
  'Which boring sign could use a more imaginative rewrite?',
  'What new flavor would capture the feeling of a pleasant surprise?',
  'If a tree could offer advice, what question would you ask it?',
  'What would be inside a toolbox made for storytellers?',
  'Which object nearby would be the hero of an animated short?',
  'How might meteorologists label a weather pattern that improves everyone’s imagination?',
  'If you hosted a parade for overlooked things, what would lead it?',
  'What optional button would you add to every elevator?',
  'Which word sounds like it should mean something more magical than it does?',
  'What sort of welcome would visitors receive in a city designed by children?',
  'If shadows could choose their shapes, what would yours become?',
  'What might be the signature dish at a restaurant for storybook characters?',
  'Which household item would you appoint as captain of an imaginary expedition?',
  'What would a postcard from ten minutes in the future show?',
  'If kindness had a mascot, what would it look like?',
  'What unusual feature would make a public bench more inviting?',
  'Which everyday sound could begin a dance track?',
  'What would you plant in a garden that grows ideas?',
  'If you could rename the hour after sunset, what name would fit?',
  'What harmless rumor would you start about pigeons?',
  'Which object would you interview for a behind-the-scenes documentary?',
  'What new tradition could make ordinary Tuesdays feel special?',
  'If a breeze delivered one scent, which scent would make you smile?',
  'What would the instruction manual for a perfect pause say?',
  'Which imaginary sport would reward cooperation more than speed?',
  'What could be hidden behind a door labeled “Only If You Are Curious”?',
  'If you made a constellation from nearby objects, what story would connect them?',
  'What costume would a very serious duck wear to a celebration?',
  'Which problem could be solved by making it smaller instead of larger?',
  'What kind of bridge would you build between two fictional worlds?',
  'If memories had book covers, what style would suit a cheerful one?',
  'What title would you give a painting made entirely of sounds?',
  'Which superpower would be most useful during a group project but least useful in an adventure film?',
  'What would a friendly robot misunderstand in an amusing way?',
  'If a recipe included one emotion, which dish would you create?',
  'What should a pocket-sized festival celebrate?',
  'Which common phrase would you illustrate literally for a cartoon?',
  'What might an island shaped like a question mark be known for?',
  'If you could add one gentle surprise to a morning routine, what would it be?',
  'What would a library card unlock in an imaginary library?',
  'Which object would be funniest if it suddenly became enormous?',
  'What name would you give a train that only stops at peaceful places?',
  'If a mirror reflected possibilities instead of appearances, what might you see?',
  'What would you include in a care package for someone beginning a creative project?',
  'Which season deserves a new sound?',
  'What sort of puzzle would have many equally good answers?',
  'If a sidewalk could tell one story, whose footsteps would it remember?',
  'What tiny change could turn a meeting into an adventure?',
  'Which imaginary plant would be useful in a shared space?',
  'What would a detective search for in the Case of the Missing Motivation?',
  'If a hat granted one very specific skill, what should it help you do?',
  'What would you display in a gallery of unfinished ideas?',
  'Which animal would design the most interesting playground?',
  'What could a calendar remind people to notice?',
  'If you could give a voice to one natural phenomenon, which would you choose?',
  'What would a celebration of quiet creativity look like?',
  'Which object could become a musical instrument in an imaginary orchestra?',
  'What unusual shortcut might exist in a town drawn by a dreamer?',
  'If your week were a board game, what would count as a bonus square?',
  'What would the menu offer at a café for time travelers?',
  'Which simple shape would make the best character in a story?',
  'What would you invent to help people remember good questions?',
  'If a river could choose its destination, where might it wander?',
  'What kind of room would help new ideas feel at home?',
  'Which tiny detail can make a made-up world feel believable?',
  'What would a neighborhood exchange if money did not exist there?',
  'If you could choreograph the movement of falling leaves, what pattern would they make?',
  'What unlikely guide would you choose for a tour of an imaginary city?',
  'Which object would have the most surprising autobiography?',
  'Which name suits a machine that turns mistakes into useful discoveries?',
  'If a song could change the lighting around you, what atmosphere would you choose?',
  'What might people collect in a world with no physical possessions?',
  'Which everyday action deserves to be performed in slow motion?',
  'What could make a waiting room feel like a place worth arriving early for?',
  'If you designed a stamp for sending ideas, what image would it show?',
  'What would a friendly ghost do to make a home more cheerful?',
  'Which imaginary subject should be taught for one day?',
  'What question belongs at the entrance to a maze?',
  'If a notebook chose what to record, what might it find important?',
  'What type of story could be told from the viewpoint of a window?',
  'Which item would you add to a kit for exploring your own neighborhood?',
  'What would happen at a conference hosted by birds?',
  'If a clock measured something besides time, what should it track?',
  'What playful feature could make a long hallway memorable?',
  'Which imaginary language would be easiest to learn?',
  'A boat is built to cross a sea of ideas; which name goes on its bow?',
  'If every question produced a small light, where would you go to see the brightest glow?',
  'What could an umbrella protect you from besides weather?',
  'Which character would you create from three traits chosen by this group?',
  'What would make a treasure hunt enjoyable even if nothing valuable were found?',
  'If the floor became a map, where would the nearest path lead?',
  'What unusual service would a dragon offer its community?',
  'Which ordinary moment could inspire a five-minute film?',
  'What might be written on the back of a ticket to nowhere?',
  'If you could bottle a sound for later, which one would you save?',
  'What would a playground for grown-up imaginations include?',
  'Which object should have a holiday named after it?',
  'What would the cover of a magazine about small wonders feature?',
  'If an empty box had one impossible property, what should it be?',
  'What could make introductions feel more like storytelling?',
  'Which creature would thrive in a habitat made of music?',
  'Which name belongs on a trail that changes with each visitor?',
  'If you designed a new punctuation mark, when would people use it?',
  'What kind of message could be delivered by changing the colors of a room?',
  'Which harmless mystery would you leave for future historians?',
  'What would be the slogan for a club devoted to noticing details?',
  'If your imagination had a reception desk, what request would you make?',
  'What invention could make sharing ideas feel more like passing a ball?',
  'Which familiar story would change most if the setting moved underwater?',
  'What could a map show that no satellite could capture?',
  'If you built a monument to an everyday pleasure, what would it honor?',
  'What would a pair of socks discuss after a long day?',
  'Which imaginary mode of transport would make the journey the main event?',
  'What should be growing on the rooftop of a floating house?',
  'If a melody opened a hidden passage, where would it lead?',
  'What would you include in a museum exhibit called “Almost”?',
  'Which task would improve if everyone approached it like a beginner?',
  'What name suits a town where nobody is ever in a hurry?',
  'If you could ask an echo to return something other than sound, what would you request?',
  'What would the uniform for an official daydreamer look like?',
  'Which object could become the centerpiece of a brand-new legend?',
  'What playful rule would you give a room full of inventors?',
  'If stars were labels on a giant diagram, what might they explain?',
  'What could a community build together in one afternoon using only imagination?',
  'Which scent would make a good chapter title?',
  'What would a weather forecast for your creative energy predict?',
  'If you could redesign applause, how else might people show appreciation?',
  'What small object would make an excellent symbol for teamwork?',
  'Which imaginary neighbor would always have an interesting story?',
  'How would you title a tune that makes chores feel heroic?',
  'If a door opened whenever someone had a generous idea, what might be on the other side?',
  'What kind of story begins with a misplaced spoon?',
  'Which part of a city would you redesign for nighttime wonder?',
  'What would an instruction manual written by a cat leave unexplained?',
  'If you could add subtitles to one everyday event, which would you choose?',
  'What would be the first attraction in a park dedicated to curiosity?',
  'Which imaginary material would be most fun to build with?',
  'What could a mailbox receive besides letters and parcels?',
  'If a familiar tune became a place, what would visitors find there?',
  'What kind of helper would you invent for a person facing a blank page?',
  'Which object would tell the funniest version of today?',
  'Which label fits a collection of ideas that are too odd to discard?',
  'If a neighborhood chose a shared theme for one day, what would you suggest?',
  'What might a kite discover above the rooftops?',
  'Which two story genres would create the most surprising blend?',
  'What would you draw on a sign pointing toward possibility?',
  'If you could rearrange the sounds of a busy place, what would become the rhythm?',
  'What useful advice might come from a very old chair?',
  'Which make-believe festival would bring strangers together gently?',
  'What would happen in a story where every mistake opens a new path?',
  'If you designed a badge for asking thoughtful questions, what would it depict?',
  'What imaginary feature could make a kitchen more sociable?',
  'Which object would be a terrible spy but a wonderful storyteller?',
  'What would you place at the center of a town square built for play?',
  'If silence had different textures, which one would feel comforting?',
  'What new use would you give an abandoned imaginary castle?',
  'Which scene from daily life deserves a grand soundtrack?',
  'What could a group create by combining one idea from each person?',
  'If you made a trail from questions, what would be waiting at the end?',
  'What would a souvenir from a dream look like?',
  'Which object might secretly be practicing for a performance?',
  'A constellation appears only when people cooperate; what is it called?',
  'If you could turn one routine into a ceremony, which would you choose?',
  'What might a dictionary of impossible words help people express?',
  'Which imaginary room would change to match the story being told?',
  'What would an orchestra of weather sounds perform first?',
  'If you planted a question today, what answer might grow later?',
  'What kind of character would live between the lines of a notebook?',
  'Which simple invention could encourage neighbors to share smiles?',
  'What would you put on a menu of conversation starters?',
  'If a pebble were a tiny planet, what landmark would be visible?',
  'What might a lantern reveal that daylight cannot?',
  'Which object deserves a sequel?',
  'What would the rules be for a game nobody can lose?',
  'If a friendly monster collected compliments, how would it store them?',
  'What could turn a bus stop into a miniature stage?',
  'Which fictional weather condition would improve a celebration?',
  'What story could explain why buttons come in so many shapes?',
  'If your favorite kind of idea had a habitat, what would it need?',
  'What name fits a tiny planet devoted to making things?',
  'Which ordinary object could inspire a new dance move?',
  'What would a sign at the edge of an unfinished world say?',
  'If you designed a room around one verb, which verb would guide it?',
  'What might be exchanged at a market where nothing can be bought?',
  'Which impossible building would be fun to explore through a story?',
  'What would an encouraging alarm clock say instead of ringing?',
  'If you could give a staircase a personality, how would it greet people?',
  'What kind of story would a raindrop tell about its journey?',
  'Which shared space could benefit from one touch of whimsy?',
  'What would you invent for a celebration that must fit inside one minute?',
  'If a compass pointed toward what you need, where might it turn today?',
  'What would a bakery sell in a town inhabited by ideas?',
  'Which unlikely object could serve as a crown in a playful kingdom?',
  'How would you title a chapter that contains no conflict, only discovery?',
  'If people greeted each other with a sound effect, which one would you choose?',
  'What could be the first exhibit in a museum of future everyday life?',
  'Which imaginary creature communicates entirely through patterns?',
  'What would a portable corner for quiet thinking include?',
  'If the horizon changed shape once a year, what shape would you hope to see?',
  'What kind of challenge would reveal everyone’s different strengths?',
  'Which object would make an unexpected but dependable sidekick?',
  'Which call sign suits a radio station broadcasting from a forest?',
  'If you could add one page to every notebook, what would it invite people to do?',
  'What might a bridge say to everyone who crosses it?',
  'Which part of a story would you turn into a place people could visit?',
  'What would happen if every yawn released a tiny bubble?',
  'If an idea arrived as a visitor, how would you make it comfortable?',
  'What creative role would you enjoy playing in a make-believe village?',
  'Which everyday object would be improved by a sense of humor?',
  'A book rearranges its own pages; what title stays on the cover?',
  'If the group invented a mascot together, what quality should it represent?',
  'What could a fountain release instead of water?',
  'Which imaginary destination would require a ticket made of a promise?',
  'What would the closing scene of a film about a very good day show?',
  'If you could make one sound visible, what form would it take?',
  'What sort of garden would grow well inside a story?',
  'Which object would you choose to narrate a tour of this room?',
  'What would a school for gentle adventures teach?',
  'If you had to represent welcome with a pattern, what would it look like?',
  'What might be found in the lost-and-found box of an imaginary world?',
  'Which familiar activity would become fascinating in zero gravity?',
  'What would you add to a blueprint for a place where everyone can contribute?',
  'If an afternoon could wear a costume, what would today’s be?',
  'What would the headline announce in a newspaper devoted to good surprises?',
  'Which imaginary tool could help two very different ideas fit together?',
  'What playful challenge could be completed in a single square meter?',
  'If a path appeared wherever someone asked “why,” where might it lead?',
  'Which name fits a creature that lives on unfinished sentences?',
  'Which ordinary container could hold an extraordinary secret?',
  'What might a city sound like if its buildings could hum?',
  'If you could redesign a handshake without touching, what gesture would you invent?',
  'What kind of map would help someone explore a conversation?',
  'Which imaginary object becomes more useful when shared?',
  'What would a team of squirrels build if given a big creative brief?',
  'If every room had a curiosity switch, what would happen when it was pressed?',
  'What title would suit a comedy about a stubborn umbrella?',
  'Which detail would you add to make a secret garden welcoming rather than mysterious?',
  'What would a machine designed by poets produce?',
  'If you could translate one feeling into architecture, what space would result?',
  'What would be the perfect name for a breeze that brings new ideas?',
  'Which item could start an interesting chain reaction in a cartoon?',
  'What would a local guide recommend in a town made entirely of paper?',
  'If you designed a tiny flag for your desk or table, what would it celebrate?',
  'What kind of ending leaves the most room for another person’s imagination?',
  'Which ordinary object would you turn into a doorway for a children’s story?',
  'What would a cloud keep in its pockets?',
  'If you could create a sound logo for this group, what elements would it combine?',
  'What imaginary job requires equal parts patience and silliness?',
  'Which place would you shrink into a miniature scene to examine closely?',
  'What title would make a shared notebook feel welcoming to imperfect ideas?',
  'If the alphabet gained a letter for delight, what might it look like?',
  'What could make a round table even better for collaboration?',
  'Which object would you send as an ambassador to another planet?',
  'What would an island built from recycled stories contain?',
  'If a streetlight could offer one helpful signal, what should it communicate?',
  'What sort of creature would guard a library without frightening anyone?',
  'Which everyday scene would you recreate with only paper shapes?',
  'What would you choose as the symbol for a fresh start?',
  'If you could make a simple object respond to gratitude, how would it react?',
  'What should happen when someone rings the bell at a house of inventions?',
  'Which imaginary path can only be followed by changing your mind?',
  'What would a portrait of teamwork show without including any people?',
  'If you could add one surprising room to a community center, what would it be?',
  'What might a storyteller discover in an empty envelope?',
  'Which everyday item could become a character simply by receiving a name?',
  'What would you build at the meeting point of a river and a rainbow?',
] as const
