export const ICEBREAKER_DEEP_PROMPTS = [
  "What value becomes clearer to you when life feels complicated?",
  "Which principle do you protect even when nobody would notice?",
  "When have two values you respect pulled you in different directions?",
  "What makes a choice feel honorable to you?",
  "Which everyday decision reveals more about a person than it seems?",
  "What belief about a good life has changed for you over time?",
  "How do you decide when fairness matters more than convenience?",
  "What quality do you admire even in someone you disagree with?",
  "Which value would you like your daily schedule to reflect more clearly?",
  "What does integrity look like when there is no perfect option?",
  "How do you recognize when a rule deserves to be questioned?",
  "What kind of generosity feels most meaningful to you?",
  "Which matters more to you lately: consistency or adaptability?",
  "What responsibility do people have toward strangers?",
  "What ordinary action can carry surprising moral weight?",
  "What part of yourself has become easier to appreciate with time?",
  "Which label has helped you understand yourself, and which has limited you?",
  "When do you feel most like the author of your own life?",
  "What do people often misunderstand about the way you move through the world?",
  "Which side of you appears only in certain settings?",
  "What personal quality took you a long time to recognize?",
  "How has your idea of being authentic matured?",
  "What role do you enjoy stepping out of for a while?",
  "Which contradiction in your personality makes sense to you?",
  "What part of your identity feels chosen rather than inherited?",
  "How do you stay yourself while adapting to a group?",
  "What would a younger version of you find surprising about you now?",
  "Which part of your character are you still getting to know?",
  "What does self-respect ask of you these days?",
  "When do you notice yourself becoming more fully present?",
  "What helps a new place begin to feel like you belong there?",
  "When have you felt welcomed without needing to prove yourself?",
  "What small gesture can turn a gathering into a community?",
  "How do you make room for someone who seems unsure of their place?",
  "What kind of difference strengthens a group?",
  "When does fitting in cost too much?",
  "What shared activity helps people connect without forcing closeness?",
  "How can a group honor both togetherness and individuality?",
  "What tells you that your presence genuinely matters somewhere?",
  "Which spaces bring out your sense of contribution?",
  "How do you respond when you are the newcomer?",
  "What makes an invitation feel sincere?",
  "When can solitude deepen your sense of connection?",
  "What does a healthy sense of belonging leave room for?",
  "What helps you decide that someone is trustworthy?",
  "How does trust change after a person admits they were wrong?",
  "What kind of reliability matters most in friendship?",
  "When is giving someone the benefit of the doubt wise?",
  "What makes honesty feel caring rather than harsh?",
  "How do you rebuild confidence in your own judgment?",
  "What is one quiet way people earn trust over time?",
  "When does transparency create more confusion than clarity?",
  "What helps you speak candidly with someone you respect?",
  "How do actions and intentions weigh against each other for you?",
  "What makes an apology believable?",
  "How do you know when confidence in a person is well placed?",
  "What does discretion communicate in a relationship?",
  "When is trust best expressed through freedom rather than reassurance?",
  "What promise should people make sparingly?",
  "What change did you resist before discovering something useful in it?",
  "How do you tell whether you are growing or merely staying busy?",
  "What part of change deserves more patience than people usually give it?",
  "Which transition taught you to release an old expectation?",
  "What helps you remain grounded when familiar routines disappear?",
  "When has changing your mind felt like progress?",
  "What do you preserve when everything else is shifting?",
  "How do you recognize that a season of life is ending?",
  "What new habit has changed how you see yourself?",
  "When does starting over feel different from beginning again?",
  "What makes gradual change easier to trust?",
  "How do you honor who you were without staying who you were?",
  "What possibility becomes visible only after plans change?",
  "Which kind of change energizes you, and which asks more of you?",
  "What have you learned about timing from an unexpected detour?",
  "What kind of courage rarely gets recognized?",
  "When have you acted before feeling fully ready?",
  "What helps you distinguish bravery from recklessness?",
  "Which conversation requires more courage than it appears to?",
  "How can asking for help be an act of strength?",
  "What makes it possible to try again after embarrassment?",
  "When is patience the boldest response available?",
  "What fear has taught you something worth knowing?",
  "How do you borrow courage from other people?",
  "What does quiet conviction look like in practice?",
  "When have you surprised yourself by speaking up?",
  "What risk feels worthwhile even without a guaranteed reward?",
  "How do you prepare for a step that cannot be fully rehearsed?",
  "What helps courage last beyond a single moment?",
  "When does walking away require more strength than staying?",
  "What gives an ordinary day a sense of meaning?",
  "Which question helps you reconnect with what matters?",
  "How do you find significance in work that remains unfinished?",
  "What experience has made time feel especially well spent?",
  "When does usefulness differ from meaningfulness?",
  "What makes a contribution feel worthwhile even if it is unseen?",
  "How has your definition of success become more personal?",
  "What can make a difficult effort feel purposeful?",
  "Which small ritual reminds you that life is larger than a task list?",
  "What kind of impact matters even if you never witness it?",
  "When have you found meaning in changing your direction?",
  "What does a fulfilling life include besides achievement?",
  "How do you notice what deserves your devotion?",
  "What idea helps you place a setback in a wider story?",
  "Which moments make you feel connected to something beyond yourself?",
  "What kind of support is easiest for you to receive?",
  "How can someone help without taking over?",
  "What lets you know a person is truly listening?",
  "When do practical actions say more than comforting words?",
  "How do you offer encouragement without making promises you cannot keep?",
  "What makes advice feel welcome?",
  "Which form of care is often underestimated?",
  "How do you learn what another person actually needs?",
  "What helps people ask for assistance with dignity?",
  "When is companionship more useful than a solution?",
  "How can a group support someone who prefers privacy?",
  "What kind of check-in feels genuine to you?",
  "How do you balance being dependable with protecting your energy?",
  "What have you learned from receiving help unexpectedly?",
  "What does it mean to stand beside someone rather than lead them?",
  "What boundary has made one of your relationships healthier?",
  "How do you recognize the difference between discomfort and overextension?",
  "What makes a respectful no easier to hear?",
  "When does availability stop being generosity?",
  "How can people clarify expectations before resentment grows?",
  "What helps you protect time for what restores you?",
  "When is distance a form of care?",
  "How do you respond when another person's limit disappoints you?",
  "What boundary supports better collaboration?",
  "How can flexibility and firm limits coexist?",
  "What makes privacy valuable even between close people?",
  "When does explaining a boundary help, and when is a simple answer enough?",
  "What signal tells you that your capacity is changing?",
  "How do you make space for needs that conflict?",
  "What does mutual respect look like during disagreement?",
  "What lesson became useful only long after you learned it?",
  "How has curiosity helped you revise an assumption?",
  "What skill taught you something unexpected about your character?",
  "When do you learn better by observing than by doing?",
  "What question has opened a subject you thought you understood?",
  "How do you stay teachable when you already have experience?",
  "What mistake changed the way you prepare?",
  "Which kind of feedback helps you grow most effectively?",
  "What have you learned from someone with a very different approach?",
  "How do you decide which lessons no longer apply?",
  "What topic could keep your curiosity for years?",
  "When has confusion been the beginning of understanding?",
  "What helps knowledge become wisdom?",
  "Which ability would you enjoy being a beginner at again?",
  "How has teaching someone else changed your own understanding?",
  "What hope feels sturdy enough to act on?",
  "How do you protect optimism from becoming denial?",
  "What small sign of progress gives you energy?",
  "When has another person's vision expanded your sense of possibility?",
  "What future improvement seems both modest and meaningful?",
  "How can hope coexist with an honest view of difficulty?",
  "What possibility are you making room for now?",
  "Which human quality gives you confidence in the future?",
  "What helps you imagine beyond current limitations?",
  "When does anticipation become a source of strength?",
  "What would you like people to become better at together?",
  "How do you keep a long-term hope connected to daily choices?",
  "What overlooked trend makes you cautiously optimistic?",
  "Whose persistence reminds you that change is possible?",
  "What is worth beginning even if you cannot finish it alone?",
  "What responsibility comes with being understood by others?",
  "How do you repair a mistake that had wider effects than you expected?",
  "When should good intentions still require accountability?",
  "What obligation do we have to question our own certainty?",
  "How do you decide what is yours to carry?",
  "What does responsible influence look like?",
  "When is stepping back the most accountable choice?",
  "How can people own an impact they did not intend?",
  "What responsibility grows when you gain more knowledge?",
  "How do you balance personal freedom with shared consequences?",
  "What makes follow-through a form of respect?",
  "When does silence become a choice with consequences?",
  "What duty do experienced people have toward beginners?",
  "How should a group respond when everyone assumed someone else would act?",
  "What helps accountability lead to improvement rather than shame?",
  "What uncertainty have you learned to live beside?",
  "How do you make a sound choice with incomplete information?",
  "When does not knowing create useful openness?",
  "What helps you resist rushing toward a simple answer?",
  "How do you tell intuition from a familiar assumption?",
  "What question do you return to without needing to settle it?",
  "When has ambiguity allowed a better option to emerge?",
  "What kind of uncertainty feels energizing rather than draining?",
  "How do you communicate confidence without pretending certainty?",
  "What steadies you when outcomes depend on other people?",
  "When is waiting for more clarity worth the delay?",
  "How do you plan while leaving room for surprise?",
  "What have unpredictable circumstances revealed about your priorities?",
  "Which unknown would you rather approach with curiosity than control?",
  "What makes an unanswered question worth keeping?",
  "What makes a community resilient beyond its resources?",
  "How can neighbors build connection before a crisis arrives?",
  "What local contribution creates more value than it receives credit for?",
  "When does helping a community also change the helper?",
  "What shared space invites people to care for one another?",
  "How can communities preserve memory while welcoming new voices?",
  "What makes participation feel possible for more people?",
  "Which community tradition would you enjoy inventing?",
  "How should a group make room for respectful dissent?",
  "What turns a collection of people into a public with shared concern?",
  "How can communities celebrate without overlooking quieter members?",
  "What does good stewardship of a shared place involve?",
  "When do informal networks matter more than formal organizations?",
  "What community problem benefits most from patient cooperation?",
  "How can people care about a place they may not stay in forever?",
  "What deserves more unhurried time in your life?",
  "How has your relationship with waiting changed?",
  "Which memory has become more meaningful as years pass?",
  "What helps you notice a season before it is gone?",
  "When does looking back clarify the present?",
  "How do deadlines sharpen or distort your priorities?",
  "What do you appreciate now that once seemed ordinary?",
  "Which pace allows you to do your best thinking?",
  "How do you decide when enough time has been given to a choice?",
  "What would you like your future self to thank you for protecting?",
  "When has a pause changed the quality of your response?",
  "What can only be understood through repetition?",
  "How do you keep urgency from taking over everything?",
  "Which part of your day feels most spacious?",
  "What makes a moment feel complete?",
  "What makes a place feel like home before it becomes familiar?",
  "Which sound gives you a sense of being settled?",
  "How do objects carry the story of a place?",
  "What part of home can travel with a person?",
  "When have you felt at home in an unexpected setting?",
  "What balance of comfort and possibility makes a good home base?",
  "How does hospitality change the feeling of a room?",
  "What feature of a place affects your mood more than you expect?",
  "How do routines help create a sense of home?",
  "What does caring for a space teach us?",
  "When can a temporary place still feel deeply grounding?",
  "What makes shared space feel respectful?",
  "How has a landscape influenced your sense of identity?",
  "What kind of welcome would you want every person to experience?",
  "Which place helps you hear your own thoughts more clearly?",
  "What makes forgiveness different from pretending nothing happened?",
  "How do you know when an apology needs action behind it?",
  "When can releasing resentment serve you without restoring a relationship?",
  "What helps people move forward without erasing the past?",
  "How can self-forgiveness include responsibility?",
  "What makes repair possible after a misunderstanding?",
  "When does forgiveness need time rather than a decision?",
  "How do changed patterns speak louder than remorse?",
  "What role can curiosity play after conflict?",
  "How can people acknowledge harm without centering their own discomfort?",
  "What does a sincere attempt to make amends include?",
  "When is reconciliation separate from forgiveness?",
  "How can grace and accountability strengthen each other?",
  "What helps an old grievance lose its hold?",
  "What can a repaired relationship understand that an untested one cannot?",
  "What purpose do you find in doing something well?",
  "How do you distinguish a calling from a compelling interest?",
  "What task leaves you tired but satisfied?",
  "When does purpose emerge from commitment rather than discovery?",
  "How can a temporary role still matter deeply?",
  "What kind of problem do you feel drawn to help solve?",
  "How does service shape a person's sense of direction?",
  "What would make your efforts feel coherent across different parts of life?",
  "When can play be purposeful?",
  "What purpose might exist in making something beautiful?",
  "How do you notice when a goal no longer serves its original purpose?",
  "What kind of contribution fits your particular strengths?",
  "When does purpose require rest?",
  "How can several small purposes form a meaningful life?",
  "What are you willing to practice without needing to master?",
  "What helps you recover your perspective after a difficult day?",
  "How has flexibility strengthened you without changing your core?",
  "What ordinary resource has helped you through demanding times?",
  "When has humor created breathing room in a tense moment?",
  "How do you recognize that you need to replenish yourself?",
  "What makes persistence sustainable rather than exhausting?",
  "Which past capability reminds you that you can adapt?",
  "How can accepting limits support resilience?",
  "What helps a group regain momentum after disappointment?",
  "When does changing strategy show strength?",
  "How do small routines support you during uncertainty?",
  "What have you learned about recovering confidence?",
  "Which form of rest helps you return with clearer judgment?",
  "How can people prepare for strain without living in fear of it?",
  "What does resilience preserve besides endurance?",
  "What makes you feel genuinely known by another person?",
  "How do you show interest without turning curiosity into intrusion?",
  "What creates ease between people who are very different?",
  "When does disagreement deepen mutual understanding?",
  "What helps a conversation move beyond polite surface talk?",
  "How do you let someone influence you without losing your own view?",
  "What makes shared silence comfortable?",
  "When have you felt respected by someone who chose different priorities?",
  "How can people remain connected while wanting different outcomes?",
  "What do attentive people notice that others may miss?",
  "How does laughter change the pace of getting to know someone?",
  "What makes reciprocity feel natural rather than calculated?",
  "When is a thoughtful question itself a form of care?",
  "How do you recognize when someone wants company rather than conversation?",
  "What allows a relationship to evolve without losing its foundation?",
  "What can paying full attention reveal that quick impressions overlook?",
] as const;
