export const LATE_NIGHT_DEEP_PROMPTS = [
  'What has been quietly making your days better lately?',
  'Which rhythm in your current routine best reflects who you are now?',
  'What small choice are you glad you made this week?',
  'When do you feel most present in an ordinary day?',
  'What kind of conversation leaves you feeling energized?',
  'Which place helps your mind settle without much effort?',
  'What have you noticed recently that others might overlook?',
  'Who brings out a playful side of you?',
  'What is something simple you look forward to?',
  'Which sound, scent, or sight makes a place feel welcoming?',
  'What part of your day would you gladly make longer?',
  'When did you last surprise yourself in a good way?',
  'What topic could keep you curious for an entire evening?',
  'Which everyday skill are you happiest to have learned?',
  'What makes time with someone feel unhurried?',
  'What is a recent moment you wish you had noticed more fully?',
  'Which season of the year best matches your natural pace?',
  'What kind of humor makes you feel instantly at ease?',
  'Where do your best unplanned conversations tend to happen?',
  'What is one pleasure you rarely need to justify to yourself?',
  'Which compliment has stayed with you for a meaningful reason?',
  'What do you enjoy doing differently from most people you know?',
  'When does a gathering begin to feel genuinely comfortable?',
  'What recent discovery would you happily share with this group?',
  'Which familiar object carries more meaning than its appearance suggests?',
  'What helps you shift from a busy day into a calmer evening?',
  'What is something you have grown to appreciate with age?',
  'Which ordinary decision reveals a lot about a person?',
  'What makes you feel welcome when entering a new space?',
  'What is a tradition you enjoy even if you do it alone?',
  'Which question do you wish people asked you more often?',
  'What kind of attention makes you feel genuinely heard?',
  'What is one thing you are currently learning at your own pace?',
  'When is silence between people comfortable for you?',
  'Which detail beyond the food turns a shared meal into a lasting memory?',
  'Which part of your personality appears only around certain people?',
  'What is a harmless opinion you have changed recently?',
  'What helps you decide that someone is easy to talk with?',
  'Which memory reliably brings a gentle smile?',
  'What would help tonight feel like time well spent?',
  'What quality makes someone memorable long after a brief meeting?',
  'How can you tell when you genuinely trust another person?',
  'What do your closest relationships make possible in your life?',
  'Which friendship has changed how you understand connection?',
  'What does being dependable look like in small moments?',
  'When has someone understood what you meant before you found the right words?',
  'Which form of support lets you keep the greatest sense of agency?',
  'How do you prefer someone to check in when you seem distant?',
  'Which quality makes an apology trustworthy enough to receive?',
  'Which boundary has improved one of your relationships?',
  'What helps you stay curious during a disagreement?',
  'How do you recognize care when it is expressed differently from your own style?',
  'What do you need before you can speak honestly about something important?',
  'When have you felt included without having to earn your place?',
  'What relationship deserves more of your deliberate attention?',
  'Which shared experience has brought you closer to someone?',
  'What does loyalty mean when two people disagree?',
  'How have you learned to ask for what you need?',
  'What makes feedback feel respectful rather than personal?',
  'When is giving someone space an act of care?',
  'What do you hope people feel after spending time with you?',
  'Which form of affection or appreciation feels most natural to you?',
  'What helps a group move from politeness to real connection?',
  'How do you distinguish privacy from emotional distance?',
  'What have you learned from a relationship that changed shape?',
  'When does compromise strengthen a connection?',
  'What does mutual effort look like when life gets crowded?',
  'Which unspoken expectation is worth making explicit in relationships?',
  'How do you want others to respond when you say you would rather pass?',
  'What makes it easier to repair a misunderstanding?',
  'When have you felt respected by someone who saw things differently?',
  'What is one way you try to make room for quieter voices?',
  'How do you know when advice is welcome?',
  'What kind of honesty brings people closer?',
  'Which relationship taught you something unexpected about yourself?',
  'What does it mean to be fully on someone’s side?',
  'How can people show care without trying to solve everything?',
  'What helps you listen when you strongly want to respond?',
  'When has a thoughtful question changed the direction of a conversation?',
  'Which relationship habit would you like to practice more consistently?',
  'What value guides you when no option feels perfect?',
  'Which principle have you kept even when it cost you convenience?',
  'What does integrity require when nobody will know your choice?',
  'How do you decide what deserves your limited attention?',
  'What belief has become more nuanced as you have lived with it?',
  'Which value did you inherit and then consciously choose for yourself?',
  'What does fairness mean when people begin with unequal advantages?',
  'When does generosity become sustainable rather than draining?',
  'What responsibility do we have for consequences we did not intend?',
  'How do you balance being truthful with being considerate?',
  'Which matters more to you in a difficult decision: consistency or context?',
  'What does enough look like in a culture that encourages more?',
  'How do you decide whether a rule deserves obedience?',
  'What kind of success would not be worth its personal cost?',
  'When is changing your position a sign of strength?',
  'What does respect require beyond basic politeness?',
  'Which everyday choice best reflects your priorities?',
  'How should gratitude influence what we do next?',
  'What do people owe the communities that helped shape them?',
  'When does protecting your peace become avoiding responsibility?',
  'What is a good reason to take a difficult stand?',
  'How do you judge an action when its motives and results point in different directions?',
  'Which personal standard do you apply most firmly to yourself?',
  'What is the difference between being nice and being kind?',
  'When does ambition serve something larger than the self?',
  'How much should tradition influence a present-day choice?',
  'What does courage look like without an audience?',
  'Which value becomes hardest to practice under pressure?',
  'How do you want power to change the person who holds it?',
  'What makes forgiveness wise in some situations and unwise in others?',
  'When is patience an active choice rather than passive waiting?',
  'What do you consider a meaningful use of influence?',
  'How should we respond when our comfort depends on someone else’s unseen labor?',
  'Which is more important in leadership: certainty or openness?',
  'What does accountability make possible after harm?',
  'How do you decide when loyalty conflicts with conscience?',
  'What obligation do we have to people we may never meet?',
  'When is refusing to participate the most constructive action?',
  'What makes a sacrifice feel chosen rather than imposed?',
  'Which value would you want a younger person to see you practice?',
  'What part of who you are took time to recognize?',
  'Which label has helped you understand yourself, and where does it fall short?',
  'How has your sense of home changed across your life?',
  'What do you know about yourself now that you once misunderstood?',
  'Which version of you would be most surprised by your life today?',
  'What aspect of your background do you carry with quiet pride?',
  'How do different communities bring forward different sides of you?',
  'What role have you outgrown but still slip into sometimes?',
  'Which part of your identity feels chosen rather than inherited?',
  'What personal story have you learned to tell with more generosity?',
  'How do you remain yourself while adapting to a new environment?',
  'What does authenticity mean when every setting asks something different of you?',
  'Which assumption about adulthood have you revised?',
  'What have you stopped needing to prove?',
  'How has lived experience reshaped what confidence means to you?',
  'What part of your character was shaped by an unlikely influence?',
  'When do you feel least concerned with how you are perceived?',
  'Which contradiction in yourself have you learned to accept?',
  'What does your younger self still contribute to your decisions?',
  'How do you tell the difference between growth and self-rejection?',
  'What name would you give the chapter of life you are in now?',
  'Which expectation about yourself are you ready to reconsider?',
  'What does belonging without conformity look like to you?',
  'How have the languages or expressions you use shaped your thinking?',
  'Which part of your identity is easiest to express through action?',
  'What do you wish people understood about the context that shaped you?',
  'How do you decide which parts of your past still deserve a vote?',
  'What personal quality has revealed itself slowly over time?',
  'When have you felt seen in a way that expanded your sense of self?',
  'Which inherited expectation have you made your own, altered, or released?',
  'What does self-respect look like in your current season?',
  'How has moving between roles changed what you notice about yourself?',
  'What part of your life feels most aligned with your inner voice?',
  'Which experience made your worldview larger?',
  'How do you want to be known beyond your work or responsibilities?',
  'What can a person change about themselves while remaining recognizably the same?',
  'Which part of becoming yourself has required the most patience?',
  'What does maturity add without needing to erase?',
  'How do you relate to the person others remember you being?',
  'What does it feel like when your choices and your sense of self agree?',
  'What gives a day meaning even when it produces nothing measurable?',
  'Which responsibility feels connected to a larger purpose?',
  'What kind of contribution would make your effort feel worthwhile?',
  'How do you recognize a goal that truly belongs to you?',
  'What are you willing to do slowly because it matters deeply?',
  'Which unfinished project still holds meaning for you?',
  'What does purpose look like during a season of rest?',
  'How has helping someone else clarified what matters to you?',
  'What would you keep doing without recognition?',
  'Which question do you want your life to explore rather than answer?',
  'What makes work feel dignified regardless of status?',
  'How do you distinguish urgency from importance?',
  'What deserves a place in your life before you feel fully ready?',
  'Which aspiration has changed form without losing its heart?',
  'What can make a modest life feel expansive?',
  'How do you want your presence to affect the rooms you enter?',
  'What kind of problem do you find meaningful to help solve?',
  'Which commitment helps organize your other choices?',
  'What would a fulfilling ordinary week look like?',
  'How does service fit into your idea of a meaningful life?',
  'What is worth protecting from constant optimization?',
  'Which achievement mattered less than the person you became pursuing it?',
  'What role does beauty play in a life well lived?',
  'How do you decide when to persevere and when to redirect?',
  'What would you like to make possible for people who come after you?',
  'Which part of your life deserves more wholehearted participation?',
  'What does progress mean when the destination keeps changing?',
  'How do you keep long-term hopes connected to present choices?',
  'What kind of effort leaves you tired but satisfied?',
  'Which ordinary responsibility carries unexpected significance?',
  'What do you hope your closest people remember about how you lived?',
  'How might your idea of purpose change if usefulness were not required?',
  'What is one way you want to spend your finite attention more deliberately?',
  'Which dream became more honest when you made it smaller?',
  'What does meaningful ambition make room for besides achievement?',
  'How do you want to contribute when you are not leading?',
  'What makes a season of waiting valuable in its own right?',
  'Which pursuit connects your abilities with someone else’s needs?',
  'What would you choose to learn if mastery were not the goal?',
  'Which change in your life first felt like a loss and later felt like space?',
  'How do you know when you are ready for a new chapter?',
  'What has uncertainty taught you about control?',
  'Which transition changed your priorities in an unexpected way?',
  'What helps you act before confidence arrives?',
  'How do you stay flexible without abandoning what anchors you?',
  'What possibility have you made peace with not knowing?',
  'Which ending eventually revealed a beginning?',
  'What do you reach for when a familiar plan stops fitting?',
  'How has a detour altered your understanding of progress?',
  'What is becoming easier to release?',
  'Which kind of uncertainty feels inviting rather than threatening?',
  'How do you make decisions when clarity is incomplete?',
  'What change are you learning to meet with less resistance?',
  'Which assumption do you revisit when circumstances surprise you?',
  'What helps you remain hopeful without demanding a particular outcome?',
  'How can you honor what ended without wishing it back?',
  'What have you discovered by being new at something again?',
  'Which risk feels worthwhile because of what it could teach you?',
  'How do you recognize when caution is serving you well?',
  'What does acceptance allow that resignation does not?',
  'Which uncertainty would be easier to carry alongside others?',
  'How has your relationship with change evolved over time?',
  'What can planning offer even when plans do not survive?',
  'When has not getting an answer helped you ask a better question?',
  'What helps you find direction when there is no clear map?',
  'Which possibility are you holding lightly right now?',
  'How do you protect curiosity from the desire for certainty?',
  'What would patient change look like in one area of your life?',
  'Which part of beginning again feels most alive?',
  'How can you tell when fear contains useful information?',
  'What has an unexpected outcome taught you about your own predictions?',
  'Which old plan are you grateful you revised?',
  'How do you want to meet the parts of the future you cannot prepare for?',
  'What does adaptability preserve rather than compromise?',
  'Which decision became possible only after you accepted uncertainty?',
  'How do you maintain trust in yourself while reconsidering your path?',
  'What is one unknown you can allow to remain open tonight?',
  'Which change would benefit from experimentation instead of a final commitment?',
  'How has waiting changed the quality of a decision?',
  'Which challenge revealed support you had not noticed before?',
  'How do you recover your perspective after a disappointing day?',
  'What practice helps you return to yourself?',
  'Which difficult season clarified what you wanted to protect?',
  'How has receiving help changed your idea of strength?',
  'What does resilience look like when it includes rest?',
  'Which small choice helps you keep going without pretending everything is fine?',
  'How do you speak to yourself when your best effort falls short?',
  'What has made you more tender without making you less strong?',
  'Which source of encouragement do you sometimes forget is available?',
  'How can a community help people remain hopeful realistically?',
  'What does starting over teach that uninterrupted success cannot?',
  'Which limit has helped you build a more sustainable life?',
  'How do you know when endurance needs company?',
  'What have you learned about rebuilding trust in your own judgment?',
  'Which ordinary habit steadies you during demanding periods?',
  'How has disappointment refined one of your hopes?',
  'What helps you remember that a hard moment is not the whole story?',
  'Which form of help would you like to become better at accepting?',
  'How do you preserve dignity while depending on others?',
  'What does being gentle with yourself make possible?',
  'Which setback eventually strengthened a skill or relationship?',
  'How do you make space for both gratitude and difficulty?',
  'What can you offer others because of something you have learned the hard way?',
  'Which sign tells you that your energy needs protecting?',
  'How does humor help you carry what cannot be quickly fixed?',
  'What does hope ask of you on an unremarkable day?',
  'Which connection has helped you feel less alone in uncertainty?',
  'How do you want people to support you when words are not useful?',
  'What helps you return after withdrawing to regain your balance?',
  'Which human challenge do you hope future generations navigate more wisely?',
  'Which overlooked contribution holds a community together?',
  'How do you want to use what you understand more clearly now?',
  'What would make your corner of the world feel more humane?',
  'Which conversation could help a group move from intention to action?',
  'How can belonging expand without asking anyone to become smaller?',
  'What responsibility comes with being welcomed somewhere?',
  'Which shared practice could strengthen trust over time?',
  'How do we make room for people whose pace differs from our own?',
  'How is solidarity practiced when no crisis commands attention?',
  'Which difference has enriched a group you belong to?',
  'How can we remain connected when our lives take different directions?',
  'What would listening across generations make possible?',
  'Which kind of hospitality goes beyond offering a seat?',
  'How should a community respond when someone says they feel unseen?',
  'What does being a good ancestor mean in the choices available today?',
  'Which act of care could ripple farther than we will ever see?',
  'How might our different strengths serve something we share?',
  'What kind of belonging would you like to help create?',
  'Which truth can we hold together without rushing to simplify it?',
  'How can a group become brave enough for honesty and gentle enough for limits?',
  'What do you want to remember about the people gathered here?',
  'Which hope would you like to place in trusted company?',
  'How can we make thoughtful conversation part of ordinary life?',
  'What would it look like to leave room for everyone’s unfinished becoming?',
  'Which shared question feels worthy of returning to in a year?',
  'How do you want care expressed when the right words are unavailable?',
  'What can we appreciate about one another without asking for more disclosure?',
  'Which small commitment could make belonging more tangible?',
  'How might tonight influence the way you listen tomorrow?',
  'What is one thing this conversation has made you newly curious about?',
] as const
