export const LATE_NIGHT_NOSTALGIA_PROMPTS = [
  "Which scent can still carry you straight into an ordinary day from long ago?",
  "What sound once marked the beginning or end of your day?",
  "Which kind of weather makes an old scene return most vividly?",
  "What texture do you associate with a place where you once spent time?",
  "Which background noise from an earlier era do you rarely hear now?",
  "What color combination instantly feels like a particular period of your life?",
  "Which familiar smell used to tell you that food or a drink was nearly ready?",
  "What did the air feel like during evenings you remember especially well?",
  "Which seasonal sound once made you pause and listen?",
  "What taste has changed least in your memory over the years?",
  "Which old setting can you picture most clearly when you close your eyes?",
  "What small sensory detail helps you date a memory without checking a calendar?",
  "Which sound from outside used to drift into a room you knew well?",
  "What kind of light reminds you of slow afternoons from another time?",
  "Which scent would you choose to preserve in a tiny bottle of memories?",
  "What everyday sound disappeared so gradually that you barely noticed?",
  "Which remembered place had the most distinctive temperature?",
  "What flavor seemed stronger or more exciting when you first encountered it?",
  "Which surface underfoot brings back a specific route you used to take?",
  "What did nighttime sound like in a place you once knew well?",

  "What ordinary object did you once carry almost everywhere?",
  "Which household item from years ago had a design you still admire?",
  "What object did you keep long after it stopped being useful?",
  "Which container, tin, box, or bag was reused in a way you remember?",
  "What small possession once made you feel surprisingly grown-up?",
  "Which tool did someone show you how to use through patient demonstration?",
  "What object had an unofficial purpose that mattered more than its intended one?",
  "Which item did people around you repair instead of replace?",
  "What everyday object once required a ritual that newer versions have removed?",
  "Which piece of clothing tells the clearest story about an earlier version of you?",
  "What object did you enjoy arranging, sorting, or organizing?",
  "Which borrowed item do you remember treating with extraordinary care?",
  "What was the most satisfying thing to open, unfold, wind, or click?",
  "Which object seemed enormous when you were smaller or younger?",
  "What item in a pocket, drawer, or bag could always be counted on?",
  "Which once-common object would be hardest to explain without demonstrating it?",
  "What object did you customize with marks, covers, labels, or decorations?",
  "Which possession gained character through scratches, fading, or repeated use?",
  "What item did you save for a special moment that eventually arrived?",
  "Which object did a community share rather than everyone owning separately?",

  "What did you look forward to during a typical day when you were younger?",
  "Which game required little more than imagination and whoever was nearby?",
  "What made a long day feel shorter during your early years?",
  "Which rule invented by young people around you was taken very seriously?",
  "What place offered you room to be curious without needing much explanation?",
  "Which skill did you practice simply because mastering it felt satisfying?",
  "What did you once collect without needing the collection to be valuable?",
  "Which question occupied your imagination at an earlier age?",
  "What was your favorite way to make use of an unexpected free hour?",
  "Which early responsibility helped you understand what others counted on you for?",
  "What did people your age teach one another away from adults or formal lessons?",
  "Which made-up character, world, or ongoing story entertained you for a while?",
  "What tiny achievement once felt worthy of a full celebration?",
  "Which place of learning mattered to you outside any formal classroom?",
  "What did you draw, build, write, perform, or invent just for yourself?",
  "Which childhood or youth trend did you observe without ever joining?",
  "What phrase did young people use that older people seemed not to understand?",
  "Which early mistake became a funny or useful lesson rather than a lasting worry?",
  "What route did you know well enough to notice every small change along it?",
  "Which quiet activity gave you a private world of your own?",

  "Which song is attached to a very specific room, route, or gathering in your mind?",
  "What program, performance, or story did people around you discuss the next day?",
  "Which piece of media did you discover later than everyone else?",
  "What was your earliest way of choosing what to watch, hear, or read?",
  "Which advertisement, announcement, or jingle lingered longer than its product?",
  "What recording did you replay until you knew its smallest details?",
  "Which fictional setting once felt almost like a place you had visited?",
  "What media format made waiting part of the experience?",
  "Which performer or character influenced a style you tried for yourself?",
  "What story did you first encounter in one format and later rediscover in another?",
  "Which title or cover design could you recognize from across a room?",
  "What broadcast or release felt like a shared appointment for many people?",
  "Which piece of entertainment improved because of the company you enjoyed it with?",
  "What media habit from your past would seem unusually patient now?",
  "Which song did you misunderstand in a way that made it more memorable?",
  "What did you once record, clip, copy, or save so you could revisit it?",
  "Which story seemed different when you returned to it at another age?",
  "What was the best part of browsing without knowing what you would find?",
  "Which voice from radio, television, recordings, or public announcements stays recognizable?",
  "What piece of popular culture helped you connect with someone unexpected?",

  "What was the first piece of technology whose workings genuinely fascinated you?",
  "Which task used to involve more steps than it does now?",
  "What machine or device had a personality people learned to work around?",
  "Which technology did you initially doubt would become part of ordinary life?",
  "What did you learn by pressing buttons or trying commands without instructions?",
  "Which obsolete sound once meant that a connection was being made?",
  "What technology changed how you kept in touch with people?",
  "Which device was shared according to an unwritten schedule?",
  "What feature once felt futuristic but now seems beautifully simple?",
  "Which technical limitation inspired the most creative workaround?",
  "What did you have to memorize before devices began remembering it for you?",
  "Which form of communication made every word feel carefully chosen?",
  "What old interface or control can your hands still remember using?",
  "Which upgrade felt less important than people predicted?",
  "What technological change altered the pace of waiting?",
  "Which device did you learn from someone younger or older than you?",
  "What piece of technology seemed to bring a distant place closer?",
  "Which digital or mechanical mishap became a good story later?",
  "What did you enjoy about searching for information before instant answers?",
  "What future technology did you imagine that still has not arrived?",

  "What simple meal or snack belongs to a particular chapter of your life?",
  "Which food preparation sound tells a story before the first bite?",
  "What ingredient did you learn to judge by feel rather than measurement?",
  "Which shared food came with an unspoken rule about who received which part?",
  "What dish or drink tastes best in the setting where you first knew it?",
  "Which food did you appreciate only after encountering it more than once?",
  "What method of wrapping, carrying, or serving food do you remember fondly?",
  "Which kitchen shortcut seemed ingenious when someone showed it to you?",
  "What food was closely tied to a certain time of day?",
  "Which aroma could gather people before anyone called them?",
  "What recipe lived mostly in gestures, estimates, or spoken reminders?",
  "Which treat felt special because it was rare rather than expensive?",
  "What local food custom surprised someone unfamiliar with it?",
  "Which meal was made memorable by an improvised substitution?",
  "What did you enjoy eating in a way others considered unusual?",
  "Which utensil or cooking vessel seemed essential to getting something right?",
  "What flavor marks a season for you more reliably than a date?",
  "Which food changed meaning for you as you grew older?",
  "What meal was worth the long preparation because the process brought people together?",
  "Which food-related task did you volunteer for or try to avoid?",

  "What landmark once told you that you were nearly where you wanted to be?",
  "Which neighborhood sound helped you tell what time it was?",
  "What unofficial gathering place did people treat as their own?",
  "Which local character made ordinary encounters more interesting?",
  "What shortcut did only regulars seem to know?",
  "Which shop, stall, service, or meeting spot had its own rhythm?",
  "What change to a familiar street took the longest to feel normal?",
  "Which view did you pass often without realizing you would later miss it?",
  "What did people nearby lend, exchange, or do for one another?",
  "Which public space worked differently at different hours?",
  "What local sign, mural, noticeboard, or display regularly caught your attention?",
  "Which route invited lingering rather than rushing?",
  "What did newcomers need someone local to explain?",
  "Which neighborhood smell belonged to a particular business or activity?",
  "What temporary event changed the feeling of a familiar area?",
  "Which boundary existed in local understanding but not on any map?",
  "What place nearby felt completely different after dark?",
  "Which familiar destination did you reach by several possible routes?",
  "What local custom made people feel recognized?",
  "Which building or open space has played several roles in your memories?",

  "What morning habit from another time still influences how you begin a day?",
  "Which weekly task had a rhythm that made it satisfying?",
  "What routine was shaped by daylight, weather, or the seasons?",
  "Which recurring errand offered an unexpected chance to socialize?",
  "What did you routinely prepare the night before?",
  "Which small delay used to be accepted as part of daily life?",
  "What signal told everyone it was time to change activities?",
  "Which chore became easier when turned into a game or shared ritual?",
  "What did a restful evening look like during one period of your life?",
  "Which recurring journey had a favorite point along the way?",
  "What household rhythm did you only notice after it changed?",
  "Which old routine would feel surprisingly luxurious now?",
  "What did you do while waiting for water, transport, food, or another everyday necessity?",
  "Which day of the week once had the strongest personality?",
  "What seasonal preparation created a sense of readiness?",
  "Which repeated task gave you useful time to think?",
  "What did people around you do when the usual routine was interrupted?",
  "Which personal ritual helped you shift from work or study into free time?",
  "What timekeeping habit worked even without looking at a clock?",
  "Which routine included a moment of pleasant anticipation?",

  "What small celebration made an ordinary achievement feel official?",
  "Which recurring occasion had a preparation you enjoyed more than the event itself?",
  "What decoration was made from whatever happened to be available?",
  "Which celebration included a role you liked taking on?",
  "What tune, phrase, gesture, or signal announced that festivities had begun?",
  "Which milestone felt real only after a quiet moment later?",
  "What gathering changed shape as different generations or friends arrived?",
  "Which special occasion had an amusing tradition nobody questioned?",
  "What did people wear, carry, or display to mark an important day?",
  "Which celebration worked especially well on a small scale?",
  "What handmade contribution made an event feel personal?",
  "Which milestone surprised you by mattering more than expected?",
  "What recurring event divided the year into a before and an after?",
  "Which festive food, sound, or activity was saved until exactly the right moment?",
  "What occasion brought together people who rarely met otherwise?",
  "Which achievement did you recognize privately before anyone else noticed?",
  "What changed about a familiar celebration as your life changed?",
  "Which gathering depended on one person's memorable sense of timing?",
  "What low-key tradition deserves to continue even if few people know about it?",
  "Which occasion created the funniest mismatch between plans and reality?",

  "What activity first made a friendship feel easy?",
  "Which friend introduced you to something that became part of your life?",
  "What tiny favor once communicated trust without needing to be discussed?",
  "Which shared joke survived long after its original context was forgotten?",
  "What place became meaningful mainly because of the people you met there?",
  "Which friendship grew through repeated brief encounters?",
  "What did you and someone else become unexpectedly good at doing together?",
  "Which form of staying in touch suited a particular friendship perfectly?",
  "What quality in an old companion helped you see the world differently?",
  "Which plan changed completely and became a better memory because of it?",
  "What did a friend remember about you that you had forgotten yourself?",
  "Which friendship crossed an age, background, or experience difference?",
  "What object, phrase, or place became shorthand between you and someone else?",
  "Which companion made waiting or traveling locally more enjoyable?",
  "What shared project revealed an unexpected side of a friend?",
  "Which casual acquaintance became important through a series of small moments?",
  "What habit did you pick up from someone whose company you enjoyed?",
  "Which old friendship could resume its rhythm after a long gap?",
  "What did you once exchange with friends instead of buying for yourselves?",
  "Which group had its own vocabulary, rules, or recurring debate?",

  "What saying from family or chosen family still slips into your speech?",
  "Which story was told differently depending on who was telling it?",
  "What practical knowledge traveled through your circle without being written down?",
  "Which household expression would require translation for an outsider?",
  "What ordinary tradition helped people feel connected across time?",
  "Which story about your younger self did others remember better than you did?",
  "What role did you naturally take when your close circle gathered?",
  "Which object moved between people and gathered stories along the way?",
  "What skill or taste links you to someone from another generation?",
  "Which familiar story gained a new meaning when you heard another perspective?",
  "What form of welcome did people in your circle do especially well?",
  "Which playful disagreement returned at gatherings without causing harm?",
  "What custom was flexible enough for new people to make it their own?",
  "Which person's way of explaining things could make everyone listen?",
  "What did your close circle celebrate that the wider world might overlook?",
  "Which shared task gave different people a chance to contribute?",
  "What story reveals how humor works among people close to you?",
  "Which name, nickname, or term of affection carries a whole history?",
  "What tradition did your circle invent rather than inherit?",
  "Which lesson arrived through watching someone handle an ordinary situation?",

  "What was the first decision that made a new chapter feel like your own?",
  "Which quiet accomplishment changed how you saw your abilities?",
  "What beginning felt ordinary at the time but important in retrospect?",
  "Which new responsibility fit you more naturally than expected?",
  "What moment showed you that a skill had become second nature?",
  "Which personal change was first noticed by someone else?",
  "What did you choose to keep the same during a period of transition?",
  "Which turning point can be represented by one everyday object?",
  "What goal changed for the better while you were pursuing it?",
  "Which leap in confidence began with a very small action?",
  "What ending created space for an interest you had neglected?",
  "Which unfamiliar role eventually became part of your identity?",
  "What milestone mattered even without a certificate, title, or public recognition?",
  "Which useful risk taught you something about your own judgment?",
  "What did you once assume you would never learn to do?",
  "Which period of practice is hidden behind something you now do easily?",
  "What new beginning benefited from knowledge carried from an earlier chapter?",
  "Which personal boundary became clearer as you gained experience?",
  "What moment made you realize your definition of success had changed?",
  "Which milestone arrived gradually rather than on a single date?",

  "What everyday behavior once considered normal now feels like a time capsule?",
  "Which public courtesy has changed most noticeably during your lifetime?",
  "What word or phrase has taken on a different meaning since you first heard it?",
  "Which change in clothing or personal style surprised you by lasting?",
  "What activity moved from public spaces into private ones, or the reverse?",
  "Which old expectation has become easier to question over time?",
  "What local change reflected a much larger shift in society?",
  "Which once-unusual idea became ordinary within your lifetime?",
  "What kind of waiting has almost vanished from everyday experience?",
  "Which job, service, or public role is performed very differently now?",
  "What change in language has made conversation more inclusive?",
  "Which trend returned with a meaning different from its first appearance?",
  "What everyday choice offers more options now than it once did?",
  "Which social rule faded without anyone formally announcing its end?",
  "What place has changed its purpose as community needs evolved?",
  "Which improvement do you appreciate even while missing what it replaced?",
  "What prediction about the future turned out to overlook something important?",
  "Which cultural change became visible through small household habits?",
  "What form of creativity became easier to share with a wider audience?",
  "Which change in how people meet has altered first impressions?",

  "What skill can your hands remember even when your mind needs a moment?",
  "Which once-useful trick deserves to be taught again for the pleasure of it?",
  "What did you learn through repetition rather than explanation?",
  "Which skill depended on noticing subtle sounds, textures, or visual cues?",
  "What old technique produced results with very simple tools?",
  "Which ability became rusty but returned faster than expected?",
  "What task taught you the value of doing things in the right sequence?",
  "Which practical skill came with its own sayings or rules of thumb?",
  "What did you learn by watching from the edge before trying it yourself?",
  "Which skill was easier to learn alongside another person?",
  "What old method gave you a stronger sense of how something worked?",
  "Which ability once helped you solve a problem in an unintended way?",
  "What craft or technique made useful work feel creative?",
  "Which skill required patience that daily life rarely asks for now?",
  "What knowledge could you demonstrate more easily than describe?",
  "Which task once demanded careful estimation without precise instruments?",
  "What skill changed as materials or tools changed?",
  "Which forgotten pastime trained an ability you still use elsewhere?",
  "What technique carries the recognizable style of the person who taught you?",
  "Which old skill would be most enjoyable to practice with a beginner?",

  "Which memory has become funnier each time you have told it?",
  "What event do you remember differently after hearing another person's version?",
  "Which detail remains sharp while the rest of a memory has softened?",
  "What memory did a photograph, recording, or object unexpectedly revise?",
  "Which story from your past has grown shorter and clearer over time?",
  "What forgotten moment returned because of an unrelated sight or sound?",
  "Which memory seems to belong partly to you and partly to repeated retellings?",
  "What place do you remember at several ages layered together?",
  "Which old opinion of yours is easiest to understand when you recall its era?",
  "What memory changed after you revisited the setting where it happened?",
  "Which ordinary day became more meaningful only in hindsight?",
  "What do you remember through other people's reactions more than your own?",
  "Which memory has lost its timeline but kept its atmosphere?",
  "What story do you now tell with more kindness toward your earlier self?",
  "Which detail might your present imagination have added to an old scene?",
  "What memory became clearer when you tried to describe it aloud?",
  "Which past worry now appears smaller without seeming foolish?",
  "What moment has acquired a new interpretation as the world changed?",
  "Which memory do you trust because several senses seem to agree?",
  "What personal story means something different depending on your audience?",
] as const;
