export const LATE_NIGHT_FIRST_DATE_PROMPTS = [
  'What small thing made today better than expected?',
  'Which part of your day usually feels most like your own?',
  'What snack has your unwavering loyalty?',
  'How do you like to spend an hour with nothing scheduled?',
  'What kind of weather brings out your best mood?',
  'Which everyday sound do you find oddly satisfying?',
  'What is your ideal pace for a weekend morning?',
  'Which meal could you happily improvise without a recipe?',
  'What tiny convenience feels like a genuine luxury?',
  'Where do you most enjoy sitting in a room?',
  'What is something ordinary you look forward to?',
  'Which season suits your personality best?',
  'What guides your choice when you put on music, a podcast, or silence?',
  'What scent instantly improves a space for you?',
  'Which simple ritual helps you shift out of a busy day?',
  'What kind of place makes you want to linger?',
  'How do you prefer to start a day with no obligations?',
  'What food combination do you think deserves more appreciation?',
  'Which routine chore is unexpectedly pleasant for you?',
  'What does a pleasantly uneventful evening look like to you?',
  'Which view could hold your attention for a long time?',
  'What is your favorite reason to step outside?',
  'How do you make a familiar space feel refreshed?',
  'What is the best thing to find in a waiting room?',
  'Which drink feels most connected to a particular mood?',
  'What do you enjoy doing slowly?',
  'Which part of getting ready do you find most satisfying?',
  'What background noise helps you settle in?',
  'What signals that an ordinary day used your time well?',
  'What is one everyday choice you enjoy taking seriously?',
  'Which song can reset the atmosphere in seconds?',
  'What kind of story keeps you up past your intended bedtime?',
  'Which fictional setting would be fun to visit for one afternoon?',
  'What topic can send you into an enthusiastic tangent?',
  'How do you discover new music, books, shows, or games?',
  'What creative skill would you enjoy trying badly at first?',
  'Which piece of art has stayed in your mind lately?',
  'What kind of puzzle or problem is fun for you to solve?',
  'Which hobby makes time disappear fastest?',
  'What is something you love learning just for its own sake?',
  'How do you choose between revisiting a favorite and trying something new?',
  'Which live event has an atmosphere you enjoy?',
  'What would your personal museum have a room dedicated to?',
  'Which character do you appreciate more as you get older?',
  'What subject would you happily hear a passionate amateur explain?',
  'How do you like to participate when music is playing?',
  'What is the most interesting object you have noticed recently?',
  'Which kind of performance impresses you most?',
  'What have you made that gave you quiet satisfaction?',
  'Which format tells a story best for you?',
  'What interest of yours surprises people who are just meeting you?',
  'How would you spend a free admission ticket to anything?',
  'Which unfinished project still feels inviting rather than guilty?',
  'What is a niche subject you could explore for an entire evening?',
  'Which familiar story would you retell from another character’s viewpoint?',
  'What do you notice first in a song?',
  'How do you know when something has earned a place among your favorites?',
  'What activity brings out your playful side?',
  'Which type of collection fascinates you, even if you do not collect it?',
  'What would you name a playlist for this chapter of your life?',
  'What harmless opinion could you defend with unnecessary passion?',
  'Which animal would make the most entertaining neighbor?',
  'What is your favorite kind of accidental comedy?',
  'How would your closest people describe your sense of humor?',
  'Which minor inconvenience turns you into a dramatic narrator?',
  'Which harmless mix-up still makes you laugh when you remember it?',
  'Which made-up award could you realistically win?',
  'What mundane event deserves dramatic theme music?',
  'How do you react when a joke lands terribly?',
  'Which word is funnier than it has any right to be?',
  'What would be an excellent name for a very unimpressive boat?',
  'Which everyday object seems to have a personality?',
  'What is your preferred role in a group joke?',
  'How would you improve a boring waiting line?',
  'Which tiny mistake makes a story better afterward?',
  'What imaginary competition would you love to judge?',
  'Which fashion trend from any era would be funniest at breakfast?',
  'What would your warning label say on a low-energy day?',
  'Which serious activity becomes funny when done by a group?',
  'What is the most creative excuse you have heard for being late?',
  'How would you entertain a room using only items on a table?',
  'Which movie title could double as a description of your week?',
  'What is a ridiculous hill you are willing to reconsider?',
  'Which sound effect would improve your daily routine?',
  'What kind of humor makes you laugh before the punchline arrives?',
  'How would you title a documentary about your kitchen habits?',
  'What is the least intimidating thing that could be a mascot?',
  'Which social situation would benefit from an official referee?',
  'What would make a delightfully useless superpower?',
  'Which joke from someone you know still makes you smile?',
  'What helps you feel comfortable around someone new?',
  'How do you usually show that you are enjoying a conversation?',
  'What kind of question makes you feel genuinely seen?',
  'When you tell a story, do you favor the details or the destination?',
  'How do you prefer someone to disagree with you?',
  'On an early date, what shows that someone can take responsibility sincerely?',
  'When do you find silence companionable?',
  'How do you let people know you need time to think?',
  'What conversational habit do you deeply appreciate?',
  'How do you like good news to be celebrated?',
  'What helps you recover from an awkward moment with someone?',
  'When plans change, what kind of communication helps most?',
  'How do you prefer to receive a thoughtful suggestion?',
  'What tells you that someone is listening closely?',
  'How do you make space for a quieter person in a group?',
  'What is your natural way of checking in with people?',
  'When is a message better than a call for you?',
  'How do you tend to express appreciation?',
  'What makes feedback easier for you to hear?',
  'How would you signal that you want to change the subject?',
  'What pace of getting acquainted feels natural to you?',
  'How do you prefer to clear up a small misunderstanding?',
  'What helps a difficult conversation stay respectful?',
  'When you are excited, how does it show?',
  'What kind of reassurance feels useful rather than excessive?',
  'How do you balance asking questions with sharing about yourself?',
  'What makes a compliment feel meaningful to you?',
  'How do you know when it is time to pause a conversation?',
  'What does being direct look like without being unkind?',
  'Which communication difference can make people more interesting to each other?',
  'What quality do you admire in the people you trust?',
  'Which value shows up most clearly in your everyday choices?',
  'What does generosity mean beyond giving things?',
  'When have you changed your mind in a way you are glad about?',
  'What makes someone dependable in your eyes?',
  'Which matters more to you in a disagreement, being understood or finding a solution?',
  'What does fairness look like when two people need different things?',
  'How do you decide which commitments deserve a yes?',
  'What kind of courage do you notice in ordinary life?',
  'Which personal principle has become more nuanced over time?',
  'Where is the line between welcome curiosity and prying for you?',
  'How do you recognize kindness that is not performative?',
  'What responsibility do people have to the spaces they share?',
  'Which matters more in a promise, intention or follow-through?',
  'What helps you extend grace without ignoring a problem?',
  'How do you decide when tradition is worth keeping?',
  'What does loyalty allow room for?',
  'Which everyday choice can reveal a lot about a person’s values?',
  'What is one belief you try to practice instead of merely stating?',
  'How do you make a decision when two good values compete?',
  'What does respect sound like during disagreement?',
  'Which form of honesty requires the most care?',
  'What makes an act of help truly helpful?',
  'How do you think people earn another chance?',
  'What does accountability look like after a small mistake?',
  'Which quality matters more with time than it does at first glance?',
  'How do you distinguish confidence from certainty?',
  'What does it mean to be considerate without guessing someone’s needs?',
  'Which boundary can actually make connection easier?',
  'How do you hope people feel after spending time with you?',
  'What rhythm between activity and rest works well for you?',
  'How much spontaneity makes a plan more enjoyable?',
  'What does being on time mean to you in social situations?',
  'How do you like to divide attention between company and your phone?',
  'What kind of environment helps you recharge?',
  'How do you approach sharing food when tastes differ?',
  'What makes a home feel welcoming to you?',
  'How much advance notice do you enjoy for plans?',
  'What place does routine have in your ideal week?',
  'How do you like to handle a day when your energy changes?',
  'What is your favorite way to mark the end of a week?',
  'How do you decide whether to join a crowded event?',
  'What role does movement play in a good day for you?',
  'How do you prefer to spend time alongside someone without talking much?',
  'What makes hosting or being hosted enjoyable for you?',
  'How tidy does a shared space need to feel comfortable?',
  'What is your relationship with last-minute invitations?',
  'How do you protect time for the things that restore you?',
  'What sort of outing feels worth dressing up for?',
  'How do you like to make decisions about shared plans?',
  'What is an everyday luxury that costs little or nothing?',
  'How do you respond when you need more rest than expected?',
  'What kind of social calendar feels balanced to you?',
  'How do you make room for both structure and surprise?',
  'What is one household task best improved by company?',
  'How do you feel about doing separate activities in the same space?',
  'What helps you shift between focused time and social time?',
  'How would you design an evening for two people with different energy levels?',
  'What does a comfortable amount of personal space look like to you?',
  'Which daily habit contributes most to your sense of balance?',
  'What kind of gathering brings out your most social self?',
  'How do you like to contribute when people come together?',
  'What makes you feel connected to a neighborhood or community?',
  'Which local place plays an important role in bringing people together?',
  'How do you maintain friendships when life gets busy?',
  'What do you appreciate about having friends with different perspectives?',
  'Which shared activity makes conversation easier for you?',
  'How do you welcome someone who is new to a group?',
  'What type of invitation feels especially thoughtful?',
  'How do you prefer to support someone celebrating an achievement?',
  'Which shared ritual helps a group keep its sense of connection?',
  'Which community effort would you enjoy contributing time or creativity to?',
  'How do you stay connected with people who live far away?',
  'What do you value in a friendship that has lasted through change?',
  'How do you know when a social space is inclusive?',
  'What is a kind thing a stranger once did that you still remember?',
  'How do you navigate being the new person in a room?',
  'What makes a shared celebration feel personal?',
  'Which public space would you love to see more of?',
  'How do you decide when to offer advice and when to simply listen?',
  'What sort of teamwork brings out your strengths?',
  'How do you show up for people without overextending yourself?',
  'What have you learned from belonging to a group?',
  'Which custom from your family or community feels meaningful to you?',
  'How can people make everyday spaces friendlier?',
  'What do you enjoy sharing with the people in your life?',
  'How do you handle competing invitations from people you care about?',
  'What makes you feel remembered between conversations?',
  'Which kind of community event would you be excited to help create?',
  'How do you express care when words are not quite enough?',
  'What makes a friendship feel easy without being taken for granted?',
  'What would you enjoy becoming more confident at?',
  'Which possibility are you quietly excited about these days?',
  'What would make the next year feel meaningful to you?',
  'How do you keep a hope alive while staying flexible about the outcome?',
  'What is something you would like to understand more deeply?',
  'Which future version of an ordinary day sounds appealing?',
  'What kind of challenge feels energizing rather than draining?',
  'How do you celebrate progress before reaching the finish line?',
  'What would you try if being impressive were irrelevant?',
  'Which skill would make your days more interesting?',
  'What do you want to make more room for in your life?',
  'How do you choose goals that actually belong to you?',
  'What is one experience you hope to create close to home?',
  'Which curiosity would you follow with unlimited library access?',
  'What kind of impact would feel meaningful on a small scale?',
  'How do you want your relationship with time to evolve?',
  'What project would be satisfying even if nobody applauded it?',
  'Which part of your life would you like to approach more playfully?',
  'What would a season of healthy growth look like for you?',
  'How do you stay open to plans turning into something different?',
  'What are you learning to enjoy without needing to master it?',
  'Which ordinary moment do you hope your future includes often?',
  'What would you like to be known for among the people close to you?',
  'How do you imagine making space for future interests you cannot predict?',
  'What is a hopeful change you have noticed in yourself?',
  'Which dream feels better when broken into tiny steps?',
  'What would make your surroundings feel more like the life you want?',
  'How do you tell the difference between persistence and forcing a path?',
  'What kind of encouragement helps you keep going?',
  'Which question about the future feels exciting rather than urgent?',
  'What does a considerate first date feel like to you?',
  'How do you prefer to decide whether to meet again?',
  'What balance of planning and improvising works when sharing an outing?',
  'How important is it for two people to enjoy the same hobbies?',
  'What differences between people can make a connection richer?',
  'How do you like to handle it when two appetites or preferences do not match?',
  'What does mutual effort look like early in getting to know someone?',
  'How do you prefer to discuss the cost of a shared activity?',
  'What makes a plan feel collaborative instead of assumed?',
  'How do you like someone to check your comfort with a change of venue?',
  'What does respecting someone’s pace look like in practice?',
  'How much contact between meetups feels comfortable to you?',
  'What makes interest feel clear without becoming pressure?',
  'How do you prefer to respond when chemistry is uncertain?',
  'What is a gracious way to handle different expectations?',
  'How do you feel about friendly debate when getting acquainted?',
  'What can two people learn from planning one simple activity together?',
  'How do you prefer to navigate a food preference that others do not share?',
  'What makes a compromise feel fair to both people?',
  'How can someone show enthusiasm while still leaving room for a no?',
  'What is worth clarifying instead of guessing about?',
  'If circumstances make you late, what update feels considerate?',
  'What signs tell you an outing has a comfortable pace?',
  'How do you prefer to end an evening when you have enjoyed it?',
  'What makes a follow-up message feel thoughtful?',
  'How do you approach making plans when schedules are unpredictable?',
  'What kind of shared decision reveals good teamwork?',
  'How can people make room for different social energy?',
  'What does privacy mean while two people are getting acquainted?',
  'Which early compatibility question deserves a relaxed conversation rather than a quick verdict?',
  'What recent choice taught you something useful about yourself?',
  'In what ways does a good life look different to you now?',
  'Which compliment have you grown into believing?',
  'What are you better at noticing now than you were a few years ago?',
  'How do you recognize when you are being true to yourself?',
  'What has become easier since you stopped trying to do it perfectly?',
  'What does feeling grounded mean in your own experience?',
  'How have your priorities surprised you as they changed?',
  'What is something you now approach with more patience?',
  'Which lesson did you learn from an ordinary moment?',
  'How do you make peace with a decision that had no perfect option?',
  'What helps you notice when you need a reset?',
  'Which assumption about yourself have you happily outgrown?',
  'What does self-respect look like on a difficult day?',
  'Where can ambition and contentment coexist in your life?',
  'What have you become more willing to ask for?',
  'Which quality in yourself appears most when someone else needs support?',
  'How do you respond when your first impression turns out to be incomplete?',
  'What ordinary experience has shaped your perspective more than expected?',
  'Which choice has made your life feel more like your own?',
  'How do you know when you have learned enough from a mistake?',
  'What has taught you to be gentler with yourself?',
  'Which uncertainty are you comfortable leaving unresolved?',
  'What has made confidence feel more authentic to you over time?',
  'What is something you appreciate more because it is temporary?',
  'How do you stay curious about someone as they change?',
  'Which part of growing older feels unexpectedly freeing?',
  'What would you want tonight’s version of you to remember?',
  'What question are you glad we made time for?',
] as const
