export const LATE_NIGHT_PARTY_PROMPTS = [
  'What tiny victory deserves a dramatic celebration tonight?',
  'Which ordinary skill would you compete in at a neighborhood championship?',
  'What harmless opinion could you defend with suspicious intensity?',
  'Which sound instantly changes the mood of a room for you?',
  'What snack disappears fastest when you are sharing with a group?',
  'Which everyday object would make the funniest award trophy?',
  'What is your favorite way to turn waiting time into fun?',
  'Which smell would you put in a welcome-home candle?',
  'What small inconvenience brings out your most creative problem-solving?',
  'Which part of the day has the best personality?',
  'What compliment has stayed with you longer than expected?',
  'Which made-up holiday would you add to the calendar?',
  'What is a very specific thing you are surprisingly good at noticing?',
  'Which simple pleasure would you happily review like a serious critic?',
  'What would your entrance music communicate before you said a word?',
  'Which household task has the strongest case for becoming a sport?',
  'What piece of everyday advice actually works for you?',
  'Which minor rule would improve every shared kitchen?',
  'What low-stakes mystery from daily life would you love solved?',
  'Which fictional job sounds enjoyable until you think about the paperwork?',
  'What is the best surprise you can create with almost no planning?',
  'Which weather deserves better publicity?',
  'What object near you could inspire the title of a comedy?',
  'Which routine feels completely different when done at night?',
  'What is a satisfying sound that deserves its own fan club?',
  'Which unnecessary invention would still improve your week?',
  'What phrase would be a terrible slogan for a relaxing spa?',
  'Which everyday decision takes you far longer than it should?',
  'What would make a five-minute break feel legendary?',
  'Which boring errand could use a red-carpet entrance?',

  'What song would you choose to start a room-wide singalong?',
  'Which instrument seems most likely to steal the spotlight?',
  'What music belongs in the soundtrack to making breakfast?',
  'Which song title could also be the name of a restaurant?',
  'What kind of music helps you feel instantly more awake?',
  'Which musical era would throw the most unforgettable party?',
  'What is your ideal first song for a long group playlist?',
  'Which non-musical sound could become a great beat?',
  'What song do you appreciate more because of where you first heard it?',
  'Which musical collaboration would be wonderfully unexpected?',
  'What makes a chorus impossible not to join?',
  'Which music video concept would you enjoy directing?',
  'What song would make a funny soundtrack for doing something extremely ordinary?',
  'Which genre would you use to retell a familiar bedtime story?',
  'What concert detail matters most besides the performers?',
  'Which voice do you find compelling even when you do not know the words?',
  'What track would you place over the closing credits of today?',
  'Which song has an opening that grabs your attention immediately?',
  'What makes a group playlist feel like everyone belongs in it?',
  'Which tune would you want a doorbell to play just once?',
  'What music would suit a slow-motion walk into a grocery store?',
  'Which artist would you trust to score a nature documentary?',
  'What is the funniest possible theme for a concept album?',
  'Which song could unite people who disagree about nearly everything else?',
  'What musical sound feels most like nighttime?',
  'Which familiar song would be transformed by a completely different tempo?',
  'What makes you decide a new song belongs on repeat?',
  'Which imaginary band name should someone actually use?',
  'What type of dance floor song gets even reluctant dancers moving in their own way?',
  'Which three moods should tonight\'s playlist move through?',

  'What food has the best contrast of textures?',
  'Which meal becomes better when everyone helps assemble it?',
  'What flavor combination sounds odd but deserves a fair chance?',
  'Which food would you appoint as the official snack of late-night conversations?',
  'What dish tells a story about a place or community you know?',
  'Which ingredient tends to improve whatever it joins?',
  'What is the most important quality of a celebration cake?',
  'Which food would be hardest to eat while giving a serious speech?',
  'What meal can make an unremarkable day feel special?',
  'Which snack should come with a warning that sharing is difficult?',
  'What dish would you name after the mood it creates?',
  'Which breakfast food deserves a place at every hour?',
  'What is a food rule you happily ignore?',
  'Which aroma can make a whole room feel welcoming?',
  'What ingredient would be the star of your imaginary food festival?',
  'Which food is improved most by eating it outdoors?',
  'What would you serve at a party themed around one color?',
  'Which menu item is often judged by the wrong standard?',
  'What food would make the most chaotic mascot?',
  'Which cooking shortcut deserves more respect?',
  'Which detail beyond the food turns a shared meal into a great gathering?',
  'Which dish would you want to learn from someone who makes it with care?',
  'What is your ideal combination of crunchy, soft, sweet, or savory?',
  'Which food would win a contest based only on its name?',
  'What late-night bite tastes best when it is unexpectedly available?',
  'Which common ingredient would you remove from the spotlight for a year?',
  'What should every build-your-own food bar include?',
  'Which meal has the greatest range from humble to fancy?',
  'What food-related debate can stay friendly but never be settled?',
  'Which imaginary restaurant would this group open together?',

  'What story from childhood still makes you laugh for a reason others can understand?',
  'Which small misunderstanding became a great story later?',
  'What is the most memorable thing you have seen happen in a queue?',
  'Which chance encounter brightened an otherwise normal day?',
  'What harmless mistake taught you a useful shortcut?',
  'Which celebration had an unexpected detail you still remember?',
  'When has a simple plan turned into a minor adventure?',
  'Which moment made you realize someone had a hidden talent?',
  'What ordinary place has given you an unusually good memory?',
  'Which surprise kindness arrived at exactly the right time?',
  'What is the funniest confusion caused by similar names or words?',
  'Which object have you kept mainly because it carries a story?',
  'What moment made a stranger feel briefly like part of your team?',
  'Which failed recipe, project, or plan became entertaining anyway?',
  'How did unexpected weather once rewrite your plans?',
  'Which accidental tradition have you continued?',
  'What story proves that timing can change everything?',
  'Which event was much more enjoyable than you expected?',
  'What is a moment when a group solved a problem in a clever way?',
  'Which ordinary day would you replay just for its atmosphere?',
  'What is the best thing that happened because someone took a wrong turn?',
  'Which moment made you appreciate a familiar place differently?',
  'What is a story behind a nickname you are comfortable sharing?',
  'Which small act of teamwork felt oddly triumphant?',
  'When did improvising work better than your original idea?',
  'Which funny coincidence still seems statistically impossible?',
  'What moment taught you that people notice more than you think?',
  'Which memory comes with a particularly vivid soundtrack?',
  'What is a story about receiving unexpectedly useful advice?',
  'Which harmless moment made you feel like the main character of a film?',

  'If this room became a tiny country, what would its first public service be?',
  'What would clouds discuss if they held meetings?',
  'If you could add one friendly feature to the moon, what would it be?',
  'What would a museum dedicated to tomorrow display?',
  'If animals reviewed human habits, which habit would confuse them most?',
  'What job would exist in a city designed entirely around naps?',
  'If every door made a sound effect, which sound would you choose for yours?',
  'What would be the first challenge on a game show for time travelers?',
  'If your week were a board game, what special square would today be?',
  'What could make a haunted house charming instead of frightening?',
  'If plants could vote on home design, what would they demand?',
  'What would an alien guest misunderstand about a birthday party?',
  'If laughter could power one machine, which machine should it run?',
  'What unusual class would belong in a school for superheroes on their days off?',
  'If every street had a theme song, what should determine the music?',
  'What would you put in a time capsule meant to puzzle the future?',
  'If shadows had hobbies, what would they do after sunset?',
  'What feature belongs in the perfect imaginary treehouse for adults?',
  'If dreams had customer reviews, what would earn five stars?',
  'What would a friendly ghost contribute to a shared home?',
  'If you could rename one color, what name would fit it better?',
  'What would be the mascot of a city devoted to good conversations?',
  'If elevators offered surprise destinations, what safe option should appear?',
  'What would you expect to find at the edge of an imaginary map?',
  'If your favorite chair could talk, what stories would it tell?',
  'How might neighbors celebrate on a planet with two sunsets?',
  'If silence had different flavors, what would peaceful silence taste like?',
  'What would a detective investigate in a world where nothing goes missing?',
  'If one everyday object could give excellent advice, which would you consult?',
  'What would make an imaginary village famous in the best possible way?',

  'Is it better for a party to begin quietly or arrive at full energy?',
  'Should a great story be allowed one harmless exaggeration?',
  'Which matters more in a snack, flavor or convenience?',
  'Would you rather know a little about many topics or a lot about one?',
  'Is a surprise better when clues were hiding in plain sight?',
  'Should playlists follow a clear theme or embrace joyful chaos?',
  'Which is more satisfying, finding a shortcut or mastering the long way?',
  'Would an extra hour be better added to the morning or the evening?',
  'Is it more fun to host an event or simply arrive?',
  'Should every group project have an official snack coordinator?',
  'Which improves a room more, excellent lighting or excellent music?',
  'Would you choose a perfect memory or a perfect imagination?',
  'Is friendly competition more about winning or creating a good story?',
  'Should a menu offer many choices or a few brilliant ones?',
  'Which is the stronger social skill, asking questions or telling stories?',
  'Would you prefer a reliable plan or a promising mystery?',
  'Is a familiar favorite more appealing than a clever surprise?',
  'Should celebrations have a clear ending or fade out naturally?',
  'Which is more revealing, someone\'s bookshelf or their snack shelf?',
  'Would you rather design the invitation or choose the entertainment?',
  'Is anticipation part of the fun or an obstacle to it?',
  'Should fictional villains be judged partly on their sense of style?',
  'Which deserves more credit, a strong beginning or a satisfying ending?',
  'Would you rather always find a seat or always find the shortest line?',
  'Is it better to be the person with a plan or the person with a backup?',
  'Should weekends feel different from weekdays even when routines stay the same?',
  'Which creates better conversation, agreement or gentle disagreement?',
  'Would you pick a useful superpower or a spectacularly entertaining one?',
  'Is a shared joke funnier because of the history behind it?',
  'Should the last piece of shared food be claimed or divided?',

  'What tradition from any community do you admire for bringing people together?',
  'Which art form can cross language barriers most easily?',
  'What custom would you enjoy learning through respectful participation?',
  'Which local saying carries more wisdom than it first appears to?',
  'What kind of public celebration makes a place feel alive?',
  'Which craft reveals the most patience from its maker?',
  'What cultural exchange becomes richer when people ask thoughtful questions?',
  'Which type of clothing can tell the most interesting story about its making?',
  'What community space helps different generations connect?',
  'Which form of storytelling deserves more attention?',
  'What can a greeting reveal about the values of a community?',
  'Which festival element creates the strongest sense of welcome?',
  'What language feature do you find especially expressive?',
  'Which handmade object can carry the spirit of a place?',
  'What makes learning the history behind a tradition worthwhile?',
  'Which public artwork would improve the mood of your neighborhood?',
  'What is a respectful way to show curiosity about an unfamiliar custom?',
  'Which kind of performance is most powerful with a live audience?',
  'What shared ritual can turn a group of strangers into a community?',
  'Which story should every neighborhood collect about itself?',
  'What makes a borrowed tradition feel appreciative rather than careless?',
  'Which celebration detail best helps newcomers feel included?',
  'What everyday object varies fascinatingly across different places?',
  'Which old-fashioned social custom could be thoughtfully reinvented?',
  'What can people learn about one another by exchanging favorite sayings?',
  'Which kind of market best captures the character of a community?',
  'What tradition would you create to welcome someone new?',
  'Which kind of public gathering encourages the best people-watching?',
  'What cultural skill is best learned by watching an expert?',
  'Which shared creative project could represent many backgrounds at once?',

  'Who in this group would invent the most useful fictional gadget?',
  'What title would fit a documentary about tonight\'s gathering?',
  'Which two answers heard tonight would make an interesting mash-up?',
  'What positive quality does this group bring out in people?',
  'Which imaginary team uniform would everyone here actually consider wearing?',
  'What question should the group answer using only sound effects?',
  'Which shared category could everyone name one favorite from?',
  'What could this group create in ten minutes using only ideas?',
  'Which person here might narrate an excellent nature documentary?',
  'What would be a fitting name for this group\'s imaginary café?',
  'Which two people might choose surprisingly similar theme songs?',
  'What harmless topic could split the room into lively teams?',
  'Which group member would be great at naming a new product?',
  'What sentence could everyone complete differently for a funny result?',
  'Which skill represented in this room would help during a power outage?',
  'What is one thing the group seems to appreciate in common?',
  'Which imaginary award category could include everyone as a nominee?',
  'What could the group rank from delightful to overrated without getting personal?',
  'Which everyday problem could this room probably solve together?',
  'What word best captures the current energy, and why?',
  'Which person here might design the cleverest secret passage?',
  'What kind of event could this group host exceptionally well?',
  'Which shared answer would make the best name for a band?',
  'What is one new thing the group has discovered about itself tonight?',
  'Which imaginary mission would suit everyone\'s combined talents?',
  'What theme could inspire a one-minute round of rapid ideas?',
  'Which answer from the group deserves a dramatic callback later?',
  'What could everyone contribute to a fictional neighborhood guide?',
  'Which group decision would be funniest to settle by applause?',
  'What closing question would leave this gathering on a high note?',

  'What hobby looks enjoyable even if you have never tried it?',
  'Which skill would be fun to learn badly, with no pressure to improve?',
  'What topic can send you into an enthusiastic explanation?',
  'Which creative activity helps time disappear for you?',
  'What pastime would benefit from a more exciting name?',
  'Which collection would be fascinating even with only three items?',
  'What could you teach in a relaxed ten-minute workshop?',
  'Which hobby produces the best gifts for other people?',
  'What activity rewards curiosity more than natural talent?',
  'Which craft would you like to watch being made from start to finish?',
  'What is the most interesting rabbit hole you have explored lately?',
  'Which game mechanic makes almost any game more fun?',
  'What would you enjoy building if materials and mistakes were free?',
  'Which interest of yours surprised people who know you?',
  'What activity is more social than it first appears?',
  'Which subject would you explore in a club with no homework?',
  'What kind of puzzle gives the most satisfying final moment?',
  'Which skill improves through play more than formal practice?',
  'What hobby could turn an empty afternoon into an event?',
  'Which everyday material has the most creative possibilities?',
  'What interest would you revisit with a beginner\'s mindset?',
  'Which activity makes collaboration easier than conversation alone?',
  'What is something you enjoy making more than owning?',
  'Which hobby has the most welcoming community you have encountered?',
  'What could become a fun obsession for exactly one weekend?',
  'Which creative constraint tends to produce better ideas?',
  'What project would be satisfying even if nobody else saw it?',
  'Which pastime works equally well alone and with company?',
  'What would your ideal community class teach?',
  'Which forgotten interest might still be waiting for your return?',

  'What quality makes someone easy to include in a conversation?',
  'Which form of encouragement feels most genuine to you?',
  'What does a thoughtful host notice before anyone asks?',
  'Which small gesture can make a new person feel welcome?',
  'What kind of humor brings people together without making anyone the target?',
  'Which question helps you understand how another person thinks?',
  'What makes a disagreement feel productive instead of tense?',
  'Which sign tells you a group is really listening?',
  'What is a generous way to make room for a quieter voice?',
  'Which shared experience can build connection surprisingly quickly?',
  'What makes an apology feel sincere without becoming dramatic?',
  'Which kind of curiosity creates trust?',
  'What is a good way to celebrate someone else\'s enthusiasm?',
  'Which conversational habit makes stories easier to tell?',
  'What helps people feel comfortable saying they see things differently?',
  'Which strength in another person do you enjoy learning from?',
  'Which recurring group ritual would you be excited to help continue?',
  'Which low-pressure invitation is hardest to resist?',
  'What is one way people can disagree and still feel like a team?',
  'Which kind of attention feels like a meaningful gift?',
  'What makes someone memorable after a brief conversation?',
  'Which group norm can turn awkwardness into ease?',
  'What is a sign that people are enjoying themselves without saying it?',
  'Which social skill deserves to be taught more often?',
  'When can a quiet pause make a gathering feel more connected?',
  'Which simple question can rescue a stalled conversation?',
  'What does it look like when a group makes space for different energy levels?',
  'Which kind of welcome would you remember long afterward?',
  'What can transform a collection of people into a real gathering?',
  'Which feeling would you like everyone to carry away from tonight?',
] as const
