export const LATE_NIGHT_FAMILY_PROMPTS = [
  // Daily life
  'What part of today would you keep if you could save one moment?',
  'Which ordinary task feels more satisfying than it probably should?',
  'What has been taking up the most space in your thoughts lately?',
  'When during the day do you usually have the most energy?',
  'What small comfort have you been especially grateful for this week?',
  'Which sound belongs in the background of a peaceful evening for you?',
  'What is something simple that made you smile recently?',
  'How can you tell when you have had enough activity for one day?',
  'What part of your routine would you gladly make more playful?',
  'Which everyday choice do you enjoy having complete freedom over?',
  'What kind of weather best matches your mood tonight?',
  'Where do you naturally settle when you want to feel comfortable?',
  'What is one thing you noticed today that others may have missed?',
  'Which meal or snack feels dependable when nothing else sounds right?',
  'What helps a busy day feel less rushed for you?',
  'If this week had a color, which one would it be?',
  'What part of tomorrow could use a little encouragement?',
  'Which tiny inconvenience have you learned to handle surprisingly well?',
  'What makes an ordinary night feel special without much planning?',
  'What would make the rest of this evening feel just right?',

  // Family stories
  'Which story about this family always seems to gain a new detail?',
  'What is an early memory of realizing someone was looking out for you?',
  'Which family member or chosen relative would make a fascinating book character?',
  'What household from your past do you remember most vividly?',
  'When did a family plan go wrong in a way that later became funny?',
  'What object has traveled through your family or community with a story attached?',
  'Which memory helps explain how you became the person you are?',
  'What family story would you like to hear from another point of view?',
  'Who in your wider family circle has lived a life you want to know more about?',
  'What is a moment when people in this family surprised one another?',
  'Which story from before you were born has shaped how you see the family?',
  'What place from your family history can you picture even if you never saw it?',
  'When have relatives or chosen family made a difficult situation more manageable?',
  'What memory captures someone’s personality better than a description could?',
  'Which old photograph would you most like to step inside for five minutes?',
  'What chapter of your own story do you think the family knows least about?',
  'How did two people in your family circle first come to matter to each other?',
  'What story deserves to be told with more kindness than it usually receives?',
  'Which family memory feels different to you now than it did at the time?',
  'What recent moment might become a story people retell years from now?',

  // Traditions and shared rituals
  'Which repeated family ritual feels meaningful because of its smallest details?',
  'What tradition have you adapted to fit who you are now?',
  'Which celebration feels most welcoming to you, and what creates that feeling?',
  'What shared ritual could happen on an ordinary day instead of a holiday?',
  'Which food tradition carries a story beyond the recipe itself?',
  'What custom from another household have you happily made your own?',
  'If we invented a yearly family day, what would everyone be invited to do?',
  'Which tradition would you keep even if you changed everything around it?',
  'What ritual helps you mark an ending or a new beginning?',
  'How could a familiar gathering better accommodate different needs?',
  'What tradition are you curious about but have never fully understood?',
  'Which seasonal habit makes time feel grounded for you?',
  'What is worth recording about the way our family does things?',
  'When has letting go of a custom created space for something better?',
  'What music, game, or activity can turn a gathering into an occasion?',
  'Which personal ritual would you enjoy sharing with the family someday?',
  'What tradition matters less for its origin than for what it offers now?',
  'How should families decide when a tradition needs to evolve?',
  'What simple welcome could become our signature for new people?',
  'Which future milestone deserves a ritual that does not exist yet?',

  // Appreciation
  'What quiet contribution by someone here deserves to be noticed?',
  'Which quality in this group makes hard moments a little easier?',
  'When did someone in the family recently make you feel considered?',
  'What have you learned to appreciate about a person as both of you changed?',
  'Who has a way of making everyday moments more interesting?',
  'What form of care do you notice even when nobody names it?',
  'Which difference between family members has turned out to be useful?',
  'What is something this family has helped you believe about yourself?',
  'When have you felt proud to be connected to someone in this circle?',
  'Whose patience has taught you something about how to treat people?',
  'What is a strength someone here may not realize they bring to the group?',
  'Which shared memory makes you grateful that your paths crossed?',
  'What kind gesture from years ago do you still carry with you?',
  'How has someone in your family welcomed a way you are different?',
  'What do you admire about the way another person handles change?',
  'Which family member has introduced you to something you now value?',
  'What do you hope people here never doubt about their importance to you?',
  'When has being known by this family felt like a gift?',
  'What is one thank-you that would be meaningful to say while there is time?',
  'Which part of our connection feels stronger than it did a year ago?',

  // Humor and lightness
  'What is the most family-specific joke that would confuse an outsider?',
  'Who here would be the funniest narrator of a nature documentary?',
  'Which harmless family habit could inspire a comedy scene?',
  'What ridiculous disagreement from the past can everyone laugh about now?',
  'If this family ran a tiny shop, what would we sell badly?',
  'Which person here has the most recognizable reaction face?',
  'What accidental phrase became part of the family vocabulary?',
  'If everyone swapped daily roles for an hour, what would go wrong first?',
  'What is a moment when laughter rescued an otherwise awkward situation?',
  'Which family talent would earn the strangest trophy?',
  'What imaginary warning label would suit our group gatherings?',
  'Who could turn a short errand into the longest story?',
  'What ordinary object has caused an unreasonable amount of family drama?',
  'If our family had a mascot, what should it be and why?',
  'Which memory still makes you laugh before you can explain it?',
  'What would be the least intimidating family superpower?',
  'If tonight were an episode title, what would it be called?',
  'Which made-up competition would someone here definitely win?',
  'What is the funniest compliment you could sincerely give this group?',
  'How would you describe our family’s sense of humor to someone new?',

  // Learning across generations
  'What skill from a different generation would you genuinely like to learn?',
  'Which piece of once-common knowledge should not be allowed to disappear?',
  'What newer idea has made you rethink something you were taught earlier?',
  'How has the meaning of growing up changed during your lifetime?',
  'What can younger people notice that older people sometimes overlook?',
  'What can people with more years of experience see that beginners may miss?',
  'Which outdated expectation are you glad people can question now?',
  'What everyday technology would be hardest to explain to your younger self?',
  'Which lesson arrived at an age you did not expect?',
  'What would you ask someone who experienced your current age in another era?',
  'How do you decide whether old advice still deserves a place in your life?',
  'What have you learned from someone much younger or older than you?',
  'Which change in language has helped people understand one another better?',
  'What ability do you think every generation underestimates in another?',
  'When has curiosity helped bridge an age difference for you?',
  'What story about your generation do you wish were less simplistic?',
  'Which lesson is best passed through doing rather than explaining?',
  'What question should people ask before giving advice across generations?',
  'How might our different ages help us solve the same problem?',
  'What wisdom do you hope keeps changing instead of becoming fixed?',

  // Belonging and identity
  'What helps you know that you belong in a family space?',
  'When do you feel most free to be fully yourself around other people?',
  'Which part of who you are has taken time for others to understand?',
  'What does the word family include for you today?',
  'Who has made belonging feel possible without asking you to earn it?',
  'What signals tell you that a group is genuinely welcoming?',
  'Which part of your identity feels especially alive in this season?',
  'How can family members honor differences they do not personally share?',
  'What name, role, or label feels important for others to use correctly?',
  'Where have you found community in an unexpected place?',
  'What makes a home feel like yours even when you do not own it?',
  'Which side of yourself appears only when you feel accepted?',
  'How has your idea of fitting in changed over time?',
  'What would help a new person feel included without being put on display?',
  'Which connection in your life proves that family can be chosen?',
  'What do you wish people understood about the communities you value?',
  'When have you felt included through someone’s actions rather than words?',
  'What part of your background do you enjoy sharing when people are curious?',
  'How can we make room for someone whose experience differs from the majority?',
  'What does being claimed with love, rather than controlled, mean to you?',

  // Support and care
  'How do you prefer someone to check in when you seem overwhelmed?',
  'What kind of practical help makes the biggest difference on a hard day?',
  'When you share a problem, how can someone tell whether you want ideas or listening?',
  'Which signs show that you are ready to receive support?',
  'What makes an offer of help feel respectful instead of intrusive?',
  'Who taught you that care can look different from fixing?',
  'What is an easy way family members can lighten one another’s load?',
  'How do you like people to celebrate with you when something goes well?',
  'What support is easier for you to give than to accept?',
  'When has someone stayed beside you without needing the perfect words?',
  'What can we do to make asking for help feel more ordinary?',
  'Which caring gesture works for you only when someone asks first?',
  'How would you want the family to respond if you needed extra quiet or space?',
  'What reminder helps you feel less alone when life is uncertain?',
  'Which kind of encouragement feels believable to you?',
  'What shared responsibility could be distributed more fairly?',
  'How can someone support you while still trusting your choices?',
  'What does dependable care look like in small, repeatable actions?',
  'When is company more helpful to you than conversation?',
  'What would help us notice one another’s needs without making assumptions?',

  // Boundaries and autonomy
  'What is a respectful way for someone to accept that you do not want to answer?',
  'How do you signal that you need a pause before continuing a conversation?',
  'Which boundary helps you show up more generously for family?',
  'What personal choice do you wish people trusted you to make for yourself?',
  'How can relatives express concern without taking over?',
  'What topic deserves an invitation before it becomes group conversation?',
  'When does advice feel welcome, and when does it feel like pressure?',
  'What does privacy mean to you within a close relationship?',
  'How should someone respond after crossing a boundary by mistake?',
  'Which expectations are reasonable to renegotiate as people grow?',
  'What helps a firm no still feel caring?',
  'How can this family respect different needs for contact and closeness?',
  'What is one way to disagree without questioning someone’s loyalty?',
  'When do you need time alone before you can reconnect well?',
  'What family role would you like more freedom to step outside?',
  'How can people ask personal questions without acting entitled to answers?',
  'Which limit protects something important in your life right now?',
  'What would make it easier to say that a joke has gone too far?',
  'How do you want others to handle information you share in confidence?',
  'What is a boundary you now understand better than you once did?',

  // Change and transitions
  'Which recent change has affected you in ways others might not see?',
  'What helps you stay grounded when familiar routines disappear?',
  'How has your place in the family shifted as you have grown?',
  'What transition are you still learning how to name?',
  'Which ending eventually opened a door you could not see at first?',
  'How do you prefer loved ones to acknowledge a change that feels complicated?',
  'What part of an earlier version of your life do you want to carry forward?',
  'When have you adapted more bravely than you gave yourself credit for?',
  'What has changed in this family that you are still making sense of?',
  'Which new beginning felt real only after a small moment?',
  'How can a family remain connected when everyone’s lives move differently?',
  'What have you discovered about yourself during an uncertain period?',
  'Which change are you relieved happened, even if it was difficult?',
  'What deserves patience while you adjust to life as it is now?',
  'How do you know when it is time to update an old expectation?',
  'What would you like others to understand about your current season?',
  'Which part of change feels harder for you: beginning, waiting, or letting go?',
  'What family strength has survived more than one transition?',
  'How could we better mark changes that do not come with ceremonies?',
  'What possibility has appeared because something else changed?',

  // Conflict and repair
  'What helps you feel safe enough to revisit a disagreement?',
  'How can someone show they understand your impact without defending their intent?',
  'Which part of an apology matters most to you after words have caused harm?',
  'What makes a conversation feel like repair rather than another argument?',
  'When is writing a message easier than speaking face to face?',
  'How do you know whether a conflict needs time, clarity, or action?',
  'What would respectful disagreement look like in this family at its best?',
  'Which habits help keep one mistake from defining a whole person?',
  'How can we address an old hurt without demanding that anyone relive every detail?',
  'What helps you listen when you initially feel misunderstood?',
  'When have changed actions meant more to you than repeated promises?',
  'What is a fair way to return to a conversation after taking a break?',
  'How can family members respect two different memories of the same event?',
  'What kind of acknowledgment helps you begin to rebuild trust?',
  'Which conflicts are eased when people name the need underneath them?',
  'How do you want someone to raise a concern about your behavior?',
  'What does taking responsibility sound like without turning into self-punishment?',
  'When is acceptance of an unresolved difference a healthy outcome?',
  'What small repair could prevent distance from becoming permanent?',
  'How might we recognize progress without pretending everything is fixed?',

  // Values and meaning
  'Which value becomes clearest in the choices you make when nobody is watching?',
  'What principle have you kept even after changing your mind about many things?',
  'How do you decide what deserves your time and attention?',
  'Which belief did you examine before choosing it for yourself?',
  'What does a meaningful life look like without using achievements as the measure?',
  'When have compassion and fairness seemed to ask different things of you?',
  'What responsibility do family members have to one another, if any?',
  'Which everyday action best reflects the person you want to be?',
  'How do you make space for uncertainty in what you believe?',
  'What matters to you more now than it did several years ago?',
  'Which value do you hope people feel from you before they hear you name it?',
  'What makes a sacrifice feel worthwhile rather than expected?',
  'How has someone with a different worldview sharpened your own thinking?',
  'What does generosity mean when money is not involved?',
  'Which kind of courage receives too little recognition?',
  'How do you tell the difference between loyalty and avoiding necessary truth?',
  'What do you hope remains nonnegotiable in the way we treat one another?',
  'When has changing your position been a sign of integrity?',
  'What does respect require when understanding is incomplete?',
  'Which question guides you when there is no clearly right choice?',

  // Hopes and possibilities
  'What are you quietly looking forward to, even if it is not guaranteed?',
  'Which part of the future feels open in an encouraging way?',
  'What would you love for this family to experience more often together?',
  'How do you hope your days feel a year from now?',
  'What skill or quality are you interested in growing next?',
  'Which possibility would you explore if you could start very small?',
  'What everyday burden do you hope future generations carry less often?',
  'How might this family become a steadier source of joy?',
  'What dream feels worth sharing even before it has a plan?',
  'Which future memory would you like us to create on purpose?',
  'What kind of home or community do you hope to help shape?',
  'How would you like your relationships to deepen over the coming years?',
  'What are you becoming more ready to try?',
  'Which hope has stayed with you through more than one life chapter?',
  'What would progress look like if it did not have to be dramatic?',
  'How can the people here make room for one another’s ambitions?',
  'What do you hope we will laugh about when we look back on this time?',
  'Which shared project could bring out the best in this group?',
  'What future change would you like to meet with curiosity instead of fear?',
  'What is one reason you feel hopeful about the people gathered here?',

  // Mutual understanding
  'What do people who care about you sometimes misunderstand about your silence?',
  'Which question would help someone see your current life more clearly?',
  'How do you usually show affection when words do not come easily?',
  'What assumption about you would you like family members to reconsider?',
  'When do you feel most carefully listened to?',
  'Which part of your decision-making process is invisible to others?',
  'What does being taken seriously look like to you?',
  'How can someone stay curious when your answer surprises them?',
  'What do you wish others knew about the effort behind something you do?',
  'Which difference between us would you like to understand with more nuance?',
  'What helps you explain yourself without feeling that you are on trial?',
  'How do you want family members to respond when your needs change?',
  'What have you recently understood about someone here that you missed before?',
  'Which of your choices makes more sense when people know the context?',
  'What form of recognition makes you feel genuinely seen?',
  'How can we ask about one another’s lives without keeping score?',
  'What would you like more permission to be honest about?',
  'Which part of your experience deserves curiosity rather than comparison?',
  'What could we learn by listening to the person who speaks least often?',
  'How would our relationships change if we checked our assumptions sooner?',

  // Legacy and continued connection
  'What story about your life would you want told with care rather than polish?',
  'Which ordinary way of loving people do you hope others continue?',
  'What lesson would you offer as an invitation instead of a rule?',
  'How would you like this family to remember the way you made people feel?',
  'What healthy family pattern are you proud to carry forward?',
  'Which inherited habit would you feel relieved to leave behind?',
  'What knowledge, recipe, craft, or practice would you enjoy passing along?',
  'How can we preserve memories without insisting everyone remembers them alike?',
  'What would you put in a family time capsule for people not yet in our lives?',
  'Which relationship would you like to tend more intentionally from now on?',
  'What do you hope remains true about us even as the group changes?',
  'How might we keep absent or distant loved ones present in respectful ways?',
  'What promise to one another feels realistic enough to keep?',
  'Which unfinished conversation would benefit from a gentler next chapter?',
  'What do you want future members of this family to feel welcomed into?',
  'How could we celebrate one another before a major occasion gives us a reason?',
  'What is worth making time for while we are together now?',
  'Which part of our shared story are we still writing?',
  'What would caring for this family connection look like in daily practice?',
  'After tonight, what is one thing you hope we understand better about each other?',
] as const
