export const LATE_NIGHT_COUPLES_PROMPTS = [
  // Settle in: affectionate, everyday connection
  'What part of today would you enjoy telling me about slowly?',
  'Where did you find a little ease today?',
  'What ordinary thing have we made feel special together?',
  'Which version of us shows up when we are completely unhurried?',
  'What has been taking up more of your inner world than I might realize?',
  'When lately have you wanted a few extra minutes with me?',
  'What small ritual between us would you miss sooner than expected?',
  'Which sound, scent, or sight has felt comforting to you this week?',
  'How could we make one routine moment feel more like ours?',
  'What kind of quiet feels connecting to you?',
  'Where do you notice tenderness in our everyday life?',
  'What helps you shift from handling the day to being present with me?',
  'Which recent moment made you think of me when I was not there?',
  'What would make tomorrow morning a little softer for you?',
  'When do we make the best team without even discussing it?',
  'What tiny pleasure would you like us to share more often?',
  'Which part of your current routine feels most like you?',
  'What is one thing your mind could happily set down tonight?',
  'After we have both been occupied, what helps us reconnect?',
  'What detail about this season of our life do you want to remember?',
  'Which everyday task becomes better when we do it side by side?',
  'What has made you smile privately lately?',
  'When does time with me feel most spacious?',
  'What is one gentle thing we could do for each other this week?',
  'Which shared comfort have we perfected?',
  'How can I tell when you are ready to relax?',
  'What recent conversation between us stayed with you in a good way?',
  'Where in our daily rhythm do you feel especially supported?',
  'What would your ideal low-energy evening together include?',
  'Where in your life could you use more lightness right now?',

  // Shared memories and relationship story
  'What early impression of me makes you laugh now?',
  'Which memory shows how far we have come as a pair?',
  'When did our connection first begin to feel dependable to you?',
  'What forgotten moment between us deserves to be retold?',
  'Which chapter of our relationship had the best soundtrack?',
  'What did we once do often that you would enjoy bringing back?',
  'When have we turned an inconvenient situation into a favorite story?',
  'Which past version of us would be most surprised by who we are now?',
  'What memory captures our particular kind of humor?',
  'When did you first notice that I understood something important about you?',
  'Which shared milestone mattered to you for reasons I may not know?',
  'What choice did we make together that quietly shaped us?',
  'Which memory of being welcomed by me feels vivid?',
  'What period in our story taught us the most about partnership?',
  'When have you felt pleasantly surprised by how we handled something?',
  'What place from our shared history still carries a feeling for you?',
  'Which of our inside jokes has the best origin story?',
  'What is a memory of us that becomes sweeter with time?',
  'When did we last feel like we were discovering something together?',
  'Which change in our relationship are you most grateful we embraced?',
  'What is one of your favorite memories of us doing almost nothing?',
  'Which hard-won moment of ours deserves more celebration?',
  'When did you see a new side of me that you came to love?',
  'What have we learned to do better since our earliest days?',
  'Which shared story do you hope we are still telling years from now?',
  'What memory reminds you that we can adapt together?',
  'When have we felt most like co-conspirators in something harmless?',
  'Which spontaneous decision gave us more than we expected?',
  'What did we misunderstand about each other at first?',
  'Which ordinary day in our past now feels quietly significant?',

  // Appreciation and being seen
  'What quality in me has become more valuable to you over time?',
  'When do you feel most appreciated by me without words?',
  'What effort of mine would you like me to know you notice?',
  'Which strength do you think I sometimes overlook in myself?',
  'What do I bring to your life that is difficult to put into words?',
  'When have you recently felt proud to be connected with me?',
  'What part of your personality feels especially welcomed by me?',
  'Which way I care for others makes you admire me?',
  'What have I taught you simply by being myself?',
  'In which moments is my delight in you easiest to feel?',
  'What is something about you that you wish received more recognition?',
  'Which compliment from me has stayed with you?',
  'What do you value about the way we make decisions together?',
  'When have I helped you feel more capable?',
  'What tenderness in you do you trust me to notice?',
  'Which difference between us has become something you appreciate?',
  'What is one way our relationship has made room for you to grow?',
  'When do my actions make you feel chosen?',
  'What contribution do you make to us that you feel proud of?',
  'Where does our bond feel unlike any other connection?',
  'What do you appreciate about how I move through a difficult day?',
  'When have you felt especially accepted by me?',
  'What is a subtle way you show love that you hope I recognize?',
  'Which of my quirks has become unexpectedly dear to you?',
  'What about our connection helps you feel more at home in yourself?',
  'When has my confidence in you made a difference?',
  'What form of gratitude lands most deeply for you?',
  'Which way have we influenced each other for the better?',
  'What do you think we bring out in each other that others may not see?',
  'How would you like us to celebrate the care we already give?',

  // Communication and emotional fluency
  'What helps you feel listened to when your thoughts are still forming?',
  'When you need empathy more than ideas, what response serves you best?',
  'What tells you that a conversation is emotionally safe?',
  'When is it easiest for you to name what you need?',
  'How do you prefer to signal that you need time before answering?',
  'What kind of check-in feels caring rather than intrusive?',
  'Which topic becomes easier to discuss when we are not rushed?',
  'How can we make space for answers that change over time?',
  'What helps you stay curious when we see something differently?',
  'In what moments do you feel free to be uncertain with me?',
  'What would help us notice a misunderstanding earlier?',
  'How do you like affection to show up during a serious conversation?',
  'What makes feedback feel respectful to you?',
  'Which feelings are easiest for you to show through actions?',
  'How can I better recognize when you want company instead of conversation?',
  'What pace helps you talk about something tender?',
  'When words are difficult, what other form of connection helps?',
  'What question from me usually helps you understand yourself?',
  'What is a caring way to handle a topic one of us is not ready to explore?',
  'What does a satisfying check-in sound like after a long day?',
  'Which assumptions would be useful for us to verify more often?',
  'How can we invite honesty without making an answer feel demanded?',
  'What helps you believe that your perspective has been understood?',
  'When would you rather receive a direct question than a hint?',
  'What conversational habit would you like us to practice together?',
  'How do you distinguish needing reassurance from needing information?',
  'What lets you know it is okay to revise something you said?',
  'Which kind of pause improves a conversation for you?',
  'How can we protect room for humor without avoiding what matters?',
  'What would make our everyday communication feel even more generous?',

  // Inner worlds and mutual understanding
  'What part of yourself are you getting to know differently these days?',
  'Which value has become clearer to you recently?',
  'What are you quietly making peace with?',
  'In which situations do your choices feel most aligned with who you are?',
  'What complexity about you do you hope I always leave room for?',
  'Which expectation are you reconsidering in this season?',
  'What gives you a sense of dignity when life feels messy?',
  'How has your idea of belonging evolved?',
  'What kind of courage are you practicing lately?',
  'Which part of adulthood feels different from what you imagined?',
  'What do you wish people understood about the way you recharge?',
  'Where do you feel closest to your background or chosen communities?',
  'What personal contradiction have you learned to accept?',
  'Which belief of yours was shaped by experience rather than instruction?',
  'What are you learning about your own limits?',
  'How does your inner voice sound when it is being kind to you?',
  'What is currently giving your life a sense of meaning?',
  'Which emotion has been visiting you more often lately?',
  'What do you want me to stay curious about as you change?',
  'What circumstances give you the greatest permission to be fully yourself?',
  'What are you proud to understand about yourself now?',
  'Which part of your story feels newly important?',
  'What helps you hold onto hope during an uncertain stretch?',
  'How have your ideas about partnership been reshaped by us?',
  'What do you need in order to feel spacious rather than stretched?',
  'Which private dream deserves a little more daylight?',
  'What does emotional rest look like for you?',
  'When have you recently trusted your own judgment?',
  'What aspect of your identity would you enjoy expressing more freely?',
  'How can I remain a good student of who you are becoming?',

  // Future hopes without fixed assumptions
  'What feeling would you like the next chapter of us to have?',
  'Which possibility for our future makes you feel quietly excited?',
  'What would growing well together mean to you?',
  'How might we protect our connection during a busier season?',
  'What new tradition could fit the people we are now?',
  'Which shared skill would be satisfying for us to develop?',
  'What do you hope becomes easier between us with time?',
  'In what direction could our support for each other evolve?',
  'What kind of community would you like around our relationship?',
  'Which future challenge do you believe we could meet thoughtfully?',
  'What adventure can you imagine that does not require going anywhere?',
  'How do you hope we keep surprising each other?',
  'What would make the coming year feel rich in connection?',
  'From our current life, what would you most like to carry forward?',
  'What shared project might reveal a new side of us?',
  'How could we leave more room for spontaneity in our future?',
  'What do you hope we will laugh about when we look back on now?',
  'Which dream of yours would you like me to understand more fully?',
  'What balance between togetherness and independence feels worth nurturing?',
  'How would you like us to mark meaningful transitions?',
  'What might a brave choice for us look like someday?',
  'Which kind of ordinary future moment are you eager to experience with me?',
  'Which aspect of us should we keep from becoming automatic?',
  'How can we keep making room for each other’s changing priorities?',
  'What would a season of flourishing look like for both of us?',
  'Which shared value do you want our future choices to reflect?',
  'What are you curious to learn about us over the next few years?',
  'How might we encourage each other without steering each other?',
  'What future version of our relationship already feels possible?',
  'Which hope would feel good to hold together without turning it into a plan?',

  // Affection, closeness, and non-explicit intimacy
  'What kind of affection helps you feel grounded with me?',
  'When does closeness feel most natural between us?',
  'What way of asking before affection feels natural to you?',
  'What atmosphere helps you feel open to tenderness?',
  'Which form of nonverbal warmth means the most to you?',
  'What helps you feel connected when physical affection is not what you want?',
  'How can we make saying not now feel easy and cared for?',
  'What helps my care reach you on a vulnerable day?',
  'What kind of compliment makes you feel warmly noticed?',
  'Which affectionate moment between us would you happily replay?',
  'How does your desire for closeness change when you are stressed?',
  'What helps a romantic moment feel genuine rather than expected?',
  'Which small gesture creates a spark of connection for you?',
  'What sort of comfort check preserves the mood for you?',
  'What makes a moment feel intimate to you even without touch?',
  'When do you most enjoy being playful and affectionate with me?',
  'What boundary helps tenderness feel safer or freer?',
  'How can we better honor different levels of energy for closeness?',
  'Which words help you receive affection when you feel self-conscious?',
  'What does being emotionally near to me feel like in your body?',
  'How would you describe the warmth you want between us lately?',
  'What kind of setting makes it easier to focus entirely on each other?',
  'When does anticipation add sweetness to our connection?',
  'What helps you trust that affection comes without obligation?',
  'Which cozy experience would you like us to create soon?',
  'Where could initiation and invitation each have more room between us?',
  'What makes you feel attractive in a way that is yours to define?',
  'Which kind of loving attention feels restorative?',
  'How has your understanding of intimacy changed during our relationship?',
  'What would help our affectionate life feel more intentional right now?',

  // Repair, resilience, and care during strain
  'What helps you believe we are on the same side during tension?',
  'How can I approach you gently when something feels unresolved?',
  'What makes an apology feel complete enough to move forward?',
  'When do you need space after a disagreement, and how should we reconnect?',
  'Which repair attempt from me is easiest for you to recognize?',
  'What would help us disagree without questioning the whole relationship?',
  'How do you want us to respond when one of us becomes overwhelmed?',
  'What have we recovered from that gives you confidence in us?',
  'Which conflict pattern are we getting better at interrupting?',
  'How can we separate a mistake from the person who made it?',
  'What does taking responsibility sound like to you?',
  'When is reassurance useful during a hard conversation?',
  'What helps you return to warmth after feeling hurt?',
  'What words could help us name tension before it builds?',
  'Which shared agreement could make difficult talks more respectful?',
  'What have our disagreements taught you about what matters to me?',
  'How can we handle imperfect timing with more grace?',
  'What helps you hear my intention without dismissing the impact?',
  'When has a sincere course correction strengthened your trust in me?',
  'What would make it safer to tell me I have misunderstood you?',
  'How do you prefer to revisit a conversation that ended too soon?',
  'Which kind of language helps you stay engaged instead of defensive?',
  'What can we do when both of us want to be understood first?',
  'What is a blameless way for us to acknowledge recurring friction?',
  'What does forgiveness mean when change is still in progress?',
  'When should we pause a conversation rather than push through it?',
  'What have you learned about repairing trust in small moments?',
  'How can we show care even while holding different views?',
  'Which past repair are you glad we took seriously?',
  'What promise about handling hard moments feels realistic and meaningful?',

  // Play, imagination, and delight
  'If our relationship had a secret mascot, what would it be?',
  'Which ridiculous challenge would we be surprisingly good at as a duo?',
  'What imaginary award would you give us this month?',
  'If we could borrow one fictional home for an evening, which would you choose?',
  'What harmless rule would make our next week more entertaining?',
  'Which of us would be better at hosting a very strange game show?',
  'What would the blooper reel of our relationship feature?',
  'If tonight needed a theme song, what mood should it capture?',
  'Which made-up holiday would suit us perfectly?',
  'What tiny competition could we invent using things already around us?',
  'If our inside jokes formed a language, which phrase would be essential?',
  'What would we name a café designed around our personalities?',
  'Which ordinary errand could we turn into a playful date?',
  'If we traded one harmless habit for a day, which swap would be funniest?',
  'What absurd luxury would delight us if practicality did not matter?',
  'Which two-person costume would capture our dynamic?',
  'If we narrated our evening like a nature documentary, what would happen?',
  'What is the silliest new tradition we could genuinely maintain?',
  'Which object nearby best represents our week together?',
  'If we designed a board game about us, how would someone win?',
  'What low-stakes mystery would you enjoy solving with me?',
  'Which meal could we reinvent with an unreasonable amount of ceremony?',
  'If our laughter had a color, what would it look like?',
  'What would our duo be famous for in an alternate universe?',
  'Which childhood form of fun should we try in our own way?',
  'If we had a catchphrase for handling chaos, what should it be?',
  'What playful dare would make both of us feel comfortable and amused?',
  'Which imaginary creature would make an excellent companion for us?',
  'If we opened a tiny museum of our relationship, what would its oddest exhibit be?',
  'What could we do for ten minutes that would make tonight more memorable?',

  // Deepening trust and ending with warmth
  'What truth about love has our relationship helped you discover?',
  'What helps you safely let me see your uncertainty?',
  'What responsibility to our connection do you choose willingly?',
  'Which part of being known by me feels most meaningful?',
  'What do you trust us to find our way through?',
  'How can I love you well when you are changing faster than usual?',
  'What kind of honesty strengthens closeness for you?',
  'When has our relationship given you room to be more courageous?',
  'While you are having trouble explaining yourself, what should I remember?',
  'Which shared principle makes our bond feel steady?',
  'What does mutual care ask of us in this chapter?',
  'How can we better protect each other’s sense of autonomy?',
  'What have you risked sharing with me that you are glad I know?',
  'In which moments do our differences expand us rather than divide us?',
  'What kind of presence from me helps you face something difficult?',
  'Where has careful tending made our connection stronger?',
  'What does loyalty mean to you beyond staying?',
  'What kind of room should we make for grief or disappointment?',
  'What helps you receive care when your instinct is to manage alone?',
  'When have we made each other feel less alone in the world?',
  'What do you want us to keep choosing deliberately?',
  'Which fear becomes smaller when you can speak it with me?',
  'How can we honor what is private while still building trust?',
  'What might our relationship offer the people around us at its best?',
  'In what situations do we most clearly meet each other as equals?',
  'What have we built emotionally that you want to protect?',
  'Which question about us feels worth returning to every year?',
  'How can we keep making affection visible during ordinary weeks?',
  'What are you grateful we can say to each other now?',
  'What would you like the final feeling of tonight’s conversation to be?',
] as const
