export const LATE_NIGHT_FRIENDS_PROMPTS = [
  'What small moment from today deserves a little more appreciation?',
  'What has been taking up the most space in your mind lately?',
  'Which part of your current routine feels surprisingly good?',
  'What is something ordinary you have enjoyed more than usual this week?',
  'When did you last feel completely unhurried?',
  'What kind of conversation have you been craving recently?',
  'Which sound, smell, or sight has lifted your mood lately?',
  'What are you quietly looking forward to right now?',
  'What has felt easier for you than it did a month ago?',
  'Which recent choice are you glad you made?',
  'What is one thing you wish today had included?',
  'Where does your attention naturally go when you finally get a quiet moment?',
  'What has made you laugh when you did not expect to?',
  'What is your favorite way to let a busy day loosen its grip?',
  'What tiny inconvenience has become a running joke in your life?',
  'Which part of the day tends to feel most like your own?',
  'What is something you noticed recently that others may have missed?',
  'Which recent moment would you gladly replay for five minutes?',
  'What is currently giving you more energy than it takes?',
  'What have you been meaning to make time for?',
  'Which simple comfort reliably helps you settle?',
  'What is one question you wish people asked you more often?',
  'What has pleasantly surprised you about this season of your life?',
  'What recent interaction left you feeling lighter?',
  'What is something you are learning to enjoy slowly?',
  'Which part of your week would make the best short story?',
  'What feels worth staying awake a little longer to talk about?',

  'What is an early memory of us that still makes you smile?',
  'Which ordinary hangout of ours became more memorable than expected?',
  'When have we laughed so hard that the original joke stopped mattering?',
  'What detail from a shared day do you remember unusually clearly?',
  'Which version of us from the past would be most surprised by us now?',
  'What is a moment when our friendship first felt easy?',
  'Which shared mistake turned into a story worth keeping?',
  'What phase of our friendship had its own special atmosphere?',
  'When did we make a boring situation genuinely fun?',
  'What is something we used to talk about constantly?',
  'Which place do you associate with a good conversation we had?',
  'What old plan of ours still sounds delightful?',
  'Which shared memory feels different to you now than it did then?',
  'What did we once take very seriously that now seems funny?',
  'When have you seen me most absorbed in the moment?',
  'What is a small kindness between us that you still remember?',
  'What shared moment deserves a dramatic movie trailer?',
  'If one of our memories became a holiday, how would we celebrate it?',
  'Which past conversation do you think quietly shaped our friendship?',
  'What is the most unexpected setting in which we have had a meaningful talk?',
  'Which memory proves that we can find fun without much of a plan?',
  'What have we introduced each other to that became part of daily life?',
  'When did our different reactions to the same event make you laugh?',
  'Which chapter of your life are you glad I got to witness?',
  'What is a shared memory you hope never gets polished into a simpler story?',
  'Which tiny tradition of ours would you like to revive?',
  'What memory of us feels especially comforting on a difficult day?',

  'If your week had a ridiculous title, what would it be?',
  'Which harmless opinion could you defend with absurd intensity?',
  'What imaginary award would you be a strong contender to win?',
  'If your mood were a low-budget mascot, what would it look like?',
  'What minor skill do you perform with completely undeserved confidence?',
  'Which object near you would make the worst motivational speaker?',
  'If tonight came with patch notes, what bug would they claim to have fixed?',
  'What would your most honest personal warning label say?',
  'Which everyday situation makes you feel like you are in a poorly written comedy?',
  'If your inner monologue had a guest narrator, whose style would suit it?',
  'Which shared misunderstanding became a favorite friendship story later?',
  'Which fictional job would you be impressively bad at?',
  'If we opened a deeply impractical business together, what would it sell?',
  'What completely unnecessary invention would improve your day?',
  'Which rule would exist in a country designed by your sleepy brain?',
  'What is your most theatrical reaction to a very small problem?',
  'If you could rename one common activity, what better name would you give it?',
  'Which animal seems most likely to hold a petty grudge?',
  'What would make an excellent plot for a two-minute mystery?',
  'If your current life had background music, what instrument would be overused?',
  'What is the least useful topic on which you could deliver a confident lecture?',
  'If our friendship had a secret handshake, what unnecessary flourish would it need?',
  'If you were a local legend, what harmless rumor would explain your fame?',
  'What mundane event would you narrate like a championship final?',
  'Which of your habits would confuse an archaeologist centuries from now?',
  'If tomorrow had a theme, what oddly specific theme should it have?',
  'What joke have you made that deserved a much better audience?',

  'What quality in a friend helps you feel at ease quickly?',
  'How do you usually show someone that you enjoy their company?',
  'What kind of invitation makes you feel genuinely included?',
  'When you care about someone, what do you tend to remember about them?',
  'How can a friend tell when you need company rather than advice?',
  'What makes time together feel meaningful to you?',
  'Which friendship ritual matters more to you than it might appear?',
  'How do you like friends to celebrate good news with you?',
  'What helps you trust that a friendship can survive busy periods?',
  'When do you feel most comfortable being quiet with someone?',
  'What does a low-pressure friendship look like to you?',
  'How do you prefer to reconnect after not speaking for a while?',
  'Which differences between friends make a bond more interesting?',
  'How do you know when an acquaintance has become a friend?',
  'What kind of honesty makes a friendship feel stronger?',
  'Which forms of care are easiest for you to receive?',
  'What do you value about friendships that leave room for independence?',
  'What makes a group feel welcoming rather than merely friendly?',
  'When has someone made you feel remembered in a meaningful way?',
  'What do you hope friends understand about the way you communicate?',
  'How do you like to share space when neither person feels talkative?',
  'What helps a friendship feel mutual to you?',
  'Which kind of follow-up question tells you someone is truly listening?',
  'What do you appreciate about friends whose style differs from yours?',
  'What helps you stay connected when routines change?',
  'Which unspoken expectation in friendship is worth saying aloud?',
  'What makes you feel chosen as a friend without feeling claimed?',

  'What is something about me that you have come to appreciate over time?',
  'When have you felt especially understood by me?',
  'What strength do you think I sometimes overlook in myself?',
  'Which part of our friendship feels most dependable?',
  'What have you learned from the way I approach life?',
  'When has my presence made a situation easier for you?',
  'What is one way our differences have helped you see something anew?',
  'Which side of you gets more room to appear around me?',
  'What do you think we bring out in each other?',
  'When have you been proud to call me your friend?',
  'What is something I do that makes our conversations feel safe?',
  'What kind of moment makes you think I would understand?',
  'How has our friendship made your world a little broader?',
  'What do you hope I never stop bringing to this friendship?',
  'What is a way I have supported you that I may not have noticed?',
  'When do you feel most free to be yourself with me?',
  'What do you admire about how we have grown alongside each other?',
  'What is something you trust me to take seriously?',
  'How would you describe the particular kind of comfort our friendship offers?',
  'What is one thing you think we handle well together?',
  'Which shared value quietly holds our friendship together?',
  'What have I helped you remember about yourself?',
  'When has our friendship felt like a place to breathe?',
  'What is one way you feel seen by me?',
  'Which quality in our friendship would you want to protect during change?',
  'What part of your appreciation for me is hardest to put into words?',
  'What are you grateful we can talk about honestly?',

  'When you are having a hard time, what kind of first response helps most?',
  'How can a friend check in without making you feel watched?',
  'What tells you that someone is ready to hear the real answer?',
  'When would you rather receive practical help than encouragement?',
  'How do you signal that you need a lighter conversation?',
  'What makes advice feel respectful rather than intrusive?',
  'Which kinds of support are difficult for you to ask for?',
  'How would you like a friend to respond when they do not know what to say?',
  'What helps you feel accompanied without needing a problem to be solved?',
  'When does humor help you cope, and when does it get in the way?',
  'How can someone make room for your feelings without amplifying them?',
  'What is a helpful way to remind you that you are not alone?',
  'How do you prefer friends to follow up after a difficult conversation?',
  'When might a quiet gesture mean more than a detailed message?',
  'What do you need before you can accept help comfortably?',
  'How can friends support your decisions even when they would choose differently?',
  'What does being believed feel like in a conversation?',
  'How do you want someone to respond if you say you are not ready to talk?',
  'What form of encouragement feels sincere to you?',
  'When do you prefer a distraction over a deeper check-in?',
  'What would make it easier for you to say that your needs have changed?',
  'How can a friend notice your effort without praising the outcome?',
  'What does steady support look like during a long uncertain stretch?',
  'How do you distinguish helpful concern from unwanted pressure?',
  'What can friends do to make asking for support feel less risky?',
  'Which caring intention sometimes lands poorly for you?',
  'What promise of support feels realistic and meaningful?',

  'What boundary helps you show up more generously in friendship?',
  'How do you prefer someone to raise a sensitive topic with you?',
  'What helps a no feel respected without becoming a debate?',
  'When do you need advance notice before making social plans?',
  'What personal topic would you rather choose the timing for yourself?',
  'How do you like to handle invitations you cannot accept?',
  'What does comfortable space look like when you are overwhelmed?',
  'Which assumptions about availability can strain a friendship?',
  'How can someone ask permission before offering difficult feedback?',
  'What makes a boundary easier for you to communicate?',
  'When have clearer expectations improved one of your relationships?',
  'How would you want a friend to respond after crossing a line unintentionally?',
  'What is a respectful way to pause a conversation that feels too intense?',
  'How can closeness exist without access to every part of someone’s life?',
  'What helps you say no without feeling responsible for another person’s disappointment?',
  'How should friends handle information shared in confidence?',
  'When does a check-in start to feel like a demand for a reply?',
  'What do you need in order to revisit a topic you once declined?',
  'How can a group make it easy for anyone to opt out gracefully?',
  'What boundary do you understand better now than you once did?',
  'How do you want differences in energy or capacity to be handled?',
  'What does mutual consent look like in an emotionally deep conversation?',
  'When is it kindest to let a subject rest?',
  'How can friends be curious without treating each other like puzzles to solve?',
  'How do you balance openness with the right to keep something for yourself?',
  'What would help you correct someone without fearing awkwardness?',
  'Which boundary deserves more appreciation as a form of care?',

  'What change in yourself have your friends had to learn alongside you?',
  'Which part of growing older feels most different from what you imagined?',
  'What have you outgrown without needing to dislike it?',
  'When has a change of mind felt like progress rather than inconsistency?',
  'What are you becoming more selective about?',
  'Which old version of yourself deserves more compassion from you?',
  'What is changing in how you define a good day?',
  'When did you realize that a familiar role no longer fit?',
  'What are you learning to release without rushing the process?',
  'Which transition taught you something unexpected about friendship?',
  'What part of yourself feels newly visible?',
  'What belief have you softened without fully abandoning?',
  'Which change has made your life quieter in a welcome way?',
  'What do you hope remains recognizable about you through future changes?',
  'When have you felt between chapters rather than firmly in one?',
  'What new priority is asking for more room in your life?',
  'How do you want friends to respond when you reinvent part of your life?',
  'What have you become less willing to pretend about?',
  'Which uncertainty are you learning to carry more gently?',
  'What has recently made you reconsider where you belong?',
  'How has your way of making decisions evolved?',
  'What kind of growth is difficult for other people to notice?',
  'Which lesson arrived later than you wanted but at the right time?',
  'What are you allowing to matter more than it used to?',
  'How do you recognize when persistence should become redirection?',
  'What part of change feels hopeful even when it is uncomfortable?',
  'What does becoming more yourself mean at this point in your life?',

  'Where do you feel welcome before you have to prove anything?',
  'What helps you participate in a group without losing your individuality?',
  'When have you found belonging in an unexpected place?',
  'Which community value makes you want to contribute?',
  'What makes a space feel safe enough for honest disagreement?',
  'How do you know when people are making room for your whole perspective?',
  'What tradition helps you feel connected to something larger than yourself?',
  'Which part of your background do you wish friends understood with more nuance?',
  'What does inclusion look like in small, everyday behavior?',
  'When have you felt connected to people despite major differences?',
  'What helps you enter a new group at your own pace?',
  'Which shared activity creates connection without requiring constant conversation?',
  'How can friends make unfamiliar settings easier for one another?',
  'What makes you feel like a contributor rather than a guest?',
  'Where have you learned the most from people unlike you?',
  'What does it mean to belong without having to blend in?',
  'Which form of hospitality feels most genuine to you?',
  'How can a group notice who has not had room to speak?',
  'What helps you stay curious across cultural differences?',
  'When does shared silence create connection rather than exclusion?',
  'Which place, practice, or gathering gives you a sense of continuity?',
  'How do you want friends to approach customs they do not understand?',
  'What makes a community feel generous with second chances?',
  'How can belonging leave space for changing your mind?',
  'When do you feel most able to offer welcome to someone else?',
  'What would a truly accessible gathering feel like to you?',
  'Which connection in your life crosses an unexpected divide?',
  'What responsibility comes with making others feel they belong?',

  'What experience would you like us to create together in the next year?',
  'Which small plan would give us something joyful to anticipate?',
  'What skill could we learn side by side without caring who improves faster?',
  'How would you like our friendship to adapt as life changes?',
  'What future tradition could start with something simple?',
  'Which conversation should we make more time for going forward?',
  'What kind of project would be fun for us to finish together?',
  'How can we protect unstructured time in our friendship?',
  'What do you hope we will still find funny years from now?',
  'Which promise to our future selves feels both kind and achievable?',
  'What would an ideal ordinary day together include?',
  'How could we make our next shared plan easier for everyone involved?',
  'Which new ritual could help us stay connected during busy seasons?',
  'What do you want more of in the next chapter of our friendship?',
  'How might we celebrate progress without waiting for a major milestone?',
  'What future challenge do you think we could face well as friends?',
  'Which curiosity of yours would you like company in exploring?',
  'What would make our plans feel flexible rather than fragile?',
  'How can we keep making room for new versions of each other?',
  'What is one thing we could plan that costs little or nothing?',
  'Which shared goal would feel playful instead of pressuring?',
  'What do you hope we remember to ask each other next year?',
  'What could we build into our routines so connection relies less on perfect timing?',
  'Which future memory would you be delighted to accidentally create?',
  'What are you excited to witness in my life?',
  'How can we support each other’s hopes without turning them into obligations?',
  'What would help our friendship remain spacious as our worlds expand?',
  'When you picture us much later in life, what feels warmly familiar?',

  'What helps you believe a friendship can recover from a mistake?',
  'How do you prefer to begin a conversation about hurt feelings?',
  'In a friendship, which part of an apology helps trust return?',
  'When conflict happens, what helps you stay connected to the other person’s humanity?',
  'How much time do you usually need before revisiting a tense moment?',
  'What is the difference between an explanation and an excuse for you?',
  'How can someone take responsibility without making you comfort them?',
  'What helps you hear feedback without feeling reduced to one action?',
  'What does changed behavior communicate that words cannot?',
  'How would you like a friend to check whether a conflict truly feels resolved?',
  'What can make forgiveness feel pressured rather than freely chosen?',
  'How do you want misunderstandings to be handled before they grow?',
  'What helps you acknowledge impact when your intention was different?',
  'When has naming awkwardness made a conversation easier?',
  'What does a fair disagreement leave intact?',
  'What makes it possible for you to offer someone another chance?',
  'Which repair attempt tends to miss what you actually need?',
  'How do you know when a difficult conversation needs a pause rather than an ending?',
  'What would help you admit a mistake sooner?',
  'When should a friendship accept a lasting difference instead of seeking agreement?',
  'How can two people repair trust at a pace that respects both of them?',
  'What role should curiosity play when memories of an event do not match?',
  'How do you separate a recurring pattern from a single bad moment?',
  'What does accountability with compassion look like to you?',
  'When is letting go healthier than restoring a friendship?',
  'How can appreciation be expressed during a disagreement without avoiding the issue?',
  'What have past repairs taught you about the way you want to be treated?',
  'What conversation between us would make our friendship clearer or kinder?',
] as const
