/**
 * 300 independently authored Never Have I Ever experiences.
 * Wording is intentionally prefix-free because the card artwork supplies
 * “Never have I ever”. Topics span everyday mishaps, digital life, food,
 * school, work, travel, friendship, dating, courage, and harmless secrets.
 */
export const NEVER_HAVE_I_EVER_PROMPTS = [
  // Everyday mishaps
  'Locked myself out of my home.',
  'Worn a shirt inside out for hours without noticing.',
  'Walked into a glass door.',
  'Missed a step because I was looking at my phone.',
  'Left home and returned because I forgot why I went out.',
  'Burned a meal badly enough to set off an alarm.',
  'Used shampoo as body wash because the soap ran out.',
  'Put something in a safe place and never found it again.',
  'Slept through more than three alarms.',
  'Waved back at someone who was greeting a person behind me.',
  'Called someone by the wrong name throughout a conversation.',
  'Tried to open the wrong car in a parking lot.',
  'Spilled a drink on myself during an important moment.',
  'Pretended to understand directions and immediately got lost.',
  'Searched for my phone while holding it.',
  'Forgot a birthday until social media reminded me.',
  'Gone to a shop and forgotten the one item I needed.',
  'Put an empty container back in the fridge.',
  'Fallen asleep with the lights and television on.',
  'Broken something and quietly placed it back.',
  'Answered a question meant for somebody else.',
  'Worn mismatched shoes outside by accident.',
  'Tried to unlock my front door with the wrong key for too long.',
  'Dropped food and checked whether anyone saw before picking it up.',
  'Practised a facial expression before entering a room.',
  'Forgot where I parked and wandered around looking for the car.',
  'Left laundry in the washing machine overnight.',
  'Started cleaning one room and somehow made three rooms messier.',
  'Used a household object for a purpose it was never designed for.',
  'Nodded confidently while having no idea what was happening.',

  // Phones and online life
  'Accidentally liked a very old post while browsing someone’s profile.',
  'Sent a screenshot to the person shown in it.',
  'Deleted and rewrote a message more than five times.',
  'Read a message from the notification preview to avoid opening it.',
  'Pretended my battery died to end a conversation.',
  'Googled myself out of curiosity.',
  'Used a second account to view someone’s profile.',
  'Posted something mainly because one specific person might see it.',
  'Removed a post because it did not get enough attention.',
  'Taken more than twenty photos to choose one selfie.',
  'Joined an online argument and regretted it.',
  'Searched the internet for the meaning of a slang word.',
  'Watched an entire series because of one short online clip.',
  'Muted a group chat without telling anyone.',
  'Scrolled so long that I forgot what I originally opened the app to do.',
  'Used an old photo to make my day look more interesting.',
  'Checked whether someone viewed my story more than once.',
  'Looked up a person before meeting them for the first time.',
  'Recorded a voice note and deleted it without sending.',
  'Pretended not to see a call while watching it ring.',
  'Sent a message to the wrong group chat.',
  'Used a filter and wished I looked like the filtered version.',
  'Stayed awake much later than planned because of endless scrolling.',
  'Changed a caption after posting because I spotted a mistake.',
  'Unfollowed someone during an argument and followed them again later.',
  'Saved a meme specifically for one person.',
  'Used airplane mode to read a message without appearing online.',
  'Checked my screen-time report and felt personally attacked.',
  'Created a password and immediately forgot it.',
  'Taken a photo of food that went cold before I ate it.',

  // Food and drink
  'Eaten dessert before dinner.',
  'Ordered the same meal at a restaurant because choosing felt risky.',
  'Pretended to enjoy food somebody proudly cooked for me.',
  'Hidden my favourite snack so nobody else would eat it.',
  'Finished someone else’s leftovers without asking.',
  'Eaten directly from the cooking pot to avoid washing a plate.',
  'Combined two foods everyone else thought should stay separate.',
  'Burned my mouth because I refused to wait for food to cool.',
  'Gone back for another serving after saying I was full.',
  'Bought groceries while hungry and regretted the total.',
  'Made a meal based entirely on what was about to expire.',
  'Eaten breakfast food for dinner.',
  'Used a spoon because every clean fork was gone.',
  'Claimed I could cook something I had never attempted.',
  'Ordered takeaway while ingredients for the same meal sat at home.',
  'Judged a restaurant by its menu photos.',
  'Taken the largest slice and acted as if it happened accidentally.',
  'Eaten a snack in bed and woken up surrounded by crumbs.',
  'Tried a food challenge purely for bragging rights.',
  'Drunk straight from a shared carton when nobody was watching.',
  'Put hot sauce on food before tasting it.',
  'Saved the best part of a meal for the final bite.',
  'Travelled across town mainly to eat one particular dish.',
  'Called a meal homemade after using mostly packaged ingredients.',
  'Eaten something after its date because it still smelled fine.',
  'Asked for a bite and taken much more than expected.',
  'Recreated a recipe from a video and produced something unrecognisable.',
  'Said I did not want fries and then ate someone else’s.',
  'Chosen a restaurant because its lighting would look good in photos.',
  'Kept eating something painfully spicy to protect my pride.',

  // School and learning
  'Copied homework minutes before class.',
  'Pretended to read a book I only knew from the film.',
  'Raised my hand and forgotten my answer when called on.',
  'Used an unnecessarily large word to sound intelligent.',
  'Studied the wrong chapter for a test.',
  'Fallen asleep during a lesson or lecture.',
  'Submitted an assignment seconds before the deadline.',
  'Invented a technical problem to explain unfinished work.',
  'Skipped a class and unexpectedly met the teacher elsewhere.',
  'Been chosen for a presentation while completely unprepared.',
  'Guessed an answer and somehow got it right.',
  'Forgotten a classmate’s name after knowing them for months.',
  'Taken a course because a friend was taking it.',
  'Written notes I could not understand later.',
  'Used a calculator for a calculation I could have done mentally.',
  'Celebrated a cancelled class more than a holiday.',
  'Joined a group project and contributed at the last possible moment.',
  'Blamed a printer for something I had not finished.',
  'Read an entire page without absorbing a single sentence.',
  'Answered attendance for an absent friend.',
  'Carried a heavy textbook all day without opening it.',
  'Changed an answer from correct to incorrect during a test.',
  'Memorised information overnight and forgotten it immediately afterward.',
  'Used a teacher’s favourite phrase in an essay to impress them.',
  'Hidden in the back row to avoid being called on.',
  'Doodled through a lesson and kept the drawing.',
  'Received credit for a group project I barely understood.',
  'Practised a presentation repeatedly and still improvised most of it.',
  'Joined an extracurricular activity mainly for the free food.',
  'Looked at the clock so often that time seemed to move backwards.',

  // Work and ambition
  'Nodded through a meeting that could have been an email.',
  'Sent a work message and immediately noticed a typo.',
  'Taken a longer route to avoid an awkward colleague conversation.',
  'Pretended to be busy when somebody walked past my screen.',
  'Rehearsed a salary conversation and then lost my nerve.',
  'Applied for a job without meeting every listed requirement.',
  'Forgotten to unmute before speaking in an online meeting.',
  'Spoken while muted and wondered why nobody responded.',
  'Worn formal clothes above the waist and casual clothes below it.',
  'Counted down the minutes until the end of a shift.',
  'Used work time to plan a holiday.',
  'Taken credit for an idea only after everyone liked it.',
  'Agreed to a deadline before checking my workload.',
  'Written a polite email while feeling extremely annoyed.',
  'Practised pronouncing someone’s name before calling them.',
  'Started a new job and forgotten nearly every introduction.',
  'Made a mistake and hoped nobody would trace it back to me.',
  'Worked from bed while claiming to be at a desk.',
  'Stayed at a job mainly because I liked the people.',
  'Considered quitting after one particularly difficult day.',
  'Celebrated a small promotion more than I expected.',
  'Searched online for how to do part of my own job.',
  'Scheduled a message so it looked as if I was working earlier.',
  'Used office supplies for a personal project.',
  'Forgotten an attachment after writing “attached” in an email.',
  'Taken a sick day because I needed a mental break.',
  'Joined a meeting without knowing why I was invited.',
  'Accidentally replied to everyone instead of one person.',
  'Kept a browser tab open purely to look productive.',
  'Dreamed about work and felt cheated out of my free time.',

  // Travel and public adventures
  'Missed a flight, train, or bus through my own poor timing.',
  'Packed far too much for a short trip.',
  'Forgotten an essential item and bought it again while travelling.',
  'Taken a photo at a landmark without learning anything about it.',
  'Gotten lost after insisting I did not need directions.',
  'Fallen asleep on public transport and missed my stop.',
  'Visited somewhere mainly because I saw it online.',
  'Tried to speak a language using only memorised phrases.',
  'Pretended to understand a local custom I had just discovered.',
  'Brought home an impractical souvenir.',
  'Chosen the cheapest journey and regretted every hour of it.',
  'Arrived at an airport dramatically earlier than necessary.',
  'Run through a station carrying luggage.',
  'Used a map while secretly following someone who looked confident.',
  'Taken a wrong turn that led to something better than the plan.',
  'Stayed somewhere that looked very different from its photos.',
  'Made friends with a stranger while travelling.',
  'Tried unfamiliar food without knowing what I ordered.',
  'Spent more time photographing a view than looking at it.',
  'Returned from a holiday needing another holiday.',
  'Used the same clothes repeatedly despite packing many options.',
  'Lost track of which day it was while away.',
  'Cancelled an itinerary and had a better day because of it.',
  'Carried a passport around after no longer needing it.',
  'Slept somewhere uncomfortable to save money.',
  'Booked a trip before fully checking my bank balance.',
  'Visited the wrong platform, gate, or terminal.',
  'Sent someone regular updates so they knew I was safe.',
  'Learned a useful phrase only after leaving the country.',
  'Promised to return to a place and genuinely meant it.',

  // Friendship and social life
  'Cancelled plans and then felt left out when everyone had fun.',
  'Made a friend because we disliked the same thing.',
  'Kept a friend’s secret for years.',
  'Forgotten how I originally met a close friend.',
  'Laughed harder because a friend was laughing.',
  'Created a group chat that became unexpectedly chaotic.',
  'Borrowed something from a friend and forgotten to return it.',
  'Defended a friend before hearing the full story.',
  'Helped a friend compose a difficult message.',
  'Pretended to be someone’s partner to discourage unwanted attention.',
  'Travelled a long distance to support a friend.',
  'Ended a friendship without a proper conversation.',
  'Reconnected with someone after years apart.',
  'Felt jealous when a close friend made a new friend.',
  'Shared an inside joke at a completely inappropriate moment.',
  'Covered for a friend when they were late.',
  'Given advice I was not following myself.',
  'Known a friendship was ending before either person said it.',
  'Stayed awake all night talking with a friend.',
  'Planned a surprise that almost got discovered.',
  'Been the only person who remembered an important detail about a friend.',
  'Apologised first even though I still thought I was right.',
  'Avoided telling a friend an outfit did not suit them.',
  'Made plans in a group chat that never happened.',
  'Felt instantly comfortable with someone I had just met.',
  'Had a friendship survive living in different places.',
  'Realised a casual friend understood me better than expected.',
  'Shared a meal because neither of us had enough money.',
  'Kept a tiny gift because of who gave it to me.',
  'Cried while saying goodbye to a friend.',

  // Dating and relationships
  'Gone on a date mostly because I was curious.',
  'Practised a casual reply before texting someone I liked.',
  'Pretended not to care how quickly someone replied.',
  'Developed feelings for someone I initially disliked.',
  'Stayed in a relationship longer than I knew I should.',
  'Re-read old messages after missing someone.',
  'Asked a friend to analyse a romantic message.',
  'Ignored an obvious red flag because the chemistry was strong.',
  'Ended a relationship by message.',
  'Been nervous before introducing a partner to friends or family.',
  'Compared a new relationship with an old one.',
  'Made a playlist for someone I liked.',
  'Had a crush on someone who never found out.',
  'Said “I’m fine” during an argument when I was not fine.',
  'Changed my mind about what I wanted from a relationship.',
  'Gone back to someone after promising myself I would not.',
  'Felt relieved after a breakup despite still caring.',
  'Planned a romantic gesture that went completely wrong.',
  'Forgotten an anniversary or relationship milestone.',
  'Fallen for someone because they made me laugh.',
  'Stayed friends with an ex.',
  'Hidden a relationship from somebody important to me.',
  'Imagined a future with someone before we became official.',
  'Been surprised by the person I found attractive.',
  'Realised I was flirting only after somebody pointed it out.',
  'Waited for someone else to make the first move.',
  'Mistaken friendliness for romantic interest.',
  'Given somebody a second chance that worked out well.',
  'Learned an important boundary through a difficult relationship.',
  'Felt loved by a small gesture more than an expensive gift.',

  // Courage, curiosity, and adventure
  'Performed on a stage in front of strangers.',
  'Tried an activity despite being genuinely afraid.',
  'Travelled somewhere alone.',
  'Spoken up when everyone else stayed quiet.',
  'Changed a major plan because my instincts said to.',
  'Introduced myself to someone I admired.',
  'Applied for something I thought was beyond my reach.',
  'Started over in a new city or community.',
  'Learned to swim, cycle, or drive as an adult.',
  'Taken a spontaneous trip with less than a day’s notice.',
  'Tried a sport that left me covered in bruises.',
  'Sang karaoke without being able to sing well.',
  'Volunteered for something before understanding the commitment.',
  'Entered a competition just to see what would happen.',
  'Asked for help after trying to solve everything alone.',
  'Admitted I was wrong in front of a group.',
  'Walked away from something that no longer felt right.',
  'Made a decision that disappointed others but protected me.',
  'Shared creative work before I felt ready.',
  'Tried to learn a difficult skill and nearly quit.',
  'Taken myself on a solo date.',
  'Said yes to an invitation where I knew nobody.',
  'Turned down an opportunity that looked impressive from outside.',
  'Asked a stranger for assistance in an unfamiliar place.',
  'Tried again after failing publicly.',
  'Changed my opinion after listening to someone else’s experience.',
  'Stood up for a person who was not in the room.',
  'Done something kind without telling anyone afterward.',
  'Made the first move toward repairing a relationship.',
  'Chosen an uncertain opportunity over a comfortable routine.',

  // Private habits and funny confessions
  'Had an imaginary argument and won it convincingly.',
  'Talked to myself while completing a simple task.',
  'Pretended I was in a music video while wearing headphones.',
  'Made a face at myself every time I passed a mirror.',
  'Looked inside a tissue after blowing my nose.',
  'Smelled clothing to decide whether it was clean enough to wear.',
  'Used the same mug for several days without washing it.',
  'Rewatched a comfort show instead of starting something new.',
  'Invented a backstory for strangers in public.',
  'Danced in the kitchen when nobody was watching.',
  'Sung the wrong lyrics with complete confidence.',
  'Checked the fridge repeatedly as if new food might appear.',
  'Stayed in pyjamas for an entire day without being ill.',
  'Practised accepting an award I have never been nominated for.',
  'Made a shopping list and then left it at home.',
  'Read a horoscope that was not for my sign.',
  'Kept a cardboard box because it seemed too useful to throw away.',
  'Watched a tutorial at double speed and still skipped parts.',
  'Named a plant, appliance, or vehicle.',
  'Saved wrapping paper to reuse later.',
  'Avoided a chore until completing it took less than five minutes.',
  'Tried to carry every shopping bag in one trip.',
  'Opened a calculator for extremely simple arithmetic.',
  'Checked whether a door was locked more than twice.',
  'Used song lyrics as if they were personal wisdom.',
  'Made an unnecessary spreadsheet for something in my personal life.',
  'Organised a drawer instead of doing a more urgent task.',
  'Kept an outfit for an imaginary future occasion.',
  'Felt proud after successfully folding a fitted sheet.',
  'Given myself a motivational speech in the mirror.',
] as const
