export const PUT_FINGER_WORK: readonly string[] = [
  "Put a finger down if you've joined a meeting before your camera was ready.",
  "Put a finger down if you've discovered halfway through a call that you were muted.",
  "Put a finger down if you've attended a meeting without knowing why you were invited.",
  "Put a finger down if you've watched a presentation run far beyond its scheduled finish.",
  "Put a finger down if you've volunteered to take notes so the discussion would stay organized.",
  "Put a finger down if you've asked a question that changed the direction of a meeting.",
  "Put a finger down if you've presented an idea to a room full of senior colleagues.",
  "Put a finger down if you've accidentally entered a virtual call meant for a different group.",
  "Put a finger down if you've had back-to-back calls with no break between them.",
  "Put a finger down if you've rescheduled a meeting because key information was missing.",
  "Put a finger down if you've used the chat box to avoid interrupting a speaker.",
  "Put a finger down if you've summarized a long discussion into clear next steps.",
  "Put a finger down if you've heard an unexpected noise take over a video call.",
  "Put a finger down if you've been the only person to arrive on time for a meeting.",
  "Put a finger down if you've facilitated a discussion between people who disagreed.",
  "Put a finger down if you've realized a calendar invite showed the wrong time zone.",
  "Put a finger down if you've left a call with more questions than answers.",
  "Put a finger down if you've declined a meeting because your input was not needed.",
  "Put a finger down if you've rewritten a work message several times before sending it.",
  "Put a finger down if you've received a message marked urgent that could wait until tomorrow.",
  "Put a finger down if you've answered a question that was already covered in the previous message.",
  "Put a finger down if you've sent an attachment and forgotten to mention what it was.",
  "Put a finger down if you've spotted a typo immediately after pressing send.",
  "Put a finger down if you've used an emoji to make a work message sound warmer.",
  "Put a finger down if you've moved a complicated conversation from chat to a call.",
  "Put a finger down if you've been copied on an email thread with dozens of replies.",
  "Put a finger down if you've drafted a response and decided it was better not to send it.",
  "Put a finger down if you've received useful feedback through a thoughtful written message.",
  "Put a finger down if you've searched an old conversation to prove a decision was documented.",
  "Put a finger down if you've sent a work message to the wrong channel.",
  "Put a finger down if you've waited for a reply that was sitting in your drafts.",
  "Put a finger down if you've turned a long email into a short checklist.",
  "Put a finger down if you've misunderstood the tone of a brief work message.",
  "Put a finger down if you've used a scheduled-send feature to respect working hours.",
  "Put a finger down if you've muted a busy work channel to concentrate.",
  "Put a finger down if you've asked someone to clarify an abbreviation everyone else seemed to know.",
  "Put a finger down if you've finished a task just minutes before its deadline.",
  "Put a finger down if you've negotiated more time after a project's scope changed.",
  "Put a finger down if you've broken a large assignment into smaller milestones.",
  "Put a finger down if you've inherited a deadline set before you joined the project.",
  "Put a finger down if you've delivered work early and surprised yourself.",
  "Put a finger down if you've had two important deadlines land on the same day.",
  "Put a finger down if you've warned a teammate that a due date was at risk.",
  "Put a finger down if you've prioritized one request by postponing another.",
  "Put a finger down if you've underestimated how long a familiar task would take.",
  "Put a finger down if you've built extra review time into a project plan.",
  "Put a finger down if you've received a last-minute request near the end of your shift.",
  "Put a finger down if you've completed the hardest item on your list first.",
  "Put a finger down if you've watched a deadline move more than once.",
  "Put a finger down if you've asked which task mattered most when everything seemed urgent.",
  "Put a finger down if you've paused a project while waiting for a decision.",
  "Put a finger down if you've kept a personal checklist beside an official project tracker.",
  "Put a finger down if you've finished a busy week with every major task completed.",
  "Put a finger down if you've discovered that a supposedly quick task required several approvals.",
  "Put a finger down if you've protected time on your calendar for uninterrupted work.",
  "Put a finger down if you've helped a teammate learn a process you know well.",
  "Put a finger down if you've asked a colleague for a second opinion before submitting work.",
  "Put a finger down if you've shared credit for a successful team effort.",
  "Put a finger down if you've covered an essential task while a coworker was away.",
  "Put a finger down if you've worked with someone whose approach was completely different from yours.",
  "Put a finger down if you've resolved a disagreement by returning to the team's shared goal.",
  "Put a finger down if you've offered help before anyone had to ask.",
  "Put a finger down if you've received support from a teammate during an unusually busy day.",
  "Put a finger down if you've divided a project according to everyone's strengths.",
  "Put a finger down if you've celebrated a team win that took months to achieve.",
  "Put a finger down if you've adapted your communication style for a new collaborator.",
  "Put a finger down if you've taken over a handoff that lacked important context.",
  "Put a finger down if you've thanked someone publicly for making your work easier.",
  "Put a finger down if you've worked across departments to solve one stubborn problem.",
  "Put a finger down if you've learned a shortcut from a colleague with less seniority.",
  "Put a finger down if you've kept a group project moving when responsibilities were unclear.",
  "Put a finger down if you've disagreed with an idea while remaining respectful of its author.",
  "Put a finger down if you've shared a reusable resource with your whole team.",
  "Put a finger down if you've joined a project after the major decisions were already made.",
  "Put a finger down if you've handled a customer question you had never heard before.",
  "Put a finger down if you've turned a frustrated customer's visit into a positive experience.",
  "Put a finger down if you've explained the same product feature several times in one day.",
  "Put a finger down if you've remembered a regular customer's usual request.",
  "Put a finger down if you've asked a manager to help with a problem outside your authority.",
  "Put a finger down if you've stayed calm while a queue kept growing.",
  "Put a finger down if you've found a practical alternative when an item was unavailable.",
  "Put a finger down if you've received a sincere thank-you from someone you served.",
  "Put a finger down if you've corrected a billing error before a client noticed it.",
  "Put a finger down if you've followed up to confirm that a customer's issue was resolved.",
  "Put a finger down if you've adjusted an explanation for someone unfamiliar with your industry.",
  "Put a finger down if you've handled several customer channels at the same time.",
  "Put a finger down if you've had a client change the brief after seeing the first draft.",
  "Put a finger down if you've documented a common customer question for future staff.",
  "Put a finger down if you've had to say no to a request that policy did not allow.",
  "Put a finger down if you've received a compliment that mentioned you by name.",
  "Put a finger down if you've solved a service problem without making the customer repeat everything.",
  "Put a finger down if you've managed expectations when a delivery was delayed.",
  "Put a finger down if you've learned something useful from a customer complaint.",
  "Put a finger down if you've worked from a kitchen table for an entire day.",
  "Put a finger down if you've rearranged a room to improve your home workspace.",
  "Put a finger down if you've started a remote call while someone rang your doorbell.",
  "Put a finger down if you've worn headphones to signal that you were concentrating at home.",
  "Put a finger down if you've lost internet access during an important online task.",
  "Put a finger down if you've taken a walking break between remote meetings.",
  "Put a finger down if you've created a morning routine to mark the start of work.",
  "Put a finger down if you've closed your laptop to mark the end of the workday.",
  "Put a finger down if you've worked with a teammate you have never met in person.",
  "Put a finger down if you've received a delivery in the middle of a presentation.",
  "Put a finger down if you've changed locations at home to find a quieter place.",
  "Put a finger down if you've shared your screen and briefly shown the wrong window.",
  "Put a finger down if you've solved a technical problem without on-site support.",
  "Put a finger down if you've missed the casual conversations that happen in a shared workplace.",
  "Put a finger down if you've planned an in-person day around collaborative work.",
  "Put a finger down if you've used captions during a virtual meeting.",
  "Put a finger down if you've attended an online social event with coworkers.",
  "Put a finger down if you've adjusted your schedule to collaborate across time zones.",
  "Put a finger down if you've improved your desk setup after noticing physical discomfort.",
  "Put a finger down if you've arrived at work after an unusually long commute.",
  "Put a finger down if you've missed your stop while thinking about the day ahead.",
  "Put a finger down if you've used travel time to plan your priorities.",
  "Put a finger down if you've changed your route because of an unexpected delay.",
  "Put a finger down if you've commuted in a carpool arranged with another employee.",
  "Put a finger down if you've commuted before sunrise for an early shift.",
  "Put a finger down if you've packed your work bag the night before.",
  "Put a finger down if you've reached the workplace and realized you forgot something essential.",
  "Put a finger down if you've walked or cycled part of your journey to work.",
  "Put a finger down if you've used a commute to switch out of work mode.",
  "Put a finger down if you've waited for public transport after a late shift.",
  "Put a finger down if you've worked at a different site from your usual one.",
  "Put a finger down if you've carried lunch through a crowded commute without spilling it.",
  "Put a finger down if you've checked the weather before choosing work clothes.",
  "Put a finger down if you've arrived early because you expected traffic that never appeared.",
  "Put a finger down if you've taken a work call while traveling between locations.",
  "Put a finger down if you've needed directions inside a large workplace.",
  "Put a finger down if you've found a quieter route that improved your commute.",
  "Put a finger down if you've kept spare work essentials at your workplace.",
  "Put a finger down if you've exchanged part of the rota with a teammate.",
  "Put a finger down if you've worked while most people you know were asleep.",
  "Put a finger down if you've handed over an unfinished task to the next shift.",
  "Put a finger down if you've covered a shift at short notice by choice.",
  "Put a finger down if you've managed a sudden rush after a slow start.",
  "Put a finger down if you've worked a schedule that changed from week to week.",
  "Put a finger down if you've prepared the workspace for the team arriving after you.",
  "Put a finger down if you've completed an opening checklist before customers arrived.",
  "Put a finger down if you've performed a closing routine with perfect timing.",
  "Put a finger down if you've taken your break later than planned because the shift was busy.",
  "Put a finger down if you've learned to estimate how busy a shift will become.",
  "Put a finger down if you've worked a weekend that felt like a weekday.",
  "Put a finger down if you've met a coworker only through shift handover notes.",
  "Put a finger down if you've balanced several stations during a staffing gap.",
  "Put a finger down if you've restocked supplies for the person taking over from you.",
  "Put a finger down if you've experienced a shift that passed surprisingly quickly.",
  "Put a finger down if you've adjusted your sleep routine around changing hours.",
  "Put a finger down if you've worn a name badge until you forgot it was there.",
  "Put a finger down if you've found an efficient rhythm during a repetitive shift.",
  "Put a finger down if you've quoted a freelance project before knowing its full complexity.",
  "Put a finger down if you've reminded a client about an overdue invoice.",
  "Put a finger down if you've turned down work because the schedule was already full.",
  "Put a finger down if you've created a contract template after learning from experience.",
  "Put a finger down if you've revised a proposal after a promising client call.",
  "Put a finger down if you've separated business expenses from personal spending.",
  "Put a finger down if you've found a new client through a recommendation.",
  "Put a finger down if you've reserved time for administration between paid projects.",
  "Put a finger down if you've explained why additional revisions would change the price.",
  "Put a finger down if you've updated your portfolio after finishing a strong project.",
  "Put a finger down if you've juggled several client assignments across one week.",
  "Put a finger down if you've made upfront payment part of your freelance terms.",
  "Put a finger down if you've followed up on a proposal that received no response.",
  "Put a finger down if you've raised your rates after gaining more experience.",
  "Put a finger down if you've referred a project to another independent professional.",
  "Put a finger down if you've built a quiet period into your freelance budget.",
  "Put a finger down if you've clarified who owns the final project files.",
  "Put a finger down if you've turned a one-time assignment into repeat work.",
  "Put a finger down if you've scheduled your own professional development.",
  "Put a finger down if you've measured twice before making a cut.",
  "Put a finger down if you've cleaned a tool before putting it away.",
  "Put a finger down if you've learned a practical technique by watching an experienced coworker.",
  "Put a finger down if you've stopped a task to check the correct procedure.",
  "Put a finger down if you've noticed a small defect before it became a larger problem.",
  "Put a finger down if you've labeled materials so the next person could find them easily.",
  "Put a finger down if you've completed a job that required both precision and patience.",
  "Put a finger down if you've replaced worn protective equipment before starting a task.",
  "Put a finger down if you've reported a hazard so it could be addressed.",
  "Put a finger down if you've read a diagram that initially looked impossible to understand.",
  "Put a finger down if you've improvised a safe solution when the original plan did not fit.",
  "Put a finger down if you've left a work area cleaner than you found it.",
  "Put a finger down if you've learned the names of unfamiliar tools on a new job.",
  "Put a finger down if you've coordinated your task with another trade on the same site.",
  "Put a finger down if you've documented a repair for whoever handles it next time.",
  "Put a finger down if you've completed required safety training before using new equipment.",
  "Put a finger down if you've asked for assistance with a lift that needed more than one person.",
  "Put a finger down if you've tested your work before calling the job finished.",
  "Put a finger down if you've taken pride in a result most people would never notice.",
  "Put a finger down if you've stared at a blank page before a creative breakthrough.",
  "Put a finger down if you've saved several versions of the same design.",
  "Put a finger down if you've received feedback that improved your original concept.",
  "Put a finger down if you've defended one creative choice and changed another.",
  "Put a finger down if you've found inspiration while working on an unrelated task.",
  "Put a finger down if you've presented unfinished creative work for review.",
  "Put a finger down if you've named a file final before making more changes.",
  "Put a finger down if you've solved a creative block by stepping away briefly.",
  "Put a finger down if you've adapted your style to match a project's audience.",
  "Put a finger down if you've cut a favorite idea because it did not serve the final piece.",
  "Put a finger down if you've kept a notebook for ideas that arrive at inconvenient times.",
  "Put a finger down if you've collaborated with someone whose medium was new to you.",
  "Put a finger down if you've recovered a creative project after the software crashed.",
  "Put a finger down if you've delivered creative work that looked simple but took hours.",
  "Put a finger down if you've learned a new tool to achieve a specific creative effect.",
  "Put a finger down if you've compared two nearly identical versions for too long.",
  "Put a finger down if you've caught an inconsistency just before final delivery.",
  "Put a finger down if you've explained the reasoning behind a creative decision.",
  "Put a finger down if you've felt proud seeing your work used in the real world.",
  "Put a finger down if you've received feedback you needed time to process.",
  "Put a finger down if you've asked for a specific example to understand a critique.",
  "Put a finger down if you've changed your approach after a performance review.",
  "Put a finger down if you've given constructive feedback to someone more senior.",
  "Put a finger down if you've praised a colleague's work directly to their manager.",
  "Put a finger down if you've learned that your effort was noticed when you least expected it.",
  "Put a finger down if you've received recognition for work that happened behind the scenes.",
  "Put a finger down if you've kept a record of positive feedback for difficult days.",
  "Put a finger down if you've watched someone else receive credit for a shared result.",
  "Put a finger down if you've corrected a misunderstanding about who completed a task.",
  "Put a finger down if you've nominated a coworker for an award or acknowledgment.",
  "Put a finger down if you've discovered a strength through someone else's feedback.",
  "Put a finger down if you've received praise that was specific enough to be useful.",
  "Put a finger down if you've asked how success would be measured before beginning work.",
  "Put a finger down if you've offered feedback privately to avoid embarrassing someone.",
  "Put a finger down if you've thanked a reviewer even when you disagreed with their suggestion.",
  "Put a finger down if you've revised your own feedback to make it clearer and kinder.",
  "Put a finger down if you've celebrated a colleague's promotion.",
  "Put a finger down if you've shared a lesson from a project that did not go as planned.",
  "Put a finger down if you've forgotten someone's name during your first week at a job.",
  "Put a finger down if you've needed help finding a basic workplace facility.",
  "Put a finger down if you've completed onboarding paperwork before understanding the job.",
  "Put a finger down if you've shadowed a colleague to learn the daily routine.",
  "Put a finger down if you've been assigned a login that did not work on your first day.",
  "Put a finger down if you've learned an unwritten workplace custom from a teammate.",
  "Put a finger down if you've introduced yourself repeatedly during a new role.",
  "Put a finger down if you've received a welcome message that helped you settle in.",
  "Put a finger down if you've asked where a file lived because no guide explained it.",
  "Put a finger down if you've started a role with a training schedule already prepared.",
  "Put a finger down if you've mentored someone through their first month.",
  "Put a finger down if you've created instructions that would have helped you as a newcomer.",
  "Put a finger down if you've attended an orientation packed with unfamiliar information.",
  "Put a finger down if you've found the unofficial go-to person while your assigned contact was away.",
  "Put a finger down if you've moved from trainee to the person answering new starters' questions.",
  "Put a finger down if you've received access to an essential system later than expected.",
  "Put a finger down if you've made a useful connection during an onboarding session.",
  "Put a finger down if you've joined a team while everyone was working remotely.",
  "Put a finger down if you've finished your first week feeling more confident than you began.",
  "Put a finger down if you've admitted a work mistake before anyone else noticed it.",
  "Put a finger down if you've fixed an error by retracing each step you took.",
  "Put a finger down if you've sent a correction after sharing outdated information.",
  "Put a finger down if you've learned to double-check a detail because you once missed it.",
  "Put a finger down if you've helped solve a problem without focusing on blame.",
  "Put a finger down if you've restored an earlier version after an accidental change.",
  "Put a finger down if you've caught your own calculation error during a final review.",
  "Put a finger down if you've apologized to a teammate for creating extra work.",
  "Put a finger down if you've reported a near miss so the process could improve.",
  "Put a finger down if you've turned a repeated mistake into a checklist item.",
  "Put a finger down if you've misunderstood an instruction and asked to start again.",
  "Put a finger down if you've found the source of a problem in an unexpected place.",
  "Put a finger down if you've learned more from correcting a failure than from an easy success.",
  "Put a finger down if you've received help recovering from a mistake under time pressure.",
  "Put a finger down if you've documented a workaround while waiting for a permanent fix.",
  "Put a finger down if you've tested a correction before announcing that the issue was solved.",
  "Put a finger down if you've owned a misunderstanding caused by an unclear message.",
  "Put a finger down if you've discovered an error early because someone asked a good question.",
  "Put a finger down if you've improved a process after reviewing what went wrong.",
  "Put a finger down if you've silenced work notifications during personal time.",
  "Put a finger down if you've told someone a request would need to wait until your next shift.",
  "Put a finger down if you've taken a full lunch break away from your workstation.",
  "Put a finger down if you've used annual leave without checking work messages.",
  "Put a finger down if you've asked for priorities before accepting additional work.",
  "Put a finger down if you've turned down an optional event to protect your energy.",
  "Put a finger down if you've explained your working hours to a new client.",
  "Put a finger down if you've delegated a task instead of extending your day.",
  "Put a finger down if you've requested a quieter space to complete focused work.",
  "Put a finger down if you've reminded a colleague that you were officially off duty.",
  "Put a finger down if you've taken time to recover after an unusually demanding period.",
  "Put a finger down if you've set a realistic limit on how many projects you could handle.",
  "Put a finger down if you've asked to move a recurring meeting outside your break time.",
  "Put a finger down if you've protected confidential work from people sharing your space.",
  "Put a finger down if you've chosen not to answer a nonurgent message immediately.",
  "Put a finger down if you've raised a concern when workload expectations became unclear.",
  "Put a finger down if you've made your availability visible to the whole team.",
  "Put a finger down if you've finished work on time despite an unfinished to-do list.",
  "Put a finger down if you've learned that setting a boundary improved your work.",
  "Put a finger down if professional training has reshaped your daily methods.",
  "Put a finger down if you've gained a practical skill by following a free online tutorial.",
  "Put a finger down if you've invited someone from another field to describe their career path.",
  "Put a finger down if you've updated your résumé after gaining a new responsibility.",
  "Put a finger down if you've applied for an internal opportunity.",
  "Put a finger down if you've discovered that a past role taught you a transferable skill.",
  "Put a finger down if you've practiced for an interview with another person.",
  "Put a finger down if you've attended an industry event and learned something unexpected.",
  "Put a finger down if you've changed career direction after trying a new kind of work.",
  "Put a finger down if you've asked for a stretch assignment to build experience.",
  "Put a finger down if you've taught yourself a tool before it became part of your role.",
  "Put a finger down if you've realized you were ready for more responsibility.",
  "Put a finger down if you've moved into a role you had not originally planned to pursue.",
  "Put a finger down if you've used a quiet work period to learn something new.",
  "Put a finger down if you've asked for clearer goals to support your development.",
  "Put a finger down if you've fixed a shared printer without knowing exactly what worked.",
  "Put a finger down if you've found a favorite lunch spot within walking distance of work.",
]
