export const PUT_FINGER_TRAVEL: readonly string[] = [
  "Put a finger down if you have taken a day trip to a place near home.",
  "Put a finger down if you have explored your own town like a visitor.",
  "Put a finger down if you have crossed a regional border during a journey.",
  "Put a finger down if you have traveled to a different time zone.",
  "Put a finger down if you have returned to the same destination more than once.",
  "Put a finger down if you have chosen a nearby getaway instead of a longer journey.",
  "Put a finger down if you have combined several towns into one trip.",
  "Put a finger down if you have visited a place because it appeared in a book or film.",
  "Put a finger down if you have discovered an interesting stop between two planned destinations.",
  "Put a finger down if you have extended a trip because you were not ready to leave.",

  "Put a finger down if you have built an itinerary around one must-see place.",
  "Put a finger down if you have planned a trip with no fixed daily schedule.",
  "Put a finger down if you have compared routes before choosing how to travel.",
  "Put a finger down if you have made a shared planning document for a group trip.",
  "Put a finger down if you have changed a destination after checking seasonal conditions.",
  "Put a finger down if you have researched local laws or customs before leaving.",
  "Put a finger down if you have checked official travel advice before a journey.",
  "Put a finger down if you have planned a backup activity for bad weather.",
  "Put a finger down if you have left free time in an otherwise busy itinerary.",
  "Put a finger down if you have scheduled a rest day during a longer trip.",

  "Put a finger down if you have saved places on a map before visiting them.",
  "Put a finger down if you have organized bookings in one folder or app.",
  "Put a finger down if you have checked whether advance reservations were required.",
  "Put a finger down if you have read recent reviews before choosing somewhere to stay.",
  "Put a finger down if you have compared the total cost rather than the advertised price.",
  "Put a finger down if you have set aside room in your plans for unexpected expenses.",
  "Put a finger down if you have split planning responsibilities with a travel companion.",
  "Put a finger down if you have agreed on different travel priorities before a group trip.",
  "Put a finger down if you have picked a meeting point in case your group became separated.",
  "Put a finger down if you have shared an itinerary with a trusted contact at home.",

  "Put a finger down if you have packed for a trip using a written checklist.",
  "Put a finger down if you have fit everything you needed into a carry-on bag.",
  "Put a finger down if you have packed something useful that everyone else forgot.",
  "Put a finger down if you have brought clothing that could be worn in several ways.",
  "Put a finger down if you have packed for two kinds of weather on one trip.",
  "Put a finger down if you have rolled your clothes to make more space.",
  "Put a finger down if you have used packing cubes or separate bags to stay organized.",
  "Put a finger down if you have weighed your luggage before leaving home.",
  "Put a finger down if you have worn your bulkiest clothing while in transit.",
  "Put a finger down if you have left extra room for something acquired on the journey.",

  "Put a finger down if you have forgotten an essential item and replaced it after arrival.",
  "Put a finger down if you have packed an item that never left your bag.",
  "Put a finger down if you have carried a reusable water bottle while traveling.",
  "Put a finger down if you have brought a small first-aid kit on a trip.",
  "Put a finger down if you have kept medication in its original labeled packaging.",
  "Put a finger down if you have packed a charger for the wrong type of outlet.",
  "Put a finger down if you have carried a portable battery for a long travel day.",
  "Put a finger down if you have made copies of important travel documents.",
  "Put a finger down if you have stored emergency contact details somewhere offline.",
  "Put a finger down if you have packed snacks for the journey rather than the destination.",

  "Put a finger down if you have arrived at an airport much earlier than necessary.",
  "Put a finger down if you have reached the gate just as boarding began.",
  "Put a finger down if you have watched your departure gate change more than once.",
  "Put a finger down if you have taken a shuttle between airport terminals.",
  "Put a finger down if you have used an airport lounge through an included benefit.",
  "Put a finger down if you have eaten a full meal while waiting for a flight.",
  "Put a finger down if you have filled your water bottle after airport security.",
  "Put a finger down if you have helped another traveler find the correct gate.",
  "Put a finger down if you have found a quiet corner during a long layover.",
  "Put a finger down if you have watched planes take off while waiting to board.",

  "Put a finger down if you have taken your first flight on a small aircraft.",
  "Put a finger down if you have sat in a middle seat for an entire flight.",
  "Put a finger down if you have swapped seats so a group could sit together.",
  "Put a finger down if you have brought your own entertainment for a flight.",
  "Put a finger down if you have slept through an in-flight meal or snack service.",
  "Put a finger down if you have seen sunrise or sunset from an airplane window.",
  "Put a finger down if you have experienced a flight diversion to another airport.",
  "Put a finger down if you have had a connection shortened by a delayed first flight.",
  "Put a finger down if you have applauded or heard applause after a plane landed.",
  "Put a finger down if you have discovered after landing that your checked bag took another route.",

  "Put a finger down if you have taken an overnight train.",
  "Put a finger down if you have reserved a specific seat on a rail journey.",
  "Put a finger down if you have boarded the wrong train and corrected the mistake safely.",
  "Put a finger down if you have watched the scenery for most of a train ride.",
  "Put a finger down if you have eaten food bought at a railway station during the journey.",
  "Put a finger down if you have changed trains with only a few minutes to spare.",
  "Put a finger down if you have used a rail pass for several journeys.",
  "Put a finger down if you have taken a local bus without knowing every stop.",
  "Put a finger down if you have ridden a ferry as part of a regular transport route.",
  "Put a finger down if you have used a tram or metro in an unfamiliar city.",

  "Put a finger down if you have taken a road trip with a planned playlist.",
  "Put a finger down if you have chosen the scenic road over the fastest route.",
  "Put a finger down if you have stopped at a roadside attraction you had never heard of.",
  "Put a finger down if you have packed a cooler for a long drive.",
  "Put a finger down if you have taken turns navigating on a road trip.",
  "Put a finger down if you have changed a driving route because of traffic or road closures.",
  "Put a finger down if you have cleaned a vehicle before returning it after a trip.",
  "Put a finger down if you have photographed a memorable road sign.",
  "Put a finger down if you have crossed a long bridge or tunnel during a journey.",
  "Put a finger down if you have ended a road-trip day somewhere different from the original plan.",

  "Put a finger down if you have stayed in a hotel for only one night.",
  "Put a finger down if you have booked accommodation directly with the host or property.",
  "Put a finger down if you have stayed in a shared room while traveling.",
  "Put a finger down if you have rented an entire home with a group.",
  "Put a finger down if you have camped at an established campsite.",
  "Put a finger down if you have stayed with someone you knew at your destination.",
  "Put a finger down if you have checked into accommodation after the front desk closed.",
  "Put a finger down if you have requested a quieter room after arrival.",
  "Put a finger down if you have inspected the emergency exit route where you stayed.",
  "Put a finger down if you have confirmed an accommodation feature before booking it.",

  "Put a finger down if you have cooked a meal in your accommodation while away.",
  "Put a finger down if you have done laundry during a trip.",
  "Put a finger down if you have shared a bathroom with other travelers.",
  "Put a finger down if you have left a thoughtful review after checking out.",
  "Put a finger down if you have asked for a late checkout and received one.",
  "Put a finger down if you have moved to different accommodation during the same visit.",
  "Put a finger down if you have remembered a room number but forgotten the floor.",
  "Put a finger down if you have used a door sign to decline housekeeping.",
  "Put a finger down if you have found the view from your room better than expected.",
  "Put a finger down if you have chosen where to stay mainly for access to public transport.",

  "Put a finger down if you have tried a regional dish for the first time while traveling.",
  "Put a finger down if you have visited a food market at your destination.",
  "Put a finger down if you have asked a local resident where they like to eat.",
  "Put a finger down if you have returned to the same café twice during one trip.",
  "Put a finger down if you have ordered food by pointing at a menu.",
  "Put a finger down if you have learned the local words needed to explain a dietary requirement.",
  "Put a finger down if you have booked a table for a special meal while away.",
  "Put a finger down if you have assembled a picnic from a neighborhood grocery shop.",
  "Put a finger down if you have taken a cooking class during a trip.",
  "Put a finger down if you have brought home a packaged food specialty where regulations allowed it.",

  "Put a finger down if you have eaten breakfast at a transport terminal.",
  "Put a finger down if you have discovered a new favorite snack on a journey.",
  "Put a finger down if you have shared several small dishes with travel companions.",
  "Put a finger down if you have waited in a long line for a popular local treat.",
  "Put a finger down if you have chosen a restaurant because its menu clearly listed ingredients.",
  "Put a finger down if you have carried a familiar snack for times when suitable food was hard to find.",
  "Put a finger down if you have enjoyed a meal with a view you still remember.",
  "Put a finger down if you have changed your dinner plans after finding a busy neighborhood spot.",
  "Put a finger down if you have learned a dining custom before eating somewhere new.",
  "Put a finger down if you have thanked a cook or server in the local language.",

  "Put a finger down if you have navigated with a paper map.",
  "Put a finger down if you have downloaded an offline map before losing signal.",
  "Put a finger down if you have walked in the wrong direction after leaving a station.",
  "Put a finger down if you have asked for directions and received more than one route.",
  "Put a finger down if you have used a landmark instead of street names to find your way.",
  "Put a finger down if you have followed signs through a city without opening a map.",
  "Put a finger down if you have navigated back to your accommodation after your phone battery died.",
  "Put a finger down if you have pinned where you parked before exploring on foot.",
  "Put a finger down if you have taken a screenshot of directions for later use.",
  "Put a finger down if you have recognized a place because you had explored it virtually first.",

  "Put a finger down if you have learned a greeting specifically for a trip.",
  "Put a finger down if you have practiced pronouncing a place name before arriving.",
  "Put a finger down if you have used a translation app to understand a sign.",
  "Put a finger down if you have communicated successfully using gestures and patience.",
  "Put a finger down if you have carried an address written in the local script.",
  "Put a finger down if you have misunderstood a word and laughed about it later.",
  "Put a finger down if you have asked someone to repeat themselves more slowly while traveling.",
  "Put a finger down if you have learned how to say thank you in a language new to you.",
  "Put a finger down if you have recognized a familiar word in an unfamiliar conversation.",
  "Put a finger down if you have used pictures to clarify what you needed.",

  "Put a finger down if you have traveled during a heat wave.",
  "Put a finger down if you have arrived to find colder weather than you packed for.",
  "Put a finger down if you have bought an umbrella after the rain started.",
  "Put a finger down if you have rearranged a sightseeing day because of a storm forecast.",
  "Put a finger down if you have seen snow during a journey when you did not expect it.",
  "Put a finger down if you have watched fog change a familiar landscape.",
  "Put a finger down if you have waited indoors for severe weather to pass.",
  "Put a finger down if you have checked air-quality information before an outdoor plan.",
  "Put a finger down if you have carried extra water because the day was unusually hot.",
  "Put a finger down if you have changed transportation after weather disrupted the original route.",

  "Put a finger down if you have visited a museum mainly to see one exhibit.",
  "Put a finger down if you have taken a guided walking tour.",
  "Put a finger down if you have climbed a viewpoint using an accessible established route.",
  "Put a finger down if you have toured a historic building with an audio guide.",
  "Put a finger down if you have spent longer in a gallery than you expected.",
  "Put a finger down if you have visited a botanical garden while away.",
  "Put a finger down if you have attended a local performance during a trip.",
  "Put a finger down if you have explored a public park in another city.",
  "Put a finger down if you have taken a boat tour with a licensed operator.",
  "Put a finger down if you have viewed a famous landmark from outside without buying a ticket.",

  "Put a finger down if you have reached a popular attraction before the crowds arrived.",
  "Put a finger down if you have skipped a famous sight because something else interested you more.",
  "Put a finger down if you have joined a tour led by a local guide.",
  "Put a finger down if you have read a place's history while standing there.",
  "Put a finger down if you have visited a free community event while traveling.",
  "Put a finger down if you have taken a photograph from a designated viewing area.",
  "Put a finger down if you have put your camera away to enjoy the moment.",
  "Put a finger down if you have followed site rules that protected a natural or historic place.",
  "Put a finger down if you have discovered your favorite attraction was not in the guidebook.",
  "Put a finger down if you have ended a sightseeing day with more steps than expected.",

  "Put a finger down if you have traveled for a work meeting.",
  "Put a finger down if you have added personal time to a work trip with permission.",
  "Put a finger down if you have joined a video call from temporary accommodation.",
  "Put a finger down if you have worked across time zones while away.",
  "Put a finger down if you have packed professional clothing so it arrived without major creases.",
  "Put a finger down if you have met a colleague in person after only knowing them online.",
  "Put a finger down if you have prepared a presentation while in transit.",
  "Put a finger down if you have carried work equipment through airport security.",
  "Put a finger down if you have found a quiet workspace in an unfamiliar city.",
  "Put a finger down if you have kept confidential work information private while traveling.",

  "Put a finger down if you have traveled to attend a conference or training event.",
  "Put a finger down if you have learned a useful skill during a business trip.",
  "Put a finger down if you have eaten alone comfortably while traveling for work.",
  "Put a finger down if you have navigated an unfamiliar commute to a temporary workplace.",
  "Put a finger down if you have received travel plans from work at short notice.",
  "Put a finger down if you have coordinated a trip around a remote team's schedule.",
  "Put a finger down if you have claimed an eligible travel expense after returning.",
  "Put a finger down if you have packed a backup outfit for an important work event.",
  "Put a finger down if you have explored a neighborhood after the workday ended.",
  "Put a finger down if you have returned from work travel with an idea that improved your routine.",

  "Put a finger down if you have traveled specifically to visit family.",
  "Put a finger down if you have stayed in your childhood room during a return visit.",
  "Put a finger down if you have carried a requested item to someone you were visiting.",
  "Put a finger down if you have planned travel around a family celebration.",
  "Put a finger down if you have taken a relative sightseeing in their own area.",
  "Put a finger down if you have learned a family story during a journey together.",
  "Put a finger down if you have adjusted a group itinerary for different energy levels.",
  "Put a finger down if you have scheduled quiet time during a busy family visit.",
  "Put a finger down if you have helped a relative understand their travel booking.",
  "Put a finger down if you have said goodbye at a station or airport and wished for more time.",

  "Put a finger down if you have confirmed step-free access before a journey.",
  "Put a finger down if you have requested assistance from a transport provider in advance.",
  "Put a finger down if you have checked whether an accommodation lift was working.",
  "Put a finger down if you have chosen an attraction with sensory-friendly visiting information.",
  "Put a finger down if you have used captions or a transcript on a travel tour.",
  "Put a finger down if you have planned regular breaks to make a trip manageable.",
  "Put a finger down if you have found a quieter route through a crowded terminal.",
  "Put a finger down if you have asked a venue about seating before attending.",
  "Put a finger down if you have traveled with an assistive device.",
  "Put a finger down if you have thanked someone for respecting an accessibility need without fuss.",

  "Put a finger down if you have taken public transport instead of a private ride while away.",
  "Put a finger down if you have walked between nearby sights rather than using a vehicle.",
  "Put a finger down if you have refilled toiletries instead of buying travel-size containers.",
  "Put a finger down if you have declined unnecessary daily linen changes at accommodation.",
  "Put a finger down if you have carried a reusable shopping bag on a trip.",
  "Put a finger down if you have sorted waste according to local instructions while away.",
  "Put a finger down if you have chosen a direct route to reduce unnecessary travel legs.",
  "Put a finger down if you have supported a locally owned business during a visit.",
  "Put a finger down if you have visited a popular place outside its busiest season.",
  "Put a finger down if you have stayed on marked paths to protect the surrounding environment.",

  "Put a finger down if you have repaired travel gear instead of replacing it.",
  "Put a finger down if you have borrowed luggage for a trip.",
  "Put a finger down if you have used a digital ticket instead of printing one.",
  "Put a finger down if you have carried your own cutlery for takeaway meals while traveling.",
  "Put a finger down if you have avoided buying a souvenir you did not truly want.",
  "Put a finger down if you have chosen a refill station over a single-use bottle.",
  "Put a finger down if you have learned how visitors can reduce pressure on a fragile destination.",
  "Put a finger down if you have followed wildlife-viewing guidance from a responsible operator.",
  "Put a finger down if you have kept a respectful distance from animals while sightseeing.",
  "Put a finger down if you have brought home memories without removing anything from nature.",

  "Put a finger down if you have missed a departure because you misunderstood the time.",
  "Put a finger down if you have arrived at the correct station on the wrong side of town.",
  "Put a finger down if you have found a booking was for a different date than expected.",
  "Put a finger down if you have had a suitcase wheel break during a journey.",
  "Put a finger down if you have spilled something on your only clean travel outfit.",
  "Put a finger down if you have left an item behind and recovered it through lost property.",
  "Put a finger down if you have had a key card stop working when you reached your room.",
  "Put a finger down if you have waited at the wrong pickup point.",
  "Put a finger down if you have discovered your reservation under a misspelled name.",
  "Put a finger down if you have needed customer support to untangle a travel booking.",

  "Put a finger down if you have handled a cancellation by making a completely new plan.",
  "Put a finger down if you have bought replacement clothing because your luggage was delayed.",
  "Put a finger down if you have used travel insurance for an eligible disruption.",
  "Put a finger down if you have kept receipts after an unexpected travel problem.",
  "Put a finger down if you have found kindness from a stranger during a difficult travel day.",
  "Put a finger down if you have offered practical help to a delayed fellow traveler.",
  "Put a finger down if you have turned a wrong turn into a pleasant discovery.",
  "Put a finger down if you have laughed later about a travel mistake that felt stressful at the time.",
  "Put a finger down if you have contacted your accommodation to explain a late arrival.",
  "Put a finger down if you have used an emergency fund to solve an unexpected travel issue.",

  "Put a finger down if carrying an overpacked bag convinced you to bring less next time.",
  "Put a finger down if you crossed a city only to discover your destination was closed.",
  "Put a finger down if a slower itinerary made one activity feel like enough for the day.",
  "Put a finger down if delayed luggage taught you to keep an essential item in your personal bag.",
  "Put a finger down if you now confirm the final transport home before an evening out.",
  "Put a finger down if a trip made you more careful about asking before taking photographs.",
  "Put a finger down if a simple local greeting opened a friendly conversation while away.",
  "Put a finger down if two places with the same name sent you toward the wrong address.",
  "Put a finger down if a tight connection persuaded you to allow more transfer time.",
  "Put a finger down if traveling with others made you more flexible about changing plans.",

  "Put a finger down if you have returned home appreciating something you once overlooked.",
  "Put a finger down if you have changed a habit after seeing how another place handled daily life.",
  "Put a finger down if you have kept a travel journal or notes from a journey.",
  "Put a finger down if you have printed photographs from a trip instead of leaving them on a phone.",
  "Put a finger down if you have stayed in touch with someone you met while traveling.",
  "Put a finger down if you have recommended an overlooked destination to someone else.",
  "Put a finger down if you have recreated a travel meal after returning home.",
  "Put a finger down if you have revisited a memory by looking at an old ticket or map.",
  "Put a finger down if you have started planning another journey before unpacking from the last one.",
  "Put a finger down if you have realized the unplanned moments became your favorite travel stories.",

  "Put a finger down if you have taken a solo trip and enjoyed choosing your own pace.",
  "Put a finger down if you have joined a group trip where you knew only one person.",
  "Put a finger down if you have spent part of a shared holiday exploring independently.",
  "Put a finger down if you have made a travel decision by taking a group vote.",
  "Put a finger down if you have compromised on an activity so everyone had something to enjoy.",
  "Put a finger down if you have asked before sharing a travel companion's photo online.",
  "Put a finger down if you have respected someone's choice to skip a group activity.",
  "Put a finger down if you have discussed budgets openly before booking a shared trip.",
  "Put a finger down if you have divided shared costs in a way the whole group accepted.",
  "Put a finger down if you have made a new friend through a shared daytime tour or activity.",

  "Put a finger down if you have checked entry requirements before booking international travel.",
  "Put a finger down if you have renewed a travel document earlier than you expected.",
  "Put a finger down if you have completed a required arrival form before reaching the border.",
  "Put a finger down if you have checked recommended health precautions before departure.",
  "Put a finger down if you have located a pharmacy or clinic soon after arriving somewhere new.",
  "Put a finger down if you have taken a rest day because your body needed one.",
  "Put a finger down if you have worn sun protection throughout a sightseeing day.",
  "Put a finger down if you have chosen a licensed ride after arriving late at night.",
  "Put a finger down if you have kept valuables secure without letting worry dominate the trip.",
  "Put a finger down if you have confirmed everyone got back safely after a group outing.",
]
