export const PUT_FINGER_DRINKING = [
  "Put a finger down if you have ordered a drink mainly because its name made you laugh.",
  "Put a finger down if you have asked a bartender what a mystery ingredient tasted like.",
  "Put a finger down if you have chosen a drink because the garnish looked impressive.",
  "Put a finger down if you have discovered a favorite beverage through a friend's recommendation.",
  "Put a finger down if you have ordered the house specialty without knowing what to expect.",
  "Put a finger down if you have picked a drink to match the food you ordered.",
  "Put a finger down if you have preferred a bitter drink after once disliking bitter flavors.",
  "Put a finger down if you have realized a drink was much sweeter than its menu description suggested.",
  "Put a finger down if you have enjoyed a smoky flavor in a beverage.",
  "Put a finger down if you have tried a savory drink out of curiosity.",
  "Put a finger down if you have requested less sweetness in a mixed drink.",
  "Put a finger down if you have asked for extra citrus in your beverage.",
  "Put a finger down if you have ordered something simply because it was served frozen.",
  "Put a finger down if you have chosen a warm drink on a cold night out.",
  "Put a finger down if you have picked a sparkling drink for a celebration.",
  "Put a finger down if you have compared two versions of the same classic drink.",
  "Put a finger down if you have learned the difference between shaken and stirred from a bartender.",
  "Put a finger down if you have asked what glassware a drink would arrive in.",
  "Put a finger down if you have been surprised by an edible flower in your drink.",
  "Put a finger down if you have saved a memorable drink menu as a souvenir.",
  "Put a finger down if you have ordered a local beverage while traveling.",
  "Put a finger down if you have tried a seasonal drink before the season ended.",
  "Put a finger down if you have chosen a familiar beverage at an unfamiliar venue.",
  "Put a finger down if you have asked for a sample before choosing from a tap list.",
  "Put a finger down if you have changed your order after hearing someone else's choice.",
  "Put a finger down if you have struggled to pronounce a beverage on the menu.",
  "Put a finger down if you have pointed at the menu to make sure your order was understood.",
  "Put a finger down if you have ordered a drink based on its color.",
  "Put a finger down if you have preferred a simple beverage over a complicated specialty drink.",
  "Put a finger down if you have asked for your drink without a garnish.",
  "Put a finger down if you have discovered that a favorite drink tastes different with fresh herbs.",
  "Put a finger down if you have watched a bartender make a drink with unexpected technique.",
  "Put a finger down if you have recognized a beverage by its aroma before tasting it.",
  "Put a finger down if you have chosen a drink because it came in a reusable cup.",
  "Put a finger down if you have brought your own bottle opener to a picnic.",
  "Put a finger down if you have chilled a glass before serving a beverage at home.",
  "Put a finger down if you have made decorative ice for a gathering.",
  "Put a finger down if you have used frozen fruit instead of ice in a party drink.",
  "Put a finger down if you have labeled drink pitchers so guests knew what was inside.",
  "Put a finger down if you have created a beverage station for guests to serve themselves.",
  "Put a finger down if you have brought a favorite mixer to a gathering.",
  "Put a finger down if you have contributed fresh fruit to a shared drink table.",
  "Put a finger down if you have matched a party drink to the event's color theme.",
  "Put a finger down if you have served a beverage in a container that was clearly the wrong shape.",
  "Put a finger down if you have improvised a drink stirrer from a clean kitchen utensil.",
  "Put a finger down if you have forgotten to chill a beverage before guests arrived.",
  "Put a finger down if you have run out of ice during a gathering.",
  "Put a finger down if you have bought too many mixers for a small event.",
  "Put a finger down if you have taken leftover unopened drinks home after a party.",
  "Put a finger down if you have found a new use for an attractive empty bottle.",

  "Put a finger down if you have ordered a mocktail that looked identical to a cocktail.",
  "Put a finger down if you have preferred the alcohol-free version of a menu specialty.",
  "Put a finger down if you have asked whether a cocktail could be made without alcohol.",
  "Put a finger down if you have found an alcohol-free beer you genuinely enjoyed.",
  "Put a finger down if you have tried an alcohol-free wine at a celebration.",
  "Put a finger down if you have made a mocktail with herbs from your kitchen.",
  "Put a finger down if you have used tea as the base of a party drink.",
  "Put a finger down if you have mixed sparkling water with fruit for a festive option.",
  "Put a finger down if you have served mocktails in the same glassware as other drinks.",
  "Put a finger down if you have brought an alcohol-free option to share at a gathering.",
  "Put a finger down if you have been excited to see a full mocktail section on a menu.",
  "Put a finger down if you have asked a server for their best non-alcoholic recommendation.",
  "Put a finger down if you have ordered a mocktail because you wanted the garnish.",
  "Put a finger down if you have invented a name for a homemade mocktail.",
  "Put a finger down if you have discovered that shrubs can be used in alcohol-free drinks.",
  "Put a finger down if you have used coconut water in a celebratory beverage.",
  "Put a finger down if you have made a frozen alcohol-free drink for hot weather.",
  "Put a finger down if you have recreated a restaurant mocktail at home.",
  "Put a finger down if you have asked for a non-alcoholic drink that was not overly sweet.",
  "Put a finger down if you have enjoyed a mocktail pairing with a meal.",
  "Put a finger down if you have chosen ginger beer as your whole drink rather than a mixer.",
  "Put a finger down if you have celebrated with sparkling juice.",
  "Put a finger down if you have used fancy ice to make water feel party-ready.",
  "Put a finger down if you have garnished a soft drink for a special occasion.",
  "Put a finger down if you have offered guests both alcoholic and alcohol-free versions of one recipe.",
  "Put a finger down if you have kept alcohol-free choices in a separate labeled cooler.",
  "Put a finger down if you have appreciated a host who listed every drink ingredient.",
  "Put a finger down if you have checked that bitters in a mocktail were truly alcohol-free.",
  "Put a finger down if you have found a zero-proof spirit more interesting than expected.",
  "Put a finger down if you have attended an event with an alcohol-free bar.",
  "Put a finger down if you have visited a venue specifically for its mocktail menu.",
  "Put a finger down if you have ordered a hot chocolate while everyone else browsed the bar menu.",
  "Put a finger down if you have carried a cup of tea around at a party.",
  "Put a finger down if you have chosen lemonade for a formal toast.",
  "Put a finger down if you have discovered a favorite cordial at an alcohol-free gathering.",

  "Put a finger down if you have given a toast without preparing any words first.",
  "Put a finger down if you have practiced a toast quietly before saying it aloud.",
  "Put a finger down if you have kept a toast short because emotions took over.",
  "Put a finger down if you have raised a glass with water in it.",
  "Put a finger down if you have joined a toast over a video call.",
  "Put a finger down if you have toasted a small everyday win.",
  "Put a finger down if you have accidentally started a toast while someone else was speaking.",
  "Put a finger down if you have clinked glasses too enthusiastically.",
  "Put a finger down if you have reached awkwardly across a table for a group toast.",
  "Put a finger down if you have made eye contact with everyone during a toast.",
  "Put a finger down if you have forgotten the final words of a traditional toast.",
  "Put a finger down if you have translated a toast for someone at the table.",
  "Put a finger down if you have learned a toast in another language.",
  "Put a finger down if you have toasted with an empty glass because yours had not arrived.",
  "Put a finger down if you have used a coffee mug for a celebratory toast.",
  "Put a finger down if you have been thanked in someone else's toast.",
  "Put a finger down if you have laughed in the middle of delivering a heartfelt toast.",
  "Put a finger down if you have turned a toast into an unexpected story.",
  "Put a finger down if you have volunteered to speak when nobody else would start the toast.",
  "Put a finger down if you have raised your drink from the back of a crowded room.",
  "Put a finger down if you have toasted someone who could not attend in person.",
  "Put a finger down if you have joined a toast without knowing what was being celebrated.",
  "Put a finger down if you have heard the same family toast at several gatherings.",
  "Put a finger down if you have saved a meaningful toast in your phone notes.",
  "Put a finger down if you have chosen not to clink delicate glassware during a toast.",

  "Put a finger down if you have waited patiently while a bartender finished another order.",
  "Put a finger down if you have returned an empty glass to the designated collection point.",
  "Put a finger down if you have moved aside after ordering so the next person could reach the bar.",
  "Put a finger down if you have asked before taking an open seat at a shared table.",
  "Put a finger down if you have saved a friend's seat while they collected a drink.",
  "Put a finger down if you have offered the menu to someone who arrived after you.",
  "Put a finger down if you have split a bar tab evenly after everyone agreed.",
  "Put a finger down if you have requested separate checks at the start of an outing.",
  "Put a finger down if you have covered a friend's soft drink while they handled the tip.",
  "Put a finger down if you have double-checked a bill before the group paid.",
  "Put a finger down if you have spotted an item on your tab that belonged to another table.",
  "Put a finger down if you have closed your tab earlier than the rest of your group.",
  "Put a finger down if you have remembered to take your card back after closing a tab.",
  "Put a finger down if you have tipped for a thoughtfully made alcohol-free drink.",
  "Put a finger down if you have complimented a bartender on a balanced beverage.",
  "Put a finger down if you have asked before moving a chair between tables.",
  "Put a finger down if you have lowered your voice after noticing nearby guests were talking.",
  "Put a finger down if you have stepped outside to take a phone call at a busy venue.",
  "Put a finger down if you have helped clear cups after a house party.",
  "Put a finger down if you have wiped up a spill before anyone stepped in it.",
  "Put a finger down if you have told staff about broken glass on the floor.",
  "Put a finger down if you have used a coaster to protect someone else's furniture.",
  "Put a finger down if you have written your name on a reusable party cup.",
  "Put a finger down if you have kept track of your own drink throughout an event.",
  "Put a finger down if you have declined a drink that you did not watch being prepared.",
  "Put a finger down if you have asked what was in a punch before deciding whether to have it.",
  "Put a finger down if you have warned guests that a shared punch contained alcohol.",
  "Put a finger down if you have separated serving tools for different drink ingredients.",
  "Put a finger down if you have checked a guest's allergy needs before mixing their drink.",
  "Put a finger down if you have kept an ingredient label available beside a party beverage.",
  "Put a finger down if you have asked permission before topping up someone's glass.",
  "Put a finger down if you have accepted a declined drink offer without asking for a reason.",
  "Put a finger down if you have changed the subject when someone was pressured to explain not drinking.",
  "Put a finger down if you have made sure a guest had a non-alcoholic option without singling them out.",
  "Put a finger down if you have handed someone the sealed can or bottle they requested.",
  "Put a finger down if you have avoided commenting on how much another person was drinking.",
  "Put a finger down if you have helped a friend retrieve a coat before leaving a venue.",
  "Put a finger down if you have checked the closing time before settling into a bar.",
  "Put a finger down if you have left a venue calmly when staff announced last call.",
  "Put a finger down if you have waited indoors with a friend until their ride arrived.",
  "Put a finger down if you have shared a taxi with friends after a night out.",
  "Put a finger down if you have chosen a meeting point in case your group got separated.",
  "Put a finger down if you have sent the group a message before leaving an event early.",
  "Put a finger down if you have returned a borrowed jacket after a chilly walk home.",
  "Put a finger down if you have thanked the host before leaving a gathering.",

  "Put a finger down if you have met a new friend while waiting to order a beverage.",
  "Put a finger down if you have bonded with someone over choosing the same drink.",
  "Put a finger down if you have joined a conversation about an unusual menu item.",
  "Put a finger down if you have played a board game at a bar or cafe.",
  "Put a finger down if you have attended a trivia night without ordering alcohol.",
  "Put a finger down if you have sung karaoke while holding a non-alcoholic drink.",
  "Put a finger down if you have danced at a party after switching to water.",
  "Put a finger down if you have taken a group photo with everyone's drinks in the frame.",
  "Put a finger down if you have decorated cups for a themed party.",
  "Put a finger down if you have worn an outfit inspired by a party's drink theme.",
  "Put a finger down if you have attended a tasting where spitting samples out was welcomed.",
  "Put a finger down if you have taken notes at a beverage tasting.",
  "Put a finger down if you have correctly identified a flavor during a blind tasting.",
  "Put a finger down if you have confidently guessed the wrong flavor in a drink.",
  "Put a finger down if you have hosted a blind taste test with alcohol-free beverages.",
  "Put a finger down if you have voted for a favorite homemade mocktail at a party.",
  "Put a finger down if you have traded drink recipes with another guest.",
  "Put a finger down if you have learned a family beverage recipe at a celebration.",
  "Put a finger down if you have brought a thermos of something warm to an outdoor gathering.",
  "Put a finger down if you have packed canned drinks for a picnic and forgotten the cooler.",
  "Put a finger down if you have opened a beverage at the exact moment a speech began.",
  "Put a finger down if you have tried to quietly unwrap a straw during a formal event.",
  "Put a finger down if you have been the person who knew where the bottle opener was.",
  "Put a finger down if you have used a phone flashlight to read a dim drink menu.",
  "Put a finger down if you have moved to better lighting to check a beverage label.",
  "Put a finger down if you have asked the DJ to announce that water was available.",
  "Put a finger down if you have refilled the water pitcher at a shared table.",
  "Put a finger down if you have brought extra reusable cups when a host ran short.",
  "Put a finger down if you have helped arrange bottles by type before guests arrived.",
  "Put a finger down if you have set out recycling bins for cans and bottles at a party.",
  "Put a finger down if you have collected unopened beverages for the host at the end of the night.",
  "Put a finger down if you have stayed to help wash glassware after a celebration.",
  "Put a finger down if you have made a playlist while someone else handled the drinks.",
  "Put a finger down if you have served snacks while guests chose their beverages.",
  "Put a finger down if you have joined a party late and gone straight to the water station.",
  "Put a finger down if you have left a crowded dance floor for a quiet beverage break.",
  "Put a finger down if you have suggested a cafe when friends first proposed meeting at a bar.",
  "Put a finger down if you have enjoyed a social event more because drinking was not the focus.",
  "Put a finger down if you have attended a celebration where every beverage was alcohol-free.",
  "Put a finger down if you have hosted a morning gathering with coffee and juice instead of a bar.",

  "Put a finger down if you have volunteered to be the designated driver before an outing.",
  "Put a finger down if you have stayed alcohol-free because you were driving later.",
  "Put a finger down if you have handed your car keys to a sober driver for the evening.",
  "Put a finger down if you have booked a ride home before arriving at an event.",
  "Put a finger down if you have checked the final public transport time before going out.",
  "Put a finger down if you have changed plans so everyone had safe transport home.",
  "Put a finger down if you have left your car overnight and collected it the next day.",
  "Put a finger down if you have offered a sober friend petrol money for driving the group.",
  "Put a finger down if you have thanked a designated driver with their favorite snack.",
  "Put a finger down if you have confirmed that your ride home had arrived before leaving friends.",
  "Put a finger down if you have shared your ride details with someone you trusted.",
  "Put a finger down if you have walked a friend to their verified ride.",
  "Put a finger down if you have refused to ride with someone who had been drinking.",
  "Put a finger down if you have helped arrange safe transport for someone else.",
  "Put a finger down if you have chosen a nearby venue so everyone could get home safely.",
  "Put a finger down if you have stayed over at the host's place instead of driving.",
  "Put a finger down if you have made space for an overnight guest who should not drive.",
  "Put a finger down if you have gone back for a forgotten car the morning after an event.",
  "Put a finger down if you have used a transport app's group ride feature after a party.",
  "Put a finger down if you have designated a pickup spot away from a crowded venue entrance.",
  "Put a finger down if you have alternated your chosen drinks with water during a social event.",
  "Put a finger down if you have kept a water bottle beside your party drink.",
  "Put a finger down if you have paused for food during a long celebration.",
  "Put a finger down if you have eaten before going to an event where alcohol was served.",
  "Put a finger down if you have chosen a smaller glass because that suited your evening.",
  "Put a finger down if you have stopped drinking alcohol earlier than you originally expected.",
  "Put a finger down if you have switched to an alcohol-free drink midway through an outing.",
  "Put a finger down if you have set a personal limit before attending a party.",
  "Put a finger down if you have tracked your own drinks privately to stay within your plan.",
  "Put a finger down if you have skipped a round because you wanted more time between drinks.",
  "Put a finger down if you have declined a refill because you were still enjoying your current drink.",
  "Put a finger down if you have chosen not to finish a drink you no longer wanted.",
  "Put a finger down if you have left a stronger-than-expected drink unfinished.",
  "Put a finger down if you have asked how strong a drink was before ordering it.",
  "Put a finger down if you have checked the alcohol percentage on a can or bottle.",
  "Put a finger down if you have selected a lower-alcohol option from a menu.",
  "Put a finger down if you have slowed your pace when a celebration lasted longer than planned.",
  "Put a finger down if you have taken a break from the bar to get fresh air with friends.",
  "Put a finger down if you have noticed you felt different and decided to stop drinking alcohol.",
  "Put a finger down if you have told a trusted friend about your plan for the evening.",
  "Put a finger down if you have checked in with yourself before deciding on another drink.",
  "Put a finger down if you have filled your water bottle before going to bed after a party.",
  "Put a finger down if you have prepared a simple breakfast before a late night out.",
  "Put a finger down if you have kept an easy meal ready for the morning after a celebration.",
  "Put a finger down if you have prioritized sleep after returning from a social event.",
  "Put a finger down if you have cleared your next morning's schedule after a late celebration.",
  "Put a finger down if you have packed sunscreen and water for a daytime festival.",
  "Put a finger down if you have taken shade breaks at an outdoor event serving drinks.",
  "Put a finger down if you have worn comfortable shoes because you planned to walk home safely.",
  "Put a finger down if you have checked a medication label before deciding whether to drink alcohol.",
  "Put a finger down if you have asked a pharmacist whether a prescription changed your beverage options.",
  "Put a finger down if you have followed medication guidance by selecting a zero-proof option.",
  "Put a finger down if you have skipped alcohol while recovering from an illness.",
  "Put a finger down if you have avoided alcohol because you needed to be alert early the next day.",
  "Put a finger down if you have chosen not to drink because you simply did not feel like it.",
  "Put a finger down if you have gone to a bar and ordered only food.",
  "Put a finger down if you have attended happy hour for the snacks rather than the alcohol.",
  "Put a finger down if you have held the same alcohol-free drink all evening.",
  "Put a finger down if you have answered a drink offer with a simple no thank you.",
  "Put a finger down if you have supported a friend who changed their mind about drinking.",
  "Put a finger down if you have offered to leave an event with a friend who felt uncomfortable.",
  "Put a finger down if you have checked that a friend got home safely after a night out.",
  "Put a finger down if you have stayed with a friend who became unwell and sought appropriate help.",
  "Put a finger down if you have asked venue staff for help when someone seemed seriously unwell.",
  "Put a finger down if you have kept flirting separate from assumptions about someone's drink choice.",
  "Put a finger down if you have checked for clear consent even when the evening included alcohol.",
  "Put a finger down if you have stopped an intimate moment when consent became unclear.",
  "Put a finger down if you have respected someone's decision to leave a party alone or with friends.",
  "Put a finger down if you have reminded your group that nobody owed an explanation for staying sober.",

  "Put a finger down if you have accidentally taken someone else's identical water glass.",
  "Put a finger down if you have received the wrong drink and noticed before tasting it.",
  "Put a finger down if you have ordered still water and been served sparkling water.",
  "Put a finger down if you have mistaken a decorative drink display for an available menu choice.",
  "Put a finger down if you have mistaken tonic water for plain sparkling water.",
  "Put a finger down if you have confused ginger ale with ginger beer.",
  "Put a finger down if you have expected a drink to be sweet and found it sour.",
  "Put a finger down if you have expected a cold drink and received it warm.",
  "Put a finger down if you have put a straw into the wrong cup at a crowded table.",
  "Put a finger down if you have carried several beverages back to the table and forgotten which was yours.",
  "Put a finger down if you have mixed up identical reusable cups at a picnic.",
  "Put a finger down if you have read the wrong line on a drink menu and surprised yourself.",
  "Put a finger down if you have misheard a bartender and agreed to a flavor you did not recognize.",
  "Put a finger down if you have ordered by pointing and received the item beside your choice.",
  "Put a finger down if you have thought a garnish was a snack and eaten it first.",
  "Put a finger down if you have tried to drink through a decorative stirrer instead of the straw.",
  "Put a finger down if you have squeezed a citrus garnish and splashed the table.",
  "Put a finger down if you have dropped an ice cube while transferring it to your glass.",
  "Put a finger down if you have opened a fizzy drink that foamed over unexpectedly.",
  "Put a finger down if you have shaken a canned drink before remembering it was carbonated.",
  "Put a finger down if you have spilled a drink while trying to pose for a photo.",
  "Put a finger down if you have knocked over your own water while protecting someone else's drink.",
  "Put a finger down if you have put your coaster on top of your drink and then forgotten why.",
  "Put a finger down if you have searched for your cup while it was already in your hand.",
  "Put a finger down if you have walked away from the bar without the drink you paid for.",
  "Put a finger down if you have returned to a table with napkins but forgotten the beverages.",
  "Put a finger down if you have brought the wrong mixer to a homemade drink station.",
  "Put a finger down if you have labeled a drink jug and later realized the label was wrong.",
  "Put a finger down if you have frozen fruit for drinks and eaten it before guests arrived.",
  "Put a finger down if you have made a beautiful party drink and forgotten to photograph it.",
  "Put a finger down if you have learned that your first-choice drink was sold out after ordering it.",
  "Put a finger down if you have struggled with a stubborn cork while everyone watched.",
  "Put a finger down if you have worn a festival wristband that identified your alcohol-free choice.",
  "Put a finger down if you have used a cup charm to distinguish your drink at a gathering.",
  "Put a finger down if you have carried a cardboard drink holder farther than expected.",
  "Put a finger down if you have returned to a drink after all its ice had melted.",
] as const satisfies readonly string[]
