export const PUT_FINGER_FRIENDS = [
  "Put a finger down if you have a group chat that is active before you wake up.",
  "Put a finger down if you have muted a busy group chat so you could focus.",
  "Put a finger down if you have returned to a group chat after missing hundreds of messages.",
  "Put a finger down if you have renamed a group chat after a memorable moment.",
  "Put a finger down if you have used a group chat poll to settle a plan.",
  "Put a finger down if you have sent a message to the wrong friendship group chat.",
  "Put a finger down if you have watched a group chat become lively at an unexpected hour.",
  "Put a finger down if you have shared good news with a group chat before posting it elsewhere.",
  "Put a finger down if you have asked a group chat for a quick recommendation.",
  "Put a finger down if you have revived an old group chat for a reunion.",
  "Put a finger down if you have reacted to a friend's message when you had no time to reply.",
  "Put a finger down if you have sent a voice note because typing could not capture the story.",
  "Put a finger down if you have listened to a friend's long voice note in several parts.",
  "Put a finger down if you have shared a harmless meme that perfectly matched a friend's mood.",
  "Put a finger down if you have used a private joke as a group chat name.",
  "Put a finger down if you have checked whether everyone was comfortable before adding someone to a chat.",
  "Put a finger down if you have moved a sensitive conversation out of a group chat.",
  "Put a finger down if you have helped catch up a friend who missed the chat discussion.",
  "Put a finger down if you have sent a reminder in a group chat that saved the plan.",
  "Put a finger down if you have typed a reply in a group chat and decided it was better left unsent.",
  "Put a finger down if you have celebrated a friend's small win with an enthusiastic message thread.",
  "Put a finger down if you have shared photos in a group chat only after checking everyone was comfortable.",
  "Put a finger down if you have started a separate chat to organize a surprise for a friend.",
  "Put a finger down if you have used a group chat to coordinate help for someone.",
  "Put a finger down if you have suggested pausing a tense group chat conversation until everyone felt calmer.",
  "Put a finger down if a friend has shown up for an event that mattered deeply to you.",
  "Put a finger down if you have attended a friend's event even though you knew almost nobody there.",
  "Put a finger down if you have helped a friend prepare for an important day.",
  "Put a finger down if you have waited with a friend who did not want to be alone.",
  "Put a finger down if you have checked that a friend got home safely.",
  "Put a finger down if you have brought a friend something useful when they were having a difficult week.",
  "Put a finger down if you have rearranged a flexible plan to support a friend.",
  "Put a finger down if a friend has remembered an important detail you mentioned in passing.",
  "Put a finger down if you have helped a friend practice for a presentation or interview.",
  "Put a finger down if you have accompanied a friend somewhere because they wanted company.",
  "Put a finger down if you have quietly handled a practical task while a friend was overwhelmed.",
  "Put a finger down if you have stayed until the end to help a friend clean up after hosting.",
  "Put a finger down if you have offered a friend a ride when their plans changed.",
  "Put a finger down if a friend has defended your need for rest when others wanted to keep going.",
  "Put a finger down if you have made sure a quieter friend had room to speak.",
  "Put a finger down if you have brought an extra item because you knew a friend might forget theirs.",
  "Put a finger down if you have helped a friend move something heavy or awkward.",
  "Put a finger down if you have kept a friend company during a long wait.",
  "Put a finger down if you have offered specific help instead of only saying to reach out.",
  "Put a finger down if a friend has checked on you after a day you were nervous about.",
  "Put a finger down if you have stayed on a call while a friend completed a stressful task.",
  "Put a finger down if you have made space for a friend whose energy was lower than usual.",
  "Put a finger down if you have helped a friend solve a problem without taking over.",
  "Put a finger down if you have celebrated a friend's progress before the final result arrived.",
  "Put a finger down if a friend has made an ordinary day feel important by showing up.",
  "Put a finger down if you have spent longer choosing a date for a meetup than attending it.",
  "Put a finger down if you have created a shared list for a trip with friends.",
  "Put a finger down if you have planned a low-cost hangout so everyone could join.",
  "Put a finger down if you have changed an activity to make it more accessible for a friend.",
  "Put a finger down if you have volunteered to make the reservation for the group.",
  "Put a finger down if you have planned a meetup around everyone's travel time.",
  "Put a finger down if you have suggested a backup plan because the weather looked uncertain.",
  "Put a finger down if you have packed snacks to share during a day out with friends.",
  "Put a finger down if you have made an itinerary that your friends treated as optional.",
  "Put a finger down if you have chosen a familiar venue to help a new friend feel comfortable.",
  "Put a finger down if you have turned a routine errand into time with a friend.",
  "Put a finger down if you have organized a recurring catch-up that lasted for months.",
  "Put a finger down if you have hosted friends with whatever food was already available.",
  "Put a finger down if you have planned a day around one activity everyone was excited about.",
  "Put a finger down if you have joined a friend's hobby for a single afternoon.",
  "Put a finger down if you have suggested staying in when the original plan felt too tiring.",
  "Put a finger down if you have coordinated a shared gift without revealing the surprise.",
  "Put a finger down if you have made plans far in advance because your calendars rarely align.",
  "Put a finger down if you have had a spontaneous meetup work better than the carefully planned one.",
  "Put a finger down if you have split planning duties according to what each friend enjoys doing.",
  "Put a finger down if you have checked dietary needs before choosing food for a gathering.",
  "Put a finger down if you have built free time into a group trip so nobody felt rushed.",
  "Put a finger down if you have rescheduled plans without treating the change as a personal slight.",
  "Put a finger down if you have made a shared calendar entry for a friendship tradition.",
  "Put a finger down if a simple walk with a friend became the highlight of your week.",
  "Put a finger down if you and a friend can communicate an entire reaction with one look.",
  "Put a finger down if you have laughed with a friend about a joke nobody else understood.",
  "Put a finger down if an ordinary phrase reminds you of one particular friend.",
  "Put a finger down if you have given a friend a nickname that became more familiar than their full name.",
  "Put a finger down if you and a friend always retell the same favorite story.",
  "Put a finger down if you have a photo with friends that becomes funnier every time you see it.",
  "Put a finger down if you have recreated an old picture with a friend years later.",
  "Put a finger down if a friend has sent you something with no explanation because they knew you would understand.",
  "Put a finger down if you have a shared tradition that started by accident.",
  "Put a finger down if you and a friend remember completely different versions of the same harmless event.",
  "Put a finger down if a song has become unofficially linked to your friendship.",
  "Put a finger down if you have quoted a favorite show back and forth with a friend.",
  "Put a finger down if you have laughed at the wrong moment because a friend made eye contact.",
  "Put a finger down if you have a running joke that has lasted longer than anyone expected.",
  "Put a finger down if you have invented a silly award for someone in your friend group.",
  "Put a finger down if you have turned a friend's minor typo into a lasting joke they also enjoy.",
  "Put a finger down if you and a friend use the same greeting every time you meet.",
  "Put a finger down if you have exchanged a small object that carries a funny friendship story.",
  "Put a finger down if a shared meal has become part of your friendship routine.",
  "Put a finger down if you have a friend who always knows which story you are about to tell.",
  "Put a finger down if you have laughed again while trying to explain why something was funny.",
  "Put a finger down if you have kept a harmless souvenir from a memorable day with friends.",
  "Put a finger down if you and a friend have a playful disagreement that never gets settled.",
  "Put a finger down if a joke with friends has made a difficult day feel lighter.",
  "Put a finger down if you have supported a friend's decision even when you would have chosen differently.",
  "Put a finger down if you have asked a friend whether they wanted advice or simply someone to listen.",
  "Put a finger down if a friend has reminded you of your strengths when you forgot them.",
  "Put a finger down if you have encouraged a friend to take an opportunity they were excited about.",
  "Put a finger down if you have listened to a friend rehearse the same concern more than once.",
  "Put a finger down if you have helped a friend notice how much progress they made.",
  "Put a finger down if a friend has made you feel welcome when you were new somewhere.",
  "Put a finger down if you have sent a thoughtful message before a friend's challenging day.",
  "Put a finger down if you have respected a friend's wish for quiet while still letting them know you cared.",
  "Put a finger down if you have offered encouragement without promising that everything would be easy.",
  "Put a finger down if a friend has helped you laugh at a manageable mistake.",
  "Put a finger down if you have learned how a friend prefers to receive support.",
  "Put a finger down if you have helped a friend break a big task into smaller steps.",
  "Put a finger down if a friend has cheered for a goal that mattered only because it mattered to you.",
  "Put a finger down if you have noticed a friend needed inclusion without making them explain why.",
  "Put a finger down if you have thanked a friend for trusting you with an honest feeling.",
  "Put a finger down if a friend has encouraged you to set a boundary that protected your energy.",
  "Put a finger down if you have checked in after giving a friend time to process something.",
  "Put a finger down if you have recommended a helpful resource without pressuring a friend to use it.",
  "Put a finger down if a friend has celebrated your effort even when the outcome was uncertain.",
  "Put a finger down if you have reminded a friend that changing their mind was allowed.",
  "Put a finger down if you have accepted that a friend needed support from someone else.",
  "Put a finger down if a friend has helped you see a situation from a kinder angle.",
  "Put a finger down if you have made room for both hope and frustration in the same conversation.",
  "Put a finger down if you have told a friend exactly what you appreciate about them.",
  "Put a finger down if you have realized a friend misunderstood your tone in a text.",
  "Put a finger down if you have apologized to a friend without adding an excuse.",
  "Put a finger down if a friendship improved after an honest conversation.",
  "Put a finger down if you have asked what a friend meant instead of assuming the worst.",
  "Put a finger down if you have discovered that two friends remembered a plan differently.",
  "Put a finger down if you have taken a break before replying to a frustrating message.",
  "Put a finger down if you have admitted that you forgot something a friend told you.",
  "Put a finger down if a friend has gently pointed out that your joke did not land well.",
  "Put a finger down if you have corrected a misunderstanding before it grew into a larger conflict.",
  "Put a finger down if you have accepted an apology while still needing time to rebuild trust.",
  "Put a finger down if you have clarified whether a plan was tentative or confirmed.",
  "Put a finger down if you have learned that silence from a friend did not mean anger.",
  "Put a finger down if you have revisited a conversation after both of you had time to think.",
  "Put a finger down if you have owned your part in a disagreement with a friend.",
  "Put a finger down if a friend has explained how your actions affected them in a way you had not noticed.",
  "Put a finger down if you have chosen a call instead of continuing a confusing text exchange.",
  "Put a finger down if you have realized you were solving a problem when your friend wanted empathy.",
  "Put a finger down if you have asked for clarification about an invitation rather than feeling excluded in silence.",
  "Put a finger down if you have repaired a friendship after a missed expectation.",
  "Put a finger down if you have accepted that friends can disagree without choosing sides.",
  "Put a finger down if you have changed a habit after a friend explained why it bothered them.",
  "Put a finger down if you have given a sincere apology for arriving late.",
  "Put a finger down if a misunderstanding ended up teaching you how to communicate better.",
  "Put a finger down if you have asked a friend for a fresh start after clearing the air.",
  "Put a finger down if you have a friend who lives in a different time zone.",
  "Put a finger down if you have scheduled a call with a faraway friend weeks ahead.",
  "Put a finger down if you have sent a postcard or letter to a friend who lives far away.",
  "Put a finger down if you have watched something at the same time as a distant friend.",
  "Put a finger down if you have celebrated a friend's milestone through a video call.",
  "Put a finger down if you have picked up with a distant friend as though no time had passed.",
  "Put a finger down if you have exchanged photos of ordinary daily life with a faraway friend.",
  "Put a finger down if you have planned a visit around finally seeing a long-distance friend.",
  "Put a finger down if you have missed a friend's call because you miscalculated the time difference.",
  "Put a finger down if you have maintained a friendship mostly through voice notes.",
  "Put a finger down if a friend moved away and introduced you to their new city from afar.",
  "Put a finger down if you have mailed a small surprise to remind a distant friend you were thinking of them.",
  "Put a finger down if you have kept a standing online game night with friends in different places.",
  "Put a finger down if you have saved a story until you could tell a faraway friend properly.",
  "Put a finger down if you have reconnected with a friend after months without talking.",
  "Put a finger down if you have learned to value occasional meaningful messages over constant contact.",
  "Put a finger down if you have introduced a local friend to someone you first knew online.",
  "Put a finger down if you have marked a distant friend's local time in your calendar.",
  "Put a finger down if you have shared a virtual meal with a friend in another place.",
  "Put a finger down if you have taken a friend on a video tour of your new surroundings.",
  "Put a finger down if you have made a playlist with a friend you rarely see in person.",
  "Put a finger down if you have adjusted your expectations as a friendship became long-distance.",
  "Put a finger down if you have met a longtime online friend in person with a mutually agreed plan.",
  "Put a finger down if a distant friend has remembered your routine despite never seeing it firsthand.",
  "Put a finger down if you have counted down the days until a friend returned for a visit.",
  "Put a finger down if you have remembered a friend's birthday without relying on a notification.",
  "Put a finger down if you have organized a celebration that matched a friend's personality.",
  "Put a finger down if you have written a heartfelt message in a friend's birthday card.",
  "Put a finger down if you have celebrated a friendship anniversary or meaningful shared date.",
  "Put a finger down if you have cheered for a friend completing a personal project.",
  "Put a finger down if you have made a homemade gift for a friend.",
  "Put a finger down if you have gathered messages from several people for a friend's celebration.",
  "Put a finger down if you have celebrated a friend choosing a new direction.",
  "Put a finger down if you have planned a quiet celebration because that was what your friend preferred.",
  "Put a finger down if you have brought a friend's favorite snack to mark good news.",
  "Put a finger down if you have applauded a friend for finishing something that took a long time.",
  "Put a finger down if you have celebrated a friend setting a healthy boundary.",
  "Put a finger down if you have made a toast with any kind of drink to honor a friend's achievement.",
  "Put a finger down if you have taken photos for a friend who wanted to remember a special day.",
  "Put a finger down if you have helped decorate for a friend's gathering.",
  "Put a finger down if you have celebrated a friend's first attempt rather than waiting for mastery.",
  "Put a finger down if you have surprised a friend with a small gesture on an ordinary day.",
  "Put a finger down if you have joined a celebration remotely because you could not attend in person.",
  "Put a finger down if you have made sure a celebration included the friend being honored in the decisions.",
  "Put a finger down if you have saved a meaningful date because it mattered to your friend.",
  "Put a finger down if you have congratulated a friend privately because they dislike public attention.",
  "Put a finger down if you have celebrated a friend's courage to try again after disappointment.",
  "Put a finger down if you have created a tradition around welcoming a friend home.",
  "Put a finger down if a friend's good news has improved your whole day.",
  "Put a finger down if you have asked before sharing a friend's news with other people.",
  "Put a finger down if you have said no to a plan without inventing an excuse.",
  "Put a finger down if a friend has respected your need to leave an event early.",
  "Put a finger down if you have asked permission before giving a friend a hug.",
  "Put a finger down if you have accepted that a friend did not want to discuss a personal topic.",
  "Put a finger down if you have told friends when you needed time alone.",
  "Put a finger down if you have checked before inviting an extra person to shared plans.",
  "Put a finger down if you have kept a confidence that a friend trusted you with.",
  "Put a finger down if you have asked before posting a photo that included a friend.",
  "Put a finger down if you have stopped teasing when a friend said a joke was uncomfortable.",
  "Put a finger down if you have explained your communication limits during a busy period.",
  "Put a finger down if you have accepted a friend's no without asking them to justify it.",
  "Put a finger down if you have requested advance notice before friends visit your home.",
  "Put a finger down if a friend has given you honest feedback with care and privacy.",
  "Put a finger down if you have declined to take sides in a conflict between friends.",
  "Put a finger down if you have asked whether a story was yours to share.",
  "Put a finger down if you have left a group activity when you reached your social limit.",
  "Put a finger down if you have made it easy for a friend to change their mind about a plan.",
  "Put a finger down if you have told a friend when a nickname no longer felt right.",
  "Put a finger down if you have respected a friend's preference not to be tagged online.",
  "Put a finger down if you have asked for space without ending the friendship.",
  "Put a finger down if a friend has returned something they borrowed without needing a reminder.",
  "Put a finger down if you have chosen not to pressure a friend for an immediate reply.",
  "Put a finger down if you have protected time already promised to yourself.",
  "Put a finger down if you and a friend have agreed on a boundary that made the friendship easier.",
  "Put a finger down if you have corrected someone who volunteered you for a plan without asking.",
  "Put a finger down if you are the friend who usually confirms the plan on the day.",
  "Put a finger down if you have arrived early to help a friend set up.",
  "Put a finger down if you have returned a borrowed item in better condition than you received it.",
  "Put a finger down if you have followed through on a small promise a friend might have forgotten.",
  "Put a finger down if a friend has trusted you to handle an important part of a shared plan.",
  "Put a finger down if you have told friends promptly when you could no longer attend.",
  "Put a finger down if you have remembered to bring the one thing the whole group needed.",
  "Put a finger down if you have kept checking in consistently after the first difficult day passed.",
  "Put a finger down if you have paid your share of a group expense without being chased.",
  "Put a finger down if you have taken notes because your friends trusted you with the details.",
  "Put a finger down if a friend has been your dependable emergency contact for ordinary mishaps.",
  "Put a finger down if you have admitted early that you could not complete a promised task.",
  "Put a finger down if you have remembered a friend's preference while ordering for the group.",
  "Put a finger down if you have looked after a friend's belongings while they stepped away.",
  "Put a finger down if you have kept a recurring plan even when everyone was busy.",
  "Put a finger down if a friend has helped you without keeping score.",
  "Put a finger down if you have shared accurate directions so nobody was left wandering.",
  "Put a finger down if you have followed up with information you promised to find.",
  "Put a finger down if you have been trusted to choose the meeting place for everyone.",
  "Put a finger down if you have taken responsibility for a mistake that affected a group plan.",
  "Put a finger down if a friend has saved you a seat without making a fuss.",
  "Put a finger down if you have made sure a friend was not left out of an important update.",
  "Put a finger down if you have returned a friend's container after receiving food in it.",
  "Put a finger down if you have kept your phone available when a friend was relying on you.",
  "Put a finger down if you have earned a friend's trust gradually through consistent actions.",
  "Put a finger down if you have introduced yourself to someone who seemed new to the group.",
  "Put a finger down if you have made a new friend through a shared hobby.",
  "Put a finger down if you have exchanged contact details with someone after one great conversation.",
  "Put a finger down if you have invited a new acquaintance to join a low-pressure group activity.",
  "Put a finger down if a mutual friend introduced you to someone you now contact directly.",
  "Put a finger down if you have become friends with someone whose first impression of you was inaccurate.",
  "Put a finger down if you have started a friendship while waiting in the same long line.",
  "Put a finger down if you have made a friend through an online community.",
  "Put a finger down if you have asked a new friend how they prefer to stay in touch.",
  "Put a finger down if you have invited someone into a conversation by asking an open question.",
  "Put a finger down if you have discovered an unexpected shared interest with a new friend.",
  "Put a finger down if you have followed up after saying that you should hang out sometime.",
  "Put a finger down if you have introduced two friends who later became close.",
  "Put a finger down if you have learned a new skill from someone you recently befriended.",
  "Put a finger down if you have attended a community event hoping to meet new people.",
  "Put a finger down if you have turned a familiar neighbor into a real friend.",
  "Put a finger down if you have made a friend at a temporary job, class, or project.",
  "Put a finger down if you have remembered a new friend's name and used it the next time you met.",
  "Put a finger down if you have welcomed someone without expecting them to perform for the group.",
  "Put a finger down if you have accepted an invitation that led to a new friendship.",
  "Put a finger down if you have bonded with someone over helping with the same task.",
  "Put a finger down if you have made friends with someone from a different generation.",
  "Put a finger down if you have asked a new friend about an interest they clearly enjoy.",
  "Put a finger down if you have grown closer to someone through many brief conversations.",
  "Put a finger down if a new friend has helped you feel connected in an unfamiliar place.",
  "Put a finger down if a friendship has changed because one of you entered a new stage of life.",
  "Put a finger down if you have grown closer to a friend after spending more time one-on-one.",
  "Put a finger down if you have accepted that an old friendship now has a different rhythm.",
  "Put a finger down if you have reconnected with a childhood friend as adults.",
  "Put a finger down if a former casual friend has become one of your closest friends.",
  "Put a finger down if you have learned to plan around a friend's new responsibilities.",
  "Put a finger down if you have maintained a friendship despite having very different routines.",
  "Put a finger down if you have let a friendship fade without turning it into a feud.",
  "Put a finger down if you have rediscovered common ground with a friend after your interests changed.",
  "Put a finger down if you have made peace with seeing a good friend less often.",
  "Put a finger down if a friendship has become stronger after surviving a major schedule change.",
  "Put a finger down if you have welcomed a friend's new circle without competing for attention.",
  "Put a finger down if you have recognized that a friendship needed more effort from both sides.",
  "Put a finger down if you have changed how you celebrate traditions as your friend group evolved.",
  "Put a finger down if you have become more honest with a friend over time.",
  "Put a finger down if you have found a new shared interest after an old one faded.",
  "Put a finger down if a friendship has shifted from daily contact to occasional deep catch-ups.",
  "Put a finger down if you have supported a friend through a change you did not fully understand at first.",
  "Put a finger down if you have updated an old assumption about who your friend has become.",
  "Put a finger down if you have built a new tradition after a group dynamic changed.",
  "Put a finger down if you have noticed that a friendship feels easier than it did at the beginning.",
  "Put a finger down if you have learned when to give an evolving friendship more space.",
  "Put a finger down if an old friend has surprised you with a new side of themselves.",
  "Put a finger down if you have thanked a friend for growing alongside you.",
  "Put a finger down if you have accepted that different friendships meet different needs.",
  "Put a finger down if you have made room for a friendship to change without predicting its ending.",
  "Put a finger down if you have carried a lesson from an old friendship into a newer one.",
] as const satisfies readonly string[]
