export const PUT_FINGER_SPICY: readonly string[] = [
  'Put a finger down if you have flirted with someone using only eye contact.',
  'Put a finger down if you have rehearsed a flirty opening line before saying it.',
  'Put a finger down if you have complimented someone because you hoped they would ask you out.',
  'Put a finger down if you have made the first move after noticing mutual chemistry.',
  'Put a finger down if you have admitted your attraction before knowing whether it was returned.',
  'Put a finger down if you have asked a friend to help you approach someone you found attractive.',
  'Put a finger down if you have slipped your number to someone instead of asking for theirs.',
  'Put a finger down if you have flirted across a crowded room and hoped nobody else noticed.',
  'Put a finger down if you have used a playful challenge as an excuse to keep flirting.',
  'Put a finger down if you have turned an ordinary compliment into obvious flirting.',
  'Put a finger down if you have flirted with someone while both pretending it was only banter.',
  'Put a finger down if you have changed seats so you could talk to someone attractive.',
  'Put a finger down if you have found someone more attractive after hearing them laugh.',
  'Put a finger down if you have been instantly drawn to someone because of their voice.',
  'Put a finger down if you have developed a crush after one unexpectedly deep conversation.',
  'Put a finger down if you have felt chemistry with someone you did not initially consider your type.',
  'Put a finger down if you have been attracted to someone mainly because of their confidence.',
  'Put a finger down if you have fallen for someone\'s mind before noticing their looks.',
  'Put a finger down if you have realized you were attracted to a friend at an inconvenient moment.',
  'Put a finger down if you have felt a spark during a completely ordinary errand together.',
  'Put a finger down if you have become interested in someone after watching them be kind to others.',
  'Put a finger down if you have had a crush on someone whose style was completely different from yours.',
  'Put a finger down if you have found a small mannerism unexpectedly attractive.',
  'Put a finger down if you have been surprised by how attractive emotional honesty felt.',
  'Put a finger down if you have mistaken nervousness for a lack of chemistry on a first date.',
  'Put a finger down if you have felt romantic tension during a long goodbye.',
  'Put a finger down if you have caught feelings for someone you expected to date casually.',
  'Put a finger down if you have discovered attraction only after spending time apart.',
  'Put a finger down if you have felt butterflies when someone remembered a tiny detail about you.',
  'Put a finger down if you have been charmed by someone\'s terrible but confident joke.',
  'Put a finger down if you have stared at a message from your crush without knowing how to reply.',
  'Put a finger down if you have sent a bold message and immediately put your phone face down.',
  'Put a finger down if you have rewritten a flirty text more than five times before sending it.',
  'Put a finger down if you have added an emoji to make a message sound more suggestive.',
  'Put a finger down if you have deleted a draft because it revealed too much interest.',
  'Put a finger down if you have sent the first message after promising yourself you would wait.',
  'Put a finger down if you have stayed awake later than planned because the flirting was too good.',
  'Put a finger down if you have received a message that made you blush in public.',
  'Put a finger down if you have used a song link to hint at your feelings.',
  'Put a finger down if you have sent a voice note because your tone mattered more than the words.',
  'Put a finger down if you have turned a practical text thread into a flirtatious one.',
  'Put a finger down if you have risked a double text because you genuinely wanted the conversation.',
  'Put a finger down if you have asked someone directly whether their message was meant to be flirty.',
  'Put a finger down if you have exchanged goodnight messages that neither person wanted to end.',
  'Put a finger down if you have sent a selfie to one particular person hoping for a compliment.',
  'Put a finger down if you have used an inside joke to restart a conversation with a crush.',
  'Put a finger down if you have admitted over text that you were too nervous to say something in person.',
  'Put a finger down if you have received an unexpectedly romantic message during a workday.',
  'Put a finger down if you have told someone you missed them sooner than you planned.',
  'Put a finger down if you have asked for clarity instead of decoding mixed messages.',
  'Put a finger down if you have matched with someone you had already noticed in real life.',
  'Put a finger down if you have recognized someone from a dating app while out in public.',
  'Put a finger down if you have changed your dating profile to attract more compatible matches.',
  'Put a finger down if you have used a very specific profile detail to start a conversation.',
  'Put a finger down if you have matched with someone because their answer made you laugh.',
  'Put a finger down if you have paused your dating profile after one especially promising date.',
  'Put a finger down if you have returned to a dating app sooner than you expected after a breakup.',
  'Put a finger down if you have asked a match what they were looking for before agreeing to meet.',
  'Put a finger down if you have unmatched someone after they ignored a clearly stated boundary.',
  'Put a finger down if you have moved a dating app conversation to a call before meeting.',
  'Put a finger down if you have asked a friend to review your dating profile.',
  'Put a finger down if you have gone on a date with someone whose profile almost made you swipe past.',
  'Put a finger down if you have discovered a shared niche interest through a dating app prompt.',
  'Put a finger down if you have politely ended an app conversation that was going nowhere.',
  'Put a finger down if you have been pleasantly surprised that someone looked better than their photos.',
  'Put a finger down if you have chosen a public first-date spot that helped you feel comfortable.',
  'Put a finger down if you have declined to share your number until after meeting in person.',
  'Put a finger down if you have deleted a dating app because swiping started to feel exhausting.',
  'Put a finger down if you have reconnected with an old match after timing improved.',
  'Put a finger down if you have suggested meeting quickly because texting could not reveal chemistry.',
  'Put a finger down if you have arrived early to a date because you were nervous.',
  'Put a finger down if you have changed outfits several times before a first date.',
  'Put a finger down if you have practiced saying your date\'s name before meeting them.',
  'Put a finger down if you have chosen a date activity mainly because it allowed easy conversation.',
  'Put a finger down if you have realized within five minutes that a date had real potential.',
  'Put a finger down if you have laughed through an awkward silence on a date.',
  'Put a finger down if you have spilled something because your date made you nervous.',
  'Put a finger down if you have forgotten your planned questions once the date began.',
  'Put a finger down if you have extended a date by suggesting one more stop.',
  'Put a finger down if you have ended a date early and communicated the reason kindly.',
  'Put a finger down if you have gone on a date that felt more like a job interview.',
  'Put a finger down if you have bonded with a date over something that went wrong.',
  'Put a finger down if you have let your date know immediately that you wanted to see them again.',
  'Put a finger down if you have been on a date where both people admitted they were nervous.',
  'Put a finger down if you have accidentally dressed far more formally than your date.',
  'Put a finger down if you have planned a second date before the first one ended.',
  'Put a finger down if you have gone on a date somewhere neither person had visited before.',
  'Put a finger down if you have shared dessert on a date after insisting you were not hungry.',
  'Put a finger down if you have missed a turn because the date conversation was so absorbing.',
  'Put a finger down if you have felt relieved when a date openly named the awkwardness.',
  'Put a finger down if you have gone on a blind date arranged by someone who knew you well.',
  'Put a finger down if you have discovered halfway through a date that you had met before.',
  'Put a finger down if you have planned an elaborate date that became memorable for an unplanned reason.',
  'Put a finger down if you have preferred a simple walk to an expensive date plan.',
  'Put a finger down if you have met a date\'s friends much earlier than expected.',
  'Put a finger down if you have left a date unsure whether the chemistry was romantic or friendly.',
  'Put a finger down if you have gone on another date despite an awkward first impression.',
  'Put a finger down if you have been surprised by how different someone seemed away from texting.',
  'Put a finger down if you have thanked someone for a date even though you did not want another.',
  'Put a finger down if you have arranged your own ride home so you could leave whenever you wished.',
  'Put a finger down if you have asked someone whether you could kiss them.',
  'Put a finger down if you have been asked for a kiss in a way that made you feel especially respected.',
  'Put a finger down if you have shared a first kiss after a long moment of mutual anticipation.',
  'Put a finger down if you have laughed during a kiss and found it made the moment better.',
  'Put a finger down if you have bumped noses during a first kiss.',
  'Put a finger down if you have stopped to check whether a kiss still felt welcome.',
  'Put a finger down if you have waited for a clearer signal instead of assuming someone wanted a kiss.',
  'Put a finger down if you have decided not to kiss someone because the timing felt wrong.',
  'Put a finger down if you have kissed someone goodbye and immediately wanted to return.',
  'Put a finger down if you have felt more nervous about a kiss than about the entire date.',
  'Put a finger down if you have talked about kissing before actually doing it.',
  'Put a finger down if you have discovered that a slow, clearly mutual moment was worth the wait.',
  'Put a finger down if you have asked someone what kind of physical affection they enjoy.',
  'Put a finger down if you have realized a forehead kiss felt more intimate than expected.',
  'Put a finger down if you have shared a kiss that clarified feelings neither person had named.',
  'Put a finger down if you have paused a romantic moment because one person needed reassurance.',
  'Put a finger down if you have told someone you wanted to take physical affection more slowly.',
  'Put a finger down if you have appreciated someone asking before holding your hand.',
  'Put a finger down if you have initiated a kiss after receiving an unmistakably enthusiastic yes.',
  'Put a finger down if you have ended a good date with a hug because that felt right.',
  'Put a finger down if you have clearly stated a dating boundary before it became an issue.',
  'Put a finger down if you have asked someone about their boundaries without waiting for conflict.',
  'Put a finger down if you have changed your mind during a romantic moment and said so.',
  'Put a finger down if you have respected someone\'s change of mind without taking it personally.',
  'Put a finger down if you have asked for a slower pace even though the chemistry was strong.',
  'Put a finger down if you have accepted a romantic no without asking for an explanation.',
  'Put a finger down if you have said no to a date you wanted because the timing was unhealthy for you.',
  'Put a finger down if you have checked in after misreading someone\'s comfort level.',
  'Put a finger down if you have apologized for crossing a minor boundary and changed your behavior.',
  'Put a finger down if you have told a partner that privacy still matters inside a relationship.',
  'Put a finger down if you have discussed what kinds of photos were okay to share with others.',
  'Put a finger down if you have asked before posting a date photo online.',
  'Put a finger down if you have agreed on how public to be about a new relationship.',
  'Put a finger down if you have kept someone\'s romantic confidence private.',
  'Put a finger down if you have declined to exchange phone passwords and explained why.',
  'Put a finger down if you have asked before using a pet name in public.',
  'Put a finger down if you have discussed how much texting feels comfortable during the day.',
  'Put a finger down if you have protected your alone time while dating someone you really liked.',
  'Put a finger down if you have felt closer to someone after an honest boundary conversation.',
  'Put a finger down if you have admitted feeling jealous without blaming the other person.',
  'Put a finger down if you have asked for reassurance instead of making an accusation.',
  'Put a finger down if you have realized your jealousy came from insecurity and owned it.',
  'Put a finger down if you have felt jealous of someone who was genuinely only a friend.',
  'Put a finger down if you have taken time to cool down before discussing jealousy.',
  'Put a finger down if you have been honest that a former partner\'s presence made you uncomfortable.',
  'Put a finger down if you have reassured a partner without giving up a reasonable boundary.',
  'Put a finger down if you have apologized after letting jealousy distort a conversation.',
  'Put a finger down if you have chosen curiosity over suspicion when something felt unclear.',
  'Put a finger down if you have talked openly about what each person considers flirting.',
  'Put a finger down if you have felt a flash of jealousy over a harmless celebrity crush.',
  'Put a finger down if you have admitted wanting more attention without turning it into a demand.',
  'Put a finger down if you have supported someone\'s friendships even while managing your own insecurity.',
  'Put a finger down if you have recognized that attraction to others can exist without betrayal.',
  'Put a finger down if you have asked what exclusivity meant instead of assuming you agreed.',
  'Put a finger down if you have discussed expectations before using a relationship label.',
  'Put a finger down if you have navigated different comfort levels about public affection.',
  'Put a finger down if you have clarified a misunderstanding before it became an argument.',
  'Put a finger down if you have chosen not to compare yourself with someone\'s former partner.',
  'Put a finger down if you have felt proud of how calmly you handled a jealous moment.',
  'Put a finger down if you have confessed a crush to the person directly.',
  'Put a finger down if you have kept a crush secret because you valued the friendship.',
  'Put a finger down if you have discovered that a long-term crush liked you too.',
  'Put a finger down if you have moved on from a crush after receiving a clear no.',
  'Put a finger down if you have written out a confession before delivering it in person.',
  'Put a finger down if you have accidentally revealed your crush through an obvious reaction.',
  'Put a finger down if you have told a mutual friend about a crush but asked them not to interfere.',
  'Put a finger down if you have developed a crush on someone you met through a shared hobby.',
  'Put a finger down if you have had a crush fade as soon as you got to know the person.',
  'Put a finger down if you have felt relieved after finally naming your feelings.',
  'Put a finger down if you have realized someone had a crush on you only much later.',
  'Put a finger down if you have turned down a crush kindly because you did not feel the same.',
  'Put a finger down if you have had two crushes at the same time while single.',
  'Put a finger down if you have developed feelings for someone after they stopped pursuing you.',
  'Put a finger down if you have avoided idealizing a crush by actually getting to know them.',
  'Put a finger down if you have admitted that friendship was all you could offer.',
  'Put a finger down if you have been surprised when a casual acquaintance confessed feelings for you.',
  'Put a finger down if you have invited your crush somewhere without disguising it as a group plan.',
  'Put a finger down if you have celebrated a crush\'s happiness even when they chose someone else.',
  'Put a finger down if you have outgrown a crush that once felt impossible to escape.',
  'Put a finger down if you have asked someone out in person despite being visibly nervous.',
  'Put a finger down if you have planned a romantic surprise around something they genuinely enjoy.',
  'Put a finger down if you have traveled to another city for a promising date.',
  'Put a finger down if you have gone to an event alone hoping to meet someone new.',
  'Put a finger down if you have danced with someone after asking whether they wanted to.',
  'Put a finger down if you have invited someone to meet your friends as a romantic signal.',
  'Put a finger down if you have worn something daring because it made you feel confident on a date.',
  'Put a finger down if you have openly said that you wanted romance instead of pretending to be casual.',
  'Put a finger down if you have risked changing a friendship by asking about mutual attraction.',
  'Put a finger down if you have booked a spontaneous date after a conversation felt electric.',
  'Put a finger down if you have made a playlist for someone before the relationship was official.',
  'Put a finger down if you have cooked for someone you were trying to impress.',
  'Put a finger down if you have sent flowers or a thoughtful gift early in a romance.',
  'Put a finger down if you have introduced yourself to someone after nearly losing your nerve.',
  'Put a finger down if you have asked to turn a friendly hangout into an actual date.',
  'Put a finger down if you have taken a chance on a date outside your usual routine.',
  'Put a finger down if you have shared an embarrassing story to make a nervous date feel at ease.',
  'Put a finger down if you have been the first person to say the connection felt special.',
  'Put a finger down if you have returned to a place hoping to see someone you had spoken with there.',
  'Put a finger down if you have chosen honesty even though it might end a promising romance.',
  'Put a finger down if you have mistaken friendly warmth for romantic interest.',
  'Put a finger down if you have learned that someone thought your flirting was simple politeness.',
  'Put a finger down if you have called someone by the wrong name on a date.',
  'Put a finger down if you have told a joke on a date that landed completely wrong.',
  'Put a finger down if you have waved at someone attractive who was greeting the person behind you.',
  'Put a finger down if you have tripped or stumbled while trying to look confident around a crush.',
  'Put a finger down if you have accidentally sent a romantic message to the wrong chat.',
  'Put a finger down if you have forgotten an important detail your date had just told you.',
  'Put a finger down if you have panicked when someone attractive caught you looking at them.',
  'Put a finger down if you have made an awkward joke right after a romantic moment.',
  'Put a finger down if you have gone in for a hug while your date offered a handshake.',
  'Put a finger down if you have misunderstood whether an invitation was actually a date.',
  'Put a finger down if you have been interrupted at the exact moment you planned to confess feelings.',
  'Put a finger down if you have tried to act mysterious and only seemed distracted.',
  'Put a finger down if you have overthought punctuation in a message from someone you liked.',
  'Put a finger down if you have realized too late that someone had been flirting with you.',
  'Put a finger down if you have accidentally revealed how much you already knew about your date.',
  'Put a finger down if you have forgotten how to speak normally around an especially attractive person.',
  'Put a finger down if you have had a romantic plan ruined by terrible timing.',
  'Put a finger down if you have made eye contact with a friend after your crush entered the room.',
  'Put a finger down if you have recovered from an awkward date by laughing about it together.',
  'Put a finger down if you have told someone exactly what quality made you attracted to them.',
  'Put a finger down if you have asked a partner what makes them feel desired.',
  'Put a finger down if you have received a compliment that changed the mood of your entire day.',
  'Put a finger down if you have discovered that thoughtful conversation creates more chemistry for you than appearance.',
  'Put a finger down if you have felt more attracted to someone after resolving a disagreement respectfully.',
  'Put a finger down if you have enjoyed a comfortable silence that still felt charged.',
  'Put a finger down if you have noticed mutual chemistry before learning anything personal about each other.',
  'Put a finger down if you have felt a romantic connection grow through shared humor.',
  'Put a finger down if you have become more attracted to someone after seeing their vulnerable side.',
  'Put a finger down if you have experienced chemistry that made time seem to move faster.',
  'Put a finger down if you have realized a connection lacked chemistry despite perfect compatibility on paper.',
  'Put a finger down if you have told someone the spark felt mutual instead of waiting for them to say it.',
  'Put a finger down if you have confused intense chemistry with long-term compatibility.',
  'Put a finger down if you have felt attraction return after a heartfelt conversation.',
  'Put a finger down if you have been drawn to someone because they made you feel completely at ease.',
  'Put a finger down if you have discovered that anticipation was more exciting than the eventual date.',
  'Put a finger down if you have felt sparks while doing something deeply unglamorous together.',
  'Put a finger down if you have acknowledged strong chemistry while still maintaining your pace.',
  'Put a finger down if you have noticed attraction deepen when someone respected your independence.',
  'Put a finger down if you have felt desired because someone paid close attention to your words.',
  'Put a finger down if you have asked someone whether they wanted something casual or committed.',
  'Put a finger down if you have initiated a conversation about exclusivity.',
  'Put a finger down if you have admitted you wanted more than the other person could offer.',
  'Put a finger down if you have ended a casual connection after your feelings changed.',
  'Put a finger down if you have agreed to keep dating slowly instead of rushing into a label.',
  'Put a finger down if you have defined a relationship in a conversation that felt scarier than the first date.',
  'Put a finger down if you have discovered that your preferred dating pace differed from someone else\'s.',
  'Put a finger down if you have chosen compatibility over undeniable chemistry.',
  'Put a finger down if you have told someone you were not ready to date seriously.',
  'Put a finger down if you have revisited a relationship conversation after your needs changed.',
  'Put a finger down if you have discussed whether dating other people was still welcome.',
  'Put a finger down if you have asked what commitment looks like to the person you were seeing.',
  'Put a finger down if you have been honest about wanting a relationship before becoming deeply invested.',
  'Put a finger down if you have stepped back from someone who could not offer consistent communication.',
  'Put a finger down if you have agreed on a casual connection without treating each other casually.',
  'Put a finger down if you have felt nervous introducing someone as your partner for the first time.',
  'Put a finger down if you have realized you were dating exclusively before either person named it.',
  'Put a finger down if you have declined a relationship label that did not fit your connection.',
  'Put a finger down if you have chosen to remain single rather than accept an unclear arrangement.',
  'Put a finger down if you have felt closer after a direct conversation about romantic expectations.',
  'Put a finger down if you have gone on a date with someone you once considered only a friend.',
  'Put a finger down if you have reconnected romantically with someone after years apart.',
  'Put a finger down if you have given a second chance after both people showed meaningful growth.',
  'Put a finger down if you have declined to rekindle a romance because the old issues remained.',
  'Put a finger down if you have become attracted to someone after collaborating on a project.',
  'Put a finger down if you have dated someone with a completely different daily routine.',
  'Put a finger down if you have found romance while traveling and stayed in touch afterward.',
  'Put a finger down if you have navigated a long-distance connection that began unexpectedly.',
  'Put a finger down if you have reunited with someone and discovered the chemistry was still there.',
  'Put a finger down if you have tried dating someone after previously turning them down.',
  'Put a finger down if you have been pleasantly surprised by a setup from friends.',
  'Put a finger down if you have dated someone who challenged your idea of your usual type.',
  'Put a finger down if you have explored a connection despite an inconvenient schedule.',
  'Put a finger down if you have chosen not to pursue attraction because of a professional boundary.',
  'Put a finger down if you have dated someone who lived far enough away to require real planning.',
  'Put a finger down if you have discovered a former almost-romance still had potential.',
  'Put a finger down if you have let a friendship remain platonic despite mutual attraction.',
  'Put a finger down if you have started dating again after taking a deliberate break.',
  'Put a finger down if you have found an unexpected connection at a gathering you nearly skipped.',
  'Put a finger down if you have learned that good timing mattered as much as attraction.',
  'Put a finger down if you have ended a promising connection because your life goals did not align.',
  'Put a finger down if you have been the first to apologize after a dating misunderstanding.',
  'Put a finger down if you have asked for a difficult conversation instead of quietly pulling away.',
  'Put a finger down if you have told someone their inconsistent effort was affecting your interest.',
  'Put a finger down if you have received honest rejection and appreciated the clarity.',
  'Put a finger down if you have given honest rejection without leaving false hope.',
  'Put a finger down if you have explained that disappearing communication was not working for you.',
  'Put a finger down if you have chosen a clean ending over keeping someone as a backup option.',
  'Put a finger down if you have admitted you handled an early dating conflict poorly.',
  'Put a finger down if you have asked what repair would look like after hurting someone\'s feelings.',
  'Put a finger down if you have accepted that an apology did not require another chance.',
  'Put a finger down if you have told someone their teasing crossed a line.',
  'Put a finger down if you have listened without becoming defensive when a date raised a concern.',
  'Put a finger down if you have ended a romantic connection face to face because it felt appropriate and safe.',
  'Put a finger down if you have chosen a phone conversation for an ending because distance made more sense.',
  'Put a finger down if you have resisted sending a late-night message to someone you had already released.',
  'Put a finger down if you have returned belongings without using them as an excuse to reopen a romance.',
  'Put a finger down if you have taken responsibility for mixed signals you gave while uncertain.',
  'Put a finger down if you have asked for space and clearly explained what that meant.',
  'Put a finger down if you have respected a request for space without repeatedly checking in.',
]
