export const PUT_FINGER_RELATIONSHIPS: readonly string[] = [
  'Put a finger down if you have rehearsed what to say before talking to a crush.',
  'Put a finger down if a crush has made an ordinary day feel unusually exciting.',
  'Put a finger down if you once mistook friendliness for flirting.',
  'Put a finger down if you have discovered that someone you liked also liked you.',
  'Put a finger down if your friends knew about your crush before the person did.',
  'Put a finger down if you have tried to act casual around someone who made you nervous.',
  'Put a finger down if a shared joke helped you connect with someone you liked.',
  'Put a finger down if you have developed a crush after getting to know someone slowly.',
  'Put a finger down if someone became more attractive to you because of their kindness.',
  'Put a finger down if you have been surprised by the person you ended up liking.',
  'Put a finger down if you made the first move and felt proud of yourself afterward.',
  'Put a finger down if you have waited eagerly for a message from someone special.',
  'Put a finger down if a compliment from a crush stayed with you for years.',
  'Put a finger down if you have realized a crush was better suited to friendship.',
  'Put a finger down if you felt relieved after finally telling someone you liked them.',
  'Put a finger down if you have liked someone whose schedule rarely matched yours.',
  'Put a finger down if a mutual friend introduced you to someone you dated.',
  'Put a finger down if you have had a crush on someone you met through a hobby.',
  'Put a finger down if an unexpected conversation changed how you saw someone.',
  'Put a finger down if you chose not to pursue a crush because the timing felt wrong.',
  'Put a finger down if you have gone on a first date that lasted much longer than planned.',
  'Put a finger down if a first date included an awkward silence you can laugh about now.',
  'Put a finger down if you have changed outfits more than once before a date.',
  'Put a finger down if bad weather unexpectedly improved a date.',
  'Put a finger down if you have planned a date around a shared interest.',
  'Put a finger down if a date introduced you to a place you still enjoy.',
  'Put a finger down if you have politely ended a date when the connection was not there.',
  'Put a finger down if someone remembered a tiny detail you mentioned on an early date.',
  'Put a finger down if you have gone on a date that felt more like an interview.',
  'Put a finger down if a simple walk turned into one of your favorite dates.',
  'Put a finger down if you have arrived early because you were excited for a date.',
  'Put a finger down if you bonded with a date over something unexpectedly specific.',
  'Put a finger down if you have met someone in person after first connecting online.',
  'Put a finger down if you suggested a low-cost date that turned out wonderfully.',
  'Put a finger down if a date went off plan but still became a good memory.',
  'Put a finger down if you have asked someone directly whether they wanted another date.',
  'Put a finger down if you realized during a date that you wanted different things.',
  'Put a finger down if you have taken yourself on a solo date after plans changed.',
  'Put a finger down if a thoughtful question made a first date feel comfortable.',
  'Put a finger down if you have needed a recovery day after an especially social date.',
  'Put a finger down if you sent the first message after a promising date.',
  'Put a finger down if you have overthought the punctuation in a romantic message.',
  'Put a finger down if a voice note helped you feel closer to someone.',
  'Put a finger down if you misunderstood a text and later cleared it up by talking.',
  'Put a finger down if you have asked for time to think before answering a relationship question.',
  'Put a finger down if someone listened to you without trying to solve the problem.',
  'Put a finger down if you have learned to say what you need more directly.',
  'Put a finger down if a difficult conversation made a relationship stronger.',
  'Put a finger down if you have apologized without adding an excuse.',
  'Put a finger down if you needed reassurance but found it hard to ask.',
  'Put a finger down if you have agreed to revisit a conversation after cooling down.',
  'Put a finger down if a partner taught you a better way to handle disagreement.',
  'Put a finger down if you have used humor to ease tension at the right moment.',
  'Put a finger down if you realized you were arguing about two different things.',
  'Put a finger down if you have written down your thoughts before a serious conversation.',
  'Put a finger down if someone asked how you prefer to receive support.',
  'Put a finger down if you have admitted that you did not understand what your partner meant.',
  'Put a finger down if a check-in prevented a small concern from growing.',
  'Put a finger down if you have changed your mind after truly hearing another perspective.',
  'Put a finger down if you and a partner created a phrase for pausing heated conversations.',
  'Put a finger down if someone made you feel safe enough to share an unpopular opinion.',
  'Put a finger down if you have asked a follow-up question instead of making an assumption.',
  'Put a finger down if a conversation about expectations saved you future confusion.',
  'Put a finger down if you have received an apology that genuinely repaired trust.',
  'Put a finger down if you learned that silence can mean different things to different people.',
  'Put a finger down if you and someone close have different texting habits.',
  'Put a finger down if you have scheduled time for a conversation that mattered.',
  'Put a finger down if you admitted feeling jealous without blaming anyone.',
  'Put a finger down if a partner encouraged you to express a concern sooner next time.',
  'Put a finger down if you have felt closer to someone after resolving a misunderstanding.',
  'Put a finger down if you remember the first time a partner said they appreciated you.',
  'Put a finger down if you have saved a sweet note from someone you dated.',
  'Put a finger down if a thoughtful snack felt more romantic than an expensive gift.',
  'Put a finger down if you and a partner have a greeting that is uniquely yours.',
  'Put a finger down if you have made a playlist for someone you cared about.',
  'Put a finger down if a partner celebrated an achievement that mattered to you.',
  'Put a finger down if you have left an encouraging message for someone before a big day.',
  'Put a finger down if shared laughter has helped you through a stressful week.',
  'Put a finger down if you and someone special have a song that brings back memories.',
  'Put a finger down if you have cooked a favorite meal as an act of affection.',
  'Put a finger down if a partner remembered an occasion you had forgotten.',
  'Put a finger down if you have felt loved through practical help rather than words.',
  'Put a finger down if a handwritten card meant more to you than the gift beside it.',
  'Put a finger down if you and a partner invented a silly tradition together.',
  'Put a finger down if you have been surprised by affection expressed in an unfamiliar way.',
  'Put a finger down if a quiet evening together felt like a perfect date.',
  'Put a finger down if you have proudly introduced a partner to people important to you.',
  'Put a finger down if someone made room for your favorite thing even though it was not theirs.',
  'Put a finger down if you have learned what makes a partner feel appreciated.',
  'Put a finger down if an ordinary goodbye made you realize how much you cared.',
  'Put a finger down if you have celebrated a relationship milestone in a simple way.',
  'Put a finger down if a sincere compliment changed the mood of your whole day.',
  'Put a finger down if you and a partner laugh about your first impression of each other.',
  'Put a finger down if you have kept a small souvenir from a meaningful date.',
  'Put a finger down if someone supported your interest without needing to share it.',
  'Put a finger down if you have expressed affection by doing an unwanted chore for someone.',
  'Put a finger down if a familiar routine with a partner became something you treasured.',
  'Put a finger down if you and a partner have made up a word that only you understand.',
  'Put a finger down if you have felt deeply cared for during an ordinary errand.',
  'Put a finger down if you confused the time or place of a date.',
  'Put a finger down if a joke landed badly and required a sincere conversation.',
  'Put a finger down if you have forgotten an important detail and made amends afterward.',
  'Put a finger down if different definitions of being on time caused tension in a relationship.',
  'Put a finger down if you and a partner remembered the same event completely differently.',
  'Put a finger down if you have assumed someone was upset when they were only tired.',
  'Put a finger down if an autocorrect mistake created a romantic misunderstanding.',
  'Put a finger down if you gave advice when your partner only wanted empathy.',
  'Put a finger down if you have laughed together after a minor disagreement was resolved.',
  'Put a finger down if a surprise plan failed because the other person dislikes surprises.',
  'Put a finger down if you have misread a social cue and later talked about it openly.',
  'Put a finger down if you and a partner disagreed over what counts as quality time.',
  'Put a finger down if you have forgotten whose turn it was to handle a shared task.',
  'Put a finger down if different communication styles initially seemed like lack of interest.',
  'Put a finger down if you planned the same surprise for each other.',
  'Put a finger down if you have accidentally spoiled a gift you were trying to keep secret.',
  'Put a finger down if a missed call led to more worry than the situation deserved.',
  'Put a finger down if you and a date ordered the same meal without planning it.',
  'Put a finger down if you have mistaken a relationship anniversary by a day.',
  'Put a finger down if a shared calendar solved a recurring disagreement.',
  'Put a finger down if you have clearly stated a boundary even though it felt awkward.',
  'Put a finger down if someone respected your need for time alone without taking it personally.',
  'Put a finger down if you and a partner discussed what privacy means to each of you.',
  'Put a finger down if you have declined public affection and felt respected afterward.',
  'Put a finger down if a relationship improved when you stopped saying yes automatically.',
  'Put a finger down if you have asked before sharing a partner\'s story with other people.',
  'Put a finger down if someone accepted your no without demanding an explanation.',
  'Put a finger down if you and a partner set expectations about social media together.',
  'Put a finger down if you have protected regular time for your own friends or interests.',
  'Put a finger down if a partner encouraged you to maintain your independence.',
  'Put a finger down if you have changed a habit after learning it crossed someone\'s boundary.',
  'Put a finger down if you and someone you dated had different needs for personal space.',
  'Put a finger down if you have asked permission before posting a couple photo.',
  'Put a finger down if a conversation about money boundaries prevented resentment.',
  'Put a finger down if you have felt comfortable changing your mind about a plan.',
  'Put a finger down if someone checked what kind of affection you wanted in the moment.',
  'Put a finger down if you and a partner agreed on topics that should remain private.',
  'Put a finger down if you have stepped away from a conversation that became disrespectful.',
  'Put a finger down if a partner honored your need for advance notice before visitors.',
  'Put a finger down if you have supported someone\'s boundary even when you felt disappointed.',
  'Put a finger down if you and a partner discussed how much togetherness feels healthy.',
  'Put a finger down if you have recognized that access to someone is not proof of trust.',
  'Put a finger down if a respectful boundary made you feel more secure in a relationship.',
  'Put a finger down if you have learned that compromise should not erase either person.',
  'Put a finger down if someone gave you space to make a decision without pressure.',
  'Put a finger down if you have ended a conversation until everyone could speak kindly.',
  'Put a finger down if you and a partner found a shared hobby neither of you expected to enjoy.',
  'Put a finger down if different sleep schedules required creative planning in a relationship.',
  'Put a finger down if you have dated someone with a very different social battery.',
  'Put a finger down if a shared value mattered more than having identical interests.',
  'Put a finger down if you and a partner have opposite approaches to planning ahead.',
  'Put a finger down if you have learned to enjoy an activity because someone you loved enjoyed it.',
  'Put a finger down if different spending habits led to a useful conversation.',
  'Put a finger down if you and someone you dated preferred different levels of spontaneity.',
  'Put a finger down if a relationship helped you distinguish chemistry from compatibility.',
  'Put a finger down if you have discovered that shared humor is important to you.',
  'Put a finger down if different food preferences made choosing dinner a regular negotiation.',
  'Put a finger down if you and a partner found a holiday tradition that worked for everyone.',
  'Put a finger down if you have dated someone who organized everything differently from you.',
  'Put a finger down if matching long-term goals made a relationship feel steadier.',
  'Put a finger down if you and a partner disagreed about how early to arrive anywhere.',
  'Put a finger down if you have realized that similar personalities do not guarantee compatibility.',
  'Put a finger down if a difference in conflict style took patience to understand.',
  'Put a finger down if you and someone special speak different first languages.',
  'Put a finger down if you have balanced a relationship with very different work hours.',
  'Put a finger down if a partner introduced you to a custom that became meaningful to you.',
  'Put a finger down if you and a partner have different ideas of an ideal weekend.',
  'Put a finger down if you have discussed whether marriage fits your future.',
  'Put a finger down if a conversation about children clarified a relationship decision.',
  'Put a finger down if you and a partner have negotiated how to divide household responsibilities.',
  'Put a finger down if you have learned that compatibility can grow through collaboration.',
  'Put a finger down if someone you dated challenged you to reconsider a harmless preference.',
  'Put a finger down if you and a partner cheer for rival teams.',
  'Put a finger down if you have found a fair way to alternate who chooses the activity.',
  'Put a finger down if a difference you once worried about became something you valued.',
  'Put a finger down if you and a partner have adjusted plans around different accessibility needs.',
  'Put a finger down if you have brought someone comfort food during a difficult week.',
  'Put a finger down if a partner showed up for an event that mattered to you.',
  'Put a finger down if you have practiced a presentation with someone you were dating.',
  'Put a finger down if someone believed in your goal during a period of self-doubt.',
  'Put a finger down if you have handled extra everyday tasks while a partner was overwhelmed.',
  'Put a finger down if a relationship gave you confidence to try something new.',
  'Put a finger down if you have celebrated a partner\'s success without comparing it to your own.',
  'Put a finger down if someone stayed present while you processed disappointing news.',
  'Put a finger down if you have asked what support would be useful instead of guessing.',
  'Put a finger down if a partner reminded you to rest when you were pushing too hard.',
  'Put a finger down if you have encouraged someone you love to seek help beyond the relationship.',
  'Put a finger down if a partner respected that you wanted to solve a problem independently.',
  'Put a finger down if you have accompanied someone to an appointment for moral support.',
  'Put a finger down if someone helped you see progress you had overlooked.',
  'Put a finger down if you have taken care of a shared responsibility during a partner\'s busy season.',
  'Put a finger down if a partner defended your need for downtime to other people.',
  'Put a finger down if you have learned how someone prefers to be comforted.',
  'Put a finger down if someone encouraged your friendship with people outside the relationship.',
  'Put a finger down if you have been the calm person during a partner\'s stressful moment.',
  'Put a finger down if a partner gave honest feedback that helped you grow.',
  'Put a finger down if you have cheered someone through a long-term project.',
  'Put a finger down if receiving support felt harder than offering it.',
  'Put a finger down if you and a partner created a plan for handling an uncertain period.',
  'Put a finger down if you have expressed gratitude for emotional labor you once overlooked.',
  'Put a finger down if a partner encouraged you to take an opportunity that meant time apart.',
  'Put a finger down if you have learned that support can include giving someone quiet space.',
  'Put a finger down if you and a partner have assembled furniture together without giving up.',
  'Put a finger down if choosing what to watch has taken longer than the show itself.',
  'Put a finger down if you have shared a grocery list with someone you dated.',
  'Put a finger down if a partner knows your usual order without needing to ask.',
  'Put a finger down if you and someone special have a favorite place to run errands.',
  'Put a finger down if you have fallen asleep during a movie your partner chose.',
  'Put a finger down if a household chore became easier when you did it together.',
  'Put a finger down if you and a partner have debated the correct room temperature.',
  'Put a finger down if you have packed snacks for a shared journey.',
  'Put a finger down if a partner returned something you repeatedly left behind.',
  'Put a finger down if you and someone you dated created a shared calendar.',
  'Put a finger down if you have turned an ordinary weeknight into an impromptu celebration.',
  'Put a finger down if a pet had strong opinions about someone you were dating.',
  'Put a finger down if you and a partner have worked from the same space for a day.',
  'Put a finger down if you have learned another person\'s precise morning routine.',
  'Put a finger down if a quick errand together somehow took the entire afternoon.',
  'Put a finger down if you and a partner have a recurring debate about directions.',
  'Put a finger down if you have divided leftovers with surprising seriousness.',
  'Put a finger down if a partner has borrowed your favorite mug often enough to claim it.',
  'Put a finger down if you and someone special have danced while making dinner.',
  'Put a finger down if you have shared an umbrella and neither person stayed completely dry.',
  'Put a finger down if a routine check-in became the best part of your day.',
  'Put a finger down if you and a partner have maintained separate hobbies under the same roof.',
  'Put a finger down if you have made a home feel shared through one small change.',
  'Put a finger down if a minor inconvenience became a favorite relationship story.',
  'Put a finger down if you and a partner have invented a system for deciding what to eat.',
  'Put a finger down if you have been in a relationship that involved living in different places.',
  'Put a finger down if scheduling calls across time zones became part of your routine.',
  'Put a finger down if you and a long-distance partner watched something together remotely.',
  'Put a finger down if distance taught you to communicate more intentionally.',
  'Put a finger down if you have planned a visit months in advance.',
  'Put a finger down if reuniting after time apart felt both familiar and new.',
  'Put a finger down if you and a partner have celebrated an occasion through a video call.',
  'Put a finger down if a delayed journey disrupted an eagerly awaited reunion.',
  'Put a finger down if you have mailed a care package to someone you missed.',
  'Put a finger down if a relationship survived a major change in routine.',
  'Put a finger down if you and a partner moved to a new place together.',
  'Put a finger down if you have navigated a relationship while one person was studying.',
  'Put a finger down if a career change required renegotiating shared plans.',
  'Put a finger down if you and someone you love handled a period of limited free time.',
  'Put a finger down if your relationship changed shape while remaining meaningful.',
  'Put a finger down if you have discussed how to stay connected during a busy season.',
  'Put a finger down if a reunion included an activity you had both been saving.',
  'Put a finger down if you and a partner have made a countdown to seeing each other.',
  'Put a finger down if distance clarified what you valued about a relationship.',
  'Put a finger down if you have adjusted a shared goal after circumstances changed.',
  'Put a finger down if you ended a relationship because your futures pointed in different directions.',
  'Put a finger down if a breakup taught you to communicate earlier in future relationships.',
  'Put a finger down if you have returned shared belongings through a calm, agreed plan.',
  'Put a finger down if ending a relationship brought both sadness and relief.',
  'Put a finger down if you have needed time alone before dating again.',
  'Put a finger down if a relationship ended respectfully despite real disappointment.',
  'Put a finger down if you discovered a new interest while rebuilding after a breakup.',
  'Put a finger down if you have leaned on friends while adjusting to being single.',
  'Put a finger down if a breakup helped you recognize a boundary you needed.',
  'Put a finger down if you have wished a former partner well from a healthy distance.',
  'Put a finger down if a relationship ended because timing mattered more than affection.',
  'Put a finger down if you have changed a routine that reminded you of a past relationship.',
  'Put a finger down if healing took longer than you expected but still happened.',
  'Put a finger down if you have learned not to measure every new connection against an old one.',
  'Put a finger down if a breakup conversation gave you useful clarity.',
  'Put a finger down if you have recognized that closure can come from your own reflection.',
  'Put a finger down if being single helped you better understand what you want.',
  'Put a finger down if you have kept the lesson while letting go of the relationship.',
  'Put a finger down if a former relationship changed your definition of compatibility.',
  'Put a finger down if you have chosen peace over reopening an old disagreement.',
  'Put a finger down if you realized that missing someone did not mean you should reunite.',
  'Put a finger down if you have felt proud of how kindly you handled an ending.',
  'Put a finger down if a relationship taught you that love alone cannot solve every mismatch.',
  'Put a finger down if you have rebuilt confidence after romantic disappointment.',
  'Put a finger down if an ending made space for a healthier chapter later.',
  'Put a finger down if you have learned to recognize consistency as a form of care.',
  'Put a finger down if a past relationship changed how you approach apologies.',
  'Put a finger down if you now ask about expectations earlier than you once did.',
  'Put a finger down if you have become better at noticing when effort feels one-sided.',
  'Put a finger down if a relationship taught you not to confuse intensity with closeness.',
  'Put a finger down if you have outgrown an old idea of what romance should look like.',
  'Put a finger down if someone showed you that disagreement can remain respectful.',
  'Put a finger down if you have learned to trust steady actions more than grand promises.',
  'Put a finger down if a relationship helped you become more comfortable asking for help.',
  'Put a finger down if you now value emotional availability more than you used to.',
  'Put a finger down if you have dated casually while communicating your intentions clearly.',
  'Put a finger down if a committed relationship has never been part of your life so far.',
  'Put a finger down if you have taken a break from dating to focus on yourself.',
  'Put a finger down if you and a partner chose a commitment style that suited you both.',
  'Put a finger down if clear agreements helped a nonexclusive relationship feel respectful.',
  'Put a finger down if you have preferred getting to know someone slowly without labels.',
  'Put a finger down if you have talked openly about exclusivity instead of assuming it.',
  'Put a finger down if you and a partner maintain separate homes by choice.',
  'Put a finger down if a relationship worked well without following a traditional timeline.',
  'Put a finger down if you and a partner defined commitment in your own words.',
  'Put a finger down if a relationship revealed a strength you did not know you had.',
  'Put a finger down if you have learned that affection should not require guessing games.',
  'Put a finger down if dating taught you to pay attention to how you feel after an interaction.',
  'Put a finger down if you now define romance differently from how you did years ago.',
  'Put a finger down if you have become more intentional about making time for connection.',
  'Put a finger down if a relationship taught you to repair mistakes instead of seeking perfection.',
  'Put a finger down if you have learned that mutual curiosity keeps connection alive.',
  'Put a finger down if you enjoy being single and remain open to a future relationship.',
]
