export const PUT_FINGER_SCHOOL = [
  "Put a finger down if you have ever packed your school bag the night before.",
  "Put a finger down if you have ever arrived at class before the teacher.",
  "Put a finger down if you have ever forgotten which classroom you were supposed to be in.",
  "Put a finger down if you have ever taken a seat near the front so you could focus.",
  "Put a finger down if you have ever chosen a seat near the door for a quick exit after class.",
  "Put a finger down if you have ever had an assigned seat that became your favorite spot.",
  "Put a finger down if you have ever walked into the wrong class by mistake.",
  "Put a finger down if you have ever rushed across campus to avoid being late.",
  "Put a finger down if you have ever followed a friend because they knew the way to class.",
  "Put a finger down if you have ever needed a map to find a room at school.",
  "Put a finger down if you have ever decorated a notebook for a new term.",
  "Put a finger down if you have ever labeled all your school supplies.",
  "Put a finger down if you have ever borrowed a pen before a lesson began.",
  "Put a finger down if you have ever lent someone a pencil and received a different one back.",
  "Put a finger down if you have ever used the last page of a notebook for doodles.",
  "Put a finger down if you have ever color-coded notes by topic.",
  "Put a finger down if you have ever discovered an old snack in your school bag.",
  "Put a finger down if you have ever carried more books than you could comfortably hold.",
  "Put a finger down if you have ever left a textbook in the place where you studied.",
  "Put a finger down if you have ever personalized a folder with stickers or drawings.",
  "Put a finger down if you have ever sharpened a pencil until it became unusually short.",
  "Put a finger down if you have ever used scrap paper as an emergency bookmark.",
  "Put a finger down if you have ever found a note from a past class inside a book.",
  "Put a finger down if you have ever organized your desk instead of starting an assignment.",
  "Put a finger down if you have ever carried a reusable water bottle to class.",
  "Put a finger down if you have ever answered a question without being called on.",
  "Put a finger down if you have ever known an answer but felt too shy to share it.",
  "Put a finger down if you have ever changed your answer after hearing the class discussion.",
  "Put a finger down if you have ever asked a question that helped someone else understand.",
  "Put a finger down if you have ever explained a lesson to a classmate in your own words.",
  "Put a finger down if you have ever learned something from a classmate's question.",
  "Put a finger down if you have ever volunteered to demonstrate something for the class.",
  "Put a finger down if you have ever read aloud during a lesson.",
  "Put a finger down if you have ever lost your place while reading aloud.",
  "Put a finger down if you have ever tried not to laugh during a very quiet lesson.",
  "Put a finger down if you have ever made the whole class laugh with an unexpected answer.",
  "Put a finger down if you have ever watched the clock during the final minutes of class.",
  "Put a finger down if you have ever wished a fascinating lesson could continue longer.",
  "Put a finger down if you have ever connected a lesson to something that happened outside school.",
  "Put a finger down if you have ever remembered a surprising fact long after the lesson ended.",
  "Put a finger down if you have ever enjoyed a subject more because of one teacher.",
  "Put a finger down if you have ever received feedback that changed how you approached learning.",
  "Put a finger down if you have ever stayed after class to ask a teacher a question.",
  "Put a finger down if you have ever thanked a teacher for helping you understand something.",
  "Put a finger down if you have ever had a teacher remember a detail you shared.",
  "Put a finger down if you have ever been encouraged by a teacher when you doubted yourself.",
  "Put a finger down if you have ever needed a teacher to explain the same idea in a different way.",
  "Put a finger down if you have ever learned a useful life lesson from a teacher's story.",
  "Put a finger down if you have ever been surprised by a teacher's hidden talent.",
  "Put a finger down if you have ever seen a teacher use humor to make a topic memorable.",
  "Put a finger down if you have ever had a substitute teacher pronounce your name correctly on the first try.",
  "Put a finger down if you have ever helped a new teacher learn the class routine.",
  "Put a finger down if you have ever attended an extra-help session with an instructor.",
  "Put a finger down if you have ever written a note of appreciation to an educator.",
  "Put a finger down if you have ever met a former teacher years after their class.",
  "Put a finger down if you have ever used a teacher's memory trick on an exam.",
  "Put a finger down if you have ever had homework take much less time than expected.",
  "Put a finger down if you have ever underestimated how long an assignment would take.",
  "Put a finger down if you have ever finished homework during a break between classes.",
  "Put a finger down if you have ever started an assignment on the day it was given.",
  "Put a finger down if you have ever completed an assignment just before the deadline.",
  "Put a finger down if you have ever submitted homework and immediately noticed a typo.",
  "Put a finger down if you have ever forgotten to attach a file to an online submission.",
  "Put a finger down if you have ever uploaded the wrong document for an assignment.",
  "Put a finger down if you have ever saved schoolwork under a confusing file name.",
  "Put a finger down if you have ever lost work because you forgot to save it.",
  "Put a finger down if you have ever celebrated when a document autosaved successfully.",
  "Put a finger down if you have ever redone an assignment after misunderstanding the instructions.",
  "Put a finger down if you have ever asked for clarification before beginning a task.",
  "Put a finger down if you have ever used a checklist to finish a long assignment.",
  "Put a finger down if you have ever broken a large project into smaller steps.",
  "Put a finger down if you have ever rewarded yourself after finishing schoolwork.",
  "Put a finger down if you have ever studied with music playing in the background.",
  "Put a finger down if you have ever needed complete silence to concentrate.",
  "Put a finger down if you have ever changed study locations to regain focus.",
  "Put a finger down if you have ever studied at a library until closing time.",
  "Put a finger down if you have ever turned your phone over to avoid distractions while studying.",
  "Put a finger down if you have ever used a timer for a focused study session.",
  "Put a finger down if you have ever turned blank cards into a study deck.",
  "Put a finger down if you have ever used a digital flashcard set.",
  "Put a finger down if you have ever taught an imaginary class while reviewing a topic.",
  "Put a finger down if you have ever recorded yourself explaining study material.",
  "Put a finger down if you have ever rewritten notes to make them easier to review.",
  "Put a finger down if you have ever created an acronym to remember a list.",
  "Put a finger down if you have ever drawn a diagram to understand an idea.",
  "Put a finger down if you have ever turned facts into a song or rhyme.",
  "Put a finger down if you have ever practiced with questions from an earlier exam.",
  "Put a finger down if you have ever discovered that taking breaks improved your studying.",
  "Put a finger down if you have ever joined a study group for a difficult topic.",
  "Put a finger down if you have ever kept a study group on track.",
  "Put a finger down if you have ever learned more by helping someone else revise.",
  "Put a finger down if you have ever shared notes with a classmate who missed a lesson.",
  "Put a finger down if you have ever compared two different ways to solve the same problem.",
  "Put a finger down if you have ever changed your study method after one did not work.",
  "Put a finger down if you have ever planned a study schedule and adjusted it later.",
  "Put a finger down if you have ever studied something early and felt relieved afterward.",
  "Put a finger down if you have ever used office hours to work through a confusing concept.",
  "Put a finger down if you have ever found a helpful explanation in a library book.",
  "Put a finger down if you have ever used a practice quiz to find gaps in your knowledge.",
  "Put a finger down if you have ever explained a concept using an everyday example.",
  "Put a finger down if you have ever taken an exam in a room you had never visited before.",
  "Put a finger down if you have ever arrived early for an exam to settle in.",
  "Put a finger down if you have ever brought an extra writing tool to a test.",
  "Put a finger down if you have ever reread an exam question and noticed an important word.",
  "Put a finger down if you have ever skipped a difficult question and returned to it later.",
  "Put a finger down if you have ever changed an answer at the last moment.",
  "Put a finger down if you have ever finished an assessment with time to review your work.",
  "Put a finger down if you have ever used every minute available on an assessment.",
  "Put a finger down if you have ever felt calmer after answering the first test question.",
  "Put a finger down if you have ever remembered an answer just after leaving an exam.",
  "Put a finger down if you have ever taken an open-book assessment.",
  "Put a finger down if you have ever completed an oral assessment.",
  "Put a finger down if you have ever demonstrated a practical skill for an assessment.",
  "Put a finger down if you have ever built a portfolio instead of taking a final exam.",
  "Put a finger down if you have ever received useful comments on a draft before it was graded.",
  "Put a finger down if you have ever asked how an assessment would be evaluated.",
  "Put a finger down if you have ever used a rubric to improve your work.",
  "Put a finger down if you have ever corrected your own mistakes after an assessment.",
  "Put a finger down if you have ever been proud of your progress regardless of the score.",
  "Put a finger down if you have ever discovered that a test measured something you had practiced well.",
  "Put a finger down if you have ever given a presentation using slides.",
  "Put a finger down if you have ever presented without slides or notes.",
  "Put a finger down if you have ever practiced a presentation in front of a mirror.",
  "Put a finger down if you have ever timed yourself while rehearsing a speech.",
  "Put a finger down if you have ever memorized the opening line of a presentation.",
  "Put a finger down if you have ever forgotten a point and recovered during a presentation.",
  "Put a finger down if you have ever answered an unexpected question after presenting.",
  "Put a finger down if you have ever made a visual aid by hand.",
  "Put a finger down if you have ever used a prop to explain an idea.",
  "Put a finger down if you have ever presented a project with a partner.",
  "Put a finger down if you have ever divided speaking parts among a group.",
  "Put a finger down if you have ever redesigned a slide because it had too much text.",
  "Put a finger down if you have ever had presentation technology fail and continued anyway.",
  "Put a finger down if you have ever received applause after sharing your work.",
  "Put a finger down if you have ever become more comfortable speaking to a class over time.",
  "Put a finger down if you have ever watched a recorded presentation to improve your delivery.",
  "Put a finger down if you have ever asked the audience a question during a presentation.",
  "Put a finger down if you have ever demonstrated a process step by step for classmates.",
  "Put a finger down if you have ever created a poster for a class project.",
  "Put a finger down if you have ever presented research you genuinely enjoyed doing.",
  "Put a finger down if you have ever worked on a group project with someone new.",
  "Put a finger down if you have ever volunteered to organize a team's tasks.",
  "Put a finger down if you have ever taken meeting notes for a school project.",
  "Put a finger down if you have ever helped resolve a disagreement in a project group.",
  "Put a finger down if you have ever combined different teammates' ideas into one plan.",
  "Put a finger down if you have ever completed your part of a group project ahead of schedule.",
  "Put a finger down if you have ever reminded a project team about an upcoming deadline.",
  "Put a finger down if you have ever learned a new skill from a project teammate.",
  "Put a finger down if you have ever changed roles midway through a group assignment.",
  "Put a finger down if you have ever worked with classmates in a shared online document.",
  "Put a finger down if you have ever watched two people edit the same sentence at once.",
  "Put a finger down if you have ever named a group project something memorable.",
  "Put a finger down if you have ever built a model as part of a team.",
  "Put a finger down if you have ever conducted a survey for a class project.",
  "Put a finger down if you have ever interviewed someone for an assignment.",
  "Put a finger down if you have ever tested a project and improved it after feedback.",
  "Put a finger down if you have ever celebrated finishing a long team assignment.",
  "Put a finger down if you have ever stayed in touch with someone you met through a class project.",
  "Put a finger down if you have ever discovered that collaboration changed your original idea.",
  "Put a finger down if you have ever credited a teammate for a contribution others missed.",
  "Put a finger down if you have ever made a new friend in class.",
  "Put a finger down if you have ever saved a seat for a classmate.",
  "Put a finger down if you have ever welcomed a new student or learner.",
  "Put a finger down if you have ever helped someone catch up after an absence.",
  "Put a finger down if you have ever received help from a classmate without asking.",
  "Put a finger down if you have ever shared lunch with someone from your class.",
  "Put a finger down if you have ever swapped book recommendations with a classmate.",
  "Put a finger down if you have ever practiced a new language with another learner.",
  "Put a finger down if you have ever recognized a classmate years after studying together.",
  "Put a finger down if you have ever had a friendly debate during a lesson.",
  "Put a finger down if you have ever changed your perspective after hearing a classmate's view.",
  "Put a finger down if you have ever worked with someone whose approach was very different from yours.",
  "Put a finger down if you have ever encouraged a nervous classmate before they presented.",
  "Put a finger down if you have ever clapped for someone who tried something difficult in class.",
  "Put a finger down if you have ever invited someone to join your study table.",
  "Put a finger down if you have ever learned a greeting from a classmate's language.",
  "Put a finger down if you have ever discovered a shared hobby through a classroom conversation.",
  "Put a finger down if you have ever exchanged contact details to coordinate schoolwork.",
  "Put a finger down if you have ever recognized former classmates at a reunion.",
  "Put a finger down if you have ever laughed with classmates about a harmless classroom mix-up.",
  "Put a finger down if you have ever joined an academic club.",
  "Put a finger down if you have ever joined a club just to try something unfamiliar.",
  "Put a finger down if you have ever attended a club meeting during a lunch break.",
  "Put a finger down if you have ever helped plan a school club activity.",
  "Put a finger down if you have ever designed a flyer for a student event.",
  "Put a finger down if you have ever represented your class or course in a student group.",
  "Put a finger down if you have ever participated in a school election.",
  "Put a finger down if you have ever volunteered at a school event.",
  "Put a finger down if you have ever performed in a school concert or show.",
  "Put a finger down if you have ever worked behind the scenes at a school production.",
  "Put a finger down if you have ever displayed artwork at school.",
  "Put a finger down if you have ever entered a writing, science, or design competition.",
  "Put a finger down if you have ever attended a school fair or open day.",
  "Put a finger down if you have ever taken part in a themed school day.",
  "Put a finger down if you have ever contributed to a school publication.",
  "Put a finger down if you have ever helped with a fundraiser for a school cause.",
  "Put a finger down if you have ever joined a school trip connected to a lesson.",
  "Put a finger down if you have ever learned something memorable during a museum visit.",
  "Put a finger down if you have ever visited a workplace as part of a course.",
  "Put a finger down if you have ever received a certificate for participating in a school activity.",
  "Put a finger down if you have ever done a science experiment that worked on the first try.",
  "Put a finger down if you have ever repeated an experiment because the first result was unexpected.",
  "Put a finger down if you have ever worn safety equipment for a practical lesson.",
  "Put a finger down if you have ever grown a plant for a class activity.",
  "Put a finger down if you have ever built something that was stronger than you expected.",
  "Put a finger down if you have ever taken apart an object to learn how it worked.",
  "Put a finger down if you have ever followed a recipe during a learning activity.",
  "Put a finger down if you have ever practiced a workplace skill in a training room.",
  "Put a finger down if you have ever learned to use a tool under supervision.",
  "Put a finger down if you have ever fixed a small mistake in a practical project.",
  "Put a finger down if you have ever created something useful in a workshop class.",
  "Put a finger down if you have ever followed a demonstration before trying a task yourself.",
  "Put a finger down if you have ever learned through a simulation or role-play exercise.",
  "Put a finger down if you have ever practiced a procedure until it felt natural.",
  "Put a finger down if you have ever completed an internship, placement, or apprenticeship task.",
  "Put a finger down if you have ever kept a logbook of skills you were learning.",
  "Put a finger down if you have ever asked a trainer to check your technique.",
  "Put a finger down if you have ever earned a credential for a practical skill.",
  "Put a finger down if you have ever used classroom knowledge to solve a real-world problem.",
  "Put a finger down if you have ever taught someone a hands-on skill you learned in a course.",
  "Put a finger down if you have ever attended a live online class from home.",
  "Put a finger down if you have ever realized your microphone was on during an online lesson.",
  "Put a finger down if you have ever spoken while your microphone was muted.",
  "Put a finger down if you have ever used the chat box to answer an instructor's question.",
  "Put a finger down if you have ever changed your virtual background for class.",
  "Put a finger down if you have ever joined an online lesson from an unusual location.",
  "Put a finger down if you have ever had your internet connection freeze during an explanation.",
  "Put a finger down if you have ever watched a recorded lesson at a different time.",
  "Put a finger down if you have ever paused a lesson video to take notes.",
  "Put a finger down if you have ever increased or decreased a lecture video's playback speed.",
  "Put a finger down if you have ever completed an entire course online.",
  "Put a finger down if you have ever introduced yourself in an online discussion forum.",
  "Put a finger down if you have ever worked with a remote classmate in another time zone.",
  "Put a finger down if you have ever submitted a question through a virtual classroom tool.",
  "Put a finger down if you have ever taken notes on one screen while watching another.",
  "Put a finger down if you have ever downloaded lesson materials for offline study.",
  "Put a finger down if you have ever used captions or a transcript while learning.",
  "Put a finger down if you have ever attended virtual office hours.",
  "Put a finger down if you have ever completed an interactive online lab or simulation.",
  "Put a finger down if you have ever met an online classmate in person later.",
  "Put a finger down if you have ever returned to education after time away.",
  "Put a finger down if you have ever taken an evening or weekend class.",
  "Put a finger down if you have ever balanced coursework with a job.",
  "Put a finger down if you have ever studied while caring for other responsibilities.",
  "Put a finger down if you have ever enrolled in a course purely out of curiosity.",
  "Put a finger down if you have ever learned alongside people from several age groups.",
  "Put a finger down if you have ever taken a community education class.",
  "Put a finger down if you have ever attended a short workshop to refresh an old skill.",
  "Put a finger down if you have ever changed career plans after taking a course.",
  "Put a finger down if you have ever learned a skill to support a new role at work.",
  "Put a finger down if you have ever asked a younger classmate for help with a topic.",
  "Put a finger down if you have ever shared professional experience during a lesson.",
  "Put a finger down if you have ever completed coursework during a commute.",
  "Put a finger down if you have ever created a study routine around family commitments.",
  "Put a finger down if you have ever attended orientation as an adult learner.",
  "Put a finger down if you have ever rediscovered your confidence through learning.",
  "Put a finger down if you have ever earned a qualification later than you originally planned.",
  "Put a finger down if you have ever recommended a course to another adult learner.",
  "Put a finger down if you have ever used a newly learned skill the same week you learned it.",
  "Put a finger down if you have ever surprised yourself by enjoying being a student again.",
  "Put a finger down if you have ever checked out more library books than you could finish.",
  "Put a finger down if you have ever returned a library book just before it was due.",
  "Put a finger down if you have ever asked a librarian for help finding a source.",
  "Put a finger down if you have ever discovered a useful book while looking for another one.",
  "Put a finger down if you have ever used an index or table of contents to locate an answer.",
  "Put a finger down if you have ever searched an academic database for the first time.",
  "Put a finger down if you have ever read an abstract before deciding whether to use a source.",
  "Put a finger down if you have ever followed a citation to find the original research.",
  "Put a finger down if you have ever changed a research question after finding new evidence.",
  "Put a finger down if you have ever kept a list of sources while working on a project.",
  "Put a finger down if you have ever learned how to cite a source in a new format.",
  "Put a finger down if you have ever caught a missing citation during proofreading.",
  "Put a finger down if you have ever compared sources that disagreed with each other.",
  "Put a finger down if you have ever asked whether an online source was trustworthy.",
  "Put a finger down if you have ever used an archive or special collection for research.",
  "Put a finger down if you have ever surveyed classmates to gather original data.",
  "Put a finger down if you have ever made a chart to understand research findings.",
  "Put a finger down if you have ever narrowed a topic because it was too broad.",
  "Put a finger down if you have ever found the perfect source near the end of a project.",
  "Put a finger down if you have ever enjoyed researching a question with no obvious answer.",
  "Put a finger down if you have ever mixed up two similar terms during a lesson.",
  "Put a finger down if you have ever confidently opened a book to the wrong chapter.",
  "Put a finger down if you have ever written the correct answer in the wrong space.",
  "Put a finger down if you have ever misunderstood a deadline and checked it twice afterward.",
  "Put a finger down if you have ever brought the wrong materials to a class.",
  "Put a finger down if you have ever completed the optional question by accident.",
  "Put a finger down if you have ever studied a topic that was not included on the assessment.",
  "Put a finger down if you have ever pronounced a new academic word differently than expected.",
  "Put a finger down if you have ever erased a hole through a sheet of paper.",
  "Put a finger down if you have ever dropped your notes and had to reorder the pages.",
  "Put a finger down if you have ever opened a squeaky chair during a silent activity.",
  "Put a finger down if you have ever had a pen stop working in the middle of writing.",
  "Put a finger down if you have ever clicked the wrong button during a digital lesson.",
  "Put a finger down if you have ever printed a document with unexpected formatting.",
  "Put a finger down if you have ever noticed a calculation error by checking your units.",
  "Put a finger down if you have ever learned the most from a project that did not go as planned.",
  "Put a finger down if you have ever turned a mistake into an example for someone else.",
  "Put a finger down if you have ever laughed at your own harmless learning mix-up.",
  "Put a finger down if you have ever asked for another attempt after learning from feedback.",
  "Put a finger down if you have ever kept an early draft to see how much your work improved.",
] as const satisfies readonly string[];
