export const PUT_FINGER_PARTY: readonly string[] = [
  'Put a finger down if you have arrived at a party before the host finished setting up.',
  'Put a finger down if you have shown up late enough to miss the welcome speech.',
  'Put a finger down if you have waited outside a venue because you were unsure which entrance to use.',
  'Put a finger down if you have arrived while the venue was still being transformed for the celebration.',
  'Put a finger down if you have been the first guest to arrive and helped arrange the room.',
  'Put a finger down if you have timed your entrance so you would not be the first person there.',
  'Put a finger down if you have brought a guest after checking with the host first.',
  'Put a finger down if you have forgotten the apartment number while standing at the building.',
  'Put a finger down if you have followed music to find where a party was happening.',
  'Put a finger down if you have greeted the same person twice at one crowded event.',
  'Put a finger down if you have changed outfits at the last minute before a celebration.',
  'Put a finger down if you have arrived carrying more decorations than personal belongings.',
  'Put a finger down if you have offered to pick something up on the way to a gathering.',
  'Put a finger down if you have entered a party and immediately looked for someone you knew.',
  'Put a finger down if you have attended a celebration where the directions were part of the adventure.',
  'Put a finger down if you have mistaken a neighbor for another invited guest.',
  'Put a finger down if you have been welcomed by a pet before being welcomed by the host.',
  'Put a finger down if you have had to explain a very large gift at the door.',
  'Put a finger down if you have joined a party after another plan ended earlier than expected.',
  'Put a finger down if you have left home and gone back because you forgot the invitation.',
  'Put a finger down if you have recognized a party venue only because of the balloons outside.',
  'Put a finger down if you have been greeted with a name tag at a social event.',
  'Put a finger down if you have taken a quiet minute before walking into a lively room.',
  'Put a finger down if you have hosted a party and underestimated how many chairs you needed.',
  'Put a finger down if you have rearranged your living room to make space for dancing.',
  'Put a finger down if you have made a party playlist longer than the event itself.',
  'Put a finger down if you have hidden everyday clutter just before guests arrived.',
  'Put a finger down if you have welcomed guests while still finishing the decorations.',
  'Put a finger down if you have hosted a gathering where everyone ended up in the kitchen.',
  'Put a finger down if you have created a backup plan for an outdoor party because of the weather.',
  'Put a finger down if you have labeled party food so guests could identify what suited them.',
  'Put a finger down if you have moved the music to a comfortable volume after someone asked.',
  'Put a finger down if you have prepared a quieter corner for guests who wanted a break.',
  'Put a finger down if you have hosted more people than you originally expected.',
  'Put a finger down if you have sent a reminder because guests interpreted the start time differently.',
  'Put a finger down if you have improvised decorations from items already at home.',
  'Put a finger down if you have asked friends to help choose the party theme.',
  'Put a finger down if you have planned an activity that nobody used because conversation took over.',
  'Put a finger down if you have spent the whole event checking whether everyone had what they needed.',
  'Put a finger down if you have forgotten to take photos at a party you hosted.',
  'Put a finger down if you have offered guests containers for leftover food.',
  'Put a finger down if you have hosted a celebration in a space smaller than the guest list suggested.',
  'Put a finger down if you have delegated party jobs when doing everything alone became impossible.',
  'Put a finger down if you have checked dietary preferences before planning a party menu.',
  'Put a finger down if you have ended a gathering by sending everyone home with snacks.',
  'Put a finger down if you have cleaned up decorations the morning after hosting.',
  'Put a finger down if you have danced before anyone else joined the dance floor.',
  'Put a finger down if you have learned a dance move by copying the person beside you.',
  'Put a finger down if you have joined a dance circle without knowing what would happen next.',
  'Put a finger down if you have requested a song and celebrated when it finally played.',
  'Put a finger down if you have recognized a song from its first second.',
  'Put a finger down if you have taken a break because the music felt too loud.',
  'Put a finger down if you have moved away from a speaker so you could hear a conversation.',
  'Put a finger down if you have danced in a group where everyone knew different steps.',
  'Put a finger down if you have invented choreography during a song and immediately forgotten it.',
  'Put a finger down if you have cheered when the playlist switched to a favorite throwback.',
  'Put a finger down if you have stayed seated and still danced with your hands.',
  'Put a finger down if you have watched someone turn a quiet room into a dance floor.',
  'Put a finger down if you have sung the wrong lyrics with complete confidence.',
  'Put a finger down if you have asked the person controlling the music what song was playing.',
  'Put a finger down if you have joined a line dance after watching one full round.',
  'Put a finger down if you have danced in shoes that looked better than they felt.',
  'Put a finger down if you have switched to comfortable shoes before the dancing ended.',
  'Put a finger down if you have made a dramatic entrance when your favorite song came on.',
  'Put a finger down if you have formed a tiny dance floor in a room meant for something else.',
  'Put a finger down if you have heard a party song that became tied to that exact night.',
  'Put a finger down if you have danced under decorations that kept brushing your head.',
  'Put a finger down if you have helped build a playlist that pleased several generations.',
  'Put a finger down if you have ended the night with one last song everyone agreed on.',
  'Put a finger down if you have worn a costume that made sitting down surprisingly difficult.',
  'Put a finger down if you have arrived at a themed party more dressed up than everyone else.',
  'Put a finger down if you have interpreted a costume theme differently from the other guests.',
  'Put a finger down if you have made a costume from things you already owned.',
  'Put a finger down if you have helped someone repair a costume during a party.',
  'Put a finger down if you have worn face paint that lasted longer than the celebration.',
  'Put a finger down if you have coordinated costumes with a group.',
  'Put a finger down if you have abandoned part of a costume because it was uncomfortable.',
  'Put a finger down if you have had to explain your costume several times in one evening.',
  'Put a finger down if you have guessed someone immediately despite an elaborate disguise.',
  'Put a finger down if you have attended a decade-themed event and researched the fashion first.',
  'Put a finger down if you have added a last-minute accessory to match a party theme.',
  'Put a finger down if you have posed in character for a costume photo.',
  'Put a finger down if you have mistaken a regular outfit for a clever costume.',
  'Put a finger down if you have chosen a costume mainly because it had useful pockets.',
  'Put a finger down if you have attended a color-themed party in exactly the requested shade.',
  'Put a finger down if you have used a name tag because your costume hid your face.',
  'Put a finger down if you have voted in a friendly costume contest.',
  'Put a finger down if you have complimented a costume without understanding the reference.',
  'Put a finger down if you have kept a handmade prop after the themed event ended.',
  'Put a finger down if you have gone to a party decorated like a different place or era.',
  'Put a finger down if you have matched the theme using only one very specific accessory.',
  'Put a finger down if you have taken off a mask so people could hear you clearly.',
  'Put a finger down if you have explained a party game to people who all remembered different rules.',
  'Put a finger down if you have joined a game after it started and learned by watching.',
  'Put a finger down if you have kept score for a game you were not playing.',
  'Put a finger down if you have won a party game through luck rather than strategy.',
  'Put a finger down if you have become unexpectedly competitive during a harmless game.',
  'Put a finger down if you have suggested a team name that everyone actually used.',
  'Put a finger down if you have acted out a charades clue that nobody understood.',
  'Put a finger down if you have guessed a clue before the performance properly began.',
  'Put a finger down if you have drawn something unrecognizable during a guessing game.',
  'Put a finger down if you have changed a game rule so more guests could participate comfortably.',
  'Put a finger down if you have chosen to watch a round before deciding whether to join.',
  'Put a finger down if you have played a game that continued long after the planned finish.',
  'Put a finger down if you have celebrated a teammate solving the clue at the last second.',
  'Put a finger down if you have served as the unofficial referee for a friendly dispute.',
  'Put a finger down if you have invented a house rule that improved the game.',
  'Put a finger down if you have switched teams to make the numbers even.',
  'Put a finger down if you have played a game using improvised equipment.',
  'Put a finger down if you have laughed so much that you could not finish your turn.',
  'Put a finger down if you have taught a familiar game to someone playing it for the first time.',
  'Put a finger down if you have picked the hardest possible word in a guessing game.',
  'Put a finger down if you have applauded an especially creative wrong answer.',
  'Put a finger down if you have joined a party tournament with no expectation of reaching the final.',
  'Put a finger down if you have preferred the conversation around a game to the score.',
  'Put a finger down if you have introduced yourself to someone after talking for several minutes.',
  'Put a finger down if you have forgotten a new name immediately and politely asked again.',
  'Put a finger down if you have discovered a shared hobby with someone you met at a party.',
  'Put a finger down if you have been introduced by a friend who gave an unexpectedly long description of you.',
  'Put a finger down if you have joined a conversation because you recognized the topic.',
  'Put a finger down if you have helped a newcomer feel included in a group discussion.',
  'Put a finger down if you have realized you already followed a new acquaintance online.',
  'Put a finger down if you have met someone who knew you through a completely different friend group.',
  'Put a finger down if you have spent most of a party talking to one fascinating person.',
  'Put a finger down if you have exchanged contact details to continue a party conversation later.',
  'Put a finger down if you have used the food table as an easy place to start chatting.',
  'Put a finger down if you have bonded with another guest over not knowing many people there.',
  'Put a finger down if you have introduced two guests because you thought they would get along.',
  'Put a finger down if you have learned an unexpected fact about someone you had known for years.',
  'Put a finger down if you have joined a group conversation that moved through five unrelated topics.',
  'Put a finger down if you have mistaken how two guests knew each other.',
  'Put a finger down if you have remembered someone by their party story instead of their name.',
  'Put a finger down if you have reconnected with someone you had not seen in a long time.',
  'Put a finger down if you have found a familiar face at an event full of strangers.',
  'Put a finger down if you have welcomed someone into a conversation by explaining the context.',
  'Put a finger down if you have discovered that a new acquaintance lives surprisingly nearby.',
  'Put a finger down if you have left a celebration with a new friend.',
  'Put a finger down if you have thanked a host for seating you near people you enjoyed meeting.',
  'Put a finger down if you have squeezed into a group photo at the very last second.',
  'Put a finger down if you have blinked in the one photo everyone else loved.',
  'Put a finger down if you have taken several pictures because somebody was never ready.',
  'Put a finger down if you have volunteered to take the photo so nobody had to be left out.',
  'Put a finger down if you have used a timer and rushed into position for a party picture.',
  'Put a finger down if you have stood on the edge of a group photo and leaned inward.',
  'Put a finger down if you have asked before posting a celebration photo with other people in it.',
  'Put a finger down if you have discovered a decoration blocking someone in every picture.',
  'Put a finger down if you have taken a candid photo that captured the mood of the event.',
  'Put a finger down if you have posed with a prop that appeared in dozens of photos that night.',
  'Put a finger down if you have tried to recreate an old group picture at a reunion.',
  'Put a finger down if you have organized people by height for a large celebration photo.',
  'Put a finger down if you have laughed midway through a serious photo pose.',
  'Put a finger down if you have noticed later that someone was making a funny face in the background.',
  'Put a finger down if you have taken a picture of the decorations before guests arrived.',
  'Put a finger down if you have captured a cake moments before it was cut.',
  'Put a finger down if you have sent the best group photos to everyone the next day.',
  'Put a finger down if you have preferred an unplanned party picture to all the posed ones.',
  'Put a finger down if you have held several phones so the group could get the same picture.',
  'Put a finger down if you have stepped out of a photo and offered to take it instead.',
  'Put a finger down if you have found yourself in the background of a stranger’s celebration photo.',
  'Put a finger down if you have made a tiny photo booth from a decorated wall.',
  'Put a finger down if you have saved a party photo that still makes you smile years later.',
  'Put a finger down if you have gone back for seconds before some guests found the food table.',
  'Put a finger down if you have brought a dish that disappeared faster than expected.',
  'Put a finger down if you have asked for the recipe after tasting party food.',
  'Put a finger down if you have tried a celebration snack you could not identify at first.',
  'Put a finger down if you have balanced a plate while standing and talking.',
  'Put a finger down if you have saved room for cake even after a full meal.',
  'Put a finger down if you have helped carry a heavy cake without tilting it.',
  'Put a finger down if you have cut slices in several sizes so guests could choose.',
  'Put a finger down if you have brought your own suitable snack to an event.',
  'Put a finger down if you have found the last piece of your favorite party food.',
  'Put a finger down if you have decorated a dessert to match the celebration theme.',
  'Put a finger down if you have mistaken a decorative item for something edible.',
  'Put a finger down if you have guarded a dish until the guest of honor saw it.',
  'Put a finger down if you have turned leftovers into breakfast after a party.',
  'Put a finger down if you have helped serve food when the queue became long.',
  'Put a finger down if you have chosen a seat based on its distance from the snacks.',
  'Put a finger down if you have arrived with food in a container you wanted returned.',
  'Put a finger down if you have compared several versions of the same celebration dish.',
  'Put a finger down if you have made a separate portion to accommodate a guest’s dietary needs.',
  'Put a finger down if you have dropped a harmless crumb on an outfit moments before a photo.',
  'Put a finger down if you have packed a slice of cake to enjoy later.',
  'Put a finger down if you have helped set out food so every label was visible.',
  'Put a finger down if you have attended a party where the homemade food was the main attraction.',
  'Put a finger down if you have chosen a karaoke song because the chorus was easy.',
  'Put a finger down if you have sung karaoke with a group to feel more confident.',
  'Put a finger down if you have started a karaoke song in the wrong key.',
  'Put a finger down if you have handed the microphone to the audience for the best part.',
  'Put a finger down if you have added dramatic gestures to a karaoke performance.',
  'Put a finger down if you have discovered that a quiet guest had an incredible singing voice.',
  'Put a finger down if you have performed a duet without practicing together.',
  'Put a finger down if you have forgotten a lyric even while it was displayed on the screen.',
  'Put a finger down if you have chosen a song that was much longer than you remembered.',
  'Put a finger down if you have cheered for every karaoke singer regardless of skill.',
  'Put a finger down if you have changed your song choice after hearing someone else perform it.',
  'Put a finger down if you have sung backup from your seat instead of taking the microphone.',
  'Put a finger down if you have dedicated a karaoke song to the guest of honor.',
  'Put a finger down if you have turned one karaoke performance into a full group singalong.',
  'Put a finger down if you have selected a nostalgic song that everyone knew.',
  'Put a finger down if you have applauded someone for attempting a difficult song.',
  'Put a finger down if you have sung the harmony while another person carried the melody.',
  'Put a finger down if you have ended a song with a bow as though you were on tour.',
  'Put a finger down if you have laughed through a karaoke verse and recovered for the chorus.',
  'Put a finger down if you have encouraged a nervous singer without pressuring them to perform.',
  'Put a finger down if you have chosen a song mainly for its dance break.',
  'Put a finger down if you have performed karaoke in front of people you had just met.',
  'Put a finger down if you have lost your place because the karaoke screen changed too quickly.',
  'Put a finger down if you have helped light birthday candles while shielding them from the wind.',
  'Put a finger down if you have sung the birthday song at a completely different tempo from everyone else.',
  'Put a finger down if you have planned a surprise birthday and nearly revealed it by accident.',
  'Put a finger down if you have signed a birthday card moments before handing it over.',
  'Put a finger down if you have carried balloons that kept tangling together.',
  'Put a finger down if you have wrapped a birthday present in whatever paper was available.',
  'Put a finger down if you have attended two birthday celebrations for the same person in one week.',
  'Put a finger down if you have hidden before a surprise party and waited longer than expected.',
  'Put a finger down if you have chosen a birthday cake flavor by group vote.',
  'Put a finger down if you have made a birthday banner by hand.',
  'Put a finger down if you have remembered the candles but forgotten something to light them with.',
  'Put a finger down if you have coordinated a birthday message from people in different places.',
  'Put a finger down if you have attended a milestone birthday with photos from many years displayed.',
  'Put a finger down if you have guessed a birthday gift correctly before opening it.',
  'Put a finger down if you have helped create a birthday slideshow.',
  'Put a finger down if you have celebrated a birthday with an activity instead of a traditional party.',
  'Put a finger down if you have delivered a birthday cake without letting the guest of honor see it.',
  'Put a finger down if you have written a birthday message that filled the whole card.',
  'Put a finger down if you have shared your birthday celebration with someone born near the same date.',
  'Put a finger down if you have organized a low-key birthday exactly as the celebrant requested.',
  'Put a finger down if you have made breakfast feel like a birthday party.',
  'Put a finger down if you have celebrated a birthday remotely with a screen full of faces.',
  'Put a finger down if you have stayed late to help pack up after a birthday party.',
  'Put a finger down if you have attended a wedding where the ceremony started later than planned.',
  'Put a finger down if you have carried an extra safety pin for a formal celebration.',
  'Put a finger down if you have teared up during a wedding speech.',
  'Put a finger down if you have learned a family dance at a wedding reception.',
  'Put a finger down if you have caught up with relatives mainly at weddings.',
  'Put a finger down if you have helped direct guests toward their reception tables.',
  'Put a finger down if you have signed a wedding guest book with more than your name.',
  'Put a finger down if you have kept a wedding favor as a souvenir.',
  'Put a finger down if you have danced with someone from a different generation at a reception.',
  'Put a finger down if you have applauded a wedding entrance that became a full performance.',
  'Put a finger down if you have taken home a centerpiece after receiving permission.',
  'Put a finger down if you have worn formal clothes through unexpectedly warm weather.',
  'Put a finger down if you have helped fix a wedding decoration that came loose.',
  'Put a finger down if you have read the seating chart more than once to find your place.',
  'Put a finger down if you have met distant family members at a wedding.',
  'Put a finger down if you have joined a wedding photo containing more people than the photographer expected.',
  'Put a finger down if you have enjoyed a wedding tradition that was new to you.',
  'Put a finger down if you have traveled with formal clothes packed more carefully than everything else.',
  'Put a finger down if you have helped a wedding guest solve a small wardrobe problem.',
  'Put a finger down if you have watched the dance floor fill immediately after the first dance.',
  'Put a finger down if you have written advice for newlyweds as part of a reception activity.',
  'Put a finger down if you have joined a send-off line at the end of a wedding celebration.',
  'Put a finger down if you have left a wedding with a song stuck in your head.',
  'Put a finger down if you have attended a graduation party and compared school memories.',
  'Put a finger down if you have celebrated a promotion with a gathering outside work.',
  'Put a finger down if you have gone to a housewarming and toured every room.',
  'Put a finger down if you have brought a practical gift to a housewarming party.',
  'Put a finger down if you have attended a farewell celebration that felt both happy and sad.',
  'Put a finger down if you have made a toast using a non-alcoholic drink.',
  'Put a finger down if you have celebrated someone finishing a difficult project.',
  'Put a finger down if you have joined a reunion where nobody agreed on how long it had been.',
  'Put a finger down if you have attended a watch party where conversation drowned out the program.',
  'Put a finger down if you have decorated for a seasonal celebration with friends.',
  'Put a finger down if you have marked a small achievement with an unexpectedly big cheer.',
  'Put a finger down if you have attended an engagement celebration and heard the proposal story several times.',
  'Put a finger down if you have celebrated a new home before all the furniture arrived.',
  'Put a finger down if you have joined a retirement party filled with stories from different decades.',
  'Put a finger down if you have attended a launch party and tried something for the first time.',
  'Put a finger down if you have planned a picnic celebration around the weather forecast.',
  'Put a finger down if you have joined a countdown that the group started too early.',
  'Put a finger down if you have celebrated an anniversary by recreating an old photo.',
  'Put a finger down if you have attended a baby celebration with games for the guests.',
  'Put a finger down if you have turned an ordinary dinner into a celebration with one decoration.',
  'Put a finger down if you have traveled across town to celebrate good news in person.',
  'Put a finger down if you have joined a cultural celebration and followed the hosts’ guidance respectfully.',
  'Put a finger down if you have helped clean a venue after a community celebration.',
  'Put a finger down if you have exchanged an enthusiastic wave with someone whose name you could not remember.',
  'Put a finger down if you have opened a door and interrupted a surprise waiting on the other side.',
  'Put a finger down if you have spent several minutes looking for glasses that were on your head.',
  'Put a finger down if you have called someone by the wrong name and corrected yourself immediately.',
  'Put a finger down if you have dropped a party napkin and chased it across the room.',
  'Put a finger down if you have sat in a seat someone was saving without realizing it.',
  'Put a finger down if you have told a story at a party and forgotten the ending halfway through.',
  'Put a finger down if you have laughed at a joke a moment after everyone else.',
  'Put a finger down if you have worn a sticker from a party game for the rest of the evening.',
  'Put a finger down if you have carried someone else’s identical coat before noticing.',
  'Put a finger down if you have tried to leave a conversation and accidentally started a new one.',
  'Put a finger down if you have clapped because everyone else started clapping.',
  'Put a finger down if you have mistaken a decorative bowl for the snack bowl.',
  'Put a finger down if you have returned from getting food and forgotten where you were sitting.',
  'Put a finger down if you have walked into a photo just as it was being taken.',
  'Put a finger down if you have given directions to the restroom despite not knowing where it was.',
  'Put a finger down if you have tried to help with decorations and made one hang crooked.',
  'Put a finger down if you have begun telling a party story before realizing the group already knew it.',
  'Put a finger down if you have found confetti in your belongings days after a celebration.',
  'Put a finger down if you have left a party with a container that belonged to a different guest.',
  'Put a finger down if you have started saying goodbye and remained at the party for another hour.',
  'Put a finger down if you have checked every pocket for a party ticket that was tucked inside your phone case.',
  'Put a finger down if you have joined the wrong queue at a busy celebration.',
  'Put a finger down if you have taken a party decoration home because it was accidentally stuck to you.',
] as const
