export const PUT_FINGER_FUNNY = [
  'Put a finger down if you have ever opened the fridge and forgotten what you wanted.',
  'Put a finger down if you have ever searched for glasses that were already on your face.',
  'Put a finger down if you have ever looked for your phone while holding it.',
  'Put a finger down if you have ever walked into a room and forgotten why you went there.',
  'Put a finger down if you have ever put something somewhere safe and never found it again.',
  'Put a finger down if you have ever checked the time and immediately forgotten it.',
  'Put a finger down if you have ever started a sentence and lost your point halfway through.',
  'Put a finger down if you have ever forgotten a familiar word and described it with gestures.',
  'Put a finger down if you have ever left home and returned to check whether you locked the door.',
  'Put a finger down if you have ever forgotten your reusable bag until you reached the checkout.',
  'Put a finger down if you have ever made a reminder and then forgotten to read it.',
  'Put a finger down if you have ever entered the wrong password several times with total confidence.',
  'Put a finger down if you have ever forgotten which side of a building you parked on.',
  'Put a finger down if you have ever put the television remote in an unusual place.',
  'Put a finger down if you have ever nearly left home wearing slippers.',
  'Put a finger down if you have ever forgotten about a drink until it went cold.',
  'Put a finger down if you have ever opened a cupboard and stared at it for inspiration.',
  'Put a finger down if you have ever written a shopping list and left it at home.',
  'Put a finger down if you have ever forgotten what day of the week it was.',
  'Put a finger down if you have ever carried an empty container around instead of throwing it away.',
  'Put a finger down if you have ever tried to unlock the wrong car.',
  'Put a finger down if you have ever forgotten an umbrella on the one day it rained.',
  'Put a finger down if you have ever found something you lost after replacing it.',
  'Put a finger down if you have ever set two alarms and slept through both.',
  'Put a finger down if you have ever forgotten a task while opening the app meant to help with it.',
  'Put a finger down if you have ever carried a letter around for days before mailing it.',
  'Put a finger down if you have ever reheated food and left it in the microwave.',
  'Put a finger down if you have ever forgotten the punch line while telling a joke.',
  'Put a finger down if you have ever packed everything except the item you needed most.',
  'Put a finger down if you have ever arrived early because you remembered the time incorrectly.',
  'Put a finger down if you have ever typed a message in the search bar by mistake.',
  'Put a finger down if you have ever replied to a message only in your head.',
  'Put a finger down if you have ever joined a video call with the camera pointed somewhere unexpected.',
  'Put a finger down if you have ever spoken for a while before noticing you were muted.',
  'Put a finger down if you have ever taken a screenshot while trying to turn off your phone.',
  'Put a finger down if you have ever watched a loading icon before realizing the video was paused.',
  'Put a finger down if you have ever blamed the internet before checking your own Wi-Fi setting.',
  'Put a finger down if you have ever tried to zoom in on a printed photograph.',
  'Put a finger down if you have ever sent an unfinished message by tapping the wrong button.',
  'Put a finger down if you have ever refreshed a page as though that would make news arrive faster.',
  'Put a finger down if you have ever had autocorrect turn a normal message into nonsense.',
  'Put a finger down if you have ever plugged in a device and forgotten to switch on the outlet.',
  'Put a finger down if you have ever worn headphones that were not connected to anything.',
  'Put a finger down if you have ever recorded a voice note and disliked the sound of your own voice.',
  'Put a finger down if you have ever accidentally opened the front camera at an unflattering angle.',
  'Put a finger down if you have ever clicked a notification and immediately forgotten what it said.',
  'Put a finger down if you have ever flipped a reversible charging plug several times.',
  'Put a finger down if you have ever waited for a reply before noticing your message never sent.',
  'Put a finger down if you have ever ended a call and kept talking to the empty room.',
  'Put a finger down if you have ever waved at your own reflection on a video call.',
  'Put a finger down if you have ever closed the tab that was playing music and lost it among many tabs.',
  'Put a finger down if you have ever used a calculator for a sum you could have done in your head.',
  'Put a finger down if you have ever accepted an update and instantly regretted the new layout.',
  'Put a finger down if you have ever tried to swipe a screen that was not touch-sensitive.',
  'Put a finger down if you have ever stared at a frozen screen before realizing the battery was empty.',
  'Put a finger down if you have ever copied something and pasted an entirely different thing.',
  'Put a finger down if you have ever turned your volume up during an unexpectedly loud video.',
  'Put a finger down if you have ever used a device flashlight to search for that same device.',
  'Put a finger down if you have ever created a new password and immediately needed to reset it.',
  'Put a finger down if you have ever reacted to the wrong message in a group chat.',
  'Put a finger down if you have ever answered a question meant for someone else.',
  'Put a finger down if you have ever introduced two people who had already met.',
  'Put a finger down if you have ever held a door for someone who was still very far away.',
  'Put a finger down if you have ever smiled at someone who was looking past you.',
  'Put a finger down if you have ever said goodbye and then walked in the same direction as the other person.',
  'Put a finger down if you have ever forgotten a name moments before making an introduction.',
  'Put a finger down if you have ever started clapping before everyone else.',
  'Put a finger down if you have ever laughed because everyone else was laughing without knowing why.',
  'Put a finger down if you have ever joined the wrong queue and waited before noticing.',
  'Put a finger down if you have ever mistaken a stranger for someone you knew from behind.',
  'Put a finger down if you have ever responded to a greeting that was meant for the person beside you.',
  'Put a finger down if you have ever told a story to someone who was there when it happened.',
  'Put a finger down if you have ever practiced saying a name quietly before greeting someone.',
  'Put a finger down if you have ever forgotten whether you had already told someone the same news.',
  'Put a finger down if you have ever taken too long choosing a casual sign-off for a message.',
  'Put a finger down if you have ever ended a conversation and then remembered the important part.',
  'Put a finger down if you have ever complimented something only to learn it was borrowed.',
  'Put a finger down if you have ever missed a joke and laughed several seconds late.',
  'Put a finger down if you have ever worn a name tag with the writing upside down.',
  'Put a finger down if you have ever joined a conversation just as everyone stopped talking.',
  'Put a finger down if you have ever tried to shake hands while the other person offered a wave.',
  'Put a finger down if you have ever forgotten how you knew someone while chatting with them.',
  'Put a finger down if you have ever said something at the exact same time as another person.',
  'Put a finger down if you have ever walked away after paying before taking what you bought.',
  'Put a finger down if you have ever whispered something just as the room became quiet.',
  'Put a finger down if you have ever dressed for an event more formally than everyone else.',
  'Put a finger down if you have ever realized halfway through a conversation that you misunderstood the topic.',
  'Put a finger down if you have ever forgotten to unmute yourself after a quiet moment on a call.',
  'Put a finger down if you have ever waved goodbye and then had to return for something you forgot.',
  'Put a finger down if you have ever said good morning when it was already evening.',
  'Put a finger down if you have ever nodded as though you heard something you did not hear.',
  'Put a finger down if you have ever opened a snack upside down and spilled it.',
  'Put a finger down if you have ever taken a huge bite just before someone asked you a question.',
  'Put a finger down if you have ever burned toast and tried to scrape off the evidence.',
  'Put a finger down if you have ever made too much pasta because the dry portion looked tiny.',
  'Put a finger down if you have ever put a drink down and immediately forgotten which one was yours.',
  'Put a finger down if you have ever dropped food on your shirt during an important meal.',
  'Put a finger down if you have ever bitten into something before checking whether it was hot.',
  'Put a finger down if you have ever cooked something beautifully on one side and forgotten the other.',
  'Put a finger down if you have ever mistaken salt for sugar while cooking.',
  'Put a finger down if you have ever tried to quietly open a snack in a silent room.',
  'Put a finger down if you have ever chosen the messiest item on the menu by accident.',
  'Put a finger down if you have ever balanced too many groceries and dropped the lightest one.',
  'Put a finger down if you have ever found a missing utensil inside the food container.',
  'Put a finger down if you have ever eaten the garnish without knowing it was a garnish.',
  'Put a finger down if you have ever ordered food by pointing because you could not pronounce its name.',
  'Put a finger down if you have ever prepared a whole meal and then wanted cereal instead.',
  'Put a finger down if you have ever forgotten to remove the spoon before turning on a blender.',
  'Put a finger down if you have ever tried to catch a falling snack and made the spill worse.',
  'Put a finger down if you have ever taken the last piece and then discovered another box was coming.',
  'Put a finger down if you have ever hidden a snack from yourself and still found it too soon.',
  'Put a finger down if you have ever squeezed a sauce bottle and received far more than expected.',
  'Put a finger down if you have ever eaten around the burnt parts instead of starting over.',
  'Put a finger down if you have ever poured a bowl of cereal before noticing there was no milk.',
  'Put a finger down if you have ever dropped an ice cube and kicked it under an appliance.',
  'Put a finger down if you have ever peeled fruit and accidentally removed most of the fruit too.',
  'Put a finger down if you have ever tried to split a biscuit evenly and clearly failed.',
  'Put a finger down if you have ever made a sandwich too tall to eat neatly.',
  'Put a finger down if you have ever forgotten your food was being delivered until the doorbell rang.',
  'Put a finger down if you have ever eaten a sample and then felt obliged to consider buying it.',
  'Put a finger down if you have ever microwaved something that stayed cold in the middle.',
  'Put a finger down if you have ever cleaned one small spot and somehow made the entire room messier.',
  'Put a finger down if you have ever folded laundry and lived out of the basket anyway.',
  'Put a finger down if you have ever lost a sock between the washer and the drawer.',
  'Put a finger down if you have ever watered a plant because you forgot you already watered it.',
  'Put a finger down if you have ever moved clutter from one chair to another before a guest arrived.',
  'Put a finger down if you have ever changed the bedsheets and put one corner on the wrong way.',
  'Put a finger down if you have ever swept crumbs directly into another set of crumbs.',
  'Put a finger down if you have ever used a mug as a temporary storage container.',
  'Put a finger down if you have ever started tidying and become distracted by something you found.',
  'Put a finger down if you have ever carried every shopping bag at once to avoid a second trip.',
  'Put a finger down if you have ever tried to quietly close a door that became surprisingly loud.',
  'Put a finger down if you have ever left one clean plate in the dishwasher for several days.',
  'Put a finger down if you have ever bought an organizer and left it unorganized.',
  'Put a finger down if you have ever sat down just after remembering something across the room.',
  'Put a finger down if you have ever hidden a mess outside the camera frame.',
  'Put a finger down if you have ever worn an outfit straight from the drying rack.',
  'Put a finger down if you have ever discovered a pocket full of tissues after doing laundry.',
  'Put a finger down if you have ever used a chair as a wardrobe for longer than a week.',
  'Put a finger down if you have ever vacuumed around an object instead of picking it up.',
  'Put a finger down if you have ever bought batteries and forgotten what needed them.',
  'Put a finger down if you have ever left a cupboard door open and walked into it later.',
  'Put a finger down if you have ever made the bed moments before getting back into it.',
  'Put a finger down if you have ever discovered the missing remote underneath you.',
  'Put a finger down if you have ever replaced a light bulb only to learn the lamp was unplugged.',
  'Put a finger down if you have ever heard a mysterious noise that turned out to be an appliance.',
  'Put a finger down if you have ever put off a tiny chore longer than the chore eventually took.',
  'Put a finger down if you have ever opened all the windows and then complained about the temperature.',
  'Put a finger down if you have ever kept an empty box because it seemed too useful to discard.',
  'Put a finger down if you have ever measured furniture only after bringing it home.',
  'Put a finger down if you have ever taken the scenic route because you missed a turn.',
  'Put a finger down if you have ever packed for cold weather and arrived during a warm spell.',
  'Put a finger down if you have ever sat at the wrong gate until the crowd looked suspiciously small.',
  'Put a finger down if you have ever taken a travel pillow and never used it.',
  'Put a finger down if you have ever unpacked after a trip and found something you meant to use daily.',
  'Put a finger down if you have ever boarded public transport going in the wrong direction.',
  'Put a finger down if you have ever taken a photograph of a landmark with your finger in the frame.',
  'Put a finger down if you have ever arrived at a station just as your ride pulled away.',
  'Put a finger down if you have ever packed snacks that did not survive the first hour of a journey.',
  'Put a finger down if you have ever followed a map and still ended up back where you started.',
  'Put a finger down if you have ever brought a book on a trip and never opened it.',
  'Put a finger down if you have ever struggled to close a suitcase that closed easily at home.',
  'Put a finger down if you have ever waited at the wrong pickup point.',
  'Put a finger down if you have ever forgotten where you were going during a long walk.',
  'Put a finger down if you have ever packed matching clothes that did not match when you wore them.',
  'Put a finger down if you have ever taken more photos of food than of the destination.',
  'Put a finger down if you have ever had a souvenir break before the trip ended.',
  'Put a finger down if you have ever missed a stop because you were enjoying the view.',
  'Put a finger down if you have ever worn several layers because they would not fit in your bag.',
  'Put a finger down if you have ever confused two similar street names.',
  'Put a finger down if you have ever packed an empty charger without the cable.',
  'Put a finger down if you have ever taken a nap during a journey and woken up completely disoriented.',
  'Put a finger down if you have ever bought a postcard and brought it home unsent.',
  'Put a finger down if you have ever used a suitcase as furniture after returning home.',
  'Put a finger down if you have ever planned an early start and left around lunchtime.',
  'Put a finger down if you have ever chosen the slowest line at a ticket counter.',
  'Put a finger down if you have ever walked confidently while secretly waiting for directions to reload.',
  'Put a finger down if you have ever packed a backup item and forgotten the main item.',
  'Put a finger down if you have ever returned from a short trip with more luggage than you took.',
  'Put a finger down if you have ever swiped a transit pass at a hotel door.',
  'Put a finger down if you have ever put on a shirt backward and noticed much later.',
  'Put a finger down if you have ever worn two slightly different socks without realizing it.',
  'Put a finger down if you have ever discovered a clothing sticker only after getting home.',
  'Put a finger down if you have ever planned an outfit around one comfortable item.',
  'Put a finger down if you have ever dressed for sunshine and been surprised by rain.',
  'Put a finger down if you have ever tried on an outfit and returned to the first choice.',
  'Put a finger down if you have ever worn a new item before removing every tag.',
  'Put a finger down if you have ever discovered your pocket was sewn shut.',
  'Put a finger down if you have ever worn a jumper inside out because the seams looked intentional.',
  'Put a finger down if you have ever spent longer choosing shoes than attending the errand.',
  'Put a finger down if you have ever tucked in only the front of a shirt and forgotten about the back.',
  'Put a finger down if you have ever brought a jacket for weather that never arrived.',
  'Put a finger down if you have ever bought something because it had excellent pockets.',
  'Put a finger down if you have ever dressed in colors that matched by accident.',
  'Put a finger down if you have ever changed clothes after seeing the weather through the window.',
  'Put a finger down if you have ever discovered a price tag while already out in public.',
  'Put a finger down if you have ever worn a hat mainly to avoid fixing your hair.',
  'Put a finger down if you have ever found money in a coat you had not worn for months.',
  'Put a finger down if you have ever chosen comfort and immediately felt overdressed anyway.',
  'Put a finger down if you have ever put on shoes before remembering one last indoor task.',
  'Put a finger down if you have ever worn sunglasses on your head and searched for them.',
  'Put a finger down if you have ever tried to remove a loose thread and made it much longer.',
  'Put a finger down if you have ever packed a spare outfit that was less practical than the first.',
  'Put a finger down if you have ever worn something new and checked it for marks all day.',
  'Put a finger down if you have ever buttoned a shirt incorrectly and wondered why it felt uneven.',
  'Put a finger down if you have ever saved a nice outfit for an occasion that never appeared.',
  'Put a finger down if you have ever folded a sleeve differently on each arm.',
  'Put a finger down if you have ever worn a belt that was mostly decorative.',
  'Put a finger down if you have ever abandoned an outfit because the fabric squeaked.',
  'Put a finger down if you have ever dressed perfectly for the weather from the previous day.',
  'Put a finger down if you have ever sung a lyric confidently and learned years later that it was wrong.',
  'Put a finger down if you have ever danced while waiting for the kettle to boil.',
  'Put a finger down if you have ever narrated a simple task like a cooking show host.',
  'Put a finger down if you have ever made a dramatic entrance into an empty room.',
  'Put a finger down if you have ever practiced a facial expression in a mirror.',
  'Put a finger down if you have ever pretended an ordinary walk had a soundtrack.',
  'Put a finger down if you have ever applauded yourself for completing a tiny task.',
  'Put a finger down if you have ever invented a song about what you were doing.',
  'Put a finger down if you have ever raced an elevator by taking the stairs.',
  'Put a finger down if you have ever made sound effects for an object you were moving.',
  'Put a finger down if you have ever given a pet or plant an elaborate nickname.',
  'Put a finger down if you have ever held an imaginary interview with yourself.',
  'Put a finger down if you have ever turned a short walk into a personal parade.',
  'Put a finger down if you have ever celebrated finding something as though you won a trophy.',
  'Put a finger down if you have ever tried to land a paper ball in a bin from across the room.',
  'Put a finger down if you have ever copied a dance move without knowing the rest of the dance.',
  'Put a finger down if you have ever pretended a floor pattern had rules you needed to follow.',
  'Put a finger down if you have ever given a household object a pep talk before using it.',
  'Put a finger down if you have ever answered your own question out loud.',
  'Put a finger down if you have ever made a victory pose when nobody was watching.',
  'Put a finger down if you have ever turned tidying into a timed competition with yourself.',
  'Put a finger down if you have ever made up a backstory for a stranger you saw from afar.',
  'Put a finger down if you have ever tried to balance something on your head for no reason.',
  'Put a finger down if you have ever bowed after telling a joke that actually worked.',
  'Put a finger down if you have ever pretended to understand a pet or appliance sound.',
  'Put a finger down if you have ever walked in slow motion because the music felt right.',
  'Put a finger down if you have ever used a kitchen utensil as a pretend microphone.',
  'Put a finger down if you have ever created a rule for yourself and immediately negotiated an exception.',
  'Put a finger down if you have ever cheered when a traffic light changed in your favor.',
  'Put a finger down if you have ever named a Wi-Fi network something that amused only you.',
  'Put a finger down if you have ever walked past your destination because you were daydreaming.',
  'Put a finger down if you have ever tripped over absolutely nothing.',
  'Put a finger down if you have ever pulled a door marked push.',
  'Put a finger down if you have ever taken a wrong turn while following someone who also looked lost.',
  'Put a finger down if you have ever bumped into a chair that had not moved.',
  'Put a finger down if you have ever reached for a step that was not there.',
  'Put a finger down if you have ever dodged someone in the same direction more than once.',
  'Put a finger down if you have ever dropped something and kicked it farther away while retrieving it.',
  'Put a finger down if you have ever walked into a cobweb and performed an unexpected dance.',
  'Put a finger down if you have ever missed the bin from a very short distance.',
  'Put a finger down if you have ever hurried through the wrong doorway.',
  'Put a finger down if you have ever caught your sleeve on a door handle.',
  'Put a finger down if you have ever stumbled while trying to look graceful.',
  'Put a finger down if you have ever walked around an obstacle that was only a shadow.',
  'Put a finger down if you have ever tried to sit before the chair was fully in place.',
  'Put a finger down if you have ever bumped elbows with someone while both reaching for the same thing.',
  'Put a finger down if you have ever stepped around a puddle and landed in a different puddle.',
  'Put a finger down if you have ever dropped your keys while trying to look organized.',
  'Put a finger down if you have ever walked into the wrong restroom and backed out immediately.',
  'Put a finger down if you have ever spun around and forgotten which direction you were facing.',
  'Put a finger down if you have ever missed a high five and tried again.',
  'Put a finger down if you have ever waved an automatic door open before it detected you.',
  'Put a finger down if you have ever lost balance while putting on a shoe.',
  'Put a finger down if you have ever reached for an escalator handrail moving at a different speed.',
  'Put a finger down if you have ever taken one step onto a moving walkway and felt dramatically faster.',
  'Put a finger down if you have ever walked the wrong way around a revolving door.',
  'Put a finger down if you have ever stacked your belongings carefully and watched the top item slide off.',
  'Put a finger down if you have ever stepped on a squeaky floorboard while trying to be quiet.',
  'Put a finger down if you have ever caught something after several clumsy attempts and felt heroic.',
  'Put a finger down if you have ever turned around too quickly and startled yourself in a mirror.',
  'Put a finger down if you have ever watched one more episode after announcing you were going to bed.',
  'Put a finger down if you have ever read the same page twice because your mind wandered.',
  'Put a finger down if you have ever paused a film to look up where you recognized an actor from.',
  'Put a finger down if you have ever browsed every streaming option and then gone to bed.',
  'Put a finger down if you have ever cheered for a fictional character as though they could hear you.',
  'Put a finger down if you have ever skipped an introduction and then missed useful information.',
  'Put a finger down if you have ever reread an old message and laughed again.',
  'Put a finger down if you have ever opened a book at a random page to decide whether to read it.',
  'Put a finger down if you have ever guessed a plot twist and announced it too proudly.',
  'Put a finger down if you have ever watched the credits because the remote was out of reach.',
  'Put a finger down if you have ever listened to one song repeatedly until you needed a break from it.',
  'Put a finger down if you have ever started a new series while already halfway through another one.',
  'Put a finger down if you have ever used a receipt as a bookmark and then lost your place.',
  'Put a finger down if you have ever quoted a line that nobody else recognized.',
  'Put a finger down if you have ever fallen asleep during the part you were most excited to see.',
  'Put a finger down if you have ever judged a book by its cover and been completely wrong.',
  'Put a finger down if you have ever hummed a tune all day without knowing its title.',
  'Put a finger down if you have ever paused a podcast to tell an imaginary listener your opinion.',
  'Put a finger down if you have ever started a hobby after watching one impressive tutorial.',
  'Put a finger down if you have ever kept a puzzle piece aside and then forgotten where you put it.',
  'Put a finger down if you have ever laughed at a joke only after someone explained it.',
  'Put a finger down if you have ever turned two book pages at once and become completely confused.',
  'Put a finger down if you have ever become invested in a show someone else was watching nearby.',
  'Put a finger down if you have ever restarted a song because you missed your favorite part.',
  'Put a finger down if you have ever tried a craft and ended up with something entirely different.',
  'Put a finger down if you have ever watched a tutorial at double speed and still felt impatient.',
  'Put a finger down if you have ever continued watching something mainly because you had already started.',
  'Put a finger down if you have ever practiced trivia facts that never came up in conversation.',
  'Put a finger down if you have ever kept a ticket from an event and forgotten which event it was.',
  'Put a finger down if you have ever invented your own ending after a story finished unexpectedly.',
] as const satisfies readonly string[]
