export const RECONNECT_FAMILY_DEEP = [
  'What helps a family conversation feel emotionally safe enough for you to be honest?',
  'Which subjects would you rather approach slowly, and what pace would feel respectful?',
  'How can someone show they accept your no without becoming distant or punitive?',
  'What does privacy mean to you within a family relationship?',
  'When you need space, how would you like to communicate that?',
  'What boundary of yours is easiest to respect once people understand its purpose?',
  'How can relatives check whether advice is welcome before offering it?',
  'Which forms of affection feel comfortable to you, and which require asking first?',
  'What would make it easier to leave a tense conversation without ending the relationship?',
  'How do you prefer someone to respond when you decline a family invitation?',
  'Where do you draw the line between caring curiosity and intrusive questioning?',
  'What information about your life do you want control over sharing?',
  'How could this family make room for a person who chooses not to answer a question?',
  'When does helping begin to feel like taking over?',
  'What agreement could protect everyone during a difficult discussion?',
  'How would you like others to handle photos or stories about you in public?',
  'What kind of contact feels sustainable for you at this point in your life?',
  'Which boundary have you learned to state more clearly over time?',
  'How can family members honor different comfort levels around touch?',
  'What does a respectful pause look like when emotions are running high?',
  'When is it important to ask permission before involving another relative in a conflict?',
  'How might someone disagree with your choice while still respecting that it is yours?',
  'What would help you feel free to change your mind after saying yes?',
  'Which expectations around availability deserve to be discussed rather than assumed?',
  'How can care continue even when a boundary limits closeness?',
  'What part of your identity do you wish family members understood with more nuance?',
  'How has your sense of who counts as family changed across your life?',
  'Which name, title, or way of being addressed helps you feel recognized?',
  'What family label feels too narrow for a relationship that matters to you?',
  'How do culture and personal choice meet in the way you define yourself?',
  'What is something about your current life that an older version of you would not have predicted?',
  'Which part of yourself becomes easier to express outside family settings?',
  'How could relatives show respect for an identity or experience they do not fully understand?',
  'What does belonging feel like when it is not based on similarity?',
  'Which family tradition reflects you, and which one leaves you feeling unseen?',
  'How have your values become more your own over time?',
  'What assumption about your role in the family would you like retired?',
  'Who has earned a place in your chosen family, and what did they do to create that bond?',
  'What helps you feel included without being singled out?',
  'How should a family respond when someone shares a new name, pronoun, belief, or identity?',
  'Which parts of family history feel relevant to you without defining you?',
  'What would it mean for this family to celebrate difference without turning it into a debate?',
  'How do you want your relationships to adapt as you continue becoming yourself?',
  'What experience shaped you even though other relatives may not relate to it?',
  'Which qualities connect you to your family beyond biology or legal ties?',
  'How has moving between cultures, households, communities, or roles influenced you?',
  'What does being known on your own terms look like?',
  'How can someone stay curious about you without asking you to represent an entire group?',
  'What part of your identity brings you a sense of strength or ease?',
  'Which version of you do family members sometimes keep expecting, even though you have changed?',
  'What change in another relative have you needed time to understand?',
  'How do you want people to acknowledge growth without erasing what came before?',
  'What has changed in your life that deserves more room in family conversations?',
  'When have you surprised yourself by responding differently from an old pattern?',
  'Which family expectation no longer fits the person you are now?',
  'How can relationships stay flexible when people grow in different directions?',
  'What transition has altered the kind of support you need?',
  'How do you recognize when a familiar role has become limiting?',
  'What would help relatives update their understanding of you?',
  'Which change are you still making sense of, without needing anyone to solve it?',
  'How has distance, closeness, or changing contact affected the way you see this family?',
  'What is one belief about family that you have reconsidered?',
  'How might you make room for someone whose priorities have shifted?',
  'What do you hope remains steady even as your relationships evolve?',
  'Which past family rule deserves a thoughtful review?',
  'How have your needs for independence and connection changed over time?',
  'What would a generous response to an unexpected life change sound like?',
  'When a tradition changes, what meaning would you want to preserve?',
  'What are you learning to release about how family life is supposed to look?',
  'How could you tell someone that your capacity has changed without apologizing for existing?',
  'Which new pattern would you like to practice, even if it feels unfamiliar at first?',
  'What does it take for family members to let each other outgrow old stories?',
  'How can people remain connected without requiring everyone to change at the same speed?',
  'What would you want acknowledged before attempting to repair a strained relationship?',
  'How can an apology center impact rather than the speaker\'s intentions?',
  'What makes a promise to do better feel believable to you?',
  'When harm cannot be undone, what kind of responsibility is still possible?',
  'How would you distinguish accountability from blame in a family conflict?',
  'What signs tell you that someone is repairing trust through actions?',
  'Which matters more after a rupture: explanation, acknowledgment, changed behavior, or something else?',
  'How can someone hear about hurt they caused without demanding reassurance?',
  'What would a sincere attempt to make amends include for you?',
  'When is an apology premature because the person still needs to listen?',
  'How could relatives address a painful pattern without assigning one person the entire problem?',
  'What role does patience play when repair is wanted but trust has not returned?',
  'How can you take responsibility without defining yourself only by a mistake?',
  'What does repair look like when renewed closeness is not the desired outcome?',
  'Which behavior change would speak louder than repeated apologies?',
  'How should someone respond if their attempt at repair is not accepted?',
  'What helps prevent a disagreement from becoming a trial of someone\'s character?',
  'When have you seen accountability handled with dignity?',
  'How can two people recognize different impacts from the same event?',
  'What would make it safer to name a small hurt before it becomes resentment?',
  'Which repair efforts require collaboration, and which belong to the person who caused harm?',
  'How can family members avoid using good intentions to dismiss consequences?',
  'What is the difference between moving forward and pretending nothing happened?',
  'How might someone demonstrate remorse while respecting another person\'s need for distance?',
  'What would help a repaired relationship become different rather than merely restored?',
  'What kind of support feels most useful when you are overwhelmed?',
  'How do you prefer people to ask about your needs when you seem quiet?',
  'Which need is hardest for you to express without feeling demanding?',
  'What helps you receive care without feeling indebted?',
  'How can someone offer practical help while leaving you room to choose?',
  'When you share a problem, how can a listener learn whether you want empathy or ideas?',
  'What makes a request feel clear rather than loaded with unspoken consequences?',
  'How do you tell the difference between a need and a preferred solution?',
  'Which small act helps you feel considered during a stressful week?',
  'What would make it safer to say that you do not have capacity to help?',
  'How can relatives discuss money, time, or caregiving needs without treating access as entitlement?',
  'What kind of reassurance is comforting to you, and what kind feels dismissive?',
  'When do you need company, and when do you recover better alone?',
  'How would you like someone to check in after a difficult conversation?',
  'What support can be offered without requiring you to explain everything first?',
  'Which unmet need tends to show up indirectly in the way you communicate?',
  'How could family members make asking for accommodation feel ordinary?',
  'What does mutual support look like when people have very different resources?',
  'How do you want others to respond when they cannot meet a request?',
  'What helps you clarify a need before frustration takes over?',
  'Which kinds of care are meaningful to you even when they are quiet or practical?',
  'How can a family avoid making one person the default helper?',
  'What would equitable support look like here, rather than identical support?',
  'When has someone respected both your vulnerability and your competence?',
  'How might you ask for connection without making another person responsible for your emotions?',
  'What familiar pattern do you notice yourself entering during family tension?',
  'How does your communication change when you expect not to be heard?',
  'Which role do you slip into automatically around relatives?',
  'What usually happens just before a family conversation becomes unproductive?',
  'How can you interrupt a cycle without claiming to control everyone in it?',
  'When does humor bring relief, and when does it prevent honesty?',
  'What family habit once served a purpose but now creates distance?',
  'How do silence and avoidance function differently for you?',
  'Which unspoken rule influences this family more than people admit?',
  'What helps you stay present instead of preparing your defense?',
  'How do people in this family signal disagreement without saying it directly?',
  'What pattern would become clearer if everyone described only their own part?',
  'When does urgency make a conflict harder to resolve?',
  'How could a recurring argument be reframed as a shared problem?',
  'What happens when someone in the family breaks from an expected role?',
  'Which coping style of yours is useful in some settings but costly in family relationships?',
  'How can you recognize escalation early enough to choose a different response?',
  'What does defensiveness protect for you, and what does it make harder?',
  'When do old comparisons between relatives still shape present interactions?',
  'How might the family respond differently to mistakes than it has in the past?',
  'Which subjects tend to collect assumptions because nobody discusses them directly?',
  'What pattern would you like others to point out gently when you repeat it?',
  'How can one person\'s growth affect a family system without making them responsible for fixing it?',
  'What helps a new habit survive when the old dynamic feels more familiar?',
  'Which cycle could soften if people slowed down and checked what they heard?',
  'Where does decision-making power sit in this family, whether formally or informally?',
  'How can age or seniority be honored without giving someone unlimited authority?',
  'When does financial support come with expectations that need to be named?',
  'Whose preferences are most often treated as the default?',
  'How can a person with more influence make disagreement safer for others?',
  'What does shared decision-making look like when outcomes affect people differently?',
  'Which family contribution is undervalued because it is less visible?',
  'How do status, income, education, health, or location shape whose voice is heard?',
  'When can generosity become leverage, even if that was not the stated intention?',
  'What would it take to question a family leader without being labeled disrespectful?',
  'How should adults relate when childhood authority patterns still linger between them?',
  'Who absorbs the inconvenience when the family avoids a difficult decision?',
  'How can caregiving responsibility be negotiated rather than assigned by gender or birth order?',
  'What family choices should belong only to the person most affected?',
  'When is consensus useful, and when is individual consent the deciding factor?',
  'How could someone use their influence to create more room for quieter voices?',
  'What does respect mean when it flows in every direction?',
  'Which resources create obligation in this family, and are those obligations fair?',
  'How can relatives support someone\'s independence without withdrawing care?',
  'What changes when the person who usually organizes everything steps back?',
  'How might cultural expectations and personal agency be discussed without dismissing either?',
  'Where could responsibilities be redistributed more transparently?',
  'How can family members notice when gratitude is being demanded as obedience?',
  'What would make it possible for a less powerful person to say no safely?',
  'Which decision would benefit from hearing the people who usually adapt in silence?',
  'What personal choice do you want relatives to trust you to make for yourself?',
  'How do you balance accepting input with keeping ownership of your decisions?',
  'What does supportive concern sound like when it does not become control?',
  'When has someone given you room to learn from your own choice?',
  'How can relatives stay connected to a path they would not choose themselves?',
  'Which consequence of your decisions are you willing to carry without rescue?',
  'What helps you trust your judgment when family opinions are strong?',
  'How would you like loved ones to respond to a risk that matters to you?',
  'What does independence mean to you beyond doing everything alone?',
  'When do repeated reminders cross from care into pressure?',
  'How can someone voice worry once and then respect your answer?',
  'What choice have you made that taught you something important about yourself?',
  'Where would collaboration strengthen your autonomy rather than reduce it?',
  'How do you want family members to treat decisions about your body, relationships, beliefs, or future?',
  'What freedom do you want younger or newer family members to have that you lacked?',
  'How can interdependence work without anyone losing their right to choose?',
  'When is stepping back the most caring response to someone else\'s decision?',
  'What would help separate disagreement from disloyalty?',
  'How might family advice become an invitation instead of an instruction?',
  'Which area of your life needs more confidence from others and less supervision?',
  'What responsibilities belong with autonomy in a healthy adult relationship?',
  'How can a family member remain available without monitoring your progress?',
  'When has permission to decide increased your willingness to seek guidance?',
  'What does it look like to honor someone\'s agency when they make an imperfect choice?',
  'How can concern be expressed without predicting disaster or withdrawing love?',
  'Which family expectation feels mutual, and which feels one-sided?',
  'What obligation have you carried without ever agreeing to it?',
  'How can traditions be offered as invitations rather than tests of loyalty?',
  'What do relatives assume about how often people should call, visit, or reply?',
  'Which milestone expectations leave too little room for different lives?',
  'How might celebrations include people with varied beliefs, budgets, abilities, and energy?',
  'What expectation becomes healthier once it is spoken aloud?',
  'How should a family handle different definitions of success?',
  'Which courtesy matters deeply to you even if others see it differently?',
  'What does showing up mean when physical presence is not possible or wanted?',
  'How can people renegotiate commitments when circumstances change?',
  'What role does reciprocity play in your expectations of family?',
  'Which holiday or gathering norm could become more flexible?',
  'How do you want relatives to respond when your priorities conflict with theirs?',
  'What expectations come with the word family that you do not personally share?',
  'When is disappointment honest, and when does expressing it become pressure?',
  'How can invitations make both acceptance and refusal genuinely welcome?',
  'What would reduce comparison around careers, relationships, caregiving, or achievement?',
  'Which family role carries expectations that no single person could meet?',
  'How might different capacities change what fairness looks like?',
  'What promise should be discussed more carefully before anyone makes it?',
  'How can relatives respect that closeness may look different across relationships?',
  'Which inherited expectation deserves consent from the current generation?',
  'What would happen if family members replaced guessing with asking?',
  'How do you separate what you hope for from what another person owes you?',
  'What helps you admit your part in a conflict without taking responsibility for all of it?',
  'How can someone explain their intentions while still owning the impact?',
  'Which commitment are you responsible for communicating when you can no longer keep it?',
  'What does reliability look like when life is unpredictable?',
  'How should responsibility be shared when several people contributed to a problem?',
  'When is it fair to ask for context without using context as an excuse?',
  'What responsibility do listeners have when someone speaks vulnerably?',
  'How can a person correct misinformation without exposing private details?',
  'Which consequences are appropriate to accept after breaking an agreement?',
  'What is your responsibility when you realize you have misunderstood someone?',
  'How can relatives own biased assumptions without making the affected person educate them?',
  'When have you confused keeping the peace with doing your part?',
  'What does following through communicate that words cannot?',
  'How might someone acknowledge benefiting from an unfair family pattern?',
  'Which shared responsibility needs a clearer owner, deadline, or limit?',
  'How can you repair a missed commitment before resentment builds?',
  'What belongs to you in managing your emotions during disagreement?',
  'When does protecting someone from consequences prevent growth?',
  'How can family members hold each other accountable without humiliation?',
  'What would responsible communication look like after you need to cancel?',
  'Which mistake taught you to make expectations more explicit?',
  'How can someone take ownership when their memory of an event differs from yours?',
  'What does it mean to be accountable for a pattern, not just a single incident?',
  'Where might self-compassion help you face responsibility more honestly?',
  'How do you know when trust is growing rather than merely being requested?',
  'What kind of consistency helps you relax in a family relationship?',
  'Which actions make confidentiality feel dependable?',
  'How can trust be rebuilt without asking the hurt person to ignore uncertainty?',
  'What makes someone safe to disagree with?',
  'When has a relative respected information you shared on your terms?',
  'How do transparency and privacy coexist in a trustworthy relationship?',
  'What would make a promise more realistic and easier to keep?',
  'Which small behavior affects your trust more than others might expect?',
  'How can someone respond when you question whether a change will last?',
  'What does emotional predictability mean to you?',
  'When is trust specific to one area rather than all-or-nothing?',
  'How should a person handle private information after a relationship changes?',
  'What helps you believe that your boundaries will be honored when you are absent?',
  'Which kind of honesty strengthens trust, even when the news is disappointing?',
  'How can relatives avoid turning access to one another into proof of trust?',
  'What would allow trust to grow at a pace chosen by the more cautious person?',
  'When does checking in feel reassuring, and when does it feel like surveillance?',
  'How can people be trustworthy when they cannot be constantly available?',
  'What do you need before relying on someone with an important task?',
  'Which breach of trust calls for a new boundary rather than a return to the old arrangement?',
  'How does admitting uncertainty affect your trust in someone?',
  'What evidence of change would matter more than a request for another chance?',
  'How can trust exist alongside a decision to keep some distance?',
  'What would help this family treat trust as something practiced, not owed?',
  'What form of connection would feel realistic and welcome in the next season?',
  'How could this family create meaningful contact without assuming everyone wants the same amount?',
  'Which conversation would be worth having if everyone could pause or pass?',
  'What is one way you hope family relationships become more spacious?',
  'How might you stay connected across different households, locations, or schedules?',
  'What new tradition could include biological, adoptive, foster, blended, extended, and chosen family?',
  'Which existing relationship would benefit from less intensity and more steadiness?',
  'What would a low-pressure invitation to connect look like?',
  'How can future gatherings make room for people who participate differently?',
  'What kind of relationship are you willing to build, without promising more than that?',
  'Which shared value could guide future contact even when opinions differ?',
  'How might technology support connection without creating constant access?',
  'What would make the next conversation feel more balanced than the last?',
  'How can relatives leave the door open without waiting at it or applying pressure?',
  'What would you enjoy learning about the people your family members are becoming?',
  'Which hopes for this family depend on your actions, and which do not?',
  'How could future plans account for disability, finances, caregiving, faith, and energy without judgment?',
  'What is one gentle experiment in connection you would be open to trying?',
  'How might separate traditions coexist without one being treated as the real family event?',
  'What would connection look like if it were measured by quality rather than frequency?',
  'Which relationship deserves clearer terms before it becomes closer?',
  'How can people honor a decision for limited or no contact without closing off their own growth?',
  'What do you want future family conversations to make more possible?',
  'How might you preserve goodwill when closeness is not currently workable?',
  'What is a hopeful next step that leaves every person free to choose?',
  'Which family story could be retold with more room for perspectives that were previously missing?',
  'How can relatives acknowledge unequal access to safety or opportunity without competing over hardship?',
  'What would help you listen for understanding when agreement may never come?',
] as const satisfies readonly string[]
