export const RECONNECT_FAMILY_MEANINGFUL: readonly string[] = [
  "What is something you appreciate about the way someone here shows care?",
  "Which quality in this family circle deserves more recognition?",
  "Name a small kindness from a relative or chosen family member that stayed with you.",
  "What do you admire about how someone here handles change?",
  "Who in your family network has taught you something useful without making a big speech?",
  "What is one contribution you make to family life that you feel good about?",
  "Which everyday gesture helps you feel valued by the people you call family?",
  "What strength do you see in this family when plans go sideways?",
  "Share a compliment for someone here that has nothing to do with achievement.",
  "What is a way a family member has made room for you to be yourself?",
  "Whose sense of humor brings something special to your family connections?",
  "What quiet form of care do you notice and appreciate?",
  "Which personal quality would you like someone in your family to know you see in them?",
  "What is something this family does well when people have different opinions?",
  "Recall a time someone related to you made an ordinary day easier.",
  "What is a family member's skill or talent you enjoy witnessing?",
  "How has someone in your family network helped you feel capable?",
  "What kind of effort from family feels especially meaningful to you?",
  "Which shared connection are you grateful has grown in its own way?",
  "What is one thing you respect about a person here, even if you are different?",
  "Describe a moment when a relative or chosen family member surprised you in a good way.",
  "What form of encouragement have you received from family that genuinely helped?",
  "Which trait has helped your family adapt across different seasons?",
  "What do you hope people in your family feel appreciated for?",
  "Offer thanks for something specific that someone here has done recently, if you wish.",
  "What is a strength you have developed through being part of this family?",
  "Who has a perspective that adds something valuable to your family conversations?",
  "When do you feel most like you belong with the people you consider family?",
  "What helps a family gathering feel welcoming to you?",
  "How would you describe the kind of belonging you want in family relationships?",
  "Which people, related or not, have earned a place in your idea of family?",
  "What makes it easier for you to bring your full personality into a family space?",
  "Is there a family role or label that feels especially right for you?",
  "What could help someone new feel included in this family circle?",
  "Where do you find a sense of home when home is not necessarily a place?",
  "What is one way family can honor both closeness and individuality?",
  "Which shared activity gives you an easy sense of connection?",
  "What signals tell you that you are welcome rather than merely expected?",
  "How can relatives make space for chosen family without ranking either bond?",
  "What does being included in a decision look like to you?",
  "Which parts of your identity feel understood in your family relationships?",
  "What would make celebrations more inclusive of the people who matter to you?",
  "How do you like family members to introduce or describe your relationship?",
  "What helps you stay connected when you do not share the same routines or location?",
  "Name a place, object, song, or flavor that gives you a sense of family belonging.",
  "What does a comfortable amount of togetherness look like for you these days?",
  "How might a family show that different life paths are equally welcome?",
  "What helps you feel seen when your experience differs from everyone else's?",
  "Which connection in your wider family network would you enjoy understanding better?",
  "What is one way people can include you without putting you on the spot?",
  "How has your definition of family expanded or shifted over time?",
  "What makes a shared space feel emotionally comfortable to you?",
  "When family members disagree about customs, what could help everyone still belong?",
  "What would a family culture of genuine welcome sound like?",
  "When you are having a hard day, what kind of support usually feels helpful?",
  "Would you rather receive advice, practical help, company, or space when stressed?",
  "What is a respectful way for family to check in with you?",
  "How can someone tell whether you want help or simply want to be heard?",
  "Which practical task would you be comfortable asking family for help with?",
  "What kind of encouragement feels sincere to you?",
  "If you go quiet, how would you prefer people respond?",
  "What makes an offer of help feel free of pressure?",
  "How do you like others to celebrate your good news?",
  "What support can family offer when there is no obvious solution?",
  "When you need time to decide, what response helps you feel respected?",
  "Which phrase helps you know someone is listening rather than fixing?",
  "How would you like a family member to ask about something important in your life?",
  "What kind of company feels comforting without requiring conversation?",
  "When plans change suddenly, what helps you adjust?",
  "What is one type of help you enjoy giving, and one you prefer not to give?",
  "How can family members support your goals without monitoring them?",
  "What does dependable support look like when people live far apart?",
  "If you are unsure what you need, how can others be present without guessing for you?",
  "What is a caring way to follow up after a difficult conversation?",
  "Which offers of support are easiest for you to receive?",
  "How do you prefer someone to respond when you say you are fine but seem tired?",
  "What would make asking for assistance feel safer or simpler?",
  "How can family show care while respecting a private matter?",
  "When someone declines help, what is a kind way to leave the door open?",
  "What kind of reassurance lands well for you during uncertainty?",
  "How do you want loved ones to respond when you change your mind?",
  "Which role in your family life has changed most naturally over time?",
  "What is different about the way you relate to family now compared with a few years ago?",
  "How can a family make room for someone who is becoming a new version of themselves?",
  "What expectation about your role would you like to update, if any?",
  "Which responsibility feels fair for you at this stage of life?",
  "How do you hope family relationships can adapt when circumstances change?",
  "What have you learned about letting people grow beyond old impressions?",
  "When a family structure changes, what helps preserve connection?",
  "What is one role you value and one role you do not want assigned to you?",
  "How might relatives check assumptions about who handles what?",
  "What part of growing older has changed the way you show care?",
  "How can people acknowledge a new partner, caregiver, sibling, or family member with warmth?",
  "Which family expectation has become less important to you over time?",
  "What helps relationships adjust when someone's capacity changes?",
  "How would you like your family to respond to a major life transition?",
  "What can make shifting responsibilities feel collaborative rather than imposed?",
  "Which old role are you glad no longer defines you?",
  "How do you recognize when a family arrangement needs renegotiation?",
  "What does mutual respect look like between generations or age groups?",
  "How can family members stay curious about each other instead of relying on old stories?",
  "What new chapter in a family relationship feels worth welcoming?",
  "When someone joins or leaves a household, what helps everyone find a workable rhythm?",
  "How might a family honor past roles without freezing anyone in them?",
  "What is one responsibility you would willingly share differently?",
  "How can changing availability be discussed without measuring anyone's love?",
  "Which relationship has become easier as expectations evolved?",
  "What does it mean to let a family bond find its own form?",
  "Which value do you try to bring into your family relationships?",
  "What does loyalty mean to you when healthy limits are also important?",
  "Which family value feels chosen by you rather than inherited?",
  "How do you decide what fairness looks like among people with different needs?",
  "Which words help disagreement remain respectful in a family conversation?",
  "Which principle guides how you repair a misunderstanding?",
  "What is one belief about family that you have thoughtfully revised?",
  "How can honesty and kindness support each other in a difficult conversation?",
  "Which value would you like future family decisions to reflect?",
  "What does generosity mean beyond money or gifts?",
  "How do you balance keeping your word with recognizing changed circumstances?",
  "Which matters more to you in conflict: clarity, calm, time, or something else?",
  "What does accountability look like without humiliation?",
  "How can a family respect different spiritual, cultural, or personal beliefs?",
  "Which everyday choice best reflects what you care about?",
  "What does privacy mean within a caring relationship?",
  "How do you distinguish support from obligation?",
  "Which values help people stay connected across strong differences?",
  "What is something you believe each person should get to decide for themselves?",
  "How can family members be honest when certainty is not available?",
  "What does trust require from both closeness and distance?",
  "Which inherited lesson still serves you well?",
  "What value do you hope people experience through your actions?",
  "How should care be expressed when two people define respect differently?",
  "What does keeping someone's confidence mean to you?",
  "Which is a meaningful way to make amends without demanding a particular response?",
  "How can people hold shared values while choosing different lives?",
  "Is there a tradition you enjoy because of how it feels rather than how long it has existed?",
  "What optional ritual could make ordinary time together more meaningful?",
  "Which food tradition would you keep, adapt, or happily replace?",
  "How can a celebration make room for people who participate in different ways?",
  "What new custom might fit the family you have now?",
  "Which tradition feels better when attendance is genuinely optional?",
  "What is a low-pressure ritual for staying connected across distance?",
  "How could a familiar holiday be made more comfortable for different needs?",
  "What shared practice would you enjoy starting without expecting it to last forever?",
  "Which tradition tells an interesting story about where someone came from?",
  "What would make gift-giving more thoughtful or less stressful for you?",
  "How might your family mark achievements that do not come with certificates?",
  "What seasonal activity feels inviting even to someone who skips the main celebration?",
  "Which cultural practice would you like to learn about respectfully?",
  "What is a tradition you prefer to observe quietly or in your own way?",
  "How can old customs be adapted when they no longer include everyone?",
  "What simple ritual could help people reconnect after time apart?",
  "Which sounds, scents, or dishes make a gathering feel distinctive to your family?",
  "What kind of celebration suits you better than a large event?",
  "If you could create a no-pressure family day, what might it include?",
  "What tradition could be retired with gratitude rather than conflict?",
  "How would you invite someone to share a custom without making them a spokesperson?",
  "What small recurring moment could become meaningful over time?",
  "Which tradition from a chosen family or blended family deserves a place at the table?",
  "How can a gathering honor multiple backgrounds without forcing them into one story?",
  "What is your favorite way to recognize a personal milestone?",
  "Which family recipe, craft, game, or saying would you enjoy teaching someone?",
  "Tell a family story that still makes you smile, if one comes to mind.",
  "What ordinary moment from your past feels surprisingly vivid?",
  "Which story about a relative or chosen family member captures their personality well?",
  "What is a harmless family mix-up that became funny later?",
  "Describe a meal you remember more for the company than the food.",
  "What object in your life carries a story you would be comfortable sharing?",
  "Which journey or outing taught you something unexpected about someone close to you?",
  "What family saying has a meaning outsiders might miss?",
  "Recall a time a plan changed and something delightful happened instead.",
  "What is a story about resourcefulness in your family network?",
  "Which memory shows someone being unmistakably themselves?",
  "What is the backstory of a nickname you are happy to discuss?",
  "Share a moment when different generations or age groups learned from one another.",
  "What tale about a pet, plant, neighborhood, or place belongs in your family lore?",
  "Which memory would you tell through sounds rather than photographs?",
  "What is a small adventure you would enjoy remembering together?",
  "Describe a time family teamwork worked better than expected.",
  "Which familiar story changes depending on who tells it?",
  "What is something amusing you once misunderstood about your family?",
  "Tell us about a skill that traveled through your family or chosen community.",
  "Which story deserves to be remembered even though it was not a major event?",
  "What is a moment when someone improvised brilliantly?",
  "If you want to share, what memory connects you to a particular song?",
  "Which family photo has an interesting scene just outside the frame?",
  "What story shows how a relationship began or found its footing?",
  "Recall a time someone made you laugh when you needed lightness.",
  "What is a pleasant memory you would like to hear from another person's perspective?",
  "What helps you know that someone has truly heard you?",
  "How do you prefer to begin a conversation about a sensitive topic?",
  "When you need a pause during a discussion, how would you like to signal it?",
  "What question makes it easier for you to clarify what you mean?",
  "How can someone disagree with you in a way that preserves connection?",
  "Which communication format works best for you when emotions are running high?",
  "What does a sincere apology need to include for you?",
  "How do you like to receive feedback from someone close to you?",
  "What helps you return to a conversation after taking space?",
  "Which assumption would you like family members to check with you instead of making?",
  "How can someone show curiosity without asking for more than you want to share?",
  "What tone or setting helps you speak honestly?",
  "When words come slowly, what kind of patience feels supportive?",
  "How would you prefer someone to tell you they cannot talk right now?",
  "What is a respectful way to correct a misunderstanding about you?",
  "How can a listener reflect what they heard while leaving room to be corrected?",
  "Which conversation habit would make family discussions easier for you?",
  "What helps you separate a person's intent from the impact of their words?",
  "How do you want people to raise a concern without turning it into a verdict?",
  "What makes a check-in feel genuine rather than routine?",
  "When is silence a helpful part of communication for you?",
  "What helps a conversation work for people who need different amounts of time to process?",
  "What is one sign that a conversation should continue later instead of now?",
  "How do you prefer to resolve a minor tension before it grows?",
  "Which words help you feel that a boundary has been understood?",
  "What would make group conversations easier for quieter voices to enter?",
  "How can humor connect people without dismissing what matters?",
  "What is one boundary that helps you show up more genuinely in family relationships?",
  "How would you like people to respond when you say no?",
  "Which topics do you prefer to discuss only when you choose the time?",
  "What helps a boundary feel caring rather than rejecting?",
  "How can family members ask before sharing your news with others?",
  "What does respectful physical affection look like to you?",
  "How do you prefer to handle invitations when your answer is uncertain?",
  "What is a comfortable way for someone to ask about your availability?",
  "Which personal decisions would you like family to trust you to make?",
  "How can people stay connected without expecting immediate replies?",
  "What kind of advance notice helps you participate by choice?",
  "How would you explain the difference between privacy and secrecy in a healthy relationship?",
  "What does consent look like when taking or posting family photos?",
  "How can someone revisit a boundary without arguing against it?",
  "Which form of contact feels most manageable when your energy is low?",
  "What would help family members respect different comfort levels around touch?",
  "How do you want others to handle a question you choose not to answer?",
  "What is a considerate way to leave a gathering early?",
  "How can relatives offer closeness without treating access as an entitlement?",
  "What boundary helps you protect time for rest or other relationships?",
  "How should family members respond when customs conflict with someone's limits?",
  "What is a respectful way to request space without explaining everything?",
  "How can a host make dietary or accessibility needs easy to state?",
  "Which expectations around calls, messages, or visits would benefit from clarity?",
  "What helps you trust that a private conversation will stay private?",
  "How can someone accept a changed boundary with grace?",
  "What is one way to care for a relationship while limiting a particular interaction?",
  "What part of your identity feels especially alive these days?",
  "Which name, title, or form of address feels most comfortable to you?",
  "What interest or community has shaped how you see yourself?",
  "How would you like family to support an identity or choice they are still learning about?",
  "What part of your background do you enjoy sharing on your own terms?",
  "Which aspect of yourself has become clearer with time?",
  "What helps you feel respected when your identity does not fit someone's expectations?",
  "How do language, place, culture, or community influence your sense of self?",
  "What is something about you that cannot be summed up by your family role?",
  "Which chosen connection has helped you understand yourself better?",
  "How can family show interest in your life without treating you as a lesson?",
  "What part of your identity brings you energy or joy?",
  "How would you like people to respond when they use the wrong word for you?",
  "Which personal interest deserves more room in how family members know you?",
  "What does being known accurately mean to you?",
  "How can a family honor multiple cultures within one gathering?",
  "What is one way you have made an inherited practice your own?",
  "Which part of your story would you rather describe for yourself than have others define?",
  "What has helped you feel at home in a community?",
  "How do you want family to make space for beliefs that are still developing?",
  "What is a label you value, dislike, or simply feel unsure about?",
  "Which influence outside your family has enriched who you are?",
  "How can relatives remain open when someone's self-understanding changes?",
  "What part of your identity do you express differently in different settings?",
  "Which family resemblance do you enjoy, whether or not it is biological?",
  "What does authenticity look like for you in a family setting?",
  "How might people celebrate individuality without making anyone feel singled out?",
  "What is a realistic hope you have for a family relationship?",
  "Which kind of moment would you like to make more room for together?",
  "If family communication improved in one practical way, what change would matter to you?",
  "How would you like support to evolve over the next year?",
  "What future gathering could feel meaningful without being elaborate?",
  "Which shared project might bring out the best in different people?",
  "What do you hope remains flexible in your family connections?",
  "How might this family become more welcoming to new perspectives?",
  "What is one gentle change that could improve time spent together?",
  "Which relationship would you like to approach with fresh curiosity, if any?",
  "What do you hope younger or newer family members are free to choose for themselves?",
  "How could family members make future decisions more collaboratively?",
  "What is a skill you would enjoy learning with someone in your family network?",
  "Which kind of support do you hope becomes easier to request?",
  "What would a sustainable rhythm of connection look like for you?",
  "When relatives want different futures, how could each hope be treated with respect?",
  "What is something pleasant you would like to plan without turning it into an obligation?",
  "Which value do you hope guides the next chapter of your family life?",
  "What could help future conversations feel safer and more balanced?",
  "How would you like people to notice and celebrate growth in one another?",
  "What is a hope you can hold lightly, without needing a promise from anyone?",
  "Which new tradition might reflect who your family is becoming?",
  "What would you like more space for in your relationships: play, rest, honesty, learning, or something else?",
  "How can family members encourage one another's plans while allowing them to change?",
  "What future memory would you enjoy creating with people you consider family?",
  "Which conversation would you like to have someday, with no pressure to have it now?",
  "What would respectful connection look like if everyone chose their own pace?",
  "How might your family care for its relationships during a busy season?",
  "What is one possibility for greater understanding that feels manageable?",
  "What do you hope people carry with them after spending time with this family circle?",
]
