export const RECONNECT_FAMILY_LIGHT: readonly string[] = [
  'What has been taking up the good kind of space in your week?',
  'Which ordinary part of your day has felt especially pleasant lately?',
  'What is something new you have learned to enjoy?',
  'How would you describe your current routine using a movie title?',
  'Which recent moment made you laugh harder than expected?',
  'What small win would you happily celebrate with confetti?',
  'Which app, tool, or shortcut has made life easier recently?',
  'What have you been curious about these days?',
  'Which part of your week deserves a tiny trophy?',
  'What is the nicest surprise you have had lately?',
  'Which everyday task do you secretly find satisfying?',
  'What are you currently looking forward to, however small?',
  'Which recent purchase has earned its keep?',
  'What is one thing you have gotten better at without noticing?',
  'If today had a weather forecast for your mood, what would it say?',
  'What has been your most reliable source of a quick smile?',
  'What easy conversation has added a little brightness to your week?',
  'What is a harmless opinion you have changed your mind about?',
  'Which part of your current schedule would you gladly keep?',
  'What has felt refreshingly simple lately?',
  'Which song best matches the pace of your life right now?',
  'What is one update from your world that you would put in a friendly newsletter?',
  'Which skill are you enjoying using these days?',
  'What is the most interesting thing you have noticed this month?',
  'Which little luxury feels completely worth it to you?',
  'What is giving you a sense of momentum at the moment?',
  'Which part of your day could use a more fun name?',
  'What is one recent choice you are pleased you made?',
  'Which object near you says the most about your life these days?',
  'What topic could you give a cheerful two-minute update about?',
  'Which snack has been doing excellent work for you lately?',
  'What meal would you happily eat twice in one week?',
  'How do you like your toast, if toast is on the menu?',
  'Which food aroma instantly gets your attention?',
  'What dish do you enjoy more as leftovers?',
  'Which fruit has the best personality?',
  'What is your ideal level of spice?',
  'Which drink feels most like a treat without needing an occasion?',
  'What food combination sounds odd but works for you?',
  'Which breakfast could persuade you to get up early?',
  'What ingredient makes almost anything better?',
  'Which type of potato deserves the top spot?',
  'What is your strongest harmless restaurant preference?',
  'Which dessert has the best texture?',
  'What would you put on a build-your-own sandwich bar?',
  'Which soup would you choose on a rainy day?',
  'What food do you enjoy preparing as much as eating?',
  'Which snack would you bring for a relaxed catch-up?',
  'What is the best thing to eat straight from the fridge?',
  'Which cuisine would you like to explore more?',
  'What meal tastes better outdoors?',
  'Which kitchen gadget actually deserves its cupboard space?',
  'What is your preferred shape of pasta, and why?',
  'Which topping can completely rescue a plain dish?',
  'What would be on your ideal no-fuss picnic plate?',
  'Which food would make a surprisingly good mascot?',
  'What is your favorite way to upgrade instant noodles?',
  'Which baked good has the most inviting smell?',
  'What would you order at a café where everything is free?',
  'Which meal would you choose for a cozy, low-key gathering?',
  'What color are you most drawn to at the moment?',
  'Which sound do you find oddly soothing?',
  'What is your favorite kind of lighting in a room?',
  'Which season has the best wardrobe?',
  'What everyday item do you think is beautifully designed?',
  'Which pattern would you happily wear or decorate with?',
  'What song makes an excellent background soundtrack?',
  'Which fictional home has the most appealing atmosphere?',
  'What kind of weather makes you want to go outside?',
  'Which scent belongs in your perfect candle?',
  'What is your favorite way to make a space feel welcoming?',
  'Which tiny design detail do you always notice?',
  'What clothing item makes you feel instantly comfortable?',
  'Which animal has the most entertaining walk?',
  'What kind of art would you enjoy having on your wall?',
  'Which musical instrument has your favorite sound?',
  'What is a popular style you admire on others?',
  'Which book cover has stayed in your memory?',
  'What is your ideal background noise while getting things done?',
  'Which flower, leaf, or tree catches your eye?',
  'What harmless trend have you genuinely enjoyed?',
  'Which everyday sound would make a terrible notification tone?',
  'What item do you own in more colors than necessary?',
  'Which room would you paint a bold color if there were no rules?',
  'What visual detail makes a place feel cheerful to you?',
  'Which type of chair always wins your vote?',
  'What is a taste you appreciate now more than you used to?',
  'Which old-fashioned object still has plenty of charm?',
  'What texture do you find especially satisfying?',
  'Which harmless fashion choice would you bring back?',
  'What nearby place would you recommend for an easy outing?',
  'Which journey do you enjoy even when the destination is ordinary?',
  'What kind of view makes you pause for a moment?',
  'Which place helps you feel pleasantly anonymous?',
  'What is your favorite thing to notice while walking around a neighborhood?',
  'Where nearby can you find an underrated little pleasure?',
  'What type of shop can tempt you to browse without buying?',
  'Which route would you choose when you have time for the scenic way?',
  'What place would you revisit mainly for the atmosphere?',
  'Which setting makes conversation feel easiest to you?',
  'What would your perfect park include?',
  'Where would you take a tasting tour if travel were effortless?',
  'What is the best thing to do beside water?',
  'Which indoor place is ideal when the weather changes your plans?',
  'What destination seems perfect for a single unhurried day?',
  'Which mode of transport has the best window views?',
  'What place have you discovered through a book, show, or game?',
  'Which kind of market is most fun to wander through?',
  'What would make a road trip comfortable for you?',
  'Which landmark in your area would you show a visitor?',
  'What type of landscape feels most peaceful?',
  'Which place would be improved by adding hammocks?',
  'What is your ideal length for a casual outing?',
  'Which location would make a fun backdrop for a group photo?',
  'What place feels special because of one tiny detail?',
  'Which destination would you choose for people-watching?',
  'What is the best way to spend an hour in a new town?',
  'Which familiar place looks completely different at another time of day?',
  'What imaginary attraction would convince you to visit a theme park?',
  'Which place on your someday list feels easiest to picture?',
  'What tradition from any part of your life would you gladly repeat?',
  'Which celebration could be improved with a new snack?',
  'What simple ritual helps mark the end of a busy week?',
  'Which occasion deserves its own made-up greeting?',
  'What yearly event do you enjoy in your own way?',
  'Which tradition from a book, film, or community seems delightful?',
  'What would you name a holiday devoted to resting?',
  'Which song would you add to a celebration playlist?',
  'What low-effort tradition could begin with a group chat?',
  'Which special-day breakfast feels festive to you?',
  'What decoration would you reuse for every celebration?',
  'Which tradition involving food has caught your interest?',
  'What occasion would you invent just to brighten an ordinary month?',
  'Which game works well when different ages or personalities gather?',
  'What tiny ritual makes arrivals feel welcoming?',
  'Which custom would you happily adapt rather than follow exactly?',
  'What is a fun way to mark someone finishing a project?',
  'Which annual activity is better when kept simple?',
  'What tradition could happen entirely outdoors?',
  'Which celebration deserves a quieter alternative?',
  'What shared ritual could fit into ten minutes?',
  'Which occasion calls for everyone to wear a ridiculous hat?',
  'What would be a good theme for a completely optional gathering?',
  'Which tradition would benefit from letting each person choose a role?',
  'What small gesture can make a welcome feel genuine?',
  'Which month needs a cheerful made-up festival?',
  'What item would you place in a present-day time capsule?',
  'Which ritual would make saying goodbye after a visit more playful?',
  'What kind of celebration feels comfortable even for a small group?',
  'Which tradition would you keep exactly because it is delightfully silly?',
  'What harmless habit reveals that you are getting comfortable?',
  'Which household chore do you approach in an unusually specific way?',
  'What item do you regularly misplace in a predictable location?',
  'Which word do you enjoy saying more than the situation requires?',
  'What is your most particular preference about pillows?',
  'Which tiny inconvenience turns you into an amateur inventor?',
  'What do you always check twice, even when once would do?',
  'Which everyday decision takes you far too long?',
  'What is your signature move when a room feels too quiet?',
  'Which task brings out your competitive side for no good reason?',
  'What harmless rule have you made for your own comfort?',
  'Which object do you talk to as if it can cooperate?',
  'What is your funniest automatic response to a minor surprise?',
  'Which mundane thing do you organize with unexpected enthusiasm?',
  'What sound effect do you sometimes add to daily life?',
  'Which item must be arranged just so before you can relax?',
  'What do you do while waiting for a kettle, microwave, or download?',
  'Which small task do you postpone until it becomes an event?',
  'What is your most dependable excuse for carrying an extra bag?',
  'Which everyday object have you given an unofficial name?',
  'What is the most elaborate way you do a simple thing?',
  'Which minor victory makes you feel absurdly accomplished?',
  'What do you tend to hum without realizing it?',
  'Which cupboard, drawer, or digital folder has its own logic?',
  'What is your preferred method for choosing something at random?',
  'Which polite phrase do you use with machines?',
  'What tiny mess can you tolerate more easily than most?',
  'Which ordinary item do you keep long after it stops looking new?',
  'What is your unofficial signal that the day is winding down?',
  'Which quirk of yours would make a gentle cartoon scene?',
  'If your week came with a free bonus hour, how would you spend it?',
  'Suppose every meal needed a theme song; which dish gets the best one?',
  'If you could add one cozy feature to public transport, what would it be?',
  'Imagine opening a tiny shop for fun; what would it sell?',
  'If your phone could perform one household chore, which would you assign?',
  'Suppose you could rename one day of the week; what would you call it?',
  'If you designed a cereal box, what character would appear on it?',
  'Imagine a parade celebrating something ordinary; what leads the parade?',
  'If you had a personal flag, which harmless symbol would be on it?',
  'Suppose your favorite snack became a movie hero; what power would it have?',
  'If all meetings had to happen somewhere fun, where would you choose?',
  'Imagine receiving a medal for an everyday talent; what is engraved on it?',
  'If you could make one pleasant sound follow you around, which would it be?',
  'Suppose a room in your home or usual space had a secret button; what would it do?',
  'If you invented a board game about your current routine, how would someone win?',
  'Imagine animals could review restaurants; which animal would be the toughest critic?',
  'If you could borrow a fictional vehicle for one afternoon, which would you pick?',
  'Suppose socks could send messages; what reminder would yours give you?',
  'If your neighborhood gained one whimsical feature overnight, what should appear?',
  'Imagine a museum exhibit about ordinary mornings; what belongs in the display?',
  'If you were hired to improve waiting rooms, what would you add first?',
  'Suppose you could create a new ice-cream flavor for your current mood; what is in it?',
  'If your laugh had a color, which color would suit it?',
  'Imagine a friendly robot joining a casual gathering; what job should it have?',
  'If you could turn any errand into a game, which errand would you choose?',
  'Suppose your shoes kept a travel diary; which entry would be most interesting?',
  'If a cloud could deliver one nonessential item, what would you order?',
  'Imagine choosing a mascot for weekends; what gets the role?',
  'If you could install a snack drawer anywhere, where would it go?',
  'Suppose everyone got a harmless superpower before breakfast; which one would help most?',
  'What small thing made today a little better?',
  'Which recent photo are you glad you took?',
  'What is a sound that can lift your mood quickly?',
  'Which comfortable object are you grateful exists?',
  'What pleasant detail did you notice on your way somewhere?',
  'Which simple pleasure rarely disappoints you?',
  'What has made you feel quietly proud lately?',
  'Which part of getting ready do you enjoy most?',
  'What is a compliment you enjoy giving people?',
  'Which smell brings a welcome sense of calm?',
  'What tiny convenience feels like a modern miracle?',
  'Which moment of the day often offers a fresh start?',
  'What is something kind you recently saw someone do?',
  'Which song can improve an ordinary errand?',
  'What is your favorite sign that a meal is nearly ready?',
  'Which natural detail can reliably hold your attention?',
  'What is a recent moment you would happily replay for ten seconds?',
  'Which ordinary object feels pleasing to use?',
  'What is one thing that made you feel welcome somewhere?',
  'Which low-cost treat has a high happiness return?',
  'What has recently restored a bit of your energy?',
  'What noise makes completion feel official?',
  'What is a small kindness you like receiving?',
  'Which part of a slow day feels best?',
  'What made you pleasantly lose track of time recently?',
  'Which familiar flavor feels reassuring?',
  'What is a tiny choice that improves your mornings?',
  'Which bit of good news have you enjoyed hearing lately?',
  'What glimpse of daily activity is fun to watch?',
  'Which modest comfort would you pack for a long day?',
  'What easy activity could we enjoy together sometime, if everyone is interested?',
  'What refreshment is easiest to serve without fuss?',
  'What would make a group video call more fun and less formal?',
  'Which place would work for a relaxed catch-up with an easy exit?',
  'What simple plan sounds good for an unhurried afternoon?',
  'Which game would you suggest for twenty minutes of shared fun?',
  'What could make staying in feel like a small occasion?',
  'Which meal is easiest for people to customize to their tastes?',
  'What is a pleasant activity that requires almost no planning?',
  'How would you soundtrack an evening with no agenda?',
  'What could we make, arrange, or assemble without needing special skills?',
  'Which local outing leaves plenty of room for conversation or quiet?',
  'What is an easy way to share recommendations without creating homework?',
  'Which time of day feels best for a brief check-in?',
  'What activity lets people participate as much or as little as they like?',
  'Which dish could everyone top or season their own way?',
  'What would make a walk more interesting for the group?',
  'Which friendly challenge could be completed in under five minutes?',
  'What is a good plan for people with different energy levels?',
  'Which ordinary errand could become a companionable outing?',
  'What shared project could be finished in a single sitting?',
  'Which kind of swap would be fun: books, recipes, songs, or something else?',
  'What simple invitation feels easy to accept or decline?',
  'Which activity works whether two people join or ten?',
  'What would be a fun theme for exchanging photos in a group chat?',
  'Which café order would pair well with a quick conversation?',
  'What low-pressure plan could brighten an otherwise ordinary week?',
  'Which collaborative playlist would be entertaining to build?',
  'What is one enjoyable thing people could do from different locations?',
  'Which tiny adventure could fit between other commitments?',
  'What comfortable memory involving food still makes you smile?',
  'Which harmless joke or funny phrase has lingered in family lore?',
  'What is a pleasant outing from the past that you would recommend to anyone?',
  'Which familiar song reminds you of an easygoing moment?',
  'What shared game do you remember being especially fun?',
  'Which past celebration detail was delightfully over-the-top?',
  'What is a useful tip you picked up from someone in your family circle?',
  'Which remembered meal had an especially good atmosphere?',
  'What ordinary object brings to mind a comfortable moment from years ago?',
  'Which travel mishap is funny to you now, if one comes to mind?',
  'What is a kind gesture from the past that you still appreciate?',
  'Which old photo has a detail that always makes you laugh?',
  'What shared activity once turned out better than expected?',
  'Which familiar saying do you remember hearing in a playful way?',
  'What is a weather-related memory that feels cozy rather than dramatic?',
  'Which small tradition did you enjoy whenever it happened?',
  'What past fashion choice can you now appreciate with humor?',
  'Which room or gathering place do you remember for its welcoming feel?',
  'What simple treat once felt unusually exciting?',
  'Which story about a pet or animal visitor is safe to retell for laughs?',
  'What is a shared moment when improvising saved the day?',
  'Which old piece of technology created the funniest inconvenience?',
  'What friendly competition from the past stayed friendly?',
  'Which journey had a particularly good soundtrack?',
  'What is a moment when someone made an ordinary day more fun?',
  'Which handmade item do you remember with affection?',
  'What shared discovery felt like finding a hidden gem?',
  'Which memory involves everyone being amused by the same harmless thing?',
  'What familiar place from the past would be interesting to see again?',
  'Which comfortable memory would make a charming postcard scene?',
]
