export const RECONNECT_PARTNER_LIGHT: readonly string[] = [
  'What tiny moment with me has made you smile lately?',
  'Which snack best matches our energy as a pair?',
  'What would you name a café inspired by us?',
  'Which of our everyday exchanges could be a comedy scene?',
  'What kind of weather feels most like a date with me?',
  'Which harmless habit of mine has become oddly endearing?',
  'What would our two-person parade celebrate?',
  'Which recent conversation left you in a better mood?',
  'What song would you choose for our entrance into a room?',
  'What is one easy outing that sounds good this week?',
  'Which fictional duo would be fun for us to play for a day?',
  'What is your ideal shared treat after a long day?',
  'Which color combination captures us right now?',
  'What silly award would you give our relationship?',
  'What ordinary errand is more enjoyable when we do it together?',
  'Which photo of us deserves an amusing caption?',
  'What is a low-effort way we could make tonight feel special?',
  'Which sound instantly reminds you of time we have spent together?',
  'What would be on the menu at our imaginary food truck?',
  'What is something new and easy you would enjoy showing me?',
  'Which shared joke still catches you off guard?',
  'What would our relationship mascot be?',
  'Which room would we be funniest at redesigning with no rules?',
  'How should I greet you when we have both had an ordinary day?',
  'Which small luxury would make our next hour better?',
  'What would you put in a five-item picnic for us?',
  'Which everyday object has become part of our story?',
  'What is a playful challenge we could finish in ten minutes?',
  'Which word describes the nicest part of being around me today?',
  'What would make a perfect unplanned afternoon together?',
  'Which meal would you happily share with me on repeat?',
  'What is the funniest difference in how we approach a simple task?',
  'Which small adventure is hiding close to where we are?',
  'What nickname would our current season together have?',
  'What is your favorite way for us to waste a little time?',
  'Which shop could we browse without needing to buy anything?',
  'What harmless competition could we invent right now?',
  'Which outfit of mine has a memorable story attached to it?',
  'What would our ideal blanket-fort include?',
  'Which emoji combination could summarize our week?',
  'What simple thing do we make into more fun than it should be?',
  'Which smell belongs in a candle named after us?',
  'What would you choose for a surprise fifteen-minute break together?',
  'Which animal would make the most entertaining third wheel?',
  'What is a recent detail about your day I would enjoy hearing?',
  'Which dessert would we be most likely to disagree about sharing?',
  'What would the first episode of a show about us be called?',
  'Which of us would be better at hosting a game show, and why?',
  'What is your favorite way we make each other laugh without trying?',
  'Which tiny plan would give us something pleasant to anticipate?',
  'What could we add to our next walk to make it more playful?',
  'Which invented holiday would suit us best?',
  'What is one thing nearby that we could turn into a date idea?',
  'Which shared expression deserves a place in our private dictionary?',
  'What would be our strategy in a friendly scavenger hunt?',
  'Which comforting drink fits a quiet catch-up with me?',
  'What is a small surprise that would delight you but require no spending?',
  'Which ordinary place would be fun to visit at an unusual time?',
  'What would our matching socks look like?',
  'Which of your current interests would make a great mini-lesson for me?',
  'What has been the most amusing part of your week so far?',
  'Which three items would go in a time capsule from today?',
  'What is a friendly bet we could settle by the end of the day?',
  'Which kind of music should score our next meal together?',
  'What would you like us to photograph just for fun?',
  'Which small comfort do you always notice when it is available?',
  'What would our imaginary team uniform include?',
  'Which made-up business would we be hilariously bad at running?',
  'What topic can brighten your mood almost immediately?',
  'Which view would you like to enjoy beside me for twenty minutes?',
  'What would you choose for a no-pressure creative project together?',
  'Which phrase from me can reliably make you grin?',
  'What is one pleasant detour you would take with me?',
  'Which fruit best represents how today has gone for us?',
  'What would be the funniest theme for a meal we prepare together?',
  'Which childhood game could we adapt for two adults?',
  'What is a recent recommendation you are excited to give me?',
  'Which part of our usual routine could use a playful twist?',
  'What would our shared secret handshake definitely include?',
  'Which bench, corner, or spot nearby could become ours for an afternoon?',
  'What is a compliment about my taste that you genuinely mean?',
  'Which tiny inconvenience do we handle surprisingly well as a team?',
  'What would you pick for our one-song dance break?',
  'Which imaginary creature would be a good pet for us?',
  'What is the coziest plan you can make using things already around us?',
  'Which silly question could we debate with total seriousness?',
  'What detail makes a shared meal feel more inviting to you?',
  'Which place from a book or film would suit a casual date?',
  'What would our signature mocktail be called?',
  'Which sound effect should play whenever we solve a problem together?',
  'What is an easy way we could cheer each other on this week?',
  'Which small purchase has brought you disproportionate joy lately?',
  'What would we each contribute to an imaginary talent show act?',
  'Which casual invitation from me is hardest to resist?',
  'What is something pleasant you noticed on the way here?',
  'Which flavor would you add to a dessert made for us?',
  'What would a postcard from our current chapter show?',
  'Which harmless rule should govern our next hour together?',
  'What is your preferred background activity while we catch up?',
  'Which everyday decision would be fun to let chance make for us?',
  'What is the most satisfying task for us to finish side by side?',
  'Which hat would each of us wear to a deliberately ridiculous party?',
  'What tiny tradition could we begin before the day ends?',
  'Which local place deserves a second visit together?',
  'What would you put on a shared plate made only of favorites?',
  'Which ordinary word sounds funniest in one of our voices?',
  'What is a topic you could happily ramble about while I listen?',
  'Which season gives us the best options for spending time together?',
  'What would our team chant be before tackling chores?',
  'Which souvenir would best represent an outing we have enjoyed?',
  'What is a tiny celebration we could invent for getting through this week?',
  'Which puzzle or game would match our combined strengths?',
  'What is your ideal length for a spontaneous wander with me?',
  'Which recent trend would be funniest for us to attempt?',
  'What would make a car, bus, or train ride together more enjoyable?',
  'Which condiment reveals the most about our different tastes?',
  'What is a small talent of mine that deserves more applause?',
  'Which fictional restaurant would you book for us?',
  'What would we do with a free hour in a town neither of us knows?',
  'Which animal impression should we each try once?',
  'Which subjects seem to flow more freely when your feet are moving?',
  'Which inexpensive object could inspire a whole evening of fun?',
  'What would you include in a care package for our next lazy day?',
  'Which unusual sandwich would you dare me to taste?',
  'What makes our different comedy instincts work well in the same room?',
  'Which place would be perfect for people-watching with me?',
  'What could we make out of ingredients we already have?',
  'Which board game role do you naturally take when we play?',
  'What is a low-key activity you would like me to invite you into?',
  'Which of our minor mishaps is funny enough to retell?',
  'What would our names be in a gentle fantasy adventure?',
  'Which lighthearted topic always brings you to life?',
  'What is the best kind of weather for staying in together?',
  'Which room would you choose for a two-person karaoke session?',
  'What would be a charming name for a plant we cared for together?',
  'Which everyday success should earn us stickers?',
  'What is a fun way to say thank you without using words?',
  'Which local food should we nominate as our unofficial specialty?',
  'What would a miniature version of our ideal date include?',
  'Which cartoon style would make us look most amusing?',
  'What is a song you would enjoy hearing me attempt?',
  'Which object could serve as a trophy for our next friendly contest?',
  'What would you order if we shared breakfast at midnight?',
  'Which simple question helps you switch out of work mode?',
  'What is one harmless thing we are both delightfully particular about?',
  'Which tiny corner of your world would you enjoy introducing me to?',
  'If we read the same book, which genre could hold both our attention?',
  'Which spontaneous plan feels exciting without being exhausting?',
  'What is your favorite facial expression of mine?',
  'Which snack would make a movie neither of us chose more enjoyable?',
  'What would you call the playlist for our next ordinary day?',
  'Which mundane task deserves dramatic commentary while we do it?',
  'What is a new greeting we could try for a week?',
  'Which pleasant memory could inspire our next simple plan?',
  'What would we draw if we had to share one sheet of paper?',
  'Which easy ritual would make our goodbyes warmer?',
  'What is one detail that makes your favorite café or hangout appealing?',
  'Which household item could double as a ridiculous microphone?',
  'What would be our first stop on a tour of local hidden gems?',
  'Which kind of joke do you most enjoy hearing from me?',
  'What is a small choice we could make today purely for delight?',
  'Which meal do you think we could improve together?',
  'What would you title a photograph of us relaxing?',
  'Which old-fashioned pastime could be unexpectedly fun for us?',
  'What is the best thing to talk about over a warm drink?',
  'Which made-up point system could make errands more entertaining?',
  'What would an ideal ten-minute phone-free pause look like for us?',
  'Which place do you enjoy showing to someone you care about?',
  'What is a small sign that tells you I am in a playful mood?',
  'Which kind of market or fair would you explore with me?',
  'What would you choose as the cover image for our shared playlist?',
  'Which funny voice should narrate our next cooking attempt?',
  'What is one cheerful fact you learned recently?',
  'Which seat would you save for me in a crowded room?',
  'What would a relaxing Sunday morning sound like for us?',
  'Which two toppings describe our personalities surprisingly well?',
  'What is a quick game we could play using only questions?',
  'Which familiar street would feel fresh if we explored it slowly?',
  'What would you like to toast with me using whatever we are drinking?',
  'Which ordinary moment deserves a tiny round of applause today?',
  'What is a cozy item you would happily lend me?',
  'Which role would each of us play in a low-budget heist comedy?',
  'What would be a good excuse for us to dress up a little?',
  'Which bit of harmless nonsense should we bring back into our week?',
  'What is one easy thing we can do together without talking?',
  'Which breakfast item could you passionately defend to me?',
  'What would our ideal waiting-room entertainment be?',
  'Which place we pass often deserves a curious stop?',
  'What is a recent win of yours that I can celebrate?',
  'Which dance move could become our unofficial signal?',
  'What would make an at-home evening feel like a small occasion?',
  'Which friendly dare would be fun and comfortable for both of us?',
  'What is a playful way we could divide a shared task?',
  'Which tune gets stuck in your head in a good way?',
  'What would the weather forecast say for our mood today?',
  'Which sweet or savory smell would lure us into a shop?',
  'What is a little-known preference of yours I might enjoy remembering?',
  'Which simple outing works even when neither of us wants to plan?',
  'What would our imaginary advice column be called?',
  'Which common phrase should we replace with something funnier?',
  'What is a moment from this month that deserves a smile?',
  'Which simple recipe would you trust us to improvise?',
  'What would you place in a tiny museum of our everyday life?',
  'Which public place has the best atmosphere for an easy catch-up?',
  'What is one amusing thing your brain did today?',
  'Which sound should announce that our relaxing time has begun?',
  'What would be a fun prize for completing an annoying task?',
  'Which low-stakes mystery could we investigate together?',
  'Which message from me is nicest to find during a busy day?',
  'Which clothing color would you choose for me just for today?',
  'What would we serve at a party with only two guests?',
  'Which tiny spot would make a surprisingly good dance floor?',
  'What is a playful prediction you have for our next outing?',
  'Which fictional gadget would improve our time together?',
  'What is your quickest signal that you are ready to rejoin the day?',
  'Which of our tastes overlap in a way that delights you?',
  'What is a harmless subject on which we could switch opinions for fun?',
  'Which day-trip detail matters most to you: food, views, music, or wandering?',
  'What would a tiny flag representing us look like?',
  'Which pleasant task could we take turns choosing the soundtrack for?',
  'What is one thing you would like us to sample rather than master?',
  'Which joke format always works on you?',
  'What would make a rainy wait feel more like quality time?',
  'Which scent reminds you of feeling rested?',
  'What is a fun question you would put in a jar for us?',
  'Which unconventional venue could host a charming date?',
  'What would we name a boat that was somehow ours for an afternoon?',
  'Which small detail makes you feel welcome when you arrive somewhere?',
  'What is one easy way we could be tourists in our own area?',
  'Which ordinary item would you decorate for me?',
  'What would be the headline for a pleasantly uneventful day together?',
  'Which café order would you guess for me without asking?',
  'What is a playful use for a coin toss that does not involve winning?',
  'What would our ideal shared reading corner contain?',
  'Which simple activity helps conversation flow naturally for you?',
  'What is one thing you would enjoy doing badly together?',
  'Which souvenir could we make instead of buy?',
  'What would you include in a soundtrack for getting ready together?',
  'Which of our everyday preferences makes us a good combination?',
  'What is a fun way to mark the end of a busy stretch?',
  'Which local landmark would look best on our imaginary postcard?',
  'What would you name a sandwich built from our combined choices?',
  'Which minute of your day would you replay for me?',
  'What is a tiny way we could make each other feel like honored guests?',
  'Which sort of shop window makes you stop and look?',
  'What would our shared calendar include if joy got its own appointments?',
  'Which lighthearted story from your past have I not heard lately?',
  'What is an everyday sound you find unexpectedly pleasant?',
  'Which piece of fruit would win a personality contest between us?',
  'What would you pick for a gentle morning adventure?',
  'Which small object would make a funny good-luck charm for us?',
  'What is a pleasant way for us to spend time when energy is low?',
  'Which two-person job would we perform with unnecessary flair?',
  'What would a handwritten coupon from you to me offer?',
  'Which playful question would you ask my future self next week?',
  'What small pleasure would you gladly make room for this week?',
  'Which familiar song would sound funniest as a dramatic ballad?',
  'What would you choose for our shared desktop or phone wallpaper?',
  'Which routine stop could become a mini celebration?',
  'What is one food you would enjoy rating with me like serious critics?',
  'Which character would you invite to referee a debate between us?',
  'What would we call a day devoted to doing only easy things?',
  'Which small gesture from me feels especially sweet in public?',
  'What is a cheerful ritual for reconnecting after separate plans?',
  'Which object would be the worst possible symbol for our relationship?',
  'What would our entry be in a neighborhood baking contest?',
  'Which unexpected place could be perfect for a short conversation?',
  'Which minor choice has felt unusually satisfying lately?',
  'Which sound from nature would suit a quiet moment together?',
  'What would you draw on a napkin to make me laugh?',
  'Which casual plan could we enjoy even if it went slightly wrong?',
  'How do you like tenderness and playfulness to mix?',
  'Which menu item would you order partly so I could try it?',
  'What would make our next hello feel like a movie entrance?',
  'Which task would be improved by wearing ridiculous hats?',
  'What is one way we could add color to an ordinary day?',
  'Which neighborhood sound belongs on our local soundtrack?',
  'What would a very small victory dance between us look like?',
  'Which curiosity of yours could guide our next hour?',
  'What is a fun thing we could learn from a short video together?',
  'Which shared space would you refresh with one simple change?',
  'What would you write on a note meant to make me chuckle?',
  'Which two ingredients should never meet, even if we cooked together?',
  'What is one small way I can make your day feel lighter?',
  'Which imaginary title would you add after my name?',
  'What would be our ideal snack for watching the sky change?',
  'Which everyday item do you think reveals your personality?',
  'What is a place you would revisit mainly for its atmosphere?',
  'Which playful signal could mean “come sit with me”?',
  'What would you choose for a tiny shared reward after a hard week?',
  'Which activity makes us lose track of a spare half hour?',
  'What is one delightful detail you would add to our next meal?',
  'Which harmless surprise could turn a routine meeting into a date?',
  'What would our slogan be if we were a two-person travel club?',
  'Which small moment today felt more interesting than expected?',
  'What is a playful way for us to choose who goes first?',
  'Which comforting object deserves a place between us on the sofa?',
  'What would you like to hear me enthusiastically recommend?',
  'Which ordinary plan feels better when we put it on the calendar?',
  'What is a simple pleasure you would like to share with me soon?',
]

export const RECONNECT_PARTNER_MEANINGFUL: readonly string[] = [
  'What recent exchange between us felt especially nourishing?',
  'Which part of your current world would you like me to understand better?',
  'When does our relationship feel most like a true partnership to you?',
  'What everyday kindness between us deserves more notice?',
  'How has something you value changed since we last discussed it?',
  'What kind of listening helps you feel accompanied rather than advised?',
  'Which shared memory still influences how you see us today?',
  'What is one quality in me that you have come to value differently?',
  'Where have you noticed us becoming a stronger team?',
  'What helps you stay connected to yourself while being close to me?',
  'Which recent choice of mine made your day easier?',
  'What part of our relationship feels especially steady right now?',
  'How do you prefer us to reconnect after busy or separate days?',
  'What have you learned recently about how you like to receive care?',
  'Which of our rituals carries more meaning than it may appear to?',
  'What is something about your present season that I should keep in mind?',
  'Which recent interaction showed the kind of couple you want us to be?',
  'What kind of encouragement from me feels believable and useful?',
  'Which difference between us has broadened your perspective?',
  'What would make our shared time feel more intentional this month?',
  'How can I recognize when you want company without taking over?',
  'What is a way we make room for each other’s individuality?',
  'Which ordinary memory captures something important about our bond?',
  'What value do you see us practicing well in daily life?',
  'When do you feel most free to be unpolished around me?',
  'What is one aspect of your life you would enjoy inviting me into more?',
  'How has your idea of a supportive partner evolved?',
  'Which form of appreciation would you like us to express more often?',
  'What have we handled recently with more grace than we once might have?',
  'What helps affection feel genuine to you on an ordinary day?',
  'Which story from your past would help me understand a current interest?',
  'What does reliable care look like to you in small moments?',
  'Which choice of mine recently gave you welcome breathing room?',
  'What is one responsibility you feel we balance thoughtfully?',
  'How can we protect our connection when schedules become crowded?',
  'Which hope of yours would you like gentle encouragement around?',
  'Which idea about companionship has become clearer through knowing us?',
  'When has laughter helped us regain perspective?',
  'What kind of check-in feels natural rather than formal to you?',
  'Which part of your day do you most enjoy sharing with me afterward?',
  'What have you noticed about the ways we show fondness differently?',
  'When do you feel that I trust your judgment?',
  'What is something we do that makes difficult days less lonely?',
  'How would you describe the emotional pace that suits you lately?',
  'Which shared priority deserves a little more attention from us?',
  'What helps you feel welcomed back after time apart?',
  'What is one way we have influenced each other for the better?',
  'Where in our relationship do you feel pleasantly surprised?',
  'How can I best celebrate progress that matters to you?',
  'Which promise do we keep through actions rather than words?',
  'What recent moment reminded you that we know each other well?',
  'How do you like affection to fit around concentration or rest?',
  'What is an interest of mine that you have grown to appreciate?',
  'Which conversation between us changed your understanding of something?',
  'What makes shared silence feel connected instead of distant?',
  'When has our teamwork allowed you to relax?',
  'What would help us notice each other more during routine weeks?',
  'Which part of your identity feels well supported in our relationship?',
  'What does generosity between partners mean to you beyond giving things?',
  'How do you know when we have found a fair compromise?',
  'What is a meaningful way we honor each other’s preferences?',
  'Which of our experiences has become more valuable in hindsight?',
  'What would you like me to ask about with more curiosity?',
  'When do our different strengths complement each other best?',
  'What kind of reassurance lands well for you without feeling excessive?',
  'Which everyday gesture helps you feel chosen in the present?',
  'What has made you feel understood by me recently?',
  'How can we make room for fun without turning it into another task?',
  'What is one thing we have built together that you respect?',
  'Which boundary of yours has helped our connection stay healthy?',
  'What do you appreciate about the way we navigate separate interests?',
  'When has my curiosity helped you feel seen?',
  'What shared belief gives our relationship direction?',
  'How would you like us to acknowledge small acts of effort?',
  'What is one way your needs have become clearer to you lately?',
  'Which routine gives you a sense of continuity between us?',
  'What does being on the same side look like during a disagreement?',
  'What conditions help your unfinished thoughts come out naturally with me?',
  'What is something about us that feels both ordinary and precious?',
  'How has a change in your life affected what connection means to you?',
  'Which part of our shared history makes you feel warmly known?',
  'What support do you value when you are learning something new?',
  'Where could we trade assumptions for one good question?',
  'What is a caring habit you learned from someone and brought into us?',
  'When have we given each other room without losing closeness?',
  'What kind of planning makes you feel considered rather than managed?',
  'Which shared activity leaves your energy steadier than before?',
  'What is one quality you hope we keep bringing out in each other?',
  'How do you like us to respond when one person has less energy?',
  'What recent experience revealed a new side of you to yourself?',
  'Which part of our communication has become more comfortable over time?',
  'What does mutual respect sound like in our everyday conversations?',
  'Which contribution of yours would you like me to recognize more clearly?',
  'What is a shared habit you would be sad to overlook?',
  'How can I show interest in your goals without adding pressure?',
  'Which small decision reflects who we want to be together?',
  'What has helped you trust that your “no” will be respected by me?',
  'Which recent gesture between us carried unexpected tenderness?',
  'What is something we understand about each other that took time?',
  'How would you like us to make space for changing opinions?',
  'Which moment showed you that I was paying close attention?',
  'What does a balanced give-and-take feel like to you these days?',
  'When has one of our differences become a source of affection?',
  'What is a current challenge where companionship matters more than solutions?',
  'How can we signal that we need a softer conversation?',
  'Which of my efforts do you notice even when you do not mention it?',
  'What part of your routine helps you return to us with more presence?',
  'When have we turned an awkward moment into greater understanding?',
  'What is one shared experience that still makes you feel capable together?',
  'How do you prefer me to check whether advice is welcome?',
  'Which aspect of our connection feels uniquely ours?',
  'What does emotional generosity look like when time is limited?',
  'When do you feel most comfortable asking me for practical help?',
  'What is something you admire about how we recover from minor tension?',
  'How might we bring more gratitude into transitions between activities?',
  'Which of your ambitions feels most alive at the moment?',
  'What helps you believe I am interested in who you are becoming?',
  'When have we made a decision that respected both of us?',
  'What is one way our relationship makes room for playfulness?',
  'How do you experience care when I remember a small detail?',
  'Which part of our connection would you describe as quietly resilient?',
  'How can reliability survive a necessary change of plans?',
  'When have you enjoyed seeing me in my element?',
  'What is a recent insight about yourself you are comfortable sharing?',
  'How can we keep familiar routines from becoming invisible?',
  'Which shared value becomes clearest in how we treat other people?',
  'What type of invitation helps you join in without feeling obligated?',
  'When does a message from me feel especially thoughtful?',
  'What is one thing our past selves might admire about us now?',
  'How do we help each other feel at ease in unfamiliar situations?',
  'Which part of your inner world has been especially active lately?',
  'What does it mean to you when we follow through on a small agreement?',
  'Which slow process has felt easier because I did not rush you?',
  'What is a quality in yourself that our relationship has helped you notice?',
  'How would you like us to share decisions that mostly affect one person?',
  'Which tradition from your background would you enjoy exploring together?',
  'What kind of recognition feels right when you have worked hard?',
  'When have we chosen connection without canceling needed alone time?',
  'What is one thing you want our shared spaces to communicate?',
  'How has your definition of quality time shifted recently?',
  'Which story about us do you enjoy telling because it feels true to our character?',
  'What does thoughtful curiosity look like when you are still finding words?',
  'When do you feel I make room for your full attention elsewhere?',
  'What is a way we have helped each other become more confident?',
  'How can we make appreciation specific enough to feel real?',
  'Which common goal makes our individual efforts feel connected?',
  'What form of companionship helps when you are mentally tired?',
  'When have I respected a preference that was different from mine?',
  'What is something about your week that deserves more than a quick summary?',
  'How would you like us to welcome new interests as we change?',
  'Which moment made you grateful for our ability to improvise?',
  'What does a sincere apology communicate to you beyond the words?',
  'When do you feel invited to contribute rather than expected to?',
  'What is one way we make ordinary places feel familiar?',
  'How can we protect laughter when life becomes demanding?',
  'Which recent boundary has helped you use your energy more wisely?',
  'What kind of affection helps you feel connected before a busy day?',
  'When have we approached a problem as partners instead of opponents?',
  'What is something in your life you are reevaluating with curiosity?',
  'How do you like to be welcomed into a conversation about shared plans?',
  'Which practical act between us carries emotional meaning for you?',
  'What does feeling included look like when we are with other people?',
  'When have you felt safe to revise an answer you gave me?',
  'What is one of our strengths that may be easy to take for granted?',
  'How can we learn about each other without expecting immediate openness?',
  'Which part of our time together helps you feel grounded?',
  'What type of feedback helps you feel respected and capable?',
  'When have you noticed me adapting in a way you appreciated?',
  'What is a shared pleasure that reflects our values more than our habits?',
  'How do you distinguish helpful support from unwanted rescuing?',
  'Which new aspect of you would you like me to meet with fresh eyes?',
  'What does it mean to share a life while keeping distinct perspectives?',
  'When has a thoughtful pause improved a conversation between us?',
  'What is something you value about how we welcome each other’s friends?',
  'How might we make our next decision feel collaborative from the start?',
  'Which experience helped us discover a strength we did not know we had?',
  'What kind of comfort feels respectful when words are not helpful?',
  'When do you feel our affection has the most ease?',
  'What is one of your priorities that deserves renewed attention from me?',
  'How can I tell when you want to be witnessed rather than cheered up?',
  'Which part of our rhythm together feels nourishing?',
  'What does fairness mean when our available energy is unequal?',
  'When have you felt that your perspective genuinely influenced me?',
  'What is a way our relationship supports your connection with others?',
  'How would you describe the kind of home base we create emotionally?',
  'Which small courtesy between us should never become automatic?',
  'What kind of shared experience helps you feel refreshed afterward?',
  'When have we made space for disappointment without spoiling the whole day?',
  'What is something about me that makes more sense to you now?',
  'How can we be more present for moments that are going well?',
  'Which commitment do you think we renew through everyday choices?',
  'What does being taken seriously feel like in a loving conversation?',
  'When do you appreciate us choosing simplicity over an elaborate plan?',
  'What is one way we could make mutual support more sustainable?',
  'How has seeing me change affected your understanding of me?',
  'Which shared reference or phrase makes you feel connected quickly?',
  'What type of patience would help your current goals?',
  'When have we protected each other’s dignity during a difficult moment?',
  'Which quiet effort in your routine deserves more recognition from me?',
  'How can we show care for each other’s time?',
  'Which recent moment made our shared history feel alive?',
  'What does a warm welcome look like when one of us is distracted?',
  'When have you felt encouraged by my confidence in you?',
  'What is one area where we have become more accepting of difference?',
  'How would you like me to respond when your enthusiasm surprises me?',
  'Which of our ordinary exchanges feels like a private ritual?',
  'What kind of shared responsibility makes you feel connected rather than burdened?',
  'When do you feel I recognize the effort behind your choices?',
  'How has being cared for by me influenced your ability to accept kindness?',
  'How can we maintain curiosity when we think we know the answer?',
  'Which part of your current routine best reflects who you are now?',
  'What does reciprocal care mean when it takes different forms?',
  'When have we made each other feel welcome in separate communities?',
  'Which interpersonal quality do you think I contribute to a group?',
  'How might we honor a memory without trying to recreate it?',
  'Which shared accomplishment still gives you a quiet sense of satisfaction?',
  'What kind of attention helps you feel calm during a conversation?',
  'When have we allowed a good-enough plan to be enough?',
  'What is one topic you would enjoy revisiting because your view has evolved?',
  'How do we communicate care through the way we handle logistics?',
  'Which difference in our backgrounds has invited useful learning?',
  'What does being emotionally available mean on a low-energy day?',
  'When have you felt that I enjoyed you, not just loved you?',
  'What is a source of meaning you would like us to share more often?',
  'How can we notice when one person is carrying too many small decisions?',
  'Which recent exchange left you feeling respected?',
  'What type of shared pause helps you return to yourself?',
  'When have we handled uncertainty with good teamwork?',
  'What is one part of your personality that has become more visible lately?',
  'Which agreements would make genuine rest easier for both of us?',
  'Which expression of care feels special because it is specific to you?',
  'What does mutual encouragement look like when our goals differ?',
  'Which choice of mine reflected our shared values beyond the relationship?',
  'What is a lesson from our early connection that still serves us?',
  'How can we be honest about capacity without making it personal?',
  'Which ordinary choice helps our relationship feel equitable?',
  'What kind of companionship lets you think clearly?',
  'When have you enjoyed learning something alongside me?',
  'What is an assumption about partnership that you have happily outgrown?',
  'How would you like us to mark transitions into new chapters?',
  'Which memory shows us adapting well to the unexpected?',
  'What does it feel like when I honor your expertise?',
  'When have we found connection through a difference of opinion?',
  'What is one way I help you feel more at ease socially?',
  'How can we keep shared goals flexible enough for both of us?',
  'Which recent act of care felt especially well timed?',
  'What kind of conversation helps you feel closer without feeling exposed?',
  'When have you seen us choose kindness over being impressive?',
  'What is a value you hope people can sense in the way we relate?',
  'How do you want us to treat plans that matter more to one partner?',
  'Which experience reminds you that we can enjoy unfamiliar things together?',
  'What does respect for privacy look like within closeness?',
  'When have I helped you feel less rushed?',
  'What is one way our separate perspectives improve a shared result?',
  'How can we give each other the benefit of context, not just doubt?',
  'Which of our habits helps you feel remembered?',
  'What kind of gratitude feels natural for practical contributions?',
  'When have we made a mundane obligation feel companionable?',
  'What is something you would like us to understand before planning ahead?',
  'How would you describe the role of friendship in our partnership?',
  'Which way of showing up for me also feels good to you?',
  'What does shared meaning look like without needing identical beliefs?',
  'When have you felt that I was genuinely delighted by your success?',
  'What is one personal interest you want protected from becoming an obligation?',
  'How can we make room for each other to have changing levels of sociability?',
  'Which moment of cooperation made you feel especially close?',
  'What kind of question invites you to reflect without putting you on the spot?',
  'When have we handled a difference in pace with respect?',
  'What is one thing we each contribute to a sense of ease?',
  'How do you like me to show solidarity when you are frustrated elsewhere?',
  'Which aspect of our partnership feels more mature than it used to?',
  'What does it mean to you when I make room for your traditions?',
  'When have you felt cared for through something I did not say?',
  'What is a shared intention that could guide us without becoming a rule?',
  'How can we recognize each other’s invisible effort more consistently?',
  'Which part of being known by me feels most comforting?',
  'What kind of togetherness still allows you to recharge?',
  'When have we treated a misunderstanding as something to explore?',
  'What is one way we could celebrate each other without an occasion?',
  'How would you like us to approach invitations that only one of us enjoys?',
  'Which common experience has deepened your empathy for me?',
  'What does attentive presence look like when we have only a few minutes?',
  'When have you appreciated my willingness to learn your way?',
  'What is something about your current priorities that feels newly important?',
  'How can we help each other return to connection after intense work?',
  'Which of our shared choices reflects care for a wider community?',
  'What kind of honesty strengthens closeness without demanding every detail?',
  'When have we made space for both gratitude and a wish for change?',
  'What is one relationship skill you think we practice with intention?',
  'How would you like us to respond when a cherished plan no longer fits?',
  'Which moment showed you that affection can be practical?',
  'What does it mean for us to be curious about each other in the present?',
  'When have you felt supported in taking a path I would not choose myself?',
  'What is a quality of our connection that you want to nourish deliberately?',
  'How can we make our shared rituals welcoming to our changing selves?',
  'Which form of everyday respect matters more to you than grand gestures?',
  'What kind of support helps you remain the author of your own decisions?',
  'When have we made a small moment carry lasting warmth?',
  'What is one way our bond helps you approach the world with more openness?',
  'How would you like us to stay interested in each other this season?',
]

export const RECONNECT_PARTNER_DEEP: readonly string[] = [
  'What part of who you are becoming would you like our relationship to welcome?',
  'Where do you need more choice in the way we spend time together?',
  'How can we disagree without either of us having to shrink?',
  'What pattern between us would benefit from slower attention?',
  'Which need of yours is easiest to overlook when life is running smoothly?',
  'What does repair require from each of us after a tense exchange?',
  'Where might our closeness make more room for healthy privacy?',
  'How has your understanding of commitment changed in this season?',
  'What future possibility feels worth exploring without deciding anything today?',
  'Which version of yourself feels most present in our relationship lately?',
  'What helps you distinguish a request from an expectation between us?',
  'Where could our shared routines adapt better to who we are now?',
  'How would you like us to handle a boundary that changes over time?',
  'What is one conversation habit you want us to interrupt with care?',
  'Which form of independence strengthens your ability to connect with me?',
  'What does accountability feel like when it is offered without self-punishment?',
  'Where do you sense an unspoken assumption that we could gently examine?',
  'How can we make room for ambivalence without treating it as rejection?',
  'What part of our shared direction deserves a fresh conversation?',
  'Which kind of change brings out your need for extra steadiness?',
  'What helps you feel safe enough to say “not yet” to me?',
  'Where do our different coping styles create avoidable confusion?',
  'When good intentions still hurt, what response helps restore care?',
  'What personal value are you trying to live more fully right now?',
  'Which tension between comfort and growth feels relevant to us?',
  'What would a respectful pause look like during a difficult discussion?',
  'Where might we be solving a problem that first needs understanding?',
  'How has your sense of belonging within our relationship evolved?',
  'What kind of apology helps you trust that repair is underway?',
  'Which of your limits deserves clearer protection in our plans?',
  'What does emotional responsibility mean without taking responsibility for each other’s feelings?',
  'Where could we replace a familiar story about each other with curiosity?',
  'How would you like us to navigate unequal enthusiasm about a shared idea?',
  'What part of our future do you want to approach with more spaciousness?',
  'Which expectation of partnership are you currently questioning?',
  'What helps you tell me a need before it becomes resentment?',
  'Where do you want greater reciprocity, even if it looks different from equality?',
  'How can we recognize when a conversation has moved beyond our capacity?',
  'What is one way your identity has expanded since we connected?',
  'Which recurring friction might be pointing to a practical redesign?',
  'What does consent look like in the small, nonphysical parts of our life?',
  'Where might we need to renegotiate how decisions are made?',
  'How do you want me to respond when you change your mind?',
  'What part of being close to someone still requires courage from you?',
  'Which shared narrative about us feels ready for an update?',
  'What would help a hard truth feel discussable without making it urgent?',
  'Where do you want to be met with compassion rather than improvement?',
  'How can we care for the relationship without making it our only source of fulfillment?',
  'What direction in your own life needs more room to unfold?',
  'Which kind of conflict leaves you needing reconnection most afterward?',
  'What does a fair division of emotional labor mean to you?',
  'Where do you notice yourself interpreting before asking?',
  'How might we protect tenderness while setting a firm limit?',
  'What has become easier for you to name as our trust has developed?',
  'Which aspect of our connection needs permission to be imperfect?',
  'What would help us approach recurring disappointment without assigning a villain?',
  'Where might you need support that does not involve my participation?',
  'Which personal need have you become better at recognizing early?',
  'What is one future question you want us to hold rather than answer?',
  'Which subtle signal tells you that a conversation no longer feels collaborative?',
  'What does being accepted mean when one of us is still changing?',
  'Where could we be more explicit instead of relying on goodwill?',
  'How would you like us to handle different needs for contact and space?',
  'What part of our relationship feels ready for a more honest design?',
  'Which inherited idea about love no longer serves the way you want to relate?',
  'What helps you remain generous when you also need to protect your energy?',
  'Where could we distinguish disappointment from wrongdoing more clearly?',
  'How can we repair a moment when one of us felt dismissed?',
  'What aspect of your inner life do you want to keep cultivating independently?',
  'Which decision would benefit from hearing what each of us is trying to protect?',
  'What does trust mean when certainty is not available?',
  'Which structure between us could loosen without losing reliability?',
  'How do you prefer to revisit something after emotions have settled?',
  'What part of your growth might require me to learn a new way of supporting you?',
  'Which unmet preference could be discussed without turning it into a demand?',
  'What would help us stay connected while reaching different conclusions?',
  'Where might “helping” accidentally reduce the other person’s agency?',
  'How has your understanding of closeness shifted with experience?',
  'What is one change you want us to observe before trying to manage it?',
  'Which type of boundary feels loving even when it is inconvenient?',
  'What does a genuine second attempt sound like after poor communication?',
  'Where can we make more room for each person’s cultural or personal context?',
  'How would you like us to speak about our relationship with other people?',
  'What part of your present reality asks for a different kind of partnership?',
  'Which fear about change could be met with information rather than reassurance?',
  'What helps you feel respected when I cannot meet a request?',
  'Where do we risk confusing familiarity with full understanding?',
  'How can we be accountable for impact without debating someone’s experience?',
  'What dimension of intimacy would you like to define in your own words?',
  'Which recurring choice says the most about our priorities?',
  'What would a more sustainable version of mutual care look like?',
  'Where do you need permission to disappoint me and still feel loved?',
  'How has your sense of responsibility within partnership matured?',
  'What part of our dynamic improves when we name power or influence honestly?',
  'Which hope for us feels grounding rather than pressuring?',
  'What helps you stay open when feedback touches something important?',
  'Where could we choose a clearer agreement over a hopeful assumption?',
  'Which signs tell us that a once-useful solution needs retiring?',
  'What part of yourself do you want to hear more clearly in our decisions?',
  'Which form of repair feels meaningful even when the original outcome cannot change?',
  'What does commitment to growth mean without promising a specific result?',
  'Where might our roles have become too fixed for our current needs?',
  'How can we question a pattern without questioning the whole relationship?',
  'What is one need you want to express more directly and kindly?',
  'Which aspect of autonomy helps you bring more of yourself to us?',
  'What would make it easier to acknowledge defensiveness when it appears?',
  'Where do you want more room to define success on your own terms?',
  'How should we handle a conversation when one person needs longer to process?',
  'What part of our bond has changed in a way you want to honor?',
  'Which difference between us requires ongoing negotiation rather than resolution?',
  'What helps you believe that a boundary will not threaten connection?',
  'Where could we make our gratitude less dependent on unspoken sacrifice?',
  'How do you want us to approach closeness when stress changes your capacity?',
  'What personal principle do you want our partnership to make easier to live?',
  'Which small rupture tends to linger unless we address it?',
  'What would it mean to listen without preparing a defense?',
  'Where might we be expecting one conversation to accomplish too much?',
  'How has your relationship with uncertainty affected the way you plan with me?',
  'What part of care do you want to receive without having to earn it?',
  'Which choice could better reflect both our needs and our constraints?',
  'What does it look like to respect each other’s separate pace of change?',
  'Where do you want us to use more precise language instead of broad labels?',
  'How can we respond to hurt without turning intent into a shield?',
  'What aspect of your self-understanding is currently in motion?',
  'Which shared expectation would you like to turn into a clear invitation?',
  'What helps you reconnect after you have felt emotionally crowded?',
  'Where could we practice asking before offering comfort or touch?',
  'How do you want us to divide responsibility for initiating important talks?',
  'What part of our connection do you want to protect from constant optimization?',
  'Which future plan needs more curiosity about its day-to-day reality?',
  'What would help you trust that disagreement will not erase affection?',
  'Where might a request for reassurance be asking for something more specific?',
  'How has your view of loyalty become more nuanced over time?',
  'What need for recognition would you like to name without keeping score?',
  'Which area of shared life could benefit from a trial period rather than a permanent decision?',
  'What does it mean to be emotionally honest while keeping some thoughts private?',
  'Where do you want to feel more consulted before plans take shape?',
  'How can we tell when compromise has started to feel like self-abandonment?',
  'What part of our connection deserves rest rather than more effort?',
  'Which experience changed what you require to feel respected?',
  'What would make a boundary conversation feel like coordination, not rejection?',
  'Where could we better acknowledge that both perspectives may be incomplete?',
  'How do you want us to handle outside pressures that shape our choices?',
  'What emerging part of your identity needs room without needing explanation?',
  'Which repair attempt from me is easiest for you to receive?',
  'What helps you notice when you are agreeing mainly to preserve harmony?',
  'Where might our ideas of fairness be using different measures?',
  'How can we stay kind when clarity arrives at different times for each of us?',
  'Where could we stop trying to look like an ideal couple?',
  'Which shared concern could become lighter if we named its limits?',
  'What does a respectful change of plan require from the person proposing it?',
  'Where do you need more confidence that your preferences matter?',
  'How has receiving love challenged an older belief about yourself?',
  'What aspect of our future feels better discussed as a range of possibilities?',
  'Which difficult emotion do you want us to make room for without trying to fix?',
  'What would help us address a mismatch before either person feels deprived?',
  'Where could curiosity soften a judgment you have about my response?',
  'How do you want to preserve spontaneity while honoring predictability needs?',
  'What part of your life direction feels most important to choose freely?',
  'Which conversation would benefit from deciding its purpose first?',
  'What does respectful influence look like between equal partners?',
  'Where might we need to separate a practical problem from its emotional meaning?',
  'How can we make room for grief over a change without treating the change as wrong?',
  'What aspect of being known sometimes feels vulnerable even in a safe bond?',
  'Which agreement between us may need an expiration date or review point?',
  'What helps you recognize when I am reaching for connection imperfectly?',
  'Where could we practice more directness without losing warmth?',
  'How has your need for solitude changed, and what supports it now?',
  'What part of our relationship asks us to be beginners again?',
  'Which definition of support do you want us to reconsider together?',
  'What would make it easier to name an impact before building a case?',
  'Where do you feel pressure to be consistent when you are actually evolving?',
  'How can we keep repair focused on care rather than winning agreement?',
  'What personal dream do you want our choices to leave room for?',
  'Which difference in communication style most needs translation between us?',
  'What does mutual consent mean when a shared tradition no longer suits one person?',
  'Where might reassurance be less useful than a concrete change?',
  'How do you want us to approach needs that neither person can fully meet?',
  'What part of your sense of self feels strengthened by healthy separation?',
  'Which future decision should include a conversation about values before logistics?',
  'What helps you feel that conflict is contained rather than endless?',
  'Where do you notice a gap between what we intend and what we practice?',
  'How can we protect each other from becoming the default answer to every need?',
  'What aspect of our relationship would benefit from a little more experimentation?',
  'Which expectation feels loving when chosen but heavy when assumed?',
  'What would help you speak up while a concern is still small?',
  'Where could we let two valid needs coexist without rushing to rank them?',
  'How has your idea of emotional safety become more specific?',
  'Which outside script about couples would you gladly leave unused?',
  'Which recurring misunderstanding might come from different meanings of the same word?',
  'Which words let a “no” remain both clear and kind?',
  'Where do you want more room to make mistakes without being defined by them?',
  'How can we acknowledge unequal impact even when responsibility is shared?',
  'What current transition is reshaping how you want to connect?',
  'Which aspect of closeness works best when it is explicitly invited?',
  'What would a balanced response look like when one person feels more urgency?',
  'Where might our desire to be helpful prevent genuine listening?',
  'How do you want us to recognize repair that is happening gradually?',
  'What part of your autonomy would you like me to understand as an act of care?',
  'Which decision-making habit could give quieter preferences more weight?',
  'What does it mean to stay connected while allowing each other to be complex?',
  'Where could we offer context before asking the other person to interpret our behavior?',
  'How can we make difficult feedback feel bounded and actionable?',
  'What part of your relationship with time influences how you plan with me?',
  'Which form of dependence feels healthy to you, and what keeps it so?',
  'What would help us notice consent as an ongoing conversation?',
  'Which current expectation needs more exceptions built into it?',
  'How has your way of protecting your peace changed recently?',
  'What aspect of our connection do you want to approach with less certainty?',
  'Which unresolved difference can we carry respectfully rather than repeatedly debate?',
  'What does repair look like when both people are partly right?',
  'Where might we need to clarify what is private, shared, or ours to disclose?',
  'How can we make a request without predicting the other person’s answer?',
  'What part of your future self do you hope our relationship does not constrain?',
  'Which habit of interpretation would you like to replace with checking in?',
  'What helps you experience accountability as care rather than condemnation?',
  'Where do you want greater freedom to approach a shared goal differently?',
  'How should we revisit an agreement made under different circumstances?',
  'What aspect of our closeness requires the most intentional pacing?',
  'Which need becomes harder to voice when everything else seems fine?',
  'What would help us respond to disconnection before it becomes a crisis?',
  'Where can we reduce pressure by naming what is genuinely optional?',
  'How has your definition of partnership been shaped by what you do not want to repeat?',
  'Which area of joint life would benefit from shaping the rules side by side?',
  'Which emotion do you find easiest to misread in me?',
  'What does it look like to validate a feeling without endorsing every conclusion?',
  'Where might an old protective strategy be creating new distance?',
  'How can we talk about unequal effort without turning care into a ledger?',
  'What aspect of change do you want to meet with patience rather than a plan?',
  'Which kind of invitation helps you reveal a changing opinion safely?',
  'What would make our approach to conflict feel more aligned with our values?',
  'Where do you want us to separate preference, need, and boundary more clearly?',
  'How has your capacity for connection shifted under current demands?',
  'What part of our shared identity makes room for our individual identities?',
  'Which repair matters even if the other person did not mean harm?',
  'What helps you trust that saying less can still be honest?',
  'Where could we allow uncertainty to inform us without letting it lead us?',
  'How do you want us to navigate a choice with no perfect compromise?',
  'What aspect of yourself are you learning not to negotiate away?',
  'Which shared goal might need two different paths instead of one method?',
  'What does respectful persistence look like after an unanswered request?',
  'Where might we be using efficiency at the expense of participation?',
  'How can we stay responsive without becoming responsible for regulating each other?',
  'What part of our connection benefits when we lower the stakes?',
  'Which assumption about your needs would you like me to retire?',
  'What would it mean to repair trust through consistency rather than promises?',
  'Where do you want more recognition that your energy has limits?',
  'How has your understanding of emotional availability become more realistic?',
  'What aspect of our future needs room for more than one good outcome?',
  'Which form of closeness feels supportive only when you can opt out freely?',
  'What helps you hear a complaint as information rather than a verdict?',
  'Where could we build in recovery time after demanding shared experiences?',
  'How do you want us to handle moments when privacy and transparency pull differently?',
  'What part of your growth do you want witnessed without being evaluated?',
  'Which conflict skill would most improve the quality of our repairs?',
  'What does accepting influence mean without giving up your own view?',
  'Where might we need to acknowledge a loss of ease before creating something new?',
  'How can we clarify capacity before making commitments to each other?',
  'What aspect of our partnership feels strongest when neither person performs a role?',
  'Which request would feel safer if either answer were genuinely acceptable?',
  'What would help us recognize when a familiar debate is really about connection?',
  'Where do you want to practice receiving care without immediately returning it?',
  'Which former nonnegotiable now feels open to discussion?',
  'What part of our relationship would benefit from naming an uncomfortable tradeoff?',
  'Which signal could tell us that humor is helping rather than deflecting?',
  'What does fairness require when one person has more information or influence?',
  'Where can we create a little distance from a problem without avoiding it?',
  'If discomfort reveals a new limit, what should happen next between us?',
  'What aspect of your belonging should never depend on agreement?',
  'Which future conversation deserves preparation rather than spontaneity?',
  'What would make it easier to admit that a previous solution no longer fits?',
  'Where might our care become more effective if it were less automatic?',
  'How can we make space for disappointment without asking anyone to hide it?',
  'What part of your inner authority do you want our partnership to reinforce?',
  'Which difference between intention and capacity do you want us to respect?',
  'What does collaborative repair look like when memories of the moment differ?',
  'Where do you want more reassurance through actions and less through explanation?',
  'How has your understanding of compromise changed as you know yourself better?',
  'What aspect of our bond could support more honest experimentation?',
  'Which expectation would benefit from being replaced by an explicit agreement?',
  'What would help us discuss influence without framing either person as controlling?',
  'Where can we be more compassionate about the speed of unlearning old habits?',
  'How do you want us to handle a need that changes from day to day?',
  'Which form of acknowledgment helps you move forward after a misunderstanding?',
  'What does it mean to choose each other freely in everyday life?',
  'Where might we need separate support for something that affects us both?',
  'How can we keep a hard conversation from becoming a test of love?',
  'What aspect of your evolving worldview do you want me to stay curious about?',
  'Which shared decision deserves more attention to who bears its consequences?',
  'What would a gentle course correction look like for us right now?',
  'Where do you want our relationship to hold more room for contradiction?',
  'How has your definition of a meaningful future become more personal?',
  'What part of our connection would benefit from a clearer right to pause?',
  'Which need for stability can coexist with a desire for change?',
  'What does it look like to protect dignity while naming a problem plainly?',
  'Where could we trust a gradual answer instead of demanding immediate clarity?',
  'How do you want us to stay allied when a decision favors one person’s preference?',
  'What aspect of partnership are you ready to reimagine together?',
  'Which question about our direction feels useful without putting us under pressure?',
  'What would help our next chapter reflect both continuity and growth?',
]
