export const RECONNECT_GROUP_LIGHT: readonly string[] = [
  "What everyday sound would make a surprisingly good group anthem?",
  "Choose a snack that deserves a louder fan club.",
  "Which tiny convenience feels like a genuine luxury to you?",
  "What harmless rule would improve a shared picnic?",
  "Name a smell that instantly makes a place feel welcoming.",
  "Which ordinary object has an unexpectedly satisfying design?",
  "What kind of weather brings out your most playful side?",
  "Invent a cheerful name for this group in three words or fewer.",
  "Which simple activity helps strangers become teammates quickly?",
  "What color would you add to a room meant for good conversation?",
  "Describe your ideal ten-minute break between busy moments.",
  "Which animal would be the funniest community mascot?",
  "What food is easiest to enjoy while chatting with new people?",
  "Name a skill that looks fun even when done badly.",
  "Which season would be the most entertaining guest at this gathering?",
  "What would make waiting in a long line more enjoyable for everyone?",
  "Choose a sound effect for entering this gathering.",
  "What low-stakes competition could this group settle today?",
  "Which familiar game becomes funnier with one rule changed?",
  "What is your favorite reason to step outside for five minutes?",
  "Pick a theme for an imaginary community parade.",
  "What item would improve almost any shared table?",
  "Which word is simply enjoyable to say aloud?",
  "What is a small purchase that reliably brightens your week?",
  "Design a trophy for someone who keeps a group smiling.",
  "Which breakfast food could also work as a party snack?",
  "What background music suits a relaxed room full of conversation?",
  "Name a chore that is better with company.",
  "Which local spot is good for watching the world go by?",
  "What would your ideal community noticeboard always include?",
  "Choose a dance move that everyone can safely attempt seated.",
  "What simple greeting feels warm without being too familiar?",
  "Which fruit has the most dramatic appearance?",
  "How do you prefer to notice that your day has become less rushed?",
  "Name something ordinary that deserves a miniature museum.",
  "What recurring bit of harmless silliness should this group schedule?",
  "What nonverbal gesture can make a group feel more friendly?",
  "Choose a shared playlist title for an easygoing afternoon.",
  "Which household item would make the worst musical instrument?",
  "What is your preferred level of crispiness for a shared snack?",
  "Describe a hat that would make any meeting more entertaining.",
  "Which type of shop is enjoyable even when you buy nothing?",
  "What is a playful use for a completely empty room?",
  "Name a small sign that a gathering is going well.",
  "Which drink has the most inviting color?",
  "What should be included in a starter kit for a relaxed weekend?",
  "Choose an object that could represent curiosity in a group logo.",
  "What is the nicest thing about sharing food family-style?",
  "Which gentle challenge would help everyone learn names?",
  "What kind of seat makes conversation easier?",
  "Name a tune almost anyone can hum together.",
  "What ordinary group task would become funnier if everyone wore a costume?",
  "What is a funny but useful title for the person holding the map?",
  "Choose a texture that belongs in a cozy common space.",
  "What is the best shape for a table where everyone can join in?",
  "Which fictional mode of transport would suit a group outing?",
  "Name a polite excuse for taking the last biscuit.",
  "What makes a group photo feel natural instead of staged?",
  "Which familiar scent could be bottled as ‘Welcome Back’?",
  "What is an easy question that gets people comparing tastes?",
  "Pick a symbol for a club devoted to trying new things.",
  "Which vegetable has the strongest comic potential?",
  "What shared activity works well without anyone needing to be skilled?",
  "Name a small object you enjoy lending to someone.",
  "Which sound belongs at the end of a successful group task?",
  "What would make a neighborhood bench more inviting?",
  "Choose a menu category that deserves its own celebration.",
  "What could everyone draw in thirty seconds for a quick laugh?",
  "Which form of transport encourages the best people-watching?",
  "Name a harmless topic people become amusingly specific about.",
  "What is your preferred pace for exploring somewhere unfamiliar?",
  "Choose a prop for an imaginary group portrait.",
  "Which room in a public building is often underrated?",
  "What is a useful talent for organizing a casual outing?",
  "Name a sound that tells you the fun is about to begin.",
  "Which simple treat is easy to divide fairly?",
  "What kind of group challenge needs no winner?",
  "Choose a funny name for a shared jar of suggestions.",
  "What is the most cheerful type of stationery?",
  "Which familiar object looks like it has a personality?",
  "Name a reason to celebrate that does not need a special occasion.",
  "What is a comfortable silence best paired with?",
  "Choose one ingredient for a fictional friendship soup.",
  "Which outdoor sound improves a conversation break?",
  "What is an easy way to make a newcomer feel included in a game?",
  "Name a place where a five-minute chat can become memorable.",
  "Which object would be amusingly overqualified as a paperweight?",
  "What is the best kind of surprise to find in a lunch bag?",
  "Choose a hand signal for ‘great idea.’",
  "Which minor inconvenience could become a fun team puzzle?",
  "What kind of lamp gives a room an instantly friendly mood?",
  "Name a familiar tune that would make a funny doorbell.",
  "What is a playful category for an awards ceremony with no losers?",
  "Choose a pattern for matching group socks.",
  "Which common phrase sounds funnier when whispered dramatically?",
  "What could make a rainy gathering feel like a treat?",
  "Name something people can build together using only paper.",
  "Which dessert is most likely to start a cheerful debate?",
  "What is your ideal length for a spontaneous walk with others?",
  "Choose a name for a pretend café run by this group.",
  "Which object could become a mascot with only two paper eyes?",
  "What is a friendly way to invite quieter voices into a game?",
  "Name a small victory worth marking with applause.",
  "Which type of cloud looks most ready for an adventure?",
  "What would you put in a communal box labeled ‘Just in Case’?",
  "Choose a theme song for tidying up together.",
  "Which everyday container would make the silliest hat?",
  "What is the best kind of place for an unhurried catch-up?",
  "Name a food whose name is almost as enjoyable as its taste.",
  "Which friendly ritual could start a group activity?",
  "What is an entertaining way to choose who goes first?",
  "Choose a tiny decoration that makes a shared space feel cared for.",
  "Which board-game piece would you want as a desk companion?",
  "What is a good group name for people who enjoy pleasant detours?",
  "Name something that becomes more fun when passed around.",
  "Which ordinary outing feels special when planned at the last minute?",
  "What should a button labeled ‘Instant Fun’ produce?",
  "Choose a sound for a group completing something together.",
  "Which snack leaves the least distracting evidence behind?",
  "What is an easy way to add playfulness to introductions?",
  "Name an activity that makes time pass pleasantly without much talking.",
  "Which object would you place at the center of a curiosity table?",
  "What is a harmless group decision best made by coin toss?",
  "Choose a cheerful alternative to a formal round of applause.",
  "Which small comfort would you offer at every community event?",
  "What could a group collect that costs nothing and harms nothing?",
  "Name a sign you would hang over a welcoming doorway.",
  "Which kind of puzzle invites collaboration without pressure?",
  "What small touch turns food served together into an occasion?",
  "Choose an imaginary scent for a candle called ‘Good Company.’",
  "Which shape would be funniest as an oversized cushion?",
  "What is a playful question a talking elevator might ask?",
  "Name a low-effort activity that reliably lifts a room’s energy.",
  "Which item from a stationery drawer could lead a tiny parade?",
  "What would a community garden name its most confident plant?",
  "Choose a shared mission that can be completed before the next hour.",
  "Which word would you put on a banner for an ordinary good day?",
  "What is the most enjoyable thing to arrange by color?",
  "Name a place where snacks always seem to taste better.",
  "Which playful rule could make a group walk more interesting?",
  "What is a good sound for everyone to imitate at once?",
  "Choose a fictional badge you would happily earn today.",
  "Which everyday item would benefit most from brighter colors?",
  "What could a group name a shared plant besides a person’s name?",
  "Name a tiny luxury suitable for a communal break basket.",
  "Which kind of photo captures a gathering without showing faces?",
  "What is an amusing job for an imaginary committee?",
  "Choose a food that would make a terrible building material.",
  "Which public sign could use a friendlier redesign?",
  "What is a fun reason for everyone to swap seats?",
  "Name a quick activity that helps a room reset after sitting.",
  "Which object makes the most satisfying gentle tap?",
  "What would you call a group expedition to the nearest snack shelf?",
  "Choose an ordinary object worth defending with unreasonable enthusiasm.",
  "Which imaginary creature would give excellent directions?",
  "What is a good group reward that does not cost money?",
  "Name a useful thing that people often carry in surprising styles.",
  "Which shared task feels most like a game already?",
  "What is the friendliest punctuation mark?",
  "Choose a costume theme that allows everyone to use what they own.",
  "Which common object could star in a very short comedy?",
  "What would improve a waiting room for people meeting each other?",
  "Name a harmless opinion that changes with the time of day.",
  "Which simple craft leaves room for every skill level?",
  "What is an easy way to celebrate someone joining the circle?",
  "Choose a fictional radio station for a community road trip.",
  "Which object could serve as a playful talking piece?",
  "What is a pleasant question to answer using only one word?",
  "Name a team activity where careful noticing matters more than speed.",
  "Which kind of sandwich has the most architectural ambition?",
  "What should be printed on a group’s emergency confetti packet?",
  "Choose a sound that could politely interrupt a long pause.",
  "Which shared-space feature invites people to linger comfortably?",
  "What is an unusual but practical item for a community picnic?",
  "Name a made-up sport that requires excellent cooperation and no running.",
  "Which daily object deserves a more exciting name?",
  "What is a funny title for the person who remembers the charger?",
  "Choose a small creative project a group could finish in one sitting.",
  "Which kind of light makes food look most inviting?",
  "What could turn an ordinary hallway into a playful experience?",
  "Name a positive message that fits on a very small sticker.",
  "Which item is always useful at a shared gathering but often forgotten?",
  "What is the best way to divide into teams without awkwardness?",
  "Choose a gesture for thanking the whole room at once.",
  "Which simple sound can almost everyone make in rhythm?",
  "What would you include in a five-minute festival?",
  "Name a way to make introductions memorable without sharing personal facts.",
  "Which piece of furniture seems most interested in conversation?",
  "What is a charming name for a community weather report?",
  "Choose a small role that helps a group outing run smoothly.",
  "Which everyday scene would make a delightful postcard?",
  "What is the most sociable shape of food?",
  "Name an object that makes a satisfying reveal when opened.",
  "Which activity gives everyone something different to notice?",
  "What playful instruction would you put on a reusable cup?",
  "Choose a group pose that requires no touching.",
  "Which ordinary sound could begin a dance track?",
  "What is a kind way to offer someone a turn without putting them on the spot?",
  "Name a place where people naturally help one another briefly.",
  "Which fictional shop would this group enjoy browsing?",
  "What could a group make from everyone contributing one word?",
  "Choose a bright color for an imaginary community bicycle.",
  "Which kind of list is surprisingly enjoyable to compare?",
  "What is a playful alternative to saying ‘meeting adjourned’?",
  "Name a simple activity that works equally well indoors and outdoors.",
  "Which snack has the best sound when opened?",
  "What should a sign beside a communal kettle say?",
  "Choose a funny but respectful title for today’s timekeeper.",
  "Which object could be redesigned to encourage sharing?",
  "What is a low-key way for a group to mark the end of a good day?",
  "Name a type of map that would be fun to create together.",
  "Which little sound signals comfort to you?",
  "What theme would make a casual potluck easier to contribute to?",
  "Choose a word that feels like a friendly wave.",
  "Which ordinary moment is improved by good company but fine alone?",
  "What is a creative use for a roll of colorful tape at a gathering?",
  "Name a group game that could be invented around noticing details.",
  "Which food looks most like it is ready to celebrate?",
  "What would a welcome mat for curious people say?",
  "Choose a shared object that could record pleasant discoveries.",
  "Which common sound would make the funniest notification tone?",
  "What is a gentle way to energize a group after a break?",
  "Name a small feature that makes public spaces more humane.",
  "Which everyday tool could be the hero of a children’s story?",
  "What kind of souvenir could a group create without buying anything?",
  "Choose a weather forecast made entirely of encouraging words.",
  "Which topic is fun to rank even when nobody agrees?",
  "What is a useful role for someone who prefers not to speak much?",
  "Name a silly collective noun for people sharing snacks.",
  "Which familiar object could inspire a cooperative mime?",
  "What would make a group walk accessible and enjoyable for more people?",
  "Choose a gentle noise for signaling that time is nearly up.",
  "Which ordinary container has the most personality?",
  "What is an easy tradition a group could begin and end today?",
  "Name a question that can be answered by pointing somewhere in the room.",
  "Which type of decoration encourages people to add their own touch?",
  "What is the best imaginary prize for excellent listening?",
  "Choose a food to represent teamwork and explain its credentials.",
  "Which bit of good news is enjoyable to share with a room?",
  "What could everyone contribute to a collaborative doodle?",
  "Name a playful way to signal agreement without speaking.",
  "Which small public kindness is satisfying to witness?",
  "What is a funny question for a group’s imaginary advice column?",
  "Choose a practical superpower for hosting casual gatherings.",
  "Which everyday surface would make an unexpected game board?",
  "What would you call a break reserved for stretching and smiling?",
  "Name an item that is especially pleasing to share in multiples.",
  "Which low-stakes mystery could this room investigate?",
  "What is a welcoming alternative to asking everyone to perform an introduction?",
  "Choose a tiny flag design for a neighborhood of friendly introverts.",
  "Which common task reveals people’s different creative approaches?",
  "What would make a name tag more useful and less formal?",
  "Name a shared challenge where patience is the main advantage.",
  "If this group needed a meeting surface on the move, what would work?",
  "What is a pleasant way to use the final five minutes of a gathering?",
  "Choose a sound for discovering that everyone brought the same snack.",
  "Which imaginary award could every person win for a different reason?",
  "What could a group build by arranging only objects already present?",
  "Name an easy conversation that can happen while hands are busy.",
  "Which place has surprisingly good acoustics for laughter?",
  "What is a playful boundary that makes a game more enjoyable?",
  "Choose a word to describe the energy you hope this room keeps.",
  "Which shared activity makes different perspectives immediately visible?",
  "What would be a good title for a group photo album with no portraits?",
  "Name a snack-serving method that reduces awkward reaching.",
  "Which everyday object invites the most creative alternative uses?",
  "What is a quick way to appreciate the space hosting everyone?",
  "Choose a harmless challenge involving only facial expressions.",
  "Which object would make a satisfying baton for a walking group?",
  "What recurring contribution should a communal calendar help people notice?",
  "Name a simple pleasure that is easy to recommend without explanation.",
  "Which small change could make a circle of chairs more inviting?",
  "What is a funny but clear name for the lost-and-found box?",
  "Choose a group activity that produces something useful at the end.",
  "Which sound from daily life deserves a live audience?",
  "What could everyone spot on the way home for a shared scavenger list?",
  "Name a cheerful rule for borrowing communal supplies.",
  "Which ordinary object would look best at giant scale?",
  "What is a lighthearted way to learn how people prefer to participate?",
  "Choose a theme for a table where anyone may leave a recommendation.",
  "Which simple item can transform an empty space into a gathering place?",
  "What ordinary detail from today might make an amusing future reminder?",
  "Name a gentle team challenge that rewards asking for help.",
  "Which food is easiest to describe using dramatic language?",
  "What is a playful title for someone who notices when supplies run low?",
  "Choose a two-word invitation that sounds open but not demanding.",
  "Which public place offers the best free entertainment?",
  "What could make taking turns feel more like a game?",
  "Name a pleasant activity for people who arrive early.",
  "Which tiny choice says the most about someone’s style?",
  "What is a creative way to reuse event decorations together?",
  "Choose a fictional service this group could offer purely for fun.",
  "Which room feature can quietly help people feel oriented?",
  "What could everyone add to a shared drawing of an imaginary town?",
  "Name a lighthearted question with no wrong answer and many good stories.",
  "Which object should be passed around simply because it feels nice?",
  "What is a good way for a group to enjoy different music tastes?",
  "Choose an animal sound that would be hardest to perform seriously.",
  "What is a simple way to leave a shared place better than you found it?",
  "Choose a closing gesture that includes people joining from a distance.",
]

export const RECONNECT_GROUP_MEANINGFUL: readonly string[] = [
  "What helps you feel that your contribution to a group matters?",
  "Name a quality you appreciate in people who make room for others.",
  "When does a gathering begin to feel like a community to you?",
  "What kind of welcome makes participation easier on a first visit?",
  "Which shared value can guide a group through ordinary disagreements?",
  "What does thoughtful cooperation look like in a small task?",
  "Describe a time when someone’s curiosity helped you feel understood.",
  "What group habit makes it easier for different ideas to coexist?",
  "How can people show appreciation without putting anyone in the spotlight?",
  "What do you value about hearing perspectives unlike your own?",
  "Which form of support feels useful during a demanding week?",
  "What makes a shared goal feel genuinely shared?",
  "Name a strength that often goes unnoticed in group settings.",
  "How do you recognize when a group is listening well?",
  "What encourages you to offer an idea before it is fully formed?",
  "Which everyday act helps build a sense of belonging?",
  "What can a group learn from someone who participates quietly?",
  "How should people respond when a newcomer asks a basic question?",
  "What kind of acknowledgment feels sincere to you?",
  "When have differing viewpoints improved an outcome you shared?",
  "What makes it easier to ask a group for practical help?",
  "Which behind-the-scenes role changes the experience most when done well?",
  "How can a group make decisions without rushing less vocal members?",
  "What shared experience can connect people across different backgrounds?",
  "Name a value that becomes visible through small actions.",
  "What helps you remain open when someone sees an issue differently?",
  "How can a group celebrate progress that is still incomplete?",
  "What does reliability look like when many people share responsibility?",
  "Which kind of question signals real interest rather than politeness?",
  "What is one way people can make room for changing opinions?",
  "How does humor help connection when it is used with care?",
  "What makes feedback feel like an investment in the group?",
  "Name a group strength that grows when it is practiced regularly.",
  "What helps people contribute when they have different communication styles?",
  "How can shared routines create comfort without becoming rigid?",
  "What have you learned from working beside someone with different priorities?",
  "Which sign tells you a community respects people’s time?",
  "What is meaningful about being remembered in a small, accurate way?",
  "How can people disagree while protecting everyone’s dignity?",
  "What kind of encouragement helps you keep learning?",
  "Name a contribution that matters even when no one sees it happen.",
  "What helps a group move from friendly conversation to useful action?",
  "How do you prefer others to check their understanding of your point?",
  "Which shared responsibility can strengthen trust over time?",
  "What does generosity with attention look like?",
  "When has a group helped you see a familiar place differently?",
  "What makes an invitation feel genuine rather than automatic?",
  "How can a community honor both continuity and new ideas?",
  "What is one benefit of having different approaches in the same room?",
  "Which behavior makes it safer to admit a small mistake?",
  "What kind of follow-through helps appreciation feel credible?",
  "How can a group notice who is carrying invisible work?",
  "What makes shared learning feel collaborative instead of competitive?",
  "Name a lesson you gained from someone outside your usual circle.",
  "What does it mean to be a considerate guest in a community space?",
  "How might a group respond when someone needs more context?",
  "Which tradition can strengthen connection without excluding newcomers?",
  "What helps you trust that a group will use your time well?",
  "How can appreciation be expressed across different comfort levels?",
  "What is a respectful way to learn how someone wants to be included?",
  "Name a moment when cooperation made something feel lighter.",
  "What qualities make a group conversation worth returning to?",
  "How do shared stories help people understand a place?",
  "Which act of preparation shows care for a wide range of participants?",
  "What can people do when a good intention has an unhelpful impact?",
  "How does a group benefit when members can say ‘I need time’?",
  "What makes a community space feel cared for rather than merely used?",
  "Name a way to recognize effort without comparing people.",
  "What helps a group remain connected between formal gatherings?",
  "How can people make a shared task accessible to more abilities?",
  "Which question helps uncover what a team already does well?",
  "What does patience contribute to collective problem-solving?",
  "When does compromise feel constructive rather than merely convenient?",
  "What kind of support respects someone’s independence?",
  "How can a group welcome expertise without silencing other knowledge?",
  "Name a simple practice that helps people remember shared commitments.",
  "What makes it possible to enjoy connection without constant agreement?",
  "How do you like a group to handle unanswered questions?",
  "Which experience taught you something useful about taking turns?",
  "What does care look like in the way a gathering is organized?",
  "How can people acknowledge a contribution that changed their thinking?",
  "Name a community resource you value because people maintain it together.",
  "What helps you feel comfortable offering a different interpretation?",
  "How can a group make gratitude specific without making it personal?",
  "Which shared practice helps prevent assumptions from filling gaps?",
  "What do you appreciate about people who connect ideas across a group?",
  "When can slowing down improve a collective decision?",
  "What makes a request for volunteers feel respectful?",
  "How might a group include people who prefer observing before joining?",
  "Name a quality that helps communities recover from minor setbacks.",
  "What kind of transparency helps people participate with confidence?",
  "How can people make space for both celebration and unfinished work?",
  "Which group experience helped you appreciate a skill you do not have?",
  "What does shared ownership sound like in everyday conversation?",
  "How can a community show that questions are welcome?",
  "Name a supportive response to someone changing their mind.",
  "What helps different generations or experience levels learn together?",
  "How does being thanked affect your willingness to contribute again?",
  "Which norm keeps lively discussion from becoming personal competition?",
  "What makes a group’s purpose clear in the choices it makes?",
  "How can people support a plan they did not originally prefer?",
  "Name a way shared laughter can strengthen connection without targeting anyone.",
  "What does responsible participation mean when energy is limited?",
  "How might a group learn from a project that did not go as planned?",
  "Which kind of reminder helps commitments feel communal rather than imposed?",
  "What helps you notice common ground without erasing real differences?",
  "How can people invite context without demanding personal explanation?",
  "Name a way to make useful knowledge easier to pass along.",
  "What does a healthy balance between speaking and listening look like?",
  "How can a group care for the people who regularly care for logistics?",
  "Which everyday courtesy has an outsized effect on belonging?",
  "What makes it easier to receive a suggestion with curiosity?",
  "How can community members share opportunities more fairly?",
  "Name a time when a small adjustment helped more people participate.",
  "What does it mean for a group to respect a person’s ‘not today’?",
  "How might shared meals reveal both differences and common ground?",
  "Which form of recognition motivates without creating a hierarchy?",
  "What helps people repair a minor misunderstanding quickly?",
  "How can a group avoid relying on the same volunteers every time?",
  "Name a value you can hear in the way people ask questions.",
  "What makes a community promise believable?",
  "How do you know when people are building on one another’s ideas?",
  "Which shared memory could help a group remember its strengths?",
  "What does inclusion require beyond extending an invitation?",
  "How can people contribute when they cannot attend in person?",
  "Name a way a group can make room for cultural differences with care.",
  "What helps you feel that your questions will be taken seriously?",
  "How might people respond when someone corrects a name or pronunciation?",
  "Which collective accomplishment deserves quiet pride?",
  "What makes a facilitator feel trustworthy to you?",
  "How can a group share responsibility for keeping conversations welcoming?",
  "Name a practical sign that people’s feedback changed something.",
  "What does mutual respect allow a community to attempt?",
  "How can a shared project make room for different definitions of success?",
  "Which kind of appreciation is best offered in the moment?",
  "What helps a group stay curious about people it thinks it knows?",
  "How might community history guide choices without controlling them?",
  "Name a way to support someone’s idea without taking it over.",
  "What does consistency add to a sense of safety?",
  "How can people explain an unwritten norm without making anyone feel behind?",
  "What changes in a project once everyone understands where decisions sit?",
  "What helps you engage with a topic that is new to you?",
  "How can a group honor work that happens at different speeds?",
  "Name an example of leadership that does not require a title.",
  "What makes collective reflection feel useful rather than ceremonial?",
  "How might people make a recurring gathering easier to rejoin after absence?",
  "Which shared value matters most when resources are limited?",
  "What helps a community distinguish urgency from importance?",
  "How can a group appreciate candid input while maintaining kindness?",
  "Name a way to learn from disagreement after the moment has passed.",
  "What does dependable communication contribute to shared confidence?",
  "How might a group make its language easier for newcomers to follow?",
  "Which experience showed you the value of asking before helping?",
  "What helps people say they are unsure without losing credibility?",
  "How can communities celebrate traditions while allowing people to opt out?",
  "Name a strength that emerges when different skills complement one another.",
  "What does a fair opportunity to contribute look like?",
  "How can a group tell whether its usual process still serves everyone?",
  "Which thoughtful detail makes you feel expected rather than accommodated?",
  "What helps turn a collection of individual efforts into shared work?",
  "How might people express care when they do not know one another well?",
  "Name a community lesson that is best learned through practice.",
  "What does being accountable to one another add to a shared goal?",
  "How can a group protect time for reflection amid action?",
  "Which communication habit helps reduce avoidable confusion?",
  "What makes it easier to offer credit generously?",
  "How might people recognize when a familiar activity excludes someone?",
  "Name a sign that a group can handle honest questions.",
  "What does hospitality mean when no one person is the host?",
  "How can community members preserve useful knowledge through transitions?",
  "Which kind of listening helps someone refine their own idea?",
  "What helps a group keep promises realistic?",
  "How might people thank someone who prefers little attention?",
  "Name a way to create continuity when membership changes.",
  "What does shared responsibility require from people with more influence?",
  "How can a group make introductions useful rather than performative?",
  "Which act helps people feel less alone in learning something difficult?",
  "What makes an apology relevant to a whole group?",
  "How might a community invite participation without measuring commitment by visibility?",
  "Name a constructive role for someone who notices potential problems early.",
  "What does a well-kept boundary protect in a collaborative space?",
  "How can groups respond to different needs without ranking them?",
  "Which shared expectation frees people to be more creative?",
  "What helps people receive context they initially overlooked?",
  "How might a group make room for both expertise and lived observation?",
  "Name a meaningful way to mark the completion of collective work.",
  "What does it look like when people trust one another’s good faith?",
  "How can a community invite feedback from people who left early?",
  "Which kind of question helps a group examine its own habits?",
  "What makes offering help feel collaborative rather than rescuing?",
  "How might shared art or music reveal a community’s character?",
  "What unfamiliar approach have you come to respect after observing it in action?",
  "What does it mean to leave room for an answer to evolve?",
  "How can people show they value a perspective they do not share?",
  "Which group ritual can reinforce equality among participants?",
  "What helps a community sustain energy beyond an exciting beginning?",
  "How might people make expectations visible without overcomplicating them?",
  "Name a form of care that can be built into a schedule.",
  "What does a genuinely collaborative invitation include?",
  "How can a group encourage initiative while coordinating efforts?",
  "Which behavior shows respect for someone’s chosen level of openness?",
  "What helps people find their place in a project already underway?",
  "How might a community use celebration to reinforce its values?",
  "Name a question that helps reveal overlooked resources in a group.",
  "What does it look like to share influence, not only tasks?",
  "How can people respond when the same voices keep being heard first?",
  "Which group quality makes adapting plans feel less disruptive?",
  "What helps transform appreciation into ongoing support?",
  "How might a gathering honor the work of people who are absent?",
  "Name a way to make a collective decision easier to revisit later.",
  "What does curiosity contribute when people have different assumptions?",
  "How can a group discuss impact without guessing anyone’s intentions?",
  "Which shared practice helps people recover after an awkward moment?",
  "What makes room for joy in serious community work?",
  "How might people learn what access means for different participants?",
  "Name a sign that a group values maintenance as much as new ideas.",
  "What does it mean to participate in a way that leaves room for others?",
  "How can communities welcome constructive skepticism?",
  "Which type of support is easiest to offer consistently?",
  "What helps people ask for clarification without embarrassment?",
  "How might a group balance efficiency with relationship-building?",
  "Name a shared experience that can create connection without requiring disclosure.",
  "What does careful stewardship of a common resource look like?",
  "How can people acknowledge differences in availability without judging commitment?",
  "Which kind of preparation communicates respect for participants?",
  "What helps a group make space for unexpected contributions?",
  "How might people keep a conversation useful when certainty is limited?",
  "Name a value that is strengthened by being practiced collectively.",
  "What does it look like when a community learns in public?",
  "How can a group honor someone’s contribution after they step away?",
  "Which small repair can prevent a misunderstanding from growing?",
  "What helps shared spaces reflect the people who use them?",
  "How might community members exchange skills without creating obligation?",
  "Name a form of encouragement that recognizes process rather than outcome.",
  "What does respectful persistence look like in collective work?",
  "How can groups make rest compatible with shared responsibility?",
  "Which question can reconnect a discussion to its purpose?",
  "What helps people identify with a group without feeling they must conform?",
  "How might a community respond when participation changes over time?",
  "Name a way to make informal knowledge available to everyone.",
  "What does fairness require when people begin with different resources?",
  "How can a group recognize tension before it becomes conflict?",
  "Which shared habit makes coordination feel less burdensome?",
  "What helps people feel comfortable naming a practical constraint?",
  "How might communities show respect for languages they do not all speak?",
  "Name a way to invite ideas from people who process before responding.",
  "What does a generous interpretation make possible in conversation?",
  "How can group members check whether support is actually useful?",
  "Where have you noticed coordination becoming easier through practice?",
  "What helps a community preserve warmth as it grows?",
  "How might people make shared credit more visible?",
  "Name a constructive question to ask after a successful event.",
  "Where is the line between being reliable and promising beyond your capacity?",
  "How can groups support participation that happens behind the scenes?",
  "Which feature of a gathering helps you know what to expect?",
  "What helps people stay connected when priorities shift?",
  "How might a group show that opting out will be respected?",
  "Name a way different viewpoints can reveal a hidden assumption.",
  "What does thoughtful use of shared time look like?",
  "How can communities keep necessary structure from feeling impersonal?",
  "Which contribution becomes more valuable as a group gets larger?",
  "What helps a team recognize when its success depends on outside support?",
  "How might people make a shared plan legible to someone joining later?",
  "Name a way to honor both individual effort and collective conditions.",
  "What does learning someone’s preferred form of participation communicate?",
  "How can a group keep curiosity alive after familiarity grows?",
  "Which sign shows that people feel ownership of a common space?",
  "What helps communities carry lessons from one project into the next?",
  "How might people surface disagreement before a decision feels fixed?",
  "Name a form of gratitude that strengthens future cooperation.",
  "What does it look like when a group values questions as contributions?",
  "How can shared purpose coexist with different personal motivations?",
  "Which practice makes room for people whose circumstances change suddenly?",
  "What helps a community stay welcoming during a busy period?",
  "How might people describe a group strength without idealizing the group?",
  "Name a way to recognize progress that is difficult to measure.",
  "What does a respectful handoff of responsibility involve?",
  "How can group members make consent part of ordinary collaboration?",
  "Which kind of reflection helps a community choose its next step?",
  "What helps people contribute honestly without needing complete confidence?",
  "How might a group clarify who benefits from a proposed idea?",
  "Name a way to make community care practical rather than abstract.",
  "What does a good balance of continuity and experimentation feel like?",
  "How can people keep a difference of opinion from defining a relationship?",
  "Which shared experience helps reveal the range of strengths present?",
  "What helps a group notice when its pace is leaving people behind?",
  "How might communities invite correction as part of learning?",
  "Name a reminder that can reconnect people to a shared purpose.",
  "What does belonging allow someone to contribute more freely?",
  "How can a group value care work without assigning it by stereotype?",
  "Which practice helps people distinguish a preference from a requirement?",
  "What helps a community make thoughtful choices under mild pressure?",
  "How might people respond when gratitude arrives later than expected?",
  "Name a way to keep collaboration humane when the task is repetitive.",
  "What does collective confidence grow from?",
  "How can groups make space for delight alongside productivity?",
  "Which question helps identify what should remain unchanged?",
  "What helps people understand the reason behind a group norm?",
  "How might a community welcome someone without asking them to represent others?",
  "Name a useful way to document a shared learning moment.",
]

export const RECONNECT_GROUP_DEEP: readonly string[] = [
  "What would help this group make room for needs that are not immediately visible?",
  "How can a community repair trust without asking anyone to move on quickly?",
  "Which boundary allows you to participate more fully rather than less?",
  "What does meaningful change require beyond agreeing that change is needed?",
  "How might a group examine its impact without becoming defensive?",
  "What part of a community’s identity should remain open to revision?",
  "How can people name unmet needs without assigning motives to others?",
  "Which signs suggest that a group’s stated values match its habits?",
  "What does accountability look like when responsibility is widely shared?",
  "How might a community respond when its usual approach no longer fits?",
  "What helps people stay present during a difficult but respectful conversation?",
  "How can a group acknowledge harm while preserving everyone’s agency?",
  "Which expectations deserve to be reconsidered as a community changes?",
  "What makes a boundary understandable even when others would choose differently?",
  "How might people rebuild cooperation after a plan creates disappointment?",
  "What does it mean for a group to learn without demanding personal testimony?",
  "How can communities notice when belonging comes with hidden conditions?",
  "Which need is easiest for groups to overlook when momentum is high?",
  "What would make it safer to challenge an established group practice?",
  "How might collective identity expand without losing useful continuity?",
  "What does repair require from people who were not directly involved?",
  "How can a group hold uncertainty without forcing a quick consensus?",
  "Which boundary helps prevent care from turning into overreach?",
  "What makes a community’s invitation to dissent believable?",
  "How might people distinguish discomfort that teaches from pressure that silences?",
  "What does shared courage look like in a low-drama moment?",
  "How can a group respond when its impact contradicts its intentions?",
  "Which part of collaboration needs renegotiation when capacity changes?",
  "What helps people discuss power without reducing anyone to a single role?",
  "How might a community protect connection while making a necessary change?",
  "What does consent add to decisions that seem minor?",
  "How can people make repair specific without demanding public vulnerability?",
  "Which inherited norm would benefit from a fresh explanation?",
  "What helps a group recognize when silence may mean different things?",
  "How might people share responsibility for an outcome they did not foresee?",
  "What does a sustainable commitment to community look like for you?",
  "How can groups prevent urgency from overriding participation needs?",
  "Which kind of boundary can strengthen trust across differences?",
  "What would help a community revisit a decision without reopening every question?",
  "How might people respond when someone names an exclusion others missed?",
  "What does collective maturity look like after receiving difficult feedback?",
  "How can a group separate a person’s worth from the effect of an action?",
  "Which future choice could better reflect the community you want to become?",
  "What helps people stay connected while their roles are changing?",
  "How might a group notice when harmony is being valued above honesty?",
  "What does an accountable apology avoid asking from those affected?",
  "How can communities make room for ambivalence during transition?",
  "Which part of your group participation would you like to approach differently?",
  "What helps a boundary feel like useful information rather than rejection?",
  "How might people repair a process even when the outcome cannot be changed?",
  "What does shared purpose need in order to survive disagreement?",
  "How can a group recognize growth without claiming the work is finished?",
  "Which assumptions about availability should a community question?",
  "What helps people offer honesty without turning it into a demand?",
  "How might a group plan for the needs of people not currently in the room?",
  "What does it mean to belong without surrendering individuality?",
  "How can communities respond when a familiar tradition has mixed effects?",
  "Which repair matters even if no one asks for it directly?",
  "What helps a group examine who benefits from keeping things unchanged?",
  "How might people negotiate a need that cannot be fully met?",
  "What does respectful distance contribute to community life?",
  "How can a group make space for someone to re-enter after stepping back?",
  "Which values become hardest to practice under pressure?",
  "What helps people remain curious when feedback feels surprising?",
  "How might a community share difficult responsibility without spreading blame?",
  "What does a healthy limit on participation protect?",
  "How can groups avoid treating familiarity as permission?",
  "Which aspect of a collective future deserves more honest attention?",
  "What helps a community acknowledge different experiences of the same event?",
  "How might people repair a missed opportunity to include others?",
  "What does it look like to disagree with a norm while respecting the group?",
  "How can a group respond when someone’s capacity becomes less predictable?",
  "Which question helps reveal whether a change is substantive or symbolic?",
  "What helps people name limits before resentment builds?",
  "How might a community preserve relationships when responsibilities are redistributed?",
  "What does collective care require when no solution satisfies everyone?",
  "How can groups make room for people to update how they identify?",
  "Which part of repair is possible without agreement about every detail?",
  "What helps a community hear criticism as information about connection?",
  "How might people challenge a pattern without labeling one another?",
  "What does it mean to choose a future rather than drift into one?",
  "How can a group recognize when its pace is becoming a barrier?",
  "Which unspoken expectation would be useful to make discussable?",
  "What helps people remain accountable when intentions were kind?",
  "How might a community prevent one person from carrying all the emotional work?",
  "What does a flexible boundary retain even when circumstances shift?",
  "How can groups welcome changed perspectives without rewriting the past?",
  "Which shared need can be mistaken for an individual preference?",
  "What helps a community decide what it is ready to stop doing?",
  "How might people accept an incomplete repair while keeping commitments clear?",
  "What does it look like to protect dissent from social penalty?",
  "How can a group explore its identity without speaking for every member?",
  "Which form of accountability focuses attention on the next right action?",
  "What helps people distinguish support from unwanted intervention?",
  "How might a community respond when a rule affects people unevenly?",
  "What does honest hope require from a group facing change?",
  "How can groups recognize pressure disguised as enthusiasm?",
  "Which aspect of belonging should never require proving loyalty?",
  "What helps a community accept a boundary it does not fully understand?",
  "How might people repair trust through repeated ordinary actions?",
  "What does shared leadership require when opinions are sharply divided?",
  "How can a group discuss who has influence without making assumptions about identity?",
  "Which future norm could make participation more humane?",
  "What helps people revise a commitment without avoiding responsibility?",
  "How might a community respond to feedback from someone who chooses anonymity?",
  "What does a fair process offer when a perfect outcome is impossible?",
  "How can groups avoid turning openness into an expectation of disclosure?",
  "Which need deserves protection even when it slows the group down?",
  "What helps people notice when a repair attempt centers the wrong person?",
  "How might a community retire a tradition with gratitude and clarity?",
  "What does mutual agency look like in a difficult decision?",
  "How can a group learn why someone disengaged without pressuring them to explain?",
  "Which part of collective identity comes from what a community refuses to normalize?",
  "What helps people recognize when compromise would cross a boundary?",
  "How might groups support someone who needs connection on different terms?",
  "What does it mean to repair conditions, not only relationships?",
  "How can a community make its future plans resilient to changing capacity?",
  "Which quiet pattern might deserve more attention than a visible conflict?",
  "What helps people receive a ‘no’ without withdrawing warmth?",
  "How might a group acknowledge uncertainty about its own history?",
  "What does responsible influence look like for long-standing members?",
  "How can communities change course without treating earlier effort as wasted?",
  "Which shared boundary could protect both focus and connection?",
  "What helps a group recognize when asking for patience has become delay?",
  "How might people hold one another to standards without becoming punitive?",
  "What does a community owe to those affected by decisions but absent from them?",
  "How can a group remain welcoming while being clear about its purpose?",
  "Which kind of change needs conversation before implementation?",
  "What helps people discuss needs without competing over whose matters most?",
  "How might a community make repair possible when direct conversation is not wanted?",
  "What does integrity require when a group discovers a gap in its practice?",
  "How can groups treat stepping back as information rather than failure?",
  "Which future possibility would require the group to learn a new skill?",
  "What helps people challenge an idea without isolating its speaker?",
  "How might a community recognize forms of participation it cannot easily count?",
  "What does a boundary around emotional labor make possible?",
  "How can a group revisit shared language when its meaning has shifted?",
  "Which aspect of repair depends most on consistency?",
  "What helps people stay grounded when a conversation changes direction unexpectedly?",
  "How might communities prevent informal influence from becoming invisible authority?",
  "What does it mean to make space for multiple truths about a shared experience?",
  "How can a group choose transparency without exposing private information?",
  "Which need might become clearer if the group slowed its decision process?",
  "What helps people participate without performing certainty?",
  "How might a community respond when its symbols no longer represent everyone?",
  "What does a respectful ending to a shared initiative involve?",
  "How can groups notice when resilience language is masking exhaustion?",
  "Which relationship in a community needs care beyond task coordination?",
  "What helps a group use conflict as data without romanticizing it?",
  "How might people make amends when they cannot restore what was lost?",
  "What does freedom to change one’s mind contribute to psychological safety?",
  "How can a community clarify what confidentiality can and cannot mean?",
  "Which expectation of togetherness may need more flexibility?",
  "What helps people share concern without creating alarm?",
  "How might a group decide what information belongs in a public record?",
  "What does a collective boundary need in order to be fair?",
  "How can communities remain accountable to people who no longer participate?",
  "Which part of a repair process should not be rushed for convenience?",
  "What helps people name changing priorities without dismissing prior commitments?",
  "How might a group make room for someone whose values partly overlap?",
  "What does sustainable generosity look like when resources are uneven?",
  "How can a community distinguish invitation from subtle obligation?",
  "Which difficult question could improve a future gathering without seeking personal stories?",
  "What helps people tell the difference between care and control?",
  "How might groups allow leadership to move toward those closest to an issue?",
  "What does belonging mean when participation is occasional?",
  "How can a community respond when a shared story leaves some members out?",
  "Which repair can happen through changed structure rather than more conversation?",
  "What helps people remain open while protecting their own limits?",
  "How might a group prepare for disagreement before it arises?",
  "What does accountable use of community resources require?",
  "How can groups question a norm without shaming those who followed it?",
  "Which future decision should include voices beyond the regular participants?",
  "What helps a community accept that closure may look different for different people?",
  "How might people avoid assigning one person the role of peacekeeper?",
  "What does it mean to respect a boundary that arrives late?",
  "How can a group learn from departures without treating people as evidence?",
  "Which shared need could be met through redesign rather than extra effort?",
  "What helps people recognize when a conversation needs a pause?",
  "How might a community offer repair without requiring acceptance?",
  "What does a future-facing apology commit to?",
  "How can groups preserve nuance when retelling a difficult moment?",
  "Which form of change would make responsibility easier to share?",
  "What helps people separate belonging from constant agreement?",
  "How might a community respond when two valid needs compete?",
  "What does it look like to hold a firm standard with compassion?",
  "How can groups create options before asking people to choose?",
  "Which part of a community’s culture is shaped by what goes unaddressed?",
  "What helps people voice a concern without needing to propose the solution?",
  "How might a group protect those who question a popular direction?",
  "What does responsible hope sound like when outcomes are uncertain?",
  "How can a community keep belonging from depending on productivity?",
  "Which group habit might be useful to unlearn?",
  "What helps people re-establish trust after inconsistent follow-through?",
  "How might a group consider fairness across both present and future participants?",
  "What does a boundary teach others about how to collaborate with you?",
  "How can communities reflect on power without expecting anyone to disclose personal identity?",
  "Which need becomes visible only when the usual process stops?",
  "What helps people admit that a well-meant solution did not work?",
  "How might a group support change that not everyone experiences at the same pace?",
  "What does respectful accountability leave room for?",
  "How can communities prevent repair conversations from becoming debates over memory?",
  "Which future direction would better match the group’s actual capacity?",
  "What helps people release a role that has become too limiting?",
  "How might a group notice when inclusion depends on unpaid effort?",
  "What does it mean to honor a need without promising to meet it fully?",
  "How can a community make a difficult decision without manufacturing unanimity?",
  "Which form of clarity can reduce fear during a transition?",
  "What helps people rejoin a conversation after feeling misunderstood?",
  "How might a group distinguish privacy from secrecy in its processes?",
  "What does care require when someone chooses not to participate?",
  "How can communities respond when a boundary changes with context?",
  "Which repair should be visible to the whole group?",
  "What helps people question urgency when others are eager to act?",
  "How might a community share decision-making with those who have less time?",
  "What does a group learn by noticing who feels free to interrupt?",
  "How can people stay in relationship without resolving every difference?",
  "Which shared expectation could be replaced with a menu of options?",
  "What helps a community make changes that outlast individual champions?",
  "How might people express disappointment without making it another person’s burden to fix?",
  "What does repair look like when the original context has changed?",
  "How can a group make its limits as clear as its ambitions?",
  "Which part of collective care requires saying ‘enough for now’?",
  "What helps people recognize a shift in identity without demanding explanation?",
  "How might communities ensure that disagreement does not threaten access?",
  "What does it mean to invite challenge from a position of influence?",
  "How can a group respond when a common practice relies on assumptions?",
  "Which future tradition could better express shared values?",
  "What helps people stay accountable without becoming defined by one mistake?",
  "How might a community make room for grief about change without probing its source?",
  "What does autonomy contribute to genuine connection?",
  "How can groups recognize when participation options are only nominally different?",
  "Which part of repair belongs to those with the most decision-making power?",
  "What helps people accept that trust may return gradually?",
  "How might a community address a repeated pattern without creating a public trial?",
  "What does an ethical use of personal stories require from listeners?",
  "How can a group plan for continuity without expecting anyone to be indispensable?",
  "Which unmet need could be addressed through a clearer process?",
  "What helps people make room for feedback they cannot act on immediately?",
  "How might communities avoid confusing comfort with safety?",
  "What does shared responsibility mean when influence is unequal?",
  "How can a group acknowledge that one experience had unequal consequences?",
  "Which boundary needs collective support rather than individual enforcement?",
  "What helps people remain generous without ignoring patterns?",
  "How might a community turn a difficult lesson into a protective practice?",
  "What does future readiness require a group to release?",
  "How can groups recognize identity without making it the price of being heard?",
  "Which form of repair centers changed behavior over explanation?",
  "What helps people disagree about priorities without questioning commitment?",
  "How might a community respond when its growth changes the quality of connection?",
  "What does it mean to design for dignity during conflict?",
  "How can a group ensure that asking for help does not reduce someone’s influence?",
  "Which expectation needs an explicit path for renegotiation?",
  "What helps people recognize when a solution transfers burden elsewhere?",
  "How might communities keep experimentation reversible when stakes are uncertain?",
  "What does repair ask of people who benefited from the old arrangement?",
  "How can a group make space for someone to participate without reconciliation?",
  "Which future goal would require deeper cooperation rather than more effort?",
  "What helps people share a need without presenting it as universal?",
  "How might a community respond when accountability feels unevenly applied?",
  "What does a compassionate limit sound like in group language?",
  "How can groups prevent one perspective from becoming the default?",
  "Which part of a transition needs a deliberate goodbye?",
  "What helps people notice when a request carries hidden pressure?",
  "How might a community keep reflection from becoming self-congratulation?",
  "What does a group need before it can make a durable promise?",
  "How can people protect another person’s choice not to explain?",
  "Which shared practice could reduce the need for individual courage?",
  "What helps a community remain open to being changed by new members?",
  "How might groups respond when the fairest option is not the most familiar?",
  "What does collective repair look like beyond a single conversation?",
  "How can a community respect different thresholds for participation?",
  "Which part of shared identity comes from aspirations rather than history?",
  "What helps people move from defending a process to improving it?",
  "How might a group make room for a firm boundary without seeking exceptions?",
  "What does it mean to value someone apart from what they contribute?",
  "How can communities discuss change without promising certainty?",
  "Which future choice would widen the range of people who can belong?",
  "What helps people revisit an old agreement with present-day honesty?",
  "How might a group name a rupture without turning it into its whole story?",
  "What does careful repair preserve besides trust?",
  "How can communities hold leaders accountable without making change depend on one person?",
  "Which need might be better met outside the group, with its support?",
  "What helps people recognize when they are speaking beyond their experience?",
  "How might a group decide what deserves patience and what requires action?",
  "Which possibilities appear when a community deliberately chooses a slower tempo?",
  "How can communities welcome people back without demanding continuity from them?",
  "Which aspect of a future plan should remain intentionally flexible?",
  "What helps people understand the cost of an easy solution?",
  "How might a group make accountability compatible with learning?",
  "Which conditions restore a sense that participation is truly open?",
  "How can communities support identity exploration without asking for labels?",
  "Which collective habit could make difficult conversations less exceptional?",
  "What helps people tell whether consensus is real or merely quiet?",
  "When changing membership reshapes a community’s purpose, what deserves attention?",
  "What does a respectful change of direction acknowledge?",
  "How can people protect a relationship while declining a request?",
  "Which form of community care should be planned before it is needed?",
  "What helps a group stay humble about what it cannot provide?",
  "How might people shape a future that allows participation to change form?",
]
