export const RECONNECT_FRIENDS_LIGHT = [
  'What snack would make our catch-up instantly more official?',
  'Which old joke between us still deserves another round?',
  'What harmless obsession has claimed your attention lately?',
  'If today had a soundtrack, what song would open it?',
  'What tiny convenience are you weirdly grateful for right now?',
  'Which shared adventure would be funniest as a low-budget movie?',
  'What is your current go-to excuse for leaving the house?',
  'Which food opinion are you still prepared to defend?',
  'What recent purchase has been doing too much emotional heavy lifting?',
  'If we had a two-person trivia team, what should our name be?',
  'What ordinary thing have you become unexpectedly good at?',
  'Which phase of our friendship had the most chaotic energy?',
  'What has made you laugh harder than it probably deserved lately?',
  'If your week were a weather forecast, what would it predict?',
  'Which hobby would you try if being terrible were part of the fun?',
  'What is the most unnecessary fact living in your head?',
  'Which familiar place should we revisit just for the nostalgia?',
  'What would your current life mascot be?',
  'Which everyday task makes you feel strangely accomplished?',
  'What is your latest small victory?',
  'If we opened a café together, what would be its odd specialty?',
  'Which trend did you judge before quietly joining?',
  'What is the funniest photo you remember us taking?',
  'What fictional character would be exhausting in our group chat?',
  'Which smell brings back a happy, uncomplicated memory?',
  'What have you watched recently that was better than expected?',
  'If your phone battery could describe your energy, what percentage are you?',
  'Which silly competition would you confidently challenge me to?',
  'What is your favorite way to waste ten minutes?',
  'Which childhood treat still feels like a reward?',
  'What was your most dramatic reaction to a minor inconvenience recently?',
  'If we could teleport for lunch, where would we go?',
  'Which part of your routine would surprise the old me?',
  'What song can still get you moving against your will?',
  'Which app knows far too much about your habits?',
  'What low-stakes mystery would you love solved?',
  'If our friendship had merchandise, what would it say?',
  'Which recent meal deserves a full review?',
  'What is the best thing you have found by accident lately?',
  'Which minor luxury now feels essential?',
  'What would your warning label say this week?',
  'Which game could keep us entertained longer than it should?',
  'Which shared mix-up improved every time we retold it?',
  'If you had a personal theme park ride, what would happen on it?',
  'Which outfit from your past should remain safely in the past?',
  'What is your most reliable mood-lifting song?',
  'Which familiar story do you still enjoy hearing me tell?',
  'What harmless thing makes you far too competitive?',
  'If you could instantly master one party trick, which one?',
  'What everyday object would make the worst travel companion?',
  'Which recent discovery have you been recommending to everyone?',
  'What is the most fun you have had without planning it?',
  'If our next hangout had a ridiculous theme, what should it be?',
  'Which place near you is worth crossing town for?',
  'What is your current comfort rewatch?',
  'Which animal best matches your social energy these days?',
  'What small upgrade has improved your daily life?',
  'If you could rename one day of the week, which day and why?',
  'What is the best compliment you have received about something trivial?',
  'Which sound effect belongs in your morning routine?',
  'What shared memory would make a perfect reaction GIF?',
  'If we swapped playlists for a day, what would surprise me?',
  'Which boring subject can you make unexpectedly interesting?',
  'What is your favorite excuse to celebrate?',
  'Which snack combination should not work but absolutely does?',
  'If your current mood were a menu item, what would it be?',
  'What has become easier since the last time we properly caught up?',
  'Which famous person would be funniest as our third roommate?',
  'What is the most useful thing you learned from a random video?',
  'Which local spot feels like your unofficial headquarters?',
  'If we made a time capsule today, what silly item belongs inside?',
  'What is the best nickname you have ever heard?',
  'Which chore would you gladly outsource forever?',
  'What piece of harmless gossip from nature fascinates you?',
  'If you hosted a very specific awards show, what would it honor?',
  'Which old favorite have you recently rediscovered?',
  'What tiny problem have you invented an excellent solution for?',
  'Which fictional neighborhood would make a hilarious setting for our next catch-up?',
  'What is your current ideal lazy afternoon?',
  'If we had to enter a talent show tomorrow, what could we perform?',
  'Which season suits your personality best right now?',
  'What accidental tradition should we start repeating?',
  'Which word have you been overusing lately?',
  'What is the least impressive thing you are proud to know?',
  'If your day came with bonus content, what would viewers see?',
  'Which place from our past would look most different now?',
  'What recent recommendation actually lived up to the hype?',
  'Which food would you choose as your personal logo?',
  'What is your funniest recent autocorrect or typo?',
  'If we took a class together purely for laughs, what would it teach?',
  'Which ordinary errand do you secretly enjoy?',
  'What is the most cheerful thing in your space right now?',
  'Which decade would host the best themed night for us?',
  'What random skill has saved your day more than once?',
  'If you narrated your commute like a documentary, what would the title be?',
  'Which song lyric do you confidently get wrong?',
  'What is your favorite way to make a boring plan more fun?',
  'Which souvenir do you own that has the strangest story?',
  'If our friendship were a board game, what would the main challenge be?',
  'What have you eaten lately that you want to recreate?',
  'Which childhood game deserves an adult comeback?',
  'What is the quirkiest thing you have noticed about your neighborhood?',
  'If your calendar could complain, what would it say?',
  'Which small indulgence feels worth every bit of it?',
  'What would you put in a starter pack for your current era?',
  'Which memory of us has the best background scenery?',
  'What is your most enjoyable form of procrastination?',
  'If we designed matching socks, what pattern would they have?',
  'Which everyday smell should become a candle?',
  'What is the funniest thing you have seen someone carry in public?',
  'Which topic can still send us down a long conversational detour?',
  'If you got an extra hour tonight, how would you spend it?',
  'What low-effort meal never lets you down?',
  'Which piece of technology do you have an oddly personal feud with?',
  'What is your favorite recent example of good luck?',
  'If we created a custom greeting now, what move would it need?',
  'Which shop can you never enter quickly?',
  'What is the funniest way your taste has changed?',
  'Which tiny ritual makes a weekend feel like a weekend?',
  'If your current chapter were a sitcom episode, what would it be called?',
  'What is one thing you would happily taste-test for me?',
  'Which old song takes you directly to a specific place?',
  'What is the most creative excuse you have heard lately?',
  'If we planned a deliberately average day, what would make the itinerary?',
  'Which household item best represents your personality?',
  'What recent moment made you feel like a capable adult?',
  'Which place would you revisit mainly for the food?',
  'What would be your specialty on a very relaxed cooking show?',
  'Which harmless superstition do you half-believe?',
  'What is your favorite thing to do while waiting for someone?',
  'If you could add one feature to group chats, what would it do?',
  'Which old habit of mine do you remember most clearly?',
  'What is the funniest object you have kept for sentimental reasons?',
  'Which recent plan changed for the better at the last minute?',
  'If your week needed a sponsor, what brand would fit?',
  'What is your ideal snack for a long conversation?',
  'Which activity makes time pass suspiciously fast for you?',
  'What ordinary view have you been enjoying lately?',
  'If we invented a holiday, what tiny achievement would it celebrate?',
  'Which character from a show would dominate our next hangout?',
  'What is the most amusing thing you have learned about yourself?',
  'Which restaurant order feels most like you?',
  'If you had a catchphrase this month, what would it be?',
  'What is the best free entertainment you have found recently?',
  'Which shared interest could we happily revive?',
  'What is your current favorite thing to recommend?',
  'If you could borrow one fictional gadget for errands, which one?',
  'Which everyday situation brings out your inner comedian?',
  'What pleasant surprise showed up in your week?',
  'Which memory proves we can make almost anything entertaining?',
  'If you created a fragrance for your hometown, what would it smell like?',
  'What is your most specific pet peeve that stays funny?',
  'Which recent craze makes absolutely no sense to you?',
  'What would your dream vending machine dispense?',
  'If we could repeat one casual hangout, which one would you choose?',
  'Which basic skill do you perform with unreasonable confidence?',
  'What is your favorite oddly satisfying task?',
  'Which item do you always forget when leaving home?',
  'If your recent search history became a lecture, what topic would you teach?',
  'What is the best background music for catching up?',
  'Which harmless debate should we settle once and for all?',
  'What is something fun you want an excuse to do again?',
  'If we made a shared bucket list with only easy items, what goes first?',
  'Which snack would you bring to represent your personality?',
  'What is your favorite piece of useless advice?',
  'Which memory of us still has a missing detail you wonder about?',
  'If your home had a guest attraction, what would visitors come to see?',
  'What is the funniest thing you have done to avoid a task?',
  'Which fictional restaurant would you actually book?',
  'What simple pleasure has been especially good lately?',
  'If you could turn any errand into a sport, which would you choose?',
  'Which fashion choice are you glad never became your signature?',
  'What is your favorite reason to take the scenic route?',
  'Which object nearby would make the best imaginary microphone?',
  'If our conversations had chapter titles, what would this one be?',
  'What small thing always makes a place feel welcoming?',
  'Which meal best matches the way your day is going?',
  'What is the silliest goal you would genuinely enjoy completing?',
  'If you could send me one meme to summarize your month, what would it show?',
  'Which childhood belief still makes you smile?',
  'What is your favorite unexpected pairing of things?',
  'Which room in your home gets the most personality?',
  'If we were neighbors, what would you borrow most often?',
  'What is the nicest thing the weather has done for you lately?',
  'Which tune gets stuck in your head without permission?',
  'What recent moment felt like a scene from a comedy?',
  'If you had to wear one color all week, which would survive?',
  'Which place makes people-watching especially entertaining?',
  'What is the most ambitious sandwich you can imagine?',
  'Which small responsibility do you take oddly seriously?',
  'If we launched a podcast with no expertise, what would we discuss?',
  'What is your favorite thing about an unplanned phone call?',
  'Which old piece of slang should return for one day?',
  'What is a tiny luxury you would pack for a road trip?',
  'If your personality had a screen saver, what would appear?',
  'Which shared outing deserves a playful sequel?',
  'What is the strangest compliment you have enjoyed receiving?',
  'Which menu item do you order before considering anything else?',
  'If we had to communicate only through movie titles, which would you start with?',
  'What daily moment makes you feel pleasantly offline?',
  'Which game show would display your most chaotic side?',
  'What is the best thing you have done on a whim?',
  'If you could install a button for one daily task, what would it handle?',
  'Which forgotten photo would you like to stumble across?',
  'What is your current favorite form of background noise?',
  'Which made-up job would you be surprisingly qualified for?',
  'If your fridge could write a review of you, what would it mention?',
  'What is the most delightful thing you saw this month?',
  'Which place from a story would be perfect for our catch-up?',
  'What is your preferred level of adventure on a free afternoon?',
  'If we traded one everyday talent, which of mine would you take?',
  'Which past trend would you revive for a single party?',
  'What is a snack you associate with good company?',
  'Which recent inconvenience produced a surprisingly good story?',
  'If you had to decorate a room around one joke, which joke?',
  'What is your funniest example of taking the easy route?',
  'Which familiar route holds the most memories for you?',
  'What is one playful plan we could actually do soon?',
  'If this catch-up earned a badge, what would it say?',
  'Which random topic have you fallen into a rabbit hole about?',
  'What tiny talent should be added to your résumé for fun?',
  'Which food aroma can change your plans immediately?',
  'If you could make one mundane object dramatic, which one?',
  'What is the friendliest place you have visited lately?',
  'Which phrase always sounds like something I would say?',
  'What harmless choice took you far too long to make?',
  'If your week were a board game, what would the rules reward?',
  'Which old commercial or jingle still lives in your memory?',
  'What is your favorite thing to discover in a pocket?',
  'Which simple outing feels underrated?',
  'If we entered a themed costume contest, what duo should we be?',
  'What is the funniest reason you have changed your mind?',
  'Which everyday item deserves a better design?',
  'What is your most dependable conversation starter?',
  'If your mood had a texture today, what would it feel like?',
  'Which shared memory would benefit from a dramatic reenactment?',
  'What place have you been meaning to try without making a big plan?',
  'Which small kindness from a stranger recently brightened your day?',
  'If you could assign me a harmless side quest, what would it be?',
  'What is a fun fact about your current routine?',
  'Which household sound deserves its own remix?',
  'What is your preferred reward after finishing something boring?',
  'If we wrote a guide to having fun cheaply, what tip would lead?',
  'Which friend-group role do you accidentally play?',
  'What is the nicest surprise hidden in an ordinary day?',
  'Which fictional pet would fit your life best?',
  'If your wardrobe had one opinion about you, what would it be?',
  'What is your favorite way to make a long journey shorter?',
  'Which small mess tells a good story?',
  'What would you name a boat we definitely do not own?',
  'If you could replay one laugh we shared, which moment comes to mind?',
  'Which part of getting ready takes you comically long?',
  'What is the most charming thing about where you live now?',
  'Which unexpected skill would make our friendship duo unstoppable?',
  'If your lunch had a personality, how would you describe it?',
  'What old interest deserves another afternoon of attention?',
  'Which tiny object do you lose most consistently?',
  'What is your ideal setting for a completely unhurried chat?',
  'If we made a playlist called “Still Friends,” what opens it?',
  'Which recent photo on your phone has the best energy?',
  'What is something easy that always feels like a treat?',
  'Which made-up award would you give yourself this month?',
  'If you could turn one memory into a postcard, which scene would it show?',
  'What is the most entertaining way you have filled an awkward silence?',
  'Which food deserves a festival in its honor?',
  'What quirky local landmark would you proudly show a visitor?',
  'If your shoes could tell one story, where would it begin?',
  'Which hobby looks much easier than it actually is?',
  'What is your favorite sound that is not music?',
  'Which shared plan never happened but still makes you laugh?',
  'If you could outsource one decision every day, which one?',
  'What is a completely ordinary thing you have strong standards about?',
  'Which fictional vehicle would improve our next outing?',
  'What small adventure fits your energy right now?',
  'If we invented a greeting, what should it include?',
  'Which recent moment deserved applause but got none?',
  'What is the funniest thing you have confidently misremembered?',
  'Which snack aisle has the strongest hold on you?',
  'If your week had closing credits, what blooper would play?',
  'What ordinary skill would you demonstrate in a friendly contest?',
  'Which thing in your bag says the most about your life lately?',
  'What new favorite would you like to introduce me to?',
  'If we took the longest possible route somewhere, what stops would we add?',
  'Which day from our friendship felt delightfully unserious?',
  'What is a good reason for us to laugh together soon?',
  'Which imaginary business would we be terrible at running together?',
  'What is the most dramatic name for your current to-do list?',
  'If our next meal had one surprise course, what should appear?',
  'Which everyday rule would you suspend for a fun afternoon?',
  'What recent moment made you stop and take a picture?',
  'If you could give your favorite chair a title, what would it be?',
  'Which trip deserves a remake with better planning?',
  'What is the funniest thing you could teach in three minutes?',
  'If we formed a club today, what oddly specific interest would unite it?',
  'Which small local pleasure feels like an unexpected bonus?',
  'What would make an excellent prize for completing this week?',
  'If you could add a sound effect to my entrance, what would play?',
  'Which recent recommendation are you relieved you ignored?',
  'What is the most cheerful use for an empty afternoon?',
  'If our friendship had a signature dessert, what would it be?',
] as const

export const RECONNECT_FRIENDS_MEANINGFUL = [
  'What part of your life would you most enjoy bringing me up to date on?',
  'When have you felt especially supported by our friendship?',
  'What quality in me has become clearer to you over time?',
  'Which shared memory says something true about who we are as friends?',
  'What kind of encouragement is most useful to you these days?',
  'How has your idea of a good friendship changed recently?',
  'What do you appreciate about how we pick up after time apart?',
  'Which interest still makes you feel most energized?',
  'What has been taking up the best kind of space in your life?',
  'When does staying in touch feel easiest for you?',
  'What is something you have learned since we last had time to talk?',
  'Which moment in our history showed you that I was in your corner?',
  'What are you making more room for in this season?',
  'What kind of response from a friend makes your good news feel fully received?',
  'What part of your everyday life feels most meaningful now?',
  'Which value has been guiding more of your choices lately?',
  'What do you hope our friendship always makes space for?',
  'When have we brought out a good side of each other?',
  'What kind of check-in feels caring without feeling demanding?',
  'Which recent change has taught you something useful about yourself?',
  'What is one way your priorities have become clearer?',
  'How can a friend make you feel remembered between conversations?',
  'What about our connection feels easy to trust?',
  'Which ordinary memory with me carries unexpected warmth?',
  'What kind of support do you enjoy giving?',
  'What have you grown more confident about lately?',
  'Which tradition between friends matters more than its size suggests?',
  'What would help us make future catch-ups feel natural?',
  'When do you feel most understood in conversation?',
  'What is something about your current life you are glad to share?',
  'Which past version of us would be happiest to see us talking now?',
  'What have your newer routines revealed about what matters to you?',
  'How do you recognize dependable friendship?',
  'What is one thing you admire about the life I have built?',
  'Which shared experience helped shape your view of friendship?',
  'What type of invitation feels easiest for you to accept?',
  'Which recent change has made your next chapter feel more open?',
  'How have you become a different kind of friend over time?',
  'What do you remember about how we first became comfortable together?',
  'Which part of your world would you like me to know better?',
  'What kind of company feels restorative to you now?',
  'What is something our friendship taught you without either of us planning it?',
  'Which accomplishment would you like your friends to notice more?',
  'How do you prefer someone to show they are listening?',
  'What part of your personality has had more room to grow lately?',
  'Which conversation between us stayed with you in a good way?',
  'What makes reconnecting feel worthwhile to you?',
  'How do your closest friendships fit into your life now?',
  'What is one thing you hope I understand about your current pace?',
  'Which strength have you seen develop in me?',
  'What sort of shared time leaves you feeling genuinely refreshed?',
  'When have you felt proud of how we handled a difference?',
  'What has made you feel connected to people lately?',
  'Which piece of our shared history still influences you positively?',
  'What does mutual support look like in an ordinary week?',
  'How has your capacity for friendship shifted with your responsibilities?',
  'What is something you are enjoying becoming better at?',
  'Which kind gesture from a friend do you tend to remember?',
  'What do you value about friendships that survive changing circumstances?',
  'When do you feel most comfortable asking for company?',
  'What is one lesson your life has taught you about showing up?',
  'Which part of our friendship would you gladly carry into the future?',
  'How can friends respect busy seasons while staying present?',
  'What has surprised you about the person you are becoming?',
  'What do you think we have always understood about each other?',
  'Which small act makes you feel appreciated by a friend?',
  'What topic do you wish we had more time to explore together?',
  'How do you know when a friendship has room to evolve?',
  'What is something you are quietly excited about?',
  'Which memory reminds you that we work well as a team?',
  'What does being a thoughtful friend mean to you today?',
  'How would you describe the role humor plays in our connection?',
  'What part of your life feels pleasantly settled?',
  'Which of my choices have you enjoyed watching from the sidelines?',
  'What kind of plans help you feel close without draining your energy?',
  'When have you recently felt proud of someone you care about?',
  'What do you appreciate about friends who knew earlier versions of you?',
  'Which shared interest could deepen our connection now?',
  'What has helped you feel more at home in your present life?',
  'How do you like to be included when you are busy?',
  'What is a meaningful compliment a friend could give you?',
  'Which challenge helped you recognize your own resourcefulness?',
  'What do you hope friends feel when they spend time with you?',
  'How has your understanding of loyalty become more nuanced?',
  'What part of reconnecting feels familiar in the best way?',
  'Which recent experience changed what you pay attention to?',
  'What is one way we have made life lighter for each other?',
  'When does advice feel welcome rather than intrusive to you?',
  'What have you learned about balancing friendship with everything else?',
  'Which aspect of your current routine reflects your values?',
  'What do you think makes our conversations distinct?',
  'How can a friend best acknowledge a long gap in contact?',
  'What is something you have come to appreciate more with time?',
  'Which choice lately has felt especially true to you?',
  'What does a generous interpretation of a friend look like?',
  'When have we made each other feel welcome?',
  'What personal interest would you like more people to ask about?',
  'How do you prefer to share an achievement that matters to you?',
  'What is one quality you rely on in long-term friends?',
  'Which part of your story are you viewing with fresh understanding?',
  'What feels worth protecting in the way we relate?',
  'How has your definition of being available changed?',
  'What is something you would enjoy learning alongside a friend?',
  'Which shared memory captures our sense of humor best?',
  'What helps you feel that a conversation is balanced?',
  'When have you benefited from a friend believing in your ability?',
  'What part of life are you approaching with more patience?',
  'How can we make appreciation more visible in friendship?',
  'What is one thing our time apart has helped you notice?',
  'Which kind of gathering makes connection happen naturally for you?',
  'What do you value now that you did not prioritize before?',
  'How would you like old friends to meet the person you are today?',
  'What is something you enjoy remembering about our early friendship?',
  'Which form of practical help feels especially thoughtful?',
  'What makes a friendship feel spacious rather than distant?',
  'When have you seen me handle something in a way you respected?',
  'What part of your current chapter deserves more celebration?',
  'How do you stay connected to people across different lifestyles?',
  'What is a sign that someone values your perspective?',
  'Which lesson from a friendship has served you elsewhere?',
  'What do you appreciate about who you were when we met?',
  'How has your way of expressing care changed?',
  'What is one experience you would enjoy sharing with me now?',
  'Which recent decision gave you more breathing room?',
  'What does meaningful consistency look like between friends?',
  'When has laughter helped us understand each other?',
  'What are you more willing to prioritize these days?',
  'How can friends make room for each other’s changing interests?',
  'What is something you have noticed about my growth?',
  'Which place in your life currently gives you belonging?',
  'What kind of message brightens your day without requiring a response?',
  'How do you decide which friendships deserve renewed attention?',
  'What is one way you have learned to offer support more thoughtfully?',
  'Which moment between us felt simple but significant?',
  'What do you hope to make more time for with friends?',
  'How does being known for a long time feel valuable?',
  'What is something you respect about how we are different?',
  'Which recent experience made you grateful for your community?',
  'What does friendship look like when life is going well?',
  'When do you find it easiest to express appreciation?',
  'What part of your present self would surprise me most?',
  'How can we be better witnesses to each other’s progress?',
  'What is a shared memory you interpret differently now?',
  'Which friendship habit would you like to practice more often?',
  'What do you need from a catch-up for it to feel satisfying?',
  'How have changes in your life affected what you can offer socially?',
  'What is something you are grateful we never took too seriously?',
  'Which of your values becomes clearest in friendship?',
  'What makes you feel invited rather than obligated?',
  'When have you felt genuinely cheered on by me?',
  'What part of your week would you enjoy sharing with someone?',
  'How can friendship support ambition without adding pressure?',
  'What is one thing you now understand about my perspective?',
  'Which old memory has gained meaning as you have changed?',
  'What do you appreciate about a friend remembering the details?',
  'How has your social energy evolved over the years?',
  'What is something current that connects to a dream you once had?',
  'Which kind of honesty strengthens friendship without making it heavy?',
  'What makes a reunion feel comfortable from the first minute?',
  'When have you seen a friendship adapt well to change?',
  'What would you like us to be curious about together?',
  'How do you want friends to respond when your plans shift?',
  'What is one way our friendship expanded your world?',
  'Which responsibility has changed you in a way you value?',
  'What do you enjoy about sharing ordinary updates?',
  'How can friends celebrate growth that is not visible?',
  'What is something I introduced you to that still matters?',
  'Which part of being a friend comes most naturally to you?',
  'What helps you trust that distance is not disinterest?',
  'When did you last feel pleasantly understood without much explanation?',
  'What is one way your current life better suits you?',
  'How would you describe the care beneath our teasing?',
  'Which friendship expectation has become more realistic for you?',
  'What do you hope to remember about this phase of your life?',
  'How can friends make important milestones feel personal?',
  'What is a quality we share that helps us connect?',
  'Which supportive words tend to stay with you?',
  'What makes you feel comfortable sharing good news?',
  'When has a friend helped you see an option you missed?',
  'Which area of your life currently matches your convictions?',
  'How do you like friendships to recover their rhythm?',
  'What is something from our past you understand more kindly now?',
  'Which type of shared project could bring us closer?',
  'What do you notice when someone is making a real effort?',
  'How has your relationship with free time changed?',
  'What is one thing you would like to thank this friendship for?',
  'Which choice helped you create a life that fits better?',
  'What makes encouragement feel believable to you?',
  'When do you most appreciate having long-standing friends?',
  'What is a gentle way friends can hold each other accountable?',
  'How do you like to mark a fresh start?',
  'What part of our connection has aged especially well?',
  'Which new responsibility has revealed a strength in you?',
  'What do you find easier to talk about than you once did?',
  'How can we keep curiosity alive when we think we know each other?',
  'What is something about friendship you learned through experience?',
  'Which moment recently made you feel useful in a good way?',
  'What helps a conversation feel like shared discovery?',
  'When has our friendship given you a sense of continuity?',
  'What is one thing you admire in the way your friends differ?',
  'How do you balance spontaneity with needing notice?',
  'What part of your life would benefit from more companionship?',
  'Which kind of memory do you want us to create next?',
  'What do you value about being able to resume a conversation?',
  'How has your idea of success become more personal?',
  'What is something a friend noticed about you before you did?',
  'Which of our differences has taught you something useful?',
  'What makes you feel supported when no solution is needed?',
  'When do you feel most able to be generous with your attention?',
  'What is a part of your life you are tending carefully?',
  'How can old friends make room for new chapters?',
  'What do you think has kept our connection recognizable?',
  'Which recent conversation left you feeling energized?',
  'What is one way you want to invest in community?',
  'How do you like someone to remember an important day?',
  'What part of our shared past still makes you feel understood?',
  'Which quiet achievement are you glad you pursued?',
  'What does being present for a friend mean when time is limited?',
  'When has someone’s confidence in you made a difference?',
  'What is a value you hope your friendships reinforce?',
  'How would you like us to handle future stretches of silence?',
  'What do you appreciate about the pace of this conversation?',
  'Which personal change has made your relationships better?',
  'What makes you feel like your effort is reciprocated?',
  'When have we shared a silence that still felt companionable?',
  'What is something you hope your friends feel free to tell you?',
  'How do shared memories help you understand your own growth?',
  'What part of your life now feels more intentional?',
  'Which form of recognition matters more to you than praise?',
  'What do you enjoy about friends having separate worlds?',
  'How can a catch-up honor both the past and the present?',
  'What is one way I have made you feel accepted?',
  'Which new perspective has improved how you relate to people?',
  'What makes a promise between friends feel dependable?',
  'When do you prefer company over advice?',
  'What is something you are building slowly and proudly?',
  'How would you describe the friendship pace that suits you now?',
  'What do you hope we keep learning about each other?',
  'Which memory reminds you of a strength we share?',
  'What is a sign that a friendship can handle honest difference?',
  'How has your way of receiving help evolved?',
  'What part of reconnecting has felt most encouraging today?',
  'When has a friend made your everyday life easier?',
  'What is one contribution you value making to a friendship?',
  'Which shared value do you think quietly anchors us?',
  'What helps you feel considered when plans are being made?',
  'How do you want friendship to fit around your current commitments?',
  'Which quality in my life would you encourage me to protect?',
  'Which moment showed you that our friendship could stretch?',
  'What does thoughtful curiosity sound like to you?',
  'When do you feel most comfortable offering a different opinion?',
  'What is one way time has made you gentler with people?',
  'How can friends notice each other without monitoring each other?',
  'What do you appreciate about the person you are around me?',
  'Which part of your support system works especially well?',
  'What makes it easier to reconnect after missing milestones?',
  'When has friendship helped you enjoy a transition?',
  'What is something you want to approach with shared enthusiasm?',
  'How do you distinguish closeness from constant contact?',
  'What do you think we give each other permission to be?',
  'Which recent choice reflects how much you have grown?',
  'What is a memory of being welcomed by friends that stays vivid?',
  'How can we better appreciate the effort behind each other’s lives?',
  'What part of friendship feels more important as life gets fuller?',
  'When have you learned something valuable by listening to a friend?',
  'What is one way you hope our lives keep overlapping?',
  'Which interest of mine have you enjoyed seeing develop?',
  'What makes a shared plan feel worth protecting?',
  'How has your idea of fun become more authentic?',
  'What do you want friends to understand about your way of caring?',
  'Which ordinary act of friendship feels especially meaningful now?',
  'What is something good that grew during our time apart?',
  'When does reminiscing feel connecting rather than stuck in the past?',
  'How can we encourage each other without setting expectations?',
  'What part of your current identity feels newly comfortable?',
  'Which moment made you glad we became friends?',
  'What is one thing you would like us to celebrate together?',
  'How do you prefer a friend to check an assumption?',
  'What do you notice about friendships where you can relax?',
  'Which life change has made your time feel more precious?',
  'What is a way our friendship has made you feel less alone?',
  'When has someone respected your pace in a meaningful way?',
  'How can friends keep shared interests alive as tastes change?',
  'What do you hope this renewed connection adds to your life?',
  'Which quality would you like us to bring into our next chapter?',
  'What is one present-day detail you want me to remember?',
  'How would you like us to make room for future good news?',
  'What part of your day helps you feel most connected to yourself?',
  'Which friendship experience has made you more considerate?',
  'What do you hope people recognize about the effort you are making?',
  'How has your idea of a welcoming space changed?',
  'What is one way you have become more present with friends?',
  'Which shared value could guide how we stay connected?',
  'What makes a thoughtful invitation feel personal to you?',
  'When has a friend helped you appreciate your own progress?',
  'What is something about your current community that gives you hope?',
  'How would you like friendship to add ease to your life?',
  'Which everyday choice helps you become the person you want to be?',
  'What do you want to carry forward from this catch-up?',
  'How can we make our next connection easier to begin?',
] as const

export const RECONNECT_FRIENDS_DEEP = [
  'What kind of closeness feels sustainable for you in this season?',
  'How would you like our friendship to adapt to who we are now?',
  'What boundary helps you stay generous without becoming depleted?',
  'When tension appears, what helps you remain open to repair?',
  'What need in friendship have you become better at naming?',
  'How can we acknowledge distance without deciding who was at fault?',
  'What part of your identity has changed how you relate to old friends?',
  'Which expectations of friendship are you reconsidering?',
  'What does a respectful disagreement require from both people?',
  'How do you want a friend to respond when you ask for space?',
  'What would make our renewed connection feel reciprocal?',
  'Which version of yourself no longer needs to guide this friendship?',
  'How can we make honesty safer for each other?',
  'What signals tell you that a boundary has been understood?',
  'When is repair more important to you than agreement?',
  'What kind of support can you realistically offer right now?',
  'How has change altered what you expect from long-term friendship?',
  'What does accountability look like without shame?',
  'Which pattern would you like to approach differently with friends?',
  'How can we stay connected without assuming constant access?',
  'What part of being known by an old friend feels complicated?',
  'When do you need listening instead of reassurance?',
  'What would help you speak up sooner when something feels off?',
  'How do you decide whether a strained friendship can be renewed?',
  'What does emotional safety mean between friends?',
  'Which change in you deserves to be met without comparison to the past?',
  'How can a friend honor a limit they do not fully understand?',
  'What makes an apology feel grounded rather than performative?',
  'When has giving a friendship more space protected it?',
  'What would you like us to release from an earlier chapter?',
  'How can we discuss unmet expectations without keeping score?',
  'What kind of consistency feels caring rather than controlling?',
  'Which friendship role are you ready to stop automatically taking?',
  'How do you recognize when you are overextending socially?',
  'What does mutual effort look like when capacities differ?',
  'When do you prefer directness over gentleness?',
  'What part of your growth might an old friend easily miss?',
  'How can we leave room for answers that are still forming?',
  'What would a fair reset of our friendship involve?',
  'Which assumption about you would you like me to retire?',
  'How do you want us to navigate different communication habits?',
  'What makes feedback from a friend easier to receive?',
  'When has a boundary strengthened rather than weakened a connection?',
  'What are you learning about the limits of your availability?',
  'How can friends repair impact even when harm was unintended?',
  'What does choosing this friendship look like in practical terms?',
  'Which difference between us deserves more thoughtful handling?',
  'How do you want your changing priorities to be respected?',
  'What would help us be honest without making every issue urgent?',
  'When is it useful to revisit an old misunderstanding?',
  'What kind of reassurance helps without creating obligation?',
  'How has your sense of belonging evolved?',
  'What does it mean to let a friendship become something new?',
  'Which personal limit has improved the way you show up?',
  'How can we tell each other when our capacity is low?',
  'What would make difficult conversations feel more collaborative?',
  'When do expectations become pressure for you?',
  'What part of yourself are you practicing showing more accurately?',
  'How should a friend respond after realizing they misunderstood you?',
  'What does trust need after a period of distance?',
  'Which old dynamic would you not want us to recreate?',
  'How can care remain visible during disagreement?',
  'What is one need you prefer people not to guess?',
  'When do you know a conversation needs a pause?',
  'What would a respectful repair attempt sound like to you?',
  'How has your tolerance for ambiguity in friendship changed?',
  'Which part of reconnecting requires the most patience?',
  'What does reciprocity mean when support cannot be equal every day?',
  'How can we avoid treating past familiarity as present-day knowledge?',
  'What expectation helps you feel secure without feeling restricted?',
  'When has being clear prevented resentment for you?',
  'What might we need to relearn about each other?',
  'How do you prefer to address a small hurt before it grows?',
  'What does respecting a no look like beyond accepting the word?',
  'Which aspect of your life now requires firmer boundaries?',
  'How can friendship hold both care and independence?',
  'What would help you trust that honesty will not be punished?',
  'When does a request begin to feel like a demand?',
  'What are you no longer willing to perform for belonging?',
  'How can we recognize effort without overlooking impact?',
  'What does a second chance need in order to be healthy?',
  'Which change in your worldview affects how you connect?',
  'How would you like a friend to raise a concern with you?',
  'What makes room for accountability without defining someone by a mistake?',
  'When is preserving a difference better than resolving it?',
  'What part of friendship do you want to approach more intentionally?',
  'How can we be dependable without promising more than we can give?',
  'What does being seen accurately require from a friend?',
  'Which past expectation are you glad you outgrew?',
  'How do you handle closeness when your energy changes unpredictably?',
  'What would make it easier to say “not now” between us?',
  'When do you need curiosity before an explanation?',
  'What does repair look like if neither person meant harm?',
  'How can friends negotiate different needs for contact?',
  'Which part of your identity needs less explanation these days?',
  'What would help us notice resentment before it settles in?',
  'How do you want a friend to respond to a changed mind?',
  'What is the difference between privacy and distance for you?',
  'When has changing an expectation preserved your peace?',
  'What does a friendship need to survive a major life transition?',
  'How can we make space for disappointment without dramatizing it?',
  'Which kind of conflict response are you trying to unlearn?',
  'What would it mean for our friendship to feel current?',
  'How do you know when an apology needs follow-through?',
  'What part of your future do you want friendships to support?',
  'When is silence restful, and when does it feel disconnecting?',
  'What does it take for you to revise an impression of someone?',
  'How can friends ask for change without threatening the bond?',
  'Which boundary do you wish people treated as ordinary?',
  'What would balanced emotional labor look like between us?',
  'How has your relationship with conflict matured?',
  'When do you feel responsible for more than is actually yours?',
  'What does forgiveness mean if closeness changes afterward?',
  'How can we talk about impact without arguing over intention?',
  'Which friendship need has become less important to you?',
  'What would help us avoid slipping into outdated roles?',
  'How do you distinguish patience from avoiding a necessary conversation?',
  'When does compromise feel mutual rather than one-sided?',
  'What part of your voice are you learning to trust?',
  'How can a friend support you without taking over?',
  'What does rebuilding ease require after awkwardness?',
  'Which unspoken rule about friendship would you challenge?',
  'How would you like us to respond if one person feels overlooked?',
  'What makes it possible to disagree without questioning care?',
  'When have you learned that good intentions were not enough?',
  'What is one way you protect your autonomy in close friendships?',
  'How can we name unequal effort without reducing friendship to a transaction?',
  'What would a more mature version of our connection include?',
  'Which need do you find easiest to minimize?',
  'How do you want to be approached when you seem withdrawn?',
  'What does giving someone grace stop short of excusing?',
  'When can nostalgia make it harder to see a friend clearly?',
  'What are you learning about asking directly for what you want?',
  'How can we respect different definitions of closeness?',
  'What would help a hard truth land with care?',
  'Which part of friendship deserves more negotiation than assumption?',
  'How do you decide what belongs in a repair conversation?',
  'What does healthy interdependence look like to you?',
  'When is reassurance useful, and when do you need action?',
  'What future change would you want our friendship to weather well?',
  'How can we keep disappointment from becoming a verdict?',
  'Which habit makes you feel less available than you want to be?',
  'What would make room for both our perspectives during conflict?',
  'How do you want friends to respond to your evolving beliefs?',
  'What does consent look like in everyday emotional conversations?',
  'When do you need time before offering a thoughtful answer?',
  'What is a responsibility in friendship you willingly choose?',
  'How can we clarify expectations without making a contract out of care?',
  'Which part of yourself has become more protected with experience?',
  'What would help us separate a bad moment from the whole friendship?',
  'How do you know when a friendship is asking you to grow?',
  'When does support feel empowering rather than rescuing?',
  'What does making amends require beyond saying sorry?',
  'How can friends stay curious when values diverge?',
  'Which friendship pattern are you most proud to have changed?',
  'What would help you receive care without feeling indebted?',
  'How do you prefer to revisit a conversation that ended poorly?',
  'What is the role of boundaries in keeping affection genuine?',
  'When have you mistaken familiarity for understanding?',
  'How can we avoid asking one conversation to fix everything?',
  'What part of growing apart can be acknowledged with kindness?',
  'Which conditions help you take responsibility without becoming defensive?',
  'What would make our friendship more resilient to misunderstandings?',
  'How do you decide when to explain yourself and when to let something stand?',
  'What does a respectful change of plans require?',
  'When do you want a friend to challenge you gently?',
  'How can we honor the histories we do not fully share?',
  'What part of your life direction feels important for friends to respect?',
  'Which forms of closeness feel energizing rather than consuming?',
  'What would help us recognize when joking crosses a line?',
  'How do you want repair to account for repeated patterns?',
  'When is letting go of an expectation an act of care?',
  'What does it mean to be loyal without abandoning yourself?',
  'How can a friendship welcome changed circumstances without resentment?',
  'Which boundary is easier for you to honor than to express?',
  'What would you need before rebuilding trust around reliability?',
  'How do you want a friend to handle information you share selectively?',
  'When does problem-solving make you feel less heard?',
  'What is one way you are redefining connection for yourself?',
  'How can we be honest about capacity before plans become disappointments?',
  'What does a fair response to accidental hurt look like?',
  'Which part of your past do you want friends to stop using as shorthand?',
  'How would you like us to navigate different levels of social energy?',
  'What makes a request feel safe to decline?',
  'When has a friendship benefited from clearer language?',
  'How can we allow each other to be inconsistent while still seeking reliability?',
  'What does growth ask you to risk in friendship?',
  'Which expectation feels worth stating before it becomes frustration?',
  'What would help us disagree about a memory respectfully?',
  'How do you recognize care when it arrives in an unfamiliar form?',
  'When is it important to say what you cannot provide?',
  'What part of friendship repair should never be rushed?',
  'How can friends respond well to a newly stated boundary?',
  'What does maintaining dignity look like during conflict?',
  'Which kind of misunderstanding is hardest for you to correct?',
  'What would make a conversation about needs feel less personalizing?',
  'How do you want us to account for differences in resources or time?',
  'When does checking in become checking up on someone?',
  'What is one way your standards for friendship have become healthier?',
  'How can we make room for regret without demanding self-punishment?',
  'What does it mean to witness change without evaluating it?',
  'Which part of your independence do you most want friends to celebrate?',
  'What would help you name a disappointment while it is still small?',
  'How do you distinguish a rough season from a mismatched friendship?',
  'When has a limit allowed you to show up more sincerely?',
  'What does it take to trust a repaired pattern?',
  'How can we stay respectful when one person needs more distance?',
  'Which story about our friendship might deserve an update?',
  'What would you want us to do if old frustrations resurface?',
  'How do you feel about friendships that become less frequent but more deliberate?',
  'When does vulnerability feel invited rather than expected?',
  'What is a way to offer care without requiring a response?',
  'How can we avoid turning boundaries into rejection stories?',
  'What does being accountable to a friendship mean to you?',
  'Which part of your communication style are you refining?',
  'What would help us handle competing needs without choosing a winner?',
  'How do you want your no to be received by a close friend?',
  'When is a friendship conversation better held in person?',
  'What does mutual respect require when choices differ?',
  'How can we repair a missed moment without exaggerating its meaning?',
  'Which aspect of your life calls for more relational flexibility?',
  'What would a friendship designed around our actual lives look like?',
  'How do you prefer to hear that something you did had an impact?',
  'When does checking an assumption feel especially important?',
  'What is one way you want to become more trustworthy as a friend?',
  'How can we talk about imbalance without measuring every gesture?',
  'What does emotional privacy allow you to preserve?',
  'Which former version of you deserves understanding, not reenactment?',
  'What would help us accept that some needs may be met elsewhere?',
  'How do you want friendship to respond when your worldview shifts?',
  'When is a pause part of repair rather than avoidance?',
  'What does it mean to take someone seriously without agreeing?',
  'How can friends hold hope for each other without prescribing a path?',
  'Which kind of apology helps you feel your experience was understood?',
  'What would allow this friendship to be both rooted and flexible?',
  'How do you recognize when you are seeking reassurance indirectly?',
  'When does helping begin to interfere with someone’s agency?',
  'What part of reconnecting asks us to tolerate uncertainty?',
  'How can we be careful with each other’s sensitive topics?',
  'What does a boundary need in order to remain compassionate?',
  'Which change in your life has altered your sense of responsibility?',
  'What would help us move forward without rewriting the past?',
  'How do you want a friend to respond when they cannot meet a need?',
  'When can naming a pattern create relief?',
  'What does a friendship gain from allowing separate identities?',
  'How can we prevent affection from becoming entitlement?',
  'Which part of your future feels most important to choose for yourself?',
  'What would make it easier to ask before offering advice?',
  'How do you want us to handle humor around vulnerable subjects?',
  'When does being flexible start to cost you too much?',
  'What is one way you can honor your needs while staying connected?',
  'How can friends acknowledge different memories of the same event?',
  'What does patience look like when change is still underway?',
  'Which relationship skill are you practicing more deliberately?',
  'What would help us recover if expectations are missed again?',
  'How do you decide which discomfort is worth working through?',
  'When is clarity kinder than preserving harmony?',
  'What does shared responsibility for connection mean in practice?',
  'How can we protect room for spontaneity and consent at once?',
  'Which way of being supported no longer fits you?',
  'What would make a future-facing friendship feel hopeful?',
  'How do you want to be reminded of a commitment you forgot?',
  'When does context explain behavior without excusing it?',
  'What is one expectation you want to communicate more openly?',
  'How can we distinguish care from trying to manage each other?',
  'What does it take for you to believe a pattern can change?',
  'Which part of your life needs friendship to be uncomplicated?',
  'What would help us preserve warmth while setting a firm limit?',
  'How do you want friends to respond when you choose differently than before?',
  'When is acceptance more useful than encouragement?',
  'What does a meaningful reset leave intact?',
  'How can we create a friendship that makes room for becoming?',
  'Which of your needs is easiest to honor when it is spoken plainly?',
  'What would let us address friction before it changes the tone?',
  'How do you balance protecting peace with pursuing repair?',
  'When does an explanation support connection, and when is it unnecessary?',
  'What is one way our friendship could become more equitable?',
  'How can we offer each other options instead of pressure?',
  'What does closeness look like when neither person has to demonstrate it?',
  'Which assumption about long friendship creates the most trouble?',
  'What would help us keep care central during a hard conversation?',
  'How do you want our friendship to reflect the lives we are choosing?',
  'What kind of repair respects both urgency and readiness?',
  'How can we name a shift in closeness without treating it as failure?',
  'Which personal change asks your friends to learn a new way of relating?',
  'What would help us tell the difference between concern and intrusion?',
  'How do you want friendship to accommodate seasons of limited capacity?',
  'When does a familiar role keep you from responding authentically?',
  'What does it mean to respect a boundary that changes with context?',
  'How can we respond if one of us wants a different kind of friendship?',
  'Which expectations are best discussed before making plans?',
  'What would allow disagreement to deepen understanding instead of distance?',
  'How do you know when you are ready to return to an unfinished conversation?',
  'When can accepting a limitation become a form of repair?',
  'What does responsible honesty leave space for?',
  'How can we keep mutual care from depending on identical effort?',
  'Which part of rebuilding connection should remain voluntary?',
  'What would help you feel free to revise what you previously asked for?',
  'How do you want us to respond when circumstances change an agreement?',
  'When does a friendship need a new rhythm instead of a solution?',
] as const
