export const RECONNECT_COLLEAGUES_LIGHT = [
  "What small win has brightened your workday lately?",
  "Which part of your routine helps you settle into the day?",
  "What is your favorite way to begin a team catch-up?",
  "Which everyday task do you find oddly satisfying?",
  "What kind of break leaves you feeling refreshed?",
  "Which work tool would you happily give a personality to?",
  "What harmless workplace mystery still makes you curious?",
  "Which meeting snack deserves a permanent invitation?",
  "What song title best describes your inbox today?",
  "Which office supply would win an award for usefulness?",
  "What tiny convenience makes your workday noticeably better?",
  "Which background sound helps you find your rhythm?",
  "What is your most reliable cure for an afternoon slump?",
  "Which day of the week best matches your working style?",
  "What would make a team break feel genuinely fun?",
  "Which simple task do you unexpectedly enjoy completing?",
  "What is one cheerful thing you noticed at work recently?",
  "Which fictional workplace would be amusing to visit for an hour?",
  "What name would you give our team mascot?",
  "Which emoji has earned a place in your work vocabulary?",
  "What is your ideal length for a quick catch-up?",
  "Which warm drink best matches a focused morning?",
  "What low-key ritual helps you shift into work mode?",
  "Which desk item would you rescue first from a move?",
  "What is a surprisingly useful shortcut you know?",
  "Which kind of weather makes concentration easiest for you?",
  "What would your current project be called as a film?",
  "Which color feels most like a productive day?",
  "What is your favorite reason to step away from the screen?",
  "Which harmless trend would improve workplace chat?",
  "What is the nicest view you have worked beside?",
  "Which everyday sound signals that work is going well?",
  "What makes a virtual meeting feel more human to you?",
  "Which kind of team celebration feels easiest to enjoy?",
  "What is a good two-minute reset between tasks?",
  "Which word would you choose for today's team energy?",
  "What is the best use of an unexpected free ten minutes?",
  "Which type of puzzle wakes up your brain?",
  "What would improve the shared kitchen by one percent?",
  "During which season does your focus feel most natural?",
  "What pleasant detail makes a workspace feel welcoming?",
  "Which everyday technology still feels a little magical?",
  "What is your favorite kind of low-stakes team challenge?",
  "Which lunch format makes conversation flow most easily?",
  "What playful award should our team invent?",
  "Which common phrase would you retire from meetings?",
  "What is a work-appropriate superpower you would borrow for today?",
  "Which tiny accomplishment deserves more celebration?",
  "What is your preferred signal that a meeting is wrapping up?",
  "Which object near you has the most interesting story?",
  "What is a simple way colleagues can make Mondays lighter?",
  "Which kind of calendar reminder actually makes you smile?",
  "What would be on a soundtrack for quiet focus?",
  "Which shared activity requires almost no planning but usually works?",
  "What is a surprisingly good conversation starter at work?",
  "Which fictional gadget would make collaboration easier?",
  "What is your favorite way to mark the end of a busy week?",
  "Which room feature helps you feel comfortable speaking up?",
  "What quick game could fit into a five-minute pause?",
  "Which ordinary work moment deserves a better name?",
  "What is something nearby that reliably lifts your mood?",
  "Which kind of note do you enjoy receiving from a teammate?",
  "What makes an introduction feel relaxed rather than formal?",
  "Which meeting would improve with a change of scenery?",
  "What is your ideal background for a video call?",
  "Which snack has the best concentration-to-crunch ratio?",
  "What is a practical skill you enjoy using at work?",
  "Which small workplace tradition would you gladly revive?",
  "What is your favorite way to organize a fresh page?",
  "Which everyday question helps people reconnect quickly?",
  "What makes a team photo feel less awkward?",
  "Which part of a project feels most like solving a puzzle?",
  "What is the best compliment a spreadsheet could receive?",
  "Which meeting role would make a funny board-game character?",
  "What harmless debate could our team settle over lunch?",
  "Which punctuation mark best represents your work style?",
  "What is the most useful thing within arm's reach?",
  "Which kind of update is satisfying to share?",
  "What small upgrade would make your usual workspace nicer?",
  "Which team ritual would translate well to remote work?",
  "What is your favorite way to make a long task feel shorter?",
  "Which simple question gets your creative thinking started?",
  "What would a postcard from our team say?",
  "Which workday moment deserves its own theme music?",
  "What is an underrated reason to use a sticky note?",
  "Which kind of list feels most rewarding to finish?",
  "What would you put in a team time capsule from this month?",
  "Which harmless distraction sometimes leads to a good idea?",
  "What is the friendliest way to say a meeting can end early?",
  "Which recent task had an unexpectedly enjoyable moment?",
  "What is your preferred way to share a quick thought?",
  "Which familiar work object would make the best cartoon sidekick?",
  "What low-effort activity could improve a team afternoon?",
  "Which kind of workspace lighting helps you feel alert?",
  "What is the simplest recipe for a pleasant check-in?",
  "Which recurring task would you rename to sound more exciting?",
  "What would make a team noticeboard worth checking?",
  "Which everyday achievement should earn a tiny trophy?",
  "What is your favorite way to welcome someone back?",
  "Which non-work topic reliably creates easy conversation?",
  "What is a fun use for an empty whiteboard?",
  "Which part of planning feels most energizing to you?",
  "What would your laptop say after a long week?",
  "Which simple gesture makes a shared space feel considerate?",
  "What is the best kind of surprise in a workday?",
  "Which everyday item makes an excellent makeshift pointer?",
  "What is a lighthearted title for your current to-do list?",
  "Which small choice helps a meeting start smoothly?",
  "What is your favorite way to make routine work more interesting?",
  "Which team moment would look best as a comic strip?",
  "What is a work tip that sounds obvious but genuinely helps?",
  "Which kind of message is easiest for you to answer quickly?",
  "What would be a delightful name for a focus room?",
  "Which everyday work item has the best design?",
  "What is a good sign that a group is comfortable together?",
  "Which quick stretch belongs in the unofficial workday handbook?",
  "What is your favorite way to add personality to a workspace?",
  "Which ordinary workplace scene would make a charming postcard?",
  "What is a fun category for a team trivia round?",
  "Which kind of brainstorm prompt gets everyone talking?",
  "What would make the perfect fifteen-minute team break?",
  "Which useful phrase deserves more airtime in group chats?",
  "What is the most satisfying thing to tidy up digitally?",
  "Which small sound effect should play when a task is finished?",
  "What is a pleasant alternative to asking if everyone is busy?",
  "Which workday habit makes time feel well spent?",
  "What would our team café be famous for?",
  "Which kind of diagram do you enjoy seeing come together?",
  "What is a cheerful name for a shared ideas folder?",
  "Which easy question reveals how someone likes to collaborate?",
  "What is your favorite way to make a new colleague feel included?",
  "Which minor inconvenience could inspire a funny invention?",
  "What would you choose as a friendly team greeting?",
  "Which part of your day could use a two-minute celebration?",
  "What is the most creative use you have seen for a whiteboard?",
  "Which type of task pairs best with a good playlist?",
  "What is one thing that makes a shared document inviting?",
  "Which meeting format feels surprisingly lively?",
  "What would make an ordinary Tuesday memorable in a good way?",
  "Which workplace object would tell the best stories?",
  "What is your go-to way to make a request sound warm?",
  "Which tiny piece of good news is worth sharing today?",
  "What is a fun name for an informal team catch-up?",
  "Which low-pressure activity helps people learn names?",
  "What would you add to a five-minute desk picnic?",
  "Which task gives you the clearest sense of progress?",
  "What is the easiest way to brighten a group chat?",
  "Which kind of shared playlist would suit this team?",
  "What useful object deserves a more glamorous reputation?",
  "Which workday moment makes a good excuse to pause?",
  "What is a playful question you wish meetings opened with?",
  "Which team habit would make a good sticker slogan?",
  "What is the best thing about a freshly cleared desk?",
  "Which ordinary task becomes better when done together?",
  "What would a weather forecast for today's workload say?",
  "Which simple choice makes online collaboration more pleasant?",
  "What is an amusing name for a difficult-but-manageable task?",
  "Which part of wrapping up work feels most satisfying?",
  "What kind of team outing works for many energy levels?",
  "Which small courtesy do you always notice?",
  "What is your favorite way to share a useful discovery?",
  "Which object would represent calm during a hectic day?",
  "What is a good question for restarting a paused conversation?",
  "Which routine update could be made more engaging?",
  "What would a team bingo square include?",
  "Which work-friendly treat feels genuinely special?",
  "What is the nicest way to interrupt for something important?",
  "Which everyday moment helps colleagues feel like a team?",
  "What would you call a meeting with no slides?",
  "Which kind of friendly competition stays fun for everyone?",
  "What is a tiny sign that someone planned thoughtfully?",
  "Which workday shortcut would you teach in sixty seconds?",
  "What would be a good mascot for steady progress?",
  "Which phrase makes teamwork sound more inviting?",
  "What is a fun alternative use for a conference room?",
  "Which simple visual helps you understand an idea quickly?",
  "What is your favorite kind of positive team update?",
  "Which harmless work habit could become an Olympic event?",
  "What would a fortune cookie for our team predict?",
  "Which small change makes a conversation easier to join?",
  "What is an ideal topic for a walking meeting?",
  "Which everyday workplace moment feels quietly rewarding?",
  "What would a team postcard illustration show?",
  "Which quick question helps you choose where to start?",
  "What is a light way to acknowledge a packed schedule?",
  "Which team resource would benefit from a friendlier name?",
  "What would you include in a comfort kit for busy days?",
  "Which task would be more fun with a countdown?",
  "What small action turns parallel efforts into teamwork?",
  "Which workplace phrase sounds funniest taken literally?",
  "What would a one-line review of your morning say?",
  "Which kind of checkmark feels most satisfying?",
  "What is your favorite excuse to use a colorful pen?",
  "Which easy-to-learn skill would make a fun team swap?",
  "What makes a reminder feel helpful instead of nagging?",
  "Which familiar task could use a celebratory finish?",
  "What is a friendly signal that you are ready to chat?",
  "Which low-key tradition could connect different work locations?",
  "What would be the title of today's shortest meeting?",
  "Which everyday object would make a surprisingly good award?",
  "What is the coziest acceptable feature in a workspace?",
  "Which part of a team lunch do you enjoy most?",
  "What is a useful thing you learned almost by accident?",
  "Which group-chat reaction best says 'we did it'?",
  "What would make a status update more enjoyable to read?",
  "Which task is better with company, even silent company?",
  "What is an easy way to make room for late arrivals?",
  "Which workday detail would you capture in a doodle?",
  "What is a playful title for the person guarding the agenda?",
  "Which kind of question is fun to answer in one word?",
  "What would improve a waiting area for five minutes?",
  "Which ordinary workplace skill deserves a fan club?",
  "What is a nice reason to send an unplanned message?",
  "Which everyday choice saves you a surprising amount of effort?",
  "What would a team menu call its most popular item?",
  "Which moment in a project feels like turning a corner?",
  "What is a fun prompt for a collaborative doodle?",
  "Which simple activity helps reset a quiet room?",
  "What would be a good team phrase for taking a breather?",
  "Which helpful habit did you pick up from another workplace?",
  "What is your favorite sign that a plan is coming together?",
  "Which harmless question could replace small talk about busyness?",
  "What would make a shared calendar feel less mechanical?",
  "Which tiny upgrade has improved your digital workspace?",
  "What is a gentle way to bring energy back to a call?",
  "Which everyday work win is easiest to overlook?",
  "What would your ideal team bulletin contain?",
  "Which simple creative constraint makes ideas more interesting?",
  "What is the best thing to find in an old project folder?",
  "Which kind of workspace seat encourages conversation?",
  "What would you name a quiet hour with no notifications?",
  "Which low-stakes choice should the team vote on?",
  "What is a small way to make handoffs feel friendly?",
  "Which routine question deserves a more imaginative answer?",
  "What would a team-themed board game be about?",
  "Which moment deserves a collective sigh of relief?",
  "What is an easy way to welcome a different perspective?",
  "Which workplace sound would you replace with something nicer?",
  "What would make a shared task list feel more encouraging?",
  "Which quick activity helps you switch between kinds of work?",
  "What is the most cheerful shape for a sticky note?",
  "Which common tool would you redesign just for fun?",
  "What would a friendly out-of-office message include?",
  "Which light question can turn strangers into collaborators?",
  "What is a small moment of teamwork you enjoyed recently?",
  "Which workday milestone calls for a snack break?",
  "What would you choose for a team desktop wallpaper?",
  "Which simple habit makes shared spaces work better?",
  "What is an unexpectedly fun way to explain an idea?",
  "Which part of a new notebook feels most promising?",
  "What would you put on a team celebration playlist?",
  "Which meeting accessory deserves an upgrade?",
  "What is a pleasant phrase for asking someone to repeat something?",
  "Which work task has the most satisfying before-and-after?",
  "What would a team-themed postcard be sent to celebrate?",
  "Which tiny ritual helps you return after time away?",
  "What is a fun name for the last task of the day?",
  "Which simple kindness travels well across time zones?",
  "What would make a quick coffee chat worthwhile without coffee?",
  "Which familiar icon best represents collaboration?",
  "What is a playful way to choose who speaks first?",
  "Which workday moment would benefit from confetti?",
  "What would a team museum display from this week?",
  "Which everyday phrase makes you feel welcomed into a conversation?",
  "What is a small sign that a meeting was well hosted?",
  "Which task would you pair with your favorite comfortable chair?",
  "What would the cover of our team's current chapter show?",
  "Which quick exchange can improve the rest of a day?",
  "What is an easy way to make brainstorming less serious?",
  "Which ordinary item could symbolize a fresh start?",
  "What would you call a perfectly timed break?",
  "Which kind of praise feels natural to give on the spot?",
  "What is a low-pressure way to share something new you learned?",
  "Which workday scene belongs in a feel-good montage?",
  "What would make a team hello feel distinctive?",
  "Which simple question helps people find common ground?",
  "What is the best feature of your favorite work mug?",
  "Which everyday task would benefit from a buddy system?",
  "What would a tiny flag for a completed task look like?",
  "Which kind of informal gathering feels most accessible?",
  "What is a funny but accurate name for a busy hour?",
  "Which shared success still brings a quick smile?",
  "What would make a workspace tour surprisingly interesting?",
  "Which easy habit helps names stick in your memory?",
  "What is a friendly alternative to 'any questions'?",
  "Which ordinary work object could star in a short film?",
  "What would be a good theme for a team photo challenge?",
  "Which quick task gives you an instant momentum boost?",
  "What is a simple way to make a newcomer part of the rhythm?",
  "Which workplace corner has the best atmosphere?",
  "What would you draw to represent a smooth handoff?",
  "Which gentle joke can everyone safely share?",
  "What is a small comfort that travels between home and office?",
  "Which team moment would make a satisfying animated loop?",
  "What would be the ideal prize for a friendly quiz?",
  "Which kind of invitation makes joining feel optional and easy?",
  "What is a quick way to show you followed someone's explanation?",
  "Which simple improvement made you wonder why it took so long?",
  "What would a team weather vane point toward today?",
  "Which part of reconnecting with colleagues feels pleasantly familiar?",
] as const

export const RECONNECT_COLLEAGUES_MEANINGFUL = [
  "What contribution from this team have you appreciated recently?",
  "When has a colleague made your work easier in a lasting way?",
  "Which strength do you see our team using especially well?",
  "What helps you feel that your input has been heard?",
  "Which shared achievement taught us something worth keeping?",
  "What kind of recognition feels sincere and useful to you?",
  "When does collaboration bring out your best thinking?",
  "What do you value about the way this team solves problems?",
  "Which teammate behavior helps you approach work with confidence?",
  "What have we learned together that still shapes our work?",
  "How can colleagues show appreciation without making it formal?",
  "What quality in a collaborator earns your trust over time?",
  "Which part of your work feels more meaningful when shared?",
  "What recent exchange helped you understand another viewpoint?",
  "How do you prefer colleagues to acknowledge your effort?",
  "What is something this group makes possible that individuals cannot?",
  "Which team habit helps people feel respected?",
  "When have different working styles complemented each other well?",
  "What makes feedback feel like support rather than judgment?",
  "Which shared value is easiest to see in our everyday choices?",
  "What is one way the team has grown since we last connected?",
  "How can someone signal that your perspective matters?",
  "Which past project left us with a useful lesson?",
  "What kind of help is easiest for you to accept at work?",
  "When do you feel most connected to a team's purpose?",
  "What does dependable collaboration look like in small moments?",
  "Which part of your role would you like colleagues to understand better?",
  "What has a coworker taught you through their example?",
  "How do you know when a team discussion is genuinely inclusive?",
  "Which work experience changed how you approach collaboration?",
  "What team strength deserves more deliberate use?",
  "When has a thoughtful question improved your work?",
  "What does being a good colleague mean to you now?",
  "Which kind of encouragement helps you keep going?",
  "What have you come to appreciate about a different work style?",
  "How can teammates make uncertainty easier to navigate?",
  "Which shared memory captures this team at its best?",
  "What is a professional lesson you are glad to pass along?",
  "When does asking for help feel comfortable on a team?",
  "What kind of preparation shows respect for everyone's time?",
  "Which team practice helps quieter ideas reach the room?",
  "What makes a work relationship feel mutually supportive?",
  "How has your definition of useful teamwork evolved?",
  "Which small act of follow-through has stayed with you?",
  "What helps you trust that a disagreement will remain constructive?",
  "When have you felt included in a decision that affected your work?",
  "What does a generous exchange of knowledge look like?",
  "Which work challenge revealed an unexpected team capability?",
  "What is one way colleagues can protect each other's focus?",
  "How do you prefer to reconnect after a busy stretch?",
  "Which recent change has improved how we work together?",
  "What makes an update feel transparent and considerate?",
  "When has someone created space for you to contribute?",
  "What team behavior turns good intentions into reliability?",
  "Which kind of context helps you do thoughtful work?",
  "What do you appreciate about colleagues who think differently from you?",
  "How can a team honor both speed and careful thinking?",
  "Which shared experience strengthened our working connection?",
  "What helps a new idea receive a fair hearing?",
  "When have you seen curiosity prevent a misunderstanding?",
  "What does supportive accountability sound like to you?",
  "Which aspect of our collaboration feels most worth preserving?",
  "What is one way to make expertise easier to share?",
  "How do colleagues help you see a problem more clearly?",
  "Which kind of team promise builds confidence when kept?",
  "What have we become better at through practice?",
  "When does a handoff feel like genuine partnership?",
  "What is a sign that colleagues understand your priorities?",
  "Which value guides you when work becomes complicated?",
  "How can a team make room for thoughtful disagreement?",
  "What is something you respect about how this group adapts?",
  "When has a colleague's patience improved an outcome?",
  "Which workplace lesson became clearer through experience?",
  "What makes a request feel considerate of your workload?",
  "How can teammates show confidence in one another?",
  "Which moment made you feel proud to contribute here?",
  "What does fairness look like when work is divided?",
  "When have clear expectations helped you collaborate better?",
  "What team practice encourages you to ask useful questions?",
  "Which form of support helps before a deadline gets tight?",
  "What have you learned about communicating across different roles?",
  "How does a colleague make it easier to change your mind?",
  "Which shared principle helps us make better tradeoffs?",
  "What is a respectful way to surface a concern early?",
  "When has someone noticed a contribution others might miss?",
  "What does care for quality look like without perfectionism?",
  "Which team experience increased your confidence in the group?",
  "How can colleagues help each other maintain perspective?",
  "What makes a check-in feel purposeful to you?",
  "When have you benefited from someone explaining their reasoning?",
  "Which kind of collaboration leaves you with more energy?",
  "What is one strength you have seen a teammate develop?",
  "How can teams welcome questions without slowing momentum unnecessarily?",
  "Which shared practice makes remote colleagues feel present?",
  "What has this team taught you about listening?",
  "When does appreciation feel most timely?",
  "What helps people contribute before their ideas are fully formed?",
  "Which choice reflects the kind of team we want to be?",
  "What is one way to recognize invisible coordination work?",
  "How do you like colleagues to share important context?",
  "When has a teammate helped you recover from a mistake?",
  "Which part of our history is useful to remember now?",
  "What makes professional trust feel steady rather than fragile?",
  "How can a team respond well when someone needs clarification?",
  "Which example of cooperation would you like us to repeat?",
  "What is a meaningful way to thank someone for their time?",
  "When do you feel most able to offer your honest perspective?",
  "What helps colleagues stay connected across different schedules?",
  "Which team norm supports good judgment?",
  "How has working with others expanded your own approach?",
  "What is a sign that a group values learning over appearances?",
  "When has someone helped you translate an idea for others?",
  "Which responsibility benefits most from shared ownership?",
  "What does respectful urgency look like in practice?",
  "How can colleagues make progress visible without adding pressure?",
  "Which conversation helped align your understanding of the work?",
  "What is one way to support someone entering an unfamiliar task?",
  "When has a calm response changed the tone of a challenge?",
  "What team quality helps you handle ambiguity?",
  "How do you recognize when collaboration is balanced?",
  "Which kind of acknowledgment strengthens working relationships?",
  "What have we learned about coordinating under changing conditions?",
  "When does a group decision feel well considered?",
  "What is one thing colleagues can do to reduce guesswork?",
  "How can people show respect when priorities compete?",
  "Which past success offers guidance for today's work?",
  "What makes it easier to share an early concern?",
  "When has a teammate helped protect the bigger picture?",
  "What do you value in someone who facilitates a discussion?",
  "How can we make appreciation part of normal work?",
  "Which work principle has become more important to you lately?",
  "What is a helpful way to learn someone's working preferences?",
  "When have you seen inclusion improve a practical result?",
  "What makes a colleague's advice feel trustworthy?",
  "How do strong teams respond when plans need revision?",
  "Which shared expectation helps everyone participate?",
  "What is one way to keep institutional knowledge accessible?",
  "When has a colleague helped you notice an overlooked option?",
  "What does mutual respect look like during a busy period?",
  "How can a team make decisions understandable afterward?",
  "Which moment showed you that different perspectives were useful?",
  "What helps a group learn without assigning blame?",
  "When does informal support matter most in your workflow?",
  "What is one way to make collaboration more accessible?",
  "How do you prefer teammates to flag a changing priority?",
  "Which quality helps someone become a reliable thought partner?",
  "What have you learned from seeing a colleague handle uncertainty?",
  "When does a team feel safe enough to test an idea?",
  "What is a considerate way to offer additional context?",
  "How can colleagues help one another notice progress?",
  "Which team custom gives work a sense of continuity?",
  "Which signs tell you that colleagues have real ownership of a common goal?",
  "When has a colleague's flexibility made a difference?",
  "What is one way to invite input without putting anyone on the spot?",
  "How can a team preserve useful lessons between projects?",
  "Which form of clarity feels most supportive at the start?",
  "What do you appreciate in colleagues who challenge an assumption?",
  "When have you seen someone make participation easier for others?",
  "What does thoughtful responsiveness mean in your work?",
  "How can we make space for both expertise and fresh eyes?",
  "Which experience taught you the value of checking understanding?",
  "What is a useful way to share credit across roles?",
  "When does a team's pace feel sustainable?",
  "What helps you understand the impact of your contribution?",
  "How can colleagues disagree while protecting the relationship?",
  "Which work habit communicates dependability to you?",
  "What have you noticed about how this team builds momentum?",
  "When has a colleague made a complex situation feel manageable?",
  "What is one way to help people prepare for change?",
  "How do you like a team to close the loop?",
  "Which shared result reflects patient collaboration?",
  "What makes a professional conversation feel attentive?",
  "When have you felt trusted to use your judgment?",
  "What is one way to make room for dissenting views?",
  "How can teammates support focus without becoming distant?",
  "Which lesson from a difficult project still serves you?",
  "What does useful encouragement sound like during learning?",
  "When has clear ownership improved your working experience?",
  "What is a sign that a team respects different energy levels?",
  "How can colleagues acknowledge constraints without losing hope?",
  "Which shared habit prevents small issues from growing?",
  "What makes you feel comfortable saying you need more context?",
  "When has a teammate's consistency helped you plan well?",
  "What is one way to show that a question was valuable?",
  "How do you prefer to celebrate collective progress?",
  "Which kind of learning is easier with colleagues beside you?",
  "What does being well supported look like on an ordinary day?",
  "When has someone helped connect your task to a wider goal?",
  "What is a fair way to distribute opportunities to contribute?",
  "How can teams make gratitude specific without making it awkward?",
  "Which part of reconnecting can improve future coordination?",
  "What makes a working agreement useful rather than symbolic?",
  "When have you seen empathy improve a practical decision?",
  "What is one way to keep collaboration from becoming interruption?",
  "How can colleagues make transitions between projects smoother?",
  "Which experience deepened your respect for another role?",
  "What does good stewardship of shared time mean to you?",
  "When has a colleague helped you see your own strength?",
  "What is one way to make expectations easier to question?",
  "How do teams turn diverse viewpoints into coherent action?",
  "Which recent interaction renewed your sense of connection?",
  "What makes it worthwhile to revisit an old decision?",
  "When does transparency strengthen rather than overwhelm a team?",
  "What is one way to respond when someone raises a useful risk?",
  "How can colleagues keep care visible during fast work?",
  "Which shared challenge brought out thoughtful leadership from many people?",
  "What does an inclusive invitation to collaborate sound like?",
  "When has a team pause prevented wasted effort?",
  "What is one way to make helpful feedback easier to use?",
  "How do you know when colleagues are working from shared context?",
  "Which professional value do you hope others experience from you?",
  "What makes a team reflection feel constructive?",
  "When has someone's reliability given you room to think creatively?",
  "What is one way colleagues can support a sustainable pace?",
  "How can we make assumptions easier to examine together?",
  "Which team interaction helped you feel more capable?",
  "What does consideration look like across different time zones?",
  "When has a well-timed summary improved alignment?",
  "What is one way to keep shared goals visible during routine work?",
  "How can colleagues help each other make thoughtful tradeoffs?",
  "Which collaborative skill would you like us to practice more?",
  "What makes a colleague feel approachable when questions arise?",
  "When have you seen a team adapt without losing its values?",
  "What is one way to welcome people back after an absence?",
  "How do you prefer to receive appreciation for behind-the-scenes work?",
  "Which shared experience reminds you why cooperation matters?",
  "What does a respectful difference of opinion teach a team?",
  "When has someone helped make your workload more understandable?",
  "What is one way to strengthen connection without adding meetings?",
  "How can a team make learning visible and normal?",
  "Which colleague quality helps ideas move from thought to action?",
  "What makes it easier to admit that a plan needs adjustment?",
  "When has a team member modeled thoughtful restraint?",
  "What is one way to show care for a colleague's attention?",
  "How do shared standards improve creative freedom?",
  "Which moment helped you better understand how others contribute?",
  "What does good collaboration make possible for the people involved?",
  "When has someone asked for your input in a meaningful way?",
  "What is one way to keep recognition equitable?",
  "How can teammates make difficult work feel less isolating?",
  "Which group practice helps people bring their full expertise?",
  "What makes a team commitment feel credible?",
  "When has a clear boundary improved collaboration?",
  "What is one way to respect both urgency and availability?",
  "How can colleagues check assumptions without sounding distrustful?",
  "Which team lesson would you carry into a new project?",
  "What does kindness at work look like when time is short?",
  "When has a thoughtful handover protected continuity?",
  "What is one way to invite correction gracefully?",
  "How do you tell that colleagues are learning from each other?",
  "Which common challenge has helped this group mature?",
  "What makes a shared success feel personally meaningful?",
  "When has someone helped you find the right level of detail?",
  "What is one way to keep small promises visible?",
  "How can a team make room for reflection amid delivery?",
  "Which interaction demonstrated respect without needing many words?",
  "What does being included early enable you to contribute?",
  "When has a colleague helped you reconnect with the purpose?",
  "What is one way to notice who has not been heard yet?",
  "How can shared language improve cooperation across specialties?",
  "Which team quality becomes most valuable during change?",
  "What makes a request for input feel genuine?",
  "When has patience helped the team reach a better answer?",
  "What is one way to make working knowledge less dependent on memory?",
  "How do colleagues help turn pressure into clear priorities?",
  "Which past moment showed the value of asking sooner?",
  "What does professional generosity mean beyond sharing time?",
  "When has a colleague's directness been helpful and respectful?",
  "What is one way to build trust through everyday communication?",
  "How can a team value experimentation without creating unnecessary risk?",
  "Which shared responsibility could benefit from renewed attention?",
  "What makes it easier to reconnect after priorities pull people apart?",
  "When has a colleague helped preserve your sense of perspective?",
  "What is one way to make decisions more inclusive without forcing consensus?",
  "How do you recognize care in the way work is organized?",
  "Which team accomplishment reflects strengths we should use again?",
  "What makes an offer of help feel respectful?",
  "When has a different viewpoint made your own work stronger?",
  "What is one way to acknowledge effort before results are known?",
  "How can colleagues keep each other informed without creating noise?",
  "Which part of our connection would you like to renew?",
  "What does a healthy exchange of support look like over time?",
  "When has the team balanced independence and coordination well?",
  "What is one practical way to show that everyone's time matters?",
  "How can we carry our best collaborative moments forward?",
  "Which strength would you like this team to rely on more intentionally?",
  "What makes you hopeful about how we can work together next?",
  "What shared understanding would help our next chapter of work?",
  "When has someone made room for both your questions and expertise?",
  "What is one way to make routine coordination feel more respectful?",
  "How can a team recognize growth that is still in progress?",
  "Which working relationship has broadened how you define partnership?",
  "What makes collective ownership feel empowering rather than vague?",
  "When has good documentation helped colleagues support one another?",
  "What is one way to restore connection after an intense project?",
  "How can teammates make complex choices easier to understand?",
  "Which sign tells you that a group's trust is strengthening?",
  "What does genuine curiosity add to a professional relationship?",
  "When has a colleague helped make a constraint feel workable?",
  "What is one shared practice that could deepen our connection?",
] as const

export const RECONNECT_COLLEAGUES_DEEP = [
  "What working condition helps you contribute with both honesty and care?",
  "Which boundary enables you to remain a generous collaborator?",
  "What has changed in how you want to participate on this team?",
  "Where could clearer expectations reduce unnecessary strain for us?",
  "What does trust require when colleagues have incomplete information?",
  "Which part of our collaboration may need a thoughtful reset?",
  "How can we repair coordination after an important detail is missed?",
  "What need should a sustainable team pace account for more consistently?",
  "Where might our usual process unintentionally exclude useful perspectives?",
  "What would help you raise a concern before it becomes urgent?",
  "Which assumption about good work are you currently reconsidering?",
  "How should colleagues respond when impact differs from intention?",
  "What does accountability look like without blame or public pressure?",
  "Which professional boundary has become clearer to you over time?",
  "Where do we need more clarity about who decides and who advises?",
  "What helps you stay open when a colleague challenges your approach?",
  "How can we address tension while preserving everyone's dignity?",
  "Which team pattern deserves examination before our next major project?",
  "What would make it safer to say that a deadline is unrealistic?",
  "Where could we trade urgency for more durable progress?",
  "How has your sense of meaningful contribution changed recently?",
  "What makes a difficult workplace conversation feel appropriately contained?",
  "Which unspoken expectation would benefit from becoming explicit?",
  "How can a team rebuild confidence after a plan fails?",
  "What support helps you adapt without losing your working identity?",
  "Where could we distinguish healthy stretch from unsustainable demand?",
  "What does respectful repair require after a misunderstanding?",
  "Which part of collaboration asks you to grow most right now?",
  "How can colleagues acknowledge harm without assigning motives?",
  "What would help us make tradeoffs more transparent?",
  "Where do our stated values and daily habits feel misaligned?",
  "What kind of autonomy helps you do responsible work?",
  "How should a team revisit agreements that no longer fit?",
  "Which change in our environment requires a new way of cooperating?",
  "What helps you separate useful feedback from personal judgment?",
  "Where could stronger boundaries improve the quality of our work?",
  "How can we notice overload before someone must announce it?",
  "What does consent look like when adding work to someone's plate?",
  "Which team habit may reward speed at the expense of understanding?",
  "How can colleagues repair trust after inconsistent follow-through?",
  "What would make it easier to name competing priorities honestly?",
  "Where might silence be mistaken for agreement in our process?",
  "How has your approach to professional trust become more nuanced?",
  "What conditions let you disagree without feeling disconnected?",
  "Which aspect of your work would benefit from more shared ownership?",
  "How can we protect reflection when delivery pressure rises?",
  "What would a fair response to an honest mistake include?",
  "Where could our communication make more room for uncertainty?",
  "What does it mean to respect a colleague's capacity?",
  "Which responsibility should never depend on one person's quiet effort?",
  "How can a team change direction without dismissing earlier work?",
  "What helps you remain curious when you feel strongly about an answer?",
  "Where do we need a better distinction between optional and expected?",
  "What would meaningful closure look like for unfinished team business?",
  "How should colleagues approach a pattern that keeps causing friction?",
  "Which part of your professional identity feels newly important?",
  "What makes an apology at work credible to you?",
  "Where could we replace heroic effort with a healthier system?",
  "How can teams make room for changing one's mind?",
  "What do you need from colleagues when priorities shift suddenly?",
  "Which measure of progress may be obscuring something important?",
  "How should we respond when a process works unevenly for people?",
  "What helps you contribute when the path forward is ambiguous?",
  "Where could a clearer no protect a more meaningful yes?",
  "What does professional courage look like without unnecessary risk-taking?",
  "Which conversation would help us avoid repeating an old pattern?",
  "How can we question a norm without devaluing those who built it?",
  "What would help a team recover after trust has been stretched?",
  "Where should we slow down to improve future speed?",
  "Which responsibility has grown more important as you gained experience?",
  "What allows feedback to challenge you without diminishing you?",
  "Which choices reveal whether inclusion is real or merely stated?",
  "How can colleagues signal limits before reaching exhaustion?",
  "What would a more honest conversation about capacity make possible?",
  "Where might our language hide responsibility or ownership?",
  "What does repair look like when everyone acted in good faith?",
  "Which part of teamwork requires more patience than it receives?",
  "How can we preserve relationships while making a hard tradeoff?",
  "What would help you trust a revised commitment?",
  "Where are we relying on goodwill instead of a workable process?",
  "How do you want your role in group decisions to evolve?",
  "What makes a boundary understandable even when it disappoints someone?",
  "Which team belief might need updating as our work changes?",
  "How can colleagues share difficult context without creating alarm?",
  "What would make our ways of working more resilient?",
  "Where could a conversation about standards prevent future confusion?",
  "What does fairness require when circumstances differ?",
  "Which kind of pressure makes thoughtful work harder to sustain?",
  "How can we make repair proportionate to the impact of a mistake?",
  "What would help everyone distinguish urgency from anxiety?",
  "Where could clearer escalation paths protect working relationships?",
  "How has your view of loyalty at work changed?",
  "What does responsible disagreement require from each participant?",
  "Which invisible expectation creates the most avoidable friction?",
  "How can a team honor commitments while responding to new evidence?",
  "What would make it easier to ask for a pause?",
  "Where do we need less certainty and more inquiry?",
  "How should colleagues handle a concern they cannot fully verify?",
  "What does a sustainable definition of excellence include?",
  "Which aspect of belonging at work deserves more deliberate attention?",
  "How can we prevent helpful people from becoming default owners?",
  "What would allow responsibility to move without context being lost?",
  "Where might our process confuse visibility with contribution?",
  "How have your needs for focus and connection shifted?",
  "What does it take to repair a promise that could not be kept?",
  "Which decision would benefit from naming its underlying values?",
  "How can teams discuss impact without demanding personal disclosure?",
  "What would make a change feel supported rather than imposed?",
  "Where could more choice improve how people participate?",
  "How do you know when compromise has gone too far?",
  "What does healthy interdependence look like among colleagues?",
  "Which unresolved ambiguity could undermine future cooperation?",
  "How can we protect dissent when agreement feels convenient?",
  "What would help the team learn from strain without glorifying it?",
  "Where should personal preference end and shared practice begin?",
  "How has your tolerance for workplace uncertainty changed?",
  "What makes a request for flexibility feel reciprocal?",
  "Which type of repair needs action more than explanation?",
  "How can colleagues challenge a decision without challenging someone's worth?",
  "What would a humane response to changing capacity look like?",
  "Where could clearer sequencing reduce unnecessary conflict?",
  "How do we protect long-term trust during short-term pressure?",
  "What does being accountable to one another mean in daily work?",
  "Which familiar solution may no longer match the problem?",
  "How can a team acknowledge uneven impact without comparing experiences?",
  "What would help you release a responsibility that should be shared?",
  "Where could we create more room for thoughtful refusal?",
  "How has your understanding of professional respect deepened?",
  "What makes it possible to revisit a sensitive work issue calmly?",
  "Which tension between quality and pace needs a more honest agreement?",
  "How can colleagues repair connection when communication becomes purely transactional?",
  "What would equitable participation require in our current setting?",
  "Where might we be solving symptoms instead of causes?",
  "How do you want colleagues to respond when your needs change?",
  "What does it mean to hold a boundary with warmth?",
  "Which aspect of our culture is shaped by what goes unchallenged?",
  "How can a team make learning from failure professionally safe?",
  "What would help us respond to constraints without normalizing them?",
  "Where do we need clearer permission to ask basic questions?",
  "How has your relationship with ambition at work evolved?",
  "What makes constructive conflict worth the discomfort?",
  "Which shared practice could keep power from silencing information?",
  "How can we preserve context when people move between responsibilities?",
  "What would help a team recognize when persistence is no longer useful?",
  "Where could we be more explicit about the cost of a choice?",
  "How do you define enough when work can always expand?",
  "What does thoughtful leadership from any seat look like?",
  "Which workplace expectation deserves a respectful challenge?",
  "How can colleagues stay connected when their incentives differ?",
  "What would make workload conversations more factual and less personal?",
  "Where might our current success be creating a future risk?",
  "How has your preferred way of receiving challenge changed?",
  "What makes a team response feel restorative after conflict?",
  "Which responsibility would benefit from a clearer stopping point?",
  "How can we acknowledge disappointment without turning it into blame?",
  "What would help people contribute without overextending themselves?",
  "Where should consistency matter more than intensity?",
  "How do colleagues earn back confidence after a preventable gap?",
  "What does inclusion ask of us when participation styles differ?",
  "Which part of our decision process needs more traceability?",
  "How can teams make space for concerns that arrive late?",
  "What would help us distinguish healthy privacy from missing context?",
  "Where could better defaults reduce the need for individual advocacy?",
  "How has your sense of responsibility to teammates changed?",
  "What makes a change in expectations feel fair?",
  "Which difficult truth about our workflow can be discussed without fault-finding?",
  "How can we respond when a boundary reveals a planning problem?",
  "What would enable quieter forms of leadership to have more influence?",
  "Where do we need agreement about what good enough means?",
  "How do you stay aligned with values when choices are imperfect?",
  "What does a respectful exit from a commitment look like?",
  "Which team pattern might be maintained by good intentions?",
  "How can colleagues avoid making resilience an individual burden?",
  "What would help restore curiosity after a frustrating exchange?",
  "Where could we give people more control over how they engage?",
  "How has your approach to saying no at work matured?",
  "What makes a team capable of hearing inconvenient information?",
  "Which part of our shared work carries unrecognized emotional labor?",
  "How can we improve without treating the past as a failure?",
  "What would a balanced response to repeated friction involve?",
  "Where are we asking communication to compensate for unclear structure?",
  "How do we make space for recovery after unusually demanding work?",
  "What does mutuality look like when colleagues have different authority?",
  "Which change would better align our workload with our priorities?",
  "How can a team address exclusion without requiring anyone to defend belonging?",
  "What would help us notice when consensus is only surface-level?",
  "Where could fewer commitments produce more reliable collaboration?",
  "How has your understanding of influence changed within teams?",
  "What makes a difficult boundary easier to respect?",
  "Which condition helps you take responsible creative risks?",
  "How can colleagues make amends without expecting immediate reassurance?",
  "What would help us name uncertainty without weakening confidence?",
  "Where does our process need more room for professional judgment?",
  "How do you want this team to handle competing definitions of quality?",
  "What does it mean to leave space for someone to reconsider?",
  "Which team strength could become a weakness if overused?",
  "How can we challenge urgency that has become habitual?",
  "What would make a reflection on mistakes genuinely useful?",
  "Where could clearer roles reduce interpersonal tension?",
  "How has collaboration affected the kind of colleague you want to be?",
  "What makes it possible to hear impact without becoming defensive?",
  "Which norm would you keep even if the team doubled in size?",
  "How can we make boundaries visible before they are tested?",
  "What would responsible transparency leave private?",
  "Where might our standards ask different costs from different people?",
  "How do colleagues support change without rushing acceptance?",
  "What does repair require when there is no perfect solution?",
  "Which future challenge should shape how we collaborate now?",
  "How can a team remain cohesive without requiring sameness?",
  "What would help us discuss tradeoffs without framing winners and losers?",
  "Where do you want more agency in how your work is approached?",
  "How has your definition of a healthy workplace relationship evolved?",
  "What makes a team ready to retire an old practice?",
  "Which form of accountability preserves room for learning?",
  "How can colleagues acknowledge a rupture without dramatizing it?",
  "What would help make invisible constraints discussable?",
  "Where could we separate a person's idea from their standing?",
  "How do we protect trust when decisions cannot please everyone?",
  "What does a mature response to unmet expectations include?",
  "Which workplace need is easiest to overlook when things seem fine?",
  "How can a team avoid confusing constant availability with commitment?",
  "What would make our planning more honest about human limits?",
  "Where should we create a deliberate path for changing course?",
  "How has your view of professionalism become more inclusive?",
  "What makes an invitation to repair feel genuine?",
  "Which team dynamic changes when people feel secure enough to question?",
  "How can we avoid turning one person's coping strategy into a norm?",
  "What would help everyone see how decisions affect their work?",
  "Where could a pause create more responsible action?",
  "How do you want the team to balance continuity with reinvention?",
  "What does professional care require when someone declines to explain?",
  "Which current tension might point to a useful redesign?",
  "How can colleagues recognize a limit without treating it as resistance?",
  "What would help us make implicit power more visible in decisions?",
  "Where might a desire for harmony be preventing useful honesty?",
  "How has your sense of belonging shaped your contribution?",
  "What makes a shared boundary more durable than an individual request?",
  "Which team responsibility needs a clearer backup plan?",
  "How can we discuss a broken process without personalizing the problem?",
  "What would help colleagues reconnect after working in separate lanes?",
  "Where do we need to replace assumptions with explicit choice?",
  "How do you recognize when work is asking for too much adaptation?",
  "What does ethical speed look like when others depend on the outcome?",
  "Which part of our collaboration deserves more intentional closure?",
  "How can a team respond when someone withdraws an earlier agreement?",
  "What would make it possible to challenge a well-liked idea?",
  "Where could better preparation reduce pressure on live discussion?",
  "How has your experience shaped what you will no longer normalize?",
  "What makes a difficult decision easier to stand behind together?",
  "Which kind of support protects both independence and connection?",
  "How can colleagues name recurring disappointment without keeping score?",
  "What would help us redesign work around actual capacity?",
  "Where do expectations need to reflect the difference between roles?",
  "How do you want the team to respond when you revise a boundary?",
  "What does it take to turn reflection into changed behavior?",
  "Which work norm would benefit from a scheduled review?",
  "How can we keep candid conversation from becoming compulsory disclosure?",
  "What would help us make responsibility clear without creating isolation?",
  "Where could the team practice receiving a no with grace?",
  "How has your understanding of sustainable contribution shifted?",
  "What makes collaboration feel safe enough for unfinished thinking?",
  "Which pressure should be shared rather than silently absorbed?",
  "How can colleagues distinguish repair from simply moving on?",
  "What would strengthen trust before the next difficult moment?",
  "Where are our processes least responsive to changing needs?",
  "How do we maintain respect when confidence in a plan differs?",
  "What does a useful conversation about limits make clearer?",
  "Which part of our future work needs a new agreement?",
  "How can a team value candor without rewarding harshness?",
  "What would make support more proactive but not intrusive?",
  "Where might clearer criteria reduce the influence of familiarity?",
  "How has your idea of career growth broadened beyond advancement?",
  "What makes a reset feel like progress rather than retreat?",
  "Which collaboration cost should we stop treating as inevitable?",
  "How can we ensure that flexibility flows in more than one direction?",
  "What would help people question a process without owning its replacement?",
  "Where do we need a shared language for capacity?",
  "How do you want colleagues to handle context you choose not to share?",
  "What does it mean to protect someone's dignity during correction?",
  "Which aspect of trust depends most on predictability?",
  "How can a team make room for reflection without demanding conclusions?",
  "What would a healthier relationship with unfinished work look like?",
  "Where could we replace informal gatekeeping with clearer access?",
  "How has your view of effective collaboration changed through challenge?",
  "What makes it possible to renegotiate a commitment early?",
  "Which shared value should guide our next improvement?",
  "How can colleagues respond when a sincere effort falls short?",
  "What would help our team grow without losing what works?",
  "Where do we need to acknowledge tension rather than solve it immediately?",
  "How do we avoid asking individuals to fix collective conditions?",
  "What does respecting a clear no protect in professional relationships?",
  "Which future working relationship do we want to build deliberately?",
  "How can we make room for both stability and experimentation?",
  "What would help us recognize when repair is complete enough to proceed?",
  "Where could clearer mutual expectations deepen professional trust?",
  "How has reconnecting changed what you hope we improve together?",
  "What would help our future collaboration reflect what we know now?",
  "Where can we create more trust through fewer, clearer promises?",
  "How do we want to notice and address drift in our agreements?",
  "Which principle should remain steady as our ways of working evolve?",
] as const
