/** 300 original, context-dependent relationship scenarios for group voting. */
export const RED_FLAG_GREEN_FLAG_SCENARIOS = [
  // Communication
  'They reply slowly but always acknowledge important messages.',
  'They call without checking whether you are free first.',
  'They prefer resolving disagreements by text instead of in person.',
  'They need a full day to think before discussing conflict.',
  'They tell long stories and rarely ask follow-up questions.',
  'They share every detail of their day without being asked.',
  'They answer serious questions with humour before becoming sincere.',
  'They say exactly what they mean, even when it sounds blunt.',
  'They avoid difficult conversations until you initiate them.',
  'They send several messages when one would communicate the point.',
  'They want a good-morning and good-night message every day.',
  'They communicate affection through actions more than words.',
  'They ask for reassurance whenever your tone changes.',
  'They interrupt when excited but apologise when they notice.',
  'They need regular check-ins about how the relationship is going.',
  'They tell friends about an argument before speaking with you.',
  'They become quiet when overwhelmed but explain afterward.',
  'They correct your version of shared stories in front of others.',
  'They expect you to understand hints instead of making direct requests.',
  'They repeat your concern in their own words before responding.',
  'They dislike phone calls and communicate almost entirely by message.',
  'They ask many questions but reveal little about themselves.',
  'They say “we will talk later” and reliably return to the conversation.',
  'They use relationship advice from social media during disagreements.',
  'They send voice notes that are several minutes long.',
  'They discuss private relationship matters openly with one trusted friend.',
  'They want disagreements settled before either person goes to sleep.',
  'They prefer writing down feelings before saying them aloud.',
  'They point out changes in your behaviour before asking what is wrong.',
  'They can disagree without trying to change your opinion.',

  // Trust and privacy
  'They know your phone password but never use it without permission.',
  'They keep their phone face down during every date.',
  'They remain close friends with an ex-partner.',
  'They ask who you are texting whenever you smile at your phone.',
  'They share their live location whenever they travel alone.',
  'They prefer not to combine social-media accounts or passwords.',
  'They tell you when an ex contacts them, even when nothing happened.',
  'They read your public posts but rarely interact with them.',
  'They ask before looking through photos on your phone.',
  'They become uncomfortable when you spend time with a former partner.',
  'They trust you completely but dislike one particular friend of yours.',
  'They keep old romantic photographs stored privately.',
  'They tell you other people’s secrets to prove they trust you.',
  'They expect access to your location during nights out.',
  'They have never mentioned you on social media.',
  'They delete old conversations whenever a relationship ends.',
  'They ask to see messages after somebody flirts with you.',
  'They maintain friendships with people they once dated casually.',
  'They hide surprise plans by giving a misleading explanation.',
  'They tell you immediately when they break a promise.',
  'They prefer separate devices, accounts, and personal storage.',
  'They know your friends’ personal news because you tell them everything.',
  'They ask permission before sharing your photograph online.',
  'They follow many people they find attractive but never contact them.',
  'They believe partners should know every detail of each other’s past.',
  'They keep a journal and do not want you to read it.',
  'They check that you arrived safely but do not track your journey.',
  'They become defensive when you ask a simple question about their plans.',
  'They admit when jealousy is their feeling rather than your wrongdoing.',
  'They trust your explanation even when a situation looks suspicious.',

  // Conflict and repair
  'They apologise quickly but repeat the same behaviour the following week.',
  'They ask for a short break when arguments become heated.',
  'They bring up several old disagreements during one new conflict.',
  'They remain calm while you are upset and seem emotionally distant.',
  'They apologise for impact even when their intention was harmless.',
  'They use sarcasm when they feel criticised.',
  'They need physical affection soon after an argument.',
  'They forgive easily but remember every detail.',
  'They want a practical solution before discussing feelings.',
  'They become tearful whenever you express disappointment.',
  'They ask what repair would look like instead of guessing.',
  'They leave the room during conflict without saying when they will return.',
  'They accept responsibility but explain every reason behind the mistake.',
  'They raise their voice but never insult or threaten you.',
  'They need reassurance that the relationship is secure during conflict.',
  'They make jokes about arguments after both people have calmed down.',
  'They involve a family member when a disagreement feels serious.',
  'They expect an apology before they will listen to your perspective.',
  'They can name exactly what they will do differently next time.',
  'They avoid conflict so effectively that problems remain unresolved.',
  'They become very formal and polite when they are angry.',
  'They ask whether you want comfort, space, or solutions.',
  'They criticise your behaviour without attacking your character.',
  'They forgive you but need time before acting normal again.',
  'They insist on discussing disagreements only in private.',
  'They send a thoughtful message after struggling to speak clearly.',
  'They remember your exact words but forget the context around them.',
  'They seek couples counselling before the relationship feels broken.',
  'They admit uncertainty instead of pretending to know your motives.',
  'They can end a difficult conversation with warmth despite no agreement.',

  // Independence and boundaries
  'They take a solo holiday every year.',
  'They need one evening alone each week.',
  'They enjoy attending events without you.',
  'They dislike unplanned visits, even from a partner.',
  'They keep some hobbies entirely separate from the relationship.',
  'They ask before borrowing even small personal items.',
  'They expect you to attend most social events as a couple.',
  'They decline invitations from your family when tired.',
  'They want separate bedrooms available even when living together.',
  'They encourage you to maintain friendships they do not share.',
  'They need advance notice before making weekend plans.',
  'They prefer travelling with friends occasionally instead of with you.',
  'They do not want relationship conversations during working hours.',
  'They leave parties early without expecting you to leave too.',
  'They ask you to knock before entering their workspace.',
  'They dislike sharing clothes, toiletries, or personal devices.',
  'They want one day each month with no plans or obligations.',
  'They support your independence but rarely ask for help themselves.',
  'They protect their morning routine from interruptions.',
  'They expect both partners to have separate social circles.',
  'They decline physical affection when overstimulated.',
  'They ask for consent before discussing sensitive topics.',
  'They say no without providing a detailed explanation.',
  'They respect your boundary but privately disagree with it.',
  'They prefer celebrating some achievements alone before sharing them.',
  'They do not want family members holding spare keys to your home.',
  'They need quiet immediately after returning from work.',
  'They encourage separate goals alongside shared plans.',
  'They will not cancel personal commitments for spontaneous couple time.',
  'They change a boundary after discovering it no longer works for them.',

  // Money and work
  'They earn much more and prefer splitting every expense equally.',
  'They insist on paying for every date.',
  'They carry debt but follow a clear repayment plan.',
  'They avoid discussing their salary until the relationship is serious.',
  'They buy expensive gifts while struggling with regular bills.',
  'They send money to family members every month.',
  'They want a written agreement before combining finances.',
  'They track shared expenses down to the smallest amount.',
  'They change jobs often in search of work they enjoy.',
  'They work long hours but protect one evening for the relationship.',
  'They expect a partner to contribute according to income, not equally.',
  'They save carefully but spend generously on travel.',
  'They lend money to friends and rarely ask for repayment.',
  'They want separate accounts after marriage.',
  'They discuss large purchases but not everyday spending.',
  'They dislike budgeting and rely on automatic payments.',
  'They left a prestigious career for a happier, lower-paid role.',
  'They expect career opportunities to determine where you both live.',
  'They are between jobs and reject work outside their chosen field.',
  'They celebrate your promotion even when their career is struggling.',
  'They borrow money and repay it before being reminded.',
  'They buy second-hand items despite being able to afford new ones.',
  'They want one person to manage all household finances.',
  'They view financial support for relatives as non-negotiable.',
  'They never discuss money on a first date.',
  'They ask about your financial goals before discussing marriage.',
  'They keep an emergency fund nobody else can access.',
  'They prioritise free time over earning more money.',
  'They expect both partners to approve purchases above an agreed amount.',
  'They are generous with experiences but rarely buy physical gifts.',

  // Family and friends
  'They speak with a parent every day.',
  'They have no close friends but seem content.',
  'They dislike your closest friend but remain respectful.',
  'They invite family members to stay without first asking you.',
  'They spend every major holiday with their family.',
  'They become a different version of themselves around old friends.',
  'They are kind to your family but do not seek closeness with them.',
  'They share relationship milestones with friends before telling family.',
  'They cancel couple plans when a friend has a crisis.',
  'They expect you to defend them during family disagreements.',
  'They avoid a relative who repeatedly ignores their boundaries.',
  'They treat long-term friends like chosen family.',
  'They enjoy hosting but expect you to help prepare everything.',
  'They refuse to pretend to like a friend who treated you badly.',
  'They want parents involved in major life decisions.',
  'They rarely introduce partners until the relationship feels permanent.',
  'They prioritise a childhood friendship during scheduling conflicts.',
  'They remember your friends’ important events and ask about them.',
  'They find large family gatherings exhausting and attend briefly.',
  'They lend personal belongings to siblings without asking you.',
  'They expect regular double dates with another couple.',
  'They share a home with family to support them financially.',
  'They prefer solving relationship problems without outside opinions.',
  'They make an effort with the people who matter to you.',
  'They leave group gatherings when someone becomes disrespectful.',
  'They maintain a friendship with someone who openly dislikes you.',
  'They want future children to grow up near extended family.',
  'They avoid introducing you to one complicated relative.',
  'They are everyone’s emergency contact and struggle to say no.',
  'They welcome your friends but need advance notice before visits.',

  // Digital and public behaviour
  'They post photographs of you only after asking.',
  'They never update their public relationship status.',
  'They share affectionate posts after every disagreement.',
  'They use their phone throughout meals but respond when addressed.',
  'They follow former partners and occasionally like their updates.',
  'They prefer private messages to public birthday posts.',
  'They comment flirtatiously on friends’ photographs as a running joke.',
  'They archive couple photos after an argument.',
  'They record special moments before fully experiencing them.',
  'They ask you to remove an unflattering photo of them.',
  'They share indirect quotes online when upset.',
  'They have thousands of followers but keep relationships private.',
  'They expect quick replies because they can see you are online.',
  'They turn off read receipts to reduce communication pressure.',
  'They tag your location while you are still there.',
  'They keep notifications hidden on their lock screen.',
  'They post jokes about relationships that resemble your private issues.',
  'They send you posts instead of explaining how they feel.',
  'They maintain a close friendship entirely through online communication.',
  'They ask before adding your relatives on social media.',
  'They take breaks from social media without announcing them.',
  'They preserve messages and photographs from every past relationship.',
  'They share your achievements online more often than their own.',
  'They use a couple photograph as every profile picture.',
  'They refuse to film strangers for entertainment.',
  'They answer work messages during dates only when marked urgent.',
  'They want couple content to become part of their online brand.',
  'They have a private account you discovered through a friend.',
  'They delete comments that criticise your relationship.',
  'They put both phones away for planned quality time.',

  // Lifestyle and compatibility
  'They wake up several hours earlier than you every day.',
  'They keep their home untidy but know where everything is.',
  'They exercise daily and invite you without pressuring you.',
  'They dislike travelling and prefer spending holidays at home.',
  'They eat differently from you and expect separate meals.',
  'They plan weekends in detail by the middle of the week.',
  'They frequently change plans when a better option appears.',
  'They need music or television playing whenever they are home.',
  'They enjoy nightlife while you prefer quiet evenings.',
  'They adopt pets impulsively but care for them responsibly.',
  'They dislike driving and expect you to handle most journeys.',
  'They value punctuality and become anxious when you run late.',
  'They take work calls during holidays but keep them brief.',
  'They love hosting overnight guests in shared space.',
  'They spend free weekends completing household projects.',
  'They prefer routine meals and rarely try unfamiliar food.',
  'They meditate every morning and do not want interruptions.',
  'They attend religious services and do not expect you to join.',
  'They want a television in the bedroom.',
  'They prefer hiring help for chores both partners dislike.',
  'They need the room cold to sleep comfortably.',
  'They collect items that occupy significant space.',
  'They make major health changes and invite you to participate.',
  'They enjoy spontaneous visitors while you prefer planned company.',
  'They require complete silence while concentrating.',
  'They spend several hours each week gaming with friends.',
  'They avoid alcohol but are comfortable around people who drink.',
  'They want to live in the countryside while your career is city-based.',
  'They clean when stressed and expect nobody to interfere.',
  'They protect sleep even when it means leaving events early.',

  // Commitment and future
  'They discuss marriage early because they date with that intention.',
  'They want children someday but do not know when.',
  'They avoid labels while behaving like a committed partner.',
  'They include you in long-term plans after only a few dates.',
  'They want to live together before considering engagement.',
  'They prefer a long engagement with no urgent wedding plans.',
  'They change the subject whenever retirement or old age comes up.',
  'They want to keep their surname after marriage.',
  'They imagine relocating abroad within five years.',
  'They want legal agreements protecting both partners before marriage.',
  'They discuss parenting values before deciding whether to have children.',
  'They believe commitment matters more than formal marriage.',
  'They want to buy property together before getting engaged.',
  'They set relationship goals and review them every year.',
  'They hesitate to promise forever but consistently show up now.',
  'They want future caregiving responsibilities discussed in advance.',
  'They expect both partners to remain financially independent.',
  'They want a very small wedding despite having a large family.',
  'They preserve personal goals that might require time apart.',
  'They have a detailed vision of family life but welcome negotiation.',
  'They avoid making plans more than a few months ahead.',
  'They want to be engaged before signing a joint lease.',
  'They ask how your ambitions could fit beside theirs.',
  'They believe couples should renew commitment through regular rituals.',
  'They want major future decisions delayed until both careers stabilise.',
  'They openly admit uncertainty about becoming a parent.',
  'They prioritise caring for ageing relatives in future plans.',
  'They want separate personal spaces in any shared home.',
  'They view moving in together as practical rather than symbolic.',
  'They can describe the future they want without assuming your answer.',

  // Care and affection
  'They remember practical details but forget sentimental dates.',
  'They show affection freely in private but rarely in public.',
  'They bring solutions when you mainly want emotional support.',
  'They care for you when sick but become overly protective.',
  'They give thoughtful inexpensive gifts throughout the year.',
  'They need frequent compliments to feel secure.',
  'They express love through teasing that never targets insecurities.',
  'They notice you are overwhelmed before you say anything.',
  'They encourage rest but struggle to rest themselves.',
  'They celebrate your success quietly rather than dramatically.',
  'They remember your preferences but occasionally choose for you.',
  'They offer physical comfort before asking what happened.',
  'They learn how you prefer to receive apologies.',
  'They arrange surprises even though you prefer advance notice.',
  'They keep sentimental objects from ordinary days together.',
  'They ask how to support you instead of assuming.',
  'They check in often during difficult weeks but accept brief replies.',
  'They compliment you privately more than publicly.',
  'They encourage therapy without using it to dismiss your feelings.',
  'They make your favourite meal after a difficult day.',
  'They offer help repeatedly after you initially decline.',
  'They notice changes in your routine and ask gently about them.',
  'They express affection through practical errands.',
  'They remember what comforts you but ask whether it still helps.',
  'They protect your dignity when you make a mistake in public.',
  'They challenge your self-criticism without forcing positivity.',
  'They give you space while making it clear they remain available.',
  'They celebrate progress that other people might overlook.',
  'They accept care from you without treating it as weakness.',
  'They make consistent effort even when romance feels ordinary.',
] as const
