export const SIP_OR_SPILL_PARTY: readonly string[] = [
  "Spill: What celebration always brings out your happiest side? Or take a sip.",
  "Spill: Which birthday tradition would you gladly keep forever? Or take a sip.",
  "Spill: What milestone have you most enjoyed celebrating with others? Or take a sip.",
  "Spill: Which holiday gathering feels the most joyful to you? Or take a sip.",
  "Spill: What small achievement deserves a party more often? Or take a sip.",
  "Spill: Which celebration from childhood do you remember most fondly? Or take a sip.",
  "Spill: What kind of good news would make you organize a gathering immediately? Or take a sip.",
  "Spill: Which annual occasion do you start anticipating months early? Or take a sip.",
  "Spill: What is the most thoughtful way someone has celebrated you? Or take a sip.",
  "Spill: Which celebration do you prefer to keep simple and quiet? Or take a sip.",
  "Spill: What personal win did you celebrate in an unexpectedly fun way? Or take a sip.",
  "Spill: Which festive season changes your mood as soon as it begins? Or take a sip.",
  "Spill: What celebration would you invent if the calendar had room for one more? Or take a sip.",
  "Spill: Which occasion makes you happiest to gather several generations together? Or take a sip.",
  "Spill: What is your ideal way to celebrate a friend's success? Or take a sip.",
  "Spill: Which ordinary moment have you turned into a memorable celebration? Or take a sip.",
  "Spill: What part of preparing for a celebration excites you most? Or take a sip.",
  "Spill: Which celebration taught you that a small guest list can still feel special? Or take a sip.",
  "Spill: What is one occasion you wish people celebrated with less pressure? Or take a sip.",
  "Spill: Which recent reason to celebrate made you genuinely proud? Or take a sip.",

  "Spill: What role do you naturally take when friends plan a gathering? Or take a sip.",
  "Spill: Which kind of gathering helps you reconnect with people best? Or take a sip.",
  "Spill: What makes a casual get-together feel worth attending to you? Or take a sip.",
  "Spill: Which gathering have you attended that felt welcoming from the first minute? Or take a sip.",
  "Spill: What is your favorite reason to bring a group of friends together? Or take a sip.",
  "Spill: Which part of a reunion do you look forward to most? Or take a sip.",
  "Spill: What type of gathering would you happily attend every month? Or take a sip.",
  "Spill: Which group activity has helped strangers become comfortable quickly? Or take a sip.",
  "Spill: What is the best conversation starter you have heard at a gathering? Or take a sip.",
  "Spill: Which gathering made you feel unexpectedly close to a group? Or take a sip.",
  "Spill: What makes a farewell gathering meaningful rather than sad? Or take a sip.",
  "Spill: Which time of day creates your favorite atmosphere for a gathering? Or take a sip.",
  "Spill: What is your ideal size for a relaxed social gathering? Or take a sip.",
  "Spill: Which gathering would you recreate exactly if you could? Or take a sip.",
  "Spill: What is one thing that helps a mixed group connect naturally? Or take a sip.",
  "Spill: Which kind of gathering makes time seem to pass fastest? Or take a sip.",
  "Spill: What setting makes conversation flow most easily for you? Or take a sip.",
  "Spill: Which spontaneous gathering turned out better than a carefully planned one? Or take a sip.",
  "Spill: What do you enjoy most about seeing different friend groups mingle? Or take a sip.",
  "Spill: Which recurring get-together would you like to start with your friends? Or take a sip.",

  "Spill: What hosting task are you surprisingly good at? Or take a sip.",
  "Spill: Which detail do you notice first when someone welcomes you into their home? Or take a sip.",
  "Spill: What is your reliable trick for making guests feel comfortable? Or take a sip.",
  "Spill: Which part of hosting do you find more enjoyable than expected? Or take a sip.",
  "Spill: What is the most useful hosting lesson you learned through experience? Or take a sip.",
  "Spill: Which simple refreshment do you like serving to a crowd? Or take a sip.",
  "Spill: What do you usually prepare first when guests are coming over? Or take a sip.",
  "Spill: Which hosting responsibility would you happily delegate every time? Or take a sip.",
  "Spill: What is your favorite way to welcome the first guest who arrives? Or take a sip.",
  "Spill: Which last-minute hosting adjustment has saved an event for you? Or take a sip.",
  "Spill: What makes you feel most appreciated as a host? Or take a sip.",
  "Spill: Which room or space would you most enjoy transforming for a party? Or take a sip.",
  "Spill: What is your best method for keeping party preparation manageable? Or take a sip.",
  "Spill: Which homemade touch has received the warmest reaction from your guests? Or take a sip.",
  "Spill: What do you do when a gathering becomes livelier than planned? Or take a sip.",
  "Spill: Which hosting habit did you pick up from someone you admire? Or take a sip.",
  "Spill: What is your favorite part of the quiet after guests leave? Or take a sip.",
  "Spill: Which item do you always make sure is easy for guests to find? Or take a sip.",
  "Spill: What would your dream co-host contribute to the occasion? Or take a sip.",
  "Spill: Which compliment about your hosting would mean the most to you? Or take a sip.",

  "Spill: Which song can instantly turn a room into a party for you? Or take a sip.",
  "Spill: What track would you choose to open your perfect party playlist? Or take a sip.",
  "Spill: Which music genre deserves more time at parties? Or take a sip.",
  "Spill: What song always makes you sing along at a gathering? Or take a sip.",
  "Spill: Which unexpected song choice have you seen delight an entire room? Or take a sip.",
  "Spill: What is your favorite musical memory from a celebration? Or take a sip.",
  "Spill: Which decade would supply most of your party playlist? Or take a sip.",
  "Spill: What song helps you feel at ease when you arrive somewhere new? Or take a sip.",
  "Spill: Which artist would you trust to soundtrack a whole evening? Or take a sip.",
  "Spill: What kind of music suits a relaxed dinner gathering best? Or take a sip.",
  "Spill: Which tune has become linked to a particular group of friends for you? Or take a sip.",
  "Spill: What song would you save for the most energetic point of the night? Or take a sip.",
  "Spill: Which party playlist transition impressed you more than it should have? Or take a sip.",
  "Spill: What musical choice can change the mood of a gathering fastest? Or take a sip.",
  "Spill: Which familiar song makes a great crowd singalong? Or take a sip.",
  "Spill: What lesser-known track would you add to introduce friends to something new? Or take a sip.",
  "Spill: Which instrument creates the most festive sound to you? Or take a sip.",
  "Spill: What song reminds you of getting ready for a big night out? Or take a sip.",
  "Spill: Which live music experience felt like one enormous party? Or take a sip.",
  "Spill: What closing song would leave your guests smiling on the way home? Or take a sip.",

  "Spill: Which dance move do you use when you stop overthinking? Or take a sip.",
  "Spill: What song has pulled you onto the dance floor unexpectedly? Or take a sip.",
  "Spill: Which group dance do you actually enjoy joining? Or take a sip.",
  "Spill: What is your happiest memory of dancing with friends? Or take a sip.",
  "Spill: Which style of dance would you love to learn before your next party? Or take a sip.",
  "Spill: What helps you feel comfortable enough to start dancing? Or take a sip.",
  "Spill: Which person in your circle brings the best energy to a dance floor? Or take a sip.",
  "Spill: What is the funniest harmless dance-floor mix-up you have witnessed? Or take a sip.",
  "Spill: Which dance trend were you late to appreciate? Or take a sip.",
  "Spill: What makes a crowded dance floor feel joyful rather than overwhelming? Or take a sip.",
  "Spill: Which celebration gave you the most unexpected chance to dance? Or take a sip.",
  "Spill: What is your signature reaction when your favorite dance song begins? Or take a sip.",
  "Spill: Which partner dance looks the most fun to master? Or take a sip.",
  "Spill: What dancing memory still makes you laugh warmly? Or take a sip.",
  "Spill: Which kind of lighting makes a dance floor more inviting? Or take a sip.",
  "Spill: What song would you choose for a friendly dance challenge? Or take a sip.",
  "Spill: Which dance-floor moment made the whole crowd cheer? Or take a sip.",
  "Spill: What do you enjoy more about dancing in a group than dancing alone? Or take a sip.",
  "Spill: Which celebration taught you a dance from another culture? Or take a sip.",
  "Spill: What would convince you to be the first person on the dance floor? Or take a sip.",

  "Spill: What thoughtful detail has made you feel valued as a guest? Or take a sip.",
  "Spill: Which party invitation made you excited before the event even began? Or take a sip.",
  "Spill: What is the warmest welcome you have received at a gathering? Or take a sip.",
  "Spill: Which event surprised you by being much more fun than expected? Or take a sip.",
  "Spill: What makes you decide that a party was genuinely memorable? Or take a sip.",
  "Spill: Which gathering helped you discover a new interest? Or take a sip.",
  "Spill: What is the nicest introduction a host has made for you? Or take a sip.",
  "Spill: Which party activity made it easiest to meet new people? Or take a sip.",
  "Spill: What guest experience made you want to thank the host afterward? Or take a sip.",
  "Spill: Which event had the most comfortable balance of activity and conversation? Or take a sip.",
  "Spill: What is the best favor or keepsake you have received as a guest? Or take a sip.",
  "Spill: Which venue made an ordinary gathering feel extraordinary? Or take a sip.",
  "Spill: What sign tells you that you can fully relax at a party? Or take a sip.",
  "Spill: Which gathering introduced you to a food you now love? Or take a sip.",
  "Spill: What moment made you glad you accepted an invitation you nearly declined? Or take a sip.",
  "Spill: Which seating arrangement led to an unexpectedly great conversation? Or take a sip.",
  "Spill: What makes leaving a party feel like the right choice at the right time? Or take a sip.",
  "Spill: Which guest experience changed how you host your own gatherings? Or take a sip.",
  "Spill: What is the kindest thing another guest has done to include you? Or take a sip.",
  "Spill: Which invitation are you especially grateful you received? Or take a sip.",

  "Spill: What party theme would let you express your personality best? Or take a sip.",
  "Spill: Which costume theme have you interpreted most creatively? Or take a sip.",
  "Spill: What color palette would you choose for a joyful celebration? Or take a sip.",
  "Spill: Which movie world would make the most entertaining party theme? Or take a sip.",
  "Spill: What decade would you most enjoy recreating for one evening? Or take a sip.",
  "Spill: Which seasonal theme can look festive without feeling predictable? Or take a sip.",
  "Spill: What tiny decorative detail can transform a party atmosphere? Or take a sip.",
  "Spill: Which themed invitation would make you immediately curious? Or take a sip.",
  "Spill: What book or story would inspire a beautiful gathering? Or take a sip.",
  "Spill: Which travel destination would you use as inspiration for a party? Or take a sip.",
  "Spill: What theme would encourage guests to be playful without needing elaborate costumes? Or take a sip.",
  "Spill: Which retro party idea deserves a modern comeback? Or take a sip.",
  "Spill: What nature-inspired theme would you enjoy bringing indoors? Or take a sip.",
  "Spill: Which theme would make the food choices especially fun? Or take a sip.",
  "Spill: What fictional setting would create the best party decorations? Or take a sip.",
  "Spill: Which theme could work equally well for a small or large gathering? Or take a sip.",
  "Spill: What dress code would make an event feel special but still comfortable? Or take a sip.",
  "Spill: Which theme have you seen guests embrace with surprising enthusiasm? Or take a sip.",
  "Spill: What local tradition could inspire a meaningful party theme? Or take a sip.",
  "Spill: Which party theme would you avoid because it feels unlike you? Or take a sip.",

  "Spill: What usually gives you the first burst of energy at a party? Or take a sip.",
  "Spill: Which social setting makes you feel most naturally outgoing? Or take a sip.",
  "Spill: What helps you recharge during a lively gathering? Or take a sip.",
  "Spill: Which friend can lift the energy of a room without dominating it? Or take a sip.",
  "Spill: What part of a party tends to bring out your quiet side? Or take a sip.",
  "Spill: Which kind of crowd makes you feel instantly at home? Or take a sip.",
  "Spill: What is your favorite way to contribute when you are low on social energy? Or take a sip.",
  "Spill: Which moment signals that a gathering has found its rhythm? Or take a sip.",
  "Spill: What atmosphere helps you move beyond small talk? Or take a sip.",
  "Spill: Which social plan sounds energizing even after a busy week? Or take a sip.",
  "Spill: What makes you feel confident walking into a room where you know few people? Or take a sip.",
  "Spill: Which part of meeting a new group do you find easiest? Or take a sip.",
  "Spill: What is your preferred way to take a quiet break at a gathering? Or take a sip.",
  "Spill: Which type of party lets you be most fully yourself? Or take a sip.",
  "Spill: What group dynamic makes a gathering feel especially warm? Or take a sip.",
  "Spill: Which activity helps restore the mood when party energy dips? Or take a sip.",
  "Spill: What makes an enthusiastic guest fun to be around? Or take a sip.",
  "Spill: Which social situation has helped you become more confident over time? Or take a sip.",
  "Spill: What balance of familiar faces and new people suits you best? Or take a sip.",
  "Spill: Which part of an evening do you tend to enjoy most as your energy changes? Or take a sip.",

  "Spill: What piece of party etiquette do you appreciate most from guests? Or take a sip.",
  "Spill: Which polite gesture from a host is easy to overlook but meaningful? Or take a sip.",
  "Spill: What is your preferred way to respond when you cannot attend an event? Or take a sip.",
  "Spill: Which shared-space habit makes gatherings smoother for everyone? Or take a sip.",
  "Spill: What is the kindest way to handle arriving later than planned? Or take a sip.",
  "Spill: Which hosting boundary do you think guests should respect without reminders? Or take a sip.",
  "Spill: What is a gracious way to welcome someone who comes alone? Or take a sip.",
  "Spill: Which contribution from a guest feels helpful without creating extra work? Or take a sip.",
  "Spill: What is the best way to navigate a conversation you need to leave? Or take a sip.",
  "Spill: Which sign from a host tells you the gathering is winding down? Or take a sip.",
  "Spill: What etiquette rule becomes especially important at a shared meal? Or take a sip.",
  "Spill: Which thoughtful action helps keep noise considerate for nearby people? Or take a sip.",
  "Spill: What is your favorite way to thank someone for hosting? Or take a sip.",
  "Spill: Which conversational habit helps everyone get a chance to speak? Or take a sip.",
  "Spill: What is a respectful way to handle different preferences at a party? Or take a sip.",
  "Spill: Which guest habit quietly makes a host's job easier? Or take a sip.",
  "Spill: What is the fairest way to settle a friendly disagreement about party plans? Or take a sip.",
  "Spill: Which courtesy matters most when an event has a clear schedule? Or take a sip.",
  "Spill: What is your approach to offering help before you leave a gathering? Or take a sip.",
  "Spill: Which modern party custom deserves a clearer etiquette rule? Or take a sip.",

  "Spill: What harmless party mistake became funnier with time? Or take a sip.",
  "Spill: Which decoration failed in a way that improved the mood? Or take a sip.",
  "Spill: What food mix-up made everyone laugh instead of complain? Or take a sip.",
  "Spill: Which wrong turn on the way to a gathering became part of the story? Or take a sip.",
  "Spill: What outfit misunderstanding have you handled with good humor? Or take a sip.",
  "Spill: Which forgotten party item inspired a clever substitute? Or take a sip.",
  "Spill: What moment of accidental coordination looked completely planned? Or take a sip.",
  "Spill: Which party game confusion produced the funniest harmless result? Or take a sip.",
  "Spill: What cake or dessert surprise did not go according to plan? Or take a sip.",
  "Spill: Which awkward entrance turned into a cheerful memory? Or take a sip.",
  "Spill: What weather surprise forced a party to change direction? Or take a sip.",
  "Spill: Which misheard song request made the playlist more entertaining? Or take a sip.",
  "Spill: What name-tag mistake led to a genuinely good conversation? Or take a sip.",
  "Spill: Which seating mix-up introduced people who got along brilliantly? Or take a sip.",
  "Spill: What early arrival caught a host in a funny but harmless moment? Or take a sip.",
  "Spill: Which group photo attempt became memorable for all the wrong poses? Or take a sip.",
  "Spill: What party prop behaved differently from everyone expected? Or take a sip.",
  "Spill: Which surprise guest reaction made an ordinary moment hilarious? Or take a sip.",
  "Spill: What minor scheduling mix-up resulted in bonus time together? Or take a sip.",
  "Spill: Which improvised solution became better than the original party plan? Or take a sip.",

  "Spill: What family celebration tradition feels uniquely yours? Or take a sip.",
  "Spill: Which cultural tradition do you enjoy sharing with new friends? Or take a sip.",
  "Spill: What party ritual signals that the celebration has officially begun? Or take a sip.",
  "Spill: Which tradition has gained new meaning for you over time? Or take a sip.",
  "Spill: What celebratory food connects you most strongly to home? Or take a sip.",
  "Spill: Which tradition would you like to pass to a younger generation? Or take a sip.",
  "Spill: What gathering custom did you adopt from a friend? Or take a sip.",
  "Spill: Which annual group photo tradition do you secretly enjoy? Or take a sip.",
  "Spill: What song or sound marks a special tradition in your community? Or take a sip.",
  "Spill: Which traditional decoration carries the most meaning for you? Or take a sip.",
  "Spill: What new tradition would you like your friend group to create? Or take a sip.",
  "Spill: Which old-fashioned party custom still feels charming? Or take a sip.",
  "Spill: What tradition makes guests feel like active participants? Or take a sip.",
  "Spill: Which celebratory greeting feels especially warm to you? Or take a sip.",
  "Spill: What tradition have you happily adapted to fit a modern gathering? Or take a sip.",
  "Spill: Which community event best preserves a sense of shared history? Or take a sip.",
  "Spill: What repeated joke or phrase has become a tradition among your friends? Or take a sip.",
  "Spill: Which tradition makes the end of a celebration feel complete? Or take a sip.",
  "Spill: What ceremonial moment do you find unexpectedly moving? Or take a sip.",
  "Spill: Which borrowed tradition have you come to appreciate through someone else? Or take a sip.",

  "Spill: What helps you know that every guest feels included? Or take a sip.",
  "Spill: Which party activity works well for people with different energy levels? Or take a sip.",
  "Spill: What is a simple way to include someone who seems hesitant to join in? Or take a sip.",
  "Spill: Which menu choice helps a wider range of guests feel considered? Or take a sip.",
  "Spill: What makes an invitation feel genuinely open and welcoming? Or take a sip.",
  "Spill: Which seating choice can help a newcomer feel part of the group? Or take a sip.",
  "Spill: What is one way hosts can accommodate guests who prefer quieter spaces? Or take a sip.",
  "Spill: Which game allows different personalities to contribute comfortably? Or take a sip.",
  "Spill: What detail shows that a venue was chosen with accessibility in mind? Or take a sip.",
  "Spill: Which welcoming phrase helps remove pressure from party participation? Or take a sip.",
  "Spill: What have you learned from attending a celebration different from your own traditions? Or take a sip.",
  "Spill: Which role can you play when someone is new to the group? Or take a sip.",
  "Spill: What makes a multi-generational gathering enjoyable for everyone? Or take a sip.",
  "Spill: Which flexible party plan best respects different schedules? Or take a sip.",
  "Spill: What is a thoughtful way to learn a guest's preferences before an event? Or take a sip.",
  "Spill: Which activity creates connection without putting anyone on the spot? Or take a sip.",
  "Spill: What signals that guests are free to participate at their own comfort level? Or take a sip.",
  "Spill: Which small adjustment can make a loud party more comfortable? Or take a sip.",
  "Spill: What does an inclusive celebration look like at its best? Or take a sip.",
  "Spill: Which moment made you feel truly seen and welcomed at an event? Or take a sip.",

  "Spill: What party conversation stayed with you long after the night ended? Or take a sip.",
  "Spill: Which surprise celebration succeeded because of one perfect detail? Or take a sip.",
  "Spill: What shared laugh best captures a favorite gathering for you? Or take a sip.",
  "Spill: Which sunset, view, or setting made a celebration unforgettable? Or take a sip.",
  "Spill: What reunion moment felt as if no time had passed? Or take a sip.",
  "Spill: Which toast or speech was memorable for its genuine warmth? Or take a sip.",
  "Spill: What unexpected friendship began at a social event? Or take a sip.",
  "Spill: Which party ended with everyone lingering because nobody wanted to leave? Or take a sip.",
  "Spill: What handmade detail from an event do you still remember clearly? Or take a sip.",
  "Spill: Which quiet moment within a busy celebration meant the most to you? Or take a sip.",
  "Spill: What gathering changed your opinion of someone for the better? Or take a sip.",
  "Spill: Which event made a familiar place feel completely new? Or take a sip.",
  "Spill: What chance conversation became the highlight of an evening? Or take a sip.",
  "Spill: Which celebration felt special because everyone contributed something? Or take a sip.",
  "Spill: What departure moment gave a party the perfect ending? Or take a sip.",
  "Spill: Which gathering reminded you how much a friendship had grown? Or take a sip.",
  "Spill: What unexpected act of kindness shaped your memory of a party? Or take a sip.",
  "Spill: Which event would you describe as simple but unforgettable? Or take a sip.",
  "Spill: What sensory detail brings back a favorite celebration instantly? Or take a sip.",
  "Spill: Which ordinary photo reminds you of an extraordinary gathering? Or take a sip.",

  "Spill: What party game reveals people's creativity in a friendly way? Or take a sip.",
  "Spill: Which team activity made your group cooperate surprisingly well? Or take a sip.",
  "Spill: What low-pressure game would you use to warm up a room? Or take a sip.",
  "Spill: Which guessing game always produces unexpected answers? Or take a sip.",
  "Spill: What creative activity would you add to a calm gathering? Or take a sip.",
  "Spill: Which outdoor party activity brings out your playful side? Or take a sip.",
  "Spill: What friendly competition do you enjoy even when you lose? Or take a sip.",
  "Spill: Which collaborative challenge creates the best group stories? Or take a sip.",
  "Spill: What party activity can entertain both participants and spectators? Or take a sip.",
  "Spill: Which classic game deserves another round at your next gathering? Or take a sip.",
  "Spill: What talent would you contribute to an informal variety show? Or take a sip.",
  "Spill: Which craft activity would give guests a meaningful keepsake? Or take a sip.",
  "Spill: What trivia category would make you a valuable teammate? Or take a sip.",
  "Spill: Which scavenger-hunt clue would be fun without being too difficult? Or take a sip.",
  "Spill: What storytelling game would help a group learn about one another? Or take a sip.",
  "Spill: Which karaoke choice would you enjoy performing with friends? Or take a sip.",
  "Spill: What activity would make a daytime party feel special? Or take a sip.",
  "Spill: Which tabletop game fits a cozy gathering best? Or take a sip.",
  "Spill: What playful award would you give someone at this party? Or take a sip.",
  "Spill: Which group challenge has made you laugh hardest while participating? Or take a sip.",

  "Spill: What would your perfect party look like from arrival to goodbye? Or take a sip.",
  "Spill: Which celebration would you travel back in time to experience again? Or take a sip.",
  "Spill: What new kind of gathering would you like to try this year? Or take a sip.",
  "Spill: Which detail would make your next birthday feel especially personal? Or take a sip.",
  "Spill: What party-planning skill would you most like to improve? Or take a sip.",
  "Spill: Which place have you visited that would make a magical event venue? Or take a sip.",
  "Spill: What celebration would you plan for your community if resources were unlimited? Or take a sip.",
  "Spill: Which guest list would create fascinating conversation around one table? Or take a sip.",
  "Spill: What atmosphere would you want guests to remember from an event you designed? Or take a sip.",
  "Spill: Which personal interest would you build an entire gathering around? Or take a sip.",
  "Spill: What daytime celebration could become your new favorite social plan? Or take a sip.",
  "Spill: Which season would you choose for a once-in-a-lifetime gathering? Or take a sip.",
  "Spill: What would you include in a party designed entirely for relaxation? Or take a sip.",
  "Spill: Which future milestone are you most excited to celebrate with others? Or take a sip.",
  "Spill: What would make a neighborhood gathering feel worth repeating? Or take a sip.",
  "Spill: Which unusual venue would you enjoy using for a respectful celebration? Or take a sip.",
  "Spill: What single detail would you prioritize on a very small party budget? Or take a sip.",
  "Spill: Which kind of farewell would leave every guest feeling appreciated? Or take a sip.",
  "Spill: What legacy would you want a recurring gathering to build over time? Or take a sip.",
  "Spill: Which future party idea are you already eager to make real? Or take a sip.",
]
