export const SIP_OR_SPILL_DRINKING: readonly string[] = [
  "Spill: What is your favorite drink to order when you want something familiar? Or take a sip.",
  "Spill: Which drink do you enjoy more for its flavor than its reputation? Or take a sip.",
  "Spill: What beverage did you expect to dislike but ended up enjoying? Or take a sip.",
  "Spill: Which popular drink has never lived up to the hype for you? Or take a sip.",
  "Spill: What flavor makes a drink instantly appealing to you? Or take a sip.",
  "Spill: Which flavor do you avoid whenever you read it on a drinks menu? Or take a sip.",
  "Spill: What is your ideal balance between sweet, sour, bitter, and savory in a drink? Or take a sip.",
  "Spill: Which drink tastes best to you with plenty of ice? Or take a sip.",
  "Spill: What is your opinion on drinks served warm? Or take a sip.",
  "Spill: Which fizzy drink would you choose over a still one? Or take a sip.",
  "Spill: What garnish do you actually enjoy eating or smelling? Or take a sip.",
  "Spill: Which garnish would you happily leave out of every drink? Or take a sip.",
  "Spill: What drink ingredient always catches your attention on a menu? Or take a sip.",
  "Spill: Which drink would you choose if the name gave you no clues about it? Or take a sip.",
  "Spill: What is the most refreshing drink you can remember having? Or take a sip.",
  "Spill: Which creamy drink feels most like a dessert to you? Or take a sip.",
  "Spill: What drink do you associate with relaxing at the end of a long day? Or take a sip.",
  "Spill: Which beverage do you prefer in a smaller glass because the flavor is rich? Or take a sip.",
  "Spill: What drink do you think smells better than it tastes? Or take a sip.",
  "Spill: Which drink do you think tastes better than it looks? Or take a sip.",
  "Spill: What unusual drink texture have you genuinely enjoyed? Or take a sip.",
  "Spill: Which drink would you recommend to someone who shares your taste? Or take a sip.",
  "Spill: What beverage do you prefer less sweet than it is usually served? Or take a sip.",
  "Spill: Which drink do you like with an extra squeeze of citrus? Or take a sip.",
  "Spill: What is your most controversial drinks-menu opinion? Or take a sip.",
  "Spill: Which drink do you choose when you cannot decide what to order? Or take a sip.",
  "Spill: What drink have you learned to appreciate over time? Or take a sip.",
  "Spill: Which beverage did your taste buds firmly reject on the first try? Or take a sip.",
  "Spill: What ingredient can rescue an otherwise forgettable drink for you? Or take a sip.",
  "Spill: Which two flavors make your perfect drink combination? Or take a sip.",
  "Spill: What alcohol-free drink feels special enough for a celebration? Or take a sip.",
  "Spill: Which mocktail have you ordered more than once? Or take a sip.",
  "Spill: What makes an alcohol-free option feel thoughtfully made to you? Or take a sip.",
  "Spill: Which soft drink is your reliable choice at a bar? Or take a sip.",
  "Spill: What fruit would be the star of your ideal mocktail? Or take a sip.",
  "Spill: Which herb would you trust in a refreshing alcohol-free drink? Or take a sip.",
  "Spill: What hot beverage would you choose while everyone else has cocktails? Or take a sip.",
  "Spill: Which sparkling water flavor deserves a permanent place in your fridge? Or take a sip.",
  "Spill: What is the best alcohol-free pairing you have had with a meal? Or take a sip.",
  "Spill: Which childhood drink still feels like a treat? Or take a sip.",
  "Spill: What homemade nonalcoholic drink reminds you of family? Or take a sip.",
  "Spill: Which juice blend would you serve at your own gathering? Or take a sip.",
  "Spill: What drink would you invent for someone who dislikes carbonation? Or take a sip.",
  "Spill: Which iced beverage is worth waiting for on a hot day? Or take a sip.",
  "Spill: What alcohol-free nightcap helps you wind down? Or take a sip.",
  "Spill: Which tea makes the best base for a grown-up mocktail? Or take a sip.",
  "Spill: What do you order when you want a drink that is not sugary? Or take a sip.",
  "Spill: Which zero-proof option surprised you with its complexity? Or take a sip.",
  "Spill: What would make you more excited about the alcohol-free section of a menu? Or take a sip.",
  "Spill: Which beverage would you put in a fancy glass just for the presentation? Or take a sip.",
  "Spill: What is your favorite way to make plain water more interesting? Or take a sip.",
  "Spill: Which alcohol-free drink would you bring to a picnic? Or take a sip.",
  "Spill: What frozen beverage would you happily treat as dessert? Or take a sip.",
  "Spill: Which drink proves that a good toast does not need alcohol? Or take a sip.",
  "Spill: What nonalcoholic specialty from another place would you like to try? Or take a sip.",
  "Spill: Which café drink would you order during an evening out? Or take a sip.",
  "Spill: What alcohol-free drink do you wish more venues served well? Or take a sip.",
  "Spill: Which botanical flavor belongs in more zero-proof drinks? Or take a sip.",
  "Spill: What drink would you serve a guest who is skipping alcohol? Or take a sip.",
  "Spill: Which nonalcoholic option makes you feel most included in a toast? Or take a sip.",
  "Spill: What is the first cocktail you remember genuinely liking? Or take a sip.",
  "Spill: Which classic cocktail would you most like to learn how to make? Or take a sip.",
  "Spill: What cocktail name sounds more appealing than the actual recipe? Or take a sip.",
  "Spill: Which classic drink would you reinvent with a different main flavor? Or take a sip.",
  "Spill: What cocktail do you judge a bar by when you see it on the menu? Or take a sip.",
  "Spill: Which frozen cocktail feels most connected to a holiday? Or take a sip.",
  "Spill: What is the most beautifully presented cocktail you have seen? Or take a sip.",
  "Spill: Which cocktail would you order solely because of its aroma? Or take a sip.",
  "Spill: What spirit-forward drink do you prefer to savor slowly? Or take a sip.",
  "Spill: Which cocktail tastes like a season to you? Or take a sip.",
  "Spill: What drink would you choose from a menu organized only by mood? Or take a sip.",
  "Spill: Which cocktail ingredient have you only recently discovered? Or take a sip.",
  "Spill: What twist on a familiar cocktail has impressed you? Or take a sip.",
  "Spill: Which cocktail would you rename if you had the chance? Or take a sip.",
  "Spill: What drink would you ask a bartender to make less sweet? Or take a sip.",
  "Spill: Which cocktail feels too elaborate to make at home? Or take a sip.",
  "Spill: What simple mixed drink deserves more respect? Or take a sip.",
  "Spill: Which ingredient makes a cocktail feel luxurious to you? Or take a sip.",
  "Spill: What cocktail would match your current mood? Or take a sip.",
  "Spill: Which drink would you choose for a quiet conversation at the bar? Or take a sip.",
  "Spill: What cocktail glass shape makes a drink look especially inviting? Or take a sip.",
  "Spill: Which menu description has convinced you to try an unfamiliar cocktail? Or take a sip.",
  "Spill: What local ingredient would you feature in a signature cocktail? Or take a sip.",
  "Spill: Which cocktail do you prefer with a zero-proof version available? Or take a sip.",
  "Spill: What drink would you pair with a rainy evening? Or take a sip.",
  "Spill: Which cocktail would suit a sunny afternoon outdoors? Or take a sip.",
  "Spill: What is your favorite cocktail-related word to say? Or take a sip.",
  "Spill: Which drink would you serve in the simplest possible glass? Or take a sip.",
  "Spill: What cocktail flavor profile best matches your personality? Or take a sip.",
  "Spill: Which famous cocktail would you most like to know the origin story of? Or take a sip.",
  "Spill: What detail separates an excellent cocktail from an average one for you? Or take a sip.",
  "Spill: Which type of wine would you choose for a relaxed dinner? Or take a sip.",
  "Spill: What is the most useful thing someone has taught you about tasting wine? Or take a sip.",
  "Spill: Which wine description actually helps you choose a bottle? Or take a sip.",
  "Spill: What food changed your opinion of a particular wine? Or take a sip.",
  "Spill: Which matters more to you in wine, the label or the recommendation? Or take a sip.",
  "Spill: What wine label design would make you stop and look twice? Or take a sip.",
  "Spill: Which occasion calls for sparkling wine in your mind? Or take a sip.",
  "Spill: What is your favorite memory involving a shared bottle at dinner? Or take a sip.",
  "Spill: Which wine region would you enjoy visiting for the scenery and culture? Or take a sip.",
  "Spill: What question would you ask a winemaker if you met one? Or take a sip.",
  "Spill: Which wine term still sounds mysterious to you? Or take a sip.",
  "Spill: What has been your best accidental wine discovery? Or take a sip.",
  "Spill: Which do you prefer for a celebration, bubbles or a favorite still wine? Or take a sip.",
  "Spill: What snack do you think pairs surprisingly well with wine? Or take a sip.",
  "Spill: Which wine would you choose based on season rather than food? Or take a sip.",
  "Spill: What makes a wine tasting feel welcoming instead of intimidating? Or take a sip.",
  "Spill: Which bottle have you kept because the label held a memory? Or take a sip.",
  "Spill: What would you want to learn during a vineyard visit? Or take a sip.",
  "Spill: Which wine rule are you comfortable ignoring? Or take a sip.",
  "Spill: What is your honest reaction when someone describes a wine very dramatically? Or take a sip.",
  "Spill: Which beer style best suits your taste? Or take a sip.",
  "Spill: What was the setting for the best beer you remember having? Or take a sip.",
  "Spill: Which beer name or label has made you laugh? Or take a sip.",
  "Spill: What food would you choose for a beer pairing? Or take a sip.",
  "Spill: Which seasonal beer do you look forward to seeing? Or take a sip.",
  "Spill: What makes a brewery taproom enjoyable for you beyond the drinks? Or take a sip.",
  "Spill: Which ingredient would tempt you to try an unusual beer? Or take a sip.",
  "Spill: What is your opinion on fruit flavors in beer? Or take a sip.",
  "Spill: Which glass would you pick for your favorite beer if presentation mattered? Or take a sip.",
  "Spill: What would you ask a brewer about their process? Or take a sip.",
  "Spill: Which local beer discovery would you recommend to a visitor? Or take a sip.",
  "Spill: What beer style do you think is easiest to pair with a meal? Or take a sip.",
  "Spill: Which cider flavor would you happily order again? Or take a sip.",
  "Spill: What do you prefer in cider, crisp dryness or fruity sweetness? Or take a sip.",
  "Spill: Which food belongs beside a cold cider in your ideal setting? Or take a sip.",
  "Spill: What brewery tour detail would interest you most? Or take a sip.",
  "Spill: Which beer trend are you curious to understand? Or take a sip.",
  "Spill: What nonalcoholic beer has changed your view of the category? Or take a sip.",
  "Spill: Which pub snack makes any drink taste better? Or take a sip.",
  "Spill: What makes you choose a draft option over a bottled one? Or take a sip.",
  "Spill: Which spirit has the most interesting aroma to you? Or take a sip.",
  "Spill: What spirit would you like to understand better without pretending to be an expert? Or take a sip.",
  "Spill: Which whiskey note can you actually recognize when you taste it? Or take a sip.",
  "Spill: What rum-based drink reminds you most of a warm destination? Or take a sip.",
  "Spill: Which gin botanical stands out most clearly to you? Or take a sip.",
  "Spill: What tequila pairing have you enjoyed with food? Or take a sip.",
  "Spill: Which spirit bottle has the most memorable design you have seen? Or take a sip.",
  "Spill: What would you ask someone who distills spirits for a living? Or take a sip.",
  "Spill: Which aged spirit would you compare side by side out of curiosity? Or take a sip.",
  "Spill: What detail about barrel aging do you find most interesting? Or take a sip.",
  "Spill: Which regional spirit would you like to try where it is made? Or take a sip.",
  "Spill: What sipping spirit do you associate with a good story? Or take a sip.",
  "Spill: Which mixer best brings out the flavor of your preferred spirit? Or take a sip.",
  "Spill: What spirit do you think is most misunderstood? Or take a sip.",
  "Spill: Which aroma would you want in a custom botanical gin? Or take a sip.",
  "Spill: What food would you serve at a gentle spirits tasting? Or take a sip.",
  "Spill: Which distillery tradition would you like to see firsthand? Or take a sip.",
  "Spill: What makes a spirit taste smooth to you? Or take a sip.",
  "Spill: Which classic spirit would you use in a homemade infusion? Or take a sip.",
  "Spill: What bottle would you choose as a thoughtful gift for an enthusiast? Or take a sip.",
  "Spill: What was the first drink you learned to make well? Or take a sip.",
  "Spill: Which bartending skill looks easiest until you try it? Or take a sip.",
  "Spill: What ingredient do you always keep available for making drinks at home? Or take a sip.",
  "Spill: Which kitchen tool have you improvised as bar equipment? Or take a sip.",
  "Spill: What homemade syrup flavor would you like to experiment with? Or take a sip.",
  "Spill: Which drink recipe do you know without looking it up? Or take a sip.",
  "Spill: What is the funniest mistake you have made while mixing a drink? Or take a sip.",
  "Spill: Which ice shape would you choose for a home bar? Or take a sip.",
  "Spill: What glassware do you enjoy using even when it is not technically correct? Or take a sip.",
  "Spill: Which fresh ingredient makes home-mixed drinks feel special? Or take a sip.",
  "Spill: What is your best trick for making a simple drink look inviting? Or take a sip.",
  "Spill: Which drink would you batch for guests so you could enjoy their company? Or take a sip.",
  "Spill: What recipe did you improve by adjusting it to your own taste? Or take a sip.",
  "Spill: Which bar tool would you buy first for a beginner setup? Or take a sip.",
  "Spill: What drink-making technique would you like someone to teach you? Or take a sip.",
  "Spill: Which citrus peel makes the most satisfying finishing touch? Or take a sip.",
  "Spill: What is your favorite use for leftover herbs from making drinks? Or take a sip.",
  "Spill: Which homemade drink would you be proud to serve a professional bartender? Or take a sip.",
  "Spill: What is the most useful drink recipe you have saved? Or take a sip.",
  "Spill: Which ingredient would you grow specifically for your home drinks? Or take a sip.",
  "Spill: What drink would you design to represent your hometown? Or take a sip.",
  "Spill: Which three ingredients would define your signature beverage? Or take a sip.",
  "Spill: What name would you give a drink inspired by your personality? Or take a sip.",
  "Spill: Which color would your signature drink be? Or take a sip.",
  "Spill: What kind of glass would complete your signature serve? Or take a sip.",
  "Spill: Which favorite food would inspire an unexpected drink flavor? Or take a sip.",
  "Spill: What song would you pair with your custom drink? Or take a sip.",
  "Spill: Which season would your ideal drink capture? Or take a sip.",
  "Spill: What aroma would greet someone before they tasted your creation? Or take a sip.",
  "Spill: Which memory would you turn into a drink if you could? Or take a sip.",
  "Spill: What would make a drink feel unmistakably like you made it? Or take a sip.",
  "Spill: Which fictional character deserves a thoughtfully named mocktail? Or take a sip.",
  "Spill: What drink would you create for a book club discussion? Or take a sip.",
  "Spill: Which beverage would represent your favorite holiday without being obvious? Or take a sip.",
  "Spill: What ingredient would you use to represent your favorite place? Or take a sip.",
  "Spill: Which two drinks would you combine only in spirit, not literally? Or take a sip.",
  "Spill: What would the menu description of your dream drink say? Or take a sip.",
  "Spill: Which scent from nature would inspire a beverage you would actually try? Or take a sip.",
  "Spill: What drink would you invent for a midnight celebration? Or take a sip.",
  "Spill: Which zero-proof signature drink would carry your name? Or take a sip.",
  "Spill: What is your favorite memory of learning a family drink recipe? Or take a sip.",
  "Spill: Which beverage is part of a celebration tradition in your family? Or take a sip.",
  "Spill: What drink reminds you of a particular relative or chosen-family member? Or take a sip.",
  "Spill: Which holiday beverage do you enjoy mainly because of the ritual? Or take a sip.",
  "Spill: What toast or blessing has stayed with you? Or take a sip.",
  "Spill: Which drink tradition from your culture would you enjoy explaining to friends? Or take a sip.",
  "Spill: What beverage do you associate with being welcomed into someone's home? Or take a sip.",
  "Spill: Which family gathering always seems to feature the same drink? Or take a sip.",
  "Spill: What old-fashioned drink deserves a comeback at celebrations? Or take a sip.",
  "Spill: Which seasonal aroma brings back a drinks-related memory? Or take a sip.",
  "Spill: What is the kindest hosting gesture someone has made around drinks? Or take a sip.",
  "Spill: Which recipe would you preserve for the next generation? Or take a sip.",
  "Spill: What beverage marks the start of a holiday for you? Or take a sip.",
  "Spill: Which toast would you make to celebrate an ordinary good day? Or take a sip.",
  "Spill: What drink ritual helps people slow down and connect? Or take a sip.",
  "Spill: Which celebration drink would you adapt so everyone could share it? Or take a sip.",
  "Spill: What tradition makes raising a glass feel meaningful to you? Or take a sip.",
  "Spill: Which drink has a story that matters more than its taste? Or take a sip.",
  "Spill: What would you serve to welcome friends after a long journey? Or take a sip.",
  "Spill: Which beverage belongs at your ideal reunion? Or take a sip.",
  "Spill: What drink have you discovered while traveling that you still remember? Or take a sip.",
  "Spill: Which city would you visit partly for its bar or café culture? Or take a sip.",
  "Spill: What local beverage would you politely try when visiting somewhere new? Or take a sip.",
  "Spill: Which drink has instantly reminded you of a particular destination? Or take a sip.",
  "Spill: What is the most scenic place where you have enjoyed a beverage? Or take a sip.",
  "Spill: Which hotel welcome drink made a memorable first impression? Or take a sip.",
  "Spill: What market ingredient would you bring home for drink experiments? Or take a sip.",
  "Spill: Which region's drinking customs would you like to learn about respectfully? Or take a sip.",
  "Spill: What beverage would you choose while watching a sunset somewhere new? Or take a sip.",
  "Spill: Which travel companion has introduced you to a favorite drink? Or take a sip.",
  "Spill: What is the best drink recommendation you have received from a local? Or take a sip.",
  "Spill: Which souvenir glass or mug tells your best travel story? Or take a sip.",
  "Spill: What destination would inspire you to tour a vineyard, brewery, or distillery? Or take a sip.",
  "Spill: Which train, boat, or rooftop drink setting sounds most appealing? Or take a sip.",
  "Spill: What regional fruit would you love to taste in a drink? Or take a sip.",
  "Spill: Which travel memory begins with someone saying you should try this? Or take a sip.",
  "Spill: What drink would you want waiting after a long day of sightseeing? Or take a sip.",
  "Spill: Which place taught you a new way to enjoy a familiar beverage? Or take a sip.",
  "Spill: What local drinking etiquette have you found interesting? Or take a sip.",
  "Spill: Which destination drink would you recreate for friends back home? Or take a sip.",
  "Spill: What food-and-drink pairing makes a meal feel complete? Or take a sip.",
  "Spill: Which salty snack is your favorite companion to a cold drink? Or take a sip.",
  "Spill: What dessert would you pair with coffee, tea, or a dessert wine? Or take a sip.",
  "Spill: Which spicy food calls for a cooling beverage? Or take a sip.",
  "Spill: What drink would you serve with a homemade brunch? Or take a sip.",
  "Spill: Which cheese would you build a drink pairing around? Or take a sip.",
  "Spill: What unexpected pairing worked far better than you anticipated? Or take a sip.",
  "Spill: Which comfort food deserves its own signature beverage? Or take a sip.",
  "Spill: What drink would you match with your favorite street food? Or take a sip.",
  "Spill: Which pairing would you choose for a movie-night snack? Or take a sip.",
  "Spill: What beverage belongs beside a long, leisurely breakfast? Or take a sip.",
  "Spill: Which drink cuts through a rich meal perfectly for you? Or take a sip.",
  "Spill: What meal would you plan around one exceptional bottle? Or take a sip.",
  "Spill: Which drink would you pair with a dish from your childhood? Or take a sip.",
  "Spill: What food do you enjoy more at a bar than anywhere else? Or take a sip.",
  "Spill: Which picnic food deserves a better beverage pairing? Or take a sip.",
  "Spill: What drink would you bring to a potluck to complement many dishes? Or take a sip.",
  "Spill: Which flavor bridge makes a pairing work for you? Or take a sip.",
  "Spill: What menu pairing would persuade you to try something unfamiliar? Or take a sip.",
  "Spill: Which late-evening snack pairs best with your chosen alcohol-free drink? Or take a sip.",
  "Spill: What makes a bar feel comfortable enough for real conversation? Or take a sip.",
  "Spill: Which matters most in a venue, the music, lighting, seating, or menu? Or take a sip.",
  "Spill: What kind of bar would you choose for catching up with an old friend? Or take a sip.",
  "Spill: Which small detail tells you a host has thought carefully about guests? Or take a sip.",
  "Spill: What is your favorite way to make a drinks table welcoming to everyone? Or take a sip.",
  "Spill: Which background music suits a relaxed evening of shared drinks? Or take a sip.",
  "Spill: What makes you want to return to the same bartender or venue? Or take a sip.",
  "Spill: Which seat do you choose first in a cozy bar? Or take a sip.",
  "Spill: What is the best conversation you remember having over a drink? Or take a sip.",
  "Spill: Which venue would you pick for someone who dislikes loud crowds? Or take a sip.",
  "Spill: What makes a home gathering better than going out for drinks? Or take a sip.",
  "Spill: Which hosting task do you secretly enjoy most? Or take a sip.",
  "Spill: What drink station would you set up so guests could customize their own beverages? Or take a sip.",
  "Spill: Which detail makes a menu easy and enjoyable to explore? Or take a sip.",
  "Spill: What is the nicest non-drink amenity you have found at a bar? Or take a sip.",
  "Spill: Which venue theme would delight you without feeling gimmicky? Or take a sip.",
  "Spill: What makes ordering at a busy bar less stressful for you? Or take a sip.",
  "Spill: Which type of glassware makes a table look festive? Or take a sip.",
  "Spill: What would your dream neighborhood bar be known for? Or take a sip.",
  "Spill: Which welcoming phrase from a host immediately puts you at ease? Or take a sip.",
  "Spill: What helps you feel comfortable declining alcohol in a group? Or take a sip.",
  "Spill: Which response makes someone feel respected when they choose a soft drink? Or take a sip.",
  "Spill: What is your favorite polite way to turn down a drink you do not want? Or take a sip.",
  "Spill: Which sign tells you a venue takes guest wellbeing seriously? Or take a sip.",
  "Spill: What boundary around drinking are you glad you learned to keep? Or take a sip.",
  "Spill: Which hosting habit removes pressure from choosing whether to drink? Or take a sip.",
  "Spill: What makes it easier to pace an evening in a way that feels good to you? Or take a sip.",
  "Spill: Which nonalcoholic option do you like having within easy reach? Or take a sip.",
  "Spill: What have you learned about listening to your own limits? Or take a sip.",
  "Spill: Which plan helps everyone get home comfortably after a night out? Or take a sip.",
  "Spill: What would you say to a friend who felt awkward about not drinking? Or take a sip.",
  "Spill: Which part of a social night do you enjoy that has nothing to do with alcohol? Or take a sip.",
  "Spill: What makes a designated-driver arrangement feel appreciated and fair? Or take a sip.",
  "Spill: Which cue tells you it is time to switch to water or another alcohol-free option? Or take a sip.",
  "Spill: What is one way friends can look out for each other without being controlling? Or take a sip.",
  "Spill: Which personal rule helps you protect tomorrow's plans? Or take a sip.",
  "Spill: What makes an event enjoyable when you choose not to drink at all? Or take a sip.",
  "Spill: Which assumption about drinking would you like people to stop making? Or take a sip.",
  "Spill: What is the best way a host has supported your beverage choice? Or take a sip.",
  "Spill: Which reminder helps you choose what feels right instead of following the crowd? Or take a sip.",
  "Spill: What funny misunderstanding have you had while ordering a drink? Or take a sip.",
  "Spill: Which complicated drink name do you still hesitate to pronounce? Or take a sip.",
  "Spill: What is the most dramatic description you have read on a cocktail menu? Or take a sip.",
  "Spill: Which drink arrived looking completely different from what you imagined? Or take a sip.",
  "Spill: What garnish was so oversized that it became the main event? Or take a sip.",
  "Spill: Which tiny glass has made you wonder where the rest of the drink went? Or take a sip.",
  "Spill: What is the funniest drink-related gift you have received? Or take a sip.",
  "Spill: Which beverage have you accidentally matched with your outfit? Or take a sip.",
  "Spill: What menu typo would make an excellent name for a real drink? Or take a sip.",
];
