export const SIP_OR_SPILL_RELATIONSHIPS: readonly string[] = [
  'Spill: What helps you feel heard when a conversation matters? Or take a sip.',
  'Spill: Which topic do you wish people asked you about more thoughtfully? Or take a sip.',
  'Spill: How do you prefer someone to raise a concern with you? Or take a sip.',
  'Spill: What makes an apology sound sincere to you? Or take a sip.',
  'Spill: When do you need time to think before responding? Or take a sip.',
  'Spill: Which communication habit are you proud of improving? Or take a sip.',
  'Spill: What does a useful relationship check-in look like to you? Or take a sip.',
  'Spill: How can someone tell when you want advice instead of empathy? Or take a sip.',
  'Spill: What question helps you clarify a misunderstanding fastest? Or take a sip.',
  'Spill: Which tone makes difficult feedback easier for you to receive? Or take a sip.',
  'Spill: How do you signal that you are ready to revisit a paused conversation? Or take a sip.',
  'Spill: What do you tend to leave unsaid when you are trying to keep the peace? Or take a sip.',
  'Spill: When has listening changed your first impression of someone? Or take a sip.',
  'Spill: What everyday subject can you happily discuss for hours? Or take a sip.',
  'Spill: How do you prefer to handle important conversations when you are apart? Or take a sip.',
  'Spill: Which assumption about your communication style is usually wrong? Or take a sip.',
  'Spill: What helps you stay curious instead of becoming defensive? Or take a sip.',
  'Spill: How would you like someone to tell you that a joke missed the mark? Or take a sip.',
  'Spill: What is one thing you communicate better in writing than aloud? Or take a sip.',
  'Spill: Which phrase makes you feel reassured during uncertainty? Or take a sip.',
  'Spill: When do you appreciate directness, and when do you prefer gentleness? Or take a sip.',
  'Spill: What makes a silence between two people feel comfortable? Or take a sip.',
  'Spill: How do you know a conversation has reached a real resolution? Or take a sip.',
  'Spill: Which small detail do you notice when someone is truly paying attention? Or take a sip.',
  'Spill: What would make group conversations more accessible for you? Or take a sip.',
  'Spill: How do you respond when you realize you misunderstood someone? Or take a sip.',
  'Spill: What kind of follow-up question makes you feel known? Or take a sip.',
  'Spill: When do you find humor helpful in a serious conversation? Or take a sip.',
  'Spill: What is a kind way someone has corrected you? Or take a sip.',
  'Spill: Which communication skill would you like to practice next? Or take a sip.',
  'Spill: What ordinary gesture makes you feel especially cared for? Or take a sip.',
  'Spill: How do you most naturally show affection without words? Or take a sip.',
  'Spill: Which compliment has stayed with you for good reasons? Or take a sip.',
  'Spill: What kind of quality time leaves you feeling restored? Or take a sip.',
  'Spill: How do you like affection to change when you are stressed? Or take a sip.',
  'Spill: What tiny act of thoughtfulness can transform your day? Or take a sip.',
  'Spill: Which shared ritual would make a relationship feel warmer? Or take a sip.',
  'Spill: What makes praise feel genuine rather than automatic? Or take a sip.',
  'Spill: How do you prefer to celebrate someone you care about? Or take a sip.',
  'Spill: What memory makes you feel grateful for a past or present connection? Or take a sip.',
  'Spill: Which form of affection do you enjoy giving more than receiving? Or take a sip.',
  'Spill: What does being emotionally present look like in an ordinary week? Or take a sip.',
  'Spill: How can someone support you on a day when words feel tiring? Or take a sip.',
  'Spill: How do you help a newcomer relax without putting them on the spot? Or take a sip.',
  'Spill: Which low-key date would feel surprisingly special to you? Or take a sip.',
  'Spill: When have you felt appreciated for something others often overlook? Or take a sip.',
  'Spill: What makes a goodbye feel caring without becoming dramatic? Or take a sip.',
  'Spill: How do you like to reconnect after a busy stretch? Or take a sip.',
  'Spill: Which affectionate nickname, if any, would you actually enjoy? Or take a sip.',
  'Spill: What kind of surprise feels considerate rather than overwhelming? Or take a sip.',
  'Spill: How do you show care when someone is working toward a goal? Or take a sip.',
  'Spill: What shared comfort could become a rainy-day tradition? Or take a sip.',
  'Spill: Which personal achievement would you want a partner to remember? Or take a sip.',
  'Spill: What makes you feel included in someone else\'s life? Or take a sip.',
  'Spill: How do you prefer to receive encouragement before a difficult moment? Or take a sip.',
  'Spill: What makes spending quiet time together feel connected? Or take a sip.',
  'Spill: Which thoughtful message would you love to receive unexpectedly? Or take a sip.',
  'Spill: What is a caring habit you learned from someone important to you? Or take a sip.',
  'Spill: How would you design an affection-filled day that costs almost nothing? Or take a sip.',
  'Spill: What helps affection feel safe, mutual, and unforced for you? Or take a sip.',
  'Spill: Which boundary became easier to name as you got older? Or take a sip.',
  'Spill: How do you want someone to respond when you change your mind? Or take a sip.',
  'Spill: What personal space do you need even in a close relationship? Or take a sip.',
  'Spill: Which social situation makes you most appreciate having an exit plan? Or take a sip.',
  'Spill: How can a partner check in without making you feel monitored? Or take a sip.',
  'Spill: What does respecting your privacy look like day to day? Or take a sip.',
  'Spill: When do you prefer an invitation over an assumption? Or take a sip.',
  'Spill: What is your clearest sign that you need a break from a conversation? Or take a sip.',
  'Spill: How would you handle a boundary that differs from your own? Or take a sip.',
  'Spill: Which part of your routine do you like to keep independent? Or take a sip.',
  'Spill: What makes it easier for you to say no without guilt? Or take a sip.',
  'Spill: How should someone ask before sharing your news with others? Or take a sip.',
  'Spill: What digital boundary matters most to you in a relationship? Or take a sip.',
  'Spill: When is it important to ask before offering physical affection? Or take a sip.',
  'Spill: What would a respectful response to rejection sound like? Or take a sip.',
  'Spill: How do you prefer to set expectations before a social event? Or take a sip.',
  'Spill: Which boundary do people sometimes mistake for a lack of care? Or take a sip.',
  'Spill: What helps you trust that a yes is enthusiastic and freely given? Or take a sip.',
  'Spill: How would you address a friend who kept pushing someone\'s limit? Or take a sip.',
  'Spill: What information would you want before agreeing to a new experience? Or take a sip.',
  'Spill: When do you need solitude, even from people you love? Or take a sip.',
  'Spill: What is one boundary you communicate differently across cultures or families? Or take a sip.',
  'Spill: How can plans leave room for everyone to opt out comfortably? Or take a sip.',
  'Spill: What does consent look like in decisions that are not physical? Or take a sip.',
  'Spill: Which expectation should never be treated as automatic in a relationship? Or take a sip.',
  'Spill: How do you react when someone states a limit you did not expect? Or take a sip.',
  'Spill: What is a respectful way to revisit a request after circumstances change? Or take a sip.',
  'Spill: When should a couple keep a disagreement private? Or take a sip.',
  'Spill: What helps you honor your own capacity before helping someone else? Or take a sip.',
  'Spill: How do you distinguish compromise from abandoning a boundary? Or take a sip.',
  'Spill: Which difference between two people can make a relationship more interesting? Or take a sip.',
  'Spill: What daily habit would be hardest for you to merge with someone else\'s? Or take a sip.',
  'Spill: How important is punctuality to your sense of compatibility? Or take a sip.',
  'Spill: What role should alone time play in a close partnership? Or take a sip.',
  'Spill: Which approach to money conversations feels healthiest to you? Or take a sip.',
  'Spill: How much planning makes a trip enjoyable rather than rigid for you? Or take a sip.',
  'Spill: What does fairness mean when two people have different resources? Or take a sip.',
  'Spill: Which household task reveals the most about compatibility? Or take a sip.',
  'Spill: How do you feel about partners having very different hobbies? Or take a sip.',
  'Spill: What pace feels right for making plans further into the future? Or take a sip.',
  'Spill: Which value would you need to share with a long-term partner? Or take a sip.',
  'Spill: How should two people decide whose tradition to follow? Or take a sip.',
  'Spill: What kind of social calendar feels balanced to you? Or take a sip.',
  'Spill: Which difference in sleep habits could you navigate with good planning? Or take a sip.',
  'Spill: How would you divide responsibilities when energy levels are unequal? Or take a sip.',
  'Spill: What does supporting separate friendships look like to you? Or take a sip.',
  'Spill: Which future decision deserves an early conversation in dating? Or take a sip.',
  'Spill: How important is sharing a sense of humor in a relationship? Or take a sip.',
  'Spill: What kind of home environment helps you feel settled? Or take a sip.',
  'Spill: Which food preference could become a playful challenge on dates? Or take a sip.',
  'Spill: How do you approach differences in spiritual or cultural practices? Or take a sip.',
  'Spill: What does a healthy balance between spontaneity and reliability look like? Or take a sip.',
  'Spill: Which spending priority says the most about a person\'s values? Or take a sip.',
  'Spill: How should a couple handle different needs for tidiness? Or take a sip.',
  'Spill: What makes a disagreement in taste easy to laugh about? Or take a sip.',
  'Spill: Which life goal would shape your relationship choices most? Or take a sip.',
  'Spill: How do you feel about sharing passwords, calendars, or locations? Or take a sip.',
  'Spill: What kind of ambition fits well with the life you want? Or take a sip.',
  'Spill: Which difference would require patience but not be a dealbreaker? Or take a sip.',
  'Spill: How would you test everyday compatibility before a major commitment? Or take a sip.',
  'Spill: What is the funniest harmless misunderstanding you have had on a date? Or take a sip.',
  'Spill: Which awkward silence taught you something useful? Or take a sip.',
  'Spill: What date plan looked better online than it felt in person? Or take a sip.',
  'Spill: When have nerves made you say something unexpectedly strange? Or take a sip.',
  'Spill: What wardrobe mishap can you laugh about now? Or take a sip.',
  'Spill: Which wrong turn became the best part of an outing? Or take a sip.',
  'Spill: What is your most memorable attempt to impress someone that backfired harmlessly? Or take a sip.',
  'Spill: How would you recover from forgetting your date\'s name for a moment? Or take a sip.',
  'Spill: What is the kindest way someone handled a date with no chemistry? Or take a sip.',
  'Spill: Which restaurant mix-up would make a good story later? Or take a sip.',
  'Spill: When did a failed plan lead to a better conversation? Or take a sip.',
  'Spill: What is the oddest safe place you have waited for a date? Or take a sip.',
  'Spill: Which accidental overdressing or underdressing moment still makes you smile? Or take a sip.',
  'Spill: How would you respond if neither person could decide where to go? Or take a sip.',
  'Spill: What innocent habit have you discovered only after several dates? Or take a sip.',
  'Spill: Which date activity revealed a surprising competitive streak? Or take a sip.',
  'Spill: What would you do if bad weather ruined an outdoor plan? Or take a sip.',
  'Spill: When has a noisy venue made a first conversation hilariously difficult? Or take a sip.',
  'Spill: What polite escape line have you used when a date needed to end? Or take a sip.',
  'Spill: Which small mistake instantly made a date feel more human? Or take a sip.',
  'Spill: How would you handle realizing you had both planned the same surprise? Or take a sip.',
  'Spill: What is your funniest experience with a confusing dress code? Or take a sip.',
  'Spill: Which question sounded clever in your head but landed awkwardly? Or take a sip.',
  'Spill: When did technology complicate an otherwise simple date? Or take a sip.',
  'Spill: What would help you reset after arriving at the wrong meeting spot? Or take a sip.',
  'Spill: Which shared embarrassment helped two people relax around each other? Or take a sip.',
  'Spill: How do you recover when a carefully chosen activity is unexpectedly closed? Or take a sip.',
  'Spill: What date story gets funnier each time you tell it? Or take a sip.',
  'Spill: Which first impression did you later revise completely? Or take a sip.',
  'Spill: How would you kindly address spinach in someone\'s teeth during a date? Or take a sip.',
  'Spill: What is your first instinct when a disagreement begins? Or take a sip.',
  'Spill: Which repair attempt has made you feel genuinely valued? Or take a sip.',
  'Spill: How do you separate the current problem from older frustrations? Or take a sip.',
  'Spill: What helps you lower the temperature of a tense exchange? Or take a sip.',
  'Spill: When is taking a pause more caring than continuing to talk? Or take a sip.',
  'Spill: What should happen after someone accepts an apology? Or take a sip.',
  'Spill: How do you rebuild trust after a small broken promise? Or take a sip.',
  'Spill: Which conflict habit would you never want to normalize? Or take a sip.',
  'Spill: What does taking responsibility while preserving self-respect sound like? Or take a sip.',
  'Spill: How can two people disagree without recruiting others to take sides? Or take a sip.',
  'Spill: When has a sincere clarification prevented an argument? Or take a sip.',
  'Spill: What detail matters most when making amends? Or take a sip.',
  'Spill: How would you restart a conversation that ended badly? Or take a sip.',
  'Spill: Which issue is better solved by a practical change than a long discussion? Or take a sip.',
  'Spill: What helps you recognize when being right is not the real goal? Or take a sip.',
  'Spill: How should someone respond after unintentionally crossing a line? Or take a sip.',
  'Spill: When does forgiveness need more time than an apology? Or take a sip.',
  'Spill: What is one sign that a conflict has become unproductive? Or take a sip.',
  'Spill: How do you want reassurance after a misunderstanding? Or take a sip.',
  'Spill: Which small action can show that change is actually happening? Or take a sip.',
  'Spill: What makes compromise feel fair after a disagreement? Or take a sip.',
  'Spill: How would you acknowledge hurt even if your intention was different? Or take a sip.',
  'Spill: When is it useful to agree on a time to revisit an unresolved issue? Or take a sip.',
  'Spill: What have you learned from a conflict you handled well? Or take a sip.',
  'Spill: How do you prevent sarcasm from replacing an honest answer? Or take a sip.',
  'Spill: Which words help you own your part in a problem? Or take a sip.',
  'Spill: What does a fair reset look like after both people make mistakes? Or take a sip.',
  'Spill: How would you repair a moment when someone felt dismissed? Or take a sip.',
  'Spill: When should a recurring disagreement prompt outside support? Or take a sip.',
  'Spill: What helps a repaired relationship become stronger rather than merely quieter? Or take a sip.',
  'Spill: Which relationship belief have you outgrown? Or take a sip.',
  'Spill: What has taught you to choose people more carefully? Or take a sip.',
  'Spill: How has your definition of closeness changed over time? Or take a sip.',
  'Spill: Which old pattern are you trying not to repeat? Or take a sip.',
  'Spill: What have you learned about asking for what you need? Or take a sip.',
  'Spill: How has a friendship shaped the way you approach romance? Or take a sip.',
  'Spill: Which part of receiving care has become easier for you? Or take a sip.',
  'Spill: What relationship lesson arrived later than you wish it had? Or take a sip.',
  'Spill: How do you know when you are growing alongside someone? Or take a sip.',
  'Spill: Which personal change would a younger version of you admire? Or take a sip.',
  'Spill: What experience made you more patient with other people? Or take a sip.',
  'Spill: How has your idea of commitment become more nuanced? Or take a sip.',
  'Spill: Which mistake helped you become a better partner or friend? Or take a sip.',
  'Spill: What are you learning about balancing openness with discernment? Or take a sip.',
  'Spill: How has your approach to conflict matured? Or take a sip.',
  'Spill: Which quality are you actively bringing into your relationships? Or take a sip.',
  'Spill: What have endings taught you about beginning again? Or take a sip.',
  'Spill: How do you want love to support your individuality? Or take a sip.',
  'Spill: Which fear has less influence on your relationships now? Or take a sip.',
  'Spill: What does becoming more emotionally available mean to you? Or take a sip.',
  'Spill: How have you become better at noticing your own limits? Or take a sip.',
  'Spill: Which relationship skill did you learn outside of dating? Or take a sip.',
  'Spill: What have you discovered about the pace at which you trust? Or take a sip.',
  'Spill: How do you make space for someone else to change their mind? Or take a sip.',
  'Spill: Which past disappointment clarified what you value now? Or take a sip.',
  'Spill: What would healthy interdependence look like in your life? Or take a sip.',
  'Spill: How has accountability improved one of your connections? Or take a sip.',
  'Spill: Which new habit could make you more reliable to people you love? Or take a sip.',
  'Spill: What kind of growth would you want a partner to encourage gently? Or take a sip.',
  'Spill: How do you celebrate progress without expecting perfection? Or take a sip.',
  'Spill: What does emotional safety feel like in your body and mind? Or take a sip.',
  'Spill: Which behavior makes it easier for you to trust someone? Or take a sip.',
  'Spill: How do you prefer a partner to respond when you feel anxious? Or take a sip.',
  'Spill: What makes vulnerability feel invited rather than demanded? Or take a sip.',
  'Spill: Which sign tells you that someone respects your perspective? Or take a sip.',
  'Spill: How can people disagree while protecting each other\'s dignity? Or take a sip.',
  'Spill: What helps you feel secure when plans suddenly change? Or take a sip.',
  'Spill: Which promise should be made carefully and kept consistently? Or take a sip.',
  'Spill: How do you want someone to support you through uncertainty? Or take a sip.',
  'Spill: What is a green flag you noticed only with experience? Or take a sip.',
  'Spill: Which action shows that someone takes your feelings seriously? Or take a sip.',
  'Spill: How can reassurance remain honest instead of becoming empty comfort? Or take a sip.',
  'Spill: What makes you feel safe enough to admit you were wrong? Or take a sip.',
  'Spill: Which kind of consistency matters more to you than grand gestures? Or take a sip.',
  'Spill: How should a partner protect confidences shared in vulnerable moments? Or take a sip.',
  'Spill: What would make you comfortable introducing someone to your community? Or take a sip.',
  'Spill: Which response helps when you share something difficult from your past? Or take a sip.',
  'Spill: How do reliable actions change the meaning of reassuring words? Or take a sip.',
  'Spill: What is one way to build trust without rushing closeness? Or take a sip.',
  'Spill: Which sign shows that someone can handle honest feedback? Or take a sip.',
  'Spill: How can a relationship make room for changing access needs? Or take a sip.',
  'Spill: What does being accepted without being idealized mean to you? Or take a sip.',
  'Spill: Which part of trust requires the most patience from you? Or take a sip.',
  'Spill: How do you decide what personal information to share and when? Or take a sip.',
  'Spill: What helps you believe that care will remain during a hard conversation? Or take a sip.',
  'Spill: Which everyday choice can make a relationship feel more equitable? Or take a sip.',
  'Spill: How would you respond if someone disclosed a need you did not understand? Or take a sip.',
  'Spill: What makes a space welcoming to partners of any gender? Or take a sip.',
  'Spill: Which boundary helps trust recover after disappointment? Or take a sip.',
  'Spill: How can someone show curiosity about your identity without making assumptions? Or take a sip.',
  'Spill: What ordinary weekday moment would you gladly relive with someone? Or take a sip.',
  'Spill: Which harmless quirk becomes endearing once you know a person well? Or take a sip.',
  'Spill: How would you spend a free afternoon with no advance plan? Or take a sip.',
  'Spill: What song would belong on the soundtrack of your dating life? Or take a sip.',
  'Spill: Which fictional couple would you invite to dinner for the stories? Or take a sip.',
  'Spill: What snack best represents your approach to relationships, and why? Or take a sip.',
  'Spill: How would you turn an errand into a genuinely fun date? Or take a sip.',
  'Spill: Which board game reveals too much about your personality? Or take a sip.',
  'Spill: What silly tradition would you happily start with a partner? Or take a sip.',
  'Spill: Which weather makes you most want company? Or take a sip.',
  'Spill: How would you plan a date around a shared childhood favorite? Or take a sip.',
  'Spill: What is your most charmingly unrealistic date idea? Or take a sip.',
  'Spill: Which everyday skill would make you useful on a two-person team? Or take a sip.',
  'Spill: What friendly competition could you enjoy without caring who wins? Or take a sip.',
  'Spill: How would you celebrate a completely made-up anniversary? Or take a sip.',
  'Spill: Which local place deserves to become someone\'s favorite date spot? Or take a sip.',
  'Spill: What would your ideal shared playlist sound like? Or take a sip.',
  'Spill: Which tiny inconvenience would you solve with an absurd invention? Or take a sip.',
  'Spill: How would you make a video call feel like a real date? Or take a sip.',
  'Spill: What kind of museum would keep you talking all day? Or take a sip.',
  'Spill: Which meal would you enjoy learning to cook together? Or take a sip.',
  'Spill: What harmless opinion could you defend with unnecessary passion? Or take a sip.',
  'Spill: How would you spend a date if every venue suddenly closed? Or take a sip.',
  'Spill: Which pet personality would best match yours? Or take a sip.',
  'Spill: What small adventure could fit into a regular Tuesday? Or take a sip.',
  'Spill: Which photo from your life comes with the best story? Or take a sip.',
  'Spill: How would you describe your ideal date using only three moods? Or take a sip.',
  'Spill: What unusual class would you try with someone for fun? Or take a sip.',
  'Spill: Which shared joke has made a relationship feel uniquely yours? Or take a sip.',
  'Spill: What playful question would you ask on a first date? Or take a sip.',
  'Spill: Which future hope feels exciting to share with another person? Or take a sip.',
  'Spill: How do you want a relationship to fit around your existing community? Or take a sip.',
  'Spill: What would make a shared home feel like both people belong there? Or take a sip.',
  'Spill: Which tradition would you keep, adapt, or create with a partner? Or take a sip.',
  'Spill: How should two people revisit plans when their goals evolve? Or take a sip.',
  'Spill: What does mutual support look like during a career change? Or take a sip.',
  'Spill: Which dream would you pursue whether partnered or single? Or take a sip.',
  'Spill: How far ahead do you enjoy imagining life with someone? Or take a sip.',
  'Spill: What kind of legacy would you want your relationships to leave? Or take a sip.',
  'Spill: Which annual ritual could help a couple reflect and reconnect? Or take a sip.',
  'Spill: How would you prepare together for a stressful life transition? Or take a sip.',
  'Spill: What place would you love to know slowly with someone? Or take a sip.',
  'Spill: Which shared project could teach two people how they collaborate? Or take a sip.',
  'Spill: How should a relationship adapt when one person needs more care? Or take a sip.',
  'Spill: What does making room for both people\'s ambitions require? Or take a sip.',
  'Spill: Which conversation would help before adopting a pet together? Or take a sip.',
  'Spill: How do you imagine friendships changing within a long-term partnership? Or take a sip.',
  'Spill: What would make a major move feel like a shared decision? Or take a sip.',
  'Spill: Which practical skill would you want both partners to know? Or take a sip.',
  'Spill: How could a couple keep curiosity alive across many years? Or take a sip.',
  'Spill: What does growing old alongside someone mean to you? Or take a sip.',
  'Spill: Which future uncertainty would you rather discuss than avoid? Or take a sip.',
  'Spill: How should partners balance shared savings with personal freedom? Or take a sip.',
  'Spill: What role could chosen family play in your future? Or take a sip.',
  'Spill: Which milestone matters to you even if society rarely celebrates it? Or take a sip.',
  'Spill: How would you protect regular joy during a demanding season? Or take a sip.',
  'Spill: What would a flexible five-year plan include? Or take a sip.',
  'Spill: Which values should guide decisions about caregiving? Or take a sip.',
  'Spill: How might a relationship stay equitable as circumstances change? Or take a sip.',
  'Spill: What future version of yourself do you hope a partner gets to meet? Or take a sip.',
];
