export const SIP_OR_SPILL_FRIENDS: readonly string[] = [
  "Spill: What first made you think we could become real friends? Or take a sip.",
  "Spill: Which friend has shaped your life in a way they may not realize? Or take a sip.",
  "Spill: What quality makes you feel safe enough to be yourself with someone? Or take a sip.",
  "Spill: When do you feel most appreciated by your friends? Or take a sip.",
  "Spill: What small gesture from a friend has stayed with you for years? Or take a sip.",
  "Spill: Which friendship taught you the most about who you want to be? Or take a sip.",
  "Spill: What do you think you contribute to a close friendship? Or take a sip.",
  "Spill: What makes a friendship feel easy without feeling shallow? Or take a sip.",
  "Spill: When have you felt especially proud to call someone your friend? Or take a sip.",
  "Spill: What friendship in your life feels most unexpected? Or take a sip.",

  "Spill: What is your favorite ordinary memory with a friend? Or take a sip.",
  "Spill: Which shared adventure still makes you smile immediately? Or take a sip.",
  "Spill: What harmless mistake became a treasured friendship story? Or take a sip.",
  "Spill: Which meal with friends do you wish you could experience again? Or take a sip.",
  "Spill: What childhood friendship memory can you still picture clearly? Or take a sip.",
  "Spill: Which spontaneous plan with a friend turned out surprisingly well? Or take a sip.",
  "Spill: What is the funniest misunderstanding you have had with a friend? Or take a sip.",
  "Spill: Which quiet moment with friends meant more than a big celebration? Or take a sip.",
  "Spill: What trip or outing brought out the best in your friend group? Or take a sip.",
  "Spill: Which forgotten detail would complete one of your favorite friend stories? Or take a sip.",

  "Spill: What is one thing your friends understand about you without explanation? Or take a sip.",
  "Spill: When do you find it hardest to ask a friend for support? Or take a sip.",
  "Spill: What kind of reassurance helps you most from a friend? Or take a sip.",
  "Spill: How can a friend tell when you need space rather than advice? Or take a sip.",
  "Spill: What part of yourself took time to show your closest friends? Or take a sip.",
  "Spill: What makes you feel truly listened to in a friendship? Or take a sip.",
  "Spill: When have you wished a friend would check in without being asked? Or take a sip.",
  "Spill: What topic do you find easier to discuss with friends than family? Or take a sip.",
  "Spill: How do you prefer friends to respond when you are overwhelmed? Or take a sip.",
  "Spill: What helps you trust that a friend will keep showing up? Or take a sip.",

  "Spill: What is the best advice a friend has given you? Or take a sip.",
  "Spill: Which piece of friendly advice did you ignore and later understand? Or take a sip.",
  "Spill: When do you want honest feedback instead of encouragement? Or take a sip.",
  "Spill: What is a lesson you learned by watching a friend handle difficulty? Or take a sip.",
  "Spill: Which friend has helped you see a problem from a new angle? Or take a sip.",
  "Spill: What advice do your friends often seek from you? Or take a sip.",
  "Spill: When has a friend challenged you in a way that helped you grow? Or take a sip.",
  "Spill: What truth did a friend share gently at exactly the right time? Or take a sip.",
  "Spill: What have your friendships taught you about apologizing? Or take a sip.",
  "Spill: Which habit did you pick up from someone you admire as a friend? Or take a sip.",

  "Spill: What makes you feel included in a group of friends? Or take a sip.",
  "Spill: Which role do you naturally take in group plans? Or take a sip.",
  "Spill: What is one group tradition you would love to start? Or take a sip.",
  "Spill: How do you help a quieter friend feel welcome in a conversation? Or take a sip.",
  "Spill: What makes a group chat feel lively rather than exhausting? Or take a sip.",
  "Spill: When do you enjoy seeing friends one-on-one more than as a group? Or take a sip.",
  "Spill: What is the best way your friend group handles different opinions? Or take a sip.",
  "Spill: Which group plan would you happily repeat every year? Or take a sip.",
  "Spill: What unofficial role would your friends say you fill? Or take a sip.",
  "Spill: How do you know when a new person has become part of the group? Or take a sip.",

  "Spill: What friendship boundary took you time to learn? Or take a sip.",
  "Spill: How do you tell a friend you need time alone? Or take a sip.",
  "Spill: What does respectful disagreement look like between friends? Or take a sip.",
  "Spill: When have you learned not to offer advice unless invited? Or take a sip.",
  "Spill: What expectation can quietly strain a friendship? Or take a sip.",
  "Spill: How would you want a friend to raise a concern with you? Or take a sip.",
  "Spill: What personal boundary are you proud of communicating clearly? Or take a sip.",
  "Spill: When is it kinder to postpone a difficult friendship conversation? Or take a sip.",
  "Spill: What helps you respect a friend's different social limits? Or take a sip.",
  "Spill: How do you handle a friendship when your needs for contact differ? Or take a sip.",

  "Spill: What is your first instinct after a disagreement with a friend? Or take a sip.",
  "Spill: Which apology have you received from a friend that felt sincere? Or take a sip.",
  "Spill: What makes a friendship worth repairing after conflict? Or take a sip.",
  "Spill: How have you learned to disagree without trying to win? Or take a sip.",
  "Spill: When have you needed time before forgiving a friend? Or take a sip.",
  "Spill: What is one conflict habit you are trying to unlearn? Or take a sip.",
  "Spill: How can a friend rebuild your trust after letting you down? Or take a sip.",
  "Spill: What misunderstanding taught you to communicate more clearly? Or take a sip.",
  "Spill: When has taking responsibility strengthened one of your friendships? Or take a sip.",
  "Spill: What helps you know a disagreement has genuinely been resolved? Or take a sip.",

  "Spill: What friendship has changed most as your life circumstances changed? Or take a sip.",
  "Spill: How do you keep a long-distance friendship feeling close? Or take a sip.",
  "Spill: What life transition revealed who your dependable friends were? Or take a sip.",
  "Spill: Which old friend could you reconnect with comfortably after years apart? Or take a sip.",
  "Spill: What friendship survived a change you once worried about? Or take a sip.",
  "Spill: How has your idea of a good friend evolved with age? Or take a sip.",
  "Spill: What do you miss about how you made friends when you were younger? Or take a sip.",
  "Spill: When has a friendship grown stronger through less frequent contact? Or take a sip.",
  "Spill: What is hardest about maintaining friendships during a busy season? Or take a sip.",
  "Spill: Which friendship feels different now in a way you value? Or take a sip.",

  "Spill: What accomplishment by a friend have you loved celebrating? Or take a sip.",
  "Spill: How do you like friends to celebrate your wins? Or take a sip.",
  "Spill: What kind of milestone deserves more recognition among friends? Or take a sip.",
  "Spill: When have you felt inspired rather than compared by a friend's success? Or take a sip.",
  "Spill: What thoughtful way has a friend marked an important day for you? Or take a sip.",
  "Spill: Which friend's courage deserves a celebration of its own? Or take a sip.",
  "Spill: What everyday victory would you tell your friends about first? Or take a sip.",
  "Spill: How do you show genuine excitement for a friend's good news? Or take a sip.",
  "Spill: What shared goal would be fun to complete with friends? Or take a sip.",
  "Spill: Which personal change in a friend are you happiest to have witnessed? Or take a sip.",

  "Spill: What is the kindest thing a friend has done during a hard time? Or take a sip.",
  "Spill: How do you usually notice that a friend is struggling? Or take a sip.",
  "Spill: What practical help from a friend has made a real difference? Or take a sip.",
  "Spill: When has simply sitting with a friend been enough? Or take a sip.",
  "Spill: What supportive phrase do you wish people used more often? Or take a sip.",
  "Spill: How do you care for a friend without taking over their choices? Or take a sip.",
  "Spill: What has a friend done that helped you feel less alone? Or take a sip.",
  "Spill: When are you most comfortable accepting help from friends? Or take a sip.",
  "Spill: What does dependable friendship look like on an ordinary difficult day? Or take a sip.",
  "Spill: How can friends support you while still respecting your independence? Or take a sip.",

  "Spill: What hobby would you enjoy learning alongside a friend? Or take a sip.",
  "Spill: Which friend would make an ideal teammate for a creative project? Or take a sip.",
  "Spill: What activity always brings out your playful side with friends? Or take a sip.",
  "Spill: Which interest introduced you to a meaningful friendship? Or take a sip.",
  "Spill: What skill would your friends be surprised to see you try? Or take a sip.",
  "Spill: Which friend's enthusiasm has made you curious about something new? Or take a sip.",
  "Spill: What low-cost activity makes for an excellent friend date? Or take a sip.",
  "Spill: Which pastime would you happily teach your friends? Or take a sip.",
  "Spill: What would your friend group create if time and talent were unlimited? Or take a sip.",
  "Spill: Which familiar activity becomes better when a particular friend joins? Or take a sip.",

  "Spill: What type of humor makes you feel instantly connected to someone? Or take a sip.",
  "Spill: Which friend can make you laugh without saying a word? Or take a sip.",
  "Spill: What harmless inside joke has lasted far longer than expected? Or take a sip.",
  "Spill: When has laughter helped your friends through an awkward moment? Or take a sip.",
  "Spill: What is your favorite kind of silly conversation with friends? Or take a sip.",
  "Spill: Which friend's storytelling style always entertains you? Or take a sip.",
  "Spill: What ridiculous debate could your friend group revisit forever? Or take a sip.",
  "Spill: Which everyday inconvenience became funny because a friend was there? Or take a sip.",
  "Spill: What phrase from a friend reliably makes you laugh? Or take a sip.",
  "Spill: When have you laughed with a friend until you forgot the original joke? Or take a sip.",

  "Spill: What is your ideal unplanned day with friends? Or take a sip.",
  "Spill: Which place would you love to explore with your closest friends? Or take a sip.",
  "Spill: What journey would test your group's teamwork in a fun way? Or take a sip.",
  "Spill: Which friend would be best at planning a relaxed weekend away? Or take a sip.",
  "Spill: What local spot would you choose for a friendship reunion? Or take a sip.",
  "Spill: Which travel habit makes you a good companion? Or take a sip.",
  "Spill: What is your favorite way to balance group plans and solo time on a trip? Or take a sip.",
  "Spill: Which friend would stay calmest if an itinerary changed unexpectedly? Or take a sip.",
  "Spill: What destination matches your friend group's shared energy? Or take a sip.",
  "Spill: What would make a simple day trip memorable for you? Or take a sip.",

  "Spill: What annual tradition matters most in one of your friendships? Or take a sip.",
  "Spill: Which new ritual could help your friends stay connected? Or take a sip.",
  "Spill: What recurring plan do you always look forward to? Or take a sip.",
  "Spill: Which friendship anniversary would be meaningful to celebrate? Or take a sip.",
  "Spill: What food tradition belongs uniquely to your friend group? Or take a sip.",
  "Spill: How have friends made a holiday feel more like home? Or take a sip.",
  "Spill: What tradition would you preserve even if everyone moved away? Or take a sip.",
  "Spill: Which seasonal activity brings your friends together? Or take a sip.",
  "Spill: What tiny ritual signals that a friend visit has truly begun? Or take a sip.",
  "Spill: Which old tradition are you ready to reinvent with friends? Or take a sip.",

  "Spill: What first impression of a friend turned out to be completely wrong? Or take a sip.",
  "Spill: Which friendship began in the least likely setting? Or take a sip.",
  "Spill: What question helps you move beyond small talk with someone new? Or take a sip.",
  "Spill: When did an acquaintance begin to feel like a genuine friend? Or take a sip.",
  "Spill: What makes you want to know someone better? Or take a sip.",
  "Spill: Which friendship began because one of you took a small social risk? Or take a sip.",
  "Spill: What shared circumstance has introduced you to great friends? Or take a sip.",
  "Spill: How do you show a new friend that you would like to meet again? Or take a sip.",
  "Spill: What helps you feel comfortable in a room where you know nobody? Or take a sip.",
  "Spill: Which unlikely similarity has sparked a friendship for you? Or take a sip.",

  "Spill: What do you value most in a friend who lives differently from you? Or take a sip.",
  "Spill: How has a friend broadened your understanding of the world? Or take a sip.",
  "Spill: What difference between friends can make a bond stronger? Or take a sip.",
  "Spill: When has curiosity helped you avoid judging a friend's choice? Or take a sip.",
  "Spill: What have you learned from a friend of another generation? Or take a sip.",
  "Spill: Which friend has introduced you to a tradition meaningful to them? Or take a sip.",
  "Spill: How do you make room for different communication styles in friendship? Or take a sip.",
  "Spill: What assumption about friendship has someone helped you reconsider? Or take a sip.",
  "Spill: When have different strengths made you and a friend an effective team? Or take a sip.",
  "Spill: What viewpoint from a friend has stayed with you even without changing your mind? Or take a sip.",

  "Spill: What does loyalty mean to you when friends disagree? Or take a sip.",
  "Spill: When has a friend defended your dignity without speaking for you? Or take a sip.",
  "Spill: What promise between friends should never be made casually? Or take a sip.",
  "Spill: How do you balance loyalty with telling a friend a difficult truth? Or take a sip.",
  "Spill: What action makes someone feel reliably in your corner? Or take a sip.",
  "Spill: When have you chosen fairness over taking a friend's side automatically? Or take a sip.",
  "Spill: What makes you confident that a friend respects your confidence? Or take a sip.",
  "Spill: How can friends show loyalty without excluding other people? Or take a sip.",
  "Spill: What does keeping your word look like in everyday friendship? Or take a sip.",
  "Spill: Which act of consistency matters more to you than a grand gesture? Or take a sip.",

  "Spill: What makes someone an excellent host among friends? Or take a sip.",
  "Spill: How do you help a new guest feel part of the gathering? Or take a sip.",
  "Spill: What is your favorite way to spend time together without spending much? Or take a sip.",
  "Spill: Which detail makes a casual hangout feel thoughtful? Or take a sip.",
  "Spill: What kind of gathering suits your social energy best? Or take a sip.",
  "Spill: How do you contribute when a friend hosts everyone? Or take a sip.",
  "Spill: What makes a shared meal feel special among friends? Or take a sip.",
  "Spill: Which cozy setting invites the best friend conversations? Or take a sip.",
  "Spill: What is your ideal number of people for a relaxed hangout? Or take a sip.",
  "Spill: How do you know when it is time to wrap up a good gathering? Or take a sip.",

  "Spill: Which friend understands your taste in music best? Or take a sip.",
  "Spill: What film or show became meaningful because you shared it with friends? Or take a sip.",
  "Spill: Which song instantly takes you back to a friendship memory? Or take a sip.",
  "Spill: What book would you most enjoy discussing with a friend? Or take a sip.",
  "Spill: Which fictional friendship reminds you of one in your own life? Or take a sip.",
  "Spill: What recommendation from a friend became a lasting favorite? Or take a sip.",
  "Spill: Which friend would curate the best playlist for your current mood? Or take a sip.",
  "Spill: What shared favorite can always restart a stalled conversation? Or take a sip.",
  "Spill: Which piece of art would you love to experience beside a friend? Or take a sip.",
  "Spill: What popular favorite do your friends enjoy even though you do not? Or take a sip.",

  "Spill: What is your most recognizable habit as a friend? Or take a sip.",
  "Spill: Which minor quirk do your friends lovingly tease you about? Or take a sip.",
  "Spill: What habit from a friend has become oddly comforting? Or take a sip.",
  "Spill: Which friend is most likely to remember a tiny detail you mentioned? Or take a sip.",
  "Spill: What predictable choice would your friends correctly make on your behalf? Or take a sip.",
  "Spill: Which everyday task reveals the biggest differences between you and a friend? Or take a sip.",
  "Spill: What is something friends know never to rush you through? Or take a sip.",
  "Spill: Which personal routine becomes more enjoyable with company? Or take a sip.",
  "Spill: What phrase do you say so often that friends could imitate you? Or take a sip.",
  "Spill: Which friend's harmless habit would you notice immediately if it disappeared? Or take a sip.",

  "Spill: What kind of message from a friend brightens your day? Or take a sip.",
  "Spill: How quickly do you usually reply when a friend reaches out? Or take a sip.",
  "Spill: What conversation is better face-to-face than by message? Or take a sip.",
  "Spill: Which communication habit helps a friendship survive busy weeks? Or take a sip.",
  "Spill: How do you signal that a message needs no immediate response? Or take a sip.",
  "Spill: What makes a voice note feel personal rather than inconvenient? Or take a sip.",
  "Spill: When do you prefer a phone call from a friend? Or take a sip.",
  "Spill: What is the longest-running friendly conversation in your messages about? Or take a sip.",
  "Spill: How do you reconnect after accidentally leaving a message unanswered? Or take a sip.",
  "Spill: What digital habit makes you feel closer to faraway friends? Or take a sip.",

  "Spill: What does showing up for a friend's important moment mean to you? Or take a sip.",
  "Spill: Which responsibility would you trust a close friend to handle? Or take a sip.",
  "Spill: When has a friend made an inconvenient effort that mattered deeply? Or take a sip.",
  "Spill: What is one dependable thing your friends can expect from you? Or take a sip.",
  "Spill: How do you support a friend whose schedule rarely matches yours? Or take a sip.",
  "Spill: Which small commitment do you take seriously in friendship? Or take a sip.",
  "Spill: What makes you feel comfortable relying on someone? Or take a sip.",
  "Spill: When has a friend followed through in a way you still remember? Or take a sip.",
  "Spill: How do you respond when you cannot keep a plan with a friend? Or take a sip.",
  "Spill: What kind of reliability matters most during a stressful week? Or take a sip.",

  "Spill: What friendship fear have you become better at managing? Or take a sip.",
  "Spill: When do you worry that you are asking too much of a friend? Or take a sip.",
  "Spill: What helps you handle feeling left out without assuming the worst? Or take a sip.",
  "Spill: How do you work through comparison when a friend reaches a goal first? Or take a sip.",
  "Spill: What insecurity becomes quieter around your closest friends? Or take a sip.",
  "Spill: When has a friend helped you feel welcome as your full self? Or take a sip.",
  "Spill: What makes it easier to admit you misunderstood a social situation? Or take a sip.",
  "Spill: How do you reassure yourself when a friend needs distance? Or take a sip.",
  "Spill: What would help you feel safer expressing disappointment to a friend? Or take a sip.",
  "Spill: Which friendship concern became smaller once you discussed it openly? Or take a sip.",

  "Spill: What dream would you trust your friends to encourage seriously? Or take a sip.",
  "Spill: Which future milestone do you hope your friends are there to witness? Or take a sip.",
  "Spill: What kind of life do you imagine sharing with a lasting community of friends? Or take a sip.",
  "Spill: Which friend would you enjoy learning something new with years from now? Or take a sip.",
  "Spill: What future tradition would keep your friendships connected? Or take a sip.",
  "Spill: How would you like your friendships to grow over the next five years? Or take a sip.",
  "Spill: What project would be meaningful to build with friends someday? Or take a sip.",
  "Spill: Which place do you hope to revisit with old friends later in life? Or take a sip.",
  "Spill: What do you hope your friends remember about this season together? Or take a sip.",
  "Spill: Which shared hope makes you excited about your group's future? Or take a sip.",

  "Spill: What compliment from a friend have you truly believed? Or take a sip.",
  "Spill: Which strength in a friend deserves to be acknowledged more often? Or take a sip.",
  "Spill: What do your friends appreciate about you that you sometimes overlook? Or take a sip.",
  "Spill: When has a friend's belief in you changed what you attempted? Or take a sip.",
  "Spill: What sincere compliment do you find easiest to give friends? Or take a sip.",
  "Spill: Which friend's growth have you had the privilege to notice closely? Or take a sip.",
  "Spill: What part of your personality comes alive around trusted friends? Or take a sip.",
  "Spill: When has a friend recognized effort that others missed? Or take a sip.",
  "Spill: What quality would you want a close friend to remind you that you possess? Or take a sip.",
  "Spill: Which form of appreciation feels most genuine to you? Or take a sip.",

  "Spill: What friendship decision are you glad your younger self made? Or take a sip.",
  "Spill: Which former friendship are you grateful for despite its ending? Or take a sip.",
  "Spill: What have you learned about choosing friends wisely? Or take a sip.",
  "Spill: When did you realize a friendship needed a different shape rather than an ending? Or take a sip.",
  "Spill: What is one way you have become a better friend over time? Or take a sip.",
  "Spill: Which past friendship lesson now guides your closest relationships? Or take a sip.",
  "Spill: What would you tell your younger self about belonging? Or take a sip.",
  "Spill: When have you outgrown a friendship without anyone being at fault? Or take a sip.",
  "Spill: What friendship pattern are you grateful to have broken? Or take a sip.",
  "Spill: Which memory reminds you that a friendship can matter even if it changes? Or take a sip.",

  "Spill: What makes chosen family feel like family to you? Or take a sip.",
  "Spill: Which friend has become part of your home life in a meaningful way? Or take a sip.",
  "Spill: What family-like role does a close friend play in your life? Or take a sip.",
  "Spill: How have friends helped you create a sense of home? Or take a sip.",
  "Spill: What shared responsibility can deepen trust between close friends? Or take a sip.",
  "Spill: Which celebration feels complete only when your friends are included? Or take a sip.",
  "Spill: What does welcoming a friend into your wider community mean to you? Or take a sip.",
  "Spill: When has a friend's household made you feel like one of their own? Or take a sip.",
  "Spill: What value holds your chosen family together? Or take a sip.",
  "Spill: Which act turns friendship into a lasting sense of kinship? Or take a sip.",

  "Spill: What is something you wish friends asked you about more often? Or take a sip.",
  "Spill: Which part of your current life would you enjoy sharing more with friends? Or take a sip.",
  "Spill: What question can reveal a friend's priorities without feeling intrusive? Or take a sip.",
  "Spill: When do you feel most curious about a friend's inner world? Or take a sip.",
  "Spill: What topic could you discuss with a close friend for hours? Or take a sip.",
  "Spill: Which question has led to your most meaningful friendship conversation? Or take a sip.",
  "Spill: What do you want friends to understand about the season you are in? Or take a sip.",
  "Spill: When has a thoughtful question made you feel deeply known? Or take a sip.",
  "Spill: What belief of yours would you enjoy exploring with a trusted friend? Or take a sip.",
  "Spill: Which story about your life do your friends never tire of hearing? Or take a sip.",

  "Spill: What does a restorative day with a friend look like for you? Or take a sip.",
  "Spill: Which friend helps you slow down and notice the moment? Or take a sip.",
  "Spill: What quiet activity feels companionable rather than awkward? Or take a sip.",
  "Spill: How can friends help each other protect time for rest? Or take a sip.",
  "Spill: What environment helps you have an honest conversation with a friend? Or take a sip.",
  "Spill: When have you enjoyed doing separate things in the same room as a friend? Or take a sip.",
  "Spill: What simple plan helps you reset after a demanding week? Or take a sip.",
  "Spill: Which friend makes silence feel comfortable? Or take a sip.",
  "Spill: What is your favorite way to share nature with friends? Or take a sip.",
  "Spill: How do you make room for both connection and rest during a visit? Or take a sip.",

  "Spill: What challenge brought you and a friend closer together? Or take a sip.",
  "Spill: Which team effort revealed a friend's hidden strength? Or take a sip.",
  "Spill: When have friends helped you adapt to an unexpected change? Or take a sip.",
  "Spill: What difficult season strengthened your understanding of friendship? Or take a sip.",
  "Spill: How do you keep a shared problem from becoming a personal conflict? Or take a sip.",
  "Spill: Which friend stays constructive when a plan goes wrong? Or take a sip.",
  "Spill: What have you accomplished because friends kept encouraging you? Or take a sip.",
  "Spill: When has asking a friend for perspective prevented a poor decision? Or take a sip.",
  "Spill: What kind of challenge would you willingly face with your friends beside you? Or take a sip.",
  "Spill: Which shared setback later became evidence of your group's resilience? Or take a sip.",

]
