export const SIP_OR_SPILL_FUNNY = [
  "Spill: What everyday task have you accidentally made much harder than necessary? Or take a sip.",
  "Spill: Which tiny inconvenience turns you into a silent movie villain? Or take a sip.",
  "Spill: What is the funniest way you have misunderstood a simple instruction? Or take a sip.",
  "Spill: When did you confidently walk the wrong way and pretend it was intentional? Or take a sip.",
  "Spill: What harmless mistake do you keep making despite knowing better? Or take a sip.",
  "Spill: Which object have you searched for while it was already in your hand? Or take a sip.",
  "Spill: What is your most memorable battle with stubborn packaging? Or take a sip.",
  "Spill: When have you pushed a door clearly marked pull? Or take a sip.",
  "Spill: What have you dropped at the exact moment everyone went quiet? Or take a sip.",
  "Spill: Which routine errand has produced your best accidental adventure? Or take a sip.",
  "Spill: What harmless shortcut has taken you much longer than the normal route? Or take a sip.",
  "Spill: When have you apologized to a mannequin after bumping into it? Or take a sip.",
  "Spill: What is the silliest reason you have had to retrace your steps? Or take a sip.",
  "Spill: Which minor spill did you clean up with a wildly unsuitable item? Or take a sip.",
  "Spill: What did you assemble incorrectly before finally reading the instructions? Or take a sip.",
  "Spill: When has an automatic door refused to acknowledge you? Or take a sip.",
  "Spill: What ordinary sound have you mistaken for something dramatic? Or take a sip.",
  "Spill: Which chore have you postponed using an impressively creative excuse? Or take a sip.",
  "Spill: What have you worn inside out for far longer than you realized? Or take a sip.",
  "Spill: When did your attempt to save time create an extra job? Or take a sip.",
  "Spill: What is the least useful thing you have done while trying to look busy? Or take a sip.",
  "Spill: Which household item seems to personally dislike you? Or take a sip.",
  "Spill: What is your funniest case of entering a room and forgetting why? Or take a sip.",
  "Spill: When has a shopping basket revealed that your plan was far too ambitious? Or take a sip.",
  "Spill: What is the strangest place you have accidentally left an everyday item? Or take a sip.",
  "Spill: Which small repair became a comedy of errors in your hands? Or take a sip.",
  "Spill: What have you tried to unlock with the wrong key more than once? Or take a sip.",
  "Spill: When did you discover you had been carrying something unnecessary all day? Or take a sip.",
  "Spill: What minor mishap made you look around to see whether anyone noticed? Or take a sip.",
  "Spill: Which ordinary task would your blooper reel feature most often? Or take a sip.",
  "Spill: What meal have you improved only after nearly ruining it? Or take a sip.",
  "Spill: Which ingredient have you confidently forgotten until the final step? Or take a sip.",
  "Spill: What cooking smell promised more than the finished dish delivered? Or take a sip.",
  "Spill: What snack did you hide so well that you lost it yourself? Or take a sip.",
  "Spill: What food have you eaten over the sink to avoid using a plate? Or take a sip.",
  "Spill: Which recipe instruction have you interpreted with unreasonable optimism? Or take a sip.",
  "Spill: What kitchen tool do you use for a purpose its inventor never imagined? Or take a sip.",
  "Spill: When did a food container open much more dramatically than expected? Or take a sip.",
  "Spill: What is your most questionable but genuinely enjoyable snack pairing? Or take a sip.",
  "Spill: Which dish do you make differently every time because you never write it down? Or take a sip.",
  "Spill: What food did you dislike until one surprisingly good bite changed your mind? Or take a sip.",
  "Spill: When have you mistaken salt for sugar or made a similarly harmless mix-up? Or take a sip.",
  "Spill: What is the fanciest name you could give your simplest meal? Or take a sip.",
  "Spill: Which snack creates the loudest possible noise at the quietest possible time? Or take a sip.",
  "Spill: What have you cooked successfully through luck rather than skill? Or take a sip.",
  "Spill: What was your most ambitious attempt to rescue leftovers? Or take a sip.",
  "Spill: What is the funniest substitution you have made when an ingredient was missing? Or take a sip.",
  "Spill: Which food do you eat in a way that would puzzle a polite dinner table? Or take a sip.",
  "Spill: When has a microwave countdown felt like a major suspense film? Or take a sip.",
  "Spill: What treat have you bought for later and immediately eaten? Or take a sip.",
  "Spill: Which meal do you claim is a recipe even though it is mostly assembly? Or take a sip.",
  "Spill: What drink have you forgotten until it reached completely the wrong temperature? Or take a sip.",
  "Spill: What harmless food opinion would make your friends stage a playful intervention? Or take a sip.",
  "Spill: Which cooking attempt produced more dishes than actual food? Or take a sip.",
  "Spill: What is the most dramatic reaction you have had to tasting something unexpectedly spicy? Or take a sip.",
  "Spill: When did you prepare a beautiful plate and then eat directly from the pan? Or take a sip.",
  "Spill: What food order do you rehearse before reaching the counter? Or take a sip.",
  "Spill: Which crumbly snack have you regretted eating over clean clothes? Or take a sip.",
  "Spill: What is your signature meal when effort is officially cancelled? Or take a sip.",
  "Spill: Which baked item emerged from your oven in an unexpected shape? Or take a sip.",
  "Spill: What app do you open automatically before remembering you had no reason to? Or take a sip.",
  "Spill: Which autocorrect replacement made an ordinary message wonderfully confusing? Or take a sip.",
  "Spill: What technology have you fixed by turning it off and on while feeling like an expert? Or take a sip.",
  "Spill: When have you spoken to a device that was not listening? Or take a sip.",
  "Spill: What is the most unnecessary screenshot currently living on your phone? Or take a sip.",
  "Spill: Which device setting have you searched for while looking directly at it? Or take a sip.",
  "Spill: What have you accidentally typed into the wrong chat? Or take a sip.",
  "Spill: When did you discover your camera was on at an awkward but harmless moment? Or take a sip.",
  "Spill: Which notification do you check even when you know exactly what it says? Or take a sip.",
  "Spill: What is your funniest struggle with a voice assistant? Or take a sip.",
  "Spill: Which browser tab have you kept open long enough to become furniture? Or take a sip.",
  "Spill: What online form have you completed twice after forgetting to press submit? Or take a sip.",
  "Spill: When has facial recognition looked at you and politely declined? Or take a sip.",
  "Spill: What harmless typo have you noticed only after receiving a reply? Or take a sip.",
  "Spill: Which cable do you own several of but can never find when needed? Or take a sip.",
  "Spill: What was your most recent accidental pocket photo of? Or take a sip.",
  "Spill: Which update changed one button and briefly ruined your entire routine? Or take a sip.",
  "Spill: When have you tried to zoom in on a printed picture with your fingers? Or take a sip.",
  "Spill: What alarm label from your phone would sound bizarre without context? Or take a sip.",
  "Spill: Which piece of technology makes you feel oddly impatient after three seconds? Or take a sip.",
  "Spill: What search did you abandon because you forgot what you wanted halfway through typing? Or take a sip.",
  "Spill: When did headphones connect to the wrong device at the worst harmless moment? Or take a sip.",
  "Spill: What is the funniest name you have given a Wi-Fi network or device? Or take a sip.",
  "Spill: Which feature did you ignore for years before discovering it was useful? Or take a sip.",
  "Spill: What message have you drafted, overthought, and replaced with a single emoji? Or take a sip.",
  "Spill: When have you refreshed a page as though determination might improve the connection? Or take a sip.",
  "Spill: What is your most chaotic system for organizing digital files? Or take a sip.",
  "Spill: Which gadget did you charge all night without plugging in the wall end? Or take a sip.",
  "Spill: What video-call background detail distracted you from the entire conversation? Or take a sip.",
  "Spill: Which contact have you nearly called while simply trying to scroll? Or take a sip.",
  "Spill: What social greeting do you overthink every single time? Or take a sip.",
  "Spill: When have you introduced yourself to someone you had already met? Or take a sip.",
  "Spill: What name have you avoided saying because you were no longer sure of it? Or take a sip.",
  "Spill: Which goodbye lasted so long that it became a second visit? Or take a sip.",
  "Spill: What is your default response when you did not hear what someone said twice? Or take a sip.",
  "Spill: When has a handshake, wave, or hug negotiation gone hilariously wrong? Or take a sip.",
  "Spill: When did you laugh along before realizing you had missed the joke? Or take a sip.",
  "Spill: What harmless compliment came out much stranger than you intended? Or take a sip.",
  "Spill: Which small-talk question has made your mind instantly empty? Or take a sip.",
  "Spill: What is the oddest thing you have said to fill an unexpected silence? Or take a sip.",
  "Spill: When have you replied to a question that was meant for somebody else? Or take a sip.",
  "Spill: What story have you started before remembering the listener was already there? Or take a sip.",
  "Spill: Which word have you mispronounced with impressive confidence? Or take a sip.",
  "Spill: What is your funniest attempt to leave a conversation gracefully? Or take a sip.",
  "Spill: When have you stood in the wrong queue and committed to it for too long? Or take a sip.",
  "Spill: What casual question have you answered with far too much detail? Or take a sip.",
  "Spill: Which public moment made you suddenly forget how walking normally works? Or take a sip.",
  "Spill: What have you pretended to understand because everyone else nodded? Or take a sip.",
  "Spill: When did you realize halfway through a chat that you had mistaken someone for somebody else? Or take a sip.",
  "Spill: What is the most awkward place you have encountered someone immediately after saying goodbye? Or take a sip.",
  "Spill: Which conversation opener sounded much better in your head? Or take a sip.",
  "Spill: What joke did you explain so thoroughly that it stopped being a joke? Or take a sip.",
  "Spill: When have you held a door for someone who was still very far away? Or take a sip.",
  "Spill: What polite phrase do you accidentally use in completely irrelevant situations? Or take a sip.",
  "Spill: Which social plan did you misunderstand but attend anyway? Or take a sip.",
  "Spill: What is your signature move when you cannot remember where you know someone from? Or take a sip.",
  "Spill: When have you clapped because other people started clapping? Or take a sip.",
  "Spill: What question did you ask moments after someone had already answered it? Or take a sip.",
  "Spill: Which attempt at being subtle was noticed by absolutely everyone? Or take a sip.",
  "Spill: What accidental overshare was thankfully more funny than serious? Or take a sip.",
  "Spill: Which part of your morning routine operates entirely on autopilot? Or take a sip.",
  "Spill: What alarm strategy works briefly before your sleepy self defeats it? Or take a sip.",
  "Spill: When have you prepared to leave early and still arrived late? Or take a sip.",
  "Spill: What is the longest you have carried a clean laundry pile without putting it away? Or take a sip.",
  "Spill: Which chair in your home has quietly become a wardrobe? Or take a sip.",
  "Spill: What bedtime plan regularly turns into one more episode or chapter? Or take a sip.",
  "Spill: Which task do you reward yourself for before actually doing it? Or take a sip.",
  "Spill: What item do you move between surfaces instead of putting away? Or take a sip.",
  "Spill: When have you made a detailed list mainly to avoid starting the work? Or take a sip.",
  "Spill: What is your most elaborate ritual for choosing something to watch? Or take a sip.",
  "Spill: Which habit makes perfect sense to you and nobody else? Or take a sip.",
  "Spill: What part of getting ready takes three minutes on some days and thirty on others? Or take a sip.",
  "Spill: When did a quick tidy become an archaeological investigation? Or take a sip.",
  "Spill: What do you check twice even though you clearly remember checking it once? Or take a sip.",
  "Spill: Which everyday decision do you treat like a major strategic meeting? Or take a sip.",
  "Spill: What unfinished project has become part of your home decor? Or take a sip.",
  "Spill: When have you changed into comfortable clothes much earlier than planned? Or take a sip.",
  "Spill: What is the most optimistic number of errands you have scheduled for one hour? Or take a sip.",
  "Spill: Which personal rule do you invent and immediately break? Or take a sip.",
  "Spill: What object do you keep in a sensible place that you can never remember? Or take a sip.",
  "Spill: When has taking a short break required a much longer recovery from the break? Or take a sip.",
  "Spill: What do you buy repeatedly because you never check whether you already have it? Or take a sip.",
  "Spill: Which routine becomes absurdly complicated when you are running late? Or take a sip.",
  "Spill: What is your funniest example of procrastination disguised as productivity? Or take a sip.",
  "Spill: When have you opened the fridge repeatedly as if new options might appear? Or take a sip.",
  "Spill: What habit would confuse a time traveler observing your day? Or take a sip.",
  "Spill: Which tiny task feels deserving of a parade once you finally finish it? Or take a sip.",
  "Spill: What promise does your evening self keep making to your morning self? Or take a sip.",
  "Spill: When do you become suspiciously motivated to reorganize a drawer? Or take a sip.",
  "Spill: What is the most ridiculous thing you have done to avoid getting up? Or take a sip.",
  "Spill: Which outfit looked better in your imagination than in the mirror? Or take a sip.",
  "Spill: What fashion choice from your past deserves its own apology? Or take a sip.",
  "Spill: When have you dressed perfectly for yesterday's weather? Or take a sip.",
  "Spill: What item of clothing do you keep despite never knowing how to style it? Or take a sip.",
  "Spill: Which accessory has caused more practical trouble than it was worth? Or take a sip.",
  "Spill: What stain did you discover only after spending hours in public? Or take a sip.",
  "Spill: When have you worn uncomfortable shoes and insisted you were fine? Or take a sip.",
  "Spill: What is the strangest thing you have used as an emergency mirror? Or take a sip.",
  "Spill: Which haircut required the most creative explanation? Or take a sip.",
  "Spill: What color did you wear once and immediately retire from your wardrobe? Or take a sip.",
  "Spill: When has a price tag remained attached longer than anyone should admit? Or take a sip.",
  "Spill: What outfit have you changed three times before returning to the first one? Or take a sip.",
  "Spill: Which pocket has surprised you with a forgotten treasure? Or take a sip.",
  "Spill: What garment do you own mainly because it has excellent pockets? Or take a sip.",
  "Spill: When did your attempt at a new hairstyle become an indoor-only experiment? Or take a sip.",
  "Spill: What item have you borrowed and accidentally adopted for far too long? Or take a sip.",
  "Spill: What formal outfit did the weather force you to improvise around? Or take a sip.",
  "Spill: What piece of clothing has survived purely because it is comfortable? Or take a sip.",
  "Spill: When have you discovered two similar-looking shoes were not a matching pair? Or take a sip.",
  "Spill: What trend did you resist until the moment it was nearly over? Or take a sip.",
  "Spill: Which outfit makes you feel overdressed in one room and underdressed in the next? Or take a sip.",
  "Spill: What is your most dramatic wardrobe malfunction involving only a button or zipper? Or take a sip.",
  "Spill: When has static cling created an unexpected fashion partnership? Or take a sip.",
  "Spill: What purchase looked sensible in the fitting room and mysterious at home? Or take a sip.",
  "Spill: Which beloved clothing item is now held together mostly by optimism? Or take a sip.",
  "Spill: What fashion advice do you give confidently but rarely follow yourself? Or take a sip.",
  "Spill: When did a hat solve one problem while creating another? Or take a sip.",
  "Spill: What item did you wear once before realizing it needed constant adjustment? Or take a sip.",
  "Spill: Which old photo contains your boldest style experiment? Or take a sip.",
  "Spill: What clothing label have you ignored until it caused a laundry surprise? Or take a sip.",
  "Spill: What harmless excuse have you used to escape an unnecessary meeting? Or take a sip.",
  "Spill: Which email sign-off feels strangely unlike your actual personality? Or take a sip.",
  "Spill: When have you prepared extensively for a question nobody asked? Or take a sip.",
  "Spill: What obvious answer have you forgotten the moment you were called on? Or take a sip.",
  "Spill: Which notebook did you buy for organization and then refuse to write in? Or take a sip.",
  "Spill: What is the funniest thing you have done while pretending to understand a presentation? Or take a sip.",
  "Spill: When did you realize you had been muted after delivering your best point? Or take a sip.",
  "Spill: What desk snack has accidentally become a full meal? Or take a sip.",
  "Spill: Which simple calculation makes you reach for a calculator every time? Or take a sip.",
  "Spill: What have you written down so quickly that even you could not read it later? Or take a sip.",
  "Spill: When has your confident answer belonged to an entirely different question? Or take a sip.",
  "Spill: What task have you finished just before learning it was optional? Or take a sip.",
  "Spill: Which work phrase would sound most ridiculous in ordinary conversation? Or take a sip.",
  "Spill: What is your least convincing attempt to look attentive? Or take a sip.",
  "Spill: When have you carried the wrong folder or book to the right place? Or take a sip.",
  "Spill: What reminder have you snoozed until it became historical information? Or take a sip.",
  "Spill: Which typo made a formal message accidentally cheerful or dramatic? Or take a sip.",
  "Spill: What is the most unrelated thought that has interrupted your concentration? Or take a sip.",
  "Spill: When have you practiced saying a name before a call and still said it wrong? Or take a sip.",
  "Spill: What simple office machine seems to sense fear? Or take a sip.",
  "Spill: Which meeting could your facial expression have summarized perfectly? Or take a sip.",
  "Spill: What deadline did you remember at the least convenient harmless moment? Or take a sip.",
  "Spill: When have you celebrated finishing something before noticing the final step? Or take a sip.",
  "Spill: What is your funniest reason for having too many tabs or documents open? Or take a sip.",
  "Spill: Which task do you always underestimate despite years of evidence? Or take a sip.",
  "Spill: What phrase have you repeated until it stopped sounding like a real word? Or take a sip.",
  "Spill: When did your carefully planned schedule collapse before breakfast? Or take a sip.",
  "Spill: What is the most impressive doodle you have produced while thinking? Or take a sip.",
  "Spill: Which piece of stationery are you oddly protective of? Or take a sip.",
  "Spill: What harmless mistake taught you to always preview before sending? Or take a sip.",
  "Spill: What destination have you passed because you were enjoying the journey too much? Or take a sip.",
  "Spill: Which bag have you packed with everything except the one essential item? Or take a sip.",
  "Spill: When have you followed someone who only looked like they knew the way? Or take a sip.",
  "Spill: What souvenir seemed brilliant on holiday and baffling at home? Or take a sip.",
  "Spill: Which journey featured your most confidently incorrect sense of direction? Or take a sip.",
  "Spill: What have you carried all day without using once? Or take a sip.",
  "Spill: When did you arrive early enough to question whether you had the correct date? Or take a sip.",
  "Spill: What local custom did you misunderstand in a harmless and funny way? Or take a sip.",
  "Spill: Which travel photo tells a much messier story than it appears to? Or take a sip.",
  "Spill: What is the least practical item you have packed just in case? Or take a sip.",
  "Spill: When has a map made you feel more lost than before you opened it? Or take a sip.",
  "Spill: What snack did you bring for a trip and finish before leaving? Or take a sip.",
  "Spill: Which seat-selection strategy has failed you most spectacularly? Or take a sip.",
  "Spill: What phrase did you learn for a journey but never get a chance to use? Or take a sip.",
  "Spill: When did you unpack and wonder why you brought half your belongings? Or take a sip.",
  "Spill: What landmark have you photographed from an accidentally terrible angle? Or take a sip.",
  "Spill: Which outing turned into an unplanned tour of parking areas? Or take a sip.",
  "Spill: What is your funniest experience of trying to sleep somewhere unfamiliar? Or take a sip.",
  "Spill: When have you waited at the wrong entrance with total confidence? Or take a sip.",
  "Spill: What weather forecast did your outfit completely refuse to believe? Or take a sip.",
  "Spill: Which trip taught you that rolling luggage has strong opinions about pavement? Or take a sip.",
  "Spill: What tourist habit do you pretend not to have? Or take a sip.",
  "Spill: When did a short walk require an unexpected snack break? Or take a sip.",
  "Spill: What item from a hotel or guest room took you too long to figure out? Or take a sip.",
  "Spill: Which route do you keep taking even though it is never actually faster? Or take a sip.",
  "Spill: What was your most confusing encounter with an unfamiliar light switch? Or take a sip.",
  "Spill: When have you packed for every possibility except the one that happened? Or take a sip.",
  "Spill: What announcement have you misheard while travelling? Or take a sip.",
  "Spill: Which journey made you appreciate your own bed in a very dramatic way? Or take a sip.",
  "Spill: What is the silliest nickname you have given an everyday object? Or take a sip.",
  "Spill: Which song do you perform with complete confidence and unreliable lyrics? Or take a sip.",
  "Spill: What fictional character would handle your daily routine worse than you do? Or take a sip.",
  "Spill: When have you narrated an ordinary task as though it were a documentary? Or take a sip.",
  "Spill: What harmless superstition do you follow even while laughing at yourself? Or take a sip.",
  "Spill: Which ordinary object would be the rudest if it could speak? Or take a sip.",
  "Spill: What silly talent are you always slightly too eager to demonstrate? Or take a sip.",
  "Spill: When did you become unexpectedly competitive over something trivial? Or take a sip.",
  "Spill: What imaginary award could you realistically win every year? Or take a sip.",
  "Spill: Which animal best represents you before your first meal of the day? Or take a sip.",
  "Spill: Which small success made you update someone who never requested updates? Or take a sip.",
  "Spill: Which fictional narrator would make your grocery trips sound epic? Or take a sip.",
  "Spill: What household chore deserves a dramatic soundtrack when you do it? Or take a sip.",
  "Spill: Which boring subject can you discuss with suspicious enthusiasm? Or take a sip.",
  "Spill: What completely useless fact occupies valuable space in your memory? Or take a sip.",
  "Spill: When have you created a victory dance for a very minor achievement? Or take a sip.",
  "Spill: What ordinary purchase made you feel far more adult than expected? Or take a sip.",
  "Spill: Which made-up rule governs your choice of mugs, seats, or snacks? Or take a sip.",
  "Spill: What is the funniest debate you have had with yourself? Or take a sip.",
  "Spill: When did you give an object a pep talk because nothing else was working? Or take a sip.",
  "Spill: What sound effect do you add to everyday actions without noticing? Or take a sip.",
  "Spill: Which game do you take much too seriously for someone claiming to have fun? Or take a sip.",
  "Spill: What would your pet or favorite animal gently tease you about? Or take a sip.",
  "Spill: When have you invented a song about what you were doing? Or take a sip.",
  "Spill: What absurd warning label would suit your personality before noon? Or take a sip.",
  "Spill: Which ordinary item would you choose as your extremely unimpressive mascot? Or take a sip.",
  "Spill: What have you applauded even though you were completely alone? Or take a sip.",
  "Spill: When did an inside joke become impossible to explain to anyone else? Or take a sip.",
  "Spill: What is your most specific harmless pet peeve? Or take a sip.",
  "Spill: Which part of your life would make the best low-budget sitcom episode? Or take a sip.",
  "Spill: What childhood belief took you an embarrassingly long time to question? Or take a sip.",
  "Spill: Which playground achievement once made you feel legendary? Or take a sip.",
  "Spill: What snack from your younger years still has unreasonable power over you? Or take a sip.",
  "Spill: When did you take a school project far more seriously than required? Or take a sip.",
  "Spill: What was your funniest attempt to avoid bedtime as a child? Or take a sip.",
  "Spill: Which old hobby would surprise someone who met you recently? Or take a sip.",
  "Spill: What did you collect without ever deciding you were a collector? Or take a sip.",
  "Spill: When have you rediscovered an old note that made no sense at all? Or take a sip.",
  "Spill: What childhood invention were you certain would make you famous? Or take a sip.",
  "Spill: Which old trend did you embrace with maximum commitment? Or take a sip.",
  "Spill: What was your most dramatic reaction to losing a childhood game? Or take a sip.",
  "Spill: When did you first realize adults were sometimes improvising too? Or take a sip.",
  "Spill: What innocent rule did you believe applied everywhere? Or take a sip.",
  "Spill: Which childhood drawing would require the longest explanation now? Or take a sip.",
  "Spill: What funny name did you once give a toy, pet, or imaginary character? Or take a sip.",
  "Spill: When have you tried an old skill and discovered it had quietly vanished? Or take a sip.",
  "Spill: What school-day lunch choice would you happily eat again? Or take a sip.",
  "Spill: Which younger version of you had the boldest hairstyle? Or take a sip.",
  "Spill: What ordinary thing felt like a luxury when you were little? Or take a sip.",
  "Spill: When did a childhood shortcut get you hilariously lost? Or take a sip.",
  "Spill: What family saying did you assume everyone else also used? Or take a sip.",
  "Spill: Which old photo makes you wonder what the occasion possibly was? Or take a sip.",
  "Spill: What childhood fear seems funniest to you now? Or take a sip.",
  "Spill: When did you misunderstand a grown-up phrase in a memorable way? Or take a sip.",
  "Spill: What was your most serious childhood opinion about something completely trivial? Or take a sip.",
  "Spill: Which homemade costume from your past deserves a comeback? Or take a sip.",
  "Spill: What playground rule did your group treat like official law? Or take a sip.",
  "Spill: When have you found a childhood keepsake with a story nobody remembers? Or take a sip.",
  "Spill: What did you proudly learn only to discover everyone else already knew? Or take a sip.",
  "Spill: Which younger-you plan for adulthood turned out the funniest? Or take a sip.",
  "Spill: What purchase have you justified with a reason that convinced nobody, including you? Or take a sip.",
] as const satisfies readonly string[]
