export const SIP_OR_SPILL_SPICY = [
  "Spill: What is the subtlest way you have ever let someone know you were interested? Or take a sip.",
  "Spill: What kind of compliment makes you feel genuinely desired? Or take a sip.",
  "Spill: When did a conversation unexpectedly turn into flirting for you? Or take a sip.",
  "Spill: What is your favorite way to build romantic tension without rushing it? Or take a sip.",
  "Spill: What small gesture instantly makes someone more attractive to you? Or take a sip.",
  "Spill: What is the boldest respectful opening line you have used? Or take a sip.",
  "Spill: How can you tell when your flirting is being welcomed? Or take a sip.",
  "Spill: What makes eye contact feel electric rather than awkward to you? Or take a sip.",
  "Spill: What is a flirting style that always works on you? Or take a sip.",
  "Spill: When have you surprised yourself by making the first move? Or take a sip.",
  "Spill: What harmless excuse have you used to spend more time with a crush? Or take a sip.",
  "Spill: What is the most memorable sincere compliment a date has given you? Or take a sip.",
  "Spill: Which matters more to you at first, playful banter or deep conversation? Or take a sip.",
  "Spill: What trait can turn a casual interest into a serious crush for you? Or take a sip.",
  "Spill: How do you act differently when you are trying not to reveal a crush? Or take a sip.",
  "Spill: What is the clearest hint you have ever missed from someone interested in you? Or take a sip.",
  "Spill: What song best captures the feeling of a new crush for you? Or take a sip.",
  "Spill: What is the most charming way someone has remembered a detail about you? Or take a sip.",
  "Spill: What kind of humor creates instant chemistry for you? Or take a sip.",
  "Spill: What has made you realize friendly teasing had become mutual flirting? Or take a sip.",
  "Spill: What unexpected quality has made you reconsider your usual type? Or take a sip.",
  "Spill: What is your favorite part of the anticipation before a first date? Or take a sip.",
  "Spill: How do you prefer someone to show they find you attractive? Or take a sip.",
  "Spill: What is a quiet sign that you feel safe enough to flirt freely? Or take a sip.",
  "Spill: What is the most appealing kind of confidence in a potential partner? Or take a sip.",
  "Spill: When has a person's voice changed how attractive you found them? Or take a sip.",
  "Spill: What is a nonphysical feature you notice immediately when attraction begins? Or take a sip.",
  "Spill: What ordinary setting has unexpectedly felt romantic to you? Or take a sip.",
  "Spill: How would you describe your flirting style in three words? Or take a sip.",
  "Spill: What makes a flirty exchange feel clever instead of forced? Or take a sip.",
  "Spill: What is the best date invitation you have ever received? Or take a sip.",
  "Spill: What simple first date would let your personality shine? Or take a sip.",
  "Spill: When have first-date nerves led to a surprisingly sweet moment? Or take a sip.",
  "Spill: What question can transform a decent date into a fascinating one? Or take a sip.",
  "Spill: What is your favorite sign that a first date is going exceptionally well? Or take a sip.",
  "Spill: What date activity brings out your most playful side? Or take a sip.",
  "Spill: What detail do you notice first when someone arrives for a date? Or take a sip.",
  "Spill: What is the most spontaneous date you have agreed to? Or take a sip.",
  "Spill: What kind of date makes it easiest for you to open up? Or take a sip.",
  "Spill: What tiny mishap has made a date more memorable in a good way? Or take a sip.",
  "Spill: How soon do you know whether you want a second date? Or take a sip.",
  "Spill: What is your ideal way to end a wonderful first date? Or take a sip.",
  "Spill: What has been your smoothest way of asking for another date? Or take a sip.",
  "Spill: What makes a low-cost date feel luxurious to you? Or take a sip.",
  "Spill: What place would you choose for a date designed around conversation? Or take a sip.",
  "Spill: What is the most thoughtful planning detail a date has included for you? Or take a sip.",
  "Spill: What dating convention would you happily retire? Or take a sip.",
  "Spill: What date idea sounds unromantic but would delight you? Or take a sip.",
  "Spill: What is the best recovery you have seen from an awkward date moment? Or take a sip.",
  "Spill: What makes you feel comfortable being fully yourself on a date? Or take a sip.",
  "Spill: What outfit makes you feel most confident for a romantic evening? Or take a sip.",
  "Spill: What would make you extend a date that was meant to be brief? Or take a sip.",
  "Spill: What food or drink choice tells you something interesting about a date? Or take a sip.",
  "Spill: What is a first-date green flag people rarely mention? Or take a sip.",
  "Spill: What is the kindest way someone has declined another date with you? Or take a sip.",
  "Spill: What would your perfect unplanned date look like? Or take a sip.",
  "Spill: What shared activity makes romantic chemistry easiest to notice? Or take a sip.",
  "Spill: What is a date you would enjoy repeating with a different twist? Or take a sip.",
  "Spill: What conversation topic do you save until a date feels promising? Or take a sip.",
  "Spill: What signals that someone has put genuine thought into seeing you? Or take a sip.",
  "Spill: What profile detail is most likely to make you start a conversation? Or take a sip.",
  "Spill: What is the funniest honest line you could put in a dating bio? Or take a sip.",
  "Spill: What makes an opening message stand out from the usual greetings? Or take a sip.",
  "Spill: What is your preferred moment to move from messages to an actual date? Or take a sip.",
  "Spill: What texting habit makes attraction grow for you? Or take a sip.",
  "Spill: What is the longest you have drafted and redrafted a flirty message? Or take a sip.",
  "Spill: What emoji most closely matches your flirting personality? Or take a sip.",
  "Spill: What kind of voice note would make you instantly smile? Or take a sip.",
  "Spill: What is a digital sign that someone is paying real attention to you? Or take a sip.",
  "Spill: What boundary makes online flirting feel safer for you? Or take a sip.",
  "Spill: What is the best conversation you have had with someone before meeting them? Or take a sip.",
  "Spill: What makes you decide a promising chat should remain only a chat? Or take a sip.",
  "Spill: What is your most reliable clue that text chemistry will work in person? Or take a sip.",
  "Spill: What flirty message did you feel especially proud of sending? Or take a sip.",
  "Spill: What is the sweetest good-morning message you would enjoy receiving? Or take a sip.",
  "Spill: What makes a late-night conversation feel intimate to you? Or take a sip.",
  "Spill: What topic can keep you messaging someone far longer than planned? Or take a sip.",
  "Spill: What is your graceful way of ending a chat that has lost its spark? Or take a sip.",
  "Spill: What online dating assumption has experience proven wrong for you? Or take a sip.",
  "Spill: What is one thing your ideal dating profile would communicate clearly? Or take a sip.",
  "Spill: What makes exchanging playlists feel romantic to you? Or take a sip.",
  "Spill: When has a typo accidentally improved a flirty conversation? Or take a sip.",
  "Spill: What message would make you eager to rearrange your evening for a date? Or take a sip.",
  "Spill: What is the boldest question you are comfortable asking over text? Or take a sip.",
  "Spill: What response tells you someone respects your pace online? Or take a sip.",
  "Spill: What is your favorite way to revive a conversation with mutual interest? Or take a sip.",
  "Spill: What makes a video date feel surprisingly romantic? Or take a sip.",
  "Spill: What is a messaging deal-breaker you learned from experience? Or take a sip.",
  "Spill: What would make you choose a phone call over continued texting? Or take a sip.",
  "Spill: How do you keep digital flirting playful without creating pressure? Or take a sip.",
  "Spill: What is the clearest way someone can ask before kissing you? Or take a sip.",
  "Spill: What makes a first kiss feel worth waiting for? Or take a sip.",
  "Spill: What is your favorite kind of affectionate kiss? Or take a sip.",
  "Spill: When has laughter made a romantic moment even better? Or take a sip.",
  "Spill: What setting would make a mutually wanted kiss especially memorable? Or take a sip.",
  "Spill: What is the most reassuring check-in someone can make while getting closer? Or take a sip.",
  "Spill: What makes a goodbye feel charged with chemistry? Or take a sip.",
  "Spill: What affectionate gesture gives you the strongest butterflies? Or take a sip.",
  "Spill: How do you like a partner to respond when you ask to slow down? Or take a sip.",
  "Spill: What has a kiss revealed to you about a connection? Or take a sip.",
  "Spill: What makes physical affection feel emotionally intimate for you? Or take a sip.",
  "Spill: What is your favorite way to initiate cuddling? Or take a sip.",
  "Spill: What kind of touch feels most comforting after a difficult day? Or take a sip.",
  "Spill: What affectionate habit would you happily make part of every day? Or take a sip.",
  "Spill: What makes holding hands feel surprisingly significant? Or take a sip.",
  "Spill: What is the most romantic moment you have experienced without a kiss? Or take a sip.",
  "Spill: What helps you stay present during an intimate moment? Or take a sip.",
  "Spill: What sign tells you someone is attentive to your comfort? Or take a sip.",
  "Spill: How do you prefer to communicate a change of mind in the moment? Or take a sip.",
  "Spill: What kind of aftercare makes closeness feel complete for you? Or take a sip.",
  "Spill: What makes a slow-burn connection more appealing than instant sparks? Or take a sip.",
  "Spill: What is a tender gesture you find more exciting than a grand display? Or take a sip.",
  "Spill: What does mutually enthusiastic affection look like to you? Or take a sip.",
  "Spill: What helps turn nervousness into comfortable anticipation? Or take a sip.",
  "Spill: What romantic moment made time seem to slow down for you? Or take a sip.",
  "Spill: What form of affection do you prefer to receive in private? Or take a sip.",
  "Spill: What is something you appreciate hearing before intimacy deepens? Or take a sip.",
  "Spill: What makes a partner's restraint especially attractive? Or take a sip.",
  "Spill: What is a respectful way to restart affection after a pause? Or take a sip.",
  "Spill: What does a truly comfortable silence feel like with someone you desire? Or take a sip.",
  "Spill: What boundary conversation has made a connection feel more exciting, not less? Or take a sip.",
  "Spill: How do you prefer to talk about what you want before becoming intimate? Or take a sip.",
  "Spill: What makes you trust that someone will honor a no immediately? Or take a sip.",
  "Spill: What personal limit are you proud of learning to voice? Or take a sip.",
  "Spill: How can a partner make checking in feel natural to you? Or take a sip.",
  "Spill: What does enthusiastic consent sound like in your own words? Or take a sip.",
  "Spill: What makes it easier for you to ask for something you enjoy? Or take a sip.",
  "Spill: How would you want someone to handle a moment of uncertainty? Or take a sip.",
  "Spill: What boundary do you prefer to discuss well before the moment arrives? Or take a sip.",
  "Spill: What response to rejection shows emotional maturity to you? Or take a sip.",
  "Spill: What is one way you show respect after someone changes their mind? Or take a sip.",
  "Spill: What question helps you understand a new partner's comfort level? Or take a sip.",
  "Spill: What does taking things at your pace mean in practice? Or take a sip.",
  "Spill: What makes a conversation about protection feel caring rather than clinical? Or take a sip.",
  "Spill: How do you prefer a partner to raise sexual health before intimacy? Or take a sip.",
  "Spill: What expectation would you always clarify before a casual connection? Or take a sip.",
  "Spill: What is the best way to check whether playful teasing is still welcome? Or take a sip.",
  "Spill: How do you signal that you need emotional reassurance? Or take a sip.",
  "Spill: What helps you distinguish nervous excitement from genuine discomfort? Or take a sip.",
  "Spill: What makes discussing privacy feel like an act of trust? Or take a sip.",
  "Spill: What agreement helps you feel respected after an intimate encounter? Or take a sip.",
  "Spill: How would you define a pressure-free invitation? Or take a sip.",
  "Spill: What makes it safe for you to be honest about inexperience? Or take a sip.",
  "Spill: What is an attractive way someone can admit they are unsure? Or take a sip.",
  "Spill: How do you want mismatched levels of desire to be discussed? Or take a sip.",
  "Spill: What is a healthy boundary you once mistook for distance? Or take a sip.",
  "Spill: What makes direct communication feel sexier than guessing games? Or take a sip.",
  "Spill: What is a considerate way to discuss accessibility during a date? Or take a sip.",
  "Spill: How can someone make room for your answer without influencing it? Or take a sip.",
  "Spill: What is a sign that a person values your dignity as much as the chemistry? Or take a sip.",
  "Spill: What lesson about consent do you wish dating culture taught better? Or take a sip.",
  "Spill: What personality trait has become more attractive to you over time? Or take a sip.",
  "Spill: What surprising talent do you find irresistible? Or take a sip.",
  "Spill: What style choice reliably catches your attention? Or take a sip.",
  "Spill: What kind of intelligence draws you in most strongly? Or take a sip.",
  "Spill: What scent instantly creates a romantic mood for you? Or take a sip.",
  "Spill: What mannerism have you found unexpectedly captivating? Or take a sip.",
  "Spill: What kind of confidence becomes unattractive when overdone? Or take a sip.",
  "Spill: What is an unconventional feature you tend to notice? Or take a sip.",
  "Spill: What does someone do when listening that makes them appealing? Or take a sip.",
  "Spill: What combination of traits makes someone magnetic to you? Or take a sip.",
  "Spill: What skill is particularly attractive to watch someone perform? Or take a sip.",
  "Spill: What fashion era inspires your idea of a perfect date look? Or take a sip.",
  "Spill: What kind of laugh are you most drawn to? Or take a sip.",
  "Spill: What is attractive about someone who is comfortable being silly? Or take a sip.",
  "Spill: What quality matters more to you now than it did five years ago? Or take a sip.",
  "Spill: What physical detail becomes noticeable only after you like someone? Or take a sip.",
  "Spill: What type of creative expression do you find alluring? Or take a sip.",
  "Spill: What everyday act of competence makes you look twice? Or take a sip.",
  "Spill: What kind of kindness makes attraction deepen immediately? Or take a sip.",
  "Spill: What opinion can someone express that makes them more intriguing to you? Or take a sip.",
  "Spill: What is appealing about a person who can laugh at themselves? Or take a sip.",
  "Spill: What balance of mystery and openness attracts you? Or take a sip.",
  "Spill: What quality makes someone beautiful to you regardless of appearance? Or take a sip.",
  "Spill: What accent or speech pattern do you enjoy hearing? Or take a sip.",
  "Spill: What makes emotional self-awareness attractive to you? Or take a sip.",
  "Spill: What sign of independence makes a potential partner stand out? Or take a sip.",
  "Spill: What is your most unexpected romantic type? Or take a sip.",
  "Spill: What shared value creates the strongest attraction for you? Or take a sip.",
  "Spill: What is more seductive to you, curiosity or certainty? Or take a sip.",
  "Spill: What subtle expression on someone's face do you find captivating? Or take a sip.",
  "Spill: What is the bravest romantic truth you have told someone? Or take a sip.",
  "Spill: When have you risked changing a friendship by acknowledging chemistry? Or take a sip.",
  "Spill: What romantic chance are you glad you took? Or take a sip.",
  "Spill: What rejection taught you something valuable about yourself? Or take a sip.",
  "Spill: What made you confess feelings sooner than you expected? Or take a sip.",
  "Spill: When have you chosen clarity over keeping a flirtation ambiguous? Or take a sip.",
  "Spill: What is the most vulnerable part of asking someone out for you? Or take a sip.",
  "Spill: What risk feels worthwhile when chemistry is mutual? Or take a sip.",
  "Spill: When did honesty save you from the wrong romantic situation? Or take a sip.",
  "Spill: What is the boldest romantic decision you made while completely clear-headed? Or take a sip.",
  "Spill: When have you followed attraction outside your usual comfort zone? Or take a sip.",
  "Spill: What helped you return to dating after a difficult ending? Or take a sip.",
  "Spill: When have you been pleasantly wrong about someone's interest in you? Or take a sip.",
  "Spill: What is a romantic opportunity you passed on for the right reasons? Or take a sip.",
  "Spill: What made you give a promising connection another chance? Or take a sip.",
  "Spill: When have you admitted that your feelings had changed? Or take a sip.",
  "Spill: What truth ended uncertainty in a relationship for you? Or take a sip.",
  "Spill: What is the most confident way you have expressed desire? Or take a sip.",
  "Spill: When has patience paid off in your romantic life? Or take a sip.",
  "Spill: What made you realize a crush was better left unpursued? Or take a sip.",
  "Spill: When have you surprised someone by being direct about attraction? Or take a sip.",
  "Spill: What is a romantic leap you would consider taking again? Or take a sip.",
  "Spill: When did you choose self-respect over intense chemistry? Or take a sip.",
  "Spill: What is the kindest romantic risk someone has taken with you? Or take a sip.",
  "Spill: When have you asked a difficult question instead of assuming the answer? Or take a sip.",
  "Spill: What helped you stay open after an awkward romantic moment? Or take a sip.",
  "Spill: When has being turned down actually brought you relief? Or take a sip.",
  "Spill: What is the most honest thing you have said at the end of a date? Or take a sip.",
  "Spill: What would make you pursue a connection despite inconvenient timing? Or take a sip.",
  "Spill: When have you let go of pride to repair romantic tension? Or take a sip.",
  "Spill: What is one desire you became comfortable naming only recently? Or take a sip.",
  "Spill: What does being swept off your feet look like without losing your footing? Or take a sip.",
  "Spill: What romantic fantasy is really about feeling understood? Or take a sip.",
  "Spill: What kind of surprise date would feel tailored perfectly to you? Or take a sip.",
  "Spill: What fictional romance contains a moment you would love to experience? Or take a sip.",
  "Spill: What setting belongs in your ideal romantic getaway? Or take a sip.",
  "Spill: What would your dream slow-dance song be? Or take a sip.",
  "Spill: What is one glamorous date experience you would try once? Or take a sip.",
  "Spill: What cozy romantic scenario appeals to you more than a lavish one? Or take a sip.",
  "Spill: What season best matches your preferred kind of romance? Or take a sip.",
  "Spill: What would make an ordinary weekend feel deliciously romantic? Or take a sip.",
  "Spill: What kind of love letter would you treasure? Or take a sip.",
  "Spill: What would be on the soundtrack to your ideal night with someone special? Or take a sip.",
  "Spill: What romantic cliché would you secretly enjoy living out? Or take a sip.",
  "Spill: What fantasy date would reveal whether you and someone travel well together? Or take a sip.",
  "Spill: What meal would set the scene for your perfect intimate evening? Or take a sip.",
  "Spill: What would your ideal private celebration with a partner include? Or take a sip.",
  "Spill: What is a playful role you like taking in a romantic dynamic? Or take a sip.",
  "Spill: What atmosphere makes you feel most flirtatious? Or take a sip.",
  "Spill: What is one romantic experience you hope is still ahead of you? Or take a sip.",
  "Spill: What kind of shared secret can deepen closeness without harming anyone? Or take a sip.",
  "Spill: What would the perfect reunion after time apart feel like? Or take a sip.",
  "Spill: What destination seems made for falling in love slowly? Or take a sip.",
  "Spill: What fantasy is appealing mainly because it involves total trust? Or take a sip.",
  "Spill: What everyday location would you transform for a romantic surprise? Or take a sip.",
  "Spill: What would make a midnight conversation unforgettable? Or take a sip.",
  "Spill: What kind of dancing makes you feel most connected to a partner? Or take a sip.",
  "Spill: What is the most appealing part of a spontaneous romantic adventure? Or take a sip.",
  "Spill: What dream date would work equally well without spending much money? Or take a sip.",
  "Spill: What romantic scene would you rewrite to include better communication? Or take a sip.",
  "Spill: What does your ideal morning after a wonderful date look like? Or take a sip.",
  "Spill: What makes a casual relationship feel respectful and fulfilling to you? Or take a sip.",
  "Spill: What expectation should always be discussed before becoming exclusive? Or take a sip.",
  "Spill: How do you know when attraction is developing into emotional attachment? Or take a sip.",
  "Spill: What does healthy independence look like inside a passionate relationship? Or take a sip.",
  "Spill: What would make you reconsider keeping a connection casual? Or take a sip.",
  "Spill: How do you prefer to define a relationship without killing the mood? Or take a sip.",
  "Spill: What sign tells you someone is emotionally available? Or take a sip.",
  "Spill: What kind of reassurance matters when a relationship is new? Or take a sip.",
  "Spill: How should two people handle chemistry when they want different futures? Or take a sip.",
  "Spill: What makes exclusivity feel exciting rather than restrictive? Or take a sip.",
  "Spill: What is one thing you need before calling someone your partner? Or take a sip.",
  "Spill: What conversation can reveal whether a situationship has real potential? Or take a sip.",
  "Spill: How do you protect your feelings while still being open to connection? Or take a sip.",
  "Spill: What does consistency add to physical chemistry for you? Or take a sip.",
  "Spill: What is a sign that passion and compatibility are working together? Or take a sip.",
  "Spill: When does mystery stop being intriguing and start feeling evasive? Or take a sip.",
  "Spill: What makes you feel chosen without feeling possessed? Or take a sip.",
  "Spill: How do you want a partner to discuss attraction to other people? Or take a sip.",
  "Spill: What agreement helps long-distance chemistry stay grounded? Or take a sip.",
  "Spill: What is an underrated pleasure of a secure romantic bond? Or take a sip.",
  "Spill: What does commitment allow you to explore more freely? Or take a sip.",
  "Spill: What difference between desire and compatibility took you time to learn? Or take a sip.",
  "Spill: What makes reconnecting with a former flame worth considering? Or take a sip.",
  "Spill: What would you need to know before dating more than one person ethically? Or take a sip.",
  "Spill: How can partners keep novelty alive without creating insecurity? Or take a sip.",
  "Spill: What makes a relationship label meaningful to you? Or take a sip.",
  "Spill: What form of loyalty matters most in an intimate relationship? Or take a sip.",
  "Spill: How do you recognize when chemistry is masking incompatibility? Or take a sip.",
  "Spill: What truth should be shared before feelings become serious? Or take a sip.",
  "Spill: What does romantic freedom mean within clear agreements? Or take a sip.",
  "Spill: What is the healthiest way you have handled jealousy? Or take a sip.",
  "Spill: What tends to trigger romantic insecurity for you? Or take a sip.",
  "Spill: How do you ask for reassurance without making an accusation? Or take a sip.",
  "Spill: What helps you trust a partner's friendships? Or take a sip.",
  "Spill: What is jealousy sometimes trying to tell you about your own needs? Or take a sip.",
  "Spill: How do you cool down before discussing a sensitive attraction issue? Or take a sip.",
  "Spill: What makes a conversation about flirting boundaries productive? Or take a sip.",
  "Spill: What comparison habit have you had to unlearn while dating? Or take a sip.",
  "Spill: How would you want a partner to mention receiving unwanted attention? Or take a sip.",
  "Spill: What helps you separate intuition from insecurity? Or take a sip.",
  "Spill: What is a mature way to discuss an ex who remains in your life? Or take a sip.",
  "Spill: When can a little jealousy feel flattering without becoming controlling? Or take a sip.",
  "Spill: What behavior would make you question a partner's trust in you? Or take a sip.",
  "Spill: How do you respond when a partner needs reassurance you did not anticipate? Or take a sip.",
  "Spill: What agreement about former partners gives you peace of mind? Or take a sip.",
  "Spill: What insecurity becomes easier to manage when named aloud? Or take a sip.",
  "Spill: What is the difference between privacy and secrecy in dating? Or take a sip.",
  "Spill: How do you rebuild trust after a small boundary misunderstanding? Or take a sip.",
  "Spill: What can someone do to make you feel secure without giving up autonomy? Or take a sip.",
  "Spill: What does trusting your partner in a flirty social setting look like? Or take a sip.",
  "Spill: What is a respectful way to disclose a new friendship that might stir insecurity? Or take a sip.",
  "Spill: How can someone own their jealousy without placing blame? Or take a sip.",
  "Spill: What sign tells you reassurance has become a demand for control? Or take a sip.",
  "Spill: What helps you stay curious during a difficult relationship conversation? Or take a sip.",
  "Spill: What does earned trust feel like compared with blind trust? Or take a sip.",
  "Spill: What assumption about jealousy would you challenge? Or take a sip.",
  "Spill: How do you want a partner to react when someone flirts with you? Or take a sip.",
  "Spill: What helps you recover confidence after feeling romantically compared? Or take a sip.",
] as const satisfies readonly string[]
