export const STRANGERS_COLLEAGUES_CONNECT: readonly string[] = [
  'What helps a new collaboration get off to a thoughtful start?',
  'In what way should teammates bring you into a piece of work?',
  'Which early conversation makes working together easier later?',
  'What does a strong handoff look like from your side of the work?',
  'How can collaborators make their expectations easier to understand?',
  'What helps you see how your contribution fits the wider effort?',
  'Where do shared working agreements make the biggest difference?',
  'What would make cross-team work feel less like passing a baton?',
  'When responsibilities overlap, how would you divide the work?',
  'When is asking a teammate for context most comfortable?',
  'Which sign tells you a collaboration is building momentum?',
  'If coordination starts to drift, what could help the group recover?',
  'What kind of preparation makes joint work more productive?',
  'When does pairing with someone improve the work most?',
  'Which practice lets people contribute without duplicating one another?',
  'How would you make ownership visible on a shared project?',
  'What keeps a collaboration balanced when roles carry different constraints?',
  'Which team habit turns individual effort into collective progress?',
  'Where can colleagues clarify dependencies without creating friction?',
  'What is one useful way to close out a collaboration together?',

  'Which channel works best for an important update?',
  'What makes a work message easy for you to act on?',
  'When is a conversation more useful than a written note?',
  'How can someone signal the urgency of a request clearly?',
  'Before responding to a new request, which context do you need?',
  'Which communication habit saves your team the most confusion?',
  'In what terms should a meeting purpose be framed?',
  'What makes an async discussion feel genuinely inclusive?',
  'How can teammates check understanding without sounding repetitive?',
  'What helps you follow a conversation when the topic is unfamiliar?',
  'Where should a team record decisions so people can find them?',
  'When clarification is needed, how might someone interrupt respectfully?',
  'Where should people raise a topic that needs focused attention?',
  'Which details belong in a useful project update?',
  'What makes a question feel easy to answer honestly at work?',
  'How can a speaker leave room for others without losing momentum?',
  'What does good listening look like in a busy workplace?',
  'When has paraphrasing helped a group reach shared understanding?',
  'How could your team make remote conversations easier to enter?',
  'What communication norm would make your workday smoother?',

  'What makes feedback feel useful rather than overwhelming?',
  'What is a considerate way to check whether you are open to feedback?',
  'Which setting helps you consider constructive input clearly?',
  'What kind of example makes feedback easier to understand?',
  'How can feedback stay focused on the work instead of the person?',
  'What helps turn a suggestion into a practical next step?',
  'When is it helpful to hear what is already working?',
  'How would you invite input on an unfinished idea?',
  'When advice does not fit the situation, what helps you say so?',
  'How can colleagues clarify the kind of feedback they want?',
  'What timing makes a debrief most valuable?',
  'Which question opens up a productive feedback conversation?',
  'How can someone offer a different perspective with care?',
  'What helps you separate a rough draft from a final judgment?',
  'After changes are made, how might the team revisit earlier feedback?',
  'What makes peer feedback feel like collaboration?',
  'What keeps critique proportional to the decision at hand?',
  'What is a useful response when feedback needs time to process?',
  'Which acknowledgment feels appropriate after you share input?',
  'What could make everyday feedback more two-way?',

  'What kind of contribution deserves more recognition in most teams?',
  'Which form of workplace appreciation suits you best?',
  'What makes recognition feel specific and sincere?',
  'Which behind-the-scenes effort is easiest for a team to overlook?',
  'How can colleagues celebrate progress without creating pressure?',
  'What is a meaningful way to credit shared work?',
  'When does private appreciation work better than public praise?',
  'Which practice could reveal quiet contributions more consistently?',
  'What should recognition highlight besides the final result?',
  'How can gratitude travel across team boundaries?',
  'What makes a thank-you useful after a difficult piece of work?',
  'Which small act of acknowledgment improves a workday?',
  'How would you recognize someone who made the process better?',
  'What keeps celebration inclusive when many people contributed?',
  'How can leaders share credit in a way that feels fair?',
  'What form of appreciation feels natural among peers?',
  'Where could your workplace create more room to mark milestones?',
  'How does recognition become meaningfully connected to impact?',
  'When an outcome is uncertain, how might experimentation be appreciated?',
  'What would a healthy culture of everyday acknowledgment look like?',

  'How can teammates make workload visible before it becomes a problem?',
  'What information helps you judge whether you can take on a request?',
  'Which sign suggests a team needs to rebalance its commitments?',
  'How would you raise a capacity concern early?',
  'Which conditions support an honest deadline renegotiation?',
  'How can a project plan reflect interruptions and unseen work?',
  'What helps a team distinguish urgent work from merely noisy work?',
  'When priorities compete, what conversation should happen first?',
  'How could colleagues flag bottlenecks without assigning blame?',
  'What does a realistic commitment sound like?',
  'Which recurring task is worth making more visible?',
  'How can a team account for the effort of helping others?',
  'What would make it safer to say that your queue is full?',
  'How should new work enter an already busy plan?',
  'What helps people understand the tradeoffs behind a timeline?',
  'How can teams avoid rewarding hidden overwork?',
  'Where would a simple capacity check improve coordination?',
  'What is a fair way to redistribute work when circumstances change?',
  'How can a teammate offer help without making assumptions?',
  'What question reveals whether a plan is sustainable?',

  'What helps you know it is safe to ask a basic question?',
  'When someone spots a mistake, what response supports openness?',
  'What makes it easier to voice a concern before certainty arrives?',
  'Which leader behavior creates room for honest disagreement?',
  'How should colleagues react when an idea does not work?',
  'What can a meeting host do to welcome a dissenting view?',
  'What behavior shows that changing your mind is allowed?',
  'What response encourages people to share early warnings?',
  'Where could curiosity replace defensiveness in workplace conversations?',
  'How would you repair trust after someone is dismissed in a discussion?',
  'What makes it possible to admit that you need help?',
  'How can uncertainty be named without undermining confidence?',
  'Which team ritual could normalize learning from missteps?',
  'What helps people challenge a process without challenging one another?',
  'How should a group handle a question nobody can answer yet?',
  'What does respectful disagreement sound like in practice?',
  'How can colleagues make room for a cautious voice?',
  'What would show that candor is welcomed consistently?',
  'When tension rises, what helps a conversation remain constructive?',
  'After a difficult meeting, what could rebuild openness?',

  'What helps everyone find an entry point into a group discussion?',
  'How can a meeting include people who need more thinking time?',
  'Which facilitation choice prevents a few voices from dominating?',
  'What makes written participation as valuable as speaking live?',
  'How could a team explain its unwritten rules to newcomers?',
  'What helps people contribute when they are closest to the problem?',
  'How can colleagues avoid mistaking confidence for expertise?',
  'What would make social workplace activities easier to opt into or out of?',
  'When a reference excludes some listeners, what response helps the group?',
  'What is a welcoming way to invite a perspective without putting someone on the spot?',
  'Where can accessibility needs become part of ordinary planning?',
  'Which meeting practice gives quieter contributions more space?',
  'What helps distributed teammates feel equally present?',
  'How can workplace language remain clear across different backgrounds and experiences?',
  'What would make brainstorming safer for unconventional ideas?',
  'How can a group notice whose input is missing without making assumptions?',
  'What makes a team tradition flexible enough for more people?',
  'How should colleagues respond when a name or term is mispronounced?',
  'Where can choice improve participation at work?',
  'Which wording makes a collaboration invitation feel open rather than assigned?',

  'How do you prefer to protect focused work time?',
  'What makes a boundary around availability clear and respectful?',
  'How can colleagues set response-time expectations without creating pressure?',
  'Which requests deserve permission before they become meetings?',
  'Which agreement could help teammates respect different working rhythms?',
  'How would you communicate that a topic needs to wait?',
  'Before taking calendar time, what would a considerate request include?',
  'What would reduce the expectation of being constantly reachable?',
  'When work falls outside current priorities, what supports a clear decline?',
  'Where could clearer boundaries prevent resentment?',
  'How should colleagues handle messages sent outside agreed hours?',
  'What does a healthy boundary around urgency look like?',
  'How can someone revise a boundary when the situation changes?',
  'What helps people ask before offering sensitive advice?',
  'Which workplace norm would protect uninterrupted breaks?',
  'What does honoring a no without demanding an explanation look like?',
  'What would make travel or event participation feel more optional?',
  'How do you signal when you need time to think before answering?',
  'What is a respectful way to end a conversation that has run over?',
  'How can teams plan around time off without making anyone feel guilty?',

  'Which information allows you to participate meaningfully in a decision?',
  'How should a team decide which choices need broad input?',
  'What makes the owner of a decision clear?',
  'What language distinguishes consultation from consensus?',
  'Which decision is worth documenting even if it seems small?',
  'What helps people support a choice they would not have made themselves?',
  'How should new evidence reopen a settled decision?',
  'What makes a decision process feel fair even when time is short?',
  'Before choosing a direction, how might teammates surface tradeoffs?',
  'What role should the people doing the work play in planning it?',
  'When is a reversible experiment better than a long debate?',
  'How would you explain the reasoning behind a difficult choice?',
  'What prevents consultation from becoming performative?',
  'How can disagreement be captured without stalling progress?',
  'Which question helps reveal who will be affected by a decision?',
  'What should happen after a decision is made?',
  'Which review would reveal whether a past choice still serves its purpose?',
  'What would help decisions travel clearly across groups?',
  'How should a decision-maker acknowledge input they did not adopt?',
  'What does appropriate decision speed look like for different kinds of work?',

  'What kind of question helps you learn from a colleague?',
  'How can teammates share expertise without turning it into a lecture?',
  'Which work challenge would benefit from a short learning exchange?',
  'What helps you try a new skill before you feel fully ready?',
  'During delivery, where could colleagues make room for learning?',
  'What makes a demonstration more useful than written instructions?',
  'How can a colleague explain something without assuming prior knowledge?',
  'What would make lessons from a project easier to reuse?',
  'Where does observation teach more than formal training?',
  'How do you like to explore a tool or process that is new to you?',
  'Which habit preserves shared knowledge when responsibilities shift?',
  'Which mistake can become a useful lesson without becoming a label?',
  'How can peers exchange tips without adding another meeting?',
  'What would make asking for a walkthrough feel ordinary?',
  'What should guide the choice of what to learn next?',
  'What creates a good environment for practicing in public?',
  'How can someone check whether their explanation is landing?',
  'Which question turns experience into shareable knowledge?',
  'What could make mentoring feel mutual?',
  'How can colleagues recognize that there may be several valid ways to learn?',

  'What helps you understand where your responsibility begins and ends?',
  'How can overlapping roles become a strength rather than a source of confusion?',
  'Which conversation clarifies ownership when a project changes shape?',
  'What makes an expectation concrete enough to act on?',
  'When work belongs to no obvious role, how should ownership be set?',
  'What context helps you prioritize within your role?',
  'How can colleagues question a responsibility without seeming unhelpful?',
  'Where would a clearer definition of done improve teamwork?',
  'What should happen when authority and accountability do not match?',
  'How can a manager and teammate compare assumptions about a task?',
  'Which part of a role is often invisible to collaborators?',
  'What makes a request clearly different from an assignment?',
  'How would you clarify who has the final call?',
  'What helps temporary responsibilities stay truly temporary?',
  'How can teams prevent helpful people from becoming default owners?',
  'What would make escalation paths easier to understand?',
  'How should responsibilities shift when capacity changes?',
  'What question uncovers a gap between roles?',
  'How can project contributors agree on what completion means?',
  'What does useful role clarity leave flexible?',

  'What kind of support is easiest for a colleague to accept?',
  'How can someone ask what help would be useful without taking over?',
  'When does encouragement matter more than advice?',
  'What makes an offer of help feel genuine and low-pressure?',
  'How would you support a teammate navigating an unfamiliar process?',
  'Which practical resource is most useful to share with a new collaborator?',
  'What helps people name the support they need for a task?',
  'What makes a check-in supportive rather than another obligation?',
  'What does good backup look like during an absence?',
  'When help is politely declined, what response keeps the offer low-pressure?',
  'When would inviting a second pair of eyes feel most natural?',
  'What makes context available before someone has to chase it?',
  'Where could a buddy system reduce avoidable friction?',
  'What is a helpful way to stand beside someone in a challenging meeting?',
  'How can support remain available without becoming surveillance?',
  'Which kind of follow-through builds confidence between colleagues?',
  'What would make onboarding feel more like belonging than information transfer?',
  'What would help someone rejoin a project that kept moving?',
  'What question helps distinguish listening from problem-solving?',
  'How do colleagues create a reliable safety net for shared work?',

  'What helps you do steady work without relying on last-minute heroics?',
  'Where can recovery time fit within demanding periods?',
  'Which routine protects quality when the pace increases?',
  'What would a sustainable deadline-setting conversation include?',
  'How can colleagues notice when a temporary sprint has become the norm?',
  'What makes a workload plan resilient to ordinary surprises?',
  'Where could simplifying a process reduce strain without lowering standards?',
  'Before exhaustion sets in, how could colleagues discuss pace?',
  'What helps people take leave without carrying work with them?',
  'Which recurring meeting would benefit from a fresh purpose check?',
  'Which signals suggest that work no longer adds enough value to continue?',
  'What does sustainable ambition look like in practice?',
  'How would you protect thoughtful work during a busy season?',
  'What makes rest compatible with professionalism?',
  'What would balance planning for maintenance with planning for launches?',
  'Which tradeoff could create a healthier pace?',
  'What helps a group learn when to stop polishing?',
  'How can success be defined without celebrating overextension?',
  'What would make the way your team works more durable?',
  'How should colleagues reset after an intense project?',

  'What question would help two work styles understand each other better?',
  'How can colleagues adapt when one prefers detail and another prefers the headline?',
  'Which difference in approach can improve a team’s thinking?',
  'What helps people discuss working preferences without turning them into labels?',
  'How would you compare preferred levels of structure on a shared task?',
  'Across different planning habits, what makes collaboration smoother?',
  'How can teammates agree on quality when their methods differ?',
  'Where might two contrasting perspectives be complementary?',
  'Which norm prevents one work style from becoming the default?',
  'How should colleagues negotiate different needs for discussion time?',
  'Which shared outcome can unite people with different approaches?',
  'What makes curiosity useful when a teammate’s process is unfamiliar?',
  'How can a pair design a workflow that uses both of their strengths?',
  'What would help colleagues compare preferences before conflict appears?',
  'How can someone explain their process without defending it?',
  'When should collaborators adapt to each other, and when should the system adapt?',
  'When preferences compete, what would a fair resolution involve?',
  'Which meeting formats suit different kinds of work?',
  'What helps translate between big-picture and detail-focused thinking?',
  'How can different approaches coexist without slowing a decision?',

  'What kind of work conversation leaves you feeling more connected to a colleague?',
  'How can teammates learn what matters to one another professionally without prying?',
  'Which shared challenge can strengthen a working relationship?',
  'What makes professional warmth feel genuine?',
  'How would you create room for connection in a task-focused day?',
  'What helps colleagues move from polite coordination to real partnership?',
  'Where can humor support connection without excluding anyone?',
  'What is worth learning about a collaborator before a project begins?',
  'What makes informal connection accessible to remote team members?',
  'Which conversation can reveal common ground through the work itself?',
  'What makes curiosity about a colleague feel respectful?',
  'How can people build rapport without expecting personal disclosure?',
  'What does companionship at work add to collaboration?',
  'How would you welcome someone into an established working group?',
  'What helps a colleague feel remembered between projects?',
  'Which shared moment can turn a group into a team?',
  'How can people connect across seniority without ignoring power differences?',
  'What makes a professional relationship feel reciprocal?',
  'Where could unexpected collaboration be encouraged?',
  'What would you like colleagues to understand about working well with you?',
] as const
