export const STRANGERS_COLLEAGUES_WARM_UP: readonly string[] = [
  "What kind of task tends to bring out your best focus?",
  "How would you describe your natural pace when starting something new?",
  "Which part of a project do you usually find most energizing?",
  "Where do your clearest work ideas tend to show up?",
  "When a blank page is in front of you, what helps you begin?",
  "What does a satisfyingly productive hour look like for you?",
  "Which work habit has earned a permanent place in your routine?",
  "How do you like to make a complicated task feel manageable?",
  "What signals to you that you have found a good working rhythm?",
  "Which kinds of details naturally catch your attention?",
  "How do you prefer to keep track of loose ends?",
  "What makes a workday feel well paced to you?",
  "Which stage of turning an idea into reality suits you best?",
  "What helps you shift between very different kinds of work?",
  "How do you decide what deserves your attention first?",
  "What sort of problem makes persistence feel enjoyable to you?",
  "Which everyday tool would be hardest for you to work without?",
  "How does your workspace change when you are deeply focused?",
  "What is your favorite way to capture an idea before it disappears?",
  "When do you prefer a checklist, and when do you prefer to improvise?",
  "What small ritual helps you settle into the workday?",
  "How do you know when an idea is ready to share?",
  "Which kind of deadline brings out a useful side of you?",
  "What is something you like to finish in one sitting?",
  "How do you create momentum on a slow-starting day?",

  "What strength do you enjoy getting to use at work?",
  "Which ability of yours becomes more useful the busier things get?",
  "What do people often come to you for help thinking through?",
  "How would you explain a skill you make look easier than it is?",
  "What type of contribution feels especially natural to you?",
  "Which part of your working style took time for you to recognize as a strength?",
  "What are you unusually patient with at work?",
  "How do you tend to make a group task smoother?",
  "What kind of puzzle lets you use your strengths in an interesting way?",
  "Which quality do you most enjoy seeing in a collaborator?",
  "What is a low-key skill you appreciate in yourself?",
  "How does your curiosity show up in your work?",
  "What are you good at noticing before other people mention it?",
  "Which strength of a teammate makes your own work better?",
  "What is your version of being resourceful?",
  "How do you help an idea become clearer?",
  "What kind of knowledge are you always glad to share?",
  "Which work challenge tends to reveal your creative side?",
  "What do you bring to a discussion when everyone is still figuring things out?",
  "How would a teammate recognize that you are in your element?",
  "What is one way you make information easier for others to use?",
  "Which of your skills has grown through simple repetition?",
  "What role do you naturally take when a plan is still taking shape?",
  "How do you add calm to a busy situation?",
  "What kind of useful question are you especially good at asking?",

  "What communication channel works best when you need a quick answer?",
  "How do you like someone to introduce a complex topic to you?",
  "What makes a written update easy for you to absorb?",
  "When is a conversation more useful to you than a message?",
  "How do you prefer people to signal that something is urgent?",
  "What helps you feel prepared for a productive discussion?",
  "Which meeting format tends to get your best participation?",
  "How do you like to receive context for a new request?",
  "What makes instructions feel clear without feeling rigid?",
  "When you have a half-formed thought, how do you prefer to explore it with others?",
  "What does a helpful project update include for you?",
  "How do you usually show that you are listening in a conversation?",
  "Which questions help you understand what someone really needs?",
  "What makes it easier for you to ask a follow-up question?",
  "How do you prefer to revisit a topic that was left unresolved?",
  "What kind of response lets you know your message landed as intended?",
  "When does silence in a conversation feel useful to you?",
  "How do you make room for quieter voices in a group discussion?",
  "What helps a brainstorming conversation stay open and useful?",
  "Which communication habit saves you the most time?",
  "How would you invite someone to clarify an unfamiliar term?",
  "What tone makes a work message feel easy to respond to?",
  "How do you prefer to hear about a change of plans?",
  "What makes a handoff conversation feel complete?",
  "Which part of active listening matters most in everyday teamwork?",

  "What does an ideal collaboration begin with?",
  "How do you like responsibilities to be divided on a shared task?",
  "Which signs tell you that a partnership is working smoothly?",
  "What makes it enjoyable to build on someone else's idea?",
  "How do you prefer to compare different approaches with a teammate?",
  "What helps a group move from discussion into action?",
  "When several people have ideas, how do you like to combine them?",
  "What is a small courtesy that improves collaboration for you?",
  "How do you keep shared work visible without creating extra noise?",
  "Which team habit makes it easier to depend on one another?",
  "What makes you feel included in a project from the beginning?",
  "How do you like to celebrate a shared milestone?",
  "What does a fair division of an interesting task look like to you?",
  "When is it helpful for collaborators to work side by side?",
  "What do you appreciate from a teammate during a busy stretch?",
  "How can a group make asking for help feel ordinary?",
  "What helps you trust a collaborative process?",
  "Which kind of check-in keeps teamwork moving without interrupting it?",
  "How do you prefer to pass work to the next person?",
  "What makes shared ownership feel real on a team?",
  "Where can a little humor make collaboration easier?",
  "How do you like a teammate to offer a fresh perspective?",
  "What keeps group decisions from becoming more complicated than they need to be?",
  "Which ingredient turns a collection of people into a team?",
  "What is one thoughtful way colleagues can make remote collaboration warmer?",

  "What kind of progress is most motivating for you to see?",
  "Which aspect of a new challenge sparks your curiosity first?",
  "What gives an ordinary task a sense of purpose for you?",
  "How do you keep your interest alive during a long project?",
  "What sort of useful impact feels rewarding to you?",
  "Which small win can brighten your workday?",
  "What makes learning something new at work enjoyable?",
  "How do you reconnect with the point of a task when it feels repetitive?",
  "What kind of goal gives you room to think creatively?",
  "Which signs of progress are more meaningful to you than a finished checklist?",
  "What makes you want to return to a problem with fresh energy?",
  "How does helping someone else affect your motivation?",
  "What can turn a routine assignment into an interesting one?",
  "Which part of improving a process do you find satisfying?",
  "What makes a work question worth exploring even without an immediate answer?",
  "How do you recognize work that feels worthwhile to you?",
  "What kind of autonomy helps you stay engaged?",
  "Which visible result gives you the strongest sense of completion?",
  "What encourages you to keep experimenting with an idea?",
  "How does variety influence your energy during the week?",
  "What makes you excited to teach someone a useful shortcut?",
  "Which type of challenge feels like an inviting stretch?",
  "What helps you find meaning in behind-the-scenes work?",
  "How do you mark progress when the finish line is far away?",
  "What is a question about your field that keeps you curious?",

  "What feature would your ideal workspace definitely have?",
  "How does background sound affect the way you work?",
  "Which surroundings help you think expansively?",
  "What is your preferred balance between quiet time and social energy?",
  "How do you make a temporary workspace feel workable?",
  "What kind of lighting puts you in a productive mood?",
  "Which item near your workspace has a good story or purpose?",
  "What helps you focus when the environment is busier than usual?",
  "How do you use movement or a change of scene during the day?",
  "What would make a shared work area more inviting?",
  "Which spot is best for the kind of thinking you do most often?",
  "What is your favorite thing about working near other people?",
  "How do you signal that you are available for a quick chat?",
  "What belongs in a well-designed break space?",
  "Which environmental detail has a surprising effect on your mood?",
  "What does a comfortable video-call setup look like for you?",
  "How would you improve the view from your usual workspace?",
  "What kind of room makes brainstorming feel more playful?",
  "Which workspace convenience do you appreciate more than expected?",
  "How do you reset your surroundings after a hectic task?",
  "What is the best use of a spare corner in a workplace?",
  "Which office sound deserves its own soundtrack credit?",
  "What imaginary upgrade would make your workspace more fun?",
  "How does the time of day change where you like to work?",
  "What would you name your ideal focus zone?",

  "What is a meeting habit of yours that colleagues might recognize?",
  "How would you describe your note-taking style?",
  "Which phrase do you catch yourself using at work?",
  "What is your signature move when technology takes an unexpected break?",
  "How does your desk reveal that a deadline is approaching?",
  "What tiny task do you complete with unusual enthusiasm?",
  "Which harmless work quirk have you decided to embrace?",
  "What do you tend to doodle while thinking?",
  "How would a colleague know you have just solved something?",
  "What snack or drink has become part of your workday lore?",
  "Which browser tab seems to be permanently open for you?",
  "What is your most recognizable getting-ready-for-a-call routine?",
  "How do your notes look to someone seeing them for the first time?",
  "What ordinary office object do you use in an unintended way?",
  "Which task makes you talk to yourself the most?",
  "What expression appears on your face when you are concentrating?",
  "How would you narrate your typical search for a missing file?",
  "What is your personal sign that it is time for a screen break?",
  "Which workplace sound effect could you imitate best?",
  "What would the title of a documentary about your inbox be?",
  "How does your calendar show your personality?",
  "What is the funniest name you have given a draft or folder?",
  "Which everyday work moment feels like a tiny victory scene?",
  "What would your laptop say is your most predictable habit?",
  "How would you describe your relationship with notifications?",

  "What is your favorite low-stakes topic for a break-time chat?",
  "Which hobby has taught you something unexpectedly useful at work?",
  "What kind of music helps you change gears after a long task?",
  "How would you spend an extra twenty minutes between commitments?",
  "What subject can reliably send you down an interesting rabbit hole?",
  "Which kind of recommendation do you most enjoy exchanging with colleagues?",
  "What creative activity do you appreciate, whether or not you practice it?",
  "How do you like to add a little play to an ordinary week?",
  "What food could inspire a surprisingly passionate team discussion?",
  "Which season has the best working atmosphere for you?",
  "What kind of local place do you enjoy discovering?",
  "How would you design a five-minute mental refresh?",
  "What is something you enjoy learning purely for curiosity?",
  "Which fictional workplace would be interesting to visit for a day?",
  "What simple activity reliably helps you return with fresh eyes?",
  "How do you choose what to read, watch, or listen to next?",
  "What is a skill outside work that you enjoy practicing slowly?",
  "Which everyday object do you think is exceptionally well designed?",
  "What topic would you happily give a very short, informal talk about?",
  "How would you describe your ideal shared lunch conversation?",
  "What kind of trivia question are you always hoping will appear?",
  "Which small discovery recently delighted you?",
  "What does a genuinely refreshing pause in the day involve?",
  "How would you turn a familiar commute into a mini adventure?",
  "What playful contest could this group enjoy without keeping score?",

  "What first detail helps you understand how a new teammate works?",
  "How do you help someone get comfortably oriented to a project?",
  "Which question makes introductions more interesting than job titles do?",
  "What helps names and new faces stick in your memory?",
  "How would you explain your role without using any industry language?",
  "What is useful for a new collaborator to know about your approach?",
  "What do you enjoy discovering when you meet a new colleague?",
  "How do you make a first working session feel less formal?",
  "What would you put in a friendly guide to collaborating with you?",
  "Which early conversation can prevent confusion later?",
  "What do you notice about the way someone approaches a new task?",
  "How do you prefer to learn the unwritten rhythms of a team?",
  "Which conditions let you contribute comfortably in an unfamiliar group?",
  "Which shared activity helps people learn one another's styles naturally?",
  "What is a welcoming way to explain how a team communicates?",
  "How would you help a newcomer find the right person to ask?",
  "What can colleagues learn about you from your questions?",
  "Which part of your work would be most interesting to demonstrate to someone new?",
  "What makes a professional introduction feel memorable?",
  "How do you like others to pronounce or use your name?",
  "What context helps you join a project already in motion?",
  "Which team tradition would you explain first to a newcomer?",
  "What would make a first week feel thoughtfully paced?",
  "How can established teammates leave room for a new perspective?",
  "What is a comfortable way to move from small talk into working together?",

  "Faced with an unfamiliar tool, where do you begin learning?",
  "What kind of example makes a new concept click for you?",
  "Which question do you ask when you want to understand the bigger picture?",
  "When learning by trial and error, what keeps the process constructive?",
  "What topic at work would you enjoy seeing through a beginner's eyes again?",
  "Which teaching style helps information stay with you?",
  "What have you learned from watching someone else's process?",
  "How do you decide whether to explore independently or ask for guidance?",
  "What makes a how-to resource genuinely helpful?",
  "Which part of explaining something deepens your own understanding?",
  "What is an unexpectedly useful thing a colleague has shown you?",
  "How would you make a learning session feel more conversational?",
  "What kind of practice helps you build confidence with a new skill?",
  "Which unfamiliar task would you be curious to observe up close?",
  "What helps you remember a useful tip at the moment you need it?",
  "When an explanation is new, what is a good way to check understanding?",
  "What is a concept you enjoy translating into plain language?",
  "Which learning curve has been more fun than you expected?",
  "What makes it easy to say that you need more context?",
  "How do you share a shortcut without skipping the reasoning behind it?",
  "What can a team do to make curiosity visible?",
  "Which question opens the door to a useful demonstration?",
  "After trying something new, how do you enjoy comparing notes?",
  "How does teaching change the way you notice your own habits?",
  "What would you include in a tiny library for your team?",

  "What makes a check-in feel worth the time?",
  "How do you like a team to close a productive meeting?",
  "Which kind of agenda leaves enough room for good surprises?",
  "What helps you contribute when a discussion moves quickly?",
  "How would you improve the first five minutes of a meeting?",
  "What is a useful role for someone who is not leading the conversation?",
  "Which visual aid helps you follow a complicated discussion?",
  "How do you prefer ideas to be gathered before a group decides?",
  "What makes a question feel safe to ask in a meeting?",
  "Which meeting could become a message, and what would the message need?",
  "How do you help a conversation return to its purpose?",
  "What is a graceful way to create thinking time during a discussion?",
  "Which closing question helps everyone leave with clarity?",
  "How can a facilitator make room for different viewpoints?",
  "What makes a virtual meeting feel more human?",
  "How do you like decisions to be captured after people talk?",
  "Which kind of contribution is easiest to make after some reflection?",
  "What would a genuinely useful no-meeting hour allow you to do?",
  "How can a group tell when it has discussed something enough?",
  "What keeps a recurring meeting from becoming routine?",
  "Which meeting norm would you happily borrow from another team?",
  "How do you prefer to signal that you have a thought to add?",
  "What makes a round of introductions feel natural?",
  "How would you give a brainstorm a playful title?",
  "What is the best way to leave space for one final thought?",

  "What kind of appreciation feels natural to hear from a colleague?",
  "How do you like to acknowledge someone's behind-the-scenes help?",
  "Which everyday contribution deserves more casual celebration?",
  "What makes a thank-you message feel specific and sincere?",
  "How can teammates notice progress before a project is finished?",
  "What is a simple way to recognize a good idea in the moment?",
  "Which team effort is fun to celebrate collectively?",
  "How do you show appreciation when someone saves you time?",
  "What kind of encouragement helps during the unfinished middle of a task?",
  "Which compliment about your approach would mean something to you?",
  "What makes recognition feel inclusive rather than competitive?",
  "How would you celebrate solving a stubborn little problem?",
  "What is a thoughtful way to credit the people who contributed?",
  "Which quiet act of teamwork do you tend to notice?",
  "How can a group make gratitude part of ordinary work?",
  "What is worth a tiny round of applause on a typical day?",
  "How do you prefer to share good news with collaborators?",
  "Which milestone calls for something more creative than cake?",
  "What makes praise useful as well as kind?",
  "How would you thank a colleague who offered helpful context?",
  "What type of progress deserves a cheerful message in the group chat?",
  "Which word best captures the feeling of finishing a shared task?",
  "After a successful project, how should a team preserve the good memories?",
  "What is a lighthearted award everyone could enjoy receiving?",
  "How can colleagues celebrate a win without adding pressure to the next goal?",
]
