export const STRANGERS_GROUP_REFLECT = [
  'What is one detail from this conversation that you are glad you noticed?',
  'Which idea shared here gave you a new angle to consider?',
  'How would you describe the energy of this group in a few words?',
  'What felt easier to discuss than you expected?',
  'Where did you notice curiosity showing up in the room?',
  'Which part of the exchange felt most useful to you?',
  'What did this group help you see from a slightly different viewpoint?',
  'How did the conversation compare with what you expected at the start?',
  'What small moment from the discussion would you like to remember?',
  'Which response made you pause and think, without needing to agree with it?',
  'What did you learn about how this group approaches a question?',
  'When did the conversation feel most engaged to you?',
  'What ordinary topic became more interesting because others weighed in?',
  'Which part of tonight felt unexpectedly easygoing?',
  'What did you notice about the range of answers in the group?',
  'How did hearing several perspectives affect your own thinking?',
  'What is one word you would use for what the group created together?',
  'Which question opened the widest range of possible answers?',
  'What seemed to help the conversation find its rhythm?',
  'Where did you notice the group becoming more comfortable?',
  'What did you discover about a topic, rather than about a person?',
  'Which moment showed that people can connect without knowing each other well?',
  'How might you summarize the conversation for someone who was not here?',
  'What was different about listening to a group instead of one person?',
  'Which contribution added a useful detail to the bigger picture?',
  'What did the group make room to think about?',
  'Where did the conversation take a turn you found interesting?',
  'What value seemed to appear in several answers, even in different forms?',
  'Which principle mattered to you during this exchange?',
  'How did the group show care in an everyday way?',
  'What shared priority, if any, became visible through the discussion?',
  'Where did two different viewpoints seem equally reasonable?',
  'What difference in perspective helped make the conversation richer?',
  'Which answer reminded you that people can value the same thing differently?',
  'How would you distinguish a shared value from a shared opinion here?',
  'What did the conversation suggest about what this group considers respectful?',
  'Which quality would you want to carry into another group conversation?',
  'What kind of fairness seemed relevant to the way people participated?',
  'Where did the group hold more than one good answer at once?',
  'What did you hear that broadened your sense of what matters to people?',
  'Which difference could remain unresolved without becoming a problem?',
  'How did variety in the room contribute to the discussion?',
  'What belief about good conversation was reinforced or reconsidered for you?',
  'Which group value could be expressed through a simple action?',
  'What did respect look or sound like during this round?',
  'Where did you notice people making space for complexity?',
  'What common ground felt real without requiring everyone to match?',
  'Which contrast between answers was informative rather than divisive?',
  'How can a group honor a shared aim while allowing different approaches?',
  'What did you value in an answer that was unlike your own?',
  'Which part of the conversation showed room for both individuality and connection?',
  'What is one way agreement and understanding differed in this discussion?',
  'Where might curiosity be more helpful than trying to settle a difference?',
  'What did the group reveal about the many ways people define a good experience?',
  'When did you feel most included in the flow of the conversation?',
  'What helped the room feel welcoming, even in a small way?',
  'How might someone participate here without speaking at length?',
  'Which group habit could help a newcomer feel less on the outside?',
  'What sign told you that different kinds of answers were welcome?',
  'Where was there room to join in at your own pace?',
  'What could make belonging feel possible before familiarity develops?',
  'Which part of the setup made participation feel more approachable?',
  'How did the group respond when an answer was brief or uncertain?',
  'What would help someone feel included without putting them on the spot?',
  'Which invitation to contribute felt genuine rather than pressuring?',
  'What is one quiet way a person can add to a group?',
  'How can a group welcome someone whose conversational style is different?',
  'What made it possible to be present without needing to perform?',
  'Where could the group make more room for people who need time to think?',
  'What does a low-pressure welcome sound like to you?',
  'Which small choice can signal that every person counts?',
  'How might a group notice inclusion without asking anyone to explain themselves?',
  'What allowed you to take part at a level that suited you?',
  'Where did the conversation leave space for observation as participation?',
  'What kind of opening helps people enter a discussion comfortably?',
  'How can people show that a pass is as acceptable as an answer?',
  'Which aspect of the exchange supported a sense of being among equals?',
  'What would make this kind of gathering easier to enter midway through?',
  'How might the group include someone who prefers writing, gestures, or short replies?',
  'What is a welcoming question that does not assume shared experience?',
  'Where did you notice connection forming through something simple?',
  'What helped you decide when to speak and when to listen?',
  'How did turn-taking shape the quality of the exchange?',
  'Which contribution created room for someone else to add on?',
  'What is one way the group used silence constructively?',
  'Where did listening change the direction of the discussion?',
  'How could the group invite more voices without singling anyone out?',
  'What made a response feel heard, even when nobody commented on it?',
  'Which listening behavior would you gladly encounter in another group?',
  'How did shorter and longer contributions work together?',
  'What helped keep any one voice from carrying the whole conversation?',
  'Where might a pause have improved understanding?',
  'What does attentive listening look like when people have just met?',
  'Which kind of follow-up question adds space instead of pressure?',
  'How can a listener show interest without asking for personal details?',
  'What did you notice about who introduced topics and who developed them?',
  'Where could the conversation have benefited from a clearer invitation to enter?',
  'What helps you know that your contribution can be concise?',
  'How might people check that they understood without speaking for someone else?',
  'Which moment showed the value of letting an answer stand on its own?',
  'What can make interruptions easier to repair in the moment?',
  'How did the group balance spontaneous reactions with attentive space?',
  'What is one respectful way to redirect a conversation that has drifted?',
  'Where did someone build on an idea without taking ownership of it?',
  'How could a group make room for a person returning after a pause?',
  'Which cue made it clear that the floor was open?',
  'What did you learn about your preferred pace for group conversation?',
  'How might listening include noticing what has not yet been addressed?',
  'What part of the group effort worked smoothly?',
  'How did people help move the conversation along together?',
  'Which moment felt like genuine collaboration rather than parallel talking?',
  'What did the group accomplish that no single answer could have done?',
  'Where did one person’s idea give another person a useful starting point?',
  'How were different strengths useful in this exchange?',
  'What is one cooperative choice that made the round easier?',
  'Which role emerged naturally, such as inviting, connecting, or summarizing?',
  'How did the group handle a change in topic or mood?',
  'What helped the conversation recover when its energy dipped?',
  'Where did people coordinate without needing formal instructions?',
  'Which shared task would this group likely approach thoughtfully?',
  'What did the discussion show about making something together from partial ideas?',
  'How could cooperation remain fair when people have different amounts of energy?',
  'What made it easier to contribute without competing for attention?',
  'Where did the group benefit from someone choosing not to fill every gap?',
  'Which kind of support kept the exchange moving without controlling it?',
  'What could help a mixed group share the work of conversation?',
  'How did people signal readiness to shift or continue?',
  'What is one way a group can acknowledge effort without ranking contributions?',
  'Which moment showed flexibility in how the group worked?',
  'Where could shared expectations have made cooperation simpler?',
  'What did the group do when several people had something to add?',
  'How can responsibility for a good conversation be distributed?',
  'What might help the group adjust when one approach is not working?',
  'Which choice supported both the group’s momentum and individual comfort?',
  'What did cooperation sound like in the language people used?',
  'What pattern in the group became clearer as the conversation continued?',
  'How did the mood influence who spoke or how answers were offered?',
  'Which unwritten rule seemed to guide the exchange?',
  'Where did the group’s attention gather most strongly?',
  'What changed after the first few people answered?',
  'How did the size of the group affect the way ideas moved?',
  'Which moment shifted the room from separate individuals toward a group?',
  'What did you notice about how people responded to uncertainty?',
  'Where was influence shared, and where did it collect?',
  'How might the order of responses have shaped what followed?',
  'What group tendency would be useful to notice next time?',
  'Which topic changed the tempo of the room?',
  'How did humor affect the sense of connection?',
  'What happened when the group encountered a less familiar viewpoint?',
  'Where did expectations seem to form without being stated?',
  'What did the group do with moments of agreement?',
  'How were differences in confidence visible without defining anyone?',
  'Which response influenced later answers in an interesting way?',
  'What might an observer have noticed about the group’s rhythm?',
  'Where did the conversation become more focused or more expansive?',
  'How did people test whether a topic felt comfortable for the room?',
  'What allowed the group to move on without forcing closure?',
  'Which dynamic supported curiosity, and which one limited it?',
  'What did the group seem to reward with attention?',
  'How could shared power become more visible in a conversation like this?',
  'Where might an unspoken assumption have shaped the exchange?',
  'What changed when someone offered a different interpretation?',
  'What feature of the setting supported participation?',
  'How could the physical or digital space be easier to use?',
  'Which adjustment could help people follow the conversation more comfortably?',
  'What would make the pace more accessible to a wider range of participants?',
  'Where could clearer wording reduce the effort needed to join in?',
  'How might the group offer more than one way to answer?',
  'What environmental detail made listening easier or harder?',
  'Which part of the activity could benefit from a visible explanation?',
  'What would help someone participate while managing limited time or energy?',
  'How can a group check access needs without requesting personal disclosure?',
  'Where would an extra pause or recap be useful?',
  'What alternative to speaking aloud could fit naturally into this activity?',
  'Which instruction, if any, could be made simpler?',
  'How might seating, sound, lighting, or screen layout affect this conversation?',
  'What could make it easier to hear or track whose turn it is?',
  'Where did the format allow people to choose their level of participation?',
  'What is one way to make a group activity more predictable without making it rigid?',
  'How could a facilitator offer choices without overwhelming the room?',
  'Which part of the experience worked well for different communication styles?',
  'What would make a break feel like a normal option rather than an exception?',
  'How might the group support someone who needs a question repeated or rephrased?',
  'Where could examples help without narrowing the possible answers?',
  'What accessibility improvement would also benefit the whole group?',
  'Which cue could make transitions easier to anticipate?',
  'How can the activity remain engaging for someone who chooses to observe?',
  'What would allow people to rejoin the conversation without explanation?',
  'Where might a slower pace produce a better discussion?',
  'What helped you maintain your own comfort during the conversation?',
  'How can a group respect a boundary without asking for its reason?',
  'Which phrase makes it easier to decline a question gracefully?',
  'Where did people show that changing one’s mind was allowed?',
  'What does consent look like in an ordinary group discussion?',
  'How might someone signal that they want to move to another topic?',
  'What helped answers feel optional rather than expected?',
  'Which boundary-supporting habit would improve most gatherings?',
  'How can curiosity stay respectful when a person gives a limited answer?',
  'Where did the group accept uncertainty without pushing for clarity?',
  'What is a comfortable way to say that a topic is not for today?',
  'How should a group respond when someone withdraws an earlier answer?',
  'Which choices can participants retain even within a structured activity?',
  'What would make permission to pass more believable in practice?',
  'How can people avoid treating silence as agreement?',
  'Where could the group check before changing the level of depth?',
  'What does respecting privacy mean when no private details were requested?',
  'Which response can acknowledge a boundary and keep the conversation flowing?',
  'How might the group distinguish an invitation from an obligation?',
  'What should happen when a question lands differently than intended?',
  'Where did someone preserve choice for others through the way they spoke?',
  'How can a participant redirect attention without becoming the topic?',
  'Which expectations are worth stating so nobody has to guess them?',
  'What does it mean to let each person define enough for themselves?',
  'How could the group normalize revising or shortening an answer?',
  'Where is the line between a helpful follow-up and unwanted pressure?',
  'What is one way to keep participation voluntary when enthusiasm is high?',
  'What responsibility does each person have for the tone of a group conversation?',
  'How can someone take ownership of an impact without guessing another person’s feelings?',
  'Which small action can help restore ease after an awkward moment?',
  'What makes a correction easier to receive?',
  'Where could a simple acknowledgment be enough?',
  'How might the group revisit a misunderstanding without assigning motives?',
  'What does a useful apology make room for next?',
  'Which repair step can happen even when people remember a moment differently?',
  'How can a person clarify their meaning without dismissing the effect of their words?',
  'What helps a group learn from friction without making anyone explain more than they want?',
  'Where did the conversation model accountability in a low-key way?',
  'What is one sign that a repair attempt is responsive rather than performative?',
  'How could the group respond if someone was interrupted repeatedly?',
  'Which words can reopen space after an accidental assumption?',
  'What would help people name a concern without turning it into a verdict?',
  'How can the group correct course while preserving everyone’s dignity?',
  'Where might good intent matter, and where might attention to impact matter more?',
  'What does shared responsibility look like when no single person caused a problem?',
  'Which response can lower defensiveness while keeping an issue visible?',
  'How might a group recognize a missed voice without demanding that person speak?',
  'What can participants do when a joke does not land as hoped?',
  'Where is there room for both explanation and accountability?',
  'How can a conversation recover after people talk past one another?',
  'Which kind of feedback is easiest to act on in the moment?',
  'What makes it possible to repair without requiring immediate resolution?',
  'How might someone thank a person for a correction without centering themselves?',
  'What does learning publicly look like at a manageable scale?',
  'What form of care was present in the way people interacted?',
  'How can a group notice who may need space without making assumptions?',
  'Which small gesture helps conserve everyone’s energy?',
  'What would mutual support look like in a group of people who just met?',
  'Where did kindness appear without becoming personal or intrusive?',
  'How might the group share attention as a community resource?',
  'What can people do to keep the gathering welcoming as energy changes?',
  'Which choice showed consideration for the whole room?',
  'What does community care look like when everyone has different preferences?',
  'How can a group balance individual needs with shared momentum?',
  'Where could appreciation be expressed without putting anyone on display?',
  'What is one way to leave a shared space better than you found it?',
  'How might people support participation without taking over for someone?',
  'Which group resource, such as time or attention, could be shared more evenly?',
  'What would help care remain practical rather than assumed?',
  'How can a gathering make room for both connection and rest?',
  'Where did someone contribute to the group’s ease?',
  'What does it mean to look after the conversation as well as your own part in it?',
  'Which act of consideration tends to go unnoticed in groups?',
  'How might the group close in a way that respects different energy levels?',
  'What is one lesson from this conversation that could help another community space?',
  'How can gratitude be offered without creating pressure to respond?',
  'Where might the group benefit from sharing information more clearly?',
  'What kind of care can be built into the format rather than added later?',
  'Which shared practice could help people feel supported without assuming closeness?',
  'How might a group make room for someone whose needs change during an activity?',
  'What does considerate use of time look like in this setting?',
  'What might you try differently in a future group conversation, if it suits the moment?',
  'Which part of today’s format would you adapt for another setting?',
  'How could a next gathering begin with more shared choice?',
  'What is one listening practice you may want to experiment with?',
  'Where might you leave more room for an answer unlike your own?',
  'How would you make a future discussion easier to enter?',
  'Which group habit seems worth testing again?',
  'What could you invite without expecting anyone to accept?',
  'How might the next conversation offer a clearer way to pass?',
  'What is one flexible intention this group could carry forward?',
  'Which useful question could remain open until another time?',
  'How could future participants have more influence over the process?',
  'What would you keep optional in any follow-up gathering?',
  'Where might a check-in improve the next group experience?',
  'How could the group make future decisions more transparent?',
  'Which adjustment would you suggest as an experiment rather than a rule?',
  'What might help the next conversation include a wider range of responses?',
  'How would you preserve what worked while allowing the format to change?',
  'What is one possibility for continuing the spirit of this exchange?',
  'Which future choice should remain with each participant?',
  'How could a group revisit an idea without assuming everyone wants to?',
  'What might make shared reflection feel lighter next time?',
  'Where could participants help shape the questions themselves?',
  'How would you know whether a future change improved the experience?',
  'Which intention could guide the group without becoming a promise?',
  'What could be offered next time in more than one format?',
  'How might a future host share power more visibly?',
  'What would make another round worthwhile for people with different aims?',
  'Which part of this experience are you content to leave here?',
  'How could the next ending leave everyone free to choose what comes after?',
] as const satisfies readonly string[]
