export const STRANGERS_FAMILY_WARM_UP = [
  "What kind of day do you seem to be having so far?",
  "What is something you have been enjoying lately?",
  "Which small comfort do you reach for most often?",
  "How would you describe your sense of humor?",
  "What topic can usually get you talking?",
  "Which everyday task seems easier when you take it on?",
  "What is one thing you seem especially curious about?",
  "What is your way of making an ordinary day more interesting?",
  "What kind of setting seems to bring out your relaxed side?",
  "Which detail about today has caught your attention?",
  "What is your ideal pace for a free afternoon?",
  "How do you usually choose what to watch?",
  "What kind of food rarely disappoints you?",
  "Which sound instantly improves a room for you?",
  "What makes a conversation feel easy to you?",
  "How would you spend an unexpected hour with no obligations?",
  "Which season best matches your energy, and why?",
  "Which small comfort currently makes your routines easier?",
  "How do you know when you are having fun?",
  "What sort of plan are you happiest to say yes to?",
  "Which snack deserves more respect than it gets?",
  "What kind of day makes you want to linger outdoors?",
  "How do you like your mornings to begin?",
  "What is your favorite way to pass time while waiting?",
  "Which everyday smell do you find especially pleasant?",
  "What kind of place makes you want to stay awhile?",
  "Where is your taste in music taking you lately?",
  "Which detail helps an unfamiliar room feel welcoming?",
  "Which simple pleasure never feels boring to you?",
  "What is your version of a satisfying evening?",
  "How do you decide whether something is worth trying?",
  "What kind of surprise do you actually enjoy?",
  "Which color seems to show up most in things you choose?",
  "What is something ordinary that you find oddly fascinating?",
  "Where do routines fit into your life?",
  "What do you like to have nearby when you are relaxing?",
  "Which meal feels most like a treat to you?",
  "What kind of outing suits you best these days?",
  "What helps you get comfortable in an unfamiliar place?",
  "What is a recent discovery you would happily recommend?",
  "Which part of the day tends to suit you best?",
  "What do you enjoy doing at your own pace?",
  "How would you design a pleasantly uneventful day?",
  "What is a harmless opinion you could defend with enthusiasm?",
  "Which object do you use more than you expected to?",
  "What kind of background noise helps you settle in?",
  "What marks the end of a busy day for you?",
  "What is one choice you rarely overthink?",
  "Which local spot would you be curious to explore?",
  "What would make today feel like time well spent?",

  "What strength do you think you bring to everyday situations?",
  "How do you tend to help when a group needs direction?",
  "What are you surprisingly patient about?",
  "Which practical skill are you glad you picked up?",
  "What kind of problem do you enjoy figuring out?",
  "How do you contribute when people are making a plan?",
  "What do others tend to ask your help with?",
  "Which responsibility do you handle in your own distinctive way?",
  "Which things are you especially good at noticing?",
  "Which response helps a family plan recover from a small surprise?",
  "What kind of decision do you make confidently?",
  "Which useful trick have you learned through experience?",
  "In what way do you help people feel included?",
  "How do you approach a task you have never tried before?",
  "What is a low-key talent you enjoy using?",
  "Which role do you naturally choose during a group activity?",
  "Where do you add enjoyment for other people?",
  "How do you keep track of the things that matter to you?",
  "What are you dependable about without making a fuss?",
  "Which everyday challenge brings out your resourceful side?",
  "Which skill or idea do you enjoy teaching to someone interested?",
  "How do you encourage people without putting them on the spot?",
  "What is a strength you have come to value more over time?",
  "Which kind of detail are you usually the first to catch?",
  "What do you bring to a gathering besides something tangible?",
  "What is your knack for making a shared task feel lighter?",
  "Which thing can you improvise well?",
  "Which personal quality helps you adapt when plans change?",
  "What are you better at now than you were a year ago?",
  "How do you show care in small, practical ways?",
  "What kind of organizer are you when something needs arranging?",
  "Which compliment about your abilities feels accurate?",
  "Which ability of yours might not be obvious at first?",
  "What helps you make room for quieter voices in a conversation?",
  "What is your approach to learning a new skill?",
  "Which challenge can reliably bring out your playful side?",
  "What helps you stay steady when everyone has a different idea?",
  "How do you add your personality to routine work?",
  "Which small gesture do you use to make people feel welcome?",
  "Which type of project tends to hold your attention?",
  "What do you appreciate about the way you think?",
  "When do you choose to lead, and when do you follow?",
  "Which thing are you quietly proud of handling well?",
  "Which skill would you gladly trade tips about?",
  "What does being helpful look like in your style?",
  "How do you recover when a simple plan goes sideways?",
  "What is a quality you enjoy seeing in yourself?",
  "Which situations reveal your creative side?",
  "What do you make more fun simply by joining in?",
  "What energy do you tend to bring into a room?",

  "Which harmless mix-up became a useful family story?",
  "Which harmless habit of yours would make a good cartoon?",
  "What kind of joke almost always works on you?",
  "How would a narrator describe your entrance today?",
  "What minor inconvenience turns you into a dramatic character?",
  "Which animal best represents your mood right now?",
  "What would your personal warning label say on a relaxed day?",
  "How do you react when you realize you have been confidently wrong?",
  "What is the silliest thing you take oddly seriously?",
  "Which everyday object would you nominate for an award?",
  "What title would you give this gathering if it were an episode?",
  "How would you explain your favorite snack to an alien?",
  "What is your most entertaining way of avoiding a boring chore?",
  "Which fictional character might appreciate your sense of humor?",
  "What would make a terrible name for a family group chat?",
  "How would you celebrate winning a completely meaningless trophy?",
  "What tiny event can make you feel absurdly accomplished?",
  "Which phrase do you say often enough to deserve merchandise?",
  "What would your signature move be in a very slow action movie?",
  "How do you make yourself laugh when nobody else is around?",
  "What food combination would you defend before a skeptical audience?",
  "Which household item would be the worst at keeping a secret?",
  "What would you name a boat you did not have to pay for?",
  "Suppose mild mischief were encouraged; where would the day take you?",
  "What is the funniest compliment you could sincerely receive?",
  "Which ordinary activity deserves dramatic theme music?",
  "What would your mascot be for getting through a busy week?",
  "What tells you a joke is too good not to repeat?",
  "What imaginary competition could you have a chance of winning?",
  "Which vegetable has the strongest personality?",
  "What would be included in a museum exhibit about your week?",
  "How would you make a routine errand unnecessarily fancy?",
  "What is your best excuse for ordering dessert first?",
  "Which sound effect belongs in your daily life?",
  "What would you call a holiday invented just for resting?",
  "How might your shoes describe a typical day with you?",
  "What is a ridiculous hill you are willing to picnic on?",
  "Which game show would be improved by having you as a contestant?",
  "What kind of song matches your pace on a busy morning?",
  "How would you turn a rainy afternoon into a low-budget adventure?",
  "What is the most unnecessary thing you enjoy being particular about?",
  "Which snack would make the best peace offering?",
  "What would a friendly robot find confusing about your routine?",
  "Where does comedy enter when you tell an ordinary story?",
  "What is your preferred level of chaos during a game?",
  "Which made-up job would suit you surprisingly well?",
  "What would you put on a menu inspired by your personality?",
  "How might you improve the design of a standard weekend?",
  "What is a playful rule everyone could follow for one hour?",
  "Which everyday achievement deserves a tiny parade?",

  "Take a guess: what do I enjoy doing to unwind?",
  "Which snack would you guess I choose for a movie night, and why?",
  "What kind of music do you imagine suits my current mood?",
  "Picture my quiet Sunday; how do you think I spend it?",
  "Which everyday skill do you suspect I have mastered?",
  "What do you imagine makes me laugh quickly?",
  "Which color would you associate with my energy today?",
  "What type of outing do you think I would enjoy?",
  "When plans change, what response would you predict from me?",
  "Which fictional world do you think I might visit for a day?",
  "What kind of gift would you guess I enjoy giving?",
  "During a game, which role can you picture me taking?",
  "What do you think I might order at a café I have never visited?",
  "By what means might I make an ordinary day feel better?",
  "Which animal seems to match my pace today?",
  "What sort of hobby could you picture me trying?",
  "Which season would you pair with my personality so far?",
  "Where do you imagine I might go to recharge?",
  "Faced with staying in or going out, how might I choose?",
  "Which small task do you imagine I am unusually good at?",
  "What do you suppose I notice first in a new place?",
  "Which meal would you guess I could happily eat often?",
  "How might I react to receiving a surprise day off?",
  "What kind of story do you think I tell with the most enthusiasm?",
  "Which board game behavior would you predict from me?",
  "What would the background noise I find ideal sound like?",
  "If instructions were missing, how might I approach assembling something?",
  "Which simple pleasure do you suspect I appreciate?",
  "What type of weather seems to fit my vibe?",
  "In what way could you picture me putting guests at ease?",
  "Which subject might I know an unexpected amount about?",
  "Which name can you imagine me giving a pet cactus?",
  "If I arrived early, what do you suppose I would do?",
  "Which kind of shop could you imagine me browsing for ages?",
  "What might my ideal breakfast include?",
  "Imagine I have a small win; how might I celebrate?",
  "Which travel companion role do you imagine I would choose?",
  "What would you guess is my favorite part of a celebration?",
  "How might I personalize a workspace?",
  "Which everyday sound do you think I find satisfying?",
  "What sort of challenge might bring out my competitive side?",
  "How would you guess I decide what deserves a photo?",
  "Which kind of compliment do you imagine makes me smile?",
  "Where might my dream reading spot be?",
  "How might I spend twenty unexpected free minutes?",
  "Which food do you suspect I have strong opinions about?",
  "What kind of teammate do you imagine I am?",
  "When a favorite song comes on, how might I react?",
  "Which tiny luxury do you think I would choose today?",
  "Which addition might I choose to make this room cozier?",

  "What is a pleasant moment from any gathering that you like remembering?",
  "Which celebration from any time in your life had a detail you loved?",
  "What is a meal memory you would revisit just for the flavors?",
  "How did someone once make you feel especially welcome?",
  "Which longtime favorite song do you still enjoy hearing?",
  "Which past outing would you happily repeat if it were easy?",
  "What is a kind gesture you remember with a smile?",
  "How have your tastes changed in a way that amuses you?",
  "What is a game you have enjoyed with other people?",
  "Which former fashion choice can you appreciate with good humor?",
  "What is a useful lesson you picked up in an ordinary moment?",
  "How did you discover a food you now like?",
  "What is a happy coincidence that led to something enjoyable?",
  "Which place from your past had an atmosphere you liked?",
  "What is a compliment you were glad to receive?",
  "How has a hobby brought some fun into your life?",
  "Which small success still feels satisfying to remember?",
  "Which event had better music than you expected?",
  "What is a souvenir or keepsake with a lighthearted story?",
  "How did a spontaneous plan once turn out well?",
  "What is a favorite memory involving an animal?",
  "Which ordinary day became memorable for a good reason?",
  "What is something delicious you once tried on a recommendation?",
  "How did you spend a birthday you remember fondly?",
  "When has teamwork felt genuinely enjoyable to you?",
  "Which old interest would be fun to pick up again?",
  "Which harmless mistake led to a funny moment?",
  "How did someone introduce you to something you still enjoy?",
  "What is a view you remember stopping to admire?",
  "Which past purchase turned out to be unexpectedly useful?",
  "What is a tradition you have encountered and enjoyed, wherever it came from?",
  "How has your idea of a good time evolved?",
  "What is a memorable conversation that stayed light and enjoyable?",
  "Which trip, long or short, included a welcome surprise?",
  "What is a creative project you enjoyed at any age?",
  "How did you first realize you were good at something?",
  "When have you felt pleasantly brave?",
  "Which meal have you enjoyed making or helping to make?",
  "Which joke has kept its power to make you laugh?",
  "How did a change of plans once improve the day?",
  "What is a friendly competition you remember enjoying?",
  "Which past version of your style deserves a cheerful comeback?",
  "When has a stranger brightened your day?",
  "How did you celebrate an achievement that mattered to you?",
  "What is a simple activity that has given you good memories?",
  "Which childhood interest, if any, still shows up in your life?",
  "What is a time when you laughed harder than you expected?",
  "How did you come across one of your favorite places?",
  "What is a positive memory connected to a particular scent?",
  "Which past adventure would make a good short story?",

  "Where does your idea of family show up in everyday life?",
  "Where should individuality fit within family connections?",
  "What helps a family gathering feel welcoming to different people?",
  "Which kind of family role do you enjoy choosing for yourself?",
  "How can relatives or chosen family stay curious about each other?",
  "Which gestures tell you that someone is thinking of you?",
  "What makes shared time feel comfortable rather than formal?",
  "Which activity can help family members of different ages connect?",
  "Which quality matters to you in the people you call family?",
  "How can someone make space for a newcomer at a gathering?",
  "What kind of check-in feels natural to you?",
  "Which everyday gesture can say a lot without being elaborate?",
  "What helps people enjoy time together even when their tastes differ?",
  "When several people are involved, how should decisions be made?",
  "What is a comfortable way for people to learn more about you?",
  "Which shared activity leaves plenty of room for conversation?",
  "What makes an invitation feel genuinely inviting?",
  "What lets family members celebrate one another without creating pressure?",
  "What kind of update do you enjoy hearing from people in your circle?",
  "Which small ritual could make staying connected more fun?",
  "What does a respectful disagreement sound like to you?",
  "How do you prefer to join a conversation already in progress?",
  "How might a group accommodate different energy levels?",
  "Which topic makes for an easy catch-up conversation?",
  "What helps humor bring people together rather than leave someone out?",
  "How can people show interest without asking for more than someone wants to share?",
  "What kind of plan works well for both planners and spontaneous people?",
  "Which contribution to a gathering is easy to overlook but worth appreciating?",
  "What makes you feel heard during a casual conversation?",
  "When someone joins a shared activity, how do you welcome them?",
  "What is a thoughtful way to remember people's preferences?",
  "Which family custom could be invented from scratch today?",
  "What helps a group move on gracefully when a topic does not land?",
  "How can people make ordinary time together feel meaningful?",
  "What kind of appreciation is easiest for you to receive?",
  "Which low-pressure activity would you suggest for getting acquainted?",
  "Where can a group make room for both talkers and listeners?",
  "When you change your mind, what response do you appreciate from others?",
  "What makes it easier to be yourself around a mixed group?",
  "Which shared responsibility can become surprisingly enjoyable?",
  "What is a good way to include someone who joins remotely?",
  "How can a group keep a playful mood without forcing participation?",
  "What type of family connection would you like to know more about?",
  "Which everyday kindness helps relationships feel cared for?",
  "What does giving someone the benefit of the doubt look like to you?",
  "How do you recognize when someone wants a little more space?",
  "What is a gentle way to invite a person's perspective?",
  "Which kind of shared experience can create an easy sense of connection?",
  "What helps people with different histories find common ground?",
  "What could make the next few minutes enjoyable for everyone here?",
] as const satisfies readonly string[]
