export const STRANGERS_PARTNER_CONNECT = [
  "What part of your world would you like me to understand better right now?",
  "Where in your life do you feel most like yourself these days?",
  "What has been taking up more of your attention than I might realize?",
  "Which side of you has had the least room to show up lately?",
  "Which recent experience has revealed something new about who you are today?",
  "When have you felt especially understood by me recently?",
  "What do you wish I noticed more often about your day-to-day experience?",
  "How has your idea of feeling known changed over time?",
  "What is something you are still figuring out that you want me to be patient with?",
  "What subject would you enjoy having me invite you to talk about more often?",
  "What feels easy to share with me, and what helps make it easy?",
  "In what moments do you feel free to be unfiltered around me?",
  "What has surprised you about who you are becoming?",
  "How would you describe the version of you that needs more attention lately?",
  "What personal win have you not had enough space to celebrate?",
  "Which everyday experience shapes your mood more than people tend to notice?",
  "What would help me recognize when something matters deeply to you?",
  "How do you want to be seen when you are still making sense of something?",
  "What is one belief about yourself that you are currently reconsidering?",
  "Where do you feel most understood without needing to explain everything?",

  "When life feels heavy, what kind of support from me lands best?",
  "How can I tell whether you want comfort, ideas, practical help, or company?",
  "What does useful encouragement sound like to you?",
  "Which small act of support makes a bigger difference than it may seem?",
  "What helps you accept care when you are used to handling things alone?",
  "How would you like me to check in when you seem quieter than usual?",
  "What kind of help feels supportive without making you feel managed?",
  "When you are overwhelmed, what should I understand about the way you respond?",
  "What makes it easier for you to ask me for what you need?",
  "How do you prefer we handle moments when neither of us has much energy to give?",
  "What is a form of support you value even if you rarely request it?",
  "When you share a problem, how do you want me to respond before offering solutions?",
  "What would make our check-ins feel more caring and less routine?",
  "How can I stand beside you during uncertainty without rushing you toward an answer?",
  "What tells you that someone is truly in your corner?",
  "Which responsibilities feel lighter when we approach them as a team?",
  "What kind of reassurance feels genuine to you rather than automatic?",
  "How do you like to be supported when you are excited but nervous about something?",
  "What could I do to make receiving help from me feel more comfortable?",
  "Where could we give each other more grace this week?",

  "What kind of affection helps you feel close on an ordinary day?",
  "How do you naturally show care when words do not quite fit?",
  "Which gesture from me tends to stay with you afterward?",
  "What makes a moment between us feel tender to you?",
  "When you are stressed or distracted, what adjustment to affection feels right?",
  "What form of closeness feels especially welcome lately?",
  "Which quiet expression of care do you think deserves more appreciation?",
  "How can we make warmth easier to express when the day has been busy?",
  "What affectionate habit would you enjoy creating together?",
  "When do words of care mean the most to you?",
  "What helps affection feel sincere and not expected?",
  "When you reach for connection, which response from me feels most welcoming?",
  "Which kinds of compliments feel most meaningful to receive?",
  "What does emotional closeness feel like in your body or mood?",
  "In your experience, what separates attention from affection?",
  "What caring gesture feels uniquely like us?",
  "When you need space, what forms of warmth still feel good?",
  "What helps you feel cherished without putting you on the spot?",
  "How do playfulness and affection connect for you?",
  "What is one gentle way we could reconnect at the end of a long day?",

  "What helps trust grow between two people after the early excitement settles?",
  "Which of my actions makes you feel that you can rely on me?",
  "How do you decide when it feels safe to be more open?",
  "What does keeping your word look like in the small moments?",
  "Where would greater predictability help you feel more secure with me?",
  "How can we be honest about uncertainty without weakening trust?",
  "What makes an apology believable to you?",
  "When plans change, what kind of communication protects your trust?",
  "What agreement should guide us when either person shares something in confidence?",
  "What does loyalty mean to you in a partnership like ours?",
  "Which boundary helps you trust more freely rather than less?",
  "How can I show that I take your concerns seriously even when I see things differently?",
  "What helps you believe that a difficult conversation will remain respectful?",
  "When you make a mistake, what response helps you stay honest instead of defensive?",
  "What is one way trust can be strengthened without a big conversation?",
  "How should we address assumptions before they turn into doubts?",
  "What makes vulnerability feel cared for after it is shared?",
  "How do consistency and flexibility each contribute to trust for you?",
  "What would transparency look like in an area where we currently rely on guesswork?",
  "Which promises should always be discussed rather than casually made?",

  "While you explain something important, what lets you know I am truly listening?",
  "How can I check that I understood you without making you repeat everything?",
  "What tone helps you stay open during a sensitive conversation?",
  "When is silence from me comforting, and when does it feel distant?",
  "What is your preferred way to raise an issue before it becomes frustrating?",
  "How should a partner introduce a concern so curiosity stays possible?",
  "Which conversations are better for us in person rather than by message?",
  "How can we signal that we need more time to find the right words?",
  "What tends to get lost when we communicate in a hurry?",
  "When a comment lands badly, what is the best way for us to clarify its intent?",
  "What helps you speak honestly when you expect we may disagree?",
  "When do you want questions, and when would you rather finish your thought uninterrupted?",
  "Where could directness and gentleness work better together in our conversations?",
  "What is a phrase that helps you feel invited into a conversation rather than confronted?",
  "What approach could help us revisit topics that never seem to have a clean ending?",
  "Which aspect of your communication style deserves a more generous reading from me?",
  "When emotions are high, what pace helps you communicate clearly?",
  "How can we tell each other that something is hard to discuss without shutting it down?",
  "Where could our everyday conversations become more balanced?",
  "Which misunderstanding taught you something useful about how we communicate?",

  "What have I done lately that made you feel appreciated?",
  "Which part of what you bring to our relationship are you proudest of?",
  "What effort of yours would you like me to acknowledge more clearly?",
  "How do you most enjoy being thanked?",
  "What quality in me have you come to value in a new way?",
  "Which ordinary moment between us are you grateful for today?",
  "What is something we do well together that we rarely name?",
  "How has my presence made a recent experience better for you?",
  "What do you appreciate about the way we handle differences?",
  "Which strength of yours do you feel this relationship brings forward?",
  "What is one choice I made that helped you feel considered?",
  "How can we celebrate each other's progress without turning it into pressure?",
  "What detail about me are you glad you have gotten to know?",
  "Which shared memory reminds you of what works well between us?",
  "What kind of recognition motivates you, and what kind feels uncomfortable?",
  "How has your appreciation for us changed recently?",
  "What is something kind you noticed me do that you never mentioned?",
  "Which of our differences has become easier to value?",
  "What would you like us to thank each other for more often?",
  "How can appreciation remain specific and meaningful between us?",

  "What personal boundary helps you show up more fully in a relationship?",
  "When you say no or change your mind, what response from me best honors your choice?",
  "Which kinds of plans need more checking in before either of us commits?",
  "What does respectful privacy look like to you while staying connected?",
  "How can we talk about limits before either person feels stretched too far?",
  "What signs tell you that you need time to yourself?",
  "Where would a clearer agreement make our choices feel more mutual?",
  "When one of us wants to decline an invitation, what handling feels respectful?",
  "What helps you express a boundary without fearing disconnection?",
  "Which expectations should never be treated as automatic between partners?",
  "What could make pausing or opting out feel free from guilt between us?",
  "When I set a limit, what context would make its purpose clearer to you?",
  "When our comfort levels differ, what would a respectful next step look like?",
  "How do you distinguish between healthy compromise and giving up too much?",
  "What makes a request feel like a choice rather than an obligation?",
  "Which area of your life is important for you to keep independently yours?",
  "How should we check in when a previously comfortable situation starts to feel different?",
  "What does giving each other room look like without becoming disconnected?",
  "How can we protect personal downtime while still caring for the relationship?",
  "What would help us notice and respect a quiet no as carefully as a spoken one?",

  "What need has been easiest for you to name with me?",
  "How do you notice that one of your needs has gone unattended?",
  "What do you need more of from your own life, apart from anything I can provide?",
  "Which need do you sometimes minimize because it feels inconvenient?",
  "How can we separate asking for something from expecting an immediate yes?",
  "What helps you translate a feeling into a clear request?",
  "Where could I ask instead of assuming what you need?",
  "When our needs compete for time or energy, what response would feel considerate?",
  "What need feels especially important for you this month?",
  "Which kind of care is hardest for you to request directly?",
  "Which habit could help us discuss unmet needs before resentment builds?",
  "What helps you decide whether to meet a need yourself or bring it to me?",
  "When you cannot offer what I ask for, how would you like that conversation to go?",
  "What is a need you understand differently now than you once did?",
  "What check-in could help us recognize needs that change from day to day?",
  "What would help you feel less responsible for guessing what I need?",
  "Which shared need deserves more deliberate attention from us?",
  "What would let my curiosity about your needs feel caring rather than examining?",
  "Which way of framing a request helps you hear it without feeling criticized?",
  "How might we care for the relationship when both of us need rest?",

  "What kinds of decisions feel best when we make them together?",
  "When practicality competes with meaning, how do you weigh the two?",
  "Which choice on our horizon deserves a slower conversation?",
  "What shows you that your perspective genuinely shaped a shared decision?",
  "How should we move forward when neither option fully satisfies both of us?",
  "What role does intuition play in the choices you make with a partner?",
  "How much time do you usually need before committing to an important plan?",
  "What information helps you feel ready to decide?",
  "Where do you prefer a clear plan, and where do you enjoy spontaneity?",
  "How can we revisit a shared decision if its impact is different than expected?",
  "What does fairness mean when we contribute in different ways?",
  "What division of the work behind making plans would feel fair to you?",
  "Which values should guide us when convenience and principle pull apart?",
  "Which signs show that a shared decision reflects both people's influence?",
  "How can we avoid treating the faster answer as the final answer?",
  "What should we consider before making commitments that affect each other?",
  "When would you rather take the lead, and when would you prefer I did?",
  "How do we know when a choice is truly ours rather than shaped by outside expectations?",
  "What decision-making habit would make us a stronger team?",
  "How can we leave room for either person to reconsider without losing momentum?",

  "What are you quietly hoping for in the next chapter of your life?",
  "Which shared possibility feels energizing to imagine right now?",
  "How do you hope our connection will feel as we both continue to change?",
  "What experience would you love for us to create together someday?",
  "Which part of the near future are you most curious about?",
  "What personal goal would you like me to understand rather than manage?",
  "How can our relationship support the person you hope to become?",
  "What do you want us to preserve even as circumstances shift?",
  "Which dream feels more possible when you say it out loud?",
  "What would a fulfilling ordinary week look like for you in the future?",
  "As new interests emerge, where should they find space in each other's lives?",
  "What kind of courage do you want us to encourage in one another?",
  "Which future conversation are you looking forward to having with me?",
  "What do you hope we become better at together?",
  "Where would you enjoy taking our sense of adventure next?",
  "What is one hope for us that feels both simple and important?",
  "Where do you want more possibility and less pressure in your life?",
  "How can we cheer for separate goals while staying connected?",
  "What shared value do you hope will shape our next big choice?",
  "Which part of your future would you like us to remain curious about together?",

  "After a tense moment, what helps you feel ready to reconnect?",
  "Which cues show that you need a pause rather than an immediate resolution?",
  "What makes taking responsibility feel sincere to you?",
  "Which repair gesture works for you only when the timing is right?",
  "When a conversation goes off track, what helps us begin again?",
  "How do you recognize that the impact of a hurtful moment has truly been understood?",
  "When an apology is offered, what follow-through matters most?",
  "How can we disagree without making the relationship itself feel uncertain?",
  "Which early sign of tension should we pay more attention to next time?",
  "Which words or actions make it easier for you to lower your guard?",
  "How should we return to a topic after taking space?",
  "What does forgiveness mean to you when trust still needs time?",
  "How can we acknowledge different memories of the same disagreement?",
  "What helps you recognize that I am trying to repair, even if my attempt is imperfect?",
  "When humor enters a tense moment, what makes it connecting rather than dismissive?",
  "What language could help us name patterns without blaming each other?",
  "What lesson from a past disagreement could serve us now?",
  "When something cannot be undone, what would meaningful amends look like?",
  "What lets you know a difficult chapter is actually changing?",
  "Which small reset could help us move from defensiveness back to teamwork?",

  "What are you curious to learn about the way I experience our relationship?",
  "Which part of my inner world feels least familiar to you?",
  "What assumption about me would you like to replace with a question?",
  "How have I changed in a way you are still getting to know?",
  "What would you ask if you knew there was no perfect answer?",
  "Which of my reactions has made you wonder what was happening underneath?",
  "What topic between us deserves fresh curiosity instead of an old conclusion?",
  "How do you think I feel most cared for, and what makes you think so?",
  "Where does my way of making decisions leave you most curious?",
  "Which difference between us are you interested in exploring more?",
  "What question could help us see a familiar story from a new angle?",
  "How might your view of me be incomplete in a way worth discovering?",
  "What part of our dynamic do you find most interesting?",
  "Which opinion of mine would you like to hear more about?",
  "What do you wonder about the way I experience closeness?",
  "How could we stay curious when we think we already know what the other will say?",
  "What is something about us that you cannot fully explain but enjoy noticing?",
  "Which question are you glad I have never stopped asking you?",
  "What new context might help me understand a choice you made?",
  "Where could curiosity help us be kinder to each other?",

  "Which conditions give you enough emotional safety to be candid with me?",
  "How do you know when a conversation is respectful even if it is uncomfortable?",
  "Which response from me helps you feel accepted while you are being vulnerable?",
  "What would make it safer to admit that you do not know what you feel yet?",
  "What shared rule could guard against either of us feeling mocked or dismissed?",
  "When you share something delicate, what kind of follow-up feels caring?",
  "What helps you trust that your feelings will not be used against you later?",
  "How should we respond if one of us realizes a topic feels too personal for the moment?",
  "What does being on the same side look like during a hard conversation?",
  "Which signs tell you that it is okay to speak more freely?",
  "How can we welcome honesty that is still uncertain or unfinished?",
  "What makes room for disagreement without threatening belonging?",
  "In which moments have our different viewpoints still left you feeling respected by me?",
  "How could we make questions feel less like tests and more like invitations?",
  "What creates enough confidence for you to say, 'I see it differently'?",
  "How do we keep a private conversation private in ways that feel clear to both of us?",
  "Which reassurance gives you courage to take an emotional risk?",
  "Where can we replace judgment with a genuine wish to understand?",
  "If you decide not to answer something, what response from me would respect that choice?",
  "What practice could help both of us feel safer bringing up small concerns?",

  "What everyday ritual helps you feel that we are choosing each other?",
  "How does the way we spend attention affect your sense of connection?",
  "Which part of our current rhythm feels nourishing to you?",
  "What small change could make our time together feel more intentional?",
  "After we have both been focused elsewhere, what brings you back into connection?",
  "What kind of shared quiet feels companionable to you?",
  "Which routine would you happily make more playful?",
  "How can we create meaningful moments without needing elaborate plans?",
  "What helps you stay present when we have time together?",
  "Where in our routine could we make more room for conversation?",
  "What does quality time mean to you when energy is limited?",
  "Which simple experience brings out the best in us?",
  "How might we protect connection during especially busy periods?",
  "What pace of togetherness and independence feels healthy to you right now?",
  "When do you most enjoy doing separate things in the same space?",
  "What shared habit no longer fits us as well as it once did?",
  "What might smooth the transitions between work, rest, and time together?",
  "Which ordinary part of life would you like to experience more consciously with me?",
  "What helps a planned moment feel genuine rather than scheduled?",
  "Where might a little more delight fit into the life we have now?",

  "What feeling have you wanted more room to express lately?",
  "If your feelings shift mid-conversation, which response from me would support you?",
  "Which emotion is easiest for you to share with me, and why?",
  "When you do not want cheering up, what still helps you feel accompanied?",
  "How can I recognize when excitement matters as much as distress?",
  "Which part of how you process feelings is often misunderstood?",
  "When you are disappointed, what kind of presence feels supportive?",
  "How does being understood differ from being agreed with for you?",
  "What helps you name mixed feelings without needing to simplify them?",
  "Which emotions do you tend to express through actions more than words?",
  "Where can feelings that neither of us can fix find room between us?",
  "What does validation sound like in language that feels natural to you?",
  "When you feel proud of yourself, how would you like me to join that moment?",
  "What helps you share frustration without feeling defined by it?",
  "If I misread your emotional state, what response would help me reconnect with you?",
  "Which feeling has taught you something useful about what matters to you?",
  "When you lack a full explanation, what allows emotional honesty to come more easily?",
  "How can we keep one person's mood from becoming the other person's job?",
  "What would compassionate attention look like for you today?",
  "Which emotion would you like us to become better at welcoming together?",
] as const satisfies readonly string[]
