export const STRANGERS_GROUP_WARM_UP: readonly string[] = [
  'What kind of energy are you bringing into the room today?',
  'Which word best captures your current pace?',
  'What color matches your energy right now, and why?',
  'If your entrance had background music, what would be playing?',
  'What small detail in this space caught your attention first?',
  'Where in the room would you choose to sit if every spot were open?',
  'Which nearby object seems most interesting to you?',
  'How does this setting compare with places where you usually relax?',
  'What would make this room feel one notch more comfortable?',
  'What is something pleasant you noticed on your way here?',
  'Which sound in the background would you keep in a soundtrack of this moment?',
  'How would you rename this gathering based only on the atmosphere so far?',
  'What imaginary scent would fit the mood of the room?',
  'If this group were meeting inside a movie scene, what kind of scene would it be?',
  'Which part of meeting new people feels easiest for you?',
  'How do you usually settle into an unfamiliar group?',
  'What helps a first conversation feel natural to you?',
  'What sign tells you that a group is beginning to feel comfortable?',
  'Which way of participating appeals today: talking, listening, joking, or something else?',
  'What kind of question are you most in the mood to answer?',
  'Which role sounds appealing right now: storyteller, curious listener, or comic relief?',
  'How much thinking time do you enjoy before answering a playful question?',
  'What makes passing on a question feel easy and ordinary?',
  'Which group habit could offer a warm opening to quieter voices?',
  'How can people show they are listening without interrupting?',
  'Which conversational habit makes you feel included quickly?',
  'What does a friendly pause in conversation feel like to you?',
  'How would you signal that you want to hear more from someone?',
  'Which simple preference could you happily explain for a minute?',
  'Which everyday choice do you enjoy making more than most people?',
  'What makes a morning begin well for you?',
  'What does your ideal low-key evening include?',
  'Which snack deserves a permanent place at group gatherings?',
  'What drink feels most like a small treat to you?',
  'How would you build the perfect sandwich for your taste?',
  'What food texture do you find especially satisfying?',
  'Which flavor do you reach for when you cannot decide?',
  'What meal works at almost any time of day?',
  'Where would an unexpected free hour most likely take you?',
  'What kind of background noise helps you focus?',
  'Which kind of daylight best matches your energy?',
  'What temperature makes a day feel just right?',
  'Where would you rather watch a sunset: a rooftop, a beach, or somewhere else?',
  'Which excuse most happily gets you outside?',
  'What tips your decision between staying in and going out?',
  'Which type of journey is more fun for you than the destination?',
  'What makes a walk worth taking?',
  'Where do you like to go when you want a change of scenery?',
  'What song would you add to a playlist for people who just met?',
  'Which instrument has a sound you always notice?',
  'How do you discover music that is new to you?',
  'What kind of song improves an ordinary task?',
  'Which familiar tune could you recognize in only a few seconds?',
  'What movie genre matches your sense of fun?',
  'Which fictional side character would improve most shows?',
  'Which fictional setting would make a great place for a casual meetup?',
  'What makes a story easy for you to get lost in?',
  'Who is a fictional character you would trust to plan a party?',
  'Which kind of ending leaves you most satisfied?',
  'How would you explain your taste in entertainment to a stranger?',
  'What is a topic you enjoy learning about just for fun?',
  'Where does your curiosity tend to wander online?',
  'What harmless rabbit hole have you enjoyed exploring?',
  'Which question about the everyday world would you love answered?',
  'Which approach helps you learn something unfamiliar?',
  'What skill looks enjoyable even if you never master it?',
  'Which museum section would you visit first?',
  'What could someone teach you in five minutes that you would appreciate?',
  'How would you spend a day devoted entirely to curiosity?',
  'What ordinary process seems surprisingly fascinating?',
  'Which tiny mystery do you still wonder about?',
  'What subject becomes interesting when the right person explains it?',
  'Which three objects could describe you better than three adjectives?',
  'What personal quality tends to show up early when you meet people?',
  'Which side of your personality is awake today?',
  'What is an easy-to-miss thing that delights you?',
  'How would a friendly narrator introduce you right now?',
  'Which everyday item feels most like part of your signature look?',
  'What is a small choice that says a lot about your style?',
  'What harmless topic can always tempt you into a playful debate?',
  'What kind of compliment is especially fun for you to receive?',
  'Which animal matches one of your lighter personality traits?',
  'What would your imaginary personal mascot be?',
  'How would you represent your personality with a simple logo?',
  'What three ingredients would go into a recipe called “You Today”?',
  'What would the tagline on your harmless action figure box say?',
  'What words capture your laugh without demonstrating it?',
  'What nickname would you give your most productive mode?',
  'Which version of you shows up when plans change unexpectedly?',
  'What is one gentle contradiction in your personality?',
  'What do you become unexpectedly enthusiastic about?',
  'How would you finish the sentence “I am usually the person who…”?',
  'Which small decision do you make with surprising confidence?',
  'What is something you approach with beginner energy?',
  'What puts your personal stamp on an ordinary day?',
  'What strength of yours is useful in everyday situations?',
  'Which task brings out your patient side?',
  'How do you help when a plan needs organizing?',
  'What are you good at noticing before others mention it?',
  'Which practical ability are you glad to have?',
  'What kind of problem do you enjoy untangling?',
  'How do you make people feel welcome in a casual setting?',
  'What is your most reliable contribution to a group project?',
  'Which strength becomes obvious when you are having fun?',
  'What do people often ask for your help with?',
  'How would you use one of your talents to improve a rainy afternoon?',
  'What is a quiet skill that deserves more appreciation?',
  'Which ability would you happily lend this group for the next hour?',
  'What can you do faster than most everyday tasks require?',
  'Which role do you naturally take when a group plan changes?',
  'What type of encouragement comes naturally to you?',
  'Which detail are you especially good at remembering?',
  'What is your preferred way to make a decision with others?',
  'How do you keep a conversation moving when it slows down?',
  'What playful award could you realistically win today?',
  'Which made-up competition would suit your oddly specific strengths?',
  'What would you be the unofficial expert on in this room?',
  'If everyone here formed a trivia team, what category would you volunteer for?',
  'What game rule would you be good at explaining?',
  'How would you contribute to planning an imaginary picnic?',
  'Which job would you choose on a team building a blanket fort?',
  'What part would you play in a low-stakes heist to steal the last cookie?',
  'If the group opened a tiny café, what would you add to the menu?',
  'What would your specialty be on an expedition to the corner shop?',
  'How might you help this group win a contest with no athletic events?',
  'Which harmless mission could everyone here complete in ten minutes?',
  'What team name would you suggest based on what you can see around you?',
  'How would you design a flag for this gathering?',
  'What silly tradition could this group begin immediately?',
  'Which object nearby would make the best team mascot?',
  'What theme would you choose for an impromptu group photo?',
  'How could everyone turn this room into a one-minute adventure?',
  'What imaginary headline should describe this gathering tomorrow?',
  'Which collective superpower would be entertaining but not very useful?',
  'What do you guess this group could agree on unusually quickly?',
  'What snack does the atmosphere suggest might disappear first?',
  'Which song do you imagine could get the widest range of reactions here?',
  'What harmless debate might divide the room almost evenly?',
  'How would you guess this group handles a surprise change of plans?',
  'What board game role seems likely to be popular around here?',
  'Which imaginary destination might earn the most group votes?',
  'What do you predict would make everyone laugh at once?',
  'How many different uses could this group invent for a paper cup?',
  'What kind of group challenge seems to fit the energy so far?',
  'Which weather forecast would best match the room right now?',
  'What might be the unofficial color of this gathering?',
  'What pace has the conversation found so far?',
  'What do the seating choices suggest about the mood in the room?',
  'Which visible detail could inspire a group nickname?',
  'What is one friendly observation you can make about the space we share?',
  'How has the energy shifted since everyone arrived?',
  'What part of the setting seems most likely to start a conversation?',
  'Which shared circumstance gives us an easy thing to talk about?',
  'What would an outside observer find cheerful about this scene?',
  'How could the lighting here be described as a personality?',
  'What does the room seem ready for next?',
  'Which detail would you include in a postcard from this moment?',
  'What would you change if you were the set designer for this gathering?',
  'How might this space look from the viewpoint of a very small animal?',
  'What story could explain the most unusual object you can see?',
  'Which corner would make the best stage for a two-minute talent show?',
  'What name would suit a café designed to look exactly like this place?',
  'What details would help someone picture this room without seeing it?',
  'What feature here would you keep in your dream hangout space?',
  'What harmless first impression do you think your outfit gives today?',
  'Which accessory in the room seems to have the biggest personality?',
  'Which book genre resembles your current look?',
  'What practical choice did you make when getting ready today?',
  'Which color are you happiest to wear or carry?',
  'What item do you almost always bring when leaving home?',
  'How does comfort influence what you choose to wear?',
  'What style from another era would you try for one afternoon?',
  'Which fictional character would you trust to choose your outfit?',
  'What tiny upgrade makes you feel more put together?',
  'How would you dress for an event called “casually spectacular”?',
  'What visual detail tends to catch your eye on other people?',
  'Which pattern deserves to appear on more things?',
  'What object in your pocket or bag is most useful today?',
  'How would you redesign an everyday item to make it more fun?',
  'What is the best shape for a piece of furniture?',
  'Which ordinary object has excellent design?',
  'What color combination always works for you?',
  'What breaks a tie when several options look equally good?',
  'What would your ideal name tag reveal besides your name?',
  'What easy question could you ask almost anyone?',
  'Which answer usually leads you to a good follow-up question?',
  'How do you show curiosity when someone mentions an unfamiliar interest?',
  'What topic makes it easy for you to ask “Tell me more”?',
  'What makes a question feel welcoming rather than demanding?',
  'How can a listener make room for an answer to change direction?',
  'Which conversation cue tells you someone wants to continue?',
  'What do you appreciate about people who listen carefully?',
  'How would you invite someone back into a discussion after a pause?',
  'What is a graceful way to change the subject in a group?',
  'Which follow-up question helps people share at their own pace?',
  'What makes an explanation enjoyable to listen to?',
  'How do you respond when someone gives an answer you did not expect?',
  'What can turn small talk into genuinely interesting talk?',
  'Which signs make a conversation feel balanced?',
  'How can disagreement stay both playful and respectful?',
  'What lets different senses of humor share the same conversation?',
  'What makes a group introduction feel less formal?',
  'Which kinds of details stick with you after a conversation?',
  'What would make introductions more enjoyable than usual?',
  'What is a harmless opinion you enjoy hearing different takes on?',
  'Which everyday convenience would you nominate for an award?',
  'How should the perfect weekend breakfast be arranged?',
  'What common item would benefit from a complete redesign?',
  'Which minor luxury feels worth the effort every time?',
  'What makes a seat the best seat in a room?',
  'How would you rank comfort, style, and usefulness when choosing a chair?',
  'What household chore would be improved by adding music?',
  'Which errand can be unexpectedly enjoyable?',
  'Which spontaneous plan would be easiest for this group to enjoy?',
  'How early is “on time” in your personal clock?',
  'What small purchase reliably brightens an ordinary day?',
  'Which simple thing should always be available at a gathering?',
  'What makes a gift thoughtful without making it expensive?',
  'How would you improve the standard waiting-room experience?',
  'What is the finest use of a five-minute break?',
  'Which everyday smell deserves more appreciation?',
  'What sound makes a place feel welcoming?',
  'Where would you place the perfect spot for people-watching?',
  'What tiny inconvenience inspires your most creative solution?',
  'If your day had a texture, what would it feel like?',
  'What would today look like as a simple doodle?',
  'Which food comparisons could capture this moment?',
  'What imaginary holiday would fit your current mood?',
  'Where would your thoughts go if they could take a short vacation?',
  'What would a souvenir from your morning look like?',
  'Which cartoon sound effect belongs in your day?',
  'How would a sports commentator narrate your arrival?',
  'What would the menu description for your personality say?',
  'If your attention were a flashlight, what would it be pointing at?',
  'What shape is your schedule today?',
  'Which fictional vehicle matches your usual pace?',
  'What would your personal loading-screen message say?',
  'How would you turn your current mood into a dance move?',
  'What would be inside a starter pack for getting to know you?',
  'Which three sounds could form your personal doorbell?',
  'What would your friendly warning label mention?',
  'How might a poet describe your favorite snack?',
  'What would you name a boat based on your sense of humor?',
  'What recent moment made you curious rather than certain?',
  'Which new experience would feel easy to try with a group?',
  'How do you decide what deserves a closer look?',
  'What is something nearby you would like to know the history of?',
  'Where would you look first for inspiration on a blank afternoon?',
  'What question would you ask an expert in any harmless subject?',
  'Which everyday skill would you like to watch someone perform brilliantly?',
  'What unfamiliar food would you sample if someone recommended it warmly?',
  'How could you make learning a new name into a game?',
  'What place would you explore if you had a perfect local guide?',
  'Which creative hobby would you test with free supplies and no audience?',
  'What would you like to understand about how something is made?',
  'How do you react when a plan leads somewhere unexpectedly interesting?',
  'What harmless experiment would you run for a day?',
  'Which question could inspire ten very different answers in this group?',
  'What would you ask the room if curiosity earned points?',
  'How might you turn an ordinary object into a conversation starter?',
  'What new group activity could be invented from things within reach?',
  'Which perspective do you enjoy hearing when people compare preferences?',
  'What could everyone teach in a one-minute skill swap?',
  'What kind of contribution feels comfortable for you in a new group?',
  'Which option sounds best right now: answer first, answer later, or simply listen?',
  'How would you like others to respond if you pass on a prompt?',
  'What role can a quiet participant play in making a gathering enjoyable?',
  'What gives you enough space to think before joining in?',
  'How can someone join a lively conversation without competing for attention?',
  'Which group size makes casual conversation easiest for you?',
  'What format would make sharing ideas feel more playful?',
  'How do you prefer a group to choose what happens next?',
  'What invitation to participate feels genuinely optional?',
  'Which activity lets people contribute in different ways?',
  'What makes taking turns feel natural instead of formal?',
  'How can a host help everyone find their own level of involvement?',
  'What would a comfortable five-minute break look like?',
  'Which signal could mean “I’m happy to listen this round”?',
  'What helps a group recover smoothly from an awkward moment?',
  'How would you make room for someone who changes their mind?',
  'What does respectful curiosity sound like in a mixed group?',
  'Which simple agreement could keep a conversation low-pressure?',
  'What choice should every participant get to make for themselves?',
  'What is one light thing you would enjoy being asked about?',
  'Which everyday story can you tell without needing much setup?',
  'How would you introduce one of your interests to complete beginners?',
  'What recent discovery is easy for you to recommend?',
  'Where do you find small moments of amusement?',
  'What part of your routine has the most personality?',
  'Which object you use often deserves a better name?',
  'Which uncomplicated plan are you looking forward to?',
  'How do you add variety to a familiar week?',
  'Where would ten bonus minutes with no obligations go?',
  'What small thing makes a place feel friendly to you?',
  'Which type of welcome feels most natural to give?',
  'What do you enjoy contributing when people gather casually?',
  'How can strangers become a good temporary team?',
  'What shared activity makes names easier to remember?',
  'Which low-stakes challenge could reveal everyone’s creative side?',
  'What would make the rest of this gathering feel like time well spent?',
]
