export const STRANGERS_FRIENDS_CONNECT = [
  "What part of our friendship feels especially worth celebrating?",
  "Which quality in me has become more meaningful as you've known me longer?",
  "How have I made an ordinary day better for you?",
  "What do you appreciate about the way we spend time together?",
  "Which side of you gets more room to exist in our friendship?",
  "What is something I bring to your life that you hope I never underestimate?",
  "When have you felt quietly cared for by me?",
  "What about our friendship makes you feel lucky?",
  "Which of my everyday gestures carries more meaning than I probably realize?",
  "How would you describe the kind of joy we create together?",
  "What makes an appreciation feel sincere to you?",
  "Which recent choice of mine would you like to acknowledge?",
  "How has knowing me added something unexpected to your life?",
  "What do you value about the pace of our friendship?",
  "Which difference between us has enriched your perspective?",
  "What do you think we bring out in each other at our best?",
  "How do you like friends to show that they notice your effort?",
  "Which memory best captures what you value about us?",
  "What would you thank this friendship for if it could hear you?",
  "How can a friend tell when you want comfort rather than solutions?",
  "What kind of support feels useful when your energy is low?",
  "When life gets busy, what small gesture helps you still feel remembered?",
  "What makes it easier for you to ask a friend for help?",
  "How would you want me to check in when you seem unlike yourself?",
  "What type of encouragement helps you keep going without feeling pressured?",
  "When you share a problem, how do you prefer someone to respond first?",
  "What practical help from a friend tends to make the biggest difference?",
  "How can I support something important to you without taking it over?",
  "Which action from a friend makes support feel dependable?",
  "Which forms of support do you find easiest to receive?",
  "What makes help feel respectful rather than intrusive?",
  "When your needs change, which response from friends feels most supportive?",
  "What would make a difficult week feel less lonely?",
  "When you are excited about something, what response helps you feel supported?",
  "How can friends care for you when there is nothing they can fix?",
  "What kind of reminder feels encouraging when you are working toward a goal?",
  "When would giving you space be the most caring response?",
  "What is one way we could make asking each other for support more natural?",
  "What helps trust grow slowly between friends?",
  "When did our friendship begin to feel dependable to you?",
  "What does keeping someone's confidence mean in practice?",
  "How do you decide which parts of yourself are safe to share with a friend?",
  "What action rebuilds trust more effectively than a promise?",
  "Which agreements matter most for protecting a friendship?",
  "How would you want a friend to handle information you shared privately?",
  "What makes honesty feel caring instead of harsh?",
  "When has consistency mattered more to you than a grand gesture?",
  "What helps you believe that a friendship can survive an uncomfortable truth?",
  "How should a friend respond after realizing they broke your trust?",
  "What makes someone feel emotionally reliable to you?",
  "If a promise can no longer be kept, how should the person address it?",
  "What would you want us to clarify rather than assume about each other?",
  "Which part of trust comes most naturally to you, and which takes intention?",
  "How can friends be honest about uncertainty while staying dependable?",
  "When is privacy especially important in a friendship?",
  "What would help you trust that a disagreement will not end our friendship?",
  "What helps you feel fully heard in a conversation?",
  "How do you signal that you need someone to listen without offering advice?",
  "What kind of follow-up question makes you feel understood?",
  "When do pauses improve a conversation for you?",
  "How would you like me to check that I understood what you meant?",
  "What tends to make you stop sharing, even when someone means well?",
  "How can a friend listen well when their experience is very different?",
  "What conversation deserves more attention between us?",
  "When time is limited, what is a considerate way to interrupt you?",
  "What makes curiosity feel genuine rather than nosy?",
  "When have you changed your view because a friend listened carefully?",
  "What helps you stay present when a conversation becomes complicated?",
  "How can we tell each other when we do not have the capacity for a full conversation?",
  "Which details help you feel that someone remembers what matters to you?",
  "What do you wish people understood about the way you communicate?",
  "How do you want a friend to respond when your words come out wrong?",
  "What helps you listen without preparing your reply?",
  "How can we make space for both people when one story takes up most of a conversation?",
  "What does attentive listening look like when we are communicating by text?",
  "What boundary has made your friendships healthier?",
  "How do you like someone to ask before offering advice?",
  "What makes it easier to say no to a friend without fearing distance?",
  "How should we handle topics one of us would rather skip?",
  "When you set a new limit, which response from friends feels respectful?",
  "What are your signals that a joke has gone far enough?",
  "How can we protect each other's privacy in group settings?",
  "What expectations around replying to messages feel fair to you?",
  "When do you prefer an invitation with no follow-up pressure?",
  "What personal choice do you most want friends to respect without debate?",
  "How can someone ask about a sensitive subject while leaving a real option not to answer?",
  "What does enough alone time look like for you within a close friendship?",
  "How would you like me to tell you when I need to change a plan?",
  "What boundary can be easy to miss unless it is spoken aloud?",
  "How do you balance being available with protecting your own energy?",
  "What would help us disagree with a boundary without challenging the person's right to set it?",
  "When has a clear limit allowed you to be a better friend?",
  "How should we respond if one of us shares more than intended?",
  "How has your capacity for friendship changed recently?",
  "What kind of contact feels manageable during your busiest seasons?",
  "How do you want our friendship to adapt when one of us has less time?",
  "What helps you stay connected across different routines?",
  "When plans keep changing, what communication preserves goodwill for you?",
  "How can friends avoid measuring care by response speed?",
  "During a quieter season, what would keep our friendship feeling secure?",
  "After a long gap, what kind of reconnection feels natural to you?",
  "What is a realistic rhythm for us when life is full?",
  "How can we be honest about availability before resentment builds?",
  "What kinds of plans fit your life better now than they once did?",
  "When you have little social energy, what form of connection still feels welcome?",
  "What does staying close mean when we cannot be consistently present?",
  "How can a friendship remain mutual when our free time is unequal?",
  "What helps you feel included even when you cannot join an event?",
  "How would you like a friend to explain a period of distance?",
  "What change in your life would you want our friendship to accommodate?",
  "How can we keep cancellations from feeling like personal rejection?",
  "What is one low-effort way we could remain part of each other's lives?",
  "Where do you feel the strongest sense of belonging with friends?",
  "What helps you know there is room for you in a group?",
  "How can a friend make an unfamiliar setting feel more welcoming?",
  "What allows you to be yourself without performing a role?",
  "When have you felt chosen in a friendship?",
  "What group habit helps everyone have a voice?",
  "How do you like to be brought into a conversation when you are quiet?",
  "What makes an invitation feel thoughtful rather than obligatory?",
  "How could we notice when someone is at the edge of the group?",
  "What shared space would you like our friendship to create?",
  "How does belonging feel different from simply being included?",
  "What helps you enter a friendship where others already share history?",
  "How can inside jokes stay fun without leaving people behind?",
  "What makes you feel welcome to bring different opinions into a friendship?",
  "How do you know when a group values your presence, not just your participation?",
  "What part of yourself feels most at home around trusted friends?",
  "How can we make plans that account for different comfort levels?",
  "What would help you speak up if you felt overlooked?",
  "What could our friendship do to make room for who we are becoming?",
  "How do you usually realize that tension needs to be discussed?",
  "What approach helps you stay open during a disagreement?",
  "When conflict arises, what do you need before trying to solve it?",
  "How can we challenge an idea without making the person feel diminished?",
  "What makes a difficult conversation feel fair to you?",
  "What is a gentle way to name a small irritation before it grows?",
  "What helps you separate someone's impact from their intention?",
  "When is it better to pause a disagreement and return later?",
  "How would you want me to raise a concern about our friendship?",
  "What keeps defensiveness from taking over for you?",
  "How can friends make room for two different memories of the same event?",
  "What would respectful disagreement sound like between us?",
  "How do you want to be told when your words landed differently than you intended?",
  "What helps you remain curious when you feel misunderstood?",
  "Which conflicts are worth working through, even when they seem small?",
  "How can we avoid bringing an audience into a private disagreement?",
  "How do you tell the difference between compromise and abandoning your needs?",
  "What makes feedback from a friend easier to consider?",
  "How can we disagree without rushing to decide who is right?",
  "What makes an apology meaningful to you?",
  "How do you recognize when a friendship is ready for repair?",
  "What would help you believe that changed behavior will last?",
  "How should a friend make amends when the impact cannot be undone?",
  "What does taking responsibility sound like without self-punishment?",
  "When do you need time before accepting an apology?",
  "How can friends rebuild warmth after resolving the facts of a conflict?",
  "What small act can reopen connection after an awkward moment?",
  "If a hurt still lingers after seeming settled, how could we revisit it?",
  "What helps forgiveness remain a choice rather than an obligation?",
  "How can we acknowledge progress without pretending everything is fixed?",
  "How could we check whether an apology addressed what actually hurt?",
  "What have you learned about repairing friendship from a past mistake?",
  "How can someone show remorse without asking the hurt person to comfort them?",
  "What needs to be restored after trust has been strained?",
  "How would you want us to mark the end of a difficult chapter?",
  "How can a friend acknowledge impact while preserving everyone's dignity?",
  "How can a repaired friendship become wiser rather than simply return to normal?",
  "What part of who you are are you enjoying getting to know right now?",
  "How has friendship influenced the way you see yourself?",
  "Which version of you shows up when you feel accepted?",
  "What personal value has become clearer to you over time?",
  "As your interests change, what response do you value from friends?",
  "What assumption about you would you rather people replace with a question?",
  "Which part of your story do you like sharing with new friends?",
  "How can a friendship support growth without expecting constant reinvention?",
  "What do you hope your closest friends understand about your priorities?",
  "When have you felt free to revise an old opinion around friends?",
  "What name, description, or way of being addressed helps you feel recognized?",
  "How do different friendships reveal different strengths in you?",
  "What part of your personality takes time for people to notice?",
  "How would you like friends to respond when they are unsure about your experience?",
  "Which choice in your life feels especially true to you?",
  "How do you want our friendship to honor the ways we are different?",
  "What helps you feel known without feeling defined?",
  "How can friends give each other room to outgrow old labels?",
  "What aspect of yourself would you like to express more often around me?",
  "Which shared experience revealed something new about our friendship?",
  "What ordinary outing with me became more memorable than expected?",
  "How has a challenge we faced together shaped the way we cooperate?",
  "What moment between us would you preserve in perfect detail?",
  "Which conversation changed the direction of our friendship?",
  "What have we learned to do better through spending time together?",
  "How does one of our shared traditions reflect who we are?",
  "What unfinished adventure would you still like us to continue?",
  "Which place has taken on new meaning because we were there together?",
  "What did an unexpected change of plans teach you about us?",
  "How have our shared experiences differed from what you first imagined?",
  "What memory of us becomes funnier or richer each time it is told?",
  "Which quiet moment together felt more significant than it looked?",
  "What have you discovered about yourself while trying something with me?",
  "What experience would help us understand each other in a new setting?",
  "Which shared accomplishment deserves more celebration?",
  "How has distance changed the meaning of a memory we share?",
  "What have we navigated together that required patience from both of us?",
  "Which chapter of our friendship would you title, and what would you call it?",
  "What do you need more of from your friendships at this point in your life?",
  "How can I make it safer for you to tell me when a need is not being met?",
  "What form of reassurance feels genuine to you?",
  "When do you need clarity more than encouragement?",
  "When you want company, what makes asking for it feel comfortable?",
  "What need do you tend to minimize because it feels inconvenient?",
  "How can friends discuss unequal effort without keeping score?",
  "Which part of planning together helps your preferences carry real weight?",
  "Which need is easiest for you to express through actions rather than words?",
  "What would make our friendship feel more reciprocal?",
  "How can someone respond kindly when they cannot meet a friend's need?",
  "When do you most value predictability from a friend?",
  "How would you like us to handle needs that conflict?",
  "What kind of companionship feels restorative to you?",
  "How can we ask for more without erasing what is already being given?",
  "What need has become easier to name as you have grown?",
  "How do you want a friend to check whether their support is still helping?",
  "What is one expectation that becomes healthier when spoken plainly?",
  "How can we leave room for needs neither of us can anticipate?",
  "What helps a new friendship move beyond surface conversation at a comfortable pace?",
  "How do you know when you want to invest more in a newer friend?",
  "What would you like a new friend to learn about you gradually?",
  "How can two people build closeness without rushing disclosure?",
  "What early sign suggests a friendship could become important?",
  "What shift helps casual plans become a more intentional friendship?",
  "What question helps you understand a new friend's world?",
  "How can new friends be clear about interest without creating pressure?",
  "What does a comfortable first disagreement reveal to you?",
  "How do you make space for a new friend alongside established relationships?",
  "What kind of consistency helps a new connection take root?",
  "How would you like someone to follow up after an especially honest conversation?",
  "What are you curious to build with a friend you are still getting to know?",
  "How can new friends talk about expectations before habits form?",
  "Which part of friendship should never be hurried?",
  "How do you decide whether to extend another invitation after plans do not work out?",
  "What helps unfamiliar people become comfortable companions?",
  "How can a newer friendship acknowledge uncertainty without losing momentum?",
  "What would make you feel welcome to deepen this friendship?",
  "What helps a long-distance friendship feel present in daily life?",
  "How do you like to share small moments when we are far apart?",
  "What ritual could make distance feel less defining for us?",
  "How should we handle time differences or mismatched schedules?",
  "What kind of update helps you feel connected without requiring a long conversation?",
  "How can we celebrate each other's milestones from afar?",
  "What do you miss most when a friend lives far away?",
  "How would you like visits to balance planned time and breathing room?",
  "What makes digital communication feel warm to you?",
  "How can we stay curious about the lives we are not witnessing firsthand?",
  "After a misunderstanding over text, what repair approach works for you?",
  "What shared activity works surprisingly well from different places?",
  "How can we make reunions feel natural rather than like a test of closeness?",
  "What would help us plan contact without making it feel like an obligation?",
  "How has being apart changed what you value about a friendship?",
  "What deserves to be said directly instead of saved for the next visit?",
  "How can a distant friend stay informed without expecting every detail?",
  "What keeps physical distance from turning into emotional guesswork?",
  "What future memory would you like us to plan across the miles?",
  "How has our friendship matured without either of us noticing at first?",
  "What old pattern between us still serves us well?",
  "Which part of a long friendship needs deliberate renewal?",
  "How can longtime friends remain curious about each other?",
  "What do you understand about me now that took years to learn?",
  "How should friendship adapt when our lives take different directions?",
  "What history between us feels grounding rather than limiting?",
  "How can we keep nostalgia from replacing present-day connection?",
  "What change in me have you been glad to witness?",
  "Which assumption based on our past might need updating?",
  "How do you want us to care for the history we share?",
  "What helps a long friendship recover from taking each other for granted?",
  "How can we welcome new people without weakening an established bond?",
  "What would make the next season of our friendship feel intentional?",
  "What do we know about each other that helps us offer better care now?",
  "Which tradition should we revisit, revise, or retire?",
  "How can friends recognize when familiarity has become an excuse not to listen?",
  "What have we successfully allowed each other to become?",
  "What keeps a long friendship alive beyond shared history?",
  "How would you like our friendship to support your next chapter?",
  "How can we make room for future versions of each other?",
  "What would you like us to be more intentional about this year?",
  "How do you hope we will respond when one of us faces a major change?",
  "What kind of check-in would you want during an uncertain season?",
  "Which future celebration would you be excited to share?",
  "How can we protect our friendship from becoming only an item on a schedule?",
  "What would growing older as friends mean to you?",
  "How do you imagine our ways of showing care might evolve?",
  "What conversation could prepare us to support each other better later?",
  "How can we keep future plans flexible enough for real life?",
  "What do you hope remains recognizable about us through change?",
  "Which small commitment could make our friendship more sustainable?",
  "How would you like us to handle a future season when our priorities diverge?",
  "How can we remind each other of what matters without directing each other's choices?",
  "What would you like our friendship to make possible for both of us?",
  "How might we care for each other while also welcoming more independence?",
  "What do you hope we will be able to say honestly to each other years from now?",
] as const satisfies readonly string[]
