export const STRANGERS_PARTNER_REFLECT = [
  "What have you learned about yourself through being with me?",
  "How has your understanding of partnership changed during our time together?",
  "Which part of our relationship feels most different from when we began?",
  "Where have you noticed us becoming more thoughtful with each other?",
  "What has surprised you about the way we have grown together?",
  "How would you describe the chapter of our relationship we are in now?",
  "What do you understand about me now that took time to learn?",
  "Which shared experience changed how you see us as a team?",
  "In what way has knowing me expanded your view of a good relationship?",
  "What feels more natural between us now than it once did?",
  "How have our differences helped you see another point of view?",
  "What have we outgrown that you are glad no longer defines us?",
  "Which quality in our connection has become clearer over time?",
  "What does our relationship reveal about the kind of partner you want to be?",
  "How has the meaning of closeness evolved for you since we met?",
  "What do you think we know how to do better together now?",
  "Where have we become more honest without becoming less kind?",
  "What lesson from our relationship would you want to carry into any future season?",
  "How has our pace as a couple changed, and what does its current rhythm reveal?",
  "Which early assumption about us has changed the most for you?",
  "What has become simpler between us as trust has developed?",
  "How do you think we have influenced each other's everyday choices?",
  "What part of loving each other has required the most learning?",
  "When you look at us now, what growth are you most able to notice?",
  "What have you discovered about receiving care from another person?",
  "How has being known by me affected the way you know yourself?",
  "Which turning point helped our relationship feel more mutual?",
  "What do you appreciate about how our story has unfolded rather than being planned?",
  "In what area have we learned to give each other more room?",
  "What has our relationship taught you about balancing closeness and individuality?",
  "Which influence of mine has brought something useful into your life?",
  "How have you shaped the way I approach something important?",
  "What habit or perspective have we gently passed between us?",
  "Where do you see our personalities bringing out something good in each other?",
  "Which lesson have you drawn from a strength of mine that differs from yours?",
  "How has my way of caring affected what care means to you?",
  "Which part of your world feels broader because we share our lives?",
  "What is something you do differently now because of what we have experienced together?",
  "How do our distinct perspectives improve a decision we make as partners?",
  "What quality in yourself has this relationship given more space to develop?",
  "Where have I encouraged you without taking over your direction?",
  "What have our conversations helped you reconsider in a helpful way?",
  "How do you hope we continue influencing each other without losing ourselves?",
  "Which of my values has helped you understand your own values more clearly?",
  "What have you taught me that you hope stays with me?",
  "How has sharing ordinary life changed either of our priorities?",
  "What part of your individuality feels especially welcomed in our relationship?",
  "Where have our different approaches created a better third option?",
  "Watching each other handle change has taught us what about partnership?",
  "How has my presence affected the way you celebrate your own progress?",
  "Which shared interest has opened a new side of you?",
  "What is one way our relationship has made your life feel more spacious?",
  "How have we helped each other become more curious rather than more certain?",
  "What influence between us feels reciprocal instead of one-sided?",
  "In which moments are we borrowing each other's best habits?",
  "What has being my partner shown you about the impact you have on someone else?",
  "When growth takes us in different directions, what support would feel right?",
  "Which part of my outlook helps you see possibilities you might otherwise miss?",
  "What do our choices teach you about the life we are shaping together?",
  "What lets us inspire one another while still respecting separate goals?",
  "What helps a difficult conversation between us remain respectful?",
  "How do you recognize when we are ready to revisit a disagreement?",
  "Which repair from a past misunderstanding taught us something useful?",
  "What makes an apology feel meaningful to you without requiring instant resolution?",
  "How can I show that I understand your perspective even when mine differs?",
  "What helps you return to connection after tension without rushing yourself?",
  "Where have we improved at addressing an issue instead of attacking each other?",
  "What would make it easier to pause a conversation before it becomes unproductive?",
  "How do you prefer us to check whether a misunderstanding has truly cleared?",
  "Which lessons about timing guide us when something important needs discussion?",
  "Which small act helps rebuild warmth after we have been out of sync?",
  "What does taking responsibility look like to you in an everyday conflict?",
  "What would leave room for two valid experiences of the same moment?",
  "What signs tell you that I am listening to understand rather than to respond?",
  "Where could we be gentler with ourselves while working through friction?",
  "When does raising a concern feel possible without it becoming a verdict on us?",
  "How might we handle a recurring disagreement with more curiosity next time?",
  "Which words or actions help you feel respected during a hard conversation?",
  "What would a fair reset look like when either of us needs to start a discussion again?",
  "How do we know when a problem needs a solution and when it mainly needs listening?",
  "What have our mistakes taught us about making room for imperfection?",
  "Where can we replace mind-reading with a clearer question?",
  "What kind of follow-up helps you feel cared for after a challenging talk?",
  "When hurt needs naming, what language keeps us from defining each other's character?",
  "Which conflict habit would be useful for us to practice leaving behind?",
  "What allows accountability and compassion to exist together for us?",
  "How can we protect each other's dignity when emotions run high?",
  "What have we done well when a conversation did not end in agreement?",
  "Where might a little more patience change the way we repair?",
  "What approach could help us learn from tension without letting it define the relationship?",
  "What does healthy independence look like inside our partnership?",
  "What creates room for separate interests without making distance feel like rejection?",
  "Which personal goal would you like more freedom to explore?",
  "When do you feel connected while still having time that is fully your own?",
  "Where could we trust each other's judgment more?",
  "When one person needs solitude, what response from us would feel caring?",
  "What aspect of your life would you like to nurture independently right now?",
  "Which choices feel important for each of us to make individually?",
  "How can our relationship support friendships beyond the two of us?",
  "What makes space apart feel restorative rather than uncertain for you?",
  "Where do our routines allow enough room for spontaneity and personal choice?",
  "Where is the line between helpful support and taking over for you?",
  "What does being your own person within a close relationship mean to you?",
  "Which independent strength do you most appreciate in me?",
  "How can we celebrate separate accomplishments without comparing our paths?",
  "What balance between shared and individual plans feels sustainable these days?",
  "Where might we give one another more permission to change our minds?",
  "Where should autonomy show up more clearly in our everyday decisions?",
  "What helps you ask for space in a way that still feels caring?",
  "What aspect of our togetherness benefits most when we each recharge separately?",
  "How could we stay interested in the parts of each other's lives we do not share?",
  "What personal ritual would you like our partnership to protect?",
  "Where can we loosen expectations that no longer fit either of us?",
  "How do we encourage each other's ambitions without making them joint obligations?",
  "What would mutual freedom look like in the next season of our relationship?",
  "Which responsibility belongs to you that you want me to trust you with more fully?",
  "How can we avoid measuring closeness by how much time we spend together?",
  "What does interdependence offer us that either total independence or dependence cannot?",
  "Where would clearer ownership of a decision reduce tension between us?",
  "How might we stay close while allowing each other to keep evolving?",
  "What boundary helps you bring your best self to this relationship?",
  "When you are not ready to talk, what response from me would respect that?",
  "Which limit makes our shared life feel more respectful?",
  "What helps you communicate a no without feeling responsible for my reaction?",
  "Where would a clearer agreement protect both our energy?",
  "How can we check in about comfort without making either answer feel wrong?",
  "What boundary of mine has helped you understand me better?",
  "Which topic benefits from asking permission before we discuss it?",
  "How do you distinguish privacy from secrecy in a way that feels fair to us?",
  "What would make changing your mind feel easier to communicate?",
  "Where do we need a more explicit conversation about expectations?",
  "How can we respect a pause without assuming what it means?",
  "What does consent look like in the ordinary choices we make together?",
  "Which shared plan needs more room for either person to opt out?",
  "How would you want me to raise a boundary that affects both of us?",
  "What helps a limit feel like useful information rather than personal rejection?",
  "Where can we be more careful not to volunteer each other's stories?",
  "How should we handle moments when our comfort levels do not match?",
  "What agreement could make digital privacy feel clearer between us?",
  "Which forms of affection are best approached with a check-in rather than an assumption?",
  "How can we notice when a yes sounds uncertain and create room to reconsider?",
  "What does respectful persistence look like when one of us needs time to decide?",
  "Where might we replace an unspoken rule with a mutual understanding?",
  "If a familiar boundary changes, how should we respond to each other?",
  "When a conversation is not right for the moment, what makes skipping it feel safe?",
  "Which outside commitments need firmer protection in our shared calendar?",
  "What keeps a request from turning into a test of love between us?",
  "What boundary conversation have we handled in a way worth repeating?",
  "Where can we offer choices instead of assuming a single preferred path?",
  "In a relationship where both voices carry equal weight, what would you notice?",
  "What value do you see guiding our strongest decisions as a couple?",
  "How do our everyday choices reflect what matters most to us?",
  "Which principle would you like us to consult more often when plans compete?",
  "What does fairness mean in our relationship when equal is not always practical?",
  "Where do our values align even when our methods differ?",
  "When care and honesty compete, what would guide our decision?",
  "What value have you come to appreciate more because of our partnership?",
  "Which shared priority deserves more attention in how we use our time?",
  "What does generosity between partners mean beyond giving things?",
  "If our principles point in different directions, how should we approach the choice?",
  "Where does playfulness fit among the values that sustain us?",
  "What does reliability look like in the small details of our life?",
  "What keeps curiosity present when we think we already know each other?",
  "Which value should shape how we speak about each other to other people?",
  "Which lesson separates being right from being constructive for us?",
  "For time, work, or possessions, what would enough mean to us?",
  "What role should rest have in the life we build?",
  "In which moments does courage appear quietly in our relationship?",
  "What keeps kindness from becoming avoidance of necessary honesty between us?",
  "What does mutual respect ask of us when one person's preference cannot win?",
  "Which belief about partnership are you glad we have questioned together?",
  "How do we want to treat people outside our relationship when making choices for ourselves?",
  "What value could help us navigate uncertainty about the future?",
  "Where might simplicity serve us better than striving for more?",
  "What influence should gratitude have on the tone of our home or shared spaces?",
  "What does integrity between us look like when nobody else is involved?",
  "Which of our choices makes you feel most aligned with who you want to be?",
  "How can we revisit shared values as each of us changes?",
  "What principle should remain visible when life becomes especially busy?",
  "Where do compassion and accountability meet in the relationship we want?",
  "What part of our connection feels easiest to sustain, and why?",
  "How could we make care more practical during a demanding week?",
  "Which routine gives us the most connection for the energy it requires?",
  "What would help our relationship feel nourished rather than managed?",
  "How do you notice when we need to slow down and reconnect?",
  "Where can we reduce pressure while still tending to what matters?",
  "What kind of check-in would feel useful without becoming another obligation?",
  "How might we protect time together from always becoming planning time?",
  "Which simple pleasure would you like to make more room for with me?",
  "What helps our connection recover after a particularly full season?",
  "How can we share practical responsibilities in a way that feels visible and flexible?",
  "Where would a lighter expectation make closeness easier?",
  "What does consistency mean to you when neither of us can be perfect?",
  "When intentional time together is needed, what signal would work for us?",
  "What element of our routine deserves a thoughtful refresh?",
  "What helps affection stay genuine rather than automatic?",
  "What helps ordinary moments feel shared without forcing significance onto them?",
  "Where do you think our relationship gets renewed naturally?",
  "What form of support is sustainable for you to give during a stressful period?",
  "How might we divide invisible work more openly?",
  "Which expectation could we simplify to create more ease between us?",
  "What does a realistic version of quality time look like right now?",
  "How can we stay attentive to each other without being constantly available?",
  "Where would more predictability help, and where would more flexibility help?",
  "What shared practice could keep appreciation from going unspoken?",
  "When our energy levels differ, what response would support both of us?",
  "Which everyday task could become a small point of connection?",
  "What makes our partnership feel steady without making it feel fixed?",
  "How could we build rest into our plans before either of us is depleted?",
  "Where can we choose good enough so we have energy left for each other?",
  "What future choice feels worth exploring together without deciding it today?",
  "A year from now, what feeling would you welcome in our relationship?",
  "Which possibility for us brings you curiosity rather than pressure?",
  "As life changes, what deserves a continuing place in our relationship?",
  "Where might we benefit from staying flexible about the path ahead?",
  "How can we plan together while leaving space for new information?",
  "Which lesson would you welcome from our next season together?",
  "Which conversation could help us make a future decision more thoughtfully?",
  "When our goal timelines differ, how should we approach the mismatch?",
  "What kind of adventure would fit the people we are becoming?",
  "Where do you hope our individual plans can support one another?",
  "How might our definition of partnership change in the coming years?",
  "What future rhythm would balance stability with room to experiment?",
  "Which dream feels enjoyable to imagine even if it never becomes a plan?",
  "What do you want us to remember when circumstances disrupt our expectations?",
  "How can we tell whether a shared goal still belongs to both of us?",
  "Before a major choice, where could we be more intentional together?",
  "What does a hopeful future look like without requiring certainty?",
  "How might we support each other if our priorities shift at different times?",
  "What area of our life would you enjoy designing together from a blank page?",
  "What question should we keep asking as we choose what comes next?",
  "How do you imagine our connection adapting to a busier or quieter life?",
  "Where can we practice making smaller decisions before a bigger one arrives?",
  "What would help future planning feel collaborative instead of predetermined?",
  "How might we know when it is time to revise an old agreement?",
  "Which shared experience would you like to prioritize in the near future?",
  "Through future changes, which part of us do you hope stays recognizable?",
  "Where could surprise remain welcome in the life we are building?",
  "Where would a temporary experiment serve us better than a permanent decision?",
  "What future version of our partnership feels both grounded and open?",
  "When I make space for you, what about my approach do you appreciate?",
  "How has a small kindness between us had a lasting effect?",
  "Which part of our everyday connection would you miss if it disappeared?",
  "What quality do I bring to our partnership that feels uniquely helpful?",
  "Where have you felt quietly understood by me?",
  "How do I add ease to your life in a way I may not notice?",
  "What recent moment made you glad we are on the same side?",
  "Which effort of mine would you like to acknowledge today?",
  "What do you value about the way we recover our sense of humor?",
  "How has my belief in you mattered during an ordinary challenge?",
  "In which interactions does tenderness appear between us?",
  "What about our companionship feels especially dependable?",
  "How do our differences add something you are grateful for?",
  "Which memory captures a kind of joy you want us to keep noticing?",
  "Who do you get to be around me that you especially appreciate?",
  "How have I respected a choice of yours in a way that stayed with you?",
  "Where does our partnership make daily life more interesting?",
  "What strength have you seen in us during a period of adjustment?",
  "How do you feel cared for by something we do without much thought?",
  "Which part of our shared history brings you a sense of warmth?",
  "What do you admire about the way we make room for two perspectives?",
  "How has one of my quirks become meaningful to you over time?",
  "Where have we created a sense of belonging for each other?",
  "What is worth celebrating about us at this point in our story?",
  "How do I help you feel accompanied without trying to fix everything?",
  "Which ordinary memory says something important about our bond?",
  "At our particular pace of learning each other, what has served us well?",
  "How has our connection made a familiar part of life feel richer?",
  "In which unannounced moments does mutual care show up between us?",
  "What would you like me to understand about the gratitude you feel for us?",
  "What from this conversation would you like to carry into everyday life?",
  "How has hearing my perspective today changed or clarified your own?",
  "Which idea we discussed feels most useful for the way we relate?",
  "What did this conversation help you notice about our current season?",
  "Where did you feel most understood while we were talking?",
  "After something meaningful today, what kind of follow-up would suit you?",
  "What new question are you leaving this conversation with?",
  "Which answer of mine would you like more time to think about?",
  "What felt easier to name than you expected?",
  "How can we bring the same quality of listening into a future conversation?",
  "Where did our perspectives complement each other today?",
  "What did you learn about the kind of question that helps you open up?",
  "For conversations like this, what tone helps you participate most freely?",
  "Which topic from today deserves patience rather than immediate action?",
  "What are you taking away about how we handle differences?",
  "How did this exchange remind you of a strength in our partnership?",
  "After today, which area could use more curiosity from both of us?",
  "What part of the conversation would be helpful to revisit another time?",
  "What would make reflection feel natural rather than reserved for special moments?",
  "Which insight feels like yours to consider privately for a while?",
  "What did you hear from me that you want to remember accurately?",
  "When no decision is needed, what closing helps a deep conversation feel complete?",
  "Where did you notice yourself becoming more open-minded today?",
  "What might we do differently because of something we understood here?",
  "How can we honor what was shared without expecting every topic to continue?",
  "Which moment in this conversation felt most connecting to you?",
  "For what you expressed or considered today, how might you appreciate yourself?",
  "How has this reflection helped you see our choices more clearly?",
  "Where should we allow today's conversation to be complete as it is?",
  "What gentle next step, if any, feels right after what we have discussed?",
] as const satisfies readonly string[]
