export const STRANGERS_GROUP_CONNECT = [
  'What value helps you decide how to treat people you have just met?',
  'Which quality in yourself becomes most useful when a group is new?',
  'How can people make room for different comfort levels in one conversation?',
  'What kind of welcome helps you relax without putting you on the spot?',
  'When does a group begin to feel like a place where you can contribute?',
  'What does being included look like in an ordinary moment?',
  'Which small gesture tells you someone is listening with care?',
  'While you are still forming a thought, what response from others works best?',
  'What helps a conversation feel curious rather than intrusive?',
  'Where do you notice cooperation making everyday life better?',
  'Which strength do you enjoy bringing to a shared task, and why does it fit you?',
  'How would you describe support that respects your independence?',
  'Which personal principle do you return to when a choice is complicated?',
  'What makes it easier for you to ask a new group for clarification?',
  'How can someone disagree with you while still showing respect?',
  'What gives you confidence that your perspective is welcome?',
  'Which form of encouragement feels genuine to you?',
  'What tells you it is time to listen instead of preparing a response?',
  'What makes shared silence comfortable rather than awkward?',
  'Which everyday act of courage deserves more recognition?',
  'What helps people contribute without needing to compete for attention?',
  'How might a group show that changing your mind is allowed?',
  'Before offering advice, how might someone check whether it is wanted?',
  'Which kind of question makes you feel invited into a conversation?',
  'Faced with a viewpoint you do not immediately understand, how do you make space for it?',
  'What can turn a collection of strangers into a cooperative group?',
  'Which part of a good conversation stays with you afterward?',
  'How would you want a group to handle an accidental misunderstanding?',
  'In a new setting, what simple detail helps you feel oriented?',
  'Which boundary makes social connection easier for you?',
  'How can people show warmth without assuming familiarity?',
  'How can a group distribute attention without pretending every need is identical?',
  'Which strength do you often notice first in other people?',
  'In what way do you like to be invited to share an idea?',
  'What signals that someone is genuinely open to learning from you?',
  'Where have you seen a small contribution improve a group effort?',
  'What kind of patience helps people understand one another?',
  'How can a group acknowledge differences without making anyone explain themselves?',
  'Which shared responsibility matters most in a meaningful conversation?',
  'What helps you stay curious when someone reaches a different conclusion?',
  'How would you describe a community where people can be imperfect?',
  'What is a low-pressure way to help someone join an ongoing discussion?',
  'Which everyday choice reflects the kind of person you want to be?',
  'When something feels overlooked, what guides your decision to speak up?',
  'What makes an apology feel respectful and complete to you?',
  'Which type of recognition helps you feel that your effort mattered?',
  'How can people share airtime when some think aloud and others need time?',
  'How might a group make uncertainty feel acceptable?',
  'Which experience has taught you something useful about teamwork?',
  'What allows you to protect your energy while staying connected?',
  'What gives a gathering a sense of purpose beyond simply being together?',
  'Which habit helps you approach unfamiliar people with openness?',
  'How can someone show interest without expecting personal details?',
  'What do you appreciate about people who help groups run smoothly?',
  'When have you seen kindness change the tone of a room?',
  'Which sign shows that a group values honesty over perfect answers?',
  'If you pass on a question, what response from others would feel respectful?',
  'Which qualities make a person easy to collaborate with?',
  'What could help a quiet contribution receive proper attention?',
  'How does humor help connection, and where should care come in?',
  'Without forcing similarity, how might people discover what they have in common?',
  'Which hope for your community feels especially worth sharing?',
  'How do you know when encouragement is helping rather than pressuring?',
  'What can people do to make room for names they are still learning?',
  'Which kind of difference has expanded how you see the world?',
  'How would you explain the difference between hearing and listening?',
  'In a group conversation, what does every person deserve?',
  'Where do you find examples of quiet leadership?',
  'After someone is spoken over, what could help the group recover?',
  'What makes you feel trusted with a shared responsibility?',
  'Which value would you want at the center of a new community?',
  'When offering help, how can you leave genuine room for a no?',
  'During shared work, which useful role comes naturally to you?',
  'Which social expectation would you replace with a kinder one?',
  'How can people celebrate progress without comparing journeys?',
  'What helps you believe that a disagreement can still be constructive?',
  'Which part of your perspective has been shaped by a place you know well?',
  'How would an ideal listener respond when they do not understand?',
  'What is one way to show appreciation beyond saying thank you?',
  'When does compromise feel fair, and when might another approach work better?',
  'What can a group learn by noticing who has not spoken yet?',
  'Which personal strength took you time to recognize?',
  'How do you prefer to receive feedback from someone new?',
  'What makes it possible to be both honest and considerate?',
  'Where could more cooperation make daily life easier for everyone?',
  'What is a meaningful way to include someone joining late?',
  'Which kind of shared goal brings out your best contribution?',
  'How can a conversation leave people with more dignity than it found them?',
  'What helps you remain yourself while adapting to a group?',
  'Which ordinary responsibility do you think holds communities together?',
  'How do you tell the difference between support and taking over?',
  'After talking with you, what do you hope people feel?',
  'When have you benefited from someone asking instead of assuming?',
  'What would make it easier for people to admit they need more context?',
  'Which aspect of belonging can be created in a single evening?',
  'How can a group make room for both seriousness and play?',
  'If someone chooses not to elaborate, what response shows consideration?',
  'Which strength becomes visible only when people work together?',
  'In a shared challenge, what helps you identify the responsibility that is yours?',
  'What makes a difference of opinion interesting to explore?',
  'Where do you see people building trust through consistency?',
  'How might you invite correction while remaining receptive?',
  'Which action helps you feel that your time is being respected?',
  'How can people notice exclusion without singling someone out?',
  'What do you value in someone who sees a situation differently from you?',
  'When is asking for help a form of courage?',
  'What would shared responsibility look like in this conversation?',
  'When an idea is not yours, what can you do to help it grow?',
  'Which boundary should people honor without asking for an explanation?',
  'Which community space brings out a positive side of you?',
  'How can a group make decisions without rushing toward the loudest idea?',
  'What helps you listen for meaning beyond someone’s exact words?',
  'Where might curiosity be more useful than certainty?',
  'Being heard comes with what responsibility?',
  'Which kind of support helps you regain momentum?',
  'After a useful correction, how can you show that you valued it?',
  'What could make introductions feel more human and less performative?',
  'When has another person’s perspective helped you notice a blind spot?',
  'Among people who bring others together, which strength do you admire?',
  'Which agreement could help a new group have a better conversation?',
  'How can someone express a need without turning it into a demand?',
  'What does generosity look like when no money is involved?',
  'Where have you experienced belonging through a shared activity?',
  'If a conversation becomes uncomfortable, how might you gently redirect it?',
  'Which part of collaboration gives you energy?',
  'While taking a moment to process, what helps you remain open?',
  'What can make accepting help feel easier?',
  'When do you feel most able to offer your honest opinion?',
  'Which act of courage can happen within an ordinary conversation?',
  'Which small courtesy has a surprisingly large effect on you?',
  'How might people share leadership during a group activity?',
  'What helps a community balance individual freedom with care for others?',
  'Where do you draw inspiration for treating people well?',
  'After a minor mistake, what might begin repairing trust?',
  'Which question can help a group move from debate toward understanding?',
  'If you contribute an idea, how would you like others to acknowledge it?',
  'What makes room for hope in a difficult shared situation?',
  'When can stepping back be a valuable contribution?',
  'Which signal shows that people are taking one another seriously?',
  'Which everyday setting could feel more welcoming with one small change?',
  'How can a person be dependable without promising too much?',
  'What do you learn about yourself when collaborating with new people?',
  'Where is there room for more kindness in how people exchange feedback?',
  'For someone who communicates differently, how could a group make space?',
  'Which kind of group challenge makes cooperation enjoyable?',
  'With a topic you may not wish to discuss, what approach would you prefer?',
  'What helps people take responsibility without getting stuck in shame?',
  'When have you seen listening solve more than advice could?',
  'Which hopeful change have you noticed in how people connect?',
  'Which personal resource can you share freely, such as time, knowledge, or attention?',
  'How can a group keep one mistake from defining a person?',
  'What does it mean to give someone the benefit of curiosity?',
  'Where do you find common ground without requiring complete agreement?',
  'What is an inviting way to ask for another perspective?',
  'Which form of care is easy for people to overlook?',
  'How do you notice when your assumptions need updating?',
  'What helps you participate when you enter a conversation already in progress?',
  'When is it valuable to name what you do not know?',
  'What is a way to disagree that could strengthen connection?',
  'Which contribution to a community often goes unrecognized?',
  'How can people respect privacy while getting to know one another?',
  'What gives you hope about people working across differences?',
  'Where do shared rituals help create belonging?',
  'Even on a low-energy day, what can you offer a group?',
  'Which choice helps you act with integrity when nobody is checking?',
  'If another person needs a different pace, how do you adjust?',
  'What makes you willing to reconsider a first impression?',
  'When does a group feel supportive without feeling controlling?',
  'How could people fairly divide an unglamorous shared task?',
  'Which skill would you like to contribute more often in your community?',
  'How can someone communicate a limit while preserving warmth?',
  'Where have you noticed people cooperating without being asked?',
  'Which sign of respect travels well across many settings?',
  'Which hope would you enjoy working toward with other people?',
  'When a topic feels polarized, what creates room for nuance?',
  'What can turn useful feedback into a genuine act of support?',
  'When have you appreciated someone admitting they were mistaken?',
  'Before disagreement happens, how might a group welcome it constructively?',
  'Which group norm helps prevent anyone from becoming the default helper?',
  'How can shared laughter bring people together without making someone the joke?',
  'What does it look like to respect an answer you would not choose yourself?',
  'Where can everyday people have the most impact on their community?',
  'How might someone help without needing credit?',
  'Which kind of conversation makes differences feel illuminating?',
  'What respects another person’s ownership of their story?',
  'What helps a group move forward when no option is perfect?',
  'When have you felt welcomed by someone remembering a small detail?',
  'Which quality makes collective work feel lighter?',
  'Which personal practice helps you respond thoughtfully rather than quickly?',
  'How can people make participation possible without making it mandatory?',
  'What would a community designed around mutual care prioritize?',
  'Where do you see bravery in setting a reasonable limit?',
  'What is a constructive way to respond when intentions and impact differ?',
  'Which kind of invitation gives you genuine freedom to decline?',
  'How do you contribute when someone else is better suited to lead?',
  'What makes curiosity feel respectful across different life experiences?',
  'When is it helpful to ask what support would look like?',
  'What is one lesson cooperation has taught you about control?',
  'Which action shows that a group values people beyond their usefulness?',
  'How can people acknowledge unequal workloads without assigning blame?',
  'What helps you recognize the wisdom in an unfamiliar approach?',
  'Where could a simple check-in prevent a misunderstanding?',
  'What is a shared experience that can connect people without requiring disclosure?',
  'How do you define accountability in a way that leaves room for growth?',
  'What makes an offer of support feel easy to accept or decline?',
  'When have you learned something by letting another person set the pace?',
  'What is one way a group can value both expertise and fresh eyes?',
  'Which part of a healthy community depends on ordinary people showing up?',
  'How can someone challenge an idea without diminishing its speaker?',
  'What would help more people feel entitled to ask a sincere question?',
  'Where do you see empathy working alongside practical action?',
  'What is a sign that cooperation has become genuine partnership?',
  'Which strength helps you bridge a difference with someone?',
  'How do you want others to respond when you say you need time?',
  'What makes a shared space feel cared for?',
  'When can naming a positive intention improve a hard conversation?',
  'How might a group protect individual needs while pursuing a shared goal?',
  'Which perspective do you find easiest to miss when making a quick decision?',
  'How can people stay connected while leaving some questions unanswered?',
  'What helps a person speak with courage without dominating?',
  'Where have you seen a group turn limited resources into something useful?',
  'To check your interpretation of someone’s words, what could you ask?',
  'Which everyday interaction restores some of your faith in people?',
  'What balance do you seek between offering your view and making room for others?',
  'What would make a shared project feel worthwhile even before it succeeds?',
  'When is consistency more supportive than a grand gesture?',
  'When someone names a boundary, what response communicates respect?',
  'Which conditions help your best ideas emerge in a group?',
  'How can people honor contributions that are less visible?',
  'What does respectful persistence look like when solving a shared problem?',
  'Where might asking permission improve an ordinary interaction?',
  'Which value would you protect even when it slows a decision?',
  'Which role does trust play in asking honest questions?',
  'At what point can curiosity become an expectation to explain, and how do you avoid that?',
  'What helps a group recognize that one person cannot represent everyone?',
  'When has a stranger’s consideration made your day easier?',
  'How might people share power in a conversation in practical terms?',
  'Which kind of community effort would you gladly join for an hour?',
  'How can people make corrections feel normal rather than embarrassing?',
  'What do you hope future generations find easier about connecting?',
  'Where does listening require courage from the listener?',
  'When someone asks for a pause, which response would be helpful?',
  'Which quality helps a group continue after enthusiasm fades?',
  'What guides you in offering either a solution or your attention?',
  'What makes space for multiple truths about the same experience?',
  'When can asking a follow-up question be an act of care?',
  'How can a shared success be recognized so it feels truly shared?',
  'Which boundary helps you be more generous with your attention?',
  'How can groups avoid mistaking confidence for certainty?',
  'What would it look like to treat belonging as a shared practice?',
  'Where do you notice people making cooperation harder than it needs to be?',
  'Where have you noticed strength being expressed through gentleness?',
  'Which form of participation should count even when it is quiet?',
  'After a decision seems settled, how can late input still receive a fair hearing?',
  'What helps someone feel valued when their suggestion is not chosen?',
  'When is it important to leave room for a person to change their answer?',
  'How would you like neighbors to relate to one another?',
  'Which behavior tells you a person can hold confidence with humility?',
  'How can a group use differences as resources rather than obstacles?',
  'What makes an expression of gratitude specific enough to matter?',
  'Where could people replace an assumption with a simple question?',
  'For an idea you did not originate, what would meaningful support look like?',
  'Which ordinary decision can strengthen trust over time?',
  'With limited time, what keeps a conversation humane?',
  'When have you seen someone create belonging without being in charge?',
  'When a new voice enters the room, what responsibility does everyone share?',
  'Which kind of honesty builds connection instead of demanding it?',
  'How can someone acknowledge harm without centering their own discomfort?',
  'What would help a group disagree without dividing into sides?',
  'Where have you found connection through learning something together?',
  'Which understated behavior shows reliability?',
  'Without assuming shared reference points, how can you offer useful context?',
  'What makes it possible for people to contribute in different ways?',
  'When does receiving care require its own kind of courage?',
  'Which community problem might benefit from more listening before action?',
  'Which sign tells you a group is ready to have a deeper conversation?',
  'How can people disagree about methods while staying aligned on a value?',
  'What would respectful curiosity sound like when a term is unfamiliar?',
  'Where can you practice being a better community member this week?',
  'How might a group notice who is carrying invisible coordination work?',
  'Which quality helps people repair rather than retreat after tension?',
  'What makes an offer generous without creating a sense of debt?',
  'What helps a group turn good intentions into dependable action?',
  'When have you seen flexibility protect a shared goal?',
  'What is a hopeful possibility that becomes more realistic through cooperation?',
  'Which kind of support honors both connection and autonomy?',
  'How can a conversation welcome emotion without demanding vulnerability?',
  'What makes a person’s presence valuable beyond what they produce?',
  'Where do you think people learn the habits of good listening?',
  'To learn whether its process feels fair, what could a group ask?',
  'Which shared value could connect people with very different priorities?',
  'Hearing an experience you cannot relate to, what does a thoughtful response involve?',
  'What helps people move from speaking for others to listening to them?',
  'When can a clear no protect a future yes?',
  'Which form of everyday leadership would you like to practice?',
  'How can a group respond when someone notices a missing perspective?',
  'What would make it safer to admit that a question landed poorly?',
  'Where do you see potential for strangers to become good neighbors?',
  'Which practice keeps shared responsibility from becoming resentment?',
  'How do you want people to remember the way you made room for them?',
] as const satisfies readonly string[]
