export const STRANGERS_COLLEAGUES_REFLECT: readonly string[] = [
  "Which part of our collaboration has become easier over time, and what helped?",
  "What has this team taught you about sharing unfinished ideas?",
  "Where have our different working styles complemented each other well?",
  "How has your understanding of good teamwork changed through working here?",
  "What recent collaboration would you use as an example of people combining strengths?",
  "When has a colleague's question improved the direction of the work?",
  "What have you learned about asking for help before a problem grows?",
  "Which team habit has made cooperation smoother than it used to be?",
  "How do you recognize the moment when independent work needs wider input?",
  "What does an effective handoff between colleagues look like to you now?",
  "Where has patience made a meaningful difference in a shared project?",
  "What lesson about coordination would you carry into any future team?",
  "How have you learned to make your work easier for the next person to use?",
  "Which kind of contribution tends to unlock progress when a team feels stuck?",
  "What has helped this group turn individual expertise into a shared result?",
  "When did working with someone else reveal an option you would not have found alone?",
  "What do our strongest collaborations have in common?",
  "How has the team become better at noticing dependencies between tasks?",
  "Which small act of cooperation deserves more attention than it usually gets?",
  "What have shared challenges shown you about how this group works together?",
  "Where could a little more context make cross-team work noticeably easier?",
  "How do you decide when to lead, follow, or make room in a group effort?",
  "What did a successful partnership at work teach you about trust?",
  "Which collaboration practice would be worth protecting during a busy period?",
  "How has working across different specialties changed the questions you ask?",
  "What helps a group move from polite agreement to useful collaboration?",
  "Where have you seen generosity with knowledge improve the final outcome?",

  "Which change in how we work has been more useful than you first expected?",
  "What old work habit have you reconsidered since joining this team?",
  "How has the way you prepare for meetings evolved?",
  "Where has a simpler process produced a better result?",
  "What have we stopped doing that you do not miss?",
  "Which experiment in our workflow taught us the most, whether or not it lasted?",
  "How do you tell when a routine still serves the work rather than merely feeling familiar?",
  "What shift in communication has saved the team unnecessary effort?",
  "When has changing the sequence of work improved the outcome?",
  "What practice should we revisit because the context around it has changed?",
  "How has remote or hybrid work influenced what you make explicit?",
  "Which part of our workflow benefits most from occasional reinvention?",
  "What did an abandoned approach teach us that still matters?",
  "Where have better tools changed the quality of our thinking, not just our speed?",
  "How can a team distinguish useful consistency from resistance to change?",
  "What adaptation helped you contribute more effectively?",
  "Which recent adjustment deserves time to settle before we judge it?",
  "What have periods of change revealed about the information people need?",
  "How would you keep valuable context from being lost when processes change?",
  "Where might a temporary workaround have quietly become the default?",
  "What work practice feels ready for a thoughtful refresh?",
  "How have you learned to respond when a new process creates an unexpected burden?",
  "Which change worked because the people doing the work shaped it?",
  "What would help us test new ways of working with less disruption?",
  "When has slowing down the rollout of a change led to better adoption?",
  "How should we decide whether a working agreement needs revision?",
  "What has made it easier to let go of a familiar but unhelpful method?",

  "What have you picked up from a colleague that now shapes your everyday work?",
  "How has someone else's perspective changed the way you frame a problem?",
  "Which of your habits has the team influenced for the better?",
  "What is one way your approach has rubbed off on the people around you?",
  "When have you borrowed a colleague's technique and made it your own?",
  "How has this group expanded your idea of what professionalism can look like?",
  "What assumption did another person's experience help you question?",
  "Which conversation quietly changed how you work with others?",
  "How do colleagues influence the standards you set for shared work?",
  "What useful perspective have you gained from someone in a very different role?",
  "Where has another person's calm affected how you handled pressure?",
  "What have you learned by watching someone navigate uncertainty well?",
  "How has receiving a thoughtful challenge sharpened your judgment?",
  "Which quality in a colleague has encouraged you to practice it yourself?",
  "What part of your working style has become more flexible through this team?",
  "When has a colleague's curiosity made you more curious too?",
  "How have you influenced a team norm without formally setting it?",
  "What idea from this workplace will stay with you wherever you work?",
  "Which everyday interaction has had a larger effect on you than the other person may realize?",
  "How has collaborating with different thinkers affected your confidence in your own view?",
  "What have you learned about influence that does not depend on authority?",
  "Where do you see the team reflecting one another's best habits?",
  "What contribution from a quieter voice changed your understanding?",
  "How do you remain open to influence without losing your own judgment?",
  "Which lesson from a colleague took time to appreciate?",
  "What has this team taught you about the impact of tone?",
  "When have you seen one person's openness make honesty easier for everyone?",

  "Where has greater clarity about ownership helped work move faster?",
  "What aspect of your role became clearer only after doing it for a while?",
  "How do you know when responsibility is shared rather than simply unassigned?",
  "Which recurring task needs a clearer home?",
  "What information helps you understand where your work begins and ends?",
  "When has naming a decision owner prevented confusion?",
  "How could we make invisible coordination work more visible?",
  "What do you wish partner teams understood about this team's responsibilities?",
  "Where do role boundaries help collaboration rather than hinder it?",
  "How should a team respond when two people reasonably think they own the same decision?",
  "What has helped you explain your role without reducing it to a job title?",
  "Which expectation would benefit from being turned into an explicit agreement?",
  "How can we spot conflicting responsibilities before they create strain?",
  "What does useful accountability look like when several people contribute?",
  "Where could a clearer definition of done reduce rework?",
  "How do you navigate work that matters but belongs to no obvious role?",
  "What question best exposes a hidden assumption about ownership?",
  "Which boundary between roles has become more porous in a helpful way?",
  "How has role clarity affected your ability to exercise judgment?",
  "What should happen when someone's responsibilities grow beyond the time available?",
  "Where would a simple map of decisions and dependencies help most?",
  "How can colleagues clarify expectations without becoming overly rigid?",
  "What did a confusing assignment teach you about setting up work well?",
  "Which part of collaboration should never depend on guessing who is responsible?",
  "How might we make temporary ownership genuinely temporary?",
  "What helps you raise a mismatch between authority and responsibility?",
  "Which role question is worth resolving before our next major piece of work?",

  "What has helped restore trust after a work misunderstanding?",
  "How can colleagues acknowledge impact even when their intention was different?",
  "When has a sincere correction mattered more than a polished apology?",
  "What makes a difficult follow-up conversation feel constructive?",
  "How do you prefer a colleague to revisit something that landed badly?",
  "Which small repair can keep ordinary friction from becoming lasting distance?",
  "What have you learned about addressing tension while it is still manageable?",
  "How can a team make room for someone to change their mind without embarrassment?",
  "Where does curiosity help more than certainty during a disagreement?",
  "What signals that a conflict has been resolved rather than merely paused?",
  "How should we reconnect after a meeting where people talked past one another?",
  "What makes it possible to disagree with an idea while respecting its author?",
  "When has admitting a missed detail strengthened a working relationship?",
  "How can we prevent a single awkward interaction from defining future collaboration?",
  "What does taking responsibility sound like without becoming defensive?",
  "Which repair attempt taught you something about what the other person needed?",
  "How might a team revisit a decision that left someone unheard?",
  "What helps you separate a process failure from a person's character?",
  "Where can humor ease tension, and where might it get in the way of repair?",
  "How do you know when to address friction privately or with the wider group?",
  "What team norm would make recovering from mistakes less awkward?",
  "When a commitment slips, what response best preserves both candor and trust?",
  "How can colleagues repair the effect of an interruption or dismissal in the moment?",
  "What does a fair reset look like after expectations were unclear?",
  "Which kind of acknowledgment helps you move forward after a disagreement?",
  "How should a group learn from conflict without repeatedly reopening it?",
  "What have past repairs taught you about timing?",

  "Which decision improved because the reasoning was shared openly?",
  "How do you tell when a choice needs broad input and when it needs speed?",
  "What has the team learned about making decisions with incomplete information?",
  "Where could we separate consultation from approval more clearly?",
  "How should dissent be captured once a decision has been made?",
  "What helps you support a direction you questioned during discussion?",
  "When has revisiting the purpose changed the decision in front of us?",
  "How can we keep urgency from silencing useful perspectives?",
  "Which decision would have benefited from hearing affected colleagues earlier?",
  "What makes a decision process feel fair even when the outcome is not your preference?",
  "How do we avoid mistaking silence for agreement?",
  "What question helps reveal the tradeoff hidden inside a choice?",
  "Where has a small reversible decision received more debate than it needed?",
  "How can teams record enough decision context without creating extra bureaucracy?",
  "What have you learned about recognizing when a decision is truly final?",
  "Which voices are easiest to miss when a choice is made quickly?",
  "How should new evidence change a previously sound decision?",
  "What helps a group distinguish disagreement from lack of commitment?",
  "When is a trial period more useful than seeking perfect consensus?",
  "How can a decision owner show that input genuinely shaped the outcome?",
  "What does responsible escalation look like when a team cannot agree?",
  "Where could clearer decision criteria reduce circular discussion?",
  "How do you contribute when you have relevant doubts but no complete alternative?",
  "What decision-making habit would make meetings more purposeful?",
  "Which choice taught us the value of naming who will be affected?",
  "How can we leave room for challenge after senior voices have spoken?",
  "What would make it safer to say that a decision no longer fits reality?",

  "When have you felt that your contribution was genuinely invited?",
  "What makes it easier for people with different communication styles to participate?",
  "How can a meeting include those who think best after the conversation ends?",
  "Which team habit helps prevent the fastest speaker from setting the whole direction?",
  "What have you learned from a viewpoint that initially felt unfamiliar?",
  "Where could written input create a more level field for participation?",
  "How do we notice whose expertise is being overlooked?",
  "What helps colleagues pronounce names, terms, or identities correctly without making correction burdensome?",
  "When has changing the format of a discussion brought in better ideas?",
  "How can we challenge an assumption without asking one person to represent a whole group?",
  "What signals that questions and uncertainty are welcome here?",
  "Which informal norm might be easier for insiders to navigate than newcomers?",
  "How could the team make important context accessible to people who missed the room?",
  "What does respectful curiosity look like when experiences differ?",
  "Where might our usual examples or shorthand leave someone out?",
  "How can credit be shared accurately when contributions arrive in different forms?",
  "What would help a new colleague understand how participation really works here?",
  "When have multiple ways of contributing improved the quality of an outcome?",
  "How should we respond when someone points out an exclusion we did not intend?",
  "What practice helps remote participants carry equal weight in a mixed-room discussion?",
  "How do we make space for disagreement without demanding personal disclosure?",
  "Which part of our work would benefit from a wider range of perspectives?",
  "What helps you check whether accessibility was considered early enough?",
  "How can colleagues invite input without putting anyone on the spot?",
  "Where does transparency help counter assumptions about who gets opportunities?",
  "What have we learned about inclusion from a moment that did not go as planned?",
  "How can the group value specialist language while keeping discussions understandable?",

  "What has a demanding period taught us about realistic capacity?",
  "How do you recognize when prioritization has become simply adding more priorities?",
  "Which part of the workload is easiest for the team to underestimate?",
  "What makes it possible to raise a capacity concern early?",
  "How can colleagues distinguish a short sprint from an unsustainable pattern?",
  "Where could stopping work create more value than starting something new?",
  "What have deadlines taught us about the difference between ambitious and achievable?",
  "How should a team respond when every request is described as urgent?",
  "Which hidden task deserves space in workload planning?",
  "What helps you communicate limits without sounding uncommitted?",
  "How could we make tradeoffs clearer when new work arrives?",
  "When has protecting focus improved both quality and pace?",
  "What does a genuinely restorative break enable in the work?",
  "Where are we relying on individual resilience to solve a design problem?",
  "How can the team notice overload before missed commitments reveal it?",
  "Which recurring demand could be reduced at its source?",
  "What would a more sustainable rhythm look like during ordinary weeks?",
  "How do handoffs and delays affect workload in places the team rarely sees?",
  "What have you learned about estimating the effort around the task, not just the task itself?",
  "When should quality expectations be renegotiated rather than asking people to stretch further?",
  "How might meeting load be affecting the time available for the work meetings discuss?",
  "What enables colleagues to use leave without creating avoidable pressure for others?",
  "Where could better sequencing prevent several deadlines from converging?",
  "How do we protect recovery time after an unusually intense period?",
  "What workload signal should leaders treat as useful information rather than complaint?",
  "Which commitment should be questioned if capacity stays unchanged?",
  "What agreement could help us match future plans to actual capacity?",

  "Which piece of feedback changed your approach in a useful way?",
  "How has your understanding of helpful feedback matured?",
  "What makes recognition feel specific enough to learn from?",
  "When has someone noticed an effort that usually stays invisible?",
  "How do you prefer colleagues to test an observation before treating it as fact?",
  "What kind of appreciation strengthens collaboration without becoming performative?",
  "Where could timely feedback prevent avoidable rework?",
  "How can a team make positive feedback as informative as corrective feedback?",
  "What have you learned about choosing the right setting for a candid conversation?",
  "Which contribution deserves recognition for improving the process, even if it was not the final deliverable?",
  "How do you separate useful feedback from a preference about style?",
  "What helps feedback become a dialogue rather than a verdict?",
  "When did a colleague's encouragement help you try a different approach?",
  "How can we recognize support work that happens behind the scenes?",
  "What makes it easier to ask for feedback on something still in progress?",
  "Where might praise be overlooking the collective effort behind a result?",
  "How do you know whether feedback is clear enough to act on?",
  "What lesson have you gained from feedback you initially resisted?",
  "Which form of recognition helps people understand what to repeat?",
  "How could we make gratitude more evenly distributed across roles?",
  "What question turns a vague reaction into useful feedback?",
  "When has feedback arrived too late to help, and what would improve the timing?",
  "How can colleagues acknowledge growth without comparing people?",
  "What does receiving feedback with curiosity look like in practice?",
  "Where should intent, impact, and context each enter a feedback conversation?",
  "How might we celebrate a thoughtful decision whose outcome was uncertain?",
  "What has recognition taught you about what this team values?",

  "What new capability have you developed through the work itself?",
  "How do you choose a stretch that builds skill without creating needless strain?",
  "Which mistake became useful once there was space to examine it?",
  "What have you learned about giving people room to solve problems their own way?",
  "Where has greater autonomy improved your sense of responsibility?",
  "How can a team offer guidance without removing ownership?",
  "What question has helped you think more independently at work?",
  "When has observing another role broadened your understanding of the organization?",
  "How do you decide which skill is worth developing next?",
  "What learning would be easier if practice were built into regular work?",
  "Which challenge revealed a strength you had not been using?",
  "How has teaching someone else deepened your own understanding?",
  "What makes an assignment feel like meaningful growth rather than unsupported stretch?",
  "Where could more choice in method lead to better work?",
  "How do you preserve autonomy while keeping collaborators informed?",
  "What have you discovered by approaching a familiar task differently?",
  "Which team resource has supported learning especially well?",
  "How should colleagues respond when an experiment produces a useful failure?",
  "What does good sponsorship of someone's idea look like without speaking for them?",
  "Where might permission be unnecessary if the outcome and boundaries are clear?",
  "How can people ask for direction without giving away all initiative?",
  "What experience helped you become more comfortable saying, 'I don't know yet'?",
  "Which learning opportunity could be shared more fairly across the team?",
  "How do you make room for reflection before moving to the next task?",
  "What has helped you turn new knowledge into a dependable habit?",
  "When does expertise need updating rather than defending?",
  "How can the team support growth that does not require a title change?",

  "Which boundary has made your work more reliable rather than less collaborative?",
  "How do you signal when a request needs a clearer timeline or scope?",
  "What makes it easier to respect different patterns of availability?",
  "Where could a shared response-time agreement reduce pressure?",
  "How can colleagues protect focused time while remaining reachable for genuine needs?",
  "What have you learned about saying no while still helping the work move forward?",
  "Which communication channel needs a clearer purpose?",
  "How should we handle messages that arrive outside someone's stated working time?",
  "What does a respectful boundary around meetings look like?",
  "Where can a default of asking, rather than assuming, improve collaboration?",
  "How do you renegotiate a commitment when circumstances change?",
  "What boundary prevents helpfulness from turning into hidden overload?",
  "When is it useful to make availability visible to the team?",
  "How can a colleague offer support without pressing for personal details?",
  "What helps keep a professional relationship warm without requiring closeness?",
  "Which expectation about responsiveness deserves to be made explicit?",
  "How do we respect a person's choice not to discuss something at work?",
  "Where might a check-in feel supportive to one colleague and intrusive to another?",
  "What phrase or practice helps you pause a conversation that needs a better setting?",
  "How can teams distinguish an emergency from a habit of last-minute planning?",
  "What makes delegation respectful of both expertise and capacity?",
  "Which boundaries become most important when roles overlap?",
  "How should colleagues handle confidential context they do not need to know?",
  "What does consent look like before sharing someone else's work or words?",
  "Where can clearer escalation paths protect individual boundaries?",
  "How might we normalize updating a boundary without demanding an explanation?",
  "What agreement would help flexible schedules work fairly across the team?",
  "How do you leave room for exceptions without turning them into expectations?",
  "Which professional boundary supports your best contribution?",
  "What could we agree now that would make future boundary conversations easier?",
]
