export const STRANGERS_FRIENDS_WARM_UP = [
  "What did you notice about my energy when we first met?",
  "What sort of mood do I bring into a room?",
  "Which part of my personality showed up first today?",
  "What made me seem approachable, if anything?",
  "What detail about me caught your attention first?",
  "How has your first read of me shifted since we started talking?",
  "What kind of setting did you first picture me enjoying?",
  "Which three words fit the version of me you have met so far?",
  "What about my way of speaking stands out to you?",
  "How do I seem to handle being around new people?",
  "What sort of first impression do you think you usually leave?",
  "Which side of you tends to appear earliest in a friendship?",
  "What helps you feel at ease with someone new?",
  "How can you tell when you are starting to click with someone?",
  "What small sign makes a person seem welcoming to you?",
  "What do people often guess correctly about you right away?",
  "What do people tend to discover about you only after a while?",
  "How would a close friend introduce you at a casual gathering?",
  "What part of meeting someone new do you enjoy most?",
  "What kind of conversation makes time pass quickly for you?",
  "How do you usually show that you want to keep talking?",
  "Which small detail makes you curious to continue a first conversation?",
  "Which group setting lets your personality come through naturally?",
  "What helps your quieter side come out around people?",
  "How does your sense of humor usually reveal itself?",
  "What is something your face gives away easily?",
  "What tells you that someone has understood your vibe?",
  "What quality makes you curious to know someone better?",
  "Which part of your personality takes the longest to notice?",
  "What would make today feel like a good first chapter of a friendship?",
  "What kind of friend energy do you think I give off?",
  "Where do you think I naturally fit in a group plan?",
  "What role do you imagine I take when friends cannot decide?",
  "Which word captures the pace of our conversation so far?",
  "Which subjects might be easy for us to talk about?",
  "Which of us seems more likely to start an unplanned adventure?",
  "What kind of outing seems to match our combined energy?",
  "How might our friendship look different in a loud place versus a quiet one?",
  "What could we probably teach each other?",
  "Which everyday situation would show whether we make a good team?",
  "What might make us laugh at the same time?",
  "Which rhythm seems to fit our personalities together?",
  "What part of our conversation has felt most natural?",
  "What friendship habit do you think we might have in common?",
  "Where do our tastes seem likely to overlap?",
  "What harmless topic could you imagine us debating for too long?",
  "How do you picture us spending an unexpectedly free afternoon?",
  "What kind of group chat presence might each of us have?",
  "Which one of us seems more likely to remember a tiny detail?",
  "What would make us a useful duo at a party?",
  "How might we balance each other on a road trip?",
  "Which shared tradition could come easily to us?",
  "Which kind of plan would bring out the best in both of us?",
  "What could turn a casual hangout between us into a great one?",
  "How would you explain our current dynamic to someone who just arrived?",
  "What sort of challenge might be more fun if we tried it together?",
  "Which quality of yours do you think pairs well with mine?",
  "What might we each contribute to hosting a gathering?",
  "What might our recovery from getting mildly lost together look like?",
  "What shared interest would you be least surprised to uncover between us?",
  "Which strength of mine seems easiest to spot?",
  "What do I appear to pay close attention to?",
  "When have I seemed especially comfortable in this conversation?",
  "What kind of task do you imagine I would approach patiently?",
  "How does curiosity show up in the way I talk?",
  "What suggests to you that I am listening?",
  "Which quality do you think others rely on me for?",
  "What do I seem able to make less complicated?",
  "Where might my style of thinking be useful?",
  "What kind of compliment seems likely to land well with me?",
  "Which strength do friends notice in you before you do?",
  "What are you quietly good at during group plans?",
  "What is your subtle way of helping people feel included?",
  "What everyday skill are you proud to have picked up?",
  "When does your patience serve you best?",
  "What kind of problem is oddly satisfying for you to solve?",
  "How do you help a conversation feel easier?",
  "What is your most underrated social skill?",
  "Where does your creativity appear in ordinary life?",
  "What do friends trust your judgment about?",
  "How do you tend to lift the mood?",
  "What quality in yourself has become clearer over time?",
  "When are you especially good at noticing what others miss?",
  "What can you make fun even when the plan is basic?",
  "How do you contribute when you are not leading?",
  "What is a small responsibility you handle unusually well?",
  "Which personal strength feels most natural rather than effortful?",
  "How does your practical side show up with friends?",
  "What are you better at explaining than most people expect?",
  "Which of your qualities would be useful on a chaotic day out?",
  "What snack choice says the most about your taste?",
  "How would you build the ideal background playlist for a hangout?",
  "What kind of place earns an instant spot on your return list?",
  "Which flavor do you almost always choose when it is available?",
  "What makes a café feel worth staying in?",
  "What earns a show another episode from you?",
  "What song works as a reset button for your mood?",
  "Which ordinary object do you care about being well designed?",
  "What kind of weather improves your plans rather than ruins them?",
  "Which words capture your taste in clothes without naming a style?",
  "What food could convince you to change your evening plans?",
  "Which sound makes a place feel pleasant to you?",
  "What is your ideal level of background noise while talking?",
  "How do you choose what to watch when nobody has a suggestion?",
  "What makes a book, podcast, or video easy for you to recommend?",
  "Which color keeps finding its way into things you own?",
  "What kind of souvenir are you actually happy to bring home?",
  "What atmosphere do you want in a room when friends visit?",
  "What menu item are you most tempted to order just to try it?",
  "Which familiar scent puts you in a good mood?",
  "What is a tiny luxury you genuinely appreciate?",
  "What tells you an outfit feels right for you?",
  "What kind of art do you enjoy encountering unexpectedly?",
  "Which season best matches your social life?",
  "What makes a photo worth keeping on your phone?",
  "How adventurous are you when choosing something new to eat?",
  "What kind of live event can hold your attention for hours?",
  "Which local spot would best introduce someone to your taste?",
  "What is one popular thing you enjoy in your own particular way?",
  "How would you design a low-key evening around three favorite things?",
  "What is the first thing you usually do after arriving home?",
  "How does your morning pace compare with your evening pace?",
  "What tiny routine makes your day run better?",
  "Where do you naturally choose to sit in a new place?",
  "How do you keep track of ideas you do not want to lose?",
  "What do you tend to notice while walking somewhere familiar?",
  "How early or late do you like to arrive for casual plans?",
  "What is your usual method for picking a place to eat?",
  "How does your phone home screen reflect your habits?",
  "What do you like to have nearby when you are concentrating?",
  "What turns waiting time into something more enjoyable for you?",
  "What is something you nearly always carry with you?",
  "How do you choose the route when several ways will work?",
  "What household task do you approach with a surprising amount of strategy?",
  "Which part of getting ready takes you the longest?",
  "What does your ideal unhurried morning include?",
  "How do you signal that you are ready to leave a gathering?",
  "What is your pattern when you find a song you really like?",
  "Which messages feel as though they need an immediate reply?",
  "What helps you switch from busy mode into relaxed mode?",
  "Which ordinary choice do you enjoy taking your time with?",
  "How do you behave when you have ten unexpected minutes free?",
  "What is your most reliable way to remember an appointment?",
  "How does your space change when you are working on something?",
  "What do you tend to do while listening to music?",
  "How do you pick what to wear on a day with no fixed plans?",
  "What personal rule keeps your week a little simpler?",
  "Where does spontaneity fit into your usual routine?",
  "What habit of yours would a roommate notice within a week?",
  "What is your favorite way to wrap up a good day?",
  "What has been the easiest thing to talk about today?",
  "Which detail from this gathering do you think you will remember?",
  "How did you end up being part of this group?",
  "What part of today has been better than you expected?",
  "Which conversation here would you gladly continue later?",
  "What has made this setting feel comfortable so far?",
  "How does this group compare with the kinds of groups you usually join?",
  "What is one thing happening around us that you find amusing?",
  "Which shared reference has helped everyone connect?",
  "Which details would convey the atmosphere here to someone outside it?",
  "What has someone said today that made you curious?",
  "Which part of the plan are you most looking forward to?",
  "How are you choosing who to talk with in this room?",
  "What is making this moment feel distinct from an ordinary day?",
  "Which detail about this place would you point out to a friend?",
  "What could make the rest of this gathering even more enjoyable?",
  "How do you tend to find your footing in a group like this?",
  "What topic seems to bring this group to life?",
  "Which moment today would make the best captionless photo?",
  "What has surprised you about the mix of people here?",
  "How would you contribute to the perfect ending for this plan?",
  "What part of the setting affects your mood most?",
  "Which small choice by the host or group worked especially well?",
  "What would you want to remember if we all met again next year?",
  "How has the energy changed since you arrived?",
  "What is one question this particular group could answer brilliantly?",
  "Which nearby detail could inspire our next conversation?",
  "How would this gathering be different if it happened outdoors?",
  "What has helped you feel present rather than distracted?",
  "Which part of this experience would you happily repeat?",
  "Who here seems most likely to discover a great hidden restaurant?",
  "What do you predict I would do with a completely open Saturday?",
  "Which of us would adapt fastest if the plan suddenly changed?",
  "What approach would I take to choosing a team name?",
  "What kind of harmless competition might reveal my playful side?",
  "Where would you expect to find me at a street festival?",
  "What do you imagine I would order from a menu with no descriptions?",
  "How might I react if everyone started dancing?",
  "Which fictional world do I seem most equipped to navigate?",
  "What role would you assign me in planning a surprise?",
  "Where does your imagination place me on a rainy afternoon away from home?",
  "What would my signature dish be based only on my personality?",
  "Which game do you suspect I become unexpectedly competitive about?",
  "What kind of pet do you think would match my daily pace?",
  "How would I probably respond to finding an extra hour in the day?",
  "What do you imagine my travel packing style is like?",
  "Which unusual class could you picture me taking for fun?",
  "What would I be doing at the most relaxed party imaginable?",
  "What seems to guide me when I choose gifts for friends?",
  "Which part of a road trip would I volunteer to handle?",
  "What sort of neighborhood do you think would suit me?",
  "How might I celebrate winning a very small prize?",
  "What would you expect me to photograph on a day out?",
  "Which spontaneous invitation might I accept fastest?",
  "How would I entertain myself during a long delay?",
  "What theme would you trust me to bring to a costume party?",
  "Which item might I insist on bringing to a picnic?",
  "How do you picture me reacting to a surprise compliment?",
  "What job would I take most seriously on a make-believe spaceship?",
  "Which prediction about me would you most like to test someday?",
  "What brings out your most playful version of yourself?",
  "How would you spend a day built entirely around curiosity?",
  "What is the funniest useful talent a person can have?",
  "Which made-up holiday would you genuinely celebrate?",
  "How would you improve a boring queue for everyone in it?",
  "What would your entrance music communicate about you?",
  "Which everyday activity deserves its own championship?",
  "What is a harmless opinion you could defend with dramatic passion?",
  "How would you rename today based on its mood?",
  "What kind of silly challenge reliably gets you involved?",
  "Which object near us has the most personality?",
  "How would you turn an ordinary walk into a small adventure?",
  "What fictional award could your friends nominate you for?",
  "Which animal best captures your energy before breakfast?",
  "What would your warning label say on a very social day?",
  "How would you make a familiar game more ridiculous?",
  "What low-stakes mystery would you enjoy solving?",
  "Which sound effect belongs in the story of your week?",
  "What would you put in a museum of ordinary joys?",
  "How would your friends describe your dancing without demonstrating it?",
  "What tiny inconvenience brings out your most creative solution?",
  "Which imaginary shop would you be delighted to browse?",
  "What would make a terrible theme for a relaxing retreat?",
  "How could you make a meeting about nothing strangely memorable?",
  "Which snack would be your teammate in a trivia contest?",
  "What would your personal mascot encourage people to do?",
  "How would you recognize your own laugh in a crowded room?",
  "What absurdly specific world record might suit you?",
  "Which everyday moment could use a little more ceremony?",
  "How would you explain your current mood using only a weather forecast?",
  "What kind of invitation makes you glad someone thought of you?",
  "What is a considerate way for friends to suggest a change of plans?",
  "What helps you join a conversation already in progress?",
  "How can someone tell you are enjoying their company?",
  "What makes a check-in feel thoughtful instead of routine?",
  "What makes a recommendation appealing when someone shares it with you?",
  "What is a good way to include you in a group decision?",
  "How do you show appreciation after a simple hangout?",
  "What kind of follow-up question makes you feel heard?",
  "How much planning makes a social plan feel easy for you?",
  "What helps you remember a new person's name?",
  "What feels natural to you during a lull in conversation?",
  "What makes it easy for you to say yes to another hangout?",
  "How do you let friends know you need a slower day?",
  "What kind of message is pleasant to receive out of the blue?",
  "What is your way of making room for someone who has not spoken yet?",
  "What does a comfortable silence with a friend feel like to you?",
  "How can a person disagree with you while keeping things warm?",
  "What helps you feel remembered between meetups?",
  "What makes a friend's introduction of you feel accurate?",
  "What makes teasing feel friendly rather than awkward to you?",
  "How do you usually repair a minor misunderstanding?",
  "What signals that someone is genuinely curious about your answer?",
  "How can friends make a last-minute plan feel considerate?",
  "What makes an invitation easy to decline without awkwardness?",
  "What does sharing the spotlight comfortably look like for you?",
  "What helps you stay engaged during a long story?",
  "What clues tell you it is time to change the subject?",
  "What small courtesy matters more to you than people might guess?",
  "How can a new friend make the next conversation easier to begin?",
  "What ordinary moment can reveal a lot about someone's character?",
  "How has your idea of a fun hangout changed over the years?",
  "What do you notice first when two people are good friends?",
  "Which friendship quality becomes more valuable with time?",
  "How do old friends bring out a different side of you?",
  "What keeps a familiar friendship feeling fresh?",
  "When has a casual acquaintance started to feel like a real friend?",
  "What makes someone easy to spend unstructured time with?",
  "How do you recognize a friendship that has found its own rhythm?",
  "What kind of shared memory becomes funnier each time it is told?",
  "How can two friends stay connected without talking every day?",
  "What makes you interested in a perspective different from yours?",
  "How does a friend's enthusiasm affect your interest in something?",
  "What have your friendships taught you about making plans?",
  "Which everyday experience is better when shared with a friend?",
  "How do you keep learning new things about someone you have known for years?",
  "What gives a friendship its own recognizable style?",
  "How can friends with different social batteries enjoy the same plan?",
  "What makes a reunion pick up easily after time apart?",
  "Which small gesture can brighten an ordinary friendship day?",
  "Which qualities make a friendship tradition worth keeping?",
  "What kind of change can make a friendship more interesting?",
  "How does a friend's taste introduce you to something new?",
  "What turns a shared inconvenience into a good story later?",
  "What helps nostalgia and new experiences coexist in a friendship?",
  "What friendship skill improves simply through practice?",
  "Which difference between friends can make a duo stronger?",
  "In what ways can friends influence one another's routines?",
  "What makes a friendship feel easy without feeling taken for granted?",
  "What would you be curious to notice about our friendship a year from now?",
] as const satisfies readonly string[]
