export const STRANGERS_FAMILY_REFLECT = [
  'Which value from your family life feels most worth carrying forward?',
  'How has your idea of family changed as you have grown?',
  'What part of your identity has family helped you understand more clearly?',
  'Where do you notice your own values differing from family expectations?',
  'What have you learned about belonging from the families you have known?',
  'Which lesson from an older generation still guides your choices?',
  'What belief did you thoughtfully choose instead of simply inheriting?',
  'How do you decide which family customs still fit who you are?',
  'What does loyalty mean to you when personal values are also at stake?',
  'In what ways has family influenced how you define a good life?',
  'Which part of your background do you want to understand more deeply?',
  'What has family taught you about making room for different viewpoints?',
  'How would you describe the values you hope people feel around you?',
  'What quality in your family history would you like to strengthen?',
  'Where have you found freedom to become more fully yourself?',
  'What does honoring your roots look like without being limited by them?',
  'How do you want your choices to reflect both connection and individuality?',
  'Which family influence are you newly appreciating?',
  'What have you discovered about yourself through a changing family role?',
  'How would you like future generations to interpret what mattered to you?',
  'What pattern of care in your family feels healthy enough to continue?',
  'Which familiar reaction are you trying to replace with a more useful one?',
  'How do you notice when an old family pattern is shaping a present moment?',
  'What helps you respond thoughtfully instead of falling into an assigned role?',
  'Where could your family make more room for curiosity before conclusions?',
  'What communication habit would make family conversations feel more respectful?',
  'How has your approach to disagreement evolved over time?',
  'What family rhythm works well even if nobody planned it?',
  'Which unhelpful expectation would you like to stop passing along?',
  'When tension rises, what helps you stay connected to your own values?',
  'What have you learned from seeing a family pattern change for the better?',
  'How could family members make misunderstandings easier to correct?',
  'What does a fair pause in a difficult conversation look like to you?',
  'Which recurring family situation could benefit from a new approach?',
  'How do you distinguish a tradition from a habit that can be reconsidered?',
  'What kind of family feedback helps you grow without feeling diminished?',
  'Where would more direct communication reduce guesswork in your family?',
  'What could help your family handle differences without turning them into sides?',
  'How do you want to act when family members remember the same event differently?',
  'What small shift could create a healthier pattern over time?',
  'What does a respectful boundary sound like in your own words?',
  'How do you know when you need space from a family conversation?',
  'Which boundary has helped you participate in family life more honestly?',
  'What makes it easier for you to accept another person’s limits?',
  'How can family members show care without taking over one another’s choices?',
  'Where would clearer expectations make a relationship feel steadier?',
  'What does privacy mean to you within a close family?',
  'How do you balance availability to family with time for yourself?',
  'What response would help when someone says they are not ready to talk?',
  'Which kinds of decisions do you believe should remain personal?',
  'How can a family invitation leave genuine room for someone to decline?',
  'What helps you say no without abandoning warmth?',
  'Where could your family practice asking instead of assuming?',
  'How do you recognize the difference between support and pressure?',
  'What would make requests for help feel more optional and specific?',
  'How can relatives stay connected while wanting different levels of closeness?',
  'What limit would protect your energy during family gatherings?',
  'How would you like others to check before offering advice?',
  'What does respecting autonomy look like across generations?',
  'Which family expectation would benefit from becoming a conversation rather than a rule?',
  'What makes an apology feel accountable rather than performative to you?',
  'How can someone acknowledge harm without deciding how the other person should feel?',
  'What would careful repair look like after a family misunderstanding?',
  'When trust has been strained, what kinds of consistency matter most?',
  'When your intentions and impact differ, what does taking responsibility require?',
  'What helps a difficult conversation remain respectful even without agreement?',
  'Which actions can show changed behavior more clearly than promises?',
  'How might a family make room for repair without expecting a particular outcome?',
  'What do you need in order to consider re-engaging after a conflict?',
  'How can people revisit an old issue without putting anyone on trial?',
  'What role can patience play when rebuilding confidence in a relationship?',
  'How do you know when a conversation has reached a useful stopping point?',
  'What would accountability across generations look like in practice?',
  'When someone names an unintended impact, what response could move the conversation forward?',
  'What helps you separate explanation from excuse?',
  'Where can compassion and consequences exist together in family life?',
  'What would make amends meaningful even if closeness does not return?',
  'How do you hope to handle your next mistake with someone you consider family?',
  'What can a family learn from a rupture even when the ending stays unresolved?',
  'Which sign tells you that a relationship is becoming safer again?',
  'What tradition feels flexible enough to grow with your family?',
  'How would you update a family celebration so more people can participate comfortably?',
  'Which everyday ritual creates a sense of connection for you?',
  'What new tradition could honor the family you are building now?',
  'How can a family preserve stories while allowing different versions to coexist?',
  'What family object would you keep for the meaning rather than the value?',
  'Which recipe, song, saying, or practice carries a story you want remembered?',
  'How do traditions help you locate yourself in time?',
  'What custom are you comfortable letting end?',
  'How could annual gatherings better reflect who the family has become?',
  'What would a low-pressure family ritual look like?',
  'Which milestone deserves a form of recognition your family has not tried before?',
  'How can traditions include people who join a family later?',
  'What practice from chosen family would you like to bring into other relationships?',
  'Where might simplicity make a celebration more meaningful?',
  'How would you document family history without treating one account as the whole story?',
  'What tradition helps you remember someone without requiring everyone to grieve alike?',
  'Which part of a gathering matters more to you than the event itself?',
  'What would you like a future family table to make room for?',
  'How can shared rituals evolve when people live far apart?',
  'Where does decision-making power sit in your family now?',
  'What would meaningful input from the people most affected add to family decisions?',
  'What helps younger voices be taken seriously in a family?',
  'How can elders be respected without making their preferences final?',
  'Which family role gives someone influence that often goes unnoticed?',
  'What would a fairer division of emotional labor look like?',
  'How should money and generosity be discussed when they create unequal influence?',
  'Where could responsibilities be shared more transparently?',
  'What does consent look like when family members make plans on someone else’s behalf?',
  'How can a person with more resources offer help without controlling the outcome?',
  'What family rule would you want everyone to have a voice in revising?',
  'How do age and experience shape who gets believed in your family?',
  'What would make caregiving decisions feel more collaborative?',
  'Where do invisible contributions deserve more recognition?',
  'What might reveal that one person has become the family’s default problem-solver?',
  'What would shared leadership look like during a family challenge?',
  'How might relatives discuss inheritance without reducing relationships to assets?',
  'What helps you speak up when a family hierarchy feels unfair?',
  'How can hosts share control of a gathering with their guests?',
  'Which decision would improve if your family slowed down and heard more perspectives?',
  'What family role have you outgrown?',
  'How has your place in the family shifted as people have aged?',
  'Which responsibility are you ready to share, release, or redefine?',
  'What is surprising about relating to a family member as two changing adults?',
  'How can families welcome a new member without expecting instant closeness?',
  'What helps a blended family build connection at its own pace?',
  'How might a family support someone whose caregiving role is changing?',
  'What does belonging mean when legal, biological, and emotional ties differ?',
  'How can adopted family members be given ownership of their own stories?',
  'What would help foster family relationships honor both care and complexity?',
  'When your priorities change, what response from relatives feels supportive?',
  'What becomes possible when family titles are treated as relationships rather than scripts?',
  'Which role would you like to define for yourself instead of inheriting?',
  'How can siblings or peers renegotiate responsibilities set in childhood?',
  'What support helps when someone moves from receiving care to providing it?',
  'How should family life adapt when distance changes who can be present?',
  'What can make room for step-relatives to shape their own connections?',
  'How does chosen family expand your understanding of kinship?',
  'What would help extended family stay relevant without overstepping?',
  'What helps a family accept that closeness may change across seasons?',
  'What kind of care feels most respectful to you?',
  'How do you prefer family members to offer practical help?',
  'What makes support feel like partnership instead of rescue?',
  'How can care be shared without assuming one person will always provide it?',
  'Which quiet act of care has shaped how you treat others?',
  'What does mutual support look like when people have different capacities?',
  'When you seem overwhelmed, what kind of check-in works best for you?',
  'How has your understanding of reciprocal care become more flexible?',
  'Where could appreciation make unseen family work more visible?',
  'How can relatives care for one another while respecting professional support?',
  'What kind of help is easiest for you to accept?',
  'How might family members coordinate care without speaking over the person involved?',
  'What does sustainable caregiving require from the wider family?',
  'Which forms of care can travel across distance?',
  'What could help a family support rest before someone reaches exhaustion?',
  'What would make asking for assistance feel less loaded?',
  'How do you show concern when you are unsure what someone wants?',
  'What can children contribute to a caring family culture without carrying adult burdens?',
  'How should a family respond when someone’s capacity changes from day to day?',
  'What would a balanced exchange of care look like in your current season?',
  'What helps you listen to a family member without preparing your defense?',
  'How can relatives check that they understood before responding?',
  'What kind of question invites you to think rather than justify yourself?',
  'Where could silence be useful in a family conversation?',
  'How do you prefer someone to signal that they want your full attention?',
  'What helps people remain curious when their memories conflict?',
  'What would let someone who processes slowly participate fully in a family conversation?',
  'What makes you feel heard even when the listener disagrees?',
  'How could family members communicate better across language differences?',
  'What would make remote conversations feel more present and less rushed?',
  'How can humor help connection without dismissing a serious point?',
  'What does a respectful interruption repair sound like?',
  'How might your family make space for people who communicate less verbally?',
  'What helps you ask a follow-up question without sounding skeptical?',
  'When your meaning is unclear, what response would you welcome from a listener?',
  'Which topic would benefit from a calmer setting or a different format?',
  'How can family members disagree without recruiting allies?',
  'What would a useful check-in at the end of a hard conversation include?',
  'How do you recognize when advice is being requested rather than simply listening?',
  'What conversation norm would help everyone participate more freely?',
  'Which family strength deserves more deliberate use?',
  'What have you seen your family adapt to with creativity?',
  'How does your family make newcomers feel that they matter?',
  'What quality helps your family recover after a stressful period?',
  'Where do you see generosity expressed beyond money?',
  'Which family member’s way of caring has broadened your perspective?',
  'What shared resource does your family use especially well?',
  'How have family members made joy during an uncertain time?',
  'What does your family know how to celebrate well?',
  'Which strength could be used more intentionally during conflict?',
  'How does your family keep connection alive across differences?',
  'What family skill would you like to name and appreciate aloud?',
  'Where has flexibility helped your family welcome change?',
  'What example of courage from your family stays with you?',
  'How have relatives created opportunity for one another?',
  'What does resourcefulness look like in your family story?',
  'Which act of inclusion has influenced how you welcome others?',
  'How does playfulness contribute to your sense of family?',
  'Which lesson came from watching a family member begin again?',
  'Which strength do you hope your family recognizes in you?',
  'What does fairness between family members mean when their needs differ?',
  'How can relatives avoid comparing lives that have taken different paths?',
  'Where could family expectations become more responsive to individual circumstances?',
  'What makes recognition feel sincere rather than competitive?',
  'How should shared resources account for both equality and need?',
  'What helps you celebrate a relative without measuring yourself against them?',
  'What would an honest, caring family discussion of unequal opportunities involve?',
  'Which contribution tends to be valued less than it deserves?',
  'What would make household responsibilities feel more equitable?',
  'How can relatives respond when a family rule affects people differently?',
  'What does impartial support look like during a disagreement?',
  'What could addressing favoritism look like without minimizing its impact?',
  'What would help each person define success on their own terms?',
  'How can gifts be given without creating a contest or obligation?',
  'Where should family members have equal voice even when their roles differ?',
  'What is a respectful way to discuss differences in access or advantage?',
  'How can adults avoid assigning fixed labels to children in a family?',
  'What would it look like to distribute opportunities more thoughtfully?',
  'When an achievement breaks tradition, what family response would feel affirming?',
  'What family comparison are you ready to stop using as a measure?',
  'What does emotional safety in a family conversation mean to you?',
  'How can everyone signal that a question feels too personal?',
  'What would help family gatherings feel welcoming to people with different needs?',
  'When you change your mind, what response from others helps you feel respected?',
  'What makes it possible to express uncertainty around family?',
  'During disagreement, what protects each person’s dignity?',
  'What kind of reassurance helps without promising an outcome?',
  'Where could advance notice reduce stress around family plans?',
  'How should relatives handle a story that is not theirs to share?',
  'What makes a conversation feel voluntary from beginning to end?',
  'What helps family members receive correction after making an assumption?',
  'What would help someone participate without being put on the spot?',
  'What tells you that curiosity has crossed into intrusion?',
  'What can a host do to make leaving early feel acceptable?',
  'What could normalize different comfort levels with affection in a family?',
  'What language helps you disagree without questioning someone’s belonging?',
  'How can relatives support a person who prefers not to explain a decision?',
  'What would make family humor feel safer for everyone involved?',
  'How should photos and personal updates be shared with consent?',
  'What could your family do to make opting out feel ordinary?',
  'What do you hope your family relationships make possible in five years?',
  'As everyone’s lives keep changing, what kind of connection would suit you?',
  'Which family practice could you begin with one small step?',
  'What future conversation would be easier if you prepared for it now?',
  'How might your family stay close without expecting constant access?',
  'What do you want younger relatives to experience more freely than you did?',
  'Which responsibility will matter most to plan for together?',
  'How could your family make future transitions less isolating?',
  'What kind of gathering would reflect the family you are becoming?',
  'How do you hope care will be exchanged as people grow older?',
  'What family story would you like to add a new chapter to?',
  'Which relationship would benefit from a realistic shared hope?',
  'How can your family prepare for change without trying to control it?',
  'What would meaningful connection across generations look like next year?',
  'Where do you see room for more choice in your family’s future?',
  'How might technology help connection without replacing presence?',
  'What do you hope stays recognizable even as your family evolves?',
  'Which future tradition could make room for people not yet known to you?',
  'What support could family members offer for one another’s independent paths?',
  'What is one possibility for your family that feels quietly hopeful?',
  'What have family relationships taught you about changing your mind?',
  'How has your definition of responsibility become more nuanced?',
  'Which past choice do you understand with more context now?',
  'What insight have you gained about loving someone without managing their life?',
  'How do you hold gratitude and disappointment at the same time?',
  'What does maturity in a family relationship look like from your perspective?',
  'Where has distance offered useful clarity?',
  'How has becoming more independent changed the way you connect?',
  'Which insight has helped you accept care on your own terms?',
  'Which family expectation has become easier to question thoughtfully?',
  'How do you make peace with a relationship being different from what you imagined?',
  'What insight from family life has improved another relationship?',
  'How has time changed your view of a family decision?',
  'What can you appreciate without wanting to repeat it?',
  'Where have you learned that two experiences of the same family can both be valid?',
  'How do you honor progress that remains incomplete?',
  'What has family taught you about the limits of good intentions?',
  'Which part of growing up now seems more complex than it once did?',
  'How has your understanding of closeness become more flexible?',
  'What family lesson are you still deciding whether to keep?',
  'What personal commitment could improve how you show up with family?',
  'The next time a relative sets a boundary, what response would reflect your values?',
  'Which listening habit do you want to practice more consistently?',
  'What is one way you can make your care easier to understand?',
  'How might you invite feedback without pressuring someone to give it?',
  'What could help you approach a familiar disagreement with fresh curiosity?',
  'Where can you be clearer about what you can realistically offer?',
  'What form of acknowledgment would honor a family member’s effort?',
  'What assumption about someone close to you could you gently reexamine?',
  'How might you protect time for a relationship that matters to you?',
  'What would help you follow through on a promise without overcommitting?',
  'Which family story could you ask about with care and permission?',
  'How can you make more room for another person’s way of doing things?',
  'What is one household or family task you could make more collaborative?',
  'What example of accountability do you hope to set for people who look to you?',
  'What could you do to reduce pressure at the next family occasion?',
  'Where might a simple clarification prevent resentment?',
  'How can you support someone’s decision even when you would choose differently?',
  'What practice could help you stay grounded around family expectations?',
  'Which relationship deserves a more honest assessment of what is possible?',
] as const satisfies readonly string[]
