export const STRANGERS_PARTNER_WARM_UP = [
  'What detail about me caught your attention most recently?',
  'How has your first impression of me shifted since we began talking?',
  'Which part of my personality showed up sooner than you expected?',
  'What did my way of speaking suggest to you when we first met?',
  'What seemed easiest for us to talk about at the beginning?',
  'Which of my expressions did you learn to recognize quickly?',
  'What about my energy felt familiar when we met?',
  'What early moment made you curious to know me better?',
  'How would you describe the pace of our first few conversations?',
  'What did you notice about how I listened when we were getting acquainted?',
  'Which early assumption about me turned out to be pleasantly off?',
  'What part of meeting me felt unexpectedly easy?',
  'What do you remember about the atmosphere the first time we really talked?',
  'How did I seem different once I felt more comfortable around you?',
  'What quality of mine was harder to spot at first?',
  'Which early interaction best captures how we connected?',
  'What did you initially think would be our easiest point of connection?',
  'How would you compare my first-impression energy with my energy now?',
  'What small choice of mine stood out when we were first getting to know each other?',
  'Which side of me appeared only after a few conversations?',
  'What made our earliest conversations feel distinct to you?',
  'What about me seemed most approachable from the start?',
  'How did your picture of my everyday life change as you learned more?',
  'What did I reveal about myself without realizing it early on?',
  'Which first impression of yours still feels accurate today?',
  'What surprised you about the way our conversation flowed?',
  'What did my sense of humor seem like before you fully understood it?',
  'Who was the version of me you first encountered?',
  'What early detail about you do you think I noticed?',
  'Which ordinary moment helped you see me more clearly?',

  'What mood do I seem to bring into the room today?',
  'Which detail of my current look feels most like me?',
  'When I enter a space, how do I tend to settle in?',
  'How can you usually tell when I am interested in a conversation?',
  'What does my face communicate before I say anything?',
  'Which kind of setting seems to bring out my liveliest energy?',
  'What changes in my voice when I get excited about something?',
  'Which three unexpected words capture my presence today?',
  'What do my everyday choices suggest I pay attention to?',
  'Which part of my style feels especially expressive?',
  'When I am thinking, which little behaviors give me away?',
  'How does my energy change between quiet and busy places?',
  'What kind of weather seems to match my vibe today, and why?',
  'Which color feels most connected to my current energy?',
  'What makes me look most at ease?',
  'How do I signal that I am ready to join in?',
  'What is something my posture seems to say today?',
  'Which of my mannerisms feels most recognizable?',
  'When something surprises me, how does my reaction unfold?',
  'What rhythm do I bring to a conversation?',
  'What about my appearance today seems chosen with care?',
  'Which everyday object seems to suit my personality?',
  'What kind of room would match the energy I have right now?',
  'How does my attention show up when you are speaking?',
  'What seems to make my energy soften?',
  'Which small reaction of mine is easy for you to read?',
  'What part of my current mood feels contagious?',
  'How would you sketch my vibe using only shapes and colors?',
  'In new surroundings, where does my attention seem to go first?',
  'Which detail about me feels different today than usual?',

  'What kind of plan do I seem happiest to say yes to?',
  'Which snack would you pick for me without asking, and what led you there?',
  'What type of music seems to fit my everyday pace?',
  'How would you guess I choose something from a long menu?',
  'Which season seems most compatible with my personality?',
  'What sort of weekend morning do you think I enjoy most?',
  'Which movie role would be fun to watch me play?',
  'What kind of gift seems especially suited to me?',
  'How do you imagine I decide whether to try a new place?',
  'Which flavor combination feels like something I would defend?',
  'What sort of view do you think I could stare at for ages?',
  'Which household sound would I probably find most comforting?',
  'What kind of celebration seems most my speed?',
  'How would you predict I spend an unexpected free hour?',
  'Which fictional world would suit me for a day?',
  'What kind of café table would I choose first?',
  'Which simple pleasure seems most likely to brighten my afternoon?',
  'What would you put on a tiny playlist made for my current mood?',
  'How do you think I prefer a plan to be presented to me?',
  'Which local outing sounds most like my idea of fun?',
  'What kind of souvenir would I be tempted to bring home?',
  'Which breakfast says the most about my taste?',
  'What sort of story usually holds my attention?',
  'How would you guess I choose between comfort and novelty?',
  'Which sound belongs in the background of my ideal evening?',
  'What kind of tiny luxury do you think I appreciate?',
  'Which game would bring out my playful side fastest?',
  'What sort of shop could I wander through without checking the time?',
  'How do you imagine I would personalize a blank room?',
  'Which everyday choice reveals my taste most clearly?',

  'What routine of mine seems to help me find my footing?',
  'How do I usually approach a task I have been putting off?',
  'Which tiny habit of mine makes the day run more smoothly?',
  'Before going somewhere, which part of my preparation stands out?',
  'Where does being on time seem to sit among my priorities?',
  'What seems to be my first move when a plan changes?',
  'Where does my daily rhythm appear most consistent?',
  'How do I tend to make an ordinary errand more enjoyable?',
  'What does my way of organizing things reveal about my priorities?',
  'Which habit suggests I like to be prepared?',
  'How do I behave when I finally have nothing scheduled?',
  'Before leaving, what am I most likely to check twice?',
  'Which routine would you recognize as mine from across the room?',
  'How does my pace change when I am running late?',
  'What is my most charmingly inefficient habit?',
  'Which part of a shared plan do I naturally keep track of?',
  'What do I tend to do while waiting for something?',
  'What is distinctive about my approach to keeping useful little things?',
  'Which ordinary task seems to put me in a focused zone?',
  'What signals that I am ready to wrap up the day?',
  'Where does my personality appear in a familiar routine?',
  'What kind of reminder seems to work best for me?',
  'Which habit of mine would be easiest to imitate in a playful impression?',
  'How do I usually respond when technology refuses to cooperate?',
  'What does my packing style seem to say about me?',
  'Which daily decision do I make surprisingly quickly?',
  'How do I tend to use the first few minutes after arriving somewhere?',
  'What mundane thing do I somehow turn into a whole event?',
  'Which small ritual seems to improve my mood?',
  'How would you narrate one of my most familiar routines?',

  'What kind of humor seems to land best with me?',
  'Which clue reveals that I am trying not to laugh?',
  'Which harmless topic could spark my most dramatic speech?',
  'What would my signature move be in a very low-stakes competition?',
  'How do I act when I become unexpectedly competitive?',
  'Which animal would make a surprisingly good mascot for me?',
  'What silly award could I realistically win today?',
  'How would I handle being the host of a wildly niche game show?',
  'Which minor inconvenience might inspire my funniest reaction?',
  'What kind of joke do you expect me to repeat later?',
  'How would you cast me in a friendly heist involving only snacks?',
  'Which made-up holiday would I celebrate with full commitment?',
  'What would my warning label say if it had to be affectionate?',
  'How do you picture me reacting to a surprise dance break?',
  'Which completely ordinary skill could I turn into a contest?',
  'What imaginary job title matches one of my quirks?',
  'How would I try to win over a suspicious neighborhood cat?',
  'Which emoji combination captures my sense of humor?',
  'What would be the funniest item for me to collect seriously?',
  'How do I show that I am enjoying a bit?',
  'Which harmless conspiracy about my habits could you invent?',
  'What role would I take during an extremely casual trivia night?',
  'Without imitating it, what makes my laugh recognizable?',
  'Which everyday situation could become a comedy scene with me in it?',
  'What kind of nickname would suit my playful side?',
  'How might I make a boring announcement more entertaining?',
  'Which ridiculous challenge would tempt me purely for the story?',
  'What would my entrance music be for doing a routine chore?',
  'How do I recover when my joke gets no reaction?',
  'Which playful version of me deserves its own character name?',

  'What strength of mine appears in small everyday moments?',
  'In what quiet ways do I help people feel included?',
  'Which quality of mine becomes clearer the longer we talk?',
  'Where does my patience seem to come most naturally?',
  'When I encourage someone, what approach do I take?',
  'Which kind of decision brings out my practical side?',
  'What suggests that I care about getting something right?',
  'How do I respond when someone offers a different perspective?',
  'Where do two sides of my personality balance each other?',
  'What do I bring to a plan that might otherwise be missing?',
  'How does my curiosity show itself?',
  'Which situations bring out my calmest side?',
  'In a good conversation, what appears to matter most to me?',
  'Which signals show that something has earned my full attention?',
  'Which quality helps me adapt when things feel unfamiliar?',
  'What does my way of asking questions reveal about me?',
  'Without stating them directly, how do my preferences become clear?',
  'Which trait of mine seems quiet but important?',
  'What kind of problem brings out my resourceful side?',
  'Where can you see the care I put into small choices?',
  'Which aspect of my personality is easiest to underestimate?',
  'Which easily missed details am I likely to notice?',
  'How does my independent side appear in daily life?',
  'Which quality makes me good company in an ordinary moment?',
  'What do I do that shows I am comfortable being myself?',
  'Where do I land between careful planning and improvising?',
  'Which kind of conversation brings out my thoughtful side?',
  'What seems to help me stay open-minded?',
  'How do I add my own twist to a shared idea?',
  'Which everyday quality of mine deserves more credit?',

  'Which part of spending time with you seems to delight me lately?',
  'How does my energy seem to respond to yours?',
  'Which kind of moment between us feels easiest to settle into?',
  'In conversation, what do we naturally make room for?',
  'What pace do we tend to find when we are together?',
  'What side of yourself seems to come forward around me?',
  'Which of our differences makes an ordinary moment more interesting?',
  'Which things are we especially good at noticing about each other?',
  'How do we make a simple plan feel like ours?',
  'Which shared mood do we slip into most easily?',
  'What kind of silence between us feels most comfortable?',
  'How do you know when we are on the same wavelength?',
  'Which everyday topic brings out our best back-and-forth?',
  'When we make decisions together, what pattern emerges?',
  'To someone meeting us today, what would our combined energy feel like?',
  'What tiny moment between us recently felt especially natural?',
  'Which setting seems to suit us both at once?',
  'How do our senses of humor meet in the middle?',
  'Which part of your pace have I learned to understand?',
  'Which part of your everyday personality do you think I appreciate most?',
  'What happens to the atmosphere when we both relax?',
  'How do we signal that it is time to change the subject?',
  'Which choice do you think we would make similarly without consulting each other?',
  'What kind of people-watching observation would we both enjoy?',
  'How does each of us contribute to keeping a conversation moving?',
  'Which small difference in our tastes leads to good conversation?',
  'Which things appear easiest for me to share with you?',
  'What is the space we give each other to think like?',
  'Which ordinary interaction captures our dynamic particularly well?',
  'What do we seem to bring out in each other today?',

  'What question do I seem happiest to be asked?',
  'How do you like me to show that I am following your story?',
  'Which topics make time pass quickly when we talk?',
  'What helps our conversations feel unhurried?',
  'Which cues tell you that I want to hear more?',
  'What kind of follow-up question feels most natural from me?',
  'Which conversation setting helps you feel most present with me?',
  'How do you experience my way of leaving room for your answer?',
  'What do I do that makes a story easier for you to tell?',
  'Which subjects reveal the biggest contrast in how we think?',
  'What marks our shift from joking to being thoughtful?',
  'What makes you feel heard in an everyday exchange with me?',
  'Which question from me has led somewhere unexpectedly fun?',
  'How do we handle a pause when neither person knows what to say next?',
  'What do you enjoy about the way I tell a story?',
  'Which detail are you most likely to notice in one of my stories?',
  'How do our conversation styles complement each other?',
  'What helps you know I am listening rather than waiting to speak?',
  'Which kind of story do you think I could tell especially well?',
  'When I change the subject, how do I usually make the turn?',
  'What makes a question feel inviting to you?',
  'Which part of our conversations tends to be most spontaneous?',
  'How do I react when you introduce an idea I had not considered?',
  'What could we talk about for ten minutes with no preparation?',
  'Which everyday debate would be fun for us to explore?',
  'How do you prefer I check that I understood you?',
  'What do our best conversations have in common?',
  'Which topic makes both of us more animated?',
  'How do we each show curiosity differently?',
  'What is something you would enjoy comparing notes on with me?',

  'What outfit choice of mine best captures my personality?',
  'Without naming any clothing brands, which words capture my style?',
  'Which texture seems most at home in my wardrobe?',
  'What accessory would you choose to represent my vibe?',
  'How do I balance comfort and expression in what I wear?',
  'Which detail makes something look distinctly like my choice?',
  'What kind of color pairing can you imagine me trying?',
  'How would you design a casual uniform for my everyday life?',
  'Which part of getting ready seems most fun for me?',
  'What does my style communicate before I speak?',
  'How might I dress for an event with a delightfully vague theme?',
  'Which fictional character could borrow something from my closet?',
  'What style choice of mine has grown on you?',
  'What personal touch do I bring to a practical item?',
  'Which era could lend my style an interesting detail?',
  'What kind of setting makes my style stand out most?',
  'What changes most between my relaxed and dressed-up looks?',
  'Which item do you think I choose based mainly on how it feels?',
  'What visual detail do I return to in different forms?',
  'How do my surroundings reflect my taste?',
  'Which design choice would I notice first in a new place?',
  'What object would fit naturally on a mood board inspired by me?',
  'How would you translate my personality into an interior style?',
  'Which small style experiment could you picture me enjoying?',
  'What kind of pattern feels most aligned with my energy?',
  'How does my style change with my mood?',
  'Which practical choice do I still manage to make expressive?',
  'What would the cover of a magazine about my taste look like?',
  'What is my way of making familiar things feel like my own?',
  'Which element of my taste would you borrow for a day?',

  'What low-key outing would you plan around my current energy?',
  'How do you think I would spend a day with no obligations?',
  'Which small adventure would feel just outside my usual routine?',
  'What kind of place could make us both curious at the same time?',
  'How would you turn an ordinary walk into a game for us?',
  'Which nearby destination would be fun to discover together?',
  'What theme would you choose for a spontaneous hour out?',
  'How might we make a familiar neighborhood feel new?',
  'Which simple plan would leave plenty of room for improvising?',
  'What would you include in a tiny picnic chosen for our personalities?',
  'How could we spend an afternoon using only things already nearby?',
  'Which kind of market or fair would be interesting to explore side by side?',
  'What would make a short trip feel restful to both of us?',
  'How would you divide the choices on a choose-your-own-adventure day?',
  'Which everyday place might become memorable with the right conversation?',
  'What kind of class would be amusing for us to try once?',
  'How could we celebrate a completely made-up occasion?',
  'Which activity would let each of us enjoy it in our own way?',
  'What would a screen-free hour together look like today?',
  'How might we design a plan around one shared curiosity?',
  'Which small challenge could we complete as a team this week?',
  'What kind of photo walk would match our combined taste?',
  'How would you build a cozy evening from three simple ingredients?',
  'Which plan would work equally well if we changed it halfway through?',
  'What would make an everyday meal feel like an occasion?',
  'How could we each add one surprise to a simple outing?',
  'Which place would give us plenty to notice and discuss?',
  'What kind of shared project could stay playful and low-pressure?',
  'How would you create a mini tradition that fits us right now?',
  'Which uncomplicated experience would you be curious to share next?',
] as const satisfies readonly string[]
