export const STRANGERS_FAMILY_CONNECT: readonly string[] = [
  "What qualities make someone feel like family to you?",
  "How do you recognize care when it comes from a family member?",
  "What is something a family member has taught you simply by being themselves?",
  "Which kind of family encouragement stays with you the longest?",
  "What part of your connection with family feels especially worth appreciating?",
  "How do you prefer family members to celebrate your efforts?",
  "What is a quiet way someone in your family has made life easier?",
  "Which everyday gesture helps you feel valued by family?",
  "What strength do you notice in a family member that deserves more recognition?",
  "How has a family member helped you see something from a new angle?",
  "What kind of compliment feels most genuine coming from family?",
  "When does gratitude between family members feel easiest to express?",
  "What is one way family can bring out a good side of you?",
  "How would you describe a contribution you make to the people you call family?",
  "What makes an act of care feel personal rather than automatic?",
  "Which family connection has expanded your idea of what support can look like?",
  "What do you admire about how someone in your family moves through the world?",
  "How do you like to let family members know their presence matters?",
  "What is something about your family connections that you do not take for granted?",
  "Which small kindness would you happily receive more often from family?",
  "What is a family member good at noticing about you?",
  "How has someone in your family made room for you to be yourself?",
  "What kind of appreciation would feel meaningful to hear today?",
  "Which shared quality helps you relate to a family member?",
  "What would you thank a family member for if the moment felt right?",
  "What helps you feel that you belong in a family space?",
  "How do you decide who belongs in your personal idea of family?",
  "What makes a gathering feel welcoming to you?",
  "Where do you feel most at ease with people you consider family?",
  "How can family members make room for different ways of participating?",
  "What signals tell you that your perspective is welcome?",
  "Which parts of yourself feel easiest to share with family?",
  "How would you like family members to include you in decisions that affect you?",
  "What does being accepted without having to perform look like to you?",
  "When have you felt pleasantly surprised by a sense of family?",
  "What helps a newer family connection grow at a comfortable pace?",
  "How can people honor a family bond that does not fit a familiar label?",
  "What makes a family space comfortable for both talkative and quiet people?",
  "Which signs of welcome matter more to you than formal invitations?",
  "How do you stay connected to your own identity within a family group?",
  "What would make family introductions feel more thoughtful?",
  "How can a family help someone feel included without putting them on the spot?",
  "What does having a place in a family mean in your life right now?",
  "Which family setting lets you participate most naturally?",
  "How do you like differences among family members to be acknowledged?",
  "What helps belonging feel chosen rather than expected?",
  "Where have you found a family-like sense of welcome unexpectedly?",
  "How can family members show that there is room for a changing version of you?",
  "What makes you feel known without feeling defined by others?",
  "Which words best describe the kind of family atmosphere you enjoy?",
  "How do you prefer someone to ask what support you need?",
  "What kind of help feels caring without feeling intrusive?",
  "When you have a demanding week, what support is actually useful?",
  "How can a family member tell whether you want ideas or simply company?",
  "What makes an offer of help easy for you to accept?",
  "Which practical gesture helps you feel less alone with a task?",
  "How do you like people to check in when you are under pressure?",
  "What form of encouragement helps you keep your own sense of direction?",
  "When does giving you space count as support?",
  "What would a low-pressure check-in sound like to you?",
  "How do you signal that you have enough help for now?",
  "Which kind of support do people sometimes overlook because it seems small?",
  "What helps you trust that an offer comes without strings attached?",
  "How can family members support a goal without taking it over?",
  "What is your preferred way to receive care when your energy is low?",
  "When you share a concern, what response helps you feel heard?",
  "How would you want someone to follow up after offering support?",
  "What makes mutual support feel balanced over time?",
  "Which kind of reassurance lands well for you?",
  "How do you prefer to ask family for a hand with something?",
  "What support can be meaningful even when no solution is available?",
  "When does humor help you feel supported, and when does it not?",
  "How can someone be dependable while respecting your independence?",
  "What is one care preference you would like family to understand better?",
  "How do you know when support has matched what you needed?",
  "What helps a family conversation feel safe enough to be honest?",
  "How do you like someone to begin a meaningful conversation with you?",
  "When is the best time and setting for you to talk about something important?",
  "What listening habit makes you want to keep talking?",
  "How can a family member show curiosity without making you feel examined?",
  "What helps you stay open when another person sees things differently?",
  "How do you prefer misunderstandings to be clarified?",
  "What makes a question feel inviting instead of demanding?",
  "When do you find it easier to communicate in writing than aloud?",
  "How can someone let you know they understood what you meant?",
  "What pace allows a thoughtful conversation to unfold for you?",
  "How do you like to pause a discussion that needs more time?",
  "What helps you say, 'I see it differently,' with care?",
  "Which conversation topics are better approached with advance notice?",
  "How do you prefer people to respond when you change your mind?",
  "What is a respectful way to revisit a conversation later?",
  "How can family members make space for answers that are still uncertain?",
  "What tone helps you hear feedback as an invitation rather than a verdict?",
  "When does silence feel companionable during a conversation?",
  "How would you like someone to check whether they understood you correctly?",
  "What keeps a disagreement from overshadowing the relationship?",
  "How can family conversations leave room for more than one valid experience?",
  "What communication habit would you like to practice more with family?",
  "When do shared jokes strengthen communication for you?",
  "How do you want a family member to respond if a question feels too personal?",
  "What does a healthy boundary make possible in a family relationship?",
  "How do you prefer to let family know that a topic is off-limits?",
  "What helps you respect a boundary you do not fully understand?",
  "When does privacy feel especially important to you?",
  "How can invitations make it genuinely comfortable to decline?",
  "What is a considerate way to ask before sharing family news?",
  "How would you like someone to handle photos or stories that include you?",
  "What does respectful notice look like before a family visit or call?",
  "How do you decide what parts of your life to keep private?",
  "Which boundary helps you be more present when you do connect?",
  "What makes a request feel negotiable rather than assumed?",
  "How can someone respond well when your availability changes?",
  "What is a kind way to protect your time during a busy season?",
  "How do you like family members to check before offering advice?",
  "What helps a 'not today' feel accepted without further explanation?",
  "When do you prefer one-to-one connection over a group setting?",
  "How can family members avoid speaking for one another?",
  "What boundary around communication makes connection easier for you?",
  "How do you distinguish between helpful persistence and unwanted pressure?",
  "What would make it easier to correct someone who crosses a small boundary?",
  "How should family members handle information shared in confidence?",
  "What does respecting personal space mean to you beyond physical distance?",
  "How can a family plan include people with different limits?",
  "What is one boundary you appreciate when others state clearly?",
  "How do boundaries help trust grow in your experience?",
  "What choices about your life are especially important for you to make independently?",
  "How can family show interest in your plans without steering them?",
  "What does encouragement with no attached expectation sound like?",
  "When do you enjoy receiving opinions from family?",
  "How would you like others to react to a path they would not choose themselves?",
  "What helps you feel trusted to know your own needs?",
  "How can family members celebrate a decision without claiming credit for it?",
  "What does being treated as capable look like to you?",
  "When is collaboration welcome in a choice that is yours?",
  "How do you want family to approach decisions about shared resources?",
  "What makes it easier to name your own priorities around family?",
  "How can someone stay curious about your choices without asking for justification?",
  "Which kind of independence has strengthened a family connection for you?",
  "What helps you keep ownership of a goal while accepting help?",
  "How would you want a family member to respond to a firm decision?",
  "What does freedom within a close relationship mean to you?",
  "When do expectations begin to feel like obligations?",
  "How can family members make shared choices without assuming everyone agrees?",
  "What would help you participate in plans on your own terms?",
  "How do you balance personal priorities with commitments you freely choose?",
  "What is a respectful way for family to express concern about your decision?",
  "How can people leave room for your answer to change over time?",
  "What helps advice remain optional after it is offered?",
  "Which family expectation would benefit from being discussed rather than presumed?",
  "How do you want your 'yes' to be understood when it comes with conditions?",
  "What role do you naturally enjoy taking in family settings?",
  "How have your family roles shifted as your life has changed?",
  "Which responsibility feels satisfying when you choose it?",
  "How can family members notice when an old role no longer fits someone?",
  "What role would you like to step back from, even occasionally?",
  "How do you prefer responsibilities to be divided for a shared plan?",
  "What helps people rotate the invisible work of staying connected?",
  "When do you feel most comfortable taking the lead?",
  "How can a family value the person who contributes quietly?",
  "What role does humor play in your family connections?",
  "How do you want to be approached when someone hopes you will help?",
  "What responsibility is often mistaken for belonging in families?",
  "How can people check whether a familiar arrangement still works?",
  "Which strengths would you enjoy bringing to a family project?",
  "What makes shared responsibility feel fair to you?",
  "How do you prefer to hand over a task you have usually handled?",
  "What could make it easier for a family member to ask for a different role?",
  "When has letting someone else lead improved a family experience?",
  "How can family members appreciate effort that is easy to miss?",
  "What part do you like playing when plans are still taking shape?",
  "How do you respond when family members expect different things from the same role?",
  "What would a more flexible approach to family responsibilities look like?",
  "Which role feels energizing rather than draining for you?",
  "How can people make room for contribution without requiring it?",
  "What is one way you would like your place in the family to evolve?",
  "What makes a tradition meaningful enough for you to continue?",
  "How could a family tradition remain optional and still feel special?",
  "Which simple ritual helps create connection for you?",
  "What would you enjoy adding to a family gathering?",
  "How can traditions adapt when people's circumstances change?",
  "What food, activity, or sound gives a family moment extra meaning for you?",
  "How do you feel about creating traditions that are not tied to holidays?",
  "What is a tradition you enjoy experiencing in your own way?",
  "How can a gathering honor both participation and rest?",
  "Which recurring moment would you like family to make more intentional?",
  "What makes a new ritual feel natural rather than forced?",
  "How would you design a celebration that suits different comfort levels?",
  "Which familiar custom have you reshaped to better reflect your present life?",
  "How can family members ask about customs they do not know?",
  "What would make a milestone feel genuinely celebrated for you?",
  "Which family ritual deserves a fresh version?",
  "How do you decide whether to join a tradition?",
  "What small routine could make staying connected more enjoyable?",
  "How can a tradition leave room for people who relate to it differently?",
  "What kind of occasion brings out your favorite side of family connection?",
  "How might family members mark good news without making it a spectacle?",
  "What is a meaningful way to welcome someone into a shared custom?",
  "Which informal tradition feels more important than it might look?",
  "How could a family retire a tradition with appreciation?",
  "What would an ideal low-pressure family celebration include?",
  "What everyday task is easier when family approaches it as a team?",
  "How do you like practical help to be offered?",
  "Which small responsibility could be shared more thoughtfully?",
  "What makes coordinating family plans less stressful for you?",
  "How can people check what is actually helpful before stepping in?",
  "What practical skill would you be glad to share with family?",
  "When does a reminder feel useful rather than controlling?",
  "How do you prefer to plan around different schedules and energy levels?",
  "What is a fair way to divide costs for an optional family plan?",
  "How can a family member help from a distance in a meaningful way?",
  "What kind of backup plan helps you feel comfortable committing?",
  "How do you want people to communicate changes to shared arrangements?",
  "Which practical detail is worth discussing earlier than families often do?",
  "What makes hosting or organizing feel manageable for you?",
  "How can people contribute to a gathering without spending money?",
  "What is one errand or chore you would happily trade with someone?",
  "How do you prefer to coordinate care when several people want to help?",
  "What would make shared planning more accessible to everyone involved?",
  "When is a specific offer more useful than 'let me know'?",
  "How can family members notice work without assigning it automatically?",
  "What system helps you keep group plans clear without too many messages?",
  "How would you like practical decisions to be documented or remembered?",
  "What does reliability look like in a small family commitment?",
  "How can a plan leave space for someone to opt in later?",
  "Which kind of practical care communicates warmth to you?",
  "How has your definition of family changed over time?",
  "What helps a relationship adjust when people's lives move in different directions?",
  "Which change in a family connection has opened a new possibility?",
  "How do you like others to get to know the person you are becoming?",
  "What makes it easier to update an old understanding of someone?",
  "How can family stay curious about changes without demanding details?",
  "What has become more important to you in family relationships lately?",
  "Which small family gesture helps restore connection after schedules diverge?",
  "What helps closeness survive a change in routine?",
  "Which kind of change deserves more patience from family?",
  "How can a family welcome a new dynamic without comparing it to the past?",
  "What have you learned about letting relationships find a new rhythm?",
  "How do you want family members to acknowledge a transition in your life?",
  "What makes it possible to stay connected across different seasons of life?",
  "How can people release an outdated expectation with kindness?",
  "What part of a changing family role feels interesting to you?",
  "When has distance offered a useful perspective on a family connection?",
  "How might a relationship grow without needing to become closer?",
  "What helps you accept that two family members may change at different speeds?",
  "How can family ask about what is new while respecting what stays private?",
  "What is one update about your life you would enjoy sharing?",
  "How do you recognize when a family relationship needs a different pace?",
  "What can remain steady even while a family structure changes?",
  "How would you like someone to respond when you outgrow an old preference?",
  "What possibility can change bring to a family connection?",
  "What kind of time together helps you feel connected without pressure?",
  "How do you enjoy spending time with family when conversation is not the focus?",
  "Which shared activity makes it easy to be yourself?",
  "What would make a short visit feel worthwhile to you?",
  "How do you prefer to keep in touch when life is full?",
  "What kind of invitation are you most likely to enjoy?",
  "When does doing something side by side help conversation flow?",
  "How can family time work well for people with different social energy?",
  "What is an ordinary place where you enjoy connecting with someone?",
  "Which low-cost activity could make a good family memory?",
  "How do you like to balance planned time and spontaneity?",
  "What makes remote connection feel personal to you?",
  "Which shared interest could you explore with a family member?",
  "How would you spend an unhurried hour with someone you consider family?",
  "What helps a group activity feel easy to join and easy to leave?",
  "When do you most enjoy catching up one to one?",
  "What setting brings out the best conversations for you?",
  "How can family members connect when their preferred activities differ?",
  "What is something pleasant you could teach or learn during time together?",
  "Which kind of recurring plan feels sustainable to you?",
  "How do you like a visit to wind down?",
  "What would make shared downtime genuinely restful?",
  "How can people be together without needing to fill every moment?",
  "What kind of family time would you like to try once, with no obligation to repeat it?",
  "Which simple experience would you enjoy sharing soon?",
  "What do you hope family relationships add to your life?",
  "How would you like a family connection to feel a year from now?",
  "What kind of mutual understanding would you like to grow?",
  "Which part of family life would you like to make gentler?",
  "How can family members encourage one another's hopes without setting deadlines?",
  "What would more ease look like in your family connections?",
  "Which shared value would you like to put into practice more often?",
  "How do you hope people in your family will remember the way you treated them?",
  "What is one form of connection you would like to protect as life changes?",
  "How might family become a place for more curiosity?",
  "What would help future gatherings feel considerate of everyone present?",
  "Which kind of support do you hope becomes more natural among family?",
  "How would you like family members to make space for good news?",
  "What is a realistic hope you have for communicating with family?",
  "How can a family build trust through small, repeatable actions?",
  "What do you hope never becomes an obligation in your family relationships?",
  "Which new understanding would make family connection easier?",
  "How would you like care to travel across different branches of a family?",
  "What does a hopeful next chapter in a family relationship mean to you?",
  "How can family connections support each person's wider community?",
  "What would you like to learn from someone you consider family?",
  "Which family habit could create more room for joy?",
  "How do you hope autonomy and closeness can coexist in your family?",
  "What is one intention you would bring to future family conversations?",
  "What kind of family culture would you be glad to help shape?",
] as const
