export const STRANGERS_FRIENDS_REFLECT = [
  "Which lesson from knowing each other has become useful elsewhere in your life?",
  "How has your idea of a good friend become more nuanced over time?",
  "What has this friendship helped you notice about the way you connect with people?",
  "Where have you become more generous in your understanding of friendship?",
  "What belief about friendship feels less true to you than it once did?",
  "Which part of being a friend have you learned cannot be rushed?",
  "How do you now recognize when a friendship is making room for both people?",
  "What has experience taught you about letting friends be different from you?",
  "Which friendship skill are you still learning in real time?",
  "What have you learned about the difference between closeness and constant contact?",
  "How has your understanding of loyalty grown beyond simply agreeing with someone?",
  "What does friendship teach you that you rarely learn on your own?",
  "Which lesson about timing has shaped the way you approach friends?",
  "What have friendships shown you about the value of changing your mind?",
  "How do you distinguish a friendship habit from a friendship value?",
  "What has becoming a better listener changed about your friendships?",
  "Which lesson about expectations would you pass on to someone building a new friendship?",
  "What do you understand about friendship now that once confused you?",
  "How have your friendships challenged an old assumption about connection?",
  "Which lessons help you care for someone whose choices differ from yours?",
  "Which quiet lesson from a friendship has stayed with you?",
  "What has friendship taught you about making space for uncertainty?",
  "How do you think friendship wisdom differs from friendship advice?",
  "What have you learned from a friendship that changed form without losing its value?",
  "Which idea about being a good friend are you currently reconsidering?",
  "What does experience suggest matters more than having everything in common?",
  "How has friendship refined your sense of what respect looks like?",
  "In what ways do you think you have each changed since becoming friends?",
  "Which change in your life has affected how you participate in friendship?",
  "How has the pace of your life altered what connection looks like for you?",
  "What part of your friendship style has softened with time?",
  "In what situations are you more direct with friends than you used to be?",
  "How do you hope your way of caring for friends keeps evolving?",
  "Which change in yourself would an old friend notice first?",
  "What has growing into a new season revealed about your social needs?",
  "Which forms of availability feel sustainable in friendship now?",
  "What kind of change is easiest for you to welcome in a friendship?",
  "Which shift between you has brought an unexpected benefit?",
  "How do you make room for a friend to become someone new?",
  "What has stayed recognizable in your connection even as life has changed?",
  "Where might an older version of you be surprised by this friendship today?",
  "How has a change in priorities reshaped the way you spend time with friends?",
  "Which part of friendship feels more important in this season than in the last?",
  "What helps you remain curious when a friend is changing?",
  "How do you tell the difference between growing apart and simply growing differently?",
  "What evolution in your friendship are you glad you allowed to happen naturally?",
  "Which old dynamic no longer fits the people you are becoming?",
  "How has your capacity for friendship changed as your responsibilities have grown?",
  "What new side of yourself has appeared in your friendships lately?",
  "Where could your friendships benefit from updating an old expectation?",
  "What kind of friendship rhythm suits your life now?",
  "How might you stay connected while honoring a major life transition?",
  "Which change has made you appreciate a familiar friend in a new way?",
  "What do you hope friends allow you to revise about yourself?",
  "What perspective have you picked up from each other without deliberately trying?",
  "How has knowing me influenced the questions you ask yourself?",
  "Which quality in a friend has encouraged you to practice it more yourself?",
  "What have you borrowed from a friend's way of handling everyday life?",
  "How do friends expand the range of futures you can imagine for yourself?",
  "What part of your taste or routine carries a friend's influence?",
  "Which conversation between friends can quietly change a decision?",
  "How has someone else's confidence helped you recognize your own?",
  "What is one way friends can influence each other without becoming alike?",
  "Which of your habits might tell the story of people you have known?",
  "How do you decide which influences to welcome and which to question?",
  "What has a friend's different viewpoint made more interesting to you?",
  "Where do you see traces of shared experiences in the person you are now?",
  "What kind of influence feels supportive rather than controlling?",
  "How has this friendship affected the way you enter new social spaces?",
  "Which strength in another person has helped you name a strength in yourself?",
  "What part of your outlook has been widened by your friendships?",
  "How have friends helped you experiment with a new version of yourself?",
  "Which choice of yours was clarified by a friend's thoughtful question?",
  "What influence do you hope to have on the people who know you?",
  "How can friends challenge each other while leaving room for autonomy?",
  "What have you learned by seeing yourself through a friend's generous eyes?",
  "Which everyday expression or ritual did you absorb from someone close to you?",
  "How might your life be different if a particular friendship had never crossed your path?",
  "What has a friend's example taught you without requiring a conversation?",
  "Which part of your courage has been strengthened by companionship?",
  "How do you keep mutual influence from turning into unspoken pressure?",
  "How do you recognize when effort in a friendship feels mutual enough?",
  "What forms of care are easiest for you to offer consistently?",
  "Which kind of contribution to friendship often goes unnoticed?",
  "How can two friends give differently without keeping score?",
  "What makes an exchange of support feel balanced to you?",
  "Where do you prefer clear requests over guessing what a friend needs?",
  "How do you respond when a friend offers more help than you can return right away?",
  "What does shared responsibility look like in maintaining a connection?",
  "Which friendship tasks are worth discussing instead of leaving implicit?",
  "How do you know when generosity is freely chosen rather than expected?",
  "What can reciprocity look like when two friends have very different resources?",
  "Where might appreciation matter more than matching an effort exactly?",
  "How do you make receiving care comfortable for both people?",
  "What encourages you to initiate plans instead of waiting to be invited?",
  "Which signs tell you a friend is invested even when they are busy?",
  "How can friends acknowledge an imbalance without turning it into a debt?",
  "What kind of follow-through helps you trust a friendship?",
  "Where does flexibility belong in your idea of mutual effort?",
  "What invitation would help a friend tell you when they are carrying too much?",
  "What makes asking for a small favor feel safe in a friendship?",
  "Which gestures help a friendship feel like a shared creation?",
  "How do different communication styles complicate the idea of equal effort?",
  "What is a fair way to navigate seasons when one friend has less capacity?",
  "Where have you learned to accept care without immediately repaying it?",
  "How can friends celebrate each other's contributions without comparing them?",
  "What tells you that mutuality is present beneath different outward styles?",
  "Which responsibility for a healthy friendship belongs to each person individually?",
  "How have your boundaries made friendship clearer or kinder?",
  "What helps you hear a friend's limit without taking it as rejection?",
  "Which boundary is easiest to respect once you understand its purpose?",
  "How do you prefer a friend to check before offering advice?",
  "What does a comfortable amount of access to your time look like these days?",
  "Where could saying no protect the quality of a friendship?",
  "How can friends make room for privacy without creating suspicion?",
  "What signals help you know a topic is better left for another time?",
  "Which expectation is healthier when it is spoken aloud?",
  "How do you distinguish needing space from withdrawing care?",
  "What makes a boundary conversation feel collaborative to you?",
  "Where would more notice or planning help you show up willingly?",
  "How can a friend respond well when you change your mind about what feels comfortable?",
  "What does consent look like in everyday friendship decisions?",
  "Which kinds of teasing require the most attention to personal limits?",
  "What response from friends feels respectful when you choose not to answer a question?",
  "What helps boundaries remain flexible without becoming unclear?",
  "Where do digital habits create boundaries that friends may need to discuss?",
  "How might a limit communicate care for both people at once?",
  "What is a respectful way to revisit an agreement that no longer works?",
  "Which boundary do you appreciate even when it is inconvenient?",
  "How do you avoid assuming that one friend's comfort applies to everyone?",
  "What kind of permission makes shared plans feel more considerate?",
  "Where can friends offer an easy way to opt out without awkwardness?",
  "How would you describe the difference between secrecy and privacy?",
  "What helps you state a need before frustration builds?",
  "Which personal limit has taught you something valuable about your capacity?",
  "What makes an apology feel attentive rather than automatic?",
  "How do you prefer to revisit a misunderstanding once emotions settle?",
  "Which part of repair often takes longer than the initial conversation?",
  "What helps you stay curious when you and a friend remember an event differently?",
  "How can friends name impact without deciding each other's intentions?",
  "What role should changed behavior play after an apology?",
  "Where does patience help repair, and where might clarity help more?",
  "What signals tell you a difficult conversation has reached a useful stopping point?",
  "What allows trust to regrow gradually without pretending nothing happened?",
  "Which small action can reopen communication after a minor disconnect?",
  "How can someone take responsibility without speaking for the other person's experience?",
  "What does making amends look like when the original moment cannot be undone?",
  "Where might humor help reconnect, and when might it get in the way?",
  "What approach would feel respectful after a friend notices they crossed a line?",
  "What can both people learn from a conflict that ends without full agreement?",
  "Which sign suggests a repair attempt needs more listening?",
  "How can a friendship move forward while a question remains unresolved?",
  "What would a low-pressure invitation to reconnect sound like?",
  "Where does self-forgiveness fit after you have owned a mistake?",
  "How might friends acknowledge progress without rushing restoration of trust?",
  "What helps you separate one disappointing choice from a person's whole character?",
  "Which repair matters can be handled lightly, and which deserve dedicated time?",
  "How can you honor an apology even if you are not ready for renewed closeness?",
  "What does respectful closure look like when repair does not restore a friendship?",
  "Where could clearer expectations prevent the same friction from returning?",
  "How do you recognize a sincere effort that is imperfectly expressed?",
  "What could make disagreement feel less like a threat to connection?",
  "Which parts of yourself feel easier to express in friendship than elsewhere?",
  "How have friends reflected back an identity you were still discovering?",
  "What role does friendship play in reminding you who you are beyond your work?",
  "Where do you feel free to be unfinished around other people?",
  "How can a friend support your self-definition without labeling you?",
  "Which version of yourself appears when you feel socially at ease?",
  "What have friendships taught you about belonging without blending in?",
  "How do you stay connected to yourself while adapting to a group?",
  "What part of your identity has friendship given more room to explore?",
  "Where do friends help you notice that you have outgrown an old role?",
  "How can someone affirm you without claiming to know you completely?",
  "Which qualities feel more visible when you are with supportive friends?",
  "What does being known imperfectly but kindly mean to you?",
  "How have different friendships brought out different strengths in you?",
  "Where would you like friends to remain curious instead of making assumptions?",
  "What helps you resist performing a fixed role in a friendship?",
  "Which label about yourself has become less useful over time?",
  "How can friends witness change without constantly comparing you to your past?",
  "What part of yourself are you giving more permission to develop?",
  "Where does playfulness fit into your sense of who you are?",
  "How do friendships contribute to a life story without defining the whole story?",
  "What do you appreciate about friends who let you contradict an earlier version of yourself?",
  "Which social role do you enjoy, and which one drains you?",
  "How can a friendship make room for identities and experiences it does not share?",
  "What feels grounding about being remembered across different chapters of life?",
  "Where has a friend's perception of you been usefully incomplete?",
  "What kind of welcome helps when you are trying something unlike the usual you?",
  "What has a quieter season of friendship helped you appreciate?",
  "How do you decide when to revive a tradition and when to let it rest?",
  "Which kind of closeness works well without frequent conversation?",
  "What helps a friendship survive a season of mismatched schedules?",
  "How can friends acknowledge distance without treating it as failure?",
  "Why can a friendship that resumes without pretending time stood still feel valuable?",
  "Where has less contact created room for a different kind of connection?",
  "What response from friends helps when your social energy changes?",
  "Which season of a friendship can be meaningful without being the closest one?",
  "What makes reaching out after a long pause feel welcoming?",
  "How can a friendship remain real when it is no longer central to daily life?",
  "What do changing routines reveal about which connections you want to tend?",
  "Where does nostalgia enrich a friendship, and where can it limit one?",
  "How might two people mark a transition in their friendship with care?",
  "What allows old friends to meet each other as they are now?",
  "Which friendship season taught you to loosen your grip on an outcome?",
  "How can closeness expand and contract without becoming a measure of worth?",
  "What would help you greet a returning friend with curiosity?",
  "Where have you found continuity despite long gaps in contact?",
  "How do you honor what a friendship was without requiring it to stay the same?",
  "What kind of check-in suits a friendship that has become more occasional?",
  "Which signs show that a low-maintenance friendship is still cared for?",
  "How can friends renegotiate closeness after circumstances change?",
  "What does a graceful shift from daily friend to longtime friend look like?",
  "Where might a shared memory act as a bridge rather than an anchor?",
  "What feels fair during seasons when one person reaches out more often?",
  "What can make a brief reunion feel meaningful without creating new obligations?",
  "In what ways has support come to mean more than giving advice?",
  "What kind of presence helps you feel accompanied without feeling managed?",
  "Where do practical help and emotional support serve different needs?",
  "How can a friend ask what would help without assuming an answer?",
  "Which forms of encouragement feel believable to you?",
  "What role can friendship play alongside family, community, and professional support?",
  "What helps you choose between listening, helping, and giving space?",
  "What makes a support network resilient instead of dependent on one person?",
  "Where could you diversify the kinds of support available in your life?",
  "How can friends care deeply without becoming responsible for fixing everything?",
  "What helps you direct a friend toward additional support with respect?",
  "Which kind of check-in feels caring during a demanding week?",
  "How do you communicate that you have limited capacity while still showing concern?",
  "What can a group of friends provide that one close friend cannot?",
  "Where have acquaintances or community ties offered unexpected steadiness?",
  "How can friends support a decision they would not make themselves?",
  "What kind of companionship makes an ordinary task feel lighter?",
  "Which offers of help are easiest for you to respond to honestly?",
  "How might friends coordinate care without speaking over the person being supported?",
  "What does dependable support look like when circumstances are unpredictable?",
  "Where is encouragement more useful than problem-solving?",
  "How do you want someone to follow up after you have shared a concern?",
  "What helps support feel dignifying rather than pitying?",
  "Which community spaces have the potential to deepen your sense of connection?",
  "How can you appreciate a friend's care while declining their suggestion?",
  "What would make asking your wider circle for help feel more manageable?",
  "Where do shared activities provide support without requiring a serious conversation?",
  "What small detail about the way a friend shows up deserves more appreciation?",
  "How has being remembered in an ordinary moment mattered to you?",
  "Which quality in this friendship would you like to name while you can?",
  "What are you grateful this friendship has made easier to enjoy?",
  "How do you prefer appreciation to be expressed between friends?",
  "What shared effort are you glad neither of you had to make alone?",
  "Which part of a friend's growth is meaningful for you to witness?",
  "How can gratitude be specific without becoming sentimental or pressured?",
  "What ordinary memory captures something you value about your connection?",
  "Where have you felt quietly considered by a friend?",
  "What do you admire about the way your friend relates to other people?",
  "How has a friendship added texture to a routine part of life?",
  "Which difference between you has become something you appreciate?",
  "What contribution from a friend would you like to recognize more clearly?",
  "How do shared jokes or references help a friendship feel lived-in?",
  "What are you thankful to have learned alongside another person?",
  "Which moment of ordinary reliability stands out when you look back?",
  "How has a friend made room for you without making a show of it?",
  "What part of your shared history feels especially worth honoring?",
  "Where has a friend's honesty been a form of respect?",
  "How can appreciation remain present even if a friendship changes direction?",
  "Why does not being responsible for completing each other matter in friendship?",
  "Which act of flexibility has made spending time together easier?",
  "How might you celebrate the friendship without defining what comes next?",
  "What has a friend noticed about you that made you feel encouraged?",
  "Where do you see care expressed through attention rather than words?",
  "How has this friendship made a particular chapter more vivid?",
  "What kind of future contact would feel realistic and welcome to you?",
  "How can friends talk about the future while leaving room for changing circumstances?",
  "Which shared possibility would be enjoyable to explore without turning it into an obligation?",
  "What would help your friendship stay adaptable over the next few years?",
  "How might you keep a connection warm when plans remain uncertain?",
  "Where would a simple future ritual add joy without creating pressure?",
  "What kind of invitation gives you genuine freedom to say yes, no, or later?",
  "How do you imagine supporting each other's goals without directing them?",
  "Which future change would be easier to navigate with an honest conversation?",
  "What would make room for both spontaneity and reliability in your plans?",
  "How can a friendship hold hope without relying on a fixed timeline?",
  "Where might you choose quality of contact over frequency?",
  "What new context could let you discover another side of your friendship?",
  "How would you like to approach future differences in availability?",
  "Which tradition could remain optional and still feel meaningful?",
  "What does staying in touch mean when life becomes fuller?",
  "How can friends make plans that account for unequal time, money, or energy?",
  "What would you like to remain open to learning about each other?",
  "Where could clearer communication make future plans feel lighter?",
  "How might you encourage each other's independence as well as connection?",
  "What kind of shared project could suit the people you are now?",
  "Which assumption about your future friendship would be helpful to release?",
  "How can you express a wish for connection without turning it into a demand?",
  "What would a flexible version of a long-distance friendship look like?",
  "Where could you build more room for last-minute changes without resentment?",
  "What response would honor the friendship if your paths lead in different directions?",
  "What future conversation would be worth revisiting when the timing is right?",
  "Which qualities could help your friendship adapt to whatever comes next?",
  "How might you preserve goodwill even if contact becomes less frequent?",
  "What intention for your friendships feels both meaningful and possible?",
] as const satisfies readonly string[]
