export const TAKE_SIP_DRINKING = [
  "Take a sip if you chose an alcohol-free drink because it sounded genuinely delicious.",
  "Take a sip if you have ever brought your own favorite soft drink to a gathering.",
  "Take a sip if a zero-proof menu made you feel thoughtfully included.",
  "Take a sip if you have ever ordered a mocktail without needing to explain why.",
  "Take a sip if sparkling water is your celebration drink of choice.",
  "Take a sip if you have ever discovered a great alcohol-free beer.",
  "Take a sip if you would happily toast with tea.",
  "Take a sip if fruit garnish makes any drink feel more festive to you.",
  "Take a sip if you have ever chosen hot chocolate at a grown-up gathering.",
  "Take a sip if your ideal party drink involves fresh citrus.",
  "Take a sip if you have ever enjoyed a zero-proof pairing with dinner.",
  "Take a sip if you appreciate menus that list non-alcoholic options first.",
  "Take a sip if you have ever made an elaborate mocktail at home.",
  "Take a sip if a beautiful glass makes your alcohol-free drink feel special.",
  "Take a sip if you have ever swapped a cocktail recommendation for a mocktail recommendation.",
  "Take a sip if ginger beer is a reliable favorite for you.",
  "Take a sip if you have ever celebrated with fresh juice.",
  "Take a sip if you like trying unusual soda flavors at social events.",
  "Take a sip if you have ever asked a bartender to improvise something alcohol-free.",
  "Take a sip if you prefer your drink menu to include clear alcohol-free labels.",
  "Take a sip if you have ever served a signature mocktail at a party.",
  "Take a sip if you think lemonade belongs at more celebrations.",
  "Take a sip if you have ever picked a drink mainly because it came with mint.",
  "Take a sip if you enjoy matching an alcohol-free drink to the season.",
  "Take a sip if you have ever toasted with coffee.",
  "Take a sip if you keep a favorite zero-proof recipe ready for guests.",
  "Take a sip if you have ever chosen kombucha for a special occasion.",
  "Take a sip if you believe mocktails deserve names as fun as cocktails.",
  "Take a sip if you have ever found your new favorite drink on the alcohol-free page.",
  "Take a sip if you would choose a fancy iced tea from a tasting menu.",
  "Take a sip if you remembered to have water nearby before the gathering began.",
  "Take a sip if you have ever ordered water alongside another beverage.",
  "Take a sip if a host offered water before anyone had to ask.",
  "Take a sip if you appreciate a clearly marked water station at an event.",
  "Take a sip if you have ever refilled a friend's water glass after checking first.",
  "Take a sip if you brought a reusable water bottle to an outdoor celebration.",
  "Take a sip if you have ever taken a refreshment break to enjoy the conversation.",
  "Take a sip if you like alternating beverage flavors throughout an evening.",
  "Take a sip if you have ever chosen water because it was exactly what you wanted.",
  "Take a sip if you appreciate bartenders who serve water without making it awkward.",
  "Take a sip if you have ever added cucumber or citrus to party water.",
  "Take a sip if a chilled water pitcher is part of your hosting setup.",
  "Take a sip if you have ever reminded yourself that there is no rush.",
  "Take a sip if you prefer lingering over one good conversation to chasing the next activity.",
  "Take a sip if you have ever paused to actually notice a drink's aroma.",
  "Take a sip if you enjoy letting ice melt while you talk.",
  "Take a sip if you have ever set your glass down because the story was too interesting.",
  "Take a sip if you like social plans with plenty of unhurried time.",
  "Take a sip if you have ever switched to water and stayed for the fun.",
  "Take a sip if you appreciate friends who never comment on what is in your glass.",
  "Take a sip if you have ever taken a quiet breather during a busy party.",
  "Take a sip if you enjoy a gathering more when nobody treats drinking as the main event.",
  "Take a sip if you have ever left a beverage unfinished without giving it a second thought.",
  "Take a sip if you prefer savoring flavors to keeping pace with anyone else.",
  "Take a sip if you have ever asked for a serving style that suited you.",
  "Take a sip if you like knowing an alcohol-free option is always available.",
  "Take a sip if you have ever stayed on the same drink while everyone else changed orders.",
  "Take a sip if you value being able to pause a game whenever you want.",
  "Take a sip if you have ever enjoyed the music while your drink waited on the table.",
  "Take a sip if your best nights include plenty of time to catch up.",
  "Take a sip if you made sure to eat before heading to a social event.",
  "Take a sip if the snacks were secretly your favorite part of a party.",
  "Take a sip if you have ever planned a cheese board with everyone in mind.",
  "Take a sip if you appreciate a bar that serves genuinely good food.",
  "Take a sip if you have ever paired a beverage with your favorite comfort food.",
  "Take a sip if late-night fries have rescued the mood at a gathering.",
  "Take a sip if you have ever brought a dish that accommodated a guest's dietary needs.",
  "Take a sip if you think every tasting should include something good to eat.",
  "Take a sip if you have ever chosen the venue based on its snack menu.",
  "Take a sip if a bowl of popcorn makes a casual drink feel like an occasion.",
  "Take a sip if you have ever asked about allergens before serving party food.",
  "Take a sip if you prefer gatherings where the meal gets equal billing.",
  "Take a sip if you have ever discovered a surprising food-and-drink pairing.",
  "Take a sip if you believe good bread improves almost any tasting.",
  "Take a sip if you have ever made sure the designated driver got first choice of dessert.",
  "Take a sip if you enjoy building a snack plate more than choosing a beverage.",
  "Take a sip if you have ever brought extra nibbles for an unexpectedly large group.",
  "Take a sip if your hosting style includes food labels for guests.",
  "Take a sip if you have ever turned leftovers into the highlight of the evening.",
  "Take a sip if you think olives count as essential bar snacks.",
  "Take a sip if you have ever coordinated a potluck around a tasting theme.",
  "Take a sip if you appreciate a host who checks that everyone has eaten.",
  "Take a sip if you have ever chosen a hearty appetizer as the star of your order.",
  "Take a sip if a shared plate has ever started a new friendship.",
  "Take a sip if you have ever recreated a restaurant snack at home.",
  "Take a sip if you believe birthday cake pairs with every beverage.",
  "Take a sip if you have ever kept simple snacks available for drop-in guests.",
  "Take a sip if you judge a pub partly by the quality of its chips.",
  "Take a sip if you have ever served breakfast food at an evening gathering.",
  "Take a sip if the phrase 'snacks provided' makes an invitation more appealing.",
  "Take a sip if you agreed on a designated driver before making plans.",
  "Take a sip if you have ever volunteered to drive and enjoyed the night anyway.",
  "Take a sip if your group has a reliable ride-home chat.",
  "Take a sip if you have ever booked a cab before leaving home.",
  "Take a sip if you appreciate events that share transport information in advance.",
  "Take a sip if you have ever walked to a neighborhood gathering with friends.",
  "Take a sip if you chose a venue because public transport made it easy for everyone.",
  "Take a sip if you have ever offered a guest the sofa rather than let them travel unsafely.",
  "Take a sip if you keep a local taxi number saved for social nights.",
  "Take a sip if you have ever checked that a friend got home safely.",
  "Take a sip if your evening plan included the last train time.",
  "Take a sip if you have ever shared a ride with friends after a celebration.",
  "Take a sip if you appreciate venues with a safe pickup point.",
  "Take a sip if you have ever changed plans because the journey home was simpler.",
  "Take a sip if you believe the best designated driver gets control of the playlist.",
  "Take a sip if you have ever thanked someone for being the sober driver.",
  "Take a sip if you planned a celebration within walking distance of home.",
  "Take a sip if you have ever arranged a guest room before hosting a party.",
  "Take a sip if you include ride costs when budgeting for a night out.",
  "Take a sip if you have ever waited indoors with a friend until their ride arrived.",
  "Take a sip if your group confirms transport plans before ordering anything.",
  "Take a sip if you have ever taken the scenic bus ride home after a lovely evening.",
  "Take a sip if you appreciate a host who helps guests find safe transport.",
  "Take a sip if you have ever picked a daytime venue for easier travel.",
  "Take a sip if you know which friend always remembers the train schedule.",
  "Take a sip if you have ever used a ride-share split feature after dinner.",
  "Take a sip if you consider accessibility when choosing transport for the group.",
  "Take a sip if you have ever sent directions to the pickup spot before the event.",
  "Take a sip if your safest journey home became part of a funny story.",
  "Take a sip if you have ever chosen the closer bar because nobody wanted a complicated trip.",
  "Take a sip if you have ever made a toast that was shorter than everyone expected.",
  "Take a sip if a heartfelt toast has ever made you tear up.",
  "Take a sip if you have ever raised a glass to an achievement that took years.",
  "Take a sip if you prefer spontaneous toasts to formal speeches.",
  "Take a sip if you have ever toasted with whatever beverage was already in your hand.",
  "Take a sip if a wedding toast taught you something new about the couple.",
  "Take a sip if you have ever practiced a toast in the mirror.",
  "Take a sip if your favorite toast included a perfectly timed joke.",
  "Take a sip if you have ever used a favorite mug for a celebratory toast.",
  "Take a sip if you believe eye contact makes a toast feel warmer.",
  "Take a sip if you have ever toasted someone who joined by video call.",
  "Take a sip if a retirement toast has ever made the whole room laugh.",
  "Take a sip if you have ever forgotten your prepared toast and spoken from the heart.",
  "Take a sip if you appreciate a toast that includes the quiet contributors.",
  "Take a sip if you have ever celebrated good news with an impromptu kitchen toast.",
  "Take a sip if you have a family toast that appears at every holiday.",
  "Take a sip if you have ever translated a toast for someone at the table.",
  "Take a sip if you think a sincere sentence can beat a long speech.",
  "Take a sip if you have ever marked a fresh start with a toast.",
  "Take a sip if a toast has ever turned strangers into a group.",
  "Take a sip if you have ever volunteered to speak when nobody else would.",
  "Take a sip if you enjoy hearing celebration traditions from other cultures.",
  "Take a sip if you have ever toasted a friend who was not in the room.",
  "Take a sip if your group has a delightfully silly toast.",
  "Take a sip if you have ever written a toast on a napkin moments before giving it.",
  "Take a sip if you appreciate when a toast welcomes non-drinkers explicitly.",
  "Take a sip if you have ever celebrated teamwork with your whole group.",
  "Take a sip if a birthday toast has ever revealed an excellent old story.",
  "Take a sip if you have ever toasted an ordinary day that deserved celebrating.",
  "Take a sip if you believe every valid beverage belongs in a toast.",
  "Take a sip if you have ever attended a tasting led by someone wonderfully enthusiastic.",
  "Take a sip if you enjoy identifying aromas even when your guess is completely wrong.",
  "Take a sip if a tasting note has ever sounded more like poetry than description.",
  "Take a sip if you have ever learned the story behind a local beverage.",
  "Take a sip if you prefer tasting flights that include alcohol-free selections.",
  "Take a sip if you have ever compared the same style from different regions.",
  "Take a sip if a surprising flavor changed your mind about a drink.",
  "Take a sip if you have ever taken notes during a tasting for fun.",
  "Take a sip if you enjoy hearing how ingredients are grown or sourced.",
  "Take a sip if you have ever visited a brewery, winery, roastery, or tea garden.",
  "Take a sip if the glassware lesson was your favorite part of a tasting.",
  "Take a sip if you have ever recognized a flavor only after someone named it.",
  "Take a sip if you appreciate a tasting host who welcomes beginners.",
  "Take a sip if you have ever preferred the least expensive sample.",
  "Take a sip if a blind tasting result has ever surprised you.",
  "Take a sip if you like learning why temperature changes flavor.",
  "Take a sip if you have ever shared a tasting discovery with the whole table.",
  "Take a sip if you prefer curious questions to pretending expertise.",
  "Take a sip if you have ever attended a coffee cupping.",
  "Take a sip if a tea tasting introduced you to a new favorite.",
  "Take a sip if you enjoy comparing different kinds of sparkling water.",
  "Take a sip if you have ever tried a beverage made with an unfamiliar herb.",
  "Take a sip if the production process interests you as much as the flavor.",
  "Take a sip if you have ever bought a bottle because its maker told a great story.",
  "Take a sip if you appreciate tasting rooms that provide clear ingredient information.",
  "Take a sip if you have ever learned a useful pronunciation at a tasting.",
  "Take a sip if you like keeping your own opinions before hearing the official notes.",
  "Take a sip if you have ever tasted something that reminded you of a specific place.",
  "Take a sip if you enjoy a guided tasting more when questions are encouraged.",
  "Take a sip if you have ever discovered that your palate changed over time.",
  "Take a sip if you have ever found a neighborhood bar that felt instantly welcoming.",
  "Take a sip if a bartender remembered your usual alcohol-free order.",
  "Take a sip if you have ever chosen the quiet corner of a busy pub.",
  "Take a sip if live music introduced you to a venue you now love.",
  "Take a sip if you have ever made friends during a pub quiz.",
  "Take a sip if your favorite bar has unusually good lighting.",
  "Take a sip if you have ever gone to a rooftop bar mainly for the view.",
  "Take a sip if a cozy booth is your preferred seat.",
  "Take a sip if you appreciate a menu that explains unfamiliar ingredients.",
  "Take a sip if you have ever asked for the music to be turned down politely.",
  "Take a sip if you know a bar with an excellent board-game shelf.",
  "Take a sip if you have ever enjoyed people-watching from a window seat.",
  "Take a sip if you prefer a venue where conversation is easy.",
  "Take a sip if a pub garden has ever improved your entire afternoon.",
  "Take a sip if you have ever attended a poetry night at a bar.",
  "Take a sip if a bartender's recommendation matched your taste perfectly.",
  "Take a sip if you have ever picked a venue because it was accessible to everyone.",
  "Take a sip if your local has a resident pet or mascot.",
  "Take a sip if you have ever stayed for the trivia even after your team fell behind.",
  "Take a sip if you appreciate table service that never feels rushed.",
  "Take a sip if you have ever met a friend for an early-evening catch-up.",
  "Take a sip if you know a venue with a memorable sign outside.",
  "Take a sip if you have ever found an unexpectedly peaceful hotel bar.",
  "Take a sip if you prefer sitting at the bar where you can watch drinks being made.",
  "Take a sip if a restaurant lounge has ever become your regular meeting place.",
  "Take a sip if you have ever complimented a bartender on a creative mocktail.",
  "Take a sip if you appreciate venues that make it easy to hear your name or order number.",
  "Take a sip if you have ever joined a community event hosted by a local pub.",
  "Take a sip if your favorite venue has a surprisingly beautiful restroom.",
  "Take a sip if you have ever left a positive review for especially thoughtful service.",
  "Take a sip if you have ever hosted a gathering where everyone chose their own beverage.",
  "Take a sip if you put alcohol-free options on equal display with everything else.",
  "Take a sip if you have ever labeled homemade syrups or mixers for guests.",
  "Take a sip if your party invitation mentioned that not drinking was completely normal.",
  "Take a sip if you have ever chilled extra water before guests arrived.",
  "Take a sip if you keep enough clean glasses ready for surprise visitors.",
  "Take a sip if you have ever asked guests about preferences before shopping.",
  "Take a sip if your best hosting trick is a self-serve drink station.",
  "Take a sip if you have ever made ice in a shape that matched the theme.",
  "Take a sip if you enjoy choosing music for a relaxed dinner party.",
  "Take a sip if you have ever offered take-home containers after a gathering.",
  "Take a sip if you always make room in the fridge before hosting.",
  "Take a sip if you have ever borrowed extra chairs from a neighbor.",
  "Take a sip if your guests have helped turn cleanup into part of the fun.",
  "Take a sip if you have ever hosted on a balcony, patio, or shared courtyard.",
  "Take a sip if you prefer a casual open-house format to a formal party.",
  "Take a sip if you have ever planned an activity that did not revolve around drinks.",
  "Take a sip if you keep coasters where people can actually find them.",
  "Take a sip if you have ever created a menu card for a home gathering.",
  "Take a sip if you enjoy sending guests home with leftover garnish.",
  "Take a sip if you have ever hosted a themed tea or coffee evening.",
  "Take a sip if you make sure guests know they can change their drink choice anytime.",
  "Take a sip if you have ever set aside a quiet space at a lively party.",
  "Take a sip if you think good hosting means noticing who needs an introduction.",
  "Take a sip if you have ever supplied blankets for an outdoor gathering.",
  "Take a sip if your party planning includes a clear finish time.",
  "Take a sip if you have ever arranged accessible seating before guests arrived.",
  "Take a sip if you prefer reusable cups and plates when practical.",
  "Take a sip if you have ever sent transport options with the invitation.",
  "Take a sip if you believe a warm welcome matters more than perfect decorations.",
  "Take a sip if you have ever declined a drink offer and heard a simple no problem in reply.",
  "Take a sip if you have ever made someone feel welcome without asking what they were drinking.",
  "Take a sip if you appreciate friends who accept a change of mind immediately.",
  "Take a sip if you have ever offered choices without recommending one as the grown-up option.",
  "Take a sip if you believe nobody owes the room an explanation for their beverage.",
  "Take a sip if you have ever redirected a conversation away from someone's choice not to drink.",
  "Take a sip if a host remembered your dietary or sensory needs.",
  "Take a sip if you have ever checked whether a game felt comfortable for everyone.",
  "Take a sip if your group treats skipping a card as completely ordinary.",
  "Take a sip if you have ever suggested a non-drinking activity during a night out.",
  "Take a sip if you appreciate invitations that describe the venue's accessibility.",
  "Take a sip if you have ever chosen a quieter table for a friend who needed it.",
  "Take a sip if you have ever used someone's chosen name correctly in a toast.",
  "Take a sip if your social circle celebrates people who leave when they are ready.",
  "Take a sip if you have ever asked before topping up someone else's glass.",
  "Take a sip if you believe hospitality includes respecting an untouched drink.",
  "Take a sip if you have ever defended a friend's alcohol-free order from teasing.",
  "Take a sip if you appreciate games that let every player choose their own substitute.",
  "Take a sip if you have ever made room at the table for a late arrival.",
  "Take a sip if a gathering introduced you to a tradition different from your own.",
  "Take a sip if you have ever checked how to pronounce a guest's name before a celebration.",
  "Take a sip if you value hosts who state that participation is optional.",
  "Take a sip if you have ever changed a plan so a pregnant guest felt fully included.",
  "Take a sip if you appreciate alcohol-free events that still feel festive.",
  "Take a sip if you have ever welcomed someone who arrived alone into your group.",
  "Take a sip if you believe a good party has more than one way to join the fun.",
  "Take a sip if you have ever offered a menu instead of guessing someone's preferences.",
  "Take a sip if your friends respect medications and health choices without questions.",
  "Take a sip if you have ever celebrated a milestone without centering alcohol.",
  "Take a sip if you have ever thanked a friend for making every beverage choice feel ordinary.",
  "Take a sip if you have ever spilled a drink and saved the table with a stack of napkins.",
  "Take a sip if a runaway ice cube has ever crossed the room.",
  "Take a sip if you have ever worn a splash from an overenthusiastic toast.",
  "Take a sip if you have ever mistaken the garnish for a snack.",
  "Take a sip if a paper straw has ever surrendered before your drink was finished.",
  "Take a sip if you have ever ordered something mainly because its name made you laugh.",
  "Take a sip if you have ever tried to open the wrong side of a bottle cap.",
  "Take a sip if a fizzy drink has ever surprised you on opening.",
  "Take a sip if you have ever carried too many empty glasses in one trip.",
  "Take a sip if your coaster has ever traveled with the glass.",
  "Take a sip if you have ever discovered your drink was on the other side of the table.",
  "Take a sip if you have ever clinked glasses so gently that they barely met.",
  "Take a sip if you have ever posed for a photo while still holding the menu.",
  "Take a sip if your garnish has ever been larger than expected.",
  "Take a sip if you have ever stirred a drink with the wrong end of a spoon.",
  "Take a sip if you have ever confidently picked up someone else's identical glass, then swapped back.",
  "Take a sip if a drink umbrella has ever ended up in your hair.",
  "Take a sip if you have ever forgotten to remove a tea bag before serving the cup.",
  "Take a sip if you have ever made ice cubes that refused to leave the tray.",
  "Take a sip if a blender lid taught you an unforgettable kitchen lesson.",
  "Take a sip if you have ever dripped condensation onto an important piece of paper.",
  "Take a sip if a cork has ever broken while you were opening a bottle.",
  "Take a sip if you have ever poured a drink that looked nothing like the recipe photo.",
  "Take a sip if you have ever served two guests matching glasses and immediately lost track.",
  "Take a sip if a foam moustache has ever appeared at the perfect photo moment.",
  "Take a sip if you have ever waved with the hand holding your drink and instantly regretted it.",
  "Take a sip if you have ever put a glass somewhere sensible and then searched everywhere for it.",
  "Take a sip if your homemade garnish has ever sunk straight to the bottom.",
  "Take a sip if you have ever laughed hard enough to need to set your drink down.",
  "Take a sip if a harmless drink mishap became the story everyone remembered.",
] as const satisfies readonly string[];
