export const TAKE_SIP_FUNNY: readonly string[] = [
  "Take a sip if you have worn a shirt inside out without noticing.",
  "Take a sip if you have searched for glasses that were on your head.",
  "Take a sip if you have put two different socks on by accident.",
  "Take a sip if you have started a story and forgotten the ending.",
  "Take a sip if you have opened a cupboard and forgotten why.",
  "Take a sip if you have checked the time and immediately forgotten it.",
  "Take a sip if you have carried an umbrella all day without using it.",
  "Take a sip if you have left home and returned for something essential.",
  "Take a sip if you have looked for an item while holding it.",
  "Take a sip if entering a room has erased your memory of the mission.",
  "Take a sip if you have forgotten a word and replaced it with sound effects.",
  "Take a sip if you have confidently used the wrong day of the week.",
  "Take a sip if you have written a reminder and then misplaced it.",
  "Take a sip if you have packed everything except the thing you needed most.",
  "Take a sip if you have forgotten why an alarm was ringing.",
  "Take a sip if you have reheated a drink and abandoned it again.",
  "Take a sip if you have worn slippers farther from home than intended.",
  "Take a sip if you have carried an empty bag around all day.",
  "Take a sip if you have forgotten a familiar route for one confusing second.",
  "Take a sip if you have put something safe somewhere too safe to find.",
  "Take a sip if you have mixed up the names of two everyday objects.",
  "Take a sip if you have reached for a pocket that your outfit did not have.",
  "Take a sip if you have forgotten what you were saying mid-sentence.",
  "Take a sip if you have arrived early because you remembered the wrong time.",
  "Take a sip if you have carried a shopping list and never looked at it.",
  "Take a sip if you have put a household item in a very unexpected place.",
  "Take a sip if you have forgotten a login phrase immediately after resetting it.",
  "Take a sip if you have gone back to check a door you already locked.",
  "Take a sip if you have called an object by the name of a different object.",
  "Take a sip if you have remembered an important detail just after sitting down.",

  "Take a sip if autocorrect has made your harmless message sound dramatic.",
  "Take a sip if you have joined a video call with the wrong background.",
  "Take a sip if you have spoken while your microphone was muted.",
  "Take a sip if you have accidentally turned on a camera filter.",
  "Take a sip if you have refreshed a page that was still loading.",
  "Take a sip if you have unplugged the wrong charger from a crowded outlet.",
  "Take a sip if you have tapped a screen that was not a touchscreen.",
  "Take a sip if you have taken a screenshot while trying to change the volume.",
  "Take a sip if you have watched a video with no sound before noticing.",
  "Take a sip if you have typed a reply and forgotten to send it.",
  "Take a sip if you have opened the calculator for extremely simple arithmetic.",
  "Take a sip if you have blamed the internet before checking your own settings.",
  "Take a sip if you have used a flashlight to search for your phone.",
  "Take a sip if you have closed the tab you actually needed.",
  "Take a sip if you have created a new document and left it named Untitled.",
  "Take a sip if you have watched the typing indicator and received no message.",
  "Take a sip if you have answered a call with an unexpectedly strange greeting.",
  "Take a sip if you have forgotten which device was making a notification sound.",
  "Take a sip if you have tried the same incorrect login phrase several times.",
  "Take a sip if you have accidentally zoomed in so far that a webpage looked enormous.",
  "Take a sip if you have opened an app and immediately forgotten your purpose.",
  "Take a sip if you have charged a device without switching on the outlet.",
  "Take a sip if you have sent a voice note with a long silent ending.",
  "Take a sip if you have searched online for a website already open in another tab.",
  "Take a sip if you have mistaken an advertisement button for the real button.",
  "Take a sip if you have waved at your own tiny video-call preview.",
  "Take a sip if you have rotated your phone and made the screen turn the wrong way.",
  "Take a sip if you have accidentally paused music at the best part.",
  "Take a sip if you have watched a download bar before noticing it had not started.",
  "Take a sip if you have tried to unlock the wrong device with complete confidence.",

  "Take a sip if you have dropped food and caught everything except the food.",
  "Take a sip if you have made a snack while waiting for another snack.",
  "Take a sip if you have burned toast while standing beside the toaster.",
  "Take a sip if you have opened a fizzy drink and instantly regretted shaking it.",
  "Take a sip if you have mistaken salt for sugar during a harmless kitchen moment.",
  "Take a sip if you have eaten the garnish before realizing it was decoration.",
  "Take a sip if you have cooked enough pasta for a surprise crowd.",
  "Take a sip if you have cut a sandwich unevenly and chosen the larger half.",
  "Take a sip if you have found a mystery container at the back of the fridge.",
  "Take a sip if you have spilled one ingredient immediately after cleaning the counter.",
  "Take a sip if you have used the wrong lid on every container before finding the right one.",
  "Take a sip if you have waited for an oven that was never switched on.",
  "Take a sip if you have taken a bite before the food was cool enough.",
  "Take a sip if you have planned a balanced meal and ended up eating cereal.",
  "Take a sip if you have opened the fridge repeatedly hoping new food would appear.",
  "Take a sip if you have made a recipe and forgotten one harmless ingredient.",
  "Take a sip if one trip has seemed sufficient for an unreasonable number of snacks.",
  "Take a sip if you have eaten something directly over the sink to avoid a plate.",
  "Take a sip if you have saved the best bite for last and then dropped it.",
  "Take a sip if you have ordered food and immediately wanted what someone else chose.",
  "Take a sip if you have used a mug because every clean glass was unavailable.",
  "Take a sip if you have discovered your takeaway sauce after finishing the meal.",
  "Take a sip if you have made tea or coffee and forgotten to drink it while warm.",
  "Take a sip if you have overfilled a wrap and watched it become a salad.",
  "Take a sip if you have opened a snack quietly and somehow made maximum noise.",
  "Take a sip if you have followed a recipe loosely and called the result experimental.",
  "Take a sip if you have chosen the perfect fruit only to find it was not ready.",
  "Take a sip if you have balanced a spoon on a bowl and watched it fall in.",
  "Take a sip if you have forgotten which cup was yours at a gathering.",
  "Take a sip if you have prepared dipping sauce and then forgotten to use it.",

  "Take a sip if you have greeted someone and realized they were greeting the person behind you.",
  "Take a sip if you have introduced yourself twice to the same person.",
  "Take a sip if you have started a handshake when the other person offered a wave.",
  "Take a sip if you have answered a rhetorical question as though it needed details.",
  "Take a sip if you have laughed because everyone else laughed and missed the joke.",
  "Take a sip if you have entered a conversation just as everyone stopped talking.",
  "Take a sip if you have said goodbye and then walked in the same direction.",
  "Take a sip if you have responded to a compliment with an accidental fun fact.",
  "Take a sip if you have told a story to someone who was already there when it happened.",
  "Take a sip if you have misheard a question and given a wonderfully unrelated answer.",
  "Take a sip if your outfit has been much fancier than an event required.",
  "Take a sip if an event has turned out to be far dressier than your outfit.",
  "Take a sip if you have forgotten how you know someone while chatting with them.",
  "Take a sip if you have joined a group photo without knowing where to look.",
  "Take a sip if you have held a door for someone who was still very far away.",
  "Take a sip if you have mistaken a stranger for someone you know from behind.",
  "Take a sip if you have made a joke and needed to explain it immediately.",
  "Take a sip if you have clapped because one other person started clapping.",
  "Take a sip if you have replied to a group question that was aimed at someone else.",
  "Take a sip if you have walked away before realizing a conversation was not finished.",
  "Take a sip if you have nodded along before realizing you heard the question incorrectly.",
  "Take a sip if you have forgotten whether you already thanked someone.",
  "Take a sip if you have chosen a seat and then learned it was unofficially reserved.",
  "Take a sip if you have tried to whisper and produced a stage whisper.",
  "Take a sip if you have repeated a comment because nobody heard it the first time.",
  "Take a sip if you have been surprised by your own voice in a quiet room.",
  "Take a sip if you have ended a message with a sign-off that was much too formal.",
  "Take a sip if you have forgotten the point of a story while everyone was listening.",
  "Take a sip if you have started singing along before realizing you knew the wrong lyrics.",
  "Take a sip if you have offered help and discovered you misunderstood the task.",

  "Take a sip if your fitted sheet has ever won an argument with you.",
  "Take a sip if you have used a chair as a temporary wardrobe for several days.",
  "Take a sip if you have cleaned one room by moving everything into another room.",
  "Take a sip if you have discovered a light switch whose purpose remains mysterious.",
  "Take a sip if you have talked to an appliance as if encouragement would help.",
  "Take a sip if you have opened every drawer except the correct one.",
  "Take a sip if you have hidden clutter before a visitor arrived.",
  "Take a sip if you have owned a box that contained mostly other boxes.",
  "Take a sip if you have started tidying and become distracted by an old object.",
  "Take a sip if you have folded laundry and left it in a neat pile for days.",
  "Take a sip if you have used the last sheet of paper towel without replacing the roll.",
  "Take a sip if you have rearranged a room and immediately missed the old layout.",
  "Take a sip if you have watered a plant and then wondered whether you already did.",
  "Take a sip if you have kept a nearly empty container because it had one use left.",
  "Take a sip if you have stepped around the same object instead of putting it away.",
  "Take a sip if you have found a missing sock inside another piece of laundry.",
  "Take a sip if you have started a small home task that somehow required every tool.",
  "Take a sip if you have mistaken a pile of clean clothes for a pile of dirty clothes.",
  "Take a sip if you have switched off a light and hurried away from the darkness.",
  "Take a sip if you have used an unusual household object as a doorstop.",
  "Take a sip if you have heard a mysterious noise that turned out to be the fridge.",
  "Take a sip if you have found the remote in a place no remote should be.",
  "Take a sip if you have saved a gift bag for an impressively long time.",
  "Take a sip if you have sat down just before remembering a household chore.",
  "Take a sip if you have put fresh bedding on and considered it a major achievement.",
  "Take a sip if you have kept a drawer full of cables for devices you no longer own.",
  "Take a sip if you have swept debris into a pile and forgotten the final step.",
  "Take a sip if you have left one clean dish in the drying rack indefinitely.",
  "Take a sip if you have used a decorative cushion and then carefully restored it.",
  "Take a sip if you have bought storage to organize the storage you already had.",

  "Take a sip if you have stepped onto the wrong escalator and corrected course calmly.",
  "Take a sip if you have waited at the wrong side of a station platform.",
  "Take a sip if you have missed your stop while concentrating on not missing your stop.",
  "Take a sip if you have pressed a crossing button that was already glowing.",
  "Take a sip if you have followed someone who looked like they knew the way.",
  "Take a sip if you have boarded public transport and immediately questioned the direction.",
  "Take a sip if you have offered your ticket to a machine facing the wrong way.",
  "Take a sip if you have walked faster after noticing someone behind you was walking faster.",
  "Take a sip if you have chosen a queue that instantly became the slowest one.",
  "Take a sip if you have let one bus pass and then wondered whether it was yours.",
  "Take a sip if you have forgotten where you parked a bicycle or car.",
  "Take a sip if you have carried a travel card in your hand and still searched for it.",
  "Take a sip if you have taken a scenic detour by complete accident.",
  "Take a sip if you have walked past your destination while checking the map.",
  "Take a sip if you have stood up too early and waited awkwardly for your stop.",
  "Take a sip if you have sat in the one seat directly under a chilly air vent.",
  "Take a sip if you have hurried to catch transport that was not leaving yet.",
  "Take a sip if you have waved thanks toward the front of a bus with no response.",
  "Take a sip if you have used a landmark that no longer exists when giving directions.",
  "Take a sip if you have taken the stairs and raced an elevator in your imagination.",
  "Take a sip if you have realized your headphones were not connected during a commute.",
  "Take a sip if you have stood by a lift before noticing the stairs beside you.",
  "Take a sip if you have joined a queue without knowing what it was for.",
  "Take a sip if you have walked against a crowd and felt like a salmon.",
  "Take a sip if you have reached the front door and searched every pocket for your keys.",
  "Take a sip if you have checked a route after already starting in the opposite direction.",
  "Take a sip if you have picked a shortcut that took longer than the regular route.",
  "Take a sip if you have paused at a crossing while the other signal was green.",
  "Take a sip if you have politely moved aside and accidentally blocked the other side.",
  "Take a sip if you have reached a destination with no memory of the last few turns.",

  "Take a sip if a pet has ignored a new toy in favor of its packaging.",
  "Take a sip if an animal has stared at you while you ate a snack.",
  "Take a sip if a pet has claimed the exact spot where you planned to sit.",
  "Take a sip if you have apologized to an animal for moving past it.",
  "Take a sip if you have held a one-sided conversation with a pet.",
  "Take a sip if an animal has interrupted your photo at the perfect moment.",
  "Take a sip if a pet has reacted suspiciously to an ordinary household object.",
  "Take a sip if you have shown an animal its own reflection for entertainment.",
  "Take a sip if a pet has demanded attention while you were already giving it attention.",
  "Take a sip if you have taken several photos of an animal doing almost nothing.",
  "Take a sip if a pet has fallen asleep in a position that looked impossible.",
  "Take a sip if you have moved carefully to avoid waking a comfortable animal.",
  "Take a sip if an animal has inspected a visitor's belongings like a security officer.",
  "Take a sip if a pet has heard a food wrapper from another room.",
  "Take a sip if you have invented a voice for an animal you know.",
  "Take a sip if a pet has brought you an object with unclear intentions.",
  "Take a sip if you have celebrated when an animal finally looked at the camera.",
  "Take a sip if a pet has chosen your keyboard as a resting place.",
  "Take a sip if an animal has been fascinated by a blank wall.",
  "Take a sip if you have narrated an animal's routine like a documentary.",
  "Take a sip if a pet has made you get up and then taken your warm seat.",
  "Take a sip if you have greeted a neighborhood animal before greeting its person.",
  "Take a sip if a pet has hidden a toy and then asked you to find it.",
  "Take a sip if you have bought an animal accessory mainly because it looked funny.",
  "Take a sip if a pet has watched you clean and immediately created a new mess.",
  "Take a sip if an animal has misunderstood a harmless sneeze.",
  "Take a sip if you have paused a task to admire an animal outside.",
  "Take a sip if a pet has pretended not to hear a familiar instruction.",
  "Take a sip if you have made room for an animal that occupied very little space.",
  "Take a sip if a pet has treated a closed door as a personal mystery.",

  "Take a sip if you have watched one more episode after declaring the previous one last.",
  "Take a sip if you have spent longer choosing a film than watching it.",
  "Take a sip if you have recognized an actor but not remembered where from.",
  "Take a sip if you have paused a show to explain a theory nobody requested.",
  "Take a sip if you have missed a scene while reading subtitles from the previous scene.",
  "Take a sip if you have applauded at home after a fictional performance.",
  "Take a sip if you have guessed a plot twist confidently and been completely wrong.",
  "Take a sip if you have watched the credits hoping for one extra scene.",
  "Take a sip if you have replayed a song because you missed your favorite part.",
  "Take a sip if you have chosen background music and then focused only on the music.",
  "Take a sip if you have quoted a film and received only blank looks.",
  "Take a sip if you have rooted for a minor character more than the main character.",
  "Take a sip if you have read a plot summary and still felt confused.",
  "Take a sip if you have fallen asleep during a film you insisted on choosing.",
  "Take a sip if you have danced during a theme song that did not require dancing.",
  "Take a sip if you have restarted a series because you forgot nearly everything.",
  "Take a sip if you have avoided spoilers with the focus of a movie detective.",
  "Take a sip if you have watched a cooking show while eating a very simple snack.",
  "Take a sip if you have sung an instrumental part because you did not know the words.",
  "Take a sip if you have lowered the volume to help you read something.",
  "Take a sip if you have chosen a favorite contestant within the first minute.",
  "Take a sip if you have started a podcast and forgotten to listen after the introduction.",
  "Take a sip if you have watched a familiar film because choosing something new felt difficult.",
  "Take a sip if you have laughed before a favorite comedy scene even began.",
  "Take a sip if you have tried to imitate a dance from a music video.",
  "Take a sip if you have paused a mystery to inspect a tiny background clue.",
  "Take a sip if you have become invested in a show you claimed not to like.",
  "Take a sip if you have searched for a song using only a vague humming description.",
  "Take a sip if you have confused two fictional characters for an entire episode.",
  "Take a sip if you have finished a book and immediately missed its characters.",

  "Take a sip if you have created a tiny song about an ordinary task.",
  "Take a sip if you have raced a microwave countdown and lost.",
  "Take a sip if you have given yourself a dramatic entrance in an empty room.",
  "Take a sip if you have made a face at your reflection just to check it still works.",
  "Take a sip if you have narrated your own mistake like a sports commentator.",
  "Take a sip if you have practiced a conversation that never happened.",
  "Take a sip if you have balanced along a pavement line for no practical reason.",
  "Take a sip if you have pressed an elevator button more than once for encouragement.",
  "Take a sip if you have drummed on a table without noticing.",
  "Take a sip if you have made up lyrics when you only knew the chorus.",
  "Take a sip if you have turned a minor inconvenience into a full dramatic monologue.",
  "Take a sip if you have tried to throw something into a bin and celebrated the landing.",
  "Take a sip if you have assigned a personality to an inanimate object.",
  "Take a sip if you have quietly competed with someone who did not know there was a contest.",
  "Take a sip if you have counted stairs simply because they were there.",
  "Take a sip if you have used finger guns after completing a very ordinary task.",
  "Take a sip if you have imagined a soundtrack for your walk.",
  "Take a sip if you have made a sound effect while picking something up.",
  "Take a sip if you have celebrated finding exact change like winning a prize.",
  "Take a sip if you have tried to predict which raindrop would reach the window edge first.",
  "Take a sip if you have arranged food by color before eating it.",
  "Take a sip if you have used a spoon as a microphone when nobody was watching.",
  "Take a sip if you have rehearsed saying a simple name before making a call.",
  "Take a sip if you have made an everyday decision with a coin toss.",
  "Take a sip if you have walked in rhythm with a song playing nearby.",
  "Take a sip if your entrance through an ordinary door has included theatrical flair.",
  "Take a sip if you have congratulated yourself aloud for remembering something.",
  "Take a sip if every shopping bag has looked manageable in one ambitious journey.",
  "Take a sip if you have waved at a security camera out of politeness.",
  "Take a sip if you have turned matching container lids into a puzzle game.",

  "Take a sip if you have sneezed just after saying you were about to sneeze.",
  "Take a sip if you have caught your sleeve on a door handle.",
  "Take a sip if you have tried to sit elegantly and made the chair squeak.",
  "Take a sip if you have stumbled slightly and turned it into a dance move.",
  "Take a sip if you have pulled a door marked push before reading the sign.",
  "Take a sip if you have stepped into a puddle that looked much shallower.",
  "Take a sip if you have dropped a pen and kicked it farther while retrieving it.",
  "Take a sip if you have bumped into furniture that has always been in the same place.",
  "Take a sip if catching a falling object has briefly turned into juggling.",
  "Take a sip if you have walked around with a sticker attached to your clothing.",
  "Take a sip if you have missed a bin from an impressively short distance.",
  "Take a sip if an open doorway has made you forget to step through it.",
  "Take a sip if you have startled yourself with your own reflection.",
  "Take a sip if you have sat on a chair that was lower than expected.",
  "Take a sip if you have caught something falling and felt briefly heroic.",
  "Take a sip if you have tried to look casual after walking the wrong way.",
  "Take a sip if you have stepped over an obstacle and clipped it anyway.",
  "Take a sip if you have worn a price sticker longer than intended.",
  "Take a sip if you have leaned on something you assumed was stable.",
  "Take a sip if you have waved away an insect that was actually a loose thread.",
  "Take a sip if a cobweb has prompted an unexpected burst of choreography.",
  "Take a sip if you have dropped one small item and somehow scattered several others.",
  "Take a sip if a slowly closing door has inspired an unnecessary rescue attempt.",
  "Take a sip if you have worn a hood without realizing it was still up.",
  "Take a sip if you have bumped your elbow and waited for the delayed tingle.",
  "Take a sip if you have adjusted a wobbly table using whatever was nearby.",
  "Take a sip if you have taken a confident step and discovered there was no stair.",
  "Take a sip if you have walked under a dripping sign at exactly the wrong moment.",
  "Take a sip if you have tried to open packaging from every side except the marked side.",
  "Take a sip if you have put an item down carefully and watched it roll away.",
]
