export const TAKE_SIP_WORK: readonly string[] = [
  "Take a sip if a meeting invite has arrived without an agenda.",
  "Take a sip if you have joined a call while still finding your headphones.",
  "Take a sip if someone has said they cannot see the screen being shared.",
  "Take a sip if a meeting has ended early and improved your whole day.",
  "Take a sip if you have attended a call that could have been a short message.",
  "Take a sip if the first five minutes of a meeting were spent waiting for someone.",
  "Take a sip if you have volunteered to keep a discussion on track.",
  "Take a sip if a calendar reminder has rescued you from missing a meeting.",
  "Take a sip if you have spoken while muted on a video call.",
  "Take a sip if you have wondered why you were included in a meeting.",
  "Take a sip if a presentation has sparked a genuinely useful question.",
  "Take a sip if you have watched a meeting drift far from its original purpose.",
  "Take a sip if someone has joined a call from an unexpected location.",
  "Take a sip if you have used the chat to contribute without interrupting.",
  "Take a sip if a meeting decision has needed another meeting to explain it.",
  "Take a sip if you have arrived first and checked whether the link worked.",
  "Take a sip if a recurring meeting has outlived the project that created it.",
  "Take a sip if you have asked for clear next steps before everyone left.",
  "Take a sip if a quiet participant has made the most valuable point.",
  "Take a sip if you have declined a meeting to protect focused work time.",
  "Take a sip if you have rehearsed a sentence before unmuting.",
  "Take a sip if a meeting room has been booked by two groups at once.",
  "Take a sip if you have presented an update shorter than the time allotted.",
  "Take a sip if a late arrival has asked everyone to repeat the discussion.",
  "Take a sip if you have left a call with a clearer plan than you expected.",
  "Take a sip if a surprise technical issue has become the meeting icebreaker.",
  "Take a sip if you have moved a conversation to a smaller group to finish it.",
  "Take a sip if everyone has paused because nobody knew who should speak next.",
  "Take a sip if you have attended back-to-back calls in different time zones.",
  "Take a sip if a well-timed summary has prevented a discussion from looping.",
  "Take a sip if you have rewritten a work message to make the tone friendlier.",
  "Take a sip if an email thread has become harder to follow with every reply.",
  "Take a sip if you have forgotten an attachment and noticed after sending.",
  "Take a sip if a coworker has answered your question with the perfect link.",
  "Take a sip if you have typed a reply and decided a call would be clearer.",
  "Take a sip if a message marked urgent turned out not to be urgent.",
  "Take a sip if you have used an emoji to soften a very brief response.",
  "Take a sip if a typo became obvious the instant you pressed send.",
  "Take a sip if you have received a one-word reply that needed interpretation.",
  "Take a sip if a group chat has solved a problem faster than a formal process.",
  "Take a sip if you have scheduled a message for someone else's working hours.",
  "Take a sip if an unfamiliar abbreviation has sent you searching for its meaning.",
  "Take a sip if you have found key context buried deep in an old conversation.",
  "Take a sip if a carefully written update has prevented unnecessary questions.",
  "Take a sip if you have muted a noisy channel so you could concentrate.",
  "Take a sip if someone has replied only to you when the whole group needed the answer.",
  "Take a sip if you have caught yourself overthinking a simple sign-off.",
  "Take a sip if a voice note has been more useful than a long paragraph.",
  "Take a sip if you have shared a document and immediately changed its permissions.",
  "Take a sip if a colleague has interpreted a message differently from you.",
  "Take a sip if you have turned a dense update into a readable checklist.",
  "Take a sip if an automatic status message has answered your question.",
  "Take a sip if you have sent a work message to the wrong conversation.",
  "Take a sip if a polite follow-up has finally unlocked a stalled task.",
  "Take a sip if you have chosen not to send a message outside someone's workday.",
  "Take a sip if a reaction icon has saved an entire round of reply-all messages.",
  "Take a sip if you have explained the same idea differently for two audiences.",
  "Take a sip if an inbox search has felt like workplace archaeology.",
  "Take a sip if you have asked someone to confirm what a vague request meant.",
  "Take a sip if a concise subject line has made an email much easier to find.",
  "Take a sip if a coworker has taught you a shortcut you now use every day.",
  "Take a sip if you have helped someone without being asked first.",
  "Take a sip if your work friend has known exactly what your facial expression meant.",
  "Take a sip if you have shared credit for a result that took several people.",
  "Take a sip if a teammate has covered something important while you were away.",
  "Take a sip if you have learned a surprising skill from a newer colleague.",
  "Take a sip if a coworker's snack recommendation became part of your routine.",
  "Take a sip if you have celebrated a teammate's good news during the workday.",
  "Take a sip if someone from another department has become your go-to helper.",
  "Take a sip if you have quietly fixed a small problem for the next person.",
  "Take a sip if a colleague has remembered a detail you mentioned weeks ago.",
  "Take a sip if you have swapped tasks so each person could use their strengths.",
  "Take a sip if a respectful disagreement has improved the final result.",
  "Take a sip if you have thanked someone for work that usually goes unnoticed.",
  "Take a sip if a teammate has made a difficult day feel manageable.",
  "Take a sip if you have borrowed a charger, pen, or adapter from a coworker.",
  "Take a sip if an inside joke has made sense only to your team.",
  "Take a sip if you have introduced two colleagues who could help each other.",
  "Take a sip if someone has brought enough treats to share with the whole team.",
  "Take a sip if you have learned how a coworker prefers to receive feedback.",
  "Take a sip if a teammate has noticed you needed a break before you did.",
  "Take a sip if you have worked well with someone whose style differs from yours.",
  "Take a sip if a colleague's organized notes have saved everyone time.",
  "Take a sip if you have cheered for someone taking on a new opportunity.",
  "Take a sip if a team tradition has made an ordinary week more enjoyable.",
  "Take a sip if you have offered context to help a new coworker settle in.",
  "Take a sip if a colleague has recommended a tool that solved a recurring annoyance.",
  "Take a sip if you have made room for a quieter teammate to contribute.",
  "Take a sip if a quick check-in has turned into the best conversation of the day.",
  "Take a sip if you have kept in touch with someone from a previous workplace.",
  "Take a sip if your home workspace has appeared in the background of a call.",
  "Take a sip if a delivery has arrived at the least convenient work moment.",
  "Take a sip if you have changed rooms to find better internet or less noise.",
  "Take a sip if someone off camera has unexpectedly joined your video meeting.",
  "Take a sip if you have worn comfortable clothes below the camera frame.",
  "Take a sip if a household sound has been perfectly timed with your unmute button.",
  "Take a sip if you have taken a walking break between remote tasks.",
  "Take a sip if your commute has been exactly the distance between two rooms.",
  "Take a sip if you have worked with someone you have never met in person.",
  "Take a sip if a virtual background has hidden a less-than-tidy room.",
  "Take a sip if you have briefly shared the wrong window during a call.",
  "Take a sip if home internet trouble has changed your plan for the day.",
  "Take a sip if you have created a ritual that signals the workday is over.",
  "Take a sip if a remote meeting has included a welcome pet appearance.",
  "Take a sip if you have moved closer to a window for better video lighting.",
  "Take a sip if a hybrid meeting has made it hard to hear someone in the room.",
  "Take a sip if you have eaten lunch at your desk despite being at home.",
  "Take a sip if a camera-off day has helped you focus on the conversation.",
  "Take a sip if you have used captions to follow an online discussion.",
  "Take a sip if your desk has served another purpose after working hours.",
  "Take a sip if you have planned an office day around seeing particular teammates.",
  "Take a sip if a time-zone difference has made your calendar look unusual.",
  "Take a sip if you have tested your microphone by talking to yourself.",
  "Take a sip if a remote social activity has been more fun than expected.",
  "Take a sip if you have closed the laptop and reopened it for one final task.",
  "Take a sip if a borrowed corner became your long-term workspace.",
  "Take a sip if you have improved your setup after an uncomfortable workday.",
  "Take a sip if a neighbor's renovation has featured in a team call.",
  "Take a sip if you have forgotten that your camera was already on.",
  "Take a sip if remote work has introduced your teammates to your favorite mug.",
  "Take a sip if a project timeline has changed before the project truly began.",
  "Take a sip if you have discovered a hidden dependency at the worst moment.",
  "Take a sip if a supposedly small task has required several approvals.",
  "Take a sip if you have broken a large project into satisfying smaller milestones.",
  "Take a sip if the scope has grown while the deadline stayed the same.",
  "Take a sip if you have flagged a risk before it became a real problem.",
  "Take a sip if a project board has contained a card nobody remembered creating.",
  "Take a sip if you have finished the hardest task earlier than planned.",
  "Take a sip if a blocker disappeared just after you found a workaround.",
  "Take a sip if you have asked which priority mattered most when everything looked urgent.",
  "Take a sip if the final version was not actually the final version.",
  "Take a sip if you have inherited a project with very little documentation.",
  "Take a sip if an early prototype has answered a question better than debate.",
  "Take a sip if you have watched a deadline move in both directions.",
  "Take a sip if a status update has contained more colors than words.",
  "Take a sip if you have finished something that once felt impossibly complex.",
  "Take a sip if one decision has unblocked several pieces of work at once.",
  "Take a sip if you have kept a private checklist beside the official tracker.",
  "Take a sip if a project name has changed after everyone learned the old one.",
  "Take a sip if you have questioned a requirement and saved unnecessary effort.",
  "Take a sip if the test run went better than the rehearsal.",
  "Take a sip if you have documented a lesson while it was still fresh.",
  "Take a sip if a handoff has arrived with exactly the context you needed.",
  "Take a sip if you have negotiated more time after new work was added.",
  "Take a sip if a launch day has been quieter than the preparation for it.",
  "Take a sip if you have found the root cause somewhere nobody expected.",
  "Take a sip if a project retrospective has led to a real improvement.",
  "Take a sip if you have removed a feature to make the outcome stronger.",
  "Take a sip if an old document has solved a current project mystery.",
  "Take a sip if you have celebrated closing a task that lingered for months.",
  "Take a sip if you have received feedback that changed your approach for the better.",
  "Take a sip if you have asked for an example to make vague feedback useful.",
  "Take a sip if someone has recognized work you thought went unnoticed.",
  "Take a sip if you have kept a note of accomplishments for review time.",
  "Take a sip if a mentor has helped you see a new career possibility.",
  "Take a sip if you have taught a skill that once took you ages to learn.",
  "Take a sip if you have applied for a role that felt like a stretch.",
  "Take a sip if an unexpected assignment has revealed one of your strengths.",
  "Take a sip if you have asked what growth could look like in your current role.",
  "Take a sip if a training session has immediately improved your work.",
  "Take a sip if you have updated your professional profile after a major win.",
  "Take a sip if a career conversation has gone differently than you rehearsed.",
  "Take a sip if your thoughtful suggestion has influenced a leader's decision.",
  "Take a sip if a mistake has taught you more than an easy success.",
  "Take a sip if you have advocated for your contribution with clear evidence.",
  "Take a sip if a colleague has encouraged you to share your expertise.",
  "Take a sip if you have changed your mind about the direction of your career.",
  "Take a sip if a new responsibility has become your favorite part of the job.",
  "Take a sip if you have attended an event mainly to learn from other professionals.",
  "Take a sip if a useful course has been sitting in your bookmarks.",
  "Take a sip if you have requested feedback before a formal review.",
  "Take a sip if a compliment has helped you identify a skill worth developing.",
  "Take a sip if you have mentored someone and learned from them too.",
  "Take a sip if an interview question has stayed with you after the interview.",
  "Take a sip if you have negotiated for something important in a new role.",
  "Take a sip if a sideways career move has opened an unexpected door.",
  "Take a sip if you have volunteered for a project to build new experience.",
  "Take a sip if a former manager's advice still guides your decisions.",
  "Take a sip if you have become the person others ask about a particular topic.",
  "Take a sip if you have noticed your confidence grow through repeated practice.",
  "Take a sip if a professional setback has eventually redirected you somewhere better.",
  "Take a sip if you have protected your lunch break on a busy day.",
  "Take a sip if you have silenced work notifications outside your chosen hours.",
  "Take a sip if a day off has helped you return with a clearer perspective.",
  "Take a sip if you have said no because your workload was already full.",
  "Take a sip if you have blocked focus time and treated it like a real appointment.",
  "Take a sip if an evening plan has stopped you from working later than intended.",
  "Take a sip if you have asked for help before reaching complete overload.",
  "Take a sip if a walk outside has reset a difficult workday.",
  "Take a sip if you have closed every work tab before starting your weekend.",
  "Take a sip if someone has respected your status without expecting an immediate reply.",
  "Take a sip if you have used annual leave without checking your inbox.",
  "Take a sip if a personal commitment has taken rightful priority over a meeting.",
  "Take a sip if you have adjusted a deadline instead of sacrificing needed rest.",
  "Take a sip if a clear handoff has allowed you to switch off fully.",
  "Take a sip if you have removed work email from your personal phone.",
  "Take a sip if you have taken a proper break away from your screen.",
  "Take a sip if a manager has modeled healthy boundaries for the team.",
  "Take a sip if you have communicated your availability before it became an issue.",
  "Take a sip if an out-of-office reply has protected time you genuinely needed.",
  "Take a sip if you have let a nonurgent message wait until the next workday.",
  "Take a sip if a hobby has helped you stop thinking about a complicated task.",
  "Take a sip if you have rearranged work to accommodate a life appointment.",
  "Take a sip if a quiet morning has been more productive than a late night.",
  "Take a sip if you have encouraged a teammate to take the break they earned.",
  "Take a sip if a boundary became easier once you explained it clearly.",
  "Take a sip if you have chosen good-enough completion over unnecessary perfection.",
  "Take a sip if a flexible schedule has made your week work better.",
  "Take a sip if you have returned from leave to a thoughtfully organized handover.",
  "Take a sip if you have ended the day by writing tomorrow's first task.",
  "Take a sip if a weekend has passed without opening a work app.",
  "Take a sip if a customer has asked a question you had never heard before.",
  "Take a sip if you have remembered a regular customer's usual preference.",
  "Take a sip if a sincere thank-you has turned around a demanding day.",
  "Take a sip if you have found an alternative when someone's first choice was unavailable.",
  "Take a sip if a customer has taught you something useful about your own product.",
  "Take a sip if you have followed up to make sure an issue was truly resolved.",
  "Take a sip if a simple explanation has calmed a confusing situation.",
  "Take a sip if you have corrected an error before a client noticed it.",
  "Take a sip if a customer compliment has mentioned someone on your team by name.",
  "Take a sip if you have managed expectations when a timeline changed.",
  "Take a sip if a familiar customer has brightened the start of your shift.",
  "Take a sip if you have escalated a request that was outside your authority.",
  "Take a sip if feedback from a customer has improved a process.",
  "Take a sip if you have explained a policy without making it sound impersonal.",
  "Take a sip if a client has changed the brief after seeing the first draft.",
  "Take a sip if you have solved a problem without making someone repeat the whole story.",
  "Take a sip if a customer has been patient while you found the right answer.",
  "Take a sip if you have documented a frequent question for the rest of the team.",
  "Take a sip if a service recovery has created a surprisingly positive outcome.",
  "Take a sip if you have adapted your language for someone new to the subject.",
  "Take a sip if a request has revealed a use case nobody planned for.",
  "Take a sip if you have stayed composed while a queue continued growing.",
  "Take a sip if a customer has made you laugh during an ordinary interaction.",
  "Take a sip if you have said no kindly when a request could not be fulfilled.",
  "Take a sip if a follow-up message has arrived with good news.",
  "Take a sip if you have spotted a pattern across several customer questions.",
  "Take a sip if a client's clear brief has made the work noticeably easier.",
  "Take a sip if you have owned a mistake and offered a practical next step.",
  "Take a sip if a calm conversation has resolved what looked like a major complaint.",
  "Take a sip if a customer interaction has reminded you why your work matters.",
  "Take a sip if you have found a mystery container in the shared refrigerator.",
  "Take a sip if the office printer has behaved perfectly when support arrived.",
  "Take a sip if you have carried a mug around after forgetting what you needed.",
  "Take a sip if a snack appeared just when the afternoon needed one.",
  "Take a sip if you have chosen a desk based on the nearest power outlet.",
  "Take a sip if the temperature at work has inspired competing opinions.",
  "Take a sip if you have worn a name badge long enough to forget it was there.",
  "Take a sip if a plant in the workplace has unofficially joined the team.",
  "Take a sip if you have found the good pen after assuming it was gone forever.",
  "Take a sip if the elevator has stopped on nearly every floor during your ride.",
  "Take a sip if you have arrived unusually early because traffic was lighter than expected.",
  "Take a sip if a shared kitchen appliance has required unofficial instructions.",
  "Take a sip if you have taken the scenic route while looking for a meeting room.",
  "Take a sip if a birthday card has circulated with almost no space left to sign.",
  "Take a sip if you have discovered that your lunch choice matched a coworker's.",
  "Take a sip if an office chair has needed a full adjustment before use.",
  "Take a sip if you have heard hold music long enough to remember the tune.",
  "Take a sip if a package at work has caused brief excitement before being claimed.",
  "Take a sip if you have opened a cupboard and forgotten what you were seeking.",
  "Take a sip if a sunny day has made the window seats especially popular.",
  "Take a sip if you have kept emergency snacks in a desk or work bag.",
  "Take a sip if the workplace clock has seemed unusually slow before a break.",
  "Take a sip if you have recognized a coworker by their footsteps or keyboard sounds.",
  "Take a sip if a casual hallway chat has answered a work question.",
  "Take a sip if you have found an unexpectedly peaceful spot at work.",
  "Take a sip if a communal treat has disappeared faster than anyone predicted.",
  "Take a sip if you have used a sticky note for something a calendar could not capture.",
  "Take a sip if the dress code has felt open to creative interpretation.",
  "Take a sip if you have walked into a room and realized it was the wrong one.",
  "Take a sip if a small workplace convenience has made your day noticeably better.",
  "Take a sip if your first day included more introductions than you could remember.",
  "Take a sip if a teammate has helped you decode an unspoken office norm.",
  "Take a sip if a login problem has delayed the task you were ready to start.",
  "Take a sip if you have created instructions you wish existed when you joined.",
  "Take a sip if an onboarding session introduced more tools than you expected.",
  "Take a sip if you have found the unofficial expert on how things really work.",
  "Take a sip if a new starter's question has exposed an unclear process.",
  "Take a sip if you have gone from asking questions to answering them for others.",
  "Take a sip if a workplace tour included a shortcut you still use.",
  "Take a sip if you have repeated an introduction during a crowded networking event.",
  "Take a sip if a welcome message made a new role feel less unfamiliar.",
  "Take a sip if you have shadowed someone whose routine looked effortless.",
  "Take a sip if your job title has required an explanation outside your industry.",
  "Take a sip if you have discovered that two teams use different names for the same thing.",
  "Take a sip if a policy made more sense after someone explained the reason behind it.",
  "Take a sip if you have asked where a file lives and received several answers.",
  "Take a sip if a new tool felt confusing before becoming second nature.",
  "Take a sip if you have welcomed someone by sharing a practical tip.",
  "Take a sip if an old acronym has survived longer than its original meaning.",
  "Take a sip if you have discovered a benefit only after months in the role.",
  "Take a sip if a team chart has helped you understand who does what.",
  "Take a sip if you have needed access approval from someone you had not met.",
  "Take a sip if a process has contained a step nobody could fully explain.",
  "Take a sip if you have suggested an improvement after seeing a task with fresh eyes.",
  "Take a sip if a training example became relevant sooner than expected.",
  "Take a sip if you have remembered how intimidating a routine task once seemed.",
  "Take a sip if a new colleague has brought a useful perspective to the team.",
  "Take a sip if you have finally learned who manages a mysterious shared inbox.",
  "Take a sip if an organizational change has required updating your mental map.",
]
