export const TAKE_SIP_RED_FLAGS: readonly string[] = [
  "Take a sip if you have delayed a reply to seem less interested.",
  "Take a sip if you have sent a vague message hoping someone would chase you for details.",
  "Take a sip if you have answered only the easiest part of a serious message.",
  "Take a sip if you have used a reaction emoji to avoid giving a real response.",
  "Take a sip if you have disappeared from a conversation instead of ending it honestly.",
  "Take a sip if you have expected an immediate reply while taking days to send your own.",
  "Take a sip if you have started an important conversation by text when a call was clearly kinder.",
  "Take a sip if you have reread a message looking for an insult that was never intended.",
  "Take a sip if you have sent several follow-ups before giving someone time to answer.",
  "Take a sip if you have replied coldly because someone did not notice you were upset.",
  "Take a sip if you have confused bluntness with honesty.",
  "Take a sip if you have spoken for someone who was present and able to answer.",
  "Take a sip if you have expected someone to understand a hint you barely gave.",
  "Take a sip if you have kept talking after noticing the other person had checked out.",
  "Take a sip if you have used a serious conversation to show how clever you were.",
  "Take a sip if you have treated feedback as disrespect before considering it.",
  "Take a sip if you have waited until an argument to reveal an old frustration.",
  "Take a sip if you have assumed silence meant agreement.",
  "Take a sip if you have minimized a concern because it would not bother you personally.",
  "Take a sip if you have insisted on the last word after the issue was settled.",

  "Take a sip if you have agreed to plans you already suspected you would cancel.",
  "Take a sip if you have arrived late without sending an update.",
  "Take a sip if you have made a promise before checking whether you could keep it.",
  "Take a sip if you have let someone else handle the details you volunteered to manage.",
  "Take a sip if you have forgotten a commitment and hoped nobody would mention it.",
  "Take a sip if you have cancelled at the last minute for a more appealing invitation.",
  "Take a sip if you have borrowed something and returned it only after being reminded.",
  "Take a sip if you have offered help and then become mysteriously unavailable.",
  "Take a sip if you have left a shared task until someone else completed it.",
  "Take a sip if you have treated a deadline as optional because it was informal.",
  "Take a sip if you have overcommitted and made the consequences everyone else's problem.",
  "Take a sip if you have confirmed plans without reading the important details.",
  "Take a sip if you have kept someone waiting while finishing a nonurgent task.",
  "Take a sip if you have volunteered another person's time without asking them.",
  "Take a sip if you have promised to call back and quietly hoped they would forget.",
  "Take a sip if you have made reliability sound boring when someone asked for consistency.",
  "Take a sip if you have treated being busy as a complete apology.",
  "Take a sip if you have expected flexibility that you rarely offered in return.",
  "Take a sip if you have said you were on the way before actually leaving.",
  "Take a sip if you have accepted credit for a plan someone else organized.",

  "Take a sip if you have apologized mainly to end the conversation.",
  "Take a sip if you have added an excuse to every part of an apology.",
  "Take a sip if you have focused on your intentions instead of the impact you caused.",
  "Take a sip if you have waited for the other person to apologize first on principle.",
  "Take a sip if you have blamed your mood for behavior you still needed to repair.",
  "Take a sip if you have denied something until someone showed you proof.",
  "Take a sip if you have admitted a mistake but repeated it without a new plan.",
  "Take a sip if you have explained why a problem was technically not your fault.",
  "Take a sip if you have expected quick forgiveness after a slow apology.",
  "Take a sip if you have made your guilt the main topic after hurting someone's feelings.",
  "Take a sip if you have apologized for how someone reacted rather than what you did.",
  "Take a sip if you have hidden behind good intentions to avoid making amends.",
  "Take a sip if you have asked for honesty and then punished the honest answer.",
  "Take a sip if you have defended a habit simply because it was familiar.",
  "Take a sip if you have called accountability negativity.",
  "Take a sip if you have blamed stress for a pattern that outlasted the stressful week.",
  "Take a sip if you have promised change without deciding what change would look like.",
  "Take a sip if you have remembered events differently whenever responsibility came up.",
  "Take a sip if you have sought reassurance before fully acknowledging your part.",
  "Take a sip if you have treated admitting uncertainty like losing an argument.",

  "Take a sip if you have looked through someone's belongings without permission.",
  "Take a sip if you have shared news that was not yours to announce.",
  "Take a sip if you have asked a personal question after someone tried to move on.",
  "Take a sip if you have assumed closeness entitled you to private information.",
  "Take a sip if you have repeated a confidential story as anonymous gossip.",
  "Take a sip if you have posted a group photo before checking whether everyone was comfortable.",
  "Take a sip if you have tagged someone's location without asking.",
  "Take a sip if you have read over someone's shoulder on purpose.",
  "Take a sip if you have pressured a friend to explain why they declined an invitation.",
  "Take a sip if you have borrowed a device and opened more than you needed.",
  "Take a sip if you have treated a closed door as a suggestion.",
  "Take a sip if you have kept asking after receiving a clear answer.",
  "Take a sip if you have invited an extra guest without consulting the host.",
  "Take a sip if you have told a story that embarrassed someone after they asked you not to.",
  "Take a sip if you have used friendship as a reason someone should make an exception.",
  "Take a sip if you have taken a refusal personally instead of respecting it.",
  "Take a sip if you have offered advice after someone said they only wanted to vent.",
  "Take a sip if you have assumed a favor once granted was permanently available.",
  "Take a sip if you have pushed for details about a relationship that was not yours.",
  "Take a sip if you have shared someone else's contact details without checking first.",

  "Take a sip if you have compared a new person to someone from your past out loud.",
  "Take a sip if you have kept a backup plan in case a promising connection failed.",
  "Take a sip if you have tested someone's interest instead of asking where you stood.",
  "Take a sip if you have expected exclusivity without having a conversation about it.",
  "Take a sip if you have mistaken constant contact for genuine compatibility.",
  "Take a sip if you have ignored a mismatch because the chemistry was exciting.",
  "Take a sip if you have made future plans before learning someone's everyday habits.",
  "Take a sip if you have stayed vague about your intentions to keep your options open.",
  "Take a sip if you have used jealousy to measure whether someone cared.",
  "Take a sip if you have treated mixed signals as more romantic than clear interest.",
  "Take a sip if you have agreed with every preference to seem more compatible.",
  "Take a sip if you have expected a new connection to fix an old insecurity.",
  "Take a sip if you have continued dating someone while hoping their core values would change.",
  "Take a sip if you have read too much into one thoughtful gesture.",
  "Take a sip if you have confused being wanted with being well treated.",
  "Take a sip if you have avoided defining a relationship because ambiguity benefited you.",
  "Take a sip if you have judged someone's dating history by a rule you did not apply to yourself.",
  "Take a sip if you have called a reasonable request needy because it inconvenienced you.",
  "Take a sip if you have stayed interested mainly because someone became less available.",
  "Take a sip if you have tried to win someone over after realizing you were incompatible.",

  "Take a sip if you have expected a close friend to take your side without hearing the context.",
  "Take a sip if you have made a friend's good news about your own disappointment.",
  "Take a sip if you have contacted someone only when you needed a favor.",
  "Take a sip if you have let one friend do all the work of staying in touch.",
  "Take a sip if you have complained about being excluded from plans you often declined.",
  "Take a sip if you have teased a friend about something they were genuinely sensitive about.",
  "Take a sip if you have expected loyalty to include agreeing with you.",
  "Take a sip if you have treated a friend's new priorities as a personal rejection.",
  "Take a sip if you have shared a private joke that made someone else feel excluded.",
  "Take a sip if you have kept a friendship alive mostly through nostalgia.",
  "Take a sip if you have resented a friend for setting a boundary you needed to hear.",
  "Take a sip if you have avoided celebrating someone because you felt behind.",
  "Take a sip if you have expected emotional support without asking how your friend was doing.",
  "Take a sip if you have made plans in a group chat that excluded someone in it.",
  "Take a sip if you have treated a long friendship as permission to stop making effort.",
  "Take a sip if you have repeated a friend's opinion without giving them credit.",
  "Take a sip if you have competed with a friend who thought you were collaborating.",
  "Take a sip if you have dismissed a friend's concern because others agreed with you.",
  "Take a sip if you have expected a friend to remember details you regularly forgot about them.",
  "Take a sip if you have called only to unload and ended the conversation right afterward.",

  "Take a sip if you have taken the best shared item without checking whether anyone wanted it.",
  "Take a sip if you have left a mess in a shared space because someone else was tidier.",
  "Take a sip if you have used the last of something communal without replacing it.",
  "Take a sip if you have played music aloud where headphones were the considerate choice.",
  "Take a sip if you have ignored a household task until somebody asked twice.",
  "Take a sip if you have moved someone else's things and forgotten where you put them.",
  "Take a sip if you have treated a common area like personal storage.",
  "Take a sip if you have invited people over without warning the people you live with.",
  "Take a sip if you have assumed your schedule should set the household schedule.",
  "Take a sip if you have noticed supplies were low and left the problem for the next person.",
  "Take a sip if you have avoided a shared expense conversation because it felt awkward.",
  "Take a sip if you have used someone's food and planned to mention it later.",
  "Take a sip if you have complained about a chore while someone else was doing it.",
  "Take a sip if you have left a tiny portion behind to avoid finishing the container.",
  "Take a sip if you have made noise early or late without considering who was resting.",
  "Take a sip if you have claimed the most convenient spot as though it belonged to you.",
  "Take a sip if you have expected praise for completing your share of routine work.",
  "Take a sip if you have replaced a household item with a cheaper version only others use.",
  "Take a sip if you have waited for visitors before finally cleaning a shared room.",
  "Take a sip if you have called a shared rule unnecessary only after it affected you.",

  "Take a sip if you have presented a teammate's idea as though it were your own.",
  "Take a sip if you have stayed quiet about an error that someone else might be blamed for.",
  "Take a sip if you have scheduled a meeting that could have been a clear message.",
  "Take a sip if you have asked for urgent help on work you postponed.",
  "Take a sip if you have interrupted a colleague and later repeated their point.",
  "Take a sip if you have agreed to a deadline without consulting the people doing the work.",
  "Take a sip if you have taken public credit and given private thanks.",
  "Take a sip if you have withheld useful context to protect your own position.",
  "Take a sip if you have called someone difficult for asking a reasonable work question.",
  "Take a sip if you have sent a nonurgent work message outside agreed hours and expected a reply.",
  "Take a sip if you have volunteered for a visible task and avoided the unglamorous follow-through.",
  "Take a sip if you have let confidence outweigh preparation in a group project.",
  "Take a sip if you have complained about a process you never tried to improve.",
  "Take a sip if you have accepted praise that belonged to the whole team.",
  "Take a sip if you have used jargon to make a simple point sound more important.",
  "Take a sip if you have judged a colleague's availability without knowing their workload.",
  "Take a sip if you have asked for feedback after the decision was already final.",
  "Take a sip if you have kept a useful document organized only in your own private system.",
  "Take a sip if you have treated a junior teammate's time as less valuable than yours.",
  "Take a sip if you have promised a quick task before discovering what it involved.",

  "Take a sip if you have posted a vague complaint hoping one specific person would see it.",
  "Take a sip if you have mistaken frequent posting for knowing someone well.",
  "Take a sip if you have checked who viewed your post and judged who did not respond.",
  "Take a sip if you have edited a caption to make an ordinary moment look enviable.",
  "Take a sip if you have followed someone mainly to monitor them.",
  "Take a sip if you have shared an article after reading only the headline.",
  "Take a sip if you have joined an online pile-on before checking the context.",
  "Take a sip if you have compared your real life to someone else's carefully chosen highlights.",
  "Take a sip if you have posted about kindness while being unkind in the comments.",
  "Take a sip if you have refreshed a post mainly to watch the reaction count.",
  "Take a sip if you have removed a photo because it received less attention than expected.",
  "Take a sip if you have treated a public follow as proof of private loyalty.",
  "Take a sip if you have complained about oversharing and then shared someone else's news.",
  "Take a sip if you have used a private account to say what you would not say directly.",
  "Take a sip if you have assumed an online silence was aimed at you.",
  "Take a sip if you have posted during a conversation instead of being present for it.",
  "Take a sip if you have mistaken access to someone's profile for access to their life.",
  "Take a sip if you have judged a person by an old post without allowing for growth.",
  "Take a sip if you have shared a screenshot without considering the missing context.",
  "Take a sip if you have used a trending opinion before deciding what you actually believed.",

  "Take a sip if you have turned every topic back to a story about yourself.",
  "Take a sip if you have name-dropped someone to make your own story sound impressive.",
  "Take a sip if you have exaggerated a minor inconvenience for extra sympathy.",
  "Take a sip if you have pretended to know a reference rather than asking.",
  "Take a sip if you have offered a compliment that was secretly a comparison.",
  "Take a sip if you have corrected someone's pronunciation mainly to display your knowledge.",
  "Take a sip if you have acted bored by something because you did not understand it.",
  "Take a sip if you have made a conversation competitive for no reason.",
  "Take a sip if you have treated popularity as evidence that someone was right.",
  "Take a sip if you have used self-deprecation to fish for reassurance.",
  "Take a sip if you have pretended not to care about recognition you strongly wanted.",
  "Take a sip if you have dismissed a hobby because it was not considered impressive.",
  "Take a sip if you have changed your opinion when a higher-status person entered the room.",
  "Take a sip if you have made someone else's achievement sound easy.",
  "Take a sip if you have used a humblebrag and hoped nobody noticed the brag.",
  "Take a sip if you have assumed expertise based on confidence alone.",
  "Take a sip if you have told a longer story after noticing someone else got a bigger laugh.",
  "Take a sip if you have treated a conversation like an audition.",
  "Take a sip if you have mentioned being busy mainly to sound important.",
  "Take a sip if you have valued an invitation more after learning it was exclusive.",

  "Take a sip if you have avoided asking for help and then resented that nobody offered.",
  "Take a sip if you have expected someone to manage feelings you had not explained.",
  "Take a sip if you have confused worry with proof that something was wrong.",
  "Take a sip if you have sought the same reassurance after refusing every answer.",
  "Take a sip if you have assumed a delayed response meant rejection.",
  "Take a sip if you have withdrawn to see who would notice.",
  "Take a sip if you have treated a calm discussion as evidence that someone did not care.",
  "Take a sip if you have made a decision while upset and defended it after calming down.",
  "Take a sip if you have expected another person to fix a mood they did not cause.",
  "Take a sip if you have used being overwhelmed to avoid a conversation indefinitely.",
  "Take a sip if you have assumed the worst before asking one clarifying question.",
  "Take a sip if you have confused intensity with closeness.",
  "Take a sip if you have treated discomfort as a sign that a boundary was unfair.",
  "Take a sip if you have rehearsed an argument more than you prepared to listen.",
  "Take a sip if you have made a small disappointment stand in for several older ones.",
  "Take a sip if you have expected people to notice needs you worked hard to hide.",
  "Take a sip if you have interpreted neutral feedback according to your worst fear.",
  "Take a sip if you have said yes while hoping someone would detect that you meant no.",
  "Take a sip if you have confused avoiding conflict with keeping the peace.",
  "Take a sip if you have postponed a needed conversation until your patience ran out.",

  "Take a sip if you have judged someone for a choice you later made yourself.",
  "Take a sip if you have changed the standard once you were the person being evaluated.",
  "Take a sip if you have called a trait confident in one person and arrogant in another.",
  "Take a sip if you have expected grace for a mistake you mocked in someone else.",
  "Take a sip if you have criticized gossip while staying to hear the ending.",
  "Take a sip if you have asked for directness but softened none of your own mixed messages.",
  "Take a sip if you have valued punctuality only when you were the one waiting.",
  "Take a sip if you have defended your privacy while feeling entitled to someone else's details.",
  "Take a sip if you have expected support for a goal you dismissed when someone else had it.",
  "Take a sip if you have called your own stubbornness standards and someone else's inflexibility.",
  "Take a sip if you have wanted honest feedback but only from people who agreed with you.",
  "Take a sip if you have excused your own tone while focusing on someone else's wording.",
  "Take a sip if you have requested patience while offering very little of it.",
  "Take a sip if you have treated your preferences as practical and theirs as difficult.",
  "Take a sip if you have complained about assumptions after making one yourself.",
  "Take a sip if you have expected advance notice but changed plans without giving any.",
  "Take a sip if you have wanted recognition for effort while judging only someone else's result.",
  "Take a sip if you have called your own curiosity concern and another person's curiosity nosiness.",
  "Take a sip if you have dismissed advice that matched what you later told a friend.",
  "Take a sip if you have demanded context for your actions while denying it to someone else.",

  "Take a sip if you have made a joke based on a stereotype and regretted it.",
  "Take a sip if you have assumed two people were dating because they were close.",
  "Take a sip if you have guessed someone's background instead of letting them describe it.",
  "Take a sip if you have repeatedly mispronounced a name without trying to learn it.",
  "Take a sip if you have asked where someone was really from after they already answered.",
  "Take a sip if you have treated your own tradition as the default for everyone.",
  "Take a sip if you have made a group decision without checking accessibility needs.",
  "Take a sip if you have assumed a quiet person had nothing to contribute.",
  "Take a sip if you have praised someone for being unlike a stereotype.",
  "Take a sip if you have used an outdated label after someone offered a better one.",
  "Take a sip if you have expected one person to speak for an entire community.",
  "Take a sip if you have planned food without checking whether everyone could eat it.",
  "Take a sip if you have described something unfamiliar as weird before understanding it.",
  "Take a sip if you have assumed everyone celebrated the same holidays.",
  "Take a sip if you have overlooked someone's idea until another person repeated it.",
  "Take a sip if you have treated an accommodation like an unfair advantage.",
  "Take a sip if you have commented on someone's appearance when it was irrelevant.",
  "Take a sip if you have asked a person to simplify their name for your convenience.",
  "Take a sip if you have confused unfamiliarity with lack of expertise.",
  "Take a sip if you have let an awkward assumption stand instead of correcting yourself.",

  "Take a sip if you have spent shared money before agreeing on the budget.",
  "Take a sip if you have been vague about a cost until after someone committed.",
  "Take a sip if you have delayed repaying a small debt because the other person seemed comfortable.",
  "Take a sip if you have split a bill equally when your order cost much more.",
  "Take a sip if you have offered financial advice without understanding the full situation.",
  "Take a sip if you have judged a friend's budget by your own circumstances.",
  "Take a sip if you have pressured a group toward a pricier plan than some wanted.",
  "Take a sip if you have borrowed money before changing a nonessential spending habit.",
  "Take a sip if you have treated generosity as something another person owed you.",
  "Take a sip if you have hidden a fee in the fine print of a group plan.",
  "Take a sip if you have expected someone to cover you without asking first.",
  "Take a sip if you have bought a gift mainly to create an obligation.",
  "Take a sip if you have kept quiet when a cashier returned too much change.",
  "Take a sip if you have claimed not to care about money while tracking every small favor.",
  "Take a sip if you have suggested an expensive outing and resisted cheaper alternatives.",
  "Take a sip if you have made a money joke that put someone on the spot.",
  "Take a sip if you have expected prompt repayment while being slow to pay others.",
  "Take a sip if you have confused a higher price with better judgment.",
  "Take a sip if you have agreed to share a cost before checking what was included.",
  "Take a sip if you have avoided discussing money until resentment replaced clarity.",

  "Take a sip if you have kept an opinion mainly because changing it felt embarrassing.",
  "Take a sip if you have dismissed evidence because you disliked the person presenting it.",
  "Take a sip if you have argued a point you had not taken time to understand.",
  "Take a sip if you have treated being corrected as being humiliated.",
  "Take a sip if you have moved the goalposts after someone answered your objection.",
  "Take a sip if you have confused having an explanation with having an excuse.",
  "Take a sip if you have repeated a claim because it sounded true.",
  "Take a sip if you have decided someone's motive without asking them.",
  "Take a sip if you have used one bad experience to judge an entire group.",
  "Take a sip if you have rejected a useful idea because it arrived too late.",
  "Take a sip if you have chosen certainty over curiosity in a complicated situation.",
  "Take a sip if you have defended a first impression after learning it was incomplete.",
  "Take a sip if you have asked a question mainly to set up your own answer.",
  "Take a sip if you have mistaken a confident memory for an accurate one.",
  "Take a sip if you have treated compromise as defeat.",
  "Take a sip if you have applied a simple rule to someone else's complicated choice.",
  "Take a sip if you have ignored useful criticism because one detail was unfair.",
  "Take a sip if you have preferred a familiar problem to an unfamiliar solution.",
  "Take a sip if you have claimed an issue was obvious only after learning the answer.",
  "Take a sip if you have stopped listening once you found one point to challenge.",

]
