export const TAKE_SIP_TRAVEL: readonly string[] = [
  "Take a sip if you have ever built a trip around one event you could not miss.",
  "Take a sip if you have ever kept a shared wish list of future destinations.",
  "Take a sip if you have ever chosen a destination by spinning a globe or pointing at a map.",
  "Take a sip if you have ever planned a holiday farther ahead than your friends expected.",
  "Take a sip if you have ever changed a route because a festival fell on your travel dates.",
  "Take a sip if you have ever made a colour-coded itinerary that nobody else followed.",
  "Take a sip if you have ever left an entire day unplanned on purpose.",
  "Take a sip if you have ever compared several destinations before booking the least obvious one.",
  "Take a sip if you have ever scheduled a trip around the best season for local scenery.",
  "Take a sip if you have ever picked a destination because a book made it sound irresistible.",
  "Take a sip if you have ever planned a route around visiting friends in different cities.",
  "Take a sip if you have ever abandoned an ambitious itinerary for a slower holiday.",
  "Take a sip if you have ever checked local holidays before choosing your travel dates.",
  "Take a sip if you have ever researched a destination for fun without intending to book it.",
  "Take a sip if you have ever turned a long layover into a miniature sightseeing plan.",

  "Take a sip if you have ever packed everything into hand luggage for a long trip.",
  "Take a sip if you have ever made a packing list and still forgotten the first item on it.",
  "Take a sip if you have ever rolled every piece of clothing to save suitcase space.",
  "Take a sip if you have ever packed for several climates in one small bag.",
  "Take a sip if you have ever brought an outfit that never left your suitcase.",
  "Take a sip if you have ever weighed your luggage before leaving home.",
  "Take a sip if you have ever worn your bulkiest clothes during the journey to free up space.",
  "Take a sip if you have ever packed a reusable bag that became your most useful item.",
  "Take a sip if you have ever carried a travel adapter that did not fit the socket.",
  "Take a sip if you have ever put a spare outfit in your personal bag in case luggage was delayed.",
  "Take a sip if you have ever packed snacks more carefully than clothes.",
  "Take a sip if you have ever brought a tiny first-aid kit and actually needed it.",
  "Take a sip if you have ever labelled your luggage so clearly that strangers noticed.",
  "Take a sip if you have ever returned with a suitcase that was harder to close than before.",
  "Take a sip if you have ever forgotten which pocket held an important travel item.",

  "Take a sip if you have ever arrived at an airport before the check-in desk opened.",
  "Take a sip if you have ever watched the departure board change gates at the last moment.",
  "Take a sip if you have ever taken a bus across a border.",
  "Take a sip if you have ever enjoyed a train journey more than the destination.",
  "Take a sip if you have ever boarded a ferry with no idea how rough the water would be.",
  "Take a sip if you have ever shared a sleeper compartment with someone new.",
  "Take a sip if you have ever taken a tram simply to see where the line ended.",
  "Take a sip if you have ever chosen the scenic route over the fastest connection.",
  "Take a sip if you have ever travelled on a night bus and woken up unsure of the town.",
  "Take a sip if you have ever crossed a city using more than three kinds of transport.",
  "Take a sip if you have ever missed your stop because the view distracted you.",
  "Take a sip if you have ever waited on the wrong platform before an announcement redirected you.",
  "Take a sip if you have ever felt proud after navigating an unfamiliar metro system.",
  "Take a sip if you have ever taken a cable car as part of an ordinary commute.",
  "Take a sip if you have ever found an unexpectedly beautiful station.",

  "Take a sip if you have ever chosen a window seat specifically for the clouds.",
  "Take a sip if you have ever spotted a landmark from the air before landing.",
  "Take a sip if you have ever applauded a smooth landing in your head.",
  "Take a sip if you have ever packed headphones and discovered they were not charged.",
  "Take a sip if you have ever watched the same in-flight film twice on one journey.",
  "Take a sip if you have ever made friends with a seatmate for exactly one flight.",
  "Take a sip if you have ever walked through an airport so large it felt like its own city.",
  "Take a sip if you have ever bought a meal using the last of a foreign currency at the terminal.",
  "Take a sip if you have ever landed before your body clock knew what day it was.",
  "Take a sip if you have ever recognised your suitcase only because of a ribbon or sticker.",
  "Take a sip if you have ever found a quiet airport corner that felt like a secret lounge.",
  "Take a sip if you have ever watched a sunrise through a terminal window.",
  "Take a sip if you have ever had your carefully packed bag selected for an extra check.",
  "Take a sip if you have ever carried an empty reusable bottle through airport security.",
  "Take a sip if you have ever heard your name announced over an airport speaker.",

  "Take a sip if you have ever discovered that your room looked nothing like the listing photos.",
  "Take a sip if you have ever stayed somewhere with a view worth waking up early for.",
  "Take a sip if you have ever needed three attempts to unlock a hotel room door.",
  "Take a sip if you have ever slept in a bunk room with a world-class snorer.",
  "Take a sip if you have ever chosen accommodation mainly because breakfast was included.",
  "Take a sip if you have ever stayed with a host who gave better tips than any guidebook.",
  "Take a sip if you have ever found a towel folded into an unexpected animal.",
  "Take a sip if you have ever booked a room for its bathtub and never used it.",
  "Take a sip if you have ever stayed in a building older than your home town.",
  "Take a sip if you have ever heard every sound from the room next door.",
  "Take a sip if you have ever arrived before check-in and explored while carrying your bags.",
  "Take a sip if you have ever cooked a full meal in a very small holiday kitchen.",
  "Take a sip if you have ever slept somewhere unusual enough to become the trip's main story.",
  "Take a sip if you have ever extended a stay because the accommodation felt like home.",
  "Take a sip if you have ever checked under the bed before leaving for a forgotten item.",

  "Take a sip if you have ever followed a paper map after your phone battery died.",
  "Take a sip if you have ever downloaded an offline map before losing signal.",
  "Take a sip if you have ever walked in a confident direction while privately feeling lost.",
  "Take a sip if you have ever used a landmark instead of a street name to find your way.",
  "Take a sip if you have ever discovered a favourite place while taking a wrong turn.",
  "Take a sip if you have ever rotated a map repeatedly before understanding it.",
  "Take a sip if you have ever pinned your accommodation so you could find it after dark.",
  "Take a sip if you have ever asked two locals for directions and received opposite answers.",
  "Take a sip if you have ever navigated by following a river, coastline, or mountain.",
  "Take a sip if you have ever noticed that a short map distance involved a very steep hill.",
  "Take a sip if you have ever saved a place under a nickname only you understood.",
  "Take a sip if you have ever used a transit map as a souvenir.",
  "Take a sip if you have ever reached the correct street from the completely wrong end.",
  "Take a sip if you have ever relied on a compass when the path signs disappeared.",
  "Take a sip if you have ever become the group's navigator without volunteering.",

  "Take a sip if you have ever travelled somewhere mainly to taste a local dish.",
  "Take a sip if you have ever pointed at another table's meal to help place an order.",
  "Take a sip if you have ever found your best meal at a market stall.",
  "Take a sip if you have ever learned a food's name only after finishing it.",
  "Take a sip if you have ever queued for a famous snack and decided it was worth it.",
  "Take a sip if you have ever bought fruit you had never seen before.",
  "Take a sip if you have ever taken a cooking class while travelling.",
  "Take a sip if you have ever returned to the same cafe every morning of a trip.",
  "Take a sip if you have ever ordered the local breakfast when you wanted dinner food.",
  "Take a sip if you have ever carried a favourite condiment away as a souvenir.",
  "Take a sip if you have ever shared several small dishes so everyone could try them.",
  "Take a sip if you have ever confirmed ingredients across a language barrier before ordering.",
  "Take a sip if you have ever found a familiar comfort food prepared in an unfamiliar way.",
  "Take a sip if you have ever planned a walking route around bakeries or food stalls.",
  "Take a sip if you have ever recreated a holiday meal after returning home.",

  "Take a sip if you have ever learned a greeting in the local language before arrival.",
  "Take a sip if you have ever joined a celebration without knowing all its traditions.",
  "Take a sip if you have ever changed your clothing plans after learning a site's customs.",
  "Take a sip if you have ever asked before photographing a person, ceremony, or sacred place.",
  "Take a sip if you have ever attended a performance you understood without translation.",
  "Take a sip if you have ever learned the story behind a local craft from its maker.",
  "Take a sip if you have ever visited a place of worship outside your own tradition.",
  "Take a sip if you have ever checked a local tipping custom before paying.",
  "Take a sip if you have ever realised a familiar gesture meant something different abroad.",
  "Take a sip if you have ever listened to local music for the rest of a trip after hearing it live.",
  "Take a sip if you have ever joined a public dance after someone welcomed you in.",
  "Take a sip if you have ever visited a museum to understand a destination beyond its landmarks.",
  "Take a sip if you have ever learned a regional phrase that made residents smile.",
  "Take a sip if you have ever rearranged plans to respect a local day of rest.",
  "Take a sip if you have ever brought home a tradition rather than a physical souvenir.",

  "Take a sip if you have ever visited a landmark that felt smaller than expected.",
  "Take a sip if you have ever found a lesser-known attraction more memorable than the famous one.",
  "Take a sip if you have ever watched a city wake up before the crowds arrived.",
  "Take a sip if you have ever crossed a bridge simply for the view from the middle.",
  "Take a sip if you have ever planned a day around one museum and left at closing time.",
  "Take a sip if you have ever climbed a tower for a panorama of a new city.",
  "Take a sip if you have ever visited ruins and imagined the place when it was busy.",
  "Take a sip if you have ever taken a guided tour that completely changed your first impression.",
  "Take a sip if you have ever recognised a street from a film or television show.",
  "Take a sip if you have ever wandered through a neighbourhood with no attraction marked.",
  "Take a sip if you have ever visited a public library while on holiday.",
  "Take a sip if you have ever explored a destination from the top deck of a city bus.",
  "Take a sip if you have ever found public art that became your favourite photo backdrop.",
  "Take a sip if you have ever returned to a landmark at night to see it lit up.",
  "Take a sip if you have ever skipped a popular sight because the queue changed your mind.",

  "Take a sip if you have ever woken before dawn to watch the sun rise outdoors.",
  "Take a sip if you have ever stood somewhere quiet enough to hear only the landscape.",
  "Take a sip if you have ever changed plans because the weather transformed the scenery.",
  "Take a sip if you have ever seen wildlife from a respectful distance on a trip.",
  "Take a sip if you have ever packed out every piece of litter you carried into nature.",
  "Take a sip if you have ever chosen a marked trail after reconsidering a risky shortcut.",
  "Take a sip if you have ever visited both a beach and a mountain on the same holiday.",
  "Take a sip if you have ever heard a waterfall before you could see it.",
  "Take a sip if you have ever watched a sunset that silenced the whole group.",
  "Take a sip if you have ever worn the wrong shoes for an otherwise wonderful walk.",
  "Take a sip if you have ever learned a landscape's Indigenous name while visiting.",
  "Take a sip if you have ever taken a boat to reach a protected natural area.",
  "Take a sip if you have ever visited a garden in a season you did not expect to enjoy.",
  "Take a sip if you have ever had a picnic interrupted by determined birds.",
  "Take a sip if you have ever planned an entire day around the tide or weather forecast.",

  "Take a sip if you have ever taken a trip alone and surprised yourself with your confidence.",
  "Take a sip if you have ever eaten alone in a restaurant while travelling.",
  "Take a sip if you have ever joined a day tour to meet people during a solo journey.",
  "Take a sip if you have ever changed solo plans because your instincts said to leave.",
  "Take a sip if you have ever asked a stranger to take your photo at a viewpoint.",
  "Take a sip if you have ever enjoyed choosing every stop without negotiating.",
  "Take a sip if you have ever shared your itinerary with someone you trust before travelling alone.",
  "Take a sip if you have ever made a new friend in a hostel common room or guesthouse kitchen.",
  "Take a sip if you have ever spent an afternoon alone without speaking to anyone.",
  "Take a sip if you have ever booked a group activity as a break from solo sightseeing.",
  "Take a sip if you have ever felt homesick in a beautiful place.",
  "Take a sip if you have ever celebrated solving a travel problem entirely on your own.",
  "Take a sip if you have ever kept a regular check-in plan during a solo trip.",
  "Take a sip if you have ever discovered that travelling alone changed your pace.",
  "Take a sip if you have ever extended a solo journey after finding your rhythm.",

  "Take a sip if you have ever used a group poll to choose a destination.",
  "Take a sip if you have ever been ready while everyone else was still packing.",
  "Take a sip if you have ever split into smaller groups and enjoyed comparing stories later.",
  "Take a sip if you have ever created a shared budget before a friends' trip.",
  "Take a sip if you have ever let each traveller choose one must-do activity.",
  "Take a sip if you have ever mediated a debate about where the group should eat.",
  "Take a sip if you have ever shared a room with a friend who follows a completely different sleep schedule.",
  "Take a sip if you have ever invented a trip nickname that stayed in the group chat.",
  "Take a sip if you have ever waited at a meeting point for someone who went to a different entrance.",
  "Take a sip if you have ever volunteered to track shared expenses.",
  "Take a sip if you have ever changed an activity so everyone in the group could participate.",
  "Take a sip if you have ever needed quiet time during a very social holiday.",
  "Take a sip if you have ever travelled with relatives from more than one generation.",
  "Take a sip if you have ever let the hungriest person choose the next stop.",
  "Take a sip if you have ever returned from a group trip with a new inside joke.",

  "Take a sip if you have ever checked step-free routes before setting out.",
  "Take a sip if you have ever contacted a venue in advance about an access need.",
  "Take a sip if you have ever built rest breaks into a sightseeing day.",
  "Take a sip if you have ever chosen transport based on comfort rather than speed.",
  "Take a sip if you have ever confirmed that an assistive device could travel safely with you.",
  "Take a sip if you have ever selected quieter travel times to make a journey easier.",
  "Take a sip if you have ever found that a promised lift or ramp was unavailable.",
  "Take a sip if you have ever asked for information in a format you could use.",
  "Take a sip if you have ever carried details of your access requirements in another language.",
  "Take a sip if you have ever appreciated staff who offered help without making assumptions.",
  "Take a sip if you have ever changed accommodation because its access details were unclear.",
  "Take a sip if you have ever planned around medication storage or a medical routine.",
  "Take a sip if you have ever used a sensory-friendly hour at an attraction.",
  "Take a sip if you have ever found an accessible route with a better view than the original plan.",
  "Take a sip if you have ever shared accurate accessibility information after a trip.",

  "Take a sip if you have ever saved copies of important documents somewhere separate from the originals.",
  "Take a sip if you have ever checked official travel advice before departure.",
  "Take a sip if you have ever memorised the name or address of your accommodation.",
  "Take a sip if you have ever kept emergency contacts available offline.",
  "Take a sip if you have ever moved away from a situation because it did not feel right.",
  "Take a sip if you have ever verified a ride's details before getting in.",
  "Take a sip if you have ever carried a portable charger for navigation and emergencies.",
  "Take a sip if you have ever checked local laws that differed from those at home.",
  "Take a sip if you have ever agreed on a reunion point in case your group became separated.",
  "Take a sip if you have ever kept valuables out of sight on public transport.",
  "Take a sip if you have ever changed a day's plan because of an official weather warning.",
  "Take a sip if you have ever arranged trusted transport before arriving late at night.",
  "Take a sip if you have ever told someone when you expected to return from an outing.",
  "Take a sip if you have ever learned how to contact local emergency services.",
  "Take a sip if you have ever chosen a well-lit route even though it took longer.",

  "Take a sip if you have ever saved for a trip using a dedicated travel fund.",
  "Take a sip if you have ever converted prices in your head before buying anything abroad.",
  "Take a sip if you have ever discovered a bank fee only after checking your statement.",
  "Take a sip if you have ever set a daily budget and spent most of it before lunch.",
  "Take a sip if you have ever chosen a free walking route over a paid attraction.",
  "Take a sip if you have ever tracked group costs in more than one currency.",
  "Take a sip if you have ever kept a small emergency fund separate from spending money.",
  "Take a sip if you have ever negotiated which travel experience was worth a splurge.",
  "Take a sip if you have ever used public transport to make a destination affordable.",
  "Take a sip if you have ever returned home with coins nobody would exchange.",
  "Take a sip if you have ever found your favourite activity cost nothing.",
  "Take a sip if you have ever compared booking directly with using a travel platform.",
  "Take a sip if you have ever cancelled a purchase after doing the currency conversion.",
  "Take a sip if you have ever budgeted extra for taxes or fees that appeared at checkout.",
  "Take a sip if you have ever kept a receipt because the design felt like a souvenir.",

  "Take a sip if you have ever bought a postcard and forgotten to send it.",
  "Take a sip if you have ever collected a ticket stub from a memorable journey.",
  "Take a sip if you have ever chosen a handmade souvenir after meeting its maker.",
  "Take a sip if you have ever brought home a snack and saved it too long for a special occasion.",
  "Take a sip if you have ever searched for a gift that represented a place without being generic.",
  "Take a sip if you have ever carried a fragile souvenir through several connections.",
  "Take a sip if you have ever kept a transit card after its final journey.",
  "Take a sip if you have ever bought something useful that still reminds you of a trip.",
  "Take a sip if you have ever mailed a purchase home rather than fitting it in your luggage.",
  "Take a sip if you have ever regretted not buying a small item you saw while travelling.",
  "Take a sip if you have ever started a collection because of one holiday purchase.",
  "Take a sip if you have ever pressed a leaf or flower where local rules permitted it.",
  "Take a sip if you have ever brought back a recipe from a market vendor.",
  "Take a sip if you have ever found the perfect souvenir in an ordinary grocery shop.",
  "Take a sip if you have ever gifted someone the last item you expected to part with.",

  "Take a sip if you have ever taken so many photos that you forgot to look around.",
  "Take a sip if you have ever woken early to photograph an empty street.",
  "Take a sip if you have ever recreated an old family travel photo.",
  "Take a sip if you have ever kept a travel journal beyond the first few days.",
  "Take a sip if you have ever recorded ambient sounds to remember a place.",
  "Take a sip if you have ever asked permission before including someone in a travel photo.",
  "Take a sip if you have ever made a trip playlist and replayed it after coming home.",
  "Take a sip if you have ever backed up your photos before the journey ended.",
  "Take a sip if you have ever discovered a stranger's funny expression in the background of a picture.",
  "Take a sip if you have ever printed travel photos instead of leaving them on your phone.",
  "Take a sip if you have ever remembered a day clearly because you took no pictures.",
  "Take a sip if you have ever written down a phrase so you would not forget how it sounded.",
  "Take a sip if you have ever made a photo book months after returning.",
  "Take a sip if you have ever kept a daily note of one surprising travel moment.",
  "Take a sip if you have ever sent a voice note home from a place you loved.",

  "Take a sip if you have ever arrived during rain with no waterproof layer.",
  "Take a sip if you have ever opened an umbrella just as the rain stopped.",
  "Take a sip if you have ever packed for sunshine and found unexpected cold.",
  "Take a sip if you have ever watched fog hide the exact view you came to see.",
  "Take a sip if you have ever changed a beach day into a museum day.",
  "Take a sip if you have ever bought weather gear that became an accidental souvenir.",
  "Take a sip if you have ever experienced snow for the first time while travelling.",
  "Take a sip if you have ever waited out a storm in a welcoming cafe.",
  "Take a sip if you have ever seen a rainbow improve a delayed journey.",
  "Take a sip if you have ever underestimated how early the sun would set.",
  "Take a sip if you have ever carried sunscreen all day and forgotten to apply it.",
  "Take a sip if you have ever planned around midday heat like a local.",
  "Take a sip if you have ever encountered four seasons during one outing.",
  "Take a sip if you have ever changed altitude and felt the temperature drop immediately.",
  "Take a sip if you have ever enjoyed a destination more because it was off-season.",

  "Take a sip if you have ever taken a wrong exit and found something worth stopping for.",
  "Take a sip if you have ever forgotten where you parked in an unfamiliar town.",
  "Take a sip if you have ever carried a room key out and returned it just in time.",
  "Take a sip if you have ever waved enthusiastically at the wrong tour guide.",
  "Take a sip if you have ever boarded the correct route travelling in the wrong direction.",
  "Take a sip if you have ever confused two places with nearly identical names.",
  "Take a sip if you have ever discovered a leaking toiletry after opening your bag.",
  "Take a sip if you have ever tried to enter your accommodation through the wrong door.",
  "Take a sip if you have ever carried a souvenir all day after forgetting to return to your room.",
  "Take a sip if you have ever misread a timetable and gained an unexpected free hour.",
  "Take a sip if you have ever ordered far more food than the menu photo suggested.",
  "Take a sip if you have ever posed for a photo while a landmark was hidden behind you.",
  "Take a sip if you have ever packed matching socks and returned with an unmatched pair.",
  "Take a sip if you have ever walked back for something that was already in your pocket.",
  "Take a sip if you have ever laughed after a harmless travel mistake became a favourite story.",

  "Take a sip if you have ever travelled overnight to gain an extra day at your destination.",
  "Take a sip if you have ever watched a border change through a train window.",
  "Take a sip if you have ever taken a road trip with a playlist everyone helped build.",
  "Take a sip if you have ever stopped at a roadside attraction on a whim.",
  "Take a sip if you have ever shared driving duties on a long journey.",
  "Take a sip if you have ever taken a rest break because the driver needed one.",
  "Take a sip if you have ever travelled by sleeper train and actually slept well.",
  "Take a sip if you have ever watched the landscape change gradually across several hours.",
  "Take a sip if you have ever eaten a packed meal at a service station or rest stop.",
  "Take a sip if you have ever made a detour based on a handwritten sign.",
  "Take a sip if you have ever crossed a time zone without flying.",
  "Take a sip if you have ever played a word or spotting game during a long journey.",
  "Take a sip if you have ever chosen a roadside motel because continuing felt unwise.",
  "Take a sip if you have ever seen a destination sign and felt the trip suddenly become real.",
  "Take a sip if you have ever reached the end of a long route and wished it continued.",

]
