export const TAKE_SIP_SPICY = [
  "Take a sip if you have ever rehearsed a flirty message before sending it.",
  "Take a sip if you have ever caught yourself smiling at a message from a crush.",
  "Take a sip if you have ever made the first move with someone you genuinely liked.",
  "Take a sip if you have ever flirted through a shared playlist.",
  "Take a sip if you have ever used an inside joke to keep a conversation going.",
  "Take a sip if you have ever dressed with one particular person's attention in mind.",
  "Take a sip if you have ever held eye contact longer because the chemistry felt mutual.",
  "Take a sip if you have ever given someone your number without being asked.",
  "Take a sip if you have ever sent a compliment that felt unusually bold for you.",
  "Take a sip if you have ever wondered whether friendly teasing was actually flirting.",
  "Take a sip if you have ever flirted with someone through a competitive game.",
  "Take a sip if you have ever found a reason to sit closer to a crush.",
  "Take a sip if you have ever changed your route hoping to casually see someone you liked.",
  "Take a sip if you have ever let a conversation run late because neither of you wanted to leave.",
  "Take a sip if you have ever used a reaction emoji as a low-risk way to flirt.",
  "Take a sip if you have ever initiated a conversation because someone had an irresistible smile.",
  "Take a sip if you have ever felt instant chemistry during an ordinary introduction.",
  "Take a sip if you have ever exchanged a look with someone that felt like a full conversation.",
  "Take a sip if you have ever tried to sound casual while inviting a crush somewhere.",
  "Take a sip if you have ever complimented someone's voice because you found it attractive.",
  "Take a sip if you have ever flirted by remembering a tiny detail someone mentioned.",
  "Take a sip if you have ever become more interested after hearing someone laugh.",
  "Take a sip if you have ever felt butterflies before seeing a particular person.",
  "Take a sip if you have ever noticed mutual attraction before either person said anything.",
  "Take a sip if you have ever made someone blush with a sincere compliment.",
  "Take a sip if you have ever chosen a seat because it offered the best chance to talk to a crush.",
  "Take a sip if you have ever flirted while pretending to debate something trivial.",
  "Take a sip if you have ever asked a friend whether someone seemed interested in you.",
  "Take a sip if you have ever felt more chemistry in person than you expected online.",
  "Take a sip if you have ever been pleasantly surprised when someone flirted back.",
  "Take a sip if you have ever had a crush on someone you initially overlooked.",
  "Take a sip if you have ever developed a crush after one unexpectedly deep conversation.",
  "Take a sip if you have ever tried to hide a crush from your friends.",
  "Take a sip if you have ever realized your friends knew about your crush before you admitted it.",
  "Take a sip if you have ever liked someone whose personality surprised you.",
  "Take a sip if you have ever had a crush on someone with a completely different style from yours.",
  "Take a sip if you have ever rediscovered a crush after meeting someone again years later.",
  "Take a sip if you have ever had a harmless crush on someone you saw regularly but barely knew.",
  "Take a sip if you have ever confused admiration with a crush at first.",
  "Take a sip if you have ever lost interest the moment your crush liked you back.",
  "Take a sip if you have ever been surprised by who became your type.",
  "Take a sip if you have ever had two crushes at the same time.",
  "Take a sip if you have ever developed feelings for someone after insisting you were only friends.",
  "Take a sip if you have ever had a crush on someone who challenged your opinions respectfully.",
  "Take a sip if you have ever found competence unexpectedly attractive.",
  "Take a sip if you have ever found kindness more attractive than appearance.",
  "Take a sip if you have ever been drawn to someone because they made you feel understood.",
  "Take a sip if you have ever questioned your usual type after meeting someone compelling.",
  "Take a sip if you have ever had a crush fade after one disappointing conversation.",
  "Take a sip if you have ever admitted a crush and felt relieved regardless of the answer.",
  "Take a sip if you have ever learned that a past crush had liked you too.",
  "Take a sip if you have ever written about a crush without naming them.",
  "Take a sip if you have ever made a playlist inspired by someone you liked.",
  "Take a sip if you have ever had a crush become obvious through your body language.",
  "Take a sip if you have ever been attracted to someone's confidence without finding them arrogant.",
  "Take a sip if you have ever noticed your attraction grow as trust developed.",
  "Take a sip if you have ever been intrigued by someone who was difficult to read.",
  "Take a sip if you have ever felt attracted to someone after watching them be thoughtful with others.",
  "Take a sip if you have ever surprised yourself by confessing feelings first.",
  "Take a sip if you have ever decided a crush was better left as a crush.",
  "Take a sip if you have ever kissed someone after asking whether they wanted to.",
  "Take a sip if you have ever been asked for a kiss in a way that made you feel respected.",
  "Take a sip if you have ever shared a first kiss that was worth the anticipation.",
  "Take a sip if you have ever laughed during a kiss and liked the moment more because of it.",
  "Take a sip if you have ever kissed someone after a date you wished would not end.",
  "Take a sip if you have ever paused a kiss to check that you were both comfortable.",
  "Take a sip if you have ever had a goodbye kiss turn into a much longer goodbye.",
  "Take a sip if you have ever kissed someone in the rain and enjoyed the cliché.",
  "Take a sip if you have ever felt nervous right before a mutually wanted kiss.",
  "Take a sip if you have ever initiated a kiss after receiving a clear invitation.",
  "Take a sip if you have ever stopped a kiss when the mood no longer felt right.",
  "Take a sip if you have ever appreciated someone checking in before getting closer.",
  "Take a sip if you have ever kissed a friend after discussing what it might mean.",
  "Take a sip if you have ever shared a kiss that clarified your feelings.",
  "Take a sip if you have ever shared a kiss that made you realize the chemistry was missing.",
  "Take a sip if you have ever kissed someone at midnight on New Year's Eve.",
  "Take a sip if you have ever had a first kiss interrupted by something funny.",
  "Take a sip if you have ever asked to slow down during a romantic moment.",
  "Take a sip if you have ever felt safer because someone immediately respected your pause.",
  "Take a sip if you have ever talked about boundaries before a date became more intimate.",
  "Take a sip if you have ever changed your mind about a kiss and said so clearly.",
  "Take a sip if you have ever responded graciously when someone changed their mind about kissing.",
  "Take a sip if you have ever preferred a forehead kiss to a dramatic romantic gesture.",
  "Take a sip if you have ever remembered a great kiss because of the conversation around it.",
  "Take a sip if you have ever kissed someone somewhere unexpectedly romantic.",
  "Take a sip if you have ever waited several dates before sharing a first kiss.",
  "Take a sip if you have ever decided not to kiss on a first date despite strong chemistry.",
  "Take a sip if you have ever felt a kiss become meaningful only after getting to know someone.",
  "Take a sip if you have ever had to clarify whether a near-kiss was actually wanted.",
  "Take a sip if you have ever found respectful restraint surprisingly attractive.",
  "Take a sip if you have ever matched with someone you already knew in real life.",
  "Take a sip if you have ever rewritten your dating profile to sound more like yourself.",
  "Take a sip if you have ever opened with a message about a specific profile detail.",
  "Take a sip if you have ever deleted a dating app and downloaded it again later.",
  "Take a sip if you have ever had a dating-app conversation become a real relationship.",
  "Take a sip if you have ever recognized a friend while swiping on a dating app.",
  "Take a sip if you have ever matched with someone because their bio made you laugh.",
  "Take a sip if you have ever unmatched someone after they ignored a stated boundary.",
  "Take a sip if you have ever moved from an app to a phone call before meeting.",
  "Take a sip if you have ever verified that an online match was genuine before a date.",
  "Take a sip if you have ever chosen a public place for a first app date.",
  "Take a sip if you have ever told a friend your plans before meeting an online match.",
  "Take a sip if you have ever ended an app conversation because the energy felt wrong.",
  "Take a sip if you have ever been more attracted to a profile's humor than its photos.",
  "Take a sip if you have ever asked an unusually good question in an opening message.",
  "Take a sip if you have ever received an opening message that genuinely impressed you.",
  "Take a sip if you have ever spotted a deal-breaker directly in a dating profile.",
  "Take a sip if you have ever appreciated someone being clear about what they wanted on an app.",
  "Take a sip if you have ever updated your profile after friends gave honest feedback.",
  "Take a sip if you have ever taken a break from dating apps for your peace of mind.",
  "Take a sip if you have ever matched with someone while travelling and actually met for a date.",
  "Take a sip if you have ever had an app date feel better than the messages suggested.",
  "Take a sip if you have ever had excellent messages lead to no chemistry in person.",
  "Take a sip if you have ever politely declined a second date after meeting an online match.",
  "Take a sip if you have ever received a kind rejection through a dating app.",
  "Take a sip if you have ever bonded with a match over a niche interest.",
  "Take a sip if you have ever noticed the same person on more than one dating app.",
  "Take a sip if you have ever preferred a voice note to endless app messaging.",
  "Take a sip if you have ever asked a match what a good first date looked like to them.",
  "Take a sip if you have ever turned off app notifications to make dating feel less consuming.",
  "Take a sip if you have ever sent a bold message and put your phone face down immediately.",
  "Take a sip if you have ever directly told someone you found them attractive.",
  "Take a sip if you have ever invited someone on a date without disguising it as a group plan.",
  "Take a sip if you have ever sent a message admitting you wanted to see someone again.",
  "Take a sip if you have ever used a voice note to say something you could not type.",
  "Take a sip if you have ever replied to a flirty message with equal confidence.",
  "Take a sip if you have ever drafted a risky message in your notes first.",
  "Take a sip if you have ever sent a late-night message while completely clear-headed.",
  "Take a sip if you have ever asked someone to clarify the tone of a suggestive message.",
  "Take a sip if you have ever deleted an unsent message because it crossed your own boundary.",
  "Take a sip if you have ever welcomed a playful compliment and said so.",
  "Take a sip if you have ever told someone their flirting was making you uncomfortable.",
  "Take a sip if you have ever received a respectful response after setting a texting boundary.",
  "Take a sip if you have ever admitted over text that you could not stop thinking about someone.",
  "Take a sip if you have ever asked someone out in a message that left no room for confusion.",
  "Take a sip if you have ever sent the first message after exchanging numbers.",
  "Take a sip if you have ever revived a stalled conversation with unexpected honesty.",
  "Take a sip if you have ever chosen not to send a message that felt unfair to the recipient.",
  "Take a sip if you have ever expressed romantic interest without expecting an immediate reply.",
  "Take a sip if you have ever received a flirty message at exactly the right moment.",
  "Take a sip if you have ever sent a song instead of explaining how you felt.",
  "Take a sip if you have ever used a meme to test whether someone shared your sense of humor.",
  "Take a sip if you have ever asked before sending a more personal photo.",
  "Take a sip if you have ever declined a photo request without apologizing for your boundary.",
  "Take a sip if you have ever complimented a date through text before you got home.",
  "Take a sip if you have ever received a good-morning message that changed your whole mood.",
  "Take a sip if you have ever waited to respond because you wanted to choose your words carefully.",
  "Take a sip if you have ever corrected a misunderstanding before a flirtation became awkward.",
  "Take a sip if you have ever sent a message that made a friendship feel newly romantic.",
  "Take a sip if you have ever been honest that you preferred talking in person to texting.",
  "Take a sip if you have ever gone on a first date that lasted far longer than planned.",
  "Take a sip if you have ever planned a first date around a shared obsession.",
  "Take a sip if you have ever arrived early because you were excited for a date.",
  "Take a sip if you have ever changed outfits several times before a date.",
  "Take a sip if you have ever known within minutes that you wanted a second date.",
  "Take a sip if you have ever realized halfway through a date that you were not compatible.",
  "Take a sip if you have ever gracefully ended a date that was going nowhere.",
  "Take a sip if you have ever split the bill after an honest conversation about preferences.",
  "Take a sip if you have ever planned a date that cost almost nothing but felt special.",
  "Take a sip if you have ever gone on a date built around trying something new together.",
  "Take a sip if you have ever had a date derailed by terrible weather.",
  "Take a sip if you have ever laughed with a date about an awkward silence.",
  "Take a sip if you have ever mistaken a friendly hangout for a date.",
  "Take a sip if you have ever discovered halfway through that the other person thought it was a date.",
  "Take a sip if you have ever clarified whether an invitation was romantic before accepting.",
  "Take a sip if you have ever gone on a date with someone outside your usual type.",
  "Take a sip if you have ever had a memorable date at a completely ordinary place.",
  "Take a sip if you have ever chosen an activity date to avoid interview-style conversation.",
  "Take a sip if you have ever gone on a double date that became unexpectedly revealing.",
  "Take a sip if you have ever declined a date because the timing was wrong despite the attraction.",
  "Take a sip if you have ever accepted a spontaneous date and been glad you did.",
  "Take a sip if you have ever rescheduled a date instead of pretending you were available.",
  "Take a sip if you have ever had a date accidentally include someone else's friends.",
  "Take a sip if you have ever forgotten your date's name during an early conversation.",
  "Take a sip if you have ever spilled something on yourself during a promising date.",
  "Take a sip if you have ever told a terrible joke because date nerves took over.",
  "Take a sip if you have ever waved at the wrong person while waiting for a date.",
  "Take a sip if you have ever been stood up and chosen to enjoy the outing anyway.",
  "Take a sip if you have ever stayed friends with someone after one date was enough.",
  "Take a sip if you have ever sent a clear follow-up after enjoying a first date.",
  "Take a sip if you have ever taken a romantic risk that worked out better than expected.",
  "Take a sip if you have ever taken a romantic risk that taught you resilience.",
  "Take a sip if you have ever asked someone out face-to-face despite being nervous.",
  "Take a sip if you have ever travelled a reasonable distance for a promising date.",
  "Take a sip if you have ever admitted your feelings without knowing whether they were mutual.",
  "Take a sip if you have ever given a connection a chance despite imperfect timing.",
  "Take a sip if you have ever turned down a safe choice to pursue a stronger connection.",
  "Take a sip if you have ever reconnected with someone after both of you had grown.",
  "Take a sip if you have ever risked changing a friendship by discussing mutual attraction.",
  "Take a sip if you have ever attended an event mainly because someone you liked would be there.",
  "Take a sip if you have ever introduced yourself to someone after nearly losing the chance.",
  "Take a sip if you have ever asked for a second date before the first one ended.",
  "Take a sip if you have ever let someone see your sentimental side earlier than usual.",
  "Take a sip if you have ever shared an embarrassing story to make a date feel less nervous.",
  "Take a sip if you have ever been honest about wanting commitment when it felt risky.",
  "Take a sip if you have ever been honest about wanting something casual without leading anyone on.",
  "Take a sip if you have ever left your comfort zone for a romantic gesture that suited the recipient.",
  "Take a sip if you have ever trusted a friend to set you up on a date.",
  "Take a sip if you have ever gone to a singles event alone.",
  "Take a sip if you have ever approached someone at a social event and started a genuine conversation.",
  "Take a sip if you have ever returned to dating after a long break.",
  "Take a sip if you have ever asked someone whether they were available before flirting further.",
  "Take a sip if you have ever risked rejection rather than staying ambiguous.",
  "Take a sip if you have ever been proud of how kindly you handled romantic rejection.",
  "Take a sip if you have ever thanked someone for being direct about not feeling a connection.",
  "Take a sip if you have ever offered a sincere apology after sending mixed romantic signals.",
  "Take a sip if you have ever chosen honesty over keeping an easy situationship going.",
  "Take a sip if you have ever felt jealous and talked about it without making accusations.",
  "Take a sip if you have ever realized jealousy was pointing to an unmet need.",
  "Take a sip if you have ever asked for reassurance instead of testing someone's loyalty.",
  "Take a sip if you have ever apologized for acting distant when you were actually jealous.",
  "Take a sip if you have ever been surprised by jealousy before a relationship was defined.",
  "Take a sip if you have ever taken time to cool down before discussing jealousy.",
  "Take a sip if you have ever admitted that comparison was affecting your confidence.",
  "Take a sip if you have ever felt jealous of the attention a crush gave someone else.",
  "Take a sip if you have ever decided jealousy was yours to process rather than someone else's fault.",
  "Take a sip if you have ever had a calm conversation about what counted as flirting.",
  "Take a sip if you have ever clarified exclusivity instead of relying on assumptions.",
  "Take a sip if you have ever respected a partner's friendships even when you felt insecure.",
  "Take a sip if you have ever reassured someone without surrendering a reasonable boundary.",
  "Take a sip if you have ever realized you were competing for attention that was not being offered.",
  "Take a sip if you have ever stepped back from a love triangle to protect your peace.",
  "Take a sip if you have ever refused to compare yourself with someone's former partner.",
  "Take a sip if you have ever muted social media temporarily to manage romantic jealousy.",
  "Take a sip if you have ever questioned whether possessiveness was being mistaken for passion.",
  "Take a sip if you have ever supported someone you liked choosing a different connection.",
  "Take a sip if you have ever recognized that attraction did not entitle you to attention.",
  "Take a sip if you have ever stated a dating boundary before it became a problem.",
  "Take a sip if you have ever left a date after a boundary was dismissed.",
  "Take a sip if you have ever asked what someone was comfortable with before making plans.",
  "Take a sip if you have ever respected a no without asking for an explanation.",
  "Take a sip if you have ever said no to a romantic invitation you genuinely considered.",
  "Take a sip if you have ever changed a date plan so everyone involved felt comfortable.",
  "Take a sip if you have ever discussed public affection preferences with someone you were dating.",
  "Take a sip if you have ever asked before sharing a romantic photo involving another person.",
  "Take a sip if you have ever kept a private romantic detail private despite friends asking.",
  "Take a sip if you have ever corrected friends who pushed you to pursue someone uninterested.",
  "Take a sip if you have ever told a friend not to share someone else's dating business.",
  "Take a sip if you have ever declined to define a relationship in front of other people.",
  "Take a sip if you have ever asked permission before posting about a new relationship.",
  "Take a sip if you have ever removed a dating photo when the other person withdrew permission.",
  "Take a sip if you have ever requested more personal space without ending the connection.",
  "Take a sip if you have ever honored someone's request for more personal space.",
  "Take a sip if you have ever discussed communication frequency before resentment built up.",
  "Take a sip if you have ever said you were not ready for a label.",
  "Take a sip if you have ever accepted that someone else needed a label you could not offer.",
  "Take a sip if you have ever ended a connection because your relationship expectations differed.",
  "Take a sip if you have ever asked before bringing a date to a personal gathering.",
  "Take a sip if you have ever arranged your own transportation for a first date.",
  "Take a sip if you have ever shared your live plans with a trusted friend for date safety.",
  "Take a sip if you have ever used a check-in plan while meeting someone new.",
  "Take a sip if you have ever trusted your instincts and left an uncomfortable date.",
  "Take a sip if you have ever helped a friend leave a date without demanding details.",
  "Take a sip if you have ever made it clear that a date could end whenever either person wanted.",
  "Take a sip if you have ever admired someone more after they handled a boundary maturely.",
  "Take a sip if you have ever had your attraction deepen after an honest conversation about consent.",
  "Take a sip if you have ever been single and genuinely content with it.",
  "Take a sip if you have ever taken yourself on a date.",
  "Take a sip if you have ever celebrated being single on a traditionally romantic holiday.",
  "Take a sip if you have ever enjoyed flirting without wanting it to become a relationship.",
  "Take a sip if you have ever paused dating to focus on your own priorities.",
  "Take a sip if you have ever deleted dating apps because single life felt better.",
  "Take a sip if you have ever declined a setup because you were not looking to date.",
  "Take a sip if you have ever been the happily single person in a group of couples.",
  "Take a sip if you have ever bought yourself something you once hoped a partner would give you.",
  "Take a sip if you have ever gone alone to an event people assumed required a date.",
  "Take a sip if you have ever corrected someone who treated being single like a problem.",
  "Take a sip if you have ever preferred a quiet night alone to an unpromising date.",
  "Take a sip if you have ever enjoyed being the only person responsible for your weekend plans.",
  "Take a sip if you have ever realized loneliness and readiness to date were not the same thing.",
  "Take a sip if you have ever stopped chasing a connection that required constant guessing.",
  "Take a sip if you have ever raised your standards after a period of being single.",
  "Take a sip if you have ever learned something important about your type while single.",
  "Take a sip if you have ever felt relieved when a promising flirtation did not progress.",
  "Take a sip if you have ever chosen friendship when romance was possible.",
  "Take a sip if you have ever turned down attention because it did not align with what you wanted.",
  "Take a sip if you have ever enjoyed a wedding without bringing a date.",
  "Take a sip if you have ever travelled solo and enjoyed your own company.",
  "Take a sip if you have ever made a major life decision without factoring in a romantic partner.",
  "Take a sip if you have ever built a fulfilling routine that made dating feel optional.",
  "Take a sip if you have ever been open to love without actively searching for it.",
  "Take a sip if you have ever realized you missed companionship more than a particular person.",
  "Take a sip if you have ever refused to settle just to avoid being single.",
  "Take a sip if you have ever enjoyed being your friends' calm voice during dating drama.",
  "Take a sip if you have ever redefined what romance means to you while single.",
  "Take a sip if you have ever felt attractive without needing romantic validation.",
  "Take a sip if you have ever had undeniable chemistry with someone at an inconvenient time.",
  "Take a sip if you have ever felt chemistry build slowly over several meetings.",
  "Take a sip if you have ever mistaken nervousness for chemistry.",
  "Take a sip if you have ever discovered that witty conversation was your strongest source of attraction.",
  "Take a sip if you have ever felt drawn to someone because silence with them felt comfortable.",
  "Take a sip if you have ever been attracted to someone after seeing their creative work.",
  "Take a sip if you have ever found someone's passion for a hobby captivating.",
  "Take a sip if you have ever noticed attraction disappear after values came up in conversation.",
  "Take a sip if you have ever felt chemistry return after resolving a misunderstanding.",
  "Take a sip if you have ever wondered whether a friendship had hidden romantic tension.",
  "Take a sip if you have ever had mutual attraction become obvious to everyone else first.",
  "Take a sip if you have ever felt sparks during a dance with someone.",
  "Take a sip if you have ever been attracted to someone who remembered your favorite thing.",
  "Take a sip if emotional availability has ever made someone especially attractive to you.",
] as const satisfies readonly string[]
