export const TAKE_SIP_PARTY = [
  "Take a sip if you have ever learned a dance move five minutes before a party.",
  "Take a sip if you have ever started dancing before anyone else joined in.",
  "Take a sip if you have ever danced with a snack still in your hand.",
  "Take a sip if you have ever invented a dance move by accident.",
  "Take a sip if you have ever joined a dance circle without knowing what to do next.",
  "Take a sip if you have ever danced in shoes that looked better than they felt.",
  "Take a sip if you have ever turned a quiet corner into a tiny dance floor.",
  "Take a sip if you have ever celebrated when your favorite dance song came on.",
  "Take a sip if you have ever tried a choreographed group dance from memory.",
  "Take a sip if you have ever taken a dance break while helping with party setup.",
  "Take a sip if you have ever danced your way across a room instead of walking.",
  "Take a sip if you have ever used dramatic hand movements to carry a dance.",
  "Take a sip if you have ever joined a conga line after it was already moving.",
  "Take a sip if you have ever been surprised by your own dance-floor confidence.",
  "Take a sip if you have ever danced under party lights that changed your whole mood.",
  "Take a sip if you have ever attempted a spin and finished facing the wrong direction.",
  "Take a sip if you have ever cheered for someone taking the center of the dance floor.",
  "Take a sip if you have ever practiced a party dance in front of a mirror.",
  "Take a sip if you have ever kept dancing after the music briefly stopped.",
  "Take a sip if you have ever turned cleanup into a dance session.",
  "Take a sip if you have ever ended a dance with an unplanned dramatic pose.",
  "Take a sip if you have ever requested a song and waited all night to hear it.",
  "Take a sip if you have ever recognized a song from its opening second.",
  "Take a sip if you have ever sung the wrong lyric with complete confidence.",
  "Take a sip if you have ever helped build a party playlist.",
  "Take a sip if you have ever discovered a new favorite song at a celebration.",
  "Take a sip if you have ever debated which song should start the party.",
  "Take a sip if you have ever queued a throwback that brought everyone together.",
  "Take a sip if you have ever lowered the music so someone could make an announcement.",
  "Take a sip if you have ever heard the same party anthem twice in one night.",
  "Take a sip if you have ever taken charge of the speaker connection.",
  "Take a sip if you have ever saved a playlist for a future celebration.",
  "Take a sip if you have ever chosen background music to match a party theme.",
  "Take a sip if you have ever bonded with someone over an unexpected music taste.",
  "Take a sip if you have ever noticed the room change when the tempo picked up.",
  "Take a sip if you have ever been handed control of the music without warning.",
  "Take a sip if you have ever sung a chorus louder than the speakers.",
  "Take a sip if you have ever enjoyed a live musician at a celebration.",
  "Take a sip if you have ever clapped along before finding the beat.",
  "Take a sip if you have ever changed the playlist to suit a mixed-age crowd.",
  "Take a sip if you have ever used a makeshift object as a pretend microphone.",
  "Take a sip if you have ever joined a singalong from across the room.",
  "Take a sip if you have ever worn a costume that needed a last-minute repair.",
  "Take a sip if you have ever made a costume from things already at home.",
  "Take a sip if you have ever arrived in costume before confirming the theme.",
  "Take a sip if you have ever coordinated a group costume with friends.",
  "Take a sip if you have ever explained your costume more than once in an evening.",
  "Take a sip if you have ever chosen comfort over accuracy for a costume.",
  "Take a sip if you have ever recognized an obscure costume immediately.",
  "Take a sip if you have ever worn a hat that became the star of your outfit.",
  "Take a sip if you have ever helped someone finish their costume at the venue.",
  "Take a sip if you have ever reused a costume piece for a completely different theme.",
  "Take a sip if you have ever dressed as a pun for a themed event.",
  "Take a sip if you have ever mistaken regular clothing for a clever costume.",
  "Take a sip if you have ever committed to face paint for an entire party.",
  "Take a sip if you have ever built an outfit around the party invitation.",
  "Take a sip if you have ever received compliments on a homemade accessory.",
  "Take a sip if you have ever carried a costume prop that was awkward to store.",
  "Take a sip if you have ever changed out of part of a costume halfway through an event.",
  "Take a sip if you have ever voted in a costume contest.",
  "Take a sip if you have ever interpreted a dress code differently from everyone else.",
  "Take a sip if you have ever planned a costume around shoes you could actually enjoy wearing.",
  "Take a sip if you have ever posed in character for a costume photo.",
  "Take a sip if you have ever kept a costume because it had a great party story.",
  "Take a sip if you have ever taught a new party game to the whole room.",
  "Take a sip if you have ever misunderstood a game rule and still had fun.",
  "Take a sip if you have ever won a party game on your first attempt.",
  "Take a sip if you have ever formed an unexpectedly strong trivia team.",
  "Take a sip if you have ever celebrated a tiny victory like a championship.",
  "Take a sip if you have ever volunteered to keep score during a party game.",
  "Take a sip if you have ever acted out a clue that nobody could guess.",
  "Take a sip if you have ever guessed a charades clue from one gesture.",
  "Take a sip if you have ever made up a house rule everyone preferred.",
  "Take a sip if you have ever chosen a team name more carefully than a strategy.",
  "Take a sip if you have ever drawn something unrecognizable in a guessing game.",
  "Take a sip if you have ever laughed through an entire game explanation.",
  "Take a sip if you have ever joined a game after missing the first round.",
  "Take a sip if you have ever surprised the group with a niche trivia answer.",
  "Take a sip if you have ever been the tiebreaker in a party game.",
  "Take a sip if you have ever forgotten the score because the game was too entertaining.",
  "Take a sip if you have ever turned a simple game into a friendly tournament.",
  "Take a sip if you have ever helped adapt a game so everyone could join comfortably.",
  "Take a sip if you have ever applauded a creative answer that earned no points.",
  "Take a sip if you have ever suggested a game that became the evening's main event.",
  "Take a sip if you have ever retired undefeated from a party game.",
  "Take a sip if you have ever hosted a celebration in a space smaller than the guest list suggested.",
  "Take a sip if you have ever rearranged furniture to make room for a party.",
  "Take a sip if you have ever welcomed the first guest while still getting ready.",
  "Take a sip if you have ever made a party checklist and forgotten to read it.",
  "Take a sip if you have ever welcomed guests while one room was still unfinished.",
  "Take a sip if you have ever created a snack station that looked too good to touch.",
  "Take a sip if you have ever labeled something at a party to make choices clearer for guests.",
  "Take a sip if you have ever greeted people at the door while carrying party supplies.",
  "Take a sip if you have ever asked a friend to handle the music while you hosted.",
  "Take a sip if you have ever improvised a decoration after one fell down.",
  "Take a sip if you have ever offered guests more than one kind of festive drink.",
  "Take a sip if you have ever planned a quiet space away from the party noise.",
  "Take a sip if you have ever sent directions because the entrance was hard to find.",
  "Take a sip if you have ever timed the food and the guests arrived early.",
  "Take a sip if you have ever hosted an event with help from a reliable co-host.",
  "Take a sip if you have ever checked that everyone had a comfortable way home.",
  "Take a sip if you have ever made room for an additional dietary option at the last minute.",
  "Take a sip if you have ever put a welcome sign where nobody noticed it.",
  "Take a sip if you have ever spent longer cleaning before a party than after it.",
  "Take a sip if you have ever ended up enjoying your own party after the planning stress faded.",
  "Take a sip if you have ever received a thoughtful host gift.",
  "Take a sip if you have ever arrived exactly when a party was meant to start.",
  "Take a sip if you have ever circled the block while looking for the venue.",
  "Take a sip if you have ever brought a useful item the host had forgotten.",
  "Take a sip if you have ever waited outside while a friend finished getting ready.",
  "Take a sip if you have ever entered through the wrong door at an event.",
  "Take a sip if you have ever arrived early enough to help with final preparations.",
  "Take a sip if you have ever been welcomed by a pet before the host.",
  "Take a sip if you have ever carried a dish carefully across town for a gathering.",
  "Take a sip if you have ever coordinated your arrival with a group chat.",
  "Take a sip if you have ever shown up with an umbrella everyone later needed.",
  "Take a sip if you have ever paused at the entrance to remember someone's name.",
  "Take a sip if you have ever arrived in the middle of a group cheer.",
  "Take a sip if you have ever been the person everyone texted for directions.",
  "Take a sip if you have ever found a friend in the first minute of a crowded event.",
  "Take a sip if you have ever arrived carrying more bags than expected.",
  "Take a sip if you have ever checked the invitation twice on the way to the party.",
  "Take a sip if you have ever made an entrance that was louder than intended.",
  "Take a sip if you have ever arrived just as the food was being served.",
  "Take a sip if you have ever shared a ride to a celebration with friends.",
  "Take a sip if you have ever been relieved to see a familiar face upon arrival.",
  "Take a sip if you have ever left home and returned for the gift.",
  "Take a sip if you have ever introduced yourself to someone beside the snack table.",
  "Take a sip if you have ever made a new friend through a party game.",
  "Take a sip if you have ever discovered a surprising mutual friend at a celebration.",
  "Take a sip if you have ever joined a conversation because you recognized the topic.",
  "Take a sip if you have ever introduced two people who immediately got along.",
  "Take a sip if you have ever learned an interesting hobby from someone at a party.",
  "Take a sip if you have ever found the other person who also knew nobody there.",
  "Take a sip if you have ever complimented someone's party outfit and started a conversation.",
  "Take a sip if you have ever reconnected with someone after years apart at a celebration.",
  "Take a sip if you have ever joined a table where everyone made room for you.",
  "Take a sip if you have ever helped someone feel included in a group conversation.",
  "Take a sip if you have ever forgotten how you first met a longtime party friend.",
  "Take a sip if you have ever left a gathering with a new group chat.",
  "Take a sip if you have ever met someone whose laugh made the whole group laugh.",
  "Take a sip if you have ever found common ground with someone from a different friend group.",
  "Take a sip if you have ever helped clarify an inside joke for a newcomer.",
  "Take a sip if you have ever had a conversation that outlasted the event around it.",
  "Take a sip if you have ever invited someone standing alone to join your group.",
  "Take a sip if you have ever exchanged a recipe with someone you met at a party.",
  "Take a sip if you have ever discovered a shared hometown connection at an event.",
  "Take a sip if you have ever said goodbye to a new acquaintance more than once before leaving.",
  "Take a sip if you have ever volunteered to take a group photo.",
  "Take a sip if you have ever fit more people into a photo than seemed possible.",
  "Take a sip if you have ever blinked in the one group photo everyone loved.",
  "Take a sip if you have ever used a timer and sprinted into position.",
  "Take a sip if you have ever taken a candid photo that became a favorite.",
  "Take a sip if you have ever waited while everyone chose where to stand.",
  "Take a sip if you have ever held several phones to capture the same group picture.",
  "Take a sip if you have ever been partly hidden behind a taller person in a photo.",
  "Take a sip if you have ever matched poses with friends for a picture.",
  "Take a sip if you have ever taken a photo of the food before serving it.",
  "Take a sip if you have ever laughed during every attempt at a serious group portrait.",
  "Take a sip if you have ever found an unexpected reflection in a party photo.",
  "Take a sip if you have ever asked before sharing a group picture.",
  "Take a sip if you have ever taken a photo that perfectly captured the party mood.",
  "Take a sip if you have ever been trusted with the host's camera.",
  "Take a sip if you have ever recreated an old celebration photo years later.",
  "Take a sip if you have ever organized people by height for a picture.",
  "Take a sip if you have ever noticed a surprise guest in the background of a picture.",
  "Take a sip if you have ever preferred the silly photo to the polished one.",
  "Take a sip if you have ever used party decorations as a photo backdrop.",
  "Take a sip if you have ever volunteered to stay out of a photo and take it instead.",
  "Take a sip if you have ever planned your route through a party buffet.",
  "Take a sip if you have ever returned for a snack you almost overlooked.",
  "Take a sip if you have ever brought a dish that disappeared faster than expected.",
  "Take a sip if you have ever asked what was in a party dish before trying it.",
  "Take a sip if you have ever helped refill an empty snack bowl.",
  "Take a sip if you have ever balanced a plate while talking with your hands.",
  "Take a sip if you have ever chosen a dessert before choosing your main food.",
  "Take a sip if you have ever saved room for a celebration cake.",
  "Take a sip if you have ever cut a cake into more portions than planned.",
  "Take a sip if you have ever carried party food home in a carefully packed container.",
  "Take a sip if you have ever discovered that the simplest snack was the crowd favorite.",
  "Take a sip if you have ever made a festive non-alcoholic drink for a gathering.",
  "Take a sip if you have ever decorated a dessert to match an event theme.",
  "Take a sip if you have ever stood near the food because the conversation was good.",
  "Take a sip if you have ever brought extra napkins and felt unexpectedly prepared.",
  "Take a sip if you have ever guessed a cake flavor incorrectly.",
  "Take a sip if you have ever enjoyed a late addition to the party menu.",
  "Take a sip if you have ever arranged snacks by color for a themed event.",
  "Take a sip if you have ever caught a falling party plate before disaster.",
  "Take a sip if you have ever taken the last item only after checking with the group.",
  "Take a sip if you have ever found a new favorite dip at a celebration.",
  "Take a sip if you have ever helped package leftovers after a party.",
  "Take a sip if you have ever chosen a karaoke song for its unforgettable chorus.",
  "Take a sip if you have ever shared a karaoke duet with a friend.",
  "Take a sip if you have ever changed your karaoke choice at the last second.",
  "Take a sip if you have ever cheered for a first-time karaoke singer.",
  "Take a sip if you have ever added backup vocals from your seat.",
  "Take a sip if you have ever picked a karaoke song that was harder than expected.",
  "Take a sip if you have ever performed a dramatic karaoke ballad.",
  "Take a sip if you have ever turned a solo karaoke song into a group performance.",
  "Take a sip if you have ever chosen a short song because the queue was long.",
  "Take a sip if you have ever applauded a karaoke performance before the final note.",
  "Take a sip if you have ever used choreography to enhance a karaoke performance.",
  "Take a sip if you have ever discovered someone had an amazing singing voice.",
  "Take a sip if you have ever dedicated a karaoke song to the whole room.",
  "Take a sip if you have ever chosen a song everyone could sing together.",
  "Take a sip if you have ever missed your cue because you were laughing.",
  "Take a sip if you have ever treated a living room like a concert stage.",
  "Take a sip if you have ever changed your mind about singing after declining earlier.",
  "Take a sip if you have ever enjoyed karaoke more as an audience member.",
  "Take a sip if you have ever finished a karaoke number with a theatrical bow.",
  "Take a sip if you have ever sung a birthday person's favorite song for them.",
  "Take a sip if you have ever remembered a party mainly because of one karaoke performance.",
  "Take a sip if you have ever helped plan a surprise birthday celebration.",
  "Take a sip if you have ever kept a birthday surprise secret until the reveal.",
  "Take a sip if you have ever arrived before the guest of honor at a surprise party.",
  "Take a sip if you have ever joined a birthday countdown in a crowded room.",
  "Take a sip if you have ever signed a birthday card passed quietly around a party.",
  "Take a sip if you have ever helped light birthday candles in a breeze.",
  "Take a sip if you have ever sung a personalized version of the birthday song.",
  "Take a sip if you have ever wrapped a birthday gift moments before leaving home.",
  "Take a sip if you have ever attended a milestone birthday celebration.",
  "Take a sip if you have ever made a birthday toast that stayed pleasantly brief.",
  "Take a sip if you have ever worn a party hat longer than the birthday person.",
  "Take a sip if you have ever helped carry birthday decorations into a venue.",
  "Take a sip if you have ever organized a birthday message from a group.",
  "Take a sip if you have ever celebrated a birthday outdoors.",
  "Take a sip if you have ever chosen a birthday card for its joke.",
  "Take a sip if you have ever attended two birthday celebrations in one weekend.",
  "Take a sip if you have ever helped rescue a leaning birthday cake.",
  "Take a sip if you have ever planned a birthday activity around the guest of honor's favorite hobby.",
  "Take a sip if you have ever taken part in a birthday tradition unique to one family.",
  "Take a sip if you have ever celebrated a birthday later than the actual date.",
  "Take a sip if you have ever made a handmade birthday decoration.",
  "Take a sip if you have ever delivered a birthday surprise across town.",
  "Take a sip if you have ever stayed to help clean up after a birthday party.",
  "Take a sip if you have ever attended a wedding with an unforgettable dance floor.",
  "Take a sip if you have ever found your table at a wedding by a creative name.",
  "Take a sip if you have ever caught up with relatives at a wedding reception.",
  "Take a sip if you have ever teared up during a joyful wedding speech.",
  "Take a sip if you have ever signed a wedding guest book with a careful message.",
  "Take a sip if you have ever helped pin a boutonniere or adjust a corsage.",
  "Take a sip if you have ever traveled to another city for a wedding celebration.",
  "Take a sip if you have ever learned a cultural wedding tradition as a guest.",
  "Take a sip if you have ever clapped along during a wedding entrance.",
  "Take a sip if you have ever shared a table with people you met that day.",
  "Take a sip if you have ever saved a wedding favor as a keepsake.",
  "Take a sip if you have ever helped gather guests for a wedding photo.",
  "Take a sip if you have ever heard a wedding toast that was both funny and kind.",
  "Take a sip if you have ever watched the couple surprise everyone with a performance.",
  "Take a sip if you have ever used a wedding program as a fan.",
  "Take a sip if you have ever stayed until the final song at a wedding reception.",
  "Take a sip if you have ever helped someone find their seat at a formal celebration.",
  "Take a sip if you have ever joined a wedding tradition after someone explained it.",
  "Take a sip if you have ever brought comfortable shoes for the reception.",
  "Take a sip if you have ever shared cake with someone at a wedding table.",
  "Take a sip if you have ever waved farewell during a celebratory send-off.",
  "Take a sip if you have ever reunited with friends at an engagement celebration.",
  "Take a sip if you have ever attended a party with a decade theme.",
  "Take a sip if you have ever solved a clue at a mystery-themed party.",
  "Take a sip if you have ever decorated for a seasonal celebration.",
  "Take a sip if you have ever attended a party inspired by a favorite film.",
  "Take a sip if you have ever created a themed invitation.",
  "Take a sip if you have ever attended an all-white party and guarded your outfit from food.",
  "Take a sip if you have ever brought something sparkly to a glam-themed event.",
  "Take a sip if you have ever turned a backyard into a festival-style celebration.",
  "Take a sip if you have ever followed a theme more enthusiastically than the host expected.",
  "Take a sip if you have ever attended a celebration built around a favorite book.",
  "Take a sip if you have ever played detective during a party mystery.",
  "Take a sip if you have ever brought a picnic blanket to an outdoor celebration.",
  "Take a sip if you have ever attended a party where every room had different decorations.",
  "Take a sip if you have ever made a themed centerpiece by hand.",
  "Take a sip if you have ever attended a game-night celebration with a dress code.",
  "Take a sip if you have ever built a photo booth around an event theme.",
  "Take a sip if you have ever chosen a themed party favor people actually used.",
  "Take a sip if you have ever attended a celebration centered on a shared hobby.",
  "Take a sip if you have ever guessed a party theme from the invitation alone.",
  "Take a sip if you have ever combined two themes into one celebration.",
  "Take a sip if you have ever kept a decoration from a themed event.",
  "Take a sip if you have ever seen a theme carried all the way to the smallest detail.",
  "Take a sip if you have ever worn a name tag upside down for part of a party.",
  "Take a sip if you have ever opened a door expecting a closet and found another room.",
  "Take a sip if you have ever dropped a party napkin and chased it across the floor.",
  "Take a sip if you have ever waved at someone who was greeting the person behind you.",
  "Take a sip if you have ever forgotten where you left your coat at a gathering.",
  "Take a sip if you have ever applauded because everyone else started applauding.",
  "Take a sip if you have ever told a story and realized the group already knew it.",
  "Take a sip if you have ever stood in the wrong line at a party buffet.",
  "Take a sip if you have ever sat in a chair that made an unexpectedly loud noise.",
  "Take a sip if you have ever lost track of your conversation when a great song began.",
  "Take a sip if you have ever worn a sticker from an event longer than intended.",
  "Take a sip if you have ever started saying goodbye and stayed another half hour.",
  "Take a sip if you have ever laughed after realizing a joke several seconds late.",
  "Take a sip if you have ever joined the wrong group pose and been welcomed anyway.",
  "Take a sip if you have ever complimented a decoration that turned out to be permanent.",
  "Take a sip if you have ever searched for a quiet phone only to find it was yours.",
  "Take a sip if you have ever answered a question meant for someone beside you.",
  "Take a sip if you have ever tried to help with cleanup and put something in the wrong place.",
  "Take a sip if you have ever discovered confetti in your clothes the next day.",
  "Take a sip if you have ever left a party with a container that was not originally yours.",
  "Take a sip if you have ever practiced a farewell and then bumped into the host again outside.",
] as const satisfies readonly string[]
