export const TAKE_SIP_RELATIONSHIPS: readonly string[] = [
  "Take a sip if a crush has made an ordinary day feel unexpectedly exciting.",
  "Take a sip if you have rehearsed a hello before talking to someone you liked.",
  "Take a sip if one person's name appearing on your screen has made you grin.",
  "Take a sip if you once wondered whether a friendly message was actually flirting.",
  "Take a sip if you have developed a crush after getting to know someone's sense of humor.",
  "Take a sip if attraction has surprised you by arriving later than expected.",
  "Take a sip if you have tried to look calm while your crush was nearby.",
  "Take a sip if a small compliment from someone special stayed with you all day.",
  "Take a sip if you have asked a friend for perspective about a new romantic interest.",
  "Take a sip if shared enthusiasm for a hobby made someone more attractive to you.",
  "Take a sip if you have mistaken chemistry for simple friendliness.",
  "Take a sip if a crush inspired you to discover a new song, show, or place.",
  "Take a sip if you have felt butterflies before sending an honest invitation.",
  "Take a sip if someone's kindness mattered more to your attraction than their appearance.",
  "Take a sip if you have let a crush fade without turning it into a big story.",
  "Take a sip if a friendship gradually began to feel romantic to you.",
  "Take a sip if you have been pleasantly surprised that someone liked you back.",
  "Take a sip if your idea of an ideal partner has changed over time.",
  "Take a sip if you have noticed that confidence can be quietly attractive.",
  "Take a sip if an unexpected conversation sparked your interest in someone.",
  "Take a sip if you have chosen not to pursue a crush because the timing felt wrong.",
  "Take a sip if someone became more appealing after you saw how they treated others.",
  "Take a sip if you have enjoyed having a harmless crush with no plan to act on it.",
  "Take a sip if a person's laugh was the first thing that drew you toward them.",
  "Take a sip if you have realized that admiration and romantic interest are different feelings.",

  "Take a sip if you have sent the first message to someone you wanted to know better.",
  "Take a sip if a thoughtful voice note helped you feel closer to someone.",
  "Take a sip if you prefer direct questions to guessing what a partner means.",
  "Take a sip if you have asked for time to think before answering a relationship question.",
  "Take a sip if talking in person cleared up a misunderstanding created by text.",
  "Take a sip if you have learned to say what you need without expecting mind reading.",
  "Take a sip if a partner remembered a detail from a conversation you thought was minor.",
  "Take a sip if you have admitted that your tone came across differently than you intended.",
  "Take a sip if a check-in conversation made a relationship feel more secure.",
  "Take a sip if you have found it easier to write down a difficult thought before sharing it.",
  "Take a sip if someone asking follow-up questions made you feel genuinely heard.",
  "Take a sip if you have replaced a vague hint with a clear request.",
  "Take a sip if a conversation improved after both people put their phones aside.",
  "Take a sip if you have clarified whether someone wanted advice or simply wanted listening.",
  "Take a sip if hearing 'I understand' mattered more than hearing a solution.",
  "Take a sip if you have discussed how often you each like to communicate.",
  "Take a sip if a delayed reply once turned out to have an ordinary explanation.",
  "Take a sip if you have learned that honesty can be gentle as well as direct.",
  "Take a sip if you and a partner use different styles for showing enthusiasm.",
  "Take a sip if you have thanked someone for raising an uncomfortable topic respectfully.",
  "Take a sip if naming an assumption prevented it from becoming an argument.",
  "Take a sip if you have become better at expressing disappointment without assigning blame.",
  "Take a sip if a sincere question changed your understanding of a partner's perspective.",
  "Take a sip if you have asked someone how they prefer to receive difficult feedback.",
  "Take a sip if a relationship taught you that silence can mean many different things.",

  "Take a sip if a long hug from the right person has made a hard day softer.",
  "Take a sip if you show affection by remembering someone's favorite little things.",
  "Take a sip if receiving a handwritten note has made you feel cherished.",
  "Take a sip if you have cooked or brought food as a way of showing care.",
  "Take a sip if comfortable silence with someone feels like its own kind of closeness.",
  "Take a sip if you have made a playlist for a person you cared about.",
  "Take a sip if a partner's proud smile has meant more than a grand gesture.",
  "Take a sip if you enjoy affection most when it is offered with a check-in.",
  "Take a sip if you have saved a kind message because it brightened your day.",
  "Take a sip if a familiar greeting from someone you love feels grounding.",
  "Take a sip if you express care by making someone's everyday task easier.",
  "Take a sip if you have learned the difference between the affection you give and prefer to receive.",
  "Take a sip if someone cheering for your small win made it feel important.",
  "Take a sip if you have planned a low-key surprise tailored to someone's tastes.",
  "Take a sip if sharing an inside joke makes you feel connected to a partner.",
  "Take a sip if you value being asked before public displays of affection.",
  "Take a sip if a warm cup, snack, or blanket has served as a love note in disguise.",
  "Take a sip if you have felt cared for when someone gave you space without withdrawing support.",
  "Take a sip if a partner learning your routines made daily life feel sweeter.",
  "Take a sip if you enjoy celebrating relationship milestones in a private, simple way.",
  "Take a sip if you have discovered that reliability can feel deeply romantic.",
  "Take a sip if someone's encouragement helped you be kinder to yourself.",
  "Take a sip if you have a favorite ordinary memory with someone you dated.",
  "Take a sip if laughter is one of the main ways you connect romantically.",
  "Take a sip if you have adjusted an affectionate habit after learning what made someone comfortable.",

  "Take a sip if you have arrived for a date and immediately realized you were overdressed.",
  "Take a sip if a first date included an awkward pause that later became funny.",
  "Take a sip if you have forgotten a date's name for a terrifying few seconds.",
  "Take a sip if weather forced you to improvise a completely different date plan.",
  "Take a sip if you have spilled something while trying to make a good impression.",
  "Take a sip if a date venue was much louder than either person expected.",
  "Take a sip if you have told a joke on a date and had to explain it.",
  "Take a sip if you and a date waved at each other from opposite ends of the same room.",
  "Take a sip if an activity date revealed that neither person knew what they were doing.",
  "Take a sip if you have misread whether a meetup was friendly or romantic.",
  "Take a sip if a restaurant order became the most memorable part of a date.",
  "Take a sip if you have been nervous enough to talk unusually fast on a date.",
  "Take a sip if an accidental matching outfit made a date more amusing.",
  "Take a sip if you have taken a wrong turn while leading someone to a date spot.",
  "Take a sip if a date recovered gracefully after an early awkward moment.",
  "Take a sip if you have realized halfway through a story that it had no clear ending.",
  "Take a sip if a pet unexpectedly became the star of a video date.",
  "Take a sip if you have had a date where the planned activity was closed on arrival.",
  "Take a sip if saying goodbye after a date felt more complicated than the date itself.",
  "Take a sip if you have laughed with a date about both being nervous.",
  "Take a sip if a casual coffee date lasted far longer than either person planned.",
  "Take a sip if you have worn uncomfortable shoes to a date and regretted the choice.",
  "Take a sip if a date became better once the original plan was abandoned.",
  "Take a sip if you have accidentally repeated a story to someone you were dating.",
  "Take a sip if an awkward date still taught you something useful about yourself.",

  "Take a sip if you have said no to a date without inventing an excuse.",
  "Take a sip if someone respected your need for alone time without taking it personally.",
  "Take a sip if you have discussed which parts of a relationship may be shared online.",
  "Take a sip if asking before borrowing a personal item matters to you.",
  "Take a sip if you have changed your mind about a plan and communicated it clearly.",
  "Take a sip if a partner accepted your answer without asking you to justify it.",
  "Take a sip if you have protected time for friendships while dating someone.",
  "Take a sip if you prefer advance notice before someone visits your home.",
  "Take a sip if you have agreed on how to handle interruptions during work or study time.",
  "Take a sip if separate hobbies have helped a relationship stay balanced.",
  "Take a sip if you have asked permission before sharing a partner's personal news.",
  "Take a sip if someone checking your comfort level helped you relax.",
  "Take a sip if you have left an event early because your social energy was finished.",
  "Take a sip if you value being able to decline affection without causing an argument.",
  "Take a sip if a boundary conversation brought you closer instead of pushing you apart.",
  "Take a sip if you have learned not to promise availability you cannot sustain.",
  "Take a sip if you and a partner have different preferences about posting photos together.",
  "Take a sip if you have asked for privacy while processing a personal decision.",
  "Take a sip if someone responded well when you requested a different kind of support.",
  "Take a sip if you have recognized that a boundary can change as circumstances change.",
  "Take a sip if keeping some routines separate has made together-time more enjoyable.",
  "Take a sip if you have declined to discuss a relationship topic in a group setting.",
  "Take a sip if mutual agreement matters more to you than following a dating tradition.",
  "Take a sip if you have apologized after unintentionally crossing someone's stated limit.",
  "Take a sip if you feel safest with people who treat hesitation as a reason to pause.",

  "Take a sip if a partner has encouraged you before an important challenge.",
  "Take a sip if you have helped someone prepare for a stressful conversation.",
  "Take a sip if being believed in by a partner changed how you saw your own abilities.",
  "Take a sip if you have celebrated someone's achievement without making it about yourself.",
  "Take a sip if a loved one quietly handled a chore when your week was overwhelming.",
  "Take a sip if you have accompanied a partner to something that mattered more to them than to you.",
  "Take a sip if someone reminded you to rest when you were pushing too hard.",
  "Take a sip if you have asked what practical help would actually be useful.",
  "Take a sip if a partner respected your independence while still offering support.",
  "Take a sip if you have stayed present while someone worked through a difficult decision.",
  "Take a sip if receiving encouragement at the right moment changed your whole day.",
  "Take a sip if you have learned to support a partner without trying to manage their choices.",
  "Take a sip if someone made room for your feelings even when they saw the situation differently.",
  "Take a sip if you have shown up for an event because it was meaningful to your partner.",
  "Take a sip if a relationship helped you feel more confident pursuing a personal goal.",
  "Take a sip if you have offered company for a boring errand just to make it lighter.",
  "Take a sip if someone noticed you were stretched thin and asked how to help.",
  "Take a sip if you have encouraged a partner to maintain an important friendship.",
  "Take a sip if care has looked like giving honest feedback at a thoughtful time.",
  "Take a sip if you have respected a loved one's decision even when it was not what you would choose.",
  "Take a sip if a partner has made space for a tradition that matters to you.",
  "Take a sip if you have learned that support sometimes means witnessing rather than fixing.",
  "Take a sip if someone celebrated your progress before you reached the final goal.",
  "Take a sip if you have adjusted shared plans to help a partner recharge.",
  "Take a sip if mutual encouragement is one of your favorite parts of a relationship.",

  "Take a sip if shared values matter more to you now than having identical interests.",
  "Take a sip if you have dated someone whose social battery differed greatly from yours.",
  "Take a sip if a relationship worked better after you compared everyday routines.",
  "Take a sip if you have discovered that similar humor can bridge many differences.",
  "Take a sip if you and a partner prefer different ways of planning ahead.",
  "Take a sip if talking about money habits revealed an unexpected point of compatibility.",
  "Take a sip if you have learned that matching schedules can be harder than matching personalities.",
  "Take a sip if different tastes in entertainment have expanded your world.",
  "Take a sip if you value a partner who can enjoy time together without constant conversation.",
  "Take a sip if a difference in tidiness has required patient negotiation.",
  "Take a sip if you have found common ground with someone who communicates very differently.",
  "Take a sip if similar attitudes toward punctuality make dating easier for you.",
  "Take a sip if you and someone you dated had opposite ideas of an ideal weekend.",
  "Take a sip if curiosity about each other's backgrounds strengthened a connection.",
  "Take a sip if you have realized that chemistry and long-term compatibility are not the same.",
  "Take a sip if a shared approach to decision-making made partnership feel natural.",
  "Take a sip if you have enjoyed introducing a partner to a hobby they had never tried.",
  "Take a sip if differing food preferences became a fun part of choosing dates.",
  "Take a sip if you need both spontaneity and predictability in a relationship.",
  "Take a sip if you have talked about what commitment means instead of assuming agreement.",
  "Take a sip if compatible conflict styles now matter to you more than a perfect first impression.",
  "Take a sip if you and a partner have learned to alternate who chooses the plan.",
  "Take a sip if a cultural difference prompted a meaningful, respectful conversation.",
  "Take a sip if you have discovered that shared goals can coexist with separate ambitions.",
  "Take a sip if being able to change your mind together is part of compatibility for you.",

  "Take a sip if you have returned to a disagreement after everyone had time to cool down.",
  "Take a sip if an apology felt meaningful because it named the specific impact.",
  "Take a sip if you have corrected a misunderstanding without trying to win the conversation.",
  "Take a sip if a partner's repair attempt made you laugh during a tense moment.",
  "Take a sip if you have acknowledged your part in a conflict before explaining your intent.",
  "Take a sip if changing the setting helped you discuss a disagreement more calmly.",
  "Take a sip if you have agreed to pause an argument and named when you would resume it.",
  "Take a sip if feeling heard made compromise possible for you.",
  "Take a sip if you have apologized without adding a defense afterward.",
  "Take a sip if a conflict revealed a need neither person had expressed clearly.",
  "Take a sip if you have chosen a smaller, kinder sentence instead of a dramatic one.",
  "Take a sip if you and a partner solved a recurring issue by changing a routine.",
  "Take a sip if you have accepted an apology while still needing time to rebuild trust.",
  "Take a sip if a disagreement ended with a clearer plan for next time.",
  "Take a sip if you have caught yourself arguing about details instead of the real concern.",
  "Take a sip if someone taking responsibility helped you lower your guard.",
  "Take a sip if you have revisited an old conflict with more empathy than before.",
  "Take a sip if writing down shared decisions prevented the same confusion from returning.",
  "Take a sip if you have learned to distinguish a request from an ultimatum.",
  "Take a sip if repair required consistent action rather than one perfect conversation.",
  "Take a sip if you have thanked a partner for disagreeing respectfully.",
  "Take a sip if admitting you were wrong strengthened a relationship.",
  "Take a sip if you have found a compromise that neither person originally imagined.",
  "Take a sip if a conflict became manageable once you separated facts from assumptions.",
  "Take a sip if you now consider follow-through an essential part of an apology.",

  "Take a sip if you have ended a relationship because your futures pointed in different directions.",
  "Take a sip if a breakup taught you that caring about someone is not always enough for compatibility.",
  "Take a sip if you have returned belongings with kindness and minimal drama.",
  "Take a sip if you needed a new routine after a relationship ended.",
  "Take a sip if a friend helped you rediscover something you enjoyed before a breakup.",
  "Take a sip if you have felt both relief and sadness about the same relationship ending.",
  "Take a sip if you changed a familiar route or playlist while moving on.",
  "Take a sip if a breakup eventually clarified what you want from partnership.",
  "Take a sip if you have removed reminders from view without throwing everything away.",
  "Take a sip if healing surprised you by happening in small, ordinary moments.",
  "Take a sip if you have wished a former partner well from a respectful distance.",
  "Take a sip if the end of a short connection affected you more than expected.",
  "Take a sip if you learned not to measure recovery by someone else's timeline.",
  "Take a sip if a relationship ended mutually even though the conversation was difficult.",
  "Take a sip if you have made peace with never receiving a perfect explanation.",
  "Take a sip if a breakup led you to reconnect with a neglected interest.",
  "Take a sip if you have recognized that closure can be something you create for yourself.",
  "Take a sip if an ending became easier once shared logistics were settled clearly.",
  "Take a sip if you have outgrown a story you once told yourself about a breakup.",
  "Take a sip if time changed how you understood a past relationship.",
  "Take a sip if you have kept a good lesson while letting go of the connection.",
  "Take a sip if being respectful during a breakup mattered to you even when emotions were high.",
  "Take a sip if you discovered that missing someone does not require restarting the relationship.",
  "Take a sip if a former relationship helped you identify a boundary you now protect.",
  "Take a sip if moving forward meant accepting that two honest perspectives could differ.",

  "Take a sip if being single has given you more time for a favorite hobby.",
  "Take a sip if you have taken yourself somewhere you once saved for a date.",
  "Take a sip if your current relationship status feels peaceful rather than unfinished.",
  "Take a sip if you have enjoyed making weekend plans without coordinating with a partner.",
  "Take a sip if being on your own helped you learn what routines suit you best.",
  "Take a sip if you have stopped treating partnership as a deadline.",
  "Take a sip if a solo celebration felt just as meaningful as a shared one.",
  "Take a sip if you have built a full life that does not depend on dating.",
  "Take a sip if being single made your friendships feel especially important.",
  "Take a sip if you have paused dating because your attention belonged elsewhere.",
  "Take a sip if you enjoy having the whole bed arranged exactly how you like it.",
  "Take a sip if you have learned to recognize loneliness without rushing into a relationship.",
  "Take a sip if a period of being single strengthened your decision-making.",
  "Take a sip if you have attended an event solo and had a genuinely good time.",
  "Take a sip if not dating currently feels like an active choice rather than a waiting room.",
  "Take a sip if you have become more comfortable answering questions about your relationship status.",
  "Take a sip if single life has made spontaneous plans easier.",
  "Take a sip if you have created a home routine that feels entirely your own.",
  "Take a sip if you no longer compare your romantic timeline with anyone else's.",
  "Take a sip if being single helped you separate your preferences from a former partner's.",
  "Take a sip if you have skipped a dating app when it felt more tiring than fun.",
  "Take a sip if your support system includes many kinds of close relationships.",
  "Take a sip if you have found romance optional but connection essential.",
  "Take a sip if a solo trip or outing increased your confidence.",
  "Take a sip if you would rather wait for compatibility than date to avoid being alone.",

  "Take a sip if a relationship taught you to ask questions before making assumptions.",
  "Take a sip if you have learned that consistency can be more impressive than intensity.",
  "Take a sip if your past helped you become clearer about what respect looks like.",
  "Take a sip if you now notice how someone handles a small disappointment.",
  "Take a sip if dating taught you that potential is different from readiness.",
  "Take a sip if you have become more willing to discuss expectations early.",
  "Take a sip if experience changed your definition of a successful relationship.",
  "Take a sip if you learned to keep nurturing your own interests while partnered.",
  "Take a sip if a past mismatch helped you appreciate a later point of ease.",
  "Take a sip if you now pay attention to whether words and actions align.",
  "Take a sip if a relationship showed you the value of asking for clarification.",
  "Take a sip if you have learned not to confuse urgency with closeness.",
  "Take a sip if your communication improved after you stopped avoiding minor concerns.",
  "Take a sip if you now understand that affection cannot replace shared values.",
  "Take a sip if experience made you more patient with gradual trust.",
  "Take a sip if you have learned to appreciate calm connection without calling it boring.",
  "Take a sip if a past relationship helped you recognize your own conflict habits.",
  "Take a sip if you now ask whether a connection supports the life you want.",
  "Take a sip if you have learned that boundaries work best when stated before resentment builds.",
  "Take a sip if dating made you more honest about your available time and energy.",
  "Take a sip if you now value curiosity during disagreement more than quick agreement.",
  "Take a sip if you have learned that mutual effort may look different on different days.",
  "Take a sip if a relationship helped you distinguish privacy from secrecy.",
  "Take a sip if you now recognize that a kind ending can still be the right ending.",
  "Take a sip if lessons from love have made you more compassionate toward your earlier self.",

  "Take a sip if you have introduced someone you were dating to an important friend.",
  "Take a sip if meeting a partner's chosen family made the relationship feel more real.",
  "Take a sip if you and a partner created a holiday tradition of your own.",
  "Take a sip if a relationship has included more than one language or communication style.",
  "Take a sip if you have learned the pronunciation of a meaningful name or word for someone you cared about.",
  "Take a sip if sharing favorite childhood foods helped you know each other better.",
  "Take a sip if you and a partner have negotiated whose social event to attend.",
  "Take a sip if someone made an effort to understand a tradition important to you.",
  "Take a sip if you have enjoyed a double date that actually went smoothly.",
  "Take a sip if friends noticed your compatibility before you did.",
  "Take a sip if you have balanced couple time with time among a larger community.",
  "Take a sip if a partner remembered how you prefer to be introduced.",
  "Take a sip if you have welcomed someone into a friend group at their own pace.",
  "Take a sip if a relationship gave you a new appreciation for a different way of celebrating.",
  "Take a sip if you and a partner have hosted a gathering together.",
  "Take a sip if you have discussed how to divide time across important people in your lives.",
  "Take a sip if a friend offered relationship advice that became genuinely useful.",
  "Take a sip if you have supported a partner's need for community beyond the relationship.",
  "Take a sip if bringing someone to a familiar place made you see it differently.",
  "Take a sip if you and a partner have navigated different levels of comfort in groups.",
  "Take a sip if a loved one made sure you were included in a shared conversation.",
  "Take a sip if you have found a way to honor two traditions without treating either as secondary.",
  "Take a sip if your friends and your partner developed their own easy rapport.",
  "Take a sip if you have chosen a relationship label together instead of relying on assumptions.",
  "Take a sip if feeling accepted by someone's community deepened your connection.",

]
