export const TAKE_SIP_GREEN_FLAGS: readonly string[] = [
  "Take a sip if you let people finish their thoughts before responding.",
  "Take a sip if you ask follow-up questions because you genuinely want to understand.",
  "Take a sip if you can listen to someone vent without immediately offering solutions.",
  "Take a sip if you put distractions aside when someone shares something important.",
  "Take a sip if you check whether someone wants advice, comfort, or simply company.",
  "Take a sip if you remember small details people have trusted you with.",
  "Take a sip if you notice when a quieter person is trying to join the conversation.",
  "Take a sip if you can hear criticism without turning it into a counterattack.",
  "Take a sip if you reflect back what you heard when a conversation feels unclear.",
  "Take a sip if you make room for pauses instead of rushing someone to speak.",

  "Take a sip if you ask for clarification rather than assuming the worst.",
  "Take a sip if you listen with the same care even when you disagree.",
  "Take a sip if you can stay curious about an experience unlike your own.",
  "Take a sip if you notice the feelings underneath someone's words.",
  "Take a sip if you avoid turning every shared story into one about yourself.",
  "Take a sip if you give someone your full attention without demanding eye contact.",
  "Take a sip if you can summarize another person's view fairly before sharing yours.",
  "Take a sip if you invite people to correct you when you misunderstand them.",
  "Take a sip if you keep listening when the answer is more complicated than expected.",
  "Take a sip if you treat someone's change of mind as new information, not inconsistency.",

  "Take a sip if you accept a no without asking for a justification.",
  "Take a sip if you ask before giving someone a hug or other physical affection.",
  "Take a sip if you respect that people may need time alone without taking it personally.",
  "Take a sip if you can state your own limits clearly and kindly.",
  "Take a sip if you never use guilt to change someone's boundary.",
  "Take a sip if you ask before sharing another person's news.",
  "Take a sip if you knock or message before entering someone's private space.",
  "Take a sip if you respect privacy even when you are feeling insecure.",
  "Take a sip if you check before posting a photo that includes someone else.",
  "Take a sip if you understand that consent can be withdrawn at any time.",

  "Take a sip if you welcome an honest no as much as an enthusiastic yes.",
  "Take a sip if you avoid pressuring people to disclose personal information.",
  "Take a sip if you ask before borrowing something, even from someone close to you.",
  "Take a sip if you honor someone's need to leave an event early.",
  "Take a sip if you do not tease people about boundaries they have set.",
  "Take a sip if you check that a nickname is welcome before using it.",
  "Take a sip if you let friends have other close relationships without acting possessive.",
  "Take a sip if you discuss digital privacy expectations instead of guessing them.",
  "Take a sip if you can hear 'not now' without treating it as 'never'.",
  "Take a sip if you respect food, health, and sensory limits without commentary.",

  "Take a sip if you follow through on plans or give useful notice when you cannot.",
  "Take a sip if you arrive when you said you would whenever circumstances allow.",
  "Take a sip if you return borrowed items in good condition.",
  "Take a sip if you keep confidences unless someone is in immediate danger.",
  "Take a sip if people can rely on you for the unglamorous parts of helping.",
  "Take a sip if you own missed commitments without inventing excuses.",
  "Take a sip if you communicate early when a deadline or promise may slip.",
  "Take a sip if you remember to check in after saying you will.",
  "Take a sip if you keep showing up after the crisis has stopped being visible.",
  "Take a sip if you make realistic promises instead of impressive ones.",

  "Take a sip if you confirm important details so nobody is left guessing.",
  "Take a sip if you contribute your fair share without needing repeated reminders.",
  "Take a sip if you can be trusted with access to another person's home or belongings.",
  "Take a sip if you update people when travel delays change shared plans.",
  "Take a sip if your private behavior matches the values you express publicly.",
  "Take a sip if you repay money promptly or agree on a clear plan.",
  "Take a sip if you prepare before offering someone practical support.",
  "Take a sip if you remember responsibilities that matter to the group.",
  "Take a sip if you tell the truth even when a lie would be more convenient.",
  "Take a sip if you can be counted on without expecting praise each time.",

  "Take a sip if you apologize without adding a hidden excuse.",
  "Take a sip if you name the specific impact of your mistake.",
  "Take a sip if you change your behavior after someone tells you it caused harm.",
  "Take a sip if you can revisit a disagreement after everyone has cooled down.",
  "Take a sip if you focus on solving the issue instead of winning the argument.",
  "Take a sip if you admit when your memory of an event may be incomplete.",
  "Take a sip if you repair small misunderstandings before resentment grows.",
  "Take a sip if you can forgive without pretending trust returns instantly.",
  "Take a sip if you avoid bringing up unrelated past mistakes during conflict.",
  "Take a sip if you ask what repair would feel meaningful rather than deciding alone.",

  "Take a sip if you take responsibility for your tone as well as your intention.",
  "Take a sip if you can pause a heated conversation and agree when to resume it.",
  "Take a sip if you make amends without demanding immediate reassurance.",
  "Take a sip if you recognize when being technically right is not the main issue.",
  "Take a sip if you check whether an apology landed instead of assuming it did.",
  "Take a sip if you learn from recurring conflict patterns.",
  "Take a sip if you can say 'I was wrong' plainly.",
  "Take a sip if you approach tension as something to work through together.",
  "Take a sip if you do not punish someone for raising a concern.",
  "Take a sip if you allow people time to process after a difficult conversation.",

  "Take a sip if you celebrate a friend's success without making it a comparison.",
  "Take a sip if you offer practical help while respecting the answer you receive.",
  "Take a sip if you check on people during ordinary weeks, not only emergencies.",
  "Take a sip if you make newcomers feel welcome without putting them on display.",
  "Take a sip if you speak kindly about people who are not in the room.",
  "Take a sip if you notice when someone could use a seat, hand, or quiet moment.",
  "Take a sip if you give compliments that do not depend on appearance.",
  "Take a sip if you can be generous without keeping score.",
  "Take a sip if you thank people for everyday efforts that often go unnoticed.",
  "Take a sip if you offer care in ways the other person actually finds helpful.",

  "Take a sip if you bring someone into the conversation when they have been overlooked.",
  "Take a sip if you show patience when someone needs extra time or explanation.",
  "Take a sip if you return kindness without treating it as a debt.",
  "Take a sip if you support someone privately as warmly as you praise them publicly.",
  "Take a sip if you can sit with a grieving person without forcing optimism.",
  "Take a sip if you share credit with everyone who contributed.",
  "Take a sip if you offer hospitality without expecting guests to perform gratitude.",
  "Take a sip if you check whether a struggling friend has eaten or rested.",
  "Take a sip if you make thoughtful gestures based on what someone enjoys.",
  "Take a sip if you leave people feeling respected after receiving service from them.",

  "Take a sip if you say what you mean instead of expecting people to decode hints.",
  "Take a sip if you raise concerns directly with the person involved.",
  "Take a sip if you can express disappointment without insulting anyone.",
  "Take a sip if you share relevant information before it becomes a surprise.",
  "Take a sip if you ask how someone prefers to stay in touch.",
  "Take a sip if you make your requests clear enough for someone to answer honestly.",
  "Take a sip if you can discuss expectations before making a commitment.",
  "Take a sip if you tell people when you need reassurance instead of testing them.",
  "Take a sip if you distinguish between what you know and what you assume.",
  "Take a sip if you communicate changes in feelings with care and honesty.",

  "Take a sip if you can say you need time to think rather than disappearing.",
  "Take a sip if you use 'I' statements to describe your experience during conflict.",
  "Take a sip if you ask permission before starting a heavy conversation.",
  "Take a sip if you choose private settings for sensitive feedback.",
  "Take a sip if you can talk about money openly when it affects shared plans.",
  "Take a sip if you tell someone when their words helped you.",
  "Take a sip if you clarify jokes quickly when they cause genuine hurt.",
  "Take a sip if you can communicate affection in more than one way.",
  "Take a sip if you ask what an unfamiliar expression means instead of mocking it.",
  "Take a sip if you respond to vulnerability with care rather than avoidance.",

  "Take a sip if you use the name and pronouns someone asks you to use.",
  "Take a sip if you make plans that account for different access needs.",
  "Take a sip if you avoid assuming everyone celebrates the same holidays.",
  "Take a sip if you introduce people without reducing them to their job or relationship status.",
  "Take a sip if you make space for different family structures in conversation.",
  "Take a sip if you explain an inside joke so a newcomer can join the laughter.",
  "Take a sip if you offer more than one way to participate in group activities.",
  "Take a sip if you check dietary needs before choosing food for everyone.",
  "Take a sip if you avoid treating one person as spokesperson for an entire community.",
  "Take a sip if you pronounce someone's name carefully and welcome correction.",

  "Take a sip if you help make social plans affordable for different budgets.",
  "Take a sip if you include remote friends in moments that matter to the group.",
  "Take a sip if you notice when a venue may exclude someone and suggest an alternative.",
  "Take a sip if you respect cultural differences without turning them into entertainment.",
  "Take a sip if you leave room for people who do not drink alcohol to join fully.",
  "Take a sip if you ask rather than assume how two people know each other.",
  "Take a sip if you share group context with someone who missed an earlier conversation.",
  "Take a sip if you challenge exclusionary comments without making the targeted person lead.",
  "Take a sip if you invite input in formats that work for different communicators.",
  "Take a sip if you treat accessibility requests as normal planning information.",

  "Take a sip if you can identify your feelings without blaming someone else for them.",
  "Take a sip if you know when you are too overwhelmed for a useful conversation.",
  "Take a sip if you can soothe yourself without making another person responsible for everything.",
  "Take a sip if you allow mixed feelings without demanding a simple answer.",
  "Take a sip if you can feel jealous without becoming controlling.",
  "Take a sip if you notice defensiveness and choose to slow down.",
  "Take a sip if you accept that someone can be upset with you and still care about you.",
  "Take a sip if you can tolerate uncertainty without inventing a negative story.",
  "Take a sip if you recognize when stress is shaping your reaction.",
  "Take a sip if you ask for support before reaching a breaking point.",

  "Take a sip if you can receive reassurance without repeatedly moving the goalposts.",
  "Take a sip if you let yourself rest without treating it as a personal failure.",
  "Take a sip if you can celebrate progress that is not perfect.",
  "Take a sip if you notice your own patterns and work on them.",
  "Take a sip if you can sit with discomfort long enough to respond thoughtfully.",
  "Take a sip if you separate a difficult moment from someone's entire character.",
  "Take a sip if you know when professional support could help and seek it voluntarily.",
  "Take a sip if you can ask for reassurance without demanding proof of loyalty.",
  "Take a sip if you take a breath before sending an angry message.",
  "Take a sip if you let other people have emotions without rushing to fix them.",

  "Take a sip if you support a partner's friendships outside the relationship.",
  "Take a sip if you discuss exclusivity instead of relying on assumptions.",
  "Take a sip if you can enjoy separate hobbies without questioning the bond.",
  "Take a sip if you make decisions with a partner rather than for them.",
  "Take a sip if you show affection without using it to avoid a needed conversation.",
  "Take a sip if you respect a partner's ambitions even when their path differs from yours.",
  "Take a sip if you can discuss future hopes without turning them into pressure.",
  "Take a sip if you share relationship work instead of assigning one person the emotional load.",
  "Take a sip if you remain respectful when a romantic relationship ends.",
  "Take a sip if you protect your connection without isolating each other from community.",

  "Take a sip if you talk about intimacy with honesty, care, and mutual consent.",
  "Take a sip if you appreciate a partner's growth rather than fearing every change.",
  "Take a sip if you can ask for closeness without demanding constant availability.",
  "Take a sip if you keep private disagreements off public timelines.",
  "Take a sip if you make room for both partners' traditions in shared celebrations.",
  "Take a sip if you discuss household responsibilities before resentment builds.",
  "Take a sip if you treat dating preferences as compatibility questions, not personal verdicts.",
  "Take a sip if you encourage someone you love to pursue opportunities independently.",
  "Take a sip if you can talk about sexual health without shame or assumptions.",
  "Take a sip if you value steady care as much as grand romantic gestures.",

  "Take a sip if you can disagree with a friend without threatening the friendship.",
  "Take a sip if you support a friend's new chapter without making their change about you.",
  "Take a sip if you reach out even when you have nothing specific to report.",
  "Take a sip if you can reconnect after time apart without demanding an explanation.",
  "Take a sip if you tell friends you appreciate them while they can hear it.",
  "Take a sip if you respect when a friend has less social energy than usual.",
  "Take a sip if you make room for friendship traditions to evolve.",
  "Take a sip if you celebrate a friend's other friendships.",
  "Take a sip if you can name a friendship issue without recruiting sides.",
  "Take a sip if you help a friend move without disappearing when the boxes appear.",

  "Take a sip if you remember that friendship care can look different across seasons.",
  "Take a sip if you ask before bringing an extra guest to shared plans.",
  "Take a sip if you can enjoy a friend's company without needing constant entertainment.",
  "Take a sip if you do not measure closeness by response speed alone.",
  "Take a sip if you make time for friends who are going through major life changes.",
  "Take a sip if you can recommend a friend for an opportunity without feeling threatened.",
  "Take a sip if you respect the difference between friendly teasing and a sore subject.",
  "Take a sip if you are willing to be the first person to restart a neglected group chat.",
  "Take a sip if you can share a friend's joy even during a hard season of your own.",
  "Take a sip if you tell a friend privately when you think they deserve better treatment.",

  "Take a sip if you ask relatives about their preferences instead of relying on family roles.",
  "Take a sip if you can love family members without excusing harmful behavior.",
  "Take a sip if you respect an adult relative's choices even when you would choose differently.",
  "Take a sip if you avoid comparing siblings, cousins, or children.",
  "Take a sip if you make family gatherings safer for someone who feels outnumbered.",
  "Take a sip if you keep children out of adult disagreements.",
  "Take a sip if you can set a family tradition aside when it no longer serves everyone.",
  "Take a sip if you ask before giving parenting advice.",
  "Take a sip if you share caregiving tasks instead of leaving them to one relative.",
  "Take a sip if you apologize to younger family members when you get something wrong.",

  "Take a sip if you support chosen family with the same seriousness as biological family.",
  "Take a sip if you let relatives decline invitations without starting a guilt campaign.",
  "Take a sip if you can discuss inheritance or shared expenses before a crisis.",
  "Take a sip if you protect a relative's private news from family gossip.",
  "Take a sip if you learn what support a new parent actually wants.",
  "Take a sip if you respect household rules when visiting family.",
  "Take a sip if you make space for relatives whose beliefs have changed.",
  "Take a sip if you check on the family member who usually checks on everyone else.",
  "Take a sip if you can end a family call kindly when your energy is low.",
  "Take a sip if you value family connection without demanding unlimited access.",

  "Take a sip if you give colleagues credit in front of the people who make decisions.",
  "Take a sip if you respect focused work time and avoid unnecessary interruptions.",
  "Take a sip if you share useful context instead of hoarding information.",
  "Take a sip if you can receive workplace feedback without retaliating.",
  "Take a sip if you speak up when a colleague's idea is wrongly attributed.",
  "Take a sip if you keep social invitations from becoming career tests.",
  "Take a sip if you pair constructive feedback with concrete examples and room for response.",
  "Take a sip if you respect that colleagues may keep their personal lives private.",
  "Take a sip if you make meetings easier for people joining remotely.",
  "Take a sip if you acknowledge mistakes before they become someone else's problem.",

  "Take a sip if you avoid messaging coworkers outside agreed hours unless it is truly urgent.",
  "Take a sip if you explain unwritten processes to someone new.",
  "Take a sip if you advocate for fair opportunities rather than only your closest allies.",
  "Take a sip if you can disagree with an idea without belittling its author.",
  "Take a sip if you thank people whose behind-the-scenes work made success possible.",
  "Take a sip if you share the conversational floor during group decisions.",
  "Take a sip if you set clear expectations instead of relying on mind reading.",
  "Take a sip if you respect sick leave without asking for private medical details.",
  "Take a sip if you welcome corrections from someone with less seniority.",
  "Take a sip if you refuse to bond through cruelty about another coworker.",

  "Take a sip if you ask before adding someone to a group chat.",
  "Take a sip if you avoid sharing screenshots from private conversations.",
  "Take a sip if you correct false information you previously passed along.",
  "Take a sip if you wait for consent before tagging someone in a public post.",
  "Take a sip if you can leave a message unanswered until you have capacity.",
  "Take a sip if you use content warnings when a topic may be unexpectedly distressing.",
  "Take a sip if you avoid demanding instant replies to non-urgent messages.",
  "Take a sip if you ask before starting a video call.",
  "Take a sip if you protect another person's contact details from being shared casually.",
  "Take a sip if you can disagree online without sending a crowd after someone.",

  "Take a sip if you verify a story before reacting publicly to it.",
  "Take a sip if you respect a person's decision not to appear on social media.",
  "Take a sip if you move sensitive conversations away from public comment sections.",
  "Take a sip if you make your online tone clear when words could be misread.",
  "Take a sip if you delete private material when its owner asks you to.",
  "Take a sip if you avoid using read receipts as evidence of someone's priorities.",
  "Take a sip if you tell people before recording a shared call or gathering.",
  "Take a sip if you can mute a chat without announcing resentment.",
  "Take a sip if you credit the creator when sharing their work.",
  "Take a sip if your digital habits leave room for other people's autonomy.",

  "Take a sip if you ask what would help before stepping into someone's problem.",
  "Take a sip if you offer choices instead of taking over when someone is struggling.",
  "Take a sip if you know the difference between support and rescuing.",
  "Take a sip if you can help without making someone explain every painful detail.",
  "Take a sip if you respect when a person chooses a different solution than you suggested.",
  "Take a sip if you bring food in containers the recipient does not need to return quickly.",
  "Take a sip if you offer specific assistance rather than a vague promise to help sometime.",
  "Take a sip if you check whether accessibility or transport affects someone's options.",
  "Take a sip if you stay calm enough to follow another person's emergency plan.",
  "Take a sip if you encourage rest without treating someone as incapable.",

  "Take a sip if you accompany someone to a difficult appointment when invited.",
  "Take a sip if you remember that caregivers may need care too.",
  "Take a sip if you can accept gratitude without making support about yourself.",
  "Take a sip if you keep offering ordinary friendship after someone shares a diagnosis.",
  "Take a sip if you ask before discussing another person's health with anyone else.",
  "Take a sip if you notice when your help creates extra work and adjust it.",
  "Take a sip if you support someone's recovery without policing every choice.",
  "Take a sip if you can provide company without requiring conversation.",
  "Take a sip if you learn how to pronounce or understand something important to a loved one.",
  "Take a sip if you follow the lead of the person receiving support.",

  "Take a sip if you admit when you do not know something instead of bluffing.",
  "Take a sip if you can change your opinion after learning better information.",
  "Take a sip if you notice a double standard and correct your own behavior.",
  "Take a sip if you can name your needs before they turn into resentment.",
  "Take a sip if you recognize when an old hurt is shaping a new interaction.",
  "Take a sip if you can be proud of your growth without denying past mistakes.",
  "Take a sip if you ask trusted people how your behavior affects them.",
  "Take a sip if you can accept a consequence without calling it persecution.",
  "Take a sip if you question assumptions you inherited about relationships.",
  "Take a sip if you make space for feedback that was difficult to deliver.",

  "Take a sip if you can notice envy and turn it into information about your goals.",
  "Take a sip if you stop yourself before repeating gossip.",
  "Take a sip if you can recognize when humor is covering discomfort.",
  "Take a sip if you examine your role in patterns that keep repeating.",
  "Take a sip if you let your values guide you when nobody is watching.",
  "Take a sip if you can receive a compliment without arguing against it.",
  "Take a sip if you update your language when you learn it excludes someone.",
  "Take a sip if you notice when pride is keeping you from reconnecting.",
  "Take a sip if you can hold yourself accountable without collapsing into shame.",
  "Take a sip if you choose growth even when no one requires it from you.",
]
