export const TAKE_SIP_SCHOOL: readonly string[] = [
  "Take a sip if the first bell has ever caught you mid-conversation.",
  "Take a sip if you have ever checked a timetable more than once in the same morning.",
  "Take a sip if a classroom number has ever sent you to the wrong floor.",
  "Take a sip if you have ever recognized a room by its unusually squeaky door.",
  "Take a sip if your usual classroom seat has ever felt strangely important.",
  "Take a sip if you have ever chosen a desk because it had the best view of the board.",
  "Take a sip if you have ever arrived while the chairs were still being arranged.",
  "Take a sip if a timetable change has ever reshaped your whole day.",
  "Take a sip if you have ever carried a timetable screenshot for quick reference.",
  "Take a sip if a campus shortcut has ever saved you from arriving late.",
  "Take a sip if you have ever waited outside a locked classroom with everyone else.",
  "Take a sip if you have ever wondered whether you were early or in the wrong place.",
  "Take a sip if the walk between lessons has ever counted as your main exercise.",
  "Take a sip if you have ever learned which corridor gets crowded between classes.",
  "Take a sip if a familiar face in the hallway has ever improved your morning.",
  "Take a sip if you have ever found a quiet corner before a busy school day.",
  "Take a sip if you have ever heard an announcement that nobody around you understood.",
  "Take a sip if the end-of-class bell has ever interrupted an important explanation.",
  "Take a sip if you have ever packed up early and then realized the lesson was not over.",
  "Take a sip if leaving campus after a long day has ever felt like an achievement.",
  "Take a sip if you have ever opened a fresh notebook and wanted perfect handwriting.",
  "Take a sip if your handwriting has ever become less readable as a lesson continued.",
  "Take a sip if you have ever found one pen that somehow makes note-taking better.",
  "Take a sip if you have ever used the margin to capture a thought for later.",
  "Take a sip if a highlighter has ever run out halfway through an important sentence.",
  "Take a sip if you have ever turned a handout over looking for a missing second page.",
  "Take a sip if you have ever kept a worksheet because the explanation was genuinely useful.",
  "Take a sip if you have ever discovered that your notes made sense only to you.",
  "Take a sip if you have ever dated a page so your future self could find it.",
  "Take a sip if you have ever started a new topic on the wrong notebook page.",
  "Take a sip if sticky notes have ever taken over your study space.",
  "Take a sip if you have ever made a title look better than the notes beneath it.",
  "Take a sip if you have ever copied a diagram before understanding what it showed.",
  "Take a sip if you have ever found a loose page exactly when you needed it.",
  "Take a sip if you have ever used a ruler mainly to keep your place while reading.",
  "Take a sip if your backpack has ever contained supplies for a class that already ended.",
  "Take a sip if you have ever carried a charger because a full day depended on it.",
  "Take a sip if you have ever mistaken someone else's notebook for your own.",
  "Take a sip if a printed handout has ever felt refreshing after hours on a screen.",
  "Take a sip if you have ever found an unexpectedly useful item at the bottom of your bag.",
  "Take a sip if a lesson opening has ever made you immediately curious.",
  "Take a sip if you have ever understood a topic only after seeing a concrete example.",
  "Take a sip if one word on the board has ever unlocked an entire explanation.",
  "Take a sip if you have ever predicted where a lesson was going before it got there.",
  "Take a sip if a classroom discussion has ever changed the question you wanted to ask.",
  "Take a sip if you have ever noticed a connection between two completely different subjects.",
  "Take a sip if an optional reading has ever become your favorite part of a course.",
  "Take a sip if you have ever looked up a topic after class simply because it interested you.",
  "Take a sip if a difficult idea has ever clicked at an unexpected moment.",
  "Take a sip if you have ever enjoyed a lesson more than you expected from its title.",
  "Take a sip if you have ever spotted an error in an example and checked it politely.",
  "Take a sip if a class demonstration has ever worked differently than planned.",
  "Take a sip if you have ever contributed an example that moved the lesson forward.",
  "Take a sip if you have ever needed a moment to process before joining a discussion.",
  "Take a sip if you have ever preferred writing your response before saying it aloud.",
  "Take a sip if a peer's explanation has ever made a complicated topic feel simple.",
  "Take a sip if you have ever left class with a better question than the one you brought.",
  "Take a sip if a lesson has ever made an everyday object seem more interesting.",
  "Take a sip if you have ever reconsidered an opinion after examining new evidence.",
  "Take a sip if you have ever enjoyed the moment when the whole class finally understood.",
  "Take a sip if an instructor has ever begun class with a question instead of an answer.",
  "Take a sip if you have ever appreciated a teacher who learned everyone's preferred name.",
  "Take a sip if an instructor has ever made room for several ways to participate.",
  "Take a sip if you have ever received feedback that was both kind and specific.",
  "Take a sip if a teacher has ever recommended a resource perfectly suited to you.",
  "Take a sip if you have ever noticed an instructor become excited about their subject.",
  "Take a sip if a teacher's real-world example has ever stayed with you.",
  "Take a sip if you have ever appreciated an instructor admitting they needed to check something.",
  "Take a sip if a teacher has ever adjusted a lesson after noticing confusion.",
  "Take a sip if you have ever benefited from instructions provided in more than one format.",
  "Take a sip if an instructor has ever made a quiet student feel included without pressure.",
  "Take a sip if you have ever seen a teacher turn a mistake into a useful lesson.",
  "Take a sip if a teacher has ever pronounced a difficult term in a memorable way.",
  "Take a sip if you have ever appreciated a clear example of what good work looks like.",
  "Take a sip if an instructor has ever offered choices in how to complete a task.",
  "Take a sip if you have ever learned from a guest speaker with an unexpected career path.",
  "Take a sip if a librarian or learning adviser has ever solved a problem quickly.",
  "Take a sip if you have ever remembered a teacher's catchphrase outside class.",
  "Take a sip if an instructor has ever made revision feel manageable.",
  "Take a sip if you have ever felt seen when an educator noticed your improvement.",
  "Take a sip if you have ever read an assignment brief and still had three questions.",
  "Take a sip if the easiest-looking task has ever taken the longest.",
  "Take a sip if you have ever chosen a topic because you genuinely wanted to know more.",
  "Take a sip if you have ever changed an essay title after finishing the essay.",
  "Take a sip if an introduction has ever been harder to write than the rest of the work.",
  "Take a sip if you have ever cut a favorite paragraph because it did not fit the assignment.",
  "Take a sip if you have ever found the perfect source later than you wanted.",
  "Take a sip if a citation format has ever demanded more attention than expected.",
  "Take a sip if you have ever checked a word count before checking the argument.",
  "Take a sip if an assignment has ever taught you more during revision than drafting.",
  "Take a sip if you have ever renamed a final file more than once.",
  "Take a sip if you have ever kept an earlier draft in case you changed your mind.",
  "Take a sip if comments on a draft have ever clarified what the task was really asking.",
  "Take a sip if you have ever discovered a formatting issue during your final review.",
  "Take a sip if you have ever felt immediate relief after seeing a submission receipt.",
  "Take a sip if a deadline extension has ever arrived at exactly the right moment.",
  "Take a sip if you have ever submitted work early to protect your peace of mind.",
  "Take a sip if you have ever learned a useful shortcut while completing an assignment.",
  "Take a sip if an assignment has ever become more interesting once you found your angle.",
  "Take a sip if you have ever been proud of work that challenged you.",
  "Take a sip if your study plan has ever looked beautifully organized before changing completely.",
  "Take a sip if you have ever begun revising with the topic you liked most.",
  "Take a sip if you have ever discovered that a short walk helped solve a study problem.",
  "Take a sip if you have ever tested yourself without looking at your notes.",
  "Take a sip if you have ever summarized a whole topic on one page.",
  "Take a sip if you have ever used a question list to guide your revision.",
  "Take a sip if you have ever studied better after clearing one small space.",
  "Take a sip if you have ever returned to a difficult topic with a fresh perspective.",
  "Take a sip if you have ever discovered your best focus time by accident.",
  "Take a sip if you have ever used an example from your own life to remember a concept.",
  "Take a sip if you have ever practiced recalling information while doing another routine task.",
  "Take a sip if you have ever made a study guide that another learner found useful.",
  "Take a sip if you have ever realized you knew more than you thought during revision.",
  "Take a sip if you have ever closed extra browser tabs to help yourself concentrate.",
  "Take a sip if you have ever turned a complex chapter into a set of simple questions.",
  "Take a sip if you have ever scheduled rest as part of preparing for an assessment.",
  "Take a sip if you have ever reviewed feedback before studying for the next task.",
  "Take a sip if you have ever found that explaining why an answer works helped you remember it.",
  "Take a sip if you have ever stopped studying because sleep was the wiser choice.",
  "Take a sip if the quiet before an assessment has ever felt unusually loud.",
  "Take a sip if you have ever checked the front and back of an exam paper before starting.",
  "Take a sip if you have ever found a reassuring question early in an assessment.",
  "Take a sip if you have ever underlined the instruction word in a test question.",
  "Take a sip if you have ever planned an answer in the margin before writing it.",
  "Take a sip if you have ever caught a small mistake while reviewing an assessment.",
  "Take a sip if the final question has ever required more thought than all the others.",
  "Take a sip if you have ever used a permitted formula sheet during an assessment.",
  "Take a sip if you have ever completed an assessment in a format new to you.",
  "Take a sip if you have ever taken a practical assessment where preparation mattered most.",
  "Take a sip if you have ever waited for results longer than it took to complete the test.",
  "Take a sip if you have ever opened results with a friend nearby for moral support.",
  "Take a sip if feedback has ever mattered more to you than the grade.",
  "Take a sip if you have ever celebrated improvement even when the result was not perfect.",
  "Take a sip if an assessment has ever revealed a strength you had overlooked.",
  "Take a sip if you have ever learned from a question you answered incorrectly.",
  "Take a sip if you have ever requested an assessment adjustment that helped you show your knowledge.",
  "Take a sip if a practice assessment has ever been harder than the real one.",
  "Take a sip if you have ever finished an exam and resisted comparing answers immediately.",
  "Take a sip if the end of assessment season has ever made an ordinary day feel special.",
  "Take a sip if a project idea has ever appeared while you were doing something unrelated.",
  "Take a sip if you have ever started a project with a sketch no one else could interpret.",
  "Take a sip if research has ever changed the direction of your original project.",
  "Take a sip if you have ever built a prototype from whatever materials were available.",
  "Take a sip if a project test has ever produced a useful surprise.",
  "Take a sip if you have ever improved a project by removing something unnecessary.",
  "Take a sip if you have ever documented progress because the process mattered too.",
  "Take a sip if you have ever chosen a group role that matched your strengths.",
  "Take a sip if a teammate has ever noticed a problem everyone else missed.",
  "Take a sip if you have ever used a shared checklist to coordinate a project.",
  "Take a sip if your group has ever settled on an idea after a productive debate.",
  "Take a sip if you have ever made space for a teammate who needed more time to respond.",
  "Take a sip if a group project has ever introduced you to a new way of working.",
  "Take a sip if you have ever volunteered for the task nobody had claimed.",
  "Take a sip if your team has ever solved a problem during the final rehearsal.",
  "Take a sip if you have ever simplified a project so the main idea stood out.",
  "Take a sip if a peer review has ever improved something you were too close to see.",
  "Take a sip if you have ever kept a project artifact because it held good memories.",
  "Take a sip if you have ever seen separate project pieces finally come together.",
  "Take a sip if completing a project has ever felt like ending a small era.",
  "Take a sip if you have ever rehearsed a presentation in an almost empty room.",
  "Take a sip if you have ever adjusted your speaking pace after a practice run.",
  "Take a sip if a presentation opening has ever gone better than you feared.",
  "Take a sip if you have ever used one strong image instead of a crowded slide.",
  "Take a sip if you have ever paused during a presentation and found your place again.",
  "Take a sip if an audience reaction has ever helped you relax while presenting.",
  "Take a sip if you have ever explained a chart without reading every label aloud.",
  "Take a sip if you have ever adapted a presentation for a remote audience.",
  "Take a sip if captions have ever made a class presentation easier to follow.",
  "Take a sip if you have ever handed smoothly to the next speaker in a group presentation.",
  "Take a sip if a thoughtful audience question has ever improved your understanding.",
  "Take a sip if you have ever presented something you created from start to finish.",
  "Take a sip if you have ever used speaker notes mainly for reassurance.",
  "Take a sip if you have ever made a last-minute slide edit that genuinely helped.",
  "Take a sip if you have ever watched another presenter and borrowed a useful technique later.",
  "Take a sip if you have ever felt your confidence grow between the first and final sentence.",
  "Take a sip if you have ever shown an object on camera during an online presentation.",
  "Take a sip if you have ever answered a presentation question by saying you would find out.",
  "Take a sip if applause has ever made the preparation feel worthwhile.",
  "Take a sip if finishing a presentation has ever made the rest of your day feel lighter.",
  "Take a sip if you have ever become friends with someone through a shared class routine.",
  "Take a sip if you have ever learned a classmate's name from repeated group work.",
  "Take a sip if someone has ever made room for you at a study table.",
  "Take a sip if you have ever sent a classmate a reminder they were grateful to receive.",
  "Take a sip if a conversation before class has ever continued long after the course ended.",
  "Take a sip if you have ever celebrated a classmate's progress with them.",
  "Take a sip if you have ever checked in on a friend after a demanding school week.",
  "Take a sip if a class friend has ever introduced you to a favorite campus spot.",
  "Take a sip if you have ever shared an inside joke that only your classmates understood.",
  "Take a sip if you have ever found a study partner with the opposite learning style.",
  "Take a sip if you have ever asked before sharing someone else's notes or work.",
  "Take a sip if you have ever made sure a classmate was included in a group plan.",
  "Take a sip if you have ever resolved a small misunderstanding through a direct conversation.",
  "Take a sip if you have ever discovered a friend's talent during a school activity.",
  "Take a sip if you have ever supported someone attending their first club meeting.",
  "Take a sip if a school friendship has ever survived different schedules.",
  "Take a sip if you have ever reconnected with a classmate through a shared memory.",
  "Take a sip if you have ever formed a group chat that outlasted the assignment.",
  "Take a sip if you have ever thanked a peer for making a class more enjoyable.",
  "Take a sip if school has ever introduced you to someone you would not otherwise have met.",
  "Take a sip if you have ever joined a club because its meeting sounded welcoming.",
  "Take a sip if your first club meeting has ever been different from what you imagined.",
  "Take a sip if you have ever helped choose a theme for a student activity.",
  "Take a sip if you have ever brought a practical idea to a club planning session.",
  "Take a sip if a campus event has ever led you to discover a new interest.",
  "Take a sip if you have ever attended an event mainly to support someone you knew.",
  "Take a sip if you have ever helped set up chairs, signs, or supplies for an event.",
  "Take a sip if you have ever stayed afterward to help leave an event space tidy.",
  "Take a sip if you have ever contributed a small role to a successful school event.",
  "Take a sip if a student organization has ever helped you feel part of a community.",
  "Take a sip if you have ever learned a tradition from a campus group.",
  "Take a sip if you have ever visited a club table and left with more flyers than planned.",
  "Take a sip if you have ever attended a student performance that exceeded your expectations.",
  "Take a sip if you have ever cheered for a classmate at an exhibition or showcase.",
  "Take a sip if you have ever tried a creative activity at a school festival.",
  "Take a sip if a volunteering day has ever connected classroom learning to your community.",
  "Take a sip if you have ever helped make an event easier to access or understand.",
  "Take a sip if you have ever shared constructive feedback with a student organizer.",
  "Take a sip if you have ever discovered free food at an event you nearly skipped.",
  "Take a sip if you have ever left a club or activity knowing it was not the right fit.",
  "Take a sip if you have ever located a peaceful study spot away from the busiest areas.",
  "Take a sip if the library has ever felt completely different during assessment season.",
  "Take a sip if you have ever chosen a campus route based on shade or shelter.",
  "Take a sip if you have ever learned the best time to avoid a crowded café.",
  "Take a sip if a noticeboard has ever told you about something genuinely useful.",
  "Take a sip if you have ever visited an office whose purpose was unclear until you arrived.",
  "Take a sip if a campus help desk has ever pointed you in the right direction.",
  "Take a sip if you have ever found a comfortable place to recharge both yourself and a device.",
  "Take a sip if you have ever used a prayer, reflection, or wellness space on a learning campus.",
  "Take a sip if you have ever noticed a campus detail that most people walk past.",
  "Take a sip if you have ever watched a campus change across different seasons.",
  "Take a sip if you have ever navigated a building using accessibility signs or a digital map.",
  "Take a sip if you have ever attended class in a library, workshop, studio, or outdoor space.",
  "Take a sip if you have ever discovered that two buildings connect indoors.",
  "Take a sip if you have ever eaten a packed meal between learning sessions.",
  "Take a sip if you have ever found a campus printer that worked on the first attempt.",
  "Take a sip if you have ever carried something all day without needing it once.",
  "Take a sip if campus construction has ever changed your usual route.",
  "Take a sip if you have ever stopped to read a student art display.",
  "Take a sip if a familiar campus place has ever made a new term feel less daunting.",
  "Take a sip if you have ever joined an online class before anyone else appeared.",
  "Take a sip if you have ever checked your camera view before a virtual session began.",
  "Take a sip if a frozen screen has ever created an accidentally funny expression.",
  "Take a sip if you have ever typed an answer while someone else said the same thing aloud.",
  "Take a sip if you have ever used a reaction icon to encourage a classmate.",
  "Take a sip if a breakout room has ever started with a few seconds of polite silence.",
  "Take a sip if you have ever shared your screen and double-checked the correct window first.",
  "Take a sip if an online poll has ever revealed that most of the class agreed with you.",
  "Take a sip if you have ever learned from home, work, a library, or while traveling.",
  "Take a sip if you have ever replayed one part of a recorded lesson until it made sense.",
  "Take a sip if you have ever used a transcript to search for a key explanation.",
  "Take a sip if you have ever contributed to a class discussion at a time that suited you.",
  "Take a sip if you have ever collaborated with a learner you never met face to face.",
  "Take a sip if you have ever adjusted notifications to protect your study time.",
  "Take a sip if a digital whiteboard has ever become unexpectedly creative.",
  "Take a sip if you have ever completed a lesson using only a phone or borrowed device.",
  "Take a sip if you have ever downloaded materials before losing internet access.",
  "Take a sip if you have ever asked for an accessible version of a course resource.",
  "Take a sip if an online course has ever connected you with people in other places.",
  "Take a sip if flexible learning has ever helped education fit around the rest of your life.",
  "Take a sip if you have ever learned through an apprenticeship, workshop, or community course.",
  "Take a sip if you have ever practiced a skill until your hands remembered the steps.",
  "Take a sip if you have ever learned by watching an expert work slowly.",
  "Take a sip if a simulation has ever prepared you for a real task.",
  "Take a sip if you have ever made a safe mistake during practice and learned from it.",
  "Take a sip if you have ever used protective equipment that needed adjusting before the task.",
  "Take a sip if you have ever asked to see a demonstration one more time.",
  "Take a sip if you have ever discovered that the correct technique made a task easier.",
  "Take a sip if you have ever created something functional during a practical lesson.",
  "Take a sip if you have ever repaired a project instead of starting it again.",
  "Take a sip if you have ever learned why a procedure includes a step that seemed unnecessary.",
  "Take a sip if feedback from a supervisor has ever improved your technique immediately.",
  "Take a sip if you have ever kept a sample of your early work to track your progress.",
  "Take a sip if you have ever translated classroom theory into a hands-on task.",
  "Take a sip if you have ever learned a skill from someone with a different level of experience.",
  "Take a sip if you have ever balanced learning with employment, caregiving, or other commitments.",
  "Take a sip if you have ever returned to study after following a different path.",
  "Take a sip if an evening, weekend, or self-paced class has ever suited you best.",
  "Take a sip if you have ever brought knowledge from work or life into a learning discussion.",
  "Take a sip if education has ever opened a possibility you had not considered before.",
  "Take a sip if a classroom clock has ever seemed to pause during the last five minutes.",
  "Take a sip if you have ever tried to open a door that clearly said push or pull.",
  "Take a sip if a projector has ever chosen the worst possible moment to update.",
  "Take a sip if you have ever heard a chair squeak during complete silence.",
  "Take a sip if you have ever made eye contact with someone after a surprising announcement.",
  "Take a sip if a classroom temperature has ever become the unofficial discussion topic.",
  "Take a sip if you have ever watched an instructor search for the marker they were holding.",
  "Take a sip if you have ever answered a rhetorical question before realizing it was rhetorical.",
  "Take a sip if a page number announcement has ever caused a roomful of paper shuffling.",
  "Take a sip if you have ever tried to silence a noisy bag during a quiet lesson.",
  "Take a sip if you have ever waved back at someone who was greeting the person behind you.",
  "Take a sip if autocorrect has ever made a class message much funnier than intended.",
  "Take a sip if you have ever found yourself matching the walking pace of a stranger on campus.",
  "Take a sip if a snack wrapper has ever sounded impossibly loud in a study space.",
  "Take a sip if you have ever forgotten why you opened a new browser tab while researching.",
  "Take a sip if you have ever smiled when a lesson ended with the exact question you had.",
  "Take a sip if everyone has ever looked at the same person when a topic came up.",
  "Take a sip if you have ever noticed the room relax when a deadline was clarified.",
  "Take a sip if you have ever packed away one item and immediately needed it again.",
  "Take a sip if an ordinary classroom moment has ever become a favorite school memory.",
  "Take a sip if a course syllabus has ever answered a question before you needed to ask it.",
];
